### ISSUE TITLE
"captian's ID card" icon is broken following recent ID icon change

### ISSUE THREAD

**Issue by dwinters99** [VOREStation/VOREStation#10005]
#### Brief description of the bug
Title.

#### What you expected to happen
The opposite of the title.

#### What actually happened
The title.

#### Steps to reproduce
Look at the "captian's ID"
It's broken!

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/65516417/112261304-fd938b00-8c41-11eb-9778-cad83c3745ed.png)

**Comment by Heroman3003** [comment]
This has already been fixed in a followup PR.

**Comment by dwinters99** [comment]
Oh, cheers.
