### ISSUE TITLE
Items in hand of character setup 'doll' are never removed

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#10003]
#### Brief description of the bug
If an object is placed in the hand of the 'doll' seen in the character setup menu, the item is never removed until the server reboots.

This includes when loading different character slots, reloading the slot, hiding job gear, or doing anything that would affect a character's outfit.
Examples of items this can happen with are the crime scene kit and the advanced first aid kit.

#### What you expected to happen
For items to disappear when they shouldn't be around anymore because the character is no longer wearing the corresponding job's outfit.

#### What actually happened
Objects in hand remained on the 'doll' even when switching to a character or outfit that shouldn't include them

#### Steps to reproduce
- Load a CMO or Detective character (with job gear shown) or otherwise make the char setup doll equip the outfit of a job that holds something in its hand
- Switch to a different character that doesn't have such a job set to High, or hide job gear
- Observe how the item remains
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/4680835/112220020-285af080-8bfc-11eb-8451-7d070d9c5f48.png)

**Comment by Verkister** [comment]
Huh weird. Seems like my upstream fix for this never got mirrored here for some reason.
