### ISSUE TITLE
Custom item bag system fluff bug

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#1001]
#### Brief description of the issue

Loadout items are not loading inside the whitelist apped bag/satchel. Only works if you have a selected bag type, and only spawn in when redied up at the roundstart. Does not work with later spawned characters.

#### What you expected to happen

To have my loudout inventory and a standart box inside my special bag.

#### What actually happened

Spawned in with my special bag and it was empty. I was hoping it would act like the standart bag where the loadout items would spawn. But it only works, if I have readied up before hand and spawned in the game.

#### Steps to reproduce
- (Step 1) have a snowflake item bag, and deselect the standart type bag. 
- (Step 2) Spawn in during the round. Readying up on start
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by JoanRisu** [comment]
Loadouts look for the default bag you set when you're creating your character, not a custom bag. If you want some stuff to start in your bag, you're gonna have to make a list for someone to code into the bag.

**Comment by Arokha** [comment]
This was fixed by changes to the order that things happen. The items were spawning. In deep space.

Fixed by the upstream version of #1054
