### ISSUE TITLE
Custom gun back icons are broken.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1002]
#### Brief description of the issue
custom guns with item_icons = null and an item_override pull the base inventory sprite as worn item.

#### What you expected to happen
A generic back icon or something

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/14942479/23203267/b1f778d2-f8d9-11e6-9b6b-0531cb8db864.png)

#### Steps to reproduce
- spawn a battlerifle or somesuch from custom_guns_vr.dm
- put it on your back.

#### Code Revision
- Server revision: master - 2017-02-21
d08071ab7e15960cd76cff698ec6e6a93f6c0297

**Comment by SpadesNeil** [comment]
I swear this is reported already.

**Comment by Screemonster** [comment]
Thankfully all the screwing around with the particle guns to get _them_ to work has taught me what I need to do to get all of _these_ to work. Turns out the guide was wrong - setting the item_state to the same name as the icon_state means it fetches the inventory icon for the worn itemstates.

Too late in the day for me to fix it now, but I'll take a crack at it when I get up.
