### ISSUE TITLE
Show/Hide wings verb does nothing

### ISSUE THREAD

**Issue by Razgriz1032** [VOREStation/VOREStation#10060]
#### Brief description of the bug
Show/Hide wings verb does nothing.
This PR probably broke it: Kaleidoscope 2: The Retabbening - https://github.com/VOREStation/VOREStation/pull/9327

#### What you expected to happen
Wings to disappear

#### What actually happened
Wings did not disappear

#### Steps to reproduce
- Go to IC tab
- Click "Show/Hide wings"

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/pull/9327/files#diff-2fb4f4256aade3890b23da6ecc8e12232aa837c186ef9d5d27debe8c76cc2e1eL90-L113

was removed, and moved to

https://github.com/VOREStation/VOREStation/pull/9327/files#diff-88c50a053fb66bf3d7e6bc4fb8d91156017d286ba2a66f9f4e1872a7cbc0ef24R1137-R1158

Should be easily fixable. Should it be done here, or upstream?
