### ISSUE TITLE
Small say tweak

### ISSUE THREAD

**Issue by iWuna** [VOREStation/VOREStation#10066]
Fix cyrillic language.

**Comment by TheFurryFeline** [comment]
.... https://github.com/VOREStation/VOREStation/commit/e7127b834396291a3b97bff398443ed8a6c7091a This is hella old... Unless I'm misunderstanding what language you're speaking of.

**Comment by iWuna** [comment]
> .... [e7127b8](https://github.com/VOREStation/VOREStation/commit/e7127b834396291a3b97bff398443ed8a6c7091a) This is hella old... Unless I'm misunderstanding what language you're speaking of.
> 
> This is the only commit I can find with that language name you posted. Not even in code by that name.

i mean in chat, it's kinda broken  when you saying russian words in chat.

**Comment by TheFurryFeline** [comment]
Ah, fair. I dunno 'bout that stuff. Don't have a Russian keyboard.

**Comment by iWuna** [comment]
> Ah, fair. I dunno 'bout that stuff. Don't have a Russian keyboard.

just look how weird it look in game chat, just post this word "привет", it happens only with first letter.

**Comment by iWuna** [comment]
i actually can do this by myself if i figure out how to fix that w/o shitcode

**Comment by iWuna** [comment]
okay, 
`/proc/capitalize(var/t as text)
	return uppertext(copytext_char(t, 1, 2)) + copytext_char(t, 2)`
That's all.
