### ISSUE TITLE
bluespage badge twice the load out cost of webbing vest and drop pouches

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#10155]
#### Brief description of the bug
bluespace bage is a reflavour of full webbing and drop pouches but costs double the loadout points, it's even the same size.

#### What you expected to happen
reflavours to cost the same points

#### What actually happened
double points cost

#### Steps to reproduce
- (Step 1) open load out

#### Code Revision 4565b14b64dcd84d6b541ad27c05e4dae994639d 
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add: 
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by lm40** [comment]
i thought this was intentional 'cause like, yea mechanically it is (mostly) a reflavor but ICly and also just cuz the sprite is less obtrusive its basically an upgrade

**Comment by TheDavestDave** [comment]
so are drop pouches, they are barely noticeable on a  person, much like the badge.

**Comment by Very-Soft** [comment]
Yeah pretty sure this is intended. It's a slightly special thing so it costs a little more.
