### ISSUE TITLE
EAL implant still dos not work

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#1017]
#### Brief description of the issue
EAL implants when spawning give you no ability to activate them.

#### What you expected to happen
Spawn and get a message saying use this emote to activate.

#### What actually happened
Spawn and get no message or have access to the encoded audio language

#### Steps to reproduce
- Select the EAL implant from Character Setup
- Spawn in
- Look for the message on how to activate... see nothing
- Check known languages just to be sure and still nothing

#### Code Revision
Server revision: release - 2017-02-23
a1c8475c8b486a27a1da32f6562c6235235ea16e 
 
#### Anything else you may wish to add:
The regular Language Implants might also still be broken as well.

**Comment by Arokha** [comment]
The EAL implant does not teach you EAL, it makes you physically capable of speaking EAL, but it does not teach you the language. The description implies this. You have to also take the EAL language choice (which may or may not be whitelisted, I forget).

**Comment by Techtypes** [comment]
Too my knowledge it was unwhitelisted but only accessible for synthetic, also did check on a offline server using the current code and even with both the EAL implant and EAL language choice you still get no prompt or access to physically speak the language in any form or manner.

**Comment by Arokha** [comment]
EAL as a language is whitelisted on Vorestation (not Polaris). I can't tell why from the code. I want to say Ace requested it be so.

**Comment by Techtypes** [comment]
Likely from when everyone could speak before the implant, though still as previously mentioned tested offline using the current code with de-admin my self to make sure, and got the same result, nothing. Maybe I am wrong and messed something up but from what i am seeing so far it is not working.

**Comment by Techtypes** [comment]
Realized that the white list was likely also coped and so removed that on my test, it is just the white list blocking it off, sorry to take up your time with this and my misunderstanding of things.
