### ISSUE TITLE
Lasshseeki Korss' encoded audio

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#1018]
#### Brief description of the issue
Demicus Maximus approved Lasshseeki Korss' ability to speak encoded audio

#### Code Revision
Server revision: release - 2017-02-23
a1c8475c8b486a27a1da32f6562c6235235ea16e 
 
#### Anything else you may wish to add:
http://forum.vore-station.net/viewtopic.php?f=45&t=783

**Comment by Arokha** [comment]
Ain't no EAL whitelist now
