### ISSUE TITLE
Prometheans can't learn any Languages

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1021]
#### Brief description of the issue
Prometheans are unable to learn any languages beside galactic common, whatsoever.

#### What you expected to happen
Being able to learn other languages.

#### What actually happened
Not that.

#### Steps to reproduce
- Have a 'nanite' promethean
- Want to learn EAL
- Get approved for the whitelist
- Too bad, can't learn Sol Common, let alone EAL

#### Code Revision
- a1c8475c8b486a27a1da32f6562c6235235ea16e 
 
#### Anything else you may wish to add:
- http://forum.vore-station.net/viewtopic.php?f=45&t=828&p=5661
- https://github.com/VOREStation/VOREStation/issues/1022

**Comment by Arokha** [comment]
I should point out that even if you do know EAL as a Prommy, you still need the EAL implant to speak it, and it will be impossible to use the *ping emotes etc because those only work for synthetics.

**Comment by Vorrarkul** [comment]
The implant is in the loadout section. I have not been able to test if it works (I have heard rumors that it doesn't) due to https://github.com/VOREStation/VOREStation/issues/1022
