### ISSUE TITLE
Vorrarkul not on EAL Whitelist

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1022]
#### Brief description of the issue
I am not on the EAL whitelist.

#### What you expected to happen
Being on the EAL whitelist, as per http://forum.vore-station.net/viewtopic.php?f=45&t=828&p=5661

#### What actually happened
Not that.

#### Steps to reproduce
- Have a 'nanite' promethean
- Want to learn EAL
- Get approved for the whitelist
- Wait a long time until you remember you made an EAL app in the first place

#### Code Revision
- a1c8475c8b486a27a1da32f6562c6235235ea16e 
 
#### Anything else you may wish to add:
- http://forum.vore-station.net/viewtopic.php?f=45&t=828&p=5661
- https://github.com/VOREStation/VOREStation/issues/1021

**Comment by Arokha** [comment]
I'm currently pushing for EAL to be not whitelisted, so this may be a nonissue.

**Comment by Vorrarkul** [comment]
Well, either way, this will stand as a reminder about the EAL issues.

**Comment by Arokha** [comment]
What EAL whitelist ;o
