### ISSUE TITLE
Grey jean short shorts have no icon

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#10232]
#### Brief description of the bug
Grey jean short shorts (and perhaps similar items (I'm too tired and lazy to start up a local server and check)) have no icon. They appear on the mob sprite but are invisible in the inventory

#### What you expected to happen
Not that.

#### What actually happened
That.

#### Steps to reproduce
- Spawn grey jeans short shorts
- Observe lack of icon
- Submit github issue while tired from a covid shot (the coffee has done nothing) and tired of how overkill this issue template is for issues as simple as this

#### Code Revision
- 624e5fc7c1e0b2ed21d281b673d28fd33a6d4f2b

**Comment by TheFurryFeline** [comment]
It's naked man time, boys

**Comment by dwinters99** [comment]
Were you using the female version?  Grey shorts don't have a [icon]_f despite jeans/grey/female calling for it.

**Comment by Little-119** [comment]
@dwinters99 I don't believe so? I just got them from the shorts selection in the loadout, with the type set to grey jeans short shorts
