### ISSUE TITLE
Character creation is borked for tails/ears/wings

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#10237]
#### Brief description of the bug
The character setup panel's tails, ears, and wings are no longer able to be changed at all since the recent update #10223 

#### What you expected to happen
To be able to change a character's tail and or keep a pre-existing character's tail.

#### What actually happened
I've now got a tail-less, earless red panda.

#### Steps to reproduce
- (Step 1)
- Load up character setup and attempt to adjust the ears style for something more cute.
- (Step 2)
- Suffer as it fails to load anything on all fronts due to defaulting to "normal".

**Comment by Zeldazackman** [comment]
Small update that might help, but it also seems to spur on **massive** amounts of lag whenever someone connects and it attempts to load their character already in round.  

![Pbt9H8U](https://user-images.githubusercontent.com/17093432/116694196-f96b3380-a98c-11eb-9e5c-8eb0e8be2cfc.png)

**Comment by Novacat** [comment]
There is a fix for this upstream, going to wait until that gets merged.
