### ISSUE TITLE
Character creation for tails, wings, and ears is still borked

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#10253]
#### Brief description of the bug
Shockingly, character creation is still screwed up but this time with permissions wherein only staff/those with elevated server privileges can actually select anything, this is on update #10247

#### What you expected to happen
For normal players to be able to select anything other than "normal" for their character creations like previously before 

#### What actually happened
Unless you're staff or given an event pass for a server? you can't actually customize anything for your character and are met with the same issue of being forced to have "normal" as your one and only selection.
 
#### Steps to reproduce
- (Step 1)
- Load up character setup and attempt to adjust the ears style once more since the patch was applied
- (Step 2)
- Suffer once more as you cannot load in anything without it defaulting to "normal" unless given staff powers.

#### Anything else you may wish to add:
Forcing un-necessary sanitization preferences like this is akin to wrapping a chain and a bikelock around an already locked safe.

**Comment by Novacat** [comment]
Thanks for this, sent this report upstream and it should be fixed shortly!

**Comment by Novacat** [comment]
I have attempted to reproduce this on the Virgo master branch and have been unable to. I removed my Admin perms entirely (by removing the admins.txt file) and I was able to spawn in with wolf, wise ears, smooth lizard tail (colorable), and cyber dragon wing (colorable)

**Comment by Zeldazackman** [comment]
Strange, I've tried it out with a fresh copy with both a pre-existing save for characters and starting a brand new one after deleting the save and it's the copy of the pre-existing characters that gives off the error unless given elevated privileges.

**Comment by Very-Soft** [comment]
popped on a different account with no perms on a different computer

![image](https://user-images.githubusercontent.com/24854483/117423982-4b610b80-aeef-11eb-9dfc-2a8ee4d84ca5.png)

works fine on my machine. Did you try clearing your byond cache?

**Comment by Zeldazackman** [comment]
I swear it's always the simplest things, it turns out that clearing the cache worked as a solution as for whatever reason I'm guessing some files left over were blocking the ability to change the parts out. 

Once it was cleared everything worked as it normally did, my bad for causing another panic on this.

(It feels like I had gone slightly mad in trying out nearly everything else to diagnose the issue down to using DDU to clean install videocard drivers twice but had forgotten about the simplest solution of clearing byond's cache heh)

**Comment by Zeldazackman** [comment]
> Actually repo'd this and fixed it.

Well that works, winded up thinking that the bug was me being more than the usual smoothbrained self or something as I couldn't get it to hit again
