### ISSUE TITLE
Changing character slots as a ghost can cause massive lag spikes

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#10254]
#### Brief description of the bug
If you're ghosting and change a loaded character slot, you can effectively cause a runtime error that can lag out a server randomly for a couple of seconds, it doesn't always happen every time as it can just throw up the error and move on however.

#### What you expected to happen
To be able to change loaded character slots after cryo'ing out.

#### What actually happened
Ungodly amounts of hangtime randomly, as stated before it doesn't always happen but it's frequent enough to be noticeable.

#### Steps to reproduce
- (Step 1)
- Get bored of playing character A, cryo out with the intention of playing character B.
- (Step 2)
- Go to the preferences tab and then character setup after ghosting creating massive amounts of lag by accident
- (Step 3)
- Suffer

#### Anything else you may wish to add:
Some of the runtime snippits that might help to diagnose this issue

![tZugFDq](https://user-images.githubusercontent.com/17093432/117027925-2db35c80-accb-11eb-8bf0-31d9b3a9e05c.png)

**Comment by Novacat** [comment]
Thank you, forwarded this to Polaris!

**Comment by MistakeNot4892** [comment]
This runtime really shouldn't be capable of lagging the server itself, the language list is pretty short - was there any other associated runtime?

**Comment by Zeldazackman** [comment]
None that I can see, which is why I'm confused on why it's even as hit or miss on it lagging everything out to the level that it is.

**Comment by MistakeNot4892** [comment]
I don't think this is fully fixed - the runtime has been resolved but I doubt it fixed the lag from switching character slots. Apologies, should have been clearer in my PR text.
