### ISSUE TITLE
Emote Cooldown was removed by the refactor

### ISSUE THREAD

**Issue by Razgriz1032** [VOREStation/VOREStation#10275]
The cooldown for emotes from: 
https://github.com/VOREStation/VOREStation/pull/6185

was removed by: 
https://github.com/VOREStation/VOREStation/pull/10050

Now users may spam emotes as fast as they can macro.

**Comment by Little-119** [comment]
*beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep *beep

**Comment by Wickedtemp** [comment]
I like it more this way anyway. I understand a cooldown, but I wish it'd only trigger after 3 emotes. I can't do rapid dual-fingergun-snaps anymore.

**Comment by Razgriz1032** [comment]
Fixed by #1959
