### ISSUE TITLE
Surface medical syringe gun missing

### ISSUE THREAD

**Issue by FoxDoodKMG** [VOREStation/VOREStation#10274]
**Brief description of the bug**

No syringe gun in surface medical

**What actually happened**

No syringe gun placed in medical

**Steps to reproduce**

Just go look in medical, no syringe gun.

**Comment by TheFurryFeline** [comment]
To note, it's been reported that the other stuff needed for it is there but not the gun itself whereas there's still one up at asteroid medical

**Comment by FoxDoodKMG** [comment]
Update, there is one in surface medical.
However it was placed in the grenade crate for some unknown reason?

**Comment by TheFurryFeline** [comment]
That is rather weird and unintuituve.... Remind me to fix this when I get
home after class today, just a simple fix of moving that thing over with
the other equipment.
