### ISSUE TITLE
*yes and *no emotes on Cyborgs nonfucntional

### ISSUE THREAD

**Issue by VictorZisthus** [VOREStation/VOREStation#10285]
#### Brief description of the bug
*yes and *no emotes on Cyborgs nonfucntional.

#### What you expected to happen
Beepy yes and no's.

#### What actually happened
A disturbing lack of beep.

#### Steps to reproduce
- Be Cyborg
- Try to *yes or *no
- Lie down
- Try not to cry
- Cry a lot

**Comment by lm40** [comment]
i believe it's *confirm and like, *deny or something like that now, although I don't play enough synth/borg to be 100% sure that this is how the old sounds were
