### ISSUE TITLE
Post-port Map Tweaks (Clown Temple)

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#103]
Someone should go over the away mission dmms and look for any problems with the maps they made! The paths have all been updated and they load in DM now. And by someone I mean @SpadesNeil. I'm not sure what they were supposed to look like in a lot of cases.

Whenever you have time, anyway.

ToDo:
- [x] Make working airlocks for carpfarm.dmm so we can use simulated terrain.
- [x] Make new loot spawners for all levels.
- [ ] Clown Temple map needs corrected icons.

**Comment by SpadesNeil** [comment]
I can do this.

**Comment by Arokha** [comment]
Closing this since moot now and many other maps and gateway things work.

**Comment by SpadesNeil** [comment]
I just need to finish the clown level. I'm going to leave this open until I do.

**Comment by Arokha** [comment]
If you wanna do this sometime, just reopen this when you do it.
