### ISSUE TITLE
Deathgasp prints name twice

### ISSUE THREAD

**Issue by dwinters99** [VOREStation/VOREStation#10306]
#### Brief description of the bug
Using *deathgasp prints the name of the mob in chat twice.

#### What you expected to happen
Name printed once.

#### What actually happened
Name was printed twice.

#### Steps to reproduce
- *deathgasp
- Epic fail.
- Realize how complicated this form is for simple issues.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/65516417/118001343-a8f0c000-b314-11eb-87f9-05defc85e03f.png)

**Comment by dwinters99** [comment]
WELL! This has evolved into a complicated situation! Deathgasp no longer does what described in the main post, but now causes you to... drumroll... vomit. Yes, *deathgasp causes you to vomit.

**Comment by Arokha** [comment]
Think this is fixed now!
