### ISSUE TITLE
Blood Dissapears in Drinking Glasses (and Possibly More).

### ISSUE THREAD

**Issue by Wolfmeme** [VOREStation/VOREStation#10322]
#### Brief description of the bug
You can't place blood into an empty drinking glass that the bartender would use.

#### What you expected to happen
For me to be able to put blood into the glass.

#### What actually happened
Any units of blood you'd inject with the syringe just vanish.

#### Steps to reproduce
- (Step 1)Draw blood with a syringe.
- (Step 2)Inject blood into an empty glass, metamorphic glass, etc.
- (Step 3)Watch as there is no blood in the glass.
 

#### Anything else you may wish to add:
- Might be a problem on other containers than listed aswell, or maybe only works on a certain container. I do know atleast that several people including myself have noticed that you can't place blood into a normal empty glass, though inserting the blood last in a drink mix that requires it still seems to work. Beakers and syringes are known to still function correctly.

**Comment by Arokha** [comment]
Fixed by heroman's PR
