### ISSUE TITLE
'protean' appears as a prosthesis manufacturer

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#10321]
#### Brief description of the bug
'protean' appears as a prosthesis manufacturer. As in, it appears in the list when you're prompted to select what manufacturer you want your prosthetic to be made by when changing your character's limbs in character setup.

#### Code Revision
- 34657a5820a3541ad7a9b71b3da5a97820d8eb9c 
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/4680835/118098905-8311fc80-b3a2-11eb-8569-abc05bea4b14.png)

**Comment by dwinters99** [comment]
![image](https://user-images.githubusercontent.com/65516417/118114417-8f538500-b3b5-11eb-8a58-ce88c220d694.png)
Yikes! Yes, it even lets you spawn in. Doesn't kill you either. Though, it doesn't let you have any protean abilities, so it's not as pressing as it might seem.
