### ISSUE TITLE
NIF and Crafting menu HUD icons disappear and reappear semi-randomly

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10346]
#### Brief description of the bug
Title says it all

#### What you expected to happen
Them to be there all the time

#### What actually happened
They disappeared at some point... Then came back. Not sure how actually random it is and might be tied to something specific, but at least I couldn't spot the moment it actually happened to make a connection.

#### Steps to reproduce
- Play the game casually 
- Wait where'd the buttons go? How long were they even gone for?

**Comment by dwinters99** [comment]
They seem to go away when you open your equipment menu for the first time, and then only appear while said menu is open.

**Comment by Very-Soft** [comment]
I can confirm that they mostly follow that logic, but sometimes they don't. 

One of my characters who doesn't have a nif had the crafting menu while the equipment menu was closed. And I THINK the buttons appeared outside the crafting menu when I went to V4 one time. It's weird.

**Comment by Arokha** [comment]
What is an equipment menu

**Comment by Heroman3003** [comment]
> 
> 
> What is an equipment menu

The one on the bottom left, one you open when you need to look at jumpsuit/gloves/etc

**Comment by Heroman3003** [comment]
Seems to have been fixed at some point. Nice.
