### ISSUE TITLE
Directional windows don't block atmosphere

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10359]
#### Brief description of the bug
If you build a wall of directional windows all properly, they don't block atmosphere from passing them.

#### What you expected to happen
For directional windows to block air travelling to/from the direction the window is facing. 

#### Steps to reproduce
- have atmos problem
- try to block an area off with directional windows

#### Code Revision
- B:release D:
Commit: 969dccd1a0d912692d02f4ebf401ebb67061cedd

**Comment by Novacat** [comment]
This seems to be an issue with constructed windows in particular, since mapped in directional windows do block atmos. Very odd.
