### ISSUE TITLE
Resist button on UI non-functional

### ISSUE THREAD

**Issue by Theoun** [VOREStation/VOREStation#10367]
#### Brief description of the bug
Clicking the Resist button on the UI does nothing!

#### What you expected to happen
Unbuckle from a seat, break a grab, struggle in a gut...

#### What actually happened
Absolutely nothing. (The resist verb still works.)

#### Steps to reproduce
- Get yourself in a resistable situation!
- Oh no! It's irresistable, if you try clicking the button to resist anyway!

#### Code Revision
Server revision: B:release D:
Commit: befd56a2f00502696f93c62da9e516a10d56e654 
 

#### Anything else you may wish to add:
This button. Thiiiis one.
![image](https://user-images.githubusercontent.com/16782073/118977925-9dce0d80-b96e-11eb-837d-aabcd3cfce92.png)

**Comment by Very-Soft** [comment]
Can confirm this happens to me too, I meant to report this myself as well.

**Comment by Novacat** [comment]
there is a fix on polairs.
