### ISSUE TITLE
Single-floor layout for Astroid has no powernet connections for Gateway, maybe, I couldn't confirm this because of Gateway access limits

### ISSUE THREAD

**Issue by softwordDeveloper** [VOREStation/VOREStation#10386]
#### Brief description of the bug
The new single-floor layout for Astroid on Tether has no wire leading to Gateway APC, _maybe._ I can't confirm this because nobody will play someone with the access required to let me in while I'm playing engineer.

#### What you expected to happen
I expected there to be a wire that connects the powernet to the Gateway APC.

#### What actually happened
There wasn't a wire that connects the powernet to the Gateway APC.

#### Steps to reproduce
- Be an engineer
- Look at the Station Alerts and see a power alarm for the Gateway APC.
- Try to get inside, which you cannot do because nobody is playing Pathfinder or Overseer.
- Notice that the wiring in the main halls doesn't lead inside.
- Lodge an issue on the github without any solid information.

#### Code Revision
- Commit: 7fd54c3ad1794514d3f3d8d5f73c9a05a909a27c 
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/73047969/119245517-8c882b00-bb3f-11eb-9ac7-4545891f90a7.png)

**Comment by foopwo** [comment]
>I can't confirm this because nobody will play someone with the access required to let me in while I'm playing engineer.

As an engineer, access is a _suggestion_.
