### ISSUE TITLE
Emote cooldown is gone again, also some emotes or their sounds are not correct!

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10390]
#### Description of the bug
You can emote as fast as you want! Which can be annoying.

Also the *chirp sound plays the teshari chirp sound rather than the classic chirp sound and I don't like that! (and I don't think it is intended) (I'm fine with being able to make the tesh chirp but I would prefer to be able to still use the old chirp.)
The hypno emote also doesn't seem to work anymore
The burp emote doesn't work anymore

#### Code Revision
- B:release D:
Commit: 7fd54c3ad1794514d3f3d8d5f73c9a05a909a27c

**Comment by Arokha** [comment]
Emote cooldown has returned, and you fixed the chrip sound I think!
