### ISSUE TITLE
Soulcatchers will still capture prey even when the option is toggled off 

### ISSUE THREAD

**Issue by YuskoTheCoyote** [VOREStation/VOREStation#10402]
#### Brief description of the bug
Upon digesting a person, the soulcatcher that your NIF starts with will capture the person, even if the option to capture prey is toggled off. 

#### What you expected to happen
That the person will be spawned as a ghost upon losing their body, as ususal. 

#### What actually happened
The person's mind was captured in the soulcatcher.

#### Steps to reproduce
- Join a round without modifying any settings with the soulcatcher settings. By default, it's supposed to have capturing prey toggled off
- Eat and digest another player

![scbug](https://user-images.githubusercontent.com/37598481/119284888-c5430580-bc0e-11eb-82bb-f2cc093eb4a0.PNG)
A screenshot of the issue.

**Comment by Arokha** [comment]
I believe this was fixed by: https://github.com/VOREStation/VOREStation/pull/10381

Reopen if I'm wrong!
