### ISSUE TITLE
Languages seem to be resetting on characters sometimes

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10410]
#### Brief description of the bug
Sometimes when spawning in normally, character's languages will be reset, and will also be missing on character setup. 

Have been getting several ahelps about this, and it also happened to me.

Didn't change anything about the character from the previous round, didn't die or get revived or anything strange. I did miss the tram, but I don't think that would be related.

#### Code Revision
- B:release D:
Commit: b19a52e3e8afc8715b5652a193bbab4a15be7b60 
 

#### Anything else you may wish to add:
- Not sure what causes this, so I can't really replicate it, but it seems to be a thing a bunch of people are having. I've noticed wen peeking through the player panel, tons of people only have galactic common now. I AM NOT SURE IF THAT IS DIFFERENT THAN NORMAL, but I thought most people tend to have at least one or two other languages. So, I think this might be a more widespread problem than is presently reported on.

**Comment by Theoun** [comment]
I can confirm this has happened to me twice now - and I know last time, in that round, I had spent half of it speaking Daemon as Nara Liss, so I definitely had my languages then. I had to leave before the round ended, and so missed the tram. And now I have no languages again. Maybe it's related to missing the tram or leaving the round improperly?

**Comment by Arokha** [comment]
This was a sanitization issue. It's fixed now.
