### ISSUE TITLE
Jukebox is nonfunctional.

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#10441]
#### Brief description of the bug
Jukebox playlist is visually incorrect and is unable to play any .ogg's displayed.

#### What you expected to happen
The jukebox to have a songlist that plays songs when selected.

#### What actually happened
Jukebox playlist is visually incorrect and is unable to play any .ogg's displayed. Instead, Or rather, it DOES play them just that it lasts for about a second before finishing. If set to Shuffle or Next, it will rapidly cycle through the selections with no sound.

#### Steps to reproduce
- Click on jukebox.
- See improper track list.
- Try selecting one, hear no music.
- Try shuffling, rapidly cycles through silent tracks.

#### Anything else you may wish to add:
- Possibly tied to the recent jukebox related PR #10375, I dunno,
Picture of the interface.
![image](https://user-images.githubusercontent.com/80289265/119757994-02073a80-be63-11eb-8842-eb0a39b3abdf.png)

**Comment by Novacat** [comment]
We forgot to do some server-side stuff when we updated the jukebox. Should be fixed now.
