### ISSUE TITLE
Main atmospherics console broken

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10466]
#### Brief description of the bug
Cant get data of or interact with most air alarms remotely

#### What you expected to happen
Be able to open and interact with any air alarm on the station

#### What actually happened
Vast majority haphazardly display inability to get data and uninteractive interface, making it impossible to use. Manual use of air alarm in location is unaffected.

#### Steps to reproduce
- Try out opening some air alarms using main atmos computer.

**Comment by Huenererschrecker** [comment]
Seems to also happen with air alarms if you just touch them in person.
