### ISSUE TITLE
Flipped tables only block movement in one direction

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10462]
#### Brief description of the bug
When you flip table, you can go through it when moving into the top, but cant when moving from bottom. Makes it a one-directional passage.

#### What you expected to happen
Blocks passage in both directions.

#### What actually happened
Only blocks in one direction and allows in other

#### Steps to reproduce
- Get a table
- Flip it
- Try going through it in all directions

**Comment by Arokha** [comment]
Related to the ON_BORDER flag in flipping.dm

**Comment by Heroman3003** [comment]
> 
> 
> Related to the ON_BORDER flag in flipping.dm

The one on the bottom left, one you open when you need to look at jumpsuit/gloves/etc
