### ISSUE TITLE
Toggle Air Hardsuit UI button is broken

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10464]
#### Brief description of the bug
On the left of screen when hardsuit is active, there are three meters and a button. The button is broken.

#### What you expected to happen
Clicking button toggles the internals on/off

#### What actually happened
Clicking button prints big red message " disables [Charname]'s internals!"
If you have internals on, you will disable them.
If you have them off it will not enable them. Message is printed anyway.

#### Steps to reproduce
- Equip a hardsuit.
- Try using Toggle Air hardsuit UI button

#### Anything else you may wish to add:
Why does it even exist, there is already a UI button for toggling internals...

**Comment by dwinters99** [comment]
> Why does it even exist, there is already a UI button for toggling internals...

Probably because internals are usually a verb or "ability" on other codebases and require a mask and an oxytank. Hardsuits have internal oxy tanks, so.
Anyways, this didn't break recently, I'm suprised this hasn't been reported. It's been like this since at least April 2020.

**Comment by Heroman3003** [comment]
Yeah, I know its not new, just decided to finally get off my butt and report it for once.
