### ISSUE TITLE
Circuitry I/Os dissappeared

### ISSUE THREAD

**Issue by dwinters99** [VOREStation/VOREStation#10473]
#### Brief description of the bug
Circuits don't have their input/output section anymore

#### What you expected to happen
Circuits to work (for once)

#### What actually happened
![image](https://user-images.githubusercontent.com/65516417/120035345-714c6e00-bfcc-11eb-8b62-d8f2251dfa43.png)

#### Steps to reproduce
- Print an assembly from the imprinter
- Add a component with I/O i.e. examiner
- View
- FAILURE.

#### Code Revision
- 7439afbe271b582e5b2d44d05e1e4fb856224251 
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/65516417/120035399-8c1ee280-bfcc-11eb-9f72-037ade9e141a.png)

**Comment by dwinters99** [comment]
Important and forgot to add: This was working last night at roughly 7:00 PM GMT-4.

**Comment by foopwo** [comment]
This issue's still ongoing and a pretty big deal for me so please don't let this get overlooked and buried.
