### ISSUE TITLE
Talon captain and engineer suit cyclers do not work for sergals.

### ISSUE THREAD

**Issue by Wylderkarde** [VOREStation/VOREStation#10517]
#### Brief description of the bug
Trying to refit the Talon officer voidsuit to the sergal setting on the captain or engineering suit cyclers will not work and you get the following messages when trying to put it on.
Your species cannot wear the talon officer's voidsuit helmet. 
You need a suit before you can attach this talon officer's voidsuit helmet. 
You are unable to equip that.
All the other suit cyclers seem to function normally.

#### What you expected to happen
Put the suit in the captains cycler to get it refited for my species.

#### What actually happened
Suit comes out unmodified or as default race type.

#### Steps to reproduce
- Grab a voidsuit.
- Take it to either the captain or engineer's suit cyclers.
- Set cycler to sergal and hit customize.

#### Code Revision
- Server revision: B:release D:
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KillianKirilenko** [comment]
Can't replicate this on a fresh-compile of the master or release branches. Used the cyclers in the captain's quarters and engineer's quarters, using their suits.

**Comment by Arokha** [comment]
Seems to work fine to me. Was this on a downstream or on Vorestation?

**Comment by Arokha** [comment]
Fixed
