### ISSUE TITLE
Parts Lathe - Phase II

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1053]
The Parts Lathe is cool, but it could use even more enhancement!

- [ ] It is using bugfixed versions of the autolathe sprites.  Needs its own distinctive sprites.
- [ ] Support cardboard boxes.  Put all the parts for a machine in a nice box.
- [ ] Make it hackable  (What should that do? Unlike autolathe there isn't much room for "hidden" features... is there?)

**Comment by Very-Soft** [comment]
Maybe hacked partslathe could work faster, or gain access to some higher tier parts? Or maybe there are some things that could only be built by the partslathe. No idea what those would be, of course.
