### ISSUE TITLE
Instruments play from the same x/y location on every z level

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10547]
#### Brief description of the bug
Musical instruments (or at least the guitar) play on every Z level when you play them

#### What you expected to happen
for your song to only be hearable to those nearby, not people on other floors/ships/planets

#### What actually happened
The jams that crossed the stars!

#### Steps to reproduce
- (Step 1)Have someone play a song
- (Step 2)Go to the same spot on another Z

#### Code Revision
- B:release D:
Commit: 2cefe451ba0495911aef8fe44e48e637ae85f183 

#### Anything else you may wish to add:
- Was ghosted at the time, not sure if that's relevent

**Comment by Arokha** [comment]
`feature`

**Comment by Arokha** [comment]
Fixed
