### ISSUE TITLE
piano tgui interfaces don't seem to update

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#10540]
I dunno if this was a  freak accident or something but the UIs didn't seem to update. For instance, if I imported a song and clicked 'play', it started to play, but 'stop' remained highlighted unless I clicked on the piano again. Same thing with beats per minute, if I hit the plus a couple of times and then play, it played more quickly, but  the tempo reading on the interface didn't change unless I clicked the piano itself. This only seems to happen with the stationary piano (I tried it with a violin and a recorder and everything worked fine).

**Comment by Arokha** [comment]
Has the same UI as the violin and stuff so it *should* be the same behavior! It's not separate code between instruments, hmm!
