### ISSUE TITLE
*deathgasp cannot be used. 

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#10556]
#### Brief description of the bug
Attempts to use *deathgasp results in a message about being unable to use that emote. 

#### What you expected to happen
Pretend to die

#### What actually happened
The game yells at me about trying to pretend to die instead of letting me pretend to die 

#### Steps to reproduce
- rest on floor
- *deathgasp
- receive redtext about being unable to do that

 

#### Anything else you may wish to add:
- I was playing Vulpkanin at the time. Note sure if that'll have relevancy, but I figured it's worth mentioning.

**Comment by KillianKirilenko** [comment]
Already reported up on Polaris as [POL#8096](https://github.com/PolarisSS13/Polaris/issues/8096), fix (supposedly) pending as [POL#8099](https://github.com/PolarisSS13/Polaris/issues/8099).

**Comment by VictorZisthus** [comment]
Instructions unclear, every emergency supply box now has a Dead Ringer.

**Comment by MistakeNot4892** [comment]
Linked PR is already live on Virgo so this is a new bug.
