### ISSUE TITLE
Spyglass Item Does Not Have A Sprite

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#10557]
#### Brief description of the bug
Spyglass item found at the southern plains POI does not have a sprite.

#### What you expected to happen
For the Spyglass to have a sprite.

#### What actually happened
Spyglass does not have a sprite. You can still pick it up via right-click, but if you put it into a container you have no way to remove it.

#### Steps to reproduce
- Venture to the narrow cliffs POI in the plains.
- Walk to end, where the bear pelt and spyglass are located.
- See no spyglass sprite.

#### Code Revision
- e324abf0ae2cbde0e0d75324d2f691441df09f1f 
 

#### Anything else you may wish to add:
- Potentially a mapping issue, but look for the Plains POI that's raised cliffs, has an ATV, bear pelt at the south end.

**Comment by klaasjared** [comment]
sprite error caused by the change in sprites for binoculars from Polaris, fixing it now
