### ISSUE TITLE
Slimes don't eat.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#1056]
#### Brief description of the issue
More or less the title.

#### What you expected to happen
They don't eat.

#### What actually happened
They should. Xenobiology is broken right now.

#### Steps to reproduce
- (Step 1)
Create a slime.
- (Step 2)
Attempt to feed it.
- (Step 3)
**Despair.**
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-02-25
a199ef8613d6076c103bd3f3b92ea36d7c34a9d3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
We've updated now. Is this still a problem?

**Comment by chaoko99** [comment]
I had mistaken... I was not aware that polaris xenobio was a *thing*. slimes function as intended... I expected them to eat monkies.
