### ISSUE TITLE
Negroni recipe sometimes does not mix

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#10574]
#### Brief description of the bug
There is some fuckery going on with the negroni recipe (1 part gin, 1 part bitters, 1 part vermouth). Sometimes it doesn't mix at all, sometimes it goes straight to the classic martini recipe ( 2 gin, 1 vermouth). 

#### What you expected to happen
The drinks to mix together into a drink

#### What actually happened
Contents: 1 gin, 1 bitters, 1 vermouth instead of 3 negroni.

#### Steps to reproduce
- Get some bitters (not found in the bar)
- - - Fill a beaker with 5 enzymes from the kitchen, walk to the cafe, fill it up with mint. It will turn into enzymes and bitters. Go back to the kitchen and filter the enzymes out with the condimaster. (Or adminspawn them in, whatever works)
- Grab a glass or beaker, pour 10 bitters into it and insert it into the booze dispenser. 
- Pour in 10 vermouth first, then add 10 gin
- You now either have 30 negroni as intended or, more likely, 10 bitters, 5 vermouth and 15 martini

- Repeat up to the step of adding the gin. Scale it down all the way to 1 unit of gin per click (drag the slider under the numbers all the way to the left)
- You now have a chance to have all ingredients in your container without them mixing into at least parts of negroni. Adding another unit of gin has another chance of either becoming negroni or martini. 

#### Code Revision
- 2524a0777ff002bc0e12de710b40c7fd3d0543e3 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/d83205c5de4c3a98e1f0c9397a216748.png

**Comment by MarinaGryphon** [comment]
Reacting 1u of reagents is weird, this is probably(?) intended. Only 2u or more will react.
The rest I'll look into.
