### ISSUE TITLE
Department Holosigns.

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#1058]
This is something I've sprited some time ago, for Aurora community, but hasnt been used. (Not sure if they even are using the darn things)

The holosigns are for:
Medical: http://www.mediafire.com/view/bi56n1hea4m2io1/Medical%20Holosign(2).dmi#
Cargo: http://www.mediafire.com/view/5szffufi6onu0t9/Cargo%20Holosign.dmi#
Security: http://www.mediafire.com/view/1hq1gsj86r4usqk/Security%20Holosign.dmi#
Engineering: http://www.mediafire.com/view/0orxi5bd2hz5dk9/Engineering%20Holosign.dmi#
Science: http://www.mediafire.com/view/kgp3ncbeyns6cn7/Science%20holosign.dmi#
And a Unpowered Holosign sprite : http://www.mediafire.com/view/oeefryoevjs4zos/holosign.dmi#

P.S. YES I know Security one is blue. It was due to Aurora having bluecurity, nor redcurity.

**Comment by ArbyTheDragon** [comment]
I don't know. I just can't picture medical with that sign. Medical already has a big blue star sign IIRC. The 'red cross' just doesn't seem to fit them all that well.
Engineering as a multitool is weird to me too. I imagine two wrenches crossed in an X.
Cargo's sprite is fine.
Science's sprite is fine, but I always imagined the 'atom with orbiting electrons' for their icon.
Security doesn't seem to resemble anything in particular. Frankly I'm not sure what it should be. I'd like input from a sec player.
