### ISSUE TITLE
Autolathe cloning materials and not deconstructing

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#10587]
#### Brief description of the bug
Autolathe refusing to deconstruct, and spawning the materials inside without actually ejecting anything, allowing for infinite amounts of metal and glass (and any other autolathe material) to be produced.

It also stops the autolathe from being moved... I believe that it's being caused by the crowbar being deleted by inserting it into the autolathe before it has chance to actually deconstruct, but I've not checked the code.

#### What you expected to happen
Screwdriver and crowbar on the Autolathe will make the Autolathe's components and its materials come out, thus turning it into a frame with a wired circuit board.

#### What actually happened
You screwdriver open the panel, use your crowbar and then the autolathe eats the crowbar, but the materials inside the autolathe are spawned outside of the autolathe, without removing any from the autolathe itself.

#### Steps to reproduce
- (Step 1) Screwdriver open an autolathe, then apply your crowbar.
- (Step 2) Watch as your crowbar disappears and the autolathe does not deconstruct. If it's filled it will spawn whatever materials were inside.

**Comment by Kegsey** [comment]
Fixed by #10591

**Comment by Kegsey** [comment]
Love you @Hatterhat

**Comment by Kegsey** [comment]
Wait fuck- this is the wrong one.

**Comment by Novacat** [comment]
Autolathe got overhauled so this is probably not an issue anymore.

**Comment by ShadowLarkens** [comment]
If it is, open a new issue pretty please! :heart:
