### ISSUE TITLE
Weather overlay appears in survival pods on V4 beach

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#10607]
#### 
Planetside weather events occur in bar survival pods on V4

#### What you expected to happen
Rain to bounce harmlessly off the roof, rather than phasing through solid matter

#### What actually happened
Planetside weather overlay was applied inside the bar pod

#### Steps to reproduce
- Go to around 42, 108 on V4
- Deploy bar pod
- Experience weather
- Observe the weather in your pod, not on the beach

</div></div>

**Comment by Very-Soft** [comment]
Seems like the survival pods need to set their turfs to not be outdoors and that ought to fix

**Comment by Arokha** [comment]
Does this still happen? I redid weather
