### ISSUE TITLE
Psychologist's office causing hard crashes

### ISSUE THREAD

**Issue by SingingSpock** [VOREStation/VOREStation#10606]
#### Brief description of the bug
When players are in the psychologist's office, they hard crash very regularly

#### What you expected to happen
I expect the game client to not randomly crash

#### What actually happened
Random crashes happen all the time, at a much higher rate than in any other room I've spent time in

#### Steps to reproduce
- Go to psychologists office
- Hang out for an hour or two, possibly doing psych RP
- Enjoy your client crashing every 15-30 in ways that interrupt your scene

#### Code Revision
- B:release D:
- `Commit: dfc384ecbb369b44cef9bf274691658312909598 `

**Comment by Arokha** [comment]
Try latest 514
