### ISSUE TITLE
Research Stairway missing Railing

### ISSUE THREAD

**Issue by ShadowLarkens** [VOREStation/VOREStation#10618]
#### Brief description of the bug
The Research Stairway has two railings missing, one on the upper level (z3), and one on the middle level (z2), allowing you to fall off the stairs.
#### Code Revision
Master
#### Anything else you may wish to add:
![https://i.tigercat2000.net/2021/06/dreamseeker_3GLjgBhYS3.png](https://i.tigercat2000.net/2021/06/dreamseeker_3GLjgBhYS3.png)
![https://i.tigercat2000.net/2021/06/dreamseeker_qOaEvO2b9H.png](https://i.tigercat2000.net/2021/06/dreamseeker_qOaEvO2b9H.png)

**Comment by dwinters99** [comment]
I'm almost certain this was a consequence of the stairs """"improvement"""" from a little while ago.

**Comment by Kegsey** [comment]
Thanks for posting this, the amount of times I've gotten Engineers to fit railings in there is unreal....
Also, I'm definitely in the double dozens of falling down those stairs.
