### ISSUE TITLE
Yellow slime bug

### ISSUE THREAD

**Issue by Borg-of-fools** [VOREStation/VOREStation#10627]
Brief description of the bug

Being a synth and getting shocked by a yellow slime forever/never dying no matter how damaged your body becomes to it.

What you expected to happen

Not to be zapped from five to 6 tiles away

What actually happened

Being stun-locked until you fall over not dying and getting shot more by them.

Steps to reproduce

be a synth and die to the yellow slime.
be given a new body or be revived.
go back to the yellow slime and be zapped over and over again.

(i'm not even fully sure this is how it even went down but its the closest thing i know from the events.)

**Comment by Heroman3003** [comment]
Slimes have several stunlocks. Yellow slime's zap is only stunning to synths, iirc, and that's the main issue. Another one if you're a borg, then ruby slimes' fling attack is also a stunlock.

**Comment by Borg-of-fools** [comment]
The bug is that damage keeps stacking when you're meant to die as a synth, they can keep zapping you at range over and over and seemingly have no range for their zap. getting up close causes them to keep refreshing the zap stun.
