### ISSUE TITLE
Feild medic locker all kinds of broken

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#10634]
#### Brief description of the bug
FM locker is missing it's spirte and contents. If unlocked but closed it goes invisiable

#### What you expected to happen
job locker to exist with job gear

#### What actually happened
default spirte, could be invisable, no job gear

#### Steps to reproduce
- (Step 1) go to FM locker

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add: 7e1fbae5e7ce39df15ca1edff6d2160c5f9d2edf 
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Razgriz1032** [comment]
I'm betting #10615 broke it
