### ISSUE TITLE
Suit Cycler in Exploration cannot apply Vulp modification

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#10655]
#### Brief description of the bug
Suit cycler will not apply Vulp customization

#### What you expected to happen
Put suit in cycler, customize for Vulpkanin

#### What actually happened
Put suit in cycler
"Unable to apply specified cosmetics with specified species. Please try again with a different species or cosmetic option selected."

#### Steps to reproduce
- assemble suit
- Place in cycler
- select Vulpkanin and Explorer, respectively
- be denied the right to go on crazy missions.

**Comment by KillianKirilenko** [comment]
Hm. Bryn reported something like this in the explo channel a couple of weeks ago but I couldn't replicate it on master or release at the time. Which suit were you trying to cycle, a regular exploration suit or something else?

**Comment by SigholtStarsong** [comment]
Regular exploration. Specifically the leftmost suit.

**Comment by KillianKirilenko** [comment]
Testing on fresh release compile with all three explorer suits *and* the two field medic suits, all of them are running through fine.

Closest I can get to this is that I can't cycle from exploration to field medic colors, but I'm pretty sure I see why that is.
