### ISSUE TITLE
Becoming a synth on one character breaks the negative trait haemophilia permanently and for all characters

### ISSUE THREAD

**Issue by Razgriz1032** [VOREStation/VOREStation#10665]
Because apparently whatever goes on here in this code block is applied once and for all as soon as the player decides to use a synth body.
https://github.com/VOREStation/VOREStation/blob/9855a5e3702355065fabe50bc131a9424e19b368/code/modules/client/preference_setup/vore/07_traits.dm#L109

Setting all limbs to normal doesn't fix it. Clicking reset limbs also doesn't fix it. Nuking the character doesn't fix it. It corrupts your entire character roster including new characters, and so no character can take haemophilia.

**Comment by Verkister** [comment]
A fix has been tossed upstream https://github.com/PolarisSS13/Polaris/pull/8148
