### ISSUE TITLE
chameleon suit icons busted for KIN command suit

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1066]
#### Brief description of the issue
![image](https://cloud.githubusercontent.com/assets/14942479/23551122/b8e3956a-000c-11e7-9699-c50073a73d03.png)

#### What you expected to happen
Icon to work

#### What actually happened
See screenshot.

#### Steps to reproduce
- Get chameleon suit
- set to KIN command suit

#### Code Revision
Server revision: release - 2017-02-25
a199ef8613d6076c103bd3f3b92ea36d7c34a9d3 
 
#### Anything else you may wish to add:
I think the chameleon suit might be pointing at the wrong .dmi - it hasn't copied the correct icon, icon_override or item_icons vars from the item it's attempting to duplicate.

/obj/item/clothing/under/chameleon 

(E) (C) (M) icon = icons/obj/clothing/uniforms.dmi
(E) (C) (M) icon_override = null
(E) (C) (M) icon_state = "khi_uniform_cmd_i"
(E) (C) (M) item_icons = /list (2)
slot_l_hand = icons/mob/items/lefthand_uniforms.dmi
slot_r_hand = icons/mob/items/righthand_uniforms.dmi
(E) (C) (M) item_state = "khi_uniform_cmd"
(E) (C) (M) item_state_slots = /list (1)
slot_w_uniform = "khi_uniform_cmd"

**Comment by Arokha** [comment]
I would assume it doesn't work for ANY of our fluff stuff then.

**Comment by SpadesNeil** [comment]
This still an issue or did it get fixed with the changes to fluff items recently?
