### ISSUE TITLE
brass mcguffin key doesn't spawn for brass gateway

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#10681]
#### Brief description of the bug
key to get home doesn't spawn

#### What you expected to happen
key to get home spawning

#### What actually happened
key to get hone does not spawn

#### Steps to reproduce
- (Step 1) get gate way that needs key to calibrate
- (step 2) nope

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Fixed
