### ISSUE TITLE
Alt-click turf menu shows overlays that aren't there on some items

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10706]
#### Brief description of the bug
Some weird overlays happened to appear over objects in the menu that shows up when you alt-click a turf. Generic 'closed locker' icon over open locker and the 'honk texture missing' icon over CE jumpskirt

#### What you expected to happen
Icons shown as they normally are

#### What actually happened
Weird random additions related to files or something? Also, more objects than two I listed might be affected, but these were just too obvious.

#### Steps to reproduce
- Find a problematic object (in my case, open CE locker with its contents)
- Alt-click it
- Icons what?

**Comment by Arokha** [comment]
Related to tg lighting

**Comment by Arokha** [comment]
A sacrifice that we have to make \o/
