### ISSUE TITLE
Medical Aviators not selectable

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1070]
#### Brief description of the issue
The "Medical HUD Aviators, prescription (Medical)" option in the loadout cannot be selected.

#### What you expected to happen
To give my doc some shades.

#### What actually happened
It simply did nothing when I clicked it. And I mean _nothing._ I might as well have clicked on the flavor text for all the acknowledgment the game gave me.

#### Steps to reproduce
- Log into Byond
- Press Open...
- Enter VORE's byond address
  - Alternate: select VORE's bookmark
- Press OK
- Press Setup Character
- (Optional) Press Load Character
  - Select a character who has medical doctor set to High
- Press Loadout
- Press Glasses and Eyewear
- Press Medical HUD Aviators, prescription (Medical)
- (Optional) Witness as nothing happens

#### Code Revision
- a199ef8613d6076c103bd3f3b92ea36d7c34a9d3 
 
#### Anything else you may wish to add:
- I decided to have a bit of fun with the reproduction steps. I apologize in advance.

**Comment by JoanRisu** [comment]
This is being fixed in the next release.
