### ISSUE TITLE
Wheat produces half a sprite

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#10722]
#### Brief description of the bug
Wheats produce only half the sprite. See picture bellow.

#### What you expected to happen
Receiving the full fruit, complete with stalks.

#### What actually happened
See above.

#### Steps to reproduce
- Go to hydroponics
- Go to the seed vendor, vend yourself some wheat
- Plant wheat in a tray
- Wait until it grows
- Harvest it

#### Code Revision
- e31927a4166403df177da944a0efc117f2a630e2 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/0f74d355547e6c7edd52494e326ed8b1.png
- Wheat was planted in soil patches when it happened, might have something to do with that. I dunno.

**Comment by Huenererschrecker** [comment]
Problem seems to not be exclusive to wheat. I just got carrots that also lack it's full sprite. https://i.gyazo.com/475afa0b111c5ff4a0c8c935d4b3f510.png

**Comment by MarinaGryphon** [comment]
It appears to be semi-random! No idea how/why it happens, but I can confirm it.

**Comment by MarinaGryphon** [comment]
Got it.
