### ISSUE TITLE
ITV Talon moves on its own

### ISSUE THREAD

**Issue by greed23** [VOREStation/VOREStation#10734]
#### Brief description of the bug
When ITV Talon is completely and fully stopped, it may begin to move on its own at a slow speed (seems to be the same amount of acceleration as the engines can provide in one burst at their current power setting.)  

#### What you expected to happen
We expected the ship to stay put when the current speed is set to 0 Gm/h.

#### What actually happened
The ship moved on its own after a varying amount of time, always at 0.33 Gm/h (the max acceleration the engines were able to output at the time).

#### Steps to reproduce
- 1. Fly the ship, then stop its motion completely so that speed reads 0 Gm/h
- 2. Wait.  Actions performed around the ship don't seem to affect it.

**Comment by Arokha** [comment]
Tested but I'm unable to get the ship to move 'on it's own' after stopping fully.
