### ISSUE TITLE
TGUI Vorepanel visual issue

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10741]
#### Brief description of the bug
Belly 'tabs' are way too small and overlap one another in awkward way

#### What you expected to happen
Nice looking list of belly tabs

#### What actually happened
Mess

#### Steps to reproduce
- Have many bellies with varied name length
- Look at your vore panel
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/31296024/123211860-602d4900-d507-11eb-8878-a6d5ff6126c6.png)

**Comment by SplinterGP** [comment]
missing wrap into another row
