### ISSUE TITLE
Overmap Meteor event causes tons of lag with the talon (or maybe just in general?)

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10742]
#### Description of the bug

So, the talon is actually quite resistant to meteors what with all the point defense turrets it has, if it's set up, it can quite happily slowly fly through a meteor field without a crazy amount of risk, especially if you turn the shields on.

But, I have found that if you do that, the whole server gets CRAAAAZY laggy until it's out of the field, while the ship itself might take some minimal damage, if it takes any damage at all. (So, it's not like it's processing atmos changes or explosions or anything)

I was doing this because I noticed that when the meteors get destroyed, they drop some ore, so. Was attempting to mine using a spaceship, since, it at least seems somewhat intentional for that to be a thing you can do.

#### What you expected to happen

Not ruin the round for everyone with lag while seeking space profit

#### What actually happened

Everyone had a bad time

#### Steps to reproduce
- (Step 1) Set up the talon
- (Step 2) Fly the talon into a meteor field

#### Code Revision
- Server revision: B:release D:
Commit: c901b017ef9faaa5fab34126b088d695295f8715 

 

#### Anything else you may wish to add:
I should note there are kind of 3 moving parts here, and I think it could be any or all of them collectively causing this:

-The meteors spawn and get thrown in a direction
-The turrets shoot beams at the meteors, destroying them
-When destroyed, the meteors spawn a bunch of ore which continues on the meteors' original trajectory

I have noticed that the server seems to hitch for a while sometimes while the turrets' beams are firing, but, really I am not sure what part of this is causing the whole server to slow to a crawl, but it's happening, and I think it might be a source of some of our mysterious random server chuggings that happen sometimes

I haven't tested it further yet, so I'm not sure if this is a problem that just the talon has, or if it just always happens. (people usually avoid flying into meteors, and when they do fly into them, the shuttle usually blows up, so it seems normal that the server might lag.)

**Comment by Very-Soft** [comment]
Additional notes:

I adminbused the talon's power so that it could indefinitely run the shields, and found that when the shields are up, it doesn't totally murder the server. It does still seem to slow things down a little, but not quite as much. Notably, the shields being up means that the turrets cannot fire (they try, but they spam that they can't do that), so the meteors just hit the shield and leave behind their ores.

SO, it seems like it is likely related to the firing of the turrets, or the throwing of ores after the meteors are destroyed

I ALSO noticed that some of the ores that get left behind seem to be stuck in a perpetual state of getting thrown, and not just like, as a visual thing, if you move out onto the tile they are getting thrown to, you'll get hit by them a zillion times.

**Comment by KillianKirilenko** [comment]
My money's on it being the moving asteroids getting blatted and 'transferring' momentum to their ore. I don't recall noticing any unusual sluggishness when just Game Panel spawning asteroids for stationary target practice, and I was spawning a decent number of them.

Shouldn't be too hard to test either, just find where the asteroids handle the ore creation and comment it out. Worst-case scenario it has to stay disabled and they can't be used to gather resources any more, but the amounts are so small it's basically just a consolation prize for getting hit. Yay, two uranium ore and here's a giant fuckoff hole in the port cargo bay, thanks!

As for the other stuff, did you test the fire-through-shields thing with the shield setting that lets laser shots pass through? It's some... EM/Photon Modulation setting or something, I think, should be in the first block of settings.

**Comment by Very-Soft** [comment]
> Shouldn't be too hard to test either, just find where the asteroids handle the ore creation and comment it out. Worst-case scenario it has to stay disabled and they can't be used to gather resources any more, but the amounts are so small it's basically just a consolation prize for getting hit. Yay, two uranium ore and here's a giant fuckoff hole in the port cargo bay, thanks!

I would preferrrrrr to keep the ore, but maybe it doesn't need to transfer its momentum? Really it will depend on what's actually causing the issue, but, at least to me, that seems the most likely, since, when the meteors hit the shield and break, the server doesn't die. (And the amount of stuff you get can be pretty significant, you just only get a few kinds of things)

> As for the other stuff, did you test the fire-through-shields thing with the shield setting that lets laser shots pass through? It's some... EM/Photon Modulation setting or something, I think, should be in the first block of settings.

I thooooooght I had everything except hull shielding and hyperkinetic projectiles turned off, but, I can't check right now

**Comment by FartMaster69420** [comment]
A possible solution would be to replace ore spawns with some kind of asteroid geode that can be mined to drop the ores. That way, you have far less entities buzzing about.
