### ISSUE TITLE
Tall trait doesn't seem to work when character is adminspawned

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#10762]
#### Brief description of the bug
See title!  Had a character with the tall trait, but after being adminspawned, didn't have the appropriate change to my character sprite's scaling.

#### What you expected to happen
To have a tall character!

#### What actually happened
Character got adminspawned, ended up normal-sized instead of tall.

#### Steps to reproduce
- Make a character with the "Tall" neutral trait.
- Shift your scale a bit in character creation/refresh the icon so you can see the vertical stretch.
- Get adminspawned.
- Find that your character doesn't have the vertical stretch that Tall should've given them.

#### Code Revision
- Server revision: B:release D:
Commit: 82d7db23c1ee8c7c278dd8c27426b46b3dd181d5 

#### Anything else you may wish to add:
- This could possibly affect the other traits that affect the character scaling.

**Comment by Heroman3003** [comment]
Did other traits work?
