### ISSUE TITLE
Tables connect a bit too much

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10787]
#### Brief description of the bug
Tables visually 'connect' to adjacent racks and shelvings

#### What you expected to happen
Tables are tables, shelves and racks are shelves and racks

#### What actually happened
Tables 'extend' towards adjacent racks as if they're tables too

#### Steps to reproduce
- Look at the racks in, say, public EVA
- Ew.

**Comment by Arokha** [comment]
Racks ARE a subtype of table, but yes it should be more strict about merging.
