### ISSUE TITLE
Micro holders don't copy all the layers?

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10796]
#### Brief description of the bug
When you pick up someone smaller than you, they just appear as their base body sprite without ears, tail, or clothes 

#### What you expected to happen
For them to appear with all their items and effects

#### Steps to reproduce
- (Step 1)be big
- (Step 2)pick up someone small

#### Code Revision
- Server revision: B:release D:
Commit: 82d7db23c1ee8c7c278dd8c27426b46b3dd181d5 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Fixed on master
