### ISSUE TITLE
traits got messed up in a recent update

### ISSUE THREAD

**Issue by oooO0W0Oooo** [VOREStation/VOREStation#10841]
#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
That wasn't unintentional. Ascian didn't care for that being a trait dump stat, but we didn't want to just outright remove it in case people want the extra effect for fluff. So, it's -1 now.

**Comment by Heroman3003** [comment]
This wasn't a 'mess up', this was a balance change.
