### ISSUE TITLE
Talon Engines Shutdown on their own.

### ISSUE THREAD

**Issue by greed23** [VOREStation/VOREStation#10875]
Talon engines will occasionally shutdown if navigation buttons are pressed rapidly. 

The Talon engines should not cut out midflight when fuel and power is supplied.

The Talon engines will occasionally and randomly shutdown while ship is in flight, particularly when the navigational buttons are being pressed repeatedly and rapidly, as is common in emergency stops.  Engines then require to be fully restarted from the engine control console.

#### Steps to reproduce
- Step 1: Boot all talon engines
- Step 2: Fly at a high speed, then proceed to attempt a rapid stop.

**Comment by Very-Soft** [comment]
If I had to guess, they probably weren't getting enough fuel. What were the fuel pumps set to?

**Comment by Arokha** [comment]
Fuel or power! It might be that they demanded too much power in one power cycle and the area was like 'nope, can't supply that much at once' and so the engines decided they didn't have power. There's no consideration, as far as I'm aware, for like 'oh we got SOME of the power we needed so we'll keep going'. I believe they just turn off.

**Comment by Very-Soft** [comment]
One mistake I've seen people on the talon make lately is, just turning the fuel pumps on, and not increasing their values. That means they get hardly any fuel and are easy to drain. 

I've personally never had something like what's happening in this happen to me when I increase the fuel pump's rate.

**Comment by greed23** [comment]
Is this intended then? Considering the fact that the engines can just immediately be turned on again to resolve the issue, I'm hesitant to say that's how it should function.  The intuitive conclusion to come to is that max fuel flow simply determines how fast the ship can accelerate, based on values that are produced by the navigation screen; This, at the very least, gives the impression that its a bug, considering how infrequently it happens and how much you have to spam click stop to make it occur.
