### ISSUE TITLE
Inventory/Belt Phantom Item bug.

### ISSUE THREAD

**Issue by Enzo-Leon** [VOREStation/VOREStation#10873]
#### Brief description of the bug
When pulling something from any inventory space, the *used* space will remain and won't vanish/reset until you close or click the container again.

#### What you expected to happen
When pulling something out the used space/slot should vanish or the item to the right (if applicable) should take its place.

#### What actually happened
The used space remains, or the inventory does not move over. However, if you try and click the empty space on the belt, the item in your hand will act like it was "used" and do its context action. The same applies to backpack used inventory space. Currently, you need to either close the bag, click the bag again, or with the item in your active hand, click the container to stuff it back in.

#### Steps to reproduce
- Pull an item out of a container
- Attempt to put the item back in without updating the inventory space
- Either will fail, get used, or nothing happens.
- Clicking the container itself will put the item back in the container though.

#### Anything else you may wish to add:
<img width="517" alt="phantomitem" src="https://user-images.githubusercontent.com/12926003/124399680-dd0fae00-dcd1-11eb-86aa-f04c5b6c5ed1.png">

<img width="619" alt="phantomitem2" src="https://user-images.githubusercontent.com/12926003/124399710-134d2d80-dcd2-11eb-8ff3-8498dd597bf5.png">

**Comment by Enzo-Leon** [comment]
Did a clear cache and re-updated BYOND to the newest 514 version and this is no longer happening. This might be some weird cache issue with clients. I will update if this occurs again if the issue is still open.

**Comment by Heroman3003** [comment]
That same issue existed prior to this updated, with only difference being that clicking empty space left by item did nothing and that it only happened under certain circumstance (like removing item ratehr than just taking it out)
