### ISSUE TITLE
Window Build Menu Missing

### ISSUE THREAD

**Issue by Enzo-Leon** [VOREStation/VOREStation#10872]
#### Brief description of the bug
The pop-up menu for building windows with glass tiles does not show up

#### What you expected to happen
Pop-up menu for wanting to build glass windows will pop up and then you can build some cool glass windows.

#### What actually happened
Nothing happens at all

#### Steps to reproduce
Step 1 - Acquire Glass sheets
Step 2 - Press Z/use to attempt to pull up the build menu which will fail to do so.

**Comment by Arokha** [comment]
Fixed
