### ISSUE TITLE
Painting Exhibit Mountings reference Curator

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10870]
#### Brief description of the bug
Title says it all

#### What you expected to happen
Curator isn't a job that exists, so shouldn't be referenced

#### What actually happened
It is referenced

#### Steps to reproduce
- Examine a frame in library

**Comment by Arokha** [comment]
I mean, it's not a job reference so much as just like, the role of the person who curates art. Like the librarian *is* the curator in this case. They are the art curator.
