### ISSUE TITLE
Items Vanishing while Resting when attempting to remove them from hotbar

### ISSUE THREAD

**Issue by ArcanaValinar** [VOREStation/VOREStation#10882]
#### Brief description of the bug

Items vanishing when taken out of hotbar on bottom of screen, specifically with PDA on card slot or pockets when resting.

#### What you expected to happen

The item is supposed to fall to the floor.

#### What actually happened

As stated before it simply vanishes and there's no way to get it back known to me.

#### Steps to reproduce
- (Step 1)
use Rest action and lay down
- (Step 2)
attempt to remove card, pda, or any other thing from pockets

**Comment by Very-Soft** [comment]
Fixxed as of the latest version
