### ISSUE TITLE
Forks do not work

### ISSUE THREAD

**Issue by Slovakiani** [VOREStation/VOREStation#10885]
#### Brief description of the bug
Forks do not work as intended.

#### What you expected to happen
Forks to scoop food from a food item in reasonable bites, and for you to devour food off said fork.

#### What actually happened
You can, in fact, scoop food with a fork, however the sprite does not update and attempting to eat off of said fork tells you that there is no food on it. And when you try to scoop more food onto said bugged fork, it tells you there's already food on it~

#### Steps to reproduce
- (Step 1) Take fork
- (Step 2) Fork food
- (Step 3) Suffer

**Comment by MarinaGryphon** [comment]
Fixed by https://github.com/PolarisSS13/Polaris/pull/8165
