### ISSUE TITLE
Guest pass uses wrong icon

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10897]
#### Brief description of the bug
Gues passes uses default ID icon

#### What you expected to happen
Use proper unique icons for guestpass

#### What actually happened
Sad grey default ID

#### Steps to reproduce
- Make a guestpass
- Sad

**Comment by KillianKirilenko** [comment]
I know they *used* to do this but I was pretty sure I fixed it when I was doing the initial implementation. They might just need an additional `/New()` step with `update_icon` or something. Should be easy enough.
