### ISSUE TITLE
Some of the new glowies appear where they shouldn't from above

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10893]
#### Brief description of the bug
![image](https://user-images.githubusercontent.com/24854483/124426647-5510bf00-dd38-11eb-9cca-08ed0d72f1ee.png)

#### What you expected to happen
That glowy is downstairs! Not up!

#### Steps to reproduce
- (Step 1)Observe glowy

#### Code Revision
- B:release D:
Commit: 2593eca0ad592fed0be81a56b55016a3284606ca 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
that's a newscaster, and... what's the other one?
