### ISSUE TITLE
Rigsuit chestpiece sprite dissapears unless jumpsuit worn.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#109]
#### Brief description of the issue
The rigsuit chestpiece sprite doesn't show up on your character or in the O_suit slot when activated if you don't wear a jumpsuit.

#### What you expected to happen
Have the rigsuit chestpiece sprite show up

#### What actually happened
The rigsuit "suit" sprite never showed up.

#### Steps to reproduce
1. Take off jumpsuit
2. Put on rigsuit
3. Toggle the rigsuit until it's completely activated
4. Toggle the rigsuit chestpiece
4.1. Spook the crew by walking in space by retoggling the hardsuit chestpeice so it mechanically works, but doesn't actually show up on your sprite

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
One being used at time of writing
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
This effects all rigsuits that I tested. (CE, ERT, and Hazmat)

**Comment by SpadesNeil** [comment]
Fixed by https://github.com/VOREStation/VOREStation/pull/80
