### ISSUE TITLE
Shadekin can't have beards

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#10901]
#### Brief description of the bug
Im 99% sure this is unintentional, considering I made humanmob shadekin and dont even remember considering beards as exclusion and that they are the only species this happens with.

#### What you expected to happen
Beards selectable and usable, if ugly looking maybe.

#### What actually happened
NO BEARD?

#### Steps to reproduce
- Make a shadekin (any kind) in char setup
- Try to add luxurious beard

**Comment by Very-Soft** [comment]
Too much soy in their diet, can't grow beard, very sad

**Comment by TheDavestDave** [comment]
Bloody Martian can't sing shanties then, what a horrible pirate
