### ISSUE TITLE
Solid rock doesn't generate edges.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#10902]
#### Brief description of the bug
Unlike normal rock, solid rock doesn't generate edges. This looks a little weird.

#### What you expected to happen
for solid rock to generate edges.

#### What actually happened
There's no edges.

#### Steps to reproduce
Go look at the solid rock used in certain POIs, it's unbreakable

**Comment by Arokha** [comment]
Got a type to look at?

**Comment by Ketrai** [comment]
> Got a type to look at?

I saw it ingame somewhere, don't have a path no. It was just named solid rock.
