### ISSUE TITLE
(NIF?) crew monitor shows the old map layout

### ISSUE THREAD

**Issue by Detective-Google** [VOREStation/VOREStation#10903]
#### Brief description of the bug
crew monitor still shows old layout on the map setting
#### What you expected to happen
show the current map
#### What actually happened
![image](https://user-images.githubusercontent.com/48196179/124467760-e5152f80-dd5d-11eb-8030-893361f66c4e.png)
#### Steps to reproduce
uses the NIF crew monitor specifically, unsure about non NIF version
#### Code Revision
8c4c340268ad5a736c39c066b3f311abb63567e3

**Comment by Arokha** [comment]
This is updated already. Clear your cache, it's probably got an old version in there.

The current version from the server:
![tether_nanomap_z5](https://user-images.githubusercontent.com/15028025/124484777-d2a8ef00-dd79-11eb-932c-01ad20b0f17b.png)
