### ISSUE TITLE
Recipe conflict for chocolate bars & choccy milk

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#10913]
![image](https://user-images.githubusercontent.com/28861083/124498979-897a8e80-ddbd-11eb-91cd-060e6afb9e76.png)
![image](https://user-images.githubusercontent.com/28861083/124499004-94cdba00-ddbd-11eb-9e64-90f6ad4e886d.png)

Tested ingame as well.

**Comment by MarinaGryphon** [comment]
This is not a conflict. Add the coco powder last.
