### ISSUE TITLE
The random chance for frosted donuts was removed.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#10914]
#### Brief description of the bug
Donuts normally have a 30% chance to become a frosted donut when created.

#### What you expected to happen
To cook some frosted donuts, sprinkles are even used in some recipes. The only other way to get sprinkled donuts is via security, or vending machines specifically for donuts.

#### What actually happened
Find out the chance was removed with no documentation as to why.

#### Steps to reproduce
Try to make frosted donuts.
Fail horribly.
Find out it isn't possible anymore.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/28861083/124499945-2558ca00-ddbf-11eb-96ee-46524e7cb92f.png)
In snacks.dm
https://github.com/VOREStation/VOREStation/pull/10802
Guilty PR.

**Comment by Arokha** [comment]
All donuts were replaced with two types: plain and jelly. The donut boxes spawn them randomly. It made sense when there were only two donuts, one of which was 'better' to just have a less-than-half chance to turn into that 'better' donut, but when you've got like 18 coequal donuts, it doesn't make as much sense.

Sprinkles should probably just be craftable or start in the kitchen or something. 'Getting a donut to steal the sprinkles' is maximum jank and shouldn't be the 'expected' way of doing anything.
