### ISSUE TITLE
Smart Drink Storage uses the wrong sprite when filled

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10917]
#### Brief description of the bug
![image](https://user-images.githubusercontent.com/24854483/124515988-bf644680-ddae-11eb-8f8f-9a5a4d3f6710.png)
I think when you put stuff in it, it uses the wrong sprite?

#### What you expected to happen
Not that

#### Steps to reproduce
- (Step 1)Put stuff in the Smart Drink storage

#### Code Revision
- B:release D:
Commit: 9a251fc3a0c7a6f82d567aae15496a614ec8e6a1 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
This weird overlay shows up semi-randomly on vendors in various bugs. Seems like missing icon state situation.
