### ISSUE TITLE
Ship sensors capped at 3.5

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#10910]
#### Brief description of the bug
The range of ship sensors is capped at 3.5. Raising the range above 3.5 produces a sensor range identical to sensors set to a range of 3.5.

#### What you expected to happen
For setting the range of ship sensors above 3.5 to increase how far the ship's sensors can see.

#### What actually happened
Not that.

#### Steps to reproduce
(I've only personally witnessed this on the Talon, but I assume it'd happen with all ships. But it might not!)
- Find a ship
- Launch it into space if it's not the Talon
- Enable the sensors if they're not already enabled
- Enter map view
- Set the sensors' range to 3.5
- Raise the sensors' range to 7
- Observe lack of change in visibility

#### Code Revision
- 8c4c340268ad5a736c39c066b3f311abb63567e3 
 

#### Anything else you may wish to add:
- Again, I've only personally witnessed this on the Talon

**Comment by ResidentCody** [comment]
Confirming that this happens on all ships, not just the Talon.

**Comment by TheToaster98** [comment]
This is still happening as of new map.
