### ISSUE TITLE
Announce verb doesn't work

### ISSUE THREAD

**Issue by pontifexminimus2** [VOREStation/VOREStation#10920]
Please provide a clear and concise description of what the bug is.
#### Announce doesn't work.

What normally happens when this occurs? Keep in mind that behavior may be different on other servers.
#### Announce working

Please use as much detail as possible when describing the bug behavior, including any context (things you did before) that might be relevant.
#### It didn't work.

Same here, please include any context that might have contributed, such as actions taken right before.
#### Steps to reproduce
- Be Admin
- Want to make a meme announcement.
- Click Announce
- Nothing happens

**Comment by Arokha** [comment]
![image](https://user-images.githubusercontent.com/15028025/124524140-d8c5bc80-ddc7-11eb-9a62-eb732bfe31fd.png)
