### ISSUE TITLE
Security Camera Consoles are not working correctly

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10924]
#### Brief description of the bug
![image](https://user-images.githubusercontent.com/24854483/124523445-1a089d00-ddc5-11eb-87f6-52da20f7f654.png)
Security camera consoles look a bit funky and can't really be used effectively, it seems like either, space is semi-transparent on top of everything, or everything is semi-transparent on top of space

#### What you expected to happen
To be able to see things through the cameral normally.

#### Steps to reproduce
- (Step 1)Look in security camera console

#### Code Revision
- B:release D:
Commit: 9a251fc3a0c7a6f82d567aae15496a614ec8e6a1

**Comment by Arokha** [comment]
Space camera! Nice

**Comment by Arokha** [comment]
Fixed
