### ISSUE TITLE
Packaged burgers don't function properly.

### ISSUE THREAD

**Issue by MarinaGryphon** [VOREStation/VOREStation#10935]
#### Brief description of the bug
Packaged burgers turn invisible and are still called 'packaged burger' after being unwrapped, but can't be unwrapped again.

#### What you expected to happen
The burger would get unwrapped, change names, and be visible.

#### What actually happened
Burger was invisible.

#### Steps to reproduce
- Buy packaged burger
- Hit 'use' to unwrap
- Burger is invisible and in your hand.

#### Code Revision
- Server revision: B:release D:
- Commit: e9401281e9eb5fc1c69300c7b994ce2d025bae6e

**Comment by JoanRisu** [comment]
Yuh, experienced this too.

**Comment by MarinaGryphon** [comment]
Fixed in #10936.
