### ISSUE TITLE
various chemistry graphical issues

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#10947]
sometimes bottles seem to be graphically empty while containing reagents,  i'm not 100% sure how to reproduce it

the lids for bottles also don't appear to exist, the dermaline bottle here has a lid on it and the inaprovaline one doesn't but there is absolutely no visual indication
![image](https://user-images.githubusercontent.com/20329223/124773349-e20b7200-df0a-11eb-981a-eadbd08da77a.png)

**Comment by Arokha** [comment]
![uwHRhNO1Xo](https://user-images.githubusercontent.com/15028025/124863418-05730300-df85-11eb-8031-17724c0ac9e8.gif)

Mlemmmmmmmmm

**Comment by MarinaGryphon** [comment]
> sometimes bottles seem to be graphically empty while containing reagents, i'm not 100% sure how to reproduce it

Are you sure they're not just colored the same as the glass?

But also:
```
	icon_state = null
/* blah blah */
	if (!is_open_container())
		add_overlay("lid_[initial(icon_state)]")
```
Oh dear. Looks like chemmaster bottles won't work.

**Comment by lm40** [comment]
well that'll be it then, guess this is what i get for not giving step by step directions how to replicate the lid issue, it is indeed only the chemmaster ones that don't work, admin spawned bottles seem to work fine

as far as the graphically empty bottles i took a chemmaster created round bottle, poured twenty units of hyronalin into it, and it became graphically empty, also empty at 30 and 40 units. 50 units the contents became visible again.

**Comment by MarinaGryphon** [comment]
> well that'll be it then, guess this is what i get for not giving step by step directions how to replicate the lid issue, it is indeed only the chemmaster ones that don't work, admin spawned bottles seem to work fine
Figured out why.

> as far as the graphically empty bottles i took a chemmaster created round bottle, poured twenty units of hyronalin into it, and it became graphically empty, also empty at 30 and 40 units. 50 units the contents became visible again.

Looks like the scaling scheme was changed, but none of the non-Eris states got updated. Hm.
