### ISSUE TITLE
Integrated Circuits Wearable Assemblies INOP - Cannot Install Circuits Into Them

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#10986]
#### Brief description of the bug
Integrated Circuits wearable assemblies (headgear, earpiece, etc) will not accept circuits. They can be opened and you can look into them, but attempting to install a circuit (e.g. a button) has no effect. No error noise or prompt. Just nothing happens.

#### What you expected to happen
To be able to put circuits into wearable assemblies as advertised.

#### What actually happened
A total inability to put circuits into wearable assemblies as advertised.

#### Steps to reproduce
- Print a wearable assembly (gloves, earpiece, headgear, suit, etc)
- Print a button or other circuit of your choice
- Make sure to actually CTRL+SHIFT+CLICK crowbar the assembly open
- Attempt to put the circuit in
- Fail at making whatever gizmo you had in mind

#### Code Revision
- 3366230f57d6ddb71c8dbee416368a0c1d41ad75

**Comment by ktccd0** [comment]
Quick question, did you also use CTRL+SHIFT+CLICK with the button or circuit you wanted to insert?
I think I stumbled around with this as a problem myself, maybe wearable assemblies need that button combo to insert anything?
