### ISSUE TITLE
Bellies are getting "the" appended and introducing grammatical errors

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#10998]
#### Brief description of the bug
bellies get "the" added to their name automatically and this leads to silly phrases

![image](https://user-images.githubusercontent.com/14942479/125120716-c6f75880-e0ea-11eb-9773-7fcae54586a2.png)

#### What you expected to happen
That sentence to not contain "her the"

#### What actually happened
her the stomach

#### Steps to reproduce
- make a belly
- eat a telebeacon

**Comment by MarinaGryphon** [comment]
https://github.com/VOREStation/VOREStation/blob/master/code/game/objects/items/devices/translocator_vr.dm#L412
Should be `[bellychoice.name]` after possessive pronouns to prevent autoinsertion of `\the`, should also use the actual pronoun system or at the very least the `\his` built-in macro.
