### ISSUE TITLE
Polaris Port - Custom Races

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#11]
- [x] Sergals
- [x] Akula
- [x] Neveran
- [x] Fox
- [x] Fennec
- [x] Edit non-custom to be reasonable
- [x] Custom Species character setup field

**Comment by Cameron653** [comment]
Going to write down my own checklist so I can remember what needs to be done next
- [] Define all the spacesuit sprites in rig_pieces 
- [] Define all the spacesuit sprites in void
- [] Define all the spacesuit sprites in suit_storage_unit (Lines 596 and 760)
- [] Define admin spawnable humanoids in human_species (Very low priority.)
- [] Define all the different species parts in sprite_accessories_vr

**Comment by Arokha** [comment]
>  Define admin spawnable humanoids in human_species (Very low priority.)
Did this for you.

**Comment by Cameron653** [comment]
Ah, cheers.

**Comment by Cameron653** [comment]
Done and done
