### ISSUE TITLE
Multiple Atmosia related bugs

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#1101]
Analyzers are completely broken, they don't scan pipes for gas composition.

Fireaxes are permanently wielded, unable to put it back in the case unless holding another object in your hand.

do_after for relocking the fireaxe case is broken. 

You place the fire axe back in the fire axe cabinet.
Resetting circuitry...
You re-enable the locking modules.
(progress bar pops up)
 You re-enable the locking modules.

Tank injectors are complete garbage, setting the imput flow doesn't effect anything, they're limited to ~ 3 L/s

**Comment by SpadesNeil** [comment]
Is this still an issue?
