### ISSUE TITLE
Chococoat - Theodora Lindt - Vorrarkul

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1102]
**Name of Item:** Chococoat, Chocoat or alternatively Getmore Coat if you have no soul.

**Item description:** A long coat designed to resemble Getmore Chocolate Corp's namesake chocolate bar wrapper.

**Sprites (or link to sprites):** Found [here](https://www.dropbox.com/s/6h1ibpcfwpu6nlo/chocoat.dmi?dl=0), item sprite [here](https://www.dropbox.com/s/3k6p7ax62c32yrc/chocoats.dmi?dl=0)
These sprites are all thanks to Kligor.

**Any additional resources:** N/A

**BYOND Key (Username):** vorrarkul

**Name of Character:** Theodora Lindt

**Main Job(s) of Character:** Chef and Bartender. I am considering other potential job roles for her as well.

**Why your character should have this item:** I thought a chocolate wrapper inspired coat for a chocolate girl would be funny, yet fitting. Lorewise, maybe Getmore wanted to improve their advertising and brand recognition?

**Additional Notes (If it's a permit, insert the information for the permit here):** N/A

**Fluff Item slots already used:** Is this even relevant anymore? 0 for this character.

**Comment by joey4298** [comment]
I don't see any reason to deny this in the slightest, and in fact +support this cus I think Getmore needed more attention.

**Comment by DemicusMaximus** [comment]
Thought I'd approved this already, but YES, you're approved. Though I've no idea how to actually do it.
