### ISSUE TITLE
Contractor ID cards break bank accounts

### ISSUE THREAD

**Issue by Detective-Google** [VOREStation/VOREStation#11022]
- spawn with contractor ID card
- place normal ID into contractor card
- put contractor ID in PDA
- realize you are now incapable of buying things with it.

**Comment by Very-Soft** [comment]
Tested this, works for me

I should note, you do also need to use the ID in your hand one time too, not just use your ID on it. It sets some stuff up when you use it in your hand, but after you use the ID in your hand and use your ID on the ID, it behaves normally, in a PDA, or on its own.

**Comment by Arokha** [comment]
Yes, working as intended. You do need to hit it with your 'real' ID, and then also use it in your hand to 'finalize' it, as it were. The bank account copying thing is in the hand-using part (it reads your bank account off your character, not off the other ID).

Suppose you could add a copy for the bank account in the attack by ID part too but it'd be redundant.
