### ISSUE TITLE
You can multiply your soul by entering and exiting your corpse.

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#11040]
#### Brief description of the bug
When entering/exiting a corpse after death, you can create duplicate ghosts of yourself.

#### What you expected to happen
One body, one soul assigned to said body

#### What actually happened
One body, one new soul every time I reinhabit my mouldering corpse

#### Steps to reproduce
- Die A Glorious Death (Successful!)
- Exit your body to spook
- Reenter body to receive new life
- Notice your soul has cloned itself

#### Anything else you may wish to add:
- Occured in Wild West Gateway

**Comment by SigholtStarsong** [comment]
![Shadow Soul Jutsu](https://user-images.githubusercontent.com/16483818/125304979-a1896b00-e2f3-11eb-96c3-e936050183ea.PNG)

**Comment by Arokha** [comment]
Fixed
