### ISSUE TITLE
Colorblindness and Darksight combined may cause lighting bugs

### ISSUE THREAD

**Issue by greed23** [VOREStation/VOREStation#11079]
#### Brief description of the bug
Colorblindness and darkvision appear to break space maps and lighting.

#### What you expected to happen
To be able to see space maps/flashlights in darkened areas

#### What actually happened
Space maps fail to load and lighting (more specifically, Darkness) is busted for only one of my characters, so I don't think it's a client issue.  The space map on ships will open, but the grid will be missing and the only icons visible are the planets, making it impossible to fly safely.  In addition, any area considered EVA that is below the ambient lighting levels (such as indoors in debris field or outside at night) are pitch black only if someone has their flashlight on.  For some reason, if flashlights are off, darksight works just fine.  I have a suspicion that both issues are caused by having both the darksight and Para Vulp colorblindness traits active at once, but the opportunities to test this during normal play are slim.

#### Steps to reproduce
- 1. Go to an EVA area like debris field with both Para Vulp colorblindness and darksight active
- 2. Find interior area and activate flashlight.

**Comment by Arokha** [comment]
It's just colorblindness, darksight is unrelated (but makes it appear worse because once there's actually light *that you can't see* your darksight decreases in power as your 'eyes adjust' and it makes it even darker)
