### ISSUE TITLE
ITV Talon crew don't have access to their suspension field generator

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#11097]
#### Brief description of the bug
Talon crew don't have ID Access to unlock their suspension field generator.

#### What you expected to happen
To use Talon's suspension field generator as a member of the Talon Crew.

#### What actually happened
Access denied.

#### Steps to reproduce
- Be talon
- Grab suspension field generator for xenoarch
- Swipe ID over it to unlock
- Access Denied
- Cry

#### Code Revision
Server revision: B:release D:
Commit: e4c70e74130a39dabdb14a959527eb86b0d9c574

**Comment by Little-119** [comment]
Thank you for the bug report FartMaster69420
