### ISSUE TITLE
Mechs can go unusually fast due to diagonal movement

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#11126]
#### Brief description of the bug
if you diagonally move against a wall in a mech, the mech goes super fast

#### What you expected to happen
mech go normal speed

#### Steps to reproduce
- (Step 1)get mech
- (Step 2)try to walk mech diagonally into wall

#### Code Revision
- B:release D:
Commit: 9e08d712192b536e88ded2ea4c73c420b691d32c

**Comment by Screemonster** [comment]
oh god is it doing the doom thing where you're faster diagonally than in a straight line

**Comment by Arokha** [comment]
Leshana can't reproduce

**Comment by Very-Soft** [comment]
I can't reproduce this either in testing so I'm not sure what the person was doing!
