### ISSUE TITLE
There is no way to mute entertainment montors/they can be heard from offscreen

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#11127]
#### Brief description of the bug
You cannot shut off/mute the entertainment monitor

#### What you expected to happen
Some way to disable the speakers of the monitor or disassemble it

#### What actually happened
You're forced to listen to whatever inane stuff people say.

#### Steps to reproduce
- Exist in the Dark Bar
- Be beyond visual range of the entertainment monitor
- You can hear it, plain as day
- You can't mute it, and attempting to deconstruct it just opens TGUI to look at the cameras available.

#### Anything else you may wish to add:
- In Dark Bar

**Comment by Arokha** [comment]
Not sure how you could hear it beyond sight range, I can see it's set to 7 on the radio that's built in. It was probably your headset that also had the entertainment frequency enabled. You can just turn that off on your headset.
