### ISSUE TITLE
Some toolbelts are phonies

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#11145]
#### Brief description of the bug
Some toolbelts are only observable, but cannot be picked up.

#### What you expected to happen
Find toolbelt, pick it up, wear it.

#### What actually happened
Find toolbelt, cry as it is untouchable.

#### Steps to reproduce
- Go to asteroid tool storage
- Attempt to acquire belt
- Realize you can only examine it

 

#### Anything else you may wish to add:
- Asteroid tool storage. Screenshot of untouchable belts provided.
![Cannottouchbelt](https://user-images.githubusercontent.com/16483818/126198274-7ef17c23-8790-4604-8f52-1dbd87b17a3d.PNG)

**Comment by Arokha** [comment]
Tested on the same shift you reported it on, and I can pick up those toolbelts. Also tested on master on a test server, same.
