### ISSUE TITLE
Teshari clothing sprites missing or not rendered to begin with

### ISSUE THREAD

**Issue by ZeraCyfr** [VOREStation/VOREStation#11143]
#### Brief description of the bug
Multiple Teshari items of clothing have issues with rendering their inventory sprites. In addition to this, Teshari undercoat sprites are missing three of the four angles from their sprites.

#### What you expected to happen
Clothing appears in an inventory/hand/etc as it would facing from the front, and undercoats would have the same four-directional sprite sheet as other items of clothing

#### What actually happened
Multiple items of clothing appear to be empty inventory slots, unless other items are attached to them (in which case they appear to be those attachments, and those attachments only), making them impossible to interact with in many cases and causing problems for inventory management among other things, in addition to the undercoats flat out lacking sprites in the files, rather than simply not accessing/displaying them.

#### Steps to reproduce
Equip any of the following Teshari items (as a note, I have not tested literally every single instance of most of these, but sample sizes seem to indicate I either managed to pick all the broken ones, or it is a trend across a type of item):
 - Hooded cloaks
 - Worksuits
 - Smocks
 - Non-department undercoats
 - Belted cloaks
 - Smallcoats

#### Code Revision
- Command doesn't work on a private server, but it is the build active on GitHub as the master branch and release branch as of 07:45 CST 19 JUL 2021 (at that time the last commit was listed as being 17 hours prior)
 

#### Anything else you may wish to add:
- Extending on prior issue https://github.com/VOREStation/VOREStation/issues/11064
- Missing worksuit inventory sprite 
![image](https://user-images.githubusercontent.com/86967012/126163225-0c2e622f-0665-489a-bfe2-aa9c7225825e.png)
- Missing hooded cloak inventory sprite 
![image](https://user-images.githubusercontent.com/86967012/126163322-00f57a02-b804-4ba5-b90c-e41a47a61f0c.png)
- Missing belted cloak inventory sprite 
![image](https://user-images.githubusercontent.com/86967012/126164661-4ad934a0-5c86-4518-a0b8-4ebad627a9fe.png)
- Missing smallcoat inventory sprite (plus correctly displayed department undercoat inventory sprite) 
![image](https://user-images.githubusercontent.com/86967012/126164982-1cff0782-2e7e-4989-b48c-7931ce8a33b4.png)
- Any outer suit item that has storage with this issue is not able to be removed by its wearer by any means I can determine. Attachments may be used to remove uniforms, but without similar additive sprite overlays, there is no way to retrieve the item, as clicking on the inventory slot simply brings up its internal storage. It must be removed by another player.
- Poking through the sprite files, it seems like the issue with the uniforms may have to do with sprites being missing from item_teshari.dmi, though the suit version of the same file is not missing any of the MIA inventory sprites.
- Missing directional sprites for undercoats in /icons/inventory/uniform/mob_teshari.dmi 
![image](https://user-images.githubusercontent.com/86967012/126163557-899904ac-0d7c-44e3-9e9c-e76fc7d710b1.png)
- I'm not entirely clear on when this particular bug happened, I want to say there was a period early on when I came back from a break on the station where these sprites were present, but I can't remember for sure. I'm going to try and comb through older revisions to check as best as I'm able which revision removed the other directional sprites, since I know at the very least it was between now and the end of October. I'll add in a comment if I do nail down where it went missing.

**Comment by Arokha** [comment]
I figured I broke this with the shuffling of sprites around recently but I went back 2-3 months before that and it looks like Teshari are just missing the vast majority of their uniform icons.

From 950c1541 for example:
![image](https://user-images.githubusercontent.com/15028025/126183428-308e43ba-fa37-4df0-be24-6da51248fc01.png)

Compared to how many on-mob uniforms they have:
![image](https://user-images.githubusercontent.com/15028025/126183563-b6414757-5958-468e-ad4d-bb119455e9df.png)
