### ISSUE TITLE
suits can't cycle if the void suit has a helmet on

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11158]
#### Brief description of the bug
if your voidsuit has a helmet attached you can't cycle it

#### What you expected to happen
to cycle a suit

#### What actually happened
have to remove helet to cycle

#### Steps to reproduce
- (Step 1)put helemt on void suit
- (Step 2)cycle
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Not a bug.

**Comment by TheDavestDave** [comment]
it's.......you used to be able to cycle the whole thing attached at once...recently lots of people keep saying the cycleing is broken. An annocument might be needed

**Comment by Arokha** [comment]
You did, then I rewrote the cycler to make it less awful to code for but in the process removed that feature because it was more difficult to implement, so I removed it. It's intentional, it's not a bug.
