### ISSUE TITLE
Head of personal doesn't have pathfinder access

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11157]
#### Brief description of the bug
hop can't access pathfinder stuff

#### What you expected to happen
the head of exploration to be able to access the pathfinder office

#### What actually happened
access denied

#### Steps to reproduce
- (Step 1)be hop
- (Step 2)go into pathfinder office
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
I think this is intentional? HoP doesn't have all access, they aren't supposed to. Giving yourself all access is a thing HoPs do but it's a crime. I mean, I always did it when I was HoP it's not against the rules or anything, but, yanno.

**Comment by Novacat** [comment]
This is intentional, mostly as a safeguard to stop Heads of Personnel from, you know, potentially trying to do pathfinder stuff. Do note that the switch from Exploration's head from the RD to the HoP happened when we had an endemic issue of research directors playing pathfinder.

**Comment by TheDavestDave** [comment]
seems a bit silly if hop wants to give someone the BSH that is in the locker
