### ISSUE TITLE
No Teshari in-hand/on back sprites

### ISSUE THREAD

**Issue by Raeschen** [VOREStation/VOREStation#11175]
bringing this https://github.com/CHOMPStation2/CHOMPStation2/issues/2514 to here.

Everyone in CHOMP keeps insisting this is an upstream issue but I cannot test it on this server.  does this exist here?

**Comment by Heroman3003** [comment]
The sprites existing is unintended consequence of sometimes wrong holder type (aka differently-functioning Polaris teshari holder) being applied. Generic micro holder never had sprites from the start. Seems like unintentional interaction just got accidentally fixed.

**Comment by Raeschen** [comment]
Odd because they correctly colored depending on the individual teshari being grabbed and everything. It was a feature i really liked. would kinda like it back myself.

**Comment by Heroman3003** [comment]
> 
> 
> Odd because they correctly colored depending on the individual teshari being grabbed and everything. It was a feature i really liked. would kinda like it back myself.

Yes, that is the 'polaris teshari holder code' in question. It also can be equipped in different slots and generally has more specific interactions than generic 'micro holder' vorestation is using universally for all species.

**Comment by Raeschen** [comment]
> > Odd because they correctly colored depending on the individual teshari being grabbed and everything. It was a feature i really liked. would kinda like it back myself.
> 
> Yes, that is the 'polaris teshari holder code' in question. It also can be equipped in different slots and generally has more specific interactions than generic 'micro holder' vorestation is using universally for all species.

So, my point stands. Can the teshari in-hand sprites be returned? To me, loss of them is 'a bug'.

**Comment by Very-Soft** [comment]
I'm a little surprised there isn't a thing on the pickup code that's like 'if teshari, use polaris holder' since they have those special sprites. I have no idea how that all works, but it's a nifty thing and I like it so I would prefer if it was still a thing.

**Comment by Raeschen** [comment]
I should also add, the inhand sprites still show for the teshari plushes, or one variant of them.

**Comment by Raeschen** [comment]
I fixed this downstream myself.
https://github.com/CHOMPStation2/CHOMPStation2/pull/2819
