### ISSUE TITLE
Resleeving Suggestions for Aronai

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#1117]
Suggestions for Sleeving Console Improvements. [Edits by Aronai]

- ~~Very hard to find the right body/mind in the list of names as time goes on.  They're not stacked vertically, nor are they sorted in in any way.   Some sort of alphabetizing would be great.~~ Done

- In the body details, would be nice to have a body snapshot, similar to employee records.

- ~~OOC Notes should probably be displayed on body/mind notes, adding clarification for if a person doesn't mind their body being used for Transplants/Testing/Eating.~~ Done

- ~~The Synthfab has a maximum capacity, of only (Two?) a couple printings.  The growpod does not have a maximum for biomass, and starts with enough for three. Just a minor symmetry complaint.~~ Won't implement, robotics starts with enough to make 3+ given their metal/glass they start with. Also they could literally just grab and disassemble furniture and windows to make more bodies, which is not a luxury medical has.

- ~~Fully Upgraded SynthFab still prints synth shells with flaws and damage.  Not sure if it's intentional.~~ Done

**Comment by Arokha** [comment]
- Alphabetizing: Okay, makes sense. I can do that. I'll probably remove bodies when people cryo too.
- Body snapshot: I ... might ... be able to do this. The code for photos is scary okay.
- OOC notes: Can do that yeah. Probably a good idea.
- Synthfab: Synths are comparitively more rare, and R&D starts with enough materials (not in fab) to print like 10 synths
- Leshana coded the upgrades for resleever, I will have to nag them to do this one. Maybe I can figure it out from the code, but I've never coded upgrades and they are the machines expert.

**Comment by Poojawa** [comment]
make the record call from the datacore like how security records do. 

https://github.com/VOREStation/VOREStation/blob/868413c880ea5e7bb0196551593514c894c13202/code/datums/datacore.dm#L243

Also, perhaps super along down the line, CMO access could open basically the character window and make alterations to the stored body's DNA, swapping species but preserving colors (if possible) like a designer

**Comment by Arokha** [comment]
The designer thing is already planned, just haven't figured out a nice way to do it yet in terms of UI.

**Comment by Arokha** [comment]
Aaaalso the records have their own datacore, they don't use the "crew manifest" datacore. So it has it's own sorting stuff and procs. It just a one line change to make it use /proc/dd_insertObjectList(var/list/L, var/O) which keeps sorts

**Comment by Arokha** [comment]
The 'hard to find' thing is fixed by #1118

**Comment by Arokha** [comment]
Picture thing is too hard right now. We'll have to implement some kinda shenanigans whenever we do Resleeving Pt2 with body customization anyway.
