### ISSUE TITLE
you can use tgui consoles that are depowered

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#11203]
i haven't tested with all of them but i'm pretty sure the engineering ones work and i'm 100% sure the camera ones work
steps to reproduce:
open security camera monitoring console
wait for power to the APC powering the console to run out
notice that so long as the interface remains open, you can still swap through cameras/view stuff even tho the console itself is depowered
![image](https://user-images.githubusercontent.com/20329223/126589764-1130bb09-747b-480c-9398-fecabbc8872b.png)

**Comment by Very-Soft** [comment]
you're a wizard.

**Comment by Arokha** [comment]
It's probably just the camera ones because I was messing with them for the entertainment monitors. I bet it's just those.

**Comment by lm40** [comment]
i remember being able to modify rcon shit with a depowered rcon console on the bridge but i admittedly haven't tested it recently/exhaustively so i may be mistaken
