### ISSUE TITLE
Sending more than one stack of phoron through the cargo shuttle makes only one get counted

### ISSUE THREAD

**Issue by PastelPrinceDan** [VOREStation/VOREStation#11238]
**Brief description of the bug**
I sent out six stacks of phoron in a closed crate for cargo points, and only one of them ended up registering on the cargo console's export history, and was counted for points.

**What you expected to happen**
Usually, all six stacks would have gotten me points back, so I expected 1500 points instead of 250.

**What actually happened**
Only one was counted, so I got 250 points and only one stack showed up on the export history.

**Steps to reproduce**
- Put more than one stack of phoron (in this case, six) in a closed crate.
- Send it on the cargo shuttle.
- Take a look at the cargo console and notice only one was counted.

**Code Revision**
Server revision: B:release D:
Commit: c00a9e035736c519c04a028f1a11cde93cf9f7db 
 

**Anything else you may wish to add:**
I sent out more than one stack of platinum and it worked fine, so it may be a one-time issue, or it may be a phoron issue. Don't know.

**Comment by Heroman3003** [comment]
I cannot seem to replicate this bug.
