### ISSUE TITLE
Weight Gain and Weight Loss set to max does very little.

### ISSUE THREAD

**Issue by SeigaSeiga** [VOREStation/VOREStation#1125]
#### Brief description of the issue
The rate of weight change when the character's weight gain and weight loss values are set to their absolute maximum is so slow as to render the act of setting them to their maximum insignificant. Those with a preference for their character's appearance staying the same over the span of the round's time already have the option to go as low as they like. Those with a preference for changing state within the span of the ~6hr rounds can't go any higher than 100%.

#### What you expected to happen
For setting weight change values to 100 to be significantly different from setting them to 0.

#### What actually happened

Yosh - Today at 10:15 PM
weight += metabolism*(0.01*weight_gain)
(edited)
well
the issue is that uh
if you plug in the values

Yosh - Today at 10:15 PM
weight +=  0.0015*(0.01*100)

Yosh - Today at 10:16 PM
so for you to gain 1lb
it would take...
22 minutes

#### Server revision: release - 2017-03-07
2b0d55d72f3642c602025608c1bf691a25381a36 
 
#### Anything else you may wish to add:
I am both aware that this is something that may not mesh with the design philosophy of keeping things realistic (lol) and a tendency to encourage the RPing of certain elements instead of relying on game mechanics to carry them, and that I have a personal interest in this feature that may influence my opinion greatly, but this is at the point of making the option within character setup moot. Extremes of setting should be extremes of setting.

**Comment by SpadesNeil** [comment]
This is a problem related to the lack of #82

**Comment by SeigaSeiga** [comment]
It is related to it, but I'm making an entirely separate point. Let me be a bit more precise about what I'm talking about, which is sort of feature request more than anything:

* Of all the game systems that currently exist that change the player state and can be used for player gratification, **this is the only one that gates that gratification behind an unreasonably long gate of time**, with justifications of 'realism' that no other system [see: vore, transformation, digestion] is subject to.
* Given the lack of round-to-round stat processing and character persistence, the slow rate does make 100% effectively 0% for those actively keeping an eye on their examine text and character state, despite the theoretical unimplemented framework #82  it's meant to exist in.
* Overall point is that 100% weight gain/loss is not fast enough for those interested in actually seeing it **change within a span of a 6 hour round, or even a 1 hour scene in the case of more extreme tastes**. 

I'm probably terming this in way more words than I need to but ya.

**Comment by SpadesNeil** [comment]
The reason for this is because of how long it takes for nutriment to tick down. That said, it'd be nice if we had options to increase how slowly nutrition--especially excess nutrition--got processed.

**Comment by Screemonster** [comment]
Having metabolism hit a multiplier if nutrition is over 500 would be pretty simple to implement.

**Comment by Arokha** [comment]
Superseded by #1166?

**Comment by SpadesNeil** [comment]
No, because issue #1166 only involves your initial weight. This issue talks about _gaining_ weight during the shift from over-eating which, due to how the nutrition value decreases over time, is too goddamn slow to affect anything.

What I want it to do is if your character has weight gain set to anything higher than 0%, any weight you gained gets saved to the character at the end of the round before reset or when you cryo.

**Comment by SeigaSeiga** [comment]
Closing this issue due to #1333, and also because discussion of the mechanics revealed that speeding up in-round weight gain would cause a lot of balance issues with nutrition and amount of food required to keep a character at a reasonable state of hunger. 

It was a fairly subjective 'issue' to begin with but as the one who opened it I'm personally satisfied with the weight persistence system. It solves the issue of 'eating a lot has no overall effect', by giving it a long-term one. 👍

**Comment by SpadesNeil** [comment]
That works too, then.
