### ISSUE TITLE
Failing to compile.

### ISSUE THREAD

**Issue by IrishWuluf** [VOREStation/VOREStation#11267]
#### Brief description of the bug
When trying to compile the vorestation byond environment file, it comes up with the error code\game\objects\structures\barricades.dm:147:error: expected ':'

#### What you expected to happen
It should compile with zero errors or warnings

#### What actually happened
An error occurred while doing a new compile of the vorestation files downloaded from the github today.

#### Steps to reproduce
1. Download the vorestation zip folder from https://github.com/VOREStation/VOREStation/archive/master.zip
2. Extracted the files from the zip folder
3. Ran the vorestation.dme
4. Selected then ran the compile option in the dream maker
5. error during compile shows up

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
Make sure you are on the beta version of byond if you are not.

**Comment by Arokha** [comment]
Yes, you need 514 or later to compile

**Comment by IrishWuluf** [comment]
Ah, I see. Thank you.
