### ISSUE TITLE
'%countprey' doesn't work properly.

### ISSUE THREAD

**Issue by radiantAurora** [VOREStation/VOREStation#11263]
#### Brief description of the bug
When using %countprey in belly examine text it will display as "[count]prey", e.g. "1prey". %count is likely taking priority.

#### What you expected to happen
Not the above.

#### What actually happened
Above

#### Steps to reproduce
- use %countprey in any vore-panel examine text.
- Examine yourself with that belly filled.
- ???
- Profit

#### Code Revision
Unknown, found on a downstream (the downstream has not changed the examine code).

**Comment by Arokha** [comment]
Your assumption appears to be correct
