### ISSUE TITLE
Flying the ITV Talon through asteroid fields lags the server

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#11268]
#### Brief description of the bug
The server tends to lag when the Talon flies through an asteroid field.

#### What you expected to happen
To 'mine' asteroids using the point defense/shields.

#### What actually happened
Everything works, it just lags the server to an absurd amount until the Talon leaves the asteroid field.

#### Steps to reproduce
- Bring Talon shields up
- Enter an asteroid field
- Watch in awe as the server stutters to a crawl
- Leave the asteroid field and everything returns to normal

**Comment by Very-Soft** [comment]
I should note, I reported this here: https://github.com/VOREStation/VOREStation/issues/10742

There is some more insight into it there.

**Comment by FartMaster69420** [comment]
Ah, somehow missed it.
