### ISSUE TITLE
Grabs are wonky/laggy

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#1127]
#### Brief description of the issue
Grabs are lethargic on updating states, hugging someone while buckled will give you a message saying that you have to unbuckle yourself to pick yourself up and the hugging message.

You can yo-yo throw people if you're quick enough with clicking various means.

Unbuckling yourself to grab someone has a noticeable delay in being able to actually grab anyone unless you switch hands first. 

#### Anything else you may wish to add:

Probably has something to do with the grab hook for vore code, it's either placed weirdly, or is being called before any other checks and not letting grab qdel/update properly.

**Comment by SpadesNeil** [comment]
Still an issue?
