### ISSUE TITLE
Using a newspaper on nonhostile mobs should make them spit out prey

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1130]
#### Brief description of the issue
No.. no! Runtime! BAD! GET BACK HERE! That's a patient!

*WHAP*

Right, now, OUT.

#### What you want to happen
Whapping pets with a newspaper should "encourage" them to spit out anyone they've ate.

#### What actually happened
It doesn't.

**Comment by SpadesNeil** [comment]
That's fucking hilarious.

**Comment by ArbyTheDragon** [comment]
I feel as though there are several items that should do this. A space cleaner bottle should work too.

**Comment by Very-Soft** [comment]
Yes please! XD

**Comment by Arokha** [comment]
Made a little harder by the fact that Runtime and Renault /are/ hostile mobs.
