### ISSUE TITLE
Giant Spider Queens can't climb ladders

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#11308]
#### Brief description of the bug
Giant spider queens cannot climb ladders.

#### What you expected to happen
To climb as a spider

#### What actually happened
Spider can't climb

#### Steps to reproduce
- Find a ladder
- Attempt to climb it by clicking
- Attempt to climb it by move up/down verb
- Go nowhere

#### Code Revision
Server revision: B:release D:
Commit: d241b09bc4e1991f7e3bbccf36058f72e46f4162 
 

#### Anything else you may wish to add:
This can be really bad as some rooms, such as the fight club in maintenance, can be fallen into from above but only allow exit through a ladder. This effectively jails the spider queen and possibly other mobs, I haven't tested.

**Comment by Heroman3003** [comment]
This applies to all simplemobs, not just spider queens, to note.

**Comment by FartMaster69420** [comment]
That's what I thought, only encountered it as the queen personally.
