### ISSUE TITLE
Previous Vox Whitelist - HawkerTheGreat

### ISSUE THREAD

**Issue by HawkerTheGreat** [VOREStation/VOREStation#1132]
#### Brief description of the issue
I applied for vox a few years ago between the time of the port update and the Vox removal - I just noticed they were put back in and was curious if I could have consideration for re-add to the whitelist as my post was previously accepted. 

Thanks, - Its linked here - http://forum.vore-station.net/viewtopic.php?f=46&t=317

#### Code Revision
Release - 2017-03-07
2b0d55d72f3642c602025608c1bf691a25381a36 
 
#### Anything else you may wish to add:
-> Asked Admins on discord - I was pointed to add an issue on github by Scree.

**Comment by Screemonster** [comment]
Gonna just add that label since the app was approved last time and I see no reason not to grandfather this in.
