### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by Fluffy74** [VOREStation/VOREStation#11339]
#### Brief description of the bug
Broken recipes I recently found
char sui meat bun - resulted in cooked cutlet and slice of dough unharmed, seems like the recipe is conflicting with raw cutlet -> cutlet recipe
custard bun - seemingly failed (burned mess) right after. It worked fine before, but was weeks ago at least
Chocolate bars fail to properly mix, if you use normal milk - chocolate milk happens first. Soy milk works fine

Also! Recipes like Omelette rice and Astro-pudding should NOT contain 5u of Salt. I see someone simply copied the amount from Sugar, but max amount of salt used in recipes before was Zesty fish - 3u of Salt. Please fix to proper 1u of salt

**Comment by GhostActual** [comment]
I don't know about the chocolate bar, couldn't find the recipe, however
custard bun worked - tested on live server
char sui bun worked - tested on live server
and I can easily change the salt

If you can, please find the recipe for the Chocolate Bar and I will see about fixing that as well

**Comment by GhostActual** [comment]
Astro-pudding has 5u of salt to make it angry - it's a play on "you're just salty" but I did fix the salt content in the Omelette Rice
