### ISSUE TITLE
Request of reverting Vox mechanics.

### ISSUE THREAD

**Issue by MisterGrimm** [VOREStation/VOREStation#1133]
#### Brief description of the issue
Vox breath plasma/phoron now, instead of their lore based canon, nitrogen.

#### What you expected to happen
Vox to die a toxic and painful death due to phoron's and oxygen's toxicity to their species.

#### What actually happened
Vox breath phoron like candy and die due to breathing nitrogen, despite nitrogen being their canon gas for respiration.

#### Steps to reproduce
- (Step 1) Put mask on
- (Step 2) Turn on internals valve
- (Step 3) Watch as phoron doesn't kill you

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
A few months ago there was a polaris merge with our server, and among that merge was the change where Vox now breath phoron, and not nitrogen. This goes directly against their lore, and it makes certain parts of their play-style much harder to replicate. A example would be their living space, because due to them now breathing phoron they would have to fill their living space/residental room with phoron. Not only would this be a gigantic safety hazard, but it would also be un-needingly expensive for NT and their generalized budget. Nitrogen however, is one of the most common gasses known to humanity, and is extremely simple to contain in a room.
My general point is that having Vox breath phoron is not only a bad idea on a lore stand-point, but also on a mechanic standpoint. My suggestion is to revert Vox to their original mechanics, which would be breathing nitrogen, and having oxygen be poisonous to them.

**Comment by BlackjackFajah** [comment]
Pesonally I didn't even realize this was a thing until it was brought up. Mainly cause I don't play Vox at all. And well the whole fact of filling a room with fucking phoron/plasma.. That's costing in the high 100-900k range for credits/Thaler Its kinda retarded lore wise and mechanic wise.. But what do I know. I'm just Blackjack and this is my opinion.

**Comment by Arokha** [comment]
I'll point out that this is a decision the host made. A coder had changed it to nitrogen-breathing, and the host requested that it be changed back. Also keep in mind that in our lore, they do breathe phoron, so I'm not sure what lore you're referring to when you say "their lore based canon". If you mean other servers, that's largely irrelevant. Our canon diverges largely from other server lore in many places.

Nitrogen does not poison them, either.
```
	breath_type = "phoron"
	poison_type = "oxygen"
```

In terms of how expensive it is, I'm not sure about the cost of phoron, I saw someone speaking about it earlier in the Discord, I'm not sure where that is in the lore, but the station starts with a gargantuan amount of phoron in atmos at the start, so in terms of it being in short supply, I'm not sure that's the case.

https://wiki.vore-station.net/Vox

**Comment by SpadesNeil** [comment]
I am not interested in changing it back to nitrogen either. I'm doubtful the price of phoron is nearly as much as it's being made out to be--especially when we live on a rock full of the stuff. We have phoron coming out of our ears.

**Comment by Screemonster** [comment]
The way I see it, the toxicity comes from the reaction of phoron _with_ oxygen.

Most species are fuckin' jam packed full of oxygen, it's in every part of their biochemistry, so if you put them in a phoron environment it gets into their bloodstream and fucks with their biological processes and BAD JUJU ensues.

You know another chemical that kills you because it reacts more strongly with things in your biochemistry than the biochemistry itself? CYANIDE. (in this case, CN bonds very strongly with iron by stealing it out of your hemoglobin and defeating your body's ability to transport oxygen)

Vox, on the other hand, have phoron-based biochemistry, so they're fine breathing the stuff - until oxygen gets in, reacts with their phoron, and once again BAD JUJU ensues.

**Comment by Arokha** [comment]
To be completely honest, the existing Vox whitelisted players want it to stay Phoron, and they're sort of an important voice when it comes to this considering they applied and had approved the whitelist status for themselves, and we'd be changing how the thing they applied for and had approved works, after the fact.

**Comment by Poojawa** [comment]
https://github.com/PolarisSS13/Polaris/issues/3090 also, since this topic keeps getting linked.
