### ISSUE TITLE
Internal Bleeding Not Being Shown in Scanner

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1134]
#### Steps to reproduce
- (Step 1) Get internal bleeding
- (Step 2) Get a scan report, because that's the only way doctors will see it.

#### Code Revision
- Server revision: release - 2017-03-07
2b0d55d72f3642c602025608c1bf691a25381a36 
 
#### Anything else you may wish to add:
- The patient DOES have internal bleeding, you can watch their blood volume drop and it's plainly shown on printed reports. But on the Scanner's UI itself, nothing. It might be worth looking into other injuries to see if there are any similar issues with those as well... Infections, fractures, implants, necrosis, etc, just to see if the scanner has trouble displaying it.

**Comment by Arokha** [comment]
The code makes it look like this should work.

```
				<div class="itemContentNarrow">
					{{if !value.status.bleeding}}
						{{if !value.status.internalBleeding}}
							No Injuries Detected
						{{else}}
							<span class="bad">Internal Bleeding Detected</span>
						{{/if}}
					{{else}}
						{{if value.status.internalBleeding}}
							<div class='notice'>Internal Bleeding Detected. External Bleeding Detected.</div>
						{{else}}
							<span class="average">External Bleeding Detected</span>
						{{/if}}
					{{/if}}
				</div>
```
