### ISSUE TITLE
Cant mix certain drinks that require wine

### ISSUE THREAD

**Issue by EtheoBoxxman** [VOREStation/VOREStation#11354]
#### Brief description of the bug
Drink recipes that need wine dont work.

#### What you expected to happen
To be able to make drink recipes that require wine.

#### What actually happened

Nothing. 

#### Steps to reproduce
Literally try to make any drink that uses wine.
'Wine' doesnt exist, so I try to use red wine.
The recipes that take wine were not updated to take neither red or white wine.
Thus, broken.

#### Anything else you may wish to add:
- I double checked to make sure Im not a smoothbrain. The drinks that take wine only define 'wine', which I read doesnt exist anymore as a reagent.
- code/modules/reagents/reactions/instant/drinks_vr.dm is the location I checked.

**Comment by Arokha** [comment]
Fixed on master, will be fixed on server next update
