### ISSUE TITLE
Booze-o-Matic is not a solid object

### ISSUE THREAD

**Issue by GhostActual** [VOREStation/VOREStation#11351]
Can walk through the Booze-o-matic

Not be able to walk through a vendor like a ghost

Walked through the vendor like a ghost

#### Steps to reproduce
- Walk onto vendor
- Say boo
- People scream

**Comment by Very-Soft** [comment]
SPOOKY!!!?!!!!!!!!!!!!!!!!!!!!

Should be as simple as flipping its density var to 1 I imagine

**Comment by GhostActual** [comment]
> SPOOKY!!!?!!!!!!!!!!!!!!!!!!!!
> 
> Should be as simple as flipping its density var to 1 I imagine

Turns out it was isolated to the Talon and it was because there was no wall piece there, I have fixed it (I think), forgot to close this
