### ISSUE TITLE
AliCo Grab-A-Gift claw machines don't work.

### ISSUE THREAD

**Issue by PastelPrinceDan** [VOREStation/VOREStation#11361]
#### Brief description of the bug
AliCo Grab-A-Gift claw machines' interface just doesn't work. Shows a text that says 'Interface main was not found'.

#### What you expected to happen
I've never used the machine actually, so no idea. But I expected something other than an error.

#### What actually happened
Didn't work, 'interface main was not found' appeared.

#### Steps to reproduce
- Grab the grab-a-gift board from tech storage.
- Build as you would any other arcade machine (computer frame > wrench > board > screwdriver > cable > glass > screwdriver).
- Machine's done, click on it.
- Be greeted by error:
![unknown (2)](https://user-images.githubusercontent.com/75939194/128589568-5a26d032-1453-4e61-a40b-1951c28deb77.png)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: 92ff9332ea1a0605dcffaea8e2630948ae9373c6

#### Anything else you may wish to add:
- This board isn't printable by science, only available in tech storage. Might be because it wasn't actually finished, might be an error there too, don't know. Just thought it'd be good to mention as well.

**Comment by GhostActual** [comment]
The interface has never worked to my knowledge - a TGUI file was never created for the UI so it doesn't have anything to port too. The new Casino Port has a replacement that is based on the Goonstation concept of a claw machine.

**Comment by izac112** [comment]
I forgot to up-port a fix for this to vore from yawn, when we updated our codebase from here, we wanted to add the claw machine to our map then I noticed that the ui_key was set to "main" instead of "ClawMachine" on line 1247 in arcade.dm it worked fine after I changed it the tgui file is present.

**Comment by GhostActual** [comment]
With the merge I will open a separate PR that will remove the board from tech storage
