### ISSUE TITLE
Produce persistency still doesn't work

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#11380]
#### Brief description of the bug
The smart produce storage that was moved between hydroponics and the kitchen that had the persistency attached to it doesn't persist anything.

#### What you expected to happen
Produce I stuffed into the fridge to stay in there to persist into the next round to a degree

#### What actually happened
Unfortunately, this Smart Produce Storage is empty.

#### Steps to reproduce
- Plant any kind of fruit or vegetable anywhere where you can in hydroponics
- Place fruit or vegetable that you harvest into the smart produce storage
- Wait until next round
- There should have been fruit here but aren't

#### Code Revision
- 485c11bb102514bfa499677801e88a52ee84e238 
 

#### Anything else you may wish to add:
- I don't know anymore man. Maybe it was the wrong fridge to begin with that I wanted to move from the hydroponics backroom there? There's 3 fridges from what I can see, two with persistent in the name. Might just be that persistent_lossy is the wrong one and the persistent one actually does things.

**Comment by Arokha** [comment]
Is this at least one shift after the move? Moving the machine deletes the persistence that was there until you store more things.

**Comment by Huenererschrecker** [comment]
It was the shift prior to the current one where I loaded the fridge up with enough produce that multiple fruits would be at 50. The current shift started with an empty fridge. I _think_ it's a shift after the move but I can't be sure.

**Comment by Huenererschrecker** [comment]
I tested it again today. https://i.gyazo.com/908eb3c1c592f54279a6fdf35626cb8f.png
That's the load I made. The fridge didn't save any of it. So it's not a case of the code needing one shift to start working and it's indeed a case of the code not working period.
