### ISSUE TITLE
Some areas not connected to the powernet on round start.

### ISSUE THREAD

**Issue by EtheoBoxxman** [VOREStation/VOREStation#11386]
#### Brief description of the bug
It appears surface civilian has a ton of areas not connected to the grid right now. I took a screenshot of the areas after fixing it in game when I found the issue.
Given that I noticed some invisible wires, I think this is a mapping issue.

#### What you expected to happen
The entire surface 1 civilian grid to be linked to the power net.

#### What actually happened
A large portion of the east, southeast, and south portions of surface 1, as well as some areas of surface 2 were not connected to the power net.

#### Steps to reproduce
Just set up power to the station. Whereas everything is linked to the power net, the areas that arent charging arent even on powergrid sensors, an easy tell that they just arent wired to the net at all.

#### Anything else you may wish to add:
Putting a screenshot which shows the areas not on the powernet, after I manually connected them.
![image](https://user-images.githubusercontent.com/10347412/128870942-6aff58c2-2988-43bd-8fd6-e249dded3590.png)

**Comment by Arokha** [comment]
https://github.com/VOREStation/VOREStation/pull/11379 probably related and fixed by
