### ISSUE TITLE
pAI nomming bug

### ISSUE THREAD

**Issue by Kittygorluwu** [VOREStation/VOREStation#11393]
#### Bug
If a pAI eats a crewmember and then has their mobile chassis destroyed, the crewmember's body is not left as the pAI gets totally destroyed

#### What was expected
I don't know what normally happens, but I'd expect something would be left to be recovered.

#### Context
I was out on a scavenging mission with Numara, a member of the Talon crew, when we got attacked by creatures. She got knocked down and surrounded, so I unfolded and tried to rescue her by eating her. I managed to get her into my stomach, but I was destroyed by the creatures before I could escape to the shuttle. No body was left, and unfortunately she didn't have a backup scan.

#### Steps to reproduce
- Eat crewmember as pAI
- Get destroyed

**Comment by KeenShayne** [comment]
PR #11458 fixes this. Thanks for the report!
