### ISSUE TITLE
ITV Salamander Overmap Ship - Cannot Jump To Open Space

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#11394]
#### Brief description of the bug
Salamander-class ships cannot short-jump from a 'docked' location to open space so it can fly on the Overmap.

#### What you expected to happen
The ship to be able to land/dock and take-off/undock like every other shuttle and ship.

#### What actually happened
The Salamander cannot short-jump to Open Space. Testing with Move A Shuttle admin magic revealed that jumping the ship to itself ( ship_Salamander ) puts it in the proper location for Overmap flight.

#### Steps to reproduce
- Spawn a Salamander class overmap ship with "Map template - New Z"
- Run test jump to enable overmap flight
- Short jump to anywhere (V3b, Talon, V2, Fuel Depot, etc)
- Attempt to short jump back to open space and resume flight
- Fail

#### Code Revision
Server revision: B:release D:
Commit: 485c11bb102514bfa499677801e88a52ee84e238

**Comment by KillianKirilenko** [comment]
Investigating now. Did you use the `OM Ship - Salamander Corvette` or the `Special Area - Salamander Trader`? Former seems to work okay.
