### ISSUE TITLE
Talon Sheet Storage doesn't Persist

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#11436]
#### Brief description of the bug
The Smart Sheet Storage on the ITV Talon doesn't save it's contents between rounds like the station does.

#### What you expected to happen
For materials to persist between rounds when stored in the sheet storage.

#### What actually happened
Sheet Storage will be empty at the start of the round, regardless of how many sheets you put in the round before.

#### Steps to reproduce
- Load sheet storage on the Talon
- Rejoin next round
- Materials are gone, that's some bull-sheet.

**Comment by GhostActual** [comment]
If I remember correctly this was purposeful to make the Talon reliant on the station and promote trading. Need a maintainer to confirm.

**Comment by Very-Soft** [comment]
It's supposed to persist I think. The talon doesn't have any real use for most of the materials, so, similar to mining, the fridge is essentially there to make sure that, hard work done late in the shift isn't totally worthless.
