### ISSUE TITLE
Leaving the round when dead does not prevent resleeving

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#11484]
#### Brief description of the bug
If you die and leave the round you can still be pulled back into the round by getting resleeved. 

#### What you expected to happen
I hit leave the round and stay out of the round for now, leaving me on the titel menu to do whatever. 

#### What actually happened
The resleeving happened anyways, despite not being in the round anymore.

#### Steps to reproduce
- Spawn
- Implant yourself with a backup
- Die
- Leave round
- Wait for someone to work the resleever, pulling you back in

#### Code Revision
- d7d38e5b85c2c428f0d10298119e68920bc39a63 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/4cad748f6c5fc05503213cc950fd36c6.png

**Comment by Arokha** [comment]
What buttons did you hit to leave the round, exactly?

**Comment by Huenererschrecker** [comment]
https://i.gyazo.com/a5981e5bf8a30c15b1be71c3a331c4c1.png This one. I am aware that there is a 'Quit This Round' verb but after some back and forth in dev general it seems that they are the same button. I can't prove it either way tho.

**Comment by KeenShayne** [comment]
It seems that "Return to menu" just doesn't make you DNR even though it says "Returning to the menu will prevent your character from being revived in-round. Are you sure?". Should probably either make people run the "Quit this round" command before allowing them to go back to lobby or just do it when going back to lobby as well.

**Comment by Arokha** [comment]
No, they are not the same button and are not related.

**Comment by Huenererschrecker** [comment]
Well yeah, I honestly through that 'Quit This Round' and 'Return to Menu' are the same commands, because it just makes sense. So honestly, removing 'Return to Menu' and putting in 'Quit This Round' Into the button on screen should just fix this?
