### ISSUE TITLE
Weirdness with teshari and biofuel processor

### ISSUE THREAD

**Issue by radiantAurora** [VOREStation/VOREStation#11549]
#### Brief description of the bug
As a synthetic teshari with an cybernetic/assisted-interface brain (MMI) attempting to take the neutral biofuel processor trait declares you must be synthetic. This does NOT happen with positronic or drone brain synthetic teshari and, from brief testing, appears wholly unique to teshari.

#### What you expected to happen
To be able to take biofuel processor on any synthetic character.

#### What actually happened
One very specific type of synthetic character can't do this.

#### Steps to reproduce
- Setup a FBP teshari in character setup
- Ensure your brain type is cybernetic/assisted interface (seriously why are there like 3 names for this type of brain?)
- Try to put biofuel processor on in traits

#### Code Revision
4c0929aaeb6efb7bd30082ec6a8a9f1348095976

**Comment by wanderingshiba** [comment]
I have had this same issue when trying to take the trait as a FBP human, and changing brain type didn't solve it either.
The trait will either complain that I'm not synthetic, or it just plain disappears after saving and reloading the slot.

**Comment by KasparoVy** [comment]
@radiantAurora "Ensure your brain type is cybernetic/assisted interface (seriously why are there like 3 names for this type of brain?)"
It's fluff!

Assisted brain is MMI'd organic brain in the synth body
Cybernetic is Posibrain and I think there's a third representing drone-chip intelligence.

**Comment by radiantAurora** [comment]
> @radiantAurora "Ensure your brain type is cybernetic/assisted interface (seriously why are there like 3 names for this type of brain?)"
> It's fluff!
> 
> Assisted brain is MMI'd organic brain in the synth body
> Cybernetic is Posibrain and I think there's a third representing drone-chip intelligence.

Nope. Cybernetic and assisted-interface both refer to an MMI type brain, both of which are used within character setup whilst in-game MMI is used.
