### ISSUE TITLE
New Tajaran hairs do not display on character

### ISSUE THREAD

**Issue by wanderingshiba** [VOREStation/VOREStation#11547]
#### Brief description of the bug
The new hairstyles that were recently added for the Tajaran race/icon set do not display properly. They appear in the hair selection screen, but the actual sprites don't. I assume they were added in this PR: #11496 

(Semi-unrelated, however this same issue occured when other general hairstyles were ported over many months ago. That was fixed back then, but this seems to be caused by something similar.)

#### What you expected to happen
I expected to see a new hairstyle on my Tajaran character.

#### What actually happened
Instead of the new hair being shown upon selection, it displays an error sprite.

#### Steps to reproduce
- Go into character creation as a Tajaran.
- Select any of the new hairstyles (for example Tajaran Bun, Tajaran Shoulder Length, etc).
- (Optional): Cry because you received an error sprite instead of the hair sprite. :(

#### Code Revision
- Server revision: B:release D:
Commit: 4c0929aaeb6efb7bd30082ec6a8a9f1348095976 
 

#### Anything else you may wish to add:
- Character after applying one of the affected hairstyles:
![help](https://user-images.githubusercontent.com/58328860/131724257-968ab79c-6491-4169-848b-799eb090ceaf.PNG)

**Comment by Arokha** [comment]
Fixed
