### ISSUE TITLE
Loading synth character causes previously loaded character to lose neural hypersensitivity trait

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#11551]
#### Brief description of the bug
Swapping from an organic character slot that has the neural hypersensitivity trait to a synthetic character & then swapping back, even without changing anything on either, will remove the hypersensitivity trait, potentially leaving someone unable to join until they re-add it.

#### What you expected to happen
To be able to swap between the slots without having to futz with traits each time.

#### What actually happened
In this particular instance, I swapped to update flavourtexts on the synthetic, swapped back to the character I wished to play and was informed that they were unable to be spawned until issues with them were fixed, leading to me finding out about this bug.

#### Steps to reproduce
- Make/have character with the neural hypersensitivity trait
- Make/have a FBP/synthetic character
- Swap from chara 1 to 2 then back again without changing anything
- Watch as the trait is now gone from character 1

#### Code Revision
- Server revision: B:release D:
Commit: 4c0929aaeb6efb7bd30082ec6a8a9f1348095976

**Comment by KillianKirilenko** [comment]
Hearing similar issues with cold adaptation/etc. getting stripped off by slot switches. I think it's because the character in the preview/editor is basically the same one rather than being created/deleted, or something like that.

Probably just needs some tweaks for order of operations with saving/loading of traits.
