### ISSUE TITLE
Mapping units & their beacons missing from exploration rewards vendor

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#11580]
#### Brief description of the bug
After code-diving to look into mapping units, I found out that they're listed as a reward in the survey_vendor.dm file, but don't actually load. Looked further into it and noticed that there are _several_ items which aren't included in the mapload initialization and as such, are unavailable.

#### What you expected to happen
To be able to buy mapping units & their beacons as advertised in  #10382

#### What actually happened
Nothing, the vendor displays a list that _doesn't_ include those items, they're unavailable because they aren't included in the list of things to offer from the vendor once it's been loaded in.

#### Steps to reproduce
- Check #10382
- Check the explo vendor in game and notice the lack of mapping units.

#### Code Revision
Server revision: B:release D:
Commit: 4c0929aaeb6efb7bd30082ec6a8a9f1348095976

**Comment by Heroman3003** [comment]
It appears its caused by the fact that list in question is actually completely irrelevant and list actually used is defined lower down, in Initialization of the vendor, and the mapping supplies were NOT added to those lists.
