### ISSUE TITLE
Catslugs lose sign language comprehension when held or worn by others.

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#11595]
#### Brief description of the bug
Catslugs can't comprehend sign language messages from other beings when held or worn by someone.

#### What you expected to happen
For the fluffy lil' noodles to still be able to process what people might be signing at them whilst lounging around someones neck

#### What actually happened
Instead, when others tried to communicate via sign language whilst I was held, I got the "X gestures something" message.

#### Steps to reproduce
Become catslug
Find someone to pick you up, or clamber up onto them
Be spoken to in sign language by someone else
Understand none of what they say

#### Code Revision
Server revision: B:release D:
Commit: 4c0929aaeb6efb7bd30082ec6a8a9f1348095976 
 

#### Anything else you may wish to add:
I spoke briefly with Soft about this in dchat, they mentioned this is more an issue about not being able to "see" in holders & how sign language works than an outright issue with 'slugs in general.

**Comment by FartMaster69420** [comment]
This is also a problem with Promethean biolinguistics.
