### ISSUE TITLE
Drop nomming immediately digested all of my equipment but left me safe.

### ISSUE THREAD

**Issue by JohnWayne9392** [VOREStation/VOREStation#11638]
Drop nomming with 'hold' set for the belly digested all of my equipment but left me safe.

I expect drop nomming to retain the settings of the belly and not immediately digest all of my stuff even though it's all on my body.

My friend and I were trying to practice drop nomming and where for them to stand so things work out. I get in the right position and they drop on to me and it worked, I got vored. However, their belly is set to Hold and all of my equipment gets 'slimy', 'gross', 'grimy', etc. My ID got busted on top of it too.

1. Set up a drop nom with your pred.
2, Have their belly set to 'hold'.
3. Have them drop onto you.
4. See if anything happened.\
5. I had a broken leg beforehand and had to enable spontaneous pred, but that seems like it wouldn't matter.

**Comment by Heroman3003** [comment]
It would seem your friend's got had "Affect Worn Items" mode addon enabled, which works exactly as intended, it makes contamination and item mode affect items currently worn by prey as if they were dropped in the belly.

**Comment by Screemonster** [comment]
Yeah, "hold" only affects what it does to people (ie do you do damage to mobs or not) while all the other stuff like stripping, item-digesting and so on are a separate setting.
