### ISSUE TITLE
Throwing a flashbang in space causes items to disappear

### ISSUE THREAD

**Issue by JohnWayne9392** [VOREStation/VOREStation#11637]
Throwing a flashbang in space causes items in the hand you threw it in to disappear

I expected to throw an item in the direction of where I was going in space to help me speed up.

I was a security officer needing to go on EVA duty due to a bunch of carp appearing around the station in space. I ended up going out of bounds and drifting off into space. I was floating around in space for what seemed like several z levels and decided to turn off my jetpack to throw a flashbang. I throw it and don't witness the explosion, yet I notice I'm not moving. I throw other items to get me moving again, and all that happens is I 'drop' the items below me. I put the items away. I check my jetpack to see how much CO2 I have left, and then grab my ID before putting it back in the proper slot. Eventually, I notice the items I 'threw' are gone, as well as the items I grabbed. I still had my jetpack sprite on my character.

1. Go to the border of the Station Z-level.
2. Fly around with a jetpack and EVA equipment.
3. Turn off Jetpack
4. Throw flashbang
5. Try to throw any other item with the same hand.
6. Gather those items and put them on a Sec Belt
7. Check your Jetpack for air
8. Grab your Id and put it back in the Id slot
9. See if the items still exist.

**Comment by lm40** [comment]
i suspect this is related to throwing changers and would  proooobably be fixed by #11649 although i haven't tested a case this specific
