### ISSUE TITLE
Fluff Item - Advanced Medical Scanner HUD

### ISSUE THREAD

**Issue by Stulti4** [VOREStation/VOREStation#1165]
Name of item: Advanced Medical Scanner HUD

Item description: A heads-up display that scans the humans in view and provides accurate data about their health status. Upgraded to the capabilities of the AR-M glasses!

Sprites (or link to sprites): Medical Scanner HUD

Any additional resources: (in a .zip or .7z file, including sounds and DM files with code in them): None

BYOND Key (Username): Stulti

Name of Character: Kris Wilhelm

Main Job(s) of Character: Medical Officer (Surgeon), Chief Medical Officer

Why your character should have this item: Dr. Wilhelm, though highly appreciative of the capabilities of the new AR-M glasses designed by Kitsuhana Heavy Industries, prefers the look of the standard issued Medical Scanner HUD. She'll tolerate using the AR-M Glasses, as they're obviously better for the job, but is hoping to find some market out there that's found a way to cram the AR-M's Crew Monitor System into a Medical Scanner HUD.

Additional Notes (If it's a permit, insert the information for the permit here: N/A

Fluff Item slots already used: 0

**Comment by Arokha** [comment]
So basically you like the look of the MedHUD sprite and want it to do the things the AR-M glasses do?

**Comment by Stulti4** [comment]
Yes. Single-Eye, just normal like how the MedHUD is (unless you want any minor changes to it's sprite to differentiate it. I don't mind either way).

**Comment by Arokha** [comment]
That'd be easy to do. Some headmin will have to review first, though.

**Comment by JoanRisu** [comment]
Is fine with me

**Comment by SpadesNeil** [comment]
Closing this for now. Fluff items should be applied for on the forum prior to requesting on Github they be added. Re-open this once your app is approved.
