### ISSUE TITLE
Proteans Plagued with Promethean Punishment - Punishment Proves to Perform Principally Poor 

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#11668]
#### Brief description of the bug
The gods of 2321 are often fickle and cruel. They, in their unknowable disapproval of the souls that take up the nanite form, have judged these people guilty of some celestial crime. Every day their NIF integrity begins at a mere 30%, left to the challenges of software installs, program use, and natural wear and tear. At the end of every day, this haggard piece of equipment is regenerated to 30% once again so the cycle of punishment may continue indefinitely. Clearly these gods saw what happened to Prometheus and thought it was metal as fuck.

#### What you expected to happen
I don't really know what I expect to happen when it comes to Proteans and NIF integrity, it makes a whole lot of sense that theirs would be effectively indestructible since it's such a key component of their function anyways. It regenerating every shift is a pretty obvious solution to implement that.

#### What actually happened
The NIF always defaults to 30% integrity at the start of the shift. I'm not sure if this is intended or not, but it looks kinda funny. 

It's not really an issue since you have to install like 5+ NIFSofts to push it very low anyways and you're not gonna ever do more than that in a given shift.

#### Steps to reproduce
- Be a Protean
- Consequently have a NIF automagically installed (because it's key to your body working)
- Suffer NIF degradation normally via NIFSofts or whatever other means
- Finish a round
- Upon starting a new round, NIF integrity always resets to 30%
- Can be repaired above 30%, and will fall below 30% by installing NIFSofts
- Isn't really a big deal, but it's kinda unusual

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)

**Comment by Heroman3003** [comment]
Iirc that is intentional behaviour, as in a way Proteans are basically a macroscopic sapient NIF. They get one with low durability as a constant, although if durability is to change to actually be 30 that would be very messy since HUD portrays it in %, while costs of integrety are in whole numbers, so it'd just look messy with non-multiple of 10.
