### ISSUE TITLE
Switch "Body Weight" button in preferences to "BMI" because that makes more sense

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1166]
#### Brief description of the issue
People incorrectly set their body weight despite the very specific directions I give them, and end up sooperfat or anorexic. This can be fixed by changing the mechanic's name to BMI.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/9feec8e4ed92bfb2f7827841ae62a404a5c0347c
 
#### Anything else you may wish to add:
- Too much math for me. I'm lazy.

**Comment by Rykka-Stormheart** [comment]
Is this still something you'd like done? Should be a simple nametweak under the VORE preferences tab, I can do that.

**Comment by SpadesNeil** [comment]
It's a name tweak _and_ a change of a lot of math.
