### ISSUE TITLE
non-standard types of glass only fit in the smart sheet storage whenever they want to

### ISSUE THREAD

**Issue by PastelPrinceDan** [VOREStation/VOREStation#11676]
#### Brief description of the bug
Putting borosilicate glass, plastitanium glass or titanium glass in the mats fridge only seems to work once in a blue moon. I have no idea why the fuck it works somedays, then doesn't on others. I'm annoyed.

#### What you expected to happen
For glass types other than regular glass to go in the fridge.

#### What actually happened
While it told me I put the material in the fridge ("You add the titanium glass sheets to the Smart Sheet Storage.") , it actually dropped it back onto my tile, leaving a whole 0 of it in the fridge.

#### Steps to reproduce
- Make borosil, tiglass or plastiglass.
- Try to put it in the Smart Sheet Storage.
- Either be happy because hey! It fit for once! Or weep because you made stacks of it for nothing.

#### Code Revision
Server revision: B:release D:
Commit: 0ed7cd3098f11ce0e6b81bb9a6197b7b14dd960b

**Comment by Heroman3003** [comment]
Can't seem to replicate this. Any other details? Is the issue even a thing still? Did machine already have glass in it from persistance? Was it there earlier, ejected, then added again? Is it dropped specifically onto the floor under you? Any other suspicions on potential triggers?
