### ISSUE TITLE
UNLIMITED THALLERS!!

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11697]
#### Brief description of the bug
with the curret item throwing bug it's possible to get unlimited thallers. As is it's possbile to throw an item but it doesn't get deleted from your hand. But when you put down the hand item the newly spawned one created. this leads to an undeleteable items that ATMs and Admemes can't remove

#### What you expected to happen
when I put thallers in the atm, the cash to not still be in my hand.

#### Steps to reproduce
- (Step 1)get thallers
- (Step 2)throw one tile a way so an Identical pile of thallers spawns
- (step 3) put the hand thallers into the AT, and wacth your balance go up.
- (step 4) put the same pile into the at a second time, and wacth you balance go up again
- (step 5) ahelp the pile to be deleted and wacth as even the admins ban hammer can not remove the pile.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Zeldazackman** [comment]
Seems to have thankfully been fixed by PR #11649
