### ISSUE TITLE
Fancy shuttle windows act like walls

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#11723]
#### Brief description of the bug
You can't shoot lasers through them, and they don't make sound when something attacks them.

#### What you expected to happen
To be able to shoot through them, and to hear the telltale BONK of something breaking through

#### Steps to reproduce
- (Step 1) Go in the tourbus
- (Step 2) fly to space
- (Step 3) encounter space carp

#### Code Revision
- B:release D:
Commit: 0ed7cd3098f11ce0e6b81bb9a6197b7b14dd960b 
 

#### Anything else you may wish to add:
- Makes it impossible to deal with threats before they enter the ship without going outside, and makes it so that if you can't see something, you won't know it's there (such as if you're looking at the map to fly the shuttle)

**Comment by GhostActual** [comment]
this one was fixed with the Shuttle PR
