### ISSUE TITLE
Xenobotany is lacking Flora Data Disks

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#11786]
#### Brief description of the bug
Flora Data Disks, a key component of Xenobotany, are absent in the Steller Delight's Xenobotany. Apparently, these disks can also not be printed by science?

#### What you expected to happen
To have a disk box present in xenoflora, preferably two boxes.

#### What actually happened
No boxes were found.

#### Steps to reproduce
- Enter Xenobotany
- Spend several hours perfecting genes
- Go to copy those genes to another plant
- Find no box
- Cry

#### Code Revision
Server revision: B:release D:
Commit: ddc546ef8171ec5706ae43360af88a6fda706500

**Comment by Very-Soft** [comment]
Fixed via https://github.com/VOREStation/VOREStation/pull/11789
