### ISSUE TITLE
map issue: non-functional atmospherics disposal bin

### ISSUE THREAD

**Issue by CubeJackal** [VOREStation/VOREStation#11833]
#### Brief description of the bug: 
atmospherics disposal bin is not connected to the disposals network

#### What you expected to happen: 
trash inserted into bin goes to cargo sorting room

#### What actually happened: 
trash inserted into bin goes into my face at muzzle velocity

#### Steps to reproduce
- insert trash into atmospherics disposals bin
- stand in front of atmospherics disposals bin
- receive blunt damage
 

#### Anything else you may wish to add:
mapping issue, stick some pipes down so it connects up to the larger network
![bin](https://user-images.githubusercontent.com/1291755/141886295-85a2e435-19dd-46c0-bf31-c8a4a6a64ea3.png)

**Comment by Very-Soft** [comment]
Fixed via https://github.com/VOREStation/VOREStation/pull/11834
