### ISSUE TITLE
Morphs can turn permanently invisible

### ISSUE THREAD

**Issue by ontejbjoav** [VOREStation/VOREStation#11846]
#### Brief description of the bug
Morphs become permanently invisible after resting while disguised as a mouse

#### What you expected to happen
To remain visible

#### What actually happened
It became invisible

#### Steps to reproduce
- Be morph
- Shift-click on mouse
- Rest
- Look on in awe as you are now permanently invisible

**Comment by GhostActual** [comment]
Might be because the mouse doesn't have a rest icon, I'll look at it
