### ISSUE TITLE
Advanced Scanner Printout Shows Necrosis, But There Really Isn't Necrosis

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1185]
#### Brief description of the issue: 
Advanced scanner printouts are showing necrosis when there isn't any necrosis. Ahelped it, had the vars checked, germ level as at zero. The screen of the scanner itself

#### What you expected to happen
For Advanced Scanner printouts to match what's onscreen!

#### What actually happened
They seemingly don't! Again! This was an issue before where it wouldn't show internal bleeding, and IIRC I noted that it'd be a good idea to double-check that it wasn't messing up with any other types of injury... Apparently, it is.

#### Steps to reproduce
- (Step 1) Look at the scanner screen
- (Step 2) Look at the paper. They don't match.

#### Code Revision
- Server revision: release - 2017-03-13
4734bec64eda849e707f13ecf6148ec98500084e 
 
#### Anything else you may wish to add:
- https://cdn.discordapp.com/attachments/211972038665961473/291057228520226826/unknown.png

**Comment by Wickedtemp** [comment]
To add on to this, I don't believe printed reports show reagents in the bloodstream, that should probably be added as well.

**Comment by Arokha** [comment]
Necrosis is unrelated to germ_level's current value. Once germ_level reaches 1000, the organ is necrotic until repaired, even if the infection is fixed.

Was this an internal organ or an external organ?

**Comment by Wickedtemp** [comment]
I have the screenshot in the initial report.

**Comment by Wickedtemp** [comment]
Adding on to this, from what I could tell, appendicitis didn't appear on the advanced scanner either. However, it WAS visible with the health analyzer. Everything else about it seemed to be working as intended, pain messages, etc, but wasn't detectable by the advanced scanner.

**Comment by Wickedtemp** [comment]
Updating this, ran into it again yesterday while on a tether playtest.

**Comment by SpadesNeil** [comment]
Still a bug?

**Comment by Wickedtemp** [comment]
Closing this, because it's been open for so long that either it's fixed by now, or it never will be, or it doesn't need fixing. And I'd like to make a small dent in the absurd number of git issues.
