### ISSUE TITLE
Fox Taur Armor - Kateryna Petrovitch - Samanthafyre (Fixed)

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#1188]
Name of Item:Kat's Fox Taur Armor.
     
Item description:A set of security armor, light weight and easy to run in for a Taur, this item protects the entire body. (try to keep it short and sweet)

Sprites (or link to sprites): Its all implemented under "Wolf taur armor"

Any additional resources: Its all in the server already.

BYOND Key (Username):samanthafyre

Name of Character:Kateryna Petrovitch 

Main Job(s) of Character:Security

Why your character should have this item: Normal armor issued to the security forces of the station are designed for bi-pedals. Not taurs so the armor does not protect the rest of her body, she figured this would be a welcome change to apply for specialized armor after an incident with her being shot in the back.

Additional Notes (If it's a permit, insert the information for the permit here): Just a simple rename of a already implemented item. And somewhat a description add.

Fluff Item slots already used:0

**Comment by HawkerTheGreat** [comment]
Talked to Kate over Discord for a bit and she brought up her armor. It took me a few minutes to re-color the security armor to a painted purple. I'm going to drop the zip... In the DMI there is only a single state with four faces.

[kate.zip](https://github.com/VOREStation/VOREStation/files/852763/kate.zip)

**Comment by BlackjackFajah** [comment]
All that needs to be done now is it put together. The code added and shit. And BOOM its done.
