### ISSUE TITLE
Serkii's outfit

### ISSUE THREAD

**Issue by Eekmouse** [VOREStation/VOREStation#1189]
http://forum.vore-station.net/viewtopic.php?f=26&t=878

Can't attach 7zip files and it's faster to just link the thread, basically just want an outfit that matches Serkii's ref pic.

**Comment by Screemonster** [comment]
It might be easier to dropbox the actual .dmi files if you've got 'em rather than zipping them, I'm at work so I dunno what's actually in the 7z files there. You got screenshots of the items?

**Comment by Eekmouse** [comment]
I don't know how to take screenshots! I can see about dropboxing them though.

**Comment by HawkerTheGreat** [comment]
Usually .7z is the same as .rar in terms of function, - only slightly different from the .zip and a tad more efficient iirc.

I'm not sure if this is cleared, but I've been looking through the Git Issues anyways.
![ssimg](https://cloud.githubusercontent.com/assets/9869250/23961611/d7f14b9a-0981-11e7-838a-549bf83ab8e4.png)
[Serkii.zip](https://github.com/VOREStation/VOREStation/files/845436/Serkii.zip)

Save you the trouble of throwing together a picture and threw the files up. ;)

**Comment by Screemonster** [comment]
Okay, that's adorable.
We can add it as a fluff item, or just as easily make it a loadout thing. Take your pick.

**Comment by Eekmouse** [comment]
Just a fluff item for now.
