### ISSUE TITLE
start treaders perma stun lock you if mob vore turned off

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11899]
#### Brief description of the bug
star treaders peram stun lock you if you have mob vore turned off instead of eatteing you

#### What you expected to happen
to be able to get up after knocked down

#### What actually happened
it does the pounce attack before I get up and resetting the count down

#### Steps to reproduce
- (Step 1)have mob vore off
- (Step 2) get hit by star treader
- (step3)  get attacked and get knocked over well before you get up

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
This does not appear to be a bug. Star Treaders are just very slow, very tanky, mostly-low damage melee mobs with a relatively high chance to stun on hit unrelated to vore pouncing. Sounds like you just got pretty unlucky. Not a bug tho.

**Comment by TheDavestDave** [comment]
it's proven to have a way too high chance to knock over with other people. While it tends to eat people if you're not into it anyone who can't blob out is condmend to a very slow death unable to do anything.

**Comment by Heroman3003** [comment]
They, again, are VERY slow mobs that seem to be designed to be avoided rather than fought normally. And there is a certain weapon that is more efficent against them specifically. And again, stun chance is not related to vore pounce.

**Comment by TheDavestDave** [comment]
I don't find you got hit now time to slowly die by something that is hard to kill for like 30 mins unable to play or interact with the game past at best screaming for help as being fun
