### ISSUE TITLE
rad artifcts go off twice if hit by phoron bore

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11898]
#### Brief description of the bug
rad artifacts go off twice if hit by phoron bore

#### What you expected to happen
to go off once

#### What actually happened
double effects

#### Steps to reproduce
- (Step 1)blow up radation effect artifact with phoron bore
- (Step 2) screen goes white, loose heatlh then wait 5 seconds for that effect to happen again
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
might be a blob as protean bug

**Comment by Heroman3003** [comment]
Can't replicate, even using protean blob. I found fix for unrelated bug, but I can only assume that somehow either two artifacts got blown up with same effect within 5 seconds and you got hit by both or... It's something else entirely. Artifact popping while being a protean blob did not yield those results.
