### ISSUE TITLE
mining fridge will just stop dispensing mats

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#11900]
#### Brief description of the bug
some time in the shift the mining mat fridge storage will just pick a mat and decide we can't take it

#### What you expected to happen
to give mats when asked

#### What actually happened
no

#### Steps to reproduce
- (Step 1)get mat from fridge too many times
- (Step 2) have no mats, almost like it's frozen but for that one mat
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by PastelPrinceDan** [comment]
i've noticed this often happens when dispensing a lot of/all the mats from a category
it'll dispense a huge stack of the mat, and a lot of basically empty stacks that are 0 sheets and will disappear later on
and then you just can't dispense shit from that category anymore

**Comment by TheDavestDave** [comment]
this isn't fixed
