### ISSUE TITLE
Fork in Missing Vox Sprites

### ISSUE THREAD

**Issue by HawkerTheGreat** [VOREStation/VOREStation#1191]
#### Brief description of the issue
As we all know, since Polaris only recently added Vox - they've not gotten a lot of love and are missing about 70%, if not 90% of all their sprites. Most of these are replaced by the bland default item for Vox sprites and usually look like a white lab coat or a gas mask - or simply don't even appear for players unless the Vox is specifically examined. I packed up all the normal .dmi's from Paradise's open source git and would like a discussion or some idea of where to start with the files, as they need to be coded in by hand if we are to use them.

#### What you expect to happen
Short discussion of the topic and possibly the allowance to throw in a few of the missing sprite files for Vox. - I'd love to help, since the dev team is always working on other stuff and this is not incredibly important.

#### Code Revision
Release - 2017-03-14
89af151c970380f16f994bba6387fc7ce1f2e883 
 
#### Anything else you may wish to add:
I would like to also add that I have, ripped these sprites directly from the paradise github, but have no intention of changing them from their original creators design.
[vox.zip](https://github.com/VOREStation/VOREStation/files/845335/vox.zip)

**Comment by SpadesNeil** [comment]
Paradise is open source so we can use them here so long as we credit them by linking to their file we are pilfering.

**Comment by HawkerTheGreat** [comment]
I'll be throwing them in my local and running them before I throw them in a PR - I have the slightest thought that they may need to renamed or changed - but we'll see once I get around to them.

**Comment by HawkerTheGreat** [comment]
Rather than pushing this directly to our codebase, I'm trying to get it pushed to polaris first, but I'll keep this up and close it once we merge with theirs.
https://github.com/PolarisSS13/Polaris/pull/3105
