### ISSUE TITLE
Yes and No options on popup window for "Give" prompts are swapped

### ISSUE THREAD

**Issue by BigBababooey** [VOREStation/VOREStation#11915]
#### Brief description of the bug
Simply put, most other yes/no prompts have Yes on the left and No on the right, so this is possibly erroneous placement of the buttons. 

#### What you expected to happen
I go to click yes to accept on the left, where that normally is placed, and do not see it.

#### What actually happened
I decline the attempt to give an item, due to the swapped placement

#### Steps to reproduce
- Player attempts to give you an item
- You go to click yes, but click no instead because of the swapped buttons, looking like an idiot
- Be mildly inconvenienced

#### Anything else you may wish to add:
- There's a nonzero chance this isn't _actually_ a bug and was intentional placement, but I myself am consistently confused by it, and I see fairly often people get confused and gaslit by the abnormal button placement. So if it's intentional, but can be switched back without causing problems, that would be swell.

**Comment by Heroman3003** [comment]
I remember this being 'intentional', if confusing for simple reason - the first option is default one when hitting 'enter', and to avoid accidentally accepting an item because you hit enter at inopportune time, no is first.

**Comment by BigBababooey** [comment]
I figured that was a possible reason why. Admittedly I'd rather it default to accepting than what it is now, I've certainly seen annoyance/frustration that it auto declines as a result as well. It's quite funny to see in looc, tbh, but it's still not great.
