### ISSUE TITLE
Teppi Corpse remains after being butchered

### ISSUE THREAD

**Issue by BigBababooey** [VOREStation/VOREStation#11914]
#### Brief description of the bug
When one butchers a Teppi Corpse with a knife, the corpse remains after the fact, but cannot be harvested further.

#### What you expected to happen
I expected the Teppi corpse to disappear as other mobs do when butchered, as it produces meat, organs and leather which is all meant to be what was just cut up.

#### What actually happened
All the correct contents emerge meatwise, leatherwise and organwise, but the dead corpse of the teppi remains.

#### Steps to reproduce
- Slaughter full grown Teppi while it is resting on help intent with a knife, triggering special interaction that kills the Teppi (Unknown if this produces the bug, this is how it was done)
- Butcher aforementioned Teppi with knife resulting in the meat emerging, and corpse staying.

#### Anything else you may wish to add:
- Tested with the special instant kill method for Teppi, it is possible a Teppi that dies normally, or a Teppi that dies with it's Fur still grown (as one cannot do the instant kill otherwise) that they do not have the corpse remain.

**Comment by Heroman3003** [comment]
I can't seem to replicate this. Either it's inadvertedly fixed by #11882 or the reason for bug in question is something else. As I made a teppi, forced them to rest, then killed them, then butchered and corpse disappeared normally.

**Comment by BigBababooey** [comment]
This was done a couple days ago, so very possibly that did indeed fix it? No longer relevant then I guess!
