### ISSUE TITLE
Rooms show wrong pressure after reaching equilibrium

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1192]
#### Brief description of the issue
Rooms with an open airlock between them exchange gas until they reach equilibrium (or close to it).  However when this happens, the final pressure reading in both rooms is *wrong*.

#### What you expected to happen
For the Pressure of the room to read out the correct value for the amount of gas in the room (3.6 kPa in this example) Also for the gas mixture %ages to add up to 100%ish

#### What actually happened
Total pressure was showing wrong (6.1 kPa in this example, almost double the real pressure)
Also notice the %age totals don't add up anywhere close to 100% either!  (And its not because there were any hidden other gases, it was pure airmix)

#### Steps to reproduce
- Have two rooms at significantly different pressures ( 1atm and vacuum works fine )
- Open the airlock between them and wait until pressures stop changing.

#### Code Revision
89af151c970380f16f994bba6387fc7ce1f2e883 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://cloud.githubusercontent.com/assets/14110581/23961513/8ec71850-0981-11e7-9ebd-15a40f6f1e83.png)
First air readout is after the room reached equilibrium, second is after calling update_values() to fix the total_moles.
Notice that neither the gas mixture nor temperature changed, but Pressure is showing a different value!  One must be wrong... we double check which one by doing the math:

total_moles = 0.77 + 2.89 = 3.66
pressure = total_moles * R * temperature / volume = 3.66 * 8.31 * 293.2 / 2500 = **3.56**

**Comment by Arokha** [comment]
Fixed in master
