### ISSUE TITLE
Tulidaan's Got Fiddly Sprites

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#11929]
#### Brief description of the bug
Tulidaan's 'hat' sprite is not purple like the rest of his sprites.

#### What you expected to happen
Putting Tulidaan the Catslug onto my head slot to have a purple catslug scarf.

#### What actually happened
I put him on my head slot but he stopped being purple, instead becoming a default white catslug!

#### Steps to reproduce
- Acquire Tulidaan
- Put on head slot
- Get non-Tulidaan scarfslug

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- The left-hand and right-hand holding sprites where he noodles onto your shoulder work as advertised.
- https://i.imgur.com/oKJKpTa.png
- https://i.imgur.com/qH4Lz3S.png

**Comment by PastelPrinceDan** [comment]
fixed in #11889, server just needs an update

**Comment by Heroman3003** [comment]
Can confirm, its now fixed on latest master
