### ISSUE TITLE
Admin Tools - Build-Mode Bugs When Aghosting

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#11966]
#### Brief description of the bug
Using `aghost` with build mode open removes the build mode UI but still stays active, preventing normal interaction.

#### What you expected to happen
Switching between ghost and non-ghost, not fumbling around until I apply the fix.

#### What actually happened
Be incredibly frustrated at the deceptive clunkiness of build mode and aghost working together.

#### Steps to reproduce
- Be in body or aghost (either)
- Toggle build mode
- aghost to swap to opposite (body or ghost)
- UI vanishes, still active in build-mode

**Comment by Zeldazackman** [comment]
You're going to want to hit build mode again once you get back into the body in order to disable it if you aghost back in or out of the body with it active.

**Comment by ResidentCody** [comment]
I'm aware of how to fix the issue in the moment. I opened the issue just regarding the fact that it happens at all.
