### ISSUE TITLE
Injection of Phoron into Vox was insufficient for treating extremely high levels of suffocation

### ISSUE THREAD

**Issue by SeigaSeiga** [VOREStation/VOREStation#1199]
#### Brief description of the issue
Took in a critical condition Vox. Treated all organ damage and broken bones etc etc. Basically clean bill of health besides about 150 'oxygen' damage. Injections of phoron weren't outpacing the suffocation, tricordrazine had to be used in addition, and possibly worked better than the phoron itself. Obviously I could've used inaprovaline but at the time I wasn't sure if that would be poisonous as dexalin, but that's not really the issue here.

#### What you expected to happen
For something as valuable [read: non-renewable without odysseus cheese] as liquid phoron which has been coded to able to be used to phoronate Vox blood to actually... do that.

#### What actually happened
Phoron could not pull a Vox out from a deep suffocation crit. While looking at the body scan I noted that the processing rate of phoron is extremely slow.

#### Steps to reproduce
Not tested, reported based on a single server experience. Assumedly:

1. put vox into deep oxyloss crit
2. apply phoron
3. behold ineffectuality

#### Code Revision
Server revision: release - 2017-03-14
89af151c970380f16f994bba6387fc7ce1f2e883 
 
#### Anything else you may wish to add:
vox smell

**Comment by Arokha** [comment]
Phoron: `M.adjustOxyLoss(-removed * 9)`
Dexalin: `M.adjustOxyLoss(-15 * removed)`

So, 9 per full unit of phoron vs 15 per full unit of dexalin. So it is a bit slower than dexalin.

**Comment by Wickedtemp** [comment]
It's almost half the effectiveness of Dexalin without taking the metabolism rate into account. Definitely needs a buff of some kind to make it the equivalent of Dexalin, not Dexalin Plus.

**Comment by Poojawa** [comment]
Phoronalin Plus.

**Comment by SeigaSeiga** [comment]
Silly idea, but... Lexorin is a phoron-based toxin that stops most creatures from respirating, which is to say it actively causes damage to tissue that needs oxygen. Wouldn't it, through some bullshitty logic, make sense that it could potentially have application as the Vox-Dexalin that we currently lack?

**Comment by Screemonster** [comment]
Make phoron act as dex and lexorin as dex+

**Comment by ArbyTheDragon** [comment]
Lexorin currently has literally no other purpose beyond murder, antag, and grief currently.
Lexorin is a phoron based chemical (Much like dexalin!) that uses hydrogen and oxygen, which are componets of ammonia ('Ammonia based beings' were the whole idea behind what Vox used to be IIRC, when they breathed nitrous oxide-)
Similarly, dexalin and dexalin plus utilize carbon, oxygen, and iron, which are componets of everyone who isn't Vox!

Nothing makes more sense than Scree's idea.
Even the fake chemistry makes sense!

_Also, I wonder if impedrezine can become a reactant in some other product. It too has no purpose beyond murder, antag, and grief. This is perhaps the last chemical on our chemistry system that has no real usage._

Lexorin is Dexalin Plus for Vox. Do it!

**Comment by Wickedtemp** [comment]
Impedrezene actually lowers the 'jittery' effect, you know, that shaking-sprite thing people get when they drink too much coffee. Imped helps with it, but it isn't something that'd actually be utilized because giving someone a brain-damaging chemical just to help them stop shaking is... stupid.

**Comment by ArbyTheDragon** [comment]
Stopping involentary muscle contractions by stopping all involentary nerve functions is too brute force. x3

**Comment by Wickedtemp** [comment]
Discussion on this kinda died, which sucks because I liked where this was going

**Comment by ArbyTheDragon** [comment]
Might only become an issue again when more Vox players get around. Whenever I'd see a Vox though, he was always a terrorist/antag psychopath. Lul.
That was a different server though.

**Comment by Wickedtemp** [comment]
I might see if a PR of this can't be made. Discussion over it has pretty much concluded.
