### ISSUE TITLE
Polaris Port - Dogborgs

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#12]
- [x] Medihound
- [x] K9
- [x] K69
- [x] BOOP Module
- [x] Sleeper Module
- [x] Tongue Module
- [ ] Fix offset
- [ ] Fix sleeper sprite

**Comment by Cameron653** [comment]
Done. Only a minor bug that can be overlooked. See the PR for more info.

**Comment by Cameron653** [comment]
NOW I've fixed it.

**Comment by Arokha** [comment]
Dogborgs are offset oddly. When walking north/south they are offset sideways, aka they go 'halfway' through doors. Pls2fix. Also sleeper bellies don't show up, probably needs some overriding of the update icons on them borgs.

**Comment by Cameron653** [comment]
Huh. Their bellies were showing up before. I'll look back into this after I
finish egg tf.

**Comment by Cameron653** [comment]
this is fixed
