### ISSUE TITLE
Fluff Item Request - Chakat Taiga/KiwiDaNinja

### ISSUE THREAD

**Issue by KiwiDaNinja** [VOREStation/VOREStation#1200]
[b]Name of Item:[/b] Taiga's F.D Uniform
     
[b]Item description[/b]: This uniform - consisting of only the uniform shirt, and built out of a soft fleece - dons the badge of Amistad Fire and Rescuse on both shoulders. The badges denote the wearer as a FF/Paramedic, and their name is embroidered in a gold thread on their right breast; Chakat Taiga! An 'official' badge is pinned to their left breast.

[b]Sprites (or link to sprites)[/b]: https://www.dropbox.com/s/hazjjrcvkzftw81/taigaFF.dmi?dl=0

[b]Any additional resources[/b]: N/A

[b]BYOND Key (Username)[/b]: KiwiDaNinja

[b]Name of Character[/b]: Chakat Taiga

[b]Main Job(s) of Character[/b]: Atmospheric Tech/Paramedic

[b]Why your character should have this item[/b]: Taiga, outside of working on Virgo, serves as an individual of the Amistad Fire Department; this is just their uniform they'd typically wear whilst on duty there. Taiga is really quite proud of their status as a Firefighter, and a bit of 'showing off' wouldn't hurt. Plus, its /comfy/!~

[b]Additional Notes (If it's a permit, insert the information for the permit here)[/b]: This -is- a resprited Wardens outfit, so, I dont know if that'll fudge with how the code works and stuff. If its possible, could the damage resist values (if any) of the Atmospheric jumpsuit be applied? 

...I dont know how Byond code works, so, please tell me if that is even possible. Thank you!~

[b]Fluff Item slots already used[/b]: (0/1/2/3/4) 0! My first!

**Comment by Cameron653** [comment]
As far as I can see, it looks good. I'm not the person that approves these, so just give me a ping when it's approved and I'll have it added in.

**Comment by Screemonster** [comment]
Looks good to me. Can just crop it to make the inventory icon.

**Comment by Arokha** [comment]
Merged
