### ISSUE TITLE
Medbay needs request consoles

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1201]
#### Brief description of the issue
There are no request consoles available to medbay staff apart from the one in the CMO office. At least, none that are obvious.

#### What you expected to happen
For there to be a request console in chemistry and in the lobby, possibly the breakroom.

#### What actually happened
Cargo order came in, and nobody in medbay was able to get the request as there wasn't a CMO on.

#### Code Revision
Server revision: release - 2017-03-14
89af151c970380f16f994bba6387fc7ce1f2e883 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Wickedtemp** [comment]
It was especially annoying that two cargo orders went by in a row, both requiring chems that were already made... 

So yis pls.
