### ISSUE TITLE
Cannot make chocolate bars wither of the two recipes 

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#12018]
#### Brief description of the bug
You cannot make chocolate bars that are needed for kitchen related recipes 

#### What you expected to happen
I mix milk/soy, sugar and cocoa powder and print chocolate bars

#### What actually happened
I get choccy milk because whoever added it didn't check if the recipe of milk, sugar, cocoa powder was already in use OR nothing happens, I get nothing when using soymilk.

#### Steps to reproduce
- Grow cacao 
- Grind cacao
- Filter cocoa powder to get rid of nutrient (Or don't, it doesn't matter too much)
- Mix ground up cocoa powder with milk and sugar, get choccy milk and maybe a chocolate bar
- Mix ground up cocoa powder with soymilk and sugar, nothing happens

#### Code Revision
- 07d00c670d81bd546b7b763444ddee105f7a18d6
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by PastelPrinceDan** [comment]
the recipe recently changed to require 5u enzyme as a catalyst
see #11895
