### ISSUE TITLE
Precious metals crisis due to drills refusing to mine them

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#12033]
#### Brief description of the bug
No gold, silver or hematite when using the big drills.

#### What you expected to happen
To get the materials I am mining for.

#### What actually happened
Confused miner with no gold.

#### Steps to reproduce
- Analyze to check for ores.
- Find a good spot with lots of everything.
- Set up drill.
- Wait.
- Keep waiting.
- Drill is done, check what you got.
- No gold, silver or hematite even though the scanner indicated there was a lot of those on that spot.

#### Code Revision
- 749506461e486b051472737e27967b5c071c2ad4 
 

#### Anything else you may wish to add:
- Seems to happen on all minable areas, Asteroid field, V4, V2.

**Comment by Heroman3003** [comment]
this should be fixed now.
