### ISSUE TITLE
Akula blood is red instead of blue!

### ISSUE THREAD

**Issue by ArbyTheDragon** [VOREStation/VOREStation#1203]
#### Brief description of the issue
I withdrew some blood to make some synthmeat from my self while I was an Akula, but much to my surprise, the blood reagent was red in the syringe?
Blood does become red when it mixes with other reagents, but blood on the ground from bleeding wounds is also red, as well as the wound sprites on the player.

#### What you expected to happen
The blood would be a dark blue as it has been for Akulas since 2015, to symbolize that the blood uses copper based hemocyanin which is blue, instead of iron based hemoglobin which is red

#### What actually happened
The blood is red, like humans, unathi, and others.
http://puu.sh/uO3gO/69b341db88.png
#### Steps to reproduce
- (Step 1) Be Akula
- (Step 2) Bite/scratch yourself
- (Step 3) Bleed
- (Step 4) It's red

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Server revision: release - 2017-03-14
89af151c970380f16f994bba6387fc7ce1f2e883 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Previous code shows that the old hex value for the blood color was 1d2cbf

**Comment by ArbyTheDragon** [comment]
Wish I had a screenshot of how it used to look, but puush apparently deletes images past a certain age.

**Comment by Arokha** [comment]
What color blue should it be? Give it in hex.

**Comment by ArbyTheDragon** [comment]
Damn... This is where I wish I had the screenshot..

**Comment by Arokha** [comment]
Fixed in master
