### ISSUE TITLE
foam weapons can be sharpened but do no damage

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#12041]
#### Brief description of the bug
you can sharpen foam weapons but they still do no damage

#### What you expected to happen
to not be able to sharpen them or for them to do damage after being sharpen

#### What actually happened
sharpened but still no damage

#### Steps to reproduce
- (Step 1) sharpen foam weapon

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

https://user-images.githubusercontent.com/30513964/147957534-85114cd3-1ba9-40b6-99ed-40818f933880.mp4

**Comment by Very-Soft** [comment]
it's a foam axe

**Comment by TheDavestDave** [comment]
I always understood it as you are replaceing metal. As if you sharpen a plasteel knife with a durasteel sharpening kit it both uses metal and you get a durasteel knife.

The bug here is ether the foam weapon is now a steel one that does no damamge, or the ability to turn the foam weapon into a steel one, as it does use mats to do this per item. 8 for axes and 6 for swords.

**Comment by Very-Soft** [comment]
Okay but you do realize that a foam sword traditionally is either made entirely of foam, or, if it's fancy, it might have a cheap plastic handle.

It isn't a 'kit with all the pieces you need to construct a sword', it's a sharpening kit. Like, a sharpening kit almost certainly would not have a replacement blade or handle. It would probably have the things you would need to tighten up the parts, perhaps an alternate guard or two, and an implement to actually sharpen the blade. 

There isn't metal to replace on a foam weapon though. Your sharpening kit is deffo not going to allow you to turn a funny foam sword into an actual functional weapon. You can sharpen the foam, but it's still not going to be hard enough to actually cut anything that isn't of lesser hardness than foam. 

If anything it should probably just not work on the foam weapons.
