### ISSUE TITLE
Storage Pouch of Holding fails to insert items

### ISSUE THREAD

**Issue by ktccd0** [VOREStation/VOREStation#12056]
#### Brief description of the bug
so like... I can't put an item into a pouch of holding while it's equipped....
And a quick reading of the code for inserting things (while equipped) is... confusing. It looks copy-pasted from the REMOVING code, so the if-statement should never work and it will always abort inserting the item?
File in question:
https://github.com/VOREStation/VOREStation/blob/edc62e88fa376fc5f48dcf7f4d904e24bd2fb03f/code/game/objects/items/weapons/storage/pouches.dm

#### What you expected to happen
Item to be inserted into the pouch after a brief delay.

#### What actually happened
Nothing at all, not even a delay or something.

#### Steps to reproduce
- (Step 1) equip a storage pouch of holding.
- (Step 2) try to put an item in it while the pouch is equipped.

File in question:
https://github.com/VOREStation/VOREStation/blob/edc62e88fa376fc5f48dcf7f4d904e24bd2fb03f/code/game/objects/items/weapons/storage/pouches.dm

**Comment by ktccd0** [comment]
To be even more precise:
The snippet that "stalls" before you can put an item inside the pouch has an if-statement checking if the item is *already in the pouch*. That makes sense for the removal code, but will never be true for the inserting.

**Comment by ResidentCody** [comment]
I seriously just assumed that was part of the tradeoff for such a useful storage item. My understanding was that, much like using nested boxes in backpacks, you're trading to gain storage space at the cost of clunkiness. In the case of pouches,

You can instantly insert and remove items from the bag if it's in hand, so I just got used to taking the pouch out of pocket and working with one hand basically. The price of having bluespace pockets.

**Comment by PastelPrinceDan** [comment]
i believe that's intended behavior?

**Comment by ktccd0** [comment]
@PastelPrinceDan @ResidentCody 
I don't know how to describe this bug any clearer than this :S.
In the link to the code, lines 21 to 32, there is a piece of code clearly showing that you are intended to be able to insert things into the pouch while wearing it, except not un-equipping it first should cause a slight delay.

Whoever coded this just forgot to remove the last if-statement when they copy-pasted it from the "stall_removal" function.
I'd code a fix for it myself since it's just, like, deleting two lines of code and switching a false to a true, but like... I do not have github set up to do any SS13 coding and that's such a headache to do :/.
