### ISSUE TITLE
hostile ai not turning on

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#12059]
#### Brief description of the bug
hostile ai don't turn on

#### What you expected to happen
hostile ai to be active

#### What actually happened
hostile mobs don't move

#### Steps to reproduce
- (Step 1)go to hostile mob
- (Step 2) pet freely

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I have been asked to clarify. It appears to be all mobs on feilds of 3b astorid thing, and at least the snow map in the gateway. I suspect it's more

**Comment by PastelPrinceDan** [comment]
i can confirm that this has happened multiple times. it's not *always*, but it's been happening a lot. mobs on 3B, V4 and V2 have been completely unmoving a few times now, from what i've seen
