### ISSUE TITLE
Wrenching low walls to deconstruct them causes dropping of hand drill.

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#12075]
#### Brief description of the bug
When unwrenching a "low wall" to deconstruct it, you drop your held hand drill

#### What you expected to happen
Hand drill not to drop.

#### What actually happened
Hand drill dropped onto the tile I was standing on

#### Steps to reproduce
- Grab 3 steel sheets
- Use-Held-Item, construct a Bay low wall
- Grab Hand drill (either CE's, or from Science)
- Use-held-item hand-drill until it's wrench-bit
- Use hand-drill on low wall
- Wait for action to finish
- Low wall deconstructs, hand drill gets dropped

#### Code Revision
 Server revision: B:release D:
Commit: e736aef3b06acce52b279e43e6661b9399d83665 

#### Anything else you may wish to add:
- It may cause wrenches to drop too, but I didn't test.

**Comment by TheToaster98** [comment]
I can confirm, wrenches are dropped too.
