### ISSUE TITLE
Eating resting prey causes dropped items to fall out of bellies!

### ISSUE THREAD

**Issue by lirdos** [VOREStation/VOREStation#12077]
#### Brief description of the bug
Being vored while resting means dropping an item by then trying, and failing, to wield it will deploy said item on the floor.

#### What you expected to happen
Item to be deposited in belly, as intended.

#### What actually happened
Item falls on floor, even gunk-colored

#### Steps to reproduce
- Eat resting prey
- Tell prey to drop something
- Bam, bluespace belly.

#### Anything else you may wish to add:
- If you stand up and then rest as the prey in this instance, dropping functions as intended apparently.
- Tested by myself and another player on-server.
- Sorry if this was already reported, I couldn't find anything with the search tool.

**Comment by Heroman3003** [comment]
cannot replicate and old.
