### ISSUE TITLE
Ian eats things through barriers.

### ISSUE THREAD

**Issue by HawkerTheGreat** [VOREStation/VOREStation#1209]
![far reaches of space](https://cloud.githubusercontent.com/assets/9869250/24077813/d9cd52be-0c2f-11e7-8c17-91b3f23c2375.png)

- Let me re-type this... It was 1am and I was, Err... Tipsy.

**Comment by HawkerTheGreat** [comment]
So, Ians seem to spawn like mad in this port, I've seen them swarm the bar like a fifty player server made up of only Xenomorphs... Also! Its probably smart to state that they eat through walls and glass windows, and just kinda sit there, spamming the nibbles away every two seconds, but never finish the Food that they're trolling on.

**Comment by MASMC** [comment]
This is not okay... D:

**Comment by Shophaune** [comment]
Ian no longer seems to eat anything at all. So...fixed I guess?
