### ISSUE TITLE
OOC flavortext on newcode only allows single lines.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#121]
The OOC info box is only a single line rather than a full textbox.

This makes it a pain to edit compared to the neat prefs flavortext thingy we had in the last code.

**Comment by SpadesNeil** [comment]
Was this resolved? I remember this being resolved.

**Comment by SpadesNeil** [comment]
Technically #132 is the duplicate but that was the one that was fixed so... screw it.
