### ISSUE TITLE
you should be able to get job-locked loadout items as off-duty

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#12103]
if at any point i think i am likely to go on duty during a shift i have to join as on duty and then go off duty after 15 minutes or whatever the cooldown time is because otherwise i have job-locked loadout items i have no other way of obtaining. this is mostly a qol thing tho because having to join as on-duty just to get loadout items is annoying.

i guess it could be bad if you have a bunch of off-duties running around with sensitive job equipment but loadout doesnt even have anything that sensitive iirc. like you can get some glasses and holsters and stuff but not like, guns, medkits, or anything that would let you operate as the job while off-duty. UNLESS YOU START OUT ON DUTY AND SPEND THE FIFTEEN MINUTES TO WAIT DOWN THE TIMER NICKING STUFF FROM THE WORKSPACE.

**Comment by Heroman3003** [comment]
I'd say glasses definitely should stay off loadout. In part because they allow you to directly edit status of people and access seeing it and such. Otherwise yeah, I kinda agree.

**Comment by Wickedtemp** [comment]
I'd support this. There isn't anything majorly sensitive as far as I can recall, at least, not from medical's side of things and this is all stuff you'd be able to get by clocking in and out or by just asking an on-duty in-department crew member and chances are they'll just give it to you.
