### ISSUE TITLE
Thrown bottles don't smash

### ISSUE THREAD

**Issue by pantherpusher** [VOREStation/VOREStation#12102]
#### Brief description of the bug
Glass drink bottles will never smash when thrown

#### What you expected to happen
The bottle to break eventually and splash the contents on the floor

#### What actually happened
Bottle landed with a clank no matter how many times it was thrown or at what distance it was thrown from

#### Steps to reproduce
- (Step 1) Take glass drink bottle
- (Step 2) Switch to harm intent
- (Step 3) Throw it at a wall about two tiles away
- (Step 4) Notice the bottle remains intact despite being whipped at a wall from two paces away

**Comment by TankTheBirb** [comment]
Replicated, although I can find nothing that says that breaking bottles on a throw is intended. Breaking a bottle by harm intent clicking a person is intended and functional though. This may be a suggestion.
