### ISSUE TITLE
Infinite Metal at Autolathe

### ISSUE THREAD

**Issue by SomeGuy94567** [VOREStation/VOREStation#12114]
#### Brief description of the bug
It is possible to infinitely create steel at the Cargo Autolathe by removing and re-inserting sheets of steel.

#### What you expected to happen
Normally, when removing materials such as steel from an autolathe, I select how much of the material I wish to remove and get a sheet corresponding to that amount. When I re-insert the sheet into the autolathe, it only adds that much material back in. For example, if I remove 1k steel in a sheet (stored steel 3.50k -> 2.50k), then re-insert the sheet, it will add 1k steel back to the autolathe (stored steel 2.50k -> 3.50k).

#### What actually happened
When re-inserting steel sheets into the autolathe, the sheets added 2k steel into the autolathe storage even though the sheets I removed only used 0.02k steel to be created.

#### Steps to reproduce
The exact way I did it
- Craft 0.01 steel sheets from the autolathe.
- Autolathe stored steel goes from 5.98k steel -> 5.96k steel
- Re-insert steel sheet into autolathe.
- Autolathe stored steel goes from 5.96k steel -> 7.96k steel
- Repeat for infinite steel (I tested if it was consistent by repeating 3 times)

 

#### Anything else you may wish to add:
- I only tested this on the Cargo Bay autolathe, and only with steel, so I have no clue if it is an issue only for that autolathe and only for steel, or if this is an issue for all autolathes and all materials.

**Comment by TankTheBirb** [comment]
Works on all autolathes and with all materials. Curiously it doesn't work on the protolathe, as it produces a bugged sheet of materials that can only be deleted by an admin or an autolathe.
