### ISSUE TITLE
PSU not outputing power to grid

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#12117]
#### Brief description of the bug
PSU won't output power to the grid

#### What you expected to happen
PSU to outpout power to grid

#### What actually happened
no output only input

#### Steps to reproduce
- (Step 1)build psu
- (Step 2)set up one wire terminal thing to connect to grind, get input no out put
- (Step 3)do a second same problem

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TankTheBirb** [comment]
Unable to replicate, likely due to a power network glitch where it doesn't update when new things are put on the wires.
