### ISSUE TITLE
Farmbots allow plants to die

### ISSUE THREAD

**Issue by ktccd0** [VOREStation/VOREStation#12116]
#### Brief description of the bug
Farmbots tend to the plants until it is done for a moment, then turns itself off and allows them to die.
This seems to be added to the farmbot code specifically for our server, and is not a toggleable setting.

#### What you expected to happen
Farmbot should keep the plants alive while you step away from them for a while, without worry that they will randomly die off.

#### What actually happened
Farmbot counts to 150 seconds of nothing to do then turns off and remains off until manually turned back on.
So now you have to babysit the farmbot also.

#### Steps to reproduce
- (Step 1) Make farmbot
- (Step 2) Let it take care of plants
- (Step 3) After 150 units of time with no plantwork to do, it turns off.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Code for farmbot has comments showing the timer function, so at least we know it was intentionally added for our own server. Unsure why though. This might just be some kind of hidden nerf to the farmbot, but because this function is not shown or informed through the game in any way, it LOOKS like a bug or something weird going on until you code-dive here on github, which IDK how many people care to do.
If this is going to be kept as a feature, can we at least have some kind of timer shown on its interface so the player is informed about it?

https://github.com/VOREStation/VOREStation/blob/599c79a0ceeecb140ba2235a36a22fd72ebb54b2/code/modules/mob/living/bot/farmbot.dm

**Comment by KillianKirilenko** [comment]
This is from a pretty old PR, #2662, and I don't see many obvious complaints about their behavior in the discord over the past year or two.

How long are you stepping away that this is actually a problem? Farmbots are supposed to make your life a bit easier, not 100% automated.

**Comment by Very-Soft** [comment]
They keep working just fine if you're actually collecting the plants. Originally farmbots would harvest plants for you and just work forever, but in a 6 hour round, that creates crash stacks, and, if no one is around to care about whether the farmbot is still working, it USUALLY means they're done with it, so it turns itself off instead of wasting processing power looking for something to do.

**Comment by ktccd0** [comment]
@KillianKirilenko I didn't measure how long I was gone until I began trying to figure out the issue, but it must have been less than 10 minutes, as it was mainly so that I could grab the various vegetables, bring them to the kitchen, cook a few burgers, and then return to pick up more vegetables.

It should be noted that I am playing as a Diona, however, so even a short walk over to deal with a minor thing can take a couple of minutes. I'm not asking for the farmbot to harvest the plants for me, that part seems like a separate subject.


As for why nobody else hasn't complained... Well, I can only speculate as to why. Some people don't use them, some people might just stock up the kitchen a bit and then do something else.
It might just be a combination of me trying to overstock the kitchen, leading to me spending most of the shift there, and the fact that a Diona doing the same tasks can turn what would be several 1-minute absences into equally many 5-10 minute absences.


Removing auto-harvesting already solved the lag issue and the issue of it becoming the botanist for you. The PR mentions that the bot "keeps them alive", and that might have been the intent but that's not actually the result in certain circumstances. It was actually kind of frustrating to leave for a short while to go cook a few burgers and come back to find one or two plants either dead or very close to dead, wondering what was happening.

I what I'm trying to convey is...
I can water, de-weed, and feed the plants on my own, it's a bit tedious as a Diona but it's doable (and sometimes I actually like the distraction of mindless ss13 jobs). I usually get the bot if I know that I won't be in the room all the time, especially on lowpop shifts, or just shifts without a chef but with hungry crew. Leaving the botany room to go talk to people, especially I try to be social and not just take their orders and leave, then cook the food and serve... that can easily be enough time, especially with a little bad timing, to let the bot turn off and let the crops die off.

It's not a huge issue, it's just a kind of confusing annoyance. I get why the PR was made, I even remember the auto-botany days of lagging crops, but that issue was fixed just by removing the auto-harvesting.

**Comment by ktccd0** [comment]
Also, as an added bit, in case nobody agrees and this is just an easy closed-and-done non-issue... could we maybe put in something in the interface that lets us know about the idle-timer? I had to go read the github code to figure out what was going on, nobody I asked ingame had any clue whether it was bugged or if it was something intentional, and we had no idea what the conditions were until some testing let me estimate it to something vague like "if left alone for 10-ish minutes, it turns off", which wasn't even correct. IDK how long 150 units of time is, but if it's seconds then that's just 2.5 minutes (which is so short that I suspect that the units can't *really* be seconds, or I'd have it shut off every single time I left the room to do anything at all).

**Comment by Heroman3003** [comment]
The behaviour reported in issue itself is intended.
