### ISSUE TITLE
Thrown objects hit windows that aren't in the way

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1212]
#### Brief description of the issue
When thrown, objects will hit any window in any turf it passes through, regardless of the direction of the window.

#### What you expected to happen
Thrown objects to only impact windows that actually are blocking the direction the object is thrown thru.

#### What actually happened
If a window is in a tile a thrown object crosses, it hits the window and stops.

#### Steps to reproduce
- Pick up anything.
- Stand along a line of windows on your line of turfs (See screenshot for what I mean)
- Throw the object along the line of windows
![image](https://cloud.githubusercontent.com/assets/14110581/24084577/0b5422ca-0cc3-11e7-93f7-cf45874eb418.png)

**Comment by MASMC** [comment]
Wait, if it's merged, why is this issue not closed? Hmmm...
