### ISSUE TITLE
After a Tesloose, the "Main" SMES of Stellar Delight fails to output power.

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#12138]
#### Brief description of the bug
If a tesloose causes wiring to be damaged in the hard storage (for instance, breaks the plating the SMES sits on or similar), after repairs (and proper wiring) the Main SMES fails to output power.

Rebuilding the Main SMES elsewhere and using funny/ugly wiring fixed the issue, see attached screenshot.

This has occured twice now, with different engineers trying to fix it - so it's very likely not PEBKAC error.

#### What you expected to happen
For the Main SMES to output power.

#### What actually happened
The Main SMES did not output power, despite drawing adequately.

#### Steps to reproduce
- Have a Tesloose occur which damages the wiring of the Main SMES (its output wire).
- Repair Tesloose, replace knotted wire under Main SMES and the gridchecker just like the cables are at roundstart
- No power output. 

#### Code Revision
Server revision: B:release D:
Commit: 88987e534559b58da8d770f20e54fb918becec97 
 

#### Anything else you may wish to add:
- It is possible to reliably fix the issue by doing the following (please forgive the ronald mcdonald colour scheme. Had to hotwire before figuring out how to fix)
![image](https://user-images.githubusercontent.com/20523270/151873296-b2fccfea-3f35-4e01-9432-70291fe333cb.png)

Where the important step seems to be running a knotted cable from elsewhere south of the gridchecker, then up into the gridchecker.

**Comment by Heroman3003** [comment]
It may just be that cable under smes itself got destroyed without smes itself being so.

**Comment by TankTheBirb** [comment]
That was one of the first things I checked, as well as throwing cables down under the gridchecker just in case it was that. IIRC, the thing was disassembled and rebuilt on the same spot and did not function despite being set up correctly on a knotted wire. 

In this case, the plating and lattice was destroyed below the main SMES, they were rebuilt, and it did not work until moved to the new spot.

**Comment by TankTheBirb** [comment]
Ok so I figured out why this is, the issue is that if you build an SMES on top of an existing power cable, it does not connect the output to the power network (input works fine). Instead you have to connect a cable after building it. The solution I found was to put the cable under the SMES last, which is unfortunately VERY inconvenient in some SMES arrangements. It then forces a power network update and in a few seconds, the SMES should work just fine.

This is an issue with power code and is observable when making new SMES units.
