### ISSUE TITLE
Corner sofas are on the wrong layer

### ISSUE THREAD

**Issue by ktccd0** [VOREStation/VOREStation#12154]
#### Brief description of the bug
The corner-sofa sprite is in some cases drawn on the wrong layer.

#### What you expected to happen
For players to be able to be on top of the sofa corner.

#### What actually happened
The sofa corner refuses to yield to our power!

#### Steps to reproduce
- (Step 1) Make sofa corner that you should be drawn on top of.
- (Step 2) Get on top of it
- (Step 3) Fail and be sat upon by the sofa.

#### Code Revision
Server revision: B:release D:
Commit: [88987e534559b58da8d770f20e54fb918becec97](http://127.0.0.1:51301/tmp7100/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/88987e534559b58da8d770f20e54fb918becec97%22%3Ehttps://github.com/VOREStation/VOREStation/commit/88987e534559b58da8d770f20e54fb918becec97%3C/a%3E)

**Comment by BigBababooey** [comment]
Worth noting some corner sofas are on the correct layer, such as the red corner, wheras the black corner is not. It's inconsistent and odd

**Comment by ktccd0** [comment]
Thank you @BigBababooey, this was a big clue to the source of this whole mess. Fixing it now, hopefully.
