### ISSUE TITLE
Winged Flight allows flight up to the midpoint... and immediate death.

### ISSUE THREAD

**Issue by BigBababooey** [VOREStation/VOREStation#12182]
#### Brief description of the bug
A player using winged flight observed that clicking move upwards while flying in the Tether floor 3 bar did indeed seem to allow them to move upwards. Upon doing so they immediately were moved up to the midpoint, which then immediately shunted them out into space, which immediately caused them to fall from the sky and plummet to their death.

#### What you expected to happen
A ceiling to prevent the movement... or anything to stop what will allow you to fly to literal space.

#### What actually happened
The player was not stopped, and did indeed transition up a Z level, resulting in their immediate death.

#### Steps to reproduce
- Have winged flight on a character
- Activate winged flight
- select move upwards while in the surface 3 bar (and possibly elsewhere on surface 3) and watch as you die the moment it is completed as a result.

#### Code Revision
- Server revision: B:release D:
Commit: 9ee2991fe46810f7638ae30a45612a114803f6b5

**Comment by FartMaster69420** [comment]
This is due to level three lacking roofing tiles.
