### ISSUE TITLE
Xioen Diona Whitelist

### ISSUE THREAD

**Issue by Xioen** [VOREStation/VOREStation#1220]
Making an issue about my whitelist entry so it can be added
Link To Post: http://forum.vore-station.net/viewtopic.php?f=45&t=853

**Comment by MASMC** [comment]
So THIS is why I rarely see Dionae on the station... hmmm....

**Comment by SpadesNeil** [comment]
Has this been resolved yet?

**Comment by Xioen** [comment]
No, it hasn't :T
