### ISSUE TITLE
Singulary pull leaves ghost items in hand slot

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1221]
#### Brief description of the issue
When singularity pulls an item from your hand, it leaves the item shown in your hand slot on the hud, with no way to get rid of it.

#### What you expected to happen
Screen icon to disappear from the hand hud slot

#### Steps to reproduce
- Have size 5 (STAGE_THREE) or greater singularity.
- Be nearby to the singularity with something in your hand.
- Have a wall or window or something between you and it so you have time to observe what happens.
- Wait for it to pull
(do not attempt)

**Comment by MASMC** [comment]
Hm. Seems it's not clearing the icon, I feel like we need to perform the
drop, then delete the item. Could be a Polaris bug, as well.

**Comment by Leshana** [comment]
Where did you test this? It has been merged into Polaris, but not into VOREStation yet.   I tested this and it worked fine for me with the fixed code.

**Comment by MASMC** [comment]
Ah, that's why. I tested on our codebase.
