### ISSUE TITLE
Rapid Pipe Dispenser Tool - Does Not Assign Device's Pipe Layer Properly

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#12243]
#### Brief description of the bug
The RPD tool is meant to be able to assign a Pipe Layer (1 thru 5) to allow devices and pipes to be on the same tile but in different 'loops'. The RPD and apparently the Pipe Dispenser machine (that you have to pull around an wrench-secure to use) only dispense Devices (like Pumps and Filters) on Pipe Layer 2 regardless of the selected Pipe Layer.

#### What you expected to happen
Being able to dispense devices on Pipe Layers 1, 3, 4, and 5.

#### What actually happened
Only able to dispense devices on Pipe Layer 2.

#### Steps to reproduce
- Acquire a Rapid Pipe Dispenser tool or Pipe Dispenser machine
- Open the respective menu
- Select a Pipe Layer (RPD is only labeled 1-5, machine spells out Regular/Supply/Scrubber/Fuel/Aux)
- Print something from the Devices category (Connector, Vent, Scrubber, Pump, etc)
- View variables, see that it is set to Pipe Layer 2 regardless of what you chose
- Lament

#### Code Revision
Server revision: B:release D:
Commit: [182d38c68a870005c410214f9fd4a8557b8b2b72](http://127.0.0.1:57300/tmp21172/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/182d38c68a870005c410214f9fd4a8557b8b2b72%22%3Ehttps://github.com/VOREStation/VOREStation/commit/182d38c68a870005c410214f9fd4a8557b8b2b72%3C/a%3E)
 

#### Anything else you may wish to add:
- The Rapid Piping Dispenser's menu should be changed from "Layer 1-5" to match the Pipe Dispenser's written-out proper names, for ease of use.
![image](https://user-images.githubusercontent.com/80289265/154215720-8ec25a7f-c2aa-4797-a350-bd8a21eaf342.png)

**Comment by Runa-Dacino** [comment]
Last time I used the RPD, which is about a week - selecting layers worked just fine.

Could easily lay 5 pipes parallel to each other. 

Is it possible the vv is showing something else?

**Comment by ResidentCody** [comment]
The issue isn't pipes, but devices. Pumps, Filters, et cetera. The gas pipes themselves layer fine.

Immediately after submitting this I tried to force it, and it turns out that the devices are having their var set to layer 2 every time it's wrenched and unwrenched - AKA when it's changed from a fitting to the actual pump. So I can't even varedit it to "piping_layer = 4" and attach it, it just goes right onto Layer 2.

**Comment by ResidentCody** [comment]
I just tested the following:

Connector (PL2) -- Straight Pipe (PL2) -- Gas Pump (PL2) = Works normally, pump connects.
Connector (PL2) -- Straight Pipe (PL2) -- Gas Pump (PL4) = Works abnormally, pump connects and changes to PL2 when wrenched.
Connector (PL2) -- Straight Pipe (PL2) -- Straight Pipe (PL2) = Works normally, pipe connects.
Connector (PL2) -- Straight Pipe (PL2) -- Straight Pipe (PL4) = Works normally, pipe does not connect.
Connector (PL2) -- Straight Pipe (PL2) -- Straight Pipe (PL4, varedit to PL2 before wrenching) = Works as expected, pipe connected as if it had been set to PL2.

**Comment by Heroman3003** [comment]
Devices straight up do not work with non-basic layer either way. That's just part of devices. Layer only applies to regular pipes, manifolds, etc. Not anything 'functional'.

**Comment by ResidentCody** [comment]
Devices will not connect to pipes not sharing the same layer. I am not trying to put five pumps onto one tile, I am trying to connect a PL5 pipe to a gas pump. This is an issue I have noticed in the past, though I did not realize what the problem actually was. The workaround is to utilize things like universal manifolds that attach to everything.

**Comment by Heroman3003** [comment]
It's not an issue. Devices are just not meant to work with anything but base layer pipes, other than universal manifolds which exist specifically to convert one pipe type to another.

**Comment by ResidentCody** [comment]
This _appears to be_ something to do with the fuel pumps specifically. Maybe it's not an error with the RPD and atmos code is just that inherently jank.
