### ISSUE TITLE
Farwa language

### ISSUE THREAD

**Issue by MASMC** [VOREStation/VOREStation#1228]
#### Brief description of the issue
Upon using the language implant, made with RnD, you should be able to speak all known languages. This is not the case with Farwa.

#### What you expected to happen

Allow the player to speak with the Farwa language, upon using the language signal (In my case /), which is 9.

#### What actually happened

(XXX) says, "/9 Farwa"
(XXX) says, "Farwa failed, we'll get 'em next time."

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

-Get RnD to a nice level, allowing you to get language implants.
-Print the implant and get an implanter.
-Implant yourself with the implant through the regular process
-Type "say *smile" to activate the implant
-Type "say ,9 <text>"
-Notice as you do not have Farwa speak.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-03-21
4cc20a72b086c16c64e56b44263e215e9549e60f 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
The image is actually VERY recent, and taken while I was playing on the server, to show that I did not just give myself the language.
![languagefails](https://cloud.githubusercontent.com/assets/9438930/24173881/6693ba2c-0e64-11e7-98ea-39c8f57b18bb.PNG)

**Comment by MASMC** [comment]
Oh, the implant also can't be disabled.

**Comment by Arokha** [comment]
Disabling it isn't a thing, like that's just not a feature. On implanting it, it just teaches you all those languages. They're added to your languages var and you can use them from then on.

Also the monkey languages conflict with other languages. For example 6 is EAL *and* monkey. You're not supposed to know them all at the same time.
