### ISSUE TITLE
Respawn timer is 15 minutes

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#123]
Lines in question:
https://github.com/VOREStation/VOREStation/blob/9e19acb3dcd3610f79e4b679df9f661394c68c90/code/modules/mob/mob.dm#L333-L394

Respawn timer is currently 15 minutes. On the old code it was 1 minute.

**Comment by SpadesNeil** [comment]
Upgrading to severe because this is an obnoxious problem that should be fixed urgently.

**Comment by SpadesNeil** [comment]
Cryopod any other methods of early departure should have relevant timers adjusted to be less than the respawn timer.
