### ISSUE TITLE
Music Request

### ISSUE THREAD

**Issue by MASMC** [VOREStation/VOREStation#1232]
MUSAK TO ADD?
https://soundcloud.com/radixan/midilovania-undertale-megalovania

**Comment by ArbyTheDragon** [comment]
Please no.

**Comment by SpadesNeil** [comment]
I'm pretty sure there's a copyright issue anyway.

**Comment by ArbyTheDragon** [comment]
I understand that MIDIs are **always** protected by creative commons unless you sell them. It's almost like writing new music.
As far as Undertale goes- I think Toby Fox would be cool with copyrights _so long as we asked him and worked the situation out_.

**Comment by Screemonster** [comment]
Lolwat.

The format you render your song in doesn't automatically apply any particular licence. Unless the creator of the midi says it's CC, it's not CC.

**Comment by ArbyTheDragon** [comment]
Well I never said I was right.
I guess MIDI is just really under the radar because not many people have a taste for it?

**Comment by SpadesNeil** [comment]
Marking won't add until copyright ambiguity is worked out.

**Comment by Arokha** [comment]
The ambiguity has existed since like 1992 so keep waiting, lol.

**Comment by SpadesNeil** [comment]
I meant about this specific song you clod.

**Comment by JoanRisu** [comment]
I imagine this uses the whole original song as well despite transformative use, which makes it unfavorable to fair use.
