### ISSUE TITLE
Baking cookies creates Caps Ahoy cookies... again/still

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#12376]
See description.

I get the regular cookies, and it's home-baked goodness.

Cheap on-brand cookies, ew yucky. Look how stale they are.

#### Steps to reproduce
- Preheat the oven.
- 3 cups of flour, 2 cups sugar, a stick of butter (do the cookie recipe)
- empty the tray, receive carp ahoy cookies, all wrapped up in plastic

- 9c4cbdaf1cbe37c2182ea4ae521f43e4f0340d62
 

#### Anything else you may wish to add:
- #10423
- This is the same bug from back then most likely since it is STILL happening. I dunno why arokha called it temporarely intended because this is just a bug and definitly not intended, even if we can point at custom food creation that's been in the game since forever.

**Comment by Heroman3003** [comment]
Someone replaced actual cookies with snack just to add them to machine instead of adding new ones and that's just EUGH.

**Comment by GhostActual** [comment]
Give me ten minutes and I'll have all three of your issues fixed

**Comment by Heroman3003** [comment]
This should prolly be closed now
