### ISSUE TITLE
Absorbing Disables Borgs

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#12374]
#### Brief description of the bug
Being absorbed renders a borg unconscious and thus unable to see/post emotes or subtles.

#### What you expected to happen
For absorption scenes to function like they do with human prey.

#### What actually happened
Being absorbed knocks the borg unconscious, blocking them from hearing or seeing posts made. (Note, battery charge was over 40% before, during, and after the absorb.)

#### Steps to reproduce
- Eat a borg
- Absorb them
- They can no longer continue the scene

#### Code Revision

Server revision: B:release D:
Commit: 9c4cbdaf1cbe37c2182ea4ae521f43e4f0340d62

**Comment by Cyantime** [comment]
Being absorbed weakens mobs, and borgs are put unconscious by any form of stun.
