### ISSUE TITLE
Jukebox emp feature

### ISSUE THREAD

**Issue by drexample** [VOREStation/VOREStation#1237]
#### Brief description of the issue
We need jukebox to play Tom Jones's "What's new, pussycat?" on repeat when hit with EMP. And sometimes rarely play "It's not unusual"
#### What you expected to happen

Jukebox lacks such an important feature. Like it's the main thing that needed on the server. Nothing else matters.

#### What actually happened

----

#### Steps to reproduce
- EMP the jukebox
- Enjoy the timeless classic
- Watch people around suffering

**Comment by SpadesNeil** [comment]
please no

(also I suspect copyright issues)

**Comment by ArbyTheDragon** [comment]
Are any creative renditions of the song similarly copyrighted?
(I'M SORRY I CAN'T ACTUALLY OFFER ANY KNOWLEDGE ON IT ;-;)

Cause if not, we could possibly use that (With permission, because we're nice <3)
I do like the idea of the jukebox playing something 'unusual' or obnoxious when EMP'd.

**Comment by JoanRisu** [comment]
Our purposes would be using the music, whether we host it or not, as entertainment and that usually falls under the _unfavorable_ side of fair use. If you need a crash course on fair use, I can explain.

I also imagine it would be one thing if you, the user, was using a player that allowed external usage for any content as opposed to us, the hosts, which control the player in it's entirety and therefore responsible for the content played within. 

For example, Yukari in our Discord. As a user, all you need to give her is a soundcloud or youtube url and she'll start playing the song for you and anyone around you. That's something prompted by the user and is not necessarily controlled by us as far as content goes and both youtube and soundcloud is generally okay with that save for a few music labels that explicitly say you must view the music on the websites themselves.

With the html5 antilag media player, the admins control the player and content through both hosting and maintenance, making us significantly more responsible for what is played. Not to mention off-server locations for MP3 files, which by the way the format _must_ be, may not be and probably aren't legitimate sources making it a pretty shady practice to try and attempt this and puts this server in danger and I dunno if you know this but we can't afford copyright attorneys. 

Especially, unfortunately, in regards to _What's New Pussycat_. It was made before legislation was passed which explicitly protects music, thus making the cutoff for the copyright at January 1, 2067.

**Comment by SpadesNeil** [comment]
See you in fifty yeaaarrrrsssss! :U

**Comment by JoanRisu** [comment]
Just to add, we'd have to license the song in this case and I am pretty sure whoever is the current copyright holder would not give one to us considering the theme of this station.

**Comment by ArbyTheDragon** [comment]
2067? What the fuck. Copyright laws are stupid.

**Comment by Screemonster** [comment]
I musta missed this at the time but I just wanna let you know your reference was not lost

https://www.youtube.com/watch?v=fo8-EQEO_BM

**Comment by drexample** [comment]
@Screemonster 
I actually went and did that.

https://youtu.be/5DRjVHubv-w
