### ISSUE TITLE
Peanut Butter is broken

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#12384]
#### Brief description of the bug
Can't create peanut butter

#### What you expected to happen
Mix stuff into a beaker, get peanut butter

#### What actually happened
Get cooking oil

#### Steps to reproduce
- Mix the following into a beaker
- Mix in: 2u Peanut Oil, 1u Sugar, 1u Table Salt
Catalysts: 5u Universal Enzyme
Watch it turn into cooking oil

#### Code Revision
- 9c4cbdaf1cbe37c2182ea4ae521f43e4f0340d62
 

#### Anything else you may wish to add:
- We don't need cooking oil. We don't need it for anything, it is a useless recipe, please just get rid of the recipes for making cooking oil. If we ever want/need it, we can order a tub of it from cargo.

**Comment by GhostActual** [comment]
The thing is, there is no way that this should be possible, I'm not sure why this is happening, will test

**Comment by Runa-Dacino** [comment]
This can be closed as per #12388 .
