### ISSUE TITLE
Can't juice jelly donuts

### ISSUE THREAD

**Issue by drexample** [VOREStation/VOREStation#1238]
#### Brief description of the issue

Chef's All-in-one grinder can't juice jelly donuts

#### What you expected to happen

A healthy glassfull of donut juice.

#### What actually happened

It just didn't juice the donut. Just turned it into nutriment.

#### Steps to reproduce
- Put a jelly donut in the grinder
- Turn on the grinder
- Get disappointed

**Comment by SpadesNeil** [comment]
That doesn't sound like a bug what so ever. It's a donut. It has no juice. Jelly, sure, but no juice.

**Comment by JoanRisu** [comment]
But Ace, we as a nation try to liquidfy everything like salads and fruits and whatever else in our efforts to find stupid shortcuts to being healthy. y not donuts

**Comment by SpadesNeil** [comment]
Because all of those have juice in them.

**Comment by JoanRisu** [comment]
I have been defeated.

**Comment by drexample** [comment]
What do you mean jelly donuts don't have juice in them?
Jelly donuts are the juiciest things in the universe.
