### ISSUE TITLE
Cherry Candy Grub recipe is broken

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#12383]
#### Brief description of the bug
Can't create the cherry version of the candy grub.

#### What you expected to happen
Put grub and cherry into microwave, get candy grub

#### What actually happened
Burned mess

#### Steps to reproduce
-Put this stuff into the microwave
-Ingredients: 1x grub
-Coating: Must be uncoated
-Fruit: 1x cherry
-Watch it explode

#### Code Revision
- 9c4cbdaf1cbe37c2182ea4ae521f43e4f0340d62
 

#### Anything else you may wish to add:
- The berry candy grub works. The grapes candy grub MIGHT not work, I didn't have a chance to test it yet but it's a 50/50 at this point.

**Comment by GhostActual** [comment]
This one is broken cause the kitchen tag for the cherry is broken in the recipe

**Comment by Heroman3003** [comment]
This should prolly be closed now
