### ISSUE TITLE
Replace 'black on white' interfaces with NanoUI style interfaces

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#1239]
Not actually replace them with NanoUI, too time consuming. Until a need arises for that, they can be the 'fake' nanoui style.

What things in the game still have the old style?

- [ ] Clicking materials in-hand to build things
- [ ] Airlock electronics
- [ ] Autolathes
- [ ] R&D Consoles
- [ ] Circuit interface
- [ ] AI crew manifest (think this is also the admin crew manifest)
- [ ] Stripping interface

**Comment by Screemonster** [comment]
Airlock electronics.

**Comment by Very-Soft** [comment]
Autolathe and RD consoles

**Comment by Very-Soft** [comment]
Oh also, the AI's crew manifest

**Comment by Very-Soft** [comment]
Also the pickpocket/player looting interface is still black and white

**Comment by Very-Soft** [comment]
Cargo's Supply Shuttle interface too~

**Comment by lbnesquik** [comment]
@Arokha Did Ai manifest
