### ISSUE TITLE
Oh no, we don't log when admins open the VV Panel. This is important for huge reasons.

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#1247]
#### Brief description of the issue
We should probably start logging when an Admin opens a VV panel. 

This is a good thing for both admin and player to have because it prevents sanctimonious BS from happening like accusations of **_#MetaGaming_** and assists us when reviewing such accusations to a person's character. **_WE MUST AT LEAST EXPLORE THIS A LITTLE BIT._**

#### What you expected to happen
A log of a VV panel being opened for an item.

#### What actually happened
zilch happens.

#### Steps to reproduce
1. Right click item to use magic meta powers on.
2. Look for the magic VV panel button for said item you want to use your magic meta powers on.
3. Click.
4. No dang log for the VV panel button being clicked! _This is a problem for both admin and player._

#### Code Revision
Server revision: release - 2017-03-21
4cc20a72b086c16c64e56b44263e215e9549e60f 
 
#### Anything else you may wish to add:
Maybe a shaming message telling the admin they're bad for having powers. I dunno. It's 1 in the morning and I'm obsessively upset so you can probably ignore this part or edit this issue in its entirety. 

I'm also putting this high on the list cause I'm livid.

**Comment by Cameron653** [comment]
Going to take a quick stab at this since it should be simple enough from a quick look at it.

**Comment by Arokha** [comment]
We're making spite issues now? Also, we're the only ones who can see the logs. Why would someone believe the person/group of people they're accusing of metagaming when they say "Oh yeah the logs say we didn't do it".

**Comment by JoanRisu** [comment]
Because we have a full staff that is encouraged to disagree and challenge each other including our host when one or more admins are wrong about what happens in an incident? This isn't just for players, it's for the staff to hold each other accountable for their actions. 


But if this rather harmless addition, spiteful or not, isn't helpful then just throw this out. Sorry for putting up something like this up.
