### ISSUE TITLE
Exposed pipe on map in mining (z5)

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#125]
Pipe at south end of mining outpost has exposed pipe showing.

**Comment by SpadesNeil** [comment]
Screenshot?

**Comment by Arokha** [comment]
Maybe throw in those digital-looking blue floor tiles like robotics has next to their chargers or w/e?

![capture](https://cloud.githubusercontent.com/assets/15028025/15458778/32e55438-206c-11e6-80cf-befde38e9cd9.PNG)

**Comment by SpadesNeil** [comment]
Also yea where the hell are our chargers? I've seen this problem across the map.

**Comment by SpadesNeil** [comment]
Not sure if by design but it definitely looks stupid.
