### ISSUE TITLE
Trash Cans Cannot Be Deconstructed Or Moved

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#12567]
#### Brief description of the bug

/obj/structure/closet/crate/bin

These things are secured more tightly than an oyster holds onto pearls. They occasionally get in the way of people who do renovations or otherwise block travel, and it would be nice to have a way for them to be moved.

#### What you expected to happen
For the ship to not have immovable, indestructible trashcans. 

#### What actually happened
It's like a mime pushing against an immovable object, the things just don't budge! It can probably be destroyed with weapons-fire since it is technically an anchored crate but that obviously isn't a good solution.

#### Steps to reproduce
- Load into the NRV Stellar Delight map
- Find one of the many trash cans around (the ones with the flip-up lid, not Disposals receptacles)
- Attempt to move it, be unable to. It is anchored. It does not have a way to be un-anchored.
- Attempt to deconstruct it, be unable to. It is a crate. It cannot be deconstructed. Not without guns or explosions.

#### Proposal
Add some form of anchor toggle to the /closet/crate/bin so people can move them around.

**Comment by foopwo** [comment]
I will note on this issue that this specifically refers to the _varedited_ bins placed all around the Stellar Delight map.
