### ISSUE TITLE
Music Request: Pepper Steak

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#1256]
https://www.youtube.com/watch?v=-1EPegIzD2M

For the juuuuke, Maybe hacked juke?

**Comment by SpadesNeil** [comment]
The source is in French and I have no idea what the copyright status is... http://www.rpg-maker.fr/index.php?page=jeux&id=425

**Comment by JoanRisu** [comment]
I don't see any license on it as far as I can tell. The OST is found here http://www.rpg-maker.fr/index.php?page=ost&id=18

But again, no licensing or copyright status,

**Comment by Arokha** [comment]
No work being done on this, so closing it until someone wants to do work on this, if ever.
