### ISSUE TITLE
Officer Beepsky QOL and Implementation

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#1257]
#### Brief description:
- Add Officer Beepsky/generic securitron to the map in patrol mode
- Make security bots un-grabbable

 
#### Anything else you may wish to add:
We need to have Beepsky return, now that the patrol paths are functioning again. Either Beepsky or a generic securitron, spawn on map in patrol mode.

Problem is, bots are mobs now. They can be grabbed and eaten, stuffed into disposals, or otherwise vandalized. Which is un-immersive as all get out. Even a simple bot like Beepsky should be able to recognize they are being attacked and respond. The most simple fix is to make them un-grabbable.

I specify this because we've already had this problem several times since code base change, and while the main problem players were removed, the critical weakness remains.

**Comment by MASMC** [comment]
This is actually a great idea. How would one go about making it un-grabbable, though?

**Comment by Arokha** [comment]
Leshana and I talked and it's probably unusual that he'd be UNGRABBABLE. Maybe he should just BATON you if you grab him, thus falling over and making you drop the grab anyway. That way it's not some weird exception (ALL mobs are grabbable) and seems like a reasonable response. CITIZEN, YOU ARE INTERFERING WITH MY DUTIES.

**Comment by SpadesNeil** [comment]
"DO NOT INTERFERE WITH SECURITY OPERATIONS."

**Comment by Arokha** [comment]
Um, actually, I just tested this. You can't grab securitrons? Clicking them on ANY intent opens the UI.
