### ISSUE TITLE
Bomber jacket and black utility uniform bugs

### ISSUE THREAD

**Issue by Dingosilver** [VOREStation/VOREStation#1261]
The bomber jacket item from the "Suits and Overwear" part of the loadout character creation section no longer allows one to wear pants underneath. And, alternatively, the 'utility, black' item from the "Uniforms and Casual Dress" section of the loadout screen simply displays bold red letters above the character which I have been told symbolise the item not having a sprite.

Previous to now, my character has been able to wear the bomber jacket over the black utility uniform, allowing them to cover their entire body other than their head.

Now, putting on the bomber jacket leaves my character with only their underwear on underneath, and putting on the black utility outfit leaves my character with red letters above them.

**Comment by Arokha** [comment]
This is fixed in Polaris, so will be fixed next sync.
