### ISSUE TITLE
Primitive clothes shouldn't have suit sensors

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#12620]
This probably easy to fix, I'm just lazy

**Comment by Heroman3003** [comment]
I'm like 70% sure that all undersuits are hardcoded to have sensors, but making sensors locked into disabled should be possible.

**Comment by Very-Soft** [comment]
you could probably just default them to off and remove the verb for adjusting sensors on them/make that verb tell you 'there's no sensors, idiot'

**Comment by lm40** [comment]
Tactical turtleneck does not have sensors which is why I said it's probably an easy fix unless that has some kind of insane spaghetti modification to make it like that.
