### ISSUE TITLE
When Resetting from Medihound or K9, sprite position remains offset.

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#1263]
#### Code Revision
release - 2017-03-27
be01365723108b8f3cfebcf4d6e30dd945fe3afc 

https://gyazo.com/4760111d2571bedeaeb0e307aa043b9c

**Comment by Cameron653** [comment]
This was, to the best of my knowledge, fixed in the old code. I'll dig around and see if I can find it.
