### ISSUE TITLE
Ventcrawl Bugs

### ISSUE THREAD

**Issue by liache** [VOREStation/VOREStation#12654]
Maint drones can't ventcrawl, and nobody ventcrawling can hear anything, including themselves.

I expected to at least hear LOOC or passengers poses inside, or my own text. They couldn't hear any of it either. If you're not meant to hear/see stuff going on outside the vents, that makes sense, but it currently blocks pretty much EVERYTHING. With drones, I expect to be able to ventcrawl at ALL.

Ventcrawl has two current bugs I've noticed-- First, maint drones can't ventcrawl, apparently due to having an emissive blocker that's not whitelisted (as I've noticed is the case on other code), and ANYONE ventcrawling doesn't appear to be able to hear anything, including themselves, prey inside, or LOOCs. I understand if ventcrawling creatures are not supposed to be able to communicate/eavesdrop on critters outside, but the current code seems way too aggressive?

O'Brimn: I jusht wanted to feel birb squirmsh. Wai no feel?

**Comment by ItsSelis** [comment]
This issue was fixed of the following PRs:
- #12663
- #12665
