### ISSUE TITLE
Licking needs a ratelimit.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1266]
#### Brief description of the issue
Both licking as a mob AND with the dogborg thing can be spammed as fast as you can click. The dogborg one is worse because it also makes a noise.

#### What you expected to happen
For people to be reasonable, but no.

#### What actually happened
Kenzie Houser licks K-9 Shadow!
Scree chirps.
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
Pepper Steak looks down at her belly, then at the hot pocket, then back and forth a few times more. Her brow furrows.
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
 [Common] Arrivals Announcement Computer states, "Bellatrix Van Allen, Surgeon, has arrived on the station."
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
Kenzie Houser licks K-9 Shadow!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
Kenzie Houser licks K-9 Shadow!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
K-9 Shadow affectionally licks all over Kenzie Houser's face!
Roiz Lizden says, "I'm sssorry, I didn't really get your ansswer yet, mime lady..."
  Pepper Steak/(Seiga): pls.
  Scree/(Scree): holy shit
Kenzie Houser says, "I can't."
  Scree/(Scree): quit the spam

#### Steps to reproduce
stand next to someone
mash lick until everyone screams at you to stop.

#### Code Revision
Server revision: release - 2017-03-27
be01365723108b8f3cfebcf4d6e30dd945fe3afc

**Comment by SpadesNeil** [comment]
Methinks a cooldown would be nice.

A certain number of licks before your tongue is dry.
