### ISSUE TITLE
Material Scanner goggles does not protect against phoron

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#12706]
#### Brief description of the bug
Material scanner goggles, despite being goggles, do not protect against phoron and make you blind.

#### What you expected to happen
By wearing material scanner goggles, synth miner should be able to walk around outside Tether without going blind.

#### What actually happened
Went blind within second of airlock opening.

#### Steps to reproduce
- Make a synthetic character
- Put on material scanner goggles from mining
- Leave the Tether and go outdoors
- Become blind

#### Code Revision
Server revision: B:release D:
Commit: [e6a2c1477fdedb74641ab07bc7cc264f1f794f5c](http://127.0.0.1:63841/tmp13636/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/e6a2c1477fdedb74641ab07bc7cc264f1f794f5c%22%3Ehttps://github.com/VOREStation/VOREStation/commit/e6a2c1477fdedb74641ab07bc7cc264f1f794f5c%3C/a%3E)
 

#### Anything else you may wish to add:
- Easily fixed by wearing the normal goggles in the emergency box and using NIFsoft, but I feel material scanner goggles should protect against phoron.

**Comment by Cyantime** [comment]
No vision-providing glasses are airtight, they aren't those kind of "goggles". You can wear a gas mask over them to provide plasma protection.
