### ISSUE TITLE
Secureitrons and ED-209 not reacting to being hit.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#1270]
#### Brief description of the issue
When hit, Secureitrons will not chase after the person who hit them.

#### What you expected to happen
The bot to stun and cuff the offender.

#### What actually happened
Just walked right on by.

#### Steps to reproduce
- (Step 1) Make a ED-209 or Securitron.
- (Step 2) Hit it.
- (Step 3) Watch it do nothing.

#### Code Revision
- Server revision: release - 2017-03-27
be01365723108b8f3cfebcf4d6e30dd945fe3afc

**Comment by SpadesNeil** [comment]
Did this get fixed?
