### ISSUE TITLE
Ghost white dialog boxes left over from a dialog box that's been opened

### ISSUE THREAD

**Issue by grz01** [VOREStation/VOREStation#12716]
Ghost white dialog boxes left over from a dialog box that's been opened

#### What you expected to happen

I'd expect dialog boxes when close to disappear as they have previously. Many now stay 'painted' on the screen and over any application, just just ss13 instances.

 Started start of last year - initially on one other vore instance and not on virgo, but it's just started happening on virgo, a few days ago for me. Please see screenshot https://gyazo.com/865d7992eb5f79e83ee3a1ba1b80b7c6

#### Steps to reproduce

Just connect up, main menu and manifest windows, probably others don't 'clear' cleanly off the screen anymore
Ghost windows are left after dialog boxes have been closed - you can see the results, and it's rather frustrating as it impedes the view and there is no way of wiping them, and stays on the screen even if the station instance is closed. They paint over every application on the desktop and the only way of wiping them is to log off or shut down.

**Comment by grz01** [comment]
Any thoughts on this issue yet please?

**Comment by Heroman3003** [comment]
It appears nobody has had an issue like this, and it does appear to be rooted in something beyond byond. I'll be closing this for now.
