### ISSUE TITLE
Using a Cryptographic Sequencer (Emag) on a Holdout Frontier Phaser does not consume a charge.

### ISSUE THREAD

**Issue by Skysteak** [VOREStation/VOREStation#12788]
#### Brief description of the bug 
Using a Cryptographic Sequencer (Emag) with active charges remaining will not have the aforementioned charges used up when applied to a Holdout Frontier Phaser. 

#### What you expected to happen. 
For an Emag charge to be expended.

#### What actually happened 
An Emag charge was not expended.

#### Steps to reproduce
- (Step 1) Acquire a functional Cryptographic Sequencer (Emag) and a Holdout Frontier Phaser.
- (Step 2) Use the Emag upon a Holdout Frontier Phaser.
- (Step 3) Witness that an Emag charge has not been expended.

**Comment by ItsSelis** [comment]
This issue was fixed in following PR:
#12814
