### ISSUE TITLE
Drugs for mental health can't be made in the chem dispenser

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#12787]
#### Brief description of the bug
A number of chemicals can't be made in the chemical dispensers on-station currently.

#### What you expected to happen
To be able to fulfill a player characters prescription for anti-depressants 

#### What actually happened
The chemical reaction that occured in the beaker resulted in no chemical, consuming the base ingredients in the process

#### Steps to reproduce
Create dylovene with nitrogen, silicon and potassium
Add in hydrogen and silicon for mindbreaker toxin
From that, add in either hydrogen for methylphenidate, carbon for citalopram or oxygen & inaprovaline for paroxetine
Ponder the mysteries of chemistry as the reagents poof into nothing and you're left with nothing in the beaker to show for the reaction.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
I suspect this is an issue with the above mentioned chemicals being repathed into `/datum/reagent/drugs` rather than the `/datum/reagent` they were before

**Comment by ItsSelis** [comment]
I can look into this :P
Already doing a patch for the medical notes as well.

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/pull/12767

Probably related

**Comment by ItsSelis** [comment]
Yeah, I suspected that too :o
