### ISSUE TITLE
Invisible atmo tape on map

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#128]
The little maintenance room behind the janitor's closet (the one with the hydroponics trays) has atmospherics tape over the door. There's no icon on the tape, so non-engineers are barred from progressing and have to altclick it.

**Comment by SpadesNeil** [comment]
Mentioned in #147 
> There's a door I can't go through at 160/201, I receive the message "You are not supposed to go past the atmospherics tape..." but there isn't even a tape.

So the coordinates are presumably 160x, 201y. I'll check it out.
