### ISSUE TITLE
Microwaves don't dispense items, and delete ingredients.

### ISSUE THREAD

**Issue by Thopterthallid** [VOREStation/VOREStation#12935]
#### Steps to reproduce
- Stick any items into a microwave, be they a valid recipe or spoiled mess.
- Turn on microwave
- Ding
- All items are deleted.

**Comment by FartMaster69420** [comment]
Microwaves seem to be functional in my testing. Which recipes specifically were giving issue?

**Comment by Thopterthallid** [comment]
I got some recipes to work but others didn't. I should have kept better
track. Anything that would yield a burned mess gave nothing. Fish and chips
didn't work, and basket of chips didn't work either.
