### ISSUE TITLE
Make bottles spinnable

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1293]
#### Brief description of the issue
People like playing truth or dare with dice and it's often clunky because RNG leading to people sitting out for ages and not getting a turn, and there's rarely exactly 6 or 20 people available to just pass the die around and let the die decide who gets picked.

#### Proposed fix
Give beer bottles a verb that randomly picks a person within a few tiles (enough to get everyone sat around the library table if the spinner is at one end should be enough, LOS would be plenty) and announces a visible message "X spins the bottle! It points at Y."

**Comment by SpadesNeil** [comment]
Better yet. Just spin the pixels.
