### ISSUE TITLE
Bunny ears

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#1294]
#### Brief description of the issue
The white ones show as black,

#### What you expected to happen
white to be white, maybe have a black set too

#### What actually happened
see above

#### Steps to reproduce
select the "Bunny, white" from vore tab ear selection on character setup

#### Code Revision
Server revision: release - 2017-03-30
0d259622c431d33aff96783b1133d8c6bcbdc99a 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
Fixed a while ago?

**Comment by SpadesNeil** [comment]
Marked as "needs testing" to be sure.
