### ISSUE TITLE
antiseptic mlem broke

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#12961]
#### Brief description of the bug
Lick Wounds Antiseptic Saliva Fixin' Mlems is janky now

#### What you expected to happen
So, normally, you aren't supposed to be able to target yourself with this trait, but now you can. I don't really see this as a huge deal either way due to the limitations of the trait, however, because of the way the trait functions, it makes everything so much more janky and clunky to use.

#### What actually happened
Using this trait brings up a pop-up of all mobs onscreen. You then have to find the mob you want to heal in that popup, of every single mob onscreen. You then have to select the limb you want to heal and if there's no damage there or its already healed, you have to repeat this again, and again. While mobs are actively moving, because keep in mind if at any point your mlem target moves a tile away, you have to restart, use the verb, find them in the popup, etc.

#### Steps to reproduce
- Use verb.
- An annoying popup box shows up, asking you to select from a list of every single mob on your screen INSTEAD of just those adjacent to you. You are also included in this list.
- Select the person you want to mlem.
- REPEAT ELEVEN FUCKING TIMES BECAUSE YOU SOMETIMES NEED TO DO THIS ANNOYING PROCESS FOR EACH. LIMB.

#### Code Revision
- 075ebd530d5e146056f5425d8b99d076f5a552cb 
 

#### Anything else you may wish to add:
- When this was first implemented, it was much smoother. No popup if you only had one patient. I think you either just had to click on the mlem target or it'd just automatically try to target the person closest to you. This was relatively better, because all you'd have to do is make sure your target is adjacent to you. Currently, this trait is so clunky to use that its actually a bit annoying. All other first-aid is easier to apply and also straight-up better because its usage cap is higher and you can use hotkeys to cycle through target limbs after clicking. The trait is now actually tedious to use, and it's actually a huge bummer for me personally because I really like this trait.

**Comment by ItsSelis** [comment]
This issue has been improved/fixed in PR #13009
