### ISSUE TITLE
slowdown post vore

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#12964]
#### Brief description of the bug
normal movement speed is slower when ejected from a belly and walk speed is even slower than that

#### What you expected to happen
normal walk speed

#### What actually happened
slowness

#### Steps to reproduce
- (Step 1)get eatten
- (Step 2)be let go
- (Step 3) be slower

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I was playing a proten at the time, reconnecting and reforming didn't bring back normal speed, but blob speed wasn't changed

purge reagents fixes it

**Comment by Heroman3003** [comment]
It's possibly related to numbing enzyme, which is intentional.
