### ISSUE TITLE
View Runtimes tracker doesn't show any runtimes

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#12967]
#### Brief description of the bug
The 'View Runtimes' verb doesn't show any runtimes

#### What you expected to happen
To see the runtimes

#### What actually happened
There are no runtimes. 

You might think 'well why is not having any runtimes a problem? That's good!'

What I mean is, there's runtimes, I can see them in the server log, but the View Runtimes tracker isn't listing them, and that's kind of a big deal for people who don't have access to the server logs to be able to look at and report on issues.

#### Steps to reproduce
- Have there be runtimes
- Use 'View Runtimes' verb

#### Code Revision
- B:release D:
Commit: 075ebd530d5e146056f5425d8b99d076f5a552cb

**Comment by Poojawa** [comment]
what runtimes has the runtime tracker produced. 

I ask because on my offline test it worked as intended.
