### ISSUE TITLE
Fluff 'Item' - Sepulchre + Daemon Language Whitelist

### ISSUE THREAD

**Issue by Yoshax** [VOREStation/VOREStation#1297]
Oh god I have no idea how to format. Also can I two apps in one?

**Item description:** Big Ol' Sexy Wings + Daemon Language Whitelist

**Sprites:** https://cdn.discordapp.com/attachments/271753646058766338/297182415527608330/demonwings.png

**BYOND Key:** Sepulchre

**Why your character should have this item:** Wings are sexier than the ones available in character setup and Demons are rad. Also Demons speak Daemon and Table told me to apply.

I didn't include character bit stuff cause I'm an indecisive sod and might rename the character >.>
Aro totally said that they can be not character-locked.

**Comment by JoanRisu** [comment]
Is personal policy to ask. Is just app for a species called demon, no powers associated known lore, yes?

**Comment by Yoshax** [comment]
Pretty much, yup.

**Comment by JoanRisu** [comment]
Sqrl approves then.

**Comment by Yoshax** [comment]
Yay!
