### ISSUE TITLE
Body Markings - Socks+Belly Colouration

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#1299]
#### Brief description of the issue
This body marking is irremovable and you are unable to colour it.

#### What you expected to happen
When I finish picking a colour, I want the marking to accept the change. Or,
when I press the 'minus' button, I want it to be removed.

#### What actually happened
Neither of the two things happened.

#### Steps to reproduce
- Put on Socks+Belly Coloration body marking
- Try to remove it or colour it.
- Doesn't work.

#### Code Revision
- Server revision: release - 2017-03-31
58b6386fceef18e5d9fd9483beedde3c6689fac2 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Is fixed
