### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jackthemang** [VOREStation/VOREStation#12995]
#### Brief description of the bug
When opening the code to compile it, i got errors telling me "_____ does not exist, deleting"

#### What you expected to happen
no errors.

#### What actually happened
unholy amount of errors.

#### Steps to reproduce
- (Step 1) install
- (Step 2) open

**Comment by Poojawa** [comment]
Is this in the map maker? The code file? 

Because this sounds like the .dme had everything unchecked. Just revert the changes to it in your github client of preference with DM closed and re-open it.

**Comment by Very-Soft** [comment]
can't replicate
