### ISSUE TITLE
Polaris Port - Per-Character Fluff Items

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#13]
Port fluff items that characters spawn with.

Removed the checkmarks because a lot of these were done or renamed.

**Comment by SpadesNeil** [comment]
Remove tsunderenyaa. They were pbanned.

**Comment by Arokha** [comment]
Done

**Comment by JoanRisu** [comment]
dun forget me and serkii's stuff

**Comment by JoanRisu** [comment]
- [ ]joanrisu:Joan Risu:/obj/item/weapon/storage/box/fluff/joanrisu
- [ ]eekasqueak:Serkii Miishy:/obj/item/weapon/storage/box/fluff/serkii

**Comment by JoanRisu** [comment]
Mark as Done:
scree:Scree:/obj/item/clothing/under/fluff/screesuit
molenar:Giliana Gamish:/obj/item/clothing/suit/storage/toggle/labcoat/fluff/molenar

Item entries done, needs modkit:
scree:Scree:/obj/item/device/modkit_conversion/fluff/screekit

**Comment by JoanRisu** [comment]
Mark as done/ported:
//scree:Scree
/obj/item/clothing/head/fluff/pompom

//zodiacshadow: ?
/obj/item/device/radio/headset/fluff/zodiacshadow

// OrbisA: Richard D'angelo
/obj/item/weapon/melee/fluff/holochain 

//eekasqueak: Serkii Miishy
/obj/item/fluff/permit/serkiimiishy

// bwoincognito:Tasald Corlethian
/obj/item/clothing/suit/storage/det_suit/fluff/tasald

// bwoincognito:Tasald Corlethian
/obj/item/clothing/suit/storage/det_suit/fluff/tas_coat

// joey4298:Emoticon
/obj/item/device/fluff/id_kit_mime 

//General Use
/obj/item/weapon/flag

// bwoincognito:Tasald Corlethian
/obj/item/weapon/storage/box/fluff/tasald
	name = "Tasald's Kit"

// jemli:Cirra Mayhem
/obj/item/weapon/storage/box/fluff/cirra

// joey4298:Emoticon
/obj/item/weapon/storage/box/fluff/emoticon

// joanrisu:Joan Risu
/obj/item/weapon/storage/box/fluff/joanrisu

**Comment by Arokha** [comment]
Reduced priority as 90% of the items are done, and the remaining ones are either stuffed into other files where they don't stand out and can't be found, or aren't getting moved. We'll just do those whenever someone notices. No point in moving things people don't use.

**Comment by SpadesNeil** [comment]
The flag should be moved out of custom items if it isn't already.

**Comment by Arokha** [comment]
It needs to be in some custom file, so, flags_vr.dm? Seems a bit silly for one item tho.

**Comment by SpadesNeil** [comment]
We have more than just the one flag and could add more in future. Otherwise, isn't there like a misc items file? I remember there being one.

**Comment by Arokha** [comment]
Not sure. Just make a flags_vr.dm. No harm in more files. Not going to run out of filenames. Can do it later though. I'm converting your craaaazy clown map for now.

**Comment by SpadesNeil** [comment]
Woo! Enjoy that nightmare of mapping. :D

**Comment by JoanRisu** [comment]
@Arokha Start putting together that config file when you have a moment. Look at the boxes first and take note of what is already in them so we don't double up items on accident. If you want, I'll comment on the items that are already boxed to mark them down.

**Comment by JoanRisu** [comment]
I'm guessing there is some code that needs to be readded in order for auto-spawning fluff items to work? @Ace

**Comment by SpadesNeil** [comment]
This should be resolved.
