### ISSUE TITLE
Test maps broken insanely

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#13016]
#### Brief description of bug
![](https://i.gyazo.com/148101e4e5b42057fd1aee48d47cec6e.png)

![](https://i.gyazo.com/de2db5fb9a8f35260f0f9a0d926aac76.png)

#### What you expected to happen

Not being able to view the area planes entirely.
Also multiple instances of unresponsive post-initializing, requiring reboots to actually get to a working state. 

#### Steps to reproduce

Compiled code on different versions of byond, most recently 514.1584
Have myself rank set as a Host for test server.
same issue happened on the minitest as did 'example' here. 

```
(E) (C) (M) plane = -25
(E) (C) (M) planes_visible = /list (1)
1 = 2
(E) (C) (M) plane_holder [0x2100950e] = /datum/plane_holder
(E) (C) (M) vis_flags = VIS_INHERIT_PLANE
```
were first test results of VV. 

subsequent checks were similar. I have no idea.

branch is 1:1 updated with master to 12996 PR, aka the Uno card game port. 
clean compile was used several times with dreammaker,  Am bewildered as to what else could have gone on.

**Comment by ItsSelis** [comment]
It certainly is strange. 
I am unable to recreate the issue, using the example/minitest maps work fine without seeing the areas.
(Also on the latest version/514.1584, also on the master branch synced with the latest PRs)

My guess is that this most likely is connected to the unresponsive post-initializing/reboots, making the server to fail to hide those tiles. 

Are there maybe any other errors or warnings, maybe in the console, that might show anything off?

**Comment by Poojawa** [comment]
Literally no issues other than my tgui testing fails. No runtimes or anything.

**Comment by Poojawa** [comment]
Dude idk what the fuck happened but it's fixed itself somehow
