### ISSUE TITLE
Utility Uniform, or, Utility, Black is not working.

### ISSUE THREAD

**Issue by Motherforkah** [VOREStation/VOREStation#1302]
#### Brief description of the issue
The sprite of Utility, Black, or, Utility Uniform, Black is not working. Instead of the sprite on body of a character, it shows a sign "S U I T"

#### What you expected to happen
For the suit to display on character

#### What actually happened
It didn't.

#### Steps to reproduce
- (Step 1) Choose Utility, Black in loadout, Uniforms and casual dress, near the end
- (Step 2) Go on-station, or look on the Setup Character screen.

#### Code Revision
- 7dadfcafeda2c67210672cb2b705af09ca8e1eb0

**Comment by Arokha** [comment]
This should be fixed in the latest release. Can you test and report back?
