### ISSUE TITLE
Gravity failure event messes up hardsuit activation

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1306]
#### Brief description of the issue
When I made the hardsuit activate and equip it's components, and I fell from gravity randomevent, I was unable to stand up on my own. After getting shaken up, Materiel scanners didn't work anymore, and the icons for hardsuit/jetpack/glasses didn't appear in the upper left anymore.

#### What you expected to happen
To be able to go on normally and use materiell scanners.

#### What actually happened
Despite activating materiell scannners in hand, they did absolutely nothing, and the hardsuits icons such as "Toggle magboots" never appeared again.

#### Steps to reproduce
- (Step 1) Float from gravity random event
- (Step 2) Begin activating an off Hardsuits (I used Combat Hardsuit Module)
- (Step 3) Trip in the middle of it
- (Step 4) No longer able to use materiell scanners or see the upper left 'item use icons'

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-03-31
7dadfcafeda2c67210672cb2b705af09ca8e1eb0 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
https://puu.sh/v56Su/b9f88d9252.png < Shows I'm wearing a hardsuit, and materiel scanners, while the upper left doesn't have any icons for triggering the materiel scanners.

**Comment by Shophaune** [comment]
Anyone know if this is still a bug?

**Comment by Shophaune** [comment]
Cannot reproduce locally.

**Comment by Arokha** [comment]
Test comment
