### ISSUE TITLE
Mice attack people

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1307]
#### Brief description of the issue
Mice attack people/eachother/themselves when they click on people/eachother/themselves.

#### What you expected to happen
The mouse to nuzzle the target.

#### What actually happened
They attack, dealing damage to the one on whom was clicked.

#### Steps to reproduce
- (Step 1)Be mouse
- (Step 2)Move adjacent to, or on top of someone
- (Step 3)Click them
- (Step 4)Or just click yourself twice, rejoice as you are now dead.

#### Anything else you may wish to add:
I'm personally alright with mice getting the ability to attack things, as the mouse attack is pretty weak. Most things 1 shot mice after all, and it takes 2 hits for a mouse to kill itself, though I'm sure its implementation was not on purpose. If they maintain this ability though, I would prefer if they got access to help and harm intents. Clicking someone in response to them giving you food, and that being a bite, is silly.

**Comment by Very-Soft** [comment]
In case it's of interest, a small test today revealed that it takes around 47 mouse attacks to kill a person.

**Comment by Wickedtemp** [comment]
... Have mice keep the ability to attack.

Mice attacks raise the damaged limb's germ count.

**Comment by Screemonster** [comment]
Calm down, Willard.

**Comment by Shophaune** [comment]
Mice have help and harm intents presently. Issue can be closed.
