### ISSUE TITLE
New RCON UI doesn't update with additional PSU/SMES's

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#13091]
#### Brief description of the bug
Adding a tag to a newly built SMES will not have it show up in the new-fangled multi-page RCON console UI

#### What you expected to happen
To be able to remotely adjust values of a newly created SMES

#### What actually happened
Nothing. The console remained the same as it had been before

#### Steps to reproduce
-  Create a new SMES, wire it in, all that good stuff.
- Open the panel of it with a screwdriver, then using a multitool give it a tag such as "TEST SMES"
- Peep an RCON console, only to find that it's not showing up on there.

#### Code Revision
- Server revision: B:release D:
Commit: [3716834a8937aa849cb6c901f18b97897631dd8f](http://127.0.0.1:51074/tmp5840/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/3716834a8937aa849cb6c901f18b97897631dd8f%22%3Ehttps://github.com/VOREStation/VOREStation/commit/3716834a8937aa849cb6c901f18b97897631dd8f%3C/a%3E)

**Comment by ItsSelis** [comment]
I was able to reproduce this and most likely already know the cause of this problem.
Trying to work on a fix for it now.
