### ISSUE TITLE
Coffee and cream causes toxin damage to tajarans?

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#131]
Went to the cafe. Had coffee with cream in. Shortly afterwards, the health HUD icon stopped showing 100%.

Viewed variables, came to around 10 toxin damage (but I was also chowing down on warm donk pockets so the tricord would be cancelling that out.

Steps to reproduce: be tajaran. Drink some coffee/cream.

**Comment by Arokha** [comment]
Accidentally remade as #133 but mine tells me what I need to do so I'mma close this one.
