### ISSUE TITLE
Check-In/Check-Out Computer in Library not able to Sort

### ISSUE THREAD

**Issue by TheLightorTheDark** [VOREStation/VOREStation#1310]
#### Brief description of the issue
The Check-In/Out Computer in the Library is what's used to print out all of the books. At the top are two pieces of blue text, reading "TITLE" and "[Order]", which, as it can do so on another server I've played on, I imagine it is intended to allow you to sort by Title, and by Genre.

#### What you expected to happen
Upon clicking the blue text, they would become purple for a moment, and the books would become sorted by Title, or by Genre, depending on which is pushed.

#### What actually happened
Upon clicking, the blue text becomes purple for a second, returns to blue, no changes occur.

#### Steps to reproduce
- Click on Check-In/Out Computer
- Click on either the blue "TITLE" or "[Order]"
- Watch as the color changes but nothing happens

#### Code Revision
- release - 2017-04-01
3eeae8a9c6b2415f022cb1fd82633ba68581ef2a
 
#### Anything else you may wish to add:
- This was occuring prior to the Security Removal update as well.

**Comment by SpadesNeil** [comment]
Was this ever fixed?
