### ISSUE TITLE
Apostrophes generate a text bug in PDAs

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13119]
#### Brief description of the bug

When sending a message using PDAs, if it has an apostrophe, the apostrophe is interpreted weirdly.

#### What you expected to happen

Sending the message works normally and the other person can see my apostrophes.

#### What actually happened

"#5%9" or something like that appears instead.

#### Steps to reproduce
use pda to send message to someone
observe that the message you sent (or recieved) has no apostrophes and just has funny text on it
be a bit sad

#### Code Revision
- poke me to add this in the morning but it is post-hotfix

**Comment by Very-Soft** [comment]
This also affects other forms of text entry, such as belly description, and probably basically every other form of text entry apart from the ones that have already been accounted for.
