### ISSUE TITLE
[UI BUG] Pressing cancel clears Input result

### ISSUE THREAD

**Issue by ItsSelis** [VOREStation/VOREStation#13130]
I wanted to edit my flavor text, cancelling in the end and saw that it cleared the entire text (luckily was able to recover).

It's best to avoid pressing cancel for this kind of important inputs for now.

**Comment by ItsSelis** [comment]
It seems that the Flavor Text is missing sanitation checks for null, just setting it as null, even if cancel is pressed.

**Comment by Heroman3003** [comment]
As an issue on byond level, this is kind of unfixable.
