### ISSUE TITLE
Shuttle consoles issues

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#13131]
#### Brief description of the bug

1. Trying to put in a number with a decimal point in it has the consoles ignore the `.` and instead input the entered numbers as full. As in, if you were to input 3.5 to the shuttle/ship sensor console, it would try and apply 35 then go back to the maximum of... I belive it was 7.
Similar issues with the shuttle helm console, trying to input a fraction of a `unit of acceleration` on that had the value ramp up to the full number instead, making any fine tuning damn near impossible.

2. When using the short jump console, the selection of destination will apply on the console, but it won't close the window of potential destinations available.

#### What you expected to happen

1. To be able to have numbers featuring a decimal point apply correctly to shuttle console values.

2. To not have _even more_ windows cluttering up my screen whilst trying to lift off or touch down.

#### What actually happened

1. The values changed to full numbers and screwed any attempts at fine tuning.

2. I had a screen littered with one more screen I didn't need persisting around.

#### Steps to reproduce

- Spawn as pilot
- Go to one of the shuttles on the map
1. 
- Adjust the acceleration limiter on the helm/controls console with a value containing a fraction of a number, a good example would be `0.5`
- Watch as it decides "hmm, no, today it shall limit at 5 `units of acceleration`" instead
- Go to the sensors consoel, repeat above
- Watch as it throws the full value into the sensor range rather than the fractional one entered initially

2.
- Go to the short-jump console
- Hit the button to choose a destination
- Choose your destination from the list
- Grumble as the window persists after picking a destination

#### Code Revision
- Server revision: B:release D:
Commit: [7aae0c74c6fa11a798fc3999dff58ae716393ee3](http://127.0.0.1:58803/tmp34980/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/7aae0c74c6fa11a798fc3999dff58ae716393ee3%22%3Ehttps://github.com/VOREStation/VOREStation/commit/7aae0c74c6fa11a798fc3999dff58ae716393ee3%3C/a%3E)

**Comment by Heroman3003** [comment]
I believe this was fixed
