### ISSUE TITLE
Teshari undercoat clothes layer weirdly with hardsuits

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13145]
#### Brief description of the bug
The teshari undercoats appear to not be hidden when wearing hardsuits, which isn't a big thing but leaves a funny bit of clothing out all the time.

#### What you expected to happen
Undercoat is hidden under the hardsuit.

#### What actually happened
Undercoat is gmod clipping through the hardsuit.

#### Steps to reproduce
- Equip a teshari undercoat of some kind
- put on and extend the hardsuit stuff
- Notice this weird thing after many hours of playing teshari in hardsuits and not noticing it
- make a bug report

#### Code Revision
Server revision: B:release D:
Commit: [8a894bdd5b0b874e180bac653fc3698cea6f0340](http://127.0.0.1:62683/tmp6668/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/8a894bdd5b0b874e180bac653fc3698cea6f0340%22%3Ehttps://github.com/VOREStation/VOREStation/commit/8a894bdd5b0b874e180bac653fc3698cea6f0340%3C/a%3E)
 

#### Anything else you may wish to add:
No undercoat ![image](https://user-images.githubusercontent.com/96669534/175193458-ecae2c5c-292f-4d74-967d-bb3bfeebda4b.png)
![image](https://user-images.githubusercontent.com/96669534/175193487-7832663a-8c2a-4f88-9e16-bae2d5d39042.png)
![image](https://user-images.githubusercontent.com/96669534/175193506-88a176dd-f86b-4856-9f76-9f2758993ade.png)
Undercoat 
![image](https://user-images.githubusercontent.com/96669534/175193776-5f87bda9-db36-4a77-83bd-91edc60b5bf3.png)
![image](https://user-images.githubusercontent.com/96669534/175193785-e1432de6-9ff2-4b21-b7e9-d3e218419064.png)
![image](https://user-images.githubusercontent.com/96669534/175193794-03e6addc-cbc5-4b38-af5f-4ab513397aee.png)
Undercoat but a different hardsuit (Im not testing all of them but this is just what I had around)
![image](https://user-images.githubusercontent.com/96669534/175198833-89272465-ccb4-4eb6-96e7-97b3a4bf3add.png)
![image](https://user-images.githubusercontent.com/96669534/175198848-ea27a9cd-c944-418e-820a-70274836814c.png)
![image](https://user-images.githubusercontent.com/96669534/175198865-0787a40a-a79d-4a9c-b234-03a204da1603.png)

**Comment by Heroman3003** [comment]
I believe thats because all undersuits normally dont 'disappear' when you put on an oversuit, even one like a spacesuit...

**Comment by TankTheBirb** [comment]
Welp, working as intended I guess. Time to make voidsuit compatible undersuits some day. Gonna close this one.
