### ISSUE TITLE
Whitelist request Malady - Daemon speech

### ISSUE THREAD

**Issue by ZippyShanks** [VOREStation/VOREStation#1316]
#### Brief description of the issue
I would like to request a whitelist permission to use the Daemon language on the character Malady Blanche, since I play her as a demon this seems to be a fitting thing for her to be able to do.

**Comment by ZippyShanks** [comment]
I forgot to add my ckey in here it's 1R1S

**Comment by DemicusMaximus** [comment]
Oooh, I know her. Yep, sounds good to me. :3
