### ISSUE TITLE
[GENERAL] AI Shadow Realm Bug

### ISSUE THREAD

**Issue by Schrano** [VOREStation/VOREStation#13177]
#### Brief description of the bug
AI gets sent to the shadow realm by having their camera in the wrong place. This is possibly caused by the camera (or where the camera should be) getting automatically destroyed as a part of the Ship Landing process.

#### What you expected to happen
The AI to not get sent to the shadow realm, and the camera to be able to be moved as usual.

#### What actually happened

While I had my camera focused on the Stellar Delight's landing bay I had my camera over the tile of a landing ship, as it landed I got placed into a pure black void, except for my UI. Most movement buttons do not work, hotkey mode or not, the only way to move is to use the multicamera feature, and even then it only brings you to the core.

#### Steps to reproduce
- (Step 1) Place AI view (where the AI player sees) on a tile that is going to be landed upon by a ship.
- (Step 2) Wait for landing.
- (Step 3) Get sent to the void upon landing.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: [fa65411cc384ff264e751d30e9d5c5d041a64e8f](http://127.0.0.1:53516/tmp284/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/fa65411cc384ff264e751d30e9d5c5d041a64e8f%22%3Ehttps://github.com/VOREStation/VOREStation/commit/fa65411cc384ff264e751d30e9d5c5d041a64e8f%3C/a%3E)

#### Anything else you may wish to add:
The error is frightening as it looks exactly like an admin punishment, and feels like it to with the paralysis.

**Comment by ItsSelis** [comment]
This is most likely related to #10277

**Comment by Schrano** [comment]
Took a look at the bug, it sounds like exactly what I experienced.
