### ISSUE TITLE
Fluff App - JJE - Amaya

### ISSUE THREAD

**Issue by DarkWolfInsanity** [VOREStation/VOREStation#1319]
[b]Name of Item:[/b] Judge, Jury, Execution (JJE)
     
[b]Item description[/b]: A custom-made .357 revolver. Large and in charge, it fires caseless .357 ammunition, being equally as dangerous as some form of anti-tank rifle, only in the palm of your hand.

[b]Sprites (or link to sprites)[/b]: 
![jje](https://cloud.githubusercontent.com/assets/5521322/24584361/d647e7ba-1730-11e7-8891-59fa8ed71387.png)
Its essentially a recolored Jury (whoever's fluff item that is)

[b]Any additional resources[/b]: (in a .zip or .7z file, including sounds and DM files with code in them)
Will be added via pull

[b]BYOND Key (Username)[/b]: IvyMooMoo

[b]Name of Character[/b]: Amaya

[b]Main Job(s) of Character[/b]: Security / Head of Security (Commander)

[b]Why your character should have this item[/b]: Being a security officer for so long can only make you so suspicious of every action. The little guns don't feel intimidating anymore to the crew. Perhaps its the rubber bullets, or the lack of lethal force. A large gun like this fired near someone and leaving a visible hole in a wall should definitely make them stop and rethink what they're doing.

[b]Additional Notes (If it's a permit, insert the information for the permit here)[/b]: It does kinda require a permit being an extremely ass dangerous gun, and being a gun in general.

[b]Fluff Item slots already used[/b]: 1

**Comment by Screemonster** [comment]
is that sprite literally a nerf maverick

**Comment by SpadesNeil** [comment]
It will have that description but will fire nerf darts

**Comment by SpadesNeil** [comment]
shit, wait, April 1st is over, I have to be serious about this

The answer is no.

**Comment by DarkWolfInsanity** [comment]
You could atleast try to tell me "no lethals". So let's change that to caseless flash or stun 357 ammo.

**Comment by SpadesNeil** [comment]
Still no. The only .357 in the game there even _should_ be for one player right now is a single-action weapon that needs to be reloaded every shot, just like a shotgun. He's also played the server for a couple of years. His original app wanted a normal .357 and I said no.

If this app is in snarky response to the fact that Dhael has a .357 apparently, I didn't authorize that, and I am trying to get to the bottom of _why_ they have it.

**Comment by JoanRisu** [comment]
#887

**Comment by DarkWolfInsanity** [comment]
I already have the code for mine set to single action with an even longer cool down than Tasald's BIR. And if it fires flash or stun variety of the ammunition, there would be no eviromental damage (or atleast marginally less than a lethal shot). The aiming would still be shit, the fire rate would be fucking terrible, I still have the glitch where if I "overcock" I lose ammo because of what I did to make the gun caseless.

**Comment by SpadesNeil** [comment]
That reminds me. Caseless ammunition is another matter I don't like. It's because the ammo used leaves no trace of what happened.

However, now that I think more about this, forcing you to use a custom ammunition would satisfy my problems with it being a .357, even if it's one that's just semi-auto, because you'd have a strict limit on how much ammo you'd have at _any_ given time.

Re-opening for debate.
