### ISSUE TITLE
[MAPPING]  Scrubber blocking Anomaly Analyser 

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#13192]
#### Brief description of the bug
Anomaly scanner scans scrubber instead of the exotic you place on its tile. 

#### What you expected to happen
I expected the exotic anomaly to be scanned. 

#### What actually happened
Instead of getting a scan of the exotic anomaly, I got a scan of the scrubber. It looked really awesome, but I forgot to get a picture. Sadly can't nab one from my phone.  

#### Steps to reproduce
- (Step 1) Attempt to analyse an exotic anomaly
- (Step 2) Get a scrambled scrubber report, with a mosaic of scrubbers on it. 
 

#### Anything else you may wish to add:
This is on Rascals Pass at the anomaly/toxins outpost; in the room Anomaly Lab. It's a great map so far, keep up the good work!

Update:
![image](https://user-images.githubusercontent.com/11194290/176242989-bb9f105c-9393-4555-bd5f-acad58a8030d.png)
The Scrubber Mosaic.

**Comment by Aroliacue** [comment]
Not too sure if anyone's made a fix for this yet, but just in case I'll handle it.
