### ISSUE TITLE
Discussion for adding xenomorph heads for xenohybrids

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1321]
i have a collection of 4 xenomorph heads made for xenohybrids to make them look a little less stupid

this is discussing if they should be added and how because it can be a whitelisted demi item or a species restricted hair (Though it may also be whichever actually works)
![Uploading xenoheads.png…]()

**Comment by kcin2001** [comment]
ugh i cant upload the zip for some reason

**Comment by SpadesNeil** [comment]
Do this:

Take the .dmi file
Change the extension to .png and nothing else.

This tricks websites into letting you upload it, without deleting all the .dmi's information that makes it into sprites. Note, this will not work in reverse if any alterations are made to the .png version.

**Comment by kcin2001** [comment]
i cant actually figure out how to change the extension

**Comment by SpadesNeil** [comment]
Google it. :U

**Comment by Cameron653** [comment]
This would be a good addition, as the xeno chimera head is ~~absolutely hideous~~ in need of improvement at the moment

**Comment by kcin2001** [comment]
cameron its xenohybrid not chimera

**Comment by kcin2001** [comment]
since the main one seems to be stuck uploading the png for me ill upload it again her 
![xenoheads](https://cloud.githubusercontent.com/assets/16435949/24589498/45321c40-1790-11e7-8c50-be292da1998f.png)

**Comment by Screemonster** [comment]
> This would be a good addition, as the xeno chimera head is absolutely hideous in need of improvement at the moment

![screerazz512](https://cloud.githubusercontent.com/assets/14942479/24589501/5dc21ec0-17d3-11e7-8e0c-c42b6d83d4e7.png)
Screw you, I's adorable.

**Comment by kcin2001** [comment]
![image](https://cloud.githubusercontent.com/assets/16435949/24589570/695879c4-1791-11e7-88f4-4db60f4501ab.png)
im also tempted to make one like this xenomorph

**Comment by Cameron653** [comment]
Whoops, didn't mean xeno chimera, ment xeno-hybrid,

my bad :v

**Comment by kcin2001** [comment]
so should it be hair or demi item?

**Comment by SpadesNeil** [comment]
I vote hair.

**Comment by kcin2001** [comment]
if it works, i remember trying it and it didnt work but that could have been a problem with something that i did
