### ISSUE TITLE
Nanopaste has some size issues

### ISSUE THREAD

**Issue by drexample** [VOREStation/VOREStation#1322]
#### Brief description of the issue

Currently nanopaste is a normal-sized item. That means you are unable to put in a box/pocket.
So it's either a very large tube or a bug.

#### What you expected to happen

Size of Nanopaste tube should be at least small.

#### Code Revision
Server revision: release - 2017-04-02
f96a26e3cabcfcac9ea1972c6212592f85b88c6e

**Comment by Arokha** [comment]
Yeah I noticed this last night. Couldn't put it in a box. It appears to just be like a toothpaste tube thing.

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/3213
