### ISSUE TITLE
Species drug allergies

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#133]
Nullify species reagent tags. People using taj species may not actually be taj. Could be fox or sumin.

**Comment by SpadesNeil** [comment]
Yea, remove all reagent allergies except for species who use the whitelist.

**Comment by Arokha** [comment]
> supposed to be restricted to the alien whitelist

What'chu mean? All aliens are whitelist by default.

**Comment by SpadesNeil** [comment]
Tajaran and Unathi aren't, are they?

**Comment by Arokha** [comment]
By default, yes. But they have working alien whitelist, which I just turned off for now until we get species you want to actually whitelist.

I mean, Polaris removed Vox and we’re not redoing Skeletons, so.
