### ISSUE TITLE
Banning and it's several methods are effectively broken

### ISSUE THREAD

**Issue by ItsTheKet** [VOREStation/VOREStation#13309]
#### Brief description of the bug
As of current. The many methods performed (Unban panel) and Player Panel have their abilities to actual ban a person to be SEVERELY reduced. Unban Panel is effective however requires several attempts for it to land for some reason. And Player Panel bans serve no better than a kick.

#### What you expected to happen
A ban to stick

#### What actually happened
Despair over several repeated attempts only to have it actually land somehow.

#### Steps to reproduce
- Click a man on the Player Panel
- Perform the usual permaban procedure (This may take several clicks with the UI changes.)
- Have said man attempt to reconnect.
- They will predictably reconnect, so go through the manual ban process in the unban panel.
- See, even though you just banned him and the evidence is there. The person may still be there.
- Repeat this until it works.
 

#### Anything else you may wish to add:
- As mentioned previously, this also comes in tow with a slight UI based issue, however it should not be the overarching core of the issue, rather a side effect of changes.

**Comment by Cameron653** [comment]
Impossible to recreate on a local server (Due to how local servers work with bans) and when tested on main server:
player panel temp ban: works
player panel perm ban: works
unban panel temp ban: works, but doesn't kick

Marking this unable to duplicate until it occurs again and we have more info.

**Comment by Heroman3003** [comment]
I actually could recreate it when I had been using database-esque ban system but had no database connection; but main server very much DOES so IDK what could be causing it. Unless there were database connection issues at the time somehow?

**Comment by Cameron653** [comment]
An admin tested on the live server and the banning methods worked each time, with the only problem being that the unban panel wouldn't kick the user being banned.

Next time this occurs, it'd be great to have the circumstances (Was the server lagging? Everything put in the panel, etc)

**Comment by Heroman3003** [comment]
Does not seem to be replicable and has not been reported to happen again since. I am closing this, but lets put a pin in this in case it occurs again.
