### ISSUE TITLE
Solar garden!

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1331]
#### Brief description of the issue
Scree built a thing, a new area called the "solar garden" for people to sit and look out on the stars (protected, naturally, by a buttload of reinforced glass and mesh anti-meteor screens)

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/14942479/24636359/a848de3a-18d1-11e7-9843-ab91257a7e23.png)
Crew transfer was nearly unanimous the instant the first vote went through, otherwise would have had a chance to furnish it too. Was gonna basically steal all the wooden furniture and soil plots from the normal garden and make a nice little out-of-the-way solar-field observatory and relaxation area with plants and stuff.
This won't interfere with the solar's function as long as nothing that blocks LOS is placed on the glassed-in area.
 
#### Anything else you may wish to add:
Because areas and blueprints are a pain, the place glitched out a bit when trying to make it as a map - the space turfs got spit into two vertically by the existing solar array area, hence the need for two APCs and air alarms. If mapped, these won't be needed. Likewise, the windows with the lights on in the middle of the room were on the solar array area, hence why they couldn't be powered.

I didn't have time to replace the airlock in the solar control room with a normal engineering one, or move the external airlock to where I wanted it (at the end of the hall, directly east of the solar control room - where the rocks are on the screenshot)

Plan was also to place another row of grilles to protect the west side of the room - this screen would be placed between the escape pods to give them a clear space to launch (I know it's not needed, but it's nice fluff)

I got a screenshot of the pipe/wiring layout if needed:
![image](https://cloud.githubusercontent.com/assets/14942479/24636493/918577c0-18d2-11e7-96af-69ecca994145.png)

**Comment by Yoshax** [comment]
You can make wooden benches, which would probably go nicely. Also might be sensible to put the solar panels surrounded by windows, so folks can't interfere with them. Possibly a few soil patches too for plans or stuff.

**Comment by Screemonster** [comment]
Ooh, yes. Glassing in the solar panels themselves is a good idea. Can't really do much apart from pry the glass off but best not to make it easy.

**Comment by Dhaeleena** [comment]
We now have a giant solar array on its on z-level. Well its not as pretty as this one and its enveloped in toxic air! But i guees it works. Unless we get Bigger map sizes making solar arrays on space will be hard. So no longer relevant? at least until we get bigger map sizes

**Comment by Screemonster** [comment]
Yeah, this is for old map so unless we make a giant space observatory dome or something this can be closed.
