### ISSUE TITLE
Whitelist request; Deamon Language for Lirona Carinell

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1334]
Lirona Carinell is a half succubus half neko hybrid, whose mother is a succubus. Her mother as well as having lived on Infernum would have taught her the language, and therefore I'd like to be able to speak it in game.
 As such, I'd like to be whitelisted to know it, to avoid awkward moments where people try to speak with me in the language I should know, being a succubus.

Byond key: Natje
Character name: Lirona Carinell

**Comment by Vorrarkul** [comment]
I thought the demon language wasn't implemented?

**Comment by Natje0** [comment]
It has been for a bit now. Though, I was too lazy to get around to requesting whitelist until now~

**Comment by DemicusMaximus** [comment]
Sounds good to me! I'll approve it.

**Comment by Natje0** [comment]
Sweet! Thanks~
