### ISSUE TITLE
[MAPPING] HoP office on SD lacks a desk

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#13356]
#### Brief description of the bug
Rather than a desk to place paperwork on and do general HoP business, there's a low wall without a window attached.

#### What you expected to happen
For there to be a desk like there is for R&D, Engineering Monitoring room and HoP line on Tether.

#### What actually happened
Low wall without a table to put things on.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: [139bec367523665b138acc16757e37b16f226179](http://127.0.0.1:63783/tmp10816/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/139bec367523665b138acc16757e37b16f226179%22%3Ehttps://github.com/VOREStation/VOREStation/commit/139bec367523665b138acc16757e37b16f226179%3C/a%3E)

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/20523270/179403112-9dd3259d-5402-4c86-a949-f2b98ca8bfc3.png)
![image](https://user-images.githubusercontent.com/20523270/179403122-2c2a2aa2-b714-49e7-a38c-57cf8637196e.png)

**Comment by FirstSgtDan** [comment]
Created PR https://github.com/VOREStation/VOREStation/pull/13360
