### ISSUE TITLE
Whitelisted species need to link to the wiki page in their descriptions.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1336]
#### Brief description of the issue
People see a species is whitelisted and apply for it based on the short in-game description, without ever being told where the actual lore page is.

#### What you expected to happen
For a wiki page for the species name to pop up in either the descriptions or the "species is whitelisted" section.

#### What actually happened
People see a species is whitelisted and have no further information about them without digging.

#### Steps to reproduce
- change species
- look at whitelisted races

**Comment by SpadesNeil** [comment]
Let's make sure we actually have a list of all species. Can we post them here for reference?

**Comment by Screemonster** [comment]
Human, Unathi, Tajara, Promethean, Vox, Teshari, Skrell, Diona, Xenochimera, Sergal, Akula, Nevrean, Highlander Zorren, Flatland Zorren, Vulpkanin, Xenomorph Hybrid

**Comment by SpadesNeil** [comment]
I meant wiki links. :U

**Comment by SpadesNeil** [comment]
We also need to be prepared to move away from Polaris lore if we so please.
