### ISSUE TITLE
Vulpkanin Keep Species Ears

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1337]
#### Brief description of the issue
When creating a Vulpkanin, choosing a custom species ear will NOT remove the large Vulp ears from their head.

#### What you expected to happen
For the species ears to disappear in favor of the custom ears.

#### What actually happened
Both ears appeared.

#### Steps to reproduce
- Create a Vulpkanin
- Select a custom ear type
- See in both preview and ingame, both ears rendered

#### Code Revision
- c8a8119a67dbe268bdee158132dfb9112a0df5bf
 
#### Anything else you may wish to add:
- https://www.dropbox.com/s/ktog7i78axx9vqt/Screenshot%202017-04-04%2005.48.20.png?dl=0

**Comment by Poojawa** [comment]
That's because the Vulpa ears are not part of the hair styles. I don't believe there's any forced species ears thing like tails are sooo

**Comment by Verkister** [comment]
A fix is waiting for the next release merge.
