### ISSUE TITLE
Fuel Depot not charging RP's Exploration Shuttle's SMES

### ISSUE THREAD

**Issue by FirstSgtDan** [VOREStation/VOREStation#13384]
#### Brief description of the bug
- RP Exploration shuttle doesn't recharge SMES when docked at fuel depot even after setting up the depot's solars and turning off all shuttle systems. I've been told that that shuttle only charges from the east side, but that shuttle can only dock on the west dock of the fuel depot.

#### What you expected to happen
- SMES should be charging when docked at the fuel depot.

#### What actually happened
- No charging happens.

**Comment by Wulfestwulf** [comment]
This appears to have been fixed as of [985355610789d1e534e1fd975f7ed8980a70007d](http://127.0.0.1:58485/tmp5612/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%22%3Ehttps://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%3C/a%3E)
