### ISSUE TITLE
Rascal's Pass  Telecoms is not OSHA compliant [MAPPING] 

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13380]
#### Brief description of the bug
There are two issues.
The first is that the telecoms turrets are not on the telecoms turret controller, and will absolutely shoot people when the controller is set to "off". So any CE trying to show new engis telecoms stuff cannot do anything while their trainees are pelted to death by lasers.

The second is that the air alarm in the telecoms airlock causes the emergency shutters to lose their collective minds, and throw all sorts of fun alarms. Rarely an issue for CEs but annoying nonetheless.

#### What you expected to happen
Telecoms will be safety code compliant and nothing will go wrong.

#### What actually happened
Turrets go murderkillmode and the air alarm gets angy. See description for more indepth report.

Air alarm pictures below.

#### Code Revision
Server revision: B:release D:
Commit: [a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84](http://127.0.0.1:64047/tmp14516/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84%22%3Ehttps://github.com/VOREStation/VOREStation/commit/a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84%3C/a%3E)
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/96669534/180579749-5a5bf46f-71e6-4a56-a6d9-ef0f10b5c5b5.png)
![image](https://user-images.githubusercontent.com/96669534/180579722-884291dc-3cde-42f2-9604-b0a0d7e5cfad.png)
There is already one in that lobby so just remove the airlock one.

Idk about the turret controls tho. That's beyond me.

**Comment by Wulfestwulf** [comment]
This is fixed on the latest server revision. [985355610789d1e534e1fd975f7ed8980a70007d](http://127.0.0.1:58485/tmp5612/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%22%3Ehttps://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%3C/a%3E)
