### ISSUE TITLE
Rascal's Pass Medical/Cargo substation has no air alarm [MAPPING] 

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13381]
#### Brief description of the bug
Air alarm not in room! This bad!

#### What you expected to happen
Bad gas to make yellow wall go up.

#### What actually happened
No wall up also no alarms or indications. This bad, engi need alarm to know if thing bad.

#### Code Revision
Server revision: B:release D:
Commit: [a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84](http://127.0.0.1:64047/tmp14516/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84%22%3Ehttps://github.com/VOREStation/VOREStation/commit/a6c022548f4ab0a5f6770060e5f4bd8b9ecebd84%3C/a%3E)
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/96669534/180581303-52227f70-8273-491a-82ab-cf390ebec3f2.png)

**Comment by Runa-Dacino** [comment]
This appears to have been fixed. Not sure which PR but on latest revision (Server revision: B:release D:
Commit: [8dcde287d0900a4dbc54cc6e9475ce82cae6690e](http://127.0.0.1:52457/tmp13076/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/8dcde287d0900a4dbc54cc6e9475ce82cae6690e%22%3Ehttps://github.com/VOREStation/VOREStation/commit/8dcde287d0900a4dbc54cc6e9475ce82cae6690e%3C/a%3E)

it's fixed:

![image](https://user-images.githubusercontent.com/20523270/188282592-e345c695-f9b3-4992-bb82-83caca623d1f.png)

**Comment by Wulfestwulf** [comment]
This is fixed on the latest server revision. [985355610789d1e534e1fd975f7ed8980a70007d](http://127.0.0.1:58485/tmp5612/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%22%3Ehttps://github.com/VOREStation/VOREStation/commit/985355610789d1e534e1fd975f7ed8980a70007d%3C/a%3E)
