### ISSUE TITLE
Unathi lack breasts

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1346]
#### Brief description of the issue
I demand lizard tits and disapprove of the current female sprites for Unathi.

#### What you expected to happen
Lizard tits.

#### What actually happened
Turtle chests.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/89debe3c5d9edff392b3a238b7d3f7f0b120cb2f
 
#### Anything else you may wish to add:
- Screw the current lore, I want lizard tits. :U

**Comment by ArbyTheDragon** [comment]
Could we have the option to not have any? ;_;

**Comment by SpadesNeil** [comment]
Fiiiiiiiiine. Lizard tit hater.

**Comment by DeepIndigo** [comment]
I was gonna say, I might have some sprites lying around like I did for tajaran tits.
