### ISSUE TITLE
Antlers Back Sprite Off-Center

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1348]
#### Brief description of the issue
The antlers ear option is slightly off-center when the character is facing away from the camera.

#### What you expected to happen
The antlers to not be off-center.

#### What actually happened
They were off-center.

#### Steps to reproduce
- Have antlers.
- See the preview showing them off-center.
- Double-check by logging in as assistant.
- Take a crapload of screenshots. A whopping 2.

#### Code Revision
- 3bd2cc0487f710aef63e6d4ebe8e32aff1d0febb 
 
#### Anything else you may wish to add:
- https://www.dropbox.com/s/bllddj0zvx5357e/Screenshot%202017-04-04%2023.44.02.png?dl=0
- https://www.dropbox.com/s/ynw41x4z0j2tzq2/Screenshot%202017-04-04%2023.46.12.png?dl=0

**Comment by Verkister** [comment]
Been fixed a while ago.
