### ISSUE TITLE
Add trashbags to the security firing range

### ISSUE THREAD

**Issue by Michab02** [VOREStation/VOREStation#1349]
So, the previous map had trashbags in the shooting range. This was basically mandatory, because literally hundreds of shell will pile up there, and then lock up your client when you click on them. It'd be really cool if we could get them readded.

**Comment by ArbyTheDragon** [comment]
Exodus totally had one. We don't? That's only a problem if we don't wanna give the custodian something to do though.

**Comment by SeigaSeiga** [comment]
I wouldn't want security to just self-tidy, calling in a janitor should be more encouraged, since they signed up to do that job. However, the potential lag is probably a convincing argument in favour of having trash bags there. Clients locking up is no fun at all.

**Comment by Wickedtemp** [comment]
I don't think it matters too much if Security picks up after themselves. Prolly a good idea to add the bags back in.
