### ISSUE TITLE
Missing things

### ISSUE THREAD

**Issue by runeguden** [VOREStation/VOREStation#135]
Slime Race is Missing.
Machine race is missing.
Nudist permit is missing (armband) .
Silver coin is missing.
Daemon language is missing.

please fix :3

**Comment by SpadesNeil** [comment]
Please make the issue title more clear, or this will be easily looked over.

Slime race are now Prometheans last I heard.

Machine Race is not being re-added at this time.

Daemon language is also not being re-added.

Silver coin is missing? How do you know?

Please be more clear on what you mean by the nudist permit is missing.

**Comment by Screemonster** [comment]
Also it's good to split issues into multiple reports for multiple things. Races and languages are an entirely separate issue from loudout selections (the nudity permit) and mapping issues (whatever the coin is, but how you've been playing on the map long enough to know where the coin spawns is beyond me)

**Comment by Arokha** [comment]
>Machine race is missing.
Machine Race is not being re-added at this time.

'Machine' race, as in, IPC, are just people with full-body-prosthetics now. Just pick to adjust your organs on the character setup, and pick Morpheus as the manufacturer. There's a head-TV in the gear section.

**Comment by Arokha** [comment]
>Slime Race is Missing.
Slime race are now Prometheans last I heard.

I already have the fix waiting for this.

**Comment by JoanRisu** [comment]
> Please be more clear on what you mean by the nudist permit is missing.
He means that the nudity permits are not showing up on the accessories loadout.
