### ISSUE TITLE
Burst lasers cannot fully recharge

### ISSUE THREAD

**Issue by Michab02** [VOREStation/VOREStation#1350]
#### Brief description of the issue
Burst lasers are meant to hold 24 shots, and start with as many. But, when emptied and recharged, they max out at 12 shots. This is true for both the base weapon and the G44E variant.

#### Code Revision
release - 2017-04-05

**Comment by lbnesquik** [comment]
Still an issue

**Comment by lbnesquik** [comment]
Actually maybe not. The reason this happen is because lethal shots have a 200 charge_cost unlike the stun shots 100 charge_cost. So switching between fire modes gives you correctly 12 shots of lethal and 24 of stun. So not an issue?

**Comment by Screemonster** [comment]
closing as above, reopen if this is in error etc
