### ISSUE TITLE
AI can hardlight nom people from range

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1351]
#### Brief description of the issue
Can hardlight nom people while the hologram is not on top of or adjacent to people.

#### What you expected to happen
For hardlight to only work on top of or adjacent to people.

#### Steps to reproduce
- Be AI
- Activate hologram
- Disable Hologram Movement
- Move AI camera over the one you want to nom
-Hardlight nom
- Watch as they mysteriously disappear and your hologram changes color

 
#### Anything else you may wish to add:
- They seem to get released where the hologram is though. I haven't tested the range at which one could do this to its fullest extent yet. But I was able to do it from several turfs away.

**Comment by Very-Soft** [comment]
An additional test allowed me to hardlight the mouse Tom out of the Vault from one of the AI core rooms. So range or LoS appears to be unlimited.

**Comment by Screemonster** [comment]
Aro, you wrote this. Feeex. :p

**Comment by SpadesNeil** [comment]
Fixed?
