### ISSUE TITLE
Humans stop caring about being on fire if they are too on fire[GENERAL] 

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#13525]
#### Brief description of the bug
if your fire_stacks go too high (above 10 or so), your temp doesn't increase from being on fire anymore

#### What you expected to happen
for fire to kill me, ideally faster, the more on fire I am

#### What actually happened
![image](https://user-images.githubusercontent.com/24854483/185221962-c1959ef2-8a02-40f6-878a-888b85df31a4.png)
I've been here for several minutes

#### Steps to reproduce
- Become on fire, easiest way is to step into a lit bonfire
- Continue doing whatever you did to accumulate fire_stacks
- When you have enough, marvel as your body temp returns to normal

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- I discovered this while making a food that starts you on fire, if you eat too much of the food, you become impervious to being on fire

**Comment by Cameron653** [comment]
Found some segments of code that may be involved.
https://github.com/VOREStation/VOREStation/blob/af51af9677df8fbbe4994c5844cd6b2b131752ce/code/modules/mob/living/carbon/human/life.dm#L1920-L1937
This handles actually adjusting body temp. 
I believe that 
https://github.com/VOREStation/VOREStation/blob/af51af9677df8fbbe4994c5844cd6b2b131752ce/code/modules/mob/living/carbon/human/life.dm#L1934
is our culprit.

Other fire related stuff that I think is less relevant.
https://github.com/VOREStation/VOREStation/blob/035a67b3d16bf92f153325c1c4c91ff3659a57e2/code/modules/mob/living/living_defense.dm#L583-L586

https://github.com/VOREStation/VOREStation/blob/af51af9677df8fbbe4994c5844cd6b2b131752ce/code/modules/mob/living/carbon/human/life.dm#L895-L908
