### ISSUE TITLE
Proteans Can Trip Into Themselves And DIE

### ISSUE THREAD

**Issue by EtheoBoxxman** [VOREStation/VOREStation#13522]
Proteans can slipnom themselves when turning back into humanoid form.

They turn back into humanoid form without issue.

If you are afflicted with the confused status effect, or some manner of triggering slipnoms, if you go into blob form then change back while in motion, you'll trip over your protean blob on re-spawn, and be eaten. The blob then deletes, and by extension, you get deleted along with it.

You need to have spontaneous pred AND prey enabled for this to occur.

Easiest way to reproduce
- Flip until confused
- Immediately blob form
- Restore humanoid form
- Immediately attempt to move

**Comment by EtheoBoxxman** [comment]
https://media.discordapp.net/attachments/806370375810285568/1009336536782868590/unknown.png relevant screenshot

**Comment by Cameron653** [comment]
the madman did it
he ate himself
