### ISSUE TITLE
Mermen and Mermaid leg replacement sprites

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#1353]
Sugarcuddles spent some time making mermen and mermaid leg replacement sprites [here](http://i.imgur.com/QZ4kP7d.png)

The forum post is [here](http://forum.vore-station.net/viewtopic.php?f=22&t=891).
They suggest that spriters take a look and refine the sprites as needed.

**Comment by ArbyTheDragon** [comment]
The idea as a whole seems odd. How do they walk around? Flop uselessly like a fish? Use arms to crawl? ;_;
