### ISSUE TITLE
[GENERAL] Size guns do not have their texture applied

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13557]
#### Brief description of the bug
The sizeguns made at science do not have a sprite other than the purple "no sprite" box.

#### What you expected to happen
them to have one of these sprites
![image](https://user-images.githubusercontent.com/96669534/186030767-c5146117-a20f-48c4-9425-ef6dc7a2ad28.png)
![image](https://user-images.githubusercontent.com/96669534/186030800-b0b47004-6cda-47af-bbae-4377eb69c4d0.png)

#### What actually happened
Sprite-less gun :(

#### Steps to reproduce
- make sizegun on protolathe
- it has no sprite
- make bug report

#### Code Revision
Server revision: B:release D:
Commit: [caa54b8587b81b91e9bcbdbd31818657aea1d460](http://127.0.0.1:64019/tmp15900/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/caa54b8587b81b91e9bcbdbd31818657aea1d460%22%3Ehttps://github.com/VOREStation/VOREStation/commit/caa54b8587b81b91e9bcbdbd31818657aea1d460%3C/a%3E)
 

#### Anything else you may wish to add:
spriteless sizegun
![image](https://user-images.githubusercontent.com/96669534/186030522-78331d53-74be-483c-8eb4-6ff97cb98335.png)

**Comment by Cameron653** [comment]
Fixed by 13558
