### ISSUE TITLE
[GENERAL] BAGS OF HOLDING

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#13551]
#### Brief description of the bug
Using quick equip with a bag of holding in hand puts it into itself and it gets deleted. 

#### What you expected to happen
Not this. 

#### What actually happened
My bag, gone. 

#### Steps to reproduce
- (Step 1)Get a bag of holding. 
- (Step 2)Put it in your hand. 
-(Step 3)Hit E or whatever quick equip button you have. 
-(Step 4)Lose the bag if there is no valid slot to equip it to. 
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: 8cf6934c615aec5d2bbb91165ea41131d81f5839 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Fixed with #13784
