### ISSUE TITLE
issues with becoming admin

### ISSUE THREAD

**Issue by jackthemang** [VOREStation/VOREStation#13562]
I cant seem to figure out how to become admin, do i change the admin name in example? i have tried to but upon joining i have no admin.

**Comment by Cameron653** [comment]
I would suggest taking a look at this document on how to start your own private server, which also mentions how to solve the issue in question: https://docs.google.com/document/d/1e5Z9zPtqHdfNkWSHkSI6gP4qe5PhbkmzATkjUxvecrg

In short:
> Go to the folder again, go to the “config” folder, open up the “example” folder, and copy & paste all those into the “config” folder. Ctrl A, Ctrl C, Ctrl V.


> open up the “admins.txt” file that is now in the “configs” folder. 

> Delete everything in here. EVERYTHING. And put your name in. Example: “Cameron653 - Host” Ignore the warnings saying to not use capitals for your name. Do, however, make sure the rank is properly capitalized, ex: Host instead of host. 

> Close the file and save it. 

I believe the issue you are experiencing is that you are not moving out from config/example.

Following the guide above should solve your problem.
