### ISSUE TITLE
[GENERAL]  PAI Mobile Form is Invisible

### ISSUE THREAD

**Issue by ktoma36** [VOREStation/VOREStation#13582]
Changing into a mobile form as a PAI renders you invisible no matter what option you take

For the player's icon to change

Was attempting to do a scene as a PAI and learned that i was invisible when in my mobile form

Attempt to change your PAI's form. I tried both exiting and reintering mobile for as well as changign it while in mobile form. ALso for some reason when I ghosted out my icon was correct as a ghost

**Comment by Very-Soft** [comment]
Tested this on live and I could not recreate. pAI forms appeared as normal.
