### ISSUE TITLE
AI intercepting spam messages is pretty lame

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1360]
#### Brief description of the issue
As an AI, when there is spam present being sent over PDAs it can overtake the chat

#### What you expected to happen
To be able to monitor comms in relative peace

#### What actually happened
https://www.dropbox.com/s/ia8pth3jyrfrqc6/spam.png?dl=0

And it is worse than that sometimes.
 
#### Anything else you may wish to add:
I'm not really sure why the AI gets intercept messages at all. It's very occasionally helpful, but mostly it's irrelevant information that you can't actually act on. I'd sort of prefer if the AI could be authorized by command staff to monitor PDA messages from the terminal near the core to how it's presently set up.

**Comment by Very-Soft** [comment]
As an extra note after having played a bit more, pda intercept messages and hologram interaction messages look similar, in that they are both black and full italics. This can make things a bit frustrating when there's spam pushing the chat up every few seconds and you are trying to lewd the Director in peace. 

Muh lewds!

**Comment by Very-Soft** [comment]
I'll just leave this here; https://www.dropbox.com/s/27d95cjjn84gv7u/spam%20b.png?dl=0

This is an example of what it looks like when it's particularly bad.

**Comment by DeepIndigo** [comment]
That's the thing with intercepts: sometimes they're useful. That's the point

**Comment by Screemonster** [comment]
"Sometimes they're useful" doesn't address the point that when they intercept the spam messages they're annoying as fuck.

**Comment by SpadesNeil** [comment]
A toggle would be nice.
