### ISSUE TITLE
Holocarp aren't supposed to eat people.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1361]
#### Brief description of the issue
Save the vore mobs for away missions and events. :T

#### What you expected to happen
Holocarp to maul you.

#### What actually happened
Also eat you.

#### Steps to reproduce
- Aggro a holocarp.
- Lose.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/87b3376c372b625f54dfad3f860e6b105cefcac6

**Comment by Leshana** [comment]
Rather, perhaps they _should_, but not digest when in safe mode, and not delete you when they derez!
