### ISSUE TITLE
Teleporter walls in the mining roguelike do not maintain momentum

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1364]
#### Brief description of the issue
If you hit the wall, you abruptly stop, rather than continue traveling.

#### What you expected to happen
For you to keep drifting, rather than be basically fucked when you hit one of the barriers without any way to go back.

#### What actually happened
You stop drifting. Sucks if you have no jetpack.

#### Steps to reproduce
- Go to mining.
- Board the shuttle to the asteroid belt.
- Drift in any direction until hitting the map's edge.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/48648cc35c1d2b564846f87c9ea7caa34f037712
 
#### Anything else you may wish to add:
- Can I have a version of this that can be used for my away maps, @Leshana ? Because a lame invisible barrier is no fun and I want to use this in my gateway maps from now on to just teleport players to the other side of the map.

**Comment by chaoko99** [comment]
This should be closed.
