### ISSUE TITLE
Jacket deletes items put into it as you can open storage on it but not actually put things in said storage [GENERAL] 

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#13654]
#### Brief description of the bug
This jacket /obj/item/clothing/suit/storage/hooded/wintercoat/solgov/army causes items put into it to be deleted or otherwise become in accessible as it doesn't have internal storage space for some reason.

#### What you expected to happen
Having storage space or no storage space.

#### What actually happened
The death of a true soldier (maglight). It makes the noise for opening the inventory but has none and nothing can be taken out of it. It also lacks the storage GUI, and vars show no stored contents.

#### Steps to reproduce
- spawn the jacket
- Sacrifice a maglight
- cri

#### Code Revision
Commit: [dcc0464c85728e1c33fd3b54a17630e759050375](http://127.0.0.1:64716/tmp14072/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/dcc0464c85728e1c33fd3b54a17630e759050375%22%3Ehttps://github.com/VOREStation/VOREStation/commit/dcc0464c85728e1c33fd3b54a17630e759050375%3C/a%3E)

**Comment by Heroman3003** [comment]
The cause appears to be that that specific storage did not Initialize properly. Several other items didnt that round, although I cant say why those specifically or why in general...

**Comment by Heroman3003** [comment]
Gonna mark this one as cannot reproduce
