### ISSUE TITLE
Horse tail request

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1365]
#### Brief description of the issue
A player has requested a horse/cow tail that isn't a complete taur half

#### Anything else you may wish to add:
if I wasn't at work I could probably do this in like ten minutes by cropping the tail out of the taur sprite, this is a reminder for when I get home.

**Comment by Wickedtemp** [comment]
A horse body sprite to go with this would be amazing.

Until then, I'm stuck using the sergal sprite.

**Comment by Screemonster** [comment]
**KN'A FTAGHU, PUCK 'BTHNK!**

**Comment by Somekindofpony** [comment]
I play a horse character, these would be great.

**Comment by Screemonster** [comment]
would you say the character is some kind of...

(•_•)
( •_•)>⌐■-■
(⌐■_■)

pony?

**Comment by Somekindofpony** [comment]
Scree you now are the proud owner of a horse apartment.

**Comment by Screemonster** [comment]
That's good, maybe It'll help me feel more stable.

**Comment by Somekindofpony** [comment]
oh my god why
