### ISSUE TITLE
reset slot button doesnt work

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1366]
#### Brief description of the issue
the reset slot button in char setup does jack squat

#### What you expected to happen
the reset button to clear all the info in that slot

#### What actually happened
it does nothing

#### Steps to reproduce
- (Step 1) press reset slot
- (Step 2) click yes in the popup
- (Step 3) nothing happens

#### Code Revision
- 10c60202712fcc8c3f39b934e2edc6993b4e4957 

 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Has this been fixed?

**Comment by HzDonut** [comment]
It has not, no.

**Comment by Meghan-Rossi** [comment]
Looks like this one was fixed by https://github.com/VOREStation/VOREStation/pull/7694
