### ISSUE TITLE
Carthatoline is "carthatoline" instead of "Carthatoline". It physically pains me.

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1370]
#### Steps to reproduce
- Make a bottle of Carthatoline. Super neat, so glad it's fixed.
- Let's put it in a bott-... Oh. The 'C' isn't capitalized... I'll just ignore it.
- Fail horribly at ignoring it.

#### Code Revision
- Server revision: release - 2017-04-06
10c60202712fcc8c3f39b934e2edc6993b4e4957 
 
#### Anything else you may wish to add:
- The reagent name in the chem dispenser appears to have this issue, as well as the name in the Chem Master. Might wanna do a check on everywhere this name appears to make sure it's all good.

**Comment by ArbyTheDragon** [comment]
Hmm- I believe it's the /datum/reagent/ name itself! Should be easy to fix. Maybe I'll try and take a crack at it! ^-^

**Comment by ArbyTheDragon** [comment]
https://github.com/PolarisSS13/Polaris/pull/3278 This fix was just merged into polaris, now we just gotta wait for the sync.

**Comment by ArbyTheDragon** [comment]
This fix actually just got merged in PR #1389
I'll test it when I get home to confirm it's fixed.

**Comment by ArbyTheDragon** [comment]
This bug is fixed. Now you can be happy. http://puu.sh/vlF7T/62cc40a60c.jpg
