### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by DorfGuy1** [VOREStation/VOREStation#13714]
When clicking more on examining a character, a blank white page appears. Blank white boxes also occur for various other ui elements but those are fixed by liberal use of reconnect and the fix-tgui verb.

#### What you expected to happen
Being able to read the character flavor text in another window and not have a white window pop up

#### Steps to reproduce
- (Step 1) shift click or examine a character. 
- (Step 2)Press the more button. 
   Have a blank white page pop up. When moused over this provides a loading cursor icon. The little swirling wheel. It also displays text(see screenshot) below the command bar. The downloading xyx text also appears whenever ui bugs out and has white boxes for me. It seems as if byond is trying to download an image for some reason when I click the more button? 
![Screenshot 2022-09-10 184508](https://user-images.githubusercontent.com/24217198/189508156-754e7f23-a9bd-4a6a-9ebf-1284f96c3da4.png)

- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
5934bc12f6a8d2a596e751ceeda6b76966525cdc 

#### Anything else you may wish to add:
this happens briefly after every time I click the more button on the character
![Screenshot 2022-09-10 184019](https://user-images.githubusercontent.com/24217198/189508046-807f4a61-309f-4c25-aaa5-49b0eb7cde0f.png)

- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Appears to be a local issue, non-replicable.
