### ISSUE TITLE
[BUG] [MAPPING?] xenoarcheology field generators invisible

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#13764]
#### Brief description of the bug
When spawning, the icons for the field generator don't seem to be applied, rendering them invisible. It can still be found via right clicking, or alt clicking the tile. 

#### What you expected to happen
To be able to see the stasis field generators

#### What actually happened
They were unseen. 

#### Steps to reproduce
- (Step 1) go to the entrance of the Rascal's Pass Xenoarcheology Lab
- (Step 2) Look in the top right corner of the xenoarcheology equipment room
- (Step 3) Notice the invisible stasis field generators

**Comment by Cameron653** [comment]
Currently hotgixing
