### ISSUE TITLE
Whitelist approval: Mavekline Moore - ckey Zalvine

### ISSUE THREAD

**Issue by DemgelZalvine** [VOREStation/VOREStation#1381]
#### Brief description of the issue
Approved for the angelic language whitelist

#### What you expected to happen
uh. Acquiring it? :o 

#### What actually happened
Didn't know how to put the whitelist thing on here, so using this! 83

#### Steps to reproduce
be dumb
be a wah

#### Code Revision
- Server revision: release - 2017-04-10
ec84bded1899ba0553adf4bf82afc5534b2fb817 
 
#### Anything else you may wish to add:
- Just wanting to get Mavekline's language added..!

**Comment by DemgelZalvine** [comment]
Oh, right. This would be helpful too
http://forum.vore-station.net/viewtopic.php?f=45&t=885

**Comment by DemicusMaximus** [comment]
Should be added by now. Poke one of the devs directly if its not added.
