### ISSUE TITLE
[GENERAL] Winged Flight works in space (at least SD asteroid mine)

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#13856]
#### Brief description of the bug
Tiny fairy with a pair of butterfly wings can fly around in the depth of space like she's in a fantasy novel.

#### What you expected to happen
Winged flight supposedly uses wings to push against atmosphere to move around. Therefore, absence of atmosphere should make it impossible.

#### What actually happened
I slipped into deep space. I randomly pressed winged flight expecting failure. I regained control and could navigate. This enabled me to hop between asteroids as a fairy who is mining in a skirt, cardigan and sandals.

#### Steps to reproduce
- Be a Synth
- Have wings
- Take winged flight
- Take NIF that allows walking in deep space (Pressure seals, heatsinks)
- Go to space, press winged flight and dance around carp.

#### Code Revision

 Server revision: B:release D:
Commit: [061992e149811a78f6a746d0ffdc9d77390bb521](http://127.0.0.1:59507/tmp10472/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/061992e149811a78f6a746d0ffdc9d77390bb521%22%3Ehttps://github.com/VOREStation/VOREStation/commit/061992e149811a78f6a746d0ffdc9d77390bb521%3C/a%3E)

**Comment by Heroman3003** [comment]
Winged flight allows anyone to navigate in space. Im not sure its entirely something that NEEDS to be fixed to be honest, even if it is rather unrealistic.
