### ISSUE TITLE
Digestion is breaking and not causing death

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1385]
#### Brief description of the issue
Reported on Discord and confirmed as occuring in-game:

Every so often, when eaten, and you start getting digested, instead you will get your body damaged, but your health will not go down. This leads to constant wounds, including breaking all your bones eventually, but you won't die. If you get expelled from the pred during this time, and try to move around, the camera will stay locked on the pred and follow them instead. Entering a cryo pod seems to refocus the camera on you, and your health instantly goes down to where it should be, which in most cases by the time you realize this bug is happening is instant death. I have NO idea how to reproduce this.

#### What you expected to happen
for damage to be done as normal

#### What actually happened
for some reason death isn't happening sometimes

#### Steps to reproduce
- be ate
- get digested and apparently be taking damage but health doll stays at 100%
- get spat into cryopod
- embrace the sweet release of death as life procs finally realise you've got >200 damage.

#### Code Revision
Server revision: release - 2017-04-11
6a5d59915d42a39813e99b413a7ee60fca97e78b

**Comment by Screemonster** [comment]
Oh, attempting to VV someone who was experiencing the bug also caused my client to crash.

**Comment by Screemonster** [comment]
[1:51 PM] Poojawa: absorb someone, unabsorb them, digest. It's liable to just kill them forever
[1:51 PM] Poojawa: that's how it's triggered for me, anyway
[1:53 PM] Poojawa: the problem is https://github.com/VOREStation/VOREStation/blob/master/code/modules/vore/eating/bellymodes_vr.dm#L38
[1:54 PM] Poojawa: needs to be a hard number to ensure death or as an emergency 'oops' failsafe(edited)
[1:55 PM] Poojawa: 200 burn damage, for example

**Comment by Michab02** [comment]
Poojawa apparently suggested this might be caused by prey with zero nutriment being digested.

**Comment by Arokha** [comment]
Don't think it'd be that, because only absorbing cares about the prey's nutrition. Once you start digesting, it doesn't even read the prey's nutrition. Just gives you some from nowhere for each damage you do.

**Comment by SpadesNeil** [comment]
Blocker issues make the whole server crash. Is this a blocker? I recently updated how severity is explained.

https://github.com/VOREStation/VOREStation/wiki

This looks like a severe issue though.

**Comment by Arokha** [comment]
I can't duplicate it. Also VVing random people makes me crash sometimes so I'm not sure it's related. It probably exists but has some extremely weird conditions to trigger it. I couldn't trigger it with the directions above, so it must have been something else happening. Mob controller problem failing to update health, probably.

**Comment by DemicusMaximus** [comment]
Encountered this once before, but could not trace nor replicate. Seems to be a very rare and specific bug buried somewhere deep.

- Prey would not take damage at all, even via VV.
- Prey could not be gibbed.
- Prey did not update any changes made via VV.
- Prey DID however die immediately once coughed up, at which point the corpse behaved normally.

**Comment by Screemonster** [comment]
Happened again today.

[9:20 AM] Kai Highlands, Alpha Miner: You have analyzed Emily Lybsa's vitals.
Analyzing Results for Emily Lybsa:
     Overall Status: -2225% healthy
    Key: Suffocation/Toxin/Burns/Brute
    Damage Specifics: 200 - 200 - 1108.3 - 816.15
Body Temperature: 36.905°C (98.429°F)
Localized Damage, Brute/Burn:
     Upper body: 174.45 - 263.1
     Lower body: 167 - 267.6
     Head: 255.3 - 277
     Left arm: 25.1 - 54.9
     Right arm: 37.3 - 42.7
     Left leg: 42.1 - 37.9
     Right leg: 27 - 53
     Left hand: 17 - 33
     Right hand: 23.8 - 26.2
     Left foot: 25.1 - 24.9
     Right foot: 22 - 28
Severe oxygen deprivation detected | Dangerous amount of toxins detected | Severe burn damage detected | Severe anatomical damage detected

**Comment by Screemonster** [comment]
Okay, ran into another one. The person hadn't died yet, but still.
These vars leapt out at me.

BRUTE:51.7 FIRE:25.7 TOXIN:0 OXY:0 CLONE:0 BRAIN:0

(E) (C) (M) bruteloss = 0
(E) (C) (M) fireloss = 0

Should BRUTE and FIRE not match the bruteloss and fireloss vars?
