### ISSUE TITLE
[GENERAL]  Teshari FBP Suit Cooling

### ISSUE THREAD

**Issue by liache** [VOREStation/VOREStation#13852]
FBP Teshari Suit Coolers do not appear to function at the moment.

Suit coolers should keep teshari synths from taking heat damage like other species.

Made a teshari suit, attached a cooler, cycled it to ON, verified that it was active using charge, verified that 'too hot' icon was still in interface and that I was taking damage.

#### Steps to reproduce
- Make a suit
- Turn it on
- Behold the heat damage
![image](https://user-images.githubusercontent.com/76535603/193939676-781c5d98-2939-4db5-b748-acc46ce59124.png)

**Comment by KillianKirilenko** [comment]
Tesh and Taj FBPs are kinda cursed sometimes. I think it's to do with their greater sensitivity to heat.

**Comment by Cameron653** [comment]
#13853 fixes this. However, the bug that is causing this is extremely cursed and has to do with having between 0 and 1 thermal resistance. Having 1 = no overheating (unless in space). Having 0 = no overheating (unless in space). Having 0.7 (wearing just a voidsuit w/ no helmet) = overheating.

It's bizarre but you have to have a major in thermodynamics to even understand the related code unless you want to sit for 2 hours (like I did) trying to figure out all the math and formulas behind it, just to realize the bug isn't clear.
