### ISSUE TITLE
[GENERAL] pAI vore belly 'heal mode' does not function.

### ISSUE THREAD

**Issue by Aroliacue** [VOREStation/VOREStation#13885]
#### Brief description of the bug
When attempting to heal injured crew using a pAI belly, there appears to be no effect whatsoever. I believe this may have something to do with pAIs having no 'nutrition' stat.

#### What you expected to happen
1) Eat someone
2) They get healed over time

#### What actually happened
1) Eat someone
2) They stay unconscious and don't get healed at all.

#### Steps to reproduce
- Spawn in as pAI
- Create a healbelly
- Eat someone that has injuries
- Watch as they don't get healed

**Comment by Cameron653** [comment]
After testing, found that the problem is that eventually PAIs run out of nutrition (as heal belly requires nutrition) and healing ceases.
