### ISSUE TITLE
Cryogenics and Patient rooms lack air alarms!

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1395]
#### **Brief description of the issue**
Cryogenics and the four patient rooms have vents and scrubbers, but lack air alarms, making those devices largely pointless.

#### **What you expected to happen**
An air alarm to be in those places, allowing scrubber filters to be configured and environment modes to be changed as needed.

#### **What actually happened**
No air alarms, rendering the scrubbers in those areas about 96% useless.

#### **Steps to reproduce**
- 1.Start the round with the current map.
- 2.Have an atmos leak event happen in one of those places or adjacent.
- 3.Notice lack of air alarms
- 4.Despair.

#### **Code Revision**
- Server revision: release - 2017-04-12
7326a03f6b3cea38a023b1f909b09af2aa18a728 
 
#### Anything else you may wish to add:
- Cryogenics: http://puu.sh/vlRuw/73e8e2f88a.png
- Patient rooms: http://puu.sh/vlRwA/f028d4ccb6.png (note, air alarm shown is for the hall, and does not control the atmos equipment in the rooms them selves.)

**Comment by Dhaeleena** [comment]
No longer relevant on the current map.
