### ISSUE TITLE
"Gas leak" event shouldn't pick areas that trap people in arrival areas.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1396]
#### Brief description of the issue
The gas leak event doesn't exclude the shuttle dock hallway, meaning new arrivals can be cut off from the rest of the station and unable to even hit cryo.

#### What you expected to happen
For people arriving on the station to be safe from such shenanigans.

#### What actually happened
Twice in as many days, the event has filled the docking hallway with some sort of horrible gas and trapped people in the arrivals shuttle.

#### Steps to reproduce
- fire the gas leak event a bunch of times until it picks the docking hallway.

#### Code Revision
Server revision: release - 2017-04-12
7326a03f6b3cea38a023b1f909b09af2aa18a728 

#### Anything else you may wish to add:
- Elevator shouldn't have this issue people can escape from the room into maintenance. Teleporter could do with a maintenance door if the hallway is flooded.

**Comment by Wickedtemp** [comment]
Iunno if those entering from Cryo have an alternative way out, it'd be a good idea for someone to check.

**Comment by DemicusMaximus** [comment]
Cryo shuttle does not have a way out either if that hallway is filled. But since the cryo pods are right there, you can jump in and respawn in a different area. Not as big of an issue.

**Comment by Wickedtemp** [comment]
How about let's remove the fuel gas leak event, given that it literally ruins rounds and inevitably gets spread everywhere and ignited.

**Comment by SpadesNeil** [comment]
I am not in favor of removing **FUN**™

**Comment by Yoshax** [comment]
Gas leak event is fine and fun, it's something somewhat interesting to do. But only when its not volatile fuel. The whole game mechanics aren't even setup to really account for nor accommodate fuel, it's just a boring, unnecessary time sink that involves having to most of the time have to take more risks than necessary to properly fix it in a way that doesn't have people all over the station running around with burning tiles.
