### ISSUE TITLE
[GENERAL] proteans can take xenochimera winged flight trait

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#13987]
#### Brief description of the bug
proteans can take xenochimera winged flight trait form the traits menu

#### What you expected to happen
not to have free flight

#### What actually happened
free flight

#### Steps to reproduce
- (Step 1)make protean
- (Step 2)slighted xenochimera winged flight
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by CrowbarLamb** [comment]
is this not intentional?
