### ISSUE TITLE
Being wet from the pool makes you flammable.

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1400]
#### Brief description of the issue
If you weld yourself while wet, you start on fire until you are no longer wet. 

#### What you expected to happen
To not catch on fire

#### What actually happened
I caught on fire

#### Steps to reproduce
- Walk into the pool
- Walk out of the pool
- Weld self
- Praise the sun, for you are now on fire
- Go to the shower and turn it on to wash off the "Wet" status, as you will remain on fire until you are no longer "wet"
 
#### Anything else you may wish to add:
- Resist rolling doesn't help, fire extinguishers don't help, and help from other people patting you out doesn't help. If the person who is patting you out is also wet, then they too will catch fire. 

Far as I can tell, you will simply remain on fire until the "wet" status is gone, which the shower mysteriously, thankfully, removes.  The fire doesn't do all that much damage though. So it's mostly just funny, but I suspect not intended. It seems like the "wet" effect is the same as getting alcohol or something spilled on you. Perhaps the pool is full of vodka? There WERE some Russians in there that one time.

**Comment by Screemonster** [comment]
PR is up to fix this upstream.

**Comment by SpadesNeil** [comment]
pfffffff fucking what

**Comment by Screemonster** [comment]
It's 'cause "wet" is "negative firestacks" effectively.

Except someone forgot a -

**Comment by ArbyTheDragon** [comment]
So instead, having the "Wet" condition adds to the flammability instead of reducing it?

**Comment by ArbyTheDragon** [comment]
This got addressed in Merge #1409
Someone should test it to see if this bug is still present.

**Comment by Very-Soft** [comment]
I tested it, I did not catch fire.
