### ISSUE TITLE
LiquidFirefly - Gazer SCA - Accepted. Awaiting decision on fluff.

### ISSUE THREAD

**Issue by LiquidFirefly** [VOREStation/VOREStation#1403]
I was told to make an issue in here, just to give it attention so I'm just gonna plop the link in. 

http://forum.vore-station.net/viewtopic.php?f=45&t=892

Plopped all of that fluff stuff into DMIs thanks to kcin. Here's a zip with the DMIs and original pngs for the eye marking and eyestalk tail, and the GIMP project that they both came from, just in case something is super messed up.  You might want to check the dmis though, just make sure nothing is weird.
[GazerDMI.zip](https://github.com/VOREStation/VOREStation/files/938113/GazerDMI.zip)

**Comment by DemicusMaximus** [comment]
Race and character app approved, see forum link for details.

**Comment by LiquidFirefly** [comment]
Sweet!  Thanks so much!  Should I make a separate thing for the fluff tail and Eye marking or just leave this open for that, since the files are on the forums.

**Comment by LiquidFirefly** [comment]
Soo, I'm gonna leave the files for the fluff stuff here.   I made a DMI of the stalks, but I don't know if it's actually formatted right or if It's any good, I'm sorta self taught and still learning, there's also a DMI of the marking I want for her main eye, that I'd make recolorable if I knew how exactly that worked, but for right now I'll just kinda leave it as is. I also have the original GIMP project file in there with all the layers, in case I fucked up with turning it into a DMI or the PNGs included don't suffice. 
[GazerDMI.zip](https://github.com/VOREStation/VOREStation/files/931719/GazerDMI.zip)

**Comment by LiquidFirefly** [comment]
Plopped all of that stuff into DMIs thanks to kcin. Here's a zip with the DMIs and original pngs for the eye marking and eyestalk tail, and the GIMP project that they both came from, just in case something is super messed up. 
[GazerDMI.zip](https://github.com/VOREStation/VOREStation/files/938113/GazerDMI.zip)
