### ISSUE TITLE
[GENERAL] Narrate-posts are visible from the lobby

### ISSUE THREAD

**Issue by faaaay** [VOREStation/VOREStation#14031]
#### Steps to reproduce
- (Maybe relevant, maybe not) I had previously played in the round, entered cryo, ghosted, disconnected and reconnected.
- (Step 1) Connect to the server and be in the lobby.

#### Code Revision
- Server revision: B:release D:

**Comment by Runa-Dacino** [comment]
Should be fixed next update by https://github.com/VOREStation/VOREStation/pull/14025

**Comment by faaaay** [comment]
> Should be fixed next update by #14025
