### ISSUE TITLE
Fluff App - Holdout Pistol 

### ISSUE THREAD

**Issue by AeroWing** [VOREStation/VOREStation#1405]
Name of item: Holdout Pistol, 2 flash magazines (9mm), permit.

Item description: The Lumoco Arms P3 Whisper. A small, easily concealable gun. Uses 9mm rounds. | A magazine for some kind of gun.

Sprites (or link to sprites): Holdout Signal Pistol, magazine (9mm), permit.

Any additional resources: (in a .zip or .7z file, including sounds and DM files with code in them):

    /obj/item/weapon/gun/projectile/pistol/
    /obj/item/ammo_magazine/mc9mm/flash x2
    Permit?

BYOND Key (Username): AeroWing

Name of Character: Sebastian Aji

Main Job(s) of Character: Surgeon, Resident

Why your character should have this item: Sebastian as of late has been witness to many different crimes on station, several of which security has failed to respond to in time, forcing him to have to stand up and take action to minimize harm and cease hostilities between station crew. A few of the recent incidents where Sebastian has had to step up include kidnapping, assault, and attempted murder. Now filing for a permit to carry his personal weapon on station. He will only carry flash rounds for this weapon to serve as a Less Than Lethal platform. He stands strongly opposed to accosting life so he would likely never seek to load live rounds unless he has no other options remaining.

Additional Notes (If it's a permit, insert the information for the permit here): 
Gun only deals 20 brute with regular rounds or 5 burn with flash rounds (plus stun/blind) So it won't likely be an issue having it around. Pretty much a stun revolver but in a more compact form that is more practical to carry. Not effective against armored targets. Default carry would have one live magazine loaded which will quickly be switched to a flash magazine and have the lethal magazine stored away if a perilous occasion arises that requires it.

    NAME: Sebastian Aji | RACE: Panthera Tigris | HOMEWORLD: Ahdomai, Siik'tajr
    DOB: 19/Dec/2530 | HEIGHT: 198cm | SEX: Male | Expiry date: <Date added plus one year>

Fluff Item slots already used: 0 (If you count Sebastian's floofyness levels then it would be 35,663,537. /s)

**Comment by Somekindofpony** [comment]
Well, this guy isn't going to go shooting any bars up with the gun, and his character is someone who can be responsible with a firearm. I'd support.

**Comment by DemicusMaximus** [comment]
Sounds good to me.

**Comment by AeroWing** [comment]
Updated to a regular pistol to keep things practial. Max damage output would be 240brute providing all shots hit compared to a flash mag causing 40brute and 120burn.

**Comment by JoanRisu** [comment]
This is fine to me

**Comment by DemicusMaximus** [comment]
If we're fluffing it, we could easily change it to spawn with the flash rounds instead of the live ones. Already have that feature for the colts after all.

**Comment by AeroWing** [comment]
We got the pull already lined up with the permit allowing lethal and flash. So it can start with a normal magazine and I can just swap it to a flash one and holster it.
