### ISSUE TITLE
Promethean Mice Keep Escaping

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1406]
#### Brief description of the issue
The mice that spawn in the promethean's lunchboxes keep escaping when they spawn.

#### What you expected to happen
The mice to be trapped inside the box.

#### What actually happened
sqk sqk

#### Steps to reproduce
- Be promethean.
- notice the mouse running around arrivals.

#### Code Revision
- 89b93ffc4e0a33a6e2f8b8b8fb34b346a2e92fa0 
 
#### Anything else you may wish to add:
- N/A

**Comment by SpadesNeil** [comment]
Is this still an issue?

**Comment by Vorrarkul** [comment]
As of e0443cfb4b865c8561196af365d1aa78dede00b1yes it is. I will note that the mice can be put into the lunchboxes manually, but they spawn as a mob on the same tile as the promethean.

**Comment by ArgobargSoup** [comment]
Still a thing.
