### ISSUE TITLE
[MAPPING] Tether "Head of Personnel Office" (the sofa) causes BYOND to time out, forcing restart

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14099]
-- Please DO NOT report 'suggestions' on GitHub. If your issue consists of an opinion about how something should be, it doesn't belong here. -->

#### Brief description of the bug
On monday, while scening in the HoP office, my game suddenly lost connection and I had to close and re-open the game. Nobody else experienced any lag. 

While reloading, I had a black screen.

Today, I was in the HoP office doing my round-start paperwork and chatted on Command radio. Again, complete freeze, restart and black screen (NOT the "you're asleep and waking up" but as if loading assets for first time)

This occurs nowhere else while on Tether.

#### What you expected to happen
Not to crash in HoP office

#### What actually happened
Weird lag and crash

#### Code Revision
Server revision: B:release D:
Commit: [fb8c82d84113a953f8cc508789aec73aede1989f](http://127.0.0.1:64265/tmp8760/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/fb8c82d84113a953f8cc508789aec73aede1989f%22%3Ehttps://github.com/VOREStation/VOREStation/commit/fb8c82d84113a953f8cc508789aec73aede1989f%3C/a%3E)
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/20523270/202593090-b58b2eae-91c7-4472-a18c-483edba03d7c.png)

Happens both roundstart with 0 gear except stamp and folders and late round with gear.

**Comment by Heroman3003** [comment]
Irreplicable, completely. Also was not reported to have happened for some time either.
