### ISSUE TITLE
[GENERAL] Spacebikes can't fall(?)

### ISSUE THREAD

**Issue by Rick4242** [VOREStation/VOREStation#14108]
#### Brief description of the bug
even if a space-bike runs out of power, it will not fall if it has turned-off in an 'open-space'

#### What you expected to happen
If the space bike is turned off or runs out of power, it should probably just fall through open spaces in places with gravity

#### What actually happened
I was sort-of 'flying' with a spacebike just today, and it runs out of battery, but it also just kind of stayed in the open space, and I couldn't move it unless I somehow recharged or replaced the battery in order to turn it back on

#### Steps to reproduce
- Get a space-bike
- Drive the space-bike into an open space with gravity (and probably a floor at the lower z-levels)
- Turn off the space-bike in midair (or have it run out of power)
- Proceed to just sit there, unable to move the bike

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- Example of the bug happening:
![image](https://user-images.githubusercontent.com/42255398/202843221-a203b9c3-c205-465a-99d2-8c68d7fecc53.png)

**Comment by Poojawa** [comment]
can be solved by adding fall() but this seems like game/fun balance so idk about fixing it.

**Comment by Rick4242** [comment]
My main concern tbh is if someone that **doesn't** have flight or soft-fall abilities makes a space-bike, and proceeds to get stuck in the air with it powered down
Proooobably gonna hurt trying to get *off* of the bike if you can't fall safely

Not to mention the issue of trying to get the bike down if you don't have much way to get *back* to that Z-level
