### ISSUE TITLE
[GENERAL] Cannot change name of "folder" found in SD's site manager's office

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14139]
#### Brief description of the bug
Using a pen on folders in the Site Manager's Office in the SD does not change their name, they just stay as folders.

#### What you expected to happen
For me to be able to rename them as "Folder of Doom" and "Archive"

#### What actually happened
It stayed as a folder

#### Steps to reproduce
- Spawn as SM on Stellar Delight
- Grab the blue folders on your desk (see their examine in additional info)
- Use pen on them, rename as anything

#### Code Revision
Server revision: B:release D:
Commit: [891a8e24aab8ba4d65e103a65936aa3d095282a3](http://127.0.0.1:54528/tmp13216/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/891a8e24aab8ba4d65e103a65936aa3d095282a3%22%3Ehttps://github.com/VOREStation/VOREStation/commit/891a8e24aab8ba4d65e103a65936aa3d095282a3%3C/a%3E)
 

#### Anything else you may wish to add:
```
That's a folder. It is a small item.
A blue folder with Site Manager markings. 
```

**Comment by Runa-Dacino** [comment]
Confirmed working as normal with other folders (such as the HoP's red folder)

**Comment by Heroman3003** [comment]
It appears you can rename them perfectly well BUT there is unseen limitation that makes renaming silently fail if you aren't holding a folder in your hands or pockets while you're renaming.
