### ISSUE TITLE
Full Body Markings (Request w/ Sprites)

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1413]
I tried to create human full-body markings. I am intending to use these specifically to create opaque prometheans, though I imagine someone somewhere might find a more creative use for them. I don't know how to make PRs or anything, so I am leaving these here to see if you guys think it's alright. This is my first attempt at creating and editing a dmi file.

[Hopefully acceptable dmi of the sprites.](https://www.dropbox.com/s/v6tyekh1sxeypq7/human_markings.dmi?dl=0)

**Comment by Wickedtemp** [comment]
Can... can we have spots?

**Comment by Vorrarkul** [comment]
This is a... curious choice of Issue to ask that on. Are you asking me to make them? I mean, I can try... This is literally my first attempt at spriting for the server, though, a very simple edit job.

**Comment by Wickedtemp** [comment]
Oh, I was just asking cause I felt like it, you don't have to actually do it x3

**Comment by Wickedtemp** [comment]
We now have other players who are requesting this exact thing! So yeh, gud idea is gud.
