### ISSUE TITLE
[GENERAL] Joining at roundstart and Readying as Site Manager can spawn you as visitor when contested

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14168]
#### Brief description of the bug
I've readied as SM on Rascal's Pass while another player did the same. I had no other roles set to any priority, with visitor turned NO.

I spawned as a visitor despite this.

#### What you expected to happen
To be bounced back to the lobby screen so that I can pick my role manually.

#### What actually happened
I spawned as a visitor despite having it as "NO".

#### Steps to reproduce
- Take 2 players
- Player A picks a younger age, readies for Captain and nothing else
- Player B picks an older age, readies for captain.
- Wait for round to start
- Player A starts as a visitor

#### Code Revision
Server revision: B:release D:
Commit: [40027ed9185ae642f433ef7eb1497936a55b14a2](http://127.0.0.1:57995/tmp2264/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%22%3Ehttps://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%3C/a%3E)
 

#### Anything else you may wish to add:
- We were on Rascal's Pass

**Comment by Heroman3003** [comment]
Down below at the bottom of Occupation screen (or was it on top i am too lazy to check) there is an option on what to do when you fail to get any of jobs you ready up for. Three options are: Return to lobby, Spawn as Random Job or Spawn as Visitor. I imagine you had the third active.

**Comment by Runa-Dacino** [comment]
Probably got broken when the SQL went down. Fixed, non-issue!
