### ISSUE TITLE
[GENERAL] Dead geese give infinite nutrition if draining

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14169]
#### Brief description of the bug
I shot a goose and decided to be funny and ate it. I forgot I had my vorebelly on drain (thought digestion)

Something like an hour passed and I'm on max non-grey nutrition without getting below it.

#### What you expected to happen
For the goose to run out after like 30 mins.

#### What actually happened
I've got infinite nutrition. 

#### Steps to reproduce
- Spawn a goose
- Shoot it
- Eat it into a belly on digestion mode with drain mode

#### Code Revision
Server revision: B:release D:
Commit: [40027ed9185ae642f433ef7eb1497936a55b14a2](http://127.0.0.1:57995/tmp2264/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%22%3Ehttps://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%3C/a%3E)

**Comment by Heroman3003** [comment]
Can't replicate. Goose stops draining after a while, as it should. Though belly noises dont stop. And amount of nutrition gained over the total drain is ~300, which is what expected.

**Comment by Heroman3003** [comment]
Closing due to no followup info.
