### ISSUE TITLE
[GENERAL] Prometheans Lack Biolinguistics Language By Default

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#14181]
#### Brief description of the bug
Prometheans do not automatically get Promethean Biolinguistics and have to specifically select it in the Languages section.

#### What you expected to happen
Prometheans should be able to speak their blobby flashy language.

#### What actually happened
They cannot do that.

#### Steps to reproduce
- Make a promethean character.
- Do not see Biolinguistics on character setup window.
- Do not see Biolinguistics on Check Known Languages window.

**Comment by Heroman3003** [comment]
The only species that start with their languages by default are Altevians with Tavan and Shadekin with Shadekin Empathy. I'm not sure this is entirely a bug unless its gonna be a lore thing.

**Comment by ResidentCody** [comment]
I had assumed that species languages were given by default! I'm unsure at this time if that should be a thing added or not. Something to consider for later then.

**Comment by lm40** [comment]
Don't dionae get rootspeak or w/e too? Regardless I think they should have it, considering it (iirc) a special language, not really a 'conventional' thing you 'learn' or don't.
