### ISSUE TITLE
[GENERAL] Synthetic Traits Not Working w/ Drone

### ISSUE THREAD

**Issue by Obengrad** [VOREStation/VOREStation#14180]
#### Brief description of the bug
Stuff like the (discount) biofuel processor doesn't register when using drone intelligence.

#### What you expected to happen
To be allowed to take the biofuel processor family of traits while having being full-body prosthetic with a drone brain.

#### What actually happened
After taking time to make my drone synthetic character, I tried to take biofuel for convenience, but it continued to tell me that "you need to be a synthetic character to pick this trait" despite the character being fully synth. I managed to do so by switching to positronic, taking the trait, then going back to it.

#### Steps to reproduce
- Make full synth with drone intelligence.
- Try to take any of the biofuel processors.
- Have an existential crisis on your own artificial nature.

**Comment by Obengrad** [comment]
Addendum: Pain simulator doesn't work with Drone either. I'm gonna assume this issue extends to all synth traits.

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/blob/78dae78bc22bfe666e3459f12796d46ae4e74819/code/modules/client/preference_setup/vore/07_traits.dm

This seems to be where traits check if you are a synth or an organic. It's either here or in the brain defines.

**Comment by Heroman3003** [comment]
I attempted to replicate it locally and on live both and it appears I cannot get it to stop me from taking synthetic traits as any synth, drone or otherwise. Try again and if there are any other details that may be involved, do tell.
