### ISSUE TITLE
Add a separate thing in the Vore tab for wings, instead of having them under tails?

### ISSUE THREAD

**Issue by SMcGLa** [VOREStation/VOREStation#1418]
#### Brief description of the issue
I for one think that the wings should have their own tab, it just sorta makes sense to me, I suppose.

Apologies if this is a little brief  and with not a lot of stuff here in the form, but uh, I can't think of anything else to say.

**Comment by Vorrarkul** [comment]
We're only going to _increase_ the number of tail and wing options we have as we progress into the future, so it will only get harder to do this the further down the line we wait.

**Comment by Somekindofpony** [comment]
I support this as a player of a winged doggo and a catcubus.

**Comment by Cameron653** [comment]
Oh hey this issue is still open.
ITS FIXED
