### ISSUE TITLE
[GENERAL] Xenohybrid cannot wear voidsuits.

### ISSUE THREAD

**Issue by Obengrad** [VOREStation/VOREStation#14208]
No species on the voidsuit cycler allows for a Xenohybrid (custom species using the Xenohybrid base sprite) to don a voidsuit.

To be able to wear a voidsuit, not unlike a Xeno being able to wear a hardsuit.

I went through all of the species options and was unable to find one that would apply to Xenohybrid.

- Be Custom Species, select "Xenohybrid" as base sprite.
- Grab a voidsuit and attempt to put it on.
- After that fails, go through each option and re-attempt to don the voidsuit.
- Every option does not work.

**Comment by Heroman3003** [comment]
I tested it locally. I could successfully wear Unathi-adjusted suits as xenohybrid custom species. I am not sure what issue was in your case, but I cannot replicate it. Tested with engineering voidsuits.

**Comment by Obengrad** [comment]
> I tested it locally. I could successfully wear Unathi-adjusted suits as xenohybrid custom species. I am not sure what issue was in your case, but I cannot replicate it. Tested with engineering voidsuits.

I'm currently wearing an Unathi one right now, so it seems like either it was fixed already or just an issue that happened on that particular play session. Just gonna close it.
