### ISSUE TITLE
Update Command Secretary intro text to inform those who play it what it's actually for.

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1421]
#### Brief description of the issue
So, I've seen a couple of people playing Command Secretary (and equivalent) positions, who seem to think they're in some authority over other people, while under no orders from heads/no heads are even present.

#### What you expected to happen
Command Secretaries and equivalent as I have come to understand them, and have asked, are essentially bridge assistants. They are under direct orders from the command staff and are generally trusted helpers. But they don't actually have any authority over anyone unless command staff expressly tells them to go do a thing. 

Thing is, the intro text for taking that job isn't all that helpful:

> "You are a Command Liaison.
> As the Command Liaison you answer directly to command staff. Special circumstances may change this.
> To speak on your department's radio channel use :h. For the use of other channels, examine your headset."

I think it would be better if the intro text made more clear what your place and function actually was, to eliminate confusion from those who aren't very good at context clues. something along the lines of:

> You are a Command Liaison.
> As the Command Liaison you answer directly to command staff. Special circumstances may change this.
> While a part of the Command staff, you have no authority outside of what Heads of staff give you. Assist the command staff to the best of your ability.
> To speak on your department's radio channel use :h. For the use of other channels, examine your headset.

or something similar.

I'd also personally like to see one of the alternate titles for that role be "Bridge Assistant"/"Command Assistant"

**Comment by Screemonster** [comment]
This would be a good change. Personally I'm unsure where the difficulty is in understanding "you're the captain's secretary".
You're Isabelle from animal crossing. At most, you're Bellweather. You don't actually have any authority, but when you show up in an official capacity people pay attention because you've got the weight of the Director behind whatever message you're passing on.

**Comment by Benemuel** [comment]
Its always !!FUN!! when one of them tries to run security when there is a HoS present, and basically acts like a min-captain. Of course from what I have seen THAT gets them on the admin shitlist real fast. But trying to tell officers and the like that they can't do X is weird. Doing the same to assistants, is ALSO weird.

**Comment by Yoshax** [comment]
People probably get all caught in the fact that they're 'Command' or a 'Command [Doesn't Matter]'. You may be better off putting them outside the Command Manifest, and maybe with IA or something in Miscellaneous, or add another section. You could have like 'Support Staff' with Command Secretary, Internal Affairs and possibly more jobs in the future.

Also, I thought they were all of Command's assistant and not just the Colony Director?

**Comment by Benemuel** [comment]
Well I have yet to have one offer me help as the HoS so, they seem to think they are the CD and HoP's only.

**Comment by Yoshax** [comment]
I had one offer to help me when I was the CE!

**Comment by Very-Soft** [comment]
Yeah they answer to all of the heads, not just the director and hop.

**Comment by SpadesNeil** [comment]
I said this would be a problem when Polaris added it, but whatever. :U

**Comment by Wickedtemp** [comment]
The role isn't utilized too often because, on Virgo, Assistant means SexSlave.

The times it IS utilized, it's mostly by people thinking they've finally got authority with zero responsibility.

It kinda bums me out, because the job had potential to be a 'stepping stone' to other Command roles, but since it was added, I've seen a grand total of ONE player use it as such and played as an actual secretary, assisting with paperwork. They were also well-versed in SOP and the Chain of Command, so they really did put effort into learning the job. Now they're normally the HoP or CD.

Also due to 'extended only unless admins decide to blow something up' gamemode, there...usually isn't a whole lot for them to assist Command with, other than ERP.

**Comment by Very-Soft** [comment]
Yeah, I really like it as being a sort of almost 'Command intern' position. The character I play that uses that role is ICly trying to shadow the heads to learn how best to do their jobs, while generally assisting them with all kinds of things.

I love it when it's used for that.

I -hate- it when some guy in the role comes into the bar and tries to tell me to go fix some busted lights in the cargo hallway when there's no command staff around to have asked them to give that order. I don't mind helping out if asked. But I've seen a couple of different people in the role trying to give people orders while no heads are present. It happens really super rarely, but I just think that some clarification as to what the role's job actually is in the intro text could help clear that up.

Maybe.

**Comment by Benemuel** [comment]
At the same time using it as a position to just fuck off with command access like a normal assistant is also bad.

**Comment by Very-Soft** [comment]
Well, I think that the Command Secretary is generally expected to be willing to actually do stuff that the Heads ask of them. Where, while sure the Assistant ranks are supposed to do the same, it's not really treated that way.

I'd imagine that the command secretary would be prone to some pretty strict rules and potential for reprimand icly.

Mechanically though, it's basically a bridge assistant.

Well, the funny thing is that as the Command Secretary, you basically have the same authority as an assistant, but without the maints access. Sure, you can go on the bridge and to the meeting room. So there's an interesting trade off there.

**Comment by Very-Soft** [comment]
I saw a Command Secretary try to change someone's access today.

**Comment by Wickedtemp** [comment]
I guess put extra, extra emphasis on "You are an Assistant like any other, you just serve Command Staff in specific. You do not have any authority over anything, at all. You're still just an Assistant."
