### ISSUE TITLE
Science Typo!

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1424]
#### Brief description of the issue
It says 'Reseach' instead of 'Research'. 

#### What you expected to happen
I was going to perform some miscellaneous research!

#### What actually happened
I was forced to perform reseach instead, which was a bummer and a HUGE letdown.

#### Steps to reproduce
- Go into Research
- Look at the airlock
- Point out the typo
- Get brutally dominated by the RD in retaliation.

#### Code Revision
- Server revision: release - 2017-04-19
89b93ffc4e0a33a6e2f8b8b8fb34b346a2e92fa0 
 
#### Anything else you may wish to add:
http://imgur.com/a/pdrAW

**Comment by Somekindofpony** [comment]
I am in favor of leaving this in as you will be bothered by it forever.

**Comment by ArbyTheDragon** [comment]
IIRC, the 'name' of the airlock is a string that's set by the map .dmm itself. Someone misspelled it there.

This issue should be tagged as "Type: Map"

**Comment by Dhaeleena** [comment]
No longer relevant on the current map.
