### ISSUE TITLE
Make Posibrains and Intellicards edible? (But not digestible)

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1426]
So I've had a couple of people want to eat me as a carded AI, which I was pretty k with oocly, but, there's quite a lot of hoops to jump through to achieve this, beyond the whole, getting into the AI core and that.

Additionally, been gurgled as a synth with a posibrain a couple times now, and that's pretty neat. I quite like that the Posibrains aren't digestable. However, your posi starts with the switch off. Which means that if the pred wants you to be able to talk back while you are a sentient cube, they have to spit you up, put you onto something else, then eat -that- thing.

It'd be neat if the pred could cough you up, flip the switch, then eat you again. It'd be neat.
I of course have no idea how easy/hard such a thing as this would be to implement, of course.

**Comment by SpadesNeil** [comment]
Oi, no eating those. They're expensive. (Swallowing an AI card is actually probably fine. Not sure posibrain is smart, though.)

**Comment by Very-Soft** [comment]
Why's that? You can already get the posi in there as is. Problem is that after digestion the speaker switch is off and far as I know, there's no way for the pred to turn it on without coughing the brain up. Then they can eat it again by putting it onto another body, then eating and gurgling them.

You can achieve the end result of what I've suggested as is. I just think that the hoops of finding something with pockets/bags to put the brain into and then digesting that, for something that you already ate and coughed up is silly.

**Comment by Dhaeleena** [comment]
I really want this. Being a Synth player is fun and being gurgled up and still being technically alive and well but just stuck with your pred is pretty neat, But once im coughued up thats it, I need to go get a new body and stuff, It would be nice if i could be pushed into a new hole again.
Just to note, Posibrains are alredy items that stay inside belly after digestion. So i think this would be as simple as using the same code we use to Eat Beacons. Then again, We need to fix the #1358
