### ISSUE TITLE
[MAPPING] SD Away Team/Former Explo Area has misaligned Fire Alarm.

### ISSUE THREAD

**Issue by Skysteak** [VOREStation/VOREStation#14287]
#### Brief description of the bug

A Fire Alarm in the Away Team/Former Exploration lobby is not aligned correctly.

#### What you expected to happen

For the Fire Alarm to be up against a wall.

#### What actually happened

The Fire Alarm is patiently sitting on a chair. 
 

#### Anything else you may wish to add:

An image of Fire Alarm is supplied: 
![fire alarm alignment](https://user-images.githubusercontent.com/78493013/210194964-4260f763-6032-454e-a9a4-414ac09b9ec3.png)

**Comment by Heroman3003** [comment]
Fixed with #14295
