### ISSUE TITLE
Server revision: Unknown!

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#143]
#### Brief description of the issue
Server revision appears as unknown!

#### What you expected to happen
I click the server revision button and get told what revision it is.

#### What actually happened
Server revision: Unknown

#### Steps to reproduce
Click the button! You know the one, under OOC.

#### Additional info:
 - **Server Revision**: YOU KNOW DAMN WELL I HAVE NO IDEA EITHER.

Marked as blocker because it interferes with development and version control.

**Comment by Arokha** [comment]
I'm not sure why -- no wait I know why.

It reads the revision out of the git files. The folder the server runs out of has to be a local git repo. I'll get on the server and fix it for the first update.

**Comment by Arokha** [comment]
Fixed. Now lists the commit hash and date.
