### ISSUE TITLE
Runtime vanishes if put on a table.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#1433]
#### Brief description of the issue
Runtime, when put on a table, Vanishes into thin air never to be seen. Sometimes does the same when picked up and put down.

#### What you expected to happen
To pet the fluffy cat on a table. Or put them down.

#### What actually happened
Runtime vanished like a puff of smoke.

#### Steps to reproduce
- (Step 1)Grab Runtime.
- (Step 2)Put them on a table/drop them.
- (Step 3)Watch them vanish.

#### Code Revision
Server revision: release - 2017-04-26
59244d98cee95a8df9ebc3a3faa55b0640880419 
#### Anything else you may wish to add:
- I. Do not know why this could even happen. Its maybe the strangest bug I have found.

**Comment by Dhaeleena** [comment]
Dont give the cat high ground, It will ascend into a new plane of existance

**Comment by SpadesNeil** [comment]
Is Runtime just under the table?

**Comment by Benemuel** [comment]
No. And I just put them down and the dissapperead too.

**Comment by ArbyTheDragon** [comment]
Holy cow. This bug defiantly cropped up somewhere in an earlier version and wasn't in previous ones. I've never seen that happen before.

**Comment by SilverTalismen** [comment]
Guess Runtimes throwing afew..Runtimes?

**Comment by ArbyTheDragon** [comment]
SilverTailsmen, that gives me an idea actually.

 **Could the console give any insight into what's going on?**

**Comment by SilverTalismen** [comment]
On what?

**Comment by ArbyTheDragon** [comment]
I should have clarified prior. Sorry-

Well, if Runtime isn't being deleted, then Runtime is somewhere. So where is it? A spectator could follow it.
If Runtime is being deleted or is being moved to a container, maybe a console set to verbose logging could catch what the server is doing to Runtime the moment we put it down on a table? The bug occurs only under very specific circumstances, so it would be very easy to find when the action would show in a log. 

_(I do not claim to have any knowledge into how actions get printed to admins, or how the server can log certain actions)_

**Comment by Leshana** [comment]
Cannot reproduce by either putting on a table, dropping, or moving from hand to hand.  Does this still reproduce for you?

**Comment by ArbyTheDragon** [comment]
It was accidentally reproduced a few days ago when runtime was in the medbay lobby. I was holding runtime and then runtime jumped off of me and ran about. While we were trying to pick him up again, I believe one of us succeeded and he jumped off while we were _near_ a table, disappearing immediately.

So, while it might not be deliberate, this bug still occurs under some circumstances.

**Comment by Dhaeleena** [comment]
Maybe, He saw a micro? Do you know if there was a micro or some other animal runtime could have seen?

**Comment by ArbyTheDragon** [comment]
We believe he did see a micro. There was one in the scanner room at the moment.
