### ISSUE TITLE
Unathi TF

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1434]
#### Brief description of the issue
Currently, any species thta is transformed into a Unathi suffers massive internal issues =due to having appendix's and kidneys being present, due to the recent changes to unathi biology they begin to suffer large amounts of toxins and possibly even organ rejection entirely

#### What you expected to happen
To possibly have this fixed by the TF removing those organs

#### What actually happened
https://gyazo.com/84db344d44038caba7efe286ad86aaa5
Lots of organ failure
#### Steps to reproduce
- (Step 1)Be any race that isn't unathi
- (Step 2)get turned into a unathi
- (and so on)Suffer

#### Code Revision
release - 2017-04-26
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Wickedtemp** [comment]
This can become quite literally a round ruiner for some. One patient ended up with 999u toxin as a result of organ rejection. We had to just resleeve them because there's no way we could've healed them in a timely manner.

**Comment by ArbyTheDragon** [comment]
999 Toxin? At least when you die, damage stops incurring itself. Once you're at -100%HP, you're dead. How can you possibly get THAT much?

Carthatoline is a **very robust** anti-toxin. Think that would work if we catch them before they're actually dead?
Carthatoline seems to remove 8 toxin per 'tick' _(Whatever the timescale may be for incurring the adjusttoxloss damage proc)_ according to the code, whereas dylovene only removes 4 toxin.
We could combine the two for -12 tox per 'tick', for something 3X as strong as dylovene.

Whether death is preventable or not, this is still a nasty bug that needs to be fixed, I was just theorizing for fun.

**Comment by Cameron653** [comment]
Will look into this in and see if I can whip up a fix real quick

**Comment by Cameron653** [comment]
Fix found. Will put up the PR in a little bit along with a small feature.

**Comment by Wickedtemp** [comment]
Ziah, it isn't 999 toxin damage.

It's 999 units of toxin, the substance, in the bloodstream.

But yay, fix found.

Also, it might be a good idea to check whether or not blood types are affected. If they are, someone could potentially experience poisoning due to being changed to an incompatible type of blood.

**Comment by JoanRisu** [comment]
This issue seems to have spread to Taj TFing to humans.

**Comment by Wickedtemp** [comment]
Alright, lovely.

Time to check TF from every species to every other species, and TF from human to human with different bloodtype.

**Comment by Cameron653** [comment]
Tajaran don't have any special organs, so they shouldn't be having organ rejection.
Also, bloodtype is already fixed with TF via the fixblood() proc.

**Comment by Cameron653** [comment]
Fixed via #1439
