### ISSUE TITLE
Benemuel - Daemon and Enochian language apps.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#1437]
Was told by table/SomeKindOfPony to place them here now that they have been accepted, I'm guessing for someone to just make a quick edit to ad my C-Key to the whitelist and the like for the next update.

http://forum.vore-station.net/viewtopic.php?f=45&t=907&p=5866#p5866
http://forum.vore-station.net/viewtopic.php?f=45&t=906

No fluff stuff due to the chars technically already existing and not needing anything special besides the languages. Please tell me if I did something wrong with this issue, I'm honestly not entirely sure what I am doing with SCA and language apps.

**Comment by PontifexMinimus** [comment]
#1472 will put you on.
