### ISSUE TITLE
[GENERAL] Can't fix stained feet

### ISSUE THREAD

**Issue by Rick4242** [VOREStation/VOREStation#14396]
#### Brief description of the bug
For some reason there is seemingly no (IC-ly) feasible way to clean your feet if they get dirty

#### What you expected to happen
One would think sticking-around in the shower for a while could clean-off someone if their body ~~not clothes~~ is somehow stained with something.

#### What actually happened
Of all the things that **can't** be cleaned by the shower, or anything really, (pretty sure even taking the limb off and putting it back on doesn't work.) for some reason the character's feet are the only thing that can't be cleaned in such a way.

#### Steps to reproduce
- Don't wear any kind of foot-wear
- Step in any kind of 'staining' fluid (oil/blood/etc.)
- Realize your feet are now stained
- Try to get the stain off, **by any means necessary**  ~~taking off your feet and leaving them off doesn't count~~.

#### Code Revision
- Server revision: B:release D:
Commit: [88d9040f0ecd8c2381ac8567febdadfac5b95312](http://127.0.0.1:49490/tmp4316/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/88d9040f0ecd8c2381ac8567febdadfac5b95312%22%3Ehttps://github.com/VOREStation/VOREStation/commit/88d9040f0ecd8c2381ac8567febdadfac5b95312%3C/a%3E)

**Comment by CMDRYouth** [comment]
A spray bottle of space cleaner can do the trick.
Try carrying soap with you so you can clean stains before you step in them.
Or wear footwraps/legwraps around hazard areas if shoes aren't a thing your character does.
