### ISSUE TITLE
Special Character Application: Vexa 

### ISSUE THREAD

**Issue by TheLastRaccoon** [VOREStation/VOREStation#1442]
#### Type of character: Redspace entity / Demonic spirit

Vexa is an invisible spirit that normally and quite listlessly floats in a corner, generally completely out of sight and out of mind. However, every now and then, someone will catch her eye. This unfortunate person will be the subject of Vexa's morbid curiosity and amusement; some things she enjoys doing are, but not limited to; possession, mind control, and complete domination. Once touching someone she means to interact with, she becomes visible to them and only them. However, if someone she had no interest in touches her by accident, she will not appear. This seems to elude to her being able to control her transparency.

Despite being able to wreak widespread havoc with her powers, she's mostly inert and only seems to be interested in having fun. If there were records of her existing - and there surely isn't, for the thought of ghosts being real is absurd! - they would detail her only capturing / dominating persons of interest to her, only to leave them unharmed after she's done with them, with all of their belongings.

#### What does that mean from an OOC perspective?

She doesn't do stupid shit like "I AM GOING TO TAKE CONTROL OF THE CAPTAIN. I NOW HAVE ALL ACCESS, OBEY ME." That's just stupid, and completely unreasonable. I'll only interact with people who I as the player believe will enjoy interacting with Vexa. I may get upset at vidya games sometimes, and fully accept that stigma, (workin' on it of course) but I would be upset if I were accused of not roleplaying characters to their respectful mindsets. Izi will fight and incapacitate threats with little fear. Bessie will cry and pretty much piss herself if a fight breaks out or if someone is too upset at her. Linzelly will foolishly try to fight but will always be outclassed, Visivex will try to talk herself out of a situation instead of trying to fight and will surrender if talk is impossible, and so on. I never _ever_ powergame, because I make a conscious effort to not do it. With this in mind, I'm not going to pretend that Vexa can dominate anyone on the station or that she can do ridiculous things without that individual person's consent.

**Comment by SpadesNeil** [comment]
Special character apps are supposed to be done on the forum and get linked here once approved. I also don't like the idea of a redspace entity as a regular character.

**Comment by TheLastRaccoon** [comment]
I cannot access the forums, and was told to make my application here instead by administrators. Also, the character has already been played on the station numerous times; and has been interacted with and met with quite positive feedback.

**Comment by SpadesNeil** [comment]
I'll leave @JoanRisu and @Screemonster to handle this, then.

**Comment by Arokha** [comment]
I'm not sure 'invisible spirit' makes a lot of sense unless you're also going to request something that literally allows her to be an invisible spirit. Not a fan of things that SHOULD be mechanically implemented that are just shoved into OOC notes.

**Comment by Screemonster** [comment]
literally invisible spirit, how are you proposing to accomplish that mechanically?
Has powers, how are you proposing to accomplish that mechanically?
Supernatural entity just hanging around chilling in the bar, why?
I can't see anything about this character that really fits into the station setting _or_ would be enhanced by playing them in a SS13 environment instead of literally any other RP medium.

**Comment by TheLastRaccoon** [comment]
Mechanics - I'm not proposing to accomplish anything mechanically. Like I said before, I actually tried this character out on station for a few days to see if people would play along with her invisibility, and they did wonderfully. Not a single person took it upon themselves to "see" Vexa, and instead ROLEPLAYED it exceedingly well, even Security members on multiple occasions which I very much appreciated.

If you are going to bring up having "powers", she's no different than anyone else that likes to mind control people or otherwise take advantage of them. I see characters that use mind control all the time, yet no one bats an eye. I see a character labeled an "evolution master" that can literally shift his entire body into anything he wants at any time, along with a custom-raced individual who has pastebin upon pastebin of their character's special anatomy which includes having a body composed of so many different / advanced bacteria that upon death their body will explode, a woman who literally bestows omnipotent powers with a kiss who has been around for literal months, I really could go on and on.

Supernatural entity hanging around in the bar - well, that's not exactly accurate. The short answer is she goes where people are, otherwise it's the entire station, she just realizes that the place to observe most people is in the bar, so she typically goes there. If people congregated in a different place, that is where she would go as well, unless she wants to visit another place for some reason, but that's irrelevant. 

Character not fitting into the SS13 environment - I can agree with you that a spirit isn't really fitting for SS-...oh, wait. People who observe are playing ghosts, are they not? In the Cultist gamemode, ghosts are literally brought in to be played as golems, and are able to interact with the crew, so having a spirit that interacts with crew is in of itself fitting in the SS13 universe. But fair enough, since we don't have cult gamemodes, you're likely referring to this specific server, in which case I would bring up the argument that how is anyone's character enhancing the SS13 environment by playing them on the server? The short answer is it doesn't matter, they're just a character portrayed in pixels in the game. The long answer is you can pop this question on anyone because it's much too broad; how do evolution masters fit on the station? How does omnipotent-gifting women? Or even your own character, Scree? If you're going to ask this question, why give people the freedom to create their own races in the first place, or even create Redspace and have events involving it for that matter? The answer is because I want to have fun playing this character and make fun for others who interact with her. That is the objective I am aiming for, and so far, I have succeeded in getting several scenes and multiple compliments on the original idea. Not a single person (Except for staff) even hinted IC'ly that this character was unrealistic or otherwise implied that they don't want to be interacting with her, because I simply don't interact with people who wouldn't enjoy ghost stuff.

This brings me to my closing statement; it's explained in the original post, I never abuse authority, a character's powers, or a character's standings. If my character possesses the Captain, she is not going to take the ID for herself or otherwise do anything else with it - she's going to be done with the Captain and that's that. Neither is she going to attempt to bring people into a roleplay who don't want to be there, like Rana did. (I admit, I got a bit carried away with her.) Honestly, everyone who's ever interacted with her has given her nothing but praise, and I know that sounds snotty, but it's the truth. I personally don't believe that a Redspace entity who haunts the station is too out there, purely because why else have Redspace and entities that literally haunt the station in events otherwise? Yes I understand, events are to entertain the crew and all that, but I plan on doing the exact same thing, except on a smaller scale. 

I hope this has provided you with a proper explanation on the character and convinced you, if you have any other questions, I will be more than happy to answer them regarding her.

**Comment by SpadesNeil** [comment]
Ghosts are OOC in this server. Ghost are never IC and are never treated as such. We do not have cultists here. We do not even have space wizards anymore.

Using Scree's character as an example of why you should be allowed to play this is extremely bad. When making a character, you're supposed to ask the question of why this character needs to exist. Not why you can't have it, and then explaining those problems away. Scree gets to be a character because Scree is fun for players besides himself. This on the other hand is not. It's extremely immersion breaking and I am adamantly against this character being allowed as a regular character. That removes a substantial chunk of the mysteriousness of Redspace if we do this by making it a regular thing, and that ruins the experience.

I am voting against this.

**Comment by TheLastRaccoon** [comment]
...You did read past the cultist point, did you not? I also did not only use Scree's character, I used multiple. These two oversights alone lead me to believe you did not give me the decency to read my entire post. Contrary to your opinion, this character is also fun for others involved as well as myself, literally using personal experience as my facts. It's all jolly well and good if it's your opinion that it isn't a fun character, but it is a wrong one, as I have literal proof of several days worth of characters interacting with them in a positive manner. Which, again, belies your ignorance or just selective memory about my previous posts. 

As for making it a "regular thing", it isn't. This is a special character application, for this is a special character that is by no means regular. I don't know what you're trying to accomplish by posting what you did, but I'm confident that this overrides everything you've said, unless you have something else to bring to the table. That being said, I still respect your opinions, and your thoughts are your own.

**Comment by SpadesNeil** [comment]
I did read the whole thing, actually, and considering your snide remarks about our supposed ignorance for not allowing what you consider to be a character we should allow, I don't think you actually acknowledge or care about how other players will be negatively impacted by this character's existence.

Next time you post an app, post it on the forum as well. I'm not sure why someone told you to post it here, but they were incorrect for doing so. We do not review applications on Github normally. Note however that this does not affect the following result of this character.

**Your application is rejected.**
