### ISSUE TITLE
Tajara small rework maybe?

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#1444]
#### Brief description of the issue
Tajaras are creatures with fur, Covered in fur, Not covered in flammable strands of phoron. A tajara Should only take extra Burn damage from being inside a very heated room or being literally set on fire, May it be my gases or flammable fluids being spilled on the tajara.

#### What you expected to happen
Tajara to only burn harder when they actually burn.

#### What actually happened
I get shocked with electricity and instead of a second grade burn i get a third grade burn because i have extra hair on my body, I get shot by a laser and the fur on my body acts as super lenses causing it to burn even stronger.

#### Steps to reproduce
- (Step 1) Touch an electrified door. Get Instantly killed or Sent into super crit
- (Step 2) Get shot by a laser, Congrats your fur augmented the laser

#### Code Revision
release - 2017-04-26
59244d98cee95a8df9ebc3a3faa55b0640880419 
 
#### Anything else you may wish to add:
-Butts

**Comment by Arokha** [comment]
Tajara OP pls nerf. 200% fire damage instead.

:shipit:

**Comment by Yoshax** [comment]
It's just balance for being super duper fast. It's not really as huge an amount as you're making it out to be, it's 15%, the same damage reduction that Unathi get.

**Comment by Dhaeleena** [comment]
I was thinking on making tajara much harder to set *off* fire, So like, Make them have double fire stacks or make them harder to turn off without an extinguisher. But this is more for fluff too, Doesn't make much sense. Things that Stick to the fur like flammable fluids and toxic flammable gasses should be harder to remove when set on fire on a tajara, electricity doesn't make much sense neither does lasers. A badly set up engine with a massive output could possibly ash a hand on a tajara

**Comment by Dhaeleena** [comment]
Im also making this issue here because this probably wouldn't fit on a more action charged place, This kind of mechanic fluff changes just for the sake of giving things some some sense

**Comment by Wickedtemp** [comment]
I personally don't see an issue, as someone who plays a tajara mechanically. 

If you don't wear gloves and get your hands ashed when hacking something open, that's kinda your fault for not following a simple safety protocol. 

For lasers and acids, that's just something that comes with the job, Sec/Med, etc. I could accidentally splash acid on Tempest's insanely large sprite and suffer extreme damage, even more with the extra modifier, but that's just a workplace hazard that comes with the role.

**Comment by Dhaeleena** [comment]
I understand that, Im not discussing its a bad mechanic or unbalanced. Im just saying i dont think it makes sense and would like we could do some adjustments for the sake of fluff

**Comment by Arokha** [comment]
Irrelevant with upcoming trait system.
