### ISSUE TITLE
[GENERAL] APC power ticked 100%, cyborgs had their batteries charge over limit while getting warnings about power surges

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14457]
#### Brief description of the bug
Once the engine was started (tesla) the APCs on the power list kept ticking over to 101% then back down, and all the cyborgs onshift were constantly getting some kind of spam message about a 'power surge' and infinitely getting their batteries charged
they all ended with batteries in the thousands of percents

#### Steps to reproduce
- Unknown, occured on 2023/02/06

#### Code Revision
Server revision: B:release D:
Commit: [710c31b5caab2d9fb11c41b52d1bdadb9ae35498](http://127.0.0.1:55123/tmp3284/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/710c31b5caab2d9fb11c41b52d1bdadb9ae35498%22%3Ehttps://github.com/VOREStation/VOREStation/commit/710c31b5caab2d9fb11c41b52d1bdadb9ae35498%3C/a%3E)
 

#### Anything else you may wish to add:
- Third-hand account based on second-hand account given in discord. Borg player did not respond to the ping asking for first-hand account.
Was reported at UTC + 0 ~17:00

**Comment by Heroman3003** [comment]
Are you sure it was power surge and not "Energy boost"?

**Comment by Runa-Dacino** [comment]
Fixed by https://github.com/VOREStation/VOREStation/pull/14584
