### ISSUE TITLE
Whitelist - Enochian and Daemon Languages

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1446]
[Link to Approved Application,](http://forum.vore-station.net/viewtopic.php?f=45&t=910) Replicated Below
---
**BYOND Key:** vorrarkul

**What kind of character/language do you want to apply for:** Enochian and Daemonic Languages

**Name of Characters In-game:** Nereza Venatrix

**Are they a fan character of another franchise?:** No

~~**If so, what the hell are they doing here?:**~~

**How long you've been playing Vorestation:** Since October of 2014 at least, possibly even September.

**What is this character's backstory?:** Born as a succubus on Infernum to two parents who really couldn't care less, Nereza had a hard childhood. When she reached adulthood at the age of 25, they finally tried to get rid of her by selling her off. Somewhat disgruntled by this turn of events, Nereza killed both of them in a rage. Thanks to resleeving technology combined with Infernum's unique views on murder, she was merely charged with assault and paid a fine. For ten years, she worked in the city of Sloth, for the Acedia Corporation. What she did there is not really known; Acedia is notoriously bad at keeping records. It's believed she was licensed to trap and hunt animals, but there's no way to be certain.
When she was 35, she met a Sanctum-native angel who had managed to get himself stranded on Infernum. She made a deal with him- she'd help get him back to Sanctum, as long as he took her with him; she had grown tired of the chaos and anarchy that dominated her home, and had become curious about the so-called paradise ruled by the angels, and this was a golden opportunity that threw itself into her lap.
When she arrived, she found herself an outcast, a stranger in a world that shunned strangeness. She managed to get a job with the Sanctum Automation Repair Branch, maintaining the machines that support the angels' leisurely lifestyles. That was when she made her first slip- she insulted her client while on the job, and was assigned to a week of therapy. It was torturous; they explained the consequences of rude behavior to her until she was bored out of her horned skull. This was but the first of the many, many missteps she would take on her road to acceptance, and each time, more therapy. Sanctum revealed itself to be far far worse than Infernum; it was positively boring!
Nevertheless, Nereza remained determined, slowly learning what was expected of her. She started learning Enochian to better understand her clients' needs, and even accepted a generous offer to modify her genes so she wouldn't look so much like an outcast. She gained new, organic-looking prosthetic legs in place of her cold iron limbs, removed her spaded tail, changed her crimson bat wings to be covered in crimson feathers, and even altered her skin tone to be almost angelic- if a little pink thanks to her original maroon hue. Now, on her second year living on Sanctum, she has gained full citizenship and her efforts have finally born fruit, allowing her to experience the life of ease Sanctum promised to her back on Infernum.
However, idle hands make for a bored ex-succubus, and she asked the Repair Branch to give her something more to do; so, they gave her a second job on the NSB Adephagia.

**If they speak any special languages, why do they speak them?:** She grew up on Infernum and now lives on Sanctum

**What do you expect them to bring to the station's RP by this character being allowed?:** ~~Nothing but **PURE DEMONIC EVILNESS**.~~ Interesting drama should she meet citizens of Infernum or Sanctum; Infernumites may dislike her for abandoning the liberty of Infernum, or perhaps may be curious about life on Sanctum. Sanctumites may dislike her for being a filthy demon, or be curious about why a member of such a wild and untamed people would want to join them.

**Play out the following simulated RP scenario (also feel free to alter this, as it is just an example scenario):**
Recruiter: "So, tell me about yourself... what was your name again?"
You: "Nereza Venatrix." She sits, fiddling idly with her white dress- she's not yet become accustomed to angelic fashions, and would much prefer a tight pair of shorts than the soft, flowy garment she wears now.
Recruiter: "Riiiiiiight..." The recruiter scribbles on his notepad, taking down notes. "Tell me about how you came to live on Virgo Prime."
You: She is rather surprised that he didn't mention she was late- she was expecting another citation for oversleeping. "Oh, I don't; I'm a citizen of Sanctum. I use your gateway system to get here."
Recruiter: The recruiter nods, hardly making eye contact as he reads off the standard list of questions. "Do you have any past experience working on NanoTrasen stations?"
You: "No, but I've worked for big companies like Acedia Corporation and for Sanctum Automation's Repair Branch. Well, that last one isn't really a company so much as a governmental department..."
Recruiter: He nods again, writing down some notes, or perhaps doodling. It's impossible to tell which. "And what do you think you can bring to the company?"
You: "I am a very hard worker: I worked my a- I worked for an entire year just to earn citizenship for Sanctum, and even before that, I strove for excellence with Acedia... but they probably never wrote that down..." She mentally kicks herself, of course Acedia didn't bother writing down any of it; _I was probably lucky they remembered to put me on payroll,_ she thought to herself.
Recruiter: "Very well. Thank you for your time. We will contact you as soon as there is an opening suited for you." The impatient recruiter finally looks up again and waves the applicant along, ready for the next potential new employee.
You: She stands up, straightening her dress, almost performing a small curtsy before realizing that only angels care about that, and walks out, her white flats matching her white gown.

**Why do you want to play this individual?:** She has potential conversation hooks for anyone who is aware of our angel and demon lore, and hence knowing both languages will be of help in that. Knowing these also fits her backstory. As for the character herself, she is a woman trapped between worlds; she has the independent spirit of Infernum, but can see the value of the order and peace of Sanctum.

**Comment by PontifexMinimus** [comment]
#1472 fixes this.
