### ISSUE TITLE
AIs and other silicon firendohs don't have radio chat timestamps like they used to

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1448]
#### Expectation:

To have timestamps on radio messages so said messages can be cited icly as needed, like a litigious robot do.

#### What actually happened:
No timestamps

#### Steps to reproduce
- 1.Be a silicon
- 2.Hear a message on the radio.
- 3.See there is no timestamps.

#### Code Revision
- Server revision: release - 2017-04-26
59244d98cee95a8df9ebc3a3faa55b0640880419

**Comment by SpadesNeil** [comment]
Was this ever fixed? It seems to have been fixed afaik
