### ISSUE TITLE
[GENERAL] Sprite bug: Spidertaur body type unable to be surgically healed. 

### ISSUE THREAD

**Issue by Naessa** [VOREStation/VOREStation#14489]
#### Steps to reproduce
- Apply anasthetic mask
- Fail to open an incision at any point while conscious or not
- Apply bluespace size standardization bracelet, still unable to select for surgery. (Sometimes large sprites have clipping issues)
- Fail to open incision.
- Continue to try other methods after second scoop, now patient is standing unaided despite broken foot. Still asleep as tied to mask in wall dispenser
- Try turf menu and other options, ultimately give the spider a wheelchair to check back into the round after exiting for a brief time.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- Having completed surgery on the same table minutes prior, it's likely the patient's sprite was causing the issues here.

**Comment by Heroman3003** [comment]
Cannot replicate. Everything works normally.
