### ISSUE TITLE
A grammar flubb is warping reality in the gym.

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1449]
#### One of the chat messages from hitting the clown punching bag has an obvious grammar error.
"You hammer the clown right in it's face with your fist."

should be

"You hammer the clown right in its face with your fist."
 because the possessive form of "it" does not have an apostrophe ( ' ).
It's is a contraction of "it is".

#### What you expected to happen:
To hammer the clown right in its face with my fist.

#### What actually happened:
Hammered the clown right in it is face, with my fist.

#### Steps to reproduce
- 1.Punch a clown punching bag in the gym a few times.
- 2.Read chat messages that result.
- 3.Grind your teeth if that kind of thing bugs you.
- 4.Marvel as the clown becomes face.

#### Code Revision
- Server revision: release - 2017-04-26
59244d98cee95a8df9ebc3a3faa55b0640880419
 
#### Anything else you may wish to add:
- [Screenshot of a log](http://puu.sh/vzF1F/23287a5f50.png)

**Comment by DeepIndigo** [comment]
I'd like to add, this has been an issue the entire time I've been at vorestation (coming up on a year now). I just didn't think to report it until now.

**Comment by SpadesNeil** [comment]
Was this ever fixed?
