### ISSUE TITLE
[GENERAL] Protean Speech Bubble

### ISSUE THREAD

**Issue by Obengrad** [VOREStation/VOREStation#14509]
#### Brief description of the bug
Proteans seem to have the default white organic speech bubble no matter what.

#### What you expected to happen
I expect the speech bubble to be the black/blue synth bubble if I select the synthetic larynx, even if I don't technically have one, or for there to at least be a method to swap it, like the many Protean shapeshifting abilities.

#### What actually happened
When I speak as a Protean it uses the default white bubble, even after selecting the larynx or even swapping to different models from my usual.

#### Steps to reproduce
- Spawn as Protean
- Hit "T" and begin to type
- See how the bubble is default white.
- Change to a different model type and repeat the last two steps ad nauseum.

**Comment by Runa-Dacino** [comment]
@Heroman3003 should be closed as is fixed by your PR https://github.com/VOREStation/VOREStation/pull/14536
