### ISSUE TITLE
(Fluff Item)Special Implant! - Chakat Tempest - Wickedtemp

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1450]
Name of Item: Natural Mammary Glands!
     
Item description: OOCly, an implant with an internal storage that produces milk by using nutrition which you can later retrieve via container... which allows for ICly, being 'productive' and milked. 

Sprites (or link to sprites): Default implant sprite. My idea is using the implant as an OOC means to make Tempest be naturally 'milkable' ICly so the appearance doesn't matter. 

Any additional resources: The code is a WIP!

BYOND Key (Username): Wickedtemp

Name of Character: Chakat Tempest

Main Job(s) of Character: Doctor, Chemist, CMO and Resident

Why your character should have this item: Tempest is a hermaphrodite with two very large female attributes on hir chest. 

Additional Notes: http://forum.vore-station.net/viewtopic.php?f=20&t=433 This was suggested as a blanket add-in for all characters in the past and was denied because, well, let's face it. When a new feature is added, people immediately start spamming it. It happened with driders and webs, it happened with mlems and awoos, it happened with flipping. The same would happen if everyone was given a lactating mechanic. It'd get spammed, people who didn't want to see it would be forced to see it.

But, this would only be done between people who want to do it. We've approved kink 'genderswap' items in the past, another potentially pref-breaking item that has, so far, been used purely to enhance the roleplaying of those who have it. You can only GET milk out of the 'implant' by using a container on the host, so it isn't something that's likely to happen completely by accident, and I'd like to think that, if nothing else, in the time I've played on the server I've shown that I'm not the type of person that'd intentionally prefbreak. 

I've talked about it with a couple of Staff and they thought this was a neat concept, so here's the official app. Questions, comments, concerns and fun-facts are all welcome.

**Comment by Arokha** [comment]
`Pick the emote to trigger your implant:`
`*wink`

**Comment by BlackjackFajah** [comment]
Actually I find this to be a great thing. If the code was created and, following in the shadow of said code alot of other implants and mechanics can be born from it.

**Comment by DeepIndigo** [comment]
Could be neat. I play a character who's a mother so, I mean, I could see use in this. Maybe make it a whitelist thing if it's implemented for anyone other than tempest?

**Comment by Wickedtemp** [comment]
The code for it is rather generalized, so you could change it to produce...just about any reagent.

**Comment by Somekindofpony** [comment]
Honestly, I don't feel like we should be denying these features because of their possibility to break preferences, I'd rather take away their ability to use the feature instead.

**Comment by DemicusMaximus** [comment]
I am totally for this project. Unless the other staff wishes to override me, I motion it be approved.
