### ISSUE TITLE
Allow people to chose which of the verbs replace "says" when ending their message with an exclamation mark.

### ISSUE THREAD

**Issue by Treasa729** [VOREStation/VOREStation#1453]
#### Brief description of the issue
When you end any 'say' with an exclamation mark, the verb which appears in chat is changed to something else. It becomes either exclaims, shouts, or yells. This is annoying because in character when writing dialogue that is supposed to be enthusiastic, or energetic, I will tend to use exclamation marks at least from time to time. This gets interpreted in character as yelling, or shouting, which just isn't the case. It's incredibly annoying to have someone complain about you yelling ICly when you just aren't actually trying to make your character yell.

#### What you expected to happen
To be able to play a character who is enthusiastic.

#### What actually happened
I actually am only able to play characters that shout or yell very often unless I just never use the say verb and always use me to prevent myself from yelling or shouting. 

#### Steps to reproduce
- (Step 1) End a sentence with an exclamation mark.
- (Step 2) Yell for no reason at people and have people get angry at you ICly for something that has absolutely no reason to be happening.

#### Code Revision
Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 

#### Anything else you may wish to add:
What I'd suggest as a solution would be allowing for people to set which of the verbs can replace says when they end a sentence with an exclamation mark. Possibly allowing for people to have custom verbs would be nice as well, though that could also be a more general addition: Allowing people to choose what the verb(s) is/are when they speak normally (Ex: 'chirps', 'barks', etc.) not just when using exclamation marks.

**Comment by DeepIndigo** [comment]
You can already do this by using a cleverly written "me" instead of say.

**Comment by Treasa729** [comment]
I know, I already mentioned that in this with the "I actually am only able to play characters that shout or yell very often unless I just never use the say verb and always use me to prevent myself from yelling or shouting." and it'd be rather annoying to have to just avoid using the say verb at all in favour of only using 'me' instead. It'd be much more convenient to just allow players to toggle off having yell or shout be the defaults when using say.

**Comment by SpadesNeil** [comment]
It's really more trouble than it's worth to do that, DeepIndigo, especially when things like station bounced radios or voice recorders or other things outright won't work in that manner.

Still, it's a really minor bug.

**Comment by DeepIndigo** [comment]
Fair enough Ace.
