### ISSUE TITLE
Kitchen (and cooking vore) Privacy

### ISSUE THREAD

**Issue by ZippyShanks** [VOREStation/VOREStation#1454]
I have recently been in another arguement with the admins over my preference for cooking scenes and the discomfort some people experience at the mere notion of these and have once again been asked to do it in private. My issues however is that there is currently NO WAY to do it in private since the kitchen is entirely open on two sides. I only sporadically get to enjoy this particular kind of scene and having to get into a fight with the admins every time is a right bother. 

Therefore I would very much like a solution to be implemented for this and the solution could be twofold. 
One, allow privacy shutters or tinted glass ALL THE WAY around the kitchen 
and/or
allow for a dormroom style private kitchen specially suited for crewmember on crewmember cooking vore scenes.

**Comment by Arokha** [comment]
>having to get into a fight with the admins every time is a right bother

We've told you three times not to bring it into public, so maybe you wouldn't be bothered if you listened to the advice. c:

I see your point, though! Can you not construct the machines themselves? Are they not constructable/movable?

**Comment by Arokha** [comment]
We seem to have decided to just make it so the kitchen can be totally opaque, so no looking through the door or whatever. That way you can do it in private.

**Comment by DeepIndigo** [comment]
More shutters seems like a happy medium for it to me.

**Comment by Screemonster** [comment]
I like the idea of a space behind the kitchen in maintenance for lady and the tramp style private alleyway dining away from prying eyes, or a "pantry" area (similar to the freezer) with a single table and two chairs that you can let people into to dine in private, again sneakylike and out of sight of the main bar. Like the librarian backroom and other such private-zones. The freezer isn't exactly the most aesthetic place to have a private dinner, but that too would work. I note that the current map doesn't have a maintenance door into the freezer like the old boxstation map did, so there's no way to sneakily get your guests to meet you round the back so you can let them in without people in the bar seeing them enter.

**Comment by Wickedtemp** [comment]
I would support this. It'd allow people to do scenes in the kitchen without being in full view of everyone at the dining bar.

Additionally, this would make it so that literally no one can complain about the cooking-crew scenes as long as like.. fried feet and hands aren't served on the tables.

**Comment by Arokha** [comment]
The kitchen has privacy now, nobody can see in if you close all the shutters.
