### ISSUE TITLE
Fire axe cabinet graphical problems

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1455]
#### Brief description of the issue
Fire axe cabinets, when open, empty, and cracked, have no sprite, and become invisible until an axe is placed in them or they are closed.

#### What you expected to happen
The fire axe cabinet to be visible when cracked, and open.

#### What actually happened
It was not.

#### Steps to reproduce
- 1.Damage a fire axe cabinet by hitting it once.
- 2.Open it
- 3.Remove the axe
- 4.Be hailed as a talented magician for making the cabinet vanish from the wall.

#### Code Revision
- Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ArbyTheDragon** [comment]
'Tis probably just a missing sprite. Someone should view vars for what icon state it's trying to be in and add the appropriate sprite with that name- or just change the name in the code to something else we already have.

**Comment by DeepIndigo** [comment]
Figured as much. I was just noting it down here on behalf of someone who discovered it, after confirming for my self.

**Comment by TheFurryFeline** [comment]
This sort of thing is still happening, actually..... Fire axes are not obtainable from the cabinets, no matter what..... Also, requesting the severity of this bug to be changed to moderate, considering that fire axes would need to be used depending on situation and this problem makes the cabinets useless.
~TheFurryFeline
