### ISSUE TITLE
Gravity returning causes player to be stunned if buckled into chair

### ISSUE THREAD

**Issue by AeroWing** [VOREStation/VOREStation#1458]
#### Brief description of the issue
The gravity loss random event causes the player to be stunned if he buckles into a chair or is buckled into a chair prior to the gravity returning.

#### What you expected to happen
To start out floating in a most peculiar way then float to a chair and buckle myself down to safely await the return of gravity, not getting stunned in the process.

#### What actually happened
Started out floating in a tin can, far above the floor, commencing countdown seatbelt on... Find myself stunned in a most peculiar way. 

#### Steps to reproduce
- Start to float as gravity fails
- Swim over to nearest chair
- Buckle in
- Wait for gravity to return
- Get stunned

#### Code Revision
- Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 
 
#### Anything else you may wish to add:
- Can you hear me, Major Ace?
- Can you hear me, Major Aronai?
- Can you hear me, Major Yosh?
- I'm stunned in a tin can and there's nothing I can do.

(Memes aside the stun only lasts as long as if you just fell down and hit the floor.)

**Comment by ArbyTheDragon** [comment]
This bug is OLD. Bout time someone mentioned it. It's exactly as long as if you had just fallen. Clearly, the actual event doesn't care if you were sitting or not.

Also, now nobody will be able to do a space oddity joke without being a copycat :<
At least the first one was a good one.

**Comment by AeroWing** [comment]
I mean you could have easily kept the song going in your post. x3
But yeah, it's an old one and I had some spare time so I brought it up.

**Comment by ArbyTheDragon** [comment]
Damn. You're right. I ruined it ;_;
