### ISSUE TITLE
(Fluff Item) Vintage Hypo - Alexie Vidra 

### ISSUE THREAD

**Issue by AlexieOtter** [VOREStation/VOREStation#1462]
Name of Item: Vintage Hypo

Item description: An older model of Hypo made cased in polished brass with a wooden handle. 

Sprites (or link to sprites): https://cdn.discordapp.com/attachments/287763899477000192/308814933288681474/AlexieHypoBronze.dmi

Any additional resources: none. 

BYOND Key (Username): Azeroth_Margican

Name of Character: Alexie Vidra

Main Job(s) of Character: Doctor, CMO and Visitor

Why your character should have this item: As a long running doctor and medical staff worker on the station Alexie has been repeatedly exposed to the benefits of Hypos and would of course want to seek one out for herself! Alexie highly values her medical work and is constantly seeking to improve her effectiveness so acquiring a Hypo would certainly be a goal for her. She is well regarded generally and hasn't caused trouble that might bring her motives for asking to be allowed to bring a Hypo onto station into question.

Additional Notes: This would be using the old hypo code of course rather than the 2.0 code! No need to get crazy with the hypo given that the newer versions are likely more expensive and doesn't fit the aesthetic of the sprite.

**Comment by SpadesNeil** [comment]
Please post on the forum instead of directly to Github. I know other people keep doing this but it needs to stop somewhere.

Ask me to re-open this if the app gets accepted, and provide a link proving it was accepted.
