### ISSUE TITLE
Fire and Air alerts overrule each other for Firedoors

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1464]
#### Brief description of the issue
On an area with both fire and atmos alerts active, resetting either of them will open the fire doors even if the other alert is still active.

#### What you expected to happen
Fire doors to remain down until all alerts are cleared.

#### Steps to reproduce
You can reproduce this either with *real* fire and atmos problems, or just set the alert status to do it less dangerously.
1) Trigger atmos alert in any area. - Note, fire doors should close!
2) Trigger fire alert in the same area - Fire doors will remain closed.
3) Reset the fire alert without clearing the atmos alert.   - Fire doors open!

**Comment by Leshana** [comment]
Testing procedure was:
1) Activate fire alert
2) Activate atmos alert
3) Reset atmos alert
4) Activate atmos alert
5) Reset atmos alert.

**Comment by Very-Soft** [comment]
What's that, you don't want your sleeping agent to spread around once you dealt with the fire? You're silly.
