### ISSUE TITLE
*yes emote forgets an s

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1465]
#### Brief description of the issue
*yes is not recognized, it returns "Unusable emote 'ye'. Say *help for a list."

Clearly it doesn't recognize the single s in yes. If you type *yess then the emote works

#### What you expected to happen
*yes

#### What actually happened
*ye

#### Steps to reproduce
- be synthetic
- try to use the *yes emote
- boggle as it tells you you forgot an S for the fifth time in a row even though you know you hit it

**Comment by AeroWing** [comment]
Ye, I checked this out. It is indeed an issue, for non synths too.

**Comment by SpadesNeil** [comment]
Still an issue?

**Comment by AeroWing** [comment]
Ye, it is still an issue. Checked just now.

**Comment by Arokha** [comment]
This is because if you put an s at the end of an emote, it removes it, and then uses that as the emote. It's so things like *clap and *claps, *laugh and *laughs all do the same thing and work. So when you do *yes it removes the s and tries *ye. Which is not a real thing.
