### ISSUE TITLE
Putting Old Greatsword in item bank transforms it into Aria[GENERAL] 

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#14660]
#### Brief description of the bug
If you put the blue old greatsword in the item bank and take it out on another shift, it is now a sword called Aria. It has this as it's discription. "A beautifully crafted rapier owned by Joan Risu. It has a thin blade and is used for quick attacks. " This may also be an issue as it sounds like a custom item of a well known charater

#### What you expected to happen
to get the same sword I put in

#### What actually happened
I got someone's fluff item

#### Steps to reproduce
- (Step 1)put old great sword in item bank
- (Step 2)get Aria next shift

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
This is intentional behaviour. All items get their custom stats (including names) reset when put in the bank.
