### ISSUE TITLE
Sorting Office mail tag equals infinite loop

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#1466]
#### Brief description of the issue
Setting your mail tag to "Sorting Office" as a drone puts you in an endless loop, or at least until you stop in the pipes somewhere.  Possibly also happens to mailed packages.

#### What you expected to happen
To pop out in the sorting office and continue on my merry maintenance way.

#### What actually happened
Looped the station a few times before lodging under Xenobotany.  Was rescued by an admin.

#### Steps to reproduce
- Be drone.
- Set tag to "Sorting Office".
- Jump in disposal system.
- I WANT TO GET OFF MR. BONES' WILD RIDE

#### Code Revision
- release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b

**Comment by Leshana** [comment]
This shouldn't happen on the tether

**Comment by ArbyTheDragon** [comment]
I specifically remember doing this on boxstation way back when. It worked fine. This is probably a mapping issue with how the loops are designed. They probably just forgot to have the the 'sorting office' path actually end somewhere.

**Comment by Arokha** [comment]
Entirely new map (and disposals isn't quite fixed yet either, but this specific problem doesn't exist anymore, anyway)
