### ISSUE TITLE
Reloading implanters too tedious.

### ISSUE THREAD

**Issue by AeroWing** [VOREStation/VOREStation#1468]
#### Brief description of the issue
Restocking expended back up implanters is a bothersome pain because of the process involved.

#### What you expected to happen
- Take expended implanters to science, ask to get new implants. 
- Get implants printed and loaded.
- Bring implanters back to medical fully restocked and ready to ensure ~~the menu is plentiful~~ crew welfare.

#### What actually happened
- Take expended implanters to science, ask to get new implants.
- Get subjected to an irritating process of having to reload the implanter
- Question life choices

#### Steps to reproduce
- Go to science, request new implants
- Receive implant glass cases
- Request/receive old implanter
- Use old implanter to remove implants from glass case
- Remove implant from old implanter
- Load removed implant (now caseless) into new implanter
- Repeat until fully restocked

#### Code Revision
- Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 
 
#### Anything else you may wish to add:
Updating the new implanters to pull implants directly from a glass case on click would be amazing. Likely the best course of action to take here unless someone has a better suggestion.

**Comment by ArbyTheDragon** [comment]
Sure it's a bit tedious, but... So what?
The construction process can be kinda tedious too.
I'm just saying- I'm not this ticked off about it.

**Comment by AeroWing** [comment]
I think the functionality of the new implanter is supposed to be superior to the older one so having the functionality to extract implants from the glass case would be fair.

**Comment by Arokha** [comment]
They're disposaaaable. You were never really meant to reload them. I only added that feature for fun. Just chuck 'em and get the next one out of the vendor.

Usually I'd encourage interdepartmental reliance and stuff but resleeving is kinda important for RP and stuff, so medical starts with something like 30 implanters in vendors and on desks and stuff.
