### ISSUE TITLE
Misaligned Highlander Zorren hand sprite

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#1469]
#### Brief description of the issue
The south-facing left hand sprite for Highlander Zorren is a pixel off.

#### What you expected to happen
To reassemble my zorren sprite for making zorren-specific markings without incident.

#### What actually happened
Whoops, that hand is off by a pixel.  Log in to the server, look at zorren character, yup, it's off in the preview window, become ghost to see character in play, yup, it's still off.

#### Steps to reproduce
- Make a highlander zorren.
- Face south.
- Marvel at seemingly-shortened arm.

#### Code Revision
- release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 

 
#### Anything else you may wish to add:
- so many pieces to reassemble
- ~~oh god what did you do to my babies~~  :P

**Comment by SpadesNeil** [comment]
Screenshots?

**Comment by ArgobargSoup** [comment]
![zorrenhand](https://cloud.githubusercontent.com/assets/19196710/25788191/0fee404e-335c-11e7-9532-67f1d005f5dd.png)
Izzat good?

**Comment by SpadesNeil** [comment]
I assume this has been fixed.
