### ISSUE TITLE
[GENERAL/UI] Body Design Console doesn't let you change ears, wings, and tails

### ISSUE THREAD

**Issue by tacoguy7765093** [VOREStation/VOREStation#14699]
#### Brief description of the bug 
Changing ears and wings for a designed body will only apply once, any more changes and they reset.

#### What you expected to happen
I expected to be able to change the ears, wings, or tail freely

#### What actually happened
I can change any of them once, but the second I have the menu update for any reason, it all resets back to the default body part.

#### Steps to reproduce
- (Step 1) Access the body design console and make a new body/edit a existing one
- (Step 2) Give it custom ears or wing or tail
- (Step 3) Change anything else in the menu (As shown in attached gif)
- (Step 4) All ears, wings, and tails get reset back to normal.

#### Anything else you may wish to add:
- My quick glance in the code shows it touches genetics code, so if it gets too cursed to fix, its nothing the TF menu can't do anyway.
![Qsv6wKVAow](https://user-images.githubusercontent.com/10555869/225485953-61c37235-669b-458f-94a2-f0726b17b9b2.gif)

**Comment by Kashargul** [comment]
https://github.com/VOREStation/VOREStation/blob/f9985b24d6076e1c25b422072c80e78ca1e42e61/code/modules/resleeving/designer.dm#L374-L424

The code seemingly creates the prefs, transfers them and then applies them back to the mannequin, what causes issues... even when cancelling and edit, it will lead to a reset as there had been no change to the player_setup_item which then is copied to the mannequin.

**Comment by Kashargul** [comment]
https://github.com/VOREStation/VOREStation/blob/137d5c3b5248d28ad3fecefb5d505ca2b7cc21b6/code/modules/tgui/modules/appearance_changer.dm

Shows the difference in handling ears, tails and wings compared to the other options, might be a hint.
