### ISSUE TITLE
[GENERAL]  Invisible Pizza Visor

### ISSUE THREAD

**Issue by Smdytb1** [VOREStation/VOREStation#14744]
#### Brief description of the bug
The Pizza visor is completely invisible in every aspect

#### What you expected to happen
To have a pizza visor visible on my head :(

#### What actually happened
It is invisible, causing it to not be seen on the ground, inhand, or worn.

#### Steps to reproduce
- Put on the Pizza visor
- Experience sadness

#### Code Revision
- Current Live Code
 

#### Anything else you may wish to add:
![gdUMwIvDhl](https://user-images.githubusercontent.com/13372034/228716683-73ece878-9ac1-43fd-ae4e-e8cdded48f38.png)

**Comment by SomeDongus** [comment]
unplayable

**Comment by Smdytb1** [comment]
Fixed in #14769
