### ISSUE TITLE
[MAPPING] 

### ISSUE THREAD

**Issue by Beeholddrbeesphb** [VOREStation/VOREStation#14746]
Tether dorms not bringing back 200% max on leave. Able to leave at max size.

When leave dorms should trigger a 200% max size.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 [02a240f3967b551a8245b324212c697e487f45ba](http://127.0.0.1:54350/tmp73372/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/02a240f3967b551a8245b324212c697e487f45ba%22%3Ehttps://github.com/VOREStation/VOREStation/commit/02a240f3967b551a8245b324212c697e487f45ba%3C/a%3E)

- (Location if it's a mapping issue, screenshots, sprites, etc.)
DORMS TETHER then entire map.

![image](https://user-images.githubusercontent.com/129466615/228993167-86bc265d-3e44-4fda-8e00-f53d5cbb4078.png)
![image](https://user-images.githubusercontent.com/129466615/228993291-e3eb7b55-f5e7-48ff-9f03-2612ecfc3fbe.png)
![image](https://user-images.githubusercontent.com/129466615/228993304-280f884e-2f38-46b3-a658-cb239948d966.png)

The hallway DOES work properly and does not allow you to use the nif over 200%

**Comment by Beeholddrbeesphb** [comment]
![image](https://user-images.githubusercontent.com/129466615/228993516-94729547-4c1c-4adb-a18d-b30ea45ad332.png)

**Comment by Beeholddrbeesphb** [comment]
![image](https://user-images.githubusercontent.com/129466615/228993728-8d5380bc-a130-41ed-b5e2-db1978c15f94.png)

**Comment by Heroman3003** [comment]
Cannot replicate.
