### ISSUE TITLE
Cyborgs don't get OOC notes

### ISSUE THREAD

**Issue by Xonkon** [VOREStation/VOREStation#1475]
#### Brief description of the issue
Players playing as a cyborg/robot/drone don't get their OOC notes displayed

#### What you expected to happen
Join the game and have my OOC notes displayed under flavor text like they normally do.

#### What actually happened
No OOC notes

#### Steps to reproduce
-Join as the cyborg job
-Have no OOC notes

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b

**Comment by AeroWing** [comment]
You can't hug them either. This should be renamed to 'Improve rights for borg lives.' Anyway not being able to see OOC notes is a pretty big red flag to me, why hasn't this been getting any attention?

**Comment by SpadesNeil** [comment]
@Arokha this is kind of important. :U

I don't know much about this part of the code. Perhaps you or @Cameron653 could fix it?

**Comment by SpadesNeil** [comment]
New problem. See above.
