### ISSUE TITLE
Phoron items are 100% fireproof which is not consistent

### ISSUE THREAD

**Issue by SeigaSeiga** [VOREStation/VOREStation#1477]
#### Brief description of the issue
Due to balance issues, the code that handles the flammable nature of items crafted from phoron is commented out. The result is that our most flammable material can be used to make fireproof doors and furniture. [Phoron airlocks still ignite due to different handling of their fireact and temperature, but these are either harder to or impossible to craft.] As a stop-gap measure, I would like to suggest that we:

**Remove the ability to craft things out of phoron, as the items currently made from them are legitimately broken both mechanically and lore/immersion-wise.** At least until the issue of them not being flammable at all is balanced/resolved or otherwise seen to.

#### What you expected to happen
To be able to prove to the crew that phoron is a flammable substance.

#### What actually happened
Built a phoron door in toxins burn chamber. Also chair, bed. Raised temperature to over nine thousand. Phoron door proved to be both airtight and completely fireproof. Have to tell crew that phoron objects are 100% fireproof and safe. Get into argument because 'how can that possibly be true', which is a very legitimate thing to respond to that with, but as a scientist in-game I was unable to ignore evidence as a result of in-character experiment proving phoron doors fireproof.

The steel airlock built in the chamber as a control melted into ash way before the maximum temperature was reached.

#### Steps to reproduce
- (Step 1) Make Phoron door
- (Step 2) Make temperature similar to that of all-cleansing hellfire
- (Step 3) Behold as it stands as the last bastion in a universe removed of things non-phoron

#### Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b

**Comment by Screemonster** [comment]
Constructing stuff out of phoron is kinda silly.
Also I'd kinda like phoron items of any kind to be automatically and permanently treated as contaminated. Because it's fucking phoron.

**Comment by SpadesNeil** [comment]
Chemicals behave differently according to their state. Only gaseous and liquid phoron is hazardous. Solid phoron isn't very harmful, and when combined with a silica-based compound (glass), it loses its ability to burn and in fact becomes very much fireproof. Kind of like how sodium and chlorine on their own will fucking kill you, but salt is mostly harmless.

Density also plays a role. Densely packed newspaper is actually quite fire resistant and is even used to insulate homes. Things don't burn very well if they can't get oxygen to help it.

Either all phoron items should be insanely fireproof, or extremely combustable. I am in favor of them being fireproof.

**Comment by AeroWing** [comment]
I support Ace's idea. Metastability should be considered here. Some chemicals are very volatile in a liquid state and completely inert in a solid state and vice versa. I didn't want to break into several paragraphs explaining this but the refined phoron can be suspended in silicate or some other mixture to make it stable, or just it's crystallized state. If we make phoron volatile in a solid state then we'd have a fun time in chemistry and other locations where we handle phoron sheets like with PACMAN generators. That said to someone else's point via discord. You definitely shouldn't eat it. That would cause a lot of complications exposing phoron to hydrochloric acids inside of someone.

**Comment by SeigaSeiga** [comment]
Okay but even with that IC explanation Phoron doors are still a 100% airtight and fireproof solution where every other type of airlock/door/wall would melt. Haven't tested if other types of material sheet door are also fireproof yet, though.

**Comment by SeigaSeiga** [comment]
Updated summary of inconsistency:

Phoron Airlocks are horrifically flammable [may be uncraftable].
Phoron Walls will not add to a fire but will break down in the same fashion as steel.
Phoron Doors are completely impervious to fire. Also airtight.

**Comment by Screemonster** [comment]
I didn't make material doors take damage from fire 'cause they're a different path that doesn't inherit the properties of airlocks. It'd be fairly trivial to give them the same damage properties using the melting_point of whatever material they're made from.

**Comment by chaoko99** [comment]
Personally, I think it'd be smart to just re-enable the fire code. Phoron is highly toxic, I don't think you should be SLEEPING IN IT.

**Comment by SpadesNeil** [comment]
Solid phoron is completely harmless to touch, though! Just because something is toxic in one state doesn't mean it's hazardous in another.

I bet aluminum is pretty dangerous if you boil it, for instance.

**Comment by AeroWing** [comment]
Spades is correct in this matter. As a good example I work with Depleted Uranium that is safe to handle and control with only FRC rated gear, (skin exposure). The stuff is harmless when outside the body. However it becomes very very very bad when you decide to eat it. So please, don't eat Depleted Uranium. Same goes for phoron too. That stuff is so dense (70% more dense than lead) and stable that we actually use it to manufacture armor piercing ammunition and even roll plates of the stuff on our tanks (M1A2 Abrams) showing that materials in certain states can actually have some rather effective applications.
