### ISSUE TITLE
Body Markings are Not Remembering Their Order

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1478]
#### Brief description of the issue
Kaitlyn Fiasco uses multiple body markings. She uses tajaran socks to simulate fur on her hands and feet, and tiger stripes overlaid them. However, whenever I log in, I usually find that they have changed the order I put them in in the character editor- also showing up in the same order on the sprite. This wouldn't be a problem if it wasn't for the fact the stripes go UNDER the socks, leaving only her exposed skin as actually striped, which is the opposite of what I wanted to happen.

#### What you expected to happen
The body markings to remain in the order I applied them with.

#### What actually happened
Whenever I log in and check my character's markings, the pattern's lineup reset.

#### Steps to reproduce
- get taj socks
- get tiger stripes second so that they overlay the socks
- let the server reset, then check the markings. (reloading the slot or reconnecting to the server failed to replicate the issue.)

#### Code Revision
- 92420a6da5a611d0f561aa7a4e8785d2e439c50b
 
#### Anything else you may wish to add:
- N/A

**Comment by SpadesNeil** [comment]
Was this ever fixed?

**Comment by Vorrarkul** [comment]
As of e0443cfb4b865c8561196af365d1aa78dede00b1I do not believe so. Kaitlyn still has issues with maintaining the stripes over her "sock" markings. Naturally, since this seems to be related to the server resetting each shift, it takes some time to verify. I'll try and fix it again this shift and in a few hours I will make a second comment about the results.

**Comment by Vorrarkul** [comment]
I have waited several hours for a new shift, and I am unable to replicate the issue. I'll let you know if this ever comes up again, but it seems to have been fixed at some point.
