### ISSUE TITLE
[GENERAL] Wolf-Taur Armor Vest does not fit on Fat Wolf-taur body

### ISSUE THREAD

**Issue by Wyvern2901** [VOREStation/VOREStation#14802]
Attempted to equip Wolf-Taur armor vest from Security Brig on my fat wolf taur character. Game said I was unable to equip said armor despite having a taur body? I think this has been a bug for a while, as this issue seems familiar to me. Think it might have something to do with the game not recognizing a fat taur body as a 'taur body', but I'm no expert.

**Comment by Heroman3003** [comment]
It only works on 'regular' wolf taur bodies due to sprite incompatibility. Would need different set of sprites for fat taur version.
