### ISSUE TITLE
[GENERAL] Mech interaction with nanopaste

### ISSUE THREAD

**Issue by SpaceMan-Jim** [VOREStation/VOREStation#14846]
#### Brief description of the bug
Possibly a incorrect or erroneous line of code relating to nanopaste being applied to mechs/exosuits that causes a big problem. 

#### What you expected to happen
The mech/exosuit to be fully to partially repaired and using up the nanopaste as an alternative method of repairing with a welding tool.

#### What actually happened
Attempting to repair a heavily damaged exosuit with nanopaste will cause a (what I think to be) endless loop somewhere in the code of it attempting to be used, even if the entire bundle of nanopaste was used, causing the server to heavily chug to the point of unplayable... so its abit URGENT. 

#### Steps to reproduce
- Step 1: Obtain heavily damaged mech.
- Step 2: Apply nano paste to the interior of the mech.
- That's it..
 
#### Anything else you may wish to add:
- I, myself do not know much about coding talk and such, but I've heard and seen this before.. it 'should' have something to do between the two things interacting, something about the command not ending correctly due to how it might be written.. but I do not know for sure.

**Comment by SpaceMan-Jim** [comment]
I'd have less of a clue than you, all I know someone was able to find out on citadel pretty quickly, during when I found out it was a problem too. All I can say is try to ask around to see if anyone else can find it, or something.

All I do know is that it was simply one line of code that caused it to loop applying the whole amount but no 'end' part to it.. or something, again.. I don't know anything about code language, but hopefully now this can be made aware of as a problem.

**Comment by KillianKirilenko** [comment]
That's the thing! Looking at both of those blocks (refs below), I can see the `while` loop that could easily be causing it. My gut tells me that the nanopaste stack should be deleting itself as soon as it hits zero uses, which *should* be stopping this, but somehow isn't.

But I don't see anything that might have fixed the problem. It's entirely possible someone on Cit *said* they were going to fix it and simply never made a PR. I'm not sure.

Citadel's version: https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/ebfa58647db388dd8f4e3d832de8d46e23cb1093/code/game/mecha/mecha.dm#L1502
Our version: https://github.com/VOREStation/VOREStation/blob/2ae53b317167a1ea14dfb0e6ff9c88ece76f30a0/code/game/mecha/mecha.dm#L1563

**Comment by KillianKirilenko** [comment]
Tinkering with this, closing on a possible works-as-intended solution.
