### ISSUE TITLE
Carthatoline doesn't seem to work as intended.

### ISSUE THREAD

**Issue by Treasa729** [VOREStation/VOREStation#1485]
#### Brief description of the issue
From the way I was told, Carthatoline was to function as a sort of upgraded hybrid between dylovene and carbon pills. It's an emetic. By its own description when analysed in the chem_master: "Carthatoline is strong evacuant used to treat severe poisoning." It doesn't really function as an evacuant though. Carthatoline checks if the patient has toxin damage. If they do, it can cause them to vomit.

#### What you expected to happen
A patient to vomit, regardless of whether or not they have toxin damage. Furthermore,  I'd expect when the patient vomits from taking something which is considered a "Strong evacuant", they would expel some of the contents of their stomach, allowing Carthatoline to act in a similar manner to Carbon pills. 

#### What actually happened
All it does is lower their nutrition. In fact, it even slows the process of getting rid of toxins in someone's stomach because of the way vomiting works, where it 'stuns' the person's stomach and bloodstream for a while, preventing something like carbon from actually being able to reduce their level of toxins, or for the toxic substance to simply metabolize naturally.

As it stands right now, Carthatoline doesn't really do anything at all as a "Strong evacuant", only acting as an upgraded dylovene, which seems rather like a waste given that it has the potential to work as an emetic, allowing medbay to treat the ridiculous cases where [Redacted] takes 150 units of synaptizine they found in maintenance.

#### Steps to reproduce
- Inject someone who has nothing in them with Carthatoline
- Marvel as they don't vomit at all
- Give them a 5 unit pill of toxins
- Watch them begin to vomit their guts out, but because they were given Carthatoline, it will take longer for them to get rid of that 5 unit toxin pill they ingested than it would without them having Carthatoline.

#### Code Revision
Server revision: release - 2017-05-18
7f21e562eb405619c7bff368009b7d65e1a84d51 

#### Anything else you may wish to add:
I would prefer that a "Strong evacuant" works as a "Strong evacuant" all the time. As it stands, it only causes the patient to vomit when they've taken toxins damage, which is rather silly. If Carthatoline is intended to work as an emetic, it should cause vomiting regardless. It'd be rather silly for it to reduce the amount of amatoxin in someone's stomach, but not be able to be used when [Redacted] drinks 1500 units of coffee and comes to Medbay for help when they're spasming like mad.

This also doesn't need to be a change to Carthatoline's vomiting. It would be interesting if a character vomiting naturally merely from the toxin damage would actually cause them to vomit up the poisonous mushrooms they ate (their reagents anyway).

**Comment by Arokha** [comment]
The code seems to indicate that it will heal tox damage twice as fast as dylovene, and heal liver damage. If they have any tox damage, it looks like there's a 10% chance to have them vomit, which does not actually remove stomach reagents (it probably should).

```
/datum/reagent/carthatoline/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_DIONA)
		return
	if(M.getToxLoss() && prob(10))
		M.vomit(1)
	M.adjustToxLoss(-8 * removed)
	if(ishuman(M))
		var/mob/living/carbon/human/H = M
		var/obj/item/organ/internal/liver/L = H.internal_organs_by_name[O_LIVER]
		if(istype(L))
			if(L.robotic >= ORGAN_ROBOT)
				return
			if(L.damage > 0)
				L.damage = max(L.damage - 2 * removed, 0)
```

**Comment by Treasa729** [comment]
Yeah, I looked at the code while testing it. It essentially just functions as an empowered dylovene (Which also heals liver damage if it's below 10) right now with the side effect of possibly causing vomiting. While this isn't inherently bad, I think it's wasted potential. I also find it especially absurd that an emetic will slow the process of getting toxins out of someone's stomach because vomiting prevents their body from processing chems for a while.

**Comment by Arokha** [comment]
Where do you see the vomiting chem processing thing?

**Comment by Treasa729** [comment]
As I said, I don't know the code for it. I don't know code :P but you can see the effects in game. If someone vomits, their body will not process chems (and presumably lifeticks) seemingly until the duration of the stun wears off. It might actually have something to do with the stun code. I don't know, but I've not observed a case where it doesn't happen. It has consistently happened every time I've tested it.
