### ISSUE TITLE
[UI] Reagent Dispenser UI is squished to the side

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#14947]
#### Brief description of the bug
Exactly what it says on the tin

#### What you expected to happen
To take the whole area given to it.

#### What actually happened
All the options are on the right.

#### Steps to reproduce
- Find reagent dispenser
- Look disrespectfully.

#### Code Revision
- [067bf338a7cce86a5b8598945de2d8bb16e79e3d](http://127.0.0.1:54189/tmp11304/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/067bf338a7cce86a5b8598945de2d8bb16e79e3d%22%3Ehttps://github.com/VOREStation/VOREStation/commit/067bf338a7cce86a5b8598945de2d8bb16e79e3d%3C/a%3E)
 

#### Anything else you may wish to add:
- [Image of what it looks like](https://cdn.discordapp.com/attachments/467031091161858050/1114318347186745354/image.png)

**Comment by ItsSelis** [comment]
Interface file location:
tgui/packages/tgui/interfaces/ChemDispenser.js

The buttons are generated from line 30.
Though I can only start debugging this tomorrow myself, but anyone can feel free to try it before I can.
