### ISSUE TITLE
[UI] Eventkit tab appears for users without staff perms

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#14958]
#### Brief description of the bug
The Eventkit tab appears when it should not as guest account on my test server

#### What you expected to happen
It should only appear on my host account

#### What actually happened
It is visible despite the acc having no admin perms

#### Steps to reproduce
- Host test server with server version last updated at 2023/June/03 UTC 12:00
- Join without any admin perms

#### Anything else you may wish to add:
![image](https://github.com/VOREStation/VOREStation/assets/20523270/3fc3247e-d4cf-4b19-a822-ad3b6ee68f07)

**Comment by Heroman3003** [comment]
Gotta make it not a native client verb, but one granted as part of perm verb lists
