### ISSUE TITLE
Xenochimera: Recovery ability insufficient info/deletes marking

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1496]
#### Brief description of the issue
Decided to test the Xenochimera regeneration ability, to learn how it worked.

#### What you expected to happen
To safely reconstruct my body without much problem, aside from being immobilized for a while.

#### What actually happened
Exploded into a shower of gibs upon hatching, after a confusing, incomplete popup.
Made a royal mess of a treatment center.
Lost my markings.

#### Steps to reproduce
- (Step 1) Be Xenochimera fresh outta the crib
- (Step 2) Wonder 'yo how dis work' and use Begin Reconstituate Form ability
- (Step 3) Be immobile for a long while
4: Get Hatch verb.
5: Use it
6: SPRAY YOUR GIBS EVERYWHERE!
7: Also lose your markings.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ab1d6cb272157c98a140b01d0094e17901e74ffa 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
https://puu.sh/vWwB5/93265a8437.png

**Comment by Screemonster** [comment]
I've noticed adminhealing delete markings too. I think that's the part that is supposed to remove blood overlays and suchlike.
