### ISSUE TITLE
[MAPPING] The killer from V2

### ISSUE THREAD

**Issue by Rick4242** [VOREStation/VOREStation#14970]
#### Brief description of the bug
At first I thought it was just a user error thing, but one of the airlocks on the V2 aerostat is basically a deathtrap

#### What you expected to happen
If an airlock leads to somewhere dangerous, it should be bolted shut, or at least there should be a BIG warning not to open it

#### What actually happened
But no, this ONE airlock is just left unbolted, waiting for some unfortunate explorer, scientist, or someone else to open it and face near-instant death.

#### Code Revision
- Server revision: B:release D:
Commit: [067bf338a7cce86a5b8598945de2d8bb16e79e3d](http://127.0.0.1:65481/tmp51320/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/067bf338a7cce86a5b8598945de2d8bb16e79e3d%22%3Ehttps://github.com/VOREStation/VOREStation/commit/067bf338a7cce86a5b8598945de2d8bb16e79e3d%3C/a%3E)
 

#### Anything else you may wish to add:
- Evil, absolutely evil.
![image](https://github.com/VOREStation/VOREStation/assets/42255398/985eed6a-4c03-4969-b86b-f3a5b0146101)

**Comment by Smdytb1** [comment]
what aggrevates me the most is that this isn't designed like a regular airlock at all. the entire hallway that it is in is functionally the airlock itself. not just a simple one tile airlock like some are or at most a 2x2 airlock design.

**Comment by Rick4242** [comment]
I mean hot air **is** what most of V2 atmosphere is, really, **really** hot air. And in a small look-around, all of the other doors on the other sides of the solars are bolted, these weren't.

**Comment by KillianKirilenko** [comment]
Probably due to the map predating airlock helpers and such. Is this the SD, RP, or Tether version of the V2 aerostat?

**Comment by Runa-Dacino** [comment]
This should be closed as a consequence of https://github.com/VOREStation/VOREStation/pull/15059
