### ISSUE TITLE
[UI] "Enter" no longer confirms pop-ups in Chemmaster window

### ISSUE THREAD

**Issue by MiraNesyne** [VOREStation/VOREStation#14982]
#### Steps to reproduce
- Place any amount of any reagent in a beaker
- Place the beaker on a chemmaster
- Transfer the reagents to the chemmaster
- Press the "Multiple" button under "Bottle" to create multiple bottles
- Press the "Enter" key and notice that it does not confirm bottle quantity.

#### 
Server revision: B:release D:
Commit: [f04fa6b7d7f7a70f46fcb1d5f1ac508b17182459]
BYOND version: 514.15
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KillianKirilenko** [comment]
Are you using the `TGUI Input Lock` setting to allow linebreaks whilst using TGUI for say/emote type inputs? If so it's an unavoidable side-effect of the rather brute-force approach I took to the problem.

If not then something weirder is going on.

**Comment by MiraNesyne** [comment]
I don't know what that is, but I'm a command bar user, so I don't use those text boxes. I know that some other people (another chemist on the shift) complained about the problem.
