### ISSUE TITLE
Polaris Port - Xenomorphs

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#15]
- [x] Readd Sprites
- [ ] Readd Definitions

...well they said they removed xenomorphs but didn't really. Just as carbons. Their simple-mob iterations still work, and the sprites are all there, so... check?

**Comment by SpadesNeil** [comment]
We don't really need to do Xenomorphs like our current Baystation did. I'd much rather have them set up like old Baystation had them because the gameplay was immensely better. I have the old Vorestation code for reference if need be.

**Comment by Arokha** [comment]
They have some kind of other setup. I dunno. A lot of the sprites are animated and such. You should probably test it to see if you like it.

**Comment by SpadesNeil** [comment]
Oh, okay.

**Comment by SpadesNeil** [comment]
Also I should clarify.

> ...well they said they removed xenomorphs but didn't really. Just as carbons. Their simple-mob iterations still work, and the sprites are all there, so... check?

This is important because it means playable xenos are removed.

**Comment by Arokha** [comment]
If anyone ever does this, you can just reopen it. The magic of history.
