### ISSUE TITLE
no money in ATMs

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#150]
#### Brief description of the issue
There's no money in ATMs and I want to get tips for baristaing.

#### What you expected to happen
Set it to anything above 5 thalers and you have no thalers. 
[swipes card]
[ding ding! Transaction completed!]
#### What actually happened
 [Not enough funds.]

#### Steps to reproduce

Literally just try to withdraw or charge money in a manner above 5 thalers.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

[ https://www.youtube.com/watch?v=sCHkdFO8oCo](url)

**Comment by Arokha** [comment]
Self resolved
