### ISSUE TITLE
[GENERAL] AI can tip over Medibots when using macro binds to select Intent.

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [VOREStation/VOREStation#15011]
#### Brief description of the bug
When using macro keys (number row) to select intent, you can tip over medibots as an AI via cams.

#### What you expected to happen
Open the interface for the medibot's controls.

#### What actually happened
I ended up tipping over the medibot from all the way in the AI chamber.

#### Steps to reproduce
1) Login as an AI to the server. brownie points if you were initially spawned as one when the round started.
2) Find a medibot on the map, or wait for someone to build one.
3) press 2 on your keyboard.
4) while it's in camera range, locate the medibot.
5) click that bugger with the mouse and watch it flip on its back.
6) chuckle and go do something else while medbay gets a report that the GODDAMNED STATION AI SOMEHOW TIPPED THE BOT OVER!? WHAT!?

#### Code Revision
Server revision: B:release D:
Commit: [f04fa6b7d7f7a70f46fcb1d5f1ac508b17182459]
 

#### Anything else you may wish to add:
...it's kinda funny.

**Comment by Youtubeboy139** [comment]
"It's a feature"
