### ISSUE TITLE
Map - Broken cargo belt

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1502]
#### Brief description of the issue

Misaligned cargo belt corner on the shuttle loading belt, specifically, the starboard-aft windowside belt.
#### What you expected to happen
The belt to carry the box into the shuttle.

#### What actually happened
The box stops in the corner to do a little jig because it's got happy feet.

#### Steps to reproduce
- 1.Put crate on port-end of belt
- 2.Watch it wobble, but much like a weebo, never fall down.
- 3.Cry every time.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 497f8844d20627fb3cfe2bf776bcd200fe4356ce 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
http://puu.sh/vWLn2/e27883bdc5.jpg

**Comment by Dhaeleena** [comment]
Fixed by #1503
