### ISSUE TITLE
[GENERAL] Spawn in belly not safe on Talon Ship

### ISSUE THREAD

**Issue by AzzyDreemurr13** [VOREStation/VOREStation#15039]
#### Brief description of the bug
There is a bug that if you are a Talon crew member and you are on a Talon ship, your RP partner can't be spawn in your belly, because the Talon ship is not considered safe

#### What you expected to happen
Spawn in the belly on the Talon ship layer is allowed because it is a safe place and often many players play as a Talon crew

#### What actually happened
in the code there is no permission to spawn in the belly on the Talon layer

#### Steps to reproduce
Be not on the NT station/ship layer (be Talon Crew), but the second player as a ghost. Only on the NT station layer, spawn in the stomach is available

#### Code Revision
Server revision: B:release D:
Commit: [88014a194650a26007e289be6e697b7050f7444b](http://127.0.0.1:12010/tmp1472/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/88014a194650a26007e289be6e697b7050f7444b%22%3Ehttps://github.com/VOREStation/VOREStation/commit/88014a194650a26007e289be6e697b7050f7444b%3C/a%3E)
 
#### Anything else you may wish to add:
![image](https://github.com/VOREStation/VOREStation/assets/74739991/31db3878-b610-4e90-9dcb-d9fad89af49b)

**Comment by Heroman3003** [comment]
This isn't really a bug, but intentional behaviour. While a change could be made, currently its working as intended.
