### ISSUE TITLE
Cafe needs shutters

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1504]
#### Brief description of the issue
There's no shutters in the cafe.

#### What you expected to happen
There to be shutters in the cafe.

#### What actually happened
There were no shutters.

#### Steps to reproduce
- (Step 1)Go to Cafe
- (Step 2)See no shutters
- (Step 3)Rob Cafe

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ArgobargSoup** [comment]
Considerin' the fact that the cafe's actually out in the open, with no roof immediately overhead...

**Comment by Somekindofpony** [comment]
There's also no sink, that's super needed.

**Comment by Ketrai** [comment]
Neither is there a sink in the kitchen, but the kitchen does have a soda dispenser, they can get water that way.... I'm not sure if the cafe has water in their dispenser though.

**Comment by Dhaeleena** [comment]
All of the above and sink added. Fixed on #1595
