### ISSUE TITLE
[GENERAL] "Jump-To-Area" runtimes on use

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#15058]
#### Brief description of the bug
I cannot use "Jump To Area" to jump to anywhere on the Stellar Delight. I was trying to test something on the Aerostat, and got the following stacktrace

#### What you expected to happen
To be able to jump to the Aerostat for testing

#### What actually happened
DEBUG: Runtime in adminjump.dm,29: pick() from empty list [[view]](http://127.0.0.1:63566/tmp12356/99e76284.htm?src=[0x2103018c];admin_token=27101001244462645202021815470985410;viewruntime=[0x2103018c])
[2023-06-20T18:37:31] Runtime in adminjump.dm,29: pick() from empty list
   proc name: Jump to Area (/client/proc/Jump)
   usr: Anika (/mob/living/carbon/human) @ (the steel floor) (72,108,2) (/turf/simulated/floor/tiled/eris/steel/brown_platform) (ckey=runadacino)
   usr.loc: (the steel floor) (72,108,2) (/turf/simulated/floor/tiled/eris/steel/brown_platform)
   src: RunaDacino (/client)
   call stack:
   RunaDacino (/client): Jump to Area(null)

### Additional notes

Happens with both with and without TGUI/BYOND input.

#### Code Revision

 Last commit:
https://github.com/VOREStation/VOREStation/commit/860fad8a7534935044ff6bfdff9e08361a8f9bfe

**Comment by Heroman3003** [comment]
Tried locally and couldnt replicate
