### ISSUE TITLE
[GENERAL] Star Treader

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#15054]
#### Brief description of the bug
Star Treaders have no knocked down sprite

#### What you expected to happen
Shoot the thing with a hypersonic gun and have it be knocked over. 

#### What actually happened
It turned invisible due to perhaps lack of sprite. 

#### Steps to reproduce
- (Step 1)Star Treader
- (Step 2)Hypersonic gun
-(Step 3)Invisible star treader until it gets back up
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: a848dd292dfd07ab50234f15af22dcdeafdb37c2 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Runa-Dacino** [comment]
As of commit ( https://github.com/VOREStation/VOREStation/commit/a5a04920b56b68f8795178ecaae84397729877fe ) I could not reproduce this issue.

Inspecting alienanimals_x32.dm there have been no changes over the past 3 months, and preceeding the change at 3 months (squirrels), the startreader_flipped sprite was not touched.

Likewise, no changes to code/modules/mob/living/simple_mob/subtypes/animal/alien animals/startreader.dm either. 

To confirm, I made a virgo_minitest map server and spawned a star treader which I flipped. It showed the expected sprite, as shown there:

![image](https://github.com/VOREStation/VOREStation/assets/20523270/5b633111-f218-4085-8ae7-539d38a23552)
