### ISSUE TITLE
[GENERAL] Coffee Milkshake name broken

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#15075]
#### Brief description of the bug
While drinking coffee milkshake, my cup was called:
Cup of.. what?. 

#### What you expected to happen
For the cup to be named "Cup of Coffee Milkshake"

#### What actually happened
Cup of.. what?. 

#### Steps to reproduce
- Take a coffee cup
- input 6 u ice, 3 u cream, 6 u milk, 15 u coffee
- examine

#### Code Revision
Server revision: B:release D:
Commit: [a848dd292dfd07ab50234f15af22dcdeafdb37c2](http://127.0.0.1:60215/tmp11928/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/a848dd292dfd07ab50234f15af22dcdeafdb37c2%22%3Ehttps://github.com/VOREStation/VOREStation/commit/a848dd292dfd07ab50234f15af22dcdeafdb37c2%3C/a%3E)
 

n.b:
Same applies to normal milkshake
Coffee/milk/ingredients seem to work fine on their own.

**Comment by Heroman3003** [comment]
Seems like there's no properly defined glass type for the drink. This happens with any 'unusual' liquid being put inside drinking glass, so issue is not quite with name of the milkshake itself, but glass definition.

**Comment by Heroman3003** [comment]
Okay, I checked. Milkshakes, not just this one, all of them don't go in cups, is the answer. Yes, that's how it actually is. If you want name, you put it in glass, not cup. Would need to change system.
