### ISSUE TITLE
[GENERAL] Synthetics appear to be getting very little charge from cyborg chargers

### ISSUE THREAD

**Issue by PastelPrinceDan** [VOREStation/VOREStation#15071]
#### Brief description of the bug
Synthetics (not cyborgs, those work fine), when using cyborg chargers, seem to have been getting only very little charge. It doesn't matter what parts the charger is rocking, nor what kind of cell is in it, nor how much power's in the grid, the amount of charge (which is especially noticeable if looking at your NIF whilst charging) goes down extremely slowly, and not by much before the charger runs out of power.

#### What you expected to happen
Charging fairly quickly.

#### What actually happened
Tiny, slow amounts of charge.

#### Steps to reproduce
- Be fully synthetic (FBP/Protean only, not borgs, borgs work fine).
- Enter cyborg charger.
- Monitor charge via NIF power bar or self-diagnostics.
- Weep.

#### Code Revision
Server revision: B:release D:
Commit: [a848dd292dfd07ab50234f15af22dcdeafdb37c2](http://127.0.0.1:58803/tmp5748/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/a848dd292dfd07ab50234f15af22dcdeafdb37c2%22%3Ehttps://github.com/VOREStation/VOREStation/commit/a848dd292dfd07ab50234f15af22dcdeafdb37c2%3C/a%3E)

**Comment by KillianKirilenko** [comment]
I *think* I see the problem? #14905 is supposed to have capped the minimum gain, but reading the math out;

> nutrition is set to the _lower_ of current nutrition + `added value` **or** 500
>
> `added value` is 10 multiplied by 1 minus the _higher_ of the synth food coefficient **or** 0.9

If you have no biofuel processor trait (or, in fact, basically any of them) then it always takes the 0.9 and so you're only actually getting 1 per process tick on the charger.
