### ISSUE TITLE
Weight flavortext does not specify gender pronouns, and it should.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#151]
#### Brief description of the issue
Calling someone "they" is too vague and makes the English teacher in me cry.

#### What you expected to happen
Players who appear male are referred to as male pronouns, and female appearing characters appear as female pronouns in examine text.

#### What actually happened
![capture](https://cloud.githubusercontent.com/assets/6484985/15450451/d3e8e4a2-1f69-11e6-8e5d-06e14f533108.PNG)

#### Steps to reproduce
Examine someone who has gained weight.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
We actually tried to figure that out, but... we failed. We can revisit it later.

**Comment by SpadesNeil** [comment]
See gender.dm

**Comment by Arokha** [comment]
Noooot that simple. In examine.dm for human, it has all these [T_his] [T_him] variable replacement things, and those don’t get carried over to examine_vr.dm when we call to insert our lines.

**Comment by SpadesNeil** [comment]
That's odd. I mean we could probably hackysmash them in.

**Comment by Arokha** [comment]
Also why appearance? ... Isn't that sort of going against the whole thing of gender identity the game has that's used in the rest of the examine text

**Comment by SpadesNeil** [comment]
Wait, I don't understand. Why is it going against the game? This is consistent with the game using pronouns in all other circumstances.

**Comment by SpadesNeil** [comment]
I think this was fixed recently. Close if fixed.
