### ISSUE TITLE
[MAPPING] Tether Disposals Tagger Malfunctions

### ISSUE THREAD

**Issue by KillianKirilenko** [VOREStation/VOREStation#15177]
#### Brief description of the bug

Wrapped items tagged for "Chemistry" and "Medical Storage" will fail to arrive at their intended destination on the Tether.

#### What you expected to happen

For them to arrive at their intended destination.

#### What actually happened

- Items tagged for "Chemistry" will return back to the Delivery Office/Sorting Room.
- Items tagged for "Medical Storage" will instead be delivered to the Medical Breakroom.

#### Other information

Items tagged for the Medical Breakroom, CMO's Office, or Resleeving are all delivered A-OK. Following packages through the pipes using admin observation tools (by throwing a named mob in a locker, wrapping it, tagging it, kicking it through the disposals system, and then observing the mob using the Observe verb on the OOC tab) shows the packages passing straight through the pipes outside of Medical where the sorters for Chemistry and Medical Storage are located.

If I had to guess there's some weird minor hiccup with the sorters that got introduced when medbay was relocated to surface, but the sorter system is used so rarely that barely anybody notices the problem.

**Comment by Heroman3003** [comment]
Couldnt replicate the Medical storage part, but Chemistry was broken, so fix is coming up
