### ISSUE TITLE
Donut alchemy

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#1525]
#### Brief description of the issue
When trying to make banana cream pie, get donuts instead.

#### What you expected to happen
To make banana cream pie

#### What actually happened
Inserted 5u sugar, 1dough and 1 banana in the microwave, resulted in donut, which is 5u of sugar, and dough.

#### Steps to reproduce
- try to make banana cream pie
- get baffled as you actually make donuts instead
- make security happy

**Comment by Very-Soft** [comment]
You're a wizard. :C
