### ISSUE TITLE
[UI] Build 515.1613 Byond, Half of the displays are white

### ISSUE THREAD

**Issue by AzzyDreemurr13** [VOREStation/VOREStation#15271]
#### Brief description of the bug
After updating to Build 515.1613 (due to the fact that many large SS13 servers have started switching to version 515), many interfaces in the game turn white

#### What you expected to happen
everything is loading stably

#### What actually happened
![image](https://github.com/VOREStation/VOREStation/assets/74739991/86ffe7f8-48be-449d-9924-b842b3bc8ca8)

#### Steps to reproduce
- Install beta Byond 

#### Code Revision
Server revision: B:release D:
Commit: [dced16c71aa0deaf05662768b4a6f3bd70285dd0](http://127.0.0.1:3353/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/dced16c71aa0deaf05662768b4a6f3bd70285dd0%22%3Ehttps://github.com/VOREStation/VOREStation/commit/dced16c71aa0deaf05662768b4a6f3bd70285dd0%3C/a%3E)
 

#### Anything else you may wish to add:
Build 515.1613

**Comment by Heroman3003** [comment]
We do not officially support 515 builds at the moment.
