### ISSUE TITLE
A persistence bug with ghosts

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#1532]
#### Brief description of the issue
If you have your persistence settings set to remember where you left the round, if you leave the round through any exit, but your active ghost ends up on the tram and stays on it until arrival at the Centcomm colony, it'll set your character's spawn point to the tram station.

#### What you expected to happen
To arrive at the station through the teleporters I had left through last round.

#### What actually happened
Arrived at tram station instead.  Checked character setup, and it had been set to tram station instead of gateway.

#### Steps to reproduce
- Have it set to remember where you left the round.
- Go to cryo/teleporter/whatever that's not the tram station.
- Ghost to let your character be cryo'd/teleported/whatever'd.
- Verify on character setup screen that your spawn location has been set to that exit.
- Move your ghost to the tram/follow someone on the tram and stay on it until it arrives at central.
- OPTIONAL: Investigate character setup spawn location option immediately after the tram arrives and note that it's been set to tram station.
- Join next round and find yourself at the tram station, instead of the exit you had used.

#### Code Revision
- Server revision: release - 
e89565c76f3e4fe3f3549036d006833bbe364a32 

#### Anything else you may wish to add:
- Active ghost may not actually need ta be on the tram, may just need to be active at centcomm upon the tram arriving and the round ending.

**Comment by DeepIndigo** [comment]
Someone figured out why the hell it kept changing people's spawn to "shuttle"/"tram", yay!
