### ISSUE TITLE
[GENERAL] Tesla coils (possibly all types) show as being not secured when they are secured.

### ISSUE THREAD

**Issue by TankTheBirb** [VOREStation/VOREStation#15379]
#### Brief description of the bug
The tesla coil is giving me anxiety by saying it isn't secured when it is

#### What you expected to happen
Tesla coil to reassure me it is secured to the ground when examined

#### What actually happened
PANIC- then relief. Then bug report.

#### Steps to reproduce
- secure coil
- coil is secure
- coil says its not secure
- panic
- make bug report

#### Code Revision
Server revision: B:release D:
Commit: [9fa1252854b1e91d3dc41227894fef7e8f2c4f9f](http://127.0.0.1:50219/tmp10984/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/9fa1252854b1e91d3dc41227894fef7e8f2c4f9f%22%3Ehttps://github.com/VOREStation/VOREStation/commit/9fa1252854b1e91d3dc41227894fef7e8f2c4f9f%3C/a%3E)
 

#### Anything else you may wish to add:
![image](https://github.com/VOREStation/VOREStation/assets/96669534/385fd269-8521-4078-b278-142a7e7e1a80)
![image](https://github.com/VOREStation/VOREStation/assets/96669534/2aaf556a-904f-4fc1-a4e9-3fc00bea72ce)

**Comment by KillianKirilenko** [comment]
That... that one's on me. I accidentally inverted the states.

I'll fix it in a sec.
