### ISSUE TITLE
Security Department - Security Camera Consoles don't work.

### ISSUE THREAD

**Issue by MatchaFrappe** [VOREStation/VOREStation#1538]
#### Brief description of the issue
All the security camera monitors in security are broken.

#### What you expected to happen
I expected to see the whole station on the security camera monitors.

#### What actually happened
Clicking on the different camera locations doesn't change cameras.

#### Steps to reproduce
- Go to security.
- Use security camera monitor.
- Click on a camera location.

#### Code Revision
- release - a2c8cec446a68b440d5db9fd47b371c08adbae19 
 
#### Anything else you may wish to add:
- http://i.imgur.com/yIVNxOE.gifv

**Comment by Ketrai** [comment]
This ain't just the security cameras, the same goes for the mining outpost cameras for the quartermaster, and I suspect engineering too.

**Comment by SpadesNeil** [comment]
@Cameron653 
```A certain job or feature becomes unusable when the bug occurs.```

Source: https://github.com/VOREStation/VOREStation/wiki

:P
