### ISSUE TITLE
Mulebots don't have any destinations programmed into them. (BUG)

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#1539]
#### Brief description of the issue
The mulebots in cargo can't send stuff anywhere, they only have their homepads as selectable destinations.

#### What you expected to happen
There to be destinations for them to go to, at least for the third floor on which they are located.

#### What actually happened
There's only the home pads as locations.

#### Steps to reproduce
- Go to cargo, try setting mulebot destination.
- Observe as there are only three destinations, which are just the cargo home pads, you can't send the mulebot anywhere else.

**Comment by Ketrai** [comment]
A complication to this issue may be that I assume mulebots can't travel up and down stairs, at least train  carts can't.

**Comment by Screemonster** [comment]
As amusing as the mental image of mulebots clunking up and down the stairs is, I don't think they're really suited to this map anyway. They might as well be taken out given that they were buggy even before we changed. iirc they're a holdover from before disposals mailing was a thing.

For a start, you can't use them to mail stuff between station and space 'cause they can't use the elevator.

**Comment by SpadesNeil** [comment]
I agree we should remove mulebots.

**Comment by Cameron653** [comment]
Should this be labeled wontfix if we're removing them?

**Comment by SpadesNeil** [comment]
yep
