### ISSUE TITLE
Re-add Janitor Cart (Pimpmobile)

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#154]
The station is big enough for it to be used, but it must be balanced.
- [ ] Slow it the fuck down but make it faster than travel on foot. Maybe as fast as the cargo train is reasonable.
- [ ] EMP should disable the vehicle and fry the battery in case someone is fucking off with it. Cargo train should have similar effects.
- [ ] Security should be given speed traps specifically for combatting these vehicles to disable them.
- [ ] In fact, let's give Security the Paddy Wagon (Security Cart). We have old, unused sprites from the old code.

**Comment by Jwguy** [comment]
I have a simple request: Add the ability to attach the Janitor Cart to it, a la Cargo Tug method?

It'd kill two birds with one stone, and the code from the tug should be largely adaptable, I would think.

**Comment by Arokha** [comment]
Probably part of Joan's vehicles thing.

**Comment by Arokha** [comment]
A dream in the mind of a child in a snowglobe. Also it seems admin opinion has somewhat changed about readding this to be "nnno". The current janicart is also way better coded, and equipped.
