### ISSUE TITLE
Hardsuits get Phoron contamination and can't be cleaned

### ISSUE THREAD

**Issue by Yoshax** [VOREStation/VOREStation#1545]
#### Brief description of the issue
Hardsuits worn outside end up contaminated with Phoron and can't be cleaned.

#### What you expected to happen
The suit to not get contaminated, or at the least be able to clean it.

#### What actually happened
The suit got contaminated and there's no way to clean it.

#### Steps to reproduce
- Wear hardsuit outside
- Go inside
- Cry

#### Anything else you may wish to add:
- Experienced the the Industrial Hardsuit, unsure about others.

**Comment by Cameron653** [comment]
Marking this as severe as it completely prevents jobs such as xenoarch and mining to do their jobs without slowly dying and having to head back in for antitox every few minutes.

**Comment by chaoko99** [comment]
As a note, they work fine so long as you don't accidentally open something.

**Comment by AeroWing** [comment]
I am curious Yosh, did you use a suit cycler and tried to clean the suit on max UV settings? That might work out.

**Comment by chaoko99** [comment]
Hardsuit, not a voidsuit. Hard-suits go in the back slot, and do not comply with goddamn anything whatsoever.

**Comment by SpadesNeil** [comment]
Technically marking this as "won't fix" because we're removing the chance of hardsuits getting contaminated by phoron to begin with.
