### ISSUE TITLE
[GENERAL] "black jeans short shorts" have no in-character sprite

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#15477]
#### Brief description of the bug
Black jeans short shorts have no in-character sprite, they have a hand sprite though.

#### What you expected to happen
To not be missing my pants.

#### What actually happened
My pants are invisible and now everyone is staring at my underwear... I think I had this exact nightmare once.

#### Steps to reproduce
- Enter character setup ->Casual Dress
- Shorts selection -> black jeans short shorts
- black jeans short shorts are invisible.
- Curiously enough, no other shorts are invisible.

#### Code Revision
- [263effeb7e9994a0223b8953d2cfd887658df648](http://127.0.0.1:64403/tmp16796/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/263effeb7e9994a0223b8953d2cfd887658df648%22%3Ehttps://github.com/VOREStation/VOREStation/commit/263effeb7e9994a0223b8953d2cfd887658df648%3C/a%3E)

**Comment by Runa-Dacino** [comment]
Attempted to recreate on local test server synced with master.

Could not reproduce with Vulpkanin species.

Checked live. Human and custom species (human base) could not reproduce either.

Checked both spawned in and preview.

**Comment by TheToaster98** [comment]
It has been fixed after clearing cache.

**Comment by TheToaster98** [comment]
It has been fixed after clearing cache.
