### ISSUE TITLE
Custom ID - Amaya Rahl - KiraAlitruss

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#1548]
#### Brief description of the issue
I was told to make an issue about my custom ID. It was approved by Dhaeleena. The thread is here: http://forum.vore-station.net/viewtopic.php?f=26&t=945
All needed information is located within the thread. First time making something like this. I apologise for any mistakes, blunders or other such errors.

#### Code Revision
- Server revision: release - 
5009c1629a79cc303755d13980a4181128a40b61

**Comment by Arokha** [comment]
FYI only headmins can approve fluff items, so I harrassed Joan to look at it, which she was nice enough to do, and she approved it.
