### ISSUE TITLE
[GENERAL] Boozehound Vorebelly Sprite 

### ISSUE THREAD

**Issue by LunaTender** [VOREStation/VOREStation#15480]
#### What you expected to happen
Upon ingesting a mob or item, the specific dogborg's (Boozehound) belly will bloat and distend. 

#### What actually happened
Upon ingesting a mob or item, a ghostly dogborg sprite will appear vaguely visible over the boozehound sprite that says 'oops'.

#### Steps to reproduce
1) Play as Service Cyborg
2) Select Boozehound and preferred sprite
3) Change Appearance via Robot Command menu
3) Eat someone or something 

Edit: It seems to only happen after you change you appearance. It will work initially before breaking upon changing your appearance via Robot Commands

**Comment by ReoDaProtovali** [comment]
Oh oops. I'll look into that later
