### ISSUE TITLE
[GENERAL] Timestamp formatting/appearance oddities

### ISSUE THREAD

**Issue by KillianKirilenko** [VOREStation/VOREStation#15515]
#### Brief description of the bug
Timestamps don't appear for emotes or subtles if they have a linebreak in them, and can appear in the middle or at the end of them in certain circumstances.

#### What you expected to happen
For the timestamps to appear at the start of the message(s).

#### What actually happened
Timestamps appeared in weird places, or not at all.

#### Steps to reproduce
- Send a bunch of messages in subtles (without using autowhisper?).
- Use bold text somewhere in the message.
- Marvel as timestamps sometimes appear in front of the bolded text, or at the end of the message, or not at all.
 
#### Code Revision
Server revision: B:release D:
Commit: [f3b053ea8a6297de2b1168063586e7a5cfede906](http://127.0.0.1:63604/tmp13804/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/f3b053ea8a6297de2b1168063586e7a5cfede906%22%3Ehttps://github.com/VOREStation/VOREStation/commit/f3b053ea8a6297de2b1168063586e7a5cfede906%3C/a%3E)

#### Anything else you may wish to add:
My partner was composing longform posts in LibreOffice; I was using Notepad. My own subtles lacked timestamps but didn't insert in the middle or append it to the end randomly (despite liberal use of bold), only in my partner's.

I'm as baffled as to how and why, and it wasn't particularly disruptive, but it happened three posts in a row so I'm throwing this out on the offchance someone figures it out.

**Comment by Kashargul** [comment]
The timestamps not showing at all part should be resolved in #15520
The other issue could be related by chance with having a closing span right at the end of a line or an entire section in its own span. So just to see if it happens again.

**Comment by Kashargul** [comment]
Did it happen ever again since the change? Or can we close this?

**Comment by Kashargul** [comment]
With how TG-Chat works compared to previous VChat, we'll have an easy solution for all those worries. I'll add it in my next PR and then close this issue along with it.
