### ISSUE TITLE
Upward pipes do not layer properly.

### ISSUE THREAD

**Issue by KiwiDaNinja** [VOREStation/VOREStation#1551]
#### Brief description of the issue
Trying to place an 'upwards regular pipe' to traverse Z-levels will cause it to dissapear, and any attempts to place a new one gives you a 'There is already a pipe of the same type at this location.' message. Trying to run gas through the pipe to the upper level doesnt do anything.

#### What you expected to happen
The pipe to be placed down and connect

#### Steps to reproduce
-Place a connector down. (to give a place for the pipe to connect to)
-Go up a Z-level and place a down pipe - note how it actually places.
-Go back down and place the up pipe.
-Wonder how the pipe has ceased to exist.

#### Code Revision
5009c1629a79cc303755d13980a4181128a40b61 
 
#### Anything else you may wish to add:
Edit: This seems to already affect the up-pipe used to produce oxygen from the lower level, and possibly other pipes elsewhere.

Edit2: This does affect newly placed supply/scrubber pipes, but the mapped ones seem to work fine.

**Comment by chaoko99** [comment]
clarification: This only means that you placed it on a turf with a tile on it. Lever off the tile and place it, the pipe is actually there.

**Comment by chaoko99** [comment]
They work. Trust me. They just don't layer above platings like they should.

**Comment by SpadesNeil** [comment]
Was this fixed?
