### ISSUE TITLE
Putting an item into a toolbelt or bag while standing on a catwalk above a z-level causes that item to drop to the floor below

### ISSUE THREAD

**Issue by SeigaSeiga** [VOREStation/VOREStation#1552]
#### Brief description of the issue
Be me, a Vox. Put tool into toolbelt. Tool does not end up in belt despite chat message saying it does. Tool ends up on floor below.

#### What you expected to happen
Putting a tool in my belt or bag.

#### What actually happened
My character is apparently very clumsy.

#### Steps to reproduce
- (Step 1) Stand on catwalk [the catwalk overlooking the engine room will do]
- (Step 2) Hold a tool in hand, attempt to put it in toolbelt
- (Step 3) Check the z-level below where you were standing

#### Code Revision
Server revision: release - 
5009c1629a79cc303755d13980a4181128a40b61 

#### Anything else you may wish to add:
Haven't tested this as non-vox.

**Comment by SeigaSeiga** [comment]
Apparently this is a pretty easy way for the chief engineer to lose their ID by having it drop through the catwalk outside their office.

**Comment by SpadesNeil** [comment]
I have _never_ had this happen. Still a bug?
