### ISSUE TITLE
[GENERAL] [Low priority] Laundry Basket Dupes of entity

### ISSUE THREAD

**Issue by ChipsTheDoc** [VOREStation/VOREStation#15534]
"laundry basket" item seems to duplicate an "off hand" entity that duplicates infinitly.

Pick up my laundry basket, drop it and not have a leftover entity in my left hand.

Duplicated a entity called "Laundry basket - Second hand" and I could have done that infinitly,

#### Steps to reproduce
- Pick up laundry basket
- Drop laundry basket (Remaining entity on left hand isn't dropped: "Laundry basket - Second hand"
- Drop "Laundry basket - Second hand"
- Pick up "Laundry basket - Second hand", duplicates the entity
- repeat
 

![image](https://github.com/VOREStation/VOREStation/assets/45475668/690be0c7-aa58-47e8-95d9-0d08422a8171)

**Comment by Kashargul** [comment]
Guh, qdel loop.... I will take a look later.
