### ISSUE TITLE
phoron selling doesn't seem to work on tether for supply points, perhaps platinum doesn't work either?

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#1558]
#### Brief description of the issue
When selling 50 phoron in an open empty crate, only get 5 points of supply. When selling 50 phoron crystals without any crate, get nothing. 

#### What you expected to happen
To get a whole ton of points for selling centcom phoron via the shuttle.

#### What actually happened
Get ripped off.

#### Steps to reproduce
- Put phoron in crate or on the ground, then send to centcom.
- Observe no or barely any change in supply points.
- Apologize to yourself for wasting time mining so much phoron.

**Comment by Ketrai** [comment]
Seems that you need to not only get an empty crate, but close it too, it's confusing how the system works.

**Comment by SpadesNeil** [comment]
Unsecured cargo is unsafe for CentCom cargo technicians and the ship. You must obey their protocol to get paid, or they will use the phoron to pay for damages.

~~The devs and I also don't want to bother fixing this.~~
