### ISSUE TITLE
Eye covering doesn't block Phoron in the eye

### ISSUE THREAD

**Issue by Yoshax** [VOREStation/VOREStation#1567]
#### Brief description of the issue
When you go outside into the Phoron atmosphere with something only covering your eyes you take eye damage.

#### What you expected to happen
Not to take eye damage.

#### What actually happened
Took eye damage.

#### Steps to reproduce
1. Go outside with only something covering eyes
2. Eyes melt

**Comment by Arokha** [comment]
Already going to code this. It'll just use the airtight flag on eyewear, which none have for now. I'll add it to like, science goggles, and then sprite some new 'generic' goggles too.

**Comment by ArbyTheDragon** [comment]
Add it to welding goggles too

**Comment by SpadesNeil** [comment]
This was handled in Polaris sync, yes?

**Comment by chaoko99** [comment]
Fixed?
