### ISSUE TITLE
[GENERAL] Purging chat does nothing whatsoever

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#15682]
#### Brief description of the bug
Using the purge chat button on the TGchat does nothing and the log remains, growing ever larger.

#### What you expected to happen
Purge chat to clean my chat logs.

#### What actually happened
The chat is not purged, the logs are ever-growing.

#### Steps to reproduce
- Spend 5 minutes on virgo.
- Press the gear, then go to Export.
- Purge message archive.
- Nothing happens.
- Spamming the button, reconnecting to the server, restarting byond and changing the chat to oldchat after trying to purge do not purge.

#### Code Revision
- [122fbfe4d42140b8c05c2e963737aad755a9c991](https://github.com/VOREStation/VOREStation/commit/122fbfe4d42140b8c05c2e963737aad755a9c991)

**Comment by ItsSelis** [comment]
Have you also confirmed the purge of the chat (the text of the button changes)?

At least "spamming the button" would imply that.

**Comment by Kashargul** [comment]
Known issue. Selis, already tracked it back and fixed it in my PR.

**Comment by Kashargul** [comment]
There's a few instances in which the active chat array is pushed back into the storage archive.

**Comment by TheToaster98** [comment]
This happened while I was asleep, woops.
Here is what I have experienced so far:
- Exporting logs contains info from previous rounds, even after purging.
- Purging and exporting again after that last one, however, shows empty logs.
- HOWEVER, exporting again next day has all the previous logs still.
Just noting it down for the sake of offering extra context, since it seems it will be fixed with that PR.
