### ISSUE TITLE
Replace obnoxious fucking Captain whistle.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#157]
#### Brief description of the issue
THAT FUCKING WHISTLE NEEDS TO GO. TOTALLY JUSTIFIES AN EXTREME ISSUE.

#### What you expected to happen
A nice gentle ping to inform me the Captain or HoP has arrived.

#### What actually happened
![my-fucking-ears](https://cloud.githubusercontent.com/assets/6484985/15450847/4bc6c892-1f77-11e6-8310-28e4092cb1a4.jpg)

#### Steps to reproduce
Have a Captain join mid-round.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by SpadesNeil** [comment]
Am I the only one whose ears get raped by this?

**Comment by Vae42** [comment]
Could we include that horrifying alarm whenever theres a vote? Here's a shot I sent to my physician after the last mid-round vote 
![image](https://cloud.githubusercontent.com/assets/19507867/15450883/9831706e-1f78-11e6-8b6a-7407633d397b.png)

**Comment by SpadesNeil** [comment]
Make an issue for that too.

**Comment by Leshana** [comment]
I like the captain bosun whistle, altho its a bit quiet, hard to hear.

**Comment by Cameron653** [comment]
Here's the lines in question:
https://github.com/VOREStation/VOREStation/blob/ad24bfcfdf7a7c7e99b1bdc491a048ae58e62d35/code/game/jobs/job_controller.dm#L444

It's set to volume 20.
