### ISSUE TITLE
[GENERAL] TGUI 5.0 interface issues

### ISSUE THREAD

**Issue by Kashargul** [VOREStation/VOREStation#15746]
#### Brief description of the bug
Currently interfaces are no longer reloading on change as they should.

#### What you expected to happen
Interfaces to reload on change.

#### What actually happened
The interface does not react, remains in the old state.

#### Steps to reproduce
- Open one of the more complex tgui interfaces, example R&D console
- Open one of the tabs
- Try to use one of the sub categories

#### Code Revision
- current master branch
 

#### Anything else you may wish to add:
Green: Works
Red: Does NOT
![grafik](https://github.com/VOREStation/VOREStation/assets/144968721/0f09aef9-38f7-4405-b944-b5845f3fc15e)

___________________________________________________________________________________

=> In general seems to be an issue of sub-components

- [x] hand through the props in all sub components (single source of truth) | ui reload issue => See CharacterDirectory.jsx as example
Issues to look out for => localState in childs, sharedState in childs, usage of value={array[0]}
- [x] find a fix for tgui number input | allow sane inputs
- [x] edit all tgui_input_number uses with floats to have the round_value = FALSE parameter | allow floats on latest input code again
- [x] Test the job selection panel for crashes
- [x] DNAModifier.jsx => context?
- [x] NanoMap.jsx => context?

__________________________________________________________________________________

Finished example:  CharacterDirectory.jsx

To check:
UseSharedState:
- [x] AccountsTerminal.jsx
- [x] Autolathe.jsx
- [x] ExosuitFabricator.jsx
- [x] ICPrinter.jsx
- [x] LawManager.jsx
- [x] Newscaster.jsx

Search:
- [x] Biogenerator.jsx
- [x] CasinoPrizeDispenser.jsx
- [x] CameraConsole.jsx
- [x] MessageMonitor.jsx
- [x] MiningVendor.jsx
- [x] Newscaster
- [x] Uplink

UseLocalState:
- [x] AirAlarm.jsx
- [x] Biogenerator.jsx
- [x] CasinoPrizeDispenser.jsx
- [x] CrewMonitor.jsx
- [x] MiningVendor.jsx
- [x] OvermapFull.tsx
- [x] PipeDispenser.jsx
- [x] RapidPipeDispenser.jsx
- [x] Uplink.jsx
- [x] VorePanel.jsx

UseState:
- [x] MessageMonitor.jsx 
- [x] NIF.jsx
- [x] PathogenicIsolator.jsx
- [x] Pda.jsx
- [x] PersonalCrafting.jsx
- [x] PowerMonitor.jsx
- [x] RCON.jsx
- [x] SupplyConsole.jsx
- [x] pda_messenger.jsx

StaticArray:
- [x] SecureSafe.jsx
- [x] SuitCycler.jsx

Annoying to fix:
- [x] Communicator.jsx => NOPE... not right now
- [x] MobSpawner => needs an overhaul
- [x] ResearchConsole

Scroll Event from child to parent:
- [x] GeneralRecord.jsx => Scrolling broken
- [x] MedicalRecords.jsx => Scrolling broken
- [x] SecurityRecords => Scrolling broken

**Comment by chinthliss** [comment]
Think a version of this is happened with suit cyclers - after picking target paintjob and species for painting it still shows 'no change' but doing the customization works as expected.

**Comment by Kashargul** [comment]
Similar issues with the rig suit controller.

**Comment by KillianKirilenko** [comment]
To add to this, selectors/inputs no longer allow double-clicks to instantly select an option as they did under 4.0.

**Comment by Kashargul** [comment]
Job selection window seems to crash with

![image](https://github.com/VOREStation/VOREStation/assets/144968721/d8280c63-00bc-4523-a2a6-392c0f103a4a)

**Comment by Kashargul** [comment]
ToDo: Explicitly define all tgui_number_inputs with float input with round_vlaue = FALSE

**Comment by KillianKirilenko** [comment]
Good news: Ctrl+Enter now works in certain inputs.

Bad news: It doesn't work in Say (and thus possibly emote/etc., haven't tested thoroughly).

Also `Set OOC Metainfo` loads your main OOC notes into the Likes and Dislikes fields when going through via the verb.

**Comment by KillianKirilenko** [comment]
Suit cyclers are broken, *again*.

**Comment by Kashargul** [comment]
Say always was single line

**Comment by KillianKirilenko** [comment]
> Say always was single line

No no, you misunderstand my point here. My point is that OOC notes now permit shift+enter to add a newline, or just enter to send.

Which means Say/Emote/etc. could now be made to do that, instead of needing the kludgy-ass Input Lock I added a while back.

**Comment by Kashargul** [comment]
> > Say always was single line
> 
> No no, you misunderstand my point here. My point is that OOC notes now permit shift+enter to add a newline, or just enter to send.
> 
> Which means Say/Emote/etc. could now be made to do that, instead of needing the kludgy-ass Input Lock I added a while back.

Best make a suggestion issue for it. I've way too much to keep track in this one here as you can see above to get all our UIs working again.

**Comment by Kashargul** [comment]
> > ToDo: Explicitly define all tgui_number_inputs with float input with round_vlaue = FALSE
> 
> I think this still applies to the circuit debug tool. you can't use non integer values or negatives with it.

Does this one need floats / negatives? When it is a pin selection?

**Comment by TeleTubby2** [comment]
> > > ToDo: Explicitly define all tgui_number_inputs with float input with round_vlaue = FALSE
> > 
> > 
> > I think this still applies to the circuit debug tool. you can't use non integer values or negatives with it.
> 
> Does this one need floats / negatives? When it is a pin selection?

it's for any number value, not just pins. simplest non-math one would be giving a hologram a negative X offset.

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/issues/15814

@Kashargul

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/issues/15820

**Comment by Runa-Dacino** [comment]
https://github.com/VOREStation/VOREStation/issues/15831 (generalized report)
https://github.com/VOREStation/VOREStation/issues/15830 (specific report)

Consecutive TGUI text input calls are inheriting previous calls' values
