### ISSUE TITLE
[UI] vchatdark gal-com color breaks(?) with italics

### ISSUE THREAD

**Issue by Rick4242** [VOREStation/VOREStation#15749]
#### Brief description of the bug
When using multiple languages in one say, the gal-com colors when using 'vchatdark' become bugged if their language key is typed after an _italics_

#### What you expected to happen
Galactic common is represented in white text when it's being typed, and also whenever the language key is used

#### What actually happened
For some reason, if you start a 'say' in a language other than galactic common and in italics, if you close said italics and then continue in galactic common, the language color changes to a light blue that is used in all of the other themes

#### Steps to reproduce
- Open a 'say' while using the 'vchatdark' theme
- Type a message that starts with a language key other than galactic common, and then continues in galactic common
- _Italicize_ the part of the message not in galactic common (including the language keys)
- Send the 'say' message, and observe results.

#### Code Revision
- Server revision: B:release D:
Commit: [4c9b033bf55b828c00813e40556e44a29acd6e81](https://github.com/VOREStation/VOREStation/commit/4c9b033bf55b828c00813e40556e44a29acd6e81)
 

#### Anything else you may wish to add:
- Example of said bug happening while trying to replicate it
![image](https://github.com/VOREStation/VOREStation/assets/42255398/fc95ba2f-51de-4f05-b9e9-c6a99f10c224)

**Comment by Rick4242** [comment]
I swear this has to be one of the most obscure bugs that I've seen from this code.

**Comment by Kashargul** [comment]
I know the issue already, will add it to my currently open chat PR later.
