### ISSUE TITLE
[GENERAL] Dream Seeker Launch Issues, Character Directory OOC Notes.

### ISSUE THREAD

**Issue by HiddenName1702** [VOREStation/VOREStation#15756]
#### Brief description of the bug
Dream Seeker was obscenely slow on launches, would lag out for minutes when loading. (Potentially fixed by clearing message archive through the settings button above chat)
Once above issue was fixed, now I cannot access OOC notes through the character directory.

#### What you expected to happen
OOC Notes display when clicking 'view' in character directory.

#### What actually happened
Nothing happens when the button is clicked.

#### Steps to reproduce
- Open Character Directory
- Click 'view' for any player's OOC notes.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 [ec576aba4232f27b737e5acf71701def982700b3](https://github.com/VOREStation/VOREStation/commit/ec576aba4232f27b737e5acf71701def982700b3)

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Unsure if something I did before clearing the message archive cause the issue to appear, however reinstalling BYOND after clearing  the message archive fixed all but the above issue.

**Comment by Kashargul** [comment]
Tgui interface, likely part of the sub category issue, linked to #15746

**Comment by ItsSelis** [comment]
A fix has been deployed
