### ISSUE TITLE
[UI] Character Directory buttons broken

### ISSUE THREAD

**Issue by AzzyDreemurr13** [VOREStation/VOREStation#15761]
#### Brief description of the bug
Throughout yesterday and today, the buttons in the Character Directory completely do not work and do not allow you to view the OOC Notes of other players

#### What you expected to happen
The buttons are working and I can view the ooc notes of the players

#### What actually happened
![image](https://github.com/VOREStation/VOREStation/assets/74739991/2ebfa1e4-5b37-4566-850b-bbcacddb3a91)

#### Steps to reproduce
- 

#### Code Revision
Server revision: B:release D:
Commit: [ec576aba4232f27b737e5acf71701def982700b3](https://github.com/VOREStation/VOREStation/commit/ec576aba4232f27b737e5acf71701def982700b3)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Fixed, pending deployment
