### ISSUE TITLE
[MAPPING] Ventilation is broken in the Talon medical

### ISSUE THREAD

**Issue by AzzyDreemurr13** [VOREStation/VOREStation#15762]
#### Brief description of the bug
When I decided to assemble a body scanner in the Talon medical compartment, I noticed a strange ventilation, I unscrewed the tables and checked the pipes. I saw that the ventilation and pipes were in different places

#### What you expected to happen
the ventilation is in place and it works

#### What actually happened
![image](https://github.com/VOREStation/VOREStation/assets/74739991/ee8d74c7-df14-437c-b35c-c258728d04a2)
![image](https://github.com/VOREStation/VOREStation/assets/74739991/e82194ee-1e7c-47ae-b73c-c4c8e08ca7e7)
![image](https://github.com/VOREStation/VOREStation/assets/74739991/d3bf40d3-1395-4c73-8f2a-cf8bd106edcb)

#### Code Revision
Server revision: B:release D:
Commit: [ec576aba4232f27b737e5acf71701def982700b3](https://github.com/VOREStation/VOREStation/commit/ec576aba4232f27b737e5acf71701def982700b3)
 

#### Anything else you may wish to add:
Talon medbay

**Comment by Zulban48** [comment]
Looks like the vent needs to be moved to the left by one tile. At least the scrubber is fine.
