### ISSUE TITLE
RD's Window tints aren't complete

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1578]
#### Brief description of the issue
Turned on the tints.
One of the windows didn't tint.

#### What you expected to happen
Not be seen

#### What actually happened
Gave robotics A+ view

#### Steps to reproduce
- (Step 1)Turn on tints
- (Step 2)Greet your roboticist in the nude.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 427adb7fc953f9972c3c1da1a80d02e1844f86ab 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
https://puu.sh/w3xry/6803880e68.jpg

**Comment by Dhaeleena** [comment]
Fixed

**Comment by Natje0** [comment]
Oh, didn't check github for a while. As Dhael fixed it, closing it~
Thanks Dhael!
