### ISSUE TITLE
[UI] MOTD formatting broken TGChat. Linebreaks and colours are missing

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#15799]
#### Brief description of the bug
MoTD formatting is broken in TGChat. The expected linebreaks and colours are absent.

#### What you expected to happen
For it to be green with linebreaks to make it readable.

#### What actually happened
![image](https://github.com/VOREStation/VOREStation/assets/20523270/e0946888-5ab3-4cc8-b18d-cb36a4bcce31)

#### Code Revision
Server revision: B:release D:
Commit: [4a06e2a8728dfd7f2ac8a556587214ea438f6ca2](https://github.com/VOREStation/VOREStation/commit/4a06e2a8728dfd7f2ac8a556587214ea438f6ca2)

**Comment by Kashargul** [comment]
Sadly I can not help you on this one. You need to update your server txt file to be compatible. We already did that downstream.

**Comment by Runa-Dacino** [comment]
> Sadly I can not help you on this one. You need to update your server txt file to be compatible. We already did that downstream.

If I may ask, what needed to be changed so that I can convey it to the Host?

**Comment by Kashargul** [comment]
I would need to see the file's html tags for it. But for colours you want to take a look at this:

https://github.com/VOREStation/VOREStation/blob/744515e21ee38749a559e1ebae386d2b43780558/code/__defines/span_vr.dm#L4

For linebreaks, it's the common `<br>` tag

For URLs, you only ever want to use the URL now without anything tag wise around it. All URLS must be `https`

**Comment by Runa-Dacino** [comment]
Received motd.txt from host. 

Issue was simple: <br> tags were without their </br> complement. This was added and this is how it looks now on local:

![image](https://github.com/VOREStation/VOREStation/assets/20523270/8a3c2748-08a1-4823-a987-cc1866362143)

I will keep the issue open until host updates box and then close it.

**Comment by Kashargul** [comment]
Your first two links are still http, should be https if the websites support it.

**Comment by Runa-Dacino** [comment]
Closed as working.
