### ISSUE TITLE
LOOC and emote cant be seen in a borg belly

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#158]
While inside a borg stomach (brigbelly and medbelly) I cant see my Looc or emote nether can I see other players ME actions or Looc but they seem to be able to see mine. I can see anything that is spoken, and regular OOC is fine.

#### Be eaten by a borg, attempt to use ME action

**Comment by Arokha** [comment]
Same cause as #149. Fixing it there will fix it here.
