### ISSUE TITLE
Map - Library shelves

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1581]
#### Brief description of the issue
Library has no shelves for reference or non-fiction.

#### What you expected to happen
All five genres recognized by the library DB to be represented with shelves.

#### What actually happened
Only Religion, Fiction, and Adult have shelves.

#### Steps to reproduce
- 1.Go to library
- 2.Mouse over shelves
- 3.Not see shelves for reference or non-fiction

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 427adb7fc953f9972c3c1da1a80d02e1844f86ab 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
It's in the library. The shelves. Check 'em out. No pun intended.

**Comment by Dhaeleena** [comment]
Its been done. Fixed on #1595
