### ISSUE TITLE
[UI] Painting menu broken

### ISSUE THREAD

**Issue by ZodiacShadow** [VOREStation/VOREStation#15820]
Attempting to use a paintbrush on a canvas makes the canvas pop up, but does not allow for any actual panting to happen.

I expected to be able to place pixels on the white canvas. I could not.

#### Steps to reproduce
- Pick up canvas.
- Place canvas on easel.
- Pick up palette and paintbrush.
- Set paint colour.
- Use paintbrush on canvas.
- No colours are placed on the canvas.

Server revision: B:release D:
Commit: 34a300b200c181a0103a98f20c9fe2654bb039c6

**Comment by Runa-Dacino** [comment]
Confirmed not working on latest build of TGUI.

**Comment by Kashargul** [comment]
Seemingly the x, y coords on the click event are NaN now.
