### ISSUE TITLE
[UI] Multiple consecutive tgui_input_text() windows inherit the text of the previous input box rather than default return value

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#15831]
#### Brief description of the bug
When multiple consecutive tgui_input_text() windows are called as part of a single procedure, the subsequent text input boxes inherit the contents of the previous one. This can be observed with multiple procedures - such as set-ooc-meta-info or create-command-report.

#### What you expected to happen
When a new tgui_input_text() is called, it should NOT inherit the previous tgui_input_text()'s contents and instead use default value given in code, be it null or some sort of string.

#### What actually happened
It should populate the boxes with the default values.

#### Steps to reproduce
- As player, use set-ooc-meta-info or as staff, use create-command-report
- Change the text in the first popup with TGUI input framework enabled
- Observe as later inputs use the contents of the first popup rather than the default text value.

#### Code Revision
Last commit: 2faf67c: tweak: Modifies ahelps & mhelps and pms to allow multiline entry (#15828) …

**Comment by Runa-Dacino** [comment]
Testing some code variations of multiple calls.

### Case where default values is null, and we do not save the output to a variable:
`/client/verb/testing_tgui_text_input()
	set name = "TESTING TEXT INPUT"
	set category = "Debug"
	set desc = "meh"

	if(tgui_input_text(usr, "test 1 input", "testing", null))
		to_chat(usr, "boo!")
	if(tgui_input_text(usr, "test 2 input", "testing", null))
		to_chat(usr, "baa!")
	if(tgui_input_text(usr, "test 3 input", "testing", null))
		to_chat(usr, "bee!")`

**Result:** inputting "asdr" into input 1 is inherited by 2 and 3

### Case where default value of 1 is "1", rest null (same code), not saving var, pressing enter blindly:
**Result:** inputs 2 and 3 are overriden with "1" from input 1

### Case where default value of 2 is "null", rest null (same code), not saving var, pressing enter blindly:
**Result:** inputs 2 and 3 are overriden with null from input 1

### Case where we save the user input to a var
`/client/verb/testing_tgui_text_input()
	set name = "TESTING TEXT INPUT"
	set category = "Debug"
	set desc = "meh"

	var/a = tgui_input_text(usr, "test 1 input", "testing", null)
	to_chat(usr, "a is [a]")
	var/b = tgui_input_text(usr, "test 2 input", "testing", null)
	to_chat(usr, "b is [b]")
	var/c = tgui_input_text(usr, "test 3 input", "testing", null)
	to_chat(usr, "c is [c]")`
**Result:** inputs 2 and 3 are overriden with null from input 1


### Case where default value of 1 is "1", rest null (same code),  pressing enter blindly:
**Result:** inputs 2 and 3 are overriden with "1" from input 1

### Case where default value of 2 is "null", rest null (same code), pressing enter blindly:
**Result:** inputs 2 and 3 are overriden with null from input 1


@Kashargul I'm feeling like the bug might be with how TGUI handles states or sth.

**Comment by Runa-Dacino** [comment]
https://stackoverflow.com/questions/68704518/input-fields-inherits-value-from-past-input-fields-when-changing-state

this seems to be relevant

**Comment by Kashargul** [comment]
I don't think I ever say TG use more than one input at a time. So unlikely they noticed. So it seems like they never passed the title as a key to the input itself. Something we likely need to do here.
