### ISSUE TITLE
[GENERAL] "Set OOC Metainfo" verb nukes likes/dislikes sometimes

### ISSUE THREAD

**Issue by nullspace-industries** [VOREStation/VOREStation#15830]
#### Brief description of the bug
Using the "Set OOC Metainfo" verb in-round causes the likes and dislikes to populate with the text you set in the first step; hitting the X on the window wipes your likes or dislikes respectively.

#### What you expected to happen
Likes and dislikes to remain unchanged when the popup for them was closed, while still changing the section 1 notes.

#### What actually happened
Likes and dislikes were set to blank.

#### Steps to reproduce
- Be playing the round.
- Go to the OOC verb picker tab and select "Set OOC Metainfo".
- Make your changes to the first section and hit Confirm. The next box is now populated with the contents of the first section.
- Hit the X in the corner of the input box. The next box is also populated with the contents of the first.
- Hit the X in the corner of the remaining input box. Your likes and dislikes are now blank. The character setup version was briefly affected, but then reverted a minute or so later when I checked again.

#### Code Revision
- Server revision: B:release D:
Commit: [7b9eccb08518bd2c52b1467439defb2e084345b6](https://github.com/VOREStation/VOREStation/commit/7b9eccb08518bd2c52b1467439defb2e084345b6)

**Comment by Kashargul** [comment]
I'll take a look later, entering empty text should allow to clear it, but I've to check what the window actually returns on pressing the x to see if that's possible or if it needs to be handled the same as in the menu where one needs to type !clear to clear it.

**Comment by Runa-Dacino** [comment]
@Kashargul this is a general issue with tgui_text_input() as I reported here (now): https://github.com/VOREStation/VOREStation/issues/15831

**Comment by Runa-Dacino** [comment]
Yeah, tested in a random verb I wrote for testing purposes and the issue isn't with OOC metainfo. It's likely with how TGUI handles having the same window called multiple times in a single procedure.

**Comment by Runa-Dacino** [comment]
https://stackoverflow.com/questions/68704518/input-fields-inherits-value-from-past-input-fields-when-changing-state

Might be due to this?
