### ISSUE TITLE
Changing species resets preferences

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1587]
#### Brief description of the issue
Selecting Custom Species removes a LOT of options.

#### What you expected to happen
Not to lose a decent chunk of customization that I had to memorize and re-make when converting characters into custom species.

#### What actually happened
I lost hair, hair color, all markings, and all secondary languages.

#### Steps to reproduce
- Set hair to not-bald
- Set hair color to not-black
- Pick a marking
- Pick a secondary language
- Pretend this character was previously built this way
- Then change them to custom species and see ALL of these be lost.

#### Code Revision
- 9089470c68478ede01ef504a10714d125a5e796f
 
#### Anything else you may wish to add:
- N/A

**Comment by Arokha** [comment]
That's not unique to custom species... that's what happens whenever you change ANY species. It picks random hairstyles and whatnot.

**Comment by Vorrarkul** [comment]
While true, it does make switching to custom tedious- and people who don't realize what it does can lose a decent chunk of customization without noticing for a bit. Is there any way this can be remedied?

**Comment by SpadesNeil** [comment]
Probably, but this is only going to affect people who are using custom species for the first time who previously just used other species that were renamed. It's really not worth fixing imho.
