### ISSUE TITLE
[GENERAL] 

### ISSUE THREAD

**Issue by Ctrz458** [VOREStation/VOREStation#15880]
#### Brief description of the bug
MEKA V2 Service vore belly sprite doesn't appear when someone is swallowed with the "brew belly" module while **playing as an AI** in an AI shell.

#### What you expected to happen
To use the brew belly module on someone then have the sprite automatically update to reflect that.

#### What actually happened
Target was consumed, but the sprite did not update. Updating sprite by resting/unresting didn't seem to have any impact. Releasing and reconsuming the target didn't have any impact. Consumed while resting then stood up had same result.  Using robotnom verb had the same result.

#### Steps to reproduce
1) Spawn as AI
2) Enter shell
3) Set to Service, MEKA v2
4) Use the "Brew belly" module on someone

#### Code Revision
 Server revision: B:release D:
Commit: [6852e86824f89d43cf9c56c5135ba6968aef2809](https://github.com/VOREStation/VOREStation/commit/6852e86824f89d43cf9c56c5135ba6968aef2809)

#### Anything else you may wish to add:
Confirmed that what at least APPEARS to be a belly sprite exists, though haven't confirmed if there's any actual code behind it to use it. Could also be mistaken on what this is, my b if that's the case.
https://cdn.discordapp.com/attachments/1213035221604106240/1223062258465378324/image.png?ex=66187c7d&is=6606077d&hm=6adca1a5c10832de2e10f7907ba6071e4768de3c39130123c18c6595976f276c&
Reiterating that this bug was noticed in an AI shell, don't know if this has any significance but it sticks out as a potential oddity.

**Comment by Kashargul** [comment]
Did you make sure that the settings in the vorepanel were set to Sleeper or Both? As well as that the size multipliers were not set to 0?

**Comment by Ctrz458** [comment]
> Did you make sure that the settings in the vorepanel were set to Sleeper or Both? As well as that the size multipliers were not set to 0?

Still in round at the time of the reply, went in and checked. Was originally set to all defaults, "Sleeper, 1, 1, 1". Tried fiddling with it and didn't get any kind of response. Still in round now, and can try more.

**Comment by Ctrz458** [comment]
Just as a quick update - Will be trying just random combinations of settings, numbers, positions, etc and looking for something to specifically work. So far doing it has gotten no results. If you have a specific situation/setting you want me to try, let me know and I'll do it for as long as I'm on.

**Comment by Ctrz458** [comment]
Final update - Tried quite a few combos and got no positive result. Will also say that AI shells in general give a lot of grief when poking at vore panel settings, so that might have something to do with it.

**Comment by Kashargul** [comment]
Sadly I can't test right now, but from the looks, all the service ones had their sprite disabled even though available in file.
