### ISSUE TITLE
Vore Panel Options and AI Shells

### ISSUE THREAD

**Issue by Ctrz458** [VOREStation/VOREStation#15883]
Whenever swapping between/into AI shells vore panel options are wiped to default. 

#### What you expected to happen
When swapping to an AI shell for the vore panel options to remain the same.

#### What actually happened
When swapping to an AI shell the vore panel options are set to all defaults and wiped. Saves independently of slot's vore panel options, and fortunately remains even after leaving/repossessing the shell.

#### Steps to reproduce
1) Log in as AI - Have vore panel options preset in the slot
2) Control a shell
3) Check vore panel

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: [6852e86824f89d43cf9c56c5135ba6968aef2809](https://github.com/VOREStation/VOREStation/commit/6852e86824f89d43cf9c56c5135ba6968aef2809)

#### Anything else you may wish to add:
Wasn't sure if this was much worth a post, as I  imagine swapping between mobs can cause all sorts of issues. Add AI nonsense ontop and it's just a mess I'm sure. With the lack of import options it makes it a pain for bellies for shells, but they fortunately will remain saved for the round.

**Comment by Kashargul** [comment]
Reload preferences from slot works as a workaround
