### ISSUE TITLE
Replace obnoxious fucking Vote alert.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#159]
#### Brief description of the issue
The vote sound is horrible.

#### What you expected to happen
A gentle ping to tell me there's a vote that doesn't give me a heart attack.

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/19507867/15450883/9831706e-1f78-11e6-8b6a-7407633d397b.png)

#### Steps to reproduce
Trigger a vote.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
It's just a sounnndddd.

**Comment by SpadesNeil** [comment]
Players seem to universally hate it.

**Comment by Cameron653** [comment]
Here's the line in question for the alarm sound:
https://github.com/VOREStation/VOREStation/blob/454cc25cba9d3de5a0a99b7e5586ed34790d4aed/code/controllers/voting.dm#L248

It's set to volume 50 currently.

**Comment by SpadesNeil** [comment]
It's the very sound that people despise. Not the volume.
