### ISSUE TITLE
Character Directory no Worky

### ISSUE THREAD

**Issue by Rick4242** [VOREStation/VOREStation#15939]
#### Brief description of the bug 
It just doesn't.

#### What you expected to happen
Character Directory button to open the character directory window

#### What actually happened
I clicked the button, it opens a white window for a second (I assume it's trying to load), and then closes itself

#### Steps to reproduce
- Click 'Character Directory' button
- see results

#### Code Revision
- Server revision: B:release D:
Commit: da8c2d7a4322ad7d80ceec528623aee5b35c4536

**Comment by Rick4242** [comment]
This happened when I had updated my client to 515 for the record

**Comment by Kashargul** [comment]
Not a bug. 514 cache files are not compatible with 515. Clear your cache.

**Comment by Rick4242** [comment]
Cache has been cleared, can confirm this fixes it

**Comment by Kashargul** [comment]
> Afraid it doesn't, entirely. I cleared my cache after moving to 515, and it worked. But then after rejoining later today, the character directory pops open a white window and then immediately closes again. Even clearing my cache again doesn't fix it.
> 
> Ed: Crew Manifest and Character Setup also refused to do anything but whitescreen.

Make sure you are on the latest 515 version
Clear byond cache
Clear IE cache
reboot your system

Try again and see if the error returns

**Comment by HiddenName1702** [comment]
> > Afraid it doesn't, entirely. I cleared my cache after moving to 515, and it worked. But then after rejoining later today, the character directory pops open a white window and then immediately closes again. Even clearing my cache again doesn't fix it.
> > Ed: Crew Manifest and Character Setup also refused to do anything but whitescreen.
> 
> Make sure you are on the latest 515 version Clear byond cache Clear IE cache reboot your system
> 
> Try again and see if the error returns

I followed these steps and still when I load VS, Character directory whitescreens and closes after a few seconds.

**Comment by Kashargul** [comment]
> > > Afraid it doesn't, entirely. I cleared my cache after moving to 515, and it worked. But then after rejoining later today, the character directory pops open a white window and then immediately closes again. Even clearing my cache again doesn't fix it.
> > > Ed: Crew Manifest and Character Setup also refused to do anything but whitescreen.
> > 
> > 
> > Make sure you are on the latest 515 version Clear byond cache Clear IE cache reboot your system
> > Try again and see if the error returns
> 
> I followed these steps and still when I load VS, Character directory whitescreens and closes after a few seconds.

This is quite strange as we didn't have those issues downstream, are you running multiple byond versions by chance?

**Comment by HiddenName1702** [comment]
> > > > Afraid it doesn't, entirely. I cleared my cache after moving to 515, and it worked. But then after rejoining later today, the character directory pops open a white window and then immediately closes again. Even clearing my cache again doesn't fix it.
> > > > Ed: Crew Manifest and Character Setup also refused to do anything but whitescreen.
> > > 
> > > 
> > > Make sure you are on the latest 515 version Clear byond cache Clear IE cache reboot your system
> > > Try again and see if the error returns
> > 
> > 
> > I followed these steps and still when I load VS, Character directory whitescreens and closes after a few seconds.
> 
> This is quite strange as we didn't have those issues downstream, are you running multiple byond versions by chance?

Loaded it up this morning and the problem is gone. I don't know what changed but it's fixed now.
