### ISSUE TITLE
[UI] Persistent text items breaking the chat window

### ISSUE THREAD

**Issue by SatinIsle** [VOREStation/VOREStation#15956]
#### Brief description of the bug
Examining a sticky note, or a paper that is on a notice board, from a previous shift causes the text on the item to take over the chat window without any way to back out.
These items can not be found in the right click list of items on a turf.

NOTE: This only applies to items persistent from the previous shift and NOT to ones created on the same shift.

#### What you expected to happen
For a pop out window to appear just like examining the same items created on the same shift.

#### What actually happened
The text window was replaced with a white box containing the text from the item that was examined. There is no way to remove this box except for using the Fix Chat verb.

#### Steps to reproduce
- Examine a sticky note or piece of paper that is persistent from a previous shift.
- Right click on the turf containg the item to see that it is not displayed there.

#### Code Revision
- Server revision: B:release D:
Commit: [9219da9919fdccbb61484a6ae55b50ac56abef6f](https://github.com/VOREStation/VOREStation/commit/9219da9919fdccbb61484a6ae55b50ac56abef6f)
 

#### Anything else you may wish to add:
![image](https://github.com/VOREStation/VOREStation/assets/98125273/2310722f-8035-4e22-8a97-fd84f077859a)
![image](https://github.com/VOREStation/VOREStation/assets/98125273/84cba8d1-91c2-45e2-ac66-03a1d485ffee)

**Comment by Kashargul** [comment]
duplicate #15657

**Comment by Kashargul** [comment]
Could you get me the file paths of those persistent notes?
