### ISSUE TITLE
Xenochimera Hairs

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1596]
#### Brief description of the issue
Xenochimera don't have access to all of the hair's other species get [outside of Tesh which isn't sprited right for them anyway]

#### What you expected to happen
To have access to the nicer Tajara Hairs or even Skrell and Vulpkanin hairs, along with unathi's
Only have access to the base ones and none of the ones that have been added, 

#### What actually happened
Only have access to the base ones and none of the ones that have been added, 

#### Steps to reproduce
- (Step 1)Be Xenochimera
- (Step 2) Try to choose a nicer hairstyle or expect to find Skrell hairs
- (and so on)Cry

#### Code Revision
- [Couldn't find due to https://gyazo.com/85a7148136c95832d50f2e1b6935b9b0 ]
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
Remind me to do this when I update the female body sprites.
