### ISSUE TITLE
[UI] Brig timer buttons have wrong measurements

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#15988]
#### Brief description of the bug
Brig timers display completely wrong information.
The timer buttons are as follow:
- 00:00:06
- 00:00:30
- 00:01:00
One would assume these add 6 seconds, 30 seconds and 1 minute, however, they actually add 1 minute, 5 minutes and 10 minutes.

#### What you expected to happen
The timers to add a comprehensible amount of time, maybe what it says on them.

#### What actually happened
Timer buttons make no sense.
They seem to be trying to say 60 seconds, 300 seconds and 10 minutes respectively, but instead they are missing a 0 at the right on each button. (Also wrong units for the first two, should be minutes, not seconds)

#### Steps to reproduce
- Locate cell timer
- Press button, add time.
- Press Start
- Watch as sprite indicates a completely different time.

#### Anything else you may wish to add:
Picture of what shows up when pressing each button
![timerstuff](https://github.com/VOREStation/VOREStation/assets/51209769/d0dcaa75-0ad5-468c-a980-7326839842f5)

**Comment by nullspace-industries** [comment]
Noting: this may be linked to something I forgot to report a while back (and isn't fresh enough in my mind to make one now) regarding the timer bomb component. One "second" on its timer equaled about 10 seconds. Might be something to do with TGUI messing up rendering the true times in its slider boxes? I vaguely remember clicking in the time input to enter a value manually and the number in there was higher than I was expecting, which suggests to me it's translating some under-the-hood number into friendly seconds and doing it wrong.

**Comment by Kashargul** [comment]
I'll take a look later this week
