### ISSUE TITLE
[GENERAL] Cleaning HUD shows up on cameras

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#15998]
#### Brief description of the bug
When seeing anything through cameras as a sec officer, dirt appears marked by the cleaning HUD icons.

#### What you expected to happen
Security to not have cleaning HUD in their cameras.

#### What actually happened
Cameras show the clean-vision power that only mighty janitors should see.

#### Steps to reproduce
- Find dirt.
- Look at area through cameras.
- Confusion.

#### Code Revision
[ce80f544b18d1664c817e2c80b7fef482e9745ed](https://github.com/VOREStation/VOREStation/commit/ce80f544b18d1664c817e2c80b7fef482e9745ed)
 

#### Anything else you may wish to add:
![dirt](https://github.com/VOREStation/VOREStation/assets/51209769/428cd63c-48a1-4fbe-a4cc-b946acc21dc5)

**Comment by Kashargul** [comment]
Not sure that's that easy to change with the icons being overlays of the objects and the camera view likely inheriting it from the displayed objects.
