### ISSUE TITLE
Protolathe contanes nagative meterial

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#160]
#### Brief description of the issue
I put fifty sheets of photon into the Phorolathe and come to find out it has a negative number of photon
#### What you expected to happen
I expected me putting in phoron would prompted me to make items 
#### What actually happened
I could not make anything with phoron do to it somehow being negative number 

#### Additional info:
Sadly seemed to be this way before i came along so I do not know what made this happen

**Comment by SpadesNeil** [comment]
You're supposed to put the issues under the headers. :P

Also this isn't enough to work on, or even begin to know where the bug is happening.

**Comment by Techtypes** [comment]
Sorry still new to this site and sadly do not know how or why it happened i just walked in and found it that way

**Comment by SpadesNeil** [comment]
This needs steps to reproduce before it can be tested.
