### ISSUE TITLE
Clown Whitelist

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1604]
#### Brief description of the issue
Applied for a clown character [with implied job whitelist added aswell] But never got it when it became a thing

#### What you expected to happen
To possibly be remembered and given it

#### What actually happened
Did not have it, much to dissapointment

#### Steps to reproduce
- (Step 1)Have Clown character
- (Step 2)Not get clown whitelist
- (and so on)

#### Code Revision
- Server revision thing is still broken
 
#### Anything else you may wish to add: http://forum.vore-station.net/viewtopic.php?f=46&t=473
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SilverTalismen** [comment]
Ah, Approval pending?

**Comment by SpadesNeil** [comment]
That tag is obsolete. Not sure why @Screemonster added it. We don't do approvals on Github anymore, and the forum post already has it approved.
