### ISSUE TITLE
[GENERAL] AI Shell Names Resetting After Custom Name

### ISSUE THREAD

**Issue by Ctrz458** [VOREStation/VOREStation#16055]
#### Brief description of the bug
After setting a custom name with the rename module, the name will reset to a "[AI NAME] shell ###" after the AI leaves and reinhabits the body.

#### What you expected to happen
For the shell name to stay the same.

#### What actually happened
Shell name resets after leaving then reentering the shell.

#### Steps to reproduce
- Rename AI shell with reclassification board, does not seem to matter if AI is in the shell at the time of the rename or not.
- Enter it as the AI

#### Code Revision
Server revision: B:release D:
Commit: [3428bf357b3b760b8f3c4c2014345e17d7614740](https://github.com/VOREStation/VOREStation/commit/3428bf357b3b760b8f3c4c2014345e17d7614740)
 

#### Anything else you may wish to add:
Believe this hasn't always been the case, I distinctly remember using the reclassification board to rename my shells something along the lines of VIVID-S(1 through however many numbers) and the name sticking, but I may be mistaken and just failed to notice in the past.

**Comment by Kashargul** [comment]
https://github.com/VOREStation/VOREStation/blob/8df58cfc75d6eccbe1dd2373bbd13e427c93bdee/code/modules/mob/living/silicon/robot/robot.dm#L250-L252

https://github.com/VOREStation/VOREStation/blob/8df58cfc75d6eccbe1dd2373bbd13e427c93bdee/code/modules/mob/living/silicon/robot/robot_remote_control.dm#L49-L51

https://github.com/VOREStation/VOREStation/blob/8df58cfc75d6eccbe1dd2373bbd13e427c93bdee/code/modules/mob/living/silicon/robot/robot_remote_control.dm#L89-L98

Always been the case it seems.
