### ISSUE TITLE
Global OOC cooldown timer

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#161]
I'd like to restrict OOC to a cooldown defined by the config file, defaulted to 30 seconds, to mitigate OOC spam. I deliberately want to make ongoing discussions inconvenient to discourage players from using global OOC for idle banter.

Admins bypass this for obvious reasons.

If the time is commented out in the config, the cooldown is disregarded.

Server Revision: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
I could go for this.

**Comment by Vae42** [comment]
I support this for global OOC, Great idea. I've never seen an ongoing conversation in global OOC and thought "wow that is really contributing to the game, and what an appropriate place for it!"

I would hope that it wouldn't restrict LOOC the same though? its hard to abuse LOOC to the point of annoying everyone like bluetext does.

**Comment by SpadesNeil** [comment]
Should be sent upstream.
