### ISSUE TITLE
[UI] Prosthetics Fabricator and Exosuit Fabricator Queues Not Working

### ISSUE THREAD

**Issue by Lewzharri** [VOREStation/VOREStation#16124]
#### Steps to reproduce
- Press the little + icon to add anything on the exosuit/prosthetics fabricator item lists to the queue.
- Attempt to press the start queue button.

**Comment by Kashargul** [comment]
I see the error, typescript didn't mark me the length variable as it likely interpreted them as keywords. Will PR a fix later.
