### ISSUE TITLE
[GENERAL] ChemMaster 3000 dispensing not working as expecting

### ISSUE THREAD

**Issue by SatinIsle** [VOREStation/VOREStation#16138]
On the ChemMaster 3000, when dispensing bottles or pills, the second window where it requests a name for the bottles now autofills with the number of bottles you have selected rather than the name. Submitting this does still give the default name thankfully and renaming it here still works fine.
Also, you can no longer press enter twice to quickly print two bottles with the default name as it does not automatically select the second window (naming) any more.

#### What you expected to happen
The name to be automatically filled and for the window to be selected so that you can immediately press enter to submit.

#### What actually happened
The name section is filled in with a number and the window is not automatically selected.

#### Steps to reproduce
- Put a beaker of 120u of a chemical in the ChemMaster.
- Move all to the buffer.
- Attempt to create multiple bottles.

#### Code Revision
- Server revision: B:release D:
Commit: [5e6b86c9408a690f6230777923799e7f73dc251f](https://github.com/VOREStation/VOREStation/commit/5e6b86c9408a690f6230777923799e7f73dc251f)
 

#### Anything else you may wish to add:
![image](https://github.com/user-attachments/assets/67baaee8-490e-4c4a-b6ec-9860ed73e470)

**Comment by Kashargul** [comment]
Assign it to me after my trip in 2 weeks

**Comment by Kashargul** [comment]
Strange, modal input wasn't touched
