### ISSUE TITLE
[UI] TGUI Input boxes fail to return focus to the game.

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#16140]
#### Brief description of the bug
When using TGUI input framework, upon sending a message, sometimes the game won't get the focus back, forcing you to click on it to continue doing things.

#### What you expected to happen
For me to send a message and be able to move right away.

#### What actually happened
Send message on radio. Can't move, notice the VOREstation at the top is grey.

#### Steps to reproduce
- Set TGUI Input Framework to enabled in the setup -> Global
- Try sending several messages, with say/me/whisper/subtle. (This may take a while, it is random, pressing enter and T rapidly is the fastest way.)
- Eventually focus won't be returned to the game.

#### Code Revision
- Commit: [5e6b86c9408a690f6230777923799e7f73dc251f](https://github.com/VOREStation/VOREStation/commit/5e6b86c9408a690f6230777923799e7f73dc251f)
 

#### Anything else you may wish to add:
- This seems to be happening after last update, which included https://github.com/VOREStation/VOREStation/pull/16128 , unsure if is related or not.

**Comment by Kashargul** [comment]
Are say, me, whisper and subtle even using tgui inputs? If so, is it modal imputs? If reporting UI issues, always attach screenshots of the effected elements.

**Comment by TheToaster98** [comment]
> Are say, me, whisper and subtle even using tgui inputs? If so, is it modal imputs? If reporting UI issues, always attach screenshots of the effected elements.

They are as long as they are enabled as said above: _TGUI Input Framework: Enabled_
![Screenshot TGUI](https://github.com/user-attachments/assets/738648b8-2f46-4154-a592-3e2dc1d21414)

I will also add a gif to show the intended behaviour (With TGUI Input off)
![TGUIOFF](https://github.com/user-attachments/assets/8c2a320a-421a-4a5f-9957-c85ac510a99b)

And a gif showing the current behaviour (TGUI Input on)
![TGUION](https://github.com/user-attachments/assets/8af392d2-4e19-462e-90de-282d6a3b8b65)


As seen, focus comes comes back to the main game window when the inputs close on the first one, but does not when input is on.

As for the "modal inputs" part, I am not sure what you mean.

**Comment by Kashargul** [comment]
I'll give it a look after my trip in 2 weeks.

**Comment by Kashargul** [comment]
It's indeed modal inputs as well. So might be related to the other issue

**Comment by Kashargul** [comment]
happens on all tgui elements. Need to look into it.
