### ISSUE TITLE
Plastic Ashtray

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1619]
#### Brief description of the issue
It can only hold ONE Cigarette Butt

#### What you expected to happen
It could hold atleast a pack of them

#### What actually happened

One filled it up entirely, leading to me having to dump it
#### Steps to reproduce
- (Step 1)Get the Ashtray from the loadout
- (Step 2)Smoke a single cigarette
- (and so on)Put it in and fill the Ashtray

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/e3fd95976360df1d3b7a4e26fed78fd78d800746
 
#### Anything else you may wish to add:
- https://gyazo.com/3c3c304c9eef6b68f1a9f2dfa9ebddc8

**Comment by SpadesNeil** [comment]
This bug only occurs with the loadout trays, IIRC. Try testing it.

As for server revision we'll just say it's this:

https://github.com/VOREStation/VOREStation/commit/e3fd95976360df1d3b7a4e26fed78fd78d800746

**Comment by SilverTalismen** [comment]
WellI have tested it, Camilla smokes and I take the tray as on the new map I haven't seen a single Ashtray, It only holds one Cigarette butt

**Comment by SpadesNeil** [comment]
Still a bug?

**Comment by SilverTalismen** [comment]
Yes still a bug
