### ISSUE TITLE
[GENERAL] Schrodinger's Dragon

### ISSUE THREAD

**Issue by Anonogon** [VOREStation/VOREStation#16209]
Brief description of the bug: Large Dragons' "dead" sprite stays after being revived with the Commercial De-necrotizer

What you expected to happen: Sprite would not have bones left over.

What actually happened: Sprite has bones left over.

 Steps to reproduce:
- Step 1: Dead Dragon
- Step 2: Make Dragon not dead (Commercial De-necrotizer)
- Step 3: Observe Schrodinger's dragon
![schrodingerdragon](https://github.com/user-attachments/assets/e1325146-9c99-453e-87a2-8fa755bc1293)

**Comment by Kashargul** [comment]
https://github.com/VOREStation/VOREStation/blob/7dad05c1eeba151cc6efd49579c225bf50d8649e/code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm#L342-L347

well, this is never ever reset again after the dragon died once
