### ISSUE TITLE
Xenoarch has lockers for 3 but equipment for 2

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#1624]
#### Brief description of the issue
There is 3 xenoarch lockers but only 2 xenoarch equipment lockers

#### What you expected to happen
3 of each locker

#### What actually happened
2 and 3

#### Steps to reproduce
N/A
https://gyazo.com/f9f8c1117bf89ef0f07f84821b6a3d96
#### Code Revision
release - 4fa3d2e8bcccc2714dbfcce87df926807029899c 
 
#### Anything else you may wish to add:
- https://gyazo.com/f9f8c1117bf89ef0f07f84821b6a3d96 Tables could be replaced with a locker and an extra field generator

Suggested look: https://gyazo.com/d1667a901dee5165d8df046b8ec10f1f

**Comment by Cameron653** [comment]
No idea how "Old map" got in there somehow.

**Comment by SpadesNeil** [comment]
Was this fixed?

**Comment by Cameron653** [comment]
As far as I know, no.
