### ISSUE TITLE
Hardlight pretty useless.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#1625]
#### Brief description of the issue
Hardlight is not so useful for anything besides the nomming, meaning the AI can't really participate in dare dice and the like despite having a hard light function, due to being unable to use dice.

#### What you expected to happen
To be able to use the hardlight beyond nomming.

#### What actually happened
Can't use it for anything but nomming.

#### Steps to reproduce
- (Step 1) Be AI
- (Step 2) try to roll dice to write.
- (and so on)

#### Code Revision
Server revision: release - 
4fa3d2e8bcccc2714dbfcce87df926807029899c 
 
#### Anything else you may wish to add:
It would be rather nice to have something added to allow them to do something besides stare and have a useless hardlight function 99% of the time. If anyone has anything to add please say so, would be nice to see what others have to say and think.

**Comment by Arokha** [comment]
For some background: The AI can't physically interact with anything, as their body is the AI core. Even the hologram, and the hardlight version, are simply an object that slides around to follow the center of the screen. It's not a mob, and as such, can't interact with anything.

Whenever you click on things as the AI, you click on them FROM the AI core. As in, if you have an object that just tells you how far away you are when you click it, even when you're right over it with your screen and click it as the AI, it'll tell you 387 or whatever, however far the AI core is from it.

There is a special proc on computers (most of them), machines (almost all of them) that is called when the AI clicks them that does special stuff to ignore the distance limits usually associated with using computers. This proc would need to be added to every physical object in the game, which, while 'possible', is a little unweildy and will likely result in ~mysterious happenings~.

If that were done, then the AI could click on things, but to what end? The AI doesn't have hands, or any inventory slots or anything like that. So they can't pick up and hold things. The only way they'd be able to do this is if the AI could somehow dump themselves into an actual bipedal mob, which is "doable" if you want an actual hardlight 'mob', but then there are other considerations that come with it being a mob. What does it do when someone hits it with an object, and how do we code that in a sensible way? If it's going to have normal inventory slots, then it's probably going to be a subtype of human, but that means we need to make sure that life() and breathing and such don't affect it. There's a type of mob for that already, buuuut... it'd require more work to make it usable as a normal living mob thing.

**Comment by SpadesNeil** [comment]
Marking as won't add. The AI having more interactions also opens up a can of worms of am omnipresent being who can do almost anything on the station already. I don't need them also able to handle tools.
