### ISSUE TITLE
Excavation Suit + Hood from Xenoarch doesn't render on Teshari

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1629]
#### Brief description of the issue
The excavation suit doesn't render on Teshari when equipped, yet it hides the tail and ears.

#### What you expected to happen
When suit and hood were equipped, icon was expected to show Teshari in Teshari-sized excavation suit and hood

#### What actually happened
When suit and hood were equipped, icon was Teshari, with hidden tail and ears. No indication it was actually being worn.

#### Steps to reproduce
1. Play as a Teshari.
2. Wear Excavation Suit and Excavation Hood.

#### Code Revision
Server revision: release - 4fa3d2e8bcccc2714dbfcce87df926807029899c 
 
#### Anything else you may wish to add:
Before: 
![image](https://user-images.githubusercontent.com/10330701/26848550-c13071e8-4af8-11e7-9f99-e5a1d3ef3faa.png)

After:
![image](https://user-images.githubusercontent.com/10330701/26848566-d467d526-4af8-11e7-993b-893cefcd44bb.png)

**Comment by Arokha** [comment]
Probably missing sprites for Teshari.

**Comment by SpadesNeil** [comment]
jesus christ how horrifying

**Comment by SpadesNeil** [comment]
Was this ever fixed?
