### ISSUE TITLE
Humans use skin tones and not RGB?

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#163]
#### Brief description of the issue
We used to have RGB support for humans. We no longer do.

#### What you expected to happen
RGB colors for humans so I can be green for all I care.

#### What actually happened
I get skin tones.

#### Steps to reproduce
Open character setup. Note your options.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073
 - **Anything else you may wish to add** We should really have a meta-human species, and leave normal humans alone, because the normal human icons work fine for normal humans. The meta-human species could be possible to be set to any skin color.

**Comment by SpadesNeil** [comment]
Re-opening because the issue is not actually resolved.

**Comment by Arokha** [comment]
Need someone to make super dark human sprites then for the coloring.

**Comment by SpadesNeil** [comment]
@Screemonster !!!

**Comment by Screemonster** [comment]
I'm going to be going to Confuzzled later in the week so unless you're okay waiting until the 3rd of June at the earliest you might want to assign someone else.

**Comment by SpadesNeil** [comment]
Fuck.

**Comment by SpadesNeil** [comment]
@JoanRisu ?

**Comment by JoanRisu** [comment]
I have finals this week so this isn't getting fixed any time soon.

**Comment by SpadesNeil** [comment]
Can't we just port in the old icons, and snowflake code it to use the old coloring system?

**Comment by SpadesNeil** [comment]
@Cameron653 @Arokha @Leshana How did we port the old coloring system for our custom species in the old code? We need to do it again here.

**Comment by SpadesNeil** [comment]
Fuckit
