### ISSUE TITLE
[GENERAL] Station Alert Console won't stop clicking

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#16304]
#### Brief description of the bug
Station Alert Consoles keep making noises as if new alerts were popping up, but nothing is actually happening.

#### What you expected to happen
The console to remain silent and not demand my attention if nothing is going on.

#### What actually happened
The Station Alert Console keeps clicking, over, and over, and over... despite no new alerts happening.

#### Steps to reproduce
- Go to a location with a Station Alert Console (like the bridge)
- Wait
- Delight yourself with the unending click noise over and over. Puppy girls rabid.

#### Code Revision
[06531426c09e4a04e589f98b5045417743031032](https://github.com/VOREStation/VOREStation/commit/06531426c09e4a04e589f98b5045417743031032)

**Comment by Kashargul** [comment]
Likely the turning on sound of the update icon parent which gets called along on the proc
