### ISSUE TITLE
Detective Locker

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#1637]
#### Brief description of the issue
Single .44 rubber bullets spawn instead of speedloaders for the .44. 

#### What you expected to happen
For two spare .44 Rubber speedloaders to spawn, for the detective's Consul. 

#### What actually happened
Two bullet casings spawned in the locker instead. 

#### Steps to reproduce
- Be a detective. 
- Look in your equipment closet. 
- Not get spare speedloaders. 

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- Location is the detective's office in security, both lockers.

**Comment by Dhaeleena** [comment]
I think this is because the bullet paths got redefined or something on the last update
@Arokha @Leshana 
I saw something about it on the changelog

**Comment by SpadesNeil** [comment]
Yea that sounds like what happened exactly.
