### ISSUE TITLE
BSA button doesn't show logs.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1640]
#### Brief description of the issue
Use the BSA after someone uses illegal comms, no admin logs show up.

#### What you expected to happen
Admin logs to show up after killing someone.

#### What actually happened
No admin logs showed up.

#### Steps to reproduce
- (Step 1)Get message
- (Step 2)Hit BSA
- (Step 3)Get no logs.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Yoshax** [comment]
There's no logs for replying to messages either, more importantly. So nobody has any idea who has replied to what, meaning shit gets fucked up.

**Comment by SpadesNeil** [comment]
Polaris uses BSA, yes?
