### ISSUE TITLE
[UI] Timer UI is absurdly large, and doesn't seem to work with chemical grenades

### ISSUE THREAD

**Issue by peeesh** [VOREStation/VOREStation#16409]
Timer has a LOT of empty space. Time input is bizarre. Adding a timer/igniter assembly to a grenade casing seems to default to ten seconds, regardless of what is input in the assembly itself.

Separated from the grenade casing, the assembly seems to work, but adds an extra second (since I guess zero counts)

At the very least, the timer should work. UI could also be way better.

I wanted to make a cleaning grenade. It took ten seconds to detonate no matter what. Uses a timer/igniter assembly, since timers alone don't seem to be allowed to be attached (which makes sense I guess)

#### Steps to reproduce
Just open the timer UI.
 
![image](https://github.com/user-attachments/assets/84c86012-37c4-4f11-9c9e-130f1b0924cd)

**Comment by Kashargul** [comment]
Not too sure what broke it this time, yet there were a few larger code changes lately
