### ISSUE TITLE
[UI] New Integrated Circuit Breadboard 'bluescreens' when connecting nodes to themselves

### ISSUE THREAD

**Issue by Zulban48** [VOREStation/VOREStation#16447]
#### Expected:
Nodes to simply not be able to connect to themselves, just as input nodes cannot be connected to other input nodes.

#### What actually happened:
Clicking a node, or otherwise connecting a node to itself causes the breadboard to bluescreen.

#### Steps to reproduce
- Obtain an Integrated Circuit Printer and insert some steel sheets into it. Print any kind of assembly and open it with a crowbar.
- Next print any circuit with an input and/or output node(s), a simple 'button' from the Input tab will do fine.
- Insert the circuit into the assembly. This should automatically open the breadboard for that assembly.
- The colored circles are the nodes. Simply click and drag or single click a node onto itself and the breadboard window will turn into a bluescreen as shown in the screenshot.
- Side note: a circuit wirer or multitool is not required to be in your hand to do this unlike the 'basic editor'

#### Code Revision
- Server revision: B:release D:
Commit: [7c058d28e4a152a39c25935756f38197f92ff771](https://github.com/VOREStation/VOREStation/commit/7c058d28e4a152a39c25935756f38197f92ff771)
 

#### Anything else you may wish to add:
- ![image](https://github.com/user-attachments/assets/2a8a3b20-d2b4-43b0-8c05-57434c02001d)
- A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/VOREStation/VOREStation. Thank you for your cooperation. 
TypeError: Invalid operand to 'in': Object expected
   at w (http://127.0.0.1:58191/tgui.bundle.js:363:194725)
   at xe.shouldComponentUpdate (http://127.0.0.1:58191/tgui.bundle.js:275:285803)
   at Kd (http://127.0.0.1:58191/tgui.bundle.js:9:76566)
   at Gd (http://127.0.0.1:58191/tgui.bundle.js:9:84091)
   at qu (http://127.0.0.1:58191/tgui.bundle.js:9:127515)
   at Qf (http://127.0.0.1:58191/tgui.bundle.js:9:121956)
   at b0 (http://127.0.0.1:58191/tgui.bundle.js:9:121889)
   at Zu (http://127.0.0.1:58191/tgui.bundle.js:9:121737)
   at cf (http://127.0.0.1:58191/tgui.bundle.js:9:117702)
   at Yf (http://127.0.0.1:58191/tgui.bundle.js:9:118667)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"ozyton","interface":"ICAssembly","window":{"key":"[0x2026574]-main","size":null,"fancy":1,"locked":0}}

**Comment by ShadowLarkens** [comment]
Does this persist through closing the window and reopening it?

**Comment by Zulban48** [comment]
Sorry for the late reply, but closing the window and re-opening it fixes it, but wiring a node to itself will bluescreen it again. The only reason I'm reporting it is because I thought single-clicking a node would make a wire stick to the cursor, it wasn't until halfway through the report I realized I needed to click-and-drag to get things to work. I see it's been fixed anyhow so thanks for that.
