### ISSUE TITLE
HoS office hologram access and camera coverage is patchy.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1645]
#### Brief description of the issue
The holopad next to the HoS office is in direct LoS to the door, making it awkward for the AI to project a hologram in there. There's also no camera in the room itself either. Not sure if this is deliberate, but it means the AI can't access the air alarm in the office.

#### What you expected to happen
Either a holopad in the room itself, or the holopad to be placed somewhere the airlock doesn't obstruct LOS into the room.
The air alarm to be visible to the AI.

#### What actually happened
https://puu.sh/weQOK/3033ce8683.mp4

#### Steps to reproduce
- see video

#### Code Revision
- Server revision: release - 
7c649a0ae293cbd8ec94722515cf7dc1acb89bee 
 
#### Anything else you may wish to add:
-

**Comment by chaoko99** [comment]
Not only awkward, but the AI literally cannot hear things inside the room.

**Comment by DeepIndigo** [comment]
All the missing intercomms and lack of holopads only compounds this issue.

**Comment by SpadesNeil** [comment]
This appears to be deliberate. However, I don't think it's smart. The concern is you're worried about a criminal using cameras to spy on the HoS and attack when he's not there. Reality is few criminals even have access to cameras.

**Comment by chaoko99** [comment]
Okay. But the AI can't talk to the HoS in their office, unlike everyone else.
