### ISSUE TITLE
Alien vore mobs missing icons.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#166]
#### Brief description of the issue
THESE ICONS WEREN'T RE-ADDED. >:T

#### What you expected to happen
Mobs not to be invisible.

#### What actually happened
Invisible mobs.

#### Steps to reproduce
Spawn an alien drone or queen. Sentinel's probably broken too.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
Wha? I've spawned them and gotten eaten by them. Is there ONE type that's missing the icon? I think I spawned a sentinel? Maybe? I forget.

**Comment by Arokha** [comment]
vore/alien spawns fine, but not alien/sentinel and stuff.
