### ISSUE TITLE
Move slowly after being hurt and then healed

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#1670]
Brief description of the issue

You move slowly after being hurt and healed back up. Rejuvinate/healing naturally still makes you move slowly.
What you expected to happen

Get hurt, heal up, move normal
What actually happened

Get hurt, heal up, move slowly
Steps to reproduce

    (Step 1) Get hurt a lot
    (Step 2) Go into some shock
    (Step 3) Heal up
    (Step 4) Realize you're moving slowly

Code Revision

-release - 2eb09c4
Anything else you may wish to add:

Problem: shock_stage was stuck at 20, making it so they were permanently moving slowly. Changing it to 0 fixed it.
Admin rejuvinating sets traumatic_shock to 0, but not shock_stage. Traumatic_shock is set to 0 due to it being a combination of all your injuries.
Shock_stage seems to slowly go down 1 point at a time. It should go down all at once and be removed by an admin rejuvination.

This is also, presumably, present on Polaris.

####Code sections:
Where shock_stage makes you move slow
https://github.com/VOREStation/VOREStation/blob/86daf319f081f0d40a2577918156d9da11d2b10d/code/modules/mob/living/carbon/human/human_movement.dm#L61

Where shock_stage is added/removed
https://github.com/VOREStation/VOREStation/blob/f7c3ab5a8c21ce5ad94328c9fe2e56c7607fc2a4/code/modules/mob/living/carbon/human/life.dm#L1429-L1444

**Comment by Arokha** [comment]
This is because the revive proc, which needs a serious rework, does not set the two 'shock' variables to 0, and these affect your move speed. life() decreases them constantly but it can take several minutes for them to reach zero.

**Comment by Cameron653** [comment]
Yep. After some testing, it does go down for a while but until it goes away completely the person that has their shock_stage set to a value above 10 still moves extremely slowly with no cause.

It should probably have a "Your body aches from the damage you took earlier. You feel as though it'll pass in a few minutes..." message while it's removing their shock_stage.

**Comment by Screemonster** [comment]
shock _should_ come with its own periodic nagmessages about hurting unless they're broken somehow, but this is more of a bug with revive() than it is with shock_stage.
