### ISSUE TITLE
Broken ammo icons

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#168]
@Arokha how do I override icons again? I'm having that problem in a few places.

- [x] Battle Rifle ammo
- [x] Desert Eagle ammo

Server revision: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
icon is the inventory icon file
icon_state is the inventory iconstate in that file
icon_override is the on-mob icon icon file if it's different from the above
item_state is the on-mob icon-state in that file

... for MOST items. Not for all.

**Comment by Arokha** [comment]
Battle rifle is in custom_guns_vr.dm
