### ISSUE TITLE
NIF implants show as "unknown body" in Body Scanner

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1687]
#### Brief description of the issue
NIF implants show up as an "unknown body" in the body scanner, whereas other implants (e.g. backup implants) show up as what type of implant they are.

#### What you expected to happen
NIF implants would show as NIF implants specifically.

#### What actually happened
They showed up as "unknown body" in scanner, the same as bullet shrapnel would.

#### Steps to reproduce
1. Have a patient with a NIF installed
2. Put them in the scanner and look at it.

#### Code Revision
Server revision: release - 0cbf2c8c12e1984b1b38e9d94bc03472f68694c6 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/10330701/27007641-071dd4fa-4e52-11e7-8a7b-8bfcc19bf2f6.png)

**Comment by ArbyTheDragon** [comment]
I never saw this as a problem, more as a reason to ask if they have a NIF system. If this is 'fixed', it'd be more of a feature rather then a bugfix.

**Comment by SpadesNeil** [comment]
Not sure what severity to label this as. Looks purely cosmetic of a problem. Is it?

**Comment by KotetsuRedwood** [comment]
I'd probably say it's a bit more than just cosmetic. "Unknown body present" could mean anything from NIF to bullet shrapnel to some weird madman who implanted a knife in their head.

**Comment by SpadesNeil** [comment]
@Arokha know about this maybe?

**Comment by Cyantime** [comment]
Should have been closed by #1868, forgot to check if there was an issue when making the PR.
