### ISSUE TITLE
Cannot vent-crawl between Z-levels

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#1696]
#### Brief description of the issue
Cannot vent-crawl up or down.

#### What you expected to happen
To be able to crawl down the tether as a mouse/diona nymph

#### What actually happened
Slammed into pipe end, got called fat, joined a weight loss club, forgot that diona don't gain or lose weight.

#### Steps to reproduce
- (Step 1)Vent crawl to pipe end.
- (Step 2)Get your fat ass stuck in a pipe. (Break the pipe if you're Ace)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 
97b99f3dee4dd36acdd22991770e8c6c4d0ae67c 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I require more pipes.

**Comment by Arokha** [comment]
I mean. The tether is 100,000km. So not being able to ventcrawl it makes some sense there.

But I'm sure this is a general case thing where you can't ventcrawl up/down anywhere.

**Comment by Yoshax** [comment]
S-Snake Eater.
