### ISSUE TITLE
More Diona Shit

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#1699]
#### Brief description of the issue
Diona Nymphs get no visual effect when Absorbed.
Diona Nymphs crash when being consumed from being held.
Diona Gestalts that are race changed maintain their abilities (When race changed via vore system)
Diona Nymphs maintain abilities as well when race changed, but get no message informing them they are race changed.

#### What you expected to happen
To see the welding mask effect when absorbed as a nymph.
To not crash when ingested.
To not be able to do my best rendition of "I fall to pieces" when my race is altered.
To not be able to, as a full grown human, crawl into a god damn pipe.

#### What actually happened
In a scene. Was a nymph. Got ingested. Crashed. Came back. Got absorbed. Crashed. Came back. Had no welding mask effect to show absorbtion. Became a human after Gestalting again to continue the scene. Saw I still had abilities, clicked regenerate. Saw it still worked. Clicked Split. Became legion.

#### Steps to reproduce
- (Step 1)Get changed into another race as a Diona Gestalt-form.
- (Step 2)Click Split.
- (Step 3) Become Legion, and spread yourself for the great Gestalt in the sky.
- (Step 4) Get yelled at by the admins for spreading the word of our lord and savior, sky-tree.

#### Code Revision
Server revision: release - 
97b99f3dee4dd36acdd22991770e8c6c4d0ae67c 

#### Anything else you may wish to add:
Am I really the only Diona player? I humbly request a badge that says "OG DIONA 420 BLAZE IT"

**Comment by Arokha** [comment]
Nymphs are simple animals and it would require additonal checks in life() for the overlay which I don't really want to add. The ability thing... mmmmmmmmmmmmmmmmmmm. Not 100% sure how to resolve that. I guess strip off inherent_verbs from the mob when changing.

**Comment by SpadesNeil** [comment]
Was any of this ever fixed?
