### ISSUE TITLE
Thunderdome armor actually has no armor values.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#170]
#### Brief description of the issue
Thunderdome armor doesn't protect against shit.

#### What you expected to happen
It should protect against something to prologue fights.

#### What actually happened
I have to tediously explain an issue that's pretty straight forward.

#### Steps to reproduce
Right-click, view vars, search armor on thunderdome armor.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by nate657** [comment]
Already fixed it, got ya covered.
