### ISSUE TITLE
Backup Implants cannot be garbage collected

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#1719]
#### Brief description of the issue
`/obj/item/weapon/implant/backup was unable to be GC'd and was deleted`
#### What you expected to happen
qdel'd backup implants to garbage collect naturally.
#### What actually happened
The spawn()'d backup loop keeps a reference to itself forever.

A partial solution would be to add a `QDELETED(src)` check into the spawn loop.  However its only triggered every 5 minutes, so it would still hang around for awhile.  5 minutes is the same time as the SSgarbage queue, so it would solve this problem mostly.    But it would be nice to avoid the spawnloop entirely.

**Comment by Arokha** [comment]
Can we add implants to the transcore system so it processes them via a global list?

**Comment by Leshana** [comment]
Yeah, that sounds like a good way to do it.  Might be nice statistics to see all implants anyway.

**Comment by SpadesNeil** [comment]
Can't really decide what to make this priority since it's a performance issue.

**Comment by SpadesNeil** [comment]
Was this ever fixed?
