### ISSUE TITLE
Can't play Prometheans

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#172]
#### Brief description of the issue
You can select Prometheans in character creation, but attempting to join a round as one will result in a pop-up that says "Your current species, Promethean, is not available for play on the station."

#### What you expected to happen
To be able to select Promethean as my species and play on the station.

#### What actually happened
The aforementioned pop-up showed up and barred me from play.

#### Steps to reproduce
1. Create a character with Promethean as the species
2. Attempt to join
3. If you're not an admin, be locked out of play and get the above pop-up

#### Additional info:
 - **Server Revision**: 9d650c1abc9cf818c8fc4073 - 2016-05-21
849c30750d4ba1099d650c1abc9cf818c8fc4073
 - **Anything else you may wish to add**: N/A

**Comment by SpadesNeil** [comment]
@Arokha Resolved, I assume?

**Comment by Arokha** [comment]
It's resolved in a PR I've made but that shouldn't be merged yet. This will autoclose when it is.
