### ISSUE TITLE
Diona Whitelist [Missing]

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1722]
#### Brief description of the issue
Diona white list I applied for was lost somewhere in the moving of server codebases

#### What you expected to happen
To, hopefully, keep my Diona whitelest

#### What actually happened
It was gone after we switched to Polaris code awhile back

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- http://forum.vore-station.net/viewtopic.php?f=46&t=573&p=3732&hilit=SilverTalismen#p3732 The application.

**Comment by Cameron653** [comment]
I'll see about adding you to the whitelist.
