### ISSUE TITLE
Suggestion - GlassJars can hold micros

### ISSUE THREAD

**Issue by Avuds** [VOREStation/VOREStation#1724]
Not much to say tbh everything is in the title.

**Comment by Dhaeleena** [comment]
I want this

**Comment by Dorime** [comment]
Same ^

**Comment by chaoko99** [comment]
Probably not viable without a refactor of jarcode. (They check for mobtype...)

**Comment by Avuds** [comment]
This seems easy to do, you only need to add a size check to the glass jar and add the human species. The hard part is making the Icons Update in the jar..
