### ISSUE TITLE
Soul Catcher Emotes unseeable [To ghosts]

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1726]
#### Brief description of the issue
As a ghost, you can not see Soulcatcher RP as it goes on, even on top of the person holding someone's mind

#### What you expected to happen
To be able to see it like most subtle messages

#### What actually happened
Couldn't see it as the two involved seemingly sat there in silence for close to 20 minutes now

#### Steps to reproduce
- (Step 1)Be a ghost
- (Step 2)Watch someone get their mind ripped from their body into a soul catcher
- (and so on) Watch as you see none of the RP that occurs

#### Code Revision 74da4f2e4f04a6b74d7886b6305bbb3333a36947 
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
I kind of like that soulcatcher stuff is private. I wish that subtles were also not seeable by ghosts either, since, you know, it's used by people trying to be quiet and possibly somewhat private about what they are doing.

**Comment by Yoshax** [comment]
If you want to be private, you shouldn't be on a public server.

**Comment by Very-Soft** [comment]
That's a pretty poor argument though. It's like, you've got these things to pretend to be in private with with the dorms and with subtles and now the soulcatcher. But there's ways for folk who aren't involved and aren't admins to peek in on those first two things when they seem to be intended to give people a little privacy on this public server.

I don't really care all that much personally, but it seems to me that the soulcatcher stuff would be happening in a place that can't be seen. I wouldn't expect anyone who's not involved to be able to see it unless they were caught inside with whoever was in there. 

But again, that's just me.

**Comment by Very-Soft** [comment]
Like, I understand subtles being seeable by ghosts to some extent, as one might have been involved in a RP that continues after you're digested or whatever, it makes sense that you'd be able to see the aftermath.

But the soulcatcher is like, you're in there or you're not. The NIF's owner pointed at you as a ghost and said, 'youre out' and deleted you, or had you resleeved or whatnot.

I don't really see why ghosts would have a need to peek inside of there, as such.

**Comment by SpadesNeil** [comment]
Privacy in the server is simply never going to be completely feasible. Yosh's point stands.

That said I don't really see the point of fixing it if ghosts can't see subtle text. It still shows up in admin logs so that's all that matters.

Personally I'm opposed to soulcatchers existing at all.

**Comment by Yoshax** [comment]
In my opinion, subtle should be visible to ghosts, I never really realised it wasn't, I imagine that was just something that never really came up or was thought of. The server is a public environment and there's a whole bunch of reasons why someone might want to peek at someone else's RP. Several of them came up earlier today. It can help you find new ideas, ways to write things. general creative inspiration, what in what way someone might enjoy. And y'know, maybe someone would just enjoy reading it.

**Comment by Very-Soft** [comment]
No, ghosts can see subtles. I only brought them up as comparison. I understand why they are visible to ghosts, but in a number of instances I've been annoyed at ghosts commenting on what going on during or after an RP is over while writing in subtle when they hadn't been involved in the RP at any point.

Some people may like that, others do not. For me, it completely, immediately kills any kind of mood I might have been in. Luckily it's a very rare thing to happen. But I've also seen people come to me with certain expectations of how things will go based on what they've seen in subtles, which is frustrating and confusing.

But I understand a number of circumstances where ghosts being able to view subtles would be wanted, so while not my personal preference, I understand why subtles are view-able by your average ghost.

And I'm not saying complete privacy should be the goal of Soulcatcher, but when compared to subtles, there's not really a reason to make it viewable to ghosts. If someone was in the soulcatcher, and now is not, someone made a conscious action to take them out of what's going on in there. It's all 100% text based with no mechanics in the soulcatcher, so there's no real reason to remove someone from it except if you're done playing with them.

That's just my thoughts on it anyway.

**Comment by Yoshax** [comment]
If a ghost is commenting on what you're doing tell them to fuck off, or tell a staff-member. It's not really appropriate or appreciated.

**Comment by JoanRisu** [comment]
I rather this be the one private from ghosts thing on the station.

**Comment by SilverTalismen** [comment]
I understand, At the time I reported this as a possible bug, likely due to me as a ghost being used to watching scenes as they happen, mostly so I know what I would or wouldn't like in the future. This can be closed if anyone else has no issues with how this is right now.

**Comment by AeroWing** [comment]
I support Joan Risu and Very-Soft's opinion on this. I'd honestly say that it should remain private. The actions are no longer 'visible' per say and ghosts can't read minds of the players so it would make sense they can't see into a soulcatcher since it is purely within mental and electronic control. The important thing is that it is logged and viewable by the admins so I don't see anything that needs to be changed.
