### ISSUE TITLE
Add logging when items are put in the cryo store

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1730]
#### Brief description of the issue
People keep cryoing without putting their shit back. Currently, while it's possible to check the cryo consoles and VV for fingerprints, it's a pain to do so and can only be done while the round is ongoing, assuming some good samaritan didn't clean it up after the fact.

#### What you expected to happen
Some notification in the logs so we can grep that shit and find out who's doing it a lot and poke them.

#### What actually happened
If a shitton of job gear is missing, have to manually search every cryo console for the stuff, if that's even the reason it's missing and it hasn't been tossed down disposals or looted by greyshirts.

#### Steps to reproduce
- cryo with a bunch of guns and a hardsuit
- don't get caught despite it literally being in the rules to put that shit back
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Does the cryo tube actively tell players, "HEY GO RETURN YOUR SHIT" when they enter it?

**Comment by Screemonster** [comment]
Not yet. It doesn't actually check for people's stuff until they're actually removed. Adding something to the confirmation message to warn them that they should put their job gear back before leaving might be helpful. At least, it'll leave them without any excuses.

**Comment by SpadesNeil** [comment]
Let's add that warning before we continue banning players for breaking the rule, because the rule is pretty obscure to most players.
