### ISSUE TITLE
The magical tower of people

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#1736]
#### Brief description of the issue
You can walk on other people on z-levels below you to avoid falling. You can use this to do incredibly silly things.

#### What you expected to happen
To fall onto people.

#### What actually happened
Began human centipede. Became legion.

#### Steps to reproduce
- (Step 1) Have person on floor below you stand where you can -walk- onto them. Not rail hop. WALK.
- (Step 2) Step onto them
- (Step 3) Have them take one step in any direction.
- (Step 4) Step onto the space they stepped onto.
- (Step 5) Repeat and be the tower of babel(ing idiots)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 
74da4f2e4f04a6b74d7886b6305bbb3333a36947 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I demand more cookies.

**Comment by SpadesNeil** [comment]
I'm inclined to ask how you figured this out lol

**Comment by Screemonster** [comment]
![image](https://user-images.githubusercontent.com/14942479/27322424-080ec860-5596-11e7-801d-f91422deef49.png)

It's a videogame tradition.

**Comment by Rixunie** [comment]
Very carefully. I went ahead and ran my own instance of the server and just ass-spawned normal mobs below me and effectively made a bridge of people as well.

**Comment by Screemonster** [comment]
I _suspect_ it may be because it only performs the "do you fall" check when you _enter_ an open space tile. So when you step onto open space with a dense object (such as a person) below, you don't fall, and it doesn't re-check while you're standing still, so the person moving out from under you (or the canister being pushed from under you, or similar) doesn't cause you to drop, and when you move onto its new tile, you're moving onto a tile with something dense below so you don't fall, and so on and so forth.

**Comment by Rixunie** [comment]
Well there is also the whole thing of being able to just drive a cargo trolley in the open air. Crash through the railing and drive around in open air.

**Comment by Screemonster** [comment]
https://www.youtube.com/watch?v=4GE7QYc9HfM

**Comment by Rixunie** [comment]
More or less.

**Comment by AeroWing** [comment]
Can confirm this issue. Had it happen a few weeks back but forgot to report it. There was a small pileup in a stairwell near medical trying to treat a crew member who couldn't make it to medbay on their own. They tried to run down the stairs and ended up running on top of people below until they ran over an open tile and smacked down on an empty roller bed with a broken leg. Rather convenient if you ask me...

**Comment by Repede** [comment]
Other fun stuff you can do:

- Build Wooden (dragon) boat
- Get 4 (or more) people to ride the boat with you (not necessary)
- While sat on boat, ctrl+click it to begin dragging it, click tile in front of you, it will move the boat forward.
- Move the boat that way over open spaces, you are now in a flying dragon boat.

**Comment by KasparoVy** [comment]
Amazing. This is the future
