### ISSUE TITLE
Holding a contamined item deals toxin damage w/ protection

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#1739]
#### Brief description of the issue
Holding a contaminated item while you have a rigsuit on causes you to take toxin damage

#### What you expected to happen
Hold a contaminated item with a rigsuit on and not take damage, since I'm in a rigsuit and protected

#### What actually happened
Took 0.02 damage per tick while holding it

#### Steps to reproduce
- (Step 1) Wear protection
- (Step 2) Grab contaminated item
- (Step 3) Scan self

#### Code Revision
- release - 
74da4f2e4f04a6b74d7886b6305bbb3333a36947 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
Fixed upstream.
