### ISSUE TITLE
Old NanoUI issue is back. Buttons in PDAs do not appear correctly.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#174]
#### Brief description of the issue
https://github.com/SpadesNeil/VOREstation/issues/50 This was an issue in the old code.

#### What you expected to happen
Buttons!

#### What actually happened
No buttons!

#### Steps to reproduce
Open a PDA.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073 I think.

We should probably give the fix to Polaris if they want it. I just think it's ugly.

**Comment by Arokha** [comment]
This is by design.

**Comment by SpadesNeil** [comment]
But it looks stupid! ;_;
