### ISSUE TITLE
Diona Nymphs Prevent People From Moving When Attacked

### ISSUE THREAD

**Issue by Watchdoggg** [VOREStation/VOREStation#1754]
#### Brief description of the issue
Attacking a Diona Nymph causes them to make you unable to move so long as they are not completely sealed off from you.  Any movement results in (name) resists!  They also eventually turn invisible at some point as well.

#### What you expected to happen
The diona nymph does some sort of damaging attack

#### What actually happened
Diona Nymph does nothing but keeps you in place

#### Steps to reproduce
- Find Diona Nymph
- Attack Diona Nymph
- Get stuck

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd

**Comment by Novacat** [comment]
Mirrorbot was referring to polaris issues.
