### ISSUE TITLE
Xenobiology Genetic Bombarder and Grinding Slime Cores Do Not Work

### ISSUE THREAD

**Issue by Watchdoggg** [VOREStation/VOREStation#1755]
#### Brief description of the issue
Equipment in Xenobiology is bugged, along with the slimes themselves.  There is many things which seem off or wrong, however, two I could pinpoint have been listed below.

#### What you expected to happen
Using a Genetic bombarder and for it to work, and do what it is said to do.

Slime cores to be able to grinded for chemicals.

#### What actually happened
Genetic bombardier either tells you that you "it is closed and running" when neither statement is true or Genetic bombardier does not do anything to the slime except change it's name from grey slime to modified slime.

Slime cores cannot be grinded for chemicals at all.

#### Steps to reproduce
- Proceed through Xenobiology as normal, growing slimes and culling them for cores.
- Try to use Genetic Bombarder
- Try to grind slime cores at all.

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Please replace the title with something more specific to this bug. "Xenobiology bugs" is too vague.

**Comment by chaoko99** [comment]
Xenobio2 may be removed at next merge. Might not be important. Also it's resolved, so close it.
