### ISSUE TITLE
Deconstruction glitch

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#176]
#### Brief description of the issue
When deconstructing the Exosuit Fabricator and cyborg recharging station it will never be deconstructed but will produce a machine frame.
#### What you expected to happen
I expected the Exosuit Fabricator and cyborg recharging station to be deconstructed.
#### What actually happened
The Exosuit Fabricator and cyborg recharging station was not deconstructed and left a machine frame over top the fabricator
#### Steps to reproduce
1.Screwdriver the maintenance hatch open
2.Crowbar the Exosuit Fabricator or cyborg recharging station to produce a machine frame.
#### Additional info:
Cyborg recharging station suffers form the same issue

**Comment by SpadesNeil** [comment]
@Arokha wasn't this fixed in the latest sync? If so, mark as "Works in latest build"
