### ISSUE TITLE
teshari cant wear green bandana

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1765]
#### Brief description of the issue
the green bandana wont show up on a teshari, its possible this is true for other bandanas do the same 

#### What you expected to happen
to be a cute bird with a little bandana on my head 

#### What actually happened
![image](https://user-images.githubusercontent.com/16435949/27301536-5b9669a6-54e8-11e7-82d2-bfc395f1978c.png)

#### Steps to reproduce
- (Step 1) be teshari
- (Step 2) try to wear bandana
- (Step 3) be said it doesnt show up

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Bandanas are illegal in Teshari culture so they refuse to wear them

/s
