### ISSUE TITLE
Red Lawyer Skirt uses incorrect sprite when facing West.

### ISSUE THREAD

**Issue by TeleTubby2** [VOREStation/VOREStation#1766]
#### Brief description of the issue
The Lawyer skirt uses the Lawyer suit sprite when facing west

#### What you expected to happen
To not have pants

#### What actually happened
I had pants

#### Steps to reproduce
- (Step 1) Put on Lawyer suit
- (Step 2) Face West
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 256e1db4d6e43368e3e53cf3027e5ae395abdacd 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
Probably a copypasta issue in the iconstates. It's a base Polaris item.
