### ISSUE TITLE
Add torture player button

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1770]
#### Brief description of the issue
I keep forgetting to add this. Ban evaders don't care for the rules, so obviously, we need a way to deal with those who are seriously such sad people that they feel the need to come revenge griff a server full of ERPing furries.

For them, I have a special form of punishment, but currently, it can be avoided merely by turning off admin midis.

I want to have a button that specifically says "TORTURE" which subjects the offending player to one of several ear rape songs prone to getting stuck in their head through their speakers, and spam their chat log with the lyrics, just in case they have the sound turned off.

I keep forgetting to add this.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/ee7c895d07f7ef0ec3c39b1e64de6089ddb783f7

**Comment by Rixunie** [comment]
I approve of this.

**Comment by Screemonster** [comment]
I want this. I want to play stupidravershithead.mp3 at them.

**Comment by OrbisAnima** [comment]
Sorry to pop the bubble but its fairly easy to turn off the sound of byond itself, it might be nice to press the torture player button, but practically speaking, it does little.

Hell, a golden gooze might be much more effective..

**Comment by SpadesNeil** [comment]
Most players will not be smart enough to do that. If they do, they lose all sound, and the game suddenly becomes lots less entertaining.

**Comment by Screemonster** [comment]
A "spawn a bunch of hostile mobs that hate this guy in particular" button might be fun. Like the hallucination thing.

**Comment by Yoshax** [comment]
Not exactly... Lots of people play without sound. Personally I have all the ambience, music, and everything that isn't just normal sounds muted and depending on how I feel, my music might be louder then that. It's not a big deal not to have sound.

**Comment by SpadesNeil** [comment]
Well regardless, what happens when you read the lyrics to a song that usually gets stuck in your head? :)

**Comment by JoanRisu** [comment]
The chat spam itself would probably be annoying enough anyway. Maybe make their client auto open a maximized window or something with large text asking them where they went wrong in life.

**Comment by Yoshax** [comment]
Overall though, this is pretty immoral and malicious, and not something that I believe should be happening. It's immoral and overall pretty awful. You're doing nothing more than stooping to the level of the person coming to grief, tbh.

**Comment by SpadesNeil** [comment]
You're no fun. But you're probably right.

**Comment by subtumaka** [comment]
I HIGHLY APPROVE OF THIS. SHOULD YOU BE WILLING TO ADD THIS IN THE FUTURE. I WILL MAKE A GENEROUS DONATION TO YOUR POOL OF SONGS

**Comment by SpadesNeil** [comment]
_Maybe._
