### ISSUE TITLE
Humvee Invisibility Bug

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#1773]
#### Brief description of the issue
Using the humvee occasionally causes someone's character to turn invisible.

#### What you expected to happen
Turn back to normal when exiting the humvee or prevented from entering the humvee.

#### What actually happened
Still invisible when stopped from entering the humvee.

#### Steps to reproduce
1.  Have two people click on the humvee
2. Watch as one person gets in and the other disappears
2a. (Maybe observe the one who disappears attempting to misuse bug.)

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd

**Comment by SpadesNeil** [comment]
Bumping this up to severe since it is a very bad and abusable bug.

**Comment by AeroWing** [comment]
Can confirm, I was able to turn invisible by trying to enter a Humvee that was driving past me. Had to enter cryo to resolve.
