### ISSUE TITLE
CE's hardsuit has no sprite for skrell.

### ISSUE THREAD

**Issue by RezRaz** [VOREStation/VOREStation#1778]
#### Brief description of the issue
Deploying the CE's advanced hardsuit while playing a Skrell reveals that it simply has no chest sprite for the species.

EDIT: Upon further testing, this also applies to the EVA Hardsuit, and possibly others as well.
#### What you expected to happen
To be able to wear the hardsuit without looking like an idiot.

#### What actually happened
Looked like an idiot while wearing the hardsuit.

#### Steps to reproduce
- Play Skrell
- Put on hardsuit
- Deploy, and be laughed at

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd

**Comment by SpadesNeil** [comment]
Resolved?

**Comment by RezRaz** [comment]
Opened a PR on the polaris master to fix it. Tested it already, it should be good to go.
