### ISSUE TITLE
syringes slicing apples

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1779]
#### Brief description of the issue
when you interact a syringe with an apple (either on draw or inject) it will 'slice the apple but when you interact with the slice it says "None of the apple slice left!" unless you inject a reagent inside, then you can bite it normally until the reagent is gone

#### What you expected to happen
to be able to inject something into the apple and not to create face apple slices

#### What actually happened
i got fake apple slices that are basically little containers

#### Steps to reproduce
- (Step 1) optain apple and syringe
- (Step 2) click syringe onto apple
- (Step 3) try to eat apples and then find them to dissapear into nothingness

#### Code Revision
256e1db4d6e43368e3e53cf3027e5ae395abdacd 

#### Anything else you may wish to add:
- i would suspect the same thing happens to any slicable fruit but i was trying it with apples

**Comment by chaoko99** [comment]
Polaris bug. It's also a bug present on literally every server iirc. Syringes are `SHARP` for some reason. They can cut throats and whatnot. (h o w). Something to do with the fact that syringe guns don't shoot projectiles rather than literal flipping syringes.

**Comment by kcin2001** [comment]
Why doesnt it make normal slices though

**Comment by chaoko99** [comment]
It makes the same kind a knife does?

**Comment by kcin2001** [comment]
Not when this issue was made, the slices were empty of nutriment or anything
