### ISSUE TITLE
Suggestion: Porting over Citadel's vore sounds, and a few extensions thereof.

### ISSUE THREAD

**Issue by SingoDingo** [VOREStation/VOREStation#1783]
#### Considering how old all the vore sounds here appear to be, why not freshen things up a little?

They seem to have both predator and prey versions of all the sounds they have as well, in which the predator's version would be a little more muffled, which I think is a rather neat concept. They needn't replace the current ones either, variety is the spice of life, after all, and giving people the option as to what swallow/digest/stomach loop sounds they want would be a good quality of life addition. Wouldn't want wet stomach sounds playing for cloth 'bellies', now would we?

Now, I think I might add the caveat that considering how much longer the swallow sounds are, and how much more 'squick' their stomach loop might be considered by some, if this would be to happen I think other options may be warranted as well. Perhaps making them only audible by those with line of sight might be a good change on one hand, but on the other, a button specifically for toggling vore sounds might also be in order. Just a few things that'd been on my mind, is all.

For reference, here's a link to citadel's vore sounds, as listed on their GitHub:
https://github.com/Citadel-Station-13/Citadel-Station-13/tree/master/sound/vore

**Comment by Zeldazackman** [comment]
Sadly not everything from Citadel needs to be copied in fervor, Virgo can afford to have some string of independent development made just for the server that could go far and beyond what others have to offer.

The basic sounds were a commission from "Chemical Crux" if you're wanting to have something of your own unique design for a sort of vore sound system like kotetsu was talking about over here: https://github.com/VOREStation/VOREStation/issues/1782

**Comment by SpadesNeil** [comment]
Why so many thumbs down? Is their audio quality just crappy?

**Comment by Dingosilver** [comment]
I've honestly just come to the conclusion that Citadel isn't very much liked in the Virgo community. That, or people just don't particularly like them, because not being entirely unique has never been a problem before.

**Comment by SpadesNeil** [comment]
Or maybe it's Citadel players who are still sore that we took their dog borgs, because y'know, fuck open source coding I guess.

**Comment by Poojawa** [comment]
Hi these are actually sounds that belong to me. I commissioned them for myself.

I'd rather these not be stolen/used without my permission, thanks.
