### ISSUE TITLE
Can't feed trash to Janihound Cyborgs

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1784]
#### Brief description of the issue
I wanted to feed a janiborg trash, because it sounded cute and adorable, but I was disallowed.

#### What you expected to happen
I expected the janiborg to be nomphin' and gulpin' it up like a good boy.

#### What actually happened
Janiborg sparked.

#### Steps to reproduce
1. Get a cute janitorial hound cyborg friend.
2. Get trash.
3. Attempt to feed trash to Jani-doggo.
4. Sparks.

#### Code Revision
Server revision: release - 
256e1db4d6e43368e3e53cf3027e5ae395abdacd

**Comment by Verkister** [comment]
#2469
