### ISSUE TITLE
Return of the Gateway Maps

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1787]
#### Brief description of the issue
We have no Gateway maps, and the functionality for those maps is outdated and incredibly hacky. I'd like some help making this shit work correctly, and possibly also have multi-Z functionality.

- [ ] Review existing Gateway code to look for problems, which I am sure are numerous.
- [ ] Build new maps. I'll handle that.
- [ ] Convert old maps to work with the new system.
- [ ] Expand on procedural generation of maps and loot. Ideally I want a map that is all procedural generation at some point, like a cave system, or an underground lab.
- [ ] Better, unique rewards that are actually worth hunting for. (Discuss)
- [ ] Vore mobs, vore shenanigans, etc for z-levels.

Maps that need fixing...
- [ ] Zoo
- [x] Beach
- [x] Listening Outpost
- [x] Pirate Ship (blackmarketpackers.dmm)
- [ ] Clown Temple
- [ ] Xeno Station

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/eae9f038a979c622d6c285b3aa7ebcb2466e8459

**Comment by Dingosilver** [comment]
For the procedurally generated lab idea, I can certainly see having more powerful, 'experimental' versions of existing weapons around. Maybe some more fun or harmless things too, like a NSFW gun with net and strip modules, so if civilians go on the expedition they wouldn't find themselves loaded with nothing but dangerous contraband items.

**Comment by SpadesNeil** [comment]
Rix demands a monkey launcher.
