### ISSUE TITLE
Custom Species unable to select Canilunzt as a language.

### ISSUE THREAD

**Issue by JackeryFox** [VOREStation/VOREStation#1789]
#### Brief description of the issue
As stated in the title, unable to select Canilunzt from the language list as a custom species.

#### What you expected to happen
To be able to select the language as any other one.

#### What actually happened
Language doesn't even appear.

#### Steps to reproduce
Click Species
Select "Custom Species"
Click "add" under the Languages section

#### Code Revision
master - 2017-06-23
7b91330ac195c0954d26fa30d1f84a5e7ad427bb 

#### Anything else you may wish to add:
http://prntscr.com/fpdmcs
http://prntscr.com/fpdmf8

**Comment by Dingosilver** [comment]
That's odd, I have a custom species Vulpkanin that knows Canilunzt. Could be it's recent, or a bug to do with what species template you're using.

https://puu.sh/wwVZI/40e761d4bf.JPG
