### ISSUE TITLE
Resleeving Deformations Remain After Cryo

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1790]
#### Brief description of the issue
When a new sleeve is made, it is often deformed- via missing a few pixels on random parts of the body. After a dip in the cryotube, the body is usually repaired mechanically, but the sprite will still look deformed.

#### What you expected to happen
When it says my hand is shaped like normal again, for it to actually look like normal.

#### What actually happened
It doesn't.

#### Steps to reproduce
- Get resleeved
- Carefully examine the sprite for genetic malformations
- Cryo oneself
- See that the deformities remain, even after receiving the message that they have been fixed

#### Code Revision
- 256e1db4d6e43368e3e53cf3027e5ae395abdacd
 
#### Anything else you may wish to add:
![screenshot 2017-06-30 18 36 58](https://user-images.githubusercontent.com/17329033/27758199-f254c16a-5dc3-11e7-92d8-8b67c59e876d.png)

**Comment by ArgobargSoup** [comment]
...If that pic is of your deformed hand... I'm not seein' a hand deformity in that shot.  I'm seein' the sprite of the satchel you're wearin' layered over your hand.

Your character's foot does look a little off, though.

**Comment by Cameron653** [comment]
Yeah, that foot definitely looks like it has some issues.

**Comment by Vorrarkul** [comment]
Well maybe I was a bit dumb then. But the foot is still off for sure!
