### ISSUE TITLE
Mining/Xenoarch Update - The Underground

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1795]
#### Brief description of the issue
I want to create a Roguelike mining experience but I need some information on doing this correctly. So, here's what I want to do.

- [ ] tether-04-mining.dmm needs 5 additional levels, each one deeper than the last. I don't know how the z-level system works so I need @Arokha to help explain wtf I am doing. I think I can just make it have a total of 6 levels but I don't know if that will fuck with anything. Alternatively I can add an extra map file just for mining.
- [ ] Underground levels should all have the same atmosphere as the surface.
- [ ] There needs to be a way to get to the lower levels reliably, either via some kind of drill or an elevator. I think an elevator might be best.
- [ ] Each underground level should be populated with mobs, more densely populated and more dangerous the deeper we go. Rare ores should also be more present.
- [ ] Underground ruins should be possible to find levels -3 and below, populated with Xenoarcheology artifacts and other unique goodies. I can design the layout of the ruins, but they need to be turned into usable code somehow.
- [ ] Bottom level (-5) could have lava pools which players cannot walk on, but illuminate areas.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/64eb12fd9c24b929ca27bea181d2b1519c3882be
 
#### Anything else you may wish to add:
Need ideas for what kind of horrible creatures can be found underground. So far my list includes...
- Voracious lizards.
- Spiders. Duh.
- Deathclaws maybe.

**Comment by Very-Soft** [comment]
If you need monster sprites, I am happy to doodle some up.
