### ISSUE TITLE
Some vore mobs should have a random knockdown ability

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#180]
Suggested by @Screemonster a while ago.

Relies on https://github.com/VOREStation/VOREStation/issues/165 being fixed first.

Server revision: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Screemonster** [comment]
As a note, as long as voremobs incapacitate people who've been eaten by them like the did in the old code (rendering them incapable of fighting from inside) this does have the potential for an effective OHKO.

That's not to say it shouldn't happen, but they should be balanced accordingly (even if it's only giving it to "boss" mobs that are intended for combat against groups of players - if you go through the gateway and try to solo a megacarp and get eaten that's your own dumb fault)

**Comment by Poojawa** [comment]
Here ya go, TG's carp knockdown code. 

Probably need to change it up a bit to be in line with the stun resistance Baycode has.

`if(isliving(target))
	var/mob/living/L = target
	if(prob(15))
		L.Weaken(3)
		L.visible_message("<span class='danger'>\the [src] knocks down \the [L]!</span>")`

**Comment by SpadesNeil** [comment]
I forget when I did this, but I did this.
