### ISSUE TITLE
Gutter is translated by a universal translator

### ISSUE THREAD

**Issue by JemliRoivas** [VOREStation/VOREStation#1803]
#### Brief description of the issue
The criminal cant, gutter, is currently translated by the universal translator, thus voiding out the reason why it was made a whitelist reason in the first place.  Also, PAI's have it as a language

#### What you expected to happen
Have a secret language

#### What actually happened
Everyone in security takes out a translator instead of knowing how to speak it.

#### Steps to reproduce
Speak gutter near a translator.
Watch as it's not actually a secret language

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/c3a10628b272831085fca023288b86eaa9dd1dc1

**Comment by SpadesNeil** [comment]
I'm actually okay with this because it requires security to have extra foresight to be arsed to carry it with them than to just know how to speak gutter because fuck you that's why.

This isn't a bug as far as I am concerned. Sorry.

**Comment by Screemonster** [comment]
They're not in limited supply though, people can take them in loadout for 8 points.

**Comment by SpadesNeil** [comment]
It still needs to be turned on. We could also make them more expensive or remove them. Point is there's more effort than just "hurr durr I know universal now"
