### ISSUE TITLE
Skrell tentacles gone.

### ISSUE THREAD

**Issue by RezRaz** [VOREStation/VOREStation#1804]
#### Brief description of the issue
Skrell tentacle hairstyles are no longer part of the list.

#### What you expected to happen
To be able to have tentacles.

#### What actually happened
Didn't have tentacles.

#### Steps to reproduce
- Try to have tentacles.
- Fail.

#### Code Revision
- c3a10628b272831085fca023288b86eaa9dd1dc1

**Comment by Rapidvalj** [comment]
😭
