### ISSUE TITLE
Custom Species with Teshari base has no feather colouring

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1811]
#### Brief description of the issue
When creating a custom species and using the Teshari base, setting the hair colour as a different colour from the body doesn't colour the body's feather displays properly.

Also, the eye colour doesn't show up. Just noticed this while taking screens for examples.

#### What you expected to happen
Fancy colourful multicolour Teshfeathers all over the body, like how the Teshari species works normally.

#### What actually happened
Just the hair colour's different and nothin' else.

#### Steps to reproduce
1. Make a new character, intending to make something like a pooltoy teshari.
2. Select custom species - set icon base as Teshari in the VORE tab.
3. Set body and hair colour as different colours.

#### Code Revision
Server revision: release - 
c3a10628b272831085fca023288b86eaa9dd1dc1 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/10330701/27846051-626c69ba-612c-11e7-87a3-8cfe2be77cb4.png)
![image](https://user-images.githubusercontent.com/10330701/27846056-6c30ec6e-612c-11e7-8586-fcac4d5468ea.png)

**Comment by Epitaxis** [comment]
Actually if you look, it's not that the eyes don't show up. It's that they're displaced above the head.
Bottom picture with the teshari facing left, you will see an extra pixel that's floating just above the head.

**Comment by Verkister** [comment]
Been added as a markings set a while ago.
