### ISSUE TITLE
Duct taping mouth doesn't restrict speech

### ISSUE THREAD

**Issue by Konabird** [VOREStation/VOREStation#1813]
#### Brief description of the issue
Using duct tape on a person's mouth only says you are covering it, but doesn't actually have any in game function. Victims can still speak freely.

#### What you expected to happen
Duct taping the mouth would restrict speech.

#### What actually happened
Person could still speak even after several attempts to use duct tape.

#### Steps to reproduce
- (Step 1)find a person
- (Step 2)duct tape their mouth
- (and so on) have them try talking

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Konabird** [comment]
Server revision: c3a10628b272831085fca023288b86eaa9dd1dc1

Accidentally hit submit..

**Comment by SpadesNeil** [comment]
You know you can edit posts, right? :P
