### ISSUE TITLE
Sizeshifting trait

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1814]
#### Brief description of the issue
Someone on the forum suggested we should add a sizeshifting trait to be an option for a custom species in-game. By default, Prometheans should also have this ability.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/8b0f91f35b29780cd563f1a0bf6e7d3b87218459

**Comment by SilencedMP5A5** [comment]
eeehhhh it. could be pretty abusable. but i can also see the good in it.

**Comment by Arokha** [comment]
Prometheans do now have this ability.

**Comment by SpadesNeil** [comment]
Wait, just Prometheans? Could add it as a max value trait. Or keep it unique to Prometheans.
