### ISSUE TITLE
Prometheans can't choose a custom race name

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#1827]
#### Brief description of the issue
Prometheans can't choose a custom race name

#### What you expected to happen
Custom race name able to be selected and used

#### What actually happened
It didn't

#### Steps to reproduce
- Look
- Be amazed

#### Code Revision
- 19d4508730fc04a000dc5c13a6258c03432caa5d

**Comment by Cameron653** [comment]
Temp bypass:
0. Go to character setup
1. Select custom species as race. Click "select"
2. Select promethean as a custom race, do NOT click "select" just yet
3. Go to the vore tab and click "Custom Species" but do not input anything yet
4. Click "select" for the species that you chose earlier
5. Set your custom race and click "OK"

**Comment by chaoko99** [comment]
Is this still present?

**Comment by Cameron653** [comment]
This has been fixed.
