### ISSUE TITLE
Prometheans TFing someone results in them turning invisible

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#1829]
#### Brief description of the issue
When a promethean TF's someone, the person being TF'd turns invisible

#### What you expected to happen
Not be invisible

#### What actually happened
Be invisible

#### Steps to reproduce
- Be TF'd into a promethean
- Put a sweater on/off, causing runtimes
- Become invisible

#### Code Revision
- 19d4508730fc04a000dc5c13a6258c03432caa5d 
 
#### Anything else you may wish to add:
- Runtimes:
DEBUG: Runtime in species_shapeshift.dm,32: Cannot execute null.get bodytype(). [view] 
DEBUG: Runtime in species_shapeshift.dm,32: Cannot execute null.get bodytype(). [view] 
DEBUG: Runtime in species_shapeshift.dm,52: Cannot execute null.get tail(). [view] 

File: https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/living/carbon/human/species/species_shapeshift.dm

When I ran forced a proccall (shapeshifter_select_shape) and selected a species, it proceeded to not turn me invisible any more and fixed my icons.

**Comment by Epitaxis** [comment]
Vrok Anatisi was TF'd by a prothean named Nex, we had a similar incident but instead of the Anatisi's teshari sprite going invisible her hair, beard, and tail did go invisible.

**Comment by SpadesNeil** [comment]
Is this still a bug?

**Comment by Cameron653** [comment]
I believe so. I haven't seen anything done to fix this.
