### ISSUE TITLE
OOC notes missing from both Cyborg and Human flavortext.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#183]
#### Brief description of the issue
We have no OOC flavortext! Though we do have OOC notes but those don't do anything!

#### What you expected to happen
In character setup, to have a flavortext option for OOC prefs.

#### What actually happened
No such option exists. What we get is OOC notes and that doesn't do anything.

#### Steps to reproduce
Attempt to make a new character.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073
 - **Anything else you may wish to add**: Not sure if it's actually a bug, so marking as "needs testing."

**Comment by Arokha** [comment]
It’s on the left, a few buttons below name bub.

**Comment by Arokha** [comment]
Gon' close this. Button is there. Jus' look, it's on the left side. Has it's own button.

**Comment by SpadesNeil** [comment]
Oh okay.

**Comment by SpadesNeil** [comment]
OOC notes appear nowhere in-game that can be seen by players.
