### ISSUE TITLE
Players do not "Set Character Size" verb

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#1836]
#### Brief description of the issue
Players no longer have access to the "set character size" verb.

#### What you expected to happen
To have access to the "set character size" verb.

#### What actually happened
I and others did not.

#### Steps to reproduce
- Exist.
- Look for verb.
- Find it doesn't exist.

#### Code Revision
14d5421d1abb0625ca36ebefc0ddc6625f3e589c

**Comment by SpadesNeil** [comment]
This is not a bug. There's other ways to access this now.

**Comment by SpadesNeil** [comment]
@Arokha if the wiki page isn't updated please do so. :U
