### ISSUE TITLE
Preds cant hear prey whisper.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#184]
#### Brief description of the issue 
While in someone's stomach/whatever, if you whisper, they can't hear you

#### What you expected to happen
Whisper while in pred, they could hear me

#### What actually happened
Whisper while in pred, they were wondering why I wasn't responding

#### Steps to reproduce
Get eaten by pred
Whisper
Not be heard.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
849c30750d4ba1099d650c1abc9cf818c8fc4073 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
Gave this the need testing label as I'm not sure if it happens 100% of the time or what.

**Comment by Arokha** [comment]
This is already fixed in master.
