### ISSUE TITLE
Suggestion: Making the HoS's snowflake gun a NSFW handgun

### ISSUE THREAD

**Issue by SingoDingo** [VOREStation/VOREStation#1840]
Now, there were two main reasons this was running through my head as an alright idea, since the sentiment of the HoS having _something_ special for themselves is a pretty popular one and I thought I may as well see what people thought of my reasoning here.

#### 1. Readily available utility:
After looking at the code for the lethal and stun NSFW magazines, and realising they were (as far as I can tell) identical to just using the laser the HoS has already, the idea of having the NSFW gun as less of a secondary weapon and more as a utility problem solver came to mind. The amount of times sec would have quick and convenient access to either net or ion weaponry without a very productive science department or a convenient amount of warning seem few and far between, so why not have the HoS with these on hand in small amounts? Robotics has it's most recent project go on a rampage? Apply a few NSFW ion rounds. Someone with haste making it hard for your officers to hit them with stuns? Apply NSFW net rounds. They call them the problem solver.

#### 2. Actually ever making use of strip rounds:
Now, while the scene and humour uses for them are immediately obvious, they actually might be the answer to another long existing problem sec has had in the past. Imagine someone was running around committing vandalism in a hardsuit, but was also quite the grand thundercunt and didn't want to comply with security at all. They refuse to pay a fine, and are resisting arrest, but because they're in a hardsuit none of your stun weaponry will work on them. Sure they're being an asshole, but you don't just want to _shoot_ them for smashing a window, do you? That's where strip rounds come in! Call over the HoS, have them fire a round of strip ammo at the absolute wanker, and proceed with arrest as per usual after all their stun-proof gear goes flying right off. Practically a science!

If I'm missing anything that might poke massive holes in my arguments feel free to point them out, I'm mostly just spitballing here. It just seemed quite sound in my head, so I thought I'd leave it on the table as a suggestion.

**Comment by SilencedMP5A5** [comment]
this doesn't seem to be very _safe for work._
**badumtss.**

but honestly, i'm kinda uncertain. can't you fire fuckin' laser cannon bolts from the NSFW? or pulse rifle bolts? if not, i 100% think this is a good idea.

**Comment by Dingosilver** [comment]
As far as I can tell they can only fire ammo from very specific batteries made for the gun itself, and these can to my knowledge only be gained from admin spawns. So unless the person using it somehow defeats an ERT leader they probably won't be finding much lethal ammo for it around.
