### ISSUE TITLE
Bears do not attack, cause infinite loops

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#1844]
#### Brief description of the issue
Bears are broken, causing an infinite loop somewhere and never attack

#### What you expected to happen
Bears to chase and maul things

#### What actually happened
Bears chase but do not maul, then dream daemon yells about loops

#### Steps to reproduce
Spawn bear, spawn monkey, watch

#### Code Revision
 14d5421d1abb0625ca36ebefc0ddc6625f3e589c 

#### Anything else you may wish to add:
[13:03:24] Runtime in ,: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
  Caught by Mobs subsystem
  proc name: ListTargets (/mob/living/simple_animal/proc/ListTargets)
  src: (the floor) (63,73,3) (/turf/simulated/floor/tiled) ()
  src.loc: (the floor) (63,73,3) (/turf/simulated/floor/tiled) ()
  src.loc: the floor (63,73,3) (/turf/simulated/floor/tiled)
  call stack:
  the space bear (/mob/living/simple_animal/hostile/bear): ListTargets(10)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  ...
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance(1)
  the space bear (/mob/living/simple_animal/hostile/bear): handle stance()
  Mobs (/datum/controller/subsystem/mobs): fire(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): StartProcessing(0)

**Comment by SpadesNeil** [comment]
shit that explains a lot
