### ISSUE TITLE
Slug Taur Body Shows Foot Pixels From Front

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1845]
#### Brief description of the issue
As the title says, there are pixels of the foot visible from the front of the slug body.

#### What you expected to happen
The pixels to be covered up.

#### What actually happened
Two tiny pixels of whatever color footwear I was wearing were seen.

#### Steps to reproduce
- Be a slug
- Make the slug color something dark
- wear bright shoes for best effect

#### Code Revision
- 14d5421d1abb0625ca36ebefc0ddc6625f3e589c 
 
#### Anything else you may wish to add:
- ![screenshot 2017-07-08 16 11 33](https://user-images.githubusercontent.com/17329033/27990136-2458300e-6402-11e7-86e4-7fe8b460bb10.png)

**Comment by Natje0** [comment]
Oops

**Comment by Natje0** [comment]
Added a pixel up. Should cover the shoes, now!
(Updated Front Sprite attached.)
![slug front-fix d](https://user-images.githubusercontent.com/21280420/28312111-38430226-6bb2-11e7-92c9-031900bbecf8.png)

**Comment by Vorrarkul** [comment]
The updated sprite has yet to be implemented. Posting due to this stale bot.

**Comment by KasparoVy** [comment]
This was also partly resolved by a PR that prevents the rendering of legs & shoes for taurs
