### ISSUE TITLE
Feature Idea: Allow ghosts to enter NIF Soulcatchers.

### ISSUE THREAD

**Issue by Epitaxis** [VOREStation/VOREStation#1847]
#### Request Description:
Allow ghost to join into soulcatchers in a similar way that one would call a communicator as a ghost.

#### Specifics on in-game implementation:
Talking with development in discord gave a few insights that I've likely forgotten. But as for implementation of ghosts entering soulcatchers would be simple I hope?

Add a new option under the soulcatcher menus that allows for accepting or denying requests to join into a dreamscape. This would not produce a pop up when a ghost sends out an invite as to not accidentally allow one in during a scene. It would prompt in their chat as a personal NIF message they can either click to accept or deny it from there or go into the soulcatcher menu from there.

I would as well imagine it would be useful to be able to disable soulcatcher requests from ghost if you do not want to be bothers or if it is a strictly private scene.

#### Reasoning for the feature:
It would allow myself and other players to continue into scenes from a previous shift if a character would still be stuck within the soulcatcher (If that's possible?).  Otherwise the ghosts that hop in can instead be people/things 'imagined up' for the dreamscape so they may add-to/join into the scene or roleplay.

**Comment by Draycu** [comment]
Hey, love this, and hope we can implement it!  It really does seem like it will give us a fantastic way to carry over encounters with the soulcatcher to the next round!

**Comment by Very-Soft** [comment]
This is a thing now
