### ISSUE TITLE
The mob spam is too real

### ISSUE THREAD

**Issue by Yoshax** [VOREStation/VOREStation#1848]
#### Brief description of the issue
There's far too many mobs that make noise far too often. It's next to impossible to meaningfully observe.
See:
```The feral otie rurrs.
The feral otie yawns.
Schae Yonra (follow) says, "What's wrong?  You seem..."
Kseno yawns.
The feral otie yawns.
The gaslamp sways gently.
The feral otie snarls.
The feral otie rurrs.
The feral otie murrs.
 [Common] Mischere (follow) says, "People are a great food source."
Miranda Beraus huffs. "I suppose you can change it if you want..."
 [Common] Mischere (follow) says, "Sadly not enough."
 [Common] Zenova T'koi (follow) asks, "Where ya at, person that wanted metal?"
Jon Riker (follow) says, "Uhm- T-thanks for the offer though- I- Um."
The feral otie sounds hungry.
The feral otie snarls.
The feral otie stretches.
The feral otie groans softly.
The phoron dragon snaps at the gaslamp
The gaslamp sways gently.
The feral otie stretches.
Schae Shooki yawns as well. "Thinks is going home."
```

That's with 47 people on the server. There's like 8 lines of mob stuff inbetween talking.

#### What you expected to happen
To be able to observe and read station stuff without 10 lines of mob stuff every 5 seconds.

#### What actually happened
Chat window is utterly filled with mob spam.

**Comment by SpadesNeil** [comment]
That's because there are **a lot** of mobs. However we should make it so uninhabited mobs do not spam the screen like that with ghost ears/eyes on. It's annoying, and it also spoils my Z-levels sometimes.
