### ISSUE TITLE
Unable to unlock the maintenance hatch on cyborgs

### ISSUE THREAD

**Issue by Treasa729** [VOREStation/VOREStation#1854]
#### Brief description of the issue
When clicking a cyborg with a roboticist ID, it should unlock them so you can open the maintenance panel. This doesn't happen. Clicking a cyborg with an ID doesn't cause anything to happen. No message at all, no access denied, nothing.

#### What you expected to happen
To be able to unlock a cyborg to do my job.

#### What actually happened
We had to get and admin to reset the borg because we couldn't unlock the borg.

#### Steps to reproduce
- (Step 1) Click a borg with an id that should be able to unlock them
- (Step 2) Watch as nothing at all happens

#### Code Revision
Server revision: release - 
14d5421d1abb0625ca36ebefc0ddc6625f3e589c 

#### Anything else you may wish to add:
Someone else confirmed they had this issue on other shifts in LOOC.

**Comment by Cameron653** [comment]
Is this still an issue? The new release was pushed 17 hours ago and this was made 18 hours ago.
https://github.com/VOREStation/VOREStation/pull/1843 should have fixed this problem.

**Comment by Cameron653** [comment]
Just tested on the live server. This isn't an issue anymore.
