### ISSUE TITLE
Canine borg modules spam attack logs.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#187]
#### Brief description of the issue
https://github.com/SpadesNeil/VOREstation/issues/507

#### What you expected to happen
To harmlessly boop/lick/etc someone.

#### What actually happened
Attack logs. Also this.
![capture](https://cloud.githubusercontent.com/assets/6484985/15458305/faa30cc4-2065-11e6-9bd8-c99d18170164.PNG)
Also when licking other borgs, it causes sparks and oil splatter but no actual damage. It shouldn't do this.

#### Steps to reproduce
Boop, slurp, or nom someone as borg.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073
 - **Anything else you may wish to add**: This was previously fixed in old code.

**Comment by Arokha** [comment]
It's a bug I fixed on the previous server. There's a NOBLUDGEON flag that is supposed to prevent attacks with certain things but it only does it in certain places.

**Comment by SpadesNeil** [comment]
Oh!

**Comment by SpadesNeil** [comment]
Actually just either of you handle this. @Cameron653 or @Arokha assign yourself whenever you wanna fix this.

**Comment by Arokha** [comment]
Fixed but never closed.
