### ISSUE TITLE
Air Alarms "Replace Air" setting vents incorrectly.

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#1870]
#### Steps to reproduce
- Go to air alarm
- Set it to "Replace Air"
- Check the vents settings

#### Code Revision
- 861edd2c42e78d3b8327d42c2067fe5346a563b1

**Comment by Cyantime** [comment]
If you had already manually set the vent to siphon, none of the premade settings will unset that. If not, I have no idea how that could possibly happen, none of those choices will change the direction of a vent.
See: https://github.com/VOREStation/VOREStation/blob/master/code/game/machinery/alarm.dm#L408

**Comment by Fevix** [comment]
Okay, I see where it's not changing the direction and yes I had set it to siphon, but I honestly expected that setting to change it to Fill, because that's part of the description. 

While we're at it, why wouldn't Fill set the vents to pressurize either? Seems like a slight oversight.

**Comment by Cyantime** [comment]
Because those settings were made before it was possible to set vents to siphon.

**Comment by Fevix** [comment]
And that means they SHOULDNT be updated to actually do what the descriptions say they should?
