### ISSUE TITLE
Research Director's Rubber Stamp completely missing from the map.

### ISSUE THREAD

**Issue by Dankman** [VOREStation/VOREStation#1872]
Exactly what it says on the tin, that little rascal doesn't spawn in the RD office and hasn't since tether happened.

**Comment by SpadesNeil** [comment]
I was doing some map fixes already. I'll fix this.

And yes this is "severe" because an intended functionality of the game is not present. :P

**Comment by Dankman** [comment]
<3

**Comment by Natje0** [comment]
Pretty sure it's the same with the CMO stamp, but I think someone was on that? Not sure.
