### ISSUE TITLE
Suggestion: Make a rule against antags going SSD/Cryo right after the crime/right after Sec finds them

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#1873]
This happens way too often. the past two shifts I've been on, a crime was committed

- The first time, the main suspect went to Cryo before the investigation started (Which removed their fingerprints from the database and made it much harder to track them down)
- The most recent time, an assault was done, but right after the crime was reported, the culprit went SSD

**Comment by Ketrai** [comment]
There are very rarely any real antags, these are mostly people just committing crimes.

**Comment by SpadesNeil** [comment]
Please do not use Github for this. This is not the correct use of Github.
