### ISSUE TITLE
cant drag things through the z level switch between the station and mining

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1877]
#### Brief description of the issue
when im dragging an ore box to mining it will be left behind as i go through to mining proper

#### What you expected to happen
to be able to pull an ore box to mining

#### What actually happened
i had to stop pulling, get behind it and push it to mining

#### Steps to reproduce
- (Step 1) be a miner
- (Step 2) try to bring an orebox to mining
- (Step 3) cry as it gets left behind

#### Code Revision
- 861edd2c42e78d3b8327d42c2067fe5346a563b1
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Tasald** [comment]
This is fixed?
