### ISSUE TITLE
Dogborgs should be able to eat mice!

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#188]
Because reason

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073

**Comment by Arokha** [comment]
Noh. They don't have the important parts that carbons have. Like hearts and pulses and blood and reagents and whatnot. Sleepers don't work on mobs that aren't carbons. They will runtime a billion times.

**Comment by SpadesNeil** [comment]
Shit.
