### ISSUE TITLE
Unhackable Jukebox

### ISSUE THREAD

**Issue by LSommers** [VOREStation/VOREStation#1881]
#### Brief description of the issue
Jukebox electronics are tamper-proof.

#### What you expected to happen
Open jukebox, multitool, unlock more music.

#### What actually happened
Open jukebox, cry.

#### Steps to reproduce
- (Step 1) Open jukebox
- (Step 2) Observe the message regarding the elctronics

#### Code Revision
Server revision: release - 
861edd2c42e78d3b8327d42c2067fe5346a563b1 
 
#### Anything else you may wish to add:
LITERALLY UNPLAYABLE

**Comment by SpadesNeil** [comment]
Legit a severe bug. A game functionality is unusable.

**Comment by Heroman3003** [comment]
This is a misunderstanding. Tamper-proof electronics do not prevent hacking. It just means that the wire layout will be randomized compared to non-tamper proof or other tamper-proof devices of same type. So working as intended.

**Comment by LSommers** [comment]
> This is a misunderstanding. Tamper-proof electronics do not prevent hacking. It just means that the wire layout will be randomized compared to non-tamper proof or other tamper-proof devices of same type. So working as intended.

It's not a misunderstanding- At the time, attempting to hack the juke would give you a "the jukebox has tamper-proof electronics" message, and no way to actually bypass that to hack it.

Please do not assume that you are qualified to judge what other people do or do not understand.
