### ISSUE TITLE
ERT shuttle is fucked

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1891]
#### Brief description of the issue
Tried to use the ERT shuttle during an emergency. Nothing worked!

#### What you expected to happen
- To be able to board the shuttle.
- To be able to launch the shuttle with the computer.
- To AT LEAST be able to admin-launch the shuttle.

#### What actually happened
- ERT shuttle was bolted shut.
- ERT shuttle computer could not be interacted with.
- ERT shuttle didn't even exist in the shuttle list!

#### Steps to reproduce
- See above.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/861edd2c42e78d3b8327d42c2067fe5346a563b1

**Comment by SpadesNeil** [comment]
@Cameron653 I can't figure this out.

**Comment by Cameron653** [comment]
Looking for the ERT shuttle, I found
https://github.com/VOREStation/VOREStation/blob/master/maps/southern_cross/southern_cross_shuttles.dm#L3-L25

Which isn't compiled unless southern_cross is compiled. If not that, it could also be
https://github.com/VOREStation/VOREStation/blob/39ce8cfe276dde0d567af275e8e2779d5c69fc88/maps/northern_star/northern_star_shuttles.dm#L260-L270

which also doesn't compile northern_star is compiled.

This was just a quick look, however.

**Comment by SpadesNeil** [comment]
It might be the no AI interaction.

**Comment by Novacat** [comment]
I fixed this.
