### ISSUE TITLE
Examining self shows biological sex in chat log instead of gender identity

### ISSUE THREAD

**Issue by Renkindle** [VOREStation/VOREStation#1897]
#### Brief description of the issue
- Checked myself for injuries on a character whose bio sex was female but identifying gender was male. People got "x examines herself" instead of "x examines himself" in their chat log.

#### What you expected to happen
- "x examines himself" to show up in the chat log for others

#### What actually happened
- "x examines herself" showed up in the chat log for others

#### Steps to reproduce
- Have character with assigned/identifying gender different
- Check self for injuries
- Ask others what showed up (or do it in a moving elevator in the first place)

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/861edd2c42e78d3b8327d42c2067fe5346a563b1
 
#### Anything else you may wish to add:
- Asked someone else to tell me what text they got after I examined myself, and they got the same thing as I did.
 - https://puu.sh/wRrWS/8f6747466c.png
 - https://puu.sh/wRs3q/f527c5afed.png

**Comment by DarkWolfInsanity** [comment]
Well. If you're looking at your dangly bits, it would show the biological gender instead of the gender identity.

**Comment by Cyantime** [comment]
Relevent line is here https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/living/carbon/carbon.dm#L164

**Comment by Renkindle** [comment]
Still shows up for others if you're fully clothed and making sure you're not bruised.
