### ISSUE TITLE
Brig walkway does not show prisoners breaking outer windows

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1898]
#### Brief description of the issue
Exactly as the title says; when watching a prisoner from the catwalk, the outer windows are obscured and you recieve no messages that the prisoner is even doing anything suspicious.

#### What you expected to happen
For me to be alerted to the fact he broke 2 of the three layers of glass.

#### What actually happened
I only got alerted when he got shocked by the grille.

#### Steps to reproduce
- Have an escape-happy prisoner
- be on the catwalk
- Note how nothing seems to be amiss until they get through half the defenses

#### Code Revision
- 861edd2c42e78d3b8327d42c2067fe5346a563b1 
 
#### Anything else you may wish to add:
- N/A

**Comment by SpadesNeil** [comment]
Don't let them have things they can break out with, then.

That said, I think I should mess with window code a bit so objects with small attack force can't damage windows at all.

**Comment by Vorrarkul** [comment]
I wasn't aware he was attacking the window at all, even though I could see him from above. And he only had what he could get from in the brig itself, but we both know that there's plenty of stuff in there to break out with.
