### ISSUE TITLE
Obese weight lifting Bug

### ISSUE THREAD

**Issue by NadezdaFex** [VOREStation/VOREStation#192]
#### Brief description of the issue

when working out on exersize equipment or punching the bag, you loose weight but still turn to "morbidly" obese. 

#### What you expected to happen

to gain muscle mass? still lose weight but eventually gain due to growing muscles.

#### What actually happened

Working out made me overly fat.

#### Steps to reproduce

lift weights

**Comment by SpadesNeil** [comment]
/mob/living/carbon/human/proc/examine_weight()
	    var/message = ""
	
	    switch(weight)
	        if(0 to 74)
	            message = "<span class='warning'>They are terribly lithe and frail!</span>\n"
	        if(75 to 99)
	            message = "They have a very slender frame.\n"
	        if(100 to 124)
	            message = "They have a lightweight, athletic build.\n"
	        if(125 to 174)
	            message = "They have a healthy, average body.\n"
	        if(175 to 224)
	            message = "They have a thick, heavy physique.\n"
	        if(225 to 274)
	            message = "They have a plush, chubby figure.\n"
	        if(275 to 325)
	            message = "They have an especially plump body with a round potbelly and large hips.\n"
	        if(325 to 374)
	            message = "They have a very fat frame with a bulging potbelly, squishy rolls of pudge, very wide hips, and plump set of jiggling thighs.\n"
	        if(375 to 474)
	            message = "<span class='warning'>They are incredibly obese. Their massive potbelly sags over their waistline while their fat ass would probably require two chairs to sit down comfortably!</span>\n"
	        else
	            message += "<span class='warning'>They are so morbidly obese, you wonder how they can even stand, let alone waddle around the station. They can't get any fatter without being immobilized.</span>\n"
	    return message //Credit to Aronai for helping me actually get this working!

**Comment by SpadesNeil** [comment]
Your weight was 99.475 when this happened.

**Comment by SpadesNeil** [comment]
I see the problem. You were literally in between the two values. This is badly coded. I'll fix it.

**Comment by NadezdaFex** [comment]
ahh gotcha! thanks for letting me know
