### ISSUE TITLE
elevator override causes people to fall into the shaft

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1920]
#### Brief description of the issue
[1:35 AM] Kateryna: Aaaaaaaaaaaa
[1:35 AM] Kateryna: I found a glitch
[1:35 AM] Kateryna: If the elevator is over ridden
[1:36 AM] Kateryna: and someones in the door
[1:36 AM] Kateryna: You actually remain on the level
[1:36 AM] Kateryna: that you are on if you step into the shaft
[1:36 AM] Kateryna: when the elevator leaves the floor
[1:37 AM] Scree: Oh, is THAT what causes it?
[1:39 AM] Kateryna: Im not sure
[1:39 AM] Kateryna: In my experiance it does

#### What you expected to happen
Not that

#### What actually happened
That

#### Steps to reproduce
- Do that
 
#### Anything else you may wish to add:
Reported over discord. Needs testing.

**Comment by AeroWing** [comment]
I asked around and toyed with it myself. It seems that if a call to the lift is registered right as it is departing from the floor where it was called (tricky to reproduce but I got it to happen 3 times after countless attempts.) will occasionally pop the lift doors open as the lift departs, leaving an open path for someone to walk into and fall. Wonky activity is also noticed when the lift is triggered for express service (appropriate ID on the call button) and for firefighting mode (appropriate ID on the lift console), particularly when switching out of these modes back to normal service.

My thought on this would be that button abuse could be looked into. I proposed before over discord that maybe we should have a way to stop people from spam clicking the buttons. I have lost count of times where I am on the lift or waiting for it to arrive and get to watch another crew member flood the chat with 'x presses lift button' or 'x smashes lift button frantically'. Maybe we can do something like if you press it >x times over y time then it will shock you or something? I'll start attaching screenshots of players I see doing this so show how annoying the chat spam can get from spam clicking.
