### ISSUE TITLE
Slime's unable to select hair

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#1922]
#### Brief description of the issue
You can't change your hair on the character preference menu.

#### What you expected to happen
Be able to style my slime into vaguely hair-like shapes.

#### What actually happened
Have a head resembling a dick.

#### Steps to reproduce
- (Step 1) Character Preference
- (Step 2) Click hair style
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 861edd2c42e78d3b8327d42c2067fe5346a563b1 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I demand tribute of 1 monkey.

**Comment by Yoshax** [comment]
They have a verb in game that let's them change their hair whenever they please.

**Comment by Cameron653** [comment]
The bug as found. It occurs when you select custom species, set the icon-base to custom species, then swap back to another race.
