### ISSUE TITLE
Micros not having recoil effect.

### ISSUE THREAD

**Issue by DexterDude** [VOREStation/VOREStation#1923]
#### Brief description of the issue
Micros are apparently immune to recoil.

#### What you expected to happen
Micros to not have immunity to recoil.

#### What actually happened
Micros have immunity to recoil.

#### Steps to reproduce
- (Step 1) Remove the code for micro recoil.
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by kcin2001** [comment]
Those are terrible steps to reproduce
