### ISSUE TITLE
Cryo deletes Teshari-specific gear from loadout

### ISSUE THREAD

**Issue by Renkindle** [VOREStation/VOREStation#1925]
#### Brief description of the issue
 - After going into cryo, Teshari lose their species-specific gear from their loadout, causing the player to have to reselect it.

#### What you expected to happen
 - To keep everything in my loadout after going into cryo.

#### What actually happened
- I lost my undercoat and cloak, and had to reselect them in the loadout screen to have them back.

#### Steps to reproduce
- Be Teshari with smock/cloak/undercoat/whatever tesh-exclusive xenowear item you want
- Go into cryo
- Respawn
- Check loadout in character setup
- Abracadabra where the fuck did it go

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/861edd2c42e78d3b8327d42c2067fe5346a563b1
 
#### Anything else you may wish to add:
- Happens in cryo specifically, not tram/teleporter.
- Apparently, Vox going into cryo _also_ lose their species-specific gear from their loadout. (Don't have one so I can't test this myself.)
- My cloth footwraps stayed on, so I'm fairly sure it's just species-specific items, not just xenowear in general.

**Comment by HawkerTheGreat** [comment]
I can second this - it seems to happen whenever Takkkri leaves via the Cryo pods, all gear stays the same in loadout, but I have to check my race-specific gloves/boots in xenowear. I don't doubt its a problem with xenowear as a whole, aswell...

**Comment by HawkerTheGreat** [comment]
Usually only Cryo.

**Comment by SpadesNeil** [comment]
Still an issue?

**Comment by Arokha** [comment]
Don't think this is a real thing.
