### ISSUE TITLE
smoking pipes and cigars

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#1931]
#### Brief description of the issue
Smokeing pipes and cigars no longer have 'on mob' icons any more.

#### What you expected to happen
to see that fancy corncob pipe I painstakingly carved my self with a hatchet.

#### What actually happened
The pipe is invisible on my face

#### Steps to reproduce
- (Step 1)get cigar/pipe
- (Step 2)apply to mask slot
- (Step 3)cry from nothing changing

#### Code Revision
Server revision: release - 
861edd2c42e78d3b8327d42c2067fe5346a563b1

**Comment by SpadesNeil** [comment]
I am almost certain this is fixed. Is it?

**Comment by Tasald** [comment]
No, they still don't show up when worn.
