### ISSUE TITLE
Alraune Fluff bugs: Taurbulb *vwag, uniform, directional.

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1949]
Edit: Added # 5.
#### Brief description of the issue
1: Closed petal state doesn't hide bag/ears
2: Closed state broadcasts "x has started wagging their tail" (Makes sense, as it uses *vwah to switch. Not really a problem, but mentioning it~
3: The Vine uniform doesn't have sprites when equipped
4: West-facing direction's taur sprite is misaligned
5: Ears are transparent

#### What you expected to happen
1: To have bags and ears hidden by the petal
2: Either a lack of message at all when toggling state, or a "X's flower petals close over them/X's flower petals lowers." or something. Again, this one's not really a problem I don't mind it :3 
3: For the uniform to have sprites
4: The flowertaur being aligned
5: Ears to be solidly colored

#### What actually happened
1: Items and ears aren't hidden by the flowerbulb when it's closed (tested with in-hand sprites too)
2: Toggling state claims I have a tail!
3: The uniform is just a cool nudity permit.
4: Looking west moves the taurbulb sprite one or two pixels east
5: Ears, because of the Promethean base, are transparent rather than solid.

#### Steps to reproduce
- (Step 1) Equip Alraune unform, use the ears and taurflower
- (Step 2) Uniform has no sprite, ears and bags show through the taurflower, and looking west misaligns
 - (Step 3) Use ears with a promethean base, they'll be transparent

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 74caf553d59232f6e56f005c64a66bcabf980200 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Closed state showing ear and bag: https://puu.sh/x4WqA/49f1faa9cd.jpg

**Comment by Cameron653** [comment]
I think I know how to fix it. Moving the taur bulb west one or two to match will be easy, and increasing it's layer by a few should also fix it.

**Comment by Natje0** [comment]
Yeah, that sounds like it would fix it!
Edit: Added #5, the ears are transparent due to the base body used.

**Comment by Cameron653** [comment]
Hmm, not sure how to raise the taur tail layer, after taking another look at it, so that's something that'll need to be addressed at another time.

Fixing the sprite being too far to the east is a real easy fix, however.
