### ISSUE TITLE
Xenochimera Hardsuits

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#1956]
#### Brief description of the issue
Xenochimera can only wear either Scree's special hardsuit which is not avaliable to anyone but Scree, or Rigsuits and Softsuits

#### What you expected to happen
To be able to wear any hardsuit

#### What actually happened
None fit my species and had to wear a RIG or soft suit

#### Steps to reproduce
- (Step 1)Be Chimera
- (Step 2)Try to put on a hardsuit
- (and so on) Cry as only Rigs, soft suits or one specific made suit works,

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SilverTalismen** [comment]
This bug is also fixed currently with Xenochimera hardsuits being avaliable.

**Comment by Screemonster** [comment]
Closing as per above comment.
