### ISSUE TITLE
Open space item ghosting and duplication.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#1959]
#### Brief description of the issue
Removing items from your person over open space creates a ghostly item on the bottom-most z-level exposed by that open space.

#### What you expected to happen
Pretty sure you know.

#### What actually happened
The issue described.

#### Steps to reproduce
- Wear an item standing over normal turf.
- Move to a catwalk/lattice and remove an item. Keep it in your hand. 
- Move to the bottom-most z-level.
- Get spooked. Picking up that item in your other hand removes the first item you just took off.
I don't know how I did it, but you can completely duplicate items that change states like welding goggles and such.

#### Code Revision
- cf3b3a66adc7c2451ef5eef91b06e88851f6d7b4

**Comment by SpadesNeil** [comment]
Could have sworn we fixed this. Did we?

**Comment by Jakksergal** [comment]
I'll test again sometime in the future.
