### ISSUE TITLE
Cryo'd Crew's Genetic Scans Remain After Cryo-ing

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#196]
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: release - 2016-05-23
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
https://github.com/SpadesNeil/VOREstation/pull/682

Should probably be pushed upstream too if possible.

**Comment by FirstSgtDan** [comment]
Hmm... isn't that what's supposed to happen? If I get cryo'ed and come back in the same shift, is my genetic data supposed to be gone?

**Comment by SpadesNeil** [comment]
You cryo if you do not intend to come back, so yes this is intentional.

**Comment by Screemonster** [comment]
https://github.com/MagmaRam/Polaris/commit/cd3d593dfc062332310f1ded47b36c8c3b185dca

Fixed upstream, may need testing at our end.

**Comment by Screemonster** [comment]
Okay, played a shift of medbay and some people are listed who definitely left via cryo.
