### ISSUE TITLE
Off for a joy ride on the Zero G Trolly

### ISSUE THREAD

**Issue by HawkerTheGreat** [VOREStation/VOREStation#1968]
#### Brief description of the issue

I have no idea if this is normal, but apparently the trolly breaks the laws of physics, because it can just drive in the air wherever it wants to as if its some sort of space craft... The Other carts don't seem to follow it, however.

There is no better physics than this.

#### Code Revision
Release - cf3b3a66adc7c2451ef5eef91b06e88851f6d7b4 

![image](https://user-images.githubusercontent.com/9869250/29148100-011032f2-7d31-11e7-97e0-26dc33489986.png)

**Comment by Cyantime** [comment]
See #1774

**Comment by HawkerTheGreat** [comment]
I'm pretty sure this is a polaris bug, So I'll forward it to them.

**Comment by SpadesNeil** [comment]
Polaris doesn't use multi-Z if I recall

**Comment by Ketrai** [comment]
Pft, this bug has been around for a while now, it's not just trolleys, it's mechs too, etc etc
