### ISSUE TITLE
Colorable body patterns

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#197]
Talking with Poojawa in Discord gave me a neat idea. Could we have a layer on our sprites that colors our body's skin to have patterns? Spots, stripes, blotches of color, etc.

Imagine how Holly Sharp would look with tiger stripes!

https://gyazo.com/7d420ea40abc34c1761305bc89a54a62

**Comment by Screemonster** [comment]
We were talking about this in adminchat the other day.

I kinda figured it'd be easy enough to do if we just used the same code that renders underwear onto sprites.

If this gets added I'll probably tweak the tajara sprites to make them uniform colour and implement the light-coloured belly/muzzle as a markings thing.

**Comment by Arokha** [comment]
Um. I supppoooooseeeee this is possible? Someone's gotta sprite it.

**Comment by Poojawa** [comment]
The way to do this is actually hinted at in the Vulpkanin PR

what's the one thing one human males get access to?

Facial hair. Which applies to a hard layer already coded in. Just hijack it using a light grey alpha layer, bam, second layer... just watch out for razors

**Comment by SpadesNeil** [comment]
Did this ever get finished?

**Comment by Arokha** [comment]
d o n e
