### ISSUE TITLE
Borg flavor text is not visible

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#1977]
#### Brief description of the issue
You can't examine the flavor text of a cyborg.

#### What you expected to happen
Examine borg, get flavor text

#### What actually happened
Nothing

#### Steps to reproduce
Be a borg, set your flavor text, examine self or have others examine you.

#### Code Revision
65f327472204df85b8f1da241685c8ac31e01e62

**Comment by SpadesNeil** [comment]
This is a polaris bug I think.

**Comment by Cyantime** [comment]
I'm near 100% sure that flavor text was working after the polaris sync, it only stopped working a few updates after.

**Comment by Cyantime** [comment]
Checking a bit more, this also affects pAIs, and I'm almost certain it was caused by #1962

**Comment by SpadesNeil** [comment]
Marked "Hotfixed" since the issue isn't 100% solved.

**Comment by Arokha** [comment]
I've been examining borgs all up in the place and reading about how doggy they are so I assume this works.
