### ISSUE TITLE
Fire/Phoron/Atmospheric alarms being very subtle and one time only

### ISSUE THREAD

**Issue by SariNeruda** [VOREStation/VOREStation#1988]
#### Brief description of the issue
Fire/Phoron/atmospheric alarms are quiet and only go for the initial trigger

#### What you expected to happen
To be loud enough to grab your attention, and to perhaps trigger every 15-30 seconds after the initial alarm

#### What actually happened
the alarm was very subtle and not very alarming, not grabbing attention and never sounded again

#### Steps to reproduce
- (Step 1) release phoron/start a fire (please dont)
- (Step 2) listen to the alarm (its very subtle) and not hear anything after the initial sounding. 

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
5535500b51f513d884e44c8787032746235b841a

**Comment by Arokha** [comment]
All of the areas flash red/blue for the duration, which should be a pretty good hint. The sound would probably just be annoying to repeat forever, and it's generally very loud whenever I hear it, even at half volume.
