### ISSUE TITLE
Daemon Language is gone

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#199]
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by antsnap** [comment]
Bring back Daemon 2016++

**Comment by SpadesNeil** [comment]
No. c:

**Comment by antsnap** [comment]
Why?

**Comment by Somekindofpony** [comment]
Why not just lock it to people who actually play demons?

**Comment by SpadesNeil** [comment]
Needs to be coded first but we can do that.
