### ISSUE TITLE
borgs are unable to whisper or subtle

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1992]
#### Brief description of the issue
the lack of being able to whisper or subtle as a borg is a bit restrictive when it comes to rp

#### What you expected to happen
to be able to whisper and subtle

#### What actually happened
nothing

#### Steps to reproduce
- (Step 1) be a borg
- (Step 2) subtle or whisper
- (Step 3) fail

#### Code Revision
- 5535500b51f513d884e44c8787032746235b841a 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
I've been playing borg a bunch lately, and subtle works just fine for me, but whispering does nothing.

**Comment by kcin2001** [comment]
When i made this neither worked
