### ISSUE TITLE
Resisting mob stomachs doesn't work

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1998]
#### Brief description of the issue
Resisting from a mob gut should get you spat up.

#### What you expected to happen
See above.

#### What actually happened
"You struggle inside the (X)'s stomach..." And no other text.

#### Steps to reproduce
- Get eaten by a mob.
- Resist until you get something other than making its stomach rile up or failing to escape.
- Fail to escape anyway.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/78f2ee4939d7293ace6d2b3698bae30c8c3a2a53

**Comment by Screemonster** [comment]
Resisting works, it's just that the escapetime is _fucking ages_ on default mob bellies and if you mash resist again after _not_ getting the "you fail to escape" message, it resets it (or even cancels if you fail).

**Comment by SpadesNeil** [comment]
It's never worked as far as I know.
