### ISSUE TITLE
Pred snack vending machines

### ISSUE THREAD

**Issue by antsnap** [VOREStation/VOREStation#200]
We have food vending machines. Maybe make a vending machine in bar/cafeteria that dispenses monkey/sergaling/whatever cubes. Maybe you can put a coin in for a whole box, hack it for a monkey-human.

It'd be neat. Saves having to bother cargo/science/medical.

**Comment by SpadesNeil** [comment]
No, because it eliminates the need for cargo and the need for xenobiologists to manage slimes.
