### ISSUE TITLE
DSI Sergal parts are still the old ones, not the new ones

### ISSUE THREAD

**Issue by Renkindle** [VOREStation/VOREStation#2001]
#### Brief description of the issue
When choosing the full-body DSI Sergal prosthetic, the parts for the old sprites, not the newly fixed ones, are used.

#### What you expected to happen
The character to look visually identical to the new sergal sprites.

#### What actually happened
The sprite changed to the old, unfixed sergal sprite.

#### Steps to reproduce
- Go into Character Setup
- Make your character have the full-body DSI Sergal prosthetic
- Look in awe as the old sergal body makes a return

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/78f2ee4939d7293ace6d2b3698bae30c8c3a2a53

**Comment by Verkister** [comment]
A fix is now waiting for merge.

**Comment by Renkindle** [comment]
Alrighty, gonna close this then.
