### ISSUE TITLE
Mis-locked maintenance door near security

### ISSUE THREAD

**Issue by Gearshy** [VOREStation/VOREStation#2010]
#### Brief description of the issue
One of the maintenance doors near security doesn't open to engineers.

#### What you expected to happen
Maintenance doors to open to maintenance personnel.

#### What actually happened
Surprise, door's locked.

#### Steps to reproduce
- Be an engineer.
- Go to the security substation.
- Try to open the maintenance door to get at the wires.
- Get denied.

#### Code Revision
- Server revision: release - 1ac332b905f5803f979f03dc1e03ee075c2f6c3b 
 
#### Anything else you may wish to add:
![sharex_2017-08-14_14-34-03](https://user-images.githubusercontent.com/26077635/29271911-1c98daee-80fe-11e7-8b20-416a882c9673.png)

**Comment by SpadesNeil** [comment]
That door is supposed to be locked. There's other ways into that area. The air lock is Security use only.

That said, it occurs to me, "What if Engineering needs to use the airlock?" I can change this.
