### ISSUE TITLE
Sleeving, Wings and You

### ISSUE THREAD

**Issue by SubberTheFabulous** [VOREStation/VOREStation#2011]
#### Brief description of the issue

Unlike ears and tails, wings are not being copied to a new body, leaving character without them.

#### What you expected to happen

Be cloned, and still have wings on.

#### What actually happened

Been cloned, but don't have wings on.

#### Steps to reproduce
- Have wings.
- Be died.
- Be cloned.
- Not have wings.
- Be sad.
#### Code Revision

1ac332b905f5803f979f03dc1e03ee075c2f6c3b
 
#### Anything else you may wish to add:

I'd assume, it's an issue with Body Design Console.

**Comment by Cameron653** [comment]
Writing down info for later reference:

Resleever stuff:
https://github.com/VOREStation/VOREStation/blob/8c272af0beb6b50abab41c1d4afa854bd27f6828/code/modules/resleeving/infocore_records.dm#L176-L197

Wings need to be included here: 
https://github.com/VOREStation/VOREStation/blob/9e267c8f9f8b01b3014de86eb74bd98a50fc020d/code/modules/vore/persist/persist_vr.dm#L135-L141

That should be it. Will probably fiddle w/ this later.

**Comment by KotetsuRedwood** [comment]
May be relevant: I've noticed that when I get resleeved, my ears come out a slightly wrong colour as well.

**Comment by Cameron653** [comment]
That would most likely be due to persist_vr lines referenced above not having 

r_ears
g_ears 
b_ears 
r_ears2 
g_ears2 
b_ears2

**Comment by Verkister** [comment]
#2524
