### ISSUE TITLE
Digesting too many mice at once causes lag and other issues.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#2013]
#### Brief description of the issue
Digesting an obscenely large amount of mice. (30+) at once causes server issues

#### What you expected to happen
Digesting 86 mice at once to just cause ear rape, nothing more.

#### What actually happened
35 seconds of lag, doors bugging out for some people.

#### Steps to reproduce
- Eat shitton of mice
- Get a belly ache
- Break the server
 
#### Anything else you may wish to add:
- May want to like, make digestion select a random amount of prey for digesting? so you can't like, digest more than 10 at once?

**Comment by SpadesNeil** [comment]
probably a good idea to set a cooldown on this yea

**Comment by Arokha** [comment]
Bellies are a subsystem now and will handle this nicer.
