### ISSUE TITLE
Cyborg Recharging station lacking powercells

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#202]
#### Brief description of the issue
The two Cyborg recharging station in mech bay spawn with no power cells
#### What you expected to happen
The recharging stations to have power
#### What actually happened
They show no power supply or even dedicated power source aka power cell
#### Steps to reproduce
They are generated on the map that way but only the two in mech bay
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
release - 2016-05-23
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
It only seems to be the two in mech bay that i have seen

**Comment by SpadesNeil** [comment]
>Steps to reproduce
>They are generated that way

Wait, what?

**Comment by Techtypes** [comment]
yes they laterally spawn with no power-cell resulting in 0% charged from start of the shift to end

**Comment by SpadesNeil** [comment]
So, let me get this straight. You enter the pod and it actually REMOVES your charge?

**Comment by Techtypes** [comment]
Just the charger it's self has no power-cell  this dos not effect to charging things unless power goes out I believe, am not playing a borg right now so i cant be sure if it dos effect borgs. 
Also will be updating the fabricator deconstruction bug to be called just deconstruction bug.

**Comment by SpadesNeil** [comment]
![samuel-johnson-cant-believe-what-just](https://cloud.githubusercontent.com/assets/6484985/15479027/23627286-20ec-11e6-8a83-725e9b97157c.jpg)

And like that you've lost me. I don't understand this at all. Why does the cyborg _recharger_ need a power cell?

**Comment by DemicusMaximus** [comment]
Rechargers don't come with power cells normally, unless this is a feature added by the Polaris team. There APC's power cell IS the redundancy for the area.

**Comment by Techtypes** [comment]
The recharger stations have the power-cell so for say the power goes out or gets cut for some reason the borgs can still recharge do to the built in power supply, and is one of the required components to the building processes in game.

I know is a small thing but check any other recharger as i just did most of them on the map and they do have power cells, i am just reporting the issue the two of them have.

**Comment by DemicusMaximus** [comment]
Just checked and you're right. They should have a high-capacity cell inside.

**Comment by SpadesNeil** [comment]
Now I get it. Okay. I'll try to correct this.

**Comment by SpadesNeil** [comment]
This is not a map issue. I'm pretty sure they're all like this.
