### ISSUE TITLE
Anomalous Omni Gas Filter behavior

### ISSUE THREAD

**Issue by Gearshy** [VOREStation/VOREStation#2021]
#### Brief description of the issue
Certain changes made to a gas filter's config seem to make the filter to direct gas flows in ways that don't match up with said config.

#### What you expected to happen
Gas filters to work and accept mid-round reconfiguration without hiccups.

#### What actually happened
Engines getting starved of coolant by the hot loop getting entirely drained into the waste loop.

#### Steps to reproduce
- Set up a gas filter.
- Apply a legitimate configuration, switch it on then off again.
- Alter the gas filter's configuration by pressing the input/output buttons to swap connection purposes.
- All the gas flows into the output (and/or seemingly random ports when filtering out two different gasses simultaneously)

#### Code Revision
- Server revision: release - 1ac332b905f5803f979f03dc1e03ee075c2f6c3b 

#### Anything else you may wish to add:
For some reason, it seems actually using the gas-to-filter selector seems to make the filter work properly again?

**Comment by Anewbe** [comment]
I'm almost certain that we fixed this a while ago, or that it never happened on Polaris.
