### ISSUE TITLE
FAT MOUSE SPRITES

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#2022]
#### Brief description of the issue
WE LACK SPRITES FOR A FATMOUSE.  I HAVE MADE SOME.

#### What you expected to happen
TO SEE THE GLORY THAT IS FATMOUSE.

#### What actually happened
MERELY A GIANT NORMAL MOUSE.

#### Steps to reproduce
- ATTEMPT TO MAKE FATMOUSE.
- MAKE A PATHETIC RECREATION INSTEAD BY TURNING A NORMAL MOUSE GIANT.

#### Code Revision
Server revision: release - 
1ac332b905f5803f979f03dc1e03ee075c2f6c3b 
 
#### Anything else you may wish to add:
- I HAVE ATTACHED PICTURES OF AND A DMI FOR PROPER FATMOUSE SPRITES.
![fatmaus3](https://user-images.githubusercontent.com/19196710/29330189-44bf8f90-81ad-11e7-8419-8faee6b71bb3.png)
![fatmous4](https://user-images.githubusercontent.com/19196710/29330185-42998798-81ad-11e7-8949-d4841f116cd6.png)
![fatmous5](https://user-images.githubusercontent.com/19196710/29330187-42a1b01c-81ad-11e7-805a-bbf4b1491833.png)
![fatmous6](https://user-images.githubusercontent.com/19196710/29330186-429ba7e4-81ad-11e7-88e1-83c7a762556e.png)

[fatmouse.zip](https://github.com/VOREStation/VOREStation/files/1225983/fatmouse.zip)

**Comment by AeroWing** [comment]
Here is a proper description for  FATMOUSE:

http://i.imgur.com/6z4fdN2.png

**Comment by Earthcrusher** [comment]
Hey I stole your mouse. Was it okay that I stole your mouse?

**Comment by SpadesNeil** [comment]
>The code for VOREStation is licensed under the GNU Affero General Public License version 3, which can be found in full in LICENSE-AGPL3.txt.

yes

**Comment by Earthcrusher** [comment]
cool
