### ISSUE TITLE
Duplicated areas in engineering.

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#2028]
#### Brief description of the issue
There are separate rooms in the new engineering that share an area.

#### What you expected to happen
Each room to have its own area.

#### What actually happened
The Engine SMES room uses the Engine Gas Storage area, and the room next to the lobby with the computers uses the same Engine Monitering Room area as the actual monitering room next to the engine room. Each area has two APCs because of this.

#### Steps to reproduce
Go to described rooms, see area name by checking APC or air alarm names.

#### Code Revision
9614a97f946a3722ebacc2ce4f3cc61593a0acc9 
 
#### Anything else you may wish to add:
@Jakksergal

**Comment by Jakksergal** [comment]
I am quite possibly the most disorganized person alive. Thanks for making an issue ticket instead of screaming at me on Discord.
