### ISSUE TITLE
Non-colorable Inkling Hair

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#2030]
#### Brief description of the issue
The Ears option "colorable mature inkling hair" is not actually colorable. There is no color selection option when the hair is chosen, nor does changing the character's hair color change it.

#### What you expected to happen
To be able to color the Inkling hair, either on the VORE tab itself or by changing my character's hair color.

#### What actually happened
I couldn't color the Inkling hair, nor did changing my character's hair color change the Inkling hair color.

#### Steps to reproduce
- Make a character (or select one you've already made)
- Go to the VORE tab in the character creation menu
- Select "colorable mature inkling hair" under Ears
- Notice that no color-changing option appears for this hairstyle
- Attempt to change your character's hair color under the General tab
- Watch as the Inkling hair remains black

#### Code Revision
9614a97f946a3722ebacc2ce4f3cc61593a0acc9 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment]
This was fixed
