### ISSUE TITLE
Error while loading Random Gateway Z Levels

### ISSUE THREAD

**Issue by Avuds** [VOREStation/VOREStation#2032]
[04:00:00] Runtime in zlevel.dm,44: Cannot execute .load map().
  proc name: createRandomZlevel (/proc/createRandomZlevel)
  src: null
  call stack:
  createRandomZlevel()
  world: New()

**Comment by SpadesNeil** [comment]
Gateway maps aren't set to load currently. If you're running your own server to run gateway maps they can't be larger than the main map.

Please include a server revision.
