### ISSUE TITLE
doing something with xenohybrids

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#2035]
xenohybrids are currently unused and slightly uneeded, so we need to do somewith with them,
unwhitelist them
remove them and add them to the sprites of custom species 
add features to their species
something else suggested
or a combonation of the options

**Comment by kcin2001** [comment]
personally i want to do a combo of the custom species one and add features

**Comment by Arokha** [comment]
Probably not, no. People are whitelisted for them.
