### ISSUE TITLE
PAI communicator. 

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#2039]
#### Brief description of the issue
The PAI communicator does not work properly. 

#### What you expected to happen
Be able to operate the built in communicator in PAIs. 

#### What actually happened
The interface can be opened but not interacted with at all. 

#### Steps to reproduce
- Be a PAI. Get a communicator message. 
- Open your communicator. Be unable to interact with any of the buttons in it. 

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Is this still a problem? You left no code revision.

**Comment by SpadesNeil** [comment]
No code revision.
