### ISSUE TITLE
The Colony Director's space helmet isn't airtight.

### ISSUE THREAD

**Issue by Dingosilver** [VOREStation/VOREStation#2040]
#### Brief description of the issue
The space helmet, while protecting against pressure damage, is not airtight and does not protect against phoron blindness.

#### What you expected to happen
Having a space-proof helmet allowing the director to move around outside with a meson goggle+emergency gas mask combo, without having to wear a full gas mask to cover the face.

#### What actually happened
Turns out mesons aren't airtight, and every time I'd worn them under mining voidsuit helmets I wasn't blinded because the voidsuit helmet was airtight. And turns out the CD's space helmet is space-proof, but not airtight. Somehow.

#### Steps to reproduce
- Wear the colony director's space helmet
- Go outside expecting it to protect you from eye damage
- Cry as you're immediately blinded

#### Code Revision
- 4230069a59f5e135eb1b8a5ece0d8509c01cefd4

**Comment by SpadesNeil** [comment]
Not a bug. Wear the full face gas mask that comes with it.
