### ISSUE TITLE
DSI Lizard Torso Sprite Error

### ISSUE THREAD

**Issue by Xindii** [VOREStation/VOREStation#2043]
#### Brief description of the issue
There are two white pixels that appear on the character's shoulder sprite when facing 'north' when using the DSI Lizard full body prosthetics (See link below)

#### What you expected to happen
I expected there not to be two glaring white pixels following my character around.

#### What actually happened
Two glaring white pixels followed my character around. Only visible when facing 'north'.

#### Steps to reproduce
- (Step 1) Make a FBP character using the DSI Lizard option.
- (Step 2) Look at Character Preview or in-game.

#### Code Revision
4230069a59f5e135eb1b8a5ece0d8509c01cefd4 
 
#### Anything else you may wish to add:
- Screenshot of said pixels in char-setup. http://i.imgur.com/WoB7hu2.png

**Comment by Verkister** [comment]
Fixened a while ago.
