### ISSUE TITLE
Monsters are explosion proof

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#2048]
#### Brief description of the issue
Monsters don't seem to take explosion damage

#### What you expected to happen
The phoron dragon we tossed a grenade at to die instantly (240 u water + potassium reaction)

#### What actually happened
It looked to have taken no damage

#### Steps to reproduce
Find monster
throw grenade
watch them not die.

**Comment by Cyantime** [comment]
Simple animals take 30 damage from light explosion effects, 60 from heavy, and 500 and gib from dev.
Dragons hanging around the wilderness have 200 health, so unless it was standing nearly on top of the grenade there wouldn't be any visible effect.
See https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm#L639.
