### ISSUE TITLE
AI unable to view through hardsuit cameras/other worn cameras

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#2049]
The only cameras the AI can see through are station and cyborg cameras, and cyborg cameras seem to lag behind when the cyborg is moving (Which I can understand).

When someone's wearing a hardsuit with a camera, the AI cannot view through the camera. Although they can click their name in the chat to track them, the screen only shows static unless the character moves within normal camera range.

**Comment by SpadesNeil** [comment]
This is an old known bug but it's a nightmare to fix.
