### ISSUE TITLE
Body Design Console Tails are actually Wings

### ISSUE THREAD

**Issue by Renkindle** [VOREStation/VOREStation#2050]
#### Brief description of the issue
Wanted to mess around with the body design console in-round to see if my character could get resleeved into a new body. I clicked tails on it, and it gave me the wings options instead.

#### What you expected to happen
To be able to select tails.

#### What actually happened
All I got was the menu for wings.

#### Steps to reproduce
- Go to medbay
- Open body design console
- Click on tails
- Watch as wings menu shows up instead

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/f4006f65d047af977cd5ba5e015caf706af8cb14
 
#### Anything else you may wish to add:
- https://cdn.discordapp.com/attachments/182236468180287488/349739045368233984/unknown.png

**Comment by Cameron653** [comment]
Found the issue. Will patch soon.

https://github.com/VOREStation/VOREStation/blob/a2f346df0f549a5cea4293f8a5ebc1c1cbd3c57a/code/modules/resleeving/designer.dm#L118

**Comment by Renkindle** [comment]
Sweet, gonna close this then.
