### ISSUE TITLE
Window tint control for the HoP's office doesn't do anything.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#2056]
#### Brief description of the issue
The button in the HoP's office to control window tints doesn't do anything

#### What you expected to happen

for the button to blacken the windows
#### What actually happened
nothing

#### Steps to reproduce
Get in that fancy HoP office and hit the button
Be sad you can't get it to work, and go to ERP in the conference room instead
Try to explain to the CD that you're fucking in there because yadda yadda

**Comment by lbnesquik** [comment]
Still an active issue.

**Comment by Leshana** [comment]
Fixed ICly by Myryan Karnage-Cunningham, so may now be fixed on map.

**Comment by Cyantime** [comment]
I'd be impressed if it could be fixed IC, considering there is no way to interact with, build, or relink electrochromatic windows or their buttons.
