### ISSUE TITLE
Selectable Highlander and Flatland Zorren Tail/Ears are old unfixed sprites

### ISSUE THREAD

**Issue by Renkindle** [VOREStation/VOREStation#2059]
#### Brief description of the issue
Could have sworn both the highlander and flatland zorren tails and ears were supposed to be fixed to NOT be the same on both sides lately. **The flatland zorren ears are fine**, but the colorable tails and both types of highlander zorren ears are not. They show the inner ear on both sides when facing north and south.

In addition, both the colorable highlander/flatland zorren tails are the old sprites that stick up and have weird coloring.

#### What you expected to happen
To get the new sprites when selecting
- highlander zorren ears (colorable)
- highlander zorren ears
- highlander zorren tail (colorable)
- flatland zorren tail (colorable)

#### What actually happened
Old sprites that were the same from front/back came up for the ears, and the tails were the old ones that were held high and blindingly bright unless you made the color super dark.

#### Steps to reproduce
- Go into character creator
- Go to VORE tab
- Try to select the parts I mentioned earlier
- See as they're still the old sprites 

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/f4006f65d047af977cd5ba5e015caf706af8cb14

**Comment by Verkister** [comment]
Fixed?
