### ISSUE TITLE
Applying Krak-b-gone (silicate) to strengthen windows removes their sprite

### ISSUE THREAD

**Issue by Virgo113** [VOREStation/VOREStation#2065]
#### Brief description of the issue
Title.

#### What you expected to happen
The window to acquire a glossy sheen.

#### What actually happened
No more window. At least not visible, only clickable via alt-click turf viewer. From there, any update on the state of the window (which implies clicking the nonexistant sprite) will restore the sprite (e.g. use a screwdriver on it, bash it a bunch.)

#### Steps to reproduce
- Get Krak-B-Gone from the engineering vendor
- Spray reinforced window
- Wonder where the window went.

#### Code Revision
release - f4006f65d047af977cd5ba5e015caf706af8cb14

**Comment by SpadesNeil** [comment]
Still a bug? We updated recently.

**Comment by Cameron653** [comment]
https://github.com/VOREStation/VOREStation/blob/cc75893ba22920de22d5840457244ad2ebaa3fc4/code/game/objects/structures/window.dm#L77-L84

I think this is related.

**Comment by lbnesquik** [comment]
This is still a bug in the Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4
