### ISSUE TITLE
PDA network broken, even though PDA server is online.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#208]
#### Brief description of the issue
PDA server is on, but I can't PDA anyone.
![capture](https://cloud.githubusercontent.com/assets/6484985/15489523/7a73207e-212e-11e6-9c6f-c6fe905a0aa3.PNG)

#### What you expected to happen
When I open my PDA, I have a list of people to message.

#### What actually happened
PDA address book is empty.

#### Steps to reproduce
Open your PDA, open messaging.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

**Comment by SpadesNeil** [comment]
@Arokha @Leshana Either of you know why the hell this is happening? This is an extremely bad bug.

**Comment by Arokha** [comment]
Check in R&D? I mean there used to be a server in there, but also, one in the R&D computer room.

**Comment by SpadesNeil** [comment]
Why is a PDA server in R&D? I don't think that's correct. I'll look.

**Comment by Arokha** [comment]
Um. That’s ALWAYS been the case.

**Comment by SpadesNeil** [comment]
That is not the PDA server. That is a PDA console. The server is the box with the green light on it. Not the computer.

**Comment by Arokha** [comment]
I can't reproduce this on a test server. It was related to the global list "PDAs" becoming null rather than a list, but I can't find the cause, and the server did not log stack traces for whatever reason.

**Comment by SpadesNeil** [comment]
That's fucking weird. Oh well.
