### ISSUE TITLE
Tails and Skirts

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#2086]
#### Brief description of the issue
Multiple types of tails (stripey taj, colorable; stripey tag, brown; dragon, colorable; mouse, pink; mouse, colorable; horse tail, colorable; cow tail, colorable; avian fantail, colorable; avian wagtail, colorable; bee thorax; double kitsune tail, colorable; fennix tail; tiger tail (vwag); new vulptail (vwag); snake tail, colorable; sergal, dual-color; nevrean tail; nevrean tail, colorable; vulpankin, colorable) can be seen through the fronts of skirts (where they would normally be visible if the character was wearing pants). The tails not listed here do not show between the legs from the front, even when the character is wearing pants (or nothing at all).

#### What you expected to happen
For my skirt to cover my character's tail from the front.

#### What actually happened
It looks like I cut a slit into the front of my character's skirt or something so people can see part of their tail.

#### Steps to reproduce
- Create a character or load up a preexisting one
- Give them one of the tails listed above
- Give them a skirt via the loadout--the longer, the better
- Watch as your character's tail peeks out from the front of the skirt

#### Code Revision
d2c592cb48ad8ee18c7332c793945dd1e363dd14 
 
#### Anything else you may wish to add:
N/A

**Comment by SpadesNeil** [comment]
We really can't fix this in any practical way due to the way tails have to be layered. Unless someone has clever ideas I'm making this as wontfix.

**Comment by LittleBigKid2000** [comment]
I think this was fixed on Paradise, with this PR (If I'm not mistaken). I'm not sure if this was a clever idea or some madman doing the total rework, I'm not experienced with BYOND coding stuff.

https://github.com/ParadiseSS13/Paradise/pull/3195
