### ISSUE TITLE
Resleever doesn't do wings.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#2096]
#### Brief description of the issue
Get ate, get resleeved with no wings.

#### What you expected to happen
Be resleeved with wings.

#### What actually happened

No wings were resleeved.
#### Steps to reproduce
- (Step 1) Die.
- (Step 2) Have wings.
- (Step 3) Be resleeved with no wings.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cyantime** [comment]
Dupe of #2011

**Comment by Somekindofpony** [comment]
My mistake.
