### ISSUE TITLE
Riot Shields are held behind Taur Voidsuits

### ISSUE THREAD

**Issue by Neopatra** [VOREStation/VOREStation#2100]
#### Brief description of the issue
When wearing a taur voidsuit and holding a riot shield, the shield sprite is layered under the voidsuit, when it should be over it.

#### What you expected to happen
The riot shield to be held in front of you when standing.

#### What actually happened
You hold the riot shield in a very uncomfortable position behind you.

#### Steps to reproduce
- Wear taur voidsuit (Security confirmed)
- Pick up Riot Shield
- Examine how it appears behind you when facing south, instead of in front.

**Comment by SpadesNeil** [comment]
This is not possible to fix given how the layering system is, barring extreme changes.
