### ISSUE TITLE
Minor map niggles

### ISSUE THREAD

**Issue by Gearshy** [VOREStation/VOREStation#2106]
#### Brief description of the issue
A few things I wanted to add, since I was asleep during the spontaneous issue roundup.
1. Missing supply pipe near hydroponics, under a maintenance door. (Might've been fixed in #2105?)
2. Security department doors use 'Security Equipment' access (access_security) rather than 'Security' (access_sec_doors).
3. There are no suit cooling units or inflatables on hand in atmospherics.

#### What you expected to happen
1. Hydroponics to have air coming out of the vents.
2. HoPs, CMOs, RDs, CEs and IAAs to have access to security thanks to the appropriate category being on their IDs.
3. Essential equipment like that being available in atmos in case reaching space-engineering is unfeasible or flat out impossible.

#### What actually happened
1. Hydroponics isn't connected to the supply lines.
2. All the doors in security are keyed to a security and CD-exclusive category by default.
3. Nope!

#### Code Revision
- release - d127e06c0dcfb65be5a01c75ac6887c1ca3058c9 
 
#### Anything else you may wish to add:
- The missing supply pipe is under this door right here: https://puu.sh/xs5a9/2e6a53df2e.png

**Comment by Screemonster** [comment]
Are these all fixed?

**Comment by Gearshy** [comment]
#1 was fixed in #2113, #3 was fixed in #2147, but #2 hasn't been touched in any way, shape or form.

**Comment by Mewchild** [comment]
I'm fixing 2 right now

**Comment by SpadesNeil** [comment]
In future, please put unrelated issues in separate issue posts.

Being all map issues is not relevant enough to each other, as they are different map issues.
