### ISSUE TITLE
OOC notes broken on borgs and pAIs

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#2107]
#### Brief description of the issue
OOC notes link is unclickable for others as a borg. It however does open for the borg player themself, but does nothing for anyone else.
On pAIs they don't show up at all, but I'm not sure if it's restricted to the pre-download description to even begin with, but definitely is a feature that should exist.

#### What you expected to happen
OOC notes to be visible for other players.

#### What actually happened
OOC notes opened for the borg player, but showed absolutely nothing for anyone else.

#### Steps to reproduce
- (Step 1) Be a borg.
- (Step 2) Have OOC notes.
- (Step 3) Click the link and see it open up all fine.
- (Step 4) Have someone point out you have no OOC notes.
- (Step 5) Be the other player.
- (Step 6) Click on the borg's OOC notes.
- (Step 7) The computer says no.

#### Code Revision
- d127e06c0dcfb65be5a01c75ac6887c1ca3058c9
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
https://github.com/VOREStation/VOREStation/issues/2107

https://www.youtube.com/watch?v=QJFM86tgVxY

**Comment by AeroWing** [comment]
Sounds like it wasn't properly tested. @Funce you on this?

**Comment by Funce** [comment]
Oh god. Thanks for the heads up on this one. I'll have a look. I think it may have something to do with Topic calls though...

**Comment by Funce** [comment]
Yeeeeap. It's definitely exactly how you describe it. Only the Borg could possibly ever use that Topic call. Can fix.

**Comment by TheFurryFeline** [comment]
Hmmmm..... OOC Notes still don't save for pAIs..... It seems rather consistent. I save the 4 fields edited, a new round starts, and I look again and it's all freaking gone. x-x
