### ISSUE TITLE
Assembled thoughts on Atmosia.

### ISSUE THREAD

**Issue by Gearshy** [VOREStation/VOREStation#2109]
Okay. I have _thoughts_ regarding atmospherics. As in, pipe city itself. Here they are.

The good:
- **Atmospheric collector** - It's a neat idea, really. Being able to harvest the air outside for relevant gasses isn't something I've seen done. Its throughput isn't exactly enough to recover from an atmos reset, but it helps.

The neutral:
- **Loop-based gas filtering system** - Again not something I've seen before. In the atmos systems I have seen, the input pipes meet together and the various gas filters are arranged in a linear progression, removing them until there's nothing left in the final length of piping. Or volatile fuel, because that snowflake of a gas doesn't have gas filter support. Here, the gasses circulate in a loop and there's an exciting and varied blend of them in each section of piping. I'm not exactly sure how to judge which setup is better, so here it all is and hopefully somebody more knowledgable in atmos matters can weigh in.
- **Oxygen generators** - I kinda feel these are just slightly underbaked. From what I've seen, they stop working when their carbon stores reach 5,000 units (out of a stated capacity of 10,000), and they appear to slow down in response to high pressure on their input pipes, rather than the output? Probably could use a bugfix or two. Having more provisions for directing all of the CO2 from the intakes and/or stored CO2 would be nice too.
- **Pressure tanks** - Apparently the admins really don't want to use room-style gas tanks. I am more okay with that after some code digging - it seems that canisters have a volume of 1000L, tiles hold 2500L and a pressure tank carries... 10,000L?! Still, there is a bit of a bug with them - it seems tampering with the piping directly attached to them can make their contents just magically poof into nothing. IIRC, this happened specifically when attaching a regular pipe/manifold rather than a valve/pump. And there's the thing where triggering an atmos reset empties them. Can't exactly refill a room if there's literally no air available to do it.

The bad:
- **No temperature controls** - By default, none of the working pipelines have any sort of temperature control on them. Which becomes a bit of a problem when a fire happens or the atmospheric collector is switched on - in that case, the gas filters start pushing nitrogen and oxygen quite a bit away from 20C into the storage tanks, which generally pretty quickly throws the entire airmix reserve out of whack. And nobody likes breathing air that's cold/hot enough to freeze/boil water.
- **Pressure tank loadouts** - Let me put it this way. When doing my thing, filling all the pumps with lots of air, setting the air-mixing pump to 7500kPa and running the oxygen generators at a fair clip, I eventually ended up with ~1100kPa of nitrogen, and ~6500kPa of oxygen. That... is not quite a good gas ratio for mixing up more air. Ideally, the final figures would be a bit closer to the 79-21 ratio of nitrogen and oxygen in Earth's air. The other half of this is that our N2O and CO2 tanks are storing some serious pressure in them. In fact, so much of it that I genuinely have to question what we even need so much of those gasses for. But more on that in my next thing.
- **Bare filters** - Do you know how N2 and O2 tanks have gas pumps following the filters that push their appropriate gasses into them? Ideally, this would be the case for all the filters. They don't really have much pushing power, so when the pressure on the gas storage side is too high, the filters slow down all gas moving through them. In the case of phoron and especially CO2 and N2O storage, this leads to the waste line working at less than maximum speed, which can make things clog up. Of course, pumps can stall too, but it seems the only solution to that would be to use a special snowflake gas injector like the ones in the engine room and the Northern Star's 3x3 room-style gas tanks.
- **Phoron gas storage** - The way it's currently done is both way different from the other gas stores (where all the pressure tanks are connected with pipes and fed/depleted as a single unit), and fills to clogging quite quickly. The best solutions I came up with was to either put a whole bunch of canisters on the can line and use them for storage, or to replace the digivalves with pumps to force incoming phoron directly into the pressure tanks.
- **Pressure regulators for canister interactions** - The problem there is that a pressure regulator stops working once pressure on both of its ends is equal. This means that a canister can't be filled up to a desired target pressure if the pressure tanks drop below it, and a canister can't be emptied below the pressure the pressure tanks are already at.
- **Starts inert** - I remember once upon a time I got to watch somebody try to fill up a new room from distro when atmos wasn't touched by anybody. I had a good chuckle at their confusion, and then I had to walk them through making atmosia go. Ideally, not touching it would just lead to it working slower, rather than not work at all. So it would be nice if the pumps on the scrubber line and the lines leading to portables would start the shift switched on to some extent, and the pressure regulator leading away from the airmix tanks be replaced with something that starts the shift already open.

And there it is. Hopefully, this will be a decent place to start when planning out a revamp of atmospherics.

**Comment by Yoshax** [comment]
Don't forget the point where any time there's a fire and nobody has the foresight to turn basically all of atmos off your nitrogen supply is completely ruined and needs dumped.

Then you can't actually get new gas in from outside and dump waste to outside at the same time.
