### ISSUE TITLE
Zippo lighter invisible for the detective.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#2110]
#### Brief description of the issue
I'm not sure if anyone else can see it but, for me when I had the zippo lighter off, it was invisible, turning it on made if visible but, that requires constantly having an open flame when the atmos might become phoron from one mess up.

#### What you expected to happen
The zippo to always be visable.

#### What actually happened
The zippo was invisible when off.

#### Steps to reproduce
- (Step 1) Spawn as detective.
- (Step 2) Look at pockets to see nothing in it.

#### Code Revision
Server revision: release - 
d127e06c0dcfb65be5a01c75ac6887c1ca3058c9 
 
#### Anything else you may wish to add:
- MIGHT be something on my part but, just bringing it up incase it is not.

**Comment by Cameron653** [comment]
Will be fixed next sync.

**Comment by Anewbe** [comment]
This should be fixed by now.
