### ISSUE TITLE
People keep spawning outside

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#2117]
#### Brief description of the issue
People keep spawning in the southwest corner of the surface, and not being moved to one of the normal spawn points on the station.

#### What you expected to happen
That never to happen.

#### What actually happened
It happens occasionally.

#### Steps to reproduce
Unknown

#### Code Revision
d127e06c0dcfb65be5a01c75ac6887c1ca3058c9
 
#### Anything else you may wish to add:
Stuff that people can't equip on spawning builds up there, too
![spot](https://user-images.githubusercontent.com/29438599/30116892-aefaafc0-92ec-11e7-9c9f-ce257bc431df.png)
The default new-player spawn is usually under the title screen in a little box on most maps, that would probably help here.

**Comment by Yoshax** [comment]
This is caused by having no backpack.
