### ISSUE TITLE
Too many branches that could be cleaned

### ISSUE THREAD

**Issue by OrbisAnima** [VOREStation/VOREStation#2124]
#### Brief description of the issue
about 13 branches on the brannches tab, some are ok, either open or useful like release, master, etc.

but there are a lot of merged ones.

#### What you expected to happen
For the git to be clean

#### What actually happened
![image](https://user-images.githubusercontent.com/13823244/30231759-c3e689ea-94c2-11e7-8044-00c669f8308d.png)

#### Steps to reproduce
open git
go to branches

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
@SpadesNeil , clean it up!

**Comment by SpadesNeil** [comment]
dude please don't make PRs about this, it just adds to the mess
