### ISSUE TITLE
Prometheans Can't Wear Underwear

### ISSUE THREAD

**Issue by LSommers** [VOREStation/VOREStation#2134]
#### Brief description of the issue
Prometheans can have underwear selected in setup, but they are not visible.

#### What you expected to happen
To be able to have a promethean wear underwear.

#### What actually happened
Not that.

#### Steps to reproduce
- Plan out a googirl who doesn't understand white clothes + goo = eternal wet T-Shirt Contest
- Attempt to create this promethean, only to be unable to use undershirts
- Cry deeply

#### Code Revision
- Server revision: release - 
e0443cfb4b865c8561196af365d1aa78dede00b1 
 
#### Anything else you may wish to add:
- PLS

**Comment by chaoko99** [comment]
requesting priority 1. Enjoyment blocker.

**Comment by SpadesNeil** [comment]
You're made of goo. Undies will not work well. :U
