### ISSUE TITLE
Cash register UI error

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#214]
#### Brief description of the issue
This happened on the 23rd of May at around 16:00 GMT +1.
Grab item. Click on cash register with item. Item is scanned in and the order is placed.
I try to delete the order and interact with the cash register.
#### What you expected to happen
The order to be removed and me to unlock the cash register's cash box.
#### What actually happened
The interface did not respond at all.
#### Steps to reproduce
1. Grab item.
2. Scan item on the register.
3. Try to remove the order.
4. Remember that nobody can pay because you're an impatient dimwit.

#### Additional info:
 - **Server Revision**: Server revision: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add**

**Comment by Arokha** [comment]
Same as https://github.com/PolarisSS13/Polaris/issues/1452

**Comment by SpadesNeil** [comment]
Marking as duplicate since this exists in Polaris and is already reported.
