### ISSUE TITLE
Hardsuits and Centaurs

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#2142]
#### Brief description of the issue
When you activate the EMT hardsuit as a centaur, the hardsuit sprite that's supposed to appear over the taur part doesn't show up. However, when the suit is deactivated and you activate the chestpiece, that sprite appears. This is untested with other hardsuits and other taur types, however.

#### What you expected to happen
To have full centaur hardsuit coverage when the hardsuit is active.

#### What actually happened
It looks like my centaur half is uncovered if the hardsuit is active.

#### Steps to reproduce
- Be a centaur (or possibly another type of taur)
- Put on the EMT hardsuit (or possibly another suit)
- Toggle the hardsuit on
- Watch as your poor horse (or other taur) butt goes naked

#### Code Revision
- e0443cfb4b865c8561196af365d1aa78dede00b1
 
#### Anything else you may wish to add:
- Needs to be tested with other hardsuits and other taur types

**Comment by chaoko99** [comment]
Open and close the torso. This is a known issue.

**Comment by SpadesNeil** [comment]
Known issue that until now hasn't been reported so not actually known. :U
