### ISSUE TITLE
Prescription lens upgrade kits are missing from Medical.

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#216]
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: release - 2016-05-23
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

This is relatively minor, but until this is changed, anyone who plays a character that needs glasses? They can't wear welding goggles, security HUD's, medical HUD's, etc. So it hinders their ability to do the job effectively.

**Comment by SpadesNeil** [comment]
This was a feature I made for old Vorestation. I'll re-add it soon.

**Comment by Arokha** [comment]
There are proscription versions of the HUDs you listed that are available in loadout. They should probably just arrive on-station with one. o:
