### ISSUE TITLE
Camera tracking error when feeding a borg

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#217]
#### Brief description of the issue
when someone feeds a player to a borg the camera stays on who was holding them

#### What you expected to happen
the camera to be on the predator and not the one who fed the borg

#### What actually happened
the camera stayed on the person who was feeding 
#### Steps to reproduce
1. grab a micro
2. feed it to a borg
3. have one of them move to test your camera
#### Additional info:
only happens with feeding the borg a micro (the item version of the player)
to prevent this the people can use grab, upgrade, feed
as a note reconnect doesnt help

 - **Server Revision**: 3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

**Comment by Arokha** [comment]
You should probably not feed micros to borgs. It was never really intended that they be able to eat people, aside from using the K9 sleeper things. However they, like all /mob/living, have bellies now.

I'll probably disable the ability to feed people to borgs in a patch, letting them use the sleepers instead.

**Comment by SpadesNeil** [comment]
Needs testing again.

**Comment by Arokha** [comment]
Normal vore stuff with borgs (aka using the 'belly' system) is not supported. They need to use the sleepers. Digestion and lots of other belly functions deal with nutrition, which borgs lack, among other things.
