### ISSUE TITLE
Solargrubs lacks a check for ventcrawling into areas like the dorms

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#2184]
#### Brief description of the issue
Title.  Basically, solargrubs seem to be able to ventcrawl into places that should be blocked to them, like the dorms.  Or at least the holodorms.

#### What you expected to happen
Dorms to be safe from events like they usually are.

#### What actually happened
Solargrub popped up in a holodorm and interrupted a scene.

#### Steps to reproduce
- Solargrub event.
- Have one randomly ventcrawl into a dorm/holodorm.

#### Code Revision
- release - 30d353407955f4849d06c98ef496862de920c346 

#### Anything else you may wish to add:
- haha generic "seal the vents" message makin' everyone freak out
- ...Wait, shit, hold on.

**Comment by Cyantime** [comment]
@Ketrai

**Comment by ArgobargSoup** [comment]
Okay.  So.  I may have slightly jumped the gun.

The grub ventcrawled in.

**Comment by Ketrai** [comment]
Solargrubs should not spawn in the dorms, they must've crawled in yeah, sorry! :3

**Comment by SpadesNeil** [comment]
Or a check when they pop out of the vent that if they're in that spot, go somewhere else.

**Comment by Ketrai** [comment]
Please close this issue, it has been fixed.
