### ISSUE TITLE
SUGGESTION:  Revert mouse noises

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#2187]
#### Brief description of the issue
The new mouse noises are soul-crushing, and more importantly, INCREDIBLY LOUD.

And them emitting a noise on death?  Even more annoying.

#### What you expected to happen
_step on a mouse_  Oh hey, new mouse noise.  Interesting.
_kill a mouse_  Phew, one less pest.

#### What actually happened
_step on a mouse_  OH GOD MY EARS ARE BLEEDING.
_kill a mouse_  OH GOD MY EARS ARE BLEEDING.
OOC: What the fuck was that noise?

#### Steps to reproduce
- Step on a mouse and have your soul crushed and your ears blown out.
- Kill a mouse, have soul crushed, ears blown out, and people nearby asking what the hell was that noise.
- Digest a mouse, have soul crushed, ears blown out, and people nearby asking what the hell was that noise.

#### Code Revision
-  release - 30d353407955f4849d06c98ef496862de920c346 
 
#### Anything else you may wish to add:
- I fully expect someone to end up nommin' around 20+ mice, go to the bar, and kill everyone's eardrums when they hit digest.
- Honestly, could probably just reduce the volume of the noise and maybe reduce the range of the death noise, but it'd be really awesome if mice squeakin' on death was removed entirely in the process.

**Comment by LSommers** [comment]
Please for the love of fuck listen to this man's issue.
The new noises are like having the molten essence of a thousand fiery rodent holocausts poured into my ears through a funnel.

**Comment by Yewmi** [comment]
*sees this*
![sharex_2017-09-22_17-22-55](https://user-images.githubusercontent.com/22177874/30766535-58b249b2-9fbb-11e7-93e2-c985eaa4c08d.png)
*responds by doing this*
![2017-09-22_17-22-14](https://user-images.githubusercontent.com/22177874/30766527-50001f38-9fbb-11e7-8d76-57d15795f8fc.gif)

**Comment by SpadesNeil** [comment]
You're like those people who say, "Don't like OOC? Mute OOC." Because fuck people for enjoying other aspects of the game, rather than remove one shitty feature.

**Comment by ArgobargSoup** [comment]
@SpadesNeil They weren't sayin' that.  They were saying that now when they see a mouse, they have to mute the game because oh god it hurts their ears.

**Comment by SpadesNeil** [comment]
The implication to me looked like they were saying everyone else should do the same rather than fix a bug.

But if that's not what they meant, then disregard my comment.

**Comment by Yewmi** [comment]
@SpadesNeil I indeed meant that I just hate that noise. I'm physically sensitive to loud noises. Every time I join the server I have to either turn the volume super low or avoid maintenance entirely.
