### ISSUE TITLE
Financial accounts are awkward to audit as admins

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2188]
#### Brief description of the issue
There's currently no admin-equivalent of the accounts uplink terminal, which is ID-locked so we can't use it as ghosts when we want to check on things.

#### What you expected to happen
Something on the admin panel like the investigate logs for powernets or something.

#### What actually happened
I had to spawn an accounting terminal, an all-access ID and a guy to use them.

#### Steps to reproduce
- get a fax about financial weirdness
- be unable to actually verify it with an easy OOC button
- groan and go looking for somewhere quiet on the centcom level to spawn shit

#### Code Revision
Server revision: release - 
30d353407955f4849d06c98ef496862de920c346 
 
#### Anything else you may wish to add:
Just dumping an account terminal in the admin bit at centcom would save having to spawn one.

**Comment by aztectornado** [comment]
This is a problem with Polaris and even Bay if I'm not wrong. I'm amazed they've never had anyone look at this.
