### ISSUE TITLE
atmospherics laptop has a fucky icon

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2199]
#### Brief description of the issue
The overlay for the atmospherics laptop has a screen for a full-size terminal on a laptop body.

#### What you expected to happen
Either a generic laptop sprite, or an overlay that fits it.

#### What actually happened
![image](https://user-images.githubusercontent.com/14942479/30778960-23f02b34-a0da-11e7-9c9e-3c3d5d3b2114.png)

#### Steps to reproduce
- ghost over the atmospherics breakroom and feast your eyes.

#### Code Revision
Server revision: release - 
b2edc11ba5aa4c5f4e2000b48d166029293926f7

**Comment by Wutnold124** [comment]
easily solvable by imagining it as a cool future hologram :sunglasses:

**Comment by SpadesNeil** [comment]
Did this ever get fixed?
