### ISSUE TITLE
The spam filter keeps blocking me if anything untowards happens to both hands.

### ISSUE THREAD

**Issue by Brandysnap** [VOREStation/VOREStation#220]
#### Brief description of the issue
I'm not sure how to give a brief description of the issue. all it is is this.
You are nearing the spam filter limit for identical messages.
Kiri 'Mittens' drops what they were holding, their robotic right hand malfunctioning!
You have fastened the frame to the floor.
You are nearing the spam filter limit for identical messages.
Kiri 'Mittens' drops what they were holding, their robotic right hand malfunctioning!
You have unfastened the frame from the floor.
You have exceeded the spam filter limit for identical messages. An auto-mute was applied.
You have been auto-muted from IC (say and emote) by the SPAM AUTOMUTE system. Contact an admin.
which when one hands broken and the others really damaged like mine was. It's unavoidable.
#### What you expected to happen
I think it's set to ten with an unknown spam filter cooldown.
#### Steps to reproduce
break both hands then try doing anything that involves picking them up.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
The spam automute system has been removed entirely in Polaris to fix other bugs. It is apparently an ancient /tg/ holdover. So next update we pull from Polaris will fix this.
