### ISSUE TITLE
The canine type borgs simply cannot push past or move over player mobs

### ISSUE THREAD

**Issue by icowom** [VOREStation/VOREStation#2209]
#### Brief description of the issue
Borgs, tested in particular was the K9 class, the Medihound class, and the Janihound class. Are completely unable to move past, or over other player characters. However, they are able to push past you or run in between your legs with help intent. You cannot do the same to them with both parties having help intent

#### What you expected to happen
I expected borgs to be able to run past and over people like any other player character

#### What actually happened
You can literally get stoned walled by a 25% sized micro as a 200% sized borg (Size gun work)
#### Steps to reproduce
- (Step 1)
Be a borg, just run into the nearest speck of dirt micro on the floor.

- (Step 2)
Get completely stonewalled.

- (and so on)
Lament as a catgirl mob being controlled by Demicus can literally be made to past under your legs countless times, while being stonewalled to a micro right behind them.
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
https://imgur.com/a/81aRO

Note that BTX can run over Red repeatedly, a simple mob, but a player char would stonewall

**Comment by Cyantime** [comment]
This is true of all cyborgs. They also cannot initiate a help intent place-swap, but can be swapped with by other human mobs.

**Comment by icowom** [comment]
I feel like it should be included. This would allow borgs to at least hotswap with player chars infront or behind them. Very useful when borgs are considered easily repaired tanks for agro and damage. Not to mention when chasing people down, it would help to not get tripped by a micro in a way.

**Comment by Poojawa** [comment]
Borgs mulching up micros under treds when

**Comment by Verkister** [comment]
This thing's been fixed with the polaris synced version of the closed PR above.
