### ISSUE TITLE
Contraband crates for Cargo

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#221]
#### Brief description of the issue
We used to have cargo crates that spawned a variety of illegal contraband.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

**Comment by GodGivenDeath** [comment]
We still have them. Gotta hack the console to be able to order them under Operations I believe, the same one you go to in order to get a hoverpod.

The only thing missing is the _variety_, since they only give Blood Tomato seed, poison wine, Happy Pills, and Zoom Pills. The variety is lacking.

**Comment by SpadesNeil** [comment]
That's what I mean, yes. I changed it to spawn all sorts of goodies.
