### ISSUE TITLE
Slippery tiles with Fire extinguisher 

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#222]
#### Brief description of the issue
Fire extinguishers make the ground slippery which not only is anoying but is dangerous for xenbiologly or in the event of a slime outbreak
#### What you expected to happen
there to be no slippery tiles when using a fire extinguisher to kill slimes 
#### What actually happened
there is slippery tiles when using a fire extinguisher
#### Steps to reproduce
use a fire extinguisher 
#### Additional info:
im gonna guess its a polaris thing or just something that wasnt rechanged

 - **Server Revision**: 3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

**Comment by SpadesNeil** [comment]
Actually gonna make this 'Severe' because it's seriously detrimental to Xenobiology players.

**Comment by Cameron653** [comment]
Fire extinguishers are broken as a whole. They end up making the floor wet
and don't even kill the slimes 100% of the time as it did in the old code.
The only way to guarantee the slime dies is to dump a beaker of water on
them.

**Comment by Arokha** [comment]
Xenobio was just entirely rewritten on Polaris, so this is likely to change.

**Comment by SpadesNeil** [comment]
Wiki needs to be updated, then.

**Comment by SpadesNeil** [comment]
misclick
