### ISSUE TITLE
Macro Coding Issue

### ISSUE THREAD

**Issue by tonyvld** [VOREStation/VOREStation#223]
#### Brief description of the issue
When others are on a intent other than help, such as disarm, harm, etc. They become unable to be stepped over or on, even if two sizes smaller.
#### What you expected to happen
A quick fix to reinstate the code for stepping over and on, even if the two sizes or more smaller person is on a intent other than help
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Please fulfill the rest of the issue, or you will delay it being resolved.

**Comment by SpadesNeil** [comment]
Issue closed due to failure to follow correct format.
