### ISSUE TITLE
For the love of God, stop coding things to depend on Tether Datums and areas.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#2245]
#### Brief description of the issue
The Example map cannot be used for testing (counterintuitive to your mapping contest, btw), because of 
persist_vr referencing spawn points that don't exist. (Stop doing this. Check if the map has a tram.), as well as a wilderness setup that you never ACTUALLY commented out, alongside ZAS Tests and other annoyances.

This is awful for Downstream, and development at large.
Server revision: release - 
bf51b997afd5f1c066bbb24692bcb8c3a65babe3

**Comment by Arokha** [comment]
This is an old issue and doesn't happen anymore, given there's a Travis unit test that compiles without Tether to make sure nothing depends on it.
