### ISSUE TITLE
Cyborg Respawn

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#225]
#### Brief description of the issue
Respawning doesn't seem to work when going to cryo as a cyborg.

#### What you expected to happen
I expected to be able to respawn after one minute.

#### What actually happened
Well. It told me I can respawn, just didn't let me.

https://i.gyazo.com/71af58383e27974ecc6bdc416e543ec8.png

After five minutes I was able to respawn though. Dunno if this is still a serious issue. Five minutes wait time ain't much.
#### Steps to reproduce
Join in as a Cyborg. Go into Cyborg storage. Ghost, Wait a minute to respawn and try to respawn.

#### Additional info:
Server revision: release - 2016-05-23

**Comment by Arokha** [comment]
Related to https://github.com/PolarisSS13/Polaris/issues/1572 ?

**Comment by Arokha** [comment]
In your picture it says 1:30 three times. Was that you just clicking fast, or did the timer stop?

**Comment by SpadesNeil** [comment]
Marking as duplicate since it's reported on Polaris.

**Comment by SpadesNeil** [comment]
Actually I'm not going to close these because it's not fixed upstream yet.
