### ISSUE TITLE
Vulpkanin default skin is borked

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2255]
#### Brief description of the issue
https://github.com/VOREStation/VOREStation/blob/9491f4b9b3c0fc2341a07007f407f9ea10ba2f9b/code/modules/mob/new_player/sprite_accessories_vr.dm#L413

References an iconstate that does not exist in r_vulpkanin.dmi

Selecting it as your facial hair option seems to grab the groin sprite instead for your beard.
This has been reported to me via discord so I haven't have a chance to fully test/reproduce it yet but the code definitely shouldn't be pointing at icons that don't exist.

**Comment by Verkister** [comment]
Seems like a redundant relic someone forgot to remove.

**Comment by Verkister** [comment]
Been dealt with.
