### ISSUE TITLE
Mapping suggestion - gas heater/cooler for air tanks in atmo

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2269]
#### Brief description of the issue
Part of the problem with atmospherics in the current setup is that if hot or cold gas gets into the air mix tanks, your air supply is now the wrong temperature and it's an absolute pain in the arse to get it out to a heater/cooler and filtered back in.

The existing heater and cooler are there, but they're a huge pain and require dumping your air mix into the lines and piping them across the room, then to get them back into the air mix you have to pump it into the filter loop which is probably already clogged from whatever hot/cold gas caused the problem in the first place.

#### What you expected to happen
THERE'S GOT TO BE A BETTER WAY

#### What actually happened
A better way.

![image](https://user-images.githubusercontent.com/14942479/31224686-daa3109a-a9c6-11e7-8e48-a6019ed46ad9.png)

The gas meter is shifted a tile to the north, with another valve added to allow the heater and cooler to be isolated from the air mix or the lines. The existing valve is kept in place, as upgrading the machines requires the pipes to be unwrenched and wrenched again in order to recognise the connection, so some means of draining the pipes without draining the entire air tank is needed.

Setting a higher target temperature on the cooler than the heater ensures they won't be fighting each other.

#### Steps to reproduce
n/a

#### Code Revision
Server revision: release - 
551371f8adcd2620447b2e4099ddf96c1125c0b5 
 
#### Anything else you may wish to add:
This COULD be feasably added to the atmospherics guide as a "gut gud scrubs" for atmotechs. It's not exactly a difficult build if you know what you're doing, but tech storage only has one board each for heaters and coolers and no circuit printer.

**Comment by Gearshy** [comment]
Oh no, not making things easier! Reeeee-- oh wait, I don't mind this. Even if it does mean there'd now be three cooler/heater pairs in atmos if they're mapped in.

**Comment by Screemonster** [comment]
Yeah, these two are basically useless for anything besides regulating the temperature of the air mix tank, 'cause it's one of those "it's not hard to fix, it's just fucking tedious" problems.

**Comment by Cyantime** [comment]
The problem can be avoided entirely by moderating the temp in the filter line with the two existing heater/cooler pairs though. Unless you're siphoning the remains of a plasmafire, they should be able to mostly keep up, and it doesn't matter if the mix tanks get a few degrees off 20c.
