### ISSUE TITLE
The healing slime heals synths.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#2271]
#### Brief description of the issue
A healing slime heals synthetic limbs/people.

#### What you expected to happen
To only heal organic people.

**Comment by aztectornado** [comment]
It looks like they coded it specifically so it WOULD heal robotic limbs/parts, actually. Kinda an odd choice, but-

**Comment by Cameron653** [comment]
Feature, as shown by the comment here:
https://github.com/VOREStation/VOREStation/blob/4faebdc4505fec02b61d08a267d549de981439a7/code/modules/mob/living/simple_animal/slime/subtypes.dm#L520-L524
