### ISSUE TITLE
Ripley Mech needs a buff.

### ISSUE THREAD

**Issue by OrbisAnima** [VOREStation/VOREStation#2279]
#### Brief description of the issue
There are many alternatives to mining, yet one that is iconic and never used, is the ripley, the mining/cargo mech by excelence, the reason is simple, its just too slow and its too much of a bother, even reaching the mining area is a pain, so its a method that is no longer used

#### What you expected to happen
for the ripley to be one of the best mining methods, common, its a multi department accomplishment, it should make your life easier, not harder.

#### What actually happened
Even using a normal drill will yield results faster than the ripley, setting up the big drills will result more loads and using the special suit miners start with, I think its called industrial exosuit, already come with a mining drill that makes everything easy forever, in comparison to the poor ripley.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Gearshy** [comment]
The Ripley can already carry the big drills around in its cargo compartment. So... maybe the ability to use a mineral scanner, and to set up and operate said drills without having to leave the suit?

**Comment by Screemonster** [comment]
A tool-arm module that would allow it to wrench the drill parts into place would be goddamn amazing. It'd make it great as an engineering mech too.
