### ISSUE TITLE
Server consistently crashes on restart

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#2280]
#### Brief description of the issue
Self-explanatory.

#### What you expected to happen
When the round ends, for the next round to start automatically.

#### What actually happened
Most of the time, it croaks.

#### Steps to reproduce
- End round.
- Wait for reboot.
- Cry.
- Forget to bother Ace.
- Bother Ace.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/a9d8a64eda78f207ab3fcb37ffe5b9ed173516f9
 
#### Anything else you may wish to add:
- afaik Polaris is not experiencing this bug.

**Comment by Arokha** [comment]
Fixed for the most part by 512.1403
