### ISSUE TITLE
Species with NO_SCAN can still be scanned and resleeved

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#2286]
#### Brief description of the issue
Species with NO_SCAN can still be scanned and resleeved

#### What you expected to happen
Not scannable/reseleevable

#### What actually happened
They're scannable/resleevable

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/6d90a5e425ac8d0ace56d0cd5d2d9da04bbe88f0
 
#### Anything else you may wish to add:
Oversight

**Comment by Screemonster** [comment]
I thought NO_SCAN made their bodies unprintable, but a mind-scan could still be taken to allow them to be sleeved into a synth body?
