### ISSUE TITLE
Bones being set in the WRONG place on the correct limb with the bone setter.

### ISSUE THREAD

**Issue by KonBear** [VOREStation/VOREStation#2292]
#### Brief description of the issue
Sometimes while performing surgery on a limb with a broken bone, including ones where you break the bone purposefully with a bone saw  i.e. NIF surgery, it will display the message after using the Bone setter that you set the bone in the WRONG place instead of telling you that your hand slipped or you put It in the right place.

#### What you expected to happen
After putting bonegel then using a bone setter you should expect either one of two messages while working on the correct limb, that you put the bone in the right place or that your hand slipped if you failed.

#### What actually happened
Either there is a small chance the bone magically sets itself after the bone gel before the bone setter or it is displaying the wrong message by telling you that you have set the bone in the WRONG place.

#### Steps to reproduce
- (Step 1) Break a bone
- (Step 2) Perform surgery til the point of placing bonegel then get ready to use the bone setter 
- (Step 3) Doubt yourself after using the Bone setter to put the bone in the WRONG place.

#### Code Revision
- 551371f
 
#### Anything else you may wish to add:
- it's rare when it happens, so not an urgent bug to be squished~

**Comment by SpadesNeil** [comment]
This still happening?

**Comment by Arokha** [comment]
You don't use the bone setter in NIF surgery. Just bone gel. It's not the same steps as fracture.
Scalpel -> Hemostat -> Retractors -> Saw -> Retractors -> Drill -> NIF (-> Fix o' Vein)
then
Retractors -> Bone Gel -> Cautery
Done
