### ISSUE TITLE
Polaris Port - Gateway Missions

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#23]
- [x] Ensure the Gateway and away mission mechanic actually functions as intended.
- [x] Replace existing latejoin gateway with something more lore-appropriate (transporter, etc).
- [x] beach.dmm
- [x] carpfarm.dmm
- [x] listeningpost.dmm
- [x] blackmarketpackers.dmm
- [x] labyrinth.dmm

**Comment by SpadesNeil** [comment]
Made an edit. Considering how we're almost the only mainstream codebase that still uses the gateway, we have some work to do.

**Comment by Arokha** [comment]
These load in dreammaker now, but some mapper will need to touch them up later. Things they used in their maps don't exist in Polaris. Not to say items were removed, mostly just... hand-set sprites for walls and stuff that don't exist because they're autogenerated now and stuff... stuff like that. "Iron wall state" when walls are all the same and have a material that colors/sprites them now.

Not really something we want to wait on since this depends on @SpadesNeil having infinite time to tweak all the maps. :p The beach works, that's all that really matters! ;D
