### ISSUE TITLE
Custom Body Console cannot assign wings to Custom Species Sleeves

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#2303]
#### Brief description of the issue
When I was trying to assign a wing (any kind) to my custom species sleeve in Custom Body Console, I went through the menu and found nothing happening on the actual console.

#### What you expected to happen
The console should have changed from "wing" to the appropriate wing type, like with ears/tails.

#### What actually happened
Nothing! Menu appeared, I could select it alright but then it borked.

#### Steps to reproduce
- Open Custom Body Console with a Male Human
- Make a custom sleeve
-Try and fail giving it a wing

#### Code Revision
release - 
551371f8adcd2620447b2e4099ddf96c1125c0b5 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
#2524 Possibly fixes this?
