### ISSUE TITLE
KHI Net Guns and Simple mobs.

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#2307]
#### Brief description of the issue
The Capture setting on the net guns don't actually pin the grubs or, likely any simple mobs

#### What you expected to happen
For the KHI capture setting to net and pin the simple mob that it hits for a somewhat easy kill

#### What actually happened
bug proceeded to run around with the net on it chasing and attacking me

#### Steps to reproduce
- (Step 1)Set the gun to capture
- (Step 2) Zap a simple mob and watch it chase you
- (and so on)

#### Code Revision: 551371f8adcd2620447b2e4099ddf96c1125c0b5
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
The net gun feature should be made not to work on simple mobs anyway. It's too easy to cheese tough mobs.

**Comment by Screemonster** [comment]
At the very least only _certain_ mobs should be targetable with it, like if you were wanting to use it to capture things for xenobio or whatever (but nonhostile things you can just run up to them, ctrl-click, and drag them off anyway)

**Comment by Arokha** [comment]
I mean, when you netgun gaslamps they get stuck in place trying to resist out of the net. So that seems to work?

**Comment by SpadesNeil** [comment]
Maybe we should set it up so that when catching simple mobs, it can't catch mobs able to do substantial damage. That said, I should nerf gas lamp attacks.

**Comment by Screemonster** [comment]
Laff. Gaslamps you can just ctrl-click and drag off, no net needed.

**Comment by SilverTalismen** [comment]
@Arokha I believe, if I recall correctly, I zapped a Solar Grub with it.
