### ISSUE TITLE
Never ending heartbeat sounds.

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#231]
#### Brief description of the issue
The sound of a heart beating never ceases.
#### What you expected to happen
For it to stop.
#### What actually happened
It never stopped.
#### Steps to reproduce
1. Get gurgled.
2. Enjoy the annoying sound.
#### Additional info:
 - **Server Revision**: Server revision: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
So it's not just me. Yea this is very annoying.

**Comment by Cameron653** [comment]
I believe this may be the code in question. Only happens when BPM is > 120, you're in high level shock, or on a space tile.

https://github.com/VOREStation/VOREStation/blob/c8000a21e9f757d9dd1b80765d10e3166c7a90ee/code/modules/mob/living/carbon/human/life.dm#L1518-L1527

**Comment by SpadesNeil** [comment]
This seems to be gone.
