### ISSUE TITLE
Minor spelling problem with "they has" for patches of skin

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#2319]
#### Brief description of the issue
Minor spelling thing it seems, with a fresh patch of skin, it showed "they has" for it.

#### What you expected to happen
Expected "They have"

#### What actually happened
It said "They has"

#### Steps to reproduce
- (Step 1) Probably use the "they" pronouns
- (Step 2) Get a fresh patch of skin somehow?
- (Step 3) Examine

#### Code Revision
551371f8adcd2620447b2e4099ddf96c1125c0b5 
 
#### Anything else you may wish to add:
This is Qoozaooqix Zaooqr, Skrell!
They are wearing   a lightpurple jumpsuit.
They are wearing   Trenchcoat.
They are carrying   a size gun on their Trenchcoat.
They have   a leather satchel on their back.
They are holding   Captain Pete's Cuban Spiced Rum in their right hand.
They have   some insulated gloves on their hands.
They have   PDA-Qoozaooqix Zaooqr (Assistant) about their waist.
They have   Augmented shades covering their eyes.
They have   a radio headset on their left ear.
They are wearing   Qoozaooqix Zaooqr's ID Card (Assistant).
She has a lightweight, athletic build.
They are small enough that you could easily pick them up!
They has a fresh skin on their left foot.

**Comment by Screemonster** [comment]
I sees no problem wi' this, so what if they 'as a skin onna foot or whatever?
