### ISSUE TITLE
Security Cameras don't work anymore

### ISSUE THREAD

**Issue by blazerules** [VOREStation/VOREStation#2331]
#### Brief description of the issue
All network names are "undefined" and all the cameras you can access are... well extremely limited.

#### What you expected to happen
Being able to switch networks and view more cameras.

#### What actually happened
Nothing works but the listed cameras.

#### Steps to reproduce
- Click on camera console
- Notice that all networks are broken

#### Code Revision
Server revision: release - 
506e28bdf3a78e916863360f987f394efc9d65fb 
 
#### Anything else you may wish to add:
http://prntscr.com/gza10v

**Comment by SpadesNeil** [comment]
I know this was fixed.
