### ISSUE TITLE
Quit the round verb doesn't prevent using the sleevemate to scan and resleeve people

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#2336]
#### Brief description of the issue
People that have quit the round through the quit the round verb can still be resleeved, provided their body is not gibbed and accessible by someone with a sleevemate

#### What you expected to happen
I expected it to do what it did: allow me to resleeve a person who quit the round.

#### What actually happened
The sleevemate allowed me to resleeve a person who had quit the round. It was as if they hadn't used the verb, aside from their name being off the manifest and (presumably) their job slot being opened.

#### Steps to reproduce
- Find a ~~victim~~ volunteer test subject
- Kill your test subject
- Have your test subject posthumously use the quit the round verb
- Scan your test subject's body and mind with a sleevemate
- Grow them a new body using their body record and a growing pod
- Sleeve their mind record into their new body

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/506e28bdf3a78e916863360f987f394efc9d65fb

**Comment by Verkister** [comment]
Added fixing attempt for this on my active PR https://github.com/VOREStation/VOREStation/pull/2332
