### ISSUE TITLE
Assistant alt-titles show up as unknown on HUDs

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#2354]
#### Brief description of the issue
Assistant alt-titles show up as a white question mark with a black background on job HUDs

#### What you expected to happen
For assistants with an alt title to have the assistant icon

#### What actually happened
My character with the job of resident had an unknown icon instead of the assistant icon

#### Steps to reproduce
- Spawn in as an assistant with an alt title like resident
- Have a NIF and turn on the civilian HUD

#### Code Revision
dcddd0d64a82f76e991e166c8d9dc3893690fbe9
 
#### Anything else you may wish to add:
- The alt-title I had was Resident and the HUD was a NIF AR Overlay (Civ)

**Comment by Arokha** [comment]
What assistants
