### ISSUE TITLE
Jukebox is broken

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#2361]
#### Brief description of the issue
The jukebox is not working. It indicates that it is not working in-game.

#### What you expected to happen
To be able to listen to bar music.

#### What actually happened
Deafening silence and also each time I click it:
`The space jukebox doesn't appear to function.`

#### Steps to reproduce
- Click Jukebox.
- Cry.

#### Code Revision
- release - 
dcddd0d64a82f76e991e166c8d9dc3893690fbe9

**Comment by SpadesNeil** [comment]
@Leshana pls

**Comment by Arokha** [comment]
It works fine??
