### ISSUE TITLE
The new synth colouring system doesn't allow players to play any lighter coloured synths

### ISSUE THREAD

**Issue by Treasa729** [VOREStation/VOREStation#2362]
#### Brief description of the issue
With the new colour system a 255, 255, 255 RGB colour scheme ends up being 128, 128, 128. The brightest possible synth coloration is a dark grey.

#### What you expected to happen
To continue to be able to play my synth character who has a brighter colour scheme.

#### What actually happened
The brightest synth coloration is a dark grey, I cannot get my character to look even remotely similar to their old appearance and they are no longer at all recognizable by their sprite.

#### Steps to reproduce
1) Load up a synth body
2) Try any feasible colour scheme and see that it is always a dark colour.

#### Code Revision
Server revision: release - 
dcddd0d64a82f76e991e166c8d9dc3893690fbe9 
 
#### Anything else you may wish to add:
A pure white (255,255,255) DSI Tajaran looks like this. I'd expect this colour if I had selected something that was nearly black. All of the full prosthetics I looked at ended up looking similar though granted, I didn't check if every single one had this issue.
![untitled](https://user-images.githubusercontent.com/15188540/31920932-290cb2c8-b83a-11e7-9602-da3c1933d568.png)

**Comment by Dhaeleena** [comment]
This not only happens with Synthetics. The whole color 'fix' in general has ruined coloring if you ask me. It is impossible to input an exact RGB value and get what you want. The outlines too see to be much more darker or tajara or something.

**Comment by Screemonster** [comment]
Looks like they were changed to colour_mult without changing the base sprite to white.

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/pull/4080 might be responsible

**Comment by Arokha** [comment]
![image](https://user-images.githubusercontent.com/15028025/35027316-0fbf9cb4-fb1e-11e7-8a8a-cbc333a5e088.png)
