### ISSUE TITLE
AI holograms can be cleaned up

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#2363]
#### Brief description of the issue
AI holograms can be cleaned with a mop, as if the hologram is dirt or blood

#### What you expected to happen
For AI holograms to not be cleaned up by mops

#### What actually happened
An AI hologram was cleaned up with a mop

#### Steps to reproduce
- Have an AI use a holopad
- Clean the tile the hologram is on with a mop

#### Code Revision
- dcddd0d64a82f76e991e166c8d9dc3893690fbe9
 
#### Anything else you may wish to add:
- I am only certain that this works with mops, but the issue may be present for other methods of cleaning (i.e. soap, space cleaner)

**Comment by OrbisAnima** [comment]
Polaris Issue.

That said, this is hillarious, and totally a feature.

**Comment by Arokha** [comment]
Important part of Janitor/AI balance. All jobs have checks and balances.

**Comment by SpadesNeil** [comment]
Arokha you know damn well that being able to clean up light with a mop isn't an intended feature. :P
