### ISSUE TITLE
no hotkey for whisper

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#237]
#### Brief description of the issue
I need to be able to press Y for whispering.
#### What you expected to happen
whisper " ay lemme eatchu
#### What actually happened
[nothing]
#### Steps to reproduce

1. press y
2. there is no step 2

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by KiraAlitruss** [comment]
I'm not a developer or coder or anyone important so I don't think my opinion will matter, but please oh please don't override the Y hotkey. Keep it in. I don't want to click on every item I want to activate in my hands, it's a nightmare that makes things less enjoyable.

**Comment by viv-eret** [comment]
just use z

**Comment by KiraAlitruss** [comment]
No. It doesn't even work. Be considerate of other people's keyboard layouts.

**Comment by SpadesNeil** [comment]
No server revision is listed.

**Comment by SpadesNeil** [comment]
Closing this because #239 explains it better.
