### ISSUE TITLE
being in librarian could use some improvements

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#2372]
#### Brief description of the issue
the librarian computer is kinda clunky to use and there are too many duplicate books

#### What you to happen
It would be nice if you could sort the library computer by category and the admins to remove the duplicate books in the database 

#### Code Revision
- i dont know if this is needed rn but im not home anyway
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ktccd** [comment]
Would be cool if there was some way to remove books from the database, maybe if you are the author? Since if you notice an error in the text later, well, it's in there forever now.

**Comment by Screemonster** [comment]
I want an admin-panel book manager damnit.

**Comment by Anewbe** [comment]
Oh boy, something I'm relevant to. Our end maaaaay be looking into making the admin-side cleanup a lot easier. No promises or timeframe, just yet.
