### ISSUE TITLE
Neutral Traits don't take up trait slots

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2373]
#### Brief description of the issue
Neutral traits cost zero points and zero trait slots

#### What you expected to happen
Neutral traits cost one trait slot, zero points

#### What actually happened
Total number of traits is unaffected by the number of neutral traits taken

#### Steps to reproduce
- Create a custom character
- Select any number of neutral traits
- Observe number of allowed traits before and after selecting

#### Code Revision
release - 
dcddd0d64a82f76e991e166c8d9dc3893690fbe9 
 
#### Anything else you may wish to add:
- https://thumbs.gfycat.com/DependableImpressionableGrub-size_restricted.gif

**Comment by Cyantime** [comment]
See https://github.com/VOREStation/VOREStation/pull/2234
