### ISSUE TITLE
no Univends or something similar

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#238]
#### Brief description of the issue
I need to be able to dress people in schoolgirl uniforms.
#### What you expected to happen
There to be a clothes vendor.
#### What actually happened
Nothing.
It no exist.
#### Steps to reproduce
Just log on.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
No server revision is listed.
