### ISSUE TITLE
It's possible to die, respawn, then be resleeved into your original character.

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#2383]
#### Brief description of the issue
It's possible to be resleeved into your original character after respawning as a different one. The character you respawned as will fall SSD, displaying a message as if they ghosted.
It's also possible for this to be reversed, if someone resleeves you into the character you respawned as if the above is done. (It should be noted that the person I discovered it with left on the tram before I resleeved them into the character they respawned as)

#### What you expected to happen
For resleeving to fail if the player has respawned.

#### What actually happened
The player was sleeved into their old character. Then I reversed it.

#### Steps to reproduce
- Spawn in, with a medical doctor partner.
- Die and ghost, or just ghost (without departing)
- Respawn
- Have your medical doctor partner resleeve your old character

#### Code Revision
- dcddd0d64a82f76e991e166c8d9dc3893690fbe9 
 
#### Anything else you may wish to add:
- A SleeveMate mind scan was used to resleeve both the new and old characters by scanning them after they died or went SSD when I discovered this, but I assume a backup implant or scan before the player left the body would work just as well.

**Comment by SpadesNeil** [comment]
Duplicate of https://github.com/VOREStation/VOREStation/issues/2336

**Comment by SpadesNeil** [comment]
Wait, you posted this twice. Don't do that.

**Comment by LittleBigKid2000** [comment]
@SpadesNeil  The other is about the quit-the-round verb not preventing resleeving. This is about respawning as a different character not preventing you from being pulled back to the same character via resleeving from a mind backup of the original character. Similar and might even be solved with the same fix, but different things.

**Comment by SpadesNeil** [comment]
Oh, nevermind then.

**Comment by Arokha** [comment]
Does it ask you if you want to, or not?

var/answer = alert(active_mr.mind_ref.current,"Someone is attempting to restore a backup of your mind. Do you want to abandon this body, and move there? You MAY suffer memory loss! (Same rules as CMD apply)","Resleeving","Yes","No")

It's supposed to.
