### ISSUE TITLE
Whisper hotkey 

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#239]
#### Brief description of the issue
Some players are apparently dependent on a hot key for their whispering. Instead of gutting everyone else who isn't reliant on such by using the old hot key for it, which was Y, I would like to suggest that a different key is selected for this. V is a good key as it's right above the space bar and is easily reached without changing hand position on the keyboard.
#### What you expected to happen
To not have the luxury of an activation hot key taken away so soon.
#### What actually happened
Requests to gut the activation hot key and have it be replaced by whispering popped up.
#### Steps to reproduce
It's a suggestion, not a bug report. But;
1. Press your Y key to attempt to whisper.
2. You will not whisper, only activate whatever item you are holding.
#### Additional info:
 - **Server Revision**: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
I would like to stress that it'd be amazing if the Y hot key for activating items was not removed. I am putting this up in fear of losing this hot key. My understanding of what'll happen or not happen is poor nonetheless.

**Comment by SpadesNeil** [comment]
You _commented_ in the thread originally reporting this issue. :U

But you also explained it way better.

The "activate held item" hotkey was already Ctrl+Z so I see no reason to not allocate the whisper hotkey to something like one of the F keys or Y.

**Comment by KiraAlitruss** [comment]
Oh, so either way there's still a chance of Y being overriden. Darn. I'll make a better report on the uni-vendors aswell.
