### ISSUE TITLE
Unlit welders still ignite things. (Atleast Experimental ones)

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#2392]
#### Brief description of the issue
Held an unlit welder

#### What you expected to happen
Not blast into a fiery demise

#### What actually happened
Became a roast

#### Steps to reproduce
- (Step 1)Sit in phoron
- (Step 2)Hold a welder
- (Step 3) Embrace your new life as a roast.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 dcddd0d64a82f76e991e166c8d9dc3893690fbe9 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ZombieTsar** [comment]
issue still persists
