### ISSUE TITLE
Config option to enable or disable vore for the whole server.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#2393]
#### Brief description of the issue
"SPADES WHY?!" Well, a lot of people, including myself, have wanted to use Vorestation code for non-vore things, sometimes not even ERP things. We have a lot of very cool features _besides_ vore.

This is just something I want to do when we're bored one weekend. This will not affect our server. This is purely for downstream servers to use.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/22a42902f571d5f0e5baab6b65578e7e2ff2fe53

**Comment by Ketrai** [comment]
Do et
