### ISSUE TITLE
Can't use the Xenomorph hybrid as a custom species base in the vore tab

### ISSUE THREAD

**Issue by ghost** [VOREStation/VOREStation#2397]
I can't use the Xenomorph hybrid as a custom species base in the vore tab

To be able to use the Xenomorph hybrid as a base so I could add traits to my character 

Couldn't use the Xenomorph hybrid as a base

Character Setup
Change species to custom species under general
go to the VORE tab
click Icon base and look through the options

master - 2017-10-29

 (I don't know if its something I am doing or no)

**Comment by SilverTalismen** [comment]
That is set up like that because Xenohybrid's are a species you have to apply for to be, a whitelisted species. 

If you feel they are missing some trait or need tweaked in some way I'm sure you could speak to someone on the Development team.

**Comment by Vanceshark** [comment]
On the server I play for Xenomorph hybrids can be played by anyone, Yawn Wider

**Comment by Screemonster** [comment]
Give your issue a more descriptive title please.

**Comment by SilverTalismen** [comment]
> On the server I play Xenomorph hybrids can be played by anyone, Yawn Wider

Likely because Xenomorph hybrids were unwhitelisted there.

**Comment by SpadesNeil** [comment]
This is actually not a bug but I'll open it to discussion. My vote is no. People may just use it to bypass the system.

**Comment by SilverTalismen** [comment]
I would rather not see Xenohybrid sprites become a open thing for Custom Species either.

**Comment by Arokha** [comment]
Whitelisted species don't show up here, that wouldn't make sense.
