### ISSUE TITLE
Lack of univend vendors.

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#240]
#### Brief description of the issue
On the previous station, there were clothes vendors present in dorms and the locker room, alongside the genetics cloning room.

#### What you expected to happen
To be able to vend myself new clothes to wear.

#### What actually happened
I had no ability to vend myself clothes.

#### Steps to reproduce
1. Arrive with a default load out.
2. Attempt to find an/a univend for clothes.
3. There are none. Wear one of the few clothes each department gets.

#### Additional info:
 - **Server Revision**: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
The vendors could work with being added to the most needed locations; the apartments, the genetics lab, the cryogenics ship's arrivals area and possibly even the strange dock arrivals area which has plenty of room as far as I guessed.

**Comment by SpadesNeil** [comment]
Technically a duplicate of #240 but better explained.

**Comment by SpadesNeil** [comment]
Probably obsolete due to new loadout feature.
