### ISSUE TITLE
Disassembling windows gives wrong amount of glass sheets

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2403]
#### Brief description of the issue
Disassembling windows gives only one sheet of glass instead of four despite four being needed to make a full window.

#### What you expected to happen
Take apart the window and get the four sheets needed to put it back together.

#### What actually happened
Take apart the window and get one sheet instead of four, making it so you can't rebuild the full window

#### Steps to reproduce
- Take apart any window (screwdriver, crowbar, screwdriver, wrench)

#### Code Revision
- release - 
dcddd0d64a82f76e991e166c8d9dc3893690fbe9 
 
#### Anything else you may wish to add:
- https://gyazo.com/dc08872fa6aa79973109ea76e92a0816 The window I can build next to the type of window I took apart.
- https://gyazo.com/b18b90dcb25f92c190aab272c4fc59f6 Confirmation that I need four sheets to build a full sized window.
- https://my.mixtape.moe/swisxl.gif GIF of the process

**Comment by HzDonut** [comment]
Update: It's only mapped windows that have this issue, ones created by players give four sheets like they should.

**Comment by Very-Soft** [comment]
It's been that way since before tether I think. I always assumed it was meant to prevent people from disassembling the station for parts, as you wouldn't get as much stuff from it.
