### ISSUE TITLE
Atmos Techs lack basic Engineering Access

### ISSUE THREAD

**Issue by HalfdeadKiller** [VOREStation/VOREStation#2404]
#### Brief description of the issue
Atmospheric Technicians don't have access to basic engineering gear, such as Electrical Closets and Engi-Vend machines.

#### What you expected to happen
I expected to get materials and tools to help with engineering.

#### What actually happened
I did not get things to help with engineering.

#### Steps to reproduce
- Be Atmos Tech
- Attempt to access Engi-Vend or Electrical Closet
- Receive Access Denied

#### Code Revision
- dcddd0d64a82f76e991e166c8d9dc3893690fbe9
 
#### Anything else you may wish to add:
- Nothing else to note.

**Comment by Cyantime** [comment]
https://github.com/VOREStation/VOREStation/issues/2321
Fixed in the next release.
