### ISSUE TITLE
Bumping into scanner pod no longer puts you inside the pod.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#241]
#### Brief description of the issue
You used to be able to just walk into an open genetics scanning pod.

#### What you expected to happen
Bumping into it puts you inside.

#### What actually happened
I have to right-click.

#### Steps to reproduce
Walk into a genetics scanning pod.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

**Comment by Arokha** [comment]
Dupe of #130
