### ISSUE TITLE
Fluff item app was accepted. Needs to be implimented

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#2413]
Name of Item: regent implant? 

Item description: Basically allows Kat to milk her taur tits and her upper tits for breast milk. Considering shes been fucky with her hormones her lack of a sex has created the need for breast milk to be produced

Sprites (or link to sprites): Dont think there is one.

Any additional resources: Its already implemented so im not sure what i can add.(in a .zip or .7z file, including sounds and DM files with code in them)

BYOND Key (Username): Samanthafyre

Name of Character: Kateryna Petrovitch

Main Job(s) of Character: Security

Why your character should have this item: She has a habit of bottling her milk for reasons.. But in general I figure why not, its lewd but its also something people would probably enjoy as she sometimes has a habit of being motherly. She again as stated above, has lactating breasts due to her fully synthetic sex replacing the real thing. Due to lack of hormones or her body being knocked out of whack by the loss of it. She lactates!

Additional Notes (If it's a permit, insert the information for the permit here):

Fluff Item slots already used: 2

Fluff application was accepted already. Just need it to be implimented

Included various stuff probably needed:
Generated reagent: "milk"
Empty message: "Your nipples are sore from being milked." and "Your breasts feel drained, milk is no longer coming out of your upper or lower teats."
Full message: "Your breasts are full, their swollen state feels sore as you walk or move." or "Your breasts feel full, milk is starting to leak from both sets of nipples, upper and lower, dribbling down to the floor occasionally" 
Emote descriptors: "squeezes some warm milk from Kateryna", "tugs on Kats nipples, milking them", and "kneads Kats breasts, milking them"
Self emote descriptor: "squeeze" and "knead"
Random emote: "lets out a quiet huff" and "gives a soft huff, looking around"
Assigned proc name: "Milk"
Assigned proc description: "Grab one of Kats many teats and squeeze or pull on them to draw out her lovely warm milk."

Proof of acceptance:
https://forum.vore-station.net/viewtopic.php?f=27&t=1016

**Comment by Arokha** [comment]
Haven't seen you in quite a while.
