### ISSUE TITLE
Xeno-hybrid colors and head are broken

### ISSUE THREAD

**Issue by ghost** [VOREStation/VOREStation#2417]
#### Brief description of the issue
The Xeno-hybrid skin color is broken, say I wanted to make it white it can only be purple, and if you put it pretty much any other dark color it will be pitch black, and when you are in game the Xeno-hybrid heads don't show up

#### What you expected to happen
To get on today and it still be white

#### What actually happened
Got on and noticed that the body's and heads for the Xeno-hybrids are broken

#### Steps to reproduce
Go into character setup
Select Xeno-hybrid
Change body color to white
(And it should still be purple) - for the body

To find the head glitch just join in with the Xeno-hybrid dome and it should not show up

#### Code Revision
master - 2017-10-29

 
![broken -2](https://user-images.githubusercontent.com/33242524/32410866-bcc11b90-c22f-11e7-9f4f-6a87ef1f61b5.JPG)

![broken -1](https://user-images.githubusercontent.com/33242524/32410867-c22b7a30-c22f-11e7-8650-956797cc3a46.JPG)

**Comment by TheFurryFeline** [comment]
Xenohybrid are now custom species selection. Unsure if the issue itself with colours still remains.
