### ISSUE TITLE
Teshari colors are fucked

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#2420]
#### Brief description of the issue
Teshari tails and hairstyles are broken by the new color mode

#### What you expected to happen
them to be easily fixable in the new setup

#### What actually happened
The racial tails are glowing neon white and don't match body color, and the spike hairstyle I'm trying to use has some sort of awful white/gray shading that makes it impossible to get forest green hair.

#### Steps to reproduce
-Try to make a Teshari
-examine sprite

#### Code Revision
222337a2acf61ffc50a3fe265a70f3bc1ba2b625 
 
#### Anything else you may wish to add:
- pls fix
- reeee

**Comment by SpadesNeil** [comment]
This still an issue?

**Comment by AaronSherwood117** [comment]
Definitely fixed.
