### ISSUE TITLE
Vox eyes are doubled

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#2421]
#### Brief description of the issue
The Vox sprite revert didn't fully work. They have all of the old sprite stuff, but also the shitty new triple pink eyes underneath their normal eyes.

#### What you expected to happen
The pink eyes to be gone.

#### What actually happened
EYES FOR DAYS

#### Steps to reproduce
- Enter Character Creation
- Select Vox Race
- Examine Sprite

#### Code Revision
- 222337a2acf61ffc50a3fe265a70f3bc1ba2b625 
 
#### Anything else you may wish to add:
- All my characters are broken aaaaa

**Comment by SpadesNeil** [comment]
This still an issue? Honestly I don't know why you all just hate the newer sprite so much. I liked it.

**Comment by AaronSherwood117** [comment]
No, this can be deleted.
