### ISSUE TITLE
Rapala sprite

### ISSUE THREAD

**Issue by grey212** [VOREStation/VOREStation#2422]
#### Brief description of the issue

The wings and tails of the rapala sprites are gon
#### What you expected to happen

Buisiness as ususal
#### What actually happened

pretty much a normal human sprite
#### Steps to reproduce
- (Step 1)make a rapala
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Can brute force it though custom tail and custom wings.

**Comment by SpadesNeil** [comment]
You failed to include a server revision.
