### ISSUE TITLE
I Have no mouth and i must meow

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#2425]
#### Brief description of the issue
Tajara sprites look like shit and have no detail.

#### What you expected to happen
Tajara sprites to look AT LEAST as detailed as _3 year old baystation 12 original sprites_

#### What actually happened
It looks like shit, why does it even have a dark outline, were is the Nose? What happened to the mouth?

#### Steps to reproduce
- (Step 1) Be tajara
- (Step 2) Stare at mirror
- I have no mouth and i must scream

#### Code Revision
- 222337a2acf61ffc50a3fe265a70f3bc1ba2b625
 
#### Anything else you may wish to add:
- https://i.imgur.com/TA2ZeNX.png 3 YEAR OLD SPRITE with mouth and nose.
- https://i.imgur.com/sUpW33g.png I have no mouth and i must scream. I must scream about my lack of nose, About how my body looks like it was filled with the MS paint 'fill' tool and erased all detail from my body. Also why is that outline so incredibly dark, it makes 2/3 literally become outline

**Comment by SpadesNeil** [comment]
https://github.com/VOREStation/VOREStation/pull/2479
