### ISSUE TITLE
Shading overlay looks fuckin' weird with rotated view

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2432]
#### Brief description of the issue
Rotating the view breaks the shadow overlay (and a few other sprites, like multi-tile doors)

#### What you expected to happen
Rotating the view to just rotate the view.

#### What actually happened
![image](https://user-images.githubusercontent.com/14942479/32434831-1d1f5478-c2d7-11e7-8f6e-88ac9b1bad88.png)

#### Steps to reproduce
- go somewhere with shadows
- spin view

#### Code Revision
- Server revision: master - 2017-11-06
28869d7c18298da12a906ba4ce88ef5fd136f24e

#### Anything else you may wish to add:
- I don't know if anyone actually rotates their view given that nobody's mentioned or noticed this until now.

**Comment by SpadesNeil** [comment]
View rotate is 10 shades of fucked.

**Comment by Arokha** [comment]
Yeah this isn't getting fixed. Don't rotate your view, it's memes.

**Comment by Screemonster** [comment]
Yeah. Figured as much which is why I removed the view rotate from the hallucination list for 'meras.
