### ISSUE TITLE
Botanists don't have an icon on HUDs

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2439]
#### Brief description of the issue
For some reason, botanists have no icon at all on HUDs

#### What you expected to happen
To be able to put on a HUD and view everyone's job icon, including the botanist's.

#### What actually happened
I put on my security HUD and saw everyone's icon except for the botanist.

#### Steps to reproduce
- Find a HUD
- Put it on
- Go into a room with a botanist in sight

#### Code Revision
- Server revision: release - 
a5844f786ef2a09948e6718a7d418b05d95f9324 

 
#### Anything else you may wish to add:
- https://gyazo.com/daf06a2b9bfdb8262fa37c2a7b897140 screencap of the bar, everyone has an icon except for the botanist. The other security guard next to me also couldn't see the icon.

**Comment by SpadesNeil** [comment]
I am 90% certain Polaris fixed this recently.

**Comment by Arokha** [comment]
Fixed
