### ISSUE TITLE
The recipe for dough adds 1u protein to whatever recipe you make

### ISSUE THREAD

**Issue by Dankman** [VOREStation/VOREStation#2443]
#### Brief description of the issue
title

#### What you expected to happen
not title

#### What actually happened
title

#### Steps to reproduce
https://github.com/VOREStation/VOREStation/blob/master/code/modules/reagents/reagent_containers/food/snacks.dm#L3236

This is why everything involving bread tastes like meat.

**Comment by Dankman** [comment]
bluehaus found this, it makes the taste message of everything that you use that dough for get that "faint taste of meat" message

**Comment by aztectornado** [comment]
This is because eggs are a meat, iirc.
