### ISSUE TITLE
AI crashes upon changing Z-level being viewed.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#2445]
#### Brief description of the issue
Upon changing the Z-level being viewed by camera, it is possible, and often likely, that you will crash and have to restart the client.

#### What you expected to happen
To be able to freely go around Z-levels.

#### What actually happened
Crashing instantly upon going up usually, sometimes when going down.

#### Steps to reproduce
- (Step 1)Spawn as AI.
- (Step 2)Move up or down, it is likely to crash.

#### Code Revision
Server revision: release - 
a5844f786ef2a09948e6718a7d418b05d95f9324 
 
#### Anything else you may wish to add:
Its down right frustrating, to say the least, and makes playing the game as AI borderline impossible, let along doing rapid response to an emergency.

**Comment by Benemuel** [comment]
It also crashes when you view the pool, aswell.

**Comment by Benemuel** [comment]
Far as I can tell, its anytime water appears on screen aswell that causes a crash.

**Comment by SpadesNeil** [comment]
Might be related to https://github.com/VOREStation/VOREStation/issues/2186 really.

**Comment by CockatriceXL** [comment]
I was able to avoid the bug by moving my screen outside the station to where I could only see static before changing z levels. Also this causes Dreemseeker to hang instead of crash for me. I have to end the unresponsive program manually. When I get hit by #2186 Dreemseeker crashes out instead.

**Comment by Arokha** [comment]
All crash bugs are byond bugs, but I'm curious as to what causes it, or if there's a workaround, or if it works in some clients and not others. Have you tried the latest beta?

**Comment by Arokha** [comment]
Fixed in newer byond versions.
