### ISSUE TITLE
Ability to see camera blindspot areas as a AI using cheat engine

### ISSUE THREAD

**Issue by daylight2** [VOREStation/VOREStation#2446]
#### Brief description of the issue
Ability to see camera blindspot areas as a AI using cheat engine

#### What you expected to happen
For cheat engine to have no effect on the game

#### What actually happened
was able to remove camera blindspots by editing values

#### Steps to reproduce
- (Step 1) Play as AI, open cheat engine
- (Step 2) Scan for string "black"
- (step 3) copy all results to the address list
- (step 4) edit all values to anything but "black"
- (step 5) see everything, regardless if seen by cameras or not

#### Code Revision
a5844f786ef2a09948e6718a7d418b05d95f9324 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by kcin2001** [comment]
how is this an issue, it sounds like the intended use of a hacking tool

**Comment by OrbisAnima** [comment]
Polaris/bay issue, see if this happens on tg. 

That said, this probably happens with nightvision too.

**Comment by kcin2001** [comment]
but still, how is this an issue with our code when you are modifying it with outside tools

**Comment by OrbisAnima** [comment]
instead of using a simple layer to obscure things, you could do other tricks, thats why its an issue with code.

The problem of such tricks is performance, and complexity.

**Comment by kcin2001** [comment]
yeah just dont use a hacking tool

**Comment by Cameron653** [comment]
Although this requires a hacking tool, _this shouldn't be possible with a hacking tool._

Whatever section of the code that handles this should probably be improved, because this is actually a pretty severe mechanical advantage.

**Comment by Cyantime** [comment]
See: https://github.com/vgstation-coders/vgstation13/issues/12682
And: https://github.com/tgstation/tgstation/issues/29902
and probably other issues across other ss13 codebases

**Comment by kcin2001** [comment]
This is something that needs to be shown to pol not us though
