### ISSUE TITLE
Colorable bear ears do not preserve color when being sleeved

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#2449]
#### Brief description of the issue
One of my characters has colorable bear ears as part of her appearance. When she is resleeved, her new body has ears that seem brown or yellowish instead of being black.

#### What you expected to happen
For the new body to have black bear ears

#### What actually happened
They were not

#### Steps to reproduce
- Make character with black bear ears
- Make sleeve of said character
- Behold!

#### Code Revision
- release - a5844f786ef2a09948e6718a7d418b05d95f9324 
 
#### Anything else you may wish to add:
- Color of ear is 82 on all values , used custom species, Tajara as base.

**Comment by SpadesNeil** [comment]
@Arokha This
