### ISSUE TITLE
Secure briefcase unable to be unlocked again after first lock

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2451]
#### Brief description of the issue
Using the Secure Briefcase and setting the lock works fine, as well as unlocking it for the first time. Locking it again afterward though leads to it being unopenable due to the keypad being unusable. Clicking a number causes nothing to appear and even if you enter the right code, it just errors.

#### What you expected to happen
To be able to lock and unlock the secure briefcase as many times as I needed.

#### What actually happened
I got locked out of it and can't even use the keypad.

#### Steps to reproduce
- Obtain a secure briefcase
- Set the code and lock it.
- Unlock it with the code and store any items if you want to.
- Lock it when you are finished

#### Code Revision
- release - 
a5844f786ef2a09948e6718a7d418b05d95f9324 
 
#### Anything else you may wish to add:
- https://my.mixtape.moe/jrphsk.gif - GIF of me entering the correct code (01337) and having the code cause an error.

**Comment by SpadesNeil** [comment]
Might be Polaris bug.

**Comment by Anewbe** [comment]
Just tested this Polaris Side, does not occur for us. Looks like you folks might've changed something that prevents the numbers from showing up, too.

**Comment by SpadesNeil** [comment]
shit, wonder what we buggered this time
