### ISSUE TITLE
Used bugged camera monitor and lost control of my character

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2456]
#### Brief description of the issue
I used a camera monitor console while buckled to a rolling chair and it opened without a window to switch cameras. I moved away to close it and whenever I got close again the screen reappeared. I got unbuckled from the chair by a co-worker and realized I couldn't move. Tried relogging multiples times with no success. I could still move around while buckled to a chair, though. Had to use the tram and rejoin to finally fix it.

#### What you expected to happen
To use the camera console normally and move on with my day.

#### What actually happened
I used it and became a bizarre statue man who could only use rolling chairs to move around.

#### Steps to reproduce
- Buckle into a rolling chair
- Use a security camera console until no camera selection window pops up.
- Move away from the camera console until you regain your normal view and have someone unbuckle you from the chair.
- Become a statue.

#### Code Revision
-  release - 
a5844f786ef2a09948e6718a7d418b05d95f9324 

#### Anything else you may wish to add:
- Disarm attacks did nothing to push me down, but the pin worked. I just got back up and was unable to move like usual, sadly.

**Comment by SpadesNeil** [comment]
OOC Tab -> Cancel Camera View should fix that.
