### ISSUE TITLE
Teshari Prosthetics+FBP Non-existant

### ISSUE THREAD

**Issue by Lemmypepper** [VOREStation/VOREStation#2458]
#### Brief description of the issue
Teshari do not have prosthetics or FBPs like other species have.

#### What you expected to happen
Options for prothetics that atleast match the Teshari bodytype.

#### What actually happened
Species specific prosthetics are unavailable and the other options do not match since they were made with a humanoid figure in mind

#### Steps to reproduce
- (Step 1) Choose Teshari as a race
- (Step 2) Find that there are no prosthetics or a FBP for the species
- (Step 3) Try not to cry
- (Step 4) Cry a lot.

#### Anything else you may wish to add:
- (This is sort of my first Issue submission, so forgive me for any information that I accidentally left out or incorrect formatting)

**Comment by Lemmypepper** [comment]
Does the Send this to Polaris label mean I have to make the Issue on their Git as well?

**Comment by SpadesNeil** [comment]
It means if we develop a resolution, yeah, send it to Polaris.
