### ISSUE TITLE
putting platting on latice causes pressure damage

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#2460]
#### Brief description of the issue
putting plateing down in the aitruim make take pressue damage

#### What you expected to happen
to have air in the room when I put floor down.

#### What actually happened
that

#### Steps to reproduce
- (Step 1) put lattice down
- (Step 2)put plateing down
#### Code Revision
 a5844f786ef2a09948e6718a7d418b05d95f9324 
#### Anything else you may wish to add:
putting lattice down may make you be in the middle of floor two, with unsported lattice just floating there

**Comment by Cyantime** [comment]
Tiles placed on open space start out as vaccuum, https://github.com/VOREStation/VOREStation/blob/master/code/modules/multiz/turf.dm#L142

**Comment by SpadesNeil** [comment]
They shouldn't if they are inside.

@Cameron653 or @Cameron6531 why do you have two accounts
