### ISSUE TITLE
Energy Weapons and unloading Invisibility

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#2461]
#### Brief description of the issue
Some energy weapons, such as the Energy Lugar turn invisible when you remove the weapon clip

#### What you expected to happen
To have a unloaded state to the Lugar.

#### What actually happened
The gun turned invisible

#### Steps to reproduce
- (Step 1)Pick up/Buy a Energy Lugar [ Example gun]
- (Step 2)Remove the Energy clip
- (Step 3)Watch as the gun turns invisible.
- (and so on)

#### Code Revision
-a5844f786ef2a09948e6718a7d418b05d95f9324 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Novacat** [comment]
Energy Luger battery is not eject-able, I am guessing this was fixed at some point.

**Comment by SpadesNeil** [comment]
Energy luger is indeed not meant to have a removable battery. That was how we fixed this.
