### ISSUE TITLE
This is a shitpost

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#2480]
#### Brief description of the issue
Things I eat keep escaping my belly-graveyard via cloning

#### What you expected to happen
To not see my fat walking around in a new body

#### What actually happened
My prey got away

#### Steps to reproduce
Eat someone.
Churn.
Belch.
Nap.
Wonder why I'm hungry again.

#### Code Revision
Taco

#### Anything else you may wish to add:
The intent is to provide prey with a sense of pride and accomplishment for choosing to be food.

As for turnips, we selected initial destinations based upon data from how hungry I was and other adjustments made to said destination before I stuffed them in me. Among other things, we’re looking at average per-prey size and possibility to fit into my slit on a daily basis, and we’ll be making constant adjustments to the crew manifest to ensure that prey have challenges that are compelling, rewarding, and of course attainable via doing what turnips are meant to.

We appreciate the candid feeding, and the passion the prey has put forth around the current predator here on Virgo, our forums and across numerous social media outlets.

Our team will continue to make changes and monitor the crew manifest and update everyone as soon and as often as we can, most likely through turning you into fat.

**Comment by SpadesNeil** [comment]
:T

**Comment by SpadesNeil** [comment]
I mean I giggled but no

**Comment by Screemonster** [comment]
github needs a bike horn reaction image
