### ISSUE TITLE
Loadout Job based Skirts

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#249]
#### Brief description of the issue
Is just a plaid skirt. Not the actual uniform Skirt. Makes me sad. Is very minor issue but makes me sad. Counts right?

#### What you expected to happen
To get the Head of Security Skirt. Or actual job skirt that I chose in the loadout.

#### What actually happened
I got a fucking ugly plaid skirt. Cried in a corner.

#### Steps to reproduce
In the lobby, Setup Character, >Loadout ->Uniforms and Casual Dress ->Choose skirt, HoS or any other skirt. Join as the proper job, for example HoS using the HoS skirt. Get plaid skirt and cry.

#### Additional info:
Server revision: release - 2016-05-23

**Comment by Arokha** [comment]
This was fixed upstream.
