### ISSUE TITLE
PAI Remove Access prevents Adding Access from working

### ISSUE THREAD

**Issue by HalfdeadKiller** [VOREStation/VOREStation#2504]
#### Brief description of the issue

When adding access to a PAI, add access functions properly, but remove access seems to break the ability to add access unless the PAI rejoins into the card.

#### What you expected to happen

I expected the command to remove access and not break adding access in the future.

#### What actually happened

Remove Access prevents Add Access from functioning after being applied.

#### Steps to reproduce
- 1. Take ID card.
- 2. Click on PAI with ID card.
- 3. Select Add Access
- 4. Test Access
- 5. If access works, click on PAI again with ID card
- 6. Select Remove Access
- 7. Access is now removed.
- 8. Attempt to re-add access with an ID
- 9. Adding access gives no user << "<span class='notice'>You add the access from the [W] to [src].</span>" . Access is not properly added to the PAI and requires a restart of the PAI.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
866d6b90485c5306686d77f8a4239ddd8c50b358 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

/code/modules/mob/living/silicon/pai/pai.dm

/mob/living/silicon/pai/attackby(obj/item/weapon/W as obj, mob/user as mob)
	var/obj/item/weapon/card/id/ID = W.GetID()
	if(ID)
		if (idaccessible == 1)
			switch(alert(user, "Do you wish to add access to [src] or remove access from [src]?",,"Add Access","Remove Access", "Cancel"))
				if("Add Access")
					idcard.access |= ID.access
					user << "<span class='notice'>You add the access from the [W] to [src].</span>"
					return
				if("Remove Access")
					idcard.access = null
					user << "<span class='notice'>You remove the access from [src].</span>"
					return
				if("Cancel")
					return
		else if (istype(W, /obj/item/weapon/card/id) && idaccessible == 0)
			user << "<span class='notice'>[src] is not accepting access modifcations at this time.</span>"
return

We believe the problem is idcard.access = null under if("Remove Access"). Unsure on how to properly fix.

**Comment by Cameron653** [comment]
See: https://github.com/PolarisSS13/Polaris/pull/4312
