### ISSUE TITLE
Contaminated gear can apparently poison you through hardsuits and gloves now

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2511]
#### Brief description of the issue
Apparently contaminated items are so ridiculously toxic that holding them in a gloved hand while wearing a spacesuit will still poison you.

#### What you expected to happen
Wearing a fucking HAZMAT HARDSUIT to protect you from HAZardous MATerials.

#### What actually happened
my little health doll lost the 100% indicator and it made me sad.

#### Steps to reproduce
- put on complete hardsuit and gloves
- pick up contaminated item
- take damage

#### Code Revision
- Server revision: release - 
d2194a759af92a64e9392232841f351bf15d409f

**Comment by Cameron653** [comment]
I reported this on https://github.com/PolarisSS13/Polaris/pull/4181. The relevent lines of code is at 
https://github.com/PolarisSS13/Polaris/blob/master/code/modules/mob/living/carbon/human/life.dm#L823-L828

**Comment by Anewbe** [comment]
I'll try to look into it and have a fix by the 27th, November, 2017, but it's the week of Thanksgiving so I may or may not have time.

**Comment by SpadesNeil** [comment]
No rush. 👍

**Comment by Anewbe** [comment]
Alright, so to fix this to meet my standards requires more than a little work, but I can probably have a hackfix up in like... A day?

**Comment by Anewbe** [comment]
@Screemonster To double check, what sort of gloves were you wearing?

**Comment by Screemonster** [comment]
Since I was engineer at the time, most likely yellow insulated gloves. Hardsuit was one of the engineering hazmat ones (well, a child of them)

**Comment by Screemonster** [comment]
Fixed upstream.
