### ISSUE TITLE
Missing Virgo RnD items

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#252]
#### Brief description of the issue
Lack of shrink ray, thermal goggles and tactical headset blueprints in the Protolathe.
Additionally, the excavation drill is present however its resource requirements are incorrect as they show up as $steel and $glass instead of Metal and Glass like all other items.
#### What you expected to happen
To be able to construct a shrink ray and to see the excavation drill's correct requirements.
#### What actually happened
I was unable to build a shrink ray despite the research levels at the time. I saw the excavation drill with incorrectly input resource requirements.
#### Steps to reproduce
1. Perform RnD to the point where you obtain the levels for an excavation drill.
2. This is presumably also the point where you would've previously gotten a shrink ray.
3. Look at the drill's resource requirements. See incorrectly input syntax(?) resource names.
4. Look for a shrink ray. There is none.
#### Additional info:
 - **Server Revision**: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
I'll fix the excavation drill later today.

**Comment by Leshana** [comment]
Noooooooooooooooooooooooooooo! Not the thing!
Also, what if we add a unit test to detect these?
