### ISSUE TITLE
Solar grub attacks occur too often

### ISSUE THREAD

**Issue by Gearshy** [VOREStation/VOREStation#2521]
#### Brief description of the issue
The solar grub event appears to trigger really regularly. Like, to the point where it happens once just about every round.

#### What you expected to happen
Solar grubs to be somewhat more rare in appearances.

#### What actually happened
Solar grub infestations are literally more common than grid checks.

#### Steps to reproduce
- Peek in on a few rounds.
- See very few rounds with no solar grubs.

#### Code Revision
- release - d2194a759af92a64e9392232841f351bf15d409f 
 
#### Anything else you may wish to add:
- The current frequency could be okay if other hostile mobs could spawn instead of grubs - spiders, carp and/or drones could provide a decent variety in the daily dose of PvE.

**Comment by SpadesNeil** [comment]
We can reduce the frequency. Indeed, I also want to see other kinds of monsters appearing. I would like a ground-based mob invasion too.

**Comment by Ketrai** [comment]
Can always see about making an event where gaslamps and voracious lizards, with a small chance of a phoron dragon to appear on the ground level outside. Combine that with a knock down in grub frequency to get a more varied diet?

**Comment by Ketrai** [comment]
Apparently they are able to pop up more than once in a round too. this is easily fixable by adding a lil counter that counts to one and disables the event in a round once it's occured. I'll work on fixing this once I got some decent amount of time. exam period after all.
