### ISSUE TITLE
Great white carp turns invisible when eating people

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2540]
#### Brief description of the issue
Exactly what it says on the tin. Upon eating people, the great white carp turns invisible.

#### What you expected to happen
The carp eats someone and remains visible like any other mob, maybe gets a 'full' sprite.

#### What actually happened
The carp ate someone and turned invisible, not even an error sprite appeared.

#### Steps to reproduce
- Find or spawn a great white carp (/mob/living/simple_animal/carp/large/huge)
- Get eaten by it or have someone get eaten by it (Works with monkies too)

#### Code Revision
- Main server: d2194a759af92a64e9392232841f351bf15d409f
- Testing server: master - 2017-11-28
6dca303ad1405be7b55d57ceaf60c63a602d627b
 
#### Anything else you may wish to add:
- https://imgur.com/a/wmhHO (GIF of the issue, taken on testing server)
- https://gyazo.com/ed56ec1b29ef3aca5f7aee4eff61e5fa (Screencap of the chat to show the attacks happened)
- The issue persists on both the testing and main server, however, I can only get images and do things while on the testing server. 
- Tested the carp with one prey and two (it has a vore max capacity of two) and both had invisible sprites. Returns to normal after they're digested or removed.

**Comment by SpadesNeil** [comment]
Does not occur with eating mice.

**Comment by Verkister** [comment]
Fixed in #2568

**Comment by SpadesNeil** [comment]
Icon still breaks when it's killed I think.

**Comment by Arokha** [comment]
Pretty sure this is fixed now
