### ISSUE TITLE
Accidental deletion of solar grubs

### ISSUE THREAD

**Issue by Kersakof** [VOREStation/VOREStation#2541]
#### Brief description of the issue
When dismantling a solar grub infested air alarm, the grub was deleted. I unscrewed it and cut the wires, then got told I was supposed to multitool it instead. So I put the wires back in and put the hatch back on, thing stopped flashing and I hit it with the multitool with no action.

#### What you expected to happen
The grub to fall out for me to hit it or w/e

#### What actually happened
The grub was deleted maybe?

#### Steps to reproduce
- See a grub infest an air alarm
- Screwdriver and cut the wires
- Rebuild the air alarm and multitool it

#### Code Revision
- Server revision: release - 
d2194a759af92a64e9392232841f351bf15d409f 
 
#### Anything else you may wish to add:
-

**Comment by SpadesNeil** [comment]
You squished it! Ew!

**Comment by Ketrai** [comment]
That seems super silly and unintentional.

**Comment by Cyantime** [comment]
Deconstructing a machine with a grub in it deletes the grub, this is basically fine. Just think that it got caught between some moving parts and it's a fine paste now.

**Comment by Mewchild** [comment]
I think this is easy enough to handwave. If you deconstruct a machine, add a chat notice saying "The juvenile solargrub was crushed" or something to the effect.
