### ISSUE TITLE
AI crewmember's icon broken. AI double emote bug.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#2546]
#### Brief description of the issue
- AI crewmember's icon doesn't show up in some/all cases.
- While eaten via the hardlight nom, the AI's emotes will show up twice.
#### What you expected to happen
- Able to use crewmember icon
- See only one /me

#### What actually happened
- Invisible icon
- Double AI emotes.

#### Steps to reproduce
- Select crewmember icon as sprite

- Get eaten by AI and have AI emote 

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/ac2ffeea090d23133b1aabd44758d5d353ddd840
 
#### Anything else you may wish to add:
- Needs testing to see if the icon bug and Ai emote bug will happen in all cases or only in some cases.

**Comment by SpadesNeil** [comment]
"Second half" of this is fixed. Marked as hotfixed.

Mark it as resolved when a full fix is added.

**Comment by Arokha** [comment]
Someone was working on fixing this upstream but I think they gave up.
