### ISSUE TITLE
Pointing errors

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#255]
#### Brief description of the issue
Head of Security's office: pointing at the locker will point at the office door.
#### What you expected to happen
For me to point at the locker, not the door.
#### What actually happened
I turned around and pointed at the door.
#### Steps to reproduce
1. Get into the Head of Security's office.
2. Point at his locker.
3. It will point at his door.
#### Additional info:
 - **Server Revision**: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
This is REALLY specific and I'm not sure where else it can be found.

**Comment by SpadesNeil** [comment]
Probably won't fix this bluespace bullshit. Though I think someone figured out how to fix this once before.
