### ISSUE TITLE
Critical health.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#2554]
#### Brief description of the issue
Whenever someone goes into crit, and they go down once to three times, they seem to get stuck without being able to get up forever. until treated. 

#### What you expected to happen
To actually have a game mechanic not completely turn the player dependant on outside help.

#### What actually happened
To be lying down in crit, unable to get up forever.

#### Steps to reproduce
Go into crit.
Fall down a few times.
Never get up.

#### Anything else you may wish to add:
I would suggest the ability to crawl, or at least very slow self treatment if you got medicine. This way you can at least crawl to an intercom, get help that way. Or generally just crawl to a more public area. Also silly when you got medicine, but you can't do anything because you're forced to stay down on the floor. In a lot of cases you don't even die either, you just sit in crit for an hour or longer until picked up.

**Comment by Cyantime** [comment]
That's exactly what crit is, though? If you go into crit you are incapacitated and dying, and should absolutely require outside help. The only issue here is sitting in crit for and extended period of time, could you go into more detail on when/how that happened?

**Comment by Screemonster** [comment]
That's kinda the point of being in critical condition.

**Comment by SpadesNeil** [comment]
Not a bug.
