### ISSUE TITLE
Add text to speech device to the loadout

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#2559]
#### Brief description of the issue
Science can make text to speech device. We got plenty of snowflakes who can't speak and are mute. Instead of relying on languages (sign language) which sometimes randomly reset, wouldn't it be nice if these people can select a text to speech device from the loadout menu?

#### What you expected to happen
for mute characters to have a text to speech device

#### What actually happened
no science staff, so something as simple as this is impossible to get, and makes communicating more annoying than it has to be, especially when having multiple pda messages at once.

#### Steps to reproduce
Be mute
Check loadout
Cry silently

**Comment by Arokha** [comment]
Done
