### ISSUE TITLE
Ring Selection spawns phoron contaminated

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2561]
#### Brief description of the issue
When spawning in while wearing an item from the "Ring Selection" loadout item, the ring is phoron contaminated on spawn.

#### What you expected to happen
All items appear as normal, with no danger to owner.

#### What actually happened
Ring is toxic until washed, and player requires anti-toxin to heal to full.

#### Steps to reproduce
- Select an item from the ring selection
- Select gloves, or spawn as a job that wears gloves
- Remove gloves and ring, wash ring.

#### Code Revision
- d2194a759af92a64e9392232841f351bf15d409f
 
#### Anything else you may wish to add:
https://i.imgur.com/mURttPj.png

**Comment by OrbisAnima** [comment]
I wonder if they are spawning on 1,1,1 and then moving to the user?

**Comment by Mewchild** [comment]
As an update to this, it's only contaminated if it spawns under gloves.

**Comment by Arokha** [comment]
Probably won't happen anymore.
