### ISSUE TITLE
Medihounds seems to have no HUD?

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2562]
#### Brief description of the issue
Tested on solo server. Tried to see the damage on a dummy after biting it, tried to search for glass huds. Found no glasses for medical HUD. Was disappointed.

#### What you expected to happen
Expected Medical hud. 
#### What actually happened
Found none. Complained in LOOC. Now i am here. 

#### Steps to reproduce
- (Step 1) Medihound.
- (Step 2) Open Inventory.
- (Step3) Disappointment. 

#### Code Revision
-Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
Yeah those were taken out because of the sensory augmentation thing being fixed, but now that you mentioned it I realized they would still have use for the medical/security records stuff and such. Fixing...

**Comment by lbnesquik** [comment]
Issue has been fixed, cheers.
