### ISSUE TITLE
Cyborgs can't whisper. 

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2563]
#### Brief description of the issue
Cyborgs can't whisper. Nothing go through. 

#### What you expected to happen
Whisper to work. 

#### What actually happened
Whisper didn't. Got runtime instead. 
[06:01:38] Runtime in say.dm,202: Cannot read null.whisper_verb
   proc name: say (/mob/living/say)
   usr: (the wooden floor) (96,58,3) (/turf/simulated/floor/wood) ()
   usr.loc: (the wooden floor) (96,58,3) (/turf/simulated/floor/wood) ()
   src: Default Cyborg-418 (/mob/living/silicon/robot)
   src.loc: the wooden floor (96,58,3) (/turf/simulated/floor/wood)
   call stack:
   Default Cyborg-418 (/mob/living/silicon/robot): say("Test", null, "says", "", 1)
   Default Cyborg-418 (/mob/living/silicon/robot): say("Test", 1, 1)
   Default Cyborg-418 (/mob/living/silicon/robot): Whisper("Test")
#### Steps to reproduce
Just try to whisper as a borg. 
#### Code Revision
Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by lbnesquik** [comment]
I've been informed that you are supposed to use subtle. So this issue could be marked with "Eh, just use X" and close it.

**Comment by Jakksergal** [comment]
That's.. Terrible. Don't close something because you think there's an alternative. Subtle works differently from whisper. Not being able to whisper is a real bug that has a large impact on the way people play borgs.

**Comment by lbnesquik** [comment]
Oh uh. I was under the impression it wasn't an issue anymore since subtle work about just as good. This issue didn't get much attention either so i felt it was fine. Is only staff supposed to close issues btw?

**Comment by SpadesNeil** [comment]
You're allowed to close your own issues but this _is_ a bug, albeit a minor one with an easy work-around.

**Comment by lbnesquik** [comment]
I just tested this on my own server and was able to whisper. I think this can be closed.
