### ISSUE TITLE
Hounds lack basic tools. 

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2564]
#### Brief description of the issue
Every hounds lack crowbars. The K9 and janihound lack extinguishers. The medihound and janihound lack flashes. Those three modules are present on all other borgs, but thoses three are the most played ones. 

#### What you expected to happen
Excepted tools for power outages, crew members dying on fire next to me or rowdy drunkards. 

#### What actually happened
Found none of those. Had to stand on the sidelines. 

#### Steps to reproduce
Simply open mentioned hounds inventories. 

#### Code Revision
Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0

**Comment by Verkister** [comment]
#2566

**Comment by SpadesNeil** [comment]
@Verkister please from now on say _in the PR_ that you've fixed something.

In this case:

`Fixes #2564`
or
`Fixes https://github.com/VOREStation/VOREStation/issues/2564`

The words "Resolves" (for features) and "Closes" (for obsolete things) are also acceptable.
