### ISSUE TITLE
RCD removing turfs in the atrium creates space tiles

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2565]
#### Brief description of the issue
If someone uses the RCD to remove a turf such as a gantry in the 3rd floor level, it creates a space tile and removes all the air.

#### What you expected to happen
For it to create open space.

#### What actually happened
SPAAAAAACCCEEEEEEE

#### Steps to reproduce
- Get RCD
- Build a walkway out over the atrium or something
- remove it with RCD
- choke to death

#### Code Revision
Server revision: release - 
d2194a759af92a64e9392232841f351bf15d409f 
 
#### Anything else you may wish to add:
- The area in question is as follows:

The ÿAtrium Second  Floor
/area/tether/surfacebase/atrium_two

(E) (C) (M) base_turf = null

Also might be related to this proc: https://github.com/VOREStation/VOREStation/blob/3d077aed8d89ad7d9c19647908f706285e286ccb/code/game/turfs/simulated.dm#L65

as it's called by the RCD on this line:
https://github.com/VOREStation/VOREStation/blob/3d077aed8d89ad7d9c19647908f706285e286ccb/code/game/objects/items/weapons/RCD.dm#L125

The area does _not_ appear to be in the list of overridden areas, but it's hardcoded to turn the tiles into either space, or mineral turfs if it's an overridden area. This is certainly not ideal and should definitely be changed to account for open space turfs.

**Comment by Leshana** [comment]
This particular issue was fixed upstream.  However the fix is causing runtimes. Working on it.
