### ISSUE TITLE
Alien empress sprite issue

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2567]
#### Brief description of the issue
Empress has no vore icons but the option is toggled on when spawned, resulting in a lack of sprite when it eat anything. 

#### What you expected to happen
Obvious

#### What actually happened
Obvious

#### Steps to reproduce
- Spawn empress
-Eat something
-Watch all sprites disappear into the void

#### Code Revision
Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
#2568
