### ISSUE TITLE
Botanical bag update issue. 

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2571]
#### Brief description of the issue
When you have a botany bag with produce in, if you bag inventory is open and you empty the bag into a Smartfridge, the fruit icons stay there and do not go away except by restarting. 

#### What you expected to happen
That the thing would update

#### What actually happened
It didn't. 

#### Steps to reproduce
- Get botany bag with produce
- Open inventory and fill smartfridge. 
- Be disappointed into forcing to reset. 

#### Code Revision
-Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0 
 
#### Anything else you may wish to add:
- It appear to be 'just' a matter of updating the sprites show in inventory when you empty.

**Comment by SpadesNeil** [comment]
I'm pretty sure this has been reported before. Let me check.

**Comment by SpadesNeil** [comment]
I guess not. Is it still a bug? I thought Polaris fixed this.

**Comment by Tasald** [comment]
https://github.com/VOREStation/VOREStation/issues/501 

Here ace.
