### ISSUE TITLE
Suggestion: slap cigarettes etc out of mouths

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2573]
#### Brief description of the suggestion
tl;dr I want to be able to slap cigars, cigarettes, e-cigs, pipes and other such smoking accessories out of people's faces by targeting the mouth and disarming or pulled-punch or similar.

Because slapping some motherfucker and pointing at the no smoking sign is _so_ much more effective than  just yelling at them ineffectively to stop smoking in the chemistry lab.

**Comment by Dinnel** [comment]
Could it be applied to anything that covers the mouth or face? Or just things that just sit in your mouth?

**Comment by lbnesquik** [comment]
Should only be for lolipops and that sort of things. Otherwise you would be able to swat gasmasks, surgery masks and anything else you can put on your face.
