### ISSUE TITLE
Simple animals missing verb

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2574]
#### Brief description of the issue
It appear almost none of the simple animals have the verb sleep given to them. It's fine for 92% of the time except that unless i am mistaken, the resting/sleeping sprite is linked to the sleep verb. 

#### What you expected to happen
Placeholder

#### What actually happened
Idem

#### Steps to reproduce
Same thing
#### Code Revision
Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
The resting sprite is linked to rest verb.

**Comment by lbnesquik** [comment]
I am either missing  something or /mob/living/simple_animal/hostile/alien/queen/empress can't use their sleep sprite In fact, every single simple mobs beside the Wae/Fae, catgirls and otties seems to not have access to their resting sprite.

**Comment by Verkister** [comment]
Huh yeah seems most mobs don't even have the vars set up. Looks like cats and xenos are the only ones that even have the unused sprites

**Comment by lbnesquik** [comment]
It's mostly them yeah

**Comment by Verkister** [comment]
Tossed a PR up to Polaris that enables rest icons for the cats and xenos. The rest will need theirs made in the first place.
