### ISSUE TITLE
Alien queen empress/mother sprite issue

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2575]
#### Brief description of the issue
Edit:
The alien mother has the usage of special vore related icons toggled on but doesn't actually have any icons, resulting in the mob vanishing whenever they eat something. I've been told it's an issue due to being a child of another mob. Same thing happen with the praetorian sentinel. 
#### What you expected to happen
Words

#### What actually happened
Things

#### Steps to reproduce
-Nothing

#### Code Revision
- Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
- Just turn off vore icons for now and it will be fine.

**Comment by lbnesquik** [comment]
Do not mistake all the queens together. There is a ton. Im speaking of the largest one.

**Comment by lbnesquik** [comment]
Same issue has been found with the praetorian. 
mob/living/simple_animal/hostile/alien/sentinel/praetorian
mob/living/simple_animal/hostile/alien/queen/empress/mother
Thoses are the two i've found.

**Comment by Verkister** [comment]
Can confirm mother and praetorian have no vore overrides in the code
