### ISSUE TITLE
Suggestion: Shower temperatures

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2580]
#### Brief description of the issue
Some nice fluff would be the ability to set temperature for the showers, maybe with just 3 settings, maybe more complicated. Could make the hot/cold blooded trait slightly more interesting too. 

#### What you expected to happen
Variable showers

#### What actually happened
Military/prison/public pool showers that are mildly hot. 

#### Steps to reproduce
None
#### Code Revision
- Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
I feel like having some very vague way of setting the temperature would work better than a precise kelvin based temp system.

**Comment by LittleBigKid2000** [comment]
It's possible to change the temperature with a wrench, though the only options are normal, boiling, and freezing. Despite the names and text that may pop up when you're under a boiling hot shower, neither makes the temperature indicator move to either extreme and neither does damage (To a normal human or monkey) as they do on other codebases.

**Comment by lbnesquik** [comment]
It would be a different system. Like a switch or some other gauge to set temperatures with some degree of control. What kind of person brings a wrench to a shower anyway.

**Comment by LittleBigKid2000** [comment]
I know what you mean, I'm just nothing that something similar exists.
