### ISSUE TITLE
Suggestion: Aphrodisiac bite trait

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2583]
#### Brief description of the ~~issue~~ **suggestion**
It would be an addition for the succubus style of characters. Basically, on bite, they inject a few units of a trait only aphrodisiac reagent. Said reagent metabolize slowly, make the injected person emote blushing/being red headed for all to see while they get red status messages suggesting they are feeling turned on. It wouldn't be made in the chem labs.  You would need a timer and/or a grab to be able to inject it, otherwise some peoples would just bite everyone around with impunity. 

#### ~~What you expected to happen~~ Who you stole this from:
Jasmine Lizden/Yiris/Katelynn  on the discord.

#### Steps to reproduce
None. 

#### Code Revision
-Suggestion, so no code
 
#### Anything else you may wish to add:
- Jasmine did most of the headwork on discord. Just posting that so it's 'visible'. 
-It doesn't _need_ to be a bite, it could use a breathing/gas version for all the plant based or your weird lizards. Something that would only work on one person of course.

**Comment by Cameron653** [comment]
Will look into this eventually.
