### ISSUE TITLE
Spawned Meatbread slices have no nutrition and are eaten in one bite

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2584]
#### Brief description of the issue
Simple issue. Meatbread slices in lunchboxes actually hold nothing at all. When you try to bite into it, you get the message "None of the meatbread slice left!"
 
#### What you expected to happen
Having something to eat on the station.

#### What actually happened
Ghost meatbread :c 

#### Steps to reproduce
-Get lunchbox with meatbread slice
-Try to bite into it
-Be disapointed and confused. 

#### Code Revision
- Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Appears to have been fixed.

You unwillingly chew a bit of the meatbread slice.
You can taste the flavor of bread and a hint of some sort of meat.
You unwillingly chew a bit of the meatbread slice.
You unwillingly chew a bit of the meatbread slice.
You unwillingly chew a bit of the meatbread slice.
You finish eating the meatbread slice.
