### ISSUE TITLE
Feature: Mute Vore Sounds

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2585]
Following up on a conversation and a suggestion made in discord: I'd like to suggest that vore/belly/hunger/digestion sounds be added to their own audio channel, that can be toggled with a verb , similarly the Jukebox, Lobby Music, and Admin Midis.

**Comment by SpadesNeil** [comment]
I'd like to see this done.

**Comment by Arokha** [comment]
Did this already
