### ISSUE TITLE
Suggestion: Add an internal atrium airlock for flying characters to enjoy

### ISSUE THREAD

**Issue by SingoDingo** [VOREStation/VOREStation#2586]
As of currently with the glass having been added to the atrium, it's difficult for flying characters to make use of their ability in the most obvious place for it. A few enterprising engineers have made windoor airlocks on a few occasions, and I think it'd be a nice thing to have around permanently, to make the flying trait actually something literally anyone ever uses.

Pros:
- Lets winged characters make use of their trait, by giving them a designated area to fly around in.
- Would allow winged characters to make use of drop-noms so it actually ever gets used, cause magpie swoops why not.
- Make people walk the plank?

Cons:
- Some idiots might use it to jump into the koi pond and get hurt, I guess.

**Comment by SpadesNeil** [comment]
Engineering can build this if they want. Otherwise it would not be standard, because it's such a hazard.
