### ISSUE TITLE
Fax machines requiring Head access

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#259]
#### Brief description of the issue

Fax machines are a vital part of the station, as they facilitate CC/Station communications. When something happens and an ERT or a rep is needed, you fax CC.

On Polaris you need Head access to use a fax machine, which is counterproductive, given how sometimes players have to reach CC.

#### What you expected to happen

On the old code, all you needed to do was take your paper, write your message, put your ID into the fax machine, and send it.

#### What actually happened

I built a fax machine and could not use it due to the required access.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Fax machines built should be changed to have no access restriction by default, but it should be possible to set access restriction.
