### ISSUE TITLE
Handcuffs cannot be removed in-belly

### ISSUE THREAD

**Issue by Ekrotus** [VOREStation/VOREStation#2590]
#### Brief description of the issue
You cannot remove handcuffs for some reason if you're inside a belly. It makes the attempt, the text "Attempting to remove the [handcuff name]. (This will take [x] minutes/seconds and you must remain still)."  Even if the belly owner/predator completely stands still for the entire duration or longer, nothing happens.

#### What you expected to happen
- Handcuffs would be removed and/or dropped, then I could resist again to trigger belly resist text.

#### What actually happened
- Literally nothing. Trying again just made it try removing the handcuffs again.

#### Steps to reproduce
- Apply handcuffs to the individual.
- Grab intent, eat them to put in a belly.
- Have them attempt to remove the handcuffs once inside.

#### Code Revision
- Server revision: release - d2194a759af92a64e9392232841f351bf15d409f 

#### Anything else you may wish to add:
- Once was with Wire Restraints/Cuffs, the other was with Fuzzy Cuffs. Both instances I was "Pinned" with Grab + Upgrade Grab + Disarm intent.

**Comment by Screemonster** [comment]
People who get bellybrigged can't just resist out of their cuffs and attack the sec officer from the inside like the greytiding shits they are? This sounds like a feature.

**Comment by Ekrotus** [comment]
Well, the original situation was that if the pred moved, it would cancel the cuff removal action since it force-moves the prey inside to another tile and, to remove cuffs, the restrained person isn't allowed to move for the duration of the attempt.

**Comment by SpadesNeil** [comment]
I mean _I guess_ this is a bug, but I also really don't want to fix it.

**Comment by Ekrotus** [comment]
I mean that's fair, it *is* rather niche. Not like it's a gamebreaking emergency.

**Comment by Arokha** [comment]
Probably interferes with the resist in bellies, but I mean. I'm okay with this not getting fixed, vore server and all.
