### ISSUE TITLE
Suggestion: RPED and powercells

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2595]
#### Brief description of the issue
It is impossible to put power cells in the RPED for parts exchanging. It's annoying for when you want to upgrade the cyborg rechargers or anything that have power cells. 
Currently, what you have to do is:
-Screw open the machine
-Crowbar it back to a machine frame
-Put in the desired cell.
-Grab everything off the floor, including the things that don't fit in RPED units either like cables, beakers and so on.
-Screw closed the machine. 

#### Code Revision
- Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
- It also make it very annoying to carry parts as power cells are pretty big in backpacks. If you upgrade all the five in floor 3, you practically have to empty your bag just to carry them around.

**Comment by Arokha** [comment]
Would need to be coded per-machine, because while machines all share a single var that holds their parts, they all have implemented cells differently.
