### ISSUE TITLE
Suggestion: tweak voremob behaviour with regards to absorption

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2596]
#### Brief description of the issue
At the moment, we have a few absorbymobs on the map, mainly gaslamps. They don't kill their prey, but the only way out of them once absorbed is OOC escape, which prompts people to have to kill them ICly to get people out. The resist button _does_ allow you to escape from them, but it also has a chance of prompting them to absorb. To solve this, I propose adding a sleep() after they absorb someone, so that after spending some (variable) amount of time as pudge, the bellymode switches back to unabsorb, dumps the prey back into the belly, and allows them to struggle again. Maybe they'll get out, maybe they'll just get absorbed again by a teasecritter, who knows?

Having the bellymode reset to its initial state some time after being changed by RNG-struggles is probably a good idea anyway.

Another idea was to have some mobs have an additional bellymode that _cannot_ be selected by normal means through the vore panel, that will _either_ digest _or_ absorb depending on the prey's digestibility prefs.

#### What happens now

1. Prey are eaten by an absorbymob.
2. Prey struggle, prompting it to absorb them (on an rng% chance).
3. They're stuck there basically forever unless they OOC escape or someone kills the mob.
4. Maybe they wanted to be digested instead.

#### What you want to happen

1. Prey are eaten by a mob.
2. Prey struggle, prompting it to switch bellymode (if rng applies)
3. If the bellymode is "digest" or "process" and the prey are digestible, digest them.
4. If the bellymode is "absorb", or if it is "process" _and_ the prey are not digestible, absorb them.
5. Upon modeswitching, wait some amount of time. Certainly long enough for prey to be absorbed/digested.
6. After the timer elapses, set the bellymode to unabsorb. Then the mob's roundstart stance some time after.

**Comment by HzDonut** [comment]
As a note, it's been observed that killed a mob that has somebody absorbed will delete the person from existence, so adding a way like this for people to get absorbed will definitely help in avoiding situations like that in the future.

**Comment by Screemonster** [comment]
Further: giving people a way to get out of passive voremobs _besides_ struggling might be a neat thing to do. Or an automatic release every so often.

don't do it _all_ the time so people who wanna just chill in a tum aren't ejected, maybe require some deliberate action to indicate that you're passively waiting to be let out (such as resting). Obviously this should only happen on "hold" mode and shouldn't eject actually-absorbed people.

**Comment by HzDonut** [comment]
Perhaps it ejects the player automatically unless they're _resting_ since players can do that while inside mobs. It could be used a trigger to say 'never release this player' then once they're done, they just hit rest again to stand up and wait for the timer to run down until auto-eject aaaand out they go to return to their duties.

**Comment by Screemonster** [comment]
Resting as an "I'm okay with staying" signal would work without having a separate "are they absorbed" check too, since being absorbed forces people to rest. (possibly worth putting the check in for sanity's sake anyway)

**Comment by Screemonster** [comment]
Having looked through the belly code, this would be a fairly simple thing to do (the "process" mode is something that can be skipped or left for later). #1998 refers to the belly-struggling "not working", which is possibly down to the struggle messages giving you no feedback to let you know that your escape attempt was successful (and then taking so long that you inevitably hit resist again).

One thing to consider is the edge case where a mob has an absorb chance _and_ a digest chance, because this could get the mode to switch from one to the other. Having "digest" only ever switch back to "hold" without going through unabsorb could possibly lead to undesired outcomes if, say, an absorbed prey is in the stomach then someone else struggles and triggers digest mode - or even re-triggers absorb mode. When working on this, make sure to include a check in the random mode-switching to make sure it's not already in that mode.

**Comment by Very-Soft** [comment]
I like these ideas here, these are neat!<3

**Comment by Screemonster** [comment]
Okay, so, quick testing has confirmed that since the mob revamp, retaliate mobs _forget_ who they're angry with if they lose line of site. However, some mobs _do_ call for help - so if you grab a catgirl, all the catgirls in the room will dogpile you (well, catpile you). The resulting burly brawls in past events are likely people jumping in to save the poor dumbass that aggro'd them and got ate and the result is.. well.

![image](https://user-images.githubusercontent.com/14942479/34514660-51e52f5e-f066-11e7-9c52-8c2ee00a8f8e.png)

**Comment by Arokha** [comment]
`I propose adding a sleep()`

Don't sleep in anything that's part of Life() on anything, the mob controller will burst into flames.

Just make it so you can resist against absorption in simplemobs.

**Comment by Screemonster** [comment]
I meant spawn() (or some timer or whatever), got them confused. Bellies should really reset to initial state after the randomchance changes anyway. Long enough to finish doing their thing.
Absorbing stunlocks so you can't resist, would need some other button to try and wriggle free of pudge.

**Comment by Arokha** [comment]
You fixed with newspaper
