### ISSUE TITLE
Flight Trait balance. 

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2597]
#### Brief description of the issue
So, if you look into the trait menu, you can find among many other  traits of varying utility the Winged flight trait. Like it's name tells you, it grants you winged flight, making your character sprite move slightly up and down on the tile you are on. The thing is, while it does look fancy. The winged flight ability actually doesn't give any real positive advantage. here they are in a sort of list that isn't sorted:

-Flight doesn't let you fly over most obstacles. This include tables of all sorts, railings, machinery, canisters. Basically anything that stop a walking person will stop you too. Which is a little bumming since teshari can just vault over tables and railings easily.

-Linked with the first complain, anything you hit will knock you down. This include walls, airlocks even if you do have access to them, machinery, railings, glass in any state. 

-When you trip over a railing, you pass over it, giving you potentially very damaging wounds(Such as falling down R&D stairs). Otherwise, slamming into something give you a stun, 6.3 brute damage while also being embarrassing. 

-Flying doesn't actually make you faster. I actually tried the trait for one of my bird characters, the lore of which claims that they "have been clocked at speeds of over 35 miles per hour". Slightly disappointing but not a problem itself. 

-Flying doesn't actually take you off the ground, meaning you will step into glass or any kind of spills like blood and make bloody footsteps. 

-Flying itself is like moving into space. You don't stop going into a direction until you press hover. It makes flying more immersive in a way but given that slamming into anything can have bone breaking consequences..

-Not really an issue but more as a note. You can't fly over peoples either.
So that's what i have found out. Basically, flying is walking drunk. Except it also apparently cost nutrition. If none of you feel like actually changing any of that, it should at least be placed into the Neutral list of traits given that it is by far the least useful trait of all, actually give you many ways to hurt or kill yourself while giving only one benefit. The ability to fly into the middle of the atrium when all the railings and glass is removed. 

#### Code Revision
- Server revision: master - 2017-12-14
bbddd8b722679657e546534d9a176a078f2d5dd4 
 
#### Anything else you may wish to add:
- Winged flight is also expensive, sitting at 2 points.

**Comment by Screemonster** [comment]
It's actually pretty useful OUTSIDE. Flying around the top level of the plateau in particular.

**Comment by lbnesquik** [comment]
Is it?

**Comment by Ketrai** [comment]
it's more of a fluff thing than anything, wouldn't want it to be too powerful. but it should also still make sense. like. glass shouldn't hurt you for sure. I do stil llike obstacles blocking though.

**Comment by lbnesquik** [comment]
I don't mind obstacle blocking, just at least don't make everything be a stun+damage whenever you walk into it. Especially railings.

**Comment by Ketrai** [comment]
gives medical something else to do, so I don't mind too much. Should nerf a few things though, like doors you got access to, etc.

**Comment by lbnesquik** [comment]
You mean buff?

**Comment by lbnesquik** [comment]
Note added.

**Comment by lbnesquik** [comment]
To my sight, it's currently the worst positive trait of all.

**Comment by Very-Soft** [comment]
Flight gives you an extra movement option which can allow you to get to areas that other people simply cannot without modifying the station. You can also modify parts of the station to specifically cater to flying, as I've seen done a number of times. 

It does have its disadvantages if just casually used to move about in an enclosed space, sure. But I wouldn't really expect one to try to fly around the bar, where there may be light fixtures, raised tables and chairs and other things, or the tight spaces of maintenance. 

I wouldn't say it's the worst positive trait. It's mostly a fluff thing, and it's a fluff thing that -does- actually have advantages. (I'd say that Darksight is actually more useless, being as you need mesons to actually use it to decent effect. Just as a note)

**Comment by Arokha** [comment]
Doesn't look like it's changing.

**Comment by lbnesquik** [comment]
Sad
