### ISSUE TITLE
light eyes are not used 

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#2599]
#### Brief description of the issue
The eyes sprite thats supposed to be used when a borg's lights are on are not being used for dogborgs

#### What you expected to happen
for the eye lights sprite to be used

#### What actually happened
they are unused

#### Steps to reproduce
- (Step 1) be a borg
- (Step 2) turn on your lights
- (and so on)

#### Code Revision
- d2194a759af92a64e9392232841f351bf15d409f
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Can you specify what borgs?

**Comment by kcin2001** [comment]
I dont know why i didnt say it but it's on the dog borgs i assume its another of the things thats in cit but not here

**Comment by Verkister** [comment]
The dogborg headlights are pretty much just a porting relic from citadel where those were used on all borgs back then.
