### ISSUE TITLE
Removing a mech's battery on a charging pad prevents recharging with new cell

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2601]
#### Brief description of the issue
Removing the battery of a mech while it's on a charging pad causes the new cell to not recharge.

#### What you expected to happen
I'd move the mech onto a pad, take out the old battery, slot in a better one, and the mech would recharge itself.

#### What actually happened
I put in the new battery and the charge doesn't increase.

#### Steps to reproduce
- Move a mech onto a charging pad, any one works.
- Remove the mech's battery.
- Put in a new, empty one.
- Watch as the mech doesn't recharge and now you can't even move it off the pad because it's dead.

#### Code Revision
- release - 
d2194a759af92a64e9392232841f351bf15d409f

**Comment by Arokha** [comment]
I can see that it's coded to just not support this, so it's not a bug. `mech_bay.dm` if anyone wants to think of an elegant way to change it.

**Comment by SpadesNeil** [comment]
oh wait you already retagged this -changes tags back-
