### ISSUE TITLE
Contaminated clothes from item safe digestion damage the predator

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2604]
#### Brief description of the issue
Using item safe digestion on a person causes their clothes to drop into the predator's belly and leaving that digestion setting on causes them to become 'contaminated with acids' which functions the same way as phoron contamination...however this leads to the predator getting some nasty toxins after vore if they enjoy that setting, plus some preds like to keep clothing in them as a trophy of sorts which isn't possible with this issue present, unless that want to keep taking anti-toxin medications.

#### What you expected to happen
I'd digest my prey and they'd leave a pile of clothes in my belly that'd leave me fine since it's technically just clothes soaked in my own acids.

#### What actually happened
I got sick as hell from toxins damage and had to eject all the items and snarf down an 'airlock' pill to remove the toxins.

#### Steps to reproduce
- Find a suitable prey.
- Eat and digest them with item safe digestion on
- Leave that setting on after they're gurgled, even for a. second for at least ONE clothing item to become contaminated.
- Suffer.

#### Code Revision
-  release - 
d2194a759af92a64e9392232841f351bf15d409f

**Comment by Arokha** [comment]
Doesn't seem to happen anymore. Did a lot of contamination testing when refactoring vore and never encountered toxins.
