### ISSUE TITLE
Ghost items that will haunt you forever! (until you relog)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2605]
#### Brief description of the issue
For some reason after eating and digesting prey with item safe digestion on, and I eject their clothes, those clothes will appear ALL OVER MY HUD at completely random until I relog, this has been persistent for many revisions now, and I don't know why I haven't reported it until now. 

#### What you expected to happen
I'd just spit out the clothes and go on with my day.

#### What actually happened
The sprites of items will just appear all over my screen at complete random, sometimes even getting in the way of the HUD (once it blocked my oxygen icon and I couldn't turn on my internals)

#### Steps to reproduce
- Eat prey, digest them with item safe digestion on
- Spit out their clothes, contaminated ones seem to be the problematic ones most of the time.

#### Code Revision
- release - 
d2194a759af92a64e9392232841f351bf15d409f 
 
#### Anything else you may wish to add:
- https://gyazo.com/d688b819e6d297b1bb071b9de6098fa1
- and then a few moments later https://gyazo.com/db06f2234fc89503f8799ea031ac59d1
- maybe a few seconds after the last cap, they returned to their old spots https://gyazo.com/479212a1cb7beade9d05997ef95e47d1

**Comment by HzDonut** [comment]
Update: Had a bomber jacket of some prey appear over my backpack then vanish, now i can't even click my backpack. Nice.

**Comment by HzDonut** [comment]
Update two: The clothes switched places rapidly and I crashed a while after that last screencap.

**Comment by Virgo113** [comment]
Suggestion for a fix: Dropping all ejected items sequentially (that is, picking them up then dropping from hand one by one) fixes this. Have the vore eject action proc whatever it is that dropping an item does too.

**Comment by Arokha** [comment]
Fixed
