### ISSUE TITLE
Suggestion: "fluff" var on fluff items

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2610]
#### Brief description of the suggestion
Add a "fluff" var to items that is 0 by default, and set to 1 on fluff items, so the cryo computers can check for said items and delete them when the owner leaves regardless of whether they'd otherwise be retained (such as being guns or whatever)

#### What happens now
People cryo/teleport/tram, and things are added into the cryo computer for retrieval depending on the item type, even if they're items we don't want people to be able to retrieve.

#### What you want to happen
Same as now, but qdel the item if fluff = 1 so people can't go around swiping the various custom items that people currently have to ahelp on leaving to ask for them to be deleted.

**Comment by SpadesNeil** [comment]
Maybe send this to Polaris. Items spawned by the fluff item spawner could have "fluff" var applied to them.

**Comment by Arokha** [comment]
Or you could just set item_preserved = FALSE instead of adding a new var 4noraisn.

**Comment by SpadesNeil** [comment]
oh so basically we already have that

**Comment by SpadesNeil** [comment]
Reopening this but applying Aronai's solution later.

**Comment by Screemonster** [comment]
It's preserve_item, not item_preserved.

**Comment by SpadesNeil** [comment]
@Arokha I can't find where in the cryo code that items are dumped into the frozen_items list, but I discovered something else. We can simply tick the "allow_items" var to false for the tram, as people would probably just take all their gear back to CentCom.
