### ISSUE TITLE
Bar lacks secluded exits for sneaky/unwilling scenes

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2613]
#### Brief description of the issue
All the exits to the bar area, apart from _one_ maintenance door at the far north of the room which leads to the phoron shelter, open up onto very visible and exposed hallways, all on the west side of the room. The northern exit is directly onto the atrium, the southern door is _slightly_ better once you get out of it but if someone's working botany (or playing at the card table) you're hosed with regards to getting a clear run to it.

#### What you expected to happen
To be able to see someone with "unwilling prey, don't ask, just grab me and drag me off" in the bar where people hang around to advertise that they're available for scenes, and actually fulfil said request.

#### What actually happened
I'll see 'em, but there won't be anywhere to actually run to once I grab 'em.

#### Steps to reproduce
- n/a

#### Code Revision
- Server revision: fixtheferalness - 2017-12-22
b06be78a8723491bf2c6e819dcfaf94a5d3e1acc
 
#### Anything else you may wish to add:
- This wasn't an issue on box thanks to having the pool to the north and the chapel maint tunnel to the east, it was relatively easy for someone to sit off-centre in the room and be in easy reach of a _relatively_ un-travelled area, either dragging them into maint or hauling ass through the pool and into the dorms or card den.

- quick scouting of the area in aghost suggests that it _could_ be helped by putting the bartender's backroom to the south of the bar, and repurposing the area to the east (where the backroom currently is) to a maintenance access tunnel and staircase. There's an existing maint tunnel pretty close on the level below. That'd at least allow grabbing someone who's sat at the table near the window or playing on the arcade machine when the bartender isn't looking. (At the very least put a bathroom there - this is a dining establishment and the nearest public bathroom is on the other side of the station)

- the station in general could benefit from public sitting areas dotted around the halls like on the northern star. Two chairs and a table next to a hallway. Preferably in well-trafficked areas next to less-well-trafficked maintenance doors.

**Comment by Arokha** [comment]
Can just take the stairs down to the dorms right there, now.
