### ISSUE TITLE
Resleeving console loses wings if changing ears(color)/tails(color)/(wing colors)

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#2619]
#### Brief description of the issue
Originally, I thought changing colour of wings removed them. After further testing, changing any of the following 5 options removes wings from the sprite:
Ears, Tails, Wing color, Ear color, tail color.

#### What you expected to happen
For wing to remain even when other things to change.

#### What actually happened
Wings disappeared, other things changed.

#### Steps to reproduce
- Pick a wing.
- Change any of the 5 listed items.
- Have no wing.

#### Code Revision
Server revision: release - 
720882f79f1ad4e5f689fe1b45a3e761e402e03f 
 
#### Anything else you may wish to add:
Used to be that you couldn't add wings at all. This is an improvement.

**Comment by SpadesNeil** [comment]
I think this got fixed. Verify?

**Comment by Arokha** [comment]
Still a bug unfortunately.
