### ISSUE TITLE
Resleeving console cannot give hair to custom species

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#2621]
#### Brief description of the issue
Custom species cannot change hair from bald on console.

#### What you expected to happen
To be able to make hairy sleeves.

#### What actually happened
Greytide sleeves happened.

#### Steps to reproduce
Try to make a sleeve with nice long hair and custom species.
Fail.
Cry.
Use a mirror to fix it after resleeving.

#### Code Revision
Server revision: release - 
720882f79f1ad4e5f689fe1b45a3e761e402e03f 
 
#### Anything else you may wish to add:
The issue reminds me how you couldn't change wings in last revision. You get options, but nothing changes.

**Comment by Arokha** [comment]
Custom species is only a way for you to play with a mix of traits and stuff, which you can't do on the console anyway, using any sprite set. The fact that you can even pick "Custom Species" on the console is a bug. You should pick whichever iconset you want to use the shape of instead by picking that species.

We can update the body designer console later to actually allow you to design traits and junk, but the fact that you can pick custom species at all is the problem

**Comment by SpadesNeil** [comment]
Did this get fixed?

**Comment by Arokha** [comment]
notabug
