### ISSUE TITLE
Add "no mob vore" preference

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2626]
#### Brief description of the issue
At the moment, there is a var on mobs that determines whether they will eat indigestible people or not, to prevent indigestible people from letting themselves get eaten by hostile mobs. Endomobs have to have this turned _off_ to allow them to endo-eat people. There is no such preference for people who don't want to be eaten by mobs _at all_, even harmless things, and it's probably worth adding one since it's been brought up more than once.

#### What currently happens
People who don't wanna be ate by mobs get ate by mobs.

#### What you want to happen
People to have a toggle that causes the "do I want to eat this person" check in bumpnoms and hostilenoms to fail, preventing the mob from attempting to eat the person (and in the case of hostile mobs, causing them to just murder the person instead just as a hostile/picky mob does to an indigestible person right now)

**Comment by SpadesNeil** [comment]
Suggestion tag removed on account of we should have this.
