### ISSUE TITLE
Exosuit fabricator problem

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#263]
#### Brief description of the issue

(this was done once and not anymore on other rounds because i didnt bothered. Needs testing)
Exosuit fabricators cannot have their parts changed with the RED (Rapid exchange device) when the panel is open. If i try to insert the modules manualy (by rebuilding the machine) it makes a new machine frame ontop and leaving the previous stateintact at the bottom.

#### What you expected to happen 

I expected to change the modules inside the machinery

#### What actually happened

Refused exchange and made a new machine frame if tried to dismantle 

#### Steps to reproduce

Have RED, Exosuit fabricator open panel and try exchanging it the parts (Of course RED must Have some sort of modules inside to actually exchange items. And of course crowbar the machine as the last step)

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Please be more specific with the title.
Furthermore, we just updated tonight. Please check if this is still a bug.

**Comment by Arokha** [comment]
The RPD is notoriously broken with regards to exosuit fabs. It was broken 2 years ago. It's still broken. I have no idea why.

**Comment by SpadesNeil** [comment]
Marking wontfix, then.
