### ISSUE TITLE
Mobs instantly re-aggro on players after escape (Resist and OOC)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2630]
#### Not so brief description of the issue
It seems that any aggressive mobs will just go right back after the person who escapes from them. While I understand that it's probably to prevent OOC escape cheesing...it's still a problem since it prevents anyone from actually escaping the danger zone, even if they do it legit via resist.

For example: Let's say I'm playing as a xenobiologist. I've been working on-station all shift, and there's been one other xenobiologist around during some things. Two hours into the shift I decide that I'm going to help out in the lab more, so I head on down and open xenobio to mauled and eaten by a panther! Well shit, now I'm being gurgled with no weapon and I'm damaged enough that there's a very low chance security will get to me in time to free me before I die. Well, no way am I dying just because Dumbass McScienceman decided to not report that he was going to open a dangerous predator crate, so I hit OOC escape with the intention of just leaving the danger area and making up a story about how I barely escaped. I get out...and it just beats me up and eats me again right afterward. Well shit.

Alternatively, let's say it just pounced and ate me so my health was fine. I call for help and I start using resist to get out. By some miracle, I actually do manage to get out! I don't even manage to move before I've been pounced and eaten again. Well shit.

I think that players escaping from a mob add a variable/proc/whatever (I'm not too well versed in the terminology) that marks that player as 'do not attack for [x] amount of time' so they can actually run or get pulled away from the danger. This would make it so the mob would keep kicking some ass while the player who escaped can finish escaping. Most likely the timer would be short enough so that if the player DOES want to keep fighting the thing, they can just wait around for a few moments and let it become hostile again.

#### What you expected to happen
I'd escape and be given a small grace period to actually escape from the thing trying to kill me.

#### What actually happened
I'd just get attacked and eaten again as soon as I escaped, pretty much rendering any escape attempts useless.

#### Steps to reproduce
- Get eaten by a hostile mob
- Escape either by using resist to do it 'legit' or by using OOC escape
- Watch as your efforts get proved to be in vain as you just get eaten again.

#### Code Revision
- release - 
efed34b8f7f765e9bfd8cd6708e3d6f80a28764a

**Comment by Screemonster** [comment]
Retaliate mobs should probably purge their enemy list from time to time if that's what's doing it, if they don't already.

Alternatively mobs _do_ have a "do not eat this person" list in their vars which is checked on this line in the will_eat() proc:
https://github.com/VOREStation/VOREStation/blob/c5b5f8ed39fe06d2c2fba34d08cbf4a009d28dfd/code/modules/mob/living/simple_animal/simple_animal_vr.dm#L78

So having something in the struggle result that adds you to that mob's prey_excludes list for a short time would work (still gonna get murdered though if it's a conventional hostilemob, you're not getting off that easily)

**Comment by Screemonster** [comment]
Also if you don't wanna get ate by mobs at all, #2626 is on the to-do list.

**Comment by Arokha** [comment]
When you press that button, it prints this message on the screen:
***Don't use this as a trick to get out of hostile animals. This is for escaping from preference-breaking***
You are literally breaking the rules and ignoring this by using the OOC escape button in this manner. Stop doing it.

Also you are immune to being re-eaten by the same mob for 30 minutes (and all other simple animals within 10 turfs), unless someone programmed a mob very poorly to ignore this.

**Comment by Arokha** [comment]
Tested this with a panther specifically. OOC escaping panther prevents it from re-eating you as expected. Just mauls you to death whether standing or sitting.

As mentioned OOC escape is for escaping from prefbreaking, not "getting away from mobs", stop using it in this manner. It DOES message admins every time you use it, so now that we know you're using it like that, we can watch for it.

Working as intended.

**Comment by HzDonut** [comment]
What are you on about?

First, this was all hypothetical, I've never once used it like this in-game and never would because of what you just said, and I don't really appreciate you throwing out accusations like that.

Two, this problem was for both OOC escaping _and_ escaping via using resist as intended. Why did you just latch on to OOC escape and have a fit about it? Also being eaten at all _is_ a prefbreak for me, so glad to know that the suggestion Scree linked is being made.

**Comment by HzDonut** [comment]
I don't use it like that, and nowhere on here does it say I do. It was a hypothetical situation, and it's been pointed out that I made some mistakes, most notably that 'no way am I dying' should be changed to 'no way am I digesting' as this was supposed to be about prefbreaking, not escaping from combat, which the issue Scree linked is hopefully going to fix anyways. I can see where my mention of combat could mislead you, but still nowhere was it said this is something I do. Your accusations aren't appreciated at all.

Not only that but my version of the server is **definitely broken** anyways, so the bug with mobs eating people over and over is unique to it, this issue was discovered to not be in the master.

**Comment by SpadesNeil** [comment]
The bug sounds like it was "I use OOC escape and get eaten again anyway" regardless of how improperly it was being used.

According to Arokha's test, this could not be reproduced. Corrected the tags.
