### ISSUE TITLE
[*] scanner NIFSoft doesn't work properly

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2632]
#### Brief description of the issue
When using a Meson or Material Scanner NIF soft, the items aren't revealed in fullbright as they would be with the goggle versions. This makes the material scanner NIF useless for mining, among other things.

#### What you expected to happen
The NIF Soft and Goggle versions should function identically

#### What actually happened
The goggles are superior in every way to the NIF

#### Steps to reproduce
- Have NIF, install material scanner/mining nifsoft disk.
- Compare to material scanner goggles.

#### Code Revision
e60fa65165516de6fde793c632f111bf7a9a1836 
 
#### Anything else you may wish to add:
Both of these were taken from the same position:
[Material Scanner Goggles. Note brightness of ore in walls](https://i.imgur.com/H1Fqs2t.png)
[Material Scanner NIFSoft. The faint outline of gold ore can be seen under mouse cursor](https://i.imgur.com/brSvHIO.png)

**Comment by Arokha** [comment]
Means the NIFSoft is not doing one thing glasses are doing, probably requires an additional check for those being active wherever checks for glasses being worn.

**Comment by Arokha** [comment]
Goggles didn't work either.

Fixed in master now.
