### ISSUE TITLE
Feature Suggestion: Quiet Micro Vore

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#2643]
#### Brief description of the issue
Eating a micro that is in your hand broadcasts to everyone in the vicinity.

#### What you expected to happen
Or more accurately, what I think should happen, is that when they are micros that are in your hand, they broadcast at a much lower range, possibly even at whisper range.

#### What actually happened
Security noticed my pure-subtle-emote scene in the bar and confronted me about the consent (or lack thereof) of my micro prey, because the actual nomphing was telegraphed to everyone.

#### Code Revision
- 5cb77ed9dcb08a0d6652c267d1344cf1f3cd4dfa
 
#### Anything else you may wish to add:
- I am aware that it may be seen as an IC issue rather than a mechanics one, but the only reason the whole confrontation happened at all was because the mechanics broadcasted what I was doing as if I stepped on a branch while on a forest hunt.
- Before admins mention "talk to us about it when this happens", I did not specifically complain about the instance that spurred this because it was resolved before it got that far.
- I want to emphasize I mean eating them _from your hand._ If they're small enough to fit in your hand and slip into your pocket, they're small enough to stealthily devour.

**Comment by Arokha** [comment]
My two cents is that if you make it so you can eat held people stealthily, it means you can eat 20m tall people if you're 40m tall stealthily, which does not make a whole lot of sense when you think about it.

So my concern is this:
a) We do it the 'fair' way and make it so that 40m tall people can eat 20m tall people w/o anyone noticing which makes zero sense and muh immershuns.
b) We do it the 'unfair' way and make it so that only micros below a certain size can be eaten stealthily, and get blamed for favoring a certain kink.

**Comment by Vorrarkul** [comment]
I can see where you're coming from with that, but the sizes aren't exactly law in game. 200% scale is often used to represent 20-30 foot tall people, while 25% can represent micros whose height is a matter of inches.
So unless I'm mistaking how the scale system works, a 200% scale giant would be able to stealthily consume a 100% scale person. And with the suspension of disbelief I mentioned above about the scales, that can easily represent a huge giant slipping someone into their mouth.

**Comment by Arokha** [comment]
I see it as more of an eye-chart-problem sort of thing. If you printed an eye chart on a wall and hung it up, I'd be able to read certain rows of letters until a point when I can't make out what they are, based on how far I am and stuff. If you make the eye chart (and letters, obvs) 200% bigger, I can now see those that I couldn't see before, maybe all of them.

So like for a normal sized person looking at a normal sized person with a micro. From a certain distance, sure, I can't see what they're doing or maybe even tell that it's a micro. But if you make both 200% bigger, I can see them more clearly, it makes it harder to sleight-of-hand things.

**Comment by Screemonster** [comment]
Or we can tell people to fuck off if they see a single emote and immediately pop batons and yell "YOU THERE, WAS THAT CONSENTUAL?" even when there's not a single call for help.

Pretty sure that's policy already.

**Comment by SpadesNeil** [comment]
Scree has a point but this idea would still mitigate problems and also make a unique mechanic.

**Comment by Vorrarkul** [comment]
I am aware that it's already policy to do that, this is just to mitigate problems as Ace put it. Some sec players seem to have trouble not 'acting accordingly' when presented with a scenario like this.

As for the eye exam thing, I think that is hampered by the fact that no other mechanics pay it heed already. Giants can whisper and subtle all they want, while micros can broadcast their voice to an entire room.

**Comment by lbnesquik** [comment]
Shouldn't be too hard to do 

if(prey.size_multiplier < 0.49)//micro
     then silenteat
