### ISSUE TITLE
[Date] no longer works when writing paperwork

### ISSUE THREAD

**Issue by Rickymadenson** [VOREStation/VOREStation#2654]
#### Brief description of the issue
Using the [date] doesn't automatically generate the current date anymore.

#### What you expected to happen
The command insterting the current date of today automatically

#### What actually happened
Nothing happened.

#### Steps to reproduce
- 1. Find a piece of paper
- Make sure to use a pencil on it, unless your fingers are dipped in ink or something
- write [date], if nothing pops up, it's broke

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Discovered on the 30th of December.
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Mewchild** [comment]
The code revision for this, to assist, is 588eb1648152eef0ea98de7318e6bc492918c50c
