### ISSUE TITLE
Cyborgs should not speak vocally when radio isn't available.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#2656]
#### Brief description of the issue
Exactly as the title says.

#### What you expected to happen
I expected them to say nothing at all or give a notice that the communications network is down like with PDAs.

#### What actually happened
I blurted out confidential information meant for a secure channel. 

#### Steps to reproduce
- Be a cyborg with a specific radio channel.
- Say words on that specific channel.
- Realize you just informed the nuke ops you're negotiating with that there's another team flanking them.

#### Code Revision
- 588eb1648152eef0ea98de7318e6bc492918c50c

**Comment by SpadesNeil** [comment]
This is not a bug.

**Comment by SpadesNeil** [comment]
I was under the impression that when a human tries to talk on the radio and it doesn't work, the same thing happens.

**Comment by Arokha** [comment]
Incorrect, this isn't a bug. Humans do still speak aloud when talking into headsets. Stand next to one of them when talking on the radio. The say proc is identical for the two (it's mob/living/say).

Talking into headsets tells everyone within a smaller range than normal what you said, but it still does say it to everyone nearby, just not the full normal world.view (radius 7) range.
