### ISSUE TITLE
Suggestion: Nif startup noise

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2657]
#### Brief description of the issue
Very simple. When nifs boot up, after a surgery on when you arrive, it should play this:
[Good noise.](https://www.youtube.com/watch?v=miZHa7ZC6Z0)

#### Code Revision
- Current.

**Comment by Arokha** [comment]
![telegram_actually](https://user-images.githubusercontent.com/15028025/35026655-560c5b48-fb1a-11e7-9b43-81ff402c65af.png)
![telegram_nvm](https://user-images.githubusercontent.com/15028025/35026662-5ce1d8da-fb1a-11e7-8024-8a3d5df1fe03.png)
