### ISSUE TITLE
Custom sleeve gibbed, caused mass crash and created a crash loop for some ghosts

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2660]
#### Brief description of the issue
Apparently, someone threw a custom sleeve onto the tram tracks which caused it to gib, when it did around seven people crashed. When I joined as an observer I not only crashed in the bar but kept crashing every few seconds until the round finally ended while I was on the tram. While gibs of people are known to cause problems, such a severe crash to the point where i kept crashing no matter where i was or if i had observed the body is new. At least two others who got on to observe mentioned being in a loop as well, or being unable to rejoin after the crash.

#### What you expected to happen
The body would gib normally, whatever.

#### What actually happened
Crash nuke, pretty much locked me out of observing the round with the endless loop.

#### Steps to reproduce
- Print custom sleeve
- Gib that sucker
- Watch everybody drop from a crash

#### Code Revision
- release - 
588eb1648152eef0ea98de7318e6bc492918c50c 
 
#### Anything else you may wish to add:
- I'll update this as more information comes out, if more information comes out. Just needed to make it known in the issues tracker.

**Comment by Screemonster** [comment]
... Custom sleeve is new info. Might need testing if it's custom species that are causing this bug. Would explain why it isn't happening upstream if that's the case.

**Comment by Arokha** [comment]
Unsure if this is still a problem, given that the 'limb crashing' thing is gone.

**Comment by Arokha** [comment]
http://www.byond.com/forum/?post=2348506

Contribute here (keeping in mind that they don't know anything about SS13 or limbs or anything, aka keep your comments abstract) if anything is discovered on this, since it's not our bug.
