### ISSUE TITLE
[SUGGESTION] Remove that annoying missing floor and railings from the science stairwell

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2663]
#### Brief description of the issue
The way the science stairway is currently laid out, there's a missing floor + railings right at the bottom of the stairs from the third floor to the second floor. It's both unappealing to look at, and it slows down traffic which is quite the issue if, say, a slime containment breach happens where every second matters.

#### Code Revision
- release - 
588eb1648152eef0ea98de7318e6bc492918c50c 
 
#### Anything else you may wish to add:
- Before stairway fix: https://gyazo.com/6872c6624d6d4514066ec58fe815fb7e
- After stairway fix: https://gyazo.com/6df1a8873c476802d5d4771693b2deaf

**Comment by Arokha** [comment]
Done
