### ISSUE TITLE
[Bug? Oversight?] Circuit Imprinter doesn't allow you to cancel things being printed

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2673]
#### Brief description of the issue
Well normally I'd make sure it's an actual problem before making of these, but fuck discussion am I right? Anyways, it's like the title says: the circuit imprinter doesn't let you things being actively printed, this means that once you click, you're committed. With no way to recycle circuits, you've basically just wasted glass and sulphuric acid, congrats.

#### What you expected to happen
I misclick, woops. I hit cancel and click what I meant to click.

#### What actually happened
I misclick and have to deal with wasted resources, hooray.

#### Steps to reproduce
- Just print something from the circuit imprinter and try to cancel it.

#### Code Revision
-  release - 
9056e4a5ec55bbc8fb26a9abd5ab742ab83d8948

**Comment by AaronSherwood117** [comment]
The protolathe and circuit imprinter haven't let you cancel the current printing job EVER. It's probably not an oversight. It also uses like, a tenth of a sheet of glass for a circuit so nothing is really wasted.

**Comment by SpadesNeil** [comment]
Really an incredibly minor thing.
