### ISSUE TITLE
Suggestion: Rnd borgs should be split into more than one module

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#2677]
#### Brief description of the issue
currently rnd borgs are pretty op and could easily replace the whole department with just one borg

#### What you expected to happen
for it to be slightly balanced

#### What actually happened
it wasnt
 
#### Anything else you may wish to add:
splitting it into rnd and robotics would be the most logical ones to make it into

**Comment by Arokha** [comment]
I'd like to get at least one dogborg for every department, before starting to give certain departments several.

**Comment by SpadesNeil** [comment]
Agreed but I also agree we should nerf the science doggo borggo moreo.

**Comment by kcin2001** [comment]
@ace the rnd dog was already nerfed into oblivion of the extra things its the standard one im talking about

**Comment by SpadesNeil** [comment]
**MORE NERFS!** :B

**Comment by kcin2001** [comment]
It doesnt even have a sheet loader

**Comment by SpadesNeil** [comment]
![more nerfs](https://user-images.githubusercontent.com/6484985/34695207-f64ff7ba-f497-11e7-9424-7f57a45fab9f.gif)

**Comment by kcin2001** [comment]
@arokha i dont know why you thought i meant the dogs

**Comment by SpadesNeil** [comment]
Seriously though you need to be specific or we're basically going to do nothing. Also you have no revision number in your post.

**Comment by Arokha** [comment]
@kcin2001 Because this was posted right after you made a science dogborg. Context, yo.

**Comment by kcin2001** [comment]
Well i did it after that since how i had to nerf the dog made me think about the normal ones
