### ISSUE TITLE
Darksight Balance

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2678]
#### Brief description of the issue
As it stands, Darksight and the major variant of such are some of the least useful traits that one can take, at the moment. They claim to give sight in an expanded area around them, but require mesons to actually be effective/useful.

#### What you expected to happen
With Major Darksight, I expect the darkness overlay to be removed as advertised.

#### What actually happened
The overlay is technically removed, but everything is still in shadow, unable to be seen without some form of fullbright.

#### Code Revision
a5a83f7ed84f914ac381c671e78ae764e6d09e2e 
 
#### Anything else you may wish to add:
When https://github.com/VOREStation/VOREStation/issues/2632 is fixed, I feel the correction could be ported over to this as well

**Comment by Arokha** [comment]
This is not fixable with the current lighting system and would require the invention of a new lighting system.
