### ISSUE TITLE
Digested IDs have no icon.

### ISSUE THREAD

**Issue by renthur** [VOREStation/VOREStation#268]
#### Brief description of the issue
Digested IDs have no icon.

#### What you expected to happen
Damaged ID icon that can be clicked and moved and used as evidence and such. 

#### What actually happened
Id is invisible.

#### Steps to reproduce
Eat someone, digest them.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
@Arokha having no ID icon means it cannot be clicked on while in your inventory. That's at least a moderate blocker..
