### ISSUE TITLE
Colony Director's ID held by oversight console

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2682]
#### Brief description of the issue
When a user playing colony director exits the round via storage, their ID will be kept in the tram/teleport/cryogenic oversight console instead of being deleted properly.

#### What you expected to happen
The ID is deleted, the same as any other ID.

#### What actually happened
The ID is retained and able to be collected by other players

#### Steps to reproduce
- Join as Colony Director
- Make sure your ID is NOT in a PDA.
- Leave the round via tram, cryo, teleport.

#### Code Revision
a5a83f7ed84f914ac381c671e78ae764e6d09e2e 
 
#### Anything else you may wish to add:

**Comment by LittleBigKid2000** [comment]
This is caused by `/obj/item/weapon/card/id/gold` having `preserve_item = 1`. Unless that's intended on Polaris for some reason, this is a Polaris issue.

**Comment by SpadesNeil** [comment]
Seems like a bug if you ask me.
