### ISSUE TITLE
Rainbow slime cores can provide infinite slimes.

### ISSUE THREAD

**Issue by Squi-RL** [VOREStation/VOREStation#2692]
#### Brief description of the issue
Rainbow slimes can, at the moment, produce infinite random slimes with one core

#### What you expected to happen
I expected the core to be used up upon being injected with phoron

#### What actually happened
It wasn't. though this bug doesn't work for the water reaction

#### Steps to reproduce
- (Step 1) get a rainbow core from any source
- (Step 2) inject with phoron
- (and so on) keep injecting with phoron for as long as you want

#### Code Revision
- 53d4231e17c717793eb64b86b83e68bc5c478262 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cameron653** [comment]
This occurs because the rainbow slime core random slime reaction doesn't have ..() at the end of it.

**Comment by SpadesNeil** [comment]
Seems like a Polaris bug. A nasty one at that.

**Comment by Arokha** [comment]
It appears to have the parent call now.
