### ISSUE TITLE
Robo nom shadow of items below bug

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#2698]
#### Brief description of the issue
Borgs can robo nom thing a floor below them on catwalks.

#### What you expected to happen
just to nom the mouse on the same floor as me above the trash pit.

#### What actually happened
get a massive list of dead slimes a level below in the trash pit 

#### Steps to reproduce
- stand on catwalk
- use robo nom while something is below you
- eat the mob below

#### Code Revision
- 53d4231e17c717793eb64b86b83e68bc5c478262 
 
#### Anything else you may wish to add:
- only tested above the trash pit one level above but might work any number of levels above if on a catwalk, also am not sure if it eats the real one or duplicates the mob.

**Comment by Cyantime** [comment]
This is probably eating the multiZ shadow mobs that handle seeing mobs below you, rather than the actual mob itself

**Comment by Arokha** [comment]
Cyantime is correct, it was fun to watch though.

**Comment by Techtypes** [comment]
seems to line up with what i am seeing, could not digest the dead slimes so ejected them and nothing came out, could digest the mouse that was alive though

**Comment by Arokha** [comment]
Basically you cannot see mobs on lower z-levels. That's just not a feature in byond, so to simulate the experince, there's a huge stack of fake mobs that walk around on the above z-levels in open space that look like the mob below. You were eating those.

**Comment by Techtypes** [comment]
can see it as a simple way to solve a complex issue, funny to think was eating the shadows of them mobs basically.

**Comment by Arokha** [comment]
This is odd. They're coded to only eat 'human' mobs. They shouldn't be able to eat those shadows.

**Comment by Verkister** [comment]
This happens on the "robo nom" verb, not the sleeper noms. Probably happens with other mobs' non-grab nomverbs as well.

**Comment by SpadesNeil** [comment]
Can you update the title of this bug to explain more clearly?

**Comment by Arokha** [comment]
Fixed in master.
