### ISSUE TITLE
The only engineering request console is in atmos break room

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#2700]
#### Brief description of the issue
The engineering request console is in the atmos break room. It would make more sense in main engineering, maybe in the monitoring room by the lobby since that's nice and visible.

#### What you expected to happen
Engineers in engineering to have a visible console (aside from the CE office one which has its own dedicated channel)

#### What actually happened
Engineering has to go to atmos to see alerts

#### Steps to reproduce
1. Be engineer
2. Miss requests
3. Get yelled at

#### Code Revision
release - 53d4231e17c717793eb64b86b83e68bc5c478262 
 
#### Anything else you may wish to add:
The existing atmos one might make sense in the atmos break room (or atmos monitoring room) rather than in atmos itself, but at least that one is somewhere reasonable.

**Comment by Very-Soft** [comment]
I should also note, the cargo request console is in the mailroom and inside the QM office, where no one really tends to hang out. it'd be better to have one in the actual cargo office. 

That said, it might be a good idea to look at where all the request consoles are, and make sure they're in places where people are likely to notice them.
