### ISSUE TITLE
Pop up windows don't work.

### ISSUE THREAD

**Issue by blazerules** [VOREStation/VOREStation#2702]
#### Brief description of the issue
Whenever I try to open a PDA, or any other kind of window, it always shows me a broken pop up window. I tried re-installing byond, clearing cache, trying beta version of byond and what not. Nothing seems to fix the issue.

The only thing I found to temporarily fix it is relogging 30-65 times (yeah I count since I got curious) to finally get the PDA menu working and then never, EVER close it because if you do it breaks. It's basically a dice roll to get it working.

Didn't have this issue when playing maybe... 2 months ago? Nothing really changed on my end since then. Maybe got a later byond version but that's it.

#### What you expected to happen
Pop up windows to work

#### What actually happened
I press on the PDA and nothing happens. Sometimes nothing will happen for 2-10 tries and when it does pop up I get a PDA window with no options. That gets progressively worse as I open and close it.

#### Steps to reproduce
No idea? Open any interface that has a pop up window

#### Code Revision
53d4231e17c717793eb64b86b83e68bc5c478262 
 
#### Anything else you may wish to add:
First view: http://prntscr.com/hx46yy
When I close and open it: http://prntscr.com/hx472i
Third view: http://prntscr.com/hx4766
After it reaches the third stage it stays that way.

**Comment by Jakksergal** [comment]
When in game, ask an admin to resolve this issue. There used to be a publicly available verb to fix it but it was later changed to be an admin command. If they don't know where it is, tell them to check the drop down menu in View Variables.

**Comment by Arokha** [comment]
You can also clear your byond cache to fix it (you have to delete the files by hand, clearing the cache never really seems to remove all the files, you can just delete the whole cache folder)

**Comment by Arokha** [comment]
This was NanoUI as you only had this problem on NanoUI interfaces when we discussed in the discord chat. It's just weirdness with byond caching, and not something we can fix as far as I'm aware.
