### ISSUE TITLE
If cargo charges for things, add the funds to supply points, rather than the civillian account

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2708]
So cargo has the ability to charge people for things, and sure, they could just order a new scanner, and use that to charge people directly to their own bank accounts... but that doesn't actually really help cargo, and in the event of points shortage, it doesn't help cargo in getting people what they asked for.

So, I was wondering if it would be possible for cargo to get a scanner that can exchange money for cargo points. I'm unsure what the exchange rate should actually be, as the cargo point amounts seem largely arbitrary.

I wouldn't mind over much if it was 1:1, but that dooooes make things quite cheap, and in some cases probably unbalanced, upon reviewing the list. So I think it'd probably be better to use a ratio of 5:1 or 10:1 for cash to points. 

At that point a 
pizza crate would cost 50 or 100
monkey crate would cost 100 or 200
Dangerous Predator crates would be 200 or 400
Automatic weapon crate would be 500 or 1000

This to me sounds like a reasonable ratio, people ought to still be able to afford these things if they really need them, and ideally, cargo could charge a little extra, to turn a profit off of those interactions.

This would allow people to use cargo to ACTUALLY buy things in a way that makes sense for all parties involved. People want things, cargo has things, cargo wants money to be able to buy more things, people have money.

Of course, if the people in cargo want to continue doing things like they already do, just handing things out, I don't think this ought to interfere with that. If mining gathers resources and cargo sells platinum, there's no reason why security couldn't come in and order ALL THE GUNS in an emergency and use cargo's points. But in general, cargo should be trying to get things people want, to try to make more money, I feel. 

This gives mechanical reason to have cargo roleplay its job, and rewards cargo and other people for interacting this way, since ideally everyone would get what they want out of the exchange, within reason. (Obviously, cargo shouldn't be selling weapons/dangerous crates to assistants, etc etc)

~~(Also as an aside, it'd be really nice if the supply control console showed how many points the previous shuttle to CC made for cargo)~~ This was added! :>

**Comment by SpadesNeil** [comment]
The problem is coding it. Also I'm not sure I really want cargo to be able to dump money on things to buy them early in the round.

**Comment by Very-Soft** [comment]
Forgive me if I've overlooked something but I'm sort of struggling to think of what would be especially bothersome to just be able to pay for to have at round start apart from of course lethal weapons.  

For most things I don't really see why it would be especially bothersome for someone to come in and spend all their money to get things at the start of the round, as opposed to waiting for mining to gather and ship materials.

My point in wanting this is to reward both sides of that exchange, really. For people doing jobs or rp or whatever to come in and get whatever they need, and to have that interaction actually be beneficial to both sides.

As is, if someone comes and orders a thing, the person gets the thing, and cargo actually doesn't really get anything out of those exchanges apart from a little activity in the department. They CAN charge for things, but that money doesn't actually help cargo at all, and it doesn't help other people get the things that they want/need to follow.

I don't really feel like this is any more likely to be abused than the way cargo points presently are. Cargo can already have a pretty decent sum of points in around an hour. More than enough often times to buy the most expensive things multiple times over if they've got a decent miner working. That's not really abused too much as is, so I struggle to think that it might be abused much more with people able to just purchase goods.

From an RP standpoint, and in my opinion, from a mechanics standpoint, it makes sense to allow people to pay for the things they want/need, and have the money they use actually be beneficial to cargo getting those things. 

And while I can see why one might be worried about sec, or assistants coming in trying to buy alllll the weapons crates, that can honestly already happen. But it's just not something I really see people try all that often. People rarely order anything at all. And in the last week or more of playing cargo, I think sec has come in to order things twice, and they were alternate colored uniforms once, and some armor another time. 

Of course, again, I accept that I may not have thought of everything here. And for sure, someone would need to code it. I won't pretend to know how complicated it would actually be to achieve.

I'm just kind of looking at what might make the jobs I know more fun to play, so that maybe they can be more active. In general, my aim is to see more people in departments. And I think to do that, we need to make the jobs be more appealing than assistant. Cargo's the first one I'm really peeking at.
