### ISSUE TITLE
Eye Necrotic Surgery - Not Working

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2741]
#### Brief description of the issue
You cannot remove necrotic tissue off the surface of the eyes

#### What you expected to happen
For the procedure that is described on the wiki page to work.

#### What actually happened
It doesn't work and an entirely new body has to be printed to avoid stuffing it up.

#### Steps to reproduce
- 1. Get your eyes screwed up by phoron
- 2. Wait a while for your eyes to become necrotic
- 3. Get someone to attempt necrotic organ removal on them.
- 4. Find out it doesn't work.

#### Code Revision
- 47001e607a3531cbe1018e11ee2ae974f4f00879 
 
#### Anything else you may wish to add:
- N/A.

**Comment by Arokha** [comment]
Is not a real thing. Internal organs require replacement either with the same organ from a sleeve of the same species or from robotics. Only the 11 external organs can be repaired with the necrotic organ repair steps.
