### ISSUE TITLE
Borgs can robonom ghosts

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2746]
#### Brief description of the issue
Borgs can eat ghosts

#### What you expected to happen
Borgs to not eat ghosts

#### What actually happened
I got ate, and was a ghost

#### Steps to reproduce
- (Step 1) Be a ghost/borg
- (Step 2)Have the ghost and borg be within robonom distance
- (Step 3)Robonom
- (Step 4)???
- (Step 5)Ghost as borg food

#### Code Revision
- Server revision: release - 
be023eb50b1de59298518011d0086f078298133c 
 
#### Anything else you may wish to add:
- After the ghost is eaten, the borg can see them in their vore panel as if they had eaten a person normally. Can't absorb or digest. VERY INTERESTING!

**Comment by SpadesNeil** [comment]
This is _not_ a feature or suggestion. This is a bug.

**Comment by Arokha** [comment]
@SpadesNeil I was being sarcastic, dork.

It's fixed in master.

**Comment by SpadesNeil** [comment]
:U
