### ISSUE TITLE
Can target ghosts with certain verbs

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2757]
#### Steps to reproduce
- (Step 1)Try to lick/give someone a thing, while a ghost is also in range
- (Step 2)Dialogue pops up to show unseen targets
- (Step 3)Try to target these ghosts to see what a ghost tastes like
- (Step 4)Nothing happens

#### Code Revision
- release - 
1c41215a8241619a11dfc5d9c36ebc75a3936042

**Comment by OrbisAnima** [comment]
"I can Lick you and know you are there, stop spying on us!"

**Comment by Arokha** [comment]
Fixed in master.
