### ISSUE TITLE
OOC Notes don't like apostrophes or quotations

### ISSUE THREAD

**Issue by Vae42** [VOREStation/VOREStation#276]
#### Brief description of the issue
I put words like Don't, or phrases that include quoatation marks
#### What you expected to happen
the words to be displayed as typed
#### What actually happened
don't replaces the apostrophe with the following characters & # 3 9 ; together. and quotation marks are similar with the number 38 instead. 
#### Steps to reproduce
put apostrophes and quotation marks into OOC notes and save, then check them again, or examine someone.
#### Additional info:
 - 882cf5740685135dc6aea13793cc9404f96338ff 
 -  I would REALLY like it if we could put line breaks into the OOC notes, its so much easier to parse my thoughts that way. (I know its a separate issue, but felt like its so small It isn't worth opening a thing on.)

**Comment by Arokha** [comment]
Saw this last night actually when I was playing.

**Comment by Arokha** [comment]
I fixed this upstream, it will be fixed next update from Polaris. (Soon :tm: )
