### ISSUE TITLE
Falling onto stairs negates fall damage, apparently.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2763]
#### Brief description of the issue
So I just learned that apparently if you fall down z-levels onto some stairs, you'll be perfectly fine!

#### What you expected to happen
It would hurt because I just _fell_.

#### What actually happened
I'd be 100% okay.

#### Steps to reproduce
- Head to the science stairwell since that's the easiest place to pull this off.
- Hop over a railing with some stairs below.
- Enjoy your shortcut.

#### Code Revision
- release - 
1c41215a8241619a11dfc5d9c36ebc75a3936042

**Comment by Very-Soft** [comment]
Stairs tend to be what mark the transition between z levels. It stands to reason that if you hopped the railing it probably wouldn't be that far a fall if it's just onto some stairs.

**Comment by ArgobargSoup** [comment]
@Very-Soft I think I've seen this before... they're jumping from the third floor onto the stairs that are between the first and second floors.  Falling essentially 2 z-levels.

**Comment by Arokha** [comment]
Cyantime is correct. Stairs do prevent falling damage because you 'fall' when moving between zlevels, and just land on stairs, so it stops anything bad from happening. He's also correct in that it should be changed if you fall from more than just 1 level to do something bad, though.
