### ISSUE TITLE
APC and SMES power draw priority

### ISSUE THREAD

**Issue by Knightfall5** [VOREStation/VOREStation#2764]
#### Brief description of the issue
SMES units draw power before APC units now, causing APC units to run out of power if there is no extra power in the grid.

#### What you expected to happen
APC units receive power first, then all spare power is sent to SMES units for storage.

#### What actually happened
All power goes to SMES units first for storage, then spare power to APCs for powering the station.

#### Steps to reproduce
Set substation SMES units, wonder why the tram and civilian areas nearby have no power.

#### Code Revision
1c41215a8241619a11dfc5d9c36ebc75a3936042
 
#### Anything else you may wish to add:
I know it wasn't like this before, as when I'd set substation SMES units to max charge and let them charge up before setting the output and turning off the breaker bypasses everything would be fine. Now if you do this the station will blackout due to all power being routed to the SMES units first.

**Comment by Screemonster** [comment]
Don't set the substations to draw more than is available then.

**Comment by Knightfall5** [comment]
It's unintended so I'm reporting it as a bug, which is what I've been told to do.

**Comment by SpadesNeil** [comment]
I don't know if this is a bug. Who said it was a bug?

**Comment by Dankman** [comment]
that's literally how they've always worked lol.

**Comment by Screemonster** [comment]
Like "brownouts happen if the powernet has more draw on it than supply" sounds like the opposite of unintended. The RCON console even tells you what the load is on each SMES so you can balance it all nicely.

**Comment by Arokha** [comment]
Managing the input values on the SMESes has always been a thing. Set them too high and not everything gets power. If it was the other way around, you couldn't charge a SMES if you wanted to, because APCs would be busy stealing all the power.

**Comment by Knightfall5** [comment]
Lol what, it never worked like this. I'd know since I'm one of the few people who actually used the substations. It also doesn't work like this on any other server. Why? Because if it did the solar room APCs would all run out of power, like it does here.

**Comment by Knightfall5** [comment]
I have a version of the code from three months ago from when I was working on some gateway stuff, and guess what? APCs get power first, then the SMES units, just like I described above. This is new.

**Comment by OrbisAnima** [comment]
I agree with Knight on this one, in the meaning that it worked with APC's drawing first and then SMES would charge. But leaving that aside.

Wherever or not this is intended, intentional or unintentional, the question should be...

Is this what should happen? Should an APC draw before or after the SMES, what is better for gameplay? What makes sense?

**Comment by Knightfall5** [comment]
https://github.com/Cameron653/VOREStation-1/commit/a97a57427801b3ac0b2f7d7bac3619e2e0f4d5ea

Here is what I think was changed that caused this, it moved how the powernet is processed into a new StonedMC subsystem. It fits in perfectly from when I started noticing the issue

**Comment by Screemonster** [comment]
Either way, I like actually having to adjust things rather than just maxing the inputs and calling it a day.

**Comment by Knightfall5** [comment]
Personally, I don't mind it all that much, the issue is that there are places that aren't hooked up to a substation, or even an SMES at all - looking at you, solar shack - so they tend to loose power and go dark. Alot. The tram and civilian areas nearby have been loosing power quite frequently, just yesterday I joined in to two separate rounds with no power down there.
