### ISSUE TITLE
Two completelly unrelated bugs that i found out

### ISSUE THREAD

**Issue by stobarico** [VOREStation/VOREStation#2765]
## Brief description of the issue:
- The electrochromic windows in the HoP office don't work as intended (When you press the button nothing happens)
- Ghosts can eject cyborgs from recharging stations
 
## Code Revision
- 1c41215a8241619a11dfc5d9c36ebc75a3936042

**Comment by SpadesNeil** [comment]
If it's two separate bugs please make two separate issues.
