### ISSUE TITLE
Ghosts pointing is visible to the living

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#2766]
#### Brief description of the issue
When a ghost points at someone, living people around can see it.

#### What you expected to happen
Not for them to see it.

#### What actually happened
They did see it.

#### Steps to reproduce
Be a ghost, point at a person.

#### Code Revision
1c41215a8241619a11dfc5d9c36ebc75a3936042
 
#### Anything else you may wish to add:

https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/mob.dm#L246
https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/dead/observer/observer.dm#L609

**Comment by Arokha** [comment]
It's like you want me to remove metagaming or something

**Comment by SpadesNeil** [comment]
![giphy](https://user-images.githubusercontent.com/6484985/35014101-81f63694-fadd-11e7-80c1-07f314a0ef5d.gif)
