### ISSUE TITLE
Belly flavortext being overwritten.

### ISSUE THREAD

**Issue by Vae42** [VOREStation/VOREStation#277]
#### Brief description of the issue
1. (More important issue) - All Vore panel information persists among all characters, **overwriting** any bellies and all flavor text on them. 

2. If you try to edit flavor text, it opens a blank text that saves regardless of hitting save or cancel.

#### What you expected to happen
1. Each character is supposed to have their own Vore panel custom bellies right? I expected to have them remain separate and persist independently of each other.

2. Either the text dialogue opens with the existing text present (like most other dialogues) and/or that when you hit cancel, it doesn't overwrite your existing text.

#### What actually happened
1. A new character can be made, and it will have all the vore panel stuff of the previous characters. edits made on it will overwrite bellis on other characters.

2. Accidentally clicked the flavor text button? Don't worry, I'll just erase everything for you.
both: Lose many many many lines of text.

#### Steps to reproduce
1. A) Make a character, B) set up bellies with beautifully thought out flavor text for a handful or internal organs, C) make a different character and do the same, D) Check on the first character. (This is not an issue for everyone it seems, but some definitely knew what I was talking about)

2. A) Write beautifully thought out flavor text for a handful or internal organs, B) consider editing the flavor text, C) Change your mind and hit cancel.

#### Additional info:

- the 'save preferences' button in the vore panel seems to be useless as it saves everything I do on all characters regardless of hitting the button or not. (maybe this is a separate issue too?)
 - Queried other players, some have had issue 1 since the vore update, **some haven't had the problem at all.**
 - I know this should be 2 separate issues, but I'm dumb apparently and since I started it as one issue, I just stuck with it after re-writing. 
 - Edit: This ENTIRE post was rewritten after I found time to do testing.

**Comment by SpadesNeil** [comment]
@Arokha mind checking this out?

**Comment by Vae42** [comment]
updated with better details

**Comment by SpadesNeil** [comment]
Either @Arokha or @Leshana may want to look at this because the internal panel is their doing.

**Comment by SpadesNeil** [comment]
This is still an issue.
