### ISSUE TITLE
Spy kit cameras are viewable through camera consoles

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2773]
#### Brief description of the issue
Spy cameras (bugs) are able to be viewed through security camera consoles

#### What you expected to happen
Only be able to view bug footage through the respective paired PDA.

#### What actually happened
All bugs are viewable through camera consoles

#### Steps to reproduce
1. Go to security camera console.
2. Select 'security' tab.
3. Click on numbered camera 'Camera #3603' in this case

#### Code Revision
1c41215a8241619a11dfc5d9c36ebc75a3936042 
 
#### Anything else you may wish to add:
![bugcameras](https://user-images.githubusercontent.com/33539568/35026870-a57b89a6-fba1-11e7-90c0-ed0c51472c29.JPG)

**Comment by Arokha** [comment]
Fixed
