### ISSUE TITLE
Account age locks/checks not functioning

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#278]
#### Brief description of the issue
Any account logging into the server is supposed to have an age check, limiting access to certain roles until you have played here for a span of time.

#### What you expected to happen
Logged in on a brand new account, expected to be denied access to Head of Personnel role. 

#### What actually happened
Was able to play as Head of Personnel.

#### Steps to reproduce
Using a new Byond account, try logging in as a "locked" role like HoP or Cap.

#### Additional info:
 - **Server Revision**: 2016-06-01 - 882cf5740685135dc6aea13793cc9404f96338ff 
 - **Anything else you may wish to add** This is a critical issue if it isn't working.

**Comment by SpadesNeil** [comment]
I suspect SQL isn't working.
