### ISSUE TITLE
Double click to follow the person who digested you makes you re-enter your nonexistent body

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2784]
#### What you expected to happen
Doubleclick predator while they run off to get me resleeved to follow them

#### What actually happened
Re-entered corpse. Health showed at 100, and all the normal hud things showed up. Couldn't do anything. Deaf, could hear radio though. Allows you to ghost and re-enter as much as you like.

#### Steps to reproduce
- (Step 1)Get gurg'd
- (Step 2)Double click predator
- (Step 3)Become actual sentient pudge

#### Code Revision
- release - 
7582a0e2abeb10a9f85b22275b6fd87e9aa1308a

**Comment by Arokha** [comment]
🤔

**Comment by Arokha** [comment]
This is maybe fixed now. Lemme know.

**Comment by SpadesNeil** [comment]
I've never had such a bug.

**Comment by Very-Soft** [comment]
Can't reproduce now, closing
