### ISSUE TITLE
Ghosts can be seen on NIFs/ AR Huds

### ISSUE THREAD

**Issue by Xonkon** [VOREStation/VOREStation#2785]
#### Brief description of the issue
When having a NIF hud (or AR hud) activated, ghosts/observers can be seen thanks to the floating icon above their head.

#### What you expected to happen
Ghosts to be invisible

#### What actually happened
I see dead people

#### Steps to reproduce
- (Step 1) Put on AR glasses/ download AR HUD
- (Step 2)Notice floating icons with names that belong to dead people/ observers
- (Step 3) Flip the fuck out
#### Code Revision
- 7582a0e2abeb10a9f85b22275b6fd87e9aa1308a

**Comment by HzDonut** [comment]
Already has a fix ready to go with the next update: https://github.com/VOREStation/VOREStation/pull/2782

**Comment by Arokha** [comment]
Updated, fixed
