### ISSUE TITLE
So many ghosts (of items and such)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2801]
#### Brief description of the issue
Ever since the most recent update, ghost images for things have been popping up all over, from a clone of yourself appearing on some stairs after you walk up them, to removing a battery from a floodlight and somehow getting two. Rather than have issue after issue of it spring up, i figure one to compile them all would work better. Specifically, the issue i witnessed to make me finally open this was the floodlight incident since it was more severe than the others i saw, so i'll fill out the rest of the form accordingly.

UPDATE: It apparently counts as a two-handed battery, if that makes sense. The empty hand also counts as me holding the battery. Nearly prevented me from using my right hand at all until i dropped the ghost battery to now have TWO BATTERIES.

#### What you expected to happen
Pop out the one battery, get one battery.

#### What actually happened
Got one battery and a ghost battery.

#### Steps to reproduce
- Just open up a floodlight and pop the battery out.

#### Code Revision
- release - 
e1a9a611a8259561240bb0fb973331f9a9eb413b 
 
#### Anything else you may wish to add:
- https://gyazo.com/d301fe44acfebcd9a6fa04aa779e3679 two batteries, nothing weird here...
- https://gyazo.com/4548d34e2a49e547b9f938202b574250 ...oh dear.

**Comment by Arokha** [comment]
Think this is either fixed, or just you, as nobody else has encountered this that I'm aware of.
