### ISSUE TITLE
Meson Goggles on borgs don't work well with the new lighting

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2805]
#### Brief description of the issue
Mesons goggles don't get rid of darkness when in a dark room.

#### What you expected to happen
Everything is bright and colourful and see-through when wearing mesons.

#### What actually happened
The room is dark, the surrounding areas are bright.

#### Steps to reproduce
- Go to a dark room or go outside.
- Wear mesons
- Watch as your character is still submerged in darkness but everywhere else is bright.

#### Code Revision
e1a9a611a8259561240bb0fb973331f9a9eb413b 
 
#### Anything else you may wish to add:
![darknessmeson](https://user-images.githubusercontent.com/33539568/35189580-56e2b118-fea1-11e7-9da3-bf39edab8e69.JPG)

**Comment by Arokha** [comment]
Only affects borgs.

**Comment by Arokha** [comment]
![image](https://user-images.githubusercontent.com/15028025/35189634-28f3daa4-fe1d-11e7-9a3c-fc48710b6e42.png)
![image](https://user-images.githubusercontent.com/15028025/35189636-31f90ce6-fe1d-11e7-953e-c92f77cffae1.png)

**Comment by MrSign** [comment]
The issue also occurs with the Mining module material scanner vision, if that runs on a seperate item code.

**Comment by Arokha** [comment]
Fixed
