### ISSUE TITLE
Random engine - Supermatter - Siphoning vent doesn't turn on automatically.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2820]
#### Brief description of the issue
The siphoning vent in the supermatter core is not automatically on, requiring someone, such as a cyborg, to enter the core and un-wrench and re-wrench the vent in order to get it to properly work with the air alarm.

#### What you expected to happen
Upon round start, vent is already siphoning.

#### What actually happened
Vent is turned off, requiring extreme measures in order to be activated.

#### Steps to reproduce
- Start up map and hope for SM spawn.
- Set up SM engine.
- Notice no gas is being pumped. Investigate further.
-See that siphoning vent is not working, attempt to turn it on at the air alarm. It doesn't respond.

#### Code Revision
093ca7d14d88b72f2d0dc924c3a52bf3a5c96e77 
 
#### Anything else you may wish to add:
N/A

**Comment by Leshana** [comment]
It is not _supposed_ to work with the air alarm, it is controlled by the Engine Cooling Control computer in the monitoring room.
However it IS supposed to start the round turned on.  I'll need to check that part.

**Comment by MrSign** [comment]
That's how I was able to turn it on to get it to start sucking the hot air to power the thermogenerator. But, I'll see next time if I can turn it on that way.

**Comment by Arokha** [comment]
Interesting. It's variable-identical to the original SME vent, so I assume it has something to do with the maploader not loading it right.
