### ISSUE TITLE
Head of Security's NSFW gun/magazine turning semi-transparent whenever interacted with.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2825]
#### Brief description of the issue
When interacting with the NSFW gun that is issued for the HoS. Placing microbatteries into the magazine causes the magazine to either 'disappear' inside the briefcase until another item is interacted with or turn semi-transparent when in the hand until dropped. The gun suffers the same fate, turning semi-transparent in the hand or 'invisible' in the briefcase when loaded with the magazine.

#### What you expected to happen
The sprites remain opaque whenever interacted with, not requiring to be dropped.

#### What actually happened
Magazine and Gun sprite consistently disappearing/reappearing or turning semi-transparent when interacted with, mostly by either loading or unloading it.

#### Steps to reproduce
- Spawn as Head of Security and go to locker
- Unlock NSFW secure briefcase
- Place a microbattery into the magazine, watch the magazine 'disappear' but you can still clearly see the grey outline of an item there. Interact with a leftover micro battery to make it reappear.
- Load magazine into the gun while it is still in the briefcase, watch the gun 'disappear' but you can still clearly see the grey outline of an item there.
- Interact with another battery to make the gun return.
- Take the gun out and unload it, the gun turns semi-transparent.
- Unload magazine, magazine will turn semi-transparent.

#### Code Revision
- 093ca7d14d88b72f2d0dc924c3a52bf3a5c96e77 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment]
Dropping and picking it back up fixes this. I think what's happening is that it's falling BEHIND the hand hud area. Dropping and picking it up resets the plane/layer it should be on and thus fixes it.

**Comment by Arokha** [comment]
Fixed
