### ISSUE TITLE
Chemistry Equipment - Layering Issue

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2828]
#### Brief description of the issue
When ejecting beakers out of the chemistry dispensers or pill bottles from the ChemMaster, they fall underneath the sprite of the machine, forcing you to right click to pick it up.

#### What you expected to happen
For the beaker/pill bottle to be above the dispenser/chem master

#### What actually happened
They fall underneath the sprite, delaying you by five seconds in order to right click and pick it up from the menu.

#### Steps to reproduce
- Go to chemistry and grab a beaker
- Slot it into the chemistry dispenser.
- Eject it.
- Panic when you think the dispenser has destroyed your beaker until you right click on it and see it is merely underneath the sprite of the dispenser.
-Repeat steps for ChemMaster

#### Code Revision
093ca7d14d88b72f2d0dc924c3a52bf3a5c96e77 
 
#### Anything else you may wish to add:
![dispenser bug](https://user-images.githubusercontent.com/33539568/35244933-f684a9d6-0015-11e8-991f-7b5f0ec25c41.png)

**Comment by Arokha** [comment]
Byond seems to have 'forgotten' how to order things on the same layer (previously it was stacked in the order they entered the turf, and this seems to have somewhat evaporated).
