### ISSUE TITLE
Delaying in interacting with items/equipment when you unbuckle yourself from a chair.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#2829]
#### Brief description of the issue
After unbuckling from a chair, it sometimes takes a few seconds or even longer to be able to interact with stuff. I found spamming the 'drop' button helps speed it up but it prevents picking up objects until the 'effects' fade.

#### What you expected to happen
To be able to interact and pick-up objects immediately after unbuckling myself from a chair.

#### What actually happened
There is a delay between interaction/pick up, even though I can freely move around with no lag.

#### Steps to reproduce
- Buckle yourself into a chair
- Unbuckle yourself
- Click on an item or equipment that has a pop-up window screen.
- Witness as nothing happens.
- Spam click until you pick up the object/interact with the equipment.

#### Code Revision
093ca7d14d88b72f2d0dc924c3a52bf3a5c96e77 

#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment]
Unbuckling probably sets the attack cooldown on clicking if I had to guess.

**Comment by Arokha** [comment]
Am told has been a bug for about a year.

**Comment by Arokha** [comment]
I think you need to wait 1 life tick to get everything returned to normal. I'm not sure this is easily fixable.

**Comment by SingoDingo** [comment]
I noticed this either only happens when one uses resist to unbuckle, or it's much shorter if you click the chair to unbuckle instead.

**Comment by Arokha** [comment]
Fixed upstream.
