### ISSUE TITLE
Farmbots get stuck in water filling loop, among other problems

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2835]
#### Brief description of the issue
Seems like the poor farming assistant bots we know and love are broken to hell and back after the update for them. Got stuck in a watertank filling loop (the tank volume actually DROPPED, somehow) and also just completely refused to water plants. Weeding and fertilizing still worked though.

#### What you expected to happen
Farmbots would work just fine.

#### What actually happened
Fills watertank forever, won't water plants.

#### Steps to reproduce
- Build farmbot
- Turn all of it's settings to 'yes' for maximum usefulness.
- Watch it derp around and be useless.

#### Code Revision
-  release - 
eabef108724ea9c1133f271ef0d406a41b68f7c3

**Comment by Draycu** [comment]
Yeah, I thought it acted oddly with refilling for a bit longer than it should have when I was using it for xenobotany.  Hope this can be addressed!

**Comment by Arokha** [comment]
None of the behavior on farmbots was changed with that PR so I doubt that was related. The only thing that changed was hiding the menu options to enable autoharvest.
