### ISSUE TITLE
Vasilissans Can't be Colored

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#2838]
#### Brief description of the issue
Vasilissans can't have their body colors changed; they're locked into a gray color. Their legs, however, can change color based on Body Color.

#### What you expected to happen
For my Vasilissan's body color to change when I change its Body Color.

#### What actually happened
It's still gray. Only the legs change color.

#### Steps to reproduce
- Go into character creation
- Make a Vasilissan
- Try to change its body color
- Watch as nothing happens

#### Code Revision
- eabef108724ea9c1133f271ef0d406a41b68f7c3
 
#### Anything else you may wish to add:
I'm pretty sure you could change their body colors before, right? I know their lore says they come in a variety of diverse colors.

**Comment by Arokha** [comment]
believe cyantime fixed this

**Comment by AliciaJewel** [comment]
Has the change not been uploaded yet? Because it still isn't working.
