### ISSUE TITLE
Commlinks probably shouldn't be in the loadout

### ISSUE THREAD

**Issue by LittleBigKid2000** [VOREStation/VOREStation#2839]
#### Brief description of the issue
Commlinks are in the loadout, as an option for the communicator selection. I'm fairly sure they're supposed to be NIF software, not an actual item you can spawn with.

#### What you expected to happen
For commlinks to not be acquirable, aside from having them in your NIF.

#### What actually happened
You can select commlinks in the loadout and spawn with them.

#### Steps to reproduce
- Go into loadout
- Select communicator selection
- Select commlink for communicator selection
- Join the game
- Find a communicator in your backpack that's labelled as 'commlink' and has its job set to '[commlink]', but is otherwise identical to a normal communicator (The '[commlink]' job can even be changed by swiping an ID).

#### Code Revision
- eabef108724ea9c1133f271ef0d406a41b68f7c3 
Note: Tested in a private testing server with completely unrelated mapping changes, but the commlink option appears in 
 
#### Anything else you may wish to add:
Side issue: Commlinks in a NIF have a flashlight button that doesn't actually do anything, presumably since the commlink is embedded in the user. Commlink items have flashlights that work just fine.

**Comment by aztectornado** [comment]
Not a bug. Commlinks were originally an item like a cell phone, and in fact the item version can do a few things the NIF can't, such as video calls. The internal comm was added so you don't need the item for some things, but the item itself is still a normal thing to have.

**Comment by Arokha** [comment]
Is a bug. Commlink is the special subtype of Communicator that's put into NIFs for use with the Commlink NIFSoft.

Communicators are the cellphone-like object, and communicator watches are the watch version. Commlinks are not supposed to be physically obtainable (the loadout just uses typesof() to find all types/subtypes of communicators though, which includes commlink):
`for(var/communicator in typesof(/obj/item/device/communicator) - list(/obj/item/device/communicator/integrated))`

You can see they also had to exclude their own 'integrated' type, which is used for borgs and the AI and such. The fix would be:
`for(var/communicator in typesof(/obj/item/device/communicator) - list(/obj/item/device/communicator/integrated,/obj/item/device/communicator/commlink)) //VOREStation Edit - Remove Commlink`

**Comment by aztectornado** [comment]
wait, you mean you can actually get the actual internal commlink as an item? Okay, yeah, that's a bug. Also what the heck. How could this even have happened?
