### ISSUE TITLE
Pathogenic Isolator UI bug

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#285]
#### Brief description of the issue
Tried to put a syringe into the isolator. Worked fine. Pushed the Database lookup buttun and The entire UI is just blank.
https://i.gyazo.com/41f5f18a561562cd45281ead05271c66.png

#### What you expected to happen
To have the Pathogenic Isolator interface show me the Virus in the database

#### What actually happened
It gave me a blank screen. Can't fix it either.

#### Steps to reproduce
Make a random virus.
Take a blood sample.
Put it into the Pathogenic Isolator.
Click the Database lookup button.

#### Additional info:
Server revision: release - 2016-06-01

**Comment by SpadesNeil** [comment]
Has this been tested lately?

**Comment by SpadesNeil** [comment]
Closing due to lack of testing.
