### ISSUE TITLE
AR glasses make it so one see "ghost" job icons

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#2852]
#### Brief description of the issue
Can see a job icon of a ghost like grey A for Assistant, but only when having AR glasses on, I specifically had AR-R glasses.

#### What you expected to happen
Just an empty seat

#### What actually happened
Seat with spooky A icon above it

#### Steps to reproduce
- Have AR glasses on 
- Sometimes see ghost job icon

#### Code Revision
- eabef108724ea9c1133f271ef0d406a41b68f7c3 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![scrnshot1](https://user-images.githubusercontent.com/19510125/35475763-bc6bd26a-0371-11e8-8b50-a3b61cba30de.png)

**Comment by SpadesNeil** [comment]
@Arokha Resolved I assume?
