### ISSUE TITLE
Glowing eyes on ghosts are visible to everyone

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2867]
#### Brief description of the issue
Right what it says in the title.

#### What you expected to happen
Ghosts would be completely invisible to living players.

#### What actually happened
Players get to see a pair of spooky floating eyes.

#### Steps to reproduce
- Get the glowing eyes trait
- Observe or ghost
- Be spooky

#### Code Revision
-  release - 
26be9d82d8720b048d2c6c58b5c3401b47555543

**Comment by Arokha** [comment]
Fixed by returning ghosts to invisible-land.
