### ISSUE TITLE
pAI medical HUD doesn't work

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2868]
#### Brief description of the issue
Getting the medHUD software and activating it just causes nothing to appear.

#### What you expected to happen
I'd enable it and get a nice medHUD to be a useful l'il bugger.

#### What actually happened
I enabled it and nothing happened.

#### Steps to reproduce
- Become a pAI
- Nab the Medical Hud software
- Enable it

#### Code Revision
- release - 
26be9d82d8720b048d2c6c58b5c3401b47555543

**Comment by Verkister** [comment]
Figured out the likely cause for the bug. Sending the fix to polaris if it works.

**Comment by Verkister** [comment]
Fixed in next Polaris sync.
