### ISSUE TITLE
Aronai currently exists

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#2876]
#### Brief description of the issue
Aronai currently exists

#### What you expected to happen
﻿ＤＥＳＴＲＵＣＴＩＯＮ

#### What actually happened
No destruction

#### Steps to reproduce
>Look at Aronai
>Not destroyed yet
>:thinking:

#### Code Revision
2.63- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
![telegram_hmph](https://user-images.githubusercontent.com/15028025/35500017-d923fbee-04a2-11e8-83cb-4ee21a404765.png)

**Comment by KotetsuRedwood** [comment]
![image](https://user-images.githubusercontent.com/10330701/35500063-fd32de54-04cc-11e8-9889-ec9a8428053e.png)

**Comment by Arokha** [comment]
WOW

**Comment by SilencedMP5A5** [comment]
destroyed

**Comment by SpadesNeil** [comment]
Can you not?

**Comment by SpadesNeil** [comment]
nvm Aronai has been memeing up my PRs **ALL DAY**

**Comment by AeroWing** [comment]
Suggested fix:

http://d.facdn.net/art/serpentsaurus/1507848133/1507848133.serpentsaurus_inktober12.png
