### ISSUE TITLE
Anomaly snowflake code needs to be rewritten

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#2883]
#### Brief description of the issue
The following lines make me scream.
```//returns 0..1, with 1 being no protection and 0 being fully protected
/proc/GetAnomalySusceptibility(var/mob/living/carbon/human/H)
	if(!istype(H))
		return 1
	if(istype(get_area(H),/area/crew_quarters/sleep)) return 0 //VOREStation Edit - Dorms are protected from anomalies
	var/protected = 0

	//anomaly suits give best protection, but excavation suits are almost as good
	if(istype(H.back,/obj/item/weapon/rig/hazmat))
		var/obj/item/weapon/rig/hazmat/rig = H.back
		if(rig.suit_is_deployed() && !rig.offline)
			protected += 1

	if(istype(H.wear_suit,/obj/item/clothing/suit/bio_suit/anomaly))
		protected += 0.6
	else if(istype(H.wear_suit,/obj/item/clothing/suit/space/anomaly))
		protected += 0.5

	if(istype(H.head,/obj/item/clothing/head/bio_hood/anomaly))
		protected += 0.3
	else if(istype(H.head,/obj/item/clothing/head/helmet/space/anomaly))
		protected += 0.2

	//latex gloves and science goggles also give a bit of bonus protection
	if(istype(H.gloves,/obj/item/clothing/gloves/sterile))
		protected += 0.1

	if(istype(H.glasses,/obj/item/clothing/glasses/science))
		protected += 0.1

	return 1 - protected
```

#### What you expected to happen
This is written horribly. If you're going to add some stupid snowflake code, at least have the variable editable by the suits as to how much protection the mob should get.

Also it would be nice if scientists weren't basically fucked even if they put on gloves, goggles, etc. The culmination of all the correct gear should result in "protected = 1" or the equivalent effect.

#### What actually happened
nah fuck you, need hazmat suit to do Xenoarch and not mutate horribly

#### Steps to reproduce
- N/A this is a balance issue

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/7f48af2b4bb7ed4bd7a6dc5c363830bfd1e8c280

**Comment by SpadesNeil** [comment]
After further review of this code and not doing sleepy Ace math I am changing the severity of this to minor because if you actually wear all the correct gear, you are fully protected.

Correct gear should be listed somewhere on our SOP or guides pages.

**Comment by ktccd** [comment]
Wait.... Science goggles work?
I thought the whole point of those goggles were "they do nothing" and are an inside joke... Why do xenoarchs have mesons in their equipment areas then? Because you can't switch those while outside either...
