### ISSUE TITLE
Tauric Hardsuits not working for Feline Taurs

### ISSUE THREAD

**Issue by Aphelion1062** [VOREStation/VOREStation#2885]
#### Brief description of the issue
It's not possible to equip tauric specific hardsuits with a feline dual-color tauric tail (Possibly standard feline tauric as well)

#### What you expected to happen
To equip the hardsuit specifically designated for taurs.

#### What actually happened
I was prompted with the message "You need to have a horse, wolf, or naga half to wear this."

#### Steps to reproduce
- Join the game with a Dual-Color Feline Taur
- Attempt to equip Taur-Specific engineering Hardsuit

#### Code Revision
-9bbc3290ae6a94d077cebe450ce66b8cd83927b3

**Comment by SilencedMP5A5** [comment]
my lazy ass never finished the taur hardsuits because motivation is sparse

**Comment by Neopatra** [comment]
my lazy ass also failed to finish the taur hardsuits because I became distracted with awaymission mapping.

**Comment by Arokha** [comment]
Lack of sprites. Use a normal hardsuit. Any taurs that can't wear a taur hardsuit can wear the normal ones.

**Comment by Arokha** [comment]
S'been like a year and nobody's made feline sprites so I'm just gonnnnaaaaaa close.
