### ISSUE TITLE
Map change in Xenoarch

### ISSUE THREAD

**Issue by Squi-RL** [VOREStation/VOREStation#2890]
#### Brief description of the issue
AMI suits appear to have been removed from the Xenoarchaeologist lockers

#### What you expected to happen
expected hardsuits for digging, or at least for the anomaly suits to hold large air tanks since I kinda need both hands to dig with any sort of efficacy

#### What actually happened
horribly disappointed

#### Steps to reproduce
- sign up as a Xenoarchaeologist
- open the lockers
- cry

#### Code Revision
- 9bbc3290ae6a94d077cebe450ce66b8cd83927b3 
 
#### Anything else you may wish to add:
- AMI suits are almost essential to QOL of Xenoarchaeology, without them it's even more annoying to do anything in it. I'm not sure if I should be posting this here, but I'm hoping this is fixed in some way, either by readding them in if they were removed; or by buffing the other tools...

**Comment by Cyantime** [comment]
The excavation suit can hold normal sized air tanks in suit storage, and is what you wear outside for digging. The anomaly suit is a biosuit variant for anomalies that you wear inside.

**Comment by Squi-RL** [comment]
Fair nough, quite frankly didn't know there was such a thing as an excavation suit... my bad on that. I do still believe there should be at least one AMI module in Xenoarchaeology, similar to how there's one in mining.

**Comment by SpadesNeil** [comment]
The AMI is not as essential as people have been led to believe.

The most common error is not wearing the correct equipment. Under the normal anomaly and excavation suits are latex gloves and science goggles. Those provide enough anomaly protection to 100% cover you with the other suit parts.

The excavation suit also does hold tanks. I'm gonna close this.
