### ISSUE TITLE
Tailwag lacks visual update.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#2891]
#### Brief description of the issue
-Starting tailwag with *vwag doesn't update the player icon, leaving the static tail on until something else calls the update, such as manually (un)equipping an item. 

#### What you expected to happen
-Tail to start wagging when intended.

#### What actually happened
-The tail icon never updated until something else called for update, in this case manual item equip.

#### Steps to reproduce
- (Step 1) Acquire tail with wag abilities.
- (Step 2) *vwag
- (Step 3) Be stuck with static tail.
- (Step 4) (un)equip a thing.
- (Step 5) Tail finally starts wagging.

#### Code Revision
- 9bbc3290ae6a94d077cebe450ce66b8cd83927b3
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
That's weird. Originally I was thinking it was because it wasn't updating the icon, but the code appears to call everything normally.
`handle_emote_vr` calls
`toggle_tail_vr` calls
`update_tail_showing` calls
`update_icons_layers` which is what is called when you equip/unequip something. ODD.
