### ISSUE TITLE
Engineering borg modue icon typo.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#29]
#### Bug description
Engineering borg doesn't spawn with  the correct module icon

#### Expected result
Choose engineering borg, module be the orange "Engineer" module

#### Actual result
Choose engineering borg, module is the green "invalid module" sprite

#### Steps to reproduce
Spawn in, choose engineering borg, see that the module sprite is broken, cry

#### Additional info:
 - **Server Revision**: Server revision: master - 2016-05-08 3130935f6b6c806e91ccccb04c360a3db15cf2d9
 - **Anything else you may wish to add** Below

To clarify: This is what I'm talking about http://puu.sh/oKKsB/c94d61e4e0.png
It starts as "Engineering" which makes it look like this: http://puu.sh/oKKuv/1cf340d7d2.png
Can be fixed by renaming the icon in screen1_robot.dmi from "engineer" to "engineering"

**Comment by SpadesNeil** [comment]
Has this been corrected yet?

**Comment by Cameron653** [comment]
I don't believe so.

There's also a bug with combat cyborgs.
https://github.com/VOREStation/VOREStation/blob/54272da16785733c4036ab3738229491b85de5a3/code/modules/mob/living/silicon/robot/robot_modules.dm#L687

On line 687. It should be /obj/item/weapon/robot_module/security/combat/New()

It doesn't work at all, otherwise.

**Comment by Cameron653** [comment]
This is going to be fixed in polaris. Closing this.
