### ISSUE TITLE
Occupation selection broken

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2900]
#### Brief description of the issue
If you select visitor as a job, it removes the visitor option, locking you into no job at all

#### What you expected to happen
Be able to toggle visitor on and off

#### What actually happened
I got put in occupational limbo

#### Steps to reproduce
Go into occupation tab in character setup
Click Visitor

#### Code Revision
6fb46857ef878d7411daa71cd4fc53d8ff81ce53
 
#### Anything else you may wish to add:
https://i.imgur.com/9Cz2q0x.png

**Comment by SpadesNeil** [comment]
@Arokha

**Comment by SpadesNeil** [comment]
Does this bug prevent you from playing?

**Comment by Mewchild** [comment]
I haven't checked yet. Give me 5 minutes, documenting another bug

**Comment by Mewchild** [comment]
Fixed in https://github.com/VOREStation/VOREStation/pull/2903
Fuck Aronai's 2quick
