### ISSUE TITLE
Several jobs have invisible AR overlay icons

### ISSUE THREAD

**Issue by LittleBigKid2000** [VOREStation/VOREStation#2904]
#### Brief description of the issue
Visitors have invisible AR overlay icons. This is apparent when you have a med AR overlay and they have a backup implant.

#### What you expected to happen
For visitors to have visible AR overlay icons.

#### What actually happened
Visitors have invisible AR overlay icons.

#### Steps to reproduce
- Get a NIF and optionally a med AR overlay
- Look at a visitor with their ID on
- Look for the icon that isn't there

#### Code Revision
- 0068aae39e36a799811cb1c444c9c576fec1b360

**Comment by Mewchild** [comment]
This also applies to explorers and pilots

**Comment by Arokha** [comment]
The icons for such don't exist. Visitor is not a Pol bug but the other 3 jobs are.

**Comment by Arokha** [comment]
@Very-Soft made icons for these, updating now
