### ISSUE TITLE
Job gear isn't showing up in char setup.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#2911]
#### Brief description of the issue
-Job specific gear and loadout presets aren't showing up, basically any high set job showing up as if you had assistant selected instead. Job gear showing up as grey jumpsuit only and job locked loadout stuff not showing up at all.

#### What you expected to happen
-Job gear and loadout stuff to match occupation prefs in char setup as they used to.

#### What actually happened
-Greytide with greytide limitations.

#### Steps to reproduce
- (Step 1) Have a character set up as high on a job.
- (Step 2) Hide loadout or just have no public access loadout gear overriding your stuff.
- (Step 3) Show job gear.
- (Step 4) Witness greytide.
- (Step 5) Pick some loadout stuff specific for your selected job and have it not show up in setup either.

#### Code Revision
- 0068aae39e36a799811cb1c444c9c576fec1b360
 
#### Anything else you may wish to add:
- Didn't try actually joining yet because got no time atm.

**Comment by Arokha** [comment]
Fixed in already merged update, going on server shortly
