### ISSUE TITLE
Botanists are missing their HUD icon

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2915]
#### Brief description of the issue
Botanists and their alt titles don't have hud icons in AR huds. (Unsure about regular huds glasses)

#### What you expected to happen
To see hud icons over everyone

#### What actually happened
Some people don't have them

#### Steps to reproduce
- (Step 1) Be near a botanist/gardener
- (Step 2) Turn on AR hud
- (Step 3) Wonder why Botanists don't have an icon!!!

#### Code Revision
- release - 
d5703da404091ce3f52db48b9cf9a6b6d66808c4

**Comment by Arokha** [comment]
Should be fixed now. Reopen if not.
