### ISSUE TITLE
Black Dufflebags are in the loadout, and cost the same as other dufflebags

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2916]
Unless this is a variant of the black dufflebag that is not awesome, this should be changed. 

The black dufflebag is not just a dufflebag that is black, it's a dufflebag that lacks the speed debuff that normal dufflebags have. It's an obviously better choice than any other bag that one could get outside of RnD. 

Previously these were relatively common on the map, and highly sought after maintenance loot, because of the fact that they are the second best bag in the game, behind the Bag of Holding or whatever it's called.

I personally don't feel that these should be in the loadout, because they are just blatantly better than any other option, and assuming they are in fact the normal black dufflebag, as soon as people figure out they are there, everyone will take them because why wouldn't they. If they remain in the loadout, they should be job locked to CD to encourage more people to play that, or they should be far more expensive to take. Like, 10 or 15 points. 

#### Code Revision
- release - 
d5703da404091ce3f52db48b9cf9a6b6d66808c4

**Comment by KotetsuRedwood** [comment]
If I recall correctly, the variant in the loadout is just a black dufflebag with the speed penalty, not the syndicate one that's somehow lighter.

**Comment by Verkister** [comment]
Yeah the loadout version is purely cosmetic.

**Comment by Very-Soft** [comment]
Understood, I'll close this then.
