### ISSUE TITLE
Parachute packing messages are leaking.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#2928]
#### Brief description of the issue
The parachute packing messages directed to the packer show up on people standing next to them.

#### What you expected to happen
The other person to be packing their parachutes, not "me" lmao.

#### What actually happened
![kuva](https://user-images.githubusercontent.com/13697337/35699502-eeaff14a-0798-11e8-8200-7f1caa5094e4.png)
![kuva](https://user-images.githubusercontent.com/13697337/35699505-f27e6aae-0798-11e8-987d-880e867b3796.png)
(I'm the one not holding any parachutes there)

#### Steps to reproduce
- (Step 1) Tell someone to pack some parachutes near you.
- (Step 2) Eavesdrop the lewd DMs between the packer and the packee.

#### Code Revision
- 486471f32df39b48d70080d34a3c4a8d65d82bc7
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cyantime** [comment]
Already fixed on Polaris
