### ISSUE TITLE
Mouse paws are too full to ventcrawl

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#2941]
#### Brief description of the issue
While a mouse standing on a vent, any attempt to ventcrawl says "You can't carry  while ventcrawling!"

#### What you expected to happen
For "Crawl through Vent" to allow entering a vent

#### What actually happened
Nope!

#### Steps to reproduce
- Observe
- Become mouse
- Stand on vent
- Use "Crawl through Vent"
- Denied!

#### Code Revision
- 486471f32df39b48d70080d34a3c4a8d65d82bc7 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/34605836/35763201-deac7958-0874-11e8-894a-4e8223cc42c3.png)
![image](https://user-images.githubusercontent.com/34605836/35763205-f4cf9e04-0874-11e8-90c4-ab3a54552450.png)
![image](https://user-images.githubusercontent.com/34605836/35763209-f87ca4f2-0874-11e8-8778-a91ef975eeac.png)

**Comment by Arokha** [comment]
Was the plane_master for augmented reality.
