### ISSUE TITLE
Sprite misalignment 

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#296]
#### Brief description of the issue
Vulpkanin sprite is misaligned. When facing north, the right side of the sprite, - the arm and legs-, are misaligned.
![image](https://cloud.githubusercontent.com/assets/19210185/15798854/8cccc0a4-2a48-11e6-8aca-0dfc9c71a5bb.png)
#### What you expected to happen
To have a correctly aligned sprite.
#### What actually happened
I had an incorrectly aligned sprite.
#### Steps to reproduce
1. Select Vulpkanin race.
2. Look at preview.
#### Additional info:
 - **Server Revision**: release - 2016-06-04
66dde0234607662f93adf2b7195b31dc70b65d62 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
@Poojawa

**Comment by Poojawa** [comment]
Fixed in #419
