### ISSUE TITLE
Suggestion: An official, harmless, SOP-worthy way of extracting people from simple mob bellies.

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#2963]
#### Brief description of the suggestion
An official item, some sort of device or gun or something, that will force a simple mob to release something it's eaten, without actually harming it, thus not drawing aggro from it.  Something that's officially known to do this, so it can be made part of "standard operating procedure" for dealing with voracious but otherwise non-hostile animals.

#### What you expect to happen
Situation 1: Say someone brings back a fennec from an excursion as a pet.  Non-hostile, endo at first, only has a chance of gurgling if you resist.
-Person enjoys cute fennec pet.
-Fennec noms a crewmember.
-Slightly panicky crewmember triggers gurgling accidentally.  (Like accidentally clicking resist.)
-This is made known, and someone brings this suggested device and safely extracts the slightly softer crewmember.
-Person with fennec pet gets to potentially keep fennec pet, with either a warning to prevent it from eating crewmembers in the future, or given the device to resolve future incidents.

Situation 2: Say you find a village of catgirl mobs on an excursion.  (Who I really wish were truly endo without the chance of digestion, but I digress.)
-Oh hey, cute catgirls.
-Whoops, they occasionally nom someone.
-We followed SOP, we got something to get them out, fetch it.
-Continue to enjoy cute catgirls wandering around.

#### What currently happens
Situation 1:
-Person enjoys cute fennec pet.  (Background screeching about how they've been known to eat people.)
-Fennec noms a crewmember.
-Slightly panicky crewmember accidentally triggers digestion.
-This is made known.  But there is no IC way to get someone out of a mob aside from killing them.  (Background screeching of "I TOLD YOU SO".  Sec member: **_"MUH VALIDS"_** )
-Person with fennec pet is soon cradling the dead corpse of said fennec pet.
-Salt in OOC.

Situation 2:
-Oh hey, cute catgirls.
-Whoops, they occasionally nom someone.
-No way to get them out ICly without killing.  Grab the guns, boys.
-Other catgirls object to death of first one.
-Dead catgirls everywhere.

#### Steps to reproduce
- Get some endo mobs involved.
- Watch what happens when someone gets nommed, triggers digestion, and announces this fact.

#### Code Revision
- release - 
1562fd8f0de8180dbba60e5e4fe5941e3f924382 
 
#### Anything else you may wish to add:
- There's the Sickshot, but A) it doesn't work on mobs, and B) even if it did, it does damage, thus drawing aggro.
- There's #1130, but A) it's nearly a year old (why hasn't someone done this yet) and B) a newspaper isn't quite something that could be officially added ta SOP.
- There's OOC escape, but A) that's officially for escapin' pref-breaky stuff, and B) who the fuck remembers you can get a pass if you RP escapin' first?  :P

**Comment by SingoDingo** [comment]
I'm still in favor of the "Bapping mobs with a rolled up newspaper makes them spit things out" suggestion. Simply make the official stance to "give them some gentle encouragement" because "these are all trained animals and shouldn't require weapons to pacify".

**Comment by ArgobargSoup** [comment]
@SingoDingo This suggestion also covers untrained animals, and slightly higher things, like, as my favorite example, wild catgirls.

**Comment by Screemonster** [comment]
the best part about the people screeching about how fennecs eat people is that they're nonhostile and only bumpnom

all you have to do to render them 100% harmless is buckle them to a chair

**Comment by SpadesNeil** [comment]
Catgirls are hostile mobs with neutral intentions. They will swarm you if you irritate one of them. This is by design and I have no intent to change it. The mechanic of catgirls is don't struggle and accept your doom as permanent bellywarmer.

But for everything else, like Oties and Fennecs and everything else that's generally not meant to be hostile, it's a good idea.

**Comment by Very-Soft** [comment]
It'd be funny if the SOP book also worked on mobs to release prey.

*bonk*

HURK

**Comment by SpadesNeil** [comment]
How about Heimlich? Grab, aggressive, and then a command to do it, wait for a cooldown bar to fill up. It'd be random chance if it works each time.

We could also maybe set up player guts to optionally do the same thing.

**Comment by ArgobargSoup** [comment]
@SpadesNeil I mean, I could go on for a bit why I would've liked the catgirl mobs ta be harmless mobs in the first place, but that's A) probably mostly personal reasons and B) not the point of this issue.

The reason for my comment up there was that... I don't mind them swarming and slapping the shit outta someone who messed with them, or punishing them by shoving them down their gullet.  I'm just saying I wish they didn't have a gurgle chance, so that, combined with an official SOP device for removing someone from a belly, there'd be less chance of dead catgirls.  More fun involved for when they do appear.  :P

I may have made "dead catgirl" sprites but that doesn't mean I like seein' them.  :P

**Comment by Burrito-Justice** [comment]
I'd like to see something like this go through, people always immediately rush to medical screeching for Ickypak but they don't realize that simple mobs can't process reagents.

**Comment by TheDavestDave** [comment]
We need a way to stop that happening to hostile mobs because at some point a deathclaws gonna eat someone to be saved by a micro booping the deathclaw with a news paper

**Comment by Screemonster** [comment]
That's easily done, just give it a proc that checks the hostile var.

_Retaliate_ mobs can have a %chance of acquiescing to the newspaper or deciding to eat you too.

**Comment by chaoko99** [comment]
>. The mechanic of catgirls is don't struggle and accept your doom as permanent bellywarmer.

Why is this fun for the player?

**Comment by SpadesNeil** [comment]
So people who actually like endo aren't fucked and not able to play with any vore mobs ever, but so they aren't completely without challenge.
