### ISSUE TITLE
Exploration shuttle doors do not have access restriction.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#2979]
#### Brief description of the issue
Every door on the exploration shuttle does not have an access requirement on it. The airlock buttons, flight console, and the bolt control button by the left-side hatch have access restrictions but the doors themselves do not. The bolt control button for the double-wide door at the rear of the shuttle does not have access restrictions.

#### What you expected to happen
To not let the filthy assistants and space-hobos into a multi-million dollar spacecraft.

#### What actually happened
They came by the thousands.

#### Steps to reproduce
- Be a space vagrant.
- Slap hand against door or bolt control button.
- Steal the valuable exploration gear.

#### Code Revision
- 373237a96720eadedff5397ca02865b3f0fdebef

**Comment by Arokha** [comment]
I mean, they can steal an air pump at worst. Also I'm 99% sure the rear button does have access restrictions.

This is to allow people on away missions like scientists or engineers or others who don't usually have access, to return to the ship if something bad happens and they need something from the ship, or need to HIDE in the ship.

**Comment by Arokha** [comment]
Checked, the rear one is missing req_one_access var, so it's free-to-use, which is a bug. Coulda sworn I set that.

**Comment by KonBear** [comment]
It's okay, stow aways will now just be considered extra rations.
