### ISSUE TITLE
Grubs spawning in engine core

### ISSUE THREAD

**Issue by Knightfall5** [VOREStation/VOREStation#2982]
#### Brief description of the issue
Solar grubs can spawn in the engine core when running the Tesla, resulting in the field collapsing and the energy ball escaping.

#### What you expected to happen
Solar grubs to be restricted from spawning in the core area, as it is with the Supermatter.

#### What actually happened
Grub spawned in the core area, power failed and bad things happened.

#### Code Revision
373237a96720eadedff5397ca02865b3f0fdebef

**Comment by aztectornado** [comment]
Could have just ventcrawled to the area outside the PA. I don't think there's a way for them to spawn outside, but those emitters take power from that region, right?

**Comment by Knightfall5** [comment]
The area you are referring to is the engine "core" in the tesla, all power to the field comes from the APC in that area yes

**Comment by Arokha** [comment]
Emitters don't get power from an APC.

**Comment by Knightfall5** [comment]
Oh yeah. They get it from the grid. Regardless, the solargrub is capable of eating all the engine core SMES output, which doesn't leave enough for the emitters

**Comment by Ketrai** [comment]
Yeah, they're not supposed to spawn there, but vents be evil. The chance is very small though... does the tesla explode that fast when the room has no power?

**Comment by Cyantime** [comment]
That quote is about the supermatter, not the tesla. The problem with the tesla isn't the APCs, it's that the grub takes power away from the emitters, which are the important part of keeping the orb contained.

**Comment by Knightfall5** [comment]
Basically above, yeah. And I linked the code revision of what the server was running when this happened. I wasn't here for the tesla getting loose, I arrived after, but once it grows to an adult and gets on a wire it'd take less than a minute for the field to collapse
