### ISSUE TITLE
Ghost Vision Verbs

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#2984]
#### Brief description of the issue
- Show/Hide Ghost Vision
Under the Preferences tab, toggles the ability to "see[ing] all mob emotes and nearby mob emotes"

- Toggle Ghost Vision
Under the Ghost tab, toggles the ability to "see things only other ghosts can see, like other ghosts"

That both of these are called "ghost vision" makes for a confusing time. Trying to explain to another staff member that Toggle Ghost Vision existed was entertaining, but shouldn't have to be a thing in the first place.

If possible one of these should be renamed to avoid future confusion.

#### Code Revision
Server revision: release - 
373237a96720eadedff5397ca02865b3f0fdebef

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/4832
