### ISSUE TITLE
Moveing a Positronic brain into a copy of your body doesn't copy your nif

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#2985]
#### Brief description of the issue
The nif deletes itself from if you get surgerly added to your body. 
#### What you expected to happen
the nif to still exist. To be part or your brain or the body
#### What actually happened
it gone

#### Steps to reproduce
have a charater with a positronic brain
get backed up
get gurgled
have rebotics print a new body
have robotics install your old brain into your new body
wait until round end
your charater no longer has a nif

#### Code Revision
- 373237a96720eadedff5397ca02865b3f0fdebef 
 
#### Anything else you may wish to add:
- Surely it should be printed with your body if it's not part of your brain, or it would install automaticly because it is part of your brain. There's no mention of this being a thing ment to happen in the wiki aswell. One of theese needs fixed

**Comment by SpadesNeil** [comment]
If anything the nif should be attached to the brain.

**Comment by Arokha** [comment]
Resleeving is what regenerates your NIF. Have them resleeve you into the body instead. The NIF is in your head, not in your brain (the brain is way too complicated for me to want to mess with, considering sometimes it's an organ, sometimes it's a mob, sometimes it's a mob inside a posibrain holder, etc).
