### ISSUE TITLE
Vasilissian icon can't change skincolor

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#2986]
#### Brief description of the issue
The Vasilissian body color doesn't change.

#### What you expected to happen
Get a gray-ish skin tone when I chose it.

#### What actually happened
It stayed as white as a Norwegian winter even when neon-green skin was selected.

#### Steps to reproduce
- (Step 1)Select Vasilissian species / Custom species with Vasilissian icon
- (Step 2)Change the skin color
- (Setp 3) Marvel at the lack of color changing

#### Code Revision
- 373237a96720eadedff5397ca02865b3f0fdebef 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Burrito-Justice** [comment]
This appears to have been reported before: https://github.com/VOREStation/VOREStation/issues/2838

**Comment by Arokha** [comment]
Dupe
