### ISSUE TITLE
Xenoarch deposits show up on counter even after mined

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#299]
#### Brief description of the issue

Xenoarch deposits show up on the Alden-Saraspova counter even after they're mined
#### What you expected to happen

Them to not show up on the Alden-Saraspova counter anymore
#### What actually happened

They show up
#### Steps to reproduce

Mine a deposit with a large artifact (Shows up on the Alden-Saraspova counter)
Mine it fully
Step back
Scan for an artifact
See it says there's still one to be mined right next to you
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab. 
  release - 2016-06-04
  66dde0234607662f93adf2b7195b31dc70b65d62 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
This should be fixed.

**Comment by Arokha** [comment]
Basically all of xenoarch was rewritten in late 08/2016.

https://github.com/Kelenius/Polaris/blob/d0a0a64722c227e8a9ad14c7621a7a70ad178d67/html/changelogs/Kelenius-fuckCael.yml
