### ISSUE TITLE
Engineering Mr. Handy has no eyes overlay

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#2995]
#### Brief description of the issue
Mr. Handy skin of Engineering cyborg module doesn't have eyes overlay

#### What you expected to happen
Mr. Handy skin of Engineering cyborg module should have eyes overlay to showcase active/not active state

#### What actually happened
it doesn't

#### Steps to reproduce
- (Step 1) Choose Engineering cyborg module and then Handy skin
- (Step 2) Look at him

#### Code Revision
- f9feb190c403c43650399fb5a4558187d5d155be 
 
#### Anything else you may wish to add:
- Issue appears to stem from robots.dmi sprite file having two different eyes-handy-science sprites and no eyes-handy-engineer. Recommended solution is to rename orange version of eyes-handy-science into eyes-handy-engineer

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/4831

**Comment by Arokha** [comment]
You probably fixed this in your borg sprites PR
