### ISSUE TITLE
Search and Rescue cannot spawn with medical loadout items

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#2999]
#### Brief description of the issue

When building a loadout for an SaR character, medical loadout items do not spawn, indicating that the game thinks they aren't part of medical or something

#### What you expected to happen

I could spawn with white drop pouches, a KHI med uniform, or even a stethescope or med hud when making a loadout. The list of affected items is large, though the department jacket seems to be an exception, oddly enough?

#### What actually happened

I didn't get anything. :c 

#### Steps to reproduce
- Get some medical stuff in your loadout
- Spawn in as Search and Rescue
- Be sad that you can't get drop pouches

#### Code Revision
- f9feb190c403c43650399fb5a4558187d5d155be 
 
#### Anything else you may wish to add:
- This job still deserves hazard pay, imo

**Comment by KonBear** [comment]
Same thing for explorers and science gear

**Comment by Arokha** [comment]
Done on Pol
