### ISSUE TITLE
Polaris Port - Vore Animals

### ISSUE THREAD

**Issue by Leshana** [VOREStation/VOREStation#30]
Port over our code for making several simple_animals predatory.
Issue #1 will handle vore bellies and such; this issue is for implementing the AI.

**Comment by SpadesNeil** [comment]
I think this is related to this issue, but we have a few vore versions of normal hostile mobs.

We should overwrite existing hostile mobs (such as hostile/carp, or hostile/bear) with vore mobs (hostile/vore/carp, hostile/vore/bear) and remove the non-vore versions from the code entirely.

**Comment by SpadesNeil** [comment]
The very final round of vore mobs was added recently via a pull request on the current Vorestation github.

**Comment by Leshana** [comment]
I actually had already pulled after PR 727, so we got those.

**Comment by SpadesNeil** [comment]
Excellent.
