### ISSUE TITLE
Xenoarch coolant issue

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#300]
#### Brief description of the issue

There is an issue with the coolant for the xenoarcheology machines- you can't feed it into tje machines. It says"120u added to the machine" but the bucket is still full.

#### What you expected to happen
1. Add coolant
2. Set coolant flow rate
3. Do science

#### What actually happened
120u of coolant added!
120u added!
The scanner overheats without coolant, making xenoarch impossible.
#### Steps to reproduce
Try to add coolant to a mass spectrometer.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
Tested and can confirm this is an issue. Possibly an upstream bug, too.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
