### ISSUE TITLE
Transform (Change Species and Taur) removes NIFs

### ISSUE THREAD

**Issue by Burrito-Justice** [VOREStation/VOREStation#3003]
#### Brief description of the issue
Getting transformed will apparently remove your NIF entirely.

#### What you expected to happen
For my hooman character to have a tail and keep their NIF.

#### What actually happened
My hooman got a tail but their NIF somehow disappeared, requiring an ahelp.

#### Steps to reproduce
- Own a fully initialized NIF
- Get TF'd on the Change Species and Taur setting
- Lose NIF and be disappointed (might take a bit)

#### Code Revision
- f9feb190c403c43650399fb5a4558187d5d155be
 
#### Anything else you may wish to add:
- The NIF tab was still there for a bit, but all of the programs were gone. The tab then shortly disappeared.

**Comment by Arokha** [comment]
Because it removes all your organs and recreates them to match the parent species, tis the only way.
