### ISSUE TITLE
Microwave losing NOREACT flag after being broken/dirtied

### ISSUE THREAD

**Issue by Jwguy** [VOREStation/VOREStation#3009]
#### Brief description of the issue
When placing ingredients into the microwave, the ingredients are supposed to be stored separately -- that is, they should not react to each other as if you were mixing them. This is essential for some recipes, such as Cakes which require both flour and egg yolk in the same microwave.

As of late 02/05/18, this was working normally. However, user `A thingy#9728` on discord reported in the `#development` channel on 02/09/18 that the microwave was not making lime cakes. We initially believed he was using the wrong recipe due to confusion with the VIRGO wiki showing Baystation recipes, but after testing the issue, it appears that placing egg yolk and flour into the microwave causes a reaction which produces dough... something that should only happen when placed into containers other than the microwave.

EDIT: Further testing in `#development` shows that this is due to microwaves losing the `NOREACT` flag after being dirtied or broken, and not regaining it after being cleaned or repaired.

#### What you expected to happen

Place the following ingredients in the microwave:

5 units Milk, 15 units Flour, 5 units Sugar, 9 units Egg Yolk, 1 Lime

and make a cake.

#### What actually happened

Placed all the ingredients in up to the Egg Yolk, but upon adding egg yolk, it produced dough, which popped out of the microwave.

#### Steps to reproduce
Introduce dough and egg yolk to the microwave.

#### Code Revision
f9feb190c403c43650399fb5a4558187d5d155be
 
#### Anything else you may wish to add:
- Further discussion in `#development` reveals loss of the `NOREACT` flag being the issue.

**Comment by Arokha** [comment]
Already fixed on Polaris, will be fixed with next sync.
