### ISSUE TITLE
ED-209's can only be accessed by Security

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3011]
The Research Director and Robotics, the people who build the ED's, can't actually change their settings.  I figure that the people who put the ID panel ON the robot should be able to make it not shoot bystanders that swap their ID around for a moment, or anyone that tries to pull-adjust it a few squares.

#### Revision
release - 
f9feb190c403c43650399fb5a4558187d5d155be 
 
#### Anything else you may wish to add:
Nobody ever makes these things they suck

**Comment by Cyantime** [comment]
Not a bug, this is also true of securitrons.

**Comment by Arokha** [comment]
Sort of important to not allow non-security to be able to just turn them off.
