### ISSUE TITLE
EAL implant and translator earpiece missing from loadout screen

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#3013]
#### Brief description of the issue
Both the EAL implant and translator earpiece seem to be missing from the loadout options

#### What you expected to happen
Talk in EA when i selected to use it

#### What actually happened
Can't speak it do to lacking the implant... and cant have the implant as it is missing

#### Steps to reproduce
- (Step 1)
Check my load out
- (Step 2)
See the option for EAL implant is missing in the utility tab, then also see translator earpiece missing from earwear tab.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 f9feb190c403c43650399fb5a4558187d5d155be 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by HzDonut** [comment]
The translator being removed was on purpose, not sure about the EAL implant though. Some say that was removed on purpose too.

**Comment by Techtypes** [comment]
Will if EAL implant was... kind of annoying for me as I normally work robotics.

**Comment by Screemonster** [comment]
See discussion in #2972, not an error.

**Comment by Techtypes** [comment]
well that answers that and less then happy with the answer.
