### ISSUE TITLE
Prey deleted when in borg bellies and the borg goes to charge

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#302]
Reported in chat. Not tested myself.

#### Brief description of the issue
If someone is held in a borg's stomach and the borg then enters a charging pod, the prey is deleted.

#### What you expected to happen
Prey to be held inescapably in churny synthetic robotum.

#### What actually happened
The prey got poofed into ghostchat.

#### Steps to reproduce
Be borg.
Eat someone.
Go charge.

**Comment by SpadesNeil** [comment]
@Leshana @Arokha or @Cameron653 please fix this.

**Comment by Cameron653** [comment]
Still looking into the issue, but from what I'm told, this happens:

When a borg releases a player (or they OOC escape) while in a charger, it adds them to the charger contents. The player was fine and could've been admin-teleported out of it, but someone deconstructed it trying to get them out.

If this _is_ the case, then this isn't really an extreme bug, but is still a moderate one.

Can probably go and fix it by adding a check to the borg belly and/or the OOC escape so they can't be let out while in the contents of a cyborg charger.

**Comment by SpadesNeil** [comment]
Closing, then.
