### ISSUE TITLE
AI Hardlight nom has the potential to delete people.

### ISSUE THREAD

**Issue by Potato-Masher** [VOREStation/VOREStation#3022]
**Description:**
So, an interesting one. Me and two others decided to circumvent the AI one person vore limit, and I swallowed person A while she had eaten person B. They were now both inside me, and person A released person B. Upon me releasing them, only person A appeared, and person B's body was deleted entirely.

**What you expected to happen:**
To be honest, I saw it coming. Best I hoped for was for both of them to appear.

**What actually happened:**
Person B's body never appeared. He then told us what happened in LOOC, and his name was now his BYOND username.

**Steps to reproduce:**
1 - Be AI.
2 - Eat someone that has eaten someone else.
3 - Have the person release the other one while inside of the AI's hologram.
4 - Eject person, only to have one appear.

**Comment by Screemonster** [comment]
You decided to deliberately fuck around to break the game, and the game broke. Congratulations, I... guess?

Filing this as "minor" because reproducing it requires circumstances that should never appear in normal play unless you're deliberately fucking around.

**Comment by SpadesNeil** [comment]
Now Scree, that is how bug testing works. :P

**Comment by KonBear** [comment]
Actually this legitimately happened on a scene I had when I first came to the station (got ate by a Borg, borg got ate by the ai, escaped from the Borg then poof) so yes it does happen without the intention of breaking the game :P

**Comment by Potato-Masher** [comment]
We were just attempting to see if we could get around the noticeable "one person only" restriction with hardlight; we never had the intention of breaking anything (or deleting people for that matter). And as with KonBear, yes, this does have the potential to happen under normal circumstances.

This can be avoided as long as person A does not let person B out, however. Person A upon being released from the AI will still have person B within them, allowing for a safe release.

Two fixes for this would either be:

1.  Go the fun route and improve hardlight nom functionality to be more robust.
2.  Go the less fun route and disallow the use of hardlight on people that contain others.
