### ISSUE TITLE
Pets give their "friend" messages to people in their stomachs.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3025]
#### Brief description of the issue
If your pet eats you, and you subsequently become friends with it, it'll still give the friendly emotes of nipping and rubbing against you and so on even while you're squirming and shoving around inside it.

#### What you expected to happen
Messages to stop.

#### What actually happened
Messages do not stop.

#### Steps to reproduce
- Be micro CMO/Colony Director.
- Get ate by your own pet.
- Befriend pet with the verb.
- Watch the friendly messages tick up your chatbar as if you were outside standing next to them.

#### Code Revision
- Server revision: stopkillingthedamncat - 2018-02-12
7a62aec59788fc607c410a47ee22f4d6be2c03b4

(branch for another open PR)
 
#### Anything else you may wish to add:
- probably resolvable by an isturf(loc) check on the friend/food as it'll return false if they're in a stomach.

**Comment by LittleBigKid2000** [comment]
Technically they _are_ rubbing against you.
