### ISSUE TITLE
AI on Virgo-4 is nonfunctioning

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#3029]
#### Brief description of the issue
95% of the time, taking a trip to Virgo 4, the lovely beach world, you will find the AI just standing around. Fennecs can still pounce, but only if you walk into and under them. Snakes do not eat micros, and 20+ trips have seen no giant snakes spawning. Hostile mobs are unaffected in the cave. (The hostile mobs in the cave do respawn instantly, however)

#### What you expected to happen
To not go to the beach and be on a creepy wax museum of fennec-friends.

#### What actually happened
I was able to capture every fennec in the bar, and turn it into a bark bar.

#### Steps to reproduce
Fly shuttle to Virgo 4.
Take pictures of statue fennecs

#### Code Revision
f9feb190c403c43650399fb5a4558187d5d155be
 
#### Anything else you may wish to add:
Natje is amazing for making the fennec hyper-active sometimes. <3

This bug can, rarely, effect Virgo-2 and make the hivebots not function, but I've only seen that once.

**Comment by Mewchild** [comment]
Hostile mobs in the cave are affected sometimes, from personal experience. I've managed to get them functional, on both the caves and Virgo-2, by attacking one of the mobs. This causes it to retaliate, and all mobs will attack as normal from then out

**Comment by Screemonster** [comment]
Possibly related to the system that turns mobs off when nobody's around failing to re-activate them when someone arrives?

**Comment by Rixunie** [comment]
Possibly. In my testing on a private server, I couldn't replicate it. It seems to only happen on the actual server.

**Comment by Rixunie** [comment]
Addendum; Attacking the non-hostile mobs does not actually fix their AI. I have been able to kick every single fennec to death, including the respawned ones, with no reply. Same for the sneks.

**Comment by Mewchild** [comment]
@Screemonster That's what Natje was telling me, when we encountered it in round some days ago, for the first time.

**Comment by Arokha** [comment]
Can't replicate it. Fennecs move around when I get there. I should mention observing is not a valid test for this, since animals won't be active until a player IN A BODY is on that z-level.

**Comment by Verkister** [comment]
Was on an expedition where this happened a little while ago. All the mobs at beach were inactive. Not entirely sure if one fennec activated on spawn after its predecessor got killed. The hostile mobs in the cave were inactive at the start as well, but retaliated after getting attacked, and the respawned ones from their spots started out active. Something with the first spawner mobs perhaps?
