### ISSUE TITLE
Dorms need either a lock or an occupied sign.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#303]
#### Brief description of the issue
I've been ghosting over the dorms for literally five minutes and seen three scenes get walked in on 'cause the other party (who was looking for an unoccupied one) had no way of telling which ones were taken.

#### What you expected to happen
Door locks like the old station, or at least an occupied sign like Surgery.

#### What actually happened
Testing every door like the stalls in a busy restroom until you find one that's unoccupied.

#### Steps to reproduce
Go to dorms.
Stroll in awkwardly upon a couple wherein one is waist-deep inside the other (facing doesn't matter)
Make awkward excuse and back away. Repeat in next dorm.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Waiting on https://github.com/VOREStation/VOREStation/pull/292 before I do any more map changes.
