### ISSUE TITLE
Cargo shuttle's conveyors aren't connected to the cargo switches?

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3031]
#### Brief description of the issue
Cargo shuttle's conveyors don't work.

#### What you expected to happen
For all the conveyors to turn on when the switch is flipped

#### What actually happened
Only the conveyors on the station turn on, the cargo shuttle's conveyors stay off.

#### Steps to reproduce
- (Step 1)Be in cargo
- (Step 2)Call the shuttle
- (Step 3)Wait
- (Step 4)When the shuttle arrives, turn the switches for the conveyors on
- (Step 5)Set all your cargo on the belts
- (Step 6)Realize they are all moving, except those on the shuttle.

#### Code Revision
- release - 
f9feb190c403c43650399fb5a4558187d5d155be

**Comment by Arokha** [comment]
The IDs are set correctly on these in the dmms, I suspect it's due to the maploader unsetting the id var or something.

**Comment by MrSign** [comment]
Reeeee!

**Comment by Leshana** [comment]
I know what is broken.  I will work on fixing it sometime.
