### ISSUE TITLE
Infinite Creation of Deuterium

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3033]
#### Brief description of the issue
With 5 hydrophoron in a beaker, and a sink, you can produce infinite quantities of deuterium at a sink

#### What you expected to happen
For construction materials and RUST fuel to not be freely available. I feel a small amount of hydrophoron should be consumed in the reaction.

#### What actually happened
Infinite ingots are produced. This can be used as a construction material, used to make knives, beds, etc, and can be used as fuel for the RUST engine.

#### Steps to reproduce
Add 5u Hydrophoron to a beaker (Hydrophoron being 1:1 Hydrogen and Phoron)
Set transfer amount to 10u
Spam click a sink and pile up 400+ sheets of deuterium

#### Code Revision
f9feb190c403c43650399fb5a4558187d5d155be 
 
#### Anything else you may wish to add:
https://i.imgur.com/rOKy9EF.png

**Comment by aztectornado** [comment]
TBH right up until I found out you could make walls entirely out of it, it was always just a fun little quirk to make random baubles out of fusion fuel, including the above 'bracelet chainmail sleeve'.

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/4830

**Comment by aztectornado** [comment]
This was fixed in the latest pull from Polaris
