### ISSUE TITLE
No warning for character limit in Say/Me

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#3046]
#### Brief description of the issue

When typing out particularly long posts in scene, there's no warning that you've reached character limit, nor any way to retrieve whatever you wrote past this invisible limit either, which I feel is too short for an RP server anyway.

#### What you expected to happen

The server would warn me when I went over that amount, or else spit it back out in a user-only message

#### What actually happened

The say message abruptly ends mid-word and doesn't allow you to easily copy-paste the remainder to your partner

#### Steps to reproduce
- Be verbose in a say/me
- Like really verbose. Really describe a lot.
- Hit enter
- Be disappointed.

#### Code Revision
- 67c7641d36ec5c12305d218aa4730c684703a1c7
 
#### Anything else you may wish to add:
- I get this way too often. I feel like the limit should be a bit higher instead of just-... Not. If not a limit change, then it'd be nice to have the message copy-pastable somehow again so I could break it up into byond-size chunks

**Comment by Screemonster** [comment]
If you're typing it into the command line just hit ctrl-up and your old message will be there again. Then delete everything between say/me and the cutoff point and hit enter again.

**Comment by aztectornado** [comment]
Fair, I should stop being a hotkey scrub

**Comment by SpadesNeil** [comment]
Still annoying.

**Comment by Arokha** [comment]
There's no possibility to add a warning. It can echo the message back at you so you don't lose it, though.

**Comment by aztectornado** [comment]
That's what I'd prefer, yeah
