### ISSUE TITLE
Explorer Shuttle's airlock problem

### ISSUE THREAD

**Issue by KonBear** [VOREStation/VOREStation#3049]
#### Brief description of the issue
The airlock pressure will reduce to absolute zero.

#### What you expected to happen
To stop once it is equal pressure to the outside.

#### What actually happened
It will lower to a vacuum no matter what the pressure is outside, forcing a unnecessarily long wait time and pop anyone inside without the proper suit. 

#### Steps to reproduce
- try to leave via airlock
- wait an hour while it does it's shenanigans
- explode into a gorey mess as you forgot to put on a space suit to go outside...

#### Code Revision
- f9eb19
 
#### Anything else you may wish to add:
- I'm calling space OSHA... and a janitor to clean up explorer bits ☻

**Comment by KonBear** [comment]
F9feb19 * dropped the f from the code revision

**Comment by Jakksergal** [comment]
It cycles to 0 kPa to better accept non-Terran atmospheric conditions. e.g. If it cycled to the same pressure as the exterior, it wouldn't care if the exterior was 100% phoron or not. Granted this is kinda annoying in environments where the exterior atmosphere is acceptable but in that case you should probably just use the cargo door or force the exterior doors open.

**Comment by Arokha** [comment]
This is by design.

This is how the airlocks purge atmosphere, like if you land on a phoron planet. They have to dump the airlock atmosphere back outside the ship.

**Comment by Arokha** [comment]
> the cargo door

Or just that door on the left side.

**Comment by Jakksergal** [comment]
Only scrubs use that voidcraft door. Double Door all the way!

**Comment by KonBear** [comment]
Apparently it's a feature. Put on your suits lads or be brought home in bags.

**Comment by KonBear** [comment]
Oh whoops the comments came up after I closed it... reopen this to let folks that actually do the organizing close it if they want.
