### ISSUE TITLE
Catwalks bugging pipes.

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#3052]
#### Brief description of the issue
Any pipes that are supposed to start wrenched down under catwalks doesn't. 
https://cdn.discordapp.com/attachments/187013248309002240/414508764214067200/unknown.png
https://cdn.discordapp.com/attachments/187013248309002240/414508840722104320/unknown.png

#### Code Revision
Server revision: master - 2018-02-13
ad6015b108e22eea35fd5f02de980a82a118cda2

**Comment by Arokha** [comment]
Duplicate of #2738
