### ISSUE TITLE
All but 3 preview backgrounds missing.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3064]
#### Brief description of the issue
-Preview background rotation has been reduced to only black void, grey tiles, and white tiles. White void, dark plating, maint plating missing unless I'm failing to recall even more of them.

#### What you expected to happen
-To be able to see how badly my character might camouflage against more than 3 environments.

#### What actually happened
-Only black void, greyfloor, and whitefloor available.

#### Steps to reproduce
- (Step 1) Open character setup.
- (Step 2) Press "Cycle background" button as many times as you feel like.
- (Step 3) Taste some frustration.

#### Code Revision
0e57ff395fd04c78fceaf788e022e8989641fc38
 
#### Anything else you may wish to add:
- Who be messing my additions for no good reason :v

**Comment by Arokha** [comment]
`var/list/bgstate_options = list("000", "fff", "steel", "white")`

I mean. Those other ones you listed don't have any code to show up. So they aren't MISSING. Just ... aren't coded in to show up.
