### ISSUE TITLE
Open space visible with mesons, energy netted people can't go down stairs, they float.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3073]
#### Brief description of the issue
Right as it says in the title.

#### What you expected to happen
I wouldn't be able to see open space and I could move people downstairs either by pushing or pulling.

#### What actually happened
I can see 'open space' tiles and people I try to move down stairs just float on the z-level i'm on.

#### Steps to reproduce
For mesons:
- Find open space
- Put on mesons
- Turn them on
For the energy net:
- Net somebody
- Try to push/drag them down stairs
- Watch them float

#### Code Revision
- release - 
c442cb00219e0cca228498d548abb3a4a8ac6c05 
 
#### Anything else you may wish to add:
- https://imgur.com/a/jZm76
- https://imgur.com/a/CyHmR
- https://imgur.com/a/O9Uhp

**Comment by Arokha** [comment]
The mesons thing is a feature so you can find open areas overhead. That's on purpose.

The net thing probably affects more than just nets, like other buckle-able objects to some extent. I know cargo tugs have a problem.

**Comment by SpadesNeil** [comment]
Please keep unrelated bug reports in separate issue posts.
