### ISSUE TITLE
Vox can't take Simple Webbing or they choke

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3092]
#### Brief description of the issue
Somehow, spawning with simple webbing (and possibly other untested loadout items) makes Vox spawn without their primary canister in-hand.

#### What you expected to happen
To appear outside the tram with my full phoron canister as a Vox and my loadout items equipped.

#### What actually happened
I joined in with no tank or internals set and taking toxin damage.  The tank was found far to the southwest, alongside the tracking implant I was supposed to have.  

#### Steps to reproduce
-Create a Vox
-Equip Simple Webbing (Accessory tab, two points)
-Choke on crappy dusty air instead of inhaling glorious, disinfected plasma

#### Code Revision
release - e9e25a7b9f4675d229fe1cb5d37c7eb70d591013 

#### Anything else you may wish to add:
The 'person has joined the station' messages sure love to spam if you need to rejoin when anything breaks.

**Comment by Arokha** [comment]
Slightly helped by making sure all players spawn ON their spawnpoints THEN get gear. At the very worst, you'll end up with the phoron tank UNDER you. This may have also been fixed by all the accessory changes.
