### ISSUE TITLE
Medihounds can't select adv health analyzer when upgraded with it.

### ISSUE THREAD

**Issue by Sebbe9123** [VOREStation/VOREStation#3095]
#### Brief description of the issue
When upgraded with the advanced health analyzer upgrade it shows up in the inventory but completely unselectable except for in the "panel" menu.

#### What you expected to happen
Click the nice sprite and select the module without a problem

#### What actually happened
Clicking as much and as hard as I can without having it move to the active modules.

#### Steps to reproduce
- (Step 1) spawn as medihound
- (Step 2) ask roboticist for scanner upgrade
- (step 3) get scanner upgrade but unable to select it in the "inventory" menu only selectable through the "panel" menu.

#### Code Revision
e9e25a7b9f4675d229fe1cb5d37c7eb70d591013 
 
#### Anything else you may wish to add:
N/A

**Comment by Cyantime** [comment]
Fix is already up on Polaris, applies to all borg types.

**Comment by Arokha** [comment]
PR to fix is here: https://github.com/PolarisSS13/Polaris/pull/4913

**Comment by Arokha** [comment]
Fixed by sync
