### ISSUE TITLE
Protector lethal mode isn't locked to Blue+

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3102]
#### Brief description of the issue
The KHI Protector handgun is a security sidearm that only allows lethal fire on code blue or higher. The alert lock is non-functional

#### What you expected to happen
An error is given by the weapon upon pulling the trigger in code green, while on lethal firing mode.

#### What actually happened
The weapon functions as a regular energy gun, with twice the ammo and no alert lock. As of right now, it is a direct upgrade to the energy gun.

#### Steps to reproduce
- Be in Code green, have a protector set to lethal firing mode.
- Observe your pew pews

#### Code Revision
e9e25a7b9f4675d229fe1cb5d37c7eb70d591013
 
#### Anything else you may wish to add:
https://i.imgur.com/PIPgNvN.png
Alert level can be seen on the fire alarm.

**Comment by Arokha** [comment]
Unuuuusual.

**Comment by Arokha** [comment]
Fixed in #3103
