### ISSUE TITLE
Synths don't get goggles in their box

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3109]
#### Brief description of the issue
I opened the gift that someone left in my bag and there's only an empty air tank in there

#### What you expected to happen
I asked for goggles

#### What actually happened
![wut](https://user-images.githubusercontent.com/24854483/36603372-8982f366-1888-11e8-8f28-522daae14ad6.png)

#### Steps to reproduce
- (Step 1)Be some kind of robot
- (Step 2)Join the round
- (Step 3)Look in box

#### Code Revision
- release - 
e9e25a7b9f4675d229fe1cb5d37c7eb70d591013
 
#### Anything else you may wish to add:
- I think Aro's adding new boxes in the next release, so this might be entirely irrelevant in a few hours

**Comment by Arokha** [comment]
That's. Odd.
