### ISSUE TITLE
Communicator

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#311]
#### Brief description of the issue
Dunno if this was reported on Polaris already. But communicators are pretty bugged right now. At least the calling function. Calling someone as a ghost, you are unable to see your own messages or other peoples messages. However the other side receives every single message.

Same with normal calling. Apparently only me commands go through.

#### What you expected to happen
To have a proper call and have my say commands go through.

#### What actually happened
I didn't get to see anything....

#### Steps to reproduce
Ghost -> Call somebody -> Try to speak
Join as a character, any job. Call somebody. And try to speak. Or have them say something

#### Additional info:
Server revision: release - 2016-06-04
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
It's actually that the communicator at the other end doesn't receive what they are saying. As in, the living person holding the communicator says stuff out loud, and that stuff does not reach the communicator. It's a bug with the communicators being held. If they set it on a table and stand next to it and talk, it should work fine.

**Comment by Arokha** [comment]
Guess I shouldn't label it a bug twice huh.

**Comment by Repede** [comment]
That bug might explain why the tape recorders also don't work if the person has it on their person.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
