### ISSUE TITLE
Ate a dead diona nymph and was unable to move or do anything for a short period of time

### ISSUE THREAD

**Issue by Alcastar** [VOREStation/VOREStation#313]
#### Brief description of the issue
When eating Diona Nymphs a nameless, invisible entity grabbed me and I was not able to move for a few seconds, even resisting and breaking the grab does nothing. This happened every time I ate a nymph.
#### What you expected to happen
to eat a dead diona nymph
#### What actually happened
Ate a dead diona nymph and was unable to move or do anything for a short period of time
#### Steps to reproduce
Grow a Diona in the park, or possibly anywhere, and eat the nymph after it dies.
#### Additional info:
Server revision: release - 2016-06-04

**Comment by SpadesNeil** [comment]
That's... odd.
