### ISSUE TITLE
digesting organics as a promethean doesn't kill you

### ISSUE THREAD

**Issue by Dankman** [VOREStation/VOREStation#3135]
#### Brief description of the issue
most organic carbon based life on the station is like 60% water, so with the new mechanics of ingesting water damaging prometheans, one would assume that digesting a player should murder the shit out of you

#### What you expected to happen
the scene where the dude gets the dip from who framed roger rabbit 

#### What actually happened
urp

#### Steps to reproduce
- (Step 1)become slem
- (Step 2)find seraph
- (and so on) urp

#### Code Revision
current 
 
#### Anything else you may wish to add:
this change is dumb and completely breaks my immersion.

can't drink water but i can drink cola and coffee and tea, tea is just water that's had some leaves in it for a bit, but it's magically okay.

**Comment by Arokha** [comment]
Do not open meme issues.

**Comment by SpadesNeil** [comment]
Told you I'd block you if you kept acting like a twat.
