### ISSUE TITLE
Button near gateway doesn't work

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3147]
#### Brief description of the issue
- Button near gateway, downstairs part, doesn't work

#### What you expected to happen
- Pressing it should open shutters to gateway and ones blocking the stairs floor up

#### What actually happened
- Nothing

#### Steps to reproduce
- Press the button
- Be disappointed

#### Code Revision
- 22568ffdf997493f46ae28b3f572e793e53a3899 
 
#### Anything else you may wish to add:
- Button located near gateway itself, second floor. Not one of three in prep upstairs.

**Comment by aztectornado** [comment]
Gateway is inactive in the code right now, but yeah this is weird.
