### ISSUE TITLE
Promethians age locked to a limit of 5, head positions requiring age of at least 25

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#315]
#### Brief description of the issue
name of the issue says it all. Promethians by this rule cannot be heads, many in the forums feel both of these locks should be removed. as shown http://forum.vore-station.net/viewtopic.php?f=20&t=698
with the new change adding more restrictions to existing characters seems like a step backward for a heavily RP based server with already established characters that fall beyond these limits.

#### What you expected to happen
simply that it would not be the case  

#### What actually happened
as seen above

#### Steps to reproduce
create a character

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
Locking players out of head roles completely is a pretty big bug. I'll see about fixing this later.

**Comment by Cameron653** [comment]
Resolved by #316
