### ISSUE TITLE
Borgs with drone brains spawn with a dropped crew synth drone ID

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3166]
#### Brief description of the issue
-Borgs without squishy or positronic brains spawn with a crew synth drone ID card on the floor.

#### What you expected to happen
-The system to not automatically try to equip borgs with player synth accessories.

#### What actually happened
-The system tried to put the drone ID accessory onto my borg's uniform and failing clumsily.

#### Steps to reproduce
- (Step 1) Select drone chip brain for your dedicated borg synth char.
- (Step 2) Join the game as a borg.
- (Step 3) Litter the floors awkwardly with shit you shouldn't have that you cannot pick up either.

#### Code Revision
- 6685d93b2ba640d244badb8e29336dd675c00c7b
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/4996
