### ISSUE TITLE
Prey cannot hear the pred's gurgles from inside.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3173]
#### Brief description of the issue
While otherwise audible in the same way as before (although hella quiet) the gurgles cannot be heard at all from inside the pred. You can hear them as the pred, next to the pred, on top of the pred, and after your spiritual remains ascend out of them, but not at all while you are inside.

#### What you expected to happen
For the prey to hear those noises especially well from their perspective.

#### What actually happened
Mime convention.

#### Steps to reproduce
- (Step 1) Get ate.
- (Step 2) Get gurgled.
- (Step 3) Hear absolutely nothing while getting gurgled.
- (Step 4) Become a burp ghost.
- (Step 5) Hear your crap still churning about ~~loud~~ and clear now.

#### Code Revision
- 7d899aeb7f6cfc60cb51726c36688e91abc14042
 
#### Anything else you may wish to add:
- Also hunger noises are MIA right now.

**Comment by Arokha** [comment]
Curious, this is one of the things I tested (by eating Briana of course) while rewriting bellies. I wonder when it got broken.
