### ISSUE TITLE
Intercoms have inversed direction

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3179]
#### Brief description of the issue
- All intercoms facing right and left have their sprites face opposite direction

#### What you expected to happen
- Sprites face from the wall to the person

#### What actually happened
- Sprites face the wall: https://prntscr.com/imtkvy

#### Steps to reproduce
- Find any intercom on the wall that faces right or left
- Look at it
- It faces opposite of you

#### Code Revision
- 7d899aeb7f6cfc60cb51726c36688e91abc14042
 
#### Anything else you may wish to add:
- Issue seems to be from mapping side.

**Comment by Arokha** [comment]
I think that IS facing the right direction? They look fine that way? I've always interpreted them as the solid bar with red and green lights as being on the 'bottom' of the intercom, which is the way they're all facing.

**Comment by Heroman3003** [comment]
Well, you see, that intercom is on the wall next to the sink, not on the wall next to the charger. So it is upside down, as those lights at the 'bottom' facing 'up' the wall.

**Comment by Heroman3003** [comment]
Update: issue actually only seems to affect intercoms facing west (so when you directly look at them, your character faces east)
