### ISSUE TITLE
Gaslamp (possibly other simple mobs too?) stomachs are broken

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3187]
#### Brief description of the issue
- Got eaten by gaslamp and stomach appeared to be a stock pred stomach rather than gaslamp's internal chamber

#### What you expected to happen
- I get put into internal chamber, with unique messages, description and escape/absorb chance on resisting

#### What actually happened
- I got put into stock stomach with stock messages, description and no escape/absorb chance on resisting

#### Steps to reproduce
- Accidentally hit a gaslamp while cutting down a tree
- Get eaten
- NOESCAPE

#### Code Revision
- 7d899aeb7f6cfc60cb51726c36688e91abc14042 
 
#### Anything else you may wish to add:
- No idea if its that way always or because it was retaliating to my accidental attack, but might be related

**Comment by Heroman3003** [comment]
They also appear to not nom you when you just walk under them.

**Comment by Arokha** [comment]
This is fixed in master, just not updated yet.
