### ISSUE TITLE
Teshari hide broken

### ISSUE THREAD

**Issue by JemliRoivas** [VOREStation/VOREStation#3192]
#### Brief description of the issue
Teshari automatically unhide after a certain amount of time

#### What you expected to happen
Remaining hidden underneath a table when hiding

#### What actually happened
Automatically pop out on top of the table after a varying amount of time

#### Steps to reproduce
Hide under a table
Wait

#### Code Revision
7d899aeb7f6cfc60cb51726c36688e91abc14042 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cameron653** [comment]
...I swear I fixed this ages ago. I wonder what made it resurface.

**Comment by KasparoVy** [comment]
Doesn't seem to be something that directly sets 'hiding'.
You also become un-hidden if you pick up/drop anything.

**Comment by Cameron653** [comment]
Hmm, relevent section of code:
https://github.com/VOREStation/VOREStation/blob/de9a37495c98946d2d09845c58c59a3c99e5ed0d/code/modules/mob/living/carbon/human/human.dm#L1568-L1578

**Comment by KasparoVy** [comment]
On a local test instance I threw a debug message under the `stat`/incapacitation check but that did 't seem to be getting triggered when the teshari was unintentionally revealed. Pretty confusing, but will check again

**Comment by KasparoVy** [comment]
I tested the `stat`/incapacitation check with a debug message yesterday but it wasn't getting triggered when the Teshari was getting revealed by the bug.
I'll double check

**Comment by KasparoVy** [comment]
Wow alright, I think I see what it is. Bahaha. Excellent
