### ISSUE TITLE
Diona Whitelist bugged

### ISSUE THREAD

**Issue by Airusish** [VOREStation/VOREStation#3202]
#### Brief description of the issue
I, (ckey: Aruis) am unable to create a new Diona character in the character setup screen, though I've been approved about a year ago.

#### What you expected to happen
I expected to be able to create a new Diona character without a popup telling me I need to be whitelisted first.

#### What actually happened
When attempting to create a new Diona character, a popup told me that I must be whitelisted for the species, which I was.

#### Steps to reproduce
- (Step 1)
In "Setup character," change the species of any slot to Diona
- (Step 2)
Close whitelist popup

#### Code Revision
- 7d899aeb7f6cfc60cb51726c36688e91abc14042 
 
#### Anything else you may wish to add:
- One of my saved characters is a Diona, created prior to this problem. Even though I'm unable to make new Diona, I can play as this one.

**Comment by Screemonster** [comment]
https://forum.vore-station.net/viewtopic.php?f=46&t=628

Approval thread here.

**Comment by Cyantime** [comment]
You aren't on the whitelist for diona, https://github.com/VOREStation/VOREStation/blob/master/config/alienwhitelist.txt. It isn't a bug
