### ISSUE TITLE
Sign Language key is broken

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3209]
#### Brief description of the issue
Sign language, unlike all other languages, cannot presently be used without swapping it to be your default language.

#### What you expected to happen
say ",s Heckie

To make me say "Heckie" in sign language

#### What actually happened
The character said ",s Heckie"

#### Steps to reproduce
- (Step 1)Have sign
- (Step 2)type ,s before a message as with other languages
- (Step 3)confuse your friends

#### Code Revision
- release - 
377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14
 
#### Anything else you may wish to add:
- Shadekin empathy also uses ,s for its key. I'd suspect there being some kind of conflict there. If I might make a suggestion for a new key for empathy, I'd say ,m

**Comment by KasparoVy** [comment]
m-pathy.

**Comment by Very-Soft** [comment]
medical is :m
