### ISSUE TITLE
catgirl inflates with air instead of people

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3215]
#### Brief description of the issue
Catgirl tried to eat me. Pinned me down. Got the vore belly message. Still free

#### What you expected to happen
to be a belly stuffer for the rest of my life

#### What actually happened
cat girl stuffed its self with air

#### Steps to reproduce
- (Step 1) get grabbed by cat girl
- (Step 2) get eatten by cat girl
- (step 3) Watch cat girl inflate from outside

#### Code Revision
- 377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14 
 
#### Anything else you may wish to add:
I was next to another player, if that does anything

**Comment by Screemonster** [comment]
We're vorestation, not inflationstation - although I swear to god that sounds like it should be the name of an early-2000s website for this sort of thing. Gif thumbnails. Default html borders around all the image links, blue for ones you haven't visted, purple for ones you have. Some fuckin' "web ring" link at the bottom and that icon of a ball with a purple lightning bolt going around it that I never bothered looking to see what it was. Slightly too professional to go quite as far as stock skull gifs but the page still probably has a vaguely tiled background that gives the whole thing a "windows 3.1 desktop" look.
