### ISSUE TITLE
Synth Radiation Repair is counter-intuitive

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3221]
#### Brief description of the issue
The system instability on synthetics, caused by radiation damage, is rather hard to notice in low levels, and repairing it is a time-sink that is both unenjoyable and non-interactive for any crew

#### What you expected to happen
Get notes about losing motor control, falling over, and the like- and report to robotics for repairs, much as an organic crew member would go to medical. Perhaps disconnecting and re-attaching the synth's brain could repair it (turn it off and back on again), or some other similar "surgery"

#### What actually happened
Sit in a recharger for 15 minutes, and watch a youtube video

#### Code Revision
377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14

**Comment by Arokha** [comment]
15 minutes? You would need more than 400 radiation for it to take 15 minutes. That level would be instantly fatal to organics.

**Comment by Mewchild** [comment]
The point still stands. Organic crew can go to medical, and get one of several medications via injection for radiation. It's an involved process, that makes use of other crew. Synths go sit in a recharger, and are removed from other people.

**Comment by TheDavestDave** [comment]
Rads still do burn damage to synths aswell. And it isn't clear to new players how to fix it. A lot of robotcist have no idea how to fix it. It makes no logical sence that sitting in a charger magicly fixes it

**Comment by Screemonster** [comment]
System instability is equivalent to toxloss. Apart from your doll no longer saying "100%", toxloss is pretty hard to see in low levels for organics too (and fairly low-impact apart from the occasional nagmessage about itching) and also generally doesn't go away without intervention of some kind. Even 2 points tends to be annoying enough for me to go and find a donk pocket and a microwave just to get rid of it.
Synths taking minor damage and not getting any pain feedback is kinda normal for all damage types.

**Comment by Arokha** [comment]
Plenty of people also just ignore the lack of 100 on healthdoll. I usually have to ask people /if I can fix them/ when I'm medical and they have a few toxins because they don't care and aren't asking to be fixed.
