### ISSUE TITLE
Players see admin's character

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3222]
#### Brief description of the issue
- When player is pmed by admin, they see their character's name in ()

#### What you expected to happen
- Just admin's byond name appears. Only if you're an admin can you see name next to pms.

#### What actually happened
- Byond name with admin's current character in () even if you're regular player/=.

#### Steps to reproduce
- Get pmed while not admin
- Observe

#### Code Revision
- 377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14 
 
#### Anything else you may wish to add:
--------

**Comment by Mewchild** [comment]
But without this, I would never know of Natje and EATS-THE-ASS

**Comment by KasparoVy** [comment]
Lmfao, that's an excellent example.
