### ISSUE TITLE
The Elevator closes slowly.

### ISSUE THREAD

**Issue by AeroWing** [VOREStation/VOREStation#3224]
#### Brief description of the issue
Found a typo in the centcomm elevator.

#### What you expected to happen
Enter the lift and get a message to confirm this.

#### What actually happened
Get shamefur dispray typos.

#### Steps to reproduce
- Enter elevator
- Read feedback message
- Feel 'muh immersions' get broken by typos.

#### Code Revision
- 377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14
 
#### Anything else you may wish to add:

![comercial](https://user-images.githubusercontent.com/5162034/37303758-721e286c-25fd-11e8-8dc2-e453343c96b2.png)
'Commercial'
This elevator was not an 'uplifting experience'

Should read 'The elevator door closes slowly. You can now head for residential, commerical, and several other floors.'

**Comment by KasparoVy** [comment]
Full stop after slowly

**Comment by AeroWing** [comment]
Full stop after slowly to you, too.

**Comment by KasparoVy** [comment]
Lmao I meant the message, but that works too 😆
