### ISSUE TITLE
Rolling Papers have issues

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#3231]
#### Brief description of the issue
The rolled joint sprite is broken pretty badly, and shows up as the generic HONK error sprite 

Also rolling papers are Normal sized, and can't be put back in their package

#### What you expected to happen

I'd see my fancy healing smoke as a proper joint, and also be able to put the papers back in their case if I change my mind

#### What actually happened

https://i.imgur.com/lNL7AIn.png

#### Steps to reproduce
- Get something dried and smokable
- Apply to a rolling paper
- ??HONK??

#### Code Revision
- 377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14 
 
#### Anything else you may wish to add:
- Healing smokes are cool, maaan

**Comment by Arokha** [comment]
Fix already merged
