### ISSUE TITLE
Can't examine your pred anymore

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3236]
#### Brief description of the issue
Until recently, when you were inside someone, via being eaten or whatever, you could examine your pred via right-click->examine.

#### What you expected to happen
To see how my pred looked while full of me.

#### What actually happened
*right-click -> examine*
*nothing*
"Huh?"
*many, many more attempts at examining*
*many, many more cases of nothing*
"NOOOOOOOOOOOOO"

#### Steps to reproduce
- Get ate.
- Right-click examine pred to check their "full belly" message like you've been used to doing since forever, because you're a curious sort.
- Find out you can't do it anymore.

#### Code Revision
- release - 
377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14 

#### Anything else you may wish to add:
- I'm pretty sure it's a side effect of how the new system handles prey location.  And I'm hoping something can be done despite "lol you're inside them you can't see anything but belly", because I always found it neat ta be able ta check my pred's full belly message  :P

**Comment by Arokha** [comment]
code\modules\examine\examine.dm:79
