### ISSUE TITLE
Simplemobs cannot hear silicons speaking otherwise hearable languages.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3238]
#### Brief description of the issue
Simplemobs cannot hear silicons speaking in common while they hear and understand organics speaking it just fine.

#### What you expected to happen
For the mob to understand the common language regardless of the speaker's squishiness.

#### What actually happened
Asterisks galore. Inconvenient communication issues with a borg with no good IC explanation.

#### Steps to reproduce
- (Step 1) Be a slightly more sentient mini event simplemob.
- (Step 2) Get first contact communicating with the crew, silicons also involved.
- (Step 3) Hear and understand the crew speaking common just fine.
- (Step 4) Smash into a language barrier with borgs trying to speak common.

#### Code Revision
- 377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14
 
#### Anything else you may wish to add:
- Was playing an event shenanigans corrupt hound. The thing was somewhat IC appropriate at first but grew inconvenient over time especially with the hound getting fixed up during the round :v

**Comment by Arokha** [comment]
Not just simplemobs, brains can't either (fixed for the 'soulcaught' brain mob by just giving them universal_understands, but don't really wanna do that for all mobs)
