### ISSUE TITLE
Frustrating trolleys

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#325]
#### Brief description of the issue
They REFUSE to latch onto one another. The cargo trolleys are SO frustrating to link up. They start unlinked and you have to link them together;
#### What you expected to happen
I wanted to LINK THEM TOGETHER.
#### What actually happened
They didn't do a single god damn thing and I was stuck with an incomplete tug.
#### Steps to reproduce
1. Get to the tug.
2. Try to connect the trolleys.
3. Become irritated.
#### Additional info:
 - **Server Revision**: release - 2016-06-04
66dde0234607662f93adf2b7195b31dc70b65d62 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

_The sound of a pot of water boiling._

**Comment by JoanRisu** [comment]
When I was checking the code when making vehicles there seems to be a lack of latching-unlatching code for cargo trolleys from what I can see.

**Comment by TheFurryFeline** [comment]
Funny thing: I've figured this issue out as of today. Issue was a simple dir = 4 not being dir = 1 for Cargo's tug and trolleys on asteroid 3. Unless.... This was a different map? All 4 were laid out towards the north, though, right?
