### ISSUE TITLE
Dying by getting crushed by the elevator happens too frequently.

### ISSUE THREAD

**Issue by Treasa729** [VOREStation/VOREStation#3254]
#### Brief description of the issue
If someone falls down the elevator shaft there is nothing they can do but hope people on the elevator listen to comms and don't go to the first floor or hit the emergency stop button. This often seems to not end up happening and the person who fell down the shaft ends up dead.
#### What you expected to happen
For there to be some sort of safety precaution in the bottom of the elevator to prevent people from getting almost regularly crushed. This could take many forms. An alcove at the bottom of the shaft that allows people to avoid the elevator if it goes to the first floor, an emergency override on the bottom floor (possibly in such an alcove) that can open the first floor doors, prevent the elevator from going to the first floor, or both. 
#### What actually happened
People instead seem to get crushed on an almost semi-regular basis. 
#### Steps to reproduce
- End up at the bottom of the elevator shaft
- Call on comms for people to not use the elevator
- Sit and hope everyone was paying attention, unable to do anything beyond that to avoid dying
- Die when someone was distracted for the 5 seconds and killed you as a result
#### Code Revision
 Server revision: release - 
377dea3bd4dfcffbe7bae0d14c7cc36c3cc2ee14 
#### Anything else you may wish to add:
It seems like there is room on the first floor for an alcove to avoid the elevator. In fact, there is an area that is just rock, directly adjacent to the elevator that could presumably be expanded into without interfering with anything else.

On another note with how often this seems to happen, you'd think this might fall into some workplace safety violation territory or something. Granted, the Tether is far from safe, but NT has been sued for privacy stuff such as cameras in the dorms, so it doesn't seem terribly far-fetched.

**Comment by Screemonster** [comment]
Honestly, a maintenance door at the bottom of the elevator shaft would solve most of these sorts of problems.

**Comment by Treasa729** [comment]
That's true, I'd worry some about people wandering through without knowing what the place is and getting crushed though. It seems like the kind of thing that should be engineering access only, and then have a manual override like the medical doors from a button inside the shaft. A normal maintenance access airlock seems like it could end poorly.

**Comment by Very-Soft** [comment]
What if there's just an emergency open button on the bottom floor? Push button and it opens the bottom floor elevator door for 5 seconds?

**Comment by SpadesNeil** [comment]
I think it would be monumentally better if we could have the elevator detect when somebody is in the way and not proceed to crush them.

**Comment by Mewchild** [comment]
I'm doing some map tweaks now to address this

**Comment by Mewchild** [comment]
I've played around a bit, and I think @SpadesNeil solution is going to be the most ideal one. Adding in a maint door in to the bottom cuts a hole in the side of the elevator itself. It seems that only the floor tiles move up and down. While it's functional, it's also... it looks incredibly out of place, having a tunnel there. I feel it'd lead to more problems than it's worth, with people getting left behind in the alcove.

**Comment by Arokha** [comment]
It's a little expensive, given that means every time the elevator moves, we need to scan the contents (and contents of contents (and contents of contents (...))) of the 16 turfs below. Door sure would be cheaper, CPU-wise.

**Comment by KiraAlitruss** [comment]
or you can have a button that opens the lift's doors from within the shaft.

**Comment by KasparoVy** [comment]
Description: "It seems to be recessed into the wall."

**Comment by Arokha** [comment]
It could be done on the map, just keep in mind that anything put in the shaft is liable to get crushed as the elevator lands on it, and buttons are often offset by 32px to the side to be on the floor but appear to be on a wall, so you can't push the button from both sides of the wall

**Comment by SilencedMP5A5** [comment]
what if you doubled up the walls on the side of the shaft it was gonna be on so you cant see it from the other side unless you deconstruct the wall behind it. like this: http://prntscr.com/iw4sel
