### ISSUE TITLE
Scarf changes colors when put as accessory

### ISSUE THREAD

**Issue by SquishyMcDoodles** [VOREStation/VOREStation#3261]
~First off is that wings are not rendering on bodies~, and my scarf seems to be changing colors when I put it on other clothing articles, I'm not alone in this and just thought I'd point it out.

**Comment by Little-119** [comment]
These should probably* be submitted as separate issues

*(I'm not a maintainer)

**Comment by Screemonster** [comment]
Please use the format and report individual issues separately so we can track them.

**Comment by KasparoVy** [comment]
Wings on spawned mobs looks to've been resolved
