### ISSUE TITLE
Synthmorph Naming

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#3264]
#### Brief description of the issue
When you're put into a synthmorph body as a positronic brain and then name yourself, the pop-up that follows does not let you actually cancel or change it. Furthermore, the naming system does not allow numbers.

#### What you expected to happen
To name my character OSI-648 after being put into a synthmorph body.

#### What actually happened
My character was named OSI-, and the pop-up that appeared only had "Ok" with no "Cancel" option.

#### Steps to reproduce
- Join as a posibrain
- Be put into a synthmorph body
- Name yourself something, preferably something with numbers
- Watch as the game asks you to confirm your number-less name without letting you cancel

#### Code Revision
- 9c4a257a7750da6daf08c00dce69e93ef864ae1b
 
#### Anything else you may wish to add:
- N/A

**Comment by aztectornado** [comment]
You can't use numbers in names at all, iirc.

**Comment by Arokha** [comment]
There's a check that's applied to see if you're allowed to have numbers when joining the round. It checks if you're a synth. But I doubt the same thing is applied anywhere else and probably sanitizes the numbers out.
