### ISSUE TITLE
Cave spiders are rebelling against the AI hibernation.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3279]
#### Brief description of the issue
The spiders in the expedition caves are perpetually active and well while the other mobs wait nicely for the explorers to arrive. They also don't like the other mobs and will wreck their helplessly hibernating arses and depleting the spawners on the spot.

#### What you expected to happen
The spiders to have the decency to not take head starts that big.

#### What actually happened
Two (maybe 3?) rogue spiders had independently turned 7 whole cave mob spawners into webbed piles of deadclaws, squished frogs, and other debris.

#### Steps to reproduce
- (Step 1) Observe the caves.
- (Step 2) Find restless spiders.
- (Step 3) Find a breach in their little cave spot.
- (Step 4) Follow a trail of corpse covered on the spot depleted mob spawners covered in webs deeper into the caves.
- (Step 5) Find a single restless spider straddling about at the end looking all smug about it.

#### Code Revision
- b3bdfc841625f7accd4e4c919d29a5f2d449d619
 
#### Anything else you may wish to add:
- Also some new savik dudes there were also restless and seemingly murderized their diyaab buddies at their estate.

**Comment by Arokha** [comment]
This is likely because only the away mission spawners set `low_priority` on their spawned mobs, whereas those are spawned in PoIs.

If you want to make a PR to fix, a simple one would be a //VOREStation Edit on giant spiders where you just add low_priority = TRUE on them

**Comment by SilencedMP5A5** [comment]
they also sometimes crash you horribly when they take over the cave. natje and i can confirm this, they also create **i m m e n s e** lag

**Comment by Arokha** [comment]
Setting low_priority would fix that, as mentioned above.
