### ISSUE TITLE
Legwraps are invisible when worn

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#3285]
#### Brief description of the issue
The legwraps from loadout do not appear on your character sprite when worn.

#### What you expected to happen
I'd appear to be wearing legwraps, instead of being barefoot.

#### What actually happened
I look like I'm barefoot when wearing them

#### Steps to reproduce
- Spawn with black, blue, or red legwraps from the shoes section of loadout
- Wear them!
- Have invisible footwear somehow.

#### Code Revision
- c89b9bfc57445fa2e90f53212c2e734c5dbd35ff 
 
#### Anything else you may wish to add:
- I remember doing something odd when I had to make my fluff defined shoes; I couldn't have the sprite from the worn and item states of the icon in the same file. I wonder if this has anything to do with that, since they're defined in fluff too?

**Comment by KasparoVy** [comment]
Does resting and getting back up make them render? 
Or are they just totally invisibru?

**Comment by aztectornado** [comment]
Tried resting, they're just invisible. Aronai even tried poking them when I ahelped to see if it was a known issue or something.
