### ISSUE TITLE
Mice Don't Go Into Belly

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#3291]
#### Brief description of the issue
Eating a mouse doesn't actually make it go into your belly--it just vanishes.

#### What you expected to happen
To eat a mouse and then either interact with it in the belly or digest it for nutrients.

#### What actually happened
With the belly in "hold" mode, the mouse just vanished. With the belly in "digest" mode, I immediately got a digestion message but didn't appear to gain any nutrients.

#### Steps to reproduce
- Eat a mouse
- Watch as it is either deleted from your stomach or gets digested instantly

#### Code Revision
- c89b9bfc57445fa2e90f53212c2e734c5dbd35ff
 
#### Anything else you may wish to add:
- This might apply to all simple mobs; something similar happened with a juvenile solargrub, but I didn't get to test it much.

**Comment by Cyantime** [comment]
Fixed by  #3295 probably

**Comment by Arokha** [comment]
It was yeah
