### ISSUE TITLE
Observeghosts spawn naked.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3298]
#### Brief description of the issue
Hitting observe and popping into the ingame astral plane now comes with a birthday dress code.

#### What you expected to happen
The ghosts to show up in their preview loadout/job gear as they used to.

#### What actually happened
Showed up completely naked.

#### Steps to reproduce
- (Step 1) Have a character slot with job/loadout gear active in preview.
- (Step 2) Hit observe.
- (Step 3) Streak astrally.

#### Code Revision
- b73b314938674162c5ede8461c4b9e3e63455fe5
 
#### Anything else you may wish to add:
- I _suppose_ this does _fix_ the gear related crashing for ghosts at least.

**Comment by Arokha** [comment]
Unaware of gear-related crashing for ghosts (tesh ghosts could crash people by observing them though). But, uh. I've spawned naked as a ghost for like. A long time.

**Comment by Verkister** [comment]
https://github.com/PolarisSS13/Polaris/pull/5045 I've always had my ghosts spawn with whatever they had on in the setup preview until just recently.

**Comment by KasparoVy** [comment]
Related to #3280
