### ISSUE TITLE
Skrell lack eyes.

### ISSUE THREAD

**Issue by RezRaz** [VOREStation/VOREStation#3308]
#### Brief description of the issue
Skrell's eyes match their skin color, as opposed to being dark grey as they usually are.

#### What you expected to happen
Skrell to have visible eyes.

#### What actually happened
Skrell had invisible eyes.

#### Steps to reproduce
- Create skrellian character.
- Set skin color.
- Wonder why your character lacks eyes.

#### Code Revision
- release - 000de3133ab7ac42724c04bf03b631590a27cf99 
 
#### Anything else you may wish to add:
- Problem seems to have developed very recently.

**Comment by Arokha** [comment]
Err. Eyes never match skin color. There's a separate setting for eye color.

**Comment by RezRaz** [comment]
Skrell have never had an eye color setting due to the species generally having large, dark eyes. The problem isn't that there is no eye color selector, it's that the default eye color just doesn't apply anymore.

**Comment by Arokha** [comment]
Ye, I found the cause, I'll make a PR in a minute.
