### ISSUE TITLE
Powernet issues

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3311]
#### Brief description of the issue
Certain areas are not ran through a breaker/aren't downstream of a subgrid. These areas are places like the cafe, dorms, visitor laundry, pool, and gateway. Areas in question are part of the MASTER powernet, when they should be part of Surface Civilian, alongside botany and the bar

#### What you expected to happen
Setting up sub-networks charges areas as normal, and areas are sectioned off appropriately.

#### What actually happened
Areas listed above tend to enter a power fail state when the department subgrids are charging, and grubs in them drain the station main SMES directly (instead of a subgrid SMES)

#### Code Revision
000de3133ab7ac42724c04bf03b631590a27cf99  
 
#### Anything else you may wish to add:
[Master Network](https://i.imgur.com/uJBJ4Vu.png)
[Surface Civilian](https://i.imgur.com/3C23Nw6.png)

**Comment by Arokha** [comment]
Feel free to map in substations for said areas.

**Comment by Mewchild** [comment]
Damn Aronai. Give the issue a chance to breathe before you jump on it ;P
I'll look into it before deciding if I want to fuck with it. It'd require a rerouting of most wires on the bottom three levels, to route them downstream of surface civilian

**Comment by Ketrai** [comment]
So that's why I get complaints about grubs knocking power down even with subgrids.
