### ISSUE TITLE
Scrubbers not responding from remote control

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3319]
#### Brief description of the issue
Scrubbers won't active nitrous oxide scrubbing mode until I went to fix a door

#### What you expected to happen
be able to set built in scrubber to filter NO from atmos

#### What actually happened
scrubber was SSD

#### Steps to reproduce
- (Step 1)try to set scubber
- (Step 2) wacth it ignore you
-
#### Code Revision
- bc2143410454de3dc7a1a9707b698724921808b9 
 
#### Anything else you may wish to add:
- I tried relogging and that didn't fix it. It only filter after I asked for help moveing things via radio returning for fixing a door. I could turn remote control fully on however.

**Comment by AbbieFland** [comment]
Assuming this is in relation to the current round active while this issue was filed, I took a screenshot explaining why nothing happened. I'll post it on this issue after the round ends, but if it's what it looks like then I don't think it's a bug.

**Comment by AbbieFland** [comment]
Most of atmos wasn't set up, including the N2O pump. With the pump set to 101 and the initial N2O pressure at 1438, the omni filter was trying to force it all into the one tiny section of pipe outlined in green.

Also, the rest of atmos not being set up made so anything being scrubbed would move at best at a snail's pace, so it would seem like virtually nothing was happening.

![image](https://user-images.githubusercontent.com/34605836/37740726-2b763898-2d35-11e8-9ddb-897cdf2dda74.png)
