### ISSUE TITLE
Simplemobs can be aggroed on phased shadekin

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#3327]
#### Brief description of the issue
In one of the pirate events yesterday, after everybody on the bridge was dead one of the simplemob pirates kept chasing after a phased shadekin.

#### What you expected to happen
Nothing without special powers being able to see shadekin

#### What actually happened
Bloodthirsty pirate marbeard

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
How dare

**Comment by Screemonster** [comment]
Not only can they see and chase them, they can actually target and attack them in melee.

**Comment by Novacat** [comment]
This seems like it was fixed?
