### ISSUE TITLE
Promethean limbs come off incredibly easily.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#3328]
#### Brief description of the issue
Promethean limbs come off INCREDIBLY easily, like. A single punch easily

#### What you expected to happen
Not to lose my limbs from someones most basic attack when they are mildly upset.

#### What actually happened
I accidently punched my head off while eating, and I had my limbs taken off with great ease and was generally made a useless prommie nugget until medical injected me with nutriment to the point I could regen.

#### Steps to reproduce
- (Step 1) Play a Promethean.
- (Step 2) Anger someone enough so that they hit you, or just have them jokingly punch you on the arm.
- (Step 3) Lose your limb and have to spend time and nutrition fixing it, and if its a bar fight possibly die because they took your arms off.

#### Code Revision
- Server revision: release - e467af8325bc7ab993a334c960db8351e8716a9b 
 
#### Anything else you may wish to add:
As mildly amusing as it is to easily become the Black Knight from Monty Python, it makes a few jobs rather untenable due to the fact that you might be dealing with accidents that deal more then 5 damage to your limbs, such as working in Xenobiology with anything other then slimes, security in general, engineering if things are really hairy, and anyone on a expedition if things go south.

**Comment by KasparoVy** [comment]
'tis but a scratch.

**Comment by Screemonster** [comment]
Now they actually do fall off as intended, we can probably look into all the previous attempts to balance them and see if they were too harsh, such as the nutrition requirement changes or the threshold at which they take damage.

This kinda reminds me of hyperzine being OP as fuck and people trying to balance it by making it toxic and so on and so forth, until finally it was dealt with by changing the part that made it OP - which meant that balancing measures like making it poisonous were no longer necessary.

**Comment by HzDonut** [comment]
Honestly the limbs falling off super easy is kinda necessary considering how indestructible they are to everything except burn damage. Hell, remember that VR test mini-event where everyone was prommies with rockets? It was really, really hard to actually die. Most of the time I'd take two or three rockets and just be stuck in crit. That combined with the fact they can just regenerate themselves as long as they have nutrition makes them really, really strong. Losin' some limbs easily is the least folk can do to compensate for all that.

**Comment by Benemuel** [comment]
They need 200 nutrition to regen limbs, or less if the other thing went through, and would take 20 seconds if it do, 30 if it did not. And since you LOSE them at the bite of a mouse somewhat literally, its kinda. Well. Say you get hit by a rocket. You lose ALL your limbs. And you need max nutrition to regenerate.

**Comment by Screemonster** [comment]
The cost _increases_ on losing limbs was put in when the limb-loss was bugged and not happening, so now that's patched we can look into it.

The VR test is kinda outdated information now.
