### ISSUE TITLE
Non-emagged holographic carp are digesting people

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3344]
#### Brief description of the issue
After the updates fixing vore bellies and whatnot, the holodeck carp are eating and digesting people (with real, non-halloss damage that persists and everything) even with the safety features on. Their normal attacks still don't do any damage though, so it's just restricted to vore. They DO spit you out before you die, but with how much damage you accrue it seems you usually just die of suffocation. Also you cannot attack them from the inside, which is very unusual.

There's also reports of them just leaving the holodeck and running rampant and breaking doors even with the safety features on, but I haven't witnessed it myself and I'm still testing things to see if that happens. If it's true, I'll make a separate issue for it.

Update: Haven't seen it happen, must've just been people getting confused by emagged carp.

#### What you expected to happen
They'd either just endo me or deal halloss digestion damage.

#### What actually happened
They were immediately in digest mode and dealt very real damage.

#### Steps to reproduce
- Go to holodeck
- Switch it to space
- Wait for carp to spawn and smack it
- Perish

#### Code Revision
-   release - 
98f5770ddf8ce271bf306cd5d85002e20d75f756

- master - 2018-03-25
e904582d94bb07df2bdcd5360e989c3bd843abe7 (Server I did the testing on, but these issues have been observed on the release version as well)

**Comment by Arokha** [comment]
I don't see anything that would have changed about updating bellies that would have altered this at all.

By the same token, I see zero code that would have PREVENTED this at all, too. I'm not sure why they haven't ALWAYS been digesting people.

**Comment by TheFurryFeline** [comment]
https://github.com/VOREStation/VOREStation/pull/3410#issuecomment-578204806 Posting to state that this is an issue again.

**Comment by TheFurryFeline** [comment]
Still an issue since I don't think anyone ever touched on this yet.
