### ISSUE TITLE
Some messed up camera console tags.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3353]
#### Brief description of the issue
There's a bunch of multiselecting dupe names that also tend to have no relation to the duped name. Missing tags?
-Medbay recovery room, shows up as dupe of MED - Surgery Hallway
-Medbay staff room west, shows up as dupe of MED - Surgery Hallway
-Medbay staff room southwest, shows up as dupe of MED - Surgery Hallway
-Chemistry lab, shows up as dupe of MED - Virology Quarantine Airlock
-Medbay staff room east, shows up as dupe of MED - Virology Quarantine Airlock
-Virology west/east cells, show up as dupes of Virology #420
-Cargo office south, shows up as dupe of CRG - Mining Airlock
-Cargo bay east, shows up as dupe of CRG - Mining Airlock
-Cargo bay warehouse, shows up as dupe of CRG - Mining Airlock
-Command meeting room east, shows up as dupe of Gateway Access
-Bridge hallway north, shows up as dupe of Gateway Access
-Bridge northeast, shows up as dupe of Gateway Access
-HoP office, shows up as dupe of Gateway Access
-Green armory, shows up as dupe of SEC- Head of Security's Office
-Warden side equipment storage, shows up as dupe of SEC- Head of Security's Office
-Red armory east, shows up as dupe of SEC- Security EVA
-Red armory west, shows up as dupe of SEC- Vault
-SEC - Vault Exterior cameras all show up in the same tag, no north/west/south distinction
-Brig visitor area, shows up as dupe of SEC- Warden's Office
-Brig center, shows up as dupe of SEC- Warden's Office
-Bridge teleport access, shows up as COM - Bridge Starboard (no dupe, just tag mismatch)
-Morgue north, shows up as MED - Examination Room (no dupe, just tag mismatch)
-Research upper hallway north and west show up as Research and Development cameras (no dupes, just tag mismatch)
-Anomaly lab containment cameras show up on Research Outpost network instead of station side Research like the rest.

#### What you expected to happen
Properly tagged cameras.

#### What actually happened
These things, each dupe button selecting all of the ones under the name at once, requiring to jump via another different cam to switch between the collectively toggled dupes.

#### Steps to reproduce
- (Step 1) Access surveillance camera monitor.
- (Step 2) Press buttons.

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8
 
#### Anything else you may wish to add:
- Locations of troubled cameras available in list above.

**Comment by Mewchild** [comment]
Is this a complete list of duplicates?

**Comment by Verkister** [comment]
All that I could find in the console during current round

**Comment by Mewchild** [comment]
I'll work on this sometime soon. It's a simple renaming. Probably sit down and smash through them on Wednesday, my next day off.
