### ISSUE TITLE
Suggestion: An upper limit to the amount of slimes that can spawn

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3359]
#### Brief description of the suggestion
Basically, some max cap to the amount of slimes that can be active at once.  Like, "if there's this many slimes, current big ones won't split and grey cores won't activate", or something like that.

#### Why suggestion
Because in low-pop times, or even just low-science times, some unlucky amber slimes can cause the server to pretty much die from the sheer amount of slimes that can spawn during an uncontrolled or unnoticed outbreak.

#### Code Revision
release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

**Comment by Heroman3003** [comment]
1. Slimes will not split if they aren't given enough free space. So they will just fill the area they're given and stop reproducing. If you keep opening doors, giving them more and more space, that is your mistake.

2. Ambers are almost most dangerous slime, and most of time problem is that xenobiologist is inexperienced enough to act like its one of regular slime types. They require constant supervision. When amber slime reproduces all offspring has to be quickly killed off. If that doesn't happen, its not bad luck, its xenobiologist's mistake.

3. Ambers do not become problem, unless you got extremely unlucky, as a single amber is manageable. More than 90% of the time that implies that they were bred by someone who didn't try to control them properly.

**Comment by Screemonster** [comment]
Something that allows people to incompetently crash the mob controller by spawning a million mobs is something that potentially allows people to maliciously crash the mob controller by spawning a million mobs.

**Comment by Heroman3003** [comment]
Also: how many would be too many without making xenobiology lack real danger in case of mass slime breakout? Limit would also make ambers too op, as you can use them without fear of losing control, as limit will prevent that from happening.

**Comment by ktccd** [comment]
doesn't "other slimes" count as free space? How else are we getting server-crashing slime-cascades? you can't get a hundred slimes without a hundred squares otherwise...
