### ISSUE TITLE
Suggestion: Event-running guidelines

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#3361]
#### Brief description of the issue
There have been an increased number of unannounced admin-run events recently, which is a nice thing! Events can create gameplay and roleplay opportunities that would not otherwise be there.

Unfortunately, they are often more disruptive than intended, sometimes even to the point that if an admin-selected player antagonist did the same thing they'd probably not be asked to be an antagonist again.

#### What you expected to happen
It may be valuable to have a set of guidelines (published or not) containing best practices for what types of events are best suited to run at what times and under what conditions.

##### A few examples of the kind of best practices I'm thinking about:
 * The crew size and role makeup are helpful to consider.
   * Large-scale combat events are more suited to large crews and crews heavy with security and exploring roles.
   * Peaceful events or small-scale avoidable combat events are more suited to small crews and crews with few combat-focused roles.
 * What point in the shift an event occurs has a major effect on how much impact it can have.
   * Within the first hour of the shift, few people are heavily invested in scenes. Additionally, if an event ends up needing more help from one department the players can fax CentCom asking for an announcement and reasonably expect some requested players to join. Most events can be started at this time and people are likely to be happy.
   * 3-4 hours into a shift, a lot of people are looking for something to do but many people are deeply invested in a scene that would be unfun to be forced into dropping. Events that are more opt-in in nature are likely to go over well, but ones that force everyone or a large percentage of roles to drop everything are likely to make some players unhappy.
   * Close to or after the extend vote, most players are either wrapping things up or getting ready for the next shift. Quick light events are a good choice, but heavily violent events are likely to disrupt endings to player activities already in progress.

**Comment by Arokha** [comment]
I like the suggestion, and I agree with most of it. I'll close this once I'm done writing the guide.

**Comment by SpadesNeil** [comment]
This probably doesn't belong on the Github but we'll make an exception in this case since Aronai wants to handle it.
