### ISSUE TITLE
Xeno empress' spit just goes right through windows

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3365]
#### Brief description of the issue
What the title says. Not only is spit phasing through things like that just bizarre, but with how potent their spit is, it really makes them even harder to deal with.

#### What you expected to happen
The windows in xenobiology would block the spit like any window would.

#### What actually happened
It just went right through and splatted me in the chest, knocking me down in seconds.

#### Steps to reproduce
- Spawn xeno empress with a window between you and them
- Get their attention
- Watch as the spit goes through the window, not even damaging it, and hits you.

#### Code Revision
- release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
- master - 2018-03-25
e904582 (Revision that the issue was tested on)
 
#### Anything else you may wish to add:
- (GIF of it in action will be put here soon)

**Comment by lbnesquik** [comment]
[GIF](https://cdn.discordapp.com/attachments/187013248309002240/497109959108984872/2018-10-03_20-16-14.gif)

**Comment by HzDonut** [comment]
Oh man I can't believe I never added a GIF to this, thanks Ibnesquik.
