### ISSUE TITLE
Crowbarring a wooden crate on the cargo trolley gives infinite wood

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#3366]
#### Brief description of the issue
Trying to crowbar a wooden crate (like a canister, animal, etc.) while loaded on the cargo trolley drops the wood planks but does not break the crate, allowing infinite creation of wood planks.

#### What you expected to happen
Open or don't open, none of this halfway business.

#### What actually happened
You got wood

#### Steps to reproduce
- Load wooden crate on cargo trolley
- Crowbar repeatedly
- Wood forever

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
One day, while Abbie was delivering...
