### ISSUE TITLE
Corpses can fly if thrown onto open tiles

### ISSUE THREAD

**Issue by Neopatra** [VOREStation/VOREStation#3370]
#### Brief description of the issue
If you kill something, like a grub for instance, and throw it onto an open space, it will suddenly fly. Tested on stairs, may work everywhere else but unsure.

#### What you expected to happen
Throwing something onto an open space would cause it to fall down to a lower level.

#### What actually happened
Gravity stopped working and it was suspended in midair.

#### Steps to reproduce
- Kill a grub
- Grab the corpse
- Throw it onto an open space (stairs tested others unconfirmed.)
-Watch it magically float in midair.

#### Code Revision
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
This is minor, but it is rather annoying.

**Comment by Verkister** [comment]
Apparently someone had made the throw_impact proc that handles the landing part after throws obj exclusive for no good reason
