### ISSUE TITLE
Bizarre floor-wall in tesla engine airlock

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3371]
#### Brief description of the issue
A floor spawned where an rwall should be. Hovering mouse over the tile showed it to be a floor, but it appeared to be airtight. People could still walk across it.

#### What you expected to happen
The wall to be a wall.

#### What actually happened
A bizarre hybrid that was a wall to air but a floor to people.

#### Steps to reproduce
- ¯\_(ツ)_/¯

#### Code Revision
Server revision: release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/14942479/38137515-ee281846-341c-11e8-9189-e624ae162d50.png)

**Comment by Screemonster** [comment]
![image](https://user-images.githubusercontent.com/14942479/38138160-38866d30-3421-11e8-861e-b99d77ddd2f9.png)
furthermore, what

**Comment by Arokha** [comment]
Likely one-time appearance corruption. It's not really on the map that way, and there's probably nothing we can do to fix it aside from plead with byond to fix the bug that causes it. Given that it's actually just a wall that looks wrong, iono.
