### ISSUE TITLE
Loadout Black dufflebag is largely indistinguishable from real Black dufflebag

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3372]
#### Brief description of the issue
The Black Dufflebag from the loadout is meant to be a normal dufflebag that looks like a black dufflebag. (which I think is silly in general) But their name and descriptions are identical, which is misleading.

Now obviously, the way to tell would be to pick it each of them up and see which one slows you down.

I'd just greatly prefer that if the loadout Black Dufflebag is to stay, that its name and/or description be altered to differentiate between the two.

**Comment by Treasa729** [comment]
To be honest, I am of the mind that all the dufflebags should either have slowdown, or not have slowdown. While I understand why that dufflebag has no slowdown mechanically, given its origins; it seems silly to penalize people who would instead like to use a department colored one rather than having to wear a black and red one to avoid the slowdown.

**Comment by KasparoVy** [comment]
I think it's the way it is merely 'cause of oversight. Just need a decision on which way to head with this.

**Comment by Treasa729** [comment]
Well, I might be entirely wrong here, but from what I've heard that specific dufflebag is the dufflebag the syndicates can order in with tele-crystals so it was meant to be a higher storage capacity without the slowdown of normal dufflebags. That doesn't really explain ICly why a dufflebag with presumably no special properties doesn't slow you down when other bags of the same size do.

**Comment by KasparoVy** [comment]
I figure that while stripping all the other special properties the slowdown was missed.

**Comment by Very-Soft** [comment]
The black duffelbag from maintenance lacking its slowdown is not a penalty. It's a special property. Dufflebags are generally pretty cumbersome to run around carrying, and in ss13, they can hold way more stuff. It makes sense generally thst your average dufflebag would slow you down. The black dufflebag from the loadout is the same

However, there is a special kind that do not. It's not explained why, but it's entirely plausable to think that it might have extra straps to hold it to you, or a reinforced structure, to make it flop around less. And further it could totally be some other technology or material that we don't understand.

The fluff of how it works is largely irrelevant. At the end of the day, the normal black duffelbag is used by antagonists in raids sometimes, and is overall a fun bit of treasure that you can find in the round. I feel like taking that away would do a little to harm the fun of treasure hunting.

My argument is not that any dufflebags should be changed mechanically, it is that there are two dufflebags which function differently, but are identical in appearance, name, and description. Which is misleading. 

I would like that to be changed, for the same reason that I like that insulated gloves and budget insulated gloves have different names and descriptions from one another.

**Comment by Cameron653** [comment]
https://github.com/PolarisSS13/Polaris/pull/5133 Did this PR for description clarity.
