### ISSUE TITLE
Citalopram pills cause chat spam.

### ISSUE THREAD

**Issue by CockatriceXL** [VOREStation/VOREStation#3373]
#### Brief description of the issue
I took a 30u citalopram pill and I immediately started getting the "Your mind feels a little less stable..." message every time reagents processed. It quickly filled my chat pane with red text.

#### What you expected to happen
I expected periodic messages about my mind feeling stable... a little stable.

#### What actually happened
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...

#### Steps to reproduce
- Create a pill containing 30 units of citalopram.
- Injest pill and observe the chat pane.

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
- My best guess is that it has to do with pills being half as potent but lasting twice as long. It always looks like the citalopram is about to wear off.

**Comment by Smdytb1** [comment]
It's a bit annoying when taking it... it never ends.

**Comment by SpadesNeil** [comment]
Honestly might be a feature to punish lolcrazy players.

**Comment by MrSign** [comment]
This is still an issue in the current code revision.

**Comment by Screemonster** [comment]
Yeah, and the last person it affected wasn't even crazy. There really _was_ something invisible lurking around her and making whispering, hungry noises in her ear.

Hee hee hee.
