### ISSUE TITLE
NIFShop vendor icon is invisible

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#3377]
#### Brief description of the issue
See title.

#### What you expected to happen
For the vending machine not to be invisible.

#### What actually happened
Only the sign was visible.

#### Steps to reproduce
N/A, just look at a NIFShop vendor.

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/6484985/38174795-e8859474-35a0-11e8-94fe-a300097a3b06.png)

**Comment by Arokha** [comment]
It's an AR vending machine. You need AR glasses or the AR NIFSoft to see it. The floor thing is just the projector.
