### ISSUE TITLE
Teal Carpets still create magic space holes, issue removed from github

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3381]
#### Brief description of the issue
teal carpets still borken. but the isse isn't on github anymore

#### What you expected to happen
to place teal carpet down

#### What actually happened
Teal carpet turns into nothingness. Then space. Then the room over pressurises. becuase aparantly space is filled with air

#### Steps to reproduce
- (Step 1) install carpet
- (Step 2) stare in awe as the station room gets too much air into it

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Why is space causeing the room to get more air in it?

**Comment by SpadesNeil** [comment]
Issues cannot be removed from GitHub. Do you mean the original issue was
closed? Because if that's the case you should comment on the original post
for better exposure.
