### ISSUE TITLE
Items are disappearing in suit storage

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#3383]
#### Brief description of the issue
Item sprites disappear sometimes when you put them in suit storage slot.

#### What you expected to happen
For that not to happen.

#### What actually happened
It happened.

#### Steps to reproduce
- Have a clothing item with suit storage
- Put an item there
- Wait where'd it go?!
- Oh it's still THERE, it's just invisible.

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
https://gyazo.com/6aa4092171326fe14c729a55e8137b09 - Item disappearing
https://gyazo.com/23c263e4f94e22e455368fd43f6cb5c3 - PDA on suit storage in examine text, no PDA sprite in suit storage.

**Comment by ktccd** [comment]
just wanna say, I remember this happening with a beaker too. Took me like, 5 minutes of searching the room before I tried clicking the suit storage on my labcoat just in case.

**Comment by Arokha** [comment]
Fixed on Polaris, so would be fixed in the sync

**Comment by Wickedtemp** [comment]
Neat.

**Comment by Leshana** [comment]
Fixed by PolarisSS13/Polaris#5110 which was synced in #3378
