### ISSUE TITLE
Character Deletion/Slot Clearing Not possible.

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#3386]
#### Brief description of the issue
You currently can't clear/delete character slots returning them to blank slates

#### What you expected to happen
To be able to do so to remove mistakes or characters I don't play anymore

#### What actually happened
Nothing at all as the feature for this doesn't work at all from what I can tell

#### Steps to reproduce
- (Step 1)Make a character
- (Step 2)Be dissapointed andtry to wipe out said character
- ((Step 3)Be unable to and end up with a full character list.

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SilverTalismen** [comment]
This has since been fixed with the copy slot function.

**Comment by SpadesNeil** [comment]
This bug is back.

**Comment by TheFurryFeline** [comment]
The copy slot is not exactly a deletion method as seems to be implied above

**Comment by TheFurryFeline** [comment]
This has been an issue for years as far as I'm aware.

**Comment by SilverTalismen** [comment]
Nope not a deletion method exactly but I literally emptied a slot of all uniqueness and named it empty slot and copied it over until I was happy.

**Comment by TheFurryFeline** [comment]
Resolved with #7694
