### ISSUE TITLE
Mob vore icons not updating anymore

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3388]
#### Brief description of the issue
Seems like nowadays whenever mobs eat folk, their icons to show their bellies don't work. Sometimes they work for a BIT, then reset back to the default mob sprite. Real shame considering it makes it harder to tell when things have people inside of them with the quieter belly noises, AND who doesn't love a good mob belly, let's be honest.

#### What you expected to happen
Mob eats person, gets belly sprite.

#### What actually happened
Mob eats person, nothing happens OR mob eats person, sprite updates, then resets back to default.

#### Steps to reproduce
- Just have any vore mob eat someone.

#### Code Revision
-  release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

**Comment by Screemonster** [comment]
I didn't spend an evening drawing tums on xenomorphs to have them not show up :v

**Comment by HzDonut** [comment]
Specific mobs I've seen it happen on in my test server (running current master branch):
Xenos, oties, bees, wolves, great white carp, normal carp, pike, deathclaws

Mobs that seemed more stable/actually worked:
Gaslamps

**Comment by KasparoVy** [comment]
Does this even work for stuff like dogborgs then, for that matter?

**Comment by Verkister** [comment]
Dogborgs use their own equipment overlay when the module belly is full. They don't show up at all for vorepanel bellies.

**Comment by KasparoVy** [comment]
Thanks for explaining the mechanics, never-mind then

**Comment by Verkister** [comment]
I have a feeling I may have found the cause for this issue
