### ISSUE TITLE
Hound Size Change bug

### ISSUE THREAD

**Issue by Jared12100** [VOREStation/VOREStation#3394]
#### Brief description of the issue
When a V2 medihound has a pose change. Either by its panel being opened or by resting, it will reset the sprite to 100%, but the game will still think your character is at 200%. As such in order to fix the sprite One must first shoot the medihound back to 100% before shooting it again with 200%

#### What you expected to happen
To rest at 200% or have my panel opened without shrinking.

#### What actually happened
I shrunk to the sprite size of 100% without the code recognizing me as 100% for no reason.

#### Steps to reproduce
- Set a medihound's size to 200%
- Have the hound rest or open its panel

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8
 
#### Anything else you may wish to add:
- I am unsure if it true with other hound sprites, but it probably is.

**Comment by Verkister** [comment]
Yup seems the resting verb burrowed towards the nonhuman icon updates through a route that was incompatible with our resizing system.
