### ISSUE TITLE
Only one solid method ingame to disinfect a wound.

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3395]
#### Brief description of the issue
There's only one item in the code that WILL disinfect a wound for sure... the advanced trauma kit, found in advanced medical kits, which has a disinfect proc.  The salve proc from ointment and advanced burn kits only has a 50/50 chance.

#### What you expected to happen
For a burn, the most easily infected type of wound, to be treated and truly disinfected by an advanced burn kit.  For more than one way to actually truly disinfect a wound.  For a fully treated wound to not get infected long after being healed.

#### What actually happened
Several cases of treating someone badly burned with an advanced burn kit, monitoring them until they were fully healed, and letting them out of medbay after the body scanner showed them with a clean bill of health, only to have them come in later with a super nasty infection on the part thought healed, because we didn't use a rare resource generally known for treating brute damage and not burn damage.

#### Steps to reproduce
- Get a nasty burn.
- Treat this burn with an advanced burn kit.
- Watch it till you have a clean bill of health from the body scanner.
- Develop a nasty infection a while afterwards.

#### Code Revision
- Server revision: release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 

#### Anything else you may wish to add:
- Possibly an upstream issue as well.
- Not as urgent as I thought due to finding the salve effect, but yeah.

**Comment by Arokha** [comment]
I believe Pol plans to make the other items also disinfect wounds. Both adv kits and ointment, I think? I'll ask and come back here and put it eventually. :p

**Comment by Wickedtemp** [comment]
I'd rather it be Gauze/Ointment with 50:50 chance, and advanced trauma/burn kits with the 100% certainty, since one is meant to be better than the other, but that can probably be changed later.
