### ISSUE TITLE
Solargrubs unable to be extracted from blenders.

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3396]
#### Brief description of the issue
Can't use a multitool to get a grub out of a blender.

#### What you expected to happen
To use the multitool, extract the grub, and kill it before it became dangerous.

#### What actually happened
> The multitool is not suitable for blending.

#### Steps to reproduce
- See a blender glowing and sparking because of a grub.
- Attempt to extract it with a multitool
- Watch your character attempt to do their own episode of "Will it Blend?" and fail.

#### Code Revision
- Server revision: release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

**Comment by Ketrai** [comment]
I mean, I can't really do anything about this the way the blender is coded, nor does it seem like a big issue, just wait for it to grow up. 

I could try to add a check to the blender? if item = multitool, don't do anything? but I don't know if that would resolve the issue, unless i further make that check more convoluted to check if there's a grub inside, tbh it's just adding the same code to a blender that already exists for machines in general.

**Comment by Screemonster** [comment]
I think I've got a solution. Testing it now.
