### ISSUE TITLE
Voremobs gib as failsneks

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3397]
#### Brief description of the issue
Mobs using vore.dmi or vore64x64.dmi have no gibbing icons, and those both files have the failsnek as blank fallback, causing the mobs to explode as failsneks.

#### What you expected to happen
No graffitied sneks flying out with other guts.

#### What actually happened
Gibbed mobs briefly explode as graffitied failsneks.

#### Steps to reproduce
- (Step 1) Gib a voremob using those files, in this case just butcher a dead grub or something.
- (Step 2) Witness the snek come and go.

#### Code Revision
- 0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Probably because there's no icon for the gibbed mobs.
