### ISSUE TITLE
Horse-taur sprites look off

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#3398]
#### Brief description of the issue
Horse-taur sprites look really off around their feet

#### What you expected to happen
Not sure, it just looks really off?

#### What actually happened
The normal body looks like it's in profile, but the horse-taur body seems to be in half-profile with the legs?
But the thing I noticed was some kind of miss-match with the feet. The feet just misses the legs by a few pixels, meaning some legs seem to end in stumps and other legs have longer feet.

#### Steps to reproduce
- use taur body sprite?

#### Code Revision
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 

#### Anything else you may wish to add:
The sprite also looks a little stunted and short, but I imagine that's more because it has to fit under half the height of the main body. I'm unsure if there's any way to even fix that, considering most taurs would probably need more height for that :S.

**Comment by Arokha** [comment]
Please don't open issues with dumb titles.

**Comment by ktccd** [comment]
oh crud... Sorry... did I really name it just "w"? I must've messed up while being tabbed into the game while writing this :S.
