### ISSUE TITLE
Medical Escape Pod (Large Escape Pod 1) Issues

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3401]
#### Brief description of the issue
The escape pod in the medical bay's doors don't open (due to the door controller never allowing you to hit the override buttons or anything) AND it doesn't launch with the tram even if you have it armed and ready to go. Thankfully very few situations happen that would make the crew rely on this pod, but it's still quite the problem.

#### What you expected to happen
The escape pod would allow me to open it/open automatically when an emergency tram is called, then launch with the tram if armed and ready.

#### What actually happened
Neither of those things happened and I just stood by the doors looking like an idiot. If you hack your way in you CAN arm it, force the doors closed, and manually launch it though, and in a worse can scenario admins can force it to launch.

#### Steps to reproduce
- Call an emergency evacuation
- Attempt to board the medical emergency shuttle to find that it will never open.
- Get left behind and likely perish from whatever the emergency is.

#### Code Revision
- release - 
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

**Comment by SpadesNeil** [comment]
Pretty sure all the escape pods are FUBAR.

**Comment by MrSign** [comment]
Yeah, the escape pod requires admin intervention in order for it to be used during an emergency evacuation.
