### ISSUE TITLE
non-emagged holocarp are reportedly digesting people

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3409]
#### Brief description of the issue
Apparently the holocarp are actually digesting people when they eat them. Not tested personally, just seen a bunch of people talking about it on the discord and OOC and none of them bothered to put an issue up.

#### What you expected to happen
Holocarp to only deal holodamage.

#### What actually happened
GLORP

#### Steps to reproduce
- get ate by holocarp
- perish

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by HzDonut** [comment]
https://github.com/VOREStation/VOREStation/issues/3344 _ahem_
