### ISSUE TITLE
Merge Taur voidsuits with regular voidsuits.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#3415]
#### Brief description of the issue
I am annoyed to no end by trying to put on a hardsuit only to be told it's a taur hardsuit. Why is it so difficult to have a means of switching a taur hardsuit to normal hardsuit and vise-versa?

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8

**Comment by Arokha** [comment]
Nobody knew how at the time, but NOW... we have the technology.
