### ISSUE TITLE
Library Lighting

### ISSUE THREAD

**Issue by Aethirshero** [VOREStation/VOREStation#342]
#### Brief description of the issue
The bottom corner of the desk in the library is dark. A light could be added to the wall, or the wall blocking the windows down there could be removed?

**Comment by SpadesNeil** [comment]
Can I get a screenshot of this?

**Comment by Aethirshero** [comment]
![space station 13 2016-07-15 185800](https://cloud.githubusercontent.com/assets/19848477/16890664/a2d513f6-4abe-11e6-800e-356c5476843b.png)
Here you go. Note the darkness in the marked corner, due to the wall in front of the window and the lack of lights.
