### ISSUE TITLE
Colorblindness [Or just Monochormacy] Is broken

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#3422]
#### Brief description of the issue
Selecting a colorblind trait after the update today and going in game, after saving, has no effect in game.

#### What you expected to happen
To see no colors

#### What actually happened
I saw colors and realized none of my clothes matched.

#### Steps to reproduce
- (Step 1)Select a colorblind trait
- (Step 2)Log in and everything is normal in character
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- https://i.imgur.com/jgPWGq7.png
 https://i.imgur.com/3BmExNI.png

**Comment by SilverTalismen** [comment]
It seems to show up for my items and stuff that I'm wearing or have in hand though oddly enough.
https://i.imgur.com/ER7c7BZ.png

**Comment by KasparoVy** [comment]
Smells like planes

**Comment by Arokha** [comment]
It is planes, I meant to write a fix for this when we got the planes update thing but it slipped my mind

**Comment by Little-119** [comment]
Silly foxxo! _patpat_

**Comment by SilverTalismen** [comment]
Glad to know there are *Planes* to fix it.

**Comment by SilverTalismen** [comment]
Still broken currently, hope to see a fix sometime soon~

**Comment by Hawk-v3** [comment]
Is this still broken?

**Comment by SilverTalismen** [comment]
Not certain, I haven't played as the character thats monochromatic.

**Comment by SilverTalismen** [comment]
This is currently fixed.
