### ISSUE TITLE
Cargo can open Security EVA Riot voidsuit crates

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3439]
#### What you expected to happen
Cargo to not be able to open locked security armor with their IDs

#### What actually happened
Cargo was able to open a locked security crate with their IDs

#### Code Revision
- release - 
0ce6c47b6acec88cdd21acb5185e0bf6b604fa0a 
 
#### Anything else you may wish to add:
- I did a bit of investigating to make sure it wasn't just emagged, and it turns out it wasn't. Asked the cargo tech if she opened it with her ID and she confirmed it.

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5193
