### ISSUE TITLE
Prometheons and Gender Identity

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#344]
#### Brief description of the issue
Prometheons cannot change their gender identity, meaning if they shape shift to another gender it will still say Female or neuter or plural when they shift
#### What you expected to happen
For it to change when I swapped to male
#### What actually happened
It still said female
#### Steps to reproduce
Make a prometheon, set your gender identity to something, switch to something else in game
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Was this ever fixed?

**Comment by SilverTalismen** [comment]
As far as I know it wasn't

**Comment by SpadesNeil** [comment]
Can it be tested? :U

**Comment by SilverTalismen** [comment]
Well yeah its pretty easy to test, make prometheon, set them as amle, or female gender with the same gender identity, board the colony and then switch genders and examine yourself, it'll say your female still

**Comment by SpadesNeil** [comment]
This should have been fixed in the latest version.
