### ISSUE TITLE
K9 Unit can't use some commands

### ISSUE THREAD

**Issue by Jared12100** [VOREStation/VOREStation#3447]
#### Brief description of the issue
Security borgs are able to use a *halt and *law command in place of having a holobadge and a hailer. Though when you try to use these commands as a K9 borg it simply says "You're not the LAW, pal." and "You are not security" respectively.

#### What you expected to happen
To be able to use *halt and *law as a security borg that looks like a dog.

#### What actually happened
I get the same message as non-security borgs when I try to use the commands

#### Steps to reproduce
- Be a K9 Borg
- Try to use *law or *halt
- Get told you can't

#### Code Revision
- 0ce6c47b6acec88cdd21acb5185e0bf6b604fa0a 
 
#### Anything else you may wish to add:
- I have no idea if this was intentional or not, but if it was I don't understand why.

**Comment by Arokha** [comment]
`if (istype(module,/obj/item/weapon/robot_module/robot/security))`
