### ISSUE TITLE
FUN™ suggestions for giant rats

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#3453]
#### Brief description of the issue
I'd like rats to be able to do a few NEAT things.

- I'd like a neutral mob version of the rat, which can appear during random events during the shift, but only in maint. It won't attack unless provoked, similar to the solar grub. Unlike the solar grubs, it would _not_ give an alert to the station's crew; you'd just find them by chance.
- If the rat smells you with food, it starts making emotes about the food in your inventory, specifically mentioning the food you have.
- If you drop the food, it'll leave you alone and eat the food like Ian.
- If you do not drop the food, it will attempt to follow you, getting gradually more aggressive in its emotes until it pounce-noms you.
- Attacking the rat will result in normal functionality of neutral mobs, being it attacks back at you, obviously.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/73d841c9c8a25a044bdcdd761b578133df86034c
 
#### Anything else you may wish to add:
- Too complicated for me to figure out in a reasonable length of time but I figure Verk or Aronai may wanna try it. Maybe Cameron or Scree. I don't have the free time to figure out cool things like I used to. :C

**Comment by Arokha** [comment]
What is a MODERATE SUGGESTION :V

**Comment by KasparoVy** [comment]
**Pri: 0-Gamebreaking**

**Comment by SilverTalismen** [comment]
I say it should do everything you've suggested, it'll spawn occasionally in maint as neutral and only bother with you if you have food and become more and more aggressive before eating you

**Comment by SpadesNeil** [comment]
>All issues are to be given a priority. Some pull requests are given priority, but this is not required. Priority is defined as follows from most to least urgent as follows:
>(...)
>(As a feature) An existing functionality is improved or changed to better perform its original purpose.

That said, maybe I should change the "priority" system to "impact" on gameplay.

**Comment by Very-Soft** [comment]
I like this idea a lot!

**Comment by Screemonster** [comment]
Sounds like the way we wanted noodle to behave with the snek-snax.

**Comment by Ketrai** [comment]
I'm still too bad with byond coding to attempt this, but maybe. just maybe.

**Comment by Verkister** [comment]
Probably gonna try this today

**Comment by Verkister** [comment]
Got it working :D

**Comment by lbnesquik** [comment]
https://github.com/VOREStation/VOREStation/pull/3472
