### ISSUE TITLE
OOC escape doesn't work in soul cacthers

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3459]
#### Brief description of the issue
No way get out of a soul cacther if you pred goes SSD

#### What you expected to happen
OOC escape to work, or have another way to get out

#### What actually happened
Trapped in a soul cacther with SSD pred

#### Steps to reproduce
- (Step 1) get nomed
- (Step 2) get soul stolen
- (Step 3) have pred go ssd
-(Step 4) be trapped forever, only way out ot abuse the ghost function with no way to be resleved in round

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 9b381f3cbd1c6df935c32b19ae72fa5ba447a1ec 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Ok, but, you have no body. How would you OOC escape. What would you OOC escape to? It's not like it's going to re-give you a body.

Ghosting out is not abuse, and actually does remove you from the soulcatcher, and shouldn't prevent you from resleeving, either, as their SC will have been doing backups.
