### ISSUE TITLE
Possible Server Crashing Bug: Promethean Issues

### ISSUE THREAD

**Issue by EmoxNeko** [VOREStation/VOREStation#346]
#### Brief description of the issue
The ability to proc several commands with a shocking 20 or so commands per tick, with no cooldown. 
#### What you expected to happen
I accidentally tried to mend wires without a wirecutter but I didn't see the mend button disappear so I kept clicking it.
#### What actually happened
I ended up terrifyingly lagging the server.
#### Steps to reproduce
Be Promethean
Find any hackable item.
Cut a wire that will confirmedly shock you.
Try to mend this wire repeatedly without tools.
End up nearly crashing the server.
#### Additional info:
 - * I'd deep this urgent.

**Comment by JoanRisu** [comment]
Dhael reported heavy lag earlier and this seems to go along with this.

**Comment by Arokha** [comment]
I'm getting the feeling this isn't really so much a bug in click cooldown as it is probably the shocking you runtiming or something and bailing out of that proc as prom have :snowflake: :snowflake: things that happen when shocked. I'll have to test.

**Comment by Cameron653** [comment]
Earlier today the machinery process was going haywire. Someone was doing an RP in which a promethean was being shocked in an electric chair and with an electric pack and the server ended up dying. Having the promethean cryo fixed the problem.

**Comment by SpadesNeil** [comment]
Fixed sort of by removing Promethean immunity to electricity.
