### ISSUE TITLE
Teshari and Hardsuits don't mix.

### ISSUE THREAD

**Issue by VailTheWolf** [VOREStation/VOREStation#3460]
#### Brief description of the issue
Teshari and Hardsuits don't mix very well. Sprite incompatibilities or something.

#### What you expected to happen
Put on a form fitting hardsuit made for a Teshari.

#### What actually happened
Sprite for the hardsuit is humanoid, and clearly not the Teshari one. (If that exists.)

#### Steps to reproduce
Put on a hardsuit as a Teshari. The industrial one is the one I tried.

#### Code Revision
- Unknown
 
#### Anything else you may wish to add:
https://i.imgur.com/0kZUkJR.png
https://i.imgur.com/xhB8VVO.png

**Comment by Draycu** [comment]
Pfft, heh...  But yeah, I would love if the sprites for those suits, especially the rad suit too, fit on Teshari a little better.

**Comment by Ketrai** [comment]
Make a sprite! This isn't just for tesh, many many species still don't have sprites for all the suits.
