### ISSUE TITLE
Grabbing Issues

### ISSUE THREAD

**Issue by UltimateFluff** [VOREStation/VOREStation#3470]
#### Brief description of the issue
When you get a reinforced grab on something then release it, the interface for that eye gets stuck as a reinforced grab when you go to interact with most anything with that hand.

#### What you expected to happen
When the target of the reinforced grab is removed, it should go back to being a free hand.

#### What actually happened
It remained stuck on a reinforced grab on a target that had been vored, and had to drop to have the hand free, but the UI was not only still glitched to show a reinforced grab, but also acted like it was holding something already still in some instances of attempting to interact with things.

#### Steps to reproduce
- Grab something, say a monkey or crew member
- Reinforce the grab
- Vore them
- Scream at the bug and disconnect, then reconnect to fix the error

#### Code Revision
- 6b58de3a2baf315de4b23d50faf616881d79d305 

#### Anything else you may wish to add:
- As mentioned, you can disconnect and reconnect to fix it, but that's kind of annoying. Plus, it's possible it stacks, as when you drop what you have in-hand with the bugged hand, then grab another mob, you see the blue of the grab intent as a border around the yellow that is the grab intent.

**Comment by Arokha** [comment]
I can't reproduce this. Was there any other issue that occurred or something? Every time I eat someone they get released, the grab disappears, etc.
