### ISSUE TITLE
Cannot cut up bedsheets

### ISSUE THREAD

**Issue by DorfGuy1** [VOREStation/VOREStation#3475]
#### Brief description of the issue
Cannot cut up bedsheets into banages, rags, or what have you

#### What you expected to happen
get rags

#### What actually happened
could cut up bedsheet, nothing dropped when done

#### Steps to reproduce
- (Step 1) get bedsheet, and knife
- (Step 2)use knife on bedsheet,
 step 3: do not receive baco, I mean rags
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
6b58de3a2baf315de4b23d50faf616881d79d305 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Mewchild** [comment]
I’ve never been able to get a knife to work. Use wire cutters?

**Comment by Arokha** [comment]
Um, is this a feature? I'm unaware of this being a feature.

**Comment by Mewchild** [comment]
You can cut up bedsheets into rags with wire cutters. This is an old feature, from the days of bay

**Comment by Mewchild** [comment]
Here's where I feel the bug would be, if anywhere. No items apparently spawned when the sheet was cut up.
https://github.com/VOREStation/VOREStation/blob/c8dd30846cfba8b058ec97399e98e8ac3649924b/code/game/objects/structures/bedsheet_bin.dm#L29
