### ISSUE TITLE
Custom Species Base Body Coloring Issues

### ISSUE THREAD

**Issue by H0lySquirr3l** [VOREStation/VOREStation#3478]
#### Brief description of the issue
The Color settings for the "Custom Species" base are horribly off.

#### What you expected to happen
Setting a the body color to (green, orange, blue, etc) would result in something similar to that color,

#### What actually happened
The body will only shift between a yellow or white hue.

#### Steps to reproduce
- Go to character creator and select custom species, either the base body type or as a species.
- Change the body color around and watch it not be anywhere close to that color.

#### Code Revision
- Server revision: release - 
6b58de3a2baf315de4b23d50faf616881d79d305 
 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/34927367/38784270-011034b0-40d5-11e8-8fde-5243bdee528f.png)

![image](https://user-images.githubusercontent.com/34927367/38784295-4fdcbc26-40d5-11e8-8ee6-661476f08562.png)

![image](https://user-images.githubusercontent.com/34927367/38784304-73e9f87c-40d5-11e8-8f7e-0572b2def6e0.png)

**Comment by Arokha** [comment]
You picked "Custom Species" as your "Icon Base", don't do that. It may have completely insane results. You're supposed to pick ANOTHER species in that choice. Like human or tajaran etc.

I'll leave this though and mark it as a bug because it shouldn't be possible to pick 'Custom Species' as an icon base.

**Comment by H0lySquirr3l** [comment]
Ok, I'm not sure how github works so I will go ahead and leave this open. Thank you.
