### ISSUE TITLE
Squirrel Ears Sprite Error

### ISSUE THREAD

**Issue by H0lySquirr3l** [VOREStation/VOREStation#3479]
#### Brief description of the issue
The Squirrel ears sprite sets, (Red, orange, colorable.) do not fit on all but 2 bald species bases. (Akula and Custom species.) Which on "Custom species" the right ear is about 2 pixels off. 

#### What you expected to happen
Be able to have cute cuddly squirrel ears for a character without having to pick a hair style. 

#### What actually happened
The ears only work on the side view sprites.

#### Steps to reproduce
- go into character creator and select any of the Squirrel ear types.
- Select a species that is not Akula or "Custom species"
- give them a bald or Hawk hair style.
- Watch as the ears magically float close to the characters head.

#### Code Revision
- Server revision: release - 
6b58de3a2baf315de4b23d50faf616881d79d305 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/34927367/38784459-ac450070-40d7-11e8-8e77-377e03f07a7f.png)
![image](https://user-images.githubusercontent.com/34927367/38784468-cdfe8f60-40d7-11e8-9f63-b2cb73a771af.png)
![image](https://user-images.githubusercontent.com/34927367/38784479-df563268-40d7-11e8-8e54-4ca649061d1a.png)

**Comment by Arokha** [comment]
"Custom species" shouldn't be chosen as a icon base.

But, the reason they are placed like such is so they appear above hair given that they are slightly smallish and not pointy. Sure, they don't look right when you're bald and have squirrel ears, it's true. But most people aren't playing them that way, and they can't be both ways (unless someone wants to go through and make a version for 'bald' and 'notbald' of every set of ears and stuff.

**Comment by H0lySquirr3l** [comment]
Ah, I see. Then I will go ahead and close this and work with what I can. Thank you.
