### ISSUE TITLE
Teshari Lonely

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#348]
#### Brief description of the issue
Made a Teshari character and spawned in. Literally after five seconds of spawning in the arrival shuttle. The effects of being a lonely Teshari kicked in. Slowing down, Hallucinations. Vision issues. I am actually not sure if it's supposed to do that so fast already.

#### What you expected to happen
To not be a lonely Teshari literally after five seconds of spawning?

#### What actually happened
I was a sad lonely Teshari who immediatly suffered from hallucinations and all the bad effects.

#### Steps to reproduce
Make Teshari Character, Spawn in. Wait a few seconds.

#### Additional info:
Server revision: release - 2016-06-09

**Comment by Arokha** [comment]
I can't reproduce this. I'm able to do laps around the station before having the hallucinations and stuff. There's a decent-sized buffer between being in company and when hallucinations start happening.
