### ISSUE TITLE
Limb Reattachment Bugs

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#3488]
#### Brief description of the issue
Printed limbs, when attached, don't function. 
However, if you cut off a hand and put it back on, it's fine.
Evidently, this is due to some code issues with how limb reattachment works, and how there used to be a surgery for limb reattachment that seemingly can't be used anymore. Bioprinted limbs start off as 'cut away', needing their nerves attached, but there isn't a way to DO that currently. Whereas amputated limbs, for some reason, don't need their nerves reattached and can simply be put back on.

#### What you expected to happen
Attach bioprinted hand, use bioprinted hand. 
Attach amputated hand, use amputated hand.
Probably by using another surgical step other than "squish hand against bloody stump".
#### What actually happened
Attach bioprinted hand. Drop everything.
Attach amputated hand, use amputated hand.
Just squish hand against bloody stump. Can't do anything else.
#### Steps to reproduce
- Bioprint a hand.
- Put hand on recipient.
- Watch as they fail to pick anything up.

#### Code Revision
- Server revision: release - 
6b58de3a2baf315de4b23d50faf616881d79d305 
 
#### Anything else you may wish to add:
- Internal organs are fine. Heart, lungs, etc, all fine. Limbs that you cut off and put back on are also fine. The printed limbs are not fine, however, which is why this bug took so long to be found since the bioprinter's relatively new and other limbs are just fine. 

This honestly ends up being something of a happy convenience for me, personally, because I've always been annoyed by the fact that limb reattachment was reduced to just using the limb on the patient and 'there, done, fixed', rather than the little surgery it used to require. Re-implementing the surgery, and changing a couple things here and there, would probably fix this.

**Comment by Arokha** [comment]
For the technical:
The bioprinter prints all organs with stat = ORGAN_CUT_AWAY (0x1) but external limbs are not expected to have this flag, and there is no surgery to correct it.

Similarly, the 'nerve reattachment' surgery expects stat = ORGAN_DESTROYED which is never set anywhere in the code.

Maybe these two surgeries could be mated up, and sawing off limbs (or the droplimb proc) can cause ORGAN_CUT_AWAY on external too (otherwise they have 0 stat, which seems odd)

**Comment by Arokha** [comment]
Fixed in https://github.com/PolarisSS13/Polaris/pull/5192
