### ISSUE TITLE
Drunk tank in Surface Security is broke

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3490]
#### Brief description of the issue
The cell monitor is not connected to the windoor, so no timer can be set.

#### What you expected to happen
For the drunk tank to be connected to the windoor so it can be ussssed!

#### What actually happened
It broke. Blue screen of death.

#### Steps to reproduce
-Go to drunk tank
-Attempt to use drunk tankl
-Drunk tank broke
#### Code Revision
6b58de3a2baf315de4b23d50faf616881d79d305 
 
#### Anything else you may wish to add:
Nah.

**Comment by Mewchild** [comment]
This is an issue in central command's cells as well.
