### ISSUE TITLE
Quantum pads cannot be deconstructed.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#3509]
#### Brief description of the issue
Read the title.

#### What you expected to happen
For them to be deconstructed when applying a crowbar to them after opening their hatch.

#### What actually happened
I bashed my tools against them like a caveman.

#### Steps to reproduce
- Should be self explanitory.

#### Code Revision
- d93b02b186fddcfc2a1877a2a4d931b48718f506
 
#### Anything else you may wish to add:
- Tried with CE's tools, did not try normal tools.

**Comment by Arokha** [comment]
Hm, they have default crowbar deconstruct in them. `default_deconstruction_crowbar(I)`, I wonder if that requires something different on our codebase than /tg/

**Comment by Jakksergal** [comment]
Normal tools do not deconstruct it either.
