### ISSUE TITLE
Bodysnatcher causes mind implant issues

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3515]
#### Brief description of the issue
Body snatcher causes mind backup implants to fail.  Thus setting off Medbay's Transcore, and causing Medical all kinds of headscratching when the resleeve fails.

#### What you expected to happen
The mind backup implant to work, even if a wrong mind was being backed up or something.

#### What actually happened
Transcore goes off, go in to resleeve, mind and body records still there, print body, wonder why mind won't go in receiver, ask questions, finally find out they're still alive, yet still marked as "past due" on the resleeving comp.

#### Steps to reproduce
- Get mind backup implant.
- Bodyswap with someone.
- Make Medical wonder what the fuck is going on.

#### Code Revision
- Server revision: release - 
d93b02b186fddcfc2a1877a2a4d931b48718f506 
 
#### Anything else you may wish to add:
- Despite my many attempts at resleeving, the person affected never resleeved, and from what I gathered, didn't get any prompts to resleeve either.  Thus, luckily, I wasn't bombing a scene, but on the other hand, hmmm.
- Also unclear whether both having implants, or just one, affects this issue.

**Comment by Arokha** [comment]
The implant does continue working. It doesn't care who it was backing up. This means that a person with an implant, and a person without an implant used the swapper, and the backups failed because the person was moved into a body without an implant, thus no backups could happen.

**Comment by Arokha** [comment]
There's a simple fix: Just make sure you have a backup implant before you use the swapper on someone. And, if THEY don't, make sure you go get an implant in your 'new' body, if you had one before!
