### ISSUE TITLE
Cyborg/AI do not have any access.

### ISSUE THREAD

**Issue by MashiMashers** [VOREStation/VOREStation#3517]
#### Brief description of the issue

Not sure what caused this, but Cyborg Modules, and the AI role are unable to open/access literally any part of the station, not even the affiliated department that they're currently in.

This doubles down with the AI core, not being able to interact with almost anything in terms of opening doors of any kind.

This also applies to not even being able to use the elevator in the Tether map.

#### What you expected to happen

AI's and Cyborgs to have all access and to interface with doors/elevator panels.

#### What actually happened

AI's and Cyborg module's have literally no access to anywhere in the station outside of civilian status.

#### Steps to reproduce
- (Step 1) Play Cyborg/AI and try to interact with doors that require an access.
- (Step 2) Realize you cannot.

EDIT: The current status of this bug is that occurred during a round, and is no longer a problem at this time, but will be left open as to keep a look out for it resurfacing.

**Comment by Arokha** [comment]
![2018-04-20_17-24-14](https://user-images.githubusercontent.com/15028025/39074517-bad1ba5c-44bf-11e8-81f7-34b8e9ec043d.gif)

Works fine for me?

**Comment by MashiMashers** [comment]
Apologies, yesterday after an AI signed on they were having trouble with access, later on I had hopped onto my Cyborg and it failed to open any doors as well.

It may have been from the teleporters being set up somehow?

**Comment by Arokha** [comment]
Odd. Was it before or after the update yesterday? Could have been fixed by something in the update... though if you say teleporters, you probably mean quantum pads, which would mean after.

**Comment by MashiMashers** [comment]
It was after, yea.

It could have just been something that had happened during that round that triggered it?

**Comment by Arokha** [comment]
Maybe. I'm wondering if borg access is somehow tied to AI access, and just the AI got broke and that affected you? Was your borg on at the same time as the AI?

**Comment by MashiMashers** [comment]
I was playing Cargo when the AI had said something about errors and access before they left.
After about 2 hours I had hopped onto my K9 to just make sure no one was afk in the sec department before I went to bed and I was unable to get any doors/elevator to even work. 

So not at the same time, no.

**Comment by Arokha** [comment]
Very odd. Well, let's just leave this open for a bit and see if anyone else has the issue.
