### ISSUE TITLE
Floor Length Braid hairstyle broken

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#352]
I think the path is wrong or the icons for the hairstyle are missing, not sure, but it seems to be an invisible hairstyle, same as if selecting Bald

**Comment by SpadesNeil** [comment]
Can you please resubmit this in the correct format for bug reports? I have no way of investigating if this is just a bug or a deliberate removal by Polaris unless you explain all the details as to how this bug is reproduced and what version you're currently using.
