### ISSUE TITLE
RIG's unable to equip backpacks into suit storage

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3520]
#### What you expected to happen
As previously, to be able to put backpack into suit storage slot when equipped with a deployed, powered rig suit

#### What actually happened
"You are unable to equip that."

#### Steps to reproduce
- (Step 1)Equip rigsuit to backpack slot, power it up and deploy
- (Step 2)attempt to put backpack into suit storage

#### Code Revision
- release - 
7be6c1a479cb498e22d6a00104ae8b8fa43add79

**Comment by VailTheWolf** [comment]
Bumping this. Still a prevalent problem.

**Comment by Novacat** [comment]
I fixed this a long time ago...
