### ISSUE TITLE
Mice are becoming invisible 

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3522]
#### Brief description of the issue
Player mice are becoming invisible sometimes when ventcrawling

#### What you expected to happen
Non invisible mice

#### Steps to reproduce
"Theres a split second were your sprite doesn't load, and if you try and enter another vent during that time you become invisable."
- Be mouse
- Attempt to enter vent
- Interrupt cast when mouse sprite becomes invisible/nearly invisible
- Immediately attempt to enter vent again (may take a few tries to achieve)

#### Code Revision
- release - 
7be6c1a479cb498e22d6a00104ae8b8fa43add79

**Comment by H0lySquirr3l** [comment]
(I was the one who reported this to Ahelp originally.)
After thinking about it, I think it has something to do with the fade out animation. I have no real Idea how its coded, But the mouse sorta sinks into the floor when crawling into the vent. I think It may just be overwriting the sprite position when you enter the second vent. So you enter the first vent, it plays the animation and the position is set to under the floor Then when you leave it there a window of time the position isn't reset. if you enter the second vent before the it does then the game gets confused and continues to lower your position, then when you leave the second vent it returns you to position you were in after the first vent. IE still under the floor.

Or It may be possible that the game is just getting confused and continues to play the animation after you interrupt it so it skips the end of the animation and leaves you sunk under the floor.

**Comment by H0lySquirr3l** [comment]
(I am the original person who Ahelped this glitch.) 
After testing I found that it is very easy to recreate.  Get to a place that will allow you to select between two vents, click "climb into vent." Then while climbing into that vent click climb into vent again and wait. Whenever you leave you will be invisible. It has something to due with the position of the animation screwing up, or the animation not ending properly.
