### ISSUE TITLE
Tentacles can be ridden

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3525]
#### Brief description of the issue
Using tentacle 'taur' tail causes you to become eligible mount

#### What you expected to happen
There is nothing to ride, therefore its impossible

#### What actually happened
Riding on my ???

#### Steps to reproduce
- Make a tentacular 'taur'
- Give rides on your ???

#### Code Revision
- 7be6c1a479cb498e22d6a00104ae8b8fa43add79 
 
#### Anything else you may wish to add:
- While it probably should apply to all existing taurs, even snakes/slugs/frogs, tentacles and alraune seem like they should not be ridden.

**Comment by Arokha** [comment]
Those should probably not be subtypes of taur tails then if they aren't taurs.

**Comment by Heroman3003** [comment]
The reason I think alraune and tentacles are taur tails, because taur category seems to encompass all tails that replace bottom part of the body in general rather than tails that only replace it with a tauric one.
