### ISSUE TITLE
Certain Recipies when followed still result in "Burnt Mess"

### ISSUE THREAD

**Issue by tonyvld** [VOREStation/VOREStation#353]
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Not likely a bug, just the recipe on the wiki is old and probably wrong. Please help by updating our current wiki.

**Comment by SpadesNeil** [comment]
Slapping "needs testing" on this anyway because whatever the recipe is, that probably isn't it. Where did you get the recipe from?

**Comment by tonyvld** [comment]
found it on the wiki, just go there, go to guides to food and drinks, and
you'll see the recipe for apple cake listed there

**Comment by SpadesNeil** [comment]
I need to dive into the code to ensure that's accurate. It's probably not.

**Comment by Arokha** [comment]
Look in recipes_microwave.dm for the recipes. There are approximately eleven billion recipes, so putting them ALL on the wiki would be ... challenging.

Gonna close this since it's just an 'update the wiki' issue which doesn't need a github issue.
