### ISSUE TITLE
Cargo tug ignores open space - cannot descend stairs.

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#3530]
#### Brief description of the issue
Driving over the 'open space' of downwards stairs is treated as though it were normal floor by a cargo tug.

#### What you expected to happen
To drop to the next z-level

#### What actually happened
Floating cargo tug

#### Steps to reproduce
- Drive up stairs (bug observed on first flight of stairs towards public gardens
- Attempt to drive down same stairs
- Float

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/7be6c1a479cb498e22d6a00104ae8b8fa43add79
 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/31856537/39085990-213ed66c-4583-11e8-9868-66078883c6cb.png)

**Comment by TheDavestDave** [comment]
also trying to interactive with the tug there teleported me (roy) across the room

**Comment by Arokha** [comment]
Leshana and I discussed, decided it does not make sense for a tiny airport baggage carrier cart to be able to handle stairs.
