### ISSUE TITLE
Small Mining Outpost Issues

### ISSUE THREAD

**Issue by AliciaJewel** [VOREStation/VOREStation#3536]
#### Brief description of the issue
The mining outpost's water cooler is empty, and there is no disposal (assuming that's even possible with the map layout).

#### What you expected to happen
To be able to get a refreshing drink of water and then throw my trash away.

#### What actually happened
I was left thirsty and had to litter.

#### Steps to reproduce
- Go to mining outpost
- Try to get water from water cooler
- Realize there's also no disposal

#### Code Revision
- 7be6c1a479cb498e22d6a00104ae8b8fa43add79 
 
#### Anything else you may wish to add:
- N/A

**Comment by Heroman3003** [comment]
While on topic of that a cyborg charger on the outpost or maybe drill station right outside it would be a useful addition.

**Comment by Screemonster** [comment]
putting the mech charger outside so you don't need to get out, cycle the airlock, get back in and walk like four feet to put it on the charger would be nice :v

**Comment by ArgobargSoup** [comment]
I'd like ta see a mech charger outside of the main station's mining office myself  :P

**Comment by Very-Soft** [comment]
I could try to make those edits after aro's map conversions are done, I don't think it would be any trouble.

**Comment by Arokha** [comment]
Hold off for a little

**Comment by HzDonut** [comment]
...shouldn't this be closed now that the outpost is gone?

**Comment by SpadesNeil** [comment]
Probably.
