### ISSUE TITLE
Slimes do not (can not?) latch onto targets

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3538]
#### Brief description of the issue
Slimes can't feed through latching. Or don't, hard to tell with mob AI.

#### What you expected to happen
Slime latches on monkey, feeds.

#### What actually happened
Slime mauls monkey to death, while constantly trying to stay on the same tile as it without latching.

#### Steps to reproduce
- Have a slime
- Put something edible in front of it
- Watch it maul food instead of eating it

#### Code Revision
- 7be6c1a479cb498e22d6a00104ae8b8fa43add79 
 
#### Anything else you may wish to add:
- Probably another thing (this time an entire lab in research) broken by taur riding.

**Comment by Arokha** [comment]
Fixed
