### ISSUE TITLE
Protolathe unable to accept chemicals.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3539]
#### Brief description of the issue
Despite having a 'chemical' storage it seems the protolathe can't accept chemicals from beakers.

#### What you expected to happen
Being able to fill up the protolathe with the chemical required to produce an item.

#### What actually happened
Nothing. Attempting to fill up the protolathe produces no results.

#### Steps to reproduce
-Get a beaker and fill it up with a chemical (sulphuric acid in this case)
-Go to the protolathe and click on it with the full beaker.
-Watch as nothing occurs.

#### Code Revision
7be6c1a479cb498e22d6a00104ae8b8fa43add79 

#### Anything else you may wish to add:
N/A

**Comment by Heroman3003** [comment]
Does protolathe even have recipies that require chemicals?

**Comment by Arokha** [comment]
"biological demolecularisor" I think is what you meant.

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5236 created to fix upstream
