### ISSUE TITLE
Floorlength Braid hairstyle is broken.

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#354]
#### Brief description of the issue
Basically, the title of the issue.  It doesn't show up.
#### What you expected to happen
To see the hairstyle on my character.
#### What actually happened
Hair doesn't load, character is bald.
#### Steps to reproduce
1. Create character.
2. Choose the Floorlength braid in the hair options.
3. See a bald head instead in the character preview.
BONUS GAME:
4. Spawn in as character.
5. See that they're still bald.

#### Additional info:
 - **Server Revision**: release - 2016-06-09
eb05fc0682f692b13d69b9e8b6f277dec003c47d 
 - It's also still a thing in the latest V.O.R.E. code.
 - Looked in the code, someone over at Polaris seems to have done it on purpose?

`	braid
		name = "Floorlength Braid"
		icon_state = "bald" //Trust me, it's better this way.`

**Comment by Cameron653** [comment]
Looked into it and found that it was deliberately removed by SinTwo nearly nine months ago.
That being said, I've restored it in my PR.
Picture: http://puu.sh/pLpJe/d0a471515e.png

**Comment by Cameron653** [comment]
This, for some reason, wasn't included in my PR as github unchecked the file. Going to put it in my next PR.

**Comment by SpadesNeil** [comment]
Reference this issue then and resolve/close it when done.

**Comment by Molenar** [comment]
This issue has not been resolved

**Comment by SpadesNeil** [comment]
Server revision?

**Comment by Molenar** [comment]
not sure the reason, but just tried it and looked bald http://i.imgur.com/YuZDsR1.png

**Comment by SpadesNeil** [comment]
Or that.
