### ISSUE TITLE
Syringes Injecting All 15u Is Causing Issues

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#3543]
#### Brief description of the issue
Since the little change a while ago, syringes now inject the full amount of reagent in a single click. This was supposed to make things easier so you didn't have to click three times on a patient to inject the full amount. But, after using it a while, myself and a few others have run into small, annoying situations where I have a full syringe, but don't want to inject the entire thing.

For a few examples, using a syringe to disperse reagents into multiple containers in chemistry. Can't do that quickly anymore. Any time you try to inject a full syringe into a container with fewer than 15u of space left, it injects forever. You have to do something to interrupt the process for it to stop and actually inject. This is true for the mass spectrometer as well, which is used for blood samples, which are only taken in 15u amounts, and only used in 5u amounts for the spectrometer.

For xenobio extracts, you have to carefully interrupt the process after the first delay progress bar, else you'll inject all of the reagents into the extract, when you only needed 5u. 

There are probably other examples of issues like these, this is just what I've seen and heard of so far. We think it'd be a good idea to either revert this or set it to a toggle, and put a small 3 second delay on the infection chance percentage to prevent infections from being injected by one syringe 3 times, administering 5u each in the span of 1 or 2 seconds. Long enough so you won't give anybody an infection between the first 5u injection and the third one, but too short to really use that syringe again without a small chance of infection.

#### Code Revision
- Server revision: release - 
7be6c1a479cb498e22d6a00104ae8b8fa43add79 
 
#### Anything else you may wish to add:
- And if I'm being completely honest, I've spent so long tripleclicking on patients to inject them, I still habitually do it even with this feature... It hasn't really made anything easier on my end, personally.

**Comment by Heroman3003** [comment]
In addition to that attempting to inject into a container when its less than 15 units below max, it will infinitely keep trying to inject it into full container.

In general, this change was seemingly made with cool new infective syringes in mind and completely ignored any application they had beyond injecting medicine into people, which reduced QoL in those applications _drastically_.

**Comment by Ketrai** [comment]
I agree, this is annoying. try doing xenobio with this too. beh.  implanting mutagen >.>

**Comment by Wickedtemp** [comment]
So, this is still a thing and it's still annoying as fuck. But it's been about a year, so I'm giving up on this being changed.
