### ISSUE TITLE
Standing up during wiggles causes tilted sprite

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3551]
#### Brief description of the issue
Standing up in the middle of wiggling crawl animation causes standing sprite to be tilted

#### What you expected to happen
Upright standing human

#### What actually happened
TILT

#### Steps to reproduce
- Rest
- Crawl by dragging yourself onto some tile
- Stand up during wiggles
- Be tilted

#### Code Revision
- 60cb2f0dc98908cd4b7d27caad9a6f9afe5c8c4b 
 
#### Anything else you may wish to add:
Technically a Polaris issue, but it was Aronai who came up with this ridiculous wiggling in the first place, so submitting it here.

**Comment by Arokha** [comment]
I've seen people using this to lean back in chairs and silly things which seem neat. I'm not super sure I really want to fix it. You can always just rest to reset it.

**Comment by Heroman3003** [comment]
For leaning in chairs, there can always be a "Lean" verb added. I've only seen it used to run around with tilted sprite looking extremely stupid.

**Comment by Mewchild** [comment]
This seems like minor issue that the removal of would be detrimental to fun. It’s minor and silly

**Comment by Very-Soft** [comment]
I tend to agree with Mewchild and Arokha. This is a super minor issue that I've only seen used by people playfully goofing off with one another. It's a bug, but it's a sort of fun bug that doesn't hurt anything, and is super easy to fix yourself.

**Comment by Arokha** [comment]
I see that you decided to make a PR to fix this upstream like a child throwing their toys out of the pram when we didn't agree with you, so I'll close this issue.
