### ISSUE TITLE
Wheelchairs are faster than the old haste+

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3556]
#### Brief description of the issue
Wheelchairs have a movement speed greater than that of a tajaran, and only slightly lower than a taj in an alien enhancement vest

#### What you expected to happen
For my legless ass to move at half the speed of smell as penance for the terrible crime of having no legs

#### What actually happened
Be the speed of sound, hell on wheels, faster than light

#### Steps to reproduce
- Find a speedwagon
- Strap self to speedwagon
- Laugh as the peasants move at a comparative crawl next to your scootymobile's might

#### Code Revision
-  60cb2f0dc98908cd4b7d27caad9a6f9afe5c8c4b

**Comment by Wickedtemp** [comment]
Instead of having it be faster, make it double your characters speed.

I want Tesh in wheelchairs to move at Mach 5.

**Comment by Screemonster** [comment]
Sadly speed is based on a delay for how many ticks it takes to move one tile, rather than a the number of tiles you move in a tick. Old hyperzine speed is literally as fast as it's possible to move.

**Comment by Ketrai** [comment]
i don't mind them having a fast mode for wheelchair racing. but it has to be initiated by a push or something, you know, smt that makes sense.

**Comment by Wickedtemp** [comment]
Yeah, wheelchair extinguishers should always remain a thing.

**Comment by Mewchild** [comment]
Okay, but hear me out here 
![image](https://user-images.githubusercontent.com/13400422/39553736-b838331a-4e34-11e8-9559-dcb5a45c032d.png)

**Comment by Verkister** [comment]
https://www.tumblr.com/video/verkele/173683944319/500/

**Comment by Mewchild** [comment]
It was mentioned on Citadel that Wheelchairs are tied with tickrate, in regards to their movement speed. Not sure, something to ponder.

**Comment by KasparoVy** [comment]
Up the tickrate so we can go faster 👽👌

**Comment by Mewchild** [comment]
I've had to stop playing one of my characters that uses a wheelchair,
because it's unwieldy. It's faster that the old haste+ used to be.

**Comment by KasparoVy** [comment]
Must be amazing when there's lag. Tap W, end up on the other end of the station

**Comment by Mewchild** [comment]
Issue is still alive and active as of 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
https://gfycat.com/CraftySmoothAmericancreamdraft

**Comment by Novacat** [comment]
Seems like the previous fix did not work, re-opening.
