### ISSUE TITLE
Floorlength Braid Hairstyle issue

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#356]
#### Brief description of the issue
The hair does not show up on the character in preview during setup, or in game. The style however is still listed under the setup tab for hairstyles. 

#### What you expected to happen
to have the hair that was available to us on the old serer.

#### What actually happened
Invisible hair, regardless of color selected. 

#### Steps to reproduce
Select the hairstyle in the character creation window, become bald despite not choosing bald.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Current version Server revision: release - 2016-06-09
eb05fc0682f692b13d69b9e8b6f277dec003c47d 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
After searching through sprites, it is shown to be present in https://github.com/VOREStation/VOREStation/blob/master/icons/mob/human_face.dmi along with the other hairstyles
under the icon name "hair_braid_s"

**Comment by SpadesNeil** [comment]
This is literally the issue posted before this one.

https://github.com/VOREStation/VOREStation/issues/356
