### ISSUE TITLE
Underdark mob balance

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3569]
#### Brief description of the issue
People are talking on discord about this but apparently can't be bothered raising an issue where the devs/mappers will actually see it.
Short version: a lot of our mobs that were created for away maps were made with the philosophy of being punishingly dangerous to solo crewmembers by way of having a lot of stuns, but only capable of keeping one person at a time down so a competent team can kill the mob while it's busy trying to eat the person it's downed, and thus cover each other - the reason for this is to encourage explorers and away teams to stick together and not go rambo, because they're a team.

Miners on the other hand are _not_ an adventure team. Teaming up is optional, rather than expected and required before they even step out the airlock. Therefore, the mobs they encounter and have to face need to be balanced accordingly. Challenging, but not the level of "frankly unfair" that away mission mobs can get away with.

We're planning to add/code new mobs for this zone anyway which will presumably replace the existing ones. Use this issue to discuss what's appropriate.

#### What you expected to happen
Mobs in the underdark to be risky and pose a threat, but not on the scale of the "if someone wanders off solo they will be chainstunned and murdered".

They should totally still get eaten though and have to struggle their way out of bellies.

#### What actually happened
Corrupt hounds appear to be on the list, and I'm informed that's exactly what they do.

#### Code Revision
Server revision: release - 
9bc62de55ac5093696fc034ea88c102c31565ee1

**Comment by KotetsuRedwood** [comment]
Have you considered re-adding Phoron Oties as an underdark mob, balanced for miners instead of explorers? Don't think their sprites have been used much since the wilderness removal...

**Comment by Verkister** [comment]
Thinking of making a cave specific variant too. Also eye glow system for the mobs in darkness?
Brainstorming some fresh mob types too to sprite up so I'm all ears for ideas.

**Comment by Arokha** [comment]
One issue encountered yesterday was just that a miner didn't realize the KA did damage to mobs, as they have not played anywhere else, and got a corrupt hound down to 12hp (with like 3-4 shots, mind) before giving up.

Keep in mind the KA is one of the most powerful things against mobs. 38 damage per shot by default, infinite ammo. That will kill most mobs in 2-3 shots. Throw some damage upgrades in there (yes, you can install multiple, they stack), an efficiency upgrade, or even the AOE damage upgrade too, and you have a formidable mob annihilator.

**Comment by Screemonster** [comment]
And before anyone asks, they don't work on away maps. Explorers get your own guns reeeeeeeee

**Comment by KasparoVy** [comment]
I'll give it a thorough testing in local, the KA sounds promising

**Comment by Wickedtemp** [comment]
If they have the firepower to handle mobs, my only other concern is how they'd contact Medical for assistance. I was told you can't use comms there, and I doubt they're within sensors range. If it's anything like belt-mining when it was first added, I'm expecting many, many dead miners needing to be resleeved.

**Comment by SpadesNeil** [comment]
We should probably allow radios and tracking down there.

**Comment by KasparoVy** [comment]
It's a dirty job, but someone's gotta do it.

**Comment by Wickedtemp** [comment]
Think it'd be neat to throw in some carp. If only for a source of carp meat.

**Comment by Screemonster** [comment]
I'd honestly be 100% okay with adding carp to the mining underdark. And removing carp sandwiches from the burger crate because _some people_ have started ordering shittons of fast food so they can grind them for carpotoxin holy shit guys can you maybe _not_ use every single thing in the fucking game to powergame please

**Comment by Mewchild** [comment]
You just described Ciph’s entire life in two words. Poor Ciphrom.

**Comment by ArgobargSoup** [comment]
@Arokha Are ya gonna get the corrupt hounds, too?

I think they even had some sorta basic lore that placed them on that one expedition planet only, so yeah, they aren't quite meant for the underdark.

**Comment by HzDonut** [comment]
Also: Why "The Underdark"? That's an established location in another setting, could be rather misleading. Surely a more generic name would be better fitting, especially since I recall Ace getting on people's cases about names of things/locations being memes/references, like 'badboi', 'prettyboi', etc?

**Comment by Arokha** [comment]
I believe they were nerfed instead. Verkister I think reduced the pounce chance. I did watch a miner promethean backpedal and shoot them with an un-upgraded KA and reduce one to 2HP before being hit, though. I think it might just be a matter of practice, really, given that someone almost solo'd one without being hit until they finally got hit. That was BEFORE the pounce nerf, too.

Regardless maybe they can be replaced by phoron oties? Not sure. There's no hostile version of the photie, so I'm not sure how exactly that would work. I'll let @Verkister make a 'hostile' photie if he wants, as there only appears to be the collared one atm.

**Comment by HzDonut** [comment]
Considering my experience with them has been them catching up to me (unless I have haste) in like a second, then taking four or five hits from a fully upgraded KA to die, this nerf sounds amazing. Regardless, yeah I still think replacing them with a hostile photie would be a better idea simply because it fits the environment more.

**Comment by ArgobargSoup** [comment]
There's hostile photies in the code, still.
/mob/living/simple_animal/otie/feral
These things were _all over_ when we had the wilderness.

**Comment by Screemonster** [comment]
Underdark probably shouldn't have pouncing mobs at all, 'cause RNG one-hit-stuns are terrible gameplay. Stuns in general should be limited when it comes to hostile mobs.
