### ISSUE TITLE
Kinetic Accelerators cannot shoot anything closer than max range

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3570]
#### Brief description of the issue
When firing the KA at a nearby mob, you can either shoot past it and miss completely, or melee it. You cannot fire adjacent, or closer than max range.

#### What you expected to happen
Be able to fire past a mob, as with every other gun, and hit the mob mauling me.

#### What actually happened
A tile 5 squares away exploded into sand, and I died

#### Steps to reproduce
- Get a kinetic accelerator
- Provoke a mob
- Fire past the mob in an effort to shoot it, and not melee it

#### Code Revision
- c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc

**Comment by SpadesNeil** [comment]
Isn't this a problem with all guns?

**Comment by KasparoVy** [comment]
While my shots hit close-range targets (so long as my RNG is good), I can't pick an empty tile closer than max range and shoot it if nothing solid is there.

**Comment by Arokha** [comment]
This is how ALL guns are in this codebase. :v

![2018-04-30_15-26-44](https://user-images.githubusercontent.com/15028025/39446002-fdb825ea-4c8a-11e8-9fc3-b0ace08a4f3c.gif)

**Comment by SpadesNeil** [comment]
That said this should probably be changed. It's very stupid to smack someone with a gun if they are at point blank range instead of just shooting them.

At the very least there should be a toggle like there is for dangerous/safe firearms handling.
