### ISSUE TITLE
Mining headsets not going into shortwave mode some shifts

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3572]
#### Brief description of the issue
For some odd reason, the mining headsets like to sometimes not work at all during rounds. No clue what causes the bug at all besides the fact it's a round long bug when it does occur, so it must be linked to something during initialization, maybe.

#### What you expected to happen
The headsets would work as intended and switch to shortwave when you leave an area with comms.

#### What actually happened
Just pure silence and no shortwave notification at all, sometimes.

#### Steps to reproduce
- None, it just...happens. Needs testing.

#### Code Revision
- release - 
c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc

**Comment by Screemonster** [comment]
Honestly the underdark could _probably_ do with a relay. It's not _that_ far from the station.

There's a machine frame in there already. Problem is grabbing parts for one from telecoms requires RD or CE access.
Put parts in mining vendor or abandoned crate loot, perhaps?
