### ISSUE TITLE
Underdark doesn't have any warning for new players

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#3575]
#### Brief description of the issue
There's no access restrictions on the underdark.

#### What you expected to happen
For the doors to have access restriction, so not any random civilian can walk out there.

#### What actually happened
Two civilians almost died.

#### Steps to reproduce
Be a civilian
Go to the underdark
Find that the doors aren't access restricted.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Would be neat if only xenoarch, cargo, security and medical would be able to access the area. So others have to ask for authorization first. Maybe also an update to the SoP about the underdark?

**Comment by Ketrai** [comment]
It may, but it would be neat to at least have something warn people better.

**Comment by Screemonster** [comment]
Warning signs would do it.

![image](https://user-images.githubusercontent.com/14942479/39351204-aecbc872-49f8-11e8-806f-abc8c86a3a32.png)

**Comment by SpadesNeil** [comment]
The real issue is we need to add a few signs then. I have no desire to access restrict it when emergencies will be frequent.
