### ISSUE TITLE
Lockers make contents invincible to disposals.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#3578]
#### Brief description of the issue
If you put a locker into disposals, everything inside doesn't get harmed, ever.

#### What you expected to happen
For the mob/person inside to get injured.

#### What actually happened
They don't take any damage.

#### Steps to reproduce
Get a locker
Put something alive in it
Push it down the conveyor belt, into disposals.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
I think one of the reason its that way is so that bodies sent around in the bodybags dont get destroyed.

**Comment by Shophaune** [comment]
But mailing myself places is so much faster than walking D:

**Comment by SpadesNeil** [comment]
I don't _want_ to fix this because it's hilarious and requires a team effort to set up.

**Comment by Ketrai** [comment]
I mean, I'm fine if it happens with body bags, coz they could be cushioned or some shit. but lockers? Seems a tad unrealistic.

**Comment by Wickedtemp** [comment]
I kinda don't want this fixed, cause its fun, short version.

**Comment by Ketrai** [comment]
What gripes me the most is the inconsistency. Throwing someone in a locker down a z-level injures them twice as bad, coz I think it thinkts the locker fell on them? but flaling down the shute from space to well, the surface in a locker is harmless. LOGIC.

**Comment by Arokha** [comment]
A little hard to fix, tbh. I don't really want to go through the contents (and content's contents (and content's content's contents...)) of everything put in disposal every time it moves. Because that's the only solution I can think of.

Are there other codebases where this is not the case?

**Comment by Arokha** [comment]
Is not a bug given it's never worked this way.
