### ISSUE TITLE
Promethean can't wear voidsuits outfitted for promethean

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3582]
#### Brief description of the issue
Title. Using a cycler to change a voidsuit to promethean spec makes it unwearable

#### What you expected to happen
To have my fluff appropriate slime suit

#### What actually happened
**Your species cannot wear the refitted mining voidsuit.**

#### Steps to reproduce
- Take voidsuit
- Put into cycler
- Apply promethean customization routine

#### Code Revision
c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc

**Comment by Mewchild** [comment]
To note, the promethean refit has a unique sprite. Not sure if it's unique to prommies, or shared to skrell, I wasn't able to tell. Promethean should be removed, and that sprite given to base prommie suits

**Comment by Arokha** [comment]
I do not see the sprite files or anything for Promethean-specific suits. Are you sure?

**Comment by Mewchild** [comment]
Nope! Just something I noticed in game. The item_state for the promethean helmet is different than the one for a human.

**Comment by Arokha** [comment]
item_state is the on-mob one, not the icon_state in-inventory one

Regardless prometheans don't have any custom suit sprites! If the item state changes, it's probably some procedural system to append letters/words onto the end of the item_state after using a suit changer or something.
