### ISSUE TITLE
Button labels on custom circuits not being used properly

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#3586]
#### Brief description of the issue
when you interact with with a machine's button its label doesnt show in the text area

#### What you expected to happen
You press the button labeled 'Power'.

#### What actually happened
You press the button labeled 'button'.

#### Steps to reproduce
- rename a button in a custom circuit case
- push it
- see that it doesnt actually show the label in chat

#### Code Revision
- c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc 
 
#### Anything else you may wish to add:

![image](https://user-images.githubusercontent.com/16435949/39499808-2b3c5d44-4d65-11e8-8de3-c300afcb78be.png)

**Comment by Arokha** [comment]
integrated_electronics\subtypes\input.dm:23 seems to be responsible for this message, but it appears to use the name. I'm unsure how you 'label' buttons and if it changes the name or not

**Comment by kcin2001** [comment]
@Arokha added an image to the main post

**Comment by kcin2001** [comment]
in the situation posted i would want the chat message to say "you pushed the button labeled 'power'
