### ISSUE TITLE
[MAP] Sending packages to the bar via trashmail causes them to end up in the bar bathroom

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3587]
#### Brief description of the issue
Title says it all.

#### What you expected to happen
It'd end up somewhere the bartender could find it, most likely in the backroom.

#### What actually happened
It popped out of the trash bin in the new bathroom where it went unnoticed.

#### Steps to reproduce
- Just send any package with the destination tag 'Bar' through the trashmail via cargo.

#### Code Revision
-  release - 
c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc 
 
#### Anything else you may wish to add:
- https://gyazo.com/0aca1ece4f899044045acfa0097a3220 <- The chute in question

**Comment by Heroman3003** [comment]
Title could use some work here

**Comment by Mewchild** [comment]
I’ll fix this tonight/tomorrow

**Comment by HzDonut** [comment]
I was tired and accidentally an entire word.
