### ISSUE TITLE
Explorers don't get maintenance access.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#3589]
#### Brief description of the issue
Explorers don't have maint access.

#### What you expected to happen
To be able to open all the non-department-specific doors.

#### What actually happened
The bridge maintenance is locked, visitors can access it.

#### Steps to reproduce
- Be explorer
- Tryna open the bridge maint door to search the trash.
- get cucked.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
This may be neat to have when we decide to restrict maint doors so mice can't open em constantly.

**Comment by Heroman3003** [comment]
There are several parts of maintenance around the station that are locked behind department-specific access. Just accept that not all trash is yours to search. There is a lot around as it is.

**Comment by Arokha** [comment]
The specific-access maint is usually the department colored doors.

**Comment by Heroman3003** [comment]
Still don't get why people feel that intense of a need to break in there to get some hoodies or drug pills.

**Comment by Ketrai** [comment]
When they don't have anything better to do? and are in the mood to tryna see what they can find? Unlike many, I actually try to used bodysnatchers when I find them, and I find a suitable partner. I search trash like, 1 out of five shifts, really. Also I'm not avocating for free access to all trash, you misunderstood. There's doors people in a department can't access, whilst visitors can, it's inconsistent.

**Comment by Very-Soft** [comment]
I do think that if visitors have access to a place, then it should be public access to all jobs.

If it's meant to be a restricted access place, visitors should be the last people to have access to it.

**Comment by SpadesNeil** [comment]
Not a bug. Explorers don't get maint access to the bridge area.
