### ISSUE TITLE
Feature request: sort books by genre

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#3592]
not really an issue per se but id like to be able to look at one genre of books at a time on the librarian's computer for easy shelf stocking, if thats already a feature tell me how to do it and ill close this issue

#### Code Revision
- c8a25ab7dd4f89e4af6d7fb736c4e5bf8c211dbc 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by OrbisAnima** [comment]
books are in a database, genre is a column of that table, its as easy as to make a query by genre.

The tricky part is to avoid people doing stuff to the database through that query, so sanitize

**Comment by SpadesNeil** [comment]
I'm sure it already exists, but what I really want is a means to _remove_ or at least edit shitty books.

**Comment by kcin2001** [comment]
Im pretty sure admins can edit the db wherever it is saved

**Comment by kcin2001** [comment]
Dont know how easily
