### ISSUE TITLE
Yet more layering issues

### ISSUE THREAD

**Issue by Smdytb1** [VOREStation/VOREStation#3594]
#### Brief description of the issue
Shower fox and curtains are below your player mob

#### What you expected to happen
to be below the layer

#### What actually happened
I am above the layer
![image](https://user-images.githubusercontent.com/13372034/39402928-bc552c9c-4b3b-11e8-92b8-a35487faa596.png)

#### Steps to reproduce
walk onto curtain. walk onto steam. either or
#### Code Revision
b18bbb45ba09571d1a0489423f3f6efd6590fd4b

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5233
