### ISSUE TITLE
Daedalus Pocket Newscaster sprite/icon/whatever is horribly off-center

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3596]
#### Brief description of the issue
The sprite/icon for the newscaster isn't centered in the slightest, and the bloody thing is giving me conniptions whenever I look at it!

#### What you expected to happen
It'd be a centered icon and fit into the inventory/onto tables perfectly fine like pretty much every other item in the game.

#### What actually happened
An OCD nightmare

#### Steps to reproduce
- Just spawn with/acquire one of the newscasters.

#### Code Revision
- release - 
b18bbb45ba09571d1a0489423f3f6efd6590fd4b 
 
#### Anything else you may wish to add:
- https://imgur.com/a/Q16Cm97 in inventory
- https://imgur.com/a/aQZKt6H on a table

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5232
