### ISSUE TITLE
Weird invisible fire safety poster

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3597]
#### Brief description of the issue
See title. For some reason using one of those good ol' contraband posters on a wall in cargonia got me an invisible poster that I can't even click on to tear off the wall. Real odd.

#### What you expected to happen
The poster would show up.

#### What actually happened
It's pretty much non-existent besides showing up as an option to examine when I right click on the wall.

#### Steps to reproduce
- Get contraband poster (i believe it was no. 66)
- Place on wall
- Be very confused by the results.

#### Code Revision
- release - 
b18bbb45ba09571d1a0489423f3f6efd6590fd4b 
 
#### Anything else you may wish to add:
- https://imgur.com/a/eyDwEUT <- Gallery of images

**Comment by HzDonut** [comment]
Correction: It might've not been a contraband poster. I forgot that normal posters can be red too on here.

**Comment by Screemonster** [comment]
Did you get a chance to see if it shows up in the list if you altclick the tile?

**Comment by HzDonut** [comment]
Alt-click shows nothing but 'steel wall', rick-clicking shows it as something to select though. Also can't put a new poster in that spot because 'there's already a poster there!'

**Comment by ArgobargSoup** [comment]
Did you try alt-clicking the tile in front of the wall?  I think that's where the poster object is actually placed, so that the poster isn't visible from the other side of the wall.

...Although that's a tangent, and yeah, I've come across this bug myself.  I don't think that the fire safety poster is the only bugged one.

**Comment by kcin2001** [comment]
yeah the carp safety poster is broken too 
![image](https://user-images.githubusercontent.com/16435949/39550561-89c94cd0-4e16-11e8-95e7-14de61691412.png)
