### ISSUE TITLE
Suggestion - Portable Freezer changes?

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#3599]
Portable freezers have the issue that they can hold bottles. Allowing medical practitioners to hold up to 10 bottles in them without any cost. On top of that, they are normal-sized, so effectively you could cram 50+ bottles in a backpack easily.  Comparable alternatives are the chemical bottle bag, which slows people down when carried. So I doubt this is intended.

This is only possible because portable freezers are marked with 
 ./obj/item/weapon/reagent_containers/glass
Aditionally they can hold food items too. I believe this is intended as per the description? : "This nifty shock-resistant device will keep your 'groceries' nice and non-spoiled." (then again, it is likely also a joke, due to the groceries being between quotation marks.)

So supposedly you could use the freezer to keep food and drinks nice and cool... elbeit even then it doesn't make that much sense, because who would want to deep freeze food using a piece of medical equipment.

I'm up for sending a change to polaris. But it probably should be discussed exactly what should be changed about these. Suggested changes 

- Make them unable to store bottles, and maybe food as well. (As the main purpose is to keep organs from going bad, it's coded that way)
- Make the storage limit smaller. Currently they can hold up to 5 normal-sized items, translating to 10 small items. The suggested size is 2 normal sized items, so they compare with boxes.
- Make the freezer a bigger item? Instead of normal sized, bulky or even huge? Albeit I don't think this really fits the small briefcase-sized item it's supposed to be, albeit it could be justified with heavy material needs for the cooling infrastructure.

I'm mainly bringing this up because well, medical powergaming.

**Comment by Screemonster** [comment]
already being addressed in https://github.com/PolarisSS13/Polaris/pull/5222
