### ISSUE TITLE
No cancel button on chemmaster

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#3604]
#### Brief description of the issue
When creating pills, after selecting the amount, you can't cancel the production. This a problem because if you badly type the number or just don't want a certain volume in your pills, you can't retry without putting some water into a beaker, hoping it doesn't react with your pill, dissolving the pill, removing the water via chem master and trying again. 

#### What you expected to happen
cancel button for quality of life

#### What actually happened
No button. 

#### Steps to reproduce
- Try to use chem master to make pills
-See no cancel button when entering the name of the preparation.
#### Code Revision
- b18bbb4

**Comment by kcin2001** [comment]
you can grind up pills to put them in beakers i think

**Comment by kcin2001** [comment]
but i agree with your sentiment

**Comment by Arokha** [comment]
Made PR to resolve upstream. Between the two chances: Leaving this open for longer than the PR exists because forgetful, and the PR not being merged, the first is more likely so I'll just close this.
