### ISSUE TITLE
Attempting to remove a cartridge from an empty PDA gives incorrect/odd failure message

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#3611]
#### Brief description of the issue
Attempting to remove a cartridge from a PDA that lacks one gives a rather confusing failure message.

#### What you expected to happen
To get a message such as 'The PDA doesn't have a cartridge!'

#### What actually happened
Got 'You cannot do this while restrained.'

#### Steps to reproduce
- Remove your starting cartridge if you have one, or find a naturally empty PDA in maint/cargo crates
- Attempt to remove the non-existent cartridge

#### Code Revision
b18bbb45ba09571d1a0489423f3f6efd6590fd4b 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5235 created to fix upstream
