### ISSUE TITLE
[Suggestion] Remove PDA spam.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#3625]
#### Brief description of the issue
Nobody ever fixes the PDA spam. There's not enough entries to fix it in the spam filter. It's annoying. Not fun, and only serves to be a hassle.

#### What you expected to happen
a fun mechanic that people will engadge in.

#### What actually happened
It's ignored, even on the highest of roleplay servers. Nobody gives a fuck.

**Comment by Wickedtemp** [comment]
I wouldn't care either way, but I don't think having PDA spam be indicative of something is a good idea, since, well... Magically, everyone's going to know exactly what it's indicative of, and instead of complaining at people to stop the spam, they'll complain at people who may be causing the spam.

**Comment by HzDonut** [comment]
Please for the love of god remove the PDA spam.
