### ISSUE TITLE
Random overlays appearing on ghosts

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3627]
#### Brief description of the issue
Ghosts have seemingly random overlays from somewhere else applied to them

#### What you expected to happen
Ghosts looking exactly like living counterpart

#### What actually happened
Have seen ghost and myself had perpetual weather effect/a speech bubble (sometimes not even appropriate for species)/item in hand/random tails (including taur ones) that character does not have. Maybe includes other things that I simply didn't notice.

#### Steps to reproduce
- Be a ghost
- It is possible you have something that doesn't belong on sprite 

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
- http://prntscr.com/jd5cfi - Lauren with wolf tail (char never had any sort of tail)
Wasn't taking screenshots prior, but specific examples include: ghost on private server with weather effect permanently attached, my char with naga tail, my char holding a box (despite not having one when leaving), my char (human) with prommie speech bubble.

**Comment by Arokha** [comment]
I've had the same issue. Might just be appearance list corruption or something. Hard to say.

**Comment by Screemonster** [comment]
Same happened to me the other day. Ghosted and suddenly had xenomorph accessories.

**Comment by Verkister** [comment]
Yup. Saw Taiga with the wet floor overlay the other day and ended up with a monkey tail myself yesterday.

**Comment by Arokha** [comment]
Sounds like appearance list corruption and perhaps not fixable by us.

**Comment by Heroman3003** [comment]
This higgs bugson still plagues the server

**Comment by KasparoVy** [comment]
Lmfao, higgs bugson. Yeah, most often happens to me with the space-bacon sprite.

**Comment by Heroman3003** [comment]
Never got fixed

**Comment by Heroman3003** [comment]
This higgs bugson is still relevant.

**Comment by Poojawa** [comment]
Got ate. 

Tram'd whilst in belly

became space. 

![](https://i.gyazo.com/a298a3083c120cc4159e3a31702ea508.png)

**Comment by Cameron653** [comment]
After having ghosted and finding myself with a naga tail and then proceeding to ghost yet again and find myself with a wolf tail, I was completely confused, only to realize that it was a truly cursed bug.

**Comment by Cameron653** [comment]
After some testing I managed to track it down to being the **first** variable in the "Overlays" list on the ghost.

Here's the most 'extreme' example, of a ghost becoming the Space overlay and it being fixed: https://i.imgur.com/4Ab2ApT.gif

**Comment by Cameron653** [comment]
I fixed it
