### ISSUE TITLE
Belly settings carry over from last played character when playing a new one

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3628]
#### Brief description of the issue
Apparently, nobody reported this shit despite everybody knowing about it every time it's brought up, so here's an issue on it. For some ungodly reason on newly made characters, they directly import the vore settings and bellies of the last played character. This can cause issues ranging from a minor annoyance to a real friggin' headache like in my case now where the imported bellies had custom messages out the wazoo that I now need to change.

#### What you expected to happen
The bellies would start from scratch on the new character with just 'Stomach'.

#### What actually happened
I got ALL the bellies and messages from my last played character.

#### Steps to reproduce
- Make a new character.
- Join as them and open the vore panel.
- Cry as you now have all the bellies of your last played character.

#### Code Revision
- release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by TheFurryFeline** [comment]
Oh, no you don't, stupid bot. This is still a current bug.

**Comment by TheFurryFeline** [comment]
Still valid
