### ISSUE TITLE
Xenochimera Whitelist

### ISSUE THREAD

**Issue by funnyman2003** [VOREStation/VOREStation#3632]
I've been approved for white listed race Xenochimera seen here, need to be added to the whitelist.

https://forum.vore-station.net/viewtopic.php?f=46&t=1328

**Comment by funnyman2003** [comment]
Odd, still can't select the species from character creation menu. Is it supposed to take a while to work?

**Comment by KasparoVy** [comment]
The PR to add you to the whitelist is still open, and then you gotta wait for the next release

**Comment by funnyman2003** [comment]
ah, alright thank you.
