### ISSUE TITLE
Several sprite inconsistancies

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3633]
#### Brief description of the issue
Top-down tg-style sprites. They're applied only to half the things in their categories and in general mesh with general style of sprites around station.

#### What you expected to happen
Consistency. Either convert all sprites to tg-style or (a better option in purely my opinion) keep them all in old style.

#### What actually happened
Top-down sprites are only applied to specific categories of objects and even then not really consistently.

#### Steps to reproduce
- Look at the sprites of stuff around the station

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100
 
#### Anything else you may wish to add:
List of particular examples below:

New, fancy, shiny machines, don't they look good?
![screenshot_2](https://user-images.githubusercontent.com/31296024/39658295-63de367a-5055-11e8-87e3-aac41018de95.png)
![screenshot_3](https://user-images.githubusercontent.com/31296024/39658296-64e655d4-5055-11e8-86d8-6f8ea4c327bf.png)

Yeah cool, except there are still ones that are not top-down:
![screenshot_1](https://user-images.githubusercontent.com/31296024/39658302-76d2a5a4-5055-11e8-9bea-7a57c4ff9cfa.png)

Or, for a better example, where difference next to each other is glaringly obvious:
![screenshot_4](https://user-images.githubusercontent.com/31296024/39658303-82a42d76-5055-11e8-88e1-a883e4f55371.png)

Can't deny, console lineup looks great on its own:
![screenshot_6](https://user-images.githubusercontent.com/31296024/39658305-9284cbd8-5055-11e8-9e43-4fac5d26ab2b.png)

Except when it starts clashing with old ones:
![screenshot_7](https://user-images.githubusercontent.com/31296024/39658309-a957e03e-5055-11e8-8c30-628afdd9448f.png)
![screenshot_8](https://user-images.githubusercontent.com/31296024/39658317-b1a36e34-5055-11e8-9584-aa477f8ba8ae.png)
![screenshot_9](https://user-images.githubusercontent.com/31296024/39658318-b3e650da-5055-11e8-88fd-f880f9db63b7.png)

In addition to that: frames are still old, colors of consoles/machines do not match colors of frames at all (they at least somewhat do with old ones) and a guessing game! Which way will console look when frame is constructed? East. Because frame has no directional sprites.
![screenshot_10](https://user-images.githubusercontent.com/31296024/39658333-ea448520-5055-11e8-8978-3648e04ba5da.png)

And while vendomats are most consistently updated with new sprites, there is still one that isn't, even though it's least used one: Laptop Vendor.
![screenshot_12](https://user-images.githubusercontent.com/31296024/39658338-0436b1ba-5056-11e8-9f2a-d4918b522685.png)

#### Suggested solution:
While I will admit that I do not really like newer top-down sprites, what bothers me much more how they clash with old ones within same object type or with other items (portable atmos machinery, minor machinery, closets, etc). I believe a vote regarding whether to go full tg regarding artstyle, or revert half-implemented new sprites could do. Unless it has been there and done before I came around, for which I apologize in advance, and just suggest pushing along the process of fully converting the artstyle, or at least have all objects within same category share it.

**Comment by Arokha** [comment]
No vote ty. It's not a democracy, and to be honest, 'calling for a vote' is a good way to make admins frown at your complaint since it appears to be a sort of 'creating a populist movement' sort of thing.

Some of the things you pointed out are fixable, some are more difficult and no server has those sprites in the angle we'd want.

**Comment by Heroman3003** [comment]
Well, as I said, vote is just a lesser thing, the main request of this issue is additional consistency.

**Comment by Screemonster** [comment]
"calling for a vote"

for what

for "someone" to resprite every object in the fucking game?

**Comment by Verkister** [comment]
I could probs sprite some. The colormate was pretty fun to make heh.

**Comment by Cyantime** [comment]
hello I would suggest going back to the old style
destroy TG 3/4 garbage wherever it sprouts up

**Comment by Heroman3003** [comment]
Never got any better

**Comment by Screemonster** [comment]
there's a _lot_ of sprites for people to rework, but no way am I gonna tell people "never make new sprites because they'll clash with the old ones" because that's just an insane thing to ask

**Comment by Heroman3003** [comment]
I still argue that some of new sprites _objectively_ worsened the recognition. Good examples of that specifically being directional consoles not actually having a frame sprite and as result making positioning those a total mess or mechfab and prothfab using same sprite when originally in oblique they were different, and such.

**Comment by SpadesNeil** [comment]
This is an inane issue post. The sprites are being updated. Either help update them or don't complain. Simple as that.
