### ISSUE TITLE
You can leave on tram from any point on map

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3636]
#### Brief description of the issue
You can use popup window of "do you wish to leave" from walking into tram doors to leave from any point around map.

#### What you expected to happen
Pressing leave only allows you to leave if you are next to the door

#### What actually happened
If you get the window and walk away without closing/canelling, you can disappear into tram at any point

#### Steps to reproduce
- Walk into tram doors
- Don't close the popup window
- Walk to any point you want to disappear  from
- Press leave

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by Screemonster** [comment]
Well, that's something. Probably worth testing upstream if they have this feature.

**Comment by Heroman3003** [comment]
Tram is tether-only thing as far as I am aware.
