### ISSUE TITLE
[Suggestions] Soulcatcher Problems

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3637]
#### Brief description of the issue
So I noticed some issues with the soulcatcher lately, both having to do with getting self-caught:

1. If you're like me, you often forget your soulcatcher settings or that you even have one. Now this isn't usually THAT big of a deal...but when you die out in the middle of bumfuck nowhere like i did on an expedition and end up being soulcaught when you wanted to ghost...you're just trapped in there forever, since if you hit ghost it locks you out of being sleeved and leads to some awkward nonsense with jobs and such. I get not being able to leave whenever you want as prey since, well, that defeats the purpose of the soulcatcher, but when you catch yourself SURELY you should be able to leave, especially if it happened on accident like with me.

2. People should really get a custom message on examine/on defib for people that have been self soulcaught since I always have to LOOC "Hey yeah I'm just in my NIF" or else people think I ghosted or am just unable to be revived, always awkward for that to happen.

3. When you talk to people as an AR 'ghost'...nothing shows up in chat for you, so you have no idea if you're actually talking, or what you said. Real awkward.

#### What you expected to happen
None of the above would really happen.

#### What actually happened
They unfortunately happened.

#### Steps to reproduce
- Just die with 'catch yourself' on and regret doing it.

#### Code Revision
- release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by HzDonut** [comment]
Because it's happened to me the last few times i've had to hit ghost. My backup disappeared and when I finally hit respawn i got the messages about being unable to join as my job.

**Comment by HzDonut** [comment]
Hell last time it happened it was because I hit succumb on the alien ship and got ghosted thanks to a glitch, but basically my backup wasn't going off and people were saying i had no mind scan, so i eventually needed to just get "resleeved off-site"...but it didn't let me rejoin as my job so I was just a visitor instead of explorer for the rest of the shift.

**Comment by Arokha** [comment]
Just tested two scenarios. Get backup implant, get NIF, enable 'catching you', and then die, and:
a) Remain in soulcatcher for 15 minutes. Medical is notified via radio to resleeve you.
b) Ghost out of soulcatcher. Mind backup is still there. Medical is notified to resleeve you.

I didn't have any of the issues you described either way, but what you described DOES fit the description of the QTR verb (or just never originally having a backup implant)

**Comment by HzDonut** [comment]
Weird, must just be a separate bug of being marked as having QTR'd when you didn't.

**Comment by Arokha** [comment]
#3 is fixed above, #1 I can't reproduce and #2 is not something we'll add right now probably. Being able to properly talk and communicate with people in AR or via commlink probably covers that aspect, but mostly because implementing 'digging' into NIF every time anyone is examined anywhere is eh.
