### ISSUE TITLE
Stuff keeps disappearing when it goes into bellies

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3640]
#### Brief description of the issue
For some reason, items like to disappear when they would normally drop into bellies.
Ex: Hard voring organs, stripping prey inside of you, etc.

#### What you expected to happen
The items would drop on into my selected belly.

#### What actually happened
Poof.

#### Steps to reproduce
- Just hard vore/strip someone/eat trash. Do anything that gets an organ or object in your stomach, really.

#### Code Revision
- release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by HzDonut** [comment]
So far it's happened with someone's backpack and someone's head, as a note.

**Comment by Arokha** [comment]
Items are digested when they go into bellies unless the belly has Itemsafe turned on. This is by design.
