### ISSUE TITLE
Mining airlock grille is electrified.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3649]
#### Brief description of the issue
The wire knot for the APC in the mining airlock is causing the grille to be electrified.

#### What you expected to happen
The APC to be on a different wall or something.

#### What actually happened
BZZZZZTTTTTTTT

#### Steps to reproduce
- be teshari
- walk into railing
- get fried and probably set the airlock on fire if it's not fully cycled

#### Code Revision
- reported on discord, tbc
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/14942479/39674067-62aa6410-513e-11e8-80c7-34157366b821.png)

**Comment by SpadesNeil** [comment]
**Zap zap stoopid birb**

no seriously we should fix that
