### ISSUE TITLE
HoS/CD ID should be able to wipe weapon permits

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3653]
Given that the HoS and CD can revoke weapon permits, I feel it'd be a nice touch to have them able to wipe them as well. Use CD/HoS ID on a weapon permit to revoke it back to it's blank, unissued state.

**Comment by SpadesNeil** [comment]
Why was this closed?

**Comment by Mewchild** [comment]
I have plans for an alternate method. Allowing paper shredders to accept permits.

**Comment by SpadesNeil** [comment]
Allowing paper shredders to accept permits is probably better anyway.
