### ISSUE TITLE
Robotics lab needs borging consent forms

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3659]
#### Brief description of the issue
The roboticist doesn't actually have a form for willing borg subjects to fill out. There's one on the wiki, but there's not a lot in-game to actually tell them there's actually anything there to look for.

#### What you expected to happen
Something that's considered absolutely essential to some aspect of the job from an RP perspective to actually be present in the game. Like the HoS getting a blank weapon permit.

#### What actually happened
Nada.

#### Steps to reproduce
- be roboticist
- make a borg from a willing crewmember
- get valid'd and tossed in perma because you forgot to dot the i's and cross the t's

#### Code Revision
- Server revision: release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 

#### Anything else you may wish to add:
- Shove it on the table next to the paper bin.

**Comment by KasparoVy** [comment]
That was a funny one.

**Comment by Screemonster** [comment]
Since we're removing the _requirement_ to fill these out and just making them a cover-your-ass formality this can be bumped down in priority.

(my "what the fuck people" over the concept of removing someone from the round over some fucking paperwork and acting like you were in the right to ruin someone's evening because "it's IC" and they're in the wrong for resisting still stands)

**Comment by Very-Soft** [comment]
I prepared a form for this, but I'm not sure how to get formatting to work correctly on a paper that's mapped in.

**Comment by Screemonster** [comment]
Mapped/varedited things might actually need straight-up html markup rather than bbcode, iunno. Worst comes to the worst, just slap a form with the vars in a .dm somewhere.

**Comment by Wickedtemp** [comment]
...To be honest, these forms should probably still be required just because they're such a huge "cover your ass formality" that I can't see how NT would simply leave it up to personal choice, especially when it's usually something as simple as "sign this and get it stamped if possible".

**Comment by Screemonster** [comment]
Oh, they're still ICly required, just not "it's automatically considered to be proof beyond reasonable doubt of fucking murder if you don't have it regardless of whether it was or not and security have valids to end your round over it immediately with no appeal" required.
