### ISSUE TITLE
Muffle belly/Thick belly feature to block speech/emotes respectively.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#3663]
#### Brief description of the issue
It was suggested to me that we add a feature for bellies to restrict speech and/or emotes by way of a toggle. Normally I would bitch "ADD IT TO GITHUB YOURSELF" but I was discussing and refining the idea and I liked it so I just posted it myself.

Said feature would not stop speech or emotes entirely. Rather, it would automatically convert all speech or emotes to their subtle equivalents.

So let's take a character, maybe a taur, for example. Taurs traditionally have multiple guts, so they are a good example.

So let's start with Jarome's first taur gut. There's not much muscle, not much fat, and it would be very easy to wiggle around in. This stomach behaves as normal. Wiggle emotes, /me emotes, and /say emotes are not restricted in any way.

Next is his second stomach, and also his largest stomach. You can wiggle, make it slosh and glunk and jiggle, but anything you say is obscured into muffled nothingness that nobody would hear no matter how hard his victim yelled. Ergo, all /say emotes are converted automatically to subtle emotes, which in this case would be 'whispers', or preferably, a new emote, 'muffles'. You can only hear muffles if you are the predator, or standing _right up next to_ the predator--just like whispers work.

After that is his third stomach. It's not surrounded by as much fat, but it's _far_ more muscular. In this stomach, the opposite issue occurs. /me emotes become subtle, while all say emotes are unmolested. Resist emotes would also not broadcast to nearby players. You can still resist, and resist will still do things, it just won't make noise or chat messages. Pretty straightforward.

Finally, his hindgut. Muscular _and_ surrounded by sagging fat, _every_ emote a player makes, be it speech or action, is suppressed. Speech _and_ actions would be unseen to anyone except those who are up close enough to be in touching distance of his belly.

This is probably more complicated than it sounds, but would be fun.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/c0c9ab541f6616b7086b5cbf14f5bd0329feffbb

**Comment by Heroman3003** [comment]
Are those to be added as belly addons or as new toggles?

**Comment by Screemonster** [comment]
I'd totally love it if being absorbed limited prey to whisper/subtle and prevented radio use. I've literally seen people decide to have loud public scenes where they're _fucking fat_ and then call for help on the fucking radio. The pred wasn't happy at all, in or out of character.

The person in question's banned for unrelated reasons but seriously you're fuckin' pudge at that point you're not in a position to use your headset.

**Comment by Arokha** [comment]
Interesting idea and I'm not opposed, but will require some thinking to decide exactly how to best implement this such that it doesn't add overhead to EVERY speech message while it "checks to see if you're in a belly" or something. Hopefully there's another way.

**Comment by SpadesNeil** [comment]
>Are those to be added as belly addons or as new toggles?

Belly addons, I'd suspect.

>Interesting idea and I'm not opposed, but will require some thinking to decide exactly how to best implement this such that it doesn't add overhead to EVERY speech message while it "checks to see if you're in a belly" or something. Hopefully there's another way.

See I'm not sure there is another way, is the issue. I was hoping somebody might come up with cleverness to do this more efficiently than how I'd do it.

**Comment by Jwguy** [comment]
In the fourth example, all items are suppressed unless the character is adjacent to the pred, it sounds like. Would it muffle the items for those adjacent parties, and simply not display anything for anyone further?

Sorry if this should already be self-evident, but I'm having trouble determining if you're meaning either 1) That the adjacent parties receive the usual broken up "...Stru*g**les ** g*t" messages, and non-adjacent parties receive nothing, or 2) adjacent parties receive full messages but non-adjacent parties receive the broken up and garbled ones.

If it's the first one, that'd be great. I'd even go as far as saying there should be one that nullifies messages entirely, if the person chooses.

**Comment by ArgobargSoup** [comment]
> I'd totally love it if being absorbed limited prey to whisper/subtle and prevented radio use. I've literally seen people decide to have loud public scenes where they're fucking fat and then call for help on the fucking radio. The pred wasn't happy at all, in or out of character.

I see one minor problem with havin' absorb prevent radio use... say you're really unlucky with a gaslamp, get wrapped up, absorbed.  Without radio, you're just plain stuck, unless someone just happens ta wander by.

**Comment by Neopatra** [comment]
Well just do something about gaslamps then. I personally _absolutely love_ this idea and it'll basically stop people from having to say "Use subtle and whisper please" every time they get eaten.

**Comment by Screemonster** [comment]
Letting people _eventually_ get released from absorption by mobs would solve the problem. It's fun for a while and a neat lil' bit of risk when it comes to struggling, but eventually it becomes a do-nothing corner.

**Comment by Rixunie** [comment]
#AceStealsIdeas2018 (In all seriousness, I support this given it was my idea :P)
