### ISSUE TITLE
HoS lacks a pet

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3664]
#### Brief description of the issue
HoS doesn't have a pet for their office

#### What you expected to happen
To be on par with other command staff

#### What actually happened
I have to use Junior Officers as pets, and that results in ethics violations

#### Steps to reproduce
- Be HoS
- Cry 

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100
 
#### Anything else you may wish to add:
- I vote a spider

**Comment by SpadesNeil** [comment]
I want a sprite to differentiate it from other spiders if we do a spider. Again.

We used to have Admiral Cheng. Then Admiral Cheng turned out to be a girl and also breeded and we had to get rid of her.

**Comment by Mewchild** [comment]
I had a pet scorpion that did that. Did Admiral Cheng also eat the babies it squirted all over it's pen?

**Comment by Very-Soft** [comment]
I made a bunch of costumes for the fennecs, including some for security, should that be at all desirable.

![south](https://user-images.githubusercontent.com/24854483/39893501-f27ecb9a-5471-11e8-8c48-a177f8f5ebc9.png)
![east](https://user-images.githubusercontent.com/24854483/39893505-f4ee3140-5471-11e8-84dd-a826fff42c36.png)
![sechud fen front](https://user-images.githubusercontent.com/24854483/39893517-fe133f7c-5471-11e8-9e08-ca5229ef7533.png)
![sechud fen side e](https://user-images.githubusercontent.com/24854483/39893521-013a28e6-5472-11e8-8514-1f799165cc06.png)
![south](https://user-images.githubusercontent.com/24854483/39893525-0684bf8c-5472-11e8-95d3-1baa9ad9b178.png)
![east](https://user-images.githubusercontent.com/24854483/39893531-08e88ede-5472-11e8-98fc-92dd02fee3e5.png)

There's also this one, but I'd need to do a little updating on it to give it proper shading
![front](https://user-images.githubusercontent.com/24854483/39893557-200ab560-5472-11e8-9f47-9de772f3941e.png)
![sechud fen side e](https://user-images.githubusercontent.com/24854483/39893558-23c4f210-5472-11e8-8446-e89cbf6d7321.png)

For your consideration! :>

**Comment by Screemonster** [comment]
oh my god if I had any idea whatsoever how to do audio editing I would absolutely modulate a fennec scream with a police siren so it went SCREEEEEEEEEOOOOEEEEOOOOO at criminals

**Comment by KotetsuRedwood** [comment]
I admittedly love the idea of a pet otie for security but then again I'm a bit biased towards them

**Comment by HzDonut** [comment]
A security otie makes more sense...but they also tend to cause more problems than anything else, so the fennec is just a smarter idea.

**Comment by Mewchild** [comment]
I also don't like the idea of a pet being something useful that you can also order from cargo. Mind, you can order corgis, but that's an old, old thing.

**Comment by Very-Soft** [comment]
![fen town wow](https://user-images.githubusercontent.com/24854483/39899221-bf96bff0-5488-11e8-902b-e7da8ea98f9f.png)

Here's all the different ones I made. They'll need a little work, and this includes the versions with full bellies.

**Comment by Ketrai** [comment]
Fennec crate and fennec costume crate when?

**Comment by Zeldazackman** [comment]
Any new updates on this?
The fennec costumes look great.
