### ISSUE TITLE
Command Pet Issues

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3665]
#### Brief description of the issue
With the exception of the RD's Kendrick, command pets are limited and could do with an upgrade

#### What you expected to happen
To be able to give pets basic commands such as Stay, Follow me, and Stop

#### What actually happened
Tell a pet to do something, and watch it lick it's balls in return

#### Steps to reproduce
- Walk up to Renault
- "Follow me"
- Fucker spins in a circle and shits itself

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by Arokha** [comment]
That's uh.

**Comment by Ketrai** [comment]
I think this isn't relevant. the pets were all designed to have some uniqueness to them. you can put hats on ian. fluffy is a ball of fluff and ends up sleeping on occasion. kendrick can be used to make rainbow slimes? Or something? renault follows you, hunts micros like runtime. runtime teleports all over the fucking place. It isn't their job to be an obedient shit, they're just mascots.

**Comment by Screemonster** [comment]
I mean

https://i.imgur.com/Osw64Ay.gif
