### ISSUE TITLE
Problem with cryo.dm

### ISSUE THREAD

**Issue by ankulanmos** [VOREStation/VOREStation#3666]
#### Brief description of the issue
Trying to compile the game leads to nothing but two errors showing themselves.

#### What you expected to happen
The game finishing compiling so I can play on my own server.

#### What actually happened
Several attempts to re-install the game because I don't know how to fix problems with code

#### Steps to reproduce
- Download most recent branch
- Compile
- Cry when you get the errors

#### Anything else you may wish to add:
The error in all it's glory:
code\game\machinery\cryo.dm:283:error: vis_contents: undefined var
code\game\machinery\cryo.dm:320:error: vis_contents: undefined var

**Comment by kcin2001** [comment]
What version of byond are you on

**Comment by ankulanmos** [comment]
Byond simply tells me it's 'up to date'. I can't find a specific version, other than 'stable'.

**Comment by kcin2001** [comment]
You need to be on beta

**Comment by Arokha** [comment]
This is due to not being on 512, yes. This codebase only compiles on 512 betas and later, as `vis_contents` is a Byond feature that was not added until 512. See the Byond docs included with Dream Maker for more info about it.
