### ISSUE TITLE
Major darksight isn't working right at all

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3674]
#### Brief description of the issue
Sorry for the rather uninformative title, but hey, it's the best way to describe what's happening here. Basically, as soon as you stop moving, major darksight stops working and you get to see a whole load of tiles...which kind've defeats the whole point of the perk, don't you think?

#### What you expected to happen
I'd be able to use major darksight as intended and see into forever through the darkness.

#### What actually happened
I'm worse off than the people who don't have darksight at all since light doesn't really...stop the issue.

#### Steps to reproduce
- Take major darksight
- Go into a dark spooky place
- See the problem I mentioned

#### Code Revision
- release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
- https://imgur.com/a/cYXN3xR <- A gif of the issue in action

**Comment by Ketrai** [comment]
TBH darksight should be reworked anyways. Like, it shouldn't work without there being at least a small light source, eyes don't work in pure pitch black darkness.

**Comment by HzDonut** [comment]
Ah, since this fits into the issue too: Darksight likes to kick in when you enter a recharger, get eaten by someone, or enter any container (but this one is a lot less reproducible from what I've seen). It's a little bit...intrusive to have to see, to say the least. Well, at least with the 'getting eaten' it makes a bit of sense.

**Comment by HzDonut** [comment]
See: the linked GIF.

**Comment by Mewchild** [comment]
This also affects night vision goggles: 
![image](https://user-images.githubusercontent.com/13400422/40140395-6fa6ca64-5918-11e8-81fe-763a0fa15f7f.png)

**Comment by Arokha** [comment]
Ascian had this issue, and it turned out to be related to the version of Byond they were using. They switched to another byond beta version and it resolved it for them.

**Comment by Arokha** [comment]
> TBH darksight should be reworked anyways. Like, it shouldn't work without there being at least a small light source, eyes don't work in pure pitch black darkness.

Not especially possible, see_in_dark is a Byond feature. Can't really alter how it works. You can make suggestions though on the Byond forums for improvements to it if you can think of a way it can be altered to accommodate this sort of behavior.

**Comment by Arokha** [comment]
Confirmed that it's a byond bug in 512.1424 only. Revert to 512.1423 to fix. Skip version 512.1424 until 1425 to see if it fixes it.
