### ISSUE TITLE
Spin View CW/CCW has problems with doors

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#3678]
#### Brief description of the issue
Some view orientations show certain doors offset by one tile.

#### What you expected to happen
Doors to rotate properly

#### What actually happened
Doors open when people are a tile away and don't line up with their emergency shutters.

#### Steps to reproduce
- Spin your view
- Walk around until you find a bugged door

#### Code Revision
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/31856537/39961508-731695e4-562f-11e8-9d52-f46e1a689bf2.png)

**Comment by Screemonster** [comment]
yeah don't spin your view, it's fucked and has been fucked for ages

**Comment by Shophaune** [comment]
![image](https://user-images.githubusercontent.com/31856537/39961526-d34b5d14-562f-11e8-9b05-e5705e5fdfce.png)
Good to know it's well known by everyone except me.

**Comment by SpadesNeil** [comment]
well now you know too :)

Seriously we should just disable that busted-ass "feature"
