### ISSUE TITLE
Spectrometer Coolant Issue

### ISSUE THREAD

**Issue by Aethirshero** [VOREStation/VOREStation#368]
#### Brief description of the issue
The Radiocarbon Spectrometer's in the Spectrometry lab will not take in coolant.

#### What you expected to happen
When the bucket of coolant was used on the machine, it should have emptied the bucket and filled the machine's tanks with coolant.

#### What actually happened
A message was given stating that the coolant was added, but the bucket remained full and the machine remained empty.

#### Steps to reproduce
Fill bucket with coolant, use on machine, click add coolant.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Tried with all three machines, same bug for each.

**Comment by SpadesNeil** [comment]
Did coolant actually go into the machine or no? I know the bucket wasn't emptied.

**Comment by Aethirshero** [comment]
Oh, sorry. No, the machine did not get any coolant, which means that it is completely unusable.

**Comment by SpadesNeil** [comment]
Is this still an issue? If I get no response in a week or two I'll close this.

**Comment by Aethirshero** [comment]
I tested it just now and the machines still will not accept coolant.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
