### ISSUE TITLE
Telepad Control Console Max Distance Always Equal to 0

### ISSUE THREAD

**Issue by iNoPeRaTiVe** [VOREStation/VOREStation#3680]
#### Brief description of the issue
The telepad control console has the max distance as zero, and no matter what you do you can't change it.

#### What you expected to happen
I expected, once I had constructed all my stuff and plugged it in, for the Max Distance to be equal to 120 meters (Or so.) like it usually is.

#### What actually happened
I constructed all my stuff, plugged it in, and when I go to open the telepad control console it reads the max distance as zero, so I tried setting the distance to another number and hitting "Send" but the telepad just "weakly fizzes."

#### Steps to reproduce
- Construct telepad+control console.
- Link them via multitool.
- Open console and observe the disappointing max distance value of zero.

#### Code Revision
849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by AbbieFland** [comment]
Did you install any crystals? I believe the infinite free crystals you get for screwdrivering the panel got fixed, so now they have to be installed manually.

**Comment by iNoPeRaTiVe** [comment]
Yes. I installed the artificial bluespace crystal when I made the machine.

**Comment by AbbieFland** [comment]
One is required for the machine itself, then the four slots in it need at least one installed to boost it. It used to spawn one magically out of thin air when you screwdriver it shut, but it doesn't since the fix a couple months ago.

**Comment by iNoPeRaTiVe** [comment]
Oh, huh that's new. I never encountered that before, guess it's not a bug, but a feature. Sorry!

**Comment by AbbieFland** [comment]
Arguably one could make the case that the base machine recipe shouldn't require one any more, since at least one has to be manually installed. The big problem with one built-in before was if you repeatedly attached and removed the panel you'd get infinite crystals piled up.

**Comment by iNoPeRaTiVe** [comment]
Glad they fixed that, then.

**Comment by iNoPeRaTiVe** [comment]
Actually how do you even put in crystals?
