### ISSUE TITLE
'Nose (Vulp)' custom marking not showing up on south-facing sprites.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3690]
#### Brief description of the issue
The 'Nose (Vulp)' marking in character creation doesn't show up right on south facing sprites, for some odd reason, and it's really killin' me here.

#### What you expected to happen
The custom nose would be on all of the sprites.

#### What actually happened
It's on all of them but south for some reason.

#### Steps to reproduce
- Just take the 'Nose (Vulp)' marking and face South, easy as pie.

#### Code Revision
- release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
- https://imgur.com/a/HFZs60C

**Comment by Arokha** [comment]
It is there, but it's darker than the other 3 directions and harder to see. If it's a dark color it's basically not noticable. I'll make the pixel 255,255,255 for south like east and west have.
