### ISSUE TITLE
Mounted equipment is usable to attack mobs from inside

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#3695]
#### Brief description of the issue
Hardsuit modules are usable inside mobs to attack said mobs.

#### What you expected to happen
Hardsuit modules to be disabled the same way other attacks are to stop people cheesing out of getting pounced by lying down.

#### What actually happened
Apparently people are able to spamclick mobs with their mounted drills.

#### Steps to reproduce
- wear hardsuit
- get eaten
- middle click to win

#### Code Revision
- Server revision: release - 
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
- Reported on discord, needs testing

**Comment by SpadesNeil** [comment]
I think this is an issue with all items currently. I don't want it possible to attack mobs from inside, but wiggle escape from mobs is also kind of broken right now. I swear I posted an issue about it but don't think it ever got fixed.
