### ISSUE TITLE
Becoming 'unknown' is broken(?)

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3696]
#### Brief description of the issue
I've seen a few times with people disguising themselves that despite having no ID and their face obscured. Their name is still visible!

#### What you expected to happen
'This is UNKNOWN'.

#### What actually happened
'This is INSERT NAME OF CHARACTER'

#### Steps to reproduce
-Get a gas mask.
-Remove your ID card and hide it somewhere, like your bag.
-Become sad as you are still identifiable by name and hope that someone just RPs that they don't know who you are.

#### Code Revision
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment]
Virgo gasmasks are not face-obscuring, they're big polycarbonate clear faceshields, ala 
![image](https://user-images.githubusercontent.com/15028025/40087690-bd86081e-5871-11e8-9afc-23d7e55929a9.png)
