### ISSUE TITLE
Micro vore foul-up

### ISSUE THREAD

**Issue by nightwingthedragon** [VOREStation/VOREStation#370]
#### Brief description of the issue

I scooped up Rune Petersen in the bar and clicked myself, giving messages saying I'd eaten him and no errors, then moved him to the second stomach using the inside panel, which also showed him as being inside me. Then noticed that Rune was still in my hand. Set him down and he could still move. Grabbed and ate him, which got him inside, but now there's two Rune's inside me.
#### What you expected to happen

Rune should have been eaten without remaining in my hand.
#### What actually happened

See description above.
#### Steps to reproduce

1) Scoop a micro with help intent
2) Click yourself
3) Check the inside panel
4) Check your hand
#### Additional info:
- **Server Revision**: release - 2016-06-15
  50aec7ce3f6e10a8cbdd4d96ecaf56a76ba4d2e8

**Comment by SpadesNeil** [comment]
This should have been fixed by https://github.com/VOREStation/VOREStation/pull/365 and https://github.com/VOREStation/VOREStation/pull/366. Is this still an issue as of the most up-to-date version of the station code? Not what's live on the server.

**Comment by Dhaeleena** [comment]
This is indeed an issue that still happens, it just happened to me today.

**Comment by Arokha** [comment]
Is this still an issue? Or?

**Comment by SpadesNeil** [comment]
Dunno. Needs testing!
