### ISSUE TITLE
Body Scanner Bug!

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#3700]
#### Brief description of the issue
It's possible to eject yourself from a body scanner while unconscious, as well as insert yourself into it via click-drag mechanics. 

#### What you expected to happen
For it to not work. 

#### What actually happened
It worked, and I tossed my sleeping self out of the scanner then climbed back in...then climbed out and in again a couple more times for good measure. 

#### Steps to reproduce
- (Step 1)Be unconscious. 
- (Step 2)Be within range of a body scanner or in one. Then just click drag yourself into it, and use the right click menu to get the eject. 
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
  release (#3620)
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
That's very odd. There's already code to prevent this.
