### ISSUE TITLE
Laser Pointer!

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#3701]
#### Brief description of the issue
Laser Pointers can be aimed at things on the other side of walls if you have visibility of them. This gives the ability to disable cameras that you don't actually have line of sight of, as well as, if you have thermal vision, blind people on the other side of a wall. 

#### What you expected to happen
The wall to stop the laser pointer laser. 

#### What actually happened
It pierced through with the power of Valhalla. 

#### Steps to reproduce
- (Step 1)Get a laser pointer. 
- (Step 2)Put a better micro laser in it because the basic one is pretty much useless for chance to get these things, and you want to test it. 
- (Step 3)Click things with your laser, like cameras, and if you have thermals, people. Watch as you blind everyone from the other side of a wall and they don't know who or what hit them. 
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
  release (#3620)
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Maybe it should throw a helper projectile?

**Comment by chaoko99** [comment]
Make it into a gun. Seriously things that use projectiles should just be guns. There's less crap involved.
