### ISSUE TITLE
Meson NIFsoft doesn't protect against SM

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3703]
#### Brief description of the issue
Looking at supermatter shouldn't cause issues when you have meson vision

#### What you expected to happen
Just like with glasses, to be able to safely be around visible SM with meson NIFSoft on

#### What actually happened
Spinning and hallucination chakats trying to kill me

#### Steps to reproduce
- Enable meson NIFsoft
- Look at SM

#### Code Revision
- 849c1374a1b064b9c9a1fb8c1c43ed19a4259100

**Comment by SpadesNeil** [comment]
Your eyes aren't actually being covered by anything, I don't think, so perhaps this should not be fixed?

**Comment by Arokha** [comment]
Would require a lore decision on WHY the SM breaks you.

**Comment by Heroman3003** [comment]
Never got a final word or decision
