### ISSUE TITLE
You get full way too fast

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#371]
#### Brief description of the issue 
You get full too quickly and are unable to eat after one single food item.

#### What you expected to happen
Be able to eat a bunch of things

#### What actually happened
Eat one muffin and instantly be  fat and unable to eat

#### Steps to reproduce
Eat something
Be unable to eat more.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab. 
N/A didn't have time to check.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Lines related: https://github.com/VOREStation/VOREStation/blob/54272da16785733c4036ab3738229491b85de5a3/code/modules/reagents/reagent_containers/food/snacks.dm#L59-L69

**Comment by SpadesNeil** [comment]
This is something that Polaris has for realism, which we remove because vore.

**Comment by Screemonster** [comment]
Scree couldn't cram the entire kitchen meatlocker down his gullet and this made me sad :v
