### ISSUE TITLE
Protolathe cannot accept chemicals / Biological Demolecularisor cannot be created

### ISSUE THREAD

**Issue by Theoun** [VOREStation/VOREStation#3717]
#### Brief description of the issue
As title; the Biological Demolecularisor, a high-Combat-level gun that I wanted to test and/or study, requires Unstable Mutagen. The Protolathe has Chemical Storage, and we even deconstructed it to put beakers inside filled with Unstable Mutagen, but nothing showed up in Chemical Storage and you cannot pour chemicals directly in like you can with the Circuit Imprinter and acid, for example.

#### What you expected to happen
To either be able to put chemicals into the Protolathe like the Circuit Imprinter, or for Protolathe items to not require chemicals.

#### What actually happened
This horrible item on the list remains black and unclickable due to the requirements to making it being impossible to achieve, destroying my self-confidence as it remains tauntingly out of reach.

#### Steps to reproduce
- Get R&D levels nice and high until you have Combat 8.
- See Biological Demolecularisor in the list.
- Be unable to print it no matter how many convoluted ways you try to get mutagen into the protolathe.

#### Code Revision
- e26028259975a51fdac9ab1b3878721c3cc2520a
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Already fixed upstream, fixed in next sync. It's a mistake on that item's design, not on the protolathe. The protolathe has never been able to accept chemicals.
