### ISSUE TITLE
Liquid Tanks hide under pipes

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3719]
#### Brief description of the issue
Water/Fueltanks hide under pipe level

#### What you expected to happen
For them to be above

#### What actually happened
They're below

#### Steps to reproduce
- Find tank in maintenance
- Look at it

#### Code Revision
- e26028259975a51fdac9ab1b3878721c3cc2520a 
 
#### Anything else you may wish to add:
- http://prntscr.com/jjabhv

**Comment by Heroman3003** [comment]
Also, while at it, wall girders (at least dislodged ones) are under catwalk and dirt layers

**Comment by Heroman3003** [comment]
Even more layering issues: warning sign below the window:
https://image.prntscr.com/image/48NQHdXCTpG2dwjQBwVWzQ.png

**Comment by SpadesNeil** [comment]
This feels like a Polaris bug.

**Comment by Heroman3003** [comment]
While some other secondary issues mentioned are still there (particularly signs below windows), all relevant stuff seems to have been fixed.
