### ISSUE TITLE
[SUGGESTION] Remove ghost autokick 'feature'

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3721]
#### Brief description of the issue
A while back we got an update that kicked ghosts after some time, and I don't recall _why_ exactly it was needed, but what I DO know is it's really fucked with people taking logs of rounds that they're interested in learning about, but don't want to/can't play in.

#### What you expected to happen
I'd be able to observe and hit the log button to get a nice recap of the round that I can read whenever I want.

#### What actually happened
I observe, start a log, and eventually get kicked because the reason I'm logging the round in the first place is that I cannot be on my PC to actually play the game, hence I can't exactly just tap a key to prevent being kicked every once in a while.

#### Steps to reproduce
- Ghost/hit observe
- Start a log
- Come back later to find out you got kicked from the round.

#### Code Revision
- release - 
e26028259975a51fdac9ab1b3878721c3cc2520a

**Comment by Arokha** [comment]
As admins we decided we did not want to allow people to just AFK-log rounds they were not a part of. That's not the purpose of observing.
