### ISSUE TITLE
Explorers have access to EVA but not the actual cycler room

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3723]
#### Brief description of the issue
Why have you done this to us? Basically, we can get into the actual main EVA area, but can't get into the room where all the cyclers are...thus making the voidsuit update kind've pointless.

#### What you expected to happen
I'd have actual EVA access.

#### What actually happened
I basically got prank access that brought me just into arms reach of my goal but, alas, it was sealed behind another door I could not open.

#### Steps to reproduce
- Just become an explorer and head on into EVA, simple as that.

#### Code Revision
- release - 
e26028259975a51fdac9ab1b3878721c3cc2520a

**Comment by Arokha** [comment]
I suggested he put a cycler IN the exploration room ;v I'll add one.

**Comment by Arokha** [comment]
Ok, in looking, there are NO suit cyclers that work with those suits. They all are designed for a specific department. I may just make the normal 'boring' voidsuits omni-species or something.
