### ISSUE TITLE
Taursuits are gone, but not other set pieces

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3724]
#### Brief description of the issue
Wherever there were taursuits, there normally were other things like radiation hood or helmet+magboots. Now the suit is gone, but other set pieces are there.

#### What you expected to happen
Either for set pieces to be removed along with suits, or regular suits to be put in place of taur ones.

#### What actually happened
Incomplete suit sets with just chest piece missing

#### Steps to reproduce
- Look inside radlocker/engineering's hardsuit racks/etc.

#### Code Revision
- e26028259975a51fdac9ab1b3878721c3cc2520a 
 
#### Anything else you may wish to add:
- Possibly problem everywhere taur suits existed, not just engineering and radlockers. Just ones I knew to highlight as example

**Comment by Arokha** [comment]
I thought I did it consistently, but there were A LOT of modified lockers and stuff. Can you list which ones were missed?

**Comment by Heroman3003** [comment]
Well, definitely radsuit lockers in engineering, as well as the hardsuit in tesla setup. Will add in another comment after looking around,
