### ISSUE TITLE
Job related laptops are like solid walls.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#3730]
#### Brief description of the issue
You can't move job related laptops, at all. You can't even hop over them.

#### What you expected to happen
To be able to unwrench them so you can relocate them? To be able to climb over/past them?

#### What actually happened
They don't move, even in the slightest.

#### Steps to reproduce
Find a medical, atmos, any job-related laptop somewhere on the map.
Be baffled that tiny slip of metal is actually stronger than any baricade you can muster.

EDIT : When you reconstruct a laptop after deconstructing it slightly, it turns into a medical records console, neat.

**Comment by Heroman3003** [comment]
That's because those are actually consoles. They just have small sprites, misleading names and are mapped on top of tables.

**Comment by Ketrai** [comment]
Yeah, I just realized deconstructing and reconstructing one. It's still bull, should be coded at least slightly differently to make sense?

**Comment by SpadesNeil** [comment]
Probably the density var set to 1 instead of 0.
