### ISSUE TITLE
remove or rework tesla

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3732]
#### Brief description of the issue
the current rotation of engineer's keep blowing up the tesal, resulting in the station have no power for most of a shift, preventing everyone else from working

#### What you expected to happen
Engineers to set the engine successfully. Station gets power. A gay time to be had by all

#### What actually happened
Engineers blow up tesla. The station goes into permanent darkness. No one can do their job. The round stay with no power or it gets canceled early, only for the cycle to repeat as a tesla spawns again, escapeing and leaveing us without power.

#### Steps to reproduce
- (Step 1)spawn tesla engine
- (Step 2) wacth as the few hours of set up wasted. As the station slowly looses all power. Mineing start to use their shelters so you have light the whole shift, inviteing you in only for engineering to burn the station down around it.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 c973f8672a981994941b90fc583c88c1ddab5fac 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
it's getting too common for a teasla to ruin the round of everyone on it. Something needs done about it

**Comment by Mewchild** [comment]
What needs to be done is that the engineers need to sit back and think about what they're doing when setting up the engine. There's steps to follow, and everything needs to be doublechecked. If the Tesla is going to fail, it'll do so in the first hour or so, assuming it's failing because of power (the most likely reason, engine SMES not being set). If it's not the SMES, it'll fail within the first couple minutes.

**Comment by TheDavestDave** [comment]
it regularly escape. Most people ICly think engineers are near brain dead due to how often it escapes. The engineers keep dieing before setting solars too. This is happening too often for it to be just one person

**Comment by Mewchild** [comment]
There was a period of about two months where the tesla almost never escaped, as engineers got used to it. This was right after it was added. The tesla escaping is no more catastrophic than the SM delaminating, and is very often less disastrous. The terrible terrible damage to the station occurs when people decide that the PA is fine to leave set at max instead of at 0, and the Tesla escapes with an absurd amount of energy stored inside it. Again, user error, and not thinking about things.

**Comment by Screemonster** [comment]
I literally set it up for the first time during the casino event. I read the goddamn manual and I did all the steps in the manual. Lo and behold, no tesloose. This is not a problem with the engine itself.

**Comment by Mewchild** [comment]
I was able to do it blind, with no guide I didn't even know there was an IC manual), by looking at the setup and how the pieces worked together. Make sure everything's secure. Make sure the emitters have power. Make sure the field is on all the way around. It's just like the singularity setup, with one more step.

**Comment by TheDavestDave** [comment]
so there is an problem with the engineers, how do we fix that?

**Comment by Mewchild** [comment]
The same way Resh and I fixed problems in security. Be an example. Train
other people. It sucks being one of the only few who are leading by
example, but fuck it it's not effective.

-Jonathon Key

**Comment by TheDavestDave** [comment]
I am not the example engineering wants
Nore am I the example engineering Needs.
Or could use

**Comment by TheDavestDave** [comment]
I can't think of any good examples come to think about it. The few good engineers we have working currently really dislike teaching. I hate teaching because I think I'm personaly responsable for every one of Josh's mistakes

**Comment by SpadesNeil** [comment]
That is why we have a manual. If people decide they don't want to learn how to do their job properly, they will get job banned.

The Tesla works exactly as intended. It's Engineering players who are broken. I say let them suffer.

**Comment by ArgobargSoup** [comment]
@SpadesNeil I do agree with your points, but to be fair, it's not just the engineering players that suffer from an engine failure/explosion.  :P

...Maybe a big fat "READ THE ENGINE MANUAL" message added to the start message for engineers...

**Comment by SpadesNeil** [comment]
I have no such intention. They should know to do that already and yelling it in their face isn't going to make them start following common sense if they won't do that already.

Instead, we'll just punish the people who are too stupid to get it right. Note, stupidity is defined as ignorance that is not learned from when you fail. Ignorance is one thing. You screw up, you fail, you know better now... but stupidity is something else, and stupidity will net job bans.
