### ISSUE TITLE
mobs ignore mechs

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3734]
#### Brief description of the issue
if all players are in  mechs V4 cave mobs don't move and ignore you. If you jump out of the mech. They will solo you and ignore the mechs shooting at it to get you

#### What you expected to happen
Us bringing three mechs into the caves to stomp everything quickly. Then the admins to spawn big scary thing we will struggle to take down, then go home with briging rights about how we killed a pack of super deathclaws and our mech on mech battles

#### What actually happened
We decided to be sporting and demount. Then got gangbanged by 4 combat drones while on foot.

#### Steps to reproduce
- (Step 1)all get mechs
- (Step 2) go in cave

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
c973f8672a981994941b90fc583c88c1ddab5fac  
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I still can't be a micro explorer. I made a git hub thing instead of complaing about it in discord.

**Comment by SpadesNeil** [comment]
Do they ignore mechs completely, or just attack mobs on foot before caring about mechs?

**Comment by TheDavestDave** [comment]
they ignored mechs inteirly. If everyone was in a mech, none of the mobs would move in the map

**Comment by TheDavestDave** [comment]
also why is this closed, how did I close this?

**Comment by SpadesNeil** [comment]
Okay that is a pretty bad problem then. They should not ignore mechs completely.

**Comment by TheDavestDave** [comment]
the ai didn't appear to be on, only moveing if someone was outside of a mech....if admins loocs were anything to go by

**Comment by Very-Soft** [comment]
I have observed this too. 

Being as mobs are 'asleep' until a player enters the Z, I suspect that the mobs are not waking up when a mech enters the zone first, because the people are still in the mech. Haven't been able to test it myself yet though, so that's just my hypothesis. 

Mobs seem to still not wake up though usually when people exit and leave the mech too though. Perhaps it only checks for them to activate the AIs where they're likely to teleport into the map?

**Comment by Arokha** [comment]
It's likely what Soft said. There's no way to fix this that doesn't generate lag though, unfortunately. Not sure of the best, least-expensive way. ALL of them will increase how long it takes to do a life() tick.
