### ISSUE TITLE
New borg weak enough to take on away missons

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3735]
#### Brief description of the issue
the currents borgs are too OP and lawed to stay on the station. 

#### What you expected to happen
there to be some kind of away misson borg

#### What actually happened
all too OP

#### Steps to reproduce
- (Step 1) be borg. Be OP. Have law to protect the station

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 c973f8672a981994941b90fc583c88c1ddab5fac 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
my idea is to have a modifed vertion of the service borg. That can produce ration packs, and inject people with tricord, with it's own laws for the away team only. It would also have it's AI powers removed. It should have a crow bar to it can Meele/open unpowered doors too. This would make it so it could aid in many things, but not replace anymember. It can heal people, but the SAR does it better. It can open places but the Engineer does it better. It can give you food, but you'd much rather bring a packed lunch

**Comment by Verkister** [comment]
Why would the expedition even take this kind of borg with them instead of the regular crew members who would supposedly be the better choice than the walking vending machine in every way then?

**Comment by Very-Soft** [comment]
I mean, the borgs could go with you if they really wanted to and you asked them to There's nothing in their laws that requires them to STAY on the station if the crew's asked them to go somewhere else just, the station and its crew's wellbeing are their top priority. So like, I'd think that a medical borg could go on the shuttle if there's other medical staff active, but there's no SARs. An engi borg could help to build a base, etc etc. I think the only one I sort of have an issue with going on away missions tbh is sec borgs. 

I don't think it's a good idea to have a 'this is the borg for going on away missions'

I think borgs are pretty fine how they are for the most part, tbh.

That said, I don't think that any borgs should have to go with the excursion team if they don't want to. If a borg told you they can't leave the station, they probably just didn't want to go.

**Comment by Natje0** [comment]
I'm with Soft on this, as I'm not a fan of borgs on expeditions at all. IMO, their place is on the station, and if they want to go exploring, they shouldn't go borg.
