### ISSUE TITLE
Itemweak digestion breaks IDs

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3745]
#### What you expected to happen
For things to not get ruined if they aren't being digested

#### What actually happened
Everything is dirty, which is fine, but ID is ruined!

#### Steps to reproduce
- (Step 1) Get ate
- (Step 2) Get gurged by something with itemweak digestion on

#### Code Revision
- release - 
c973f8672a981994941b90fc583c88c1ddab5fac
 
#### Anything else you may wish to add:
- A credit card can get wet and be fine as far as I know, being as it's mostly plastic with a magnetic strip. That seems to be more or less what the IDs are. As such, I don't think it should end up damaged from itemweak, as that's annoying to get fixxed if there's no HoP available, when the thing you got gurgled by is clearly set to not ruin all your things if it's on itemweak.

**Comment by Arokha** [comment]
Is on purpose. It was requested by Ace that no IDs ever be able to be taken from prey with full access, so contaminating them also erases them just like digestion does.
