### ISSUE TITLE
[MAPPING] RD doesn't have an intellicard in their office

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3749]
#### Brief description of the issue
What it says in the title. The RD, the person whose job it is to deal with the AI most of the time, doesn't start with an intellicard in their office anywhere like they're supposed to (if we're going off other servers). This prevents them from doing some of their AI related duties unless R&D is done and they can be printed, which is a bit of a pain. Also @Mewchild because they asked me to mention them.

#### What you expected to happen
I'd have _all_ my job-related equipment in my office.

#### What actually happened
Intellicard MIA.

#### Steps to reproduce
- None, it's a map issue.
 
#### Code Revision
- release - 
c973f8672a981994941b90fc583c88c1ddab5fac

**Comment by Mewchild** [comment]
Thank you. Got an email about the issue. Will sit down and hit it on my next session

**Comment by Mewchild** [comment]
There is absolutely an AI card on the bridge. It's on the table
