### ISSUE TITLE
Breadcrumb not showing

### ISSUE THREAD

**Issue by RishabhRkRai** [VOREStation/VOREStation#3751]
#### Brief description of the issue
I upgrade the Magento version to 2.2.4 and now on product page breadcrumb is not showing.

#### What you expected to happen
Breadcrumb has to shown on product page.

#### What actually happened
Breadcrumb is not showing on the product page.

#### Steps to reproduce
- Upgrade Magento version from 2.1.7 to 2.2.4
- Run all the magento commands after upgrade.

#### Anything else you may wish to add:
- Nginx server

**Comment by RishabhRkRai** [comment]
Where I suppose to post this @Heroman3003 ?

**Comment by Heroman3003** [comment]
This is github for SS13 server build, which your issue seems to have kinda nothing to do with?

**Comment by Little-119** [comment]
@RishabhRkRai I'm fairly certain that you meant to submit this issue to https://github.com/magento/magento2. This is a git repository for a video game server mainly centered around eating other people whole for the purposes of sexual arousal, not a git repository for ecommerce software.

**Comment by Arokha** [comment]
Wrong repository.

**Comment by Mewchild** [comment]
Also, being tongue in cheek? This is a duplicate of https://github.com/magento/magento2/issues/15490

**Comment by SpadesNeil** [comment]
I can't help but wonder how on Earth this mistake was made. You went from
what I assumed to be some sort of legitimate consumer product to a video
game run by perverts and furries. You've taken a wrong turn into the weird
part of GitHub.

**Comment by RishabhRkRai** [comment]
It is placed here by mistake. I'm really sorry for this. I didn't notice the repo.

**Comment by SpadesNeil** [comment]
Don't worry, I just find it hilarious. Cheers mate.

**Comment by pini-girit** [comment]
Do you have a custom top-menu?
-- if so, that might explain... you may try my workaround from [here](https://magento.stackexchange.com/questions/227232/magento2-breadcrumbs-disappeared-from-product-page-after-upgrading-to-2-2-4).
