### ISSUE TITLE
Virgo 4 too hard

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3766]
#### Brief description of the issue
the amount of deathclaws in the virgo 4 caves keeps sending teams home, while it is rare for teams to leave virgo 2 with injures that require flying home for medical treatment

#### What you expected to happen
virgo 4 to be the easy one, and virgo 2 to be the hard one

#### What actually happened
virgo 2 is just hard to get to, while 4 is easy to get to and hard to do

#### Steps to reproduce
- (Step 1)go to V4 caves
- (Step 2) you weren't useing that head the deathclaw just ripped off anyway

#### Code Revision
2616b963a0136fe21106af82982914ec8c1db2b9 
 
#### Anything else you may wish to add:
maybe we should add more mobs to the V4 spawn lists. Maybe a territoral herbivore, seeing as it is a plannet full of meat eaters. Or some kind of hostile plant

**Comment by Ketrai** [comment]
Would be neat to add more mobs, maybe not all hostile ones... it's kind off annoying that deathclaws constantly respawn, so  you always have one around the corner...

I wouldn't say they're too strong, just common. if one gets you, just lie down and let it eat you, your team can take it.
