### ISSUE TITLE
Character creator doesn't switch to female body sprite

### ISSUE THREAD

**Issue by blazerules** [VOREStation/VOREStation#3767]
#### Brief description of the issue
Select female gender. Dont get female body type. I'm not sure when this became a thing but I noticed how this wasnt the case a few months ago and the body type did change from male to female when you switched genders. I spoke to a few people and apparently its not a thing that just happens to me.
#### What you expected to happen
Male body sprite to be changed to female.

#### What actually happened
Male body stayed regardless of gender choice.

#### Steps to reproduce
Create new character
Switch genders to female
Stay male

#### Code Revision
release - 
2616b963a0136fe21106af82982914ec8c1db2b9 
 
#### Anything else you may wish to add:
https://image.prntscr.com/image/e6JWwHkpTQioZUwrKo-5cA.png

**Comment by kcin2001** [comment]
yeah this has been a thing since forever, but noone really minds because the proper sprite is done ingame
