### ISSUE TITLE
add Virgo 3b wilderness back so explorers can have a job when nobody wants to play pilot

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3768]
#### Brief description of the issue
Explorers don't have a job unless someone plays pilot. SAR get full medical access. Pilots don't really have a job as is other than ferrying people. 
#### What you expected to happen
to be able to make myself useful if no pilot shows up
#### What actually happened
I am playing warthunder alt tabbed because no pilots show up. Miners real;y don't like me going into the underdark, and there is little reason other than to shoot things.

#### Steps to reproduce
- (Step 1) request a pilot when you are ready to go
- (Step 2) give up and put you knife, baby knife, and phaser back in the locker room
- (Step 3) wonder why you sat at your PC for 5 horus to do nothing because you have to be ready to leave on the odd chance a pilot turns up
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 2616b963a0136fe21106af82982914ec8c1db2b9 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Ketrai** [comment]
If it isn't as buggy as last time? also this might cause issues because if people go in the wilderness whilst others go on expidition... LAAAAAAAAAAAAAAAAG?

**Comment by Very-Soft** [comment]
I mean, if you put out a request for a pilot, and no one comes within an hour, it's probably fair to fax CC to see if you can just leave without one, since explorers and SARs can also fly it. 

But I do also like the idea of adding the wilderness back.

**Comment by Rixunie** [comment]
SAR can explore the under-dark and help with general science stuff.. given, you know, they are -field scientists-

**Comment by SpadesNeil** [comment]
I would like to re-add Virgo 3b wilderness, but am unsure how to reintroduce it without it being boring. There must be a purpose to exploring.

**Comment by SpadesNeil** [comment]
@Novacat Why was this one closed?

**Comment by Screemonster** [comment]
@SpadesNeil wilderness/plains was re-added in #4648

**Comment by SpadesNeil** [comment]
Sweet.
