### ISSUE TITLE
Space lube is God in lube form.

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#377]
Space lube, cant be cleaned, there is no way of cleaning space lube at all.

Space lube should flush away like water does after a minute.

You cant clean it and it will never go away, you cant walk past it, once a tile has been lubed it will stay lubed from the entire shift, It cant be cleaned with water, cleaning granades, using soap, space cleaner, using a mop, we even tried burning it and taking the tile.

Simply lube a tile.

**Comment by SpadesNeil** [comment]
Please include server revision in future, though I know this to be an issue upstream too.

**Comment by SpadesNeil** [comment]
This is probably fixed, but please confirm.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
