### ISSUE TITLE
Explorer voidsuits make ears, tails, and hairstyles disappear on Vulpkanin

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#3770]
#### Brief description of the issue
What it says on the tin

#### What you expected to happen
Equip voidsuit, have a voidsuit show up on sprite

#### What actually happened
Equipped voidsuit, became naked walking potato-dog man hybrid

#### Steps to reproduce
Grab explorer voidsuit from storage
Put it on
Become potato
#### Code Revision
Current, at work so I can't get more specific

**Comment by Ketrai** [comment]
This is because voidsuits have a tag on them that makes them hide these things. I don't know why, but they are coded like that. Is it all voidsuits? or just the explorer one? I'm going to wait on more details... I remember I saw this when making my fluff item, and I disabled it for my fluff item.

**Comment by SigholtStarsong** [comment]
I haven't done further testing. However, the sprite itself does not appear.

Edited issue to be more accurate.

**Comment by SigholtStarsong** [comment]
![before](https://user-images.githubusercontent.com/16483818/40583555-b2e42e16-6156-11e8-87d6-63ae65f252ca.JPG)
![after](https://user-images.githubusercontent.com/16483818/40583554-b214b5a0-6156-11e8-994e-41c0677adcfa.JPG)

**Comment by Ketrai** [comment]
i thijnk this is a known issue
