### ISSUE TITLE
People in AR can understand mice

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3772]
#### Brief description of the issue
AR/soulcaught people can understand mice.

#### What you expected to happen
Squeak squeak

#### What actually happened
Legible mician speech.

#### Steps to reproduce
- Be soulcaught/an AR
- Listen to mice going deus vult

#### Code Revision
- 2616b963a0136fe21106af82982914ec8c1db2b9

**Comment by Ketrai** [comment]
Ya know, sometimes technology transcends native boundaries.

**Comment by Heroman3003** [comment]
This, among with a huge variety of other cross-species understanding issues with AR, is still true.
