### ISSUE TITLE
Belly noise settings don't actually help in the slightest

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#3774]
#### Brief description of the issue
So after many complaints, a feature was added to global prefs to disabled the noises of digestion and eating...but these prefs don't kick in unless you leave and rejoin, so if you don't have them toggled when you join, you're boned. Not only that, but it seems like they don't turn off the 'hungry stomach' noises people can have on and that's..._really_ annoying to have to listen to, so annoying in fact that sometimes I'm tempted to just tackle and forcefeed the people that just go walking around with those damned noises enabled! Augh!

#### What you expected to happen
Changing the prefs in-game would allow me to no longer have to hear these noises when they become an issue.

#### What actually happened
Nope, I'm screwed.

#### Code Revision
- release - 
2616b963a0136fe21106af82982914ec8c1db2b9

**Comment by Arokha** [comment]
Interesting, so they DO work, but only if you set them before you spawn, or rejoin?

**Comment by HzDonut** [comment]
Oh yeah I worded that weird. Yes, neither the digestion nor the hunger noises will be disabled unless you change your prefs and completely leave the round and come back in.

**Comment by lbnesquik** [comment]
Unless i am wrong, the settings are actually working fine. They just aren't easy to change like most other noise variables. Sounds more like "Belly noise settings are not flexible." than them being utterly worthless.
