### ISSUE TITLE
Xenobotany doesn't like the farmbot

### ISSUE THREAD

**Issue by viv-eret** [VOREStation/VOREStation#378]
#### Brief description of the issue

The farmbot doesn't recognize the Xenoflora lab as a valid place to operate.

#### What you expected to happen

I expected the farmbot to water plants.

#### What actually happened

I dragged it  by the public garden and it worked.
#### Steps to reproduce

Make a farmbot and bring it near the lab.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Needs testing to determine what areas it does and does not work.

[x] Xenobotany - FAIL
[ ] Garden - PASS
[ ] Botany
[ ] Elsewhere

**Comment by viv-eret** [comment]
Botany and Garden work. Xenobotany does not.

**Comment by SpadesNeil** [comment]
Set up a garden somewhere unusual and try it.

**Comment by SpadesNeil** [comment]
Removing blocker because this doesn't stop farming.

**Comment by DemicusMaximus** [comment]
Seems to be working fine now. Suggest this be closed.
