### ISSUE TITLE
NIF loss due to abduction event?

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#3784]
#### Brief description of the issue
A user reported an issue whereby they lost their NIF due to dying after being abudcted (by the UFO).

#### What you expected to happen
Not that

#### What actually happened
Lost

#### Code Revision
- Master as of 05/28/2018, around 5c4bde965a41345873f5c90f052dabb77d8b2e25
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Rixunie** [comment]
You lose your NIF on cloning, don't you? I've lost my NIF every single time I've died and been cloned.

**Comment by jakeramsay007** [comment]
@Rixunie Only if you haven't got a backup implant. If you've got a backup implant, the NIF is supposed to clone with you and in most cases does.
