### ISSUE TITLE
Medihound's medibelly has run away

### ISSUE THREAD

**Issue by Xonkon** [VOREStation/VOREStation#3787]
#### Brief description of the issue
Medical Belly is not selectable from the list of 

#### What you expected to happen
Use the medical belly to ea- heal people.

#### What actually happened
Medical belly has run away and cannot be used or accessed

#### Steps to reproduce
- (Step 1): Be medihound
- (Step 2): attempt to use medical belly
- (Step 3): Fail

#### Code Revision
- 2616b963a0136fe21106af82982914ec8c1db2b9

**Comment by Arokha** [comment]
Introduced by 1a6441cbcb7742841044b47ed0db7e5312ce8d83
