### ISSUE TITLE
Evidently there's a chance for a crew member to be immune to antibodies?

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#3789]
#### Brief description of the issue
Same as title

#### What you expected to happen
Someone is sick, and the last symptom is gibbingtons, oh no. That's okay, though, cause after a few minutes we made antibodies and just in time, too, because the third symptom just showed up in our patient.

#### What actually happened
They were immune to the antibodies and died.

#### Steps to reproduce
- Get fucked by rng/ staff and have a virus.
- Get fucked harder by rng and be incurable.

#### Code Revision
- )
#### Anything else you may wish to add:
- Not entirely relevant here, since we don't have Virology events with lethal symptoms. Figured it's worth looking at regardless. -- https://github.com/PolarisSS13/Polaris/pull/4707 -- may have resulted in this. Instead of someone simply not producing antibodies, they'll produce antibodies, the antibodies will simply not **work** and they're impossible to fix, making lethal viruses just a death sentence that you might as well cryo over because it isn't getting fixed ingame.

**Comment by Arokha** [comment]
You'd probably be better off reporting this on Polaris.

**Comment by Arokha** [comment]
I can look at it and see if I can see a way to fix it, but I know nothing about virology code so I'd have to learn the whole thing just to look at this, and I'm not suuuuper sure that's worth the time when Polaris might just know about it and fix it if you report it there.

**Comment by Wickedtemp** [comment]
Closing this, because it's been open for so long that either it's fixed by now, or it never will be, or it doesn't need fixing. And I'd like to make a small dent in the absurd number of git issues
