### ISSUE TITLE
Tether still lacks casual loitering areas.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3790]
#### Brief description of the issue
Tether is still lacking non-remote casual hangout spots. The public hangout spots we currently have are all either in remote edge locations or away from traffic. For example, bar, pool, library, public garden, cafe, and the one seated smoking nook near reading rooms are in remote locations at the edges of the station far from any traffic apart from the people who are intending to go there and are expecting something to be already happening there. And for the other part, the central hangout areas are not very close to "busy" areas, such as the atrium pond hardly getting more traffic apart from people busy just arriving/leaving/heading to dorms and miners heading out or returning for deliveries, and the station side koi park and holodeck essentially having the same situation but with explorers instead of miners, library instead of dorms, and cryo instead of tram, and occasionally engies/heads accessing lift or their departments.

#### What you expected to happen
Better chances of meeting, interacting, and hanging out with people without isolating to departments, singular edge spots, or borderline deserted public areas.

#### What actually happened
The public areas not secluded away from general traffic are hardly but deserted ghost town highways furnished for use as nothing but mere roads.

#### Steps to reproduce
- (Step 1) Exist on a decently populated station with a crew more than capable enough to surpass the busy labor requirements.
- (Step 2) Wander off from your cozy department or other secluded hangout spot.
- (Step 3) Even tumbleweeds have deserted these ghostly ~~high~~hallways. For some reason even the radio communications suddenly feel ominously silent from this perspective.
- (Step 4) Witness a fellow lost soul but find out they're already busy leaving the station.

#### Code Revision
- 2616b963a0136fe21106af82982914ec8c1db2b9
 
#### Anything else you may wish to add:
- Locations here are the general areas between departments and other edge spots.
I have couple vague ideas involving some additional furniture/decor, and sacrificing some of the maintenance/storage areas near the elevators on station levels 2 and 3, and the planetside level 3. Also balconies.

**Comment by Heroman3003** [comment]
There's also park on asteroid 1, but yeah, generally agree on the general intent behind the idea.

**Comment by Verkister** [comment]
Yeah, there are basically no public hangout areas anywhere between active departments.

**Comment by Very-Soft** [comment]
If you suggest some ideas, I can try to map them. There used to be more tables and chairs around, but they were removed for some reason. Not really sure why.

**Comment by Verkister** [comment]
Made some quick half-assed ideas for some locations.
https://i.gyazo.com/487923fe2487278be445cf14151c0a05.png
https://i.gyazo.com/d6667a4dcf7d9c1e1a07d94074e9d985.png
https://i.gyazo.com/d164e020aa1a9006b5aceb923a381349.png
https://i.gyazo.com/acf1dd46922976372bd7cf8cd724d13e.png
https://i.gyazo.com/151f48d0e02ea317794e4fd742e0173b.png

**Comment by SpadesNeil** [comment]
Aside from the last one, which I demand be untouched for fire safety reasons, the rest are good ideas.

**Comment by lbnesquik** [comment]
https://github.com/VOREStation/VOREStation/pull/3796
