### ISSUE TITLE
Mimic crates drop their guts (literally) upon death.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3795]
#### Brief description of the issue
Their 'stomach' gets drop. Like, their literal stomach. Their vore stomach!

#### What you expected to happen
Not to find their disgusting internal organs on the ground.

#### What actually happened
A delicious invisible stomach on the ground.

#### Steps to reproduce
.1 Spawn mimic crate
.2 Kill it.
3. Right click it and witness the stomach.

#### Code Revision
2616b963a0136fe21106af82982914ec8c1db2b9 
 
#### Anything else you may wish to add:
N/A

**Comment by Ketrai** [comment]
Oh no! you've killed me! BLARGL! BURY MY STOMACH;
