### ISSUE TITLE
Brown waistcoat isn't.

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#3798]
#### Brief description of the issue
The brown waistcoat from the loadout menu...isn't brown. 

#### What you expected to happen
To have a dashing brown coat.

#### What actually happened
Ugly black.

#### Steps to reproduce
Take brown waistcoat in loadout.
Put it on
Frown

#### Code Revision
- 2616b963a0136fe21106af82982914ec8c1db2b9 
 
#### Anything else you may wish to add:
- Was on an unathi-base custom species with naga dual-color (taur) tail and Hands,Feet,Belly Color (Major, Female) marking.

**Comment by lbnesquik** [comment]
They are actually brown in the DMI's and i see no reasons for them not to be. Should be re-tested.
