### ISSUE TITLE
Laying eggs inside people causes severe glitching

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#380]
#### Brief description of the issue

Severe glitches after a player was egged and then released inside another player.
#### What you expected to happen

Releasing an egged person into another person should put the egg into whatever stomach their predator is in. The person getting out of the egg should also put them into that stomach.
#### What actually happened

Came on to answer an ahelp - Ainslie had eaten Aspii, who had West inside them, and subsequently let West out in an egg. After this, Ainslie started to experience inventory glitches, and finally _suddenly died_ with 300 toxin damage. West was also unable to OOC escape, though they did manage to resist their way out of the egg.
West's location var was Ainslie, not any one of Ainslie's bellies.
#### Steps to reproduce

Person A eat person B
Person C eat person A
Person A release person B in egg
Person B resist out of egg
#### Additional info:
- **Server Revision**: Server revision: release - 2016-06-15
  50aec7ce3f6e10a8cbdd4d96ecaf56a76ba4d2e8 
- **Anything else you may wish to add** 
  Possible fuckery resulting from resisting out of a locker that is itself inside another container.

**Comment by Cameron653** [comment]
Reopening this, as PR #382 is, apparently, causing more problems than it's worth. Did some testing on a test server and found out that it'd cause the egg to be put on any turf in the area if the pred isn't  eaten and lay an egg.  If they are eaten and lay an egg, it'll work like normal. Going to have to find another way to fix this.
