### ISSUE TITLE
All voidsuit helmets in EVA are doubled

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3800]
#### Brief description of the issue
All voidsuits in EVA except skrellian ones have two helmets 

#### What you expected to happen
Each to have one helmet to go along

#### What actually happened
Two-headed crew preparations?

#### Steps to reproduce
- Enter EVA
- Look at racks with voidsuits

#### Code Revision
- 2616b963a0136fe21106af82982914ec8c1db2b9

**Comment by Heroman3003** [comment]
Addendum: atmos voidsuits in atmos itself have correct amount of helmets and suits, but double masks and magboots.

**Comment by Ketrai** [comment]
This is because of taursuits, normally?

**Comment by Heroman3003** [comment]
Long fixed.
