### ISSUE TITLE
Suggestion: A perk for a muffled belly/some privacy please?

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#3803]
The idea would be for a perk of some kind so that a pred and prey can do kinky shit, in subtle, without having to constantly move away from people so they can't see. Some people enjoy the whole "You can yell but the walls block sound" or such. Would it be possible to program such a thing into the game?

Eg. prey -yells- in belly, only predator hears it. Prey emotes, only pred sees it.

**Comment by SpadesNeil** [comment]
Is duplicate. Beat you to it, Rix! :U

**Comment by Rixunie** [comment]
You fuck, I'm the one who told you about it!

**Comment by SpadesNeil** [comment]
![image](https://user-images.githubusercontent.com/6484985/40814612-2659f9c8-650f-11e8-8de0-e559b16468bf.png)
