### ISSUE TITLE
Suggestion: Make Xenobio not shit again.

### ISSUE THREAD

**Issue by Rixunie** [VOREStation/VOREStation#3811]
The Slimes in Xenobiology are instantly hostile, often attacking you within seconds, or within a -frame- of spawning, even with monkeys present. The slime taser stuns for a whole 2 seconds, making it virtually useless. The baton stuns for 5 seconds, which is about as long as it's battery lasts. It's hard to be a scientist, and study the slimes, when it's damn near impossible to get close to them to scan with a slime-analyzer or experiment on them, because they go red eyes within 5 seconds of you trying to inject them with anything. The level 3 suit does absolutely sweet Fuck-All when it comes to protection from them ("But it stops gene damage!" That doesn't fucking matter if they down you and stun you, and then rip your leg off.)

Please, I love Xenobiology; Xenobotany is cool enough, sure, but Biology has fallen far behind in terms of being able to play or enjoy, simply because "Hey, have some genetic damage, broken bones, and absurd brute damage." Can we triple the duration on the stun so we can at least safely walk in and examine them? The stun is so short I've had slimes KILL ME WHILE I WAS STUNNING THEM. Or maybe bring back the little machine/computer you stick them in?

**Comment by Zeldazackman** [comment]
This so much please.

It's been in a state of needing attention or a small rework for quite some time as there's been a "We'll get around to renovating the department at some point" notice on paper laying on a table within xenobio for months now.

Even having a slime-sky security bot along with assistance doesn't matter when they attack without mercy right upon spawning.

![k7bamvp](https://user-images.githubusercontent.com/17093432/40869154-d73ae282-65e3-11e8-9f1a-8e77bea9e446.png)

**Comment by Ketrai** [comment]
Raising the stun time is an easy temporary fix for this problem.

**Comment by SpadesNeil** [comment]
Marking this as bug because it sounds like this part of the game is straight up broken in terms of balance.

**Comment by Rixunie** [comment]
The in-game items outright tell you the stun times. It's like this on purpose, the descriptions written to explain it as such :/ For Slime-sky, the issue is that he fires a Xeno-taser.. meaning he's shooting every 2 seconds.

**Comment by Mewchild** [comment]
Shit. Grabbed the wrong url

**Comment by Zeldazackman** [comment]
Just a reminder of what old xenobio used to look like
![envd1w3](https://user-images.githubusercontent.com/17093432/44300920-aa643980-a2dc-11e8-894b-868be1e671ca.png)
