### ISSUE TITLE
Suggestion: Buildmode spawning with edited vars

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#3812]
#### Brief description of the issue
I wanted to spawn mobs based on one I had edited the variables of.

#### What you expected to happen
The mob I copied with Advanced Buildmode to give spawned mobs with the edited stats

#### What actually happened
It didn't, and the mobs died from the atmospherical conditions.

#### Steps to reproduce
- (Step 1) Spawn a mob
- (Step 2) Edit its vars
- (Step 3) Copy it with advanced build mode
- (Step 4) Spawn it. It won't have the edited vars, just the default ones.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 2616b963a0136fe21106af82982914ec8c1db2b9 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
This would be "hard".

**Comment by Very-Soft** [comment]
this would be super useful though, to be sure!

**Comment by lbnesquik** [comment]
This is probably polaris tier.
