### ISSUE TITLE
A way to stop explorer's bleeding out on virgo 2 over simple cuts

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3823]
#### Brief description of the issue
There is no shuttle support on virgo 2 surface because the air lock takes ages to cycle, and well as no capsule houses

#### What you expected to happen

"Mining is equipped for surviving solo in a dark, freezing,  toxic environment full of monsters that want to kill you for being  there. Explorers go as a team. And THEY GET A FUCKING SPACESHIP."-Screemonster 31/05/2018

#### What actually happened
there is a mini-shuttle to get back to the shuttle and air lock that takes ages to cycle, there no fucking spaceship. 

a fun fix would be a big gun or navigation jammer on the areostat that needs disabled to land the shuttle on the surface. That we would would have a space ship

**Comment by Rixunie** [comment]
Or you could bring an SAR that knows what the hell they are doing, not threaten to shoot them for small mistakes, and just, in general, act like a cautious scientist and less like a bloodthirsty murder-hobo
