### ISSUE TITLE
The observe button's warning about respawning lies

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#3828]
#### Brief description of the issue
When you click the 'Observe' button in the lobby, it says you will have to wait one minute.
Until now, that's been correct. Now, the respawn timer after observing is apparently _5_ minutes.

#### What you expected to happen
To be able to return to the lobby after observing for one minute.

#### What actually happened
Had to wait five minutes to return to the lobby.

#### Steps to reproduce
- Observe
- Wait for a period of time between 0 and 299 seconds
- Click 'respawn'

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
![](https://i.imgur.com/4zJIqiF.png)

**Comment by Natje0** [comment]
The bug is what the Observe button claims.

**Comment by SpadesNeil** [comment]
Did it actually make you wait 5 minutes, or did it just _say_ 5 minutes?

**Comment by Little-119** [comment]
Had to wait five minutes. I thought the screenshot showed that.
Either way, I'll test it locally now just to double check.

**Comment by Cameron653** [comment]
Portion of code involved:
https://github.com/VOREStation/VOREStation/blob/4cddf6ccd0f7552358042c918bd6324e4a9bf7d7/code/modules/mob/mob.dm#L376-L380

**Comment by Rixunie** [comment]
Thanks Polaris.

**Comment by Verkister** [comment]
https://github.com/VOREStation/VOREStation/pull/3881#issuecomment-397611226
Arokha: "It wasn't an oversight. I asked other admins at the time what they wanted to do and they said it was fine to leave as 5min."
