### ISSUE TITLE
Hostile mobs in virgo 4 should be rare

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3829]
#### Brief description of the issue
Virgo 4 spawn system is currently a sea of hostile with PoIs activng as the RP ensintive to go. Yet because of all the near non-stop fighting. It attract people who just want to shoot things. Double so as  it is the "Easy" place to go explore. It also stops any non exploration staff wanting to go. 

#### What you expected to happen
Hositle mobs to be a risk not a the main attraction

#### What actually happened
No matter how hard I try to RP, I get put in the bucket with the murder hobos. I will always be fighting people demanding mechanical changes that punish all explorers because of the people who just want to shoot stuff. Even if I am one of the shit ones that are the problems. Not every explorer should be punsihed for it.

#### Steps to reproduce
- (Step 1)Go to virgo 4
- (Step 2) Basicly play coloineal marines with deathclaws and frogs instead of xenomorth. Round ends if we die of find all the pois

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ad18753b9d6bfd50b51846b726f025f1e781a75c 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
everyone is complaining exploration is just there too shoot things. Even the vertrans would like a non-combat exploration map. The current one encourge the only there to shot shit playstyle we have now. The caves should be safe enougth to only have one or two armed people to explorer. It lets you bring press and other people who dislike fighting to explore the caves. It would even allow SARs to avoid fighting if there was a hostile mobs were rare isntead of just as common as the sand tile

**Comment by SpadesNeil** [comment]
_Stay out of the caves, then._

Seriously we already have plans to add a moon level with absolutely no wildlife to get killed by. The issue is, what else would be the point of going?

**Comment by TheDavestDave** [comment]
the PoIs, exploreing isn't ment to be murdering everything. And evenone gets IC shit from both charaters and centcom for doing that.
