### ISSUE TITLE
Job selection round start bugged

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3830]
#### Brief description of the issue
I can't join with pathfinder on high if someone else gets picked for pathfinder, even if I have other jobs on low prioty

#### What you expected to happen
If the sever picks someone else to be pathfidner (and it always does) it to selecet another job I have put

#### What actually happened
round started. Still waiting at screen with ready selected

#### Steps to reproduce
- (Step 1)pick pathfinder high priority and explorer low
- (Step 2)sever pick ascian over you 100% of the time
- (Step 3)Doesn't even let you join as explorer or any job you have put at a low piroity

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ad18753b9d6bfd50b51846b726f025f1e781a75c 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Mewchild** [comment]
Sounds like you just got bad RNG for it.

**Comment by TheDavestDave** [comment]
I have ready selected and it doesn't spawn me in. That is a bug. I have Explorer on medium and it still doesn't spawn me in but I stay at the ready, not ready selector (Even when there are no explorers). That is a bug

**Comment by TheDavestDave** [comment]
closeing the client between round fixes the problem
