### ISSUE TITLE
Ace needs to remove the Rave song

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#3836]
#### Brief description of the issue
Ace: "I should probably remove the rave song because it doesn't work the way it used to."

#### What you expected to happen
Rave song to work

#### What actually happened
Jukebox code got changed and broke rave

#### Steps to reproduce
- look in discord cadet-academy channel

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Current
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Mewchild** [comment]
Can you give more info on this? This is very vague.  Code Revision is ad18753b9d6bfd50b51846b726f025f1e781a75c

**Comment by Shophaune** [comment]
Instructions were to put a reminder on Github. Vague instructions, vague reminder.
