### ISSUE TITLE
Citalopram broken

### ISSUE THREAD

**Issue by JennaSilver** [VOREStation/VOREStation#3842]
#### Brief description of the issue
Antidepressant drug "Citalopram" no longer works properly, spams you with the message "Your mind feels a little less stable..."

#### What you expected to happen
After consuming I expected to feel calm and stable

#### What actually happened
After consuming, "Your mind feels a little less stable..." tick

#### Steps to reproduce
- (Step 1) Consume Citalopram
- (Step 2) Wait for effects

#### Code Revision
ad18753b9d6bfd50b51846b726f025f1e781a75c

**Comment by Heroman3003** [comment]
Thats... not appropriate issue form.

**Comment by JennaSilver** [comment]
Sorry, first time using github, updated.

**Comment by Screemonster** [comment]
![image](https://user-images.githubusercontent.com/14942479/41139399-347330bc-6adf-11e8-97b3-a0cc778c3de0.png)
Please use the search function in future.
