### ISSUE TITLE
Mob tooltip names now start with stray "E "

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3843]
#### Brief description of the issue
The part of the mob tooltips that shows the scientific name now begins with "E " in front of the name on all but crewpeople and uncatalogued life forms.

#### What you expected to happen
Just the scientific name to appear as before.

#### What actually happened
**Some Critter**
_E Scientific Name_

#### Steps to reproduce
- (Step 1) Find catalogued simplemob.
- (Step 2) Hover at 'em.
- (Step 3) E.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
That is the first letter of the genus for when they have a subspecies I believe. It's part of the scientific name.

**Comment by Verkister** [comment]
It never showed up before and I think it should in that case be "E. Name" with period if really added on purpose.
