### ISSUE TITLE
Cargo shuttle issue

### ISSUE THREAD

**Issue by Holyw33d** [VOREStation/VOREStation#3847]
#### Brief description of the issue

Well, after sending the cargo shuttle away from the bay their thrusters appeared to get stuck there.
#### What you expected to happen

I guess I expected it to work as always, without depressurizing the whole room.
#### What actually happened
It basically depressurized the room.

#### Steps to reproduce
- Request the cargo shuttle.
- Send it away.
- Get your internals on if you entering the bay.

#### Code Revision
- No idea.
 
#### Anything else you may wish to add:
- https://i.imgur.com/UBRaVb6.png

**Comment by Heroman3003** [comment]
It is known bug that only seems to happen on forced launch.

**Comment by ArgobargSoup** [comment]
https://i.imgur.com/FgpliyM.png

**Comment by Shophaune** [comment]
Goddamn it, again?

**Comment by TheFurryFeline** [comment]
Old bug that was effectively fixed with the supply refactor
