### ISSUE TITLE
Radiation Hoods do not spawn in radiation closets.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3857]
#### Brief description of the issue
No radiation hoods = no complete protection from radiation during SM set up. :(

#### What you expected to happen
Radiation hoods to be in their lockers.

#### What actually happened
None what so ever in engineering.

#### Steps to reproduce
- Join as engineer.
-Go to a radiation closest.
-Weep as you find only a suit and no hood.

#### Code Revision
ad18753b9d6bfd50b51846b726f025f1e781a75c

#### Anything else you may wish to add:
Holy crap, I can't believe nobody posted this here, even though people have complained about it several times?! Come on, people. If you see an issue, report it on Github! REEEEEEE!

**Comment by Cameron653** [comment]
Hmm. Looking through the code
https://github.com/VOREStation/VOREStation/blob/19cfaea56d66e7f5d281a7887e2c23be4dcaffaf/code/game/objects/structures/crates_lockers/closets/utility_closets.dm#L148-L158 (Closets should have the hoods)

https://github.com/VOREStation/VOREStation/blob/c93f0832edc5080a9501af04c13b9022df81f178/maps/submaps/engine_submaps/engine_sme.dmm#L173
(Supermatter engine should have the above closet spawning)

I'm not sure what would cause this. Is it always occuring at round start?

**Comment by MrSign** [comment]
From what I've seen, yeah. One solution is to use the radiation suit crate in hard storage, that contains hoods. But, right now. From what I've noticed. All radiation closets within Engineering DO NOT contain hoods.

**Comment by KasparoVy** [comment]
Better than only a hood and no suit.

**Comment by lbnesquik** [comment]
Bump for re-testing.
