### ISSUE TITLE
Suggestion: Build mode tool to create linked portals

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#3871]
Like the ladder tool, but for traditional step activated portals. Perhaps just make it an alternate mode to the ladder tool since it would be essentially functionally the same.

Makes more sense for a mysterious portal to be in some random spot on the station than a strange ladder a lot of times. You can also sort of do more with a step activated portal thing than you can a click activated ladder.

**Comment by lbnesquik** [comment]
This could reuse most of the build code for ladders except it would be triggered by walking into the portal. Copying wormholes, applying to the portal, giving new names and re-skinning should take at most 1 hour of actual work.
