### ISSUE TITLE
Weird basketball on health doll

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#3873]
#### Brief description of the issue
Health doll has a basketball?!

#### What you expected to happen
Regular health doll

#### What actually happened
http://prntscr.com/jubmy9

#### Steps to reproduce
- I have no idea what caused it.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c

**Comment by Very-Soft** [comment]
I'll tell you what caused it

https://www.youtube.com/watch?v=J9FImc2LOr8

**Comment by Heroman3003** [comment]
Does not seem replicable? Never saw that again, never anyone else reported it, probably weird one-time thing. May open again if ever shows up, but closing for now
