### ISSUE TITLE
Suggestion: Add more SweatMAX machines on station levels.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3878]
#### Brief description of the issue
No publically accessible SweatMAX machines on station levels.

#### What you expected to happen
To be able to buy a protein shake without having to travel to the base.

#### What actually happened
WHY DO I HAVE TO TRAVEL TO THE BAAASE?! FUUUUCK!

#### Steps to reproduce
-Join the round.
-Head up to the station.
-Look around for a SweatMAX you can use in the corridors.
-Cry as you can't find any.
-Beg medical to briefly let you into their breakroom to access THEIRS.

#### Code Revision
ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
-Please put them in every department, they are a GOD SEND for characters that get destroyed by hunger.

**Comment by MrSign** [comment]
**This is a high priority, work on this immediately!!!!!!**

**Comment by Very-Soft** [comment]
I actually did do this a little bit ago~

**Comment by Screemonster** [comment]
in the meantime you can go to cargo and order takeout. They do more than just pizzas now, they've got a chinese takeout and a burger joint on speed-dial.

**Comment by lbnesquik** [comment]
fixed by #3796

**Comment by Screemonster** [comment]
closing as above, re-open if you think it's still an issue, etc
