### ISSUE TITLE
how to teleport out of a mob from anyway and return to the teather safely

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3883]
#### Steps to reproduce
- (Step 1)have mob vore turn off (Might not be needed)
- (Step 2) get held by someone as a micro
- (Step 3) get said person eatten by a mimic
- (step 4) hit resist and wiggle out of the person after wards
-(step 5) the game will crash
-(step 6) your charater will be in the bottom coner of the surface map in the phoron)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ad18753b9d6bfd50b51846b726f025f1e781a75c 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SigholtStarsong** [comment]
Sounds like it's probably the default dump for items/mobs/objects it can't find a place for.

**Comment by KasparoVy** [comment]
Better than nullspace I suppose :laughing:

**Comment by Zeldazackman** [comment]
Yeah, there was an issue wherein certain setup options for characters would have them spawn outside in the very same location, always be ready to see some weirdness in that corner if you wait long enough.
