### ISSUE TITLE
Synthetics and Monitor heads

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#3902]
#### Brief description of the issue
Monitor faces for FBP's do not protect from phoron despite being a mask

#### What you expected to happen
To be fine from Phoron as it literally replaces my face

#### What actually happened
Eyes melted when I stepped outside.

#### Steps to reproduce
- (Step 1)Be a monitor head with a monitor screen.
- (Step 2)step outside and scream as your eyes behind the monitor screen melt.
- (and so on)

#### Code Revision
-ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Gonna say this isn't a bug. You can't just be immune to phoron just because you have a different face, for gameplay reasons. You still have eyes, the eyes organ, etc. Not gonna make it snowflake.
