### ISSUE TITLE
Advanced Who verb exposes stealthmins

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3905]
#### Brief description of the issue
The Advanced Who verb subtly hints out sneaky staff.

#### What you expected to happen
The Advanced Who not being a snitch.

#### What actually happened
The verb lists stealthmin aliases with inconsistent tabbing at the bottom of the list regardless of the alphabetical order.

#### Steps to reproduce
- (Step 1) Experience unexplained shenanigans when no staff is present.
- (Step 2) Hit that button.
- (Step 3) Witness the verb commit a subtle act of treason.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KasparoVy** [comment]
Snitches get stitches... Or in this case, hopefullu just a bugfix

**Comment by Novacat** [comment]
I think upstream fixed this?
