### ISSUE TITLE
Flying clumsiness issues

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#3906]
#### Brief description of the issue
When you fly, it's incredibly hard to RP being graceful, as walls, doors and even tables make you fall over painfully, making you have to endure quite a lot of painful chat-spamming if you were trying to do something nice in a scene.
It seems so clumsy as to be some kind of bug.

#### What you expected to happen
To be a graceful, elegant demon, floating over a table and landing next to my partner, or through a corridor or other nice setting. Mostly for RP stuff, I wanted to be elegant, slowly hovering around.

#### What actually happened
I flew like a crippled duck with 1 wing and bumped on every surface possible with little to no control.
At the speed I flew I should not be THIS bad. I could see it if I had a rocket strapped to my back, but this was... embarrassing.

#### Steps to reproduce
- Pick trait for getting winged flight.
- Pick some negative traits to balance it out (Which only makes this an even more bitter pill :S)
- Try to fly and do anything graceful.
- Be more clumsy than someone just awkwardly crawling over a table in a drunken stupor.

#### Code Revision
Server revision: release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
I'm not sure if there are balance reasons, but at least make an option to do graceful, slow manouvers or something... I feel like a joke with wings on and I've basically needed to *stop* flying, move somewhere and *Start* flying again to pretend I can fly like an elegant Demoness.

**Comment by Very-Soft** [comment]
While I'd like to see more done with flight, it's not really meant to be used indoors. You gotta keep in mind that you're flapping around with a wingspan larger than your character is tall realistically. You're gonna have very little room to do that indoors, especially where tables, walls, and doors are concerned. 

It's an intended thing for flying people to take tumbles when they fly into things that would impede their flight.

Flight in RP is much better done purely in RP, as opposed to doing it mechanics wise, as you'll run out of hunger pretty fast, and then fall down. Flight itself is much more really intended to allow for an extra movement option really. You can fly up and down outside, or in the atrium. This can allow for access to areas that only people who can fly can access, if you're willing to build said places.

You CAN fly in the more cramped interior places, but once again, you're flapping around with a large wingspan in a place designed primarily for normal sized humans to walk around, so care needs to be taken to not bump into things when you do so.

Or, you know, you could just walk.

**Comment by KasparoVy** [comment]
Walking briskly while vigorously flapping your arms. Screeching all the while...

**Comment by Screemonster** [comment]
I would kinda like flying to ignore floor effects though, such as lube and water.

**Comment by ktccd** [comment]
@Very-Soft Well.... that's one way to RP it... but my problem is that not only is the game a bit too laggy to do this, even if I want to, I have to basically hover my mouse over the 'hover' button to have a chance to react in time.
And this is despite flying being actually very slow, you crash into things uncontrollably. I don't see why *tables* smack you over either, or why your character doesn't at least slow down and stop in front of a wall, instead continuing at (suddenly accelerated impact-speeds) right into it and knocking themselves silly.

And why **can't** we have the option to RP more elegant fliers? It's not like having demons/harpies/etc with a wingspan of only a fraction that you actually need isn't breaking "realism" already. (Not to mention people who prefer RPing more sci-fi like aspects of flight and take advantage of our sci-fi setting to explain how they can pull it off, probably more common with synthetics I imagine)

As it is now, it feels like a joke on people who figured they'd make a flying character but didn't know about the trait already, but I guess it kind of explains why I so rarely see anyone flying, even when they have wings... because it makes you feel like your character is an idiot who flies worse than a drunkard walks. ((And yes, I **know** you **can** just walk.... but that sounds like a weird argument to me. I wanna have an elegant succubus flier, like... it's a whole aesthetics thing with demonic fliers...))

**Comment by TheMagicalFarmWizard** [comment]
I'd also like to throw in my two cents on this issue. I really think that if you're going to have them bump into everything and fall down after flying like 30 tiles then it either shouldn't cost ability points or carry some other kind of benefit like immunity to falling, because as it stands currently all it's really used for is moving between atrium levels and making your character float up and down.

**Comment by KasparoVy** [comment]
A shame but I don't see this changing much in the future. Will probably autoclose soon
