### ISSUE TITLE
Xenoarch Digsite Sprite Missing

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#3914]
#### Brief description of the issue
When digging at a site, just as I was about to reach the minimum depth for my 2nd finding (minus clearance), the sprite changed to... something odd:
![xenoarch_bugg_2nd_finding_digsite_107depth_maybe](https://user-images.githubusercontent.com/862727/41704606-fcfe3ad4-7536-11e8-8f0d-a85098e8cadd.png)

I had somehow unearthed such ancient findings that even their sprites were lost!

#### What you expected to happen
For there to not be a placeholder sprite.

#### What actually happened
There was a placeholder sprite when I reached... around depth 106 or something around there.

#### Steps to reproduce
- Well... I dug my 2nd finding in the same digsite, at depth 106 or maybe 107?
- Be super-duper new at xenoarch and patch together a method using books and wikis
- Find weird bugs

#### Code Revision
Server revision: release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 

#### Anything else you may wish to add:
Image should be attached above I think.
EDIT:
Upon unearthing the finding, the sprite remained the same, with no more findings left to... well, find.

**Comment by ktccd** [comment]
![xenoarch_bugg_more_pics](https://user-images.githubusercontent.com/862727/41705402-2604f362-7539-11e8-9766-284631d902af.png)
Update, it seems pretty consistent once I reach those bigger depths when looking for my 2nd finding in a site.

**Comment by Novacat** [comment]
Reported as Fixed.
