### ISSUE TITLE
Drop down Menu issues

### ISSUE THREAD

**Issue by VailTheWolf** [VOREStation/VOREStation#3920]
#### Brief description of the issue
New right-click menu problem

#### What you expected to happen
When you right click on the screen, a drop down menu shows the objects on a tile and then options for each of those tiles. 

#### What actually happened
See attached screenshot.

#### Steps to reproduce
Play on the current Beta Version of BYOND.
![screenshot 248](https://user-images.githubusercontent.com/20743763/41804103-c50071c8-765e-11e8-94d1-e1e5026c92f1.png)

**Comment by Arokha** [comment]
Would suggest not using that version for now.

**Comment by Arokha** [comment]
Lummox fixed this in 1429
