### ISSUE TITLE
Abandoned Crates could use better loot

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3923]
#### Brief description of the issue
Abandoned Crates from mining, despite now having a working anti-tamper, don't actually have anything inside them worth expending effort for.

Scree said put it here.

#### Anything else you may wish to add:
http://prntscr.com/jyk0bm

**Comment by InterroLouis** [comment]
Well, my first vote is to take out that silly two pairs of athletic shorts drop. And the stupid useless rubber glove toy!

**Comment by Cameron653** [comment]
It'd certainly be nice to make the abandoned crates worthwhile with actual interesting stuff for anyone that wants to play a quick game of bulls and cows. At the moment, it's pretty much useless to open them, other than the occasional chameleon clothing you can get from it.

**Comment by AaronSherwood117** [comment]
Personal suggestions in my head would be:
Mining Gear (Saves points!)
Ores or Sheets (Saves effort!)
Contraband (Emag, Translocator, Harpoon, the usual)
Xenoarch Statics
High End Mech Parts (Seraph, Phazon)
FATMOUSE
Pre-made mining bomb and signaller
Research Design Disks

And this is just GOOD results, could also make them have a section of dud or joke rewards.

**Comment by Screemonster** [comment]
oh shit mining charges are a good one

also fatmouse

**Comment by KasparoVy** [comment]
> Pre-made mining bomb
dud or joke rewards

Crate with mining bomb that explodes when you open it, confetti optional

**Comment by lbnesquik** [comment]
There is actually some pretty good loot in there. Xray mutations, actual katanas, lot of tools, energy swords and so on. Too bad they have a 1% chance to drop however.
