### ISSUE TITLE
The majority of left-facing window panes on the station level have 1,000,000 health.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#3924]
#### Brief description of the issue
See title.

#### What you expected to happen
For the window panes to have normal health or at least be consistent between other window directions. Seriously, the medbay bathroom windows are nigh indestructible. 

#### What actually happened
The windows were infused with impervium, but only on left-facing windows. They're the strongest object in the game.

#### Steps to reproduce
N/A

#### Code Revision
N/A, as far as I'm aware this has been an issue since Tether was introduced.
 
#### Anything else you may wish to add:
- All left-facing windows in engineering (My bad)
- All left facing windows in medbay including those on the escape pod.
- All left-facing windows in the exploration hangar, including the shuttle itself.
- All left-facing windows in the multi-level construction area.

I'm currently working on an extensive map change to security, or at least a proposal of changes. Since this isn't a very urgent issue since no one's encountered this problem before, I'd really, *really* prefer this be fixed after my security proposal is merged/denied. I'll do it myself but include it in a separate commit, just wanted to make sure people know about the issue and to please not step on my toes with map conflicts.

**Comment by SpadesNeil** [comment]
Oh for fuck's sake, not again.

**Comment by KasparoVy** [comment]
Holy shite, PLASTITANIUM!

**Comment by Screemonster** [comment]
Whoops.

Can they still be deconstructed with the screwdriver-crowbar-screwdriver-wrench method?
