### ISSUE TITLE
Sleeving is non-functional on the master branch currently

### ISSUE THREAD

**Issue by jakeramsay007** [VOREStation/VOREStation#3926]
Probably worth a major bug severity tag.

#### Brief description of the issue
Resleeving is non-functional due to an inability to load biomass beakers into the clone pod.

#### What you expected to happen
To be able to load beakers with biomass in them into the clone pod to produce a sleeve

#### What actually happened
"The grower pod #1 doesn't have room for Biomass bottle."
Attempting to unload the non-existent beakers in the clonepod does nothing

#### Steps to reproduce
- Try to produce a sleeve
- Realise you can't load biomass beakers
- Cry and then make the dead person into a synth

#### Code Revision
- MASTER BRANCH, not released yet.
 
#### Anything else you may wish to add:
- Discovered this downstream and traced it upstream, it's a bug currently present on master.

**Comment by Arokha** [comment]
This actually seems like an odd bug whereby if the pod has 0 beakers you can never add a beaker. I'll look at it.

**Comment by Arokha** [comment]
This is a polaris bug.

**Comment by Arokha** [comment]
You can cherrypick the commit from the above PR if you want an immediate fix.

**Comment by Arokha** [comment]
Fixed
