### ISSUE TITLE
[Suggestion] Ingame bulletinboard for people to seek out open scenes IC.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3933]
#### Brief description of the issue
There is currently little to no way to actively seek out scenes IC without going loud over radio or arbitrarily soliciting folks in person or via PDA. This is a suggestion to give people means for some sort of IC open lfrp with a board to put notes on and hoping someone equally bored reads them.

#### What you suggest to happen
Adding and mapping in a convenient personal ads bulletinboard for people to arrange funtimes IC hassle free. Preferably having the papers provided and not too subtle with looks.

#### What's currently happening
People are pretty much limited to OOC set-ups, public radio advertising, PDA spam, in-person soliciting IC or LOOC, or hunting for random encounters (tough luck on empty station), with success/risk/effort/nuisance rates being all over the place.

**Comment by Screemonster** [comment]
You can already just create a personal ads feed on the newscasters. There's been a couple of times that enterprising librarians have run dating agencies through them.

**Comment by Verkister** [comment]
Preferably something less subtle and reliant on the crew being competent newscaster enterpreneurs. Guess it works though as long as someone keeps regularly telling people to look into those.

**Comment by Screemonster** [comment]
See, I would absolutely be up for an OOC-note-browser. Pop it on the advanced-who list or something.

Since it's never actually used for events, I'm sorely tempted to say giving people the vore-antag HUD as a toggle would be useful too, a nice big obvious indicator for "hey I'm actually completely open for unwilling scenes".

**Comment by Very-Soft** [comment]
WELL SEE, I've really wanted to use the vore antag hud, I've tried a lot of fiddling to get it to work, and I've asked others how to do, and no one seems to know. I suspect that it might be broken. BUT, having it be available to regular players would be pretty cool I think.

**Comment by KasparoVy** [comment]
ENHANCED PREDATOR VISION(tm)

**Comment by Little-119** [comment]
Maybe add a """dating""" app to the PDA and/or communicator and call it Gnawr.

**Comment by SpadesNeil** [comment]
Oh god that'd be funny. But we should keep it OOC.

**Comment by Verkister** [comment]
Hard to arrange all scenes OOC via DMs when ya hardly know a jack shit fraction of the people ingame.

**Comment by SpadesNeil** [comment]
... I don't think you understand what I mean when I say OOC.

I mean we're not adding a dating app. We can, however, add a scene finder functionality.

**Comment by Verkister** [comment]
Yeah I suppose. Not entirely sure how specific the OOC scene finder could be what comes to the prefs and what sort of scenes the people are looking for though. This thing however would be a pretty nice IC option to let people look for willing and consensual encounters without having to resort to the so called turnip behavior as their first impressions towards unfamiliar characters they might find interesting. Something little less blatantly OOC in "IC" as the current primary way of PDA messaging everyone with "((wanna scene?))"

Also we need to abolish the turnip concept. Shit's gotten stigmatized to the point where people are afraid to do any initiatives feeling too concerned of getting stamped as one for showing any active interest ingame.

**Comment by Verkister** [comment]
The word's been getting tossed around so liberally that it has essentially been memed into a synonym for any willing prey, and once that connection has been made and the usage exposed to new players, the open hatred towards the original turnip in the community has become a major concern keeping people from interacting with each other. With the harsh usage the word gets, it should be given a proper solid explanation somewhere visible enough for any prey-curious folks to read before mistakingly identifying themselves as "turnips" through the community jokestery. The ahelps won't be getting through if the people getting accused don't know the difference between aggressive turnip and the "meme turnip" (willing prey)

**Comment by SpadesNeil** [comment]
Well then I need to fix that.

**Comment by Zeldazackman** [comment]
<del>I hate to be that guy but I always thought that turnip was played by one of TASE's alts, really makes sense when they went on about rose a while back too.</del>

**Comment by Screemonster** [comment]
Wait, TASE was here? But no, willing prey aren't turnips. Turnippery goes beyond mere "willing" into outright pestering and refusing to leave the fuck alone when it's clear the prospective partner has no interest.

**Comment by Novacat** [comment]
Character Directory, implemented.
