### ISSUE TITLE
Pocket O2 tank overrides the anesthetic dispenser.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3938]
#### Brief description of the issue
Getting connected to the anesthetic pump for surgery connects the mask to the oxygen tank instead if you have one in your pocket.

#### What you expected to happen
To get KO'd for surgery.

#### What actually happened
Oxygenated agony as the anesthetic mask from the dispenser ends up supplying oxygen instead.

#### Steps to reproduce
- (Step 1) Get rekt at underdark while obviously having internals on and such.
- (Step 2) Fast forward to medical for repairs.
- (Step 3) Get hooked to the anesthetic pump after taking off your internals, still having the tank in your pocket though.
- (Step 4) "This anesthetic smells like oxygen... OH GOD AGONY!"
- (Step 5) Yeet that cursed pepsi can out of your pocket to try again.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
This is down to the priority of which tank is used. I've seen hilarious results of people turning their internals on to fill phoron cans for the radiation collectors, but because the phoron can was in their hand and the oxygen can was in their pocket or suit storage, they ended up getting a nice deep lungful of horrible killgas.

**Comment by Ornias1993** [comment]
As bay dropped support for the dispenser, it should now be fine and this could be close. Unless you guys opted not to use the new operating table.

Please also be ware this might still be an issue in my code:
https://github.com/Baystation12/Baystation12/issues/19248
