### ISSUE TITLE
Missing Roof on a space level room

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#3945]
#### Brief description of the issue
The maintenance room that looks over where the brig disposal goes to space has no corresponding roof on the level above.  This has somehow not resulted in disaster.

#### What you expected to happen
For the room to have a roof, or at least acknowledge the fact that it has no roof.

#### What actually happened
The room lacks a roof, and only ~~the madness that lays in looking up for a spessmen~~ shenanigans prevent it from venting to space.

#### Code Revision
- Server revision: release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 

#### Anything else you may wish to add:
- As someone brought up in the Discord, the most likely reason the room doesn't immediately vent is that the space tile above is just space and not "open space".
- The white square in both pics share the same XY coordinates.
![image](https://user-images.githubusercontent.com/19196710/42091237-6955e01a-7b59-11e8-86a2-ee3104036284.png)
![image](https://user-images.githubusercontent.com/19196710/42091251-7c2466c6-7b59-11e8-8b7f-5f8475607f4a.png)

**Comment by KasparoVy** [comment]
Amazing

**Comment by SpadesNeil** [comment]
https://cdn.discordapp.com/attachments/187013248309002240/462222776107925514/unknown.png How it looks in 3D

**Comment by KasparoVy** [comment]
Wow, blew my mind with that screenshot.
