### ISSUE TITLE
General Cryotube fuckery

### ISSUE THREAD

**Issue by Smdytb1** [VOREStation/VOREStation#3955]
#### Brief description of the issue
Apparently when you have someone in a grab, and you place them into cryo with a drag. the grab persists.

#### What you expected to happen
for the patient to go into cryo and only the cryo you dragged them into.

#### What actually happened
grabbing a patient and having them south east of the right cryotube will make your grab persist if you drag them. clicking on the other cryotube will clone them

#### Steps to reproduce
- grab patient
- drag to south east tile of rightmost cryo
- click and drag them into cryo
- click the left cryo
- watch as you have two patients now
- ejecting causes the icon to clone aswell outside

#### Code Revision
ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
![dreamseeker_2018-06-30_20-56-11](https://user-images.githubusercontent.com/13372034/42130198-4d95e1a6-7cab-11e8-827f-0f3453dac811.png)
![dreamseeker_2018-06-30_20-56-42](https://user-images.githubusercontent.com/13372034/42130199-52b3bb7c-7cab-11e8-88ef-df858bf11dbb.png)

**Comment by KasparoVy** [comment]
Amazing. This is the future

**Comment by Sebbe9123** [comment]
I didn't consent to my photo being taken ;~;
