### ISSUE TITLE
AI can see through walls

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3959]
#### Brief description of the issue
The station AI can see into certain areas, despite there not being camera coverage in those areas.

#### What you expected to happen
For AI view to be restricted appropriately.

#### What actually happened
Station AI can see into the dormitories, most of maintenance, etc

#### Steps to reproduce
- Play AI
- Fly around

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
- https://i.imgur.com/9eNAmxG.png
- https://i.imgur.com/fmDYyck.png
- https://i.imgur.com/tLYqCkM.png

**Comment by CameronWoof** [comment]
I almost want this to be a feature, just so the AI can peek into locked dorms to see if a crewmember we're searching for is in there.

**Comment by Heroman3003** [comment]
Cameras can be XRAY, no? I know some can at least.

**Comment by Mewchild** [comment]
Can confirm it's not because X-RAY cameras,
![image](https://user-images.githubusercontent.com/13400422/42134059-b98d3be0-7cf9-11e8-94b7-9543668f8645.png)
