### ISSUE TITLE
Block characters from joining round if their OOC notes are blank

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#396]
#### Brief description of the issue

Players who either aren't into vore at all or are not clear about preferences are causing problems by not filling their OOC notes, even though the rules say to do so. This is no longer practical to enforce the rule manually when there's no prompt to force players to fill this information.

We should make it so players cannot join unless their OOC notes section is filled out.

**Comment by ArgobargSoup** [comment]
I dunno.  Last I saw, some people still had their OOC pref stuff in their character's special description.

Might I suggest instead havin' a confirmation window pop up if their notes are blank, with a reminder ta fill out the notes or move their pref information ta said notes?  Maybe with a countdown on the "continue" button...

**Comment by SpadesNeil** [comment]
It would alert players "You cannot join because your OOC notes are blank. Please see server rules." I don't understand what you're asking for.

**Comment by ArgobargSoup** [comment]
As in, I remember seein' people with their OOC preference stuff in their flavor text instead of their OOC notes.

Was just an idea fer a confirmation window fer those people too lazy ta move the information.  But then again, blockin' might be a better idea.
