### ISSUE TITLE
Cyborgs don't eject prey when killed

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3963]
#### Brief description of the issue
If a cyborg, say, an unlawed one that's digesting a person against their will, is killed, it does not eject any of their prey. 

#### What you expected to happen
The person to be able to crawl out of the scrap pile.

#### What actually happened
Prey had to be admin-teleported to get them out of the VOID.

#### Steps to reproduce
-Feed person to a borg (dogborg in this example)
-Kill borg in attempt to get them out
-Person is still stuck inside

#### Code Revision
- release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- http://prntscr.com/k1gngo Exhibit A

**Comment by Verkister** [comment]
Was this using a vorepanel belly or sleeperbelly?

**Comment by Verkister** [comment]
Seems that simplemobs are the only mobs that do eject prey when killed. Player controlled borgs and human type mobs cannot do that. Not sure if that should be changed or so, considering the player controlled preds dying probably might not want to immediately expose their prey to the same death.

However the sickshot gun has 20% chance to eject the bellies on any "living" type mob, including borgs and humans, even dead ones. I also found out the sleeperbellies had missed their own death ejection feature from the original port, and got it fixed.

Also as player mobs, neither borgs or humans come with belly interactions, such as the escape chance, enabled by default, so unless the player has manually enabled those in their vorepanel, the sickshot gun is currently the only hope without admin intervention.

**Comment by lbnesquik** [comment]
I don't expect anyone to know that the sickshot works on borg, especially dead ones. It would be better to have borgs always eject or at the very least, let people slip out with a simple resist.
