### ISSUE TITLE
Cyborg Kill-Switch is GONE?

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3964]
#### Brief description of the issue
The ability to remotely kill or blow borgs has been removed from the control console.  This is a very very bad thing to have removed as it's the only really helpful failsafe if something needs to be dealt with RIGHT NOW and locking down doesn't tell you the borg's location.

#### What you expected to happen
To be able to detonate a borg that's gone rampant and admins haven't shown up yet.

#### What actually happened
Had to beat it to death with several people and blunt objects while it was locked down like that printer scene from Office Space.

#### Steps to reproduce
-Head to RD office
-Open Robotics Control Console
-Very Few Options

#### Code Revision
- release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
https://www.youtube.com/watch?v=N9wsjroVlu8
Scene in question; mentioned in section C

**Comment by SubberTheFabulous** [comment]
https://github.com/PolarisSS13/Polaris/pull/2087

**Comment by AaronSherwood117** [comment]
IC? It was being a shithead and it felt good.  OOC? I kinda forgot the disassemble steps and time was very limited.

**Comment by AaronSherwood117** [comment]
I suppose it's fine that it's gone, I'll just miss the old satisfaction of pressing the button.
