### ISSUE TITLE
Duplicate bodies on spawn

### ISSUE THREAD

**Issue by Keekenox** [VOREStation/VOREStation#3978]
#### Brief description of the issue

Multiple bodies spawn some times when you spawn in, they will be naked.

#### What you expected to happen

Just you to spawn when you chose a job at the lobby screen.

#### What actually happened

A lag spike caused me to be able to click the button 3 times in one single game tick.

#### Steps to reproduce
- (Step 1) Use an autoclicker to click your job when spawning latejoin.
- (Step 2) Cause some sort of artificial lag, that'd probably make it easy to reproduce.
- (and so on) Profit.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Mewchild** [comment]
Server revision: release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c
