### ISSUE TITLE
Omni filters once configured can't be reconfigured

### ISSUE THREAD

**Issue by Moltenkore** [VOREStation/VOREStation#3982]
#### Brief description of the issue
If you configure an omni filter the wrong way and try and reconfigure it to something else, it seems to just keep the original settings (or filter the wrong gas completely).

#### What you expected to happen
The omni filter should update with the new configuration.

#### What actually happened
The omni filter stays in either the old configuration or some broken configuration. (It's hard to tell) This occurs quite regularly in the engine room, the hot loop will filter out phoron if set incorrectly the first time and then fixed.

#### Steps to reproduce
- Setup the omni filter in a wrong configuration
- Setup the omni filter in the correct configuration

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- The reproduction steps above are actually a guess as to what is going wrong, however this occurs a lot more than it should in the SM engine as the hot loop will start losing phoron randomly or not filter out carbon dioxide etc. The only way to fix it is draining the hot loop and replacing the filters completely which usually involves ejecting the core.

**Comment by Gearshy** [comment]
https://github.com/VOREStation/VOREStation/issues/2021

**Comment by lbnesquik** [comment]
One PR should be closed if there is duplicates.
