### ISSUE TITLE
Deconstructing APC Frames gives more steel than it costs.

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3986]
#### Brief description of the issue
Making an APC frame takes two(2) steel sheets.

Deconstructing an APC frame produces five(5) steel sheets.

#### What you expected to happen
Two(2) sheet refund on the frame.

#### What actually happened
INFINITE CONSTRUCTION

#### Code Revision
release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 

#### Anything Additional
- I just wanted to build a room on deadpop pls no bulli admins

**Comment by lbnesquik** [comment]
This need re-testing
