### ISSUE TITLE
[Suggestion] Vox should have the Trash Can trait 

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#3988]
#### Brief description of the issue
Throwaway line on our lore page states that they have powerful digestive systems that let them process lots of things, and they'll sometimes swallow stuff to help handle tougher meals.  I think eating objects counts for this.

#### Code Revision
ad18753b9d6bfd50b51846b726f025f1e781a75c
 
#### Anything else you may wish to add:
I just really wanna be able to eat more things okay

**Comment by SpadesNeil** [comment]
I actually quite like this.
