### ISSUE TITLE
Money dub glicth

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4005]
#### Brief description of the issue
if you click the money pile just before putting it in the atm. Them put the whole pile into the atm. And click okay, money appears

#### What you expected to happen
no money

#### What actually happened
more money

#### Steps to reproduce
- (Step 1)get stack of thallers
- (Step 2) go to ATM
- (Step 3) aticiate money pile
step 4 put WHOLE pile in atm with menu open
step 5 click okay on the pile spilt menu and get extra money

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
probably worth testing upstream
