### ISSUE TITLE
Ingested reagents are bad

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#401]
#### Brief description of the issue
When ingested, things like poison berry juice are impossible to remove

#### What you expected to happen
Vomiting and things of that nature to remove them if they're not in the bloodstream yet

#### What actually happened
Them staying

#### Steps to reproduce
Drink poison berry juice

#### Additional info:
 - **Server Revision**: a3835cb52f954f5278d7987f458f75fa90ce61c7 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Asmerath** [comment]
oh shit! teaches you to eat Artemis!
SORRY!

**Comment by Arokha** [comment]
WELP. You CAN fix this. Activated carbon! You just eat carbon and it removes reagents from stomach.
