### ISSUE TITLE
internals turn themself off if you disconnect

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4011]
#### Brief description of the issue
title

#### What you expected to happen
them to be how I left them

#### What actually happened
I take phoron and oxy lost damage

#### Steps to reproduce
- (Step 1)be outside in space suit
- (Step 2) have modem die
- (Step3) have modem kill your charater when you reconnect

#### Code Revision
- (ad18753b9d6bfd50b51846b726f025f1e781a75c )
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ktccd** [comment]
Some details maybe, like... where you holding your tank in your hands? (And thus dropping it when falling over?)

**Comment by TheDavestDave** [comment]
It was connected to my suit

**Comment by Novacat** [comment]
Very minor visual issue. The UI icon for internals does not update properly if you log in.

**Comment by KasparoVy** [comment]
Bumping in hopes that this stays open - looking into this tonight to implement logic that checks active internal status and renders appropriate UI element state

**Comment by TheFurryFeline** [comment]
Resolved with #7342
