### ISSUE TITLE
Stairs are one directional

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4021]
#### Brief description of the issue
You can go down stairs but not up

#### What you expected to happen
Stairs to work like stairs

#### What actually happened
You can only go deeper

#### Steps to reproduce
- Go down stairs
- Try to go back up
- Be stuck below

#### Code Revision
- ab9727baf5e8ba523a071c136660d779bdfe909e 
 
#### Anything else you may wish to add:
Redundant issue, but just for formalities' sake making it.

**Comment by Arokha** [comment]
Appears to be caused by a change in Build 512.1436 of byond

**Comment by Zeldazackman** [comment]
Feel like folks would genuinely enjoy if there was another way added to the map to allow people to travel to and from the tether besides just the elevator or the shuttle that takes ages.

Now would be a perfect time for such a thing like public access teleporters or some sort of tube transit system that would be in line with the lore too.

**Comment by Ketrai** [comment]
Don't forget other servers already have tube transports to reach distant areas like the AI, or engine if they're off station. Making the mgo up and down wouldn't be a stretch. Maybe a little uncomfortable yeah.

**Comment by Poojawa** [comment]
As a passing test previously, the latest byond 512 version doesn't cause this issue with polaris

**Comment by lbnesquik** [comment]
I haven't tested it but i am prerty sure i went up stairs since then. Should be closed.

**Comment by Heroman3003** [comment]
This bug has been fixed within a day of appearing and should have been closed a long time ago.
