### ISSUE TITLE
Teshari broken again

### ISSUE THREAD

**Issue by JemliRoivas** [VOREStation/VOREStation#403]
#### Brief description of the issue
Teshari don't have the limited vision, lose their name so that emotes and LOOC have them blank, move at normal speed, and can't be picked up and such as normal.
#### What you expected to happen
Being a teshari as normal
#### What actually happened
Movement speed was normal, name lost, full normal vision.
#### Steps to reproduce
Play a teshari

**Comment by SpadesNeil** [comment]
Needs testing. If not confirmed still an issue, this will be closed.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
