### ISSUE TITLE
[SUGGESTION] Separate horns and ears to two different selections.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#4032]
I'm not sure if this is a reoccurring annoyance for anyone but myself but there is little to no impact for those that haven't experienced it but I've found myself unable to create the desired look of my characters, especially those that involve antlers. It's impossible to get common ear types such as canine, feline, elven, etc. *and* any type of antlers or antennae. 

As it stands the current list of selectable ears aren't very saturated with horns but eventually it might be more commonplace as the game evolves. I believe it would be a good investment to separate the current sprites and put them into independent categories so that it doesn't get as cluttered as our body markings list has become.

**Comment by KasparoVy** [comment]
The body markings list wouldn't be so much of an issue is there were buttons to change the order of markings applied to your character but I definitely agree with this suggestion for the separate ear/horn (or head accessory) selections.

**Comment by Little-119** [comment]
I've thought of this as well, as I considered giving my vulp-bot synth antennae in addition to his vulp ears (Although I don't know exactly how that'd look in practice)
