### ISSUE TITLE
umbrella too OP

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4040]
#### Brief description of the issue
Hail will pelt you to death regardless of what you are wearing. Rigsuit, hardsuit. Nothing stops it other than the umbrella. It makes it a must have items for miners. Hail able to go thougth what explorers try to steal for combat amour should not be able to be stopped by a simple umbrella

#### What you expected to happen
https://www.youtube.com/watch?v=ldVEoF0EH7o

#### What actually happened
https://youtu.be/BMUsSs9Kvf4?t=51s

#### Steps to reproduce
- (Step 1)go outside in hail
- (Step 2) get pelted to crit with a hard or rig suit on
- (step3) be saved by magic umbrealla

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 6831216aa58b34b2d6610f7de92c556b69272fbc 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
hail is also invisable if you dig a tunnel in the rocks but still does damage. I can't tell if it is amour pieceing hail, or has the active cammo amour equipment

**Comment by Mewchild** [comment]
Voidsuits not blocking weather is an oversight, and has been reported upstream: https://github.com/PolarisSS13/Polaris/issues/5412
