### ISSUE TITLE
Cyborgs see weather inside randomly

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#4044]
#### Brief description of the issue
Random tiles will appear to have the current weather outside upon them as a cyborg. The tiles themselves have no weather, as no-one else can see it and a photo shows nothing. But the bug persists when viewing through a security camera

#### What you expected to happen
Cyborg eyes to work

#### What actually happened
Phantom snow/hail/rain

#### Steps to reproduce
- Be a cyborg

#### Code Revision
- 6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/31856537/42759949-9c768422-8900-11e8-8bd6-b97c05ad13be.png)

**Comment by Arokha** [comment]
A bug that was fixed in byond beta 512.1436. Consider using that beta (or newer), which might resolve your issue.
