### ISSUE TITLE
The 7 minutes of tram have become 10 instead.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#4045]
#### Brief description of the issue
Something has recently changed the tram arrival time to 10 minutes from 7, but the announcement still states the time will be 7 minutes and not 10.

#### What you expected to happen
Honest tram announcement bringing us 7 minutes to tram.

#### What actually happened
Fradululent 7 minute announcement is handing out 10 minutes instead.

#### Steps to reproduce
- (Step 1) Survive to roundend.
- (Step 2) Hear the promise of seven minutes.
- (Step 3) Get ten instead.

#### Code Revision
- 6831216aa58b34b2d6610f7de92c556b69272fbc
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
Doesn't really make much sense for just the announcement to do that, considering how pretty much everyone will be relying on the wall displays showing the full 10 minutes as soon as the announcement has passed, thus still rushing in for the last minutes. And it used to be 7 minutes for both, the announcement and the timer before, so I'm pretty sure it's just an oversight with some recent configuration changes.

**Comment by SpadesNeil** [comment]
It used to be 10 minutes to arrive, 3 minutes to depart. That's not how it is currently?
