### ISSUE TITLE
Regenerate icons command doesn't do anything.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#405]
#### Brief description of the issue
The admin command to regenerate icons for a mob doesn't actually function.

#### What you expected to happen
For icons to regenerate.

#### What actually happened
Nothing.

#### Steps to reproduce
Change a mob's appearance with view variables and attempt to regenerate icons. Fail.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/fc059ab4e8af1bfa97e0ea521ede9ee49672ddb8

- **Additional notes**: Mobs with tails only have their tails updated. Nothing else at all.

**Comment by Arokha** [comment]
In the code it's got a comment of `For Legacy Support` on it. I'm assuming it's not really used anymore.
