### ISSUE TITLE
Candied/cearaled/grilled/baked micros

### ISSUE THREAD

**Issue by grey212** [VOREStation/VOREStation#4067]
#### Steps to reproduce
micro+candy maker= issue
#### Code Revision
6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
the cereal maker sprites are actually pretty cool

**Comment by SpadesNeil** [comment]
This is both hysterical and concerning. I know we should fix it but I don't want to.
