### ISSUE TITLE
IPC Issues

### ISSUE THREAD

**Issue by Asmerath** [VOREStation/VOREStation#407]
#### Brief description of the issue
One, IPCs need to eat food to charge and can not take their charge from an APC. 
Two, The Display monitor accessory can not be removed
Three, You cant eat food with the display monitor in your way
#### What you expected to happen
to eat via grab intent on an APC to charge
#### What actually happened
I need to eat food to charge
cant eat food with a monitor in the way.
#### Steps to reproduce
play an IPC with Display monitor accessory to start, then try and eat food.

**Comment by SilverTalismen** [comment]
IPC's, or FBP's as they are now on Pol or Synthmorphs here, Charge from the cyborg rechargers that are scattered throught the station, I agree removing the monitors is impossible and should be possible, eating food wouldn't do anything for you anyway

**Comment by Screemonster** [comment]
What ST said. Synthmorphs don't need to eat. ~they can totally cram crew down their gullets anyway though, 'cause it's fun.~
