### ISSUE TITLE
Sushi not made with fish

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#4079]
#### Brief description of the issue
Sushi is made with regular 'meat' and not raw fish.

#### What you expected to happen
needed fish to make sushi

#### What actually happened
slap meat, cabbage and rice, instead of fish, cabbage, and rice

#### Steps to reproduce
-use the recipe for making sushi

#### Code Revision
6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
I think we could have cargo have a way to order the fish we have in the code, in a freezer that is. then just replace the meat in the sushi recipe with x fish, and if possible replace the name of the sushi to match what fish was used in making it.

**Comment by SpadesNeil** [comment]
Polaris lacks fish items, but they should probably have our fish items.

I propose a sub-type of meat items called "fish fillets" that gets named (similar to burgers) when a fish is cut by a knife. This meat item would then get used in sushi and other dishes.

**Comment by Little-119** [comment]
Doesn't Carp fillet exist in this codebase and probably every other SS13 codebase?

Also, I think Paradise (and possibly other codebases) have a fishtank structure than can be used as a source of fish for cooking.

**Comment by Tasald** [comment]
if we could get the fish tank ported of that would be amazing, but ya, what Ace said sounds like a good plan to.
