### ISSUE TITLE
Xenochimera don't have any hairstyles

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#408]
#### Brief description of the issue
As title. The only hairstyle/facial styles are bald and shaved, respectively.

#### What you expected to happen
To plop the tajara messy hairstyle on and keep on truckin'.

#### What actually happened
Chrome-dome.

#### Steps to reproduce
Just spawn as a xenochimera.

**Comment by Screemonster** [comment]
Come to think of it, is there any reason hairstyles and facial hair need to be race-restricted anyway? :v

**Comment by SpadesNeil** [comment]
Yes. Many hairstyles include head tentacles and Tajaran ears and things that generally should not be present on other races because it looks terrible.

**Comment by Cameron653** [comment]
Going to fix the xenochimera hairstyles.
