### ISSUE TITLE
Self removing axes.

### ISSUE THREAD

**Issue by ProbablyCarl** [VOREStation/VOREStation#4085]
**Brief description of the issue**
- Axes vanish upon the opening of their cabinets.

**What you expected to happen**
- I had completely expected to get an axe.

**What actually happened**
- The aforementioned axe I expected to receive, has, for all intents and purposes, deleted itself from the game.

**Steps to reproduce**
- Go to any cabinet, and proceed to open it with a multi-tool. It'll delete on unlock or opening.
This issue has been observed with all cabinets aboard NSB Adephagia.

**Code Revision**
- [#4023](https://github.com/VOREStation/VOREStation/commit/6831216aa58b34b2d6610f7de92c556b69272fbc)

**Comment by Mewchild** [comment]
Fixed in https://github.com/VOREStation/VOREStation/pull/4065

**Comment by lbnesquik** [comment]
Status:resolved
