### ISSUE TITLE
SUGGESTION: Compliance laws in NIF need to be able to get purged.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4094]
#### Brief description of the issue
When you get compliance disk'd, the only way to get rid of it is to get your NIF removed entirely.

#### What you expected to happen
To be able to have a printable disk from Research that can purge laws without needing invasive surgery to remove said NIF.

#### What actually happened
Gotta detain those lawed peeps for surgery to get the NIF removed.

#### Steps to reproduce
-Have NIF
-Install laws onto NIF with a compliance disk
-Get NIF removed cause there's no way to purge laws.

#### Code Revision
6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment]
Sleevemate could do this perhaps

**Comment by Mewchild** [comment]
I strongly support this

**Comment by Heroman3003** [comment]
Ability to mess with programs on removed NIF manually is good idea.
However to adjust programs within one that's still in the head, I'd say some specific high-level and resources only tool.
Similarly to repairing it.

**Comment by KasparoVy** [comment]
Hard-reset by toolbox to the head.

**Comment by Screemonster** [comment]
Add a reformat disk that purges all nifsofts, compliance laws included. Getting that done at central is the fluff reason that you have to rebuy your nifsofts every shift anyway.

Dunno whether it should be available in all nifsoft vendors, but security and robotics should definitely have the means to purge nifsofts.

Making it purge _all_ software and not just compliance laws will make them have to think twice about just casually wiping people "just in case".

**Comment by Mewchild** [comment]
Putting the purge inside a NIFsoft vendor wouldn't make any sense, either way. No way to get the software disks out of the vendor, only the direct install software. Would be nice, but not possible now.
