### ISSUE TITLE
Xenobio electric walls only seem to shock crew, not the mobs.

### ISSUE THREAD

**Issue by KonBear** [VOREStation/VOREStation#4106]
#### Brief description of the issue
Electric grill on the inside of the windows in the Xenobio pens dont shock the mobs, only the crewmembers. 

#### What you expected to happen
When bad boi slimey attacks the grill, I expect him to be zapped for it.

#### What actually happened
Bad boi slimey breaks the grill with no issue

#### Steps to reproduce
- watch as a slime tries to break out
- laugh as you know the walls are electric 
- panic when it doesnt effect them

#### Code Revision
- 6831216
 
#### Anything else you may wish to add:
I say remove the electricity from the grills completely and upgrade the windows. But that is a hope and a dream.

**Comment by chaoko99** [comment]
this is still true.
