### ISSUE TITLE
Eaten Objects digest instantly

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#4109]
#### Brief description of the issue
If you eat an object with the Trash Eater ability, it instantly disappears regardless of damage settings or itemweak flags. 

#### What you expected to happen
Stuff in guts to cough up or keep as desired.

#### What actually happened
Poof

#### Steps to reproduce
Have Trash Eating, consume an object, open Vore Panel to check contents.

#### Code Revision
release - 
6831216aa58b34b2d6610f7de92c556b69272fbc

**Comment by ArgobargSoup** [comment]
Itemweak doesn't protect food items, but I'm assuming you're encountering this bug with the non-food items that Trash Eater lets you eat?

**Comment by Verkister** [comment]
I have plans figured out on how to make a slower, gradual item digestion. Gonna try to get the code done soonish.
