### ISSUE TITLE
The 'NSFW' gun's microbatteries cannot be recharged

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4117]
#### Brief description of the issue
The microbatteries of the NSFW cannot fit into a recharger, becoming useless if ever used.

#### What you expected to happen
To be able to recharge the batteries in order to utilise the NSFW again!

#### What actually happened
'This device does not have a battery installed into it!' B-but, it is a battery, game! IT IS A BATTERY!

#### Steps to reproduce
-Get a microbattery of any kind for the NSFW
-Attempt to fit it into a recharger
-Game tells you 'This device does not have a battery installed into it'!
-Try not to cry.
-Cry a lot.

#### Code Revision
6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
![microbattery](https://user-images.githubusercontent.com/33539568/43556863-48f7a284-9645-11e8-969f-a3dc3183f7a1.JPG)

**Comment by lbnesquik** [comment]
Sounds like an oversight or a 'feature'. NSFW batteries are actually magazines filled ammo looking like batteries. There is special snowflake code in the recharger to make them recharge. This require RETESTING.

**Comment by lbnesquik** [comment]
Well this is fucking wrong.

**Comment by Arokha** [comment]
As long as you don't mean that the gun is 'self-recharging', like I assume you mean sticking the entire gun into the recharger works. That's fine with me (though perhaps putting the magazine in would make more sense).

**Comment by king5327** [comment]
Ah, no, stick the gun in the recharger and it recharges all batteries at once, in the same time it would take a single battery to charge. The only issue is, it needs snowflake code in the recharger itself to work.

**Comment by Arokha** [comment]
Yes, that's a bit annoying. There should probably be a recharge_act(var/charge) on /obj/item that returns false if it can't be put into a recharger, or returns the amount charged, then false when nothing needs charging (so if an item already inside a recharger starts returning false, it must be done, so switch to the 'done' iconstate).

Or something like that. Not that you should do that right now.

**Comment by king5327** [comment]
recharge_act(var/recharger)
Returns <0 if not rechargeable.
Returns 0 if fully charged.
Returns >0 if charging

The numbers don't matter except if the thing doing the recharging knows how to handle them for that item specifically.

**Comment by Arokha** [comment]
That's fine. I'm pretty sure there's somewhere else that manages to get three responses by using -1 in batteries, though I don't remember where.
