### ISSUE TITLE
[SUGGESTION] Xenoarch safety adjustments

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4127]
#### Brief description of the suggestion
Remove spawning of xenoarch spots on station levels

#### What is reason for it to change
Xenoarcheologists digging around station with no regard for safety can cause phoron flooding, depressurizations, radiation waves and generally artifacts affecting people. Not speaking how some people find picksets in maints and try to excavate using those.

#### How will things work after the change
Perhaps increase spawns of artifacts elsewhere, but no more in z1 through z7.

#### Brief description of the suggestion
Move anomalies and xenoarch to the outpost

#### What is reason for it to change
Artifacts sometimes have disasterous effects and are generally very dangerous. Them being worked with and contained away from the main station makes all the sense, and has less chance to directly affect people on the station, especially since anomalists and xenoarcheologists never bother with proper safety and leave them on without knowing for sure what they do, leave them uncontained, etc.

#### How will things work after the change
Expanded outpost with Anomaly Lab and Xenoarch Storage. Freed up space in station research can be used for general purpose lab.

**Comment by TheDavestDave** [comment]
that spot would be perfect for EVA storage suit things, as it is just beside an air lock

**Comment by kcin2001** [comment]
If nothing else at least have some containment boxes outside the airlock
