### ISSUE TITLE
pizza has unlimtied storage

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4133]
#### Brief description of the issue
Pizza doesn't have an max amount you can hid in it

#### What you expected to happen
not to be able to hide anything in pizza

#### What actually happened
hides everything in the station in pizza, plus a mouse

#### Steps to reproduce
- (Step 1)get pizza
- (Step 2)put everything in pizza

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 6831216aa58b34b2d6610f7de92c556b69272fbc 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KasparoVy** [comment]
Welcome to the future hahaha
