### ISSUE TITLE
Teshari can't hide while cuffed

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [VOREStation/VOREStation#4136]
#### Brief description of the issue
Teshari can't hide while cuffed

#### What you expected to happen
Teshari can hide while cuffed

#### What actually happened
Teshari can't hide while cuffed

#### Steps to reproduce
- Become Teshari
- Get cuffed
- Try to press HIDE button in abilites

#### Code Revision
- f0a7284dc1635d3a4e0d4dd23ea2c932e16fadea 
 
#### Anything else you may wish to add:
- ~~teshari dont have exploration voidsuits~~

**Comment by SpadesNeil** [comment]
Does not sound like a bug.

**Comment by KasparoVy** [comment]
Working as intended AFAIK, [this](https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/living/living_powers.dm#L6) checks specifically for restraint.

**Comment by kcin2001** [comment]
it would be really annoying if tesh could hide while cuffed.

**Comment by KotetsuRedwood** [comment]
Not sure if this is a bug or intended.

Probably intended. Have you tried crawling under a table while cuffed??
