### ISSUE TITLE
Suggestion/Request: Digestion-Resistant Promethean Core

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#4158]
#### Brief Description of the Request
I would like for promethean cores to not be destroyed by digestion. Whether that means simply making all promethean cores indigestible or creating a prosthetic-organ variant that represents a shielded/treated core, I would just like some way to recover and reform prometheans post-scene outside of resleeving.

After some discussion on discord and queries about where to take this, it was suggested to make a github issue about it, so here I am.

**Comment by Zeldazackman** [comment]
I'd love this, especially while playing as a vox it becomes a bit of a "ah crap" moment when you digest a promie only to have their core become useless the moment their gooey congealed forms finally decides to give in to their new place of residence.

I find that even with the itemweak stomach mode toggled on, it oftentimes just removes their core outright which makes scenes really awkward and limiting as a whole.
