### ISSUE TITLE
Two mice related vore bugs.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#416]
#### Brief description of the issue
1. You're unable to remove someone from a mouse's stomach
2. Killing a mouse kills the people inside
#### What you expected to happen
1. Have a way to remove the mouse's stomach contents
2. Kill the mouse, have the prey pop out.
#### What actually happened
1. Prey has to OOC escape, or be let out by the mouse.
2. Prey that were in the mouse were deleted from existance
#### Steps to reproduce

N/A
#### Additional info:
- **Server Revision**: release - 2016-07-04
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  1.Could probably be made so you can click the mouse with a small item and you'll bop it on the nose, which will cause it to cough up its stomach contents or something like that. 
  1. There should probably be a proc that happens when the mouse dies so it spews out its stomach contents then proceeds to die.

**Comment by SpadesNeil** [comment]
Mice shouldn't be able to eat people at all. This has been abused by griefers several times already.

**Comment by Arokha** [comment]
Mice can't eat people now.
