### ISSUE TITLE
LFRP feature

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#418]
#### Brief description of the issue
Often it's hard for people to advertise that they're open for a scene without being overtly willing IC, or spamming up the OOC with "eat me plz". This is mostly an issue for unwilling prey characters, or the occasional pred who might be looking for unwilling prey but has no indication whether breaking into someone's office will lead to a fun scene, or whether it'll lead to "; HELP SCREE BREAKING INTO CHEMISTRY"

With that, I'd suggest a simple flag, toggleable from the OOC or Preferences tab, that allows a person to indicate whether they're looking for a scene or not - same as tagging up LFRP/Open in a chatroom.

In addition to that, add a button to the OOC tab that simply returns a list of those who have tagged themselves as such, along with the OOC info link that you get when examining them, gender and species.

**Comment by Jwguy** [comment]
Could add it to the Crew Manifest, maybe, too?

**Comment by SpadesNeil** [comment]
Won't add due to Discord.
