### ISSUE TITLE
Lack of IAA Stamp

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#4219]
#### Brief description of the issue
There is a lack of an IAA Stamp or two in the IAA Office near Security after the overhaul to the department which moved the old IAA Office from East of the AI Core to North of the Short Range Teleport.

#### What you expected to happen
Be able to use IAA Stamp for paperwork

#### What actually happened
Lack of IAA Stamp

#### Steps to reproduce
- (Step 1)Either spawn as IAA Officer, or have a meeting with one
- (Step 2)Fill out some paperwork
- (and so on)Need a stamp? Shit, you don't have one. Time to cry.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
New IAA office is the location.

**Comment by lbnesquik** [comment]
There is no IAA stamp

**Comment by Sebbe9123** [comment]
`/obj/item/weapon/stamp/internalaffairs
	name = "internal affairs rubber stamp"
	icon_state = "stamp-intaff"`

It exists, I see no reason to not have it.

**Comment by TheFurryFeline** [comment]
Let me clarify: the issue is that it's not mapped into the spawning cycle, generating one or two stamps on the desks in the office.
