### ISSUE TITLE
Riding crop is a bit too effective.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#4223]
#### Brief description of the issue
Smacking people with the riding crop easily makes them bleed all over.

#### What you expected to happen
The riding crop not to cause open wounds.

#### What actually happened
Only two hits, and I'm all covered up in spaghetti sauce.

#### Steps to reproduce
Find a poor soul to enact your fenfendom on.
Smack them around a bit, doesn't matter what intent.
Witness a soda volcano but worse and bloodier.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Affurit** [comment]
Pain stutters are fun >.>
