### ISSUE TITLE
Event prefs do nothing

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#4239]
#### Brief description of the issue
Event prefs have no effect in the game.

#### What you expected to happen
For event prefs to allow antags and admins to see on a glance whether or not someone is kidnap, kill, capture, or prey for events, so that it is easier to pair up people for shenanigans.

#### What actually happened
No such functionality exists.

#### Steps to reproduce
- Set your event prefs in character setup.
- This does nothing noticeable in-game.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/22acaf3fcda8451af26bba62ae9e21334150e571

**Comment by Zeldazackman** [comment]
Citadel actually has a few things planned about that in the works as seen here, perhaps it can be improved upon too. https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/306

**Comment by Very-Soft** [comment]
I should note that the vantag hud var is supposed to turn on a special hud that will allow those it's on to see the icons relating to the event preference settings, but that appears to be broken. I've seen it work only one time, and that was when my eyes were bugged out and broken. Perhaps it's an issue with planes?
