### ISSUE TITLE
Medibelly breaking mid-digestion

### ISSUE THREAD

**Issue by Movler** [VOREStation/VOREStation#4260]
#### Brief description of the issue
the medibelly module seems to break every now and then when you digest people

#### What you expected to happen
for it to continue digesting and eventually shrinking the belly flat

#### What actually happened
The medbelly console froze and it stopped digesting the person after they died

#### Steps to reproduce
consume person with medibelly
digest person with medbelly

#### Code Revision
6831216aa58b34b2d6610f7de92c556b69272fbc

**Comment by Verkister** [comment]
Has there been any specific circumstances where this is more likely to happen?

**Comment by Movler** [comment]
I have been trying to nail it down but there seems to be very little to
tell what is causing it since it freezes. Might be something with the Id
locking down digestion
