### ISSUE TITLE
Main Upper Hallway has no APC

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4261]
#### Brief description of the issue
Main Upper Hallway (third floor asteroid, from vault to cargo foyer) has no APC and gets power by magic.

#### What you expected to happen
APC is around, powers area.

#### What actually happened
No APC, no control

#### Steps to reproduce
- Need to meeddle with area
- Find no APC

#### Code Revision
- 6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
Probably introduced by sec rework.

**Comment by Verkister** [comment]
This thing will be leveling up in severity since some recent Polaris changes that removed the forementioned magic and must be fixed before the next release.
