### ISSUE TITLE
Mobvore sometimes bugs & you get "eaten" but aren't

### ISSUE THREAD

**Issue by Theoun** [VOREStation/VOREStation#4292]
#### Brief description of the issue
When a mob eats you, most notably with the catgirl mobs (dunno about others), sometimes everything goes to plan and you get swallowed in, you even get the belly description, but you remain outside the mob. They get their bellysprite but are still empty, swatting them with the newspaper does nothing unless you feed them something THEN swat them which makes them vomit up & go back to normal.

#### What you expected to happen
Get actually eaten by the mobs.

#### What actually happened
My shadow clone jutsu got ate instead, I guess?

#### Steps to reproduce
- Turn on mobvore pref.
- Order catgirl.
- Allow catgirl to charge through you repeatedly until they reluctantly bumpnom you.
- Roll the dice on whether or not you get eaten.

#### Code Revision
- db0f530d6e376aa765141f2b426c582edf45a4f9 
 
#### Anything else you may wish to add:
- Haven't tested with other mobs, but I've only noticed it happen with catgirls myself.
![image](https://user-images.githubusercontent.com/16782073/46264278-c3365080-c512-11e8-8937-eed508edfa50.png)

**Comment by Very-Soft** [comment]
I'll note that I've seen this happen at some point or another with basically every vore NPC with exception to gaslamps maybe.

I THINK that it happens because they generally try to move after they've started the cast time for eating someone. But rather than stopping the eating, it still triggers everything except for putting you in the gut.

I've noticed that generally, so long as the mob doesn't try to move, they'll pull you inside just fine.

**Comment by TheFurryFeline** [comment]
With Fennecs moving around so much, it's impossible to get nommed. :c

**Comment by lbnesquik** [comment]
It's probably more an issue with bumpnom than anything else. It may be linked to NPC's having a feel for moving to the prey turf whenever doing bumpnom or pounce?

**Comment by Zeldazackman** [comment]
If you're larger than the mob or smaller, than yeah you won't actually switch tiles and thus you'll manage to get eaten.
This is still an open issue as I tried it with a fennec on V4 shrunken down to 100% scale and a wolfgirl from cargo at my regular 155% scale with the wolfgirl actually managing to perform the nom.

**Comment by Zeldazackman** [comment]
Still an open issue as of latest.
