### ISSUE TITLE
Add back in Subtitles for certain jobs.

### ISSUE THREAD

**Issue by Smdytb1** [VOREStation/VOREStation#431]
Currently there is no Lawyer subtitle anymore, But if it were to be re-added. Would it be possible to also add Defender and Prosecutor instead of just Lawyer?
Also, several Chaplain subtitles have been removed such as Priestess and the likes.

**Comment by viv-eret** [comment]
I can make some as soon as my current PR is done.

Ideas:
IAA-

- Lawyer
- Attorney
- Company Attorney
- Company Liason

Gardener-

-Botanist

Chaplain-

-Priestess
-Priest
-Monk
-Disciple
-Divine

**Comment by OrbisAnima** [comment]
@SpadesNeil , isnt this one done?

**Comment by SpadesNeil** [comment]
I think so, yes.
