### ISSUE TITLE
Mob vore not behaving as desired

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#4314]
#### Brief description of the issue
I'm getting reports that mob vore is not behaving as intended. (**Wouldn't it be great if people reported the problems instead of me having to figure it out???**)

A list of unverified problems that need verifying:
- [ ] Mobs don't eat players who are lying down or in crit.
- [ ] Mobs don't eat players who bump into them even when bumpnom is on.
- [ ] Mob vore preferences are not being saved.

Known problems I'd like to fix (discuss):
- Players can cheese any vore mob by letting themselves get eaten, then punching/stabbing their way out.

#### Code Revision
- Can't grab this right now, as I am going to work
 
#### Anything else you may wish to add:
Related issues...
Mobs don't eat critical condition players #1857
You can attack mobs from inside of their stomachs. #541

**Comment by SpadesNeil** [comment]
For the known problem of vore mobs being too easy to cheese when they _are working_, I propose the following:

- All mobs to have itemstrip turned on by default.
- All mobs to have itemweak turned on by default.
- Prevent attacking inside of mobs, unless the person has a weapon flagged as SHARP.

Think about it. A stomach capable of swallowing someone whole is generally going to be able to withstand being bludgeoned from inside.

**Comment by ArgobargSoup** [comment]
...How recently have you tested punching your way out?
Because as far as I know, that's not been possible for a long while.

**Comment by Novacat** [comment]
Attacking inside of mob bellies was broken with a patch, and admins decided that it would be kept as a feature. It also is probably not a good idea to buff mob bellies further unless something is done about the hilariously broken pounce which has made pretty much everyone who works in field operations with regular contact with voremobs (Explorers, Miners, etc) turn off mobvore.

**Comment by SpadesNeil** [comment]
Pounce mechanics as they currently are were meant to be designed in such a way as to mercilessly punish people who lonewolf expeditions and gateway missions. That said, one possible alteration is to change the health threshold in which a target will be pounced, or maybe if you lack armor you'll get pounced, etc.

The health threshold one is one I'd like to fiddle with as some mobs I do want to just scarf down any twat who comes too close.

**Comment by Very-Soft** [comment]
It sounds like their mob vore setting is off.

One thing I've noticed is that my mob vore setting gets reset to off every shift on all my characters. I know that most mobs then try to do an eat as normal if I turn that on, but no matter how many times I save it as on, it turns off again by next shift. 

I've heard that some people don't have this issue, but I struggle to think I'm the only one with it.

Passed that, there's still #4292 that affects most things, though I've noticed that gaslamps still eat people pretty reliably as long as mob vore is on.

**Comment by Screemonster** [comment]
Giving all the mobs itemstrip and itemweak, with a digesting stomach, will instantly destroy the ID of anyone who gets eaten regardless of whether they're rescued. If it strips internals and they're in a hostile environment, then the crewmember will perish the instant they escape. Oh, and it'll strip the sharp weapon too. And if they resist out, they'll be naked and promptly either mauled to death or re-eaten by the mob, or if they're in the underdark, will die in virtually no time at all from being dumped naked into a below-freezing phoron environment.

**Comment by SpadesNeil** [comment]
Ok, no item strip then. Itemweak though, yes. I want crew to find the remains of someone if they kill a mob who ate a person.
