### ISSUE TITLE
Air Alarm Cooling

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#433]
#### Brief description of the issue
Air Alarm Thermostat ain't cooling rooms. Heating apparently works, Cooling doesn't.

#### What you expected to happen
That it starts cooling the room.

#### What actually happened
Nothing.

#### Steps to reproduce
Go to any Air alarm. Set the temperature to 0C for example , wait a few minutes. See no result. Great. ;~;

#### Additional info:
Server revision: release - 2016-07-04

**Comment by SpadesNeil** [comment]
Needs to be tested again.

**Comment by SpadesNeil** [comment]
It's been 8 days since this was marked for testing. Now closing.
