### ISSUE TITLE
Custom Items sprites displaying incorrectly

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#434]
#### Brief description of the issue

Two items in question, one, the "Gili Custom Labcoat" and two the "Clockwork Rifle" have on character sprites not displaying properly. in the case of the coat, the button option doesn't seem to function, the sprite of the item itself in the inventory slot alters between the buttoned and unbuttoned options, but the on character remains unaltered. As for the Rifle, the sprites are displaying improperly while in the Backpack item slot. it shows the North view for all four directions.
#### What you expected to happen

Have them displayed properly
#### What actually happened

They did not
#### Steps to reproduce

Simply equip the items
#### Additional info:

not a major issue but still anoying to see it messing up like that.
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Was this ever fixed?

**Comment by Molenar** [comment]
just tested and no, as of server revision: release - 2016-08-23
3324140ef5949623c13c958fe091a3532363bd3b 

it has not been fixed yet

**Comment by SpadesNeil** [comment]
I noticed @JoanRisu 's sword facing the wrong way also.
