### ISSUE TITLE
ERT OP plz nerf

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#4349]
#### Brief description of the issue
ERT armory has way too much shit in it that they should not have, including automatic 7.62 assault rifles and an LMG. This is not okay.

But in looking at these OP items I thought, what else should be removed from the ERT armory? Right now it's clearly too much, just at a glance. At least for the security part.

Meanwhile, the other branches of medical and engineering feel neglected.

Thoughts?

#### Code Revision
https://github.com/VOREStation/VOREStation/commit/5b91c8fccd05269fa2185287dc9679cca94e7ed2

**Comment by lbnesquik** [comment]
Post a picture or a list of their weapons

**Comment by SpadesNeil** [comment]
I'd rather start from the ground up.

So, stuff I think the ERT **should** have:
- Self-Recharging Energy Guns
- Night Vision Goggles.
- General purpose body armor that is objectively better than standard station armor, but still not as good as specialized armor in specialized categories (Ballistic, Swat, Energy).
- A rifle caliber weapon of _some kind_. Preferably in 5.56 or 5.45 or whatever we use now. Reminds me, I need to dick with Polaris's weapons again. I'm sure this will make their devs _so_ happy.
- _One_ net gun. Just the one.
- _Maybe one_ Bluespace Harpoon. _Maybe._
- Anything Security has access to or in their armory at round start.
- Anything Medical has access to or in their storage at round start.
- Anything Engineering has access to or in their storage at round start.

**Comment by Arokha** [comment]
Doubt they'd get BSHarpoon. Seems like a cool thing for ERT, but the 10% malfunction chance is a little high for something used professionally. Might be acceptable if you literally hide it behind a slidey wall at centcom or something. It's the ERT STASH OF EXPERIMENTAL TOYS.

**Comment by SpadesNeil** [comment]
Okay so no bluespace harpoon.

And sure we can always add the admin abuse room but then it's like we may as well call Zulu anyway.

**Comment by Novacat** [comment]
I can probably work up some map fixes for this, at least, for medical and security part. Not familiar enough with engineering to know what to add there.

**Comment by Screemonster** [comment]
buff the fucking RCD already
or make an advanced RCD that's producable in the protolathe instead of the autolathe, and give _that_ to the ERT.

Difference being simply a higher ammo count because 30 RCD ammo is _jack shit_ for doing anything besides patching the barest of breaches (seriously, 10 tiles or 3 doors and you're done) and the ammo things are a fucking huge medium-size item for every 10 extra ammo to the point where it's literally more space efficient to carry spare RCDs than to carry spare ammo, meanwhile the mech and rig mounted RCDs merrily trundle along on the suit/mech power.

**Comment by Arokha** [comment]
don't make it the advanced RCD because that's a thing on other servers. it works at a distance. the horror.

**Comment by Novacat** [comment]
Oddly enough, ERT does not even start with RCDs, they only get the rig-mounted RCDs.

**Comment by SpadesNeil** [comment]
ERT does not have access to the rest of CentCom.

**Comment by Wickedtemp** [comment]
Medical ERT would ideally have:

- Medical/Paramed Lockers.
They come with webbing, organ coolers, extinguishers, inflatables boxes, flashlights, general handy equipment. It'd be easier to just add the lockers than putting all this stuff on a rack.

- The Usual Suspects.
AR-M HUDs, toptier health analyzers, Medical belts, stasis bags, advanced rollers, dufflebags or an equivalent, syringe boxes, injectors, I'd personally throw in a few hyposprays, too. They'd be more useful with the ERT than anyone else. Backup implants, chem implants, death alarms. Could put a lot of this in a Nanomed Vendor.
