### ISSUE TITLE
Re Add Shinto book cover and Priestess Robes

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#435]
#### Brief description of the issue

the two items, the Shinto book style, and the priestess robe Kimono were in the game before we swapped over to the new code base. They do not seem to have followed.
#### What you expected to happen

to have the items there for everyone to use, or well, every chaplain to have the option to use. 
#### What actually happened

Poof, they're gone
#### Steps to reproduce

looking at the item spawn list, non existent. 
#### Additional info:

files are here for sprites https://www.dropbox.com/s/zq8ht8n307bwu70/Supesu.dmi?dl=0
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by chaoko99** [comment]
Didn't this get solved? Kinda?

**Comment by SpadesNeil** [comment]
Did it?

**Comment by chaoko99** [comment]
I've seen a kimono ingame, at least.
