### ISSUE TITLE
Monthly Polaris Sync

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#436]
We need to sync the code and update the server. I don't actually know how to sync, so, someone please write a manual for this for future reference and post it here.

**Comment by Cameron653** [comment]
:+1:

**Comment by Eearslya** [comment]
Wrote up a small description of the steps I personally took in #450, but here it is again:

First created my own fork of the repo, then...
```bash
git clone https://github.com/Eearslya/VOREStation.git
cd VOREStation/
git remote add PolarisSS13 https://github.com/PolarisSS13/Polaris.git
git fetch PolarisSS13
git merge PolarisSS13/master
```

From there, all the Polaris changes are ready to commit. Any conflicts between Polaris and VS have to be dealt with manually. There were only a few this time.

After that, I got rid of the remote tracking of Polaris (might not be necessary, but I wanted to play it safe), committed and pushed, and made this PR!

```bash
git remote remove PolarisSS13
git commit -m "Polaris sync"
git push
```

**Comment by SpadesNeil** [comment]
Will re-open this issue next time we need it.
