### ISSUE TITLE
Exosuit inventory not having a small [?] box to read the description about the item.

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#437]
#### Brief description of the issue

Missing [?] Boxes fo description
#### What you expected to happen

There are none with the new update 
#### What actually happened

Just items with no [?] boxes.
#### Steps to reproduce

They are temporary (If fixed) Just use the Exosuit fabricator to see the exosuit equipment having the items no description boxes before making them.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
S'not really a bug. Just it seems the NanoUI version of the mechfab interface just doesn't have that feature on this codebase. Bay probably had it before they switched to NanoUI. I'm not even sure Bay has this. That'd make this a feature request.
