### ISSUE TITLE
Layering on some stuff seems to have broke

### ISSUE THREAD

**Issue by Sebbe9123** [VOREStation/VOREStation#4378]
#### Brief description of the issue
https://gyazo.com/6b3dbb2eff2a9a1aedc5190784a00ed5

#### What you expected to happen
Not seeing that blinky thing

#### What actually happened
https://gyazo.com/6b3dbb2eff2a9a1aedc5190784a00ed5

#### Steps to reproduce
- (Step 1) Go into security EVA
- (Step 2) Look at cycler
- (and so on)

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
https://gyazo.com/6b3dbb2eff2a9a1aedc5190784a00ed5

**Comment by Heroman3003** [comment]
I believe those were broken before too. Just more broken now. Even before update, regular canisters rendered below meters.

**Comment by Novacat** [comment]
Not a layering issue, the meter should not be placed on top of that cycler. This is more of a mapping issue which has already been fixed.
