### ISSUE TITLE
Bridge material stacks reduced to 1

### ISSUE THREAD

**Issue by Brasnak** [VOREStation/VOREStation#4379]
#### Brief description of the issue
Material sheet stacks on the bridge have been reduced to 1 sheet per stack. Other material stacks might have been affected as well.

#### What you expected to happen
I expected to find somewhere around 20-40 metal sheets at the bridge, split up in two stacks

#### What actually happened
I found two metal sheets at the bridge, split up in two stacks.

#### Code Revision
release - 
1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Heroman3003** [comment]
Bridge always had them as two sheets of metal and one sheet of plastic.

**Comment by TheFurryFeline** [comment]
This was apparently because of two table objs being there. Fixed in #4908
