### ISSUE TITLE
Metabolic generators from the circuit printer are invisible.

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#4380]
#### Brief description of the issue
Metabolic generators are invisible.

#### What you expected to happen
I expected to see them.

#### What actually happened
They had no icons.

#### Steps to reproduce
1. Get a circuit printer.
2. Get advanced designs.
3. Print out a metabolic generator.
4. "where's the bloody hell is that metabolic generator"

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3
 
#### Anything else you may wish to add:
This might be an upstream bug, not honestly sure

**Comment by MrSign** [comment]
Bump. This is still an issue!

**Comment by MrSign** [comment]
Found the issue with it; the icon for the metabolic siphon simply doesn't exist anymore! It'll need to be ported from an early build back into the files.
