### ISSUE TITLE
Height and built descriptions disrespect custom species

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4381]
#### Brief description of the issue
They ignore species set name and instead use source name.

#### What you expected to happen
"They are heavily built for Snowflake McSpecial"

#### What actually happened
"They are heavily built for Custom Species"

#### Steps to reproduce
- Examine someone with custom species name

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
- https://prnt.sc/l5t77f

**Comment by SpadesNeil** [comment]
It happens on regular species as well.

**Comment by Runa-Dacino** [comment]
An observation:

An average height for X species may read "taller than you" if you chose average height for Y species.

Meaning, making this system custom-species friendly will require not only adjustment of name-inheritance, but also perhaps an option to define what your custom species' "average height/build" means.
