### ISSUE TITLE
Wrong Windows in Engine Room

### ISSUE THREAD

**Issue by Iroquois-Pliskin** [VOREStation/VOREStation#4382]
#### Brief description of the issue
The windows overlooking the Engine's cold loop/Surrounding the Tesla's PA are currently the wrong type, and make it very easy to vent the engine

#### What you expected to happen
Normal full tile windows

#### What actually happened
Weak little baby one side windows.

#### Steps to reproduce
- Join as anything with Engineering access
- Approach the engine room
- Behold the windows.

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
https://i.imgur.com/L3YscRS.png

Edit: Including Tesla in the issue post as well.

**Comment by Screemonster** [comment]
Tesla appears affected as well as supermatter.

**Comment by Iroquois-Pliskin** [comment]
> Tesla appears affected as well as supermatter.

Confirmed. Screenshot to boot.
https://i.imgur.com/KMhQLHm.png

**Comment by Sebbe9123** [comment]
Just took a peek at the aerostat, same problem there.
https://gyazo.com/d4f6df0f0f7687ed9a59ee2c7c3ca7e9

**Comment by Iroquois-Pliskin** [comment]
It has come to my attention that on the tesla submap, these windows leave electrified grilles exposed.

This is dangerous for inattentive engineers and victims of pushing

**Comment by Verkister** [comment]
Pretty sure someone's managed to release some sorta **severe** fuckup in startup rng map loading that might also be related to the squished cave POIs and holodeck windoors and shit.

https://i.gyazo.com/d8b8f0046ee7f7e4f8091033fab49511.png

**Comment by KasparoVy** [comment]
Ruh roh.
I'm confident in the single pane separating the room from a fiesta so long as we don't breathe on it too hard.

**Comment by Verkister** [comment]
https://github.com/PolarisSS13/Polaris/pull/5741

**Comment by Novacat** [comment]
This has been fixed. Closing.
