### ISSUE TITLE
Ticket system reveals staff member's character name

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4385]
#### What you expected to happen
ticket system to not be a snitch

#### What actually happened
![image](https://user-images.githubusercontent.com/24854483/46911849-73ee1800-cf35-11e8-88ff-23e19352d537.png)

#### Steps to reproduce
- Ahelp
- get issue resolved or closed

#### Code Revision
- release - 
1fe04192c11e2ad7357512d5a873c44a4ea687d3 

#### Anything else you may wish to add:
- Not a super huge issue, but this could be sneakily used to reveal secret characters, or event characters.

**Comment by KotetsuRedwood** [comment]
can confirm, snitched who this lanneth tal nerd was to me

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/5670
