### ISSUE TITLE
V2 PoIs are squished

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4386]
#### Brief description of the issue
All pois on virgo 2 seem to have been squished into single lines

#### What you expected to happen
Proper PoIs

#### What actually happened
http://prntscr.com/l5ttok

#### Steps to reproduce
- Observe on V2

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Arokha** [comment]
What about cave?

**Comment by Heroman3003** [comment]
Cave seemed fine from what I checked

**Comment by Verkister** [comment]
Cave confirmed for squishies as well.
![kuva](https://user-images.githubusercontent.com/13697337/47743590-13c2da00-dc88-11e8-88d6-a71b90306a9b.png)
![kuva](https://user-images.githubusercontent.com/13697337/47743601-1b827e80-dc88-11e8-871c-9551a4cc653d.png)
![kuva](https://user-images.githubusercontent.com/13697337/47743621-25a47d00-dc88-11e8-9b68-7940ac307e31.png)

**Comment by Zeldazackman** [comment]
Happened again last night
![80pj2wq](https://user-images.githubusercontent.com/17093432/48619505-c2466a80-e96a-11e8-8f60-d54fda29e39e.png)
