### ISSUE TITLE
Fluff item selectable in character setup loadout

### ISSUE THREAD

**Issue by Virgo113** [VOREStation/VOREStation#4391]
#### Brief description of the issue
My sergal's coat is selectable from the loadout tab in char setup as a part of the hazard vest selection, since it is a child item of it. Would prefer it not be since it's a unique thing and stuff.

Character and ckey in question are _Verin Raharra_ and _virgo113_ respectively

#### What you expected to happen
Item to be locked to ckey and character name as intended.

#### What actually happened
Pick it from the list and whee you can smell like wedgehead. Cause the thing literally says so in the item description.

#### Code Revision
release - 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Sebbe9123** [comment]
Is there a possibility other Fluff items have been affected?

**Comment by Heroman3003** [comment]
Only ones that are subtypes of items with selectable subtypes in loadout, probably
