### ISSUE TITLE
Light floors are spammy

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#440]
#### Brief description of the issue

Light floors in the bar display a message any time someone toggles one. For a large area, this can seriously clog the chatbox.
#### What you expected to happen

For them to just turn on and off.
#### What actually happened

Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light on.
Silver turns the floor light on.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
Silver turns the floor light off.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: release - 2016-07-04
  a3835cb52f954f5278d7987f458f75fa90ce61c7

**Comment by SpadesNeil** [comment]
This should be changed to a >> directly to the user, rather than broadcast to everyone.

**Comment by SpadesNeil** [comment]
Test if this has been fixed in current build.
