### ISSUE TITLE
The research outpost is not interesting.

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#4413]
#### Brief description of the issue
The research outpost lacks rooms to be interesting as a RP area. It's just a work area, which is fair and reasonable from nanotrasen standpoint but it's also really not a tempting place to go as a player. 
It's just a confusing mess of pipes, firelocks and burn chambers. It could be made more interesting if it held xenobio (and if xenobio was made fun too) along with some areas where you can 'rest' and 'take a break from exhausting dangerous work'.

**Comment by Screemonster** [comment]
Putting xenobio there is waaaay too safe. Half the fun of xenobio is when xenobio leaks into the rest of the station.
Putting xenoarch there, maybe. On most other stations xenoarch is on the research outpost, both to increase the isolation when things go horribly wrong due to an artefact, and in our case to stop the crazier artefacts from screwing up people who just wanted to take the elevator down to the tram.

**Comment by SpadesNeil** [comment]
I would appreciate having more things in the outpost, but we need suggestions as to what. Possibly new mechanics.

**Comment by Very-Soft** [comment]
I think xenoarch should be ANYWHERE ELSE than where it is, as if they're working with the teleporty artifact, and someone is heading through the normal surface airlock, then it almost always causes deaths.

**Comment by lbnesquik** [comment]
Xenoarch being moved would be nice, especially if you expanded the building into an interesting shape.
Maybe give it a basement or another story for the experiments.
As for what i find it lacks, food, dorms, toilets, relaxation area are a must. Even if it just serve as a hideaway for long, long scenes.

**Comment by Runa-Dacino** [comment]
How about opening the research outpost to mining and engineering, with something of a common room from which they can each head out to do their stuff on the surface?

Old NSS Exodus's asteroid outpost was a collection of mining, engineering (solars) and research (xenoarch). Polaris had toxins added to research.

**Comment by TheDavestDave** [comment]
most departments have their own "dorms" in the way of break rooms an such. Bars back room, miners houses. Sec has brig, medical has paitent rooms, engineering can build them next to their department.

Also xenoarch would only be in the worst place if it was right next to the tram entrance. It needs moved
