### ISSUE TITLE
Suggestion: Flavor cubes for the condimaster

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#4415]
#### Brief description of the request
![image](https://user-images.githubusercontent.com/19196710/47122790-3b985380-d22d-11e8-968a-12f2d24b31fe.png)

Essentially, letting the condimaster make its own version of pills, to make it a little easier to manage the amount of bottles and clutter created.

#### What you expected to happen
With the chemmaster, you can create pills to combine with existing bottles of chems.
3 plates of enchiladas, removing 20u of capsaicin from each...
Results: one bottle, then two pills dropped in, resulting in one full 60u bottle.

#### What actually happened
With the condimaster, you can only create condiment bottles, resulting in excess bottles.
3 plates of enchiladas, removing 20u of capsaicin from each...
Results: three condiment bottles, each with 20u of capsaicin.  Combining them gets you one full 50u condiment bottle, one condiment bottle with only 10u, and one empty condiment bottle.

**Comment by Sebbe9123** [comment]
Can we just use the "monkey cube" sprite for the cubes?

**Comment by lbnesquik** [comment]
https://github.com/PolarisSS13/Polaris/pull/5689
