### ISSUE TITLE
WHAT THE HECK DID YOU DO TO THE TESLA

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4419]
#### Description of the issue
The tesla is producing all in all significantly less power than it did previously, despite the fact that the new configuration has more coils, and makes the tesla always in the PA beam, so it keeps growing even when power is set to 0.

And with all that, it seems to be producing on average around 700-800kW, and I have no idea why. It seems like something's different about how it's calculating power, as previously, with two less coils and a bigger field, which allowed the tesla to scoot out of the path of the PA and shrink, it would easily produce in excess of 1 mW. Which, considering the lack of real customization, and lack of proper protection gear for working around it seemed reasonable. 

Now, the default setup should be even better than it was before, which I'm not too keen on, but it ain't. :Y

#### What you expected to happen
To be able to set the main smes output higher than 650kW without draining the thing.

#### What actually happened
The main drains under just a little more than normal station load.

#### Code Revision
- release - 
1fe04192c11e2ad7357512d5a873c44a4ea687d3
#### Anything else you may wish to add:
- I heard the server tickrate got changed again. Perhaps that has something to do with this. I haven't checked to see if the SM behaves similarly.

**Comment by Shophaune** [comment]
Ohhhh, is that it? I noticed power issues after setting up the tesla but I thought that was just from everything trying to charge constantly whilst the tesla output in bursts.

**Comment by TheDavestDave** [comment]
it sounds like, if code hasn't change. Someone wired a coil in wrong

**Comment by Shophaune** [comment]
Can't be that, tesla was very clearly putting out 4+MW in bursts.

**Comment by Iroquois-Pliskin** [comment]
Tesla has been A-okay in my experience and now averages HIGHER power outputs as well. The smaller area means it has less things to arc to, other than grounding rods and coils. The one issue I've seen is it can occasionally arc to someone standing in front of the PA inside the PA room.

**Comment by Heroman3003** [comment]
The problem I noticed with tesla is that regularly, if its not overgrown out of proportion, it only zaps coils on ONE side instead of both because of their new positions.

Also, yes, it now continues growing even with PA on zero, which is horrible.

**Comment by Very-Soft** [comment]
All I know is that I did my usual setup this morning, and ended up with a dry main after a little bit, despite putting the output on it 50kW lower than the input like I normally do. I fiddled with it, and ended up throttling main output down to 650kW before it started taking more power in than it was putting out. 

It should not be that low with a 19 ball tesla with 6 coils.

**Comment by Iroquois-Pliskin** [comment]
I can say with certainty that the Tesla outputs a consistent 2 MW now. Sometimes more, depending on how the arcs reach. The default design as of now works perfectly fine.

As for growing while the PA is on zero, if I had to guess, it's doing the same thing Singularities do on that level, where it bumps upwards for a moment, then downgrades.

**Comment by Iroquois-Pliskin** [comment]
>4.28357e+06W in power network.
>The cable is not powered.
>4.34565e+06W in power network.
>The cable is not powered.
>2.06418e+06W in power network.

Current tesla output when you scan the wire looks generally like this. The 4 MW outputs happen when you get lucky and multiple arcs bounce off of coils.

**Comment by Very-Soft** [comment]
Okay so if you're seeing consistent 2mW, then it's working inconsistently in general. Muh tesla this morning dried up the main, and it shouldn't be doing that.

**Comment by Heroman3003** [comment]
Yes, and with no changes to way engine itself works, it shouldn't have started producing more in the first place. If anything, I'd say all these inconsistencies are probably caused by differences with tickrate and experementations on it.
