### ISSUE TITLE
Borgs don't show up on PDA's crew manifset.

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4421]
#### Brief description of the issue
No borgs show up on manifest in PDAs

#### What you expected to happen
Borgs show up under Silicon category (or is it synthetic?)

#### What actually happened
Nope, none of them

#### Steps to reproduce
- Have a borg in crew
- Check manifest in PDA

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
Seems like only PDA is affected. Borgs still show up on their own manifests.

**Comment by Verkister** [comment]
Same as this #3694

**Comment by Heroman3003** [comment]
Its different actually. That issue mentioned the fact that silicon arrival doesn't update manifest, but when human arrives afterwards, it did and borgs did show up.
This issue is, borgs dont show up there PERIOD.
