### ISSUE TITLE
It'd be neat to be able to opt out of the character directory

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4423]
Just the ability to de-list yourself, or to exclude yourself from being listed in preferences or some such. For folk who get swarmed a lot, or who are shy and junk.

**Comment by Sebbe9123** [comment]
I'd like the option to disable my Flavortext appearing in the directory as... well people seeing my character through a database outside of IC stuff doesn't make sense to me.

**Comment by Shophaune** [comment]
Amen to this

**Comment by ArgobargSoup** [comment]
...Isn't there an option in character creation for not appearing in the character directory?

**Comment by Very-Soft** [comment]
Oh this is already a thing GOOD WORK
