### ISSUE TITLE
Surface 1 spawned caves and ores

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4425]
#### Brief description of the issue
Rocks on surface one for some reason decided they are mining areas and spawned the cave patterns and ores within them (with some ores glitched)

#### What you expected to happen
No ores, no caves, just rock on all station levels.

#### What actually happened
Dangerous cave spawns, ores not meant to be here, glitched out ores...
Example: https://prntscr.com/l83q4r

#### Steps to reproduce
- Fly around surface 1 as ghost with darkness off

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by KasparoVy** [comment]
Glorious

**Comment by Heroman3003** [comment]
http://prntscr.com/lqeftc
Happened again today
