### ISSUE TITLE
Containment field generators missing from cargo ordering list.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#444]
#### Brief description of the issue
Containment field generators are not orderable, despite the rest of the singulo equipment being there.

#### What you expected to happen
For containment field crates to be listed under the engineering section.

#### What actually happened
Checked the list, can't see them listed there. Can see emitters, particle accelerator and singularity generator crates.

#### Steps to reproduce
Try to order a containment field crate from cargo.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: release - 2016-07-04
a3835cb52f954f5278d7987f458f75fa90ce61c7 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
This is fixed in polaris
