### ISSUE TITLE
PAPER STUCK - The Taped Paper Problem

### ISSUE THREAD

**Issue by Daylight2** [VOREStation/VOREStation#4447]
#### Brief description of the issue
Applied duct tape to paper, dropped paper, tried to pick up paper, _The sheet of paper (taped) won't budge, you can't pick it up!_

#### What you expected to happen
Be able to pick up the paper

#### What actually happened
Paper stuck!

#### Steps to reproduce
- (Step 1) Apply duct tape on paper
- (Step 2) Drop paper
- (Step 3) Try picking up the paper

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3 
#### Anything else you may wish to add:
There's also reports of taped papers getting stuck inside backpacks and pockets, although i've been unable to reproduce those.

**Comment by Heroman3003** [comment]
This issue was never fixed to my knowledge and still appears.
