### ISSUE TITLE
NanoMed Murder

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#4448]
#### Brief description of the issue
Lucina was murdered just a while ago by a NanoMed Plus. It disintegrated both of her hands and killed her instantly.

#### What you expected to happen
When discussing the event in space lobby, apparently people were under the impression that electric shocks were generally capped to NOT kill the typical crew member, if only disintegrate their active limb and put them into crit.
**NOTE:** Lucina has no health or damage related traits despite being a custom species.

#### What actually happened
Both hands were fried, her arms damaged, and herself killed in an instant when touching the offending NanoMed machine. I will note that an engineer fixed the machine immediately prior since it was shooting bottles at people.

#### Steps to reproduce
- Unknown, I do not know the full circumstances that led to this murderous machine. It was last shift that ended perhaps 15-20 minutes ago, if the server logs might help explain how it happened.

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 

 
#### Anything else you may wish to add:
- It was the NanoMed Plus in the recovery room inside of medical.

**Comment by SpadesNeil** [comment]
This is what happens when your engineers are show-offs and juice the grid with all the power they possibly can because they think they're hot shit.

**Comment by SpadesNeil** [comment]
To those engineers that trash talk anyone who doesn't make the engine output maximum possible power, you know who you are.

This is why we mock you.

**Comment by Vorrarkul** [comment]
I made it an issue because according to some people in space lobby, apparently it's not supposed to shock BOTH hands off? I don't know so I thought I'd err on the side of caution and make an issue.

**Comment by Virgo113** [comment]
This is honestly intended behavior. The only weird part is yeah, that both hands were shocked off.
To be quite honest with you, the one at fault here is the engineer mending the machine to not fire off things pulsing the wire to leave it shocked. That's the main reason that happened.

**Comment by Shophaune** [comment]
I can confirm that big shocks take both hands, I touched a shocked machine a while ago and got incinerated. Both hands lost. That was...23rd April?

**Comment by ArgobargSoup** [comment]
I looked at the code, and as far as I can tell, it's only supposed to target one hand... is the proc getting called twice?  That would explain both hands being ashed and the instant lethality, seeing as another part of the code seems to indicate that the most possible raw damage from a single powernet shock being 160...

**Comment by Vorrarkul** [comment]
![image](https://user-images.githubusercontent.com/17329033/47318948-49b9eb80-d602-11e8-8daf-23e9d58edc38.png)
Screencap of my log, proving it was instantaneous.

**Comment by Arokha** [comment]
Dunno if bug, but 160 is enough to kill plenty of crew members, including all the precious adorable spess raptors. So the real lesson to take away is "don't put that much power in pls", as Ace said.

**Comment by Heroman3003** [comment]
It appears to have shocked twice. According to Vorra, there were no health-affecting traits, so it wouldn't have one-shot, but two-shot is expected. Also explains why both hands were ashed. And while takeaway lesson is good, bug of it shocking twice instead of once is still present, I believe, doubt it was intentional in any way.

**Comment by Arokha** [comment]
As Argo said, the damage is 160 cap for 1 shock, which is still enough to 1-shot many crew. So even if the 2-zap bug is a bug and wasn't just 2 clicks, still an important lesson about powergrid stuff. :P

**Comment by Screemonster** [comment]
It'd be interesting to add logging to shocks if they're not logged already, detailing the amount of damage dealt and the amount of power in the grid.

If the medbay was running on a substation (maximum 250kw output unupgraded) that's a different beast to "hardwired directly into the engine".

**Comment by Knightfall5** [comment]
It shocked twice for some reason, notice how there are two "You feel a powerful shock course through your body!". Also the damage cap is at 1mw, so it doesn't matter if there is 1mw or 10mw in the grid, it does the same thing.

 And 1mw is pretty much the bare minimum that an engineer is expected to put into the grid due to the Tether's much larger power needs compared to the Exodus, the era this code comes from. The real lesson to be learned here is as follows: "No insulated gloves? Call an engineer."

**Comment by Sebbe9123** [comment]
Would it be an idea to limit the voltage in machines, like they have an inbuilt adapter or so?
Most machines IRL can't survive unfiltered netgrid power.

**Comment by Verkister** [comment]
Yeah the double-zap is definitely an existing bug that I got to witness pretty recently on the bar booze machine. It happens instantaneously and zaps both hands clean off with two simultaneous shocks and instakills the victim on the spot.

**Comment by Vorrarkul** [comment]
Just for clarity because I somehow missed it back in October: @Knightfall5 "No insulated gloves? Call an engineer."

That's fine, except the fact that there WAS an engineer in the room at the time who had just finished working on the vending machine to stop it from spitting out items at people. The reason I touched the machine afterwards was to put the items back and I accidentally clicked the machine with a bare hand.

As far as I'm aware there's no way for someone to know if the machine is primed to double-zap murder them before they touch it, so I find this 'lesson' to be rather unfounded victim-blaming. Not that blame is even the point of this bug report.
