### ISSUE TITLE
Add Size-Changing Mushroom Seeds to seed vendors

### ISSUE THREAD

**Issue by Jwguy** [VOREStation/VOREStation#445]
#### Brief description of the issue

Prior to the Polaris Transfer, the Hydroponics Seed Vendors had two seed packets available to them that contained Megashrooms and Shrinkshrooms, which enlarged and shrunk whomever who consumed them (or their chemical ingredients, e.g. Microcillin).

The seeds, and presumably the mushrooms themselves, have yet to make it over to the vendors since the Polaris Transfer. I'd like to see them re-added, as it made for some fun capabilities for Chefs and Gardeners, as well as a good alternative to the Shrink Ray.
#### What you expected to happen

To open the hydroponics seed vendor and find the seed packets.
#### What actually happened

Sadly, they are not there.
#### Steps to reproduce

Check the seed vendor at the beginning of the round. Alternatively, I presume an administrator could check the list of spawnable items to verify if the mushrooms even exist on the server, at present.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  release - 2016-07-04 a3835cb

**Comment by Virgo113** [comment]
Probably should close this.
