### ISSUE TITLE
Remove Promethean exploding on death

### ISSUE THREAD

**Issue by SiennaAthens** [VOREStation/VOREStation#447]
#### Brief description of the issue
Upon digesting a promethean player, rather than the usual message of them being churned into sludge or whatever and being reduced into a slime core inside of the belly they were in, their body instead exploded into a "shower of gore." They were reduced to bloodstains on most surrounding tiles and a pile of ash plus their slime core on the tile I was on. I have saved logs if they are needed.
#### What you expected to happen
I had expected the player character I was digesting to turn into a slime core in my stomach.
#### What actually happened
They exploded and showered the nearby tiles in blood and gore.
#### Steps to reproduce
I had shifted the Promethean player through three different bellies. The first belly was holding, I started digestion in the second belly, then pushed them into the third, toggling digestion once they were inside. After some time of digesting, I shifted my character into rest mode using the appropriate verb. The victim exploded upon dying in the third belly.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: release - 2016-07-04
a3835cb52f954f5278d7987f458f75fa90ce61c7 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
pffft that's fucking hilarious

**Comment by Cameron653** [comment]
Fixed in #446
