### ISSUE TITLE
Random ghosting on trying to return after being sent away on Cargo Supply shuttle

### ISSUE THREAD

**Issue by Aylaria** [VOREStation/VOREStation#4478]
#### Brief description of the issue
Used bluespace harpoon to swooce onto shuttle as it left. Checked out the cool one room area. Shuttle was called back, but when it was my character (Cie Klara) immediately became a ghost. No corpse, and I was able to respawn almost immediately after.

#### What you expected to happen
Expected to return to station on cargo supply shuttle

#### What actually happened
Character  became a ghost, everythign besides ID evaporated. Not treated as a death

#### Steps to reproduce
- (Step 1)
Obtain bluespace harpoon gun. Prepare internals (optional)
- (Step 2)
Call supply shuttle.
- (Step 3)
When shuttle arrives, have second person send shuttle away again. Wait for doors to close, then use harpoon gun to teleport onto shuttle.
- (Step 4)
Wait for shuttle to arrive at supply area (away from station)
- (Step 5)
Have someone call the shuttle back. Make sure you are on the shuttle when they do.

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
- was fun besides that

**Comment by Arokha** [comment]
Yer not supposed to ride the shuttle, and anything sent back on the shuttle is deleted. That's how it works. It has code to prevent mailing any biologicals for a reason, using bsharpoon to circumvent this doesn't really count as a bug. :P

**Comment by Heroman3003** [comment]
You are not meant to be able to be present on the shuttle as it departs. before coming back it deletes all its contents too. Other than yet another harpoon abuse, it works as intended.

**Comment by Aylaria** [comment]
Figured, was asked to log this anyways!

**Comment by SpadesNeil** [comment]
Marked minor bug since it _is_ a bug, but it requires very specific circumstances that aren't typical of normal gameplay.

**Comment by Shophaune** [comment]
Is it possible to re-circumvent the bug by using the BS harpoon to jump back on the shuttle as it's called back?

**Comment by Screemonster** [comment]
Isn't the shuttle supposed to refuse to depart if it contains any kind of teleporter beacon, or does it only check for the regular kind of beacons?
