### ISSUE TITLE
Cryoing with prey

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#448]
#### Brief description of the issue
Cryoing with prey deletes prey but doesnt remove from jobs, getting rid of the job for the round
#### What you expected to happen
Job gets removed along with prey
#### What actually happened
Job didnt get removed but prey got deleted
#### Steps to reproduce
Get someone to eat you/Eat someone Pred/you go to cryo
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-07-26
2ef573b78aa56cbe97ae8a7047fcf5408ab3d6ec 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
There's nothing we plan to do about fixing players getting deleted when they go into cryo with prey. Just spit them out. I don't know why people want to go into cryo with prey.
