### ISSUE TITLE
Turn off xenoarch spawns on station levels

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#4496]
#### Brief description of the issue
I'm getting sick of xenoarchaeologists bitching about those mean old engineers and directors telling them not to breach holes to the outside in fucking maintenance because they wanted to dig up a shiny. "but it's my job" they say. "they're just using things like `station integrity` and `safety` as an excuse to stop me" they whine. "How was I supposed to know that anomaly would irradiate those doctors on the other side of the wall, they should have put AMI suits on since I was digging, doctors get those right?"

On a more serious note it's probably good to turn them off so that the people who _do_ have a reason to be digging holes don't get blasted with RNG radiation waves when they accidentally drill through a strange rock.

#### What you expected to happen
People on the station levels to NOT have to deal with xenoarch nonsense.

#### What actually happened
Xenoarchs repeatedly breaching/decompressing maintenance because they can't restrain themselves, then complaining when asked to restrain themselves.

**Comment by Screemonster** [comment]
I'd actually LIKE to have them there, they provide a thing to have conflict and disagreements over. A thing that's "... I know I'm not supposed to dig that thing out, but the lure of treasure is too great".

The problem is, that's not what it's become. It's turned into the equivalent of "but that thing in the vault lets me complete R&D quicker so security are being totally unreasonable when they stop me breaking into to steal it every shift."

**Comment by TheDavestDave** [comment]
Scree I've told people the location of artifacts, not even wearing xenoarch gear. And got a CD trying to micromanage me until I told them bluntly as possible to stop.

**Comment by TheDavestDave** [comment]
I think my exact words were. There's an artifact near t-coms sever I don't have a hope of hell being able to get it.

**Comment by TheDavestDave** [comment]
Oh can you boost anomly spawns while you are tinkering with things pretty pretty please. I have started needing to go in the underdark to get some
