### ISSUE TITLE
Neaera Language Broken

### ISSUE THREAD

**Issue by NeoDraconica** [VOREStation/VOREStation#4504]
#### Brief description of the issue
The Neaera language is unusable in-game.

#### What you expected to happen
Typing ,8 (text) says the text in the Neaera language.

#### What actually happened
Typing ,8 (text) instead stays in default language, and just adds ",8" to the beginning of text. (ie, Character says, ",8 This is Neaera text." instead of it actually being in Neaera.)

#### Steps to reproduce
- Select Neaera language in character setup.
- In chat, type ,8 with dialogue, like you'd do for any language.
- Press enter and observe disappointment!!

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3
 
#### Anything else you may wish to add:
- I don't know if this is a bug or if Neaera is actually a whitelisted language and it just doesn't say it. The bug list has nothing on it for Neaera so maybe I just messed up somehow, not sure.

**Comment by Screemonster** [comment]
neara are a monkey-analogue

the language probably shouldn't be in the list

**Comment by NeoDraconica** [comment]
**Quick update:**
This seems to also affect Farwa and Stok (,9 and ,7 respectively). Not sure if these shouldn't be in the list either.
