### ISSUE TITLE
Hard to get out of tram spawn without power.

### ISSUE THREAD

**Issue by cruxxansata** [VOREStation/VOREStation#4505]
#### Brief description of the issue
You can't get out of the tram spawn without power.

#### What you expected to happen
To have a crowbar accessible to me while I'm in the tram spawn in case the power is out.

#### What actually happened
The crowbar is instead just barely outside of it and all I can wonder is "why?"

#### Steps to reproduce
- Join the round when there isn't power to the tram station
- Don't be an engineer or roboticist
- Wish desperately for salvation while you stare angrily at the emergency locker just out of reach.

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/13389337/48653320-0a48aa00-e9ca-11e8-8683-12bac0a5fdda.png)

**Comment by Screemonster** [comment]
Would be good to have a fire locker in there for that reason. Maybe even just move the doors along the hallway so the locker is in the spawn room.
