### ISSUE TITLE
Chemistry Sheet Snatcher Feature?

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#451]
#### Brief description of the issue

You know, if you actually play in any Medical position that has to fill up the fridge with chems. And you are like me, know almost all the mixes without looking it up on the wiki. So you make like a pile of bottles right there... Then you have to put one after another into the fridge which is veeeeery annoying. Paradise code has a chemistry bag that acts like a sheet snatcher, able to pick up all bottles/beakers from one tile. And dump it inside the fridge with one click. Can we have that here too? Pretty please?

**Comment by Arokha** [comment]
Maybe Leshana can do?

**Comment by ArbyTheDragon** [comment]
At least we have this for pills- you can make a TON of those in very short order.

As for bottles, I never really found this to be too much of a bother. It's not impossible to collect around 20 or so full bottles. I get in the habit of stowing the bottles when I produce them so they don't pile up and clog my tables.
It takes quite a bit of chemistry and time to even produce that many bottles in the first place.

**Comment by Leshana** [comment]
It sounds like we need a CONVEYOR BELT!

**Comment by ArbyTheDragon** [comment]
... No.

**Comment by Leshana** [comment]
I'll work on getting the chemistry conveyors soon

**Comment by ArbyTheDragon** [comment]
Have it your way. We will then proceed to use conveyors to cyclically slip mobs on bananas o3o

**Comment by SpadesNeil** [comment]
Still not a thing?
