### ISSUE TITLE
Engi Dogborg lacks a magnetic gripper, and that's kind of annoying

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4512]
#### Description of the issue
Lacking a magnetic gripper makes the engi dogborg incapable of constructing, combining, or upgrading machines, while both the regular engineering borg and the maintenance drones both have the magnetic gripper. 

Being that by design the engi dogborg regenerates materials FAR SLOWER than the regular engi borg and maint drones, this is just one more thing that makes the engi dogborg rather useless and unfun in comparison to the alternatives.

**Comment by Heroman3003** [comment]
I believe lack of gripper is intentional in that none of dogborgs get any grippers. All dogborgs are pretty much inferior in their functionality to their normal counterparts. Dogborgs shouldn't ever be picked if you want them for practicality, as they are almost always outclassed by non-dog versions.

**Comment by Screemonster** [comment]
It's been so long since I even saw an engi dogborg I honestly forgot we even had them.

**Comment by Heroman3003** [comment]
They lack same category of tools that other dogborgs do. The problem, is that they are expected to be able to fix/do anything seemingly, similar to normal engineers, but they just can't.

**Comment by Very-Soft** [comment]
First, you're incorrect just in general, the sec dogborg is in general better than the regular security borg.
The Janitor dogborg is also in general more convenient than the regular jani borg at doing its job.

And while the medical dogborg can't go as deep into doing medical as the other medical borgs, it specializes as being an EMT borg, which it does better than the other borgs. 

The engi dogborg struggles to do the basics of its job. It can construct things, but it regains materials WAY slower than other borgs. That's intended to be balanced by the fact that it can eat trash to obtain materials that way. This still ends up being way less quick than just using a recharger.

But without a gripper, the engi dogborg can't do anything with machines except decon them. 

This includes fixxing broken doors, and computers, as well as makes upgrading anything as one impossible without help.

They are not just a little inferior to the other options, they are practically when compared to them.

Each of the other borgs has like, a role. The engineering dog borg sort of seems like it was meant to be specifically for structure construction, which would be fine if it wasn't just entirely outclassed by the other options. 

Adding the magnettic gripper will still leave the engi dogborg as the worst option of the three, what with its abysmal material regeneration. I just think it should have it, because it's actually sort of regularly important to be able to pick up parts and put them into a machine as an engineer. 

Like, it's the reason I leave as the engi dogborg almost every time. 

(Of course, the research dogborg I think is in worse shape than the engi borg, that poor thing can hardly do anything and I don't even know what to do to make it not worthless)

**Comment by Heroman3003** [comment]
On concept, engi dogborg was meant to be able to specifically produce materials with much more efficency. And its main purpose is not construction, but repair, as per whole 'recycler belly'. Pick up all pieces, repair the hull/floor/etc.

Dogborgs are basically "I wanna scene as borg", so I never expect a dogborg player to be useful in anything practical anyway.
