### ISSUE TITLE
Elevator Button's Nearly Invisible Sometimes

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#4518]
#### Brief description of the issue
At higher floors, the elevator button becomes less visible and more obscured in darkness.

#### What you expected to happen
To be able to see the elevator button.

#### What actually happened
On floor 6/7, it's actually so dark on my monitor that I either have to press my face against the screen to see it, or I have to have a flashlight ingame.

#### Steps to reproduce
- Go to floor 7
- Try to click the button
- Miss several times, run your cursor along the wall whilst clicking
- Get annoyed, use PDA flashlight or the 'glow' ability to be able to see it

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
- Minor issue, but all you'd have to do is make the icon glow, or... Add more lights to the elevator. Something.

Also the button's on the wrong side of the elevator anyway. It should be closer to the doors. I don't know of any elevator that has the buttons on the opposite wall.

**Comment by Verkister** [comment]
Yeah it appears that the lights inside the elevator never leave the borrom floor for some reason. Like despite the fixtures getting taken with the elevator, the lighting itself stays at the bottom floor.

**Comment by SpadesNeil** [comment]
The room should just be changed to not have dynamic lighting, and just always be lit.

**Comment by Verkister** [comment]
https://github.com/PolarisSS13/Polaris/pull/5812 fixd
