### ISSUE TITLE
Abuction/Expedition: Micros in pockets get placed with expedition shuttle on abduction

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#4521]
#### Brief description of the issue
If as a micro one is in the pocket of an expeditionary, they're placed with clothes near the shuttle. Also fully clothed.

#### What you expected to happen
Be stripped naked and placed on operation table

#### What actually happened
Be fully clothed and equipped near expedition shuttle.

#### Steps to reproduce
-Be Micro
-Be in a pocket
-Be abducted

#### Code Revision
release - 
1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by TheDavestDave** [comment]
before we going if it is fitting for micros to do this....... the same thing will happen if Macros do it with normal sized people

**Comment by KasparoVy** [comment]
Whew, cat's out of the bag now. Hopefully this cheese doesn't get too too popular before being sorted.
