### ISSUE TITLE
circuits can't charge weapons or synsths. External battery montiers can only read batteries and not weapon charge

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4537]
#### Brief description of the issue
circuits can't do anything well with power. All the equpitment is there and should work but doesn't

#### What you expected to happen
things with external battery moniter, and transfers to move power outside of one device and charge another

#### What actually happened
have to remove the cell to charge it

#### Steps to reproduce
- (Step 1) make circuit with externam battery moniter
- (Step 2) scan a weapon
- (Step 3) get no result
step 4 remove cell and ref to get reading
step 5 insert cell into weapon and get no reading

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I find it silly that I can put a laser into a circuit . But not have to take it all apart to recharge it's power cell. And no way to have it all use a single power cell

**Comment by Heroman3003** [comment]
This is not an issue, but an intended behavior. Synths are not meant to be chargeable. You CAN charge weapons, if you scan a cell inside the weapon, not weapon itself.

**Comment by Sebbe9123** [comment]
Circuitry has been nerfed heavily since its conception for being extremily op, most stuff now is intentional

**Comment by Heroman3003** [comment]
It wasn't even a nerf. Its exactly how it behaved, because only potential target for charging circuit is, well, a power cell.
