### ISSUE TITLE
xenomorths ignore drone circuits that shoot them

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4551]
#### Brief description of the issue
see title

#### What you expected to happen
an empress to swat the thing away

#### What actually happened
Tiny Tonk defeated a whole xenoarch nest

#### Steps to reproduce
- (Step 1) make combat drone
- (Step 2) take it to virgo 4 
- (step 3) perfect victroy

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
all hail tiny tonk. Destroyer of giants

**Comment by Screemonster** [comment]
Sounds like this is something that should be addressed upstream.
