### ISSUE TITLE
Xenomorphs kinda suck.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#4553]
#### Brief description of the issue
Encountered a xeno hive on expidition. Praetorian neuro spit does nothing to players, but they keep trying to spit anyways. Also eggs can't be interacted with.

#### What you expected to happen
Prae's to utterly destroy me? Also for eggs to be able to be hauled back to research for experimentation / research rp.

#### What actually happened
Neurotox doesn't have any effect / eggs are just decorative pieces.

#### Steps to reproduce
go to praetorian / egg, touch.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Novacat** [comment]
What armor was being used, out of curiosity? All voidsuits provide 100% bio resist to all body parts, and even explorer suits have very high bio resistances, which is the damage type neurotoxin uses.
