### ISSUE TITLE
Universal Recorders should record /me

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4554]
#### Brief description of the issue
Universal recorders should record /me's because a lot of people do emotes + words in the same sentence and it is hard to switch between them plus if you wish to keep recording a secret.

#### What you expected to happen
To not have the transcript look like an individual is talking to themselves cause the other is using emotes with words.

#### What actually happened
"Why are you talking to yourself?"

#### Steps to reproduce
-Get a universal recorder and start recording.
-Using an emote, type out a sentence, such as. /me lets out a snort, shaking his head. "You're kidding, right?"
-Print the transcript or playback the tape.
-Sob as it sounds like you're talking to yourself.

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3
 
#### Anything else you may wish to add:
N/A

**Comment by SpadesNeil** [comment]
We aren't going to do this outright. Recordings should not capture /me regularly just so it can capture an edge-case. You'll have to think of another solution.

**Comment by Wickedtemp** [comment]
Change the name of universal recorder to holocorder. Imply it captures movement via hologram. Let it capture /me.

Tada.

**Comment by Screemonster** [comment]
give borgs the holorecorder for sure

![image](https://user-images.githubusercontent.com/14942479/49657569-df38ff80-fa37-11e8-9c17-2a4b2109e3f5.png)

**Comment by MrSign** [comment]
I'd argue it ain't an edge-case cause a lot of heavy RP interviews/interrogations. People use emotes + words A LOT. And to have entire confessions lost because they decided to include their paragraph-long post in a /me after talking about how their character is sweating profusely, fiddling with his hands and stating how the tone of his voice has changed to one of nervousness. Then, I dunno, man. It has happened a few times to me and others recently when they're dealing with an 'antag'. I rather not have interviews/interrogations completely ruined on record by the recorder's inability to record /me just to include what the character is saying.

**Comment by MrSign** [comment]
And whether the solution is for someone to code in a 'holorecorder' which records says and /me, have it printable by Research to be the ultimate recording device. Or just update the universal recorder to be a universal holorecorder.

**Comment by Wickedtemp** [comment]
And, yeah, can confirm, it isn't an edge-case. I don't even play Security and I've run into this problem when interviewing Medical crew about serious wrongdoings as CMO, and when having psych appointments.

It's especially prevalent in psych appointments. I had one transcript that ended up being literally just Tempest asking questions because the other person used /me's for everything.

**Comment by SpadesNeil** [comment]
A holorecorder would be fine to add, but changing the existing recorder, no.
