### ISSUE TITLE
Suggestion: OOC Notes preview

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#4564]
#### Brief description of the suggestion
Essentially, making it so that when you examine someone, you get a short chunk of their OOC notes, much like you get a short chunk of their flavor text.  This way people have even less of an excuse for not reading them.  It'll also help those who like to arrange things OOCly more, because then they can have that first bit include "(quick yeses/nos) LOOC me to set things up, there's more".

#### Anything else you may wish to add:
- Would suggest that OOC notes automatically show up in the examine tab as well, but then it's sort of basically having OOC notes in flavor text again.
- Out of scope but maybe a big thing of "DON'T BE AFRAID TO LOOC" somewhere prominent would be good...

**Comment by Heroman3003** [comment]
Main problem with that is there is simply not enough space to display even 'quick yes/no', at least with amount of characters presumed to be same as currently flavor text does. And notes are considered important in the 'read it all for any nos' aspect, not to be shortened.
