### ISSUE TITLE
ghosts make tracks in snow

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#459]
#### Brief description of the issue
if you walk in snow as a ghost you make footprints
#### What you expected to happen
no footprints
#### What actually happened
yes footprints
#### Steps to reproduce
be a ghost and walk in actual snow
#### Additional info: 
more of a problem for polaris probably
 - **Server Revision**: c463944382c15a7ddc9b5b5cadc1a99165dc5b31 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/pull/2414 fixes this.
