### ISSUE TITLE
[Suggestion] A way for non-taurs and non-borgs to carry people

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#4593]
Brief description of the issue:
With taurs being able to let people ride them, it was a neat, fun gimmick, but now with borgs also being able to let people ride them, this made me think and realize: hold on, there's no method for anyone outside of these two types of characters (excluding size difference and vore) to actually carry anyone!

Suggestion:
We should either attempt to port piggybacking from TG, or implement some other sort of method for players who're not a taur or borg to carry people around, most likely at a slowdown cost. This could be used for cute moments, for fun, or just to carry injured people up to medical. At the moment, the only way to accomplish this is to make a vore belly called "Arms" or "Back", but this doesn't really sit right with some people.

**Comment by Screemonster** [comment]
We already have a way :9

**Comment by HzDonut** [comment]
Oh we do? What is it?

**Comment by Wickedtemp** [comment]
Grab intent, probably!

**Comment by Very-Soft** [comment]
I'm pretty sure he was implying that you can use vorebellies for that. You can also use general size difference to carry people, which is part of what the taur riding thing is kind of meant to emulate in a way without requiring size difference. Though, I'll say that when I think about it, I don't really see an especially good reason why a person must be a taur to be able to carry others in that way. 

I imagine in large part it would look really stupid to have people riding around on one another's shoulders, but I think it would be kind of neat if that was possible. Though, I think that should probably come with a movement penalty for doing this with people a similar size to you for obvious reasons. 

Though, mentioning that, it would be cool if, having the lightweight trait made you not cause slowdown when carried just for flavor.

Just a thought~

**Comment by KasparoVy** [comment]
Could legit just set up an 'arms' vorebelly and use that, it's what I've seen used all over the place incl. myself
