### ISSUE TITLE
Turrets outside AI core are aggressive.

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4595]
#### Brief description of the issue
While the stairs and the turrets being present up there instead of the ladder in new upload->core transition is nice, turrets outside core where they were not before are not tied to same console as turrets downstairs. They will aggro at you for just going up when you are technically still in same room, just a level higher?

#### What you expected to happen
Turrets outside core itself to not be there or to behave in match with turrets downstairs

#### What actually happened
Almost got shot.

#### Steps to reproduce
Enter upload, see turrets not shoot you. Go upstairs, but not into core itself, see them ready to fire, bolt.

#### Code Revision
fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by prismaticIris** [comment]
Turrets aren't linked to the controls by the AI core either, they need to be disabled individually should the AI expect a visitor
