### ISSUE TITLE
[Suggestion]Remove jani borgs ability to eat weapons

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#4601]
#### Description of the suggestion:
Currently jani borgs are able to completely destroy every weapon on the station should they so choose to do so. This seems really 'unreasonable' out side of say code red for them to mechanically be able to do. Especially lore wise, why wouldn't they be programmed to 'not' eat some thing like a fire arm which should go into secs armory. At that same time, I'm 90% certain guns are not on the list of items you can digest with regular guts, least my experience with it, and considering there's people with the trash eater which is basically the same thing as the janiborgs, why would they still be able to eat such items? I don't feel it lore friendly that a janitor bot can just eat known weapons just willy nilly, nor that it's 'entirely' balanced for that same reason.

#### How to implement it:

I would suggest, to tag firearms, not the melee weapons other then maybe energy weapons and stun batons, to not be on the list of items a jani borg can ingest, how ever leave them on a code red? list so it can still be utilized in some manner I sapose during emergencies to some extent.

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
I can see reasons why a borg would have need to gather up things like that (delivering them to security, for instance) - if a borg lets itself into the armory and eats/destroys all the guns in there for no good reason, that's a borg that's about to eat a silicon ban.

**Comment by Wickedtemp** [comment]
Yeh. If it becomes a problem, seems like an instaban from borgs.

**Comment by Tasald** [comment]
gathering them up to deliver is reasonable, deleting them from existence doesn't to me.

**Comment by Verkister** [comment]
They use the same digestion blacklists that regular guts do. However I don't think there's currently any way to get them out of the borg without cooperation, so if the player is a shitlord and/or gets banned/disconnected, there's no way to get the guns back without staff intervention.
