### ISSUE TITLE
deathclaw spam back

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4609]
#### Brief description of the issue
cave filled with deathclaws

#### What you expected to happen
there to be not-boss level mosters in place of grunts

#### What actually happened
an ocean of deathclaws

#### Steps to reproduce
- (Step 1)go to virgo 4 cave
- (Step 2) GL

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
10 mins chaseing event mob to take picture. 6 deathclaws

**Comment by Novacat** [comment]
Did you verify that you were not getting adminbussed?

**Comment by TheDavestDave** [comment]
I asked if they were mucking about with spawn rates and metion github, they said they didn't know they could.

**Comment by Mewchild** [comment]
From the round this was reported in: https://i.imgur.com/wDYdFPa.png
From offline testing, on the release branch. All rock deleted, every tile seen: https://i.imgur.com/UzkizHU.png

**Comment by Mewchild** [comment]
Confirmed with one of the staff that mobs were being spawned. This issue needs to be cloned.

**Comment by KasparoVy** [comment]
Resleeved
