### ISSUE TITLE
Egg implant didn't seem to work

### ISSUE THREAD

**Issue by SpoopyLizz** [VOREStation/VOREStation#4616]
#### Brief description of the issue
Tried to use the egg implant I have, but alas. I'm Roiz Lizden on station, ckey spoopylizz.

#### What you expected to happen
Clicked the 'Lay Egg' verb under the 'Object' tab. Before, this used to create an egg on my position. Not anymore.

#### What actually happened
why code man no make egg

#### Steps to reproduce
- Implant yourself with egg implant
- Click 'Lay Egg'

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Novacat** [comment]
This is fixed in the master branch already.

**Comment by SpoopyLizz** [comment]
Oh. Guess the server's running an older branch at the moment?

**Comment by KasparoVy** [comment]
Yeah, the server runs on the release branch which sees updates monthly-ish
