### ISSUE TITLE
Suggestion: More obvious pronoun selection on character setup

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#4617]
When selecting pronouns for a character, you're given a list of the following.

- Male
- Female
- Plural
- Neuter
- Herm

It'd be potentially easier to pick the right pronoun at a glance if it was a list of the following, instead.

- He/Him
- She/Her
- They/Them
- It/Its
- Shi/Hir

**Comment by Heroman3003** [comment]
I say keep both, just have it as like Male (He/Him/His), Female (She/Her/Her), etc.

**Comment by Renkindle** [comment]
I vote for the pronouns only, since characters (and real people) might not necessarily identify as male but go by he/him for example.

**Comment by SpadesNeil** [comment]
This seems reasonable. Maybe send a tweaked version to Polaris without herms.
