### ISSUE TITLE
Teshari and webbings

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#462]
#### What you expected to happen

they look normal
#### What actually happened

they dont
#### Steps to reproduce

-be teshari
-equip any webbing
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Screenshots?

**Comment by Dr0ppy** [comment]
Will give one next time im on a server AKA prolly max 15 hours from as of writing this

**Comment by Dr0ppy** [comment]
http://prntscr.com/c4pev4 is it just me or does it look like it is on his face?
here it looks like it is IN his face http://prntscr.com/c4pez8

**Comment by Arokha** [comment]
This is probably not going to get done. Sorry.

Teshari have a separate uniform sprite for every uniform, so someone would need to go through and edit every uniform accessory (like webbings, life crystal, holsters, armbands, ponchos, etc) and adjust them to fit onto the Teshari uniforms. Sometimes that's just moving them down a few px, but sometimes it might require redrawing them. ... And there are 93 of those sprites.
