### ISSUE TITLE
Marking layering issue

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#464]
Certainly a Help requested sorta gig.

I've not currently code savvy enough to know exactly what I'd need to do to get the layering and UI issues fixed on the current marking code, as I said in #458 . So any help or advice on those points would be appreciated.

This marking system would also allow for tattoos, as no-one seems to have really done cross species markings yet. So all in total we need
- layering fixed and visible, yet underlayed by underwear and damage
- UI dropbox to function as expected.
- UI and code realizing that species that don't have certain markings (as listed in their body markings list) don't try to paste them over.
- making Markings play nice with tuar bodies, ensuring that stuff like, say, Tiger stripes or spots are properly conveyed.

**Comment by SpadesNeil** [comment]
This get resolved?

**Comment by Arokha** [comment]
Implemented.
