### ISSUE TITLE
Command PTO can't be spent

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4649]
#### Brief description of the issue
Some roles earn unique command PTO, but it cannot be spent.

#### What you expected to happen
Either transform command PTO into civilian PTO or have command off-duty position

#### What actually happened
Time accumulates without ability to spend.

#### Steps to reproduce
- Play CD/HoP/Secretary
- Earn PTO
- Try to spend it
- Cry.

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 

#### Anything else you may wish to add:
I actually think Off-duty command position is unnecesary, and just automatic conversion of command pto into civilian/worker would be perfectly sufficent (even if slightly harder).

**Comment by Mewchild** [comment]
Downstream, on Citadel RP, they have the role of "Off-duty CO"

**Comment by Wickedtemp** [comment]
That could be problematic, because Command Secretary, which is literally just "an assistant for Command", might be called an Off-Duty Commanding Officer when using PTO.

**Comment by Mewchild** [comment]
An easy fix. Currently Command Secretary is 
```
/datum/job/secretary
title = "Command Secretary"
department = "Command"```

Changing that to `department = "Civilian"` would solve that issue.

**Comment by SpadesNeil** [comment]
I would rather the PTO be for their respective departments. Off-Duty command is pretty dumb.
