### ISSUE TITLE
Digestion damage needs buff.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#466]
#### Brief description of the issue
Digestion damage is too weak, and is being overtaken by natural healing rate, making digestion times ridiculously slow. I've watched the damage stop around 50 brute and burn, when it should keep going up, but it doesn't.

#### What you expected to happen
Digest!

#### What actually happened
I linger in everlasting purgatory of teetering in and out of consciousness but I am not actually damaged further.

#### Steps to reproduce
1. Get ate.
2. Get gurgled.
3. Wait forever.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/86a12253460fdb8b95fcaf4d27d3c1ed3b850cb1
 - **Anything else you may wish to add**: Either someone dicked around with digestion damage rates which I explicitly told people not to do for exactly this reason, or natural healing rate was buffed slightly by Polaris.

Changing this value also means we have to re-calculate how much nutrients a person gives, or better yet, change how nutrients are given. I propose maybe swapping out the current system of giving nutrients and damage over time, to just dumping a value of nutrients on the predator all at once when a body is destroyed, calculated by body weight, prey scale, and predator scale.

Again, IRL, the average human body is worth 110,000 calories. In-game, that translates to 1050 nutrition.

**Comment by Screemonster** [comment]
The nutrient-over-time thing being taken out would kinda wreck people who like to feed by partially-gurgling people.
I guess they could use absorption but it's not quite the same.

**Comment by SpadesNeil** [comment]
Unfortunately I'm going to have to sacrifice that fun in order to keep this working correctly. Plus people have requested the ability to change digestion strength which is incompatible with the weight gain mechanics and other things.

**Comment by SpadesNeil** [comment]
Resolved by https://github.com/VOREStation/VOREStation/pull/508
