### ISSUE TITLE
Med rebalance broke zoom pills.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#4660]
#### Brief description of the issue
Med  rebalance broke zoom pills.

#### What you expected to happen
To get speed, then brain damage.

#### What actually happened
You actually just get dunked on, immediately slowig down after taking the pill. It OD's you on hyperzine. 

#### Steps to reproduce
Take zoom pill
Suffer
Die

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Wickedtemp** [comment]
On one hand, I should probably just go through the list of reagents and test them all, one at a time, to see if their effects are still actually present when ingested and then correct them.

But, on the other, it's fitting to simply get poisoned and die by eating floor pills.
