### ISSUE TITLE
DNA scanner doesnt work and has a typo

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#467]
#### Brief description of the issue
http://prntscr.com/c4q69r Scand isntead of scans and when I click on it, nothing pops up
#### What you expected to happen
the description to say Scans instead of Scand and for the GUI to pop up
#### What actually happened
none of the above
#### Steps to reproduce
shiftclick DNA scanner, click on it
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Please keep different bugs in separate issues. The typo is only a minor issue, whereas the scanner not working is an extreme blocker issue.

**Comment by SpadesNeil** [comment]
Server revision is also missing.

**Comment by Dr0ppy** [comment]
EDIT added server revision

**Comment by SpadesNeil** [comment]
I don't see it.

**Comment by SpadesNeil** [comment]
"and for the GUI to pop up"?
