### ISSUE TITLE
Putting people into objects and then flushing them down disposals protects them.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#4670]
#### Brief description of the issue
If you pick someone up, slap them in an container, flush em. they're suddenly ironman.

#### What you expected to happen
To die horribly?

#### What actually happened
Completely fine. you can even resist at any time to pop out of disposals like some madman, potentially allowing people to sneak into areas they can't access normally. This is kinda the same with putting people into lockers, and probably rather difficult to fix as a result. 

#### Steps to reproduce
Pick up smol
Shove smole in box
Flush smol in disposals.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
perhaps add a check that dumps people out of the container they're in when put in disposals. Or just forces them to resist. It makes no sense they'd come out unscathed.

**Comment by Screemonster** [comment]
If I barrel along the road at 30 miles an hour inside (or on) a container, while I might get rattled a bit should the container hit a bump I'll be fine. If I do so without the container and just truck my clumsy over-the-handlebars ass across the asphalt at those same speeds, I come away with a busted bike helmet, several unpleasant abrasions and a sprained arm.

Ahem. Speaking from experience.

**Comment by SpadesNeil** [comment]
This is a ~~bug~~ feature.

Otherwise, how else am I going to launch turnip micros into space within a cardboard box labeled the _SS Dumbass_?

**Comment by SpadesNeil** [comment]
(We're not fixing it because it's fun.)
