### ISSUE TITLE
Tether is missing landmarks for Electrical Issue event

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4679]
#### Brief description of the issue
Tether has no landmarks named "lightsout", so event never does anything.

#### What you expected to happen
A random area is picked and overloaded, lights break

#### What actually happened
No places to be epicenter exist, nothing happens after announcement

#### Steps to reproduce
- Look around map for "lightsout" landmark
- Shrug in disappointment

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Heroman3003** [comment]
As a note to whoever takes up to put the landmarks around Tether (potentially future me): It picks APCs in 25 tile radius around single randomly picked landmark named "lightsout" and overlods lights in area that APC supplies. So there may be lights in radius that get unaffected if APC powering them is outside, or lights affected outside radius, because APC IS inside.

**Comment by MrSign** [comment]
Yeah, a few events don't have landmarks. See 'rogue drone' event as well.

**Comment by Heroman3003** [comment]
I do believe drone event is not even active, so unlike lightsout, its not as noticable with announcements of nothing.
