### ISSUE TITLE
Layering issue with lights.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#468]
#### Brief description of the issue

Lights are on a layer above all mob sprites, but this looks stupid when big mobs roam by.
#### What you expected to happen

For this not to be the case.
#### What actually happened

The light clips over the mob and looks completely stupid like it's floating over the mob.
#### Steps to reproduce
1. Be a big mob. Resize works.
2. Stand in front of a light against a north wall.
3. Cringe.
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/b3b0ae6660b10c9abdc67772eb98d08f61bc51b0
- **Anything else you may wish to add:** When this is fixed, do not set the layer for lights to always be the same or less than mobs, or we hit other stupid looking issues like standing on lights against a south wall. Instead, code it so that any light not on the north wall retains the extra layer, while the north light gets bumped down when New() is called.

**Comment by SpadesNeil** [comment]
This should be fixed now.

**Comment by Arokha** [comment]
It is fixed, lights are under macros.
