### ISSUE TITLE
Hail hits you when in caves.

### ISSUE THREAD

**Issue by Brandysnap** [VOREStation/VOREStation#4685]
#### Brief description of the issue
I was doing Xenoarch and It started hailing. I was in the middle of the caves in the Solar area and was being buffeted by the hail. I couldn't see it in any direction

#### What you expected to happen
Not to be hit by hail while in caves.

#### What actually happened
I died to hail tryingt o get out.

#### Steps to reproduce
- (Step 1) head out before hail into the caves of the solar area
- (Step 2) wait for hail.
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Umbrella's for xenoarch would be nice. Just in general.

**Comment by TheFurryFeline** [comment]
This will be fixed with #4486

**Comment by Brandysnap** [comment]
Are the excavation suits classed as voidsuits or softsuits? because if they're softsuits the problem will persist for Xenoarch.

**Comment by Heroman3003** [comment]
This issue is still active.

**Comment by TheFurryFeline** [comment]
I believe this is easily solvable by making cave areas have a roof for the turfs.
