### ISSUE TITLE
Paperback newspaper updates live

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4687]
#### Brief description of the issue
Newspapers update as the newscasters do, even after they were printed out

#### What you expected to happen
Them to have static state of the news channels saved from moment they were printed

#### What actually happened
Even after being printed they magically change, text appearing on them as more news come in

#### Steps to reproduce
- Have some news out
- Print newspaper
- Send more news through newscaster
- News appear in already-printed newspaper.

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Screemonster** [comment]
clearly it's e-ink :^)

**Comment by Very-Soft** [comment]
It's advanced technology, clearly

**Comment by Iroquois-Pliskin** [comment]
This is a feature, not a bug.

**Comment by Heroman3003** [comment]
This issue is still active.
