### ISSUE TITLE
Releasing prey then deleting predator deletes prey.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#470]
#### Brief description of the issue
Releasing isn't being handled correctly. After letting me out of their belly, Holly deleted herself (because shift was ending and couldn't be bothered with cryo) - I was also kicked to ghost even though I was stood next to her.

#### What you expected to happen
For her to vanish, not me.

#### What actually happened
Vanished.

#### Steps to reproduce
Eat prey
Later release prey
Delete self
Marvel at prey also in ghostchat.

#### Additional info:
Server revision: master - 2016-08-08
c463944382c15a7ddc9b5b5cadc1a99165dc5b31

**Comment by Screemonster** [comment]
Also I've still got the epic opera music playing that was in the bar when I got ate, even though I was carried off to the arrivals lounge before being released.

**Comment by SpadesNeil** [comment]
Considering this is a scenario that only occurs due to admin abuse, marking won't fix.
