### ISSUE TITLE
New vault checkpoint wall bugs

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#471]
#### Brief description of the issue
The areas with windows are filled in... with walls. >_>

#### What you expected to happen
To not have a wall INSIDE my window.

#### What actually happened
Some berk put a wall inside. :P

#### Steps to reproduce
Walk in and look at it. Its fucked. 

#### Additional info:
 - **Server Revision**: master - 2016-08-08
c463944382c15a7ddc9b5b5cadc1a99165dc5b31 
 - **Anything else you may wish to add**

**Comment by SpadesNeil** [comment]
Screenshooooottttttt.

**Comment by Cameron653** [comment]
Area: http://puu.sh/qAtaT/b8eb3e207a.png
Windows: http://puu.sh/qAtbv/ec64a4c416.png
