### ISSUE TITLE
Add engine setup guide to engineering

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#474]
#### Brief description of the request
Scree has written up a notice for people who haven't set the engine before, to be duct-taped to the engine room entrance. (both entrances)

#### The first note, to be put up outside the engine room, entitled "how to set the enjin by scree"
HOW NOT TO BLOW THE ENJIN UP

if yer short o power an ent dun it before, folow dis gide
espeshly captins, i no wot you lot is like fer bargin in ere like "hurr durr i got the bloo hat and a card wot lets me go enywere, i can do any job even if i dunno anyfing"

STEP WUN
IF YA DUNNO WOT YER DOIN, LEEV THE ENJIN THE HELL ALONE AN GO SET SOLARS INSTED
SOLARS IS ENUF. TURN SOME LIGHTS OFF. LEEV THE SUBSTASHUNS HOW THEY IS. WATE FER AN ENGINEER.

I dun wanna heer "oh boo hoo but solars is not as good and I gets scared of the dark like a big cryin baby so ill screw around wiv a reely danjerus fing wot blows the hel up if its set rong".

Scree

![engine setup guide](https://cloud.githubusercontent.com/assets/14942479/17648393/0a3768ba-620b-11e6-849f-afd54a94bf39.png)

#### The second note, to be pinned up somewhere in the engine room itself, titled "how to relly set the enjin"
STEP TOO - GAS AND PUMPS
if ya rilly wanna set it still, first put the gas into the pipes. Find the too ports on the starbud side of the room. Neer the nitro cans. Put a can on eech port and rench it on. Turn on and max the pumps for the ports. Wen the cans is empty, swap them for the too extra cans.
turn on the hi-volum pump onna far starbud side. Neer the window. Is hooked up to the radyater outside.

STEP FREE - WASTE STUFF
On the port side, turn the filters on. Theys the big wite square fings wiv arows.
turn on and max the pump between them and the yelow can.
ya can go to atmo and grab a can of CO2 and put it on the port to the aft of that too but that can wate.

STEP FORE - FIRE IT UP
Go to enjin room. Shut the shuters. Open the charging port. Chek the camra ta make sure its open. Turn the emiter on.
COUNT THE SHOTS. ONLY GIVE IT ATE. NOT NINE. NOT TEN. NOT BLUDY TWELV. TURN IT OFF WEN YER DUN AND IF YER DEF AND CANT HEER IT OR COUNT GO SET SOLARS INSTED.
Wen the emiters off, shut the charging port, chek the camra and open the shuters.

STEP FIVE - FOR GODS SAKE DUN MAX THE SMES INPUT
Open the power moniter and set it to enjin output.
Open the enjin moniter and hit the buton to find the port (it wil hav an erer)
Open the RCON consol and look at the main SMES.
SET THE MAIN SMES TO 100 KILOWOTSITS LESS THAN WOTEVER THE ENJIN IS PUTING OUT
DO NOT MAX THE MAIN SMES INPUT
no relly. It suks all the enjin power and then the won wot powers all the coolunt stuff in the enjin room dusnt get any charj. Then runs out. Then shuts off. Then it blows up. Stupid desine.

if ya dun all this then hopfuly the enjin wont blow
but really read a gide by some dude wot can rite gud
Scree

![engine setup guide 2](https://cloud.githubusercontent.com/assets/14942479/17648402/c1525406-620b-11e6-8ec7-26db84149e61.png)

#### Steps to reproduce
http://pastebin.com/dahfxQMg for HTML

#### Additional info:
I'll get screenshots of the locations to put them when I'm on a shift that HASN'T BLOWN UP.

**Comment by Arokha** [comment]
Polaris just updated the existing guidebook to make it concise and accurate. This might no longer be needed.
