### ISSUE TITLE
Sometimes shadekin mar so hard they break the server

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4749]
#### Brief description of the issue
when a blue eyes was in range of a corrupt hound corpse it said "MAR!!!" a lot.

#### What you expected to happen
for shadekin to not be triggered to the point of destroying reality if they see a hostile mob corpse

#### What actually happened
The shadekin said "MAR!!!" 6091 times in about 2 seconds before I could delete it.

#### Steps to reproduce
- get npc shadekin (not sure if eye color is important, but I think it would need to be one of the ones that follow you and eat you if you get too hurt, which miiiiiight be only blue eyes? I'm not 100% sure)
- present your shadekin with a hostile mob corpse (I'm not 100% sure if i must be dead, or if it happens with live hostile mobs either.)
- witness reality brought to its knees through sheer mar power

#### Code Revision
- release - 
1fe04192c11e2ad7357512d5a873c44a4ea687d3 

 
#### Anything else you may wish to add:
- I'm pretty sure what's happening is, since the blue eyes are -technically- hostile, when they see a hostile mob, they try to go for it, but then cancel out and then repeat infinitely.

**Comment by Novacat** [comment]
Shadekin no longer have AI, closing.
