### ISSUE TITLE
Prometheans are pitifully weak, and Polaris wants to nerf them more

### ISSUE THREAD

**Issue by Iroquois-Pliskin** [VOREStation/VOREStation#4795]
#### Brief description of the issue

**Primary Issues:**

- Current limb health is anywhere from 20-30. I've demonstrated extensively that Prommies can punch off their own heads/limbs in 2 hits, which must then be regenerated.

- Regeneration is time consuming, which is fine, but incredibly costly on the nutrition levels, requiring Prommies to be fully fed or above. On it's own, this would be a minor annoyance, but...

- Combined with a higher hunger speed and the fact that if regen is interrupted, the nutrition is still used, it becomes possible to nugget Prometheans permanently by removing their legs, letting them try to regen, interrupting it, and then dragging around your new victim.

- Lacking a head makes it impossible to eat normally, which isn't major, but kind of embarassing for those with table manners. They have a drain method, but you need a consenting participant, or an already subdued victim.

- Promethean Regen (Active and Passive) is done almost ENTIRELY via nutrition levels. Polaris intends to nerf this, and even make it cause pain because ???

**Secondary Issues:**

- Prometheans can't push/walk through anything that isn't another Prommie, a Teshari, or a simple animal. Previously circumvented by abusing Taur spaghetticode.

- The resistances they do have are completely offset by the weakness of their limbs, rendering the entire difference pointless.

- The worst nightmare of a prommie, welders, are widely available to any member of the crew. Not that this can really be fixed, but... it just compounds the existing issues.

**NITPICKING:**

- Prometheans can only speak 2 languages, one of which MUST BE GalCom

- The weakness to heat they have has never been adequately explained. XenoBio slimes don't seem to have a weakness to heat, but to cold.

#### What you expected to happen

To play a unique race with their own strengths and weaknesses, appearing genuinely alien in physiology, and for some characters, perhaps even mentality.

#### What actually happened

A downwards spiral of 'nerfs' and 'balancing' rendering Prommies easily killed by a stiff breeze. But hey, you're one of maybe 2 races unaffected by radiation, and can glow when exposed to it. That's nice, I guess.

#### Steps to reproduce
- Make a Promethean
- Punch your head 2 times
- Punch off a leg
- Congrats, you nuggeted yourself.

#### Code Revision
- current, 1fe04192c11e2ad7357512d5a873c44a4ea687d3

**Comment by Iroquois-Pliskin** [comment]
I would like to mention, as well, that we currently have an incoming PR that will cause regen to become painful to prommies, make them more susceptible to cold and shocks, and make regen harder to get going in more extreme environments.

Did you know that prommies were shock resistant? I certainly didn't. Not like it matters when their limbs are so weak that the hand burns off anyways.

**Comment by Mewchild** [comment]
Do keep in mind that the nerfs polaris has incoming are for *their* prometheans. Ours are nerfed heavily already, compared to Polaris prommies. I recommend removing the Vorestation edits once the prommie changes come through.

**Comment by Wickedtemp** [comment]
I'd honestly be in favor of having prometheans be as they were at the very start, maybe with a few **minor** tweaks. It's getting to the point where they have so many differences from every other playable species that honestly, they should reasonably require a whitelist, and it seems that the majority of promethean players either hate, or at the least, _don't want_ these changes. Some players with promethean characters in Exploration or Sec have simply scrapped the character altogether. 

The ability to redirect electrical charges was rather powerful - IIRC we removed that. Everything else about them wasn't really that robust, either average or perhaps just above average, and it's steadily gotten worse, and worse, and worse, and worse. We never really needed any of these changes, they all came upstream. Most of them are made with combat and antags in mind, which just aren't really a thing here. We'll have expeditions, and maybe the rare hostile-mob event, sure, but does anybody actually care if there's a promethean capable of taking a few hits without getting limbs gibbed? I don't. I don't see why it's necessary. They're already weak to burn, why completely nullify their resistance to brute by allowing them to be insta-stunned permanently by anyone capable of getting two hits off?

**Comment by Very-Soft** [comment]
I remember that we wanted nerfs for prommies at one point, because they were undeniably op when compared to other non-whitelist races in pvp settings.

The whole reason thunderdomes started getting race restrictions when they happened more often was because of the prometheans of those days (and then later because of the more extreme resistance and speed traits)

At this point though I don't think anyone would argue that our prometheans are at all OP, so it seems very silly that they'd be nerfed further.
