### ISSUE TITLE
Ian does not eat snacks with new release.

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#4806]
#### Brief description of the issue
Yeah yeah yeah, I found a bug with code that hasn't even been released yet. Sue me.

But yeah whilst testing to see if an old issue still occurs, turns out I updated my testing fork to the latest code so this maaay be broken because of the AI rewrite. But Ian does not seem capable of eating snacks when testing. He'll follow them, but no nibbling.

#### What you expected to happen
The code to work as it suggests and for candy to be nibbled.

#### What actually happened
Half an hour of a dog staring intently at a snack without ever nibbling.

#### Steps to reproduce
- Put any snack in front of Ian
- Wait. A lot.

#### Code Revision
- N/A as only noticed on a private server. Should be current master though.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Sebbe9123** [comment]
This has been an issue for ages, not sure what does it tbh.

**Comment by Shophaune** [comment]
Is this still an issue?
