### ISSUE TITLE
Scoop up code only works on humans.

### ISSUE THREAD

**Issue by Bluhblaghbluh** [VOREStation/VOREStation#481]
#### Brief description of the issue
A player can only be scooped by a macro if they use human as their species base.

#### What you expected to happen
Only size matters, not species.

#### What actually happened
See above.

#### Steps to reproduce
Take macro of any species and an average sized human and someone of any other species. Observe as the human can be scooped and put into the micro carrier and the non-human cannot.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
Already fixed by pr #477
