### ISSUE TITLE
Can't push through simple mobs

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#4817]
#### Brief description of the issue
With the latest update, it's impossible to push or trade places with simple mobs

#### What you expected to happen
Previous behavior. Push them, trade places on help intent, push on any other

#### What actually happened
They are as a wall, and only exhibit normal behavior when they move into you.

#### Code Revision
- 6c758051139daed75163f1941b40600bd97dceaa

**Comment by Novacat** [comment]
From what I gathered reading the code, this was a deliberate change from Polaris, as part of the AI refactor.
