### ISSUE TITLE
Missing item in loadout#1

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#482]
#### Brief description of the issue
Missing my revolver. was said it was ok to have a single action metbea, and it got coded in.

http://forum.vore-station.net/viewtopic.php?f=27&t=446

**Comment by Tasald** [comment]
custom_guns_vr.dmi (tasaldrevolver)

**Comment by Arokha** [comment]
Joan fixed the paths in custom-items, so next update.
