### ISSUE TITLE
Simplemobs are missing some things

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4820]
I understand that simplemobs were recently rewritten or something, but I noticed they are missing a few rather useful variables.

wander: setting it to 0 makes mobs not move around randomly

returns home: when set to 1, makes the mob return to whatever is marked as its home

wander distance: sets the distance from a mob's home turf a mob can roam when returns home is set to 1 and a home is set

home: setting this to a turf or a mob makes the mob wander to and around whatever you set if returns home is set to 1.

These variables are pretty useful for making mobs that follow people around, or stay within an area.

**Comment by ArgobargSoup** [comment]
Those variables have been moved to an "ai_holder" datum, it seems.

Check [here.](https://github.com/VOREStation/VOREStation/tree/master/code/modules/ai)

...Not quite sure how to work with them, but yeah.

**Comment by Very-Soft** [comment]
Ah! Yeah they're all there, and I think the following actually works way better than it used to! So that's that!
