### ISSUE TITLE
Cameras in Odd Categories

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#4826]
#### Brief description of the issue
There seems to be cameras listed that don't belong there.

#### What you expected to happen
Cameras in their appropriate places

#### What actually happened
An AI Upload camera under Sec, two listings for exterior view of the Vault, etc.

#### Steps to reproduce
- (Step 1) Spawn in as Sec/something with Bridge access for camera access
- (Step 2) Look at camera console
- (Step 3) Notice strange camera listings.....

#### Code Revision
- 6c758051139daed75163f1941b40600bd97dceaa 
 
#### Anything else you may wish to add:
List of borked cameras: Security Category: SEC - Vault Exterior West (2 of same name), AI Upload Chamber # 316 (Should be Command), Outside - Surface # 736 and # 803 (Should be Northern Star)
Engineering: Tether Shuttle Pad # 448 (Should be Civilian)
Northern Star Category: 2 listings for Outside - Surface # 660, 2 listings for Atrium Third Floor # 979, 
Medical Category: Redundant camera in Virology Access; either # 657 or # 630 can go, Same with Virology Quarantine, the area of moving patients from the airlock to Isolation - Virology Access # 834 and # 998
Civilian Category:  2 listings for Bar # 842

**Comment by prismaticIris** [comment]
A lot of those duplicates are for camera coverage for AI. If anything, we need more cameras because there's still a lot of weird blind spots that seem unintentional.

**Comment by Heroman3003** [comment]
The numbered cameras are randomly generated at the start of each round and as a result can have duplicate names without being duplicate. I will amend the doubling of named Vault Exterior camera, but fixing rest would need a big camera overhaul.

**Comment by TheFurryFeline** [comment]
As I said in Dev channel on discord, there was a similar issue with duplicates on CHOMPStation and was fixed with https://github.com/CHOMPstation/CHOMPstation/commit/cd57dbbd1b97e27aa14f7b1ecfa90413fe1ede6e

**Comment by Heroman3003** [comment]
From what I'm aware of, CHOMPStation uses Northern Star or Southern Cross, and if memory serves me right, both have every camera individually tagged, so in case problems ever came up with cameras, only individual tag needed fixing.

On Tether, vast majority of the cameras are not. They take name of their starting area, and a random number afterwards. If two cameras in same area happen to get same number, tough luck. I was planning to go over list of cameras with intent of fixes after atmos and post-atmos cleanup got merged, but in general current behavior is intended, even if far from best.

**Comment by TheFurryFeline** [comment]
Strange, since we still have the same collection of names for the cameras from Polaris since Chompers was synching from us for a while before stopping and it's still the same there as well. It's Northern Star, yeah.

**Comment by prismaticIris** [comment]
Camera changes may also want to reference Mewchild/Phi's Sweeping AI QoL #4599 pr

**Comment by Heroman3003** [comment]
Names for cameras are based on the map, not the code. So even if we were syncing for Polaris, we did use Tether still.
