### ISSUE TITLE
Missing item #3

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#484]
#### Brief description of the issue

Tasalds 'extra' implant for fluff.

http://forum.vore-station.net/viewtopic.php?f=27&t=26

**Comment by SpadesNeil** [comment]
Moved to extreme because GIVE THIS MAN HIS DAMN ITEMS HE JUST GAVE US 500 EUROS.

**Comment by Arokha** [comment]
Joan fixed the paths in custom-items, so next update.
