### ISSUE TITLE
Frozen pizza is not unfreezable

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4846]
#### Brief description of the issue
Frozen pizza cannot be truly unthawed

#### What you expected to happen
Microwave to make good pizza from frozen one

#### What actually happened
Microwave made it better, but did not unthaw

#### Steps to reproduce
- Microwave a frozen pizza
- Try to eat it

#### Code Revision
- 6c758051139daed75163f1941b40600bd97dceaa 
 
#### Anything else you may wish to add:
- Person who coded it 100% did not test it. The code does mention removal of frost oil for unthawed versions of pizzas, but the 'new' proc ALWAYS runs long before the reagents from ingridients are added, so oil is added after proc for its removal and sticks on pizza.

**Comment by Ketrai** [comment]
I've noticed. Trying to make a new proc as a recipes_vr.dm thing, to be ported to polaris later.

Since currently there isn't a way to properly remove reagents from food, for some reason.

**Comment by SpadesNeil** [comment]
Could just remove the frost oil as a temporary measure. Or add a negative reagent value. Or maybe we already tried that idk I haven't looked at the code in a while.
