### ISSUE TITLE
Missing item #4

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#485]
#### Brief description of the issue

Missing HoS coat, needs to be special spawned? or job restricted?

http://forum.vore-station.net/viewtopic.php?f=26&t=340

**Comment by Tasald** [comment]
custom_clothes_vr.dmi (tasaldcoat)

**Comment by SpadesNeil** [comment]
that's the DMI file ya doof, I meant the file path :U 

I meant like /obj/item/whatever/the/path/is/to/your/fluff/item

**Comment by Arokha** [comment]
Joan fixed the paths in custom-items, so next update.
