### ISSUE TITLE
Underdark Space Turfs

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#4851]
#### Brief description of the issue
So, I decided to start making submaps and was using a fresh clone of VoreStation codebase. Getting active edges as well as space turfs in one, two swaths at the Underdark on the Master branch

#### What you expected to happen
World to load normally

#### What actually happened
Two columns of space turfs at the Underdark

#### Steps to reproduce
- (Step 1) Clone current Master branch
- (Step 2) Set up private server
- (Step 3) Load, ghost, teleport to Underdark
- (Step 4) Blink in bewilderment at two swaths of space turfs that loaded in.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Very likely something to do with maploader or something. There may be other affected maps but tether_underdark.dmm is getting significant issues that need to fixed before the next updoot.

**Comment by TheFurryFeline** [comment]
I'd like to clarify that it's definitely not happening on live that I've seen.

**Comment by Sebbe9123** [comment]
I'm not able to recreate this bug, I don't see any space turfs anywhere in the map, at least within the unpassable blocks but I don't see anything outside that either.

**Comment by TheFurryFeline** [comment]
Issue explained away as caused by a conflict in the files after downloading a fresh clone of the current master branch. Others have tested and were unable to find said space turfs.
