### ISSUE TITLE
Gibber machine broke

### ISSUE THREAD

**Issue by prismaticIris** [VOREStation/VOREStation#4855]
#### Brief description of the issue
Accidentally had Cargo order too many chickens, so I decided to liquidate some of them into meat. Upon putting a chicken in the gibber and turning it on, the gibber wasn't considered empty, and let me turn it on again, producing more meat. This continued seemingly infinitely until I manually emptied the gibber. Placing another chicken in the gibber caused this to happen again.

#### What you expected to happen
One use of the gibber per chicken.

#### What actually happened
Functionally infinite uses of the fibber per chicken

#### Steps to reproduce
- (Step 1) Order chickens
- (Step 2) Smack one with the butcher cleaver, then aggressive grab into the gibber while the chicken itself is not adjacent.
- (Step 3) Get confused and try this again a few times.
- (Step 4) Move the chicken to the gibber and try aggressive grabbing it into the gibber again.
- (Step 5) Repeat Step 3
- (Step 6) Realize that you're supposed to drag the chicken into the gibber.
- (Step 7) Upon dragging the chicken into the gibber, start the machine
- (Step 8) Try dragging another chicken into it. It will report that it's not empty
- (Step 9) Start it again, and again, and again, and again, and again, receiving more meat every time.
- (and so on)

#### Code Revision
6c758051139daed75163f1941b40600bd97dceaa 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Sebbe9123** [comment]
Looks like this is an issue with the Gibber not vacating its gib contents, making it not empty and making it recycle the gore to make new meat infinitely. 
https://cdn.discordapp.com/attachments/187013248309002240/557125022657806336/5732a4eb0c5f92601c2a755b99d8e71a.png

**Comment by prismaticIris** [comment]
I forgot to mention earlier, but all the meat was being properly attributed as being chicken meat.

**Comment by Sebbe9123** [comment]
Further testing shows that the chicken does not get deleted after the gibbing process goes, Gonna guess the qdel thing isn't working correctly.

**Comment by Sebbe9123** [comment]
Just confirmed this is an upstream issue, send to polaris.
