### ISSUE TITLE
Sudden death via missing everything when pred disappears

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#486]
#### Brief description of the issue

I witnessed someone's body parts 'disappear' completely after they digested their own predator who absorbed them earlier. I've seen something similar to this earlier when I tried to cryo someone, but unsure if someone left at the exact time they suffered sudden death. It also seems to be unable to be cured via admin cure according to Hoodoo due to loss of brain as well. While everything ends up 'missing', the sprite of the character seems fine. I should also add that apparently the body was fine, but I think the missing brain may of been the cause of death.
#### What you expected to happen

Not to die and have everything 'missing' when the predator digests or poofs.
#### What actually happened

Sudden and horrible death when digesting/poofing the pred.
#### Steps to reproduce

In order to recreate the same exact scene, person 1 was first absorbed by person 2. Person 2 then coughs up person 1 and person 1 then proceeds to eat and digest person 2. I do not know if it's based by chance or it happens every time, but once this happened, person 1 ended up dying suddenly with everything missing.
#### Additional info:
- **Server Revision**: release - 2016-08-14
- **Anything else you may wish to add**: The victim themself was Katelynn Lee (FartingOwl might be their BYOND name I believe) and their partner was Dameon Owen.

**Comment by Arokha** [comment]
I can't reproduce this with the steps above.
# Person 1 ate Person 2, then set belly to absorb.
# Absorbed person 2 into Person 1.
# Used 'Eject' to spit them out.
# Person 2 ate Person 1, set belly to digest.
# Person 1 was digested, dropped digested ID etc, but nothing special happened.
