### ISSUE TITLE
remove trash POI from virgo2 (request)

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4865]
#### Brief description of the issue
virgo 2 that has POI that is just a trash pile

#### What you expected to happen
not to have some filler POI that is worse than nothing

#### What actually happened
It's just a trash pile. It only give used food packageing

#### Steps to reproduce
- (Step 1)go to virgo 2
- (Step 2) Enjoy your filler

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 6c758051139daed75163f1941b40600bd97dceaa 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Phi said he removed it. Why is it back?

**Comment by Screemonster** [comment]
Not every PoI has to serve a mechanical purpose or carry any loot. Some are _purely_ decorative just so the gaps between the PoIs that _do_ have loot is more than just a featureless wasteland.

Like, "enjoy your filler"? The hell kind of feedback is that to leave on something where the literal _purpose_ is to be filler?
