### ISSUE TITLE
 Mouthshooting yourself with a floral somatoray actually kills you 

### ISSUE THREAD

**Issue by DorfGuy1** [VOREStation/VOREStation#4869]
#### Brief description of the issue
putting a Floral Somatoray in your mouth kills you

#### What you expected to happen
for it not kill me.

#### What actually happened
I got a fucking Darwin award when I shot myself trying to prove that Floral Somatoray are harmless

#### Steps to reproduce
target mouth, 
hold floral somatoray

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 6c758051139daed75163f1941b40600bd97dceaa 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Its same thing with sizeguns and any other 'nonlethal' gun. Solution is to use common sense and not aim guns in your mouth.

**Comment by Novacat** [comment]
You should not be sticking even 'harmless' gun-shaped objects in your mouth, in my opinion.

**Comment by Wickedtemp** [comment]
Wasn't it decided that the heat or energy fired by the device, when pressed into your mouth, is lethal?

**Comment by Screemonster** [comment]
"I just blasted a giant beam of radiation capable of mutating organic life directly into my skull and it harmed me"

**Comment by prismaticIris** [comment]
Joining in on the chorus that this is expected behavior for pretty much any gun or gun-adjacent item.
