### ISSUE TITLE
Gophers mounted orebox refuses to take in new ore when full once

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#4871]
#### Brief description of the issue
A gopher (the micro-people ripley) has to use a mounted orebox instead of normal means. This works perfectly well (even if the cargo space for said orebox is way too small for my taste) exept when the box was full once. After that, even when emptied, the box will not take in any newly mined ore automaticly and you're forced to raise the box between mining and manualy sweep the are to grab all the ore.

#### What you expected to happen
Once the orebox was emptied, new ore that gets mined gets automaticly deposited into the mounted orebox, similar to how ripleys do it.

#### What actually happened
Mined ore was deposited on the ground where it was mined, just like how mining without an orebox does it.

#### Steps to reproduce
- (Step 1) Aquire a gopher and a micro, equip it with mining equipment and head to the mining areas.
- (Step 2) Mine until the gophers mounted orebox is full, then empty it
- (Step 3) Mine again and notice all the phoron/iron/whatever gets deposited on the ground.
- (Step 4 [Optional]) If no problems where found with the first 3 steps, switch out the drill for a diamond drill and repeat.

#### Code Revision
6c758051139daed75163f1941b40600bd97dceaa 
 
#### Anything else you may wish to add:
- May or may not be caused because of diamond drill and mounted orebox interactions. I can't confirm if this was because of not using the ''right'' drill or if this is a problem with the mounted orebox itself.

**Comment by Heroman3003** [comment]
It is intentional behavior. Micromech drill will automatically move mined ore into the micromech ore scooper. Regular/Diamond drill will automatically move mined ore into the orebox inside hydraulic clamp. The two do not mix-match.

**Comment by SpadesNeil** [comment]
I think you misread.

>After that, even when emptied, the box will not take in any newly mined ore automaticly and you're forced to raise the box between mining and manualy sweep the are to grab all the ore.

This doesn't sound intended.

**Comment by Heroman3003** [comment]
What really was not intended. Was ability to attach non-micro drills to micro mechs. Which resulted in ore not being automatically scooped when using micromech ore scooper with non-micromech drill. What needs to be fixed is not scooper/drill interaction but equipment capability.

**Comment by Screemonster** [comment]
yeah, if someone was mounting a non-micro drill on a gopher (which should never be mountable on a gopher, and _wasn't_ until the mech refactor upstream) then the mounted ore scoop wouldn't work because the code for putting the ore in the box is on the drill, not the box, and the non-micro drills don't check for micro ore boxes because why would they
