### ISSUE TITLE
Admin Tool issue - 'Kick' player not being able to cancel

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4876]
#### Brief description of the issue
No way to cancel a kick when you click the button.

#### What you expected to happen
Either putting in a blank reason to cancel the kick or having a 'cancel' button somewhere if you change your mind.

#### What actually happened
A blank reason will still result in a kick and there's no 'cancel' button on the pop-up window.

#### Steps to reproduce
-Open up Player Panel
-Select a player to kick
-Select 'kick'.
-Change your mind and decide you wish to cancel it.
-Enter blank reason
-X has been booted.
-Cry and hope you didn't just make an enemy for life.

#### Code Revision
6c758051139daed75163f1941b40600bd97dceaa

**Comment by SpadesNeil** [comment]
That is pretty fucking obnoxious.

**Comment by SpadesNeil** [comment]
Sent this issue to Polaris myself. Will close it here.
