### ISSUE TITLE
Fake Plasteel walls look like regular steel walls

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#488]
#### Brief description of the issue

When I was disassembling a reinforced plasteel wall, I used the plasteel sheets to make a fake plasteel wall. While there is a fake wall there, it looks like a regular steel wall instead of a reinforced wall and it's labeled as 'plasteel wall' instead of 'reinforced plasteel wall'
#### What you expected to happen

The fake wall to look like reinforced plasteel and named correctly as well.
#### What actually happened

It looks like a regular steel wall and it's called 'plasteel wall'.
#### Steps to reproduce

Disassemble the reinforced wall/assemble girders
Crowbar the girder
Apply Plasteel
Behold!
#### Additional info:
- **Server Revision**: release - 2016-08-14
- **Anything else you may wish to add**: Normally graphical problems usually aren't a major deal (along with the back view of the simple webbing looking a bit farther to the right than it should, but who notices that?), but when it comes to stealthy entrances and secret exits, it might make being a 'clever' sneaky deviant a bit harder if they weren't already caught trying to disassemble one of the game's tougher obstacles.

**Comment by Arokha** [comment]
I replaced every wall sprite, so.

**Comment by Screemonster** [comment]
Also I think there was a bit of confusion anyway.
What you made was a plasteel wall. Not a reinforced plasteel wall.
