### ISSUE TITLE
Exploration department relocation - mapping project

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#4894]
#### Brief description of the issue
The main issue this seeks to solve is the fact that the chapel is presently almost completely isolated on Asteroid 2, where pretty much nobody ever goes as the only things there are the AI upload, EVA, and a maintenance entrance into medical. Likewise, the expedition is one of the departments most likely to have a use for additional EVA suits if they're bringing extra volunteers along, so it makes sense for them to be closer, along with the back entrance to medbay.

Figured I'd make an issue to brainstorm the finer details. A crappy mockup can be found below. To sum up - chapel moved to where the hangar is now. This leaves plenty of space around it to make the chapel a little bigger, add a proper funerary area next to the mass driver like on boxstation, or whatever other changes we feel like. Exploration department is moved to the vacated space, with a little room to expand northwards, staging area / meeting room in front of the shuttle, gear storage and pathfinder office to the right, and some extra space for the backup shuttle to be parked. AI core and upload shunted to the right, the core is no longer completely surrounded by maintenance and beset by the constant sounds of mice bumping doors.
 
Discuss, 'cause although some things were discussed in discord they've already scrolled waaaaaay past the screen.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/14942479/55296527-b4255200-5412-11e9-958e-1f770731ebf1.png)

![image](https://user-images.githubusercontent.com/14942479/55296531-bdaeba00-5412-11e9-9834-0761da6f7a06.png)

![image](https://user-images.githubusercontent.com/14942479/55296535-c56e5e80-5412-11e9-8de1-cf594932d548.png)

**Comment by Heroman3003** [comment]
Posting from development, but space near chapel is best filled by moving gateway there and maybe giving it a more thought-out/refined prep area. In addition to being closer to exploration, which is what meant to be handling gateway-related events, They could potentially access it vertically via staircase down and have gateway prep area be either isolated from station 1 and only accessible from hangar or have some equivalen of shtters, just said shutters not being the only access point.

**Comment by nerdass** [comment]
chapel is only there because of the mass driver for orbital burials, which is an artifact of boxstation

**Comment by Novacat** [comment]
We can make the expedition area multi-Z level. and use the space above/below for things.

A few things to keep in mind:
- The Pathfinder's Office had a neat thing going on with windows to the explorer breifing room/prep room.
- I have plans at some point to expand the size of the expedition shuttle.
- The Hangar itself should probably have some public access way of getting to it.

**Comment by Screemonster** [comment]
I completely hadn't thought of using that _massive_ space on Asteroid 3 as a second floor to the hangar/exploration department.

**Comment by Novacat** [comment]
Mostly Stasis cages, but it would not be a bad idea to have a general storage room for large objects.

**Comment by Very-Soft** [comment]
oh I actually like this a lot.

**Comment by Screemonster** [comment]
Come to think of it, if the gear rooms and the like were on asteroid 3 (with stairs down to the hangar itself on A2, we could put a rear/maint entrance in for easier access to the hangar to/from cargo.
