### ISSUE TITLE
Solar airlocks aren't big enough.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#490]
#### Brief description of the issue
the airlocks leading out to the solars have only one tile between the doors. This wasn't a problem on old code when crates didn't block airlocks from closing, but now it's impossible to cycle the airlock properly while dragging a crate out - such as a solar panel kit.

#### What you expected to happen
To be able to drag a crate of solar panels out without having to force doors.

#### What actually happened
The airlock behind me with the crate in it just buzzed when I hit cycle.

#### Steps to reproduce
Step onto the one tile the airlock offers you while dragging a crate.
Hit "cycle to exterior"
Stand there like a lemon while the door just buzzes at you.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Climb onto the crate. :)

**Comment by SilverTalismen** [comment]
Yeah but all it takes is a single click and the crate below you opens and you fall and more than likely break something
