### ISSUE TITLE
Promethean Cores Decay

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#4913]
#### Brief description of the issue
Promethean cores decay like a regular organ!

#### What you expected to happen
For this not to happen since I literally wasn't expecting it.

#### What actually happened
The core became decayed. I wasn't able to test if the promethean can still be brought back, though.

#### Steps to reproduce
- Be promethean
- Die
- Wait then have someone check the core

#### Code Revision
- 6c758051139daed75163f1941b40600bd97dceaa 

#### Anything else you may wish to add:
- I suspect this is simply due to it being a child of brains. Still, it made me worried it would affect my revivability.

**Comment by Mewchild** [comment]
For record-keeping, closed via https://github.com/VOREStation/VOREStation/pull/4965
