### ISSUE TITLE
HUD icons duplicating

### ISSUE THREAD

**Issue by Mythophage** [VOREStation/VOREStation#4918]
#### Brief description of the issue

Security HUD icons will "stick" in place and duplicate in place after an elevator ride.
#### What you expected to happen
HUD icons will stick to characters

#### What actually happened
HUD icons freeze in place, resulting in duplicates

#### Steps to reproduce
- (Step 1) Equip security glasses/hud
- (Step 2) Take the lift up to the top floor of the asteroid, take one step forward and viola! Duplicate icons!

#### Code Revision
9be365dcb8ffd2e565ee8f6e19dc02c009156bc0 
 
#### Anything else you may wish to add:
![Hud glitch](https://user-images.githubusercontent.com/49329559/55663886-db08cd00-57f2-11e9-8491-2f28100a3a0e.png)

**Comment by Mythophage** [comment]
![Hud glitch 2](https://user-images.githubusercontent.com/49329559/55664682-1d84d680-5800-11e9-8b59-7518cdef9886.png)


Addendum: Also affects speech bubbles

**Comment by LiquidFirefly** [comment]
also clones Z level shadows 
![Capture](https://user-images.githubusercontent.com/27702808/55672446-3f667380-5869-11e9-80a5-162c21b55af6.PNG)
