### ISSUE TITLE
Closet painters make crates invisible.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#492]
#### Brief description of the issue

I tried to put a closet painter back in a station painting supplies crate, and it changed the crate's sprite to invisible.
#### What you expected to happen

For it to paint the crate at most.
#### What actually happened

The crate vanished.
#### Steps to reproduce

Order station painting supplies crate.
Pick up closet painter.
Put closet painter back in crate.

Have not yet tested what happens if I activate the closet painter in-hand to pick a colour first.
#### Additional info:

Server revision: release - 2016-08-14
46b3bb734538fe50433122d41fdd741522aa55f5

**Comment by SpadesNeil** [comment]
Is this still a bug?
