### ISSUE TITLE
Randomized items spawn on top of containers at round start

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4925]
#### Brief description of the issue
Lots of stuff in maint are randomized items some things aren't randomized. Many of these things spawn in crates and lockers.

All of the random things that would normally be in the crates and such are appearing on top of them instead, while the things that aren't randomized go inside of them.

#### What you expected to happen
Loot in treasure chest

#### What actually happened
Loot stacked on top of chest

#### Steps to reproduce
- start server
- go in maint
- behold the things on top of crates

#### Code Revision
- release - 
9be365dcb8ffd2e565ee8f6e19dc02c009156bc0
 
#### Anything else you may wish to add:
- If I had to guess, I'd probably say that the randomized stuff got put to spawn after the crates or some such as that, and so the contents don't go inside of them anymore. You can still just like open up the crate and close it again to put the things back inside so it's not like, a giant issue, but it's clearly not supposed to work this way.

**Comment by Neerti** [comment]
https://github.com/PolarisSS13/Polaris/pull/6033 should fix it.
