### ISSUE TITLE
Saddlebags broken

### ISSUE THREAD

**Issue by CSchlippy** [VOREStation/VOREStation#493]
#### Brief description of the issue
Saddlebags appear to be broken on horse tails.
#### What you expected to happen
The saddlebags are supposed to work on horse-taur/taur type characters.
#### What actually happened
It sticks out ahead of the character as though it were a backpack on a normal player.
#### Steps to reproduce
Strap a saddlepack onto a character with the horse tail.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
![saddlebag](https://cloud.githubusercontent.com/assets/21138331/17829732/d9a58dcc-667d-11e6-82f1-e10f677da93b.png)

**Comment by SpadesNeil** [comment]
@viv-eret

**Comment by Cameron653** [comment]
Looks like the sprite just needs to be flipped around from left to right.

**Comment by CSchlippy** [comment]
Here's the thing though, it does it for both directions, but works fine for North/South directions. Maybe switching the sprite locations for the side view could work?

**Comment by SpadesNeil** [comment]
I believe this was fixed but no one referenced the issue in their PR.

**Comment by SpadesNeil** [comment]
Lack of response leads me to believe this was fixed.

**Comment by SpadesNeil** [comment]
Should be fixed.
