### ISSUE TITLE
Tank Transfer Bombs Broke

### ISSUE THREAD

**Issue by LuxeSaga** [VOREStation/VOREStation#4931]
#### Brief description of the issue
The Tank Transfer based explosives do not work. It seems like the hot-cold phoron oxygen reaction just doesn't happen. 

The Phoron Temperature was around 10,000 Celsius
The Oxygen was somewhere between 0 and 20 Celsius.

#### What you expected to happen
The Phoron and Oxygen to mix via the Tank Transfer Valve and detonate once a signal had been sent to the attached Signaler

#### What actually happened
Nothing. The signaler didn't mix the gasses, and when manually activating the Tank Transfer Valve, the gasses mixed with no reaction.

#### Steps to reproduce
- (Step 1)
Create a superheated phoron gas, and a supercooled oxygen gas.
- (Step 2)
Extract Phoron and Oxygen into their respective tanks
- (Step 3)
Put the tanks together via a Tank Transfer Valve
- (Step 4)
Add a Signaler Device to the tank transfer valve
- (Step 5)
Send a signal to the signaler, or manually open the valve on the tank transfer valve.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Have you checked the result in bomb tester? Could have been a failure in the gas proportions/temperature/etc.

**Comment by LuxeSaga** [comment]
> Have you checked the result in bomb tester? Could have been a failure in the gas proportions/temperature/etc.

How do we use the bomb tester? I attempted to use it but for the life of me could not work it out :p

**Comment by Heroman3003** [comment]
Put in the TTS with attached tank and test it on the two-tank mode.

**Comment by LuxeSaga** [comment]
After further testing, it looks like the explosives do still work. However, changing this thread to address the fault in signalers not working.
