### ISSUE TITLE
People can walk over tables if micros are standing on them

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4933]
#### Brief description of the issue
If micros are standing in a table, people who can normally walk over micros will be able to walk over the table as though it's not there.

#### What you expected to happen
People to be stopped by tables

#### What actually happened
people use micros as stepping stools to cross the barrier

#### Steps to reproduce
- put micro on table
- have someone who could step over them walk into the section of table the micro is on

#### Code Revision
- release - 
9be365dcb8ffd2e565ee8f6e19dc02c009156bc0
 
#### Anything else you may wish to add:
- It's a fun bug, I like it, but I've already seen some folks deliberately abusing it, using micros scening on the bar as a shortcut.

**Comment by KasparoVy** [comment]
Helping hands.
