### ISSUE TITLE
Suggestion: Let people who need a resleeve ping medical

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#4945]
Sometimes medical gets busy and misses the message, or doesn't know if a person actually wants to be resleeved or is even still around or all that.

It'd be cool if you're eligible to be resleeved, if you clicked on the resleeving machine it would give medical a '[X] is passed due for a mind backup.'

Just like, put a 5 minute cooldown on this so that people can't spam it like crazy. This way you can politely remind medical that you're waiting, without needing to hunt all around and looc at people to help you.

**Comment by Screemonster** [comment]
Morgue trays have a little light on them that indicates whether the player's ghost is still in the body (ie. so medical know whether they can attempt to clone) so maybe something like that could be implemented?
Click button, and if your mind has a transcore record, the resleeving machine has a light come on and marks your entry with a flag. Can even fluff it as having detected the past-due backup so it basically asks the mind if they want to be resleeved or not.

**Comment by Very-Soft** [comment]
Ye. The main thing is putting in some kind of thing to get medical's attention if they miss the message or forget that they need to resleeve someone.

**Comment by Screemonster** [comment]
Having it require ghost-interaction to highlight "yes I would like to be resleeved" would also help alleviate issues of doctors going down the list and mashing resleeve on everyone, resulting in people being resleeved that are leaving the game (but haven't hit quit-round yet) or have been put into other mobs.
