### ISSUE TITLE
Cannot feed self to any simple_mobs

### ISSUE THREAD

**Issue by Nekri** [VOREStation/VOREStation#495]
it basically doesnt let you force yourself into there maw, gives this ( Nekri Fokia gently taps the corgi (Dork-dog) with the grab. ) when you try too

expected: to force feed yourself to it
#### What actually happened:

Nekri Fokia gently taps the corgi (Dork-dog) with the grab.
#### Steps to reproduce:
1. Grab mob aggressively.
2. Click the mob.
#### Additional info:
- **Server Revision**: See comments.

**Comment by SpadesNeil** [comment]
Please include the server revision. Other than that, the issue post looks good and clearly explains what is wrong.

**Comment by SpadesNeil** [comment]
Still a bug as of https://github.com/VOREStation/VOREStation/commit/2e5f80175c18f61f6069be489632ae5ee4454de1 and it's true for all animals.

**Comment by SpadesNeil** [comment]
Still an issue?
