### ISSUE TITLE
East of the station lacks solar panels

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#496]
#### Brief description of the issue
Over my time playing as an AI, cyborg, or an electrical engineer, I've noticed there are only 4 solar panels. While decent enough to power the station if a few lights are turned off, the current station only has the SE wing able to gather energy from the east, while the other 3 pretty much are left to gather trickles until the sun comes around. I'm not saying this is a MUST, but it would really be helpful to add one more wing that can gather electricity from the east so we can use something less scary than the engine, or at least move the top-most solar wing upward enough so it can gather energy when the sun goes east as well. While an AI can easily turn almost off all of engineering to somewhat balance it out, eventually it seems brown outs will happen, especially if the station has already lost enough power to the point where all the APCs are trying to recharge and some are already browning out, while the solars can only charge so much at certain periods of the shift.
#### What you expected to happen
A somewhat reliable alternative to the engine
#### What actually happened
Brownouts when the sun sets on the east of the station.
#### Additional info:
 - **Server Revision**: release - 2016-08-14
 - **Anything else you may wish to add**: This might be intentional on the mapmaker's part to simulate a 'night' cycle on the station where solar energy is really hard to obtain. Also, the SE solar has the most sun time out of all the wings with an angle greater than 180'.

Alternatively, it would be nice to add light switches to the dorms so people can save on electricity by being able to turn off the lights without unlocking the panels, that place eats up a LOT of power via lights along with the prison wing, lights that people don't need on 24/7 (Except the prison wing, those light are probably necessary to see any breakout/breakin attempts.).

**Comment by Screemonster** [comment]
Fun fact: solar panels only look for objects with density 1 within 20 tiles.
Another quirk of BYOND is that the SE SMES is the last one that the powernet will look to drain charge from, so if the other three are covering the station's needs, it won't ask for any from it.

One thing I've seen people doing is attempt to charge the substations while the station's on solars. This is not the smartest move, turn that shit off.

**Comment by Dinnel** [comment]
So you're saying it's all intentional including the 'night' cycle and it requires turning off the substatons? I've never am quite able to run the station on just solars long enough to tinker with things before an engineer turns on the engine. I might need to make a private server to see if that works.

**Comment by Screemonster** [comment]
The thing about solars on their own without an engine is...

1: it takes like an hour for the station to rotate, so it takes time to get their SMESs charged enough to be worthwhile.
2: If you set the output levels too high, as in higher than what the panels are getting, they turn off.

The station can run on less than 500kW, so 125kW output for each solar is sufficient. The problem is that you can't turn the outputs on to that level unless they've had time to charge.
Ideally, one should want to use the engine and set the solars charging so they're ready just in case something happens.

One thing that I HAVE considered as a mapping modification is moving the cable for the solar down by engineering, 'cause routing emergency power through the area that gets blown up if main power fails is silly.

**Comment by SpadesNeil** [comment]
This does sound intentional. Scree, you know more about the solars than I do. Should I mark this won't-fix, or invalid (not a bug)?

**Comment by Screemonster** [comment]
I need to measure the output in full-sun at some point for each array 'cause the new station does have higher requirements than the old one. MAYBE expand each array by one row like we did on the 2014-map. (technically Scree added two rows to both the aft arrays a couple of days ago, giving them two solar crates each, but that was 'cause the SME exploded again and when he arrived his response was "screw building an entire engine by myself, I'll just make the solars bigger")

**Comment by SpadesNeil** [comment]
I think we already expanded all solars by one row as it is. If there's four rows, then we did this already.

I still want solars to be a pain in the ass to run the station on without energy rationing but I want it to be _doable_ with energy rationing.

**Comment by Dinnel** [comment]
I believe each solar wing is capable of generating, without additions, 120kw per wing. So total it's 480kw each one CAN generate. The sun and outputting is a different story. If half of the station makes the solars go dark, in order for the output to be steady, each one would have to be 60kw if half the hour is day and the other is night (1/2 basically) so the SMES doesn't drain and eventually turn off I believe. This doesn't factor in the trickle of energy it gets from when it goes dark, so it's not completely turned off at 'night'. But total, I think the station has 240kw from solars, while the engine I think can generate close to 800-1000kw... I believe. Maybe?

**Comment by Screemonster** [comment]
The master power network _does_ draw extra at the start of a shift, mainly on account of having to charge the AI SMES and there's no way for anyone other than the AI to access that to turn it down.
Having an AI at all is a power drain too, which _can_ make the option of joining as AI to babysit the solars as an alternative to rolling engineer less viable.
