### ISSUE TITLE
Missing Fluff Items

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#497]
#### Brief description of the issue

I was approved for these back in October of 2015, nearly a year ago. Multiple requests to actually recieve these items have fallen on deaf ears. 
http://forum.vore-station.net/viewtopic.php?f=26&t=200&p=1002#p1002
#### What you expected to happen

To recieve these simple fluff items in something resembling a timely fashion.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add**
  Since the time of my request, the filepath that gave Greyson's jacket its armor values and such
  /obj/item/clothing/suit/armor/hos/fluff/brittrenchcoat 
  has changed. THIS is the new HoS jacket filepath
  /obj/item/clothing/suit/storage/vest/hoscoat

As such its inheritance has broken. I would very much appreciate if this was fixed as well. Hell, just take the Jensen coat base and change it to the new sprite.

**Comment by JoanRisu** [comment]
If there is nothing else, this should be closed.

**Comment by SpadesNeil** [comment]
Actually what should be happening is I should be correcting the lack of names on our config file.

**Comment by SpadesNeil** [comment]
This should be mostly resolved. Is it?
