### ISSUE TITLE
world.tick_usage - Undefined var

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#498]
#### Brief description of the issue
Downloaded the latest version of the code, and tried to rebuild, but received several errors about an undefined variable.

#### What you expected to happen
A finished compile.

#### What actually happened
`loading vorestation.dme
loading interface\skin.dmf
code\controllers\ProcessScheduler\core\process.dm:204:error: world.tick_usage: undefined var
code\controllers\ProcessScheduler\core\process.dm:207:error: world.tick_usage: undefined var
code\controllers\ProcessScheduler\core\processScheduler.dm:346:error: world.tick_usage: undefined var
code\_helpers\time.dm:22:error: world.tick_usage: undefined var
vorestation.dmb - 4 errors, 0 warnings (8/20/16 7:22 pm)`

#### Steps to reproduce
Download code, attempt to build?

#### Additional info:
I'm probably missing something obvious, but, well, a search through the code I have and the code here on Github reveals that world.tick_usage isn't defined anywhere.

Also I apologize if this isn't the right place for this kind of bug.

**Comment by Cameron653** [comment]
Agh, let me see about fixing this

**Comment by Cameron653** [comment]
Are you on byond V510? The code will only compile on clients that are 510 or higher. I just compiled and it came out perfect

Photo: http://puu.sh/qILxk/8676db5a39.png

**Comment by ArgobargSoup** [comment]
Ah.  I was a few BYOND versions behind.  Sorry about that!
