### ISSUE TITLE
Suggestion: Quartermaster office with privacy shutters/tints.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4993]
#### Brief description of the issue
All other offices get privacy tints but not the Quartermasters?!

#### What you expected to happen
To be able to privately scene in the Quartermaster's office!

#### What actually happened
People pressing their faces up against the glass, oogling me as I enjoy my delicious meal!!!

#### Steps to reproduce
-Go to Quartermaster's office.
-Get embarrassed as people watch you cram your fat mouth with prey.
-Go to dorms instead.

#### Code Revision
9be365dcb8ffd2e565ee8f6e19dc02c009156bc0
 
#### Anything else you may wish to add:
N/A

**Comment by Screemonster** [comment]
Has the QM office been private on any map? Even on Box I used to eat people in the warehouse or the mining dock.

**Comment by Mewchild** [comment]
Some iterations of Boxstation had windows you could tint

**Comment by Heroman3003** [comment]
+ even pathfinder office has it.
