### ISSUE TITLE
Micro cooking

### ISSUE THREAD

**Issue by Nekri** [VOREStation/VOREStation#500]
#### Additional info:
 - **Server Revision**: (( I would but im not currently logged on it ))
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Unfortunately, due to the way micros are handled, this cannot be fixed.

There is a possible work-around of changing the micro sprite for a fried placeholder, but that requires snowflake code.

**Comment by CSchlippy** [comment]
Does this happen if you manual kill a micro? (Shoot, maul, etc)

**Comment by SpadesNeil** [comment]
I imagine it would. Find a willing ~~victim~~ test subject!
