### ISSUE TITLE
Surface Eva Atmos alarm screams whenever anyone enters 

### ISSUE THREAD

**Issue by prismaticIris** [VOREStation/VOREStation#5003]
#### Brief description of the issue
The atmosphere alarm for the public surface Eva goes off whenever anyone comes back in, due to low temperature 

#### What you expected to happen
No alarms 

#### What actually happened
Alarms! 

#### Steps to reproduce
- (Step 1)go outside using whatever door you want 
- (Step 2)come back inside via public surface eva
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
I mean I wouldn't really call it screaming. It goes yellow from temp if someone comes inside, until the doors into the hallway are opened. I actually kind of like when the alarm goes yellow for that as the AI, because it lets me know when people are coming back inside, which is occasionally useful.
