### ISSUE TITLE
Missing sprites for k9 cyborg

### ISSUE THREAD

**Issue by EtheoBoxxman** [VOREStation/VOREStation#5025]
#### Brief description of the issue
Default k9 cyborg sprites are missing

#### What you expected to happen
Visible sprites :P

#### What actually happened
Invisible sprites

#### Steps to reproduce
Just join as a cyborg
Select K9
Then select the first, default, option

I've no idea how to go about fixing it myself, so.
This is the next best thing.

**Comment by Shophaune** [comment]
Fixed in #5017, it's just not live yet
