### ISSUE TITLE
Commlink News Viewing

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#5027]
#### Brief description of the issue
News on one's Commlink aren't easily viewable.

#### What you expected to happen
Open up News tab on your Commlink to see Station Announcements or other news channels

#### What actually happened
Unreliable viewing of channels' contents, unclickable channels

#### Steps to reproduce
- (Step 1): Have a NIF
- (Step 2): Open Commlink
- (Step 3) Go to News section
- (Step 4): Try to view contents of channels
- (Step 5): Cry about an epic fail. :c

#### Code Revision
0c8f28e931c3a02d580c3c805b0b1e076ef8d004 
 
#### Anything else you may wish to add:
https://imgur.com/a/RAKsmo6

Post-typing thought of the day: I realise this might be better put on Polaris but I want to check here first, since Commlinks are more for NIFs.

**Comment by Heroman3003** [comment]
Its an issue present in all forms of communicators, including upstream. From my skim, it seems like news feature is plain unifnished. Like communicators in general.
