### ISSUE TITLE
Make it easier for cloning to be restocked with biomass

### ISSUE THREAD

**Issue by Nekri** [VOREStation/VOREStation#504]
#### Brief description of the issue:

A few docs in medical second that it'd be very nice to get a Enzymatic Reclaimer in the genetics room, we are currently having to do alot of steps to get synth meat for biomass. and this could cut the steps down immensely. considering you just have to toss a monkey in it to get mass, instead of making a ton of chems. but I would also suggest installing it with the safety off or we will not be able to use it for monkeys.

http://wiki.ss13.co/Medical_Objects

down twords the bottom of the list
#### Additional info:
- **Server Revision**: 46b3bb734538fe50433122d41fdd741522aa55f5

**Comment by SpadesNeil** [comment]
When requesting a change that isn't a bug, but a change to an existing feature, you do not need to fill out anything but the brief description and server revision. I know that isn't clearly communicated, sorry. ^^;

**Comment by viv-eret** [comment]
...we could also very easily make a plant-bag for meat.

Just a suggestion.

**Comment by SpadesNeil** [comment]
That might be easier lol. Else I gotta port this thing from /tg/.

**Comment by Screemonster** [comment]
I'm sure the plant/ore bag for meat/synthmeat has been brought up in chat before and is probably the easiest way of doing it. Probably worth kicking upstream too.
