### ISSUE TITLE
AHeals do not close bleeding wounds

### ISSUE THREAD

**Issue by Novacat** [VOREStation/VOREStation#5060]
#### Brief description of the issue
Aheals do not properly close bleeding wounds.

#### What you expected to happen
Aheals to close bleeding wounds.

#### What actually happened
All injuries were removed, but the person ahealed continued to bleed. Bleeding was not treatable due to lack of wounds.

#### Steps to reproduce
- (Step 1) Injure someone to the point that they are bleeding.
- (Step 2) Aheal them.

#### Code Revision
0c8f28e931c3a02d580c3c805b0b1e076ef8d004

**Comment by Screemonster** [comment]
rejuve/revive is horrible horrible horrible old code and half of it is super deprecated.

**Comment by Wickedtemp** [comment]
Yeah, had a few instances where someone was hurt and I got there to help them and they were ahealed while I was working on them. It usually caused this problem and also didn't make sense because Medical was already there so no point in the aheal to start with.
