### ISSUE TITLE
More vore mobs icons!

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#509]
I want to discuss new vore mobs and what we should add. Limits are up to 64x64 pixels. Some mobs may be played by humans for events. Discuss ideas here.

All mobs require icons for:
- Alive (North, South, East, and West)
- Full stomach (North, South, East, and West)
- Dead

So a total of 9 icons minimum for a mob that can move.

I need sprite artists to aid in this task. Here's a list of mobs we could use sprites for:

Sprites can either be 32x32 or 64x64. The max we'll do is 96x96.
- [ ] Gator (64x64)
- [x] Wolf
- [x] Wolf (64x64)
- [ ] Komodo dragon (64x64)
- [x] Dragons! (64x64)
- [ ] More dragons! (96x96)
- [x] Big Frog
- [x] Horse
- [ ] Gryphon (64x64)
- [ ] Lion (64x64)
- [ ] Tiger (64x64)
- [x] Panther (64x64)
- [ ] Various man-eating species.
- [ ] Sarlaac pit (64x64)
- [x] Hippo (64x64)
- [ ] Sphinxes are neat too (64x64)
- [ ] Slimes
- [ ] Space Shark (64x64)
- [ ] Raptor (64x64)
- [ ] T-Rex (96x96)
- [ ] Snake (32x32)

All vore mob sprites must have an icon for each level of fullness relevant to 1 normal sized human prey. If the mob is meant to eat multiple prey, there should be multiple icon sets.

**Comment by Arokha** [comment]
No normal dragon?

**Comment by SpadesNeil** [comment]
Too big!

Ah fuck it, why not?

**Comment by Screemonster** [comment]
I need to raid tgstation's repo for things to ~steal~ port, like ash drakes

**Comment by Arokha** [comment]
> Too big!
> 
> Ah fuck it, why not?
> 

They can be like... smalldragons! SPACE WYVERNS.

**Comment by ArgobargSoup** [comment]
[I don't suppose catgirls are on the list?](http://i.imgur.com/ktUyrHL.png)   :P

Happened ta have these left over from a mostly-abandoned personal project.  Can provide the DMI if it's not too silly for ya.  :P

**Comment by SpadesNeil** [comment]
Fuck it, sure. I'll fluff some IC reason for their freakishly large anime eyes.

**Comment by ArgobargSoup** [comment]
[CatgirlForVirgo.zip](https://github.com/VOREStation/VOREStation/files/438861/CatgirlForVirgo.zip)
The "freakish anime eyes" bit was just a personal preference.  Looked a bit better to me than SS13's normal pixel eyes.  :P  Speaking of which, I dropped in a version with normal SS13 style eyes if you'd prefer to use that instead.

If I remember my project correctly, was gonna have them spawn in, pick a player to stalk, nom/UB them, then find a place to nap.  Fluffy endo stuff.

**Comment by CSchlippy** [comment]
1) Catgirl vore invasion sounds awesome.

2) could we add a toggle for once your eaten that you choose if you want to let it do endo, or you enable it to do digestion?

**Comment by ArgobargSoup** [comment]
Wolf sprites!
![wolfthing](https://cloud.githubusercontent.com/assets/19196710/18224335/9c1fa44c-7186-11e6-95ce-0b8a4a48e8ea.png)
Well, maybe a wolf, maybe something wolf-ish.  Definitely canine.  I think.  >_>
[WolfForVirgo.zip](https://github.com/VOREStation/VOREStation/files/453306/WolfForVirgo.zip)

**Comment by Kligor** [comment]
![andymobs](https://cloud.githubusercontent.com/assets/15312410/18730263/5cecba20-8023-11e6-94f4-09e8e1d1f36c.png)

Aannnddd some horse and bigfrog sprites :3

**Comment by CSchlippy** [comment]
Why not have it gib then?

**Comment by SpadesNeil** [comment]
Because cows and goats don't gib. They die in the same comical way.

**Comment by Alcastar** [comment]
Dragon(red) sprites:
Normal:
![image](https://cloud.githubusercontent.com/assets/19789034/19022027/30da6fda-8894-11e6-802d-dec94c460da1.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022030/3e3d118c-8894-11e6-976f-7d18b5271f48.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022033/445168b6-8894-11e6-99f2-f01311bd5437.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022044/8908303e-8894-11e6-85f9-febb5608beab.png)
Full:
![image](https://cloud.githubusercontent.com/assets/19789034/19022076/04999800-8895-11e6-87e6-0dfe159fbf17.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022077/092317ca-8895-11e6-925c-49734f01efca.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022078/13b9bf90-8895-11e6-8763-992998de93bf.png)
![image](https://cloud.githubusercontent.com/assets/19789034/19022080/18405416-8895-11e6-9133-7139bcecb45a.png)
Dead:
![image](https://cloud.githubusercontent.com/assets/19789034/19022089/2de540c4-8895-11e6-9e5e-feacf7d04b62.png)

**Comment by Alcastar** [comment]
Slime Sprites:
Alive:
back ![slime back](https://cloud.githubusercontent.com/assets/19789034/19023841/ae0c33ca-88bd-11e6-9f71-64772658f00d.png)
front ![slime front](https://cloud.githubusercontent.com/assets/19789034/19023843/ae16afe4-88bd-11e6-92cd-7da5368c6bfb.png)
left ![slime left](https://cloud.githubusercontent.com/assets/19789034/19023844/ae1848ea-88bd-11e6-8df8-c963d052ab04.png)
right ![slime right](https://cloud.githubusercontent.com/assets/19789034/19023842/ae16c51a-88bd-11e6-8e0f-4640c52683d6.png)
Full:
back ![full slime back](https://cloud.githubusercontent.com/assets/19789034/19023850/c62c6a92-88bd-11e6-9297-779b78182c0b.png)
front ![full slime front](https://cloud.githubusercontent.com/assets/19789034/19023851/c62cb024-88bd-11e6-8ed5-b8df1ca1efa5.png)
left ![full slime left](https://cloud.githubusercontent.com/assets/19789034/19023852/c63054d6-88bd-11e6-8e71-398786bf4003.png)
right ![full slime right](https://cloud.githubusercontent.com/assets/19789034/19023853/c632da08-88bd-11e6-8776-98b791a3657d.png)
Dead:
![slime dead](https://cloud.githubusercontent.com/assets/19789034/19023854/cf1c6800-88bd-11e6-93d0-f7bf758bfa39.png)

**Comment by SpadesNeil** [comment]
You all realize I can't upload these if they aren't in .dmi format?

Also the dragon is way too tiny. The sprite is also far too flat.

**Comment by SpadesNeil** [comment]
The wolf sprite is nice but too small. I know I said to do them small but I have changed my mind. We should model our wolves off how the K9 bots work.

**Comment by SpadesNeil** [comment]
I'm trying to make a zoo Z-level so I'd like more sprites ASAP.

**Comment by Alcastar** [comment]
Hate to disappoint, but Git doesn't support .dmi files

**Comment by Alcastar** [comment]
Thankfully i have 7zip

[Vorebee.zip](https://github.com/VOREStation/VOREStation/files/509259/Vorebee.zip)

**Comment by Alcastar** [comment]
Possible Worm:

[WormSS13.zip](https://github.com/VOREStation/VOREStation/files/509515/WormSS13.zip)

**Comment by SpadesNeil** [comment]
This is good, but can you do a grown up one at 64x64 with different full levels?

Also you can right click on sprites in .dmi files and set them to have more directions.

**Comment by Alcastar** [comment]
Worm x64
[Worm x64.zip](https://github.com/VOREStation/VOREStation/files/509868/Worm.x64.zip)

Smaller x32 counterpart
[Worm x32.zip](https://github.com/VOREStation/VOREStation/files/509869/Worm.x32.zip)

**Comment by Alcastar** [comment]
Oh, Ill be sure to do that direction thing from now on

**Comment by SpadesNeil** [comment]
The worm looks better though it's still too flat looking. Needs more depth and a softer outline.

**Comment by Kligor** [comment]
ALRIGHTY heres some large red dragon! Please tell me if theres anything I fucked up or that needs to be fixed!
![andymobs64x64](https://cloud.githubusercontent.com/assets/15312410/19147831/eec95920-8b87-11e6-84ad-adbe763fac5e.png)

**Comment by SpadesNeil** [comment]
Trouble is, the dragon still seems too... flat. Look at how the frog is done compared to the dragon. There's so much texture and contrast compared between the two.

**Comment by Kligor** [comment]
yeah now that its smaller, my textures dont show up much at all ;-;

**Comment by Kligor** [comment]
![andymobs64x64](https://cloud.githubusercontent.com/assets/15312410/19215312/7abd2920-8d68-11e6-8d1c-5c13f739860d.png)

Kay, those are the new ones and I really hope they are good enough but I dont mind adjustments if needed. X3

**Comment by Kligor** [comment]
![andymobs64x64](https://cloud.githubusercontent.com/assets/15312410/20034787/4975baae-a3a1-11e6-8a76-92c0988fc240.png)

Aaannnnddd some Hippos :D

**Comment by SpadesNeil** [comment]
blyat

**Comment by r4d6** [comment]
Do slimes need a full state? I mean they're blobs, the only thing that would change is making them bigger right?

**Comment by CommodoreSchlippy** [comment]
I'd argue they do; a shadow within them would be applicable. It's an immersion thing, sure, but it's still nice to have. Isn't it? Plus, what if someone screams "The slime ate me!" And they don't have on Location Sensors? Then you have to play Twenty Questions to find them and oops their digested.
