### ISSUE TITLE
animalis tail looks odd

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#510]
#### Brief description of the issue
animalis tail is too fare from the back on the side view
#### What you expected to happen
the animalis tail to be more flush with the chars back
#### What actually happened
its sticking out unnaturally far
#### Steps to reproduce
have an animalis tail
#### Additional info It might just be my nitpicky ness but the bit at the neck on the side view makes it look like the tail is bulging out of the back unnaturally
 - **Server Revision**: 3324140ef5949623c13c958fe091a3532363bd3b 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
![image](https://cloud.githubusercontent.com/assets/16435949/17912467/a19f40b2-6948-11e6-9843-0e375eecfe47.png)

**Comment by SpadesNeil** [comment]
Screenshots are required for something like this.

**Comment by kcin2001** [comment]
I will add screenshots later today

**Comment by kcin2001** [comment]
updated with a screenshot

**Comment by kcin2001** [comment]
its a pretty good tail 
and i like it it seems useful for anyone who would want a croc or people who have rough tails

**Comment by Cameron653** [comment]
We can't exactly fix the sprite, seeing as it isn't broken. It's attached to the back of the humanoid (As far as I can see) in the picture, and works well for other species such as the unathi. It just doesn't look the best on them.

**Comment by kcin2001** [comment]
it is the same looking on unathi and to 'fix' it would be to move it a few pixels over i think
