### ISSUE TITLE
can speak lanagues we don't know

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#5104]
#### Brief description of the issue
press ,y speaks a red lanague I don't understand. 

#### What you expected to happen
nothing

#### What actually happened
some red langue 

#### Steps to reproduce
- (Step 1)speak with ,1
- (Step 2)???
- (step 3) profit

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 0c8f28e931c3a02d580c3c805b0b1e076ef8d004 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Adien got a green one to appear too. If I could remeber the commands it might let us speak all lanagues

**Comment by Novacat** [comment]
See: https://github.com/VOREStation/VOREStation/pull/4688
