### ISSUE TITLE
Nerf Cyborg charger for androids.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#513]
#### Brief description of the issue
Android characters can recharge in the cyborg rechargers for ten seconds, and be good for another two hours. 
#### What you expected to happen
More frequent charging, or longer charging for longer power.
#### What actually happened
Instantly filled hunger.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by viv-eret** [comment]
I mean.... Lorewise, they have a special microcell so they DON'T go to a charger every 10 minutes.

**Comment by kcin2001** [comment]
the microcell does exist in game and do synths have any ill effects for being hungry?

**Comment by SilverTalismen** [comment]
They move slower

**Comment by kcin2001** [comment]
Ok so nothing different

**Comment by Somekindofpony** [comment]
I think slowing down the chargerate would be fair enough. As it stands, Synths have a super easy way to go to zero hunger without overeating.

**Comment by Screemonster** [comment]
Meanwhile I can eat a sausage and I'm good for food for the entire shift as a non-robutt. This is a total non-issue.

**Comment by Screemonster** [comment]
My reasoning for the above comment is really that it's not fun gameplay to force people to regularly run off and stand in a featureless room several times a shift.  When dogborgs were first implemented, one player had to put their scene on hold four times in a row. Eventually I just varedited their cell.

**Comment by SpadesNeil** [comment]
Scree brings up a point. I don't think we should mess with this.

**Comment by CSchlippy** [comment]
As long as their food tick is the same as the standard I don't see a problem; I've NEVER had a problem with the food ticks causing me to stop a scene or anything. >.> But if you wanna really be a Nancy for it, add it so they get half food charge from eating food, like a bio-processor.

**Comment by SpadesNeil** [comment]
Gonna close this.
