### ISSUE TITLE
Explosions on z-5 sometimes create open space to z-4

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#5144]
#### Brief description of the issue
Explosions on z-5 create open spaces to z-4

#### What you expected to happen
Create normal space tile

#### What actually happened
Hole to the technical level

#### Steps to reproduce
- Make big kaboom
- Fly around and observe

#### Code Revision
- 0c8f28e931c3a02d580c3c805b0b1e076ef8d004

**Comment by Novacat** [comment]
I already am uploading a fix for this.

**Comment by Verkister** [comment]
nice
