### ISSUE TITLE
[SUGGESTION] Phoron condenser/crystalizer

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#5145]
got to talking about it in the discord, so figured I'd give the tl;dr here:

Get a machine that can use phoron gas and some kind of crystallizing catalyst or some such thing to form phoron sheets in small quantities. I imagine it would work similarly to the algae oxygen generators in that

gas and [item] go in> after some time, the machine expels a small number of phoron sheets.

I would suggest making this job be a cargo responsibility, and I would suggest making the item needed to make these sheets be orderable from cargo but at an expense that makes farming this less profitable for cargo than mining. (Though, cargo turning a small profit from this would be nice busy work for bored folk in the department.)

I would also suggest making the item needed to make the phoron sheets be make-able by science or medical via chemistry, to encourage co-operation.

**Comment by Wickedtemp** [comment]
Could use Coolant, producable in Chemistry and literally never requested or made.

**Comment by TheDavestDave** [comment]
If it needs a cargo tech to set up, engineering to set up, and medical to run, be worse than a novice going out to the get most common ore, why wouldn't the cargo tech skip the middle men and just go mining with their mineing access? 

It also wouldn't give cargo much work other than busy work because atmos would have to send phoron canisters up to cargo, or set the whole thing in atmos and just pretend they went mining and ship it off for points.

**Comment by Very-Soft** [comment]
I mean I was thinking, give cargo a small room with a machine and a pump that pulls phoron from outside and expels the rest. (or maybe turns the rest into waste of some kind that needs to be dealt with.)

The idea here being that, if say, medical, needs some phoron, they can hand someone from cargo a thing, and that person can run to a machine, wait a minute or two, then bring medical some phoron to use, rather than having to go get all kitted up for mining.

**Comment by TheDavestDave** [comment]
that makes a lot more sence. It's still a very easy thing to say it should be in atmos, as well as all the tools needed to get phoron out the air already being in atmos, and often unused. 

We really do need a reason to take air from outside

**Comment by SpadesNeil** [comment]
This is a pretty cool idea for a machine. Would also give further purpose for our station's presence on a phoron planet.
