### ISSUE TITLE
Custom name after Diona evolution still broken

### ISSUE THREAD

**Issue by Waismuth** [VOREStation/VOREStation#516]
#### Brief description of the issue

After splitting into a nymph and waiting 200 ticks then evolving, picking your custom name doesn’t actually make you have the name. You’re still stuck with your randomly generated name.
#### What you expected to happen

I expected to get my own name after given the prompt to pick it.
#### What actually happened

I didn't get my custom name.
#### Steps to reproduce

Be diona, split, wait, evolve and try name your character

**Comment by SpadesNeil** [comment]
I'm 60% sure this is not a bug. The diona is, according to lore, not the same person as they originally were prior to splitting.

That being said, it doesn't need to be the lore.

**Comment by Waismuth** [comment]
Yes, the window prompt is a newest addition. The prompt didn’t show up before the latest patch. I talked with Joey some time ago. After you’re a Diona you can split into nymphs, after waiting 200 ticks you are able to evolve into your adult form, that’s the time when the prompt window pups up and you can input your name. That wasn’t the case before the latest update; the window didn’t pop up, so the new name input option was planned, but it just doesn’t work atm. The input name doesn’t work.

**Comment by Waismuth** [comment]
the diona "custom name after they evolve" is still broken. The window prompt allows to give a name, but the it names the nymph which gets deleted shortly after, and not the adult diona form

**Comment by JoanRisu** [comment]
Fixed upstream apparently
