### ISSUE TITLE
new Floorlenth braid Error

### ISSUE THREAD

**Issue by Molenar** [VOREStation/VOREStation#517]
#### Brief description of the issue
select the hairstyle and receive a large sprite over the entire character that looks the right color but is [ERROR]
#### What you expected to happen
hair
#### What actually happened
http://imgur.com/Xi3RxvP
#### Steps to reproduce
select the hairstyle, Floor length braid
#### Additional info:
 - **Server Revision**: release - 2016-08-23
3324140ef5949623c13c958fe091a3532363bd3b 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
I swear I've fixed this multiple times now. Going to look into this in a
bit.

**Comment by SpadesNeil** [comment]
Remember the floor length braid was _removed_ from Polaris.

**Comment by Cameron653** [comment]
Ah. I'll probably go and make a vr sprite file and place the old floor
length braid into it and fix it up
