### ISSUE TITLE
AI holograms that copy crewmembers can't change the direction they're facing

### ISSUE THREAD

**Issue by nightwingthedragon** [VOREStation/VOREStation#518]
#### Brief description of the issue

When playing as AI, you may change your hologram. When selecting a "unique" hologram, you can change your facing as you please (for anything except the face, last I checked). However, you can also look like an existing crewmember. But if you do, your direction is locked to south, and you can't face east/south/west.
#### What you expected to happen

In the past, selecting a crew member to be your AI hologram allowed you to face in all four directions.
#### What actually happened

You cannot.
#### Steps to reproduce
1. Be AI
2. Open the Change Hologram dialogue
3. Select the Crew Member button
4. Select any crew member
5. Go find a holopad
6. Click the holopad so your hologram spawns
7. Move around in all four directions
#### Additional info:
- **Server Revision**: release - 2016-08-23
  3324140ef5949623c13c958fe091a3532363bd3b

**Comment by SpadesNeil** [comment]
Hold Ctrl, use arrow keys, then try it. See if it works.

**Comment by SpadesNeil** [comment]
Misunderstood because sleepy. Labels corrected.

**Comment by DeepIndigo** [comment]
Did the holo's have tails in the past? I imagine the lack of facing change has to do with how holograms and tails work and those conflicting.

**Comment by Arokha** [comment]
This is fixed with the 'just use my own damn character' AI thing.
