### ISSUE TITLE
Info wiped when revived as promethean

### ISSUE THREAD

**Issue by CRTXBacon** [VOREStation/VOREStation#5195]
#### Brief description of the issue
When being revived as a promethean, the following information is not restored to your character and therefore lost:
Custom species name
Flavour text
OOC Notes

#### Steps to reproduce
- Be a promethean
- Die
- Get revived from your core

#### Code Revision
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

**Comment by TheDavestDave** [comment]
If someone TFs you it also breaks.

**Comment by TheFurryFeline** [comment]
Still an issue.
