### ISSUE TITLE
[SUGGESTION] Synth stomach upgrade in robotics to allow nutrition gain?

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5200]
#### Brief description of the issue
As of now synthetics can only charge via charging pods, the NIFsoft to charge from APCs, vore, and the trash eater trait (very ineffectively).

#### Suggested solution
Adding a printable stomach to robotics that can be installed in synthetics to allow for nutrition gain and alcohol processing to help them feel a bit more alive. My idea is that they start with a very basic one that just holds onto reagents like normal and doesn't do anything, and as science does R&D to develop better medical technology (bio research and engineering, maybe?), then better tiers appear with the max either being a choice of one that's 1:1 to with how organic stomachs work, or one that's even faster if you want to make maxxing out research levels "worth it". Bonus points if there's a version that can be implanted into organics too for speedy food and chem processing. To combat organ saving making it a permanent upgrade, maybe it degrades over time or something and needs to be replaced?

**Comment by TheFurryFeline** [comment]
..... I'm definitely up for something like that. Whole heartedly endorsed by the big catte!

**Comment by Shophaune** [comment]
So if the implant that goes behind the nose is a 'NIF, I vote we call this the Artificial Reagent Terminus. Or 'ART for short.
