### ISSUE TITLE
Cyborg characters still have to write flavour text that'll never be seen

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#5204]
#### Brief description of the issue
When joining as a cyborg, you still have to have a non-empty General flavour text despite cyborgs never using it.

#### What you expected to happen
Not to be allowed to join unless I had a non-empty Default Robot Flavour Text. 

#### What actually happened
Not allowed to join until I put "N/A" in General flavour text

#### Steps to reproduce
- Have a character purely for use as a lawed cyborg character, with flavour texts accordingly
- Attempt to join a round

#### Code Revision
release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

**Comment by Rykka-Stormheart** [comment]
Shouldn't be too big an issue - I'll see if it's fixable or if it even needs fixing.

**Comment by Shophaune** [comment]
Is this still an issue?

**Comment by Rykka-Stormheart** [comment]
> Is this still an issue?

Hi sho <3

And yes, it is, I've not had time to fix it. I'd do another check if you can in-game to confirm when you have the chance. Sorry </3

**Comment by Arokha** [comment]
I was able to join without setting default module robot flavortext.

**Comment by Shophaune** [comment]
@Arokha Were you able to join without setting NON-robotic flavortext?

**Comment by Arokha** [comment]
Ooooh I misread.
