### ISSUE TITLE
Condimaster doesn't work any more.

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#521]
#### Brief description of the issue

The machine in the kitchen freezer that's sapose to make condamit bottles and packs only deletes any thing put into it that doesn't stay in the beaker.
#### What you expected to happen

Transferring liquids or powders into the machine and being able to make a bottle or packet out of them to store and separate reagents. Also to not have the stuff get deleted no matter what setting its on.
#### What actually happened

I put in a beaker of caspian oil and Sbiten (a drink with vodka and caspian oil.) when I transferred the oil into the machine to make a bottle out of it, there was no option to make a bottle, and when i set it to transfer back to the beaker, it just deleted all the oil.
#### Steps to reproduce

Put a beaker into the machine with stuff in it and try to separate them.
#### Additional info:

Server revision: release - 2016-08-23
3324140ef5949623c13c958fe091a3532363bd3b 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/issues/2230 Related to this.

**Comment by SpadesNeil** [comment]
Still a bug?

**Comment by Yoshax** [comment]
Technically not.
