### ISSUE TITLE
cooking many recipes seems to produce iron ingots spora

### ISSUE THREAD

**Issue by ironsnake345** [VOREStation/VOREStation#5211]
#### Brief description of the issue
Having attempted cooking, I found that many recipes produced iron ingots instead of food.

#### What you expected to happen
cooking 1 bun and 1 raw cutlet producing 1 burger (or possibly 1 burnt mess)

#### What actually happened
cooking 1 bun and 1 raw cutlet producing 1 iron ingot

#### Steps to reproduce
- Create a dough. Microwave it into a bun.
- Combine bun and raw cutlet in microwave
- Repeat for other recipes listed on the wiki to see what else produces iron ingots

#### Code Revision
- 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- The same bug happened yesterday when I tried to make tacos and eggs benedict. It seems to be a running issue.

**Comment by Neerti** [comment]
This is an upstream issue.
I got no idea why it makes iron specifically.

**Comment by ironsnake345** [comment]
Well, is there anything I can expect to happen or for me to need to do in the near future?

**Comment by ironsnake345** [comment]
also happens with cooked cutlets, if that matters. Lots of recipes seem to put out iron instead of the intended product.

**Comment by ironsnake345** [comment]
to be clear, when I said it happens with cooked cutlets as well, I meant using cooked cutlets for cooking recipes. Come to think of it, all the examples I've tried are examples where there are multiple viable forms of one or more ingredients for the recipe. (for example, using a cooked or raw cutlet should have the same result.) Maybe something in the code which deals with the "whitelist" of usable ingredients is what's causing the bug?
