### ISSUE TITLE
No way to clear a set nickname in character creation

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5228]
#### Brief description of the issue
If you set a nickname for your character during character creation, there's no way to revert the field back to being blank, the game forces you to put SOMETHING meeting the requirements of a Nickname in the field.

#### What you expected to happen
I'd be able to make the field blank and save it in order to clear the nickname, or there'd be a button to just clear the field.

#### What actually happened
I got stuck with the nickname of a character in the slot the new one is being made in with no way to just get rid of having a nickname.

#### Steps to reproduce
- Join the server
- Setup character
- Click nickname and put whatever you want
- Save slot
- Try to remove nickname
- Perish

#### Code Revision
- release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- https://gyazo.com/ddbe1846fb5bd4651740a025288c5ada (Error message that pops up when trying to clear the slot or put spaces to simulate a cleared slot)

**Comment by Heroman3003** [comment]
Nickname never actually DOESN'T exist. Even if you don't set the parameters, your character's name pieces will be the nickname regardless of field's contents (in addition to said contents). So the way to set your nickname to no nickname is to just input your char's name.

**Comment by HzDonut** [comment]
Ah, alright then.
