### ISSUE TITLE
Atmospherics Access tunnel

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#523]
#### Brief description of the issue
People dragging cans from atmo to the engine have to take a fairly long loop that could be solved with a simple access tunnel. Additionally, the cabling for the engineering solar passes through the blast zone for the supermatter (currently it goes through the engine control room)

Scree added a new tunnel called "Atmospherics access" and rerouted the wiring to connect the solar to the grid at the atmospherics substation.

#### Scree's fax:

hav some blooprints for the new atmo access tunel I made

i also put the solar wiring through atmo so it dun go through the bit wot gets blown up if the enjin blows

http://i.imgur.com/oZWk9Gl.png

pictured wif the tiles up so ya can see the wire

-Scree

**Comment by Screemonster** [comment]
Just to note 'cause I forgot to specifically mention it, the whole arrangement with the firefighting equipment, canisters, and hazard stripes on the floor was moved two tiles north.

**Comment by SpadesNeil** [comment]
What access do those doors have?

**Comment by Screemonster** [comment]
I made them atmospherics and chief engineer access. I dunno if Polaris engineers have access to atmo but anyone who can't get into the department via the normal doors (or the substation doors) shouldn't be able to get in that way.

**Comment by SpadesNeil** [comment]
I just copied the doors from north of atmos and south east entry to the engine room. No need for chief engie access.
