### ISSUE TITLE
Closed, but not shutdown laptops still make light

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#5233]
#### Brief description of the issue
Laptops work as light sources, but are only meant to when open AND working

#### What you expected to happen
Laptop closed without being shut off makes no light

#### What actually happened
Still makes light

#### Steps to reproduce
- Open laptop
- Turn it on
- Close it without turning it off

#### Code Revision
- 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

**Comment by Sebbe9123** [comment]
Maybe make it so closing the computer automatically turns it off, like it was a standbymode or something.
