### ISSUE TITLE
[Bug/Suggestion] Bring back/fix the inability to examine anything as prey while inside of someone

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5236]
#### Brief description of the issue
It used to be that you could examine your predator to see if they have any special full stomach examine text, and continue to examine the world around you in general as prey, which was great for long endo scenes, but now you no longer can. I know not being able to see makes sense, but from a gameplay standpoint it can get rather annoying to want to examine your pred like i mentioned just to get denied.

If just bringing it back fully is an issue, then perhaps just adding it as a toggle for the pred would be better, as they can decide whether the prey can "see" or not.

#### Code Revision - release -
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

**Comment by SpadesNeil** [comment]
This is the desired functionality and it was preferred this way long ago.
