### ISSUE TITLE
Can't check OOC notes inside of someone.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#5237]
#### Brief description of the issue
If you're inside of someone you cannot examine them anymore. Therefore you also can't check up on their ooc notes again. Yes, you can ask them about every minute detail in looc. But for people who don't want to break character in looc or be distracted by it. Or spend time asking, it's nice to be able to check ooc at any time. Sure, you can scroll up, given you don't forget to check the ooc notes before going in a gut, or end up reconnecting later.

#### What you expected to happen
For there to be some way to check ooc-notes whilst in a gut, it's kinda useful.

#### What actually happened
It isn't possible

#### Steps to reproduce
try to examine your partner to find out wether or not they like X or X again.
Find out you can't access ooc notes :c

**Comment by Sebbe9123** [comment]
OOC tab
Character directory
person you want flavor text and OOC notes for
bam

**Comment by Ketrai** [comment]
> OOC tab
> Character directory
> person you want flavor text and OOC notes for
> bam

unfortunately people can disable that. So you still have to go the looc route.

**Comment by Sebbe9123** [comment]
Disabling it rests solely on the disables shoulders and is so rare that if it happens ... too bad I guess

**Comment by SpadesNeil** [comment]
That is a bit of a problem, I agree.

**Comment by Screemonster** [comment]
I'd like to be able to examine people from inside them so I can see what fun flavourtext things they've added for being a fatty fatty fatfat.
