### ISSUE TITLE
Remove .45 pistols + .45 flash rounds from SecVends

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#5239]
#### Brief description of the issue
By technicality, .45 pistols are considered lethal weaponry, therefore should not be freely dispensed by members of security in the code green armory. IIRC, there was talk about removing it aaaages ago. Like, I'm talking last year but it never went through.

#### What you expected to happen
Appropriate weaponry within the appropriate armories.

#### What actually happened
People getting called out for having 'lethal' weapons, despite it being able to get freely dispensed.

#### Steps to reproduce
- Go to a SecVend
-Dispense a .45 pistol
-Get yelled at for possessing a lethal weapon on code green.
-Cry.
#### Code Revision
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
N/A

**Comment by TheFurryFeline** [comment]
Far as I've seen, they're dispensed with only flash rounds and security don't even have access to autolathes to print off lethal ammo. Seems pretty balanced enough.

**Comment by SpadesNeil** [comment]
Yeah but what are flash pistols even _for_?

We could stick in an alternative that only uses flash rounds. The idea of flash pistols always felt unrealistic to me.

**Comment by TheFurryFeline** [comment]
Are there any unused gun objs in the code which could get changed slightly to only take flash rounds? I could probably strike two birds with one stone.

**Comment by TheDavestDave** [comment]
to look cool. It would be nice if flash rounds could damage mobs
