### ISSUE TITLE
[Suggestion] Engineering protolathe JUST to print parts for machines

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5242]
#### Brief description of the issue
As of right now, Engineering has to either get all the parts together to make their own protolathe, or keep bugging science for the parts they need to construct certain items. With this solution, they'd be able to just freely print the parts only only obtainable through the protolathe (bins, manipulators, scanners, lasers). If this is considered to be too much job stealing, it could always be reduced even further to only have the basic parts.

**Comment by Heroman3003** [comment]
Donut, it already exists.
Its called Parts Lathe. All things needed to make it are in board storage, including board and parts.

**Comment by HzDonut** [comment]
Oof.
