### ISSUE TITLE
[Suggestion] Reinforced glass in the engineering workshop

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5243]
#### Brief description of the issue
The engineering workshop has plastic, steel, plasteel, glass, and even borosilicate glass...but no reinforced glass. That's just really bizarre considering that most of the station windows are rglass, and thus we'd need rglass to replace them if they get broken. Sure we can use the nearby metal rods to make rglass, but it still just seems really odd.

**Comment by TheDavestDave** [comment]
refenforce glass can be made in a prolathe or made by mixing glass and steel rods in your hand

**Comment by Heroman3003** [comment]
Click regular glass with steel rods. The glass is not given in ready state to allow options. You can always make more rglass, but reverse process is not as simple as single click.

**Comment by HzDonut** [comment]
I literally said right in the PR that I know you can make the reinforced glass, I just thought it was weird that we didn't have a stack of it ready on a facility with an assload of reinforced glass windows :v

**Comment by SpadesNeil** [comment]
Because it's easy to combine rods and glass, and you can use rods and glass in various different applications but can't remove rods from glass once reinforced glass is made.

This is not a good suggestion.
