### ISSUE TITLE
Everyone is bald and featureless in record photos.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#5246]
#### Brief description of the issue
Going into security records (and I assume all records) show the mugshot photos as being without hair/features and naked.

#### What you expected to happen
People dressed up with all their hair and parts intact.

#### What actually happened
Nanotrasen strips and shaves people for their mugshot photos.

#### Steps to reproduce
-Log into a record console (any type; bug found on security records console)
-Select someone to view their record.
-Shield your eyes from the nudes.

#### Code Revision
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6
 
#### Anything else you may wish to add:
![ewgross](https://user-images.githubusercontent.com/33539568/57990141-e7b55c00-7ae6-11e9-8305-1943cc0ed999.JPG)

**Comment by Heroman3003** [comment]
Are you sure its not just sec records? Pretty sure employment record console applies clothes properly.

**Comment by MrSign** [comment]
That's why I said I assume it is other records! I just came across it in sec records.
