### ISSUE TITLE
Suggestion: SciPup Borg Toolkit

### ISSUE THREAD

**Issue by Damarik** [VOREStation/VOREStation#5247]
#### Brief description of the issue
Science Dogborg doesn't have the tools necessary for constructing machines (wrench, welder, cablecoil, wirecutters) or repairing other borgs. Their grippers also can't interact with many objects (small devices like timers/igniters and casings/syringes) for effectively working in areas of science.

#### What you expected to happen
Be able to perform in most science departments

#### What actually happened
Get castrated because I can't use tools I'm not equipped with, or can't interact with.

#### Steps to reproduce
- (Step 1) Try to play any Science Role outside of R&D

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
#### Anything else you may wish to add:
- I've been on other stations where SciBorgs even have access to ID scanners so they can work on other borg interiors. They could also basically pick anything out of a box and use it, and those servers don't have any problems.

The Medihound also has this problem, as it doesn't have a Chemistry Gripper, so doing Chemistry when you're the only medic on station is kinda...supremely difficult.

**Comment by SpadesNeil** [comment]
Does a normal science borg have these things? If so, then yeah, this should be done. If not, then there should be some discussion about it.

Either way, this is a pretty simple change. You can make the PR, I'm sure.
