### ISSUE TITLE
Dark Mode for SS13

### ISSUE THREAD

**Issue by CageCoding** [VOREStation/VOREStation#5248]
#### Brief description of the issue
There is no real way of setting up SS13 game window to be within Dark mode.  Dark mode meaning a black background with white text.   Currently it is the opposite of a white background with black text.

As much as this is a default standard, this causes eye strain over time.

#### What you expected to happen
To have the ability to have a dark mode within SS13. (Dark Background, White text).

#### What actually happened
No way to edit the themes at ALL.  >:/

#### Steps to reproduce
Just open up SS13 and the default window shows this.

#### Code Revision

There was a coder who had already implemented a Dark Theme onto their server.   Link is listed down below.

- https://www.reddit.com/r/SS13/comments/ayvvbk/discussion_toggle_able_dark_theme_for_ss13/

**Comment by Mewchild** [comment]
There is actually a way to edit themes. Click the BYOND logo in the top left hand corner, and select "Edit Skin" or something similar. This is an inbuilt BYOND function. 
https://i.imgur.com/0VT8bNx.png

**Comment by TheFurryFeline** [comment]
Can confirm this is possible as I play/do dev work on a downstream server. Though you'll want to change the font colour of several outputting text things. >W>

**Comment by SpadesNeil** [comment]
If another coder already did it, you can probably port it into a PR.
