### ISSUE TITLE
Observation room for the Interrogation room is unusable

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5249]
#### Brief description of the issue
The observation room in the brig is missing key features. Namely, being able to look into the interrogation room and hearing what is happening in it, making the room useless.

#### What you expected to happen
Being able to see/hear what is going on in the interrogation room from the observation room.

#### What actually happened
Not being able to even look through the windows.

#### Steps to reproduce
- (Step 1) Go into the observation room and sit in darkness, contemplating your life as you are cut off from everything else.

#### Code Revision
- 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- https://i.gyazo.com/1363098d2e01553b537facca64208733.png

**Comment by SpadesNeil** [comment]
There is supposed to be a camera monitor at least. There clearly is not.
