### ISSUE TITLE
You cannot scoop people while buckled to a chair.

### ISSUE THREAD

**Issue by Bluhblaghbluh** [VOREStation/VOREStation#525]
#### Brief description of the issue

While buckled to a chair, you cannot scoop someone small enough to be scooped. It instead says you cannot scoop yourself because you're buckled to a chair. Additionally, attempting to scoop someone buckled to a chair hugs them with no indication of WHY you have failed to scoop them.

#### What you expected to happen

You can scoop someone 2 sizes smaller than you while you are buckled to a chair.

#### What actually happened

The game believes YOU are the one attempting to be scooped.

#### Steps to reproduce

Buckle self to chair, attempt to scoop unbuckled micro.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Are you sure you didn't accidentally click yourself?

**Comment by SpadesNeil** [comment]
wontfix because if you're buckled to a chair you can't bend over to pick up micros!
