### ISSUE TITLE
[suggestion] Industrial hardsuit should probably yield major radiation protection.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#5250]
#### Brief description of the issue
Miners frequently come in with serious radiation cases, hampered by their heavy hardsuit, they'll occasionally die mid transit due to mounting toxins from the radiation. Of course, this could be resolved by not digging up obvious anomalies, but I digress.

For all it is, the industrial hardsuit is basically good for nothing but being a platform for its modules. It should probably offer some radiation protection before the radsuit winds up unironically being decided the better alternative.

#### What you expected to happen
Mining hardsuit to actually be useful on its own by stopping rads.

#### What actually happened
It doesn't, and people die constantly. To my knowledge, it actually has WORSE rad resist than the mining suit.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I'm tired of relaxing in med and getting horrible radiation cases the second things seem calm and dandy.

**Comment by SpadesNeil** [comment]
This is a pretty simple change. You can make the PR, I'm sure.

Polaris might want this too.

Though, I also feel like maybe miners shouldn't be smashing artifacts and should be letting Xenoarch get them.

**Comment by Mewchild** [comment]
As an addendum, and rebuttal to Ace's final comment, Miners oft have no way of knowing an artifact is there until it's already been broken

**Comment by SpadesNeil** [comment]
Okay then yeah this should probably be a thing. Easy PR. I believe in you. :U

**Comment by Mewchild** [comment]
Ace believed in me when I didn't believe in me uwu

**Comment by Screemonster** [comment]
KAs and resonators don't smash artefacts since the last thing I did there

pretty sure I made sonic jackhammers artefact-safe too

you can use a diamond drill and dig fast and reckless, or a jackhammer and do it slow and safe, choose
