### ISSUE TITLE
[BUG] Unidentified Medicine from crashed escape pod POI (Wilderness) can't be interacted with

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5252]
#### Brief description of the issue
The random loot drop "unidentified medicine" from the "abandoned medical closet" inside of the crashed escape pod POI out in the wilderness cannot be interacted with in any way besides examining. No picking it up, no pulling it, nada.

#### What you expected to happen
I'd be able to pick the thing up to at least bring it back to the station to experiment around with it.

#### What actually happened
Can't pick up or pull, just examine. Eventually disappeared too.

#### Steps to reproduce
- Wander around wilderness
- Find crashed drop pod (in case there's multiple, this one is surrounded by rock and has a skeleton in it)
- Loot medicine cabinet, get "Unidentified Medicine" to drop
- Attempt to do anything with it, be disappointed.

#### Code Revision
- release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- https://gyazo.com/a7e00202e413d7c26920fac78b317105 (the specific pod this problem happened with)

**Comment by mistyLuminescence** [comment]
Fixed by PolarisSS13/Polaris#6218 .
