### ISSUE TITLE
Making a meat bun creates iron

### ISSUE THREAD

**Issue by Loneguyfly** [VOREStation/VOREStation#5255]
#### Brief description of the issue
I used the meat bun recipe (one meatball and one flat dough) and it created a single iron ingot instead of the food I requested.

#### What you expected to happen
I expected the microwave to not be able to transmute meat into iron.

#### What actually happened
The microwave transmuted meat into iron.

#### Steps to reproduce
- (Step 1) Put meatball and flat dough into the microwave
- (Step 2) Activate it
- (Step 3) Observe actual magic before your eyes.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
It's probably a recipe issue.

**Comment by Shophaune** [comment]
Duplicate of #5211, fixed in #5215

**Comment by Loneguyfly** [comment]
Sorryyyyyy. x.x
