### ISSUE TITLE
[SUGGESTION] Multitool on lights to change their color

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5258]
#### Brief description of the issue
At the moment, we're stuck with the default white/yellowish lights no matter what we're building unless an admin steps in and VVs them, and it can get kinda...lame for some projects. A way to set a color for them, like by using a multitool on a bulb or tool, would be greatly appreciated.

**Comment by SpadesNeil** [comment]
This is a pretty good idea, but should probably be handled by Polaris. Still, it's enough of a game changing idea that I am not closing this.

Marked as minor because cosmetic change, but still a neat one.
