### ISSUE TITLE
[MAPPING ISSUE?] Abandoned Bar has a Smartfridge

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5259]
#### Brief description of the issue
For some reason, the abandoned bar by the maintenance dorms has a smartfridge pre-built inside of it. This just seems like such an odd choice compared to the booze-o-mat or drinks showcase that I felt like I should PROBABLY report it just to be on the safe side.

#### What you expected to happen
There'd be a bar-relevant machine in the abandoned bar, such as a booze-o-mat or drinks showcase

#### What actually happened
There's a smartfridge, which is made to store fresh fruits and vegetables for the chef.

#### Steps to reproduce
- Just walk into the place and you'll find it

#### Code Revision
- release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- https://gyazo.com/fc3b72ff01472bfea4a74b1a63cb9cfc The Bar
- https://gyazo.com/80ab45080fb42c75f3131b3efeaff6ce Just the fridge
- https://gyazo.com/293b4f4c6e2fe376b717909806f4915a Confirmation that it is definitely a smartfridge.

**Comment by TheFurryFeline** [comment]
You'll want to ask @Jakksergal about that one as they were the one who did the massive overhaul to the surface decks in #4889

**Comment by Jakksergal** [comment]
It's not intended. I'm not sure a booze-o-mat's content can be edited, though.

**Comment by Rykka-Stormheart** [comment]
Stale/Obsolete

**Comment by Cameron653** [comment]
Was told to close it, closing.
