### ISSUE TITLE
Research borg can’t insert sheets 

### ISSUE THREAD

**Issue by Waismuth** [VOREStation/VOREStation#526]
#### Brief description of the issue

When playing as the research borg you can pickup metal and glass sheets and put them into the autolathe and exhosuit and prosthetics fabricator no problem. But you can’t put the sheets into the circuit imprinter and prolathe, making it hard to do RnD.  
#### What you expected to happen

Being able to put sheets EVERYWHERE
#### What actually happened

Borg can't put sheets into prolathe and circuit imprinter
#### Steps to reproduce

Be research borg, try to put sheets into prolathe, fail, wallow in despair as you realize you're useless

**Comment by SpadesNeil** [comment]
This still an issue?

**Comment by Waismuth** [comment]
Yup, still doesn't work, just checked it.

**Comment by SpadesNeil** [comment]
This is a known bug in Polaris, but a very old one. Not sure why it hasn't been fixed yet but I'll try having it looked into.

**Comment by SpadesNeil** [comment]
This should be fixed now. Alert me if it is not.
