### ISSUE TITLE
[BUG] SmartFridge issues

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5260]
#### Brief description of the issue
Normally to deconstruct a smartfridge, you screw it open, crowbar it, cut its wires, and then wrench it to take it apart the rest of the way. For some reason on here, it just keeps "smartly refusing" all tools besides the screwdriver. You also cannot wrench it while it's open to be able to move it around either. Hell, I couldn't even find a circuit board for the thing, so it might not even be able to be built in the first place!

#### What you expected to happen
I could move and take apart smartfridges like any other machine in the game.

#### What actually happened
"The smartfridge smartly refuses the [x]"

#### Steps to reproduce
- Find a SmartFridge
- Attempt deconstruction or moving it
- Fail

#### Code Revision
- release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

**Comment by TheFurryFeline** [comment]
This may be resolved by having attackby proc allow any construction tools be used, not just screwdrivers. 
```
if(O.is_screwdriver())
		panel_open = !panel_open
		user.visible_message("[user] [panel_open ? "opens" : "closes"] the maintenance panel of \the [src].", "You [panel_open ? "open" : "close"] the maintenance panel of \the [src].")
		playsound(src, O.usesound, 50, 1)
		update_icon()
		SSnanoui.update_uis(src)
		return

	if(wrenchable && default_unfasten_wrench(user, O, 20))
		return

	if(istype(O, /obj/item/device/multitool) || O.is_wirecutter())
		if(panel_open)
			attack_hand(user)
		return
```
For some reason, https://github.com/VOREStation/VOREStation/blob/master/code/modules/food/kitchen/smartfridge.dm#L240 whole proc has just... Return. IIRC, this may mean it's not returning true and jumps to the else clause?
