### ISSUE TITLE
[SUGGESTION] Allow everyone to hide under tables or make it a trait for everyone

### ISSUE THREAD

**Issue by Nepoox** [VOREStation/VOREStation#5261]
I know this would probably cause some "balance" issues. But I would love to have it as an option for _various under the desk activities_

Maybe make it a trait that costs trait points? I dunno! I just want it for non-tesharis aswell.

**Comment by Sebbe9123** [comment]
The agility "trait" is absurdely powerful, only way I can see this done is that it's a 3 point trade with the inability to take any positive health modifiers lime brute resist and the hp cap one. as for making it availible for everyone... why even have teshari anymore?

**Comment by Nepoox** [comment]
The agility trait being the thing that allows teshari to run under table sprites right?

What if we create a extra verb/trait, where you can hide underneath one table-tile if you stand on it? But once you move it reveals you again?I just want it to be possible to crawl under tables 😔

**Comment by SpadesNeil** [comment]
No.
