### ISSUE TITLE
[BUG] Laptop camera viewer can't access different z-levels on map view

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5266]
#### Brief description of the issue
What it says in the title: the camera viewer on laptops (and presumably tablets too) cannot access the view of different z-levels in the camera map view. To view those levels, you need to just select the relevant cameras from the camera list view.

#### What you expected to happen
The laptop camera program would work like the one on the consoles.

#### What actually happened
It was missing all the z-level buttons.

#### Steps to reproduce
- Get laptop (I specifically use the custom one with all the best parts like a loser)
- Download and open the camera software
- Switch to map view

#### Code Revision
-  release - 
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
- https://gyazo.com/a1ebeb4a7dd9b62182380f19cdc291b0 camera viewer on laptop
- https://gyazo.com/3f53054d3af6cbf11339ac044898b6db camera viewer on the camera console

**Comment by TheFurryFeline** [comment]
No longer an issue with the modular computers port Ascian made a while back.
