### ISSUE TITLE
Cyborgs should not be able to use resize commands

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#527]
#### Brief description of the issue
OOC resize command works for robots.

#### What you expected to happen
For them not to be able to do this.

#### What actually happened
Tiny security droids that are the bane of all that is robust.

#### Steps to reproduce
1. Become cyborg.
2. Abuse resize button.
3. Troll

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/b8d54c903aafbe192a8e5e5e07df07648c935761

**Comment by Screemonster** [comment]
Is there any advantage to giving this button to _all_ mobs?

If a player is controlling anything that's not a human type then it's either a silicon, a mouse, a nymph or adminfuckery, and in the latter case admins can just varedit playerscale if they want to run around being FATMOUSE.
