### ISSUE TITLE
Brig basketball is just paper

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5271]
#### Brief description of the issue
The basketball in the brig is just a crumpled up piece of paper

#### What you expected to happen
There to be a real basketball

#### What actually happened
The basketball is a lie

#### Steps to reproduce
- Grab a weapon of choice
- Kill someone while security is active
- Get briged for murder
- Realise you can't slamjam because the b-ball is paper
- Cry

#### Code Revision
- 8c6c1e51e3880cfacf434b15c2ef6ee2034430c6 
 
#### Anything else you may wish to add:
https://i.gyazo.com/9ae63b893b5671ff33ed3f8bf1fd8de9.png
https://i.gyazo.com/34ceecc1a5adf01cb93a04097b404280.png

**Comment by Sebbe9123** [comment]
There is a real ball in storage.

**Comment by Jakksergal** [comment]
That was intended as a joke. Only good inmates get a real ball.
