### ISSUE TITLE
[SUGGESTION] V4 gateway/cryo pod to leave the round

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5273]
#### Brief description of the issue
Many times I've gone on "fun beach trips", many times I've wound up bored out of my mind after an hour or so. Back on the tether this is fine, since I can just go find something else to do, but on virgo 4? All I can do is sit on the shuttle and wait for them to go back. An easy fix is simply adding one of those gateway teleporters like the ones by security to the V4 map to fluff out people just going back to central, or a cryo pod just to have a way to quit if people are dilly-dallying around on the planet when you want out.

**Comment by TheFurryFeline** [comment]
This, imo, would be rather reasonable to have, actually. Since in lore, we have Anur on V4, there could feasibly be one way travel to Anur from a tram-style portal. It would have to be coded that you can't spawn into the round at the V4 portal, however, but that's easy enough.

**Comment by Sebbe9123** [comment]
Tbh, the amount of times people have gone to V4 you'd think we'd set up a gateway you can activate on the other side. Take shuttle to v4, setup a genny and charge the APC and activate the Gateway when needed.

**Comment by SpadesNeil** [comment]
I would be okay with a permanent map emplacement of a teleporter on Virgo 4 by the beach. Not too hard to map in.

**Comment by Mewchild** [comment]
Mitigated by there being a cryopod on the shuttle itself, now
