### ISSUE TITLE
[SUGGESTION] Make all dog borgs have the sitting/laying on back sprites.

### ISSUE THREAD

**Issue by iNoPeRaTiVe** [VOREStation/VOREStation#5276]
Okay, so when I was on the server, I noticed that the old medihound/sechound/janihound cyborg models, when facing north and resting would sit and when facing south and resting would lay on their backs, while east or west would produce the normal "lay on stomach" sprite. 

I am working on sprites for the new dogborgs that would replicate the same behaviour as the old ones, but wanted to know if I could even merge it into the codebase. I hope it wouldn't break anything. If I can attach files after a post is made then I will definitely attach the new sprites.

**Comment by Verkister** [comment]
Sweet. I can totally add and merge the sprites if you have any trouble.

**Comment by Verkister** [comment]
https://github.com/VOREStation/VOREStation/pull/5332 forgot to mention this here

**Comment by SpadesNeil** [comment]
Resolved, looks like.
