### ISSUE TITLE
[Bug] [AI] Gaslamps broke 

### ISSUE THREAD

**Issue by iNoPeRaTiVe** [VOREStation/VOREStation#5290]
#### Brief description of the issue
On the server, gaslamps are completely docile now. They will "try to wrap you in their tentacles" but will not get anywhere. 
They will not attack you. They will not devour you. Even if you smack them they will do nothing and say nothing. 

#### What you expected to happen
The gaslamp to attack me, eat me, anything.

#### What actually happened
Absolutely nothing. It just floats, even if you whack it.

#### Steps to reproduce
- (Step 1): Find a gaslamp.
- (Step 2): Punch it. Stand inside of its tendrils. Eat it.
- [Step 3): Observe their lack of reaction.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 
ea791ec4dafcdb1f4642e87e5a015fac917d245d

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Okay so I'm pretty sure this happens because the gaslamps may have the wrong AI set. They also can not eat you because the code still requires that the target be standing under (occupying the same tile as) the gaslamp. The "recent" AI update made it so you can't occupy the same tile as them, and so they can not devour you. 

Just wanted to make an issue about it t alert people

**Comment by HzDonut** [comment]
That's a problem with all bumpnoms, actually. The only way mobs can eat you now is if they down you from damage, or do the pounce that knocks you over and stuns you for a moment (and they're fully hostile). At least, that's what I've seen so far on the live server and in some tests on a private one.

**Comment by Verkister** [comment]
yeah the problem is that the bumpnom thing won't make the mobs stop their movement so they'll just wander off and off before the timer requiring both to stay still can do shit about it.

**Comment by SpadesNeil** [comment]
Could alter the bumpnom timer to basically eat you instantly.

**Comment by Heroman3003** [comment]
The problem in the PR does highlight problem with bumpnoms, but lack of retaliation is a severe bug unrelated actually to bumpnomming. Fix is up on Polaris. As for bumpnoms specifically, issue just for that already exists.
