### ISSUE TITLE
Mice can eat people after death

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#530]
#### Brief description of the issue
mice can eat people after dieing
#### What you expected to happen
not to eb able to
#### What actually happened
http://prntscr.com/ce9ff7
#### Steps to reproduce
ghost,be mouse,die, press animal nom
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-08-30
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
That must be an issue with the animal_nom() verb not checking if the user is dead.
