### ISSUE TITLE
Mobs don't always seem to get auto-assigned bellies anymore.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#5300]
#### Brief description of the issue
Can't feed people to mobs as far as I can tell thanks to a lack of a default stomach.

#### What you expected to happen
For me to be able to feed a nice cutie to my pet.

#### What actually happened
The universe cucked me.

#### Steps to reproduce
tries to aggresive grab feed someone to a mob
fail
ask an admin to add bellies to the mob so you can.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Examining a mob with someone inside doesn't seem to yield an examine message either.

**Comment by Novacat** [comment]
Not all mobs have vore_active (especially polaris ones), and spiders are among those that do not. This is not a bug, but a deliberate design decision that was made a long time ago.

**Comment by Ketrai** [comment]
give mr tuddly a gut  then! Or the option to give a certain mob a gut :o.

**Comment by TheFurryFeline** [comment]
As for the examine thing, simple_animal mobs don't tend to have that defined for them as they're usually NPCs.

**Comment by Sebbe9123** [comment]
> As for the examine thing, simple_animal mobs don't tend to have that defined for them as they're usually NPCs.

We don't use simple_animal

**Comment by TheFurryFeline** [comment]
> > As for the examine thing, simple_animal mobs don't tend to have that defined for them as they're usually NPCs.
> 
> We don't use simple_animal

You know what I mean, dork. simple_mobs
