### ISSUE TITLE
Rapalas Incapable of Wearing Rigsuits

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#5303]
#### Brief description of the issue
Rapalas are incapable of putting on RIG suits due to them not being apart of the species list and can be fixed by VAR Editing the RIGsuit to include Rapalas

#### What you expected to happen
Rapalas to be able to wear RIG suits without VAR edits

#### What actually happened
They couldn't

#### Steps to reproduce
- Step 1: Be a Rapala
- Step 2: Try to put on a RIGsuit
- Step 3: Fail

#### Code Revision
 ea791ec4dafcdb1f4642e87e5a015fac917d245d

#### Anything else you may wish to add:
My first Github post; Sorry if it's a bit sloppy.

**Comment by Novacat** [comment]
This is a polaris change, not so much a bug. However, it is perfectly valid to question if we should edit this out.

**Comment by Kegsey** [comment]
Right, I'll see about editing the title; am a Gitnoob
