### ISSUE TITLE
[BUG] Bodysnatcher NIF cloning

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#5304]
#### Brief description of the issue
Using the Mindsnatcher you can clone NIFs if you mindswap into someone with a NIF and get resleeved back into your own body.

#### What you expected to happen
The NIF not to get cloned when you get resleeved after using the Bodysnatcher

#### What actually happened
Used the Bodysnatcher, resleeved the person who died in my NIFd body into a fresh new custom sleeve, they had a clone of my NIF (57% damaged)

The person doesn't need to die for this to work.

#### Steps to reproduce
- Step 1: Bodysnatch into someone else's body who has a NIF
- Step 2: Use a Resleever to put your mind back in your original body
- Step 3: Enjoy your free NIF.

#### Code Revision
ea791ec4dafcdb1f4642e87e5a015fac917d245d
 
#### Anything else you may wish to add:
- I also found out that a Borg mind will be backed up if their mind is in a Backup implanted body.

**Comment by Novacat** [comment]
...Generally, duplicating NIFs is a thing but a NIF can only be keyed to one person, so the extra NIFs are kind of useless.

**Comment by Kegsey** [comment]
The cloned NIFs are persistent through the rounds

**Comment by HzDonut** [comment]
Oh man this bug still exists eh? Yeah, I had a similar thing happen a while back, guess I forgot to make a issue about it. If I remember right, it also sometimes carries over traits between characters as well as bellies.

**Comment by Kegsey** [comment]
Yeah it still carries over bellies, it saved for me; I believe that was because I hit "save prefs" when I was making sure belly noises were on.

I don't know about traits though but mine were still the same.
