### ISSUE TITLE
[SUGGESTION] Make colorblindness a toggleable ability for the sake of player enjoyment.

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#5313]
#### Brief description of the issue

Currently colorblindness traits are a permanent effect on your character, but it only effects the *player*. There is no reason to use colorblindness except for min-maxing your character setup as the effect of losing *your* ability to see color is a huge hindrance on the player experience. It's not necessary to impose colorblindness on the *player* for playing a character that is colorblind but at the same time we should have the ability to see what our characters see, just not all the time.

I personally get headaches when playing my colorblind character too long. I would just remove the trait as I don't need it for my custom species but then I lose the ability to see things as a colorblind person would, making the whole point of playing a colorblind character moot. 

#### What you suggest

Change all colorblindness traits to be a neutral trait but add a verb to toggle the filter on and off in round. This way the player can enable the filter when they need to see through the eyes of their character but don't need to experience the handicap when it's not relevant. 

#### Code Revision
- ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by chaoko99** [comment]
It's an opt-in feature. Don't take it if you're gonna complain about using it.

**Comment by Pear120** [comment]
No I see the point. Changing it to neutral and making it togglable would make it more player-friendly. I like it.

**Comment by MrSign** [comment]
You could also just RP that they have colorblindness without taking the actual trait. You don't need a mechanic/trait to RP a disability.

**Comment by Pear120** [comment]
Or, get this, we don't remove a feature that we already have. We don't need anything but text to roleplay properly, but we enjoy the additions the game provides. Colorblindness is one such additional feature that we ALREADY have. How about, instead, we balance the game properly by removing the point refund you get for taking a trait that has no gameplay impact, that people have likely used to minmax their characters, and instead just make it a toggleable free trait as suggested for the sanity of the players who use it legitimately?

**Comment by SpadesNeil** [comment]
We won't add a toggle. That removes any point of having it at all.

Making it a neutral trait however, I agree with.

**Comment by Kegsey** [comment]
I don't know, I think it should remain how it is; you can't exactly toggle colourblindness in real life (I wish).

**Comment by Sebbe9123** [comment]
Tbh considering we can print brand new organs, whole bodies, augment your vision with a NIF or simply replace eyes with robotic ones, color blindness does not make much sense except for species fluff.

**Comment by Jakksergal** [comment]
It doesn't remove the point in having it at all @SpadesNeil, the whole point of having it in the first place is to be able to see as a color blind person would see, right? Having it be a toggle rather than a persistent thing would enable the player to selectively enable it when it becomes relevant to their roleplay. Making a neutral trait is for balance, otherwise it enables people to just pick it for the trait point and toggle it off immediately. If it's persistent and a neutral trait there is no point in having it at all as the headache-inducing filter bogs down the enjoyment of the game. 

I know that the security doors are red, I know that the bridge doors are blue. A colorblind person like my character does not necessarily see those colors distinctly but I don't like the idea of being forced to view everything with the wonky filters; however, at the same time I would like to be able to occasionally see what they would see. Like I said, it does nothing to hinder the character, just the player.

**Comment by SpadesNeil** [comment]
Okay, let's delete the "needs glasses" option while we're at it, then.

/s

If you don't like it, don't pick the option.
