### ISSUE TITLE
[BUG] Two mob issues (Sprites, AI)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5327]
#### Brief description of the issue
Didn't know if this would be best in two separate issues or just one of them for the sake of convenience.

Issue 1: Some mobs still don't update to their "full" stomach icons. Seems to mainly be ones in the "vore" icon file, as other ones update just fine so far.
Issue 2: Mobs don't move after eating someone until the prey sleeps, for some reason (unable to test if having other players attacking it will force it to move).

#### What you expected to happen
1: They'd update just fine after precious fix attempts
2: They'd continue wandering around to maul and/or eat more people

#### What actually happened
They didn't do either.

#### Steps to reproduce
- Just getting eaten by a mob helps you see both issues.

#### Code Revision
-  release - 
ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by Zeldazackman** [comment]
They seem to keep the mob that they had just devoured as their primary target even as it's inside of them, aka it doesn't clear that var even upon a successful envelopment

**Comment by Zeldazackman** [comment]
Still an issue as of 9/7/2020
