### ISSUE TITLE
Ghosts causes severe lag by being close to z-level edges

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#5334]
#### Brief description of the issue
Ghosts seeming to cause an increase in 'time dilation' by being close to a z-layer edge by increasing runtime spam = lag.

#### What you expected to happen
Ghosts not causing lag.

#### What actually happened
Ghosts being in the wrong area can cause the game to be unplayable.

#### Steps to reproduce
-Go ghost. (Danny Phantom)
-Go to the edge of z-level
-Wait.

#### Code Revision
ea791ec4dafcdb1f4642e87e5a015fac917d245d 
 
#### Anything else you may wish to add:
This is going off third-hand information, however I teleported a ghost in a shift away from the edge with the assistance of @Mewchild finding 'edge' ghosts. After they were teleported away from the area, things cleared up significantly after a minute.

**Comment by Mewchild** [comment]
Going to ping @Verkister for this too. Reportedly he put out an OOC announcement in server about it.

**Comment by Novacat** [comment]
https://github.com/PolarisSS13/Polaris/pull/6214 Is a fix for this. Just got to wait for the mirror, I guess.

**Comment by Heroman3003** [comment]
Its a fix for runtimes. But I fail to see connection between runtimes and afk ghost lag
