### ISSUE TITLE
Wiki and passwords

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#534]
#### Brief description of the issue
I made an account, like 5 of em now, cause when I log in/try to change my email it always says wrong password
#### What you expected to happen
let me log in/change email
#### What actually happened
wrong password
#### Steps to reproduce
make account, try to change email
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
This isn't really an issue for the Github. This is an issue that should be posted on the forum.

http://forum.vore-station.net/viewforum.php?f=20&sid=f6dfc4520bcb5c70446094cc4e7318d7

**Comment by Dr0ppy** [comment]
thanks, will do
