### ISSUE TITLE
teshari with armbands

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#535]
#### Brief description of the issue

if a teshari has an armband attached, it looks like its floating
#### What you expected to happen

for the armband not to be floating
#### What actually happened

http://prnt.sc/cepxia
#### Steps to reproduce

step 1 be teshari 2 get armband 3 attach it to jumpsuit 4 amaze the crew by saying its a magic trick.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-08-30
  a0d7593f29da31882502068a61174a9e43cc2a6b 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  MAGIC

**Comment by Arokha** [comment]
Too hard to fix locally. Requires making new sprite sheets for all attachments usable by Teshari. If Polaris wants to fix it (or someone more bored) wants to pick it up, they can.
