### ISSUE TITLE
[Suggestion] Ready 4 review tag on github

### ISSUE THREAD

**Issue by Sebbe9123** [VOREStation/VOREStation#5351]
#### Brief description of the issue
Want to show devs that I want pr reviewed

#### What you expected to happen
The devs having an overview of what PR's are completed and need QA

#### What actually happened
Am sad cuz no indication that I can see for PR people to tag their PR's

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
we already have that
