### ISSUE TITLE
No one can wash their feet after stepping in oil barefoot

### ISSUE THREAD

**Issue by Waismuth** [VOREStation/VOREStation#536]
#### Brief description of the issue

When a diona steps into the oil spill, their feeet is forever tainted. Space cleaner, shower and soap are all useless.
#### What you expected to happen

Being able to clean the feet after they got dirty
#### What actually happened

Dirty Feet forevermore :C
#### Steps to reproduce

Be diona, step into oil spill in maint tunnels, cry as your OCD is triggered due to uncleanable feet

**Comment by SpadesNeil** [comment]
Probably a Polaris bug. We're due for an update soon but I don't think this has been fixed yet either. It might not be limited to Diona.

**Comment by Alcastar** [comment]
actually i had this happen to me while playing as Sylis, he uses the human model and when i stepped in oil  it wouldnt come off.

**Comment by DemicusMaximus** [comment]
Far as I can tell, this happens to EVERY race. I've had it happen with Human and Tajaran.

**Comment by Arokha** [comment]
My feet get washed when I shower, so this must have been fixed sometime between then and now.
