### ISSUE TITLE
Broken wire north of dorms

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#537]
#### Brief description of the issue
There's a mapping error just north of the dorms where the cable connecting the SE solars to the grid is broken.

#### What you expected to happen
For this stuff to be wired up.

#### What actually happened
![brokenwire](https://cloud.githubusercontent.com/assets/14942479/18351195/1a8b21a0-75d1-11e6-89a4-1a9e6785819b.png)

#### Additional info:
 - It's at the entrance to maintenance north of the visitor dorms. Head south and then east from the back door to medbay.

**Comment by SpadesNeil** [comment]
I had suspected something was wrong there. Let me see if this is an issue on Polaris's map too, as I do not recall changing anything down there.
