### ISSUE TITLE
[BUG] Farmbot with empty tank keeps "watering" a plant...forever.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5401]
#### Brief description of the issue
For some reason I witnessed a farmbot with a totally empty tank just repeatedly trying to water a plant. Even turning it off and back on did not make it actually get water from a sink, and dragging it to a sink just made it go back to the plant. The plant was some soybeans with no nutrition, water, and was unhealthy if that factors into things at all. Second tray from the top, left side.

Update: The dang thing's still doing it even though the plant is DEAD. Finally stopped when i removed the dying plant, now it's doing it to another one. Same plant and health status. Also it's not fertilizing any plants at all.

#### What you expected to happen
It'd go refill its tank at a sink to water the plant.

#### What actually happened
It just kept trying to water the plant while having no water.

#### Steps to reproduce
- Make farmbot
- Deploy it in botany
- Wait for it to run out of water.

#### Code Revision
- release - 
ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by Huenererschrecker** [comment]
I think I remember that kind of bug from another station where the same thing happened. If it is the same problem then the Farmbot is checking the watertanks waterstatus instead of the farmbots for whatever reason.
