### ISSUE TITLE
Virgo2 atmos tiles on the aerostat block laser shots

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#5403]
#### Brief description of the issue
air tiles on the aerostat stop laser shots

#### What you expected to happen
to be able to fire over the gaps in the floor

#### What actually happened
laser proof air

#### Steps to reproduce
- (Step 1)find hole in the ground in virgo 2 aerostat
- (Step 2)shot over it
- (Step3) it's hard cover

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ea791ec4dafcdb1f4642e87e5a015fac917d245d 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheDavestDave** [comment]
ducking autocorrect

**Comment by Rykka-Stormheart** [comment]
This issue is fixed with #5755
