### ISSUE TITLE
You can attack mobs from inside of their stomachs.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#541]
#### Brief description of the issue

Due to reasons of balance and preventing bullshit griefing, this should not be possible to do.
#### What you expected to happen

When attacking a mob from inside, for it not to work.
#### What actually happened

https://youtu.be/GGzvpvqK3Ss?t=85 (Except with melee.)
#### Steps to reproduce
1. Get ate.
2. Switch to harm intent.
3. Punch from inside.
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/1e9f00923dd3bbeca86167da0d522b7143dcfff0

**Comment by Dr0ppy** [comment]
I tought this was a feature?

**Comment by SpadesNeil** [comment]
It's a bad feature. I at least want it disabled for NPC bellies.

**Comment by Dr0ppy** [comment]
fair enough

**Comment by SpadesNeil** [comment]
Doesn't seem to be fixed.

**Comment by Eearslya** [comment]
Can you clarify? What are you trying to (and apparently succeeding) attack from inside? The change I made only modified `/mob/living/simple_animal`.

**Comment by SpadesNeil** [comment]
Allegedly, human mobs are able to attack simple mobs inside their bellies with weapons and the like. Needs testing again.

**Comment by SpadesNeil** [comment]
This bug has appeared again. I do not want melee attacks to be possible inside of stomachs. :(

Otherwise you just have to do what literally everyone does, which is get pounced and then punch/cut/stab your way out.

**Comment by SpadesNeil** [comment]
Gonna close this as a new functionality is desired.
