### ISSUE TITLE
Some admins can't download logs

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#542]
#### Brief description of the issue

Some admins can't download logs with any of the commands to do so.
#### What you expected to happen

To download the logs.
#### What actually happened

Server says they download logs.
ADMIN LOG: JerTheAce/(Andrei Vadik) accessed file: (file name goes here)
Nothing happens.
#### Steps to reproduce
1. Type .getserverlog
2. Select logs.
3. Download logs.
4. Nothing happens.

Alternate:
1. Click "Get Server Log"
2. Nothing happens.
#### Additional info:
- **Server Revision**: This has been ongoing since we switched to Linux.

**Comment by SpadesNeil** [comment]
This is most certainly a problem with our server and not the code. @Arokha or @Leshana please investigate.

**Comment by Arokha** [comment]
If it's a server problem, why does it only affect SOME admins?

**Comment by JoanRisu** [comment]
I don't think this is a Linux problem, at least not for me. I've never been able to pull logs using my laptop but I've been able to do it on my desktop computer.

**Comment by SpadesNeil** [comment]
What differences are there between the two systems?

**Comment by JoanRisu** [comment]
The only thing I can figure out that is different is my laptop is Windows 8.1 and the desktop is Windows 7.

**Comment by SpadesNeil** [comment]
Resolved with FTP access.
