### ISSUE TITLE
cant view cameras while buckled

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#543]
#### Brief description of the issue
you cant look at cameras while buckled to a chair
#### What you expected to happen
to be able to
#### What actually happened
cant
#### Steps to reproduce
make chair in front of camera monitor
buckle yourself to it
realise you cant look at cameras
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-08-30
a0d7593f29da31882502068a61174a9e43cc2a6b  
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
maybe its cause when you are buckled it doesnt let you move your view either? you also cant even select the cameras

**Comment by SpadesNeil** [comment]
This is an issue with how buckling works, and at this time, there's no work-around for it. Marking as wontfix. Sorry.
