### ISSUE TITLE
[Bug] Broken Hardsuit in Abandoned Crates

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5464]
#### Brief description of the issue
I haven't the faintest idea of what the name of the bloody thing in the code is, it was just called "Hardsuit Module". Looked like a box. When you put it on and enabled all the parts, they don't actually show up at all and just leave you bald, barefoot, and without gloves. Even looking at your inventory in the bottom-left shows no hardsuit parts whatsoever, and it also comes with no modules. No clue what the hell it is. Also yes I thought maybe it was only a problem on non-humans, but it did the same to humans as well.

#### What you expected to happen
It'd be some kind of functional hardsuit.

#### What actually happened
It was very, very broken.

#### Steps to reproduce
- Find a crate that has it
- Put it on
- Activate it

#### Code Revision
- release - 
ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by KasparoVy** [comment]
This was fixed in https://github.com/VOREStation/VOREStation/pull/8233
