### ISSUE TITLE
Xenoarcheology Excavation breaks artifacts early.

### ISSUE THREAD

**Issue by Hawk-v3** [VOREStation/VOREStation#5471]
#### Brief description of the issue
Xenoarch deposits break prematurely.

#### What you expected to happen
Digging to a deposit should let me turn on the field generator and dig out the rest to recover the artifact.

#### What actually happened
Digging will just randomly break the deposit no matter the depth.

#### Steps to reproduce
Go to any of the dig sites and try to excavate them normally.

#### Code Revision
Pulled from Master, 14/07/2019 

#### Anything else you may wish to add:
This was just slightly annoying when there wasn't much use for xenoarch but now that there's actual research that can be done through it this should really be fixed.

**Comment by mistyLuminescence** [comment]
That's a feature, you need to have the field gen on before you start digging. Turn field gen on, dig to depth, then brush 1 until something happens, turn field gen off.

**Comment by Verkister** [comment]
I think there's also an actual slightly gamebreaking runtime bug on the artifact spawning that can make like half of the digs just vanish without a trace

**Comment by Hawk-v3** [comment]
Even with the field generator, it's creating strange rocks. Before, if you dug exactly to (variable-assigned) depth, you'd not need to clean out the strange rocks. This hints to something being off with the depth calculations.

**Comment by Heroman3003** [comment]
On live, I believe, there is a bug where all fossils sorta runtime out instead of appearing. That is fixed on master. But yeah, something is weird with general way digging/excavation is handled as a whole. But missing finds might be fossils issue.

**Comment by TheFurryFeline** [comment]
Fixed with #6982, I believe.
