### ISSUE TITLE
A few broken recipies

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5474]
#### Brief description of the issue
A few of the chefs recipies from the list don't work and will either result in a broken microwave or a burnt mess. The food items in question are the fruit salad and the -kabob

#### What you expected to happen
Receive delicious food.

#### What actually happened
Broken tools and burnt messes. 

#### Steps to reproduce
- Aquire food items that you need for the cooking
- Cook the food as said by the recipes
- Aquire junk. If it's a try for the fruit salad, it will give a burned mess. If it's a try for the -kabob, it will break the microwave.

#### Code Revision
- ea791ec4dafcdb1f4642e87e5a015fac917d245d 
 
#### Anything else you may wish to add:
According to Ketrai, microwave code considers anything inedible to not belong in there, even if it checks if it's part of a recipe, which is what fucks the microwave when you try to make a -kabob (because of the metal rods).

**Comment by TheDavestDave** [comment]
kabob needs two meat and one rod to work
