### ISSUE TITLE
Universal Recorders don't capture speech from TTS

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5483]
#### Brief description of the issue
Simple, the Universal Recorders put out TTS-spoken stuff as (Unidentified sounds). This makes it extremly hard to do stuff like keeping a transcript during interrogations. 

#### What you expected to happen
The Recorder to record what is spoken with a TTS, as both are electronics and should therefore be able to record what is going on rather easy.

#### What actually happened
I'm talking to myself in the Transcript as if it's a post-credit scene from metal gear solid.

#### Steps to reproduce
- Spawn as security along with a TTS
- Walk into the processing room
- Start recording with the recorder that is there, then sing a song with your TTS.

#### Code Revision
ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by Mewchild** [comment]
This is a polaris issue, I believe

**Comment by Wickedtemp** [comment]
I'd recommend just asking in LOOC for any interviewed people to just use speech. It doesn't pick up emotes either, iirc. You can also have them provide written testimony, but that may be difficult when you're asking a series of questions and theyre having to answer on paper.
