### ISSUE TITLE
Tied Bandana bug

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#549]
#### Brief description of the issue

A tied bandana still acts as mouth cover even though it's in the hat slot. Means you can't place a cigar on your mouth slot when you wear a tied bandana on the head.
#### What you expected to happen

To be able to put a damn cigar in my mouth slot.
#### What actually happened

https://i.gyazo.com/358562fd6b35c4dfde9a29ff50c9a367.png
I had to take off the bandana to actually put on the cigar.
#### Steps to reproduce

Take bandana. Go to the objects tab. Click tie bandana. Put it on your head and try to put something on your mouth slot. Even the eye slot doesn't work properly.
#### Additional info:

Server revision: release - 2016-09-12
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
This doesn't really seem like a bug to me but I'll mark it anyway.

**Comment by Arokha** [comment]
Think I fixed this at some point.
