### ISSUE TITLE
[SUGGESTION] Add an instrument crate already!

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5507]
#### Brief description of the issue
We got the instrument code fixed ages ago now yet still have no instrument crate, meaning your only choices are the horrible space violin or begging an admin for a piano. There's no real reason to NOT add one to cargo, especially since people can just mute instruments if they find them annoying, and this will allow those who DO enjoy instruments to freely play music.

**Comment by Heroman3003** [comment]
'Fixed' is really subjective, because most of instruments still do sound like total ass.

**Comment by chaoko99** [comment]
Port bay's actual fix to the system. The one that is actually incredible and sounds like you're playing a midi instead of resource churn incarnate.

**Comment by HzDonut** [comment]
I've only heard the violin get screwed up so far.

**Comment by chaoko99** [comment]
A big thing about the violin sounding bad is because its samples honestly suck. Like. It sounds bad on Bay too, because it uses the shittiest samples I have ever heard.

**Comment by TheDavestDave** [comment]
the type of player that is going to play bad music just to bug people is going to do the same with ciruits and need ahelped anyway. Plus circuits aren't muteable.

**Comment by SpadesNeil** [comment]
This is a pretty simple change. You can make the PR, I'm sure.
