### ISSUE TITLE
[BUG] SSD/no mind players aren't properly leaving the round when put into a cryo pod (teleporter, cryo, tram)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5569]
#### Brief description of the issue
Tried loading some dud resleeves (one was SSD, the other had no mind backup) into a cryo pod to get rid of them per @Heroman3003 's suggestion, instead they just sat in there forever and never left.

#### What you expected to happen
They'd poof like anybody else does after a while

#### What actually happened
They remained in there forever

#### Steps to reproduce
- Clone a body
- Try to load it into any cryo pod variant
- Watch as they never go away

#### Code Revision
- release - 
ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by Heroman3003** [comment]
SSD ones should work, as I in practice had successfully sent out someone who died and left, but had mind backup (body printed, backup applied, but player already not here) before. As for mindless bodies that never had never been resleeved into (body printed, backup not applied), yeah, those do tend to break

**Comment by HzDonut** [comment]
One of them was definitely just SSD and didn't successfully go out.

**Comment by HzDonut** [comment]
Update: the mindless one got blocked from entering the round way later on in the shift due to their bugged body.
