### ISSUE TITLE
Autopsy Scanner :B:roken

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5575]
#### Brief description of the issue
The autopsy scanner in the morgue is straight up broken and can't be used on anything or anyone.

#### What you expected to happen
A functional item.

#### What actually happened
The item is a paperweight.

#### Steps to reproduce
- Go to the morgue and get yourself a dead body somehow
- Try to follow the steps as outlined in the wiki, realise the autopsy scanner does nothing no matter how you try to handle it.

#### Code Revision
- ea791ec4dafcdb1f4642e87e5a015fac917d245d

**Comment by Mewchild** [comment]
Make sure you're on help intent when you're using it.

**Comment by Huenererschrecker** [comment]
I was since I was cutting open the body when it happened.

**Comment by TheFurryFeline** [comment]
I've been told it's meant to be used on disarm intent

**Comment by mistyLuminescence** [comment]
Yep, has to be used on a non-help intent so it doesn't conflict with another surgery.  Kinda weird, but eh.

**Comment by Huenererschrecker** [comment]
Well then, I guess that's just weirdly coded and unintuitive then. Can we leave this up for now as a reminder to put that in the wiki when we can?
