### ISSUE TITLE
Promethean get pummeled by slimes

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5582]
#### Brief description of the issue
This is a longer one and I don't know what exactly is fucked here and what's intended, so I'm summarizing what happened. I played a promethean in xenobiology a few shifts ago, so far so good. Slimes didn't instantly agro me which was nice but the moment I disciplined them, they started breaking through windows/windows without stopping (tazing them because they started killing each other and on another time, tazing one because he started killing a medibot). I received the messages that you usualy get when you discipline them right, but that didn't stop them at all, they just all decided that the promethean with the xeno-tazer is now the bad guy. The same stuff happened when the RD at the time came in on my request and tested it, except for him they actually stopped after what feels like alot more tazing than what was needed any other time I watched xeno-bio. At that point we decided that I should put an issue up because there was alot of sketchy stuff going on.

#### What you expected to happen
In summary, that tazing slimes to discipline them stops them from attacking each other/whoever they are trying to attack, turning them a little more passive and safe for handling.

#### What actually happened
The moment I tazed them, they put the agro on me and never let go of it.

#### Steps to reproduce
- Spawn as a promethean in xenobiology
- Breed your slimes like normal, keep a tazer on hand for when they split
- When they split and start killing each other duo to mutations, discipline them
- You now should have agro of the slimes that you tazed, who will now dash at you without mercy, no matter how often you taze them

Alternatively
- Do step 1 and 2
- Keep someone near the pen that can draw initial agro, a medibot or any other non-prom will do
- Do the disciplining

#### Code Revision
- ea791ec4dafcdb1f4642e87e5a015fac917d245d
 
#### Anything else you may wish to add:
- Again, I don't know exactly what parts of this are intended and which weren't but me and the RD of that shift agreed ooc that I should put this up since there was alot of sketch.

**Comment by Novacat** [comment]
Fixed on master branch already.
