### ISSUE TITLE
"allow struggling escape" option on bellies.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#559]
#### Brief description of the request

Citadel has (or had, I dunno if this is still in their code) an option for predators to set whether or not prey would be able to escape from their tummies. By default they were stuck, but preds could allow them to wriggle free or get fulltoured if they struggle. I think something like this would be a neat feature to have.
#### What I'm proposing

Options on bellies, with the default option being to just keep prey where they are, for predators to have their stomachs react to prey struggling inside them.
%chance of releasing the prey.
%chance of setting the stomach to digest/absorb. (with a short message like "the [stomach] gets more active in response to your squirming..."
%chance of moving the prey to another designated stomach.
All default to 0, if none of these happen it should display the normal message about useless squirming.
#### Example of where this would be awesome

A macro catcubus finds a little micro, scoops them, and puts them in her "mouth" belly and subjects them to a whole lot of teasy tongueplay for an extended period of time. Her prey try to wriggle their way out of her mouth with the struggle button (set to 10% chance of escape), but when they start kicking up a fuss she accidentally swallows (set to 10% chance of transferring them to her stomach) and the little snack ends up becoming lunch rather than a toy. She was only playing!

People could also have a kangaroo or something with a "pouch" belly that just lets people out if they struggle, I guess.
Absorbed people won't be able to escape as they can't resist(). Pudge doesn't get to just leave. :p

**Comment by CSchlippy** [comment]
I like this; how hard would this be to code?

**Comment by SpadesNeil** [comment]
Not too hard at all probably.

**Comment by Poojawa** [comment]
Citadel's struggling mechanics were relaymove dealing 'integrity' damage to a particular organ. at <= 0 organ integrity, the prey was spat up and was able to run away.

The toggle was off by default, any movement other than "help" intent would instantly let you 'crawl out'. There were emetics to assist in purging, but no other real function.

**Comment by SpadesNeil** [comment]
Upgrading to severe, as vore mobs should be able to have this feature.

**Comment by SpadesNeil** [comment]
@Cameron653 can you do this?

**Comment by Cameron653** [comment]
I should be able to do it. It's extremely easy as the var and code is already there and all I need to do is add a button to toggle it on and off.
