### ISSUE TITLE
[TYPO] "Blank hypospray" from fishing is actually an autoinjector filled with medicine

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5592]
#### Brief description of the issue
Not only is it not even a hypospray, but like I said it's actually full. It should probably be changed to "unlabeled autoinjector" or something instead. It also turns back into just "autoinjector" after use.

#### Steps to reproduce
- Fish until RNG gives you one, basically.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Heroman3003** [comment]
Its one of 'exploration' autoinjectors that you can only identify in special explorer machine. It being unlabaled is intentional, as well as random medicine. Whats not intentional, is them being fishable.

**Comment by HzDonut** [comment]
It's also meant to be called a hypospray?

**Comment by Heroman3003** [comment]
Yes. It picks a random name from the pool, one being the adjective used for description. It will randomly be called hypospray or autoinjector and thats intentional.
