### ISSUE TITLE
[BUG] Fish all have toxic protein in them.

### ISSUE THREAD

**Issue by Wulfestwulf** [VOREStation/VOREStation#5593]
#### Brief description of the issue
          Fish have toxic proteins in them. 

#### What you expected to happen
          Not to get poisoned for eating the chef's fish hot pocket.

#### What actually happened
          Got Poisoned.

#### Steps to reproduce
          1. Spawn/catch a fish
          2. Cook it
          3. Eat it and get poisoned.
          or
          1. Spawn/catch a fish
          2. Grind it up and watch as the container gets filled toxic proteins.

#### Code Revision
         0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Heroman3003** [comment]
That is intentional design. The toxin can be countered by injecting equal amount of anti-toxin

**Comment by Wulfestwulf** [comment]
I take back this report. Closing it.
