### ISSUE TITLE
[BUG] Cooking recipes with fillets add in Carpotoxins.

### ISSUE THREAD

**Issue by Wulfestwulf** [VOREStation/VOREStation#5594]
#### Brief description of the issue
          Carpotoxins are added to recipes with fillets in them. 

#### What you expected to happen
          Not to be poisoned by the fish burger.

#### What actually happened
         Got poisoned.

#### Steps to reproduce
          Drain a fillet of its posion
          Make a Fillet -o- Carp Sandwich with it
          Grind it and look at the Carpotoxin.

#### Code Revision
          0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Ketrai** [comment]
This is unfortunately a polaris bug, and I have already reported it there too. 
https://github.com/PolarisSS13/Polaris/issues/6193
Doesn't look like anyone is going to fix it tho...

**Comment by Wickedtemp** [comment]
...Can we have some means of getting carp toxin still, please? This was literally the only way and it was kinda fun because you did so by fishing and cooking so you were actually still doing something.

**Comment by SpadesNeil** [comment]
Closed because it's being handled in Polaris.

Add another way of getting carp toxin, but my personal opinion is "no" because it wasn't meant to be something you can just obtain because of the strong medicine it makes and how it's _supposed_ to be rare.

But that is another issue for another day.

**Comment by Heroman3003** [comment]
Means of carpotoxin HAVE been added last update, that being Debris Field exploration area which naturally houses actual space carps.

**Comment by SpadesNeil** [comment]
Then nevermind. The problem is resolved.
