### ISSUE TITLE
[Bug/Mapping Error] Ice cave uses wrong walls

### ISSUE THREAD

**Issue by Brasnak** [VOREStation/VOREStation#5598]
#### Brief description of the issue
The ice cave sub map for Virgo 4 is using the wrong wall tiles. Instead of being made out of rock, they are made out of steel walls that are textured like slightly discolored rocks.

#### What you expected to happen
For the submap walls to be made out of rocks

#### What actually happened
The cave is surrounded by steel walls that look like rocks (kinda).

#### Steps to reproduce
- Find ice cave
- Inspect walls

#### Code Revision
release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da 
 
#### Anything else you may wish to add:

![dreamseeker_2019-08-14_04-11-21](https://user-images.githubusercontent.com/9626555/62989741-9e587c80-be49-11e9-9139-86650fb09667.png)

**Comment by Rykka-Stormheart** [comment]
Nothing seems wrong with the /turf/ files, or with the /iceCave01/ submap, so my guess is a mapgen error. I'm way outta my depth here, unfortunately. </3
