### ISSUE TITLE
[BUG] Laptop suddenly has sensors monitoring, SM monitoring, and power monitoring downloaded

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5600]
#### Brief description of the issue
Sorry for the long title. I downloaded all my usual programs available as RD, then came and saw i had gained suit sensor monitoring, supermatter monitoring, and power monitoring. Can't use any of them, but it's pretty weird. Laptop was in my office too so it's not like anyone just walked in and downloaded the programs. It's entirely possible they were always there and i didn't notice too.

#### What you expected to happen
I'd only get what was available to download.

#### What actually happened
I got bonus programs I can't use.

#### Steps to reproduce
- Get a laptop, open it up
- Download all listed programs as RD
- Wait
- See three programs

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Novacat** [comment]
I had a thonk about this, and, I believe that it may have been the AI that tapped into your laptop. They can do that. Would have to check in with the player.

**Comment by Heroman3003** [comment]
AI from that round did confirm that it was them who downloaded programs
