### ISSUE TITLE
[Bug. I think] "Customize-Say-Verbs" verb doesn't work

### ISSUE THREAD

**Issue by DrunkArcher** [VOREStation/VOREStation#5603]
#### Brief description of the issue
There's a new verb added on the update called "Customize-Say-Verbs" that, just like its description specifies, "It's used to customize the text which appears when you type- eg. 'says', 'asks', 'exclaims'." 

The problem is that the verb actually does nothing. Nothing happens when you select the verb on the IC tab in-game, nor when you use it on the chatbox.

#### What you expected to happen
Let you change the text that appears when you use the "say" verb, or atleast open up a new window/prompt in-game with further instructions.

#### What actually happened
Nothing.

#### Steps to reproduce
Either:
- Select the verb on the IC tab.
- Type in the verb on the chatbox. (Neither the commands "Customize-Say-Verbs", "Customize-Say-Verbs example", or "Customize-Say-Verbs 'example'" do anything at first sight)

#### Code Revision
release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Mewchild** [comment]
Tagging @mistyLuminescence
