### ISSUE TITLE
[Bug] Crew Monitor warning even in areas that it functions.

### ISSUE THREAD

**Issue by Tename** [VOREStation/VOREStation#5609]
#### Brief description of the issue
The crew monitor gives constant spammy warnings saying that it will not function in this area even in places that it functions.

I was in the tram as a medihound using the crew monitor when it decided to give me a constant spam of warnings saying it may not function, the monitor does function in the tram perfectly fine.

#### What you expected to happen
No warnings as it worked.

#### What actually happened
Constant spam.

#### Steps to reproduce
- Open  the crew monitor
- Step on the tram and wait for it to launch
- Spam

#### Code Revision
- 0015a40b20070fa8cc03fd2c80ca7655174b50da 
 
#### Anything else you may wish to add:
-
[![Screenshot from Gyazo](https://gyazo.com/824d9b9255f1cd098dfc1a883830f1c0/raw)](https://gyazo.com/824d9b9255f1cd098dfc1a883830f1c0)

[![Screenshot from Gyazo](https://gyazo.com/518d4cb9302e295af80771fe8915ef5f/raw)](https://gyazo.com/518d4cb9302e295af80771fe8915ef5f)

Also could it be changed to not be as spammy, just one warning is fine.

**Comment by Heroman3003** [comment]
Seems like its meant to just close and not come up at all, but you having it open caused it to continuously spam, when it is supposed to send one message and close th monitor window

**Comment by Tename** [comment]
> Seems like its meant to just close and not come up at all, but you having it open caused it to continuously spam, when it is supposed to send one message and close th monitor window

The monitor still shows crewmembers on the same Z-Level even if it is not connected, I am not sure why it should close.

**Comment by Tename** [comment]
> Seems like its meant to just close and not come up at all, but you having it open caused it to continuously spam, when it is supposed to send one message and close th monitor window

And also the monitor fully functions on the tram. And having to re-open it every time I pass the elevator would be really annoying.

**Comment by Heroman3003** [comment]
The fix for elevator is separate one. As for your picture, it doesn't seem to actually be working on level you're on? In fact it looks like its stuck in its last state it was on the station.

**Comment by Tename** [comment]
> The fix for elevator is separate one. As for your picture, it doesn't seem to actually be working on level you're on? In fact it looks like its stuck in its last state it was on the station.

Ah, ya I guess your right, sorry about that.

**Comment by Heroman3003** [comment]
Tbh, you shou;dn't have closed the issue, its still reporting a bug, just not the one you thought was a bug. The bug where it just spams instead of closing the window still is there..

**Comment by mistyLuminescence** [comment]
Elevator/tram both use Transit Z iirc, so the fix should fix both. It *should* be closing the window when it sends the message, kinda weird that it isn't.

**Comment by Heroman3003** [comment]
Actually no. Elevator uses z-4, tram uses the Ships z-level. The two are different.
