### ISSUE TITLE
[SUGGESTION] Explorer, Field Medic, and Pilot all shouldn't share the same slot pool (Update: more complex than we thought)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5618]
#### Brief description of the issue
For some reason, all those jobs in the title share the same three slot limit for expeditions, so you can end up with two pilots and only one explorer. Considering pilots are more of a "support" role and the fact no field medic can spawn either, this is pretty problematic as you might imagine. At LEAST up the slots to help with this.

UPDATE: Problem is even weirder than first glance. One pilot, one pathfinder, and one explorer doesn't allow a new explorer to spawn in. Before you could have a PF, three explorers, and a pilot.

#### What you expected to happen
Different jobs with entirely different roles would have different slot limits.

#### What actually happened
They share the same small job pool.

#### Steps to reproduce
- Just fill the slots with whatever.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Novacat** [comment]
They do not share the same slot pool. The number of slots for each job role:
1 Pathfinder
2 Explorer
2 Field Medic
2 Pilot
