### ISSUE TITLE
[SUGGESTION] Lower the time it takes to recharge frontier phasers.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5619]
#### Brief description of the issue
50 seconds. 50 friggin' seconds of making everyone wait to reload every single time you run out of charge. Do you know how fun that is around ion monsters? Do you? It's terrible, dreadful, unfun.

#### What you expected to happen
NOT THAT

#### What actually happened
THAT

#### Steps to reproduce
- Just recharge a fully empty frontier phaser or frontier holdout pistol.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by SpadesNeil** [comment]
You know how to code, right? This is a very simple change. You can make the PR.

**Comment by Rykka-Stormheart** [comment]
I know this was just closed, but I'll do it soon, too, if it's still not been done! <3
