### ISSUE TITLE
[BUG] "Virgo 2 Atmosphere" tiles block projectiles

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5620]
#### Brief description of the issue
It's right in the title, they prevent you from shooting past them. Make the aerostat real fucked up to fight in.

#### What you expected to happen
Projectiles would go over the "open space" of the atmosphere.

#### What actually happened
BLOCKED

#### Steps to reproduce
- Try to shoot over any hole in the aerostat, really.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by TheDavestDave** [comment]
yeah I noticed this. The devs seemed to of not noticed it. https://github.com/VOREStation/VOREStation/issues/5403

**Comment by Rykka-Stormheart** [comment]
It's a turf thing.

Per a discussion in #development the other day:
PrismaticGynoid#4492

> Theory tested and confirmed: The reason you can't shoot over the sky tiles is that the sky calls do_fall on the projectiles and they fall out of the sky
Which is hilarious and probably not how it's supposed to work

I'll see if I can fix it or drag in @Novacat to help. <3

**Comment by Screemonster** [comment]
Sounds like do_fall() needs to just return false for projectiles

and flying things for that matter

**Comment by Rykka-Stormheart** [comment]
> Sounds like do_fall() needs to just return false for projectiles
> 
> and flying things for that matter

already done, screedork <3
