### ISSUE TITLE
[SUGGESTION] Virgo 2 rebalance (mainly the aerostat)

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5621]
#### Brief description of the issue
I'm getting a wee bit sick of walking through a door and getting one or two shot by the blue laser hivebots or the ballistic ones. This map needs a serious look over to try to balance it out a bit more. I get it's the "hard" map but this is outright unplayable at times with how hard you can get hit.

#### Code Revision
-  release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Novacat** [comment]
Personally, I consider it a bad idea to go to V2 with a largely inexperienced expedition crew.
