### ISSUE TITLE
[BUG] Cyborg/Synth chargers still charge even without a battery/no charge/no power

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5622]
#### Brief description of the issue
A combination of the above works too. A battery and no power, an uncharged batter and no power, etc.

#### What you expected to happen
It wouldn't work due to a lack of power.

#### What actually happened
Still recharged

#### Steps to reproduce
- Mess around with a recharger to either make one in an unpowered are or remove the battery of one
- Go inside
- Charge

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Heroman3003** [comment]
No power at all is weird, but charging without battery/charge left in it is intentional, as that way of charging is notably much slower than when there IS stockpiled power in it, and its supposed to charge straight from powernet

**Comment by Arokha** [comment]
Can't replicate this. If I turn off machinery power in an area, and get in, I charge until the cell runs out, then stop charging.

There's also not supposed to be any way to remove the battery so if you found a way to do that let me know. They aren't constructable without a battery, and there's no procedure for removing it.

I see another bug related to machines that I'll open in a sec, though, that if you decon and recon a machine in an area with power turned off, it will assume power is turned on.
