### ISSUE TITLE
[SUGGESTION] Borg vore toggle

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5623]
#### Brief description of the issue
Basically maybe we should add a vore pref thing that doesn't allow hounds to even vore you. Too many of them just nomph people down as soon as they get hurt, it's an annoyance.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Rykka-Stormheart** [comment]
Agreed.

**Comment by SpadesNeil** [comment]
Not a bug. This is an OOC issue. Ahelp it.

**Comment by Screemonster** [comment]
I'd rather see something like this as a "be prey at all" toggle rather than making it specifically about borgs just because a borg player is being a problem.

Or just ahelp it and we can apply the _malleus interdico_.
