### ISSUE TITLE
[BUG] (Jokey Title) Virgo 2 is so hard that even the mobs die

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5625]
#### Brief description of the issue
Seriously, everything on the planet was dead. Hivebots? Dead. Combat drones? Blown up. Corrupt hounds? Mostly dead. All the syndies? Dead as a doornail.

#### What you expected to happen
The virgo 2 mobs would be able to survive on virgo 2.

#### What actually happened
Death.

#### Steps to reproduce
- Just go to v2 and head down to the planet.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by FoxCalledBox** [comment]
I wasn't expecting people to go to V2 I was messing with mob spawning there. Those mobs were alive when I got there.
This is not a bug, this is a admeme.
