### ISSUE TITLE
[SUGGESTION] Make the resleeving process ALWAYS require a confirm.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5627]
#### Brief description of the issue
I'M SICK OF ALMOST BEING DEFIBBED AND THEN RESLEEVED, MAN. Also it'd help prevent people from coming out SSD, I guess.

#### What you expected to happen
I'd get a confirm like when you get almost resleeved while alive.

#### What actually happened
NO CHANCE. IT JUST HAPPENS.

#### Steps to reproduce
- Die and not want to come back, then be brought back. 

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Heroman3003** [comment]
If you don't want to come back into round, you can just hit Quit the Round verb. Thats what its for, it prevents being resleeved and gets rid of your records/slots.

**Comment by HzDonut** [comment]
That's not even remotely the problem here.

**Comment by Heroman3003** [comment]
Tbh, that would be more of issue in terms of failed intercommunication in medical? If they are resleeving and defibbing same person at same time

**Comment by HzDonut** [comment]
Happens a lot on expeditions too, someone's about to get rez'd but then poof, gone.

**Comment by TheFurryFeline** [comment]
I agree with Hero here. But then again, we already have the confirmation window for resleeves when already alive. Don't think it'd be hard to integrate that with the mind backup system so it can bring that window up if you're being resleeved.

**Comment by Rykka-Stormheart** [comment]
> I agree with Hero here. But then again, we already have the confirmation window for resleeves when already alive. Don't think it'd be hard to integrate that with the mind backup system so it can bring that window up if you're being resleeved.

Yessssss. I really want a confirm window for being resleeved so you can deny it if you're currently being defibbed. Exploration has issues with comms depending on where they are, and if someone resleeves somebody super far away from the active expedition, *ESPECIALLY* when they've got a shelter and such in place to defib them, it makes it more of a pain because they have to "run the gauntlet" again so to speak.

**Comment by Heroman3003** [comment]
And on the other hand it exhilirates the problem of printing out bodies for AFK people and sleeving them, since requiring confirmation will prevent those from working.

**Comment by Mewchild** [comment]
Medical gets a resleeve notification fifteen-twenty minutes after your death, and the defib timer is only up to ten minutes. If you're being defibbed at the same time medical is getting the resleeve notification, you're too far gone in most cases, anyway.

**Comment by HzDonut** [comment]
Closing this since clearly the point is getting through/people don't care

**Comment by Rykka-Stormheart** [comment]
Testing issue reopen?

**Comment by HzDonut** [comment]
Suggestions aren't allowed on the github anymore anyways, remember?

**Comment by Rykka-Stormheart** [comment]
> Suggestions aren't allowed on the github anymore anyways, remember?

They still are! Just not en masse, and they need to be a clearly-written format or a clearly-important issue/suggestion - this one would be good, imo. But, I'd ask Ace.

**Comment by SpadesNeil** [comment]
This one I will allow because it's a feature that we should have.

**Comment by HzDonut** [comment]
Alright then. Since the original post was written in a time of salt, lemme rephrase the issue a bit better:
As of right now, if you are dead and someone resleeves you, you get slapped into your body with no warning or chance to deny it. This can lead to you getting yoinked from potential rescues or who knows what else. When the issue was brought up in lobby, one idea we came up with was that we could reduce the resleeve notification to 10 minutes to match the defib timer, then make it so that before those 10 minutes, you will get a warning pop up so you can deny a resleeve, but after those 10 minutes it's automatic.
