### ISSUE TITLE
Disposable teleporter and bluespace crystal (xenobio) have no cancel button

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5628]
#### Brief description of the issue
Why the hell would there ever be an item in the game that opens a menu and then fully locks you into it without a cancel, seriously? For context, when you use either of those items it opens a menu to select a place to warp to. However, there's no cancel. You need to DC to fully ensure you don't warp off.

#### Code Revision
-  release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by SpadesNeil** [comment]
I _think_ this is a Polaris bug. Are those mechanics Polaris things too? I forget.
