### ISSUE TITLE
[BUG] Red Candle Pack goes invisible and ceases to exist (mostly) when filled with six candles

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5643]
#### Brief description of the issue
Like the title says, for some reason when you insert a sixth candle into a red candle pack, it vanishes. You can right-click the tile it's on to see it for examination and picking it up, but if you hover your mouse over the tile it's not there and you can't interact with it beyond that.

#### What you expected to happen
It'd either tell me the candle pack is too full or let me insert the sixth candle.

#### What actually happened
Poof.

#### Steps to reproduce
- Just grab a red candle pack and slide another candle into it.

#### Code Revision
- release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da 
 
#### Anything else you may wish to add:
- Could apply to all candle packs, but I've only ever seen red ones.
- https://gyazo.com/c771b632eaa01bf9b325d8628671a98a examine text
- https://gyazo.com/a01b46a2257cbe51e7f8bc081c51c9ae the table the pack is on

**Comment by TheFurryFeline** [comment]
Seems this is cropping up again.
