### ISSUE TITLE
[SUGGESTION/DISCUSSION] Problems with voidsuits as loot

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5644]
#### Description of the issue
As of right now, most of the voidsuits you can find out in expeditions are human versions, and unfortunately most of them are also UNIQUE voidsuits with unique sprites. This means pretty much every time an explorer finds the thing, and they're not human/have a human base (as most players are, let's be honest), their choices are to either never wear the voidsuit or pop it into a cycler and overwrite the sprite with whatever choices are in there. At least with syndie voidsuits you can maybe get an emag from maint trash or pray one into existence to emag the cycler and get a proper voidsuit, but others like the "reinforced engineering voidsuit" have no matching cycler that I've seen yet. This issue has gotten so obnoxious to me personally that I've just made my explorer human so I can finally enjoy the fruit of my labor during expeditions. I've opened this github issue to see if maybe we can figure out some kind of solution to this annoying problem.

**Comment by Novacat** [comment]
More sprites. A lot of the issue is missing sprites.
