### ISSUE TITLE
Lack of Keycard Auth in HOP

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#5653]
#### Brief description of the issue
No Keycard Authentication device in HOP Office

#### What you expected to happen
All command staff rooms to have one.

#### What actually happened
Lack of it in HOP Office.

#### Steps to reproduce
- (Step 1) Be HOP
- (Step 2) Need to boost to Code Red
- (Step 3) Fuck, there's none in my office!

#### Code Revision
- 0015a40b20070fa8cc03fd2c80ca7655174b50da 
 
#### Anything else you may wish to add:
- Location: HOP Office

**Comment by Heroman3003** [comment]
...yes they have one. Bottom left corner of the office.

http://prntscr.com/oudwrp

**Comment by TheFurryFeline** [comment]
Oh, whoops. Alrighty, then
