### ISSUE TITLE
Augment Upgrades

### ISSUE THREAD

**Issue by SioxGWolf** [VOREStation/VOREStation#5663]
#### Anything else you may wish to add:
-Allowing new and varied upgrades to augments. Similar to genetics, but for both cyborgs and people with synthetic organs, it could allow a variety of both useful, erotic, or varied abilities all explainable in the realms of science. Such as strength in augmenting limbs, allowing hubs or ARs in cybernetic eyes, as well as flash protection. All things I have seen done in other servers... and in this one particular, more flexibility without breaking canon.

**Comment by Rykka-Stormheart** [comment]
I've got a couple characters that, canonically, have "stronger" cybernetic arms in the sense that the individual prosthetic is built "for combat", and in the case of my synth character, the rest of her body isn't built to handle combat to that degree.

It'd really be nice to "upgrade" Suzu or Rykka's left arms to be capable of heavy combat, or say, doing extra damage in melee, being more resistant *to* harm, etc etc. Of course, limits should be in place, but, I think it'd be a good thing to have.

**Comment by SioxGWolf** [comment]
And including a builtin stunbaton or tazer, would...honestly just be kinda cool... or a built in drill for a miner!

**Comment by SioxGWolf** [comment]
With proper ya, regulations I suppose...and in CANON a few of the books do mention modifying and improving cybernetic limbs of certain brands, like that cyber surplus thing or something.

**Comment by Heroman3003** [comment]
Main issue with that is with persistance system it'd either be possible to kit yourself out on strongest upgrades and get to keep them every round forward, or for some weird reason require to cut your arm again every single shift...

**Comment by SioxGWolf** [comment]
Welp, just make the upgrades a bit of a modular system maybe? So they have to canonically be just removed and returned or such? And for weaker upgrades, kept, but are part of the already existing point system, similar to the computer is upgradable but only with points.

**Comment by SioxGWolf** [comment]
And could allow certain augments to replace certain items in the buy pool, especially if we go down a route of these augments being some type of modular.

**Comment by Rykka-Stormheart** [comment]
Would you be able to assist in coding/setting this up?

You can reach me on Discord via Soryn#8798 or Rykka Stormheart#8798 <3

**Comment by SioxGWolf** [comment]
Oh, I can help test it out if ya need a test subject but nothing more.
