### ISSUE TITLE
Unathi snouts at larger sizes

### ISSUE THREAD

**Issue by SioxGWolf** [VOREStation/VOREStation#5668]
#### Brief description of the issue
Shoots'air Aejura-Kakralia Nyzkcusz: Btw, I don't make their heigh much taller since, unathi snouts and shit get fucked up.

apparently fix unathi snouts at larger sizes. 
I don't play one but still an issue I noticing. Posted for another.

**Comment by Mewchild** [comment]
That's just an issue with how pixel scaling and the like works. It's not a bug

**Comment by SioxGWolf** [comment]
Would there be any way to fix that? maybe a new sprite at certain sizes?

**Comment by Heroman3003** [comment]
Its a "More complicated than you think" type of issue. Its just how sprites scale. Making different sprites of a new scale for a humanoid species is endeavor of gargantuan work that would yield little payoff

**Comment by SioxGWolf** [comment]
The biggest question is why are the snouts specifically having issue?

**Comment by Mewchild** [comment]
It's not just snouts. It's all sprites. They all get distorted when scaling upwards, because the pixels themselves get stretched.

**Comment by SioxGWolf** [comment]
Welp, nothing more I can say, it is a lot of effort for no pay off, wouldn't mind someone putting the foundations for sonething like this, but I am gonna close it offically, and only hope I can reopen it one day.
