### ISSUE TITLE
Lore Conflict in Wilderness

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#5672]
#### Brief description of the issue
The voidsuit wearing mob in the wilderness is titled "Syndicate Commando" where, in our lore, the syndicate fell apart several decades ago. The commando should either be removed, or renamed to something lore appropriate.

Snipped the rest of the issue template because not needed
 
#### Code Revision
Server revision: release - 4538389237f9e51dda94af66869ed0481d3317da

**Comment by TheDavestDave** [comment]
https://github.com/VOREStation/VOREStation/pull/5297

it's been brought up before. Personl I like a Hiroo Onoda kind of deal where they saw the message and went. This is an NT lie.

**Comment by Heroman3003** [comment]
I believe it already was renamed approprietly in a different PR before, and appears to still be named Mercenary Commando
