### ISSUE TITLE
Spawn Character doesn't have a cancel button. (and maybe more admin commands)

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#5677]
#### Brief description of the issue
Going through the stages of using the 'Spawn Character' verb as an admin. IIRC, at no point are you able to cancel the action at any point. Resulting in having to disconnect from the client in order to avoid spawning the person in.

#### What you expected to happen
Being able to cancel at any point without having to reconnect.

#### What actually happened
Being forced to close the client and reconnect because a change of mind occured.

#### Steps to reproduce
-Special Verbs, 'Spawn Character'.
-Select desired c-key and go through the steps.
-Change your mind during it.
-Realise you cannot cancel.
-Close client.

#### Code Revision
4538389237f9e51dda94af66869ed0481d3317da 
 
#### Anything else you may wish to add:
I'm going to guess a lot more admin commands have the downside of not being able to cancel at any point. So... Would be very good if admins can cancel stuff without requiring to disconnect.

**Comment by Heroman3003** [comment]
It... actually does have cancel buttons though? On every step of the way past selecting the ckey there is a  cancel button, amounting to total of three chances to cancel. Though as I found out, first one of them isn't functioning, going to fix up on Polairs now. But the last two absolutely work.

**Comment by Rykka-Stormheart** [comment]
@Heroman3003 @SpadesNeil would you guys consider this resolved?

Just digging through issues to find stuff to fix <3
