### ISSUE TITLE
[SUGGESTION] Allow pAI devices to slot into Electronic Gloves (or give a list of items for them)

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5678]
#### Brief description of the issue

Allow pAI devices to slot into electronic gloves, or give some sort of a list or info on the wiki as to what fits into them and the other "electronic" loadout options.

#### What you expected to happen

See electronic gloves with screen, description says you can put stuff into them. Expect to fit pAI device into gloves because screen, or have at least *some* knowledge of stuff you can put in it.

#### What actually happened

pAI devices don't fit, and desc has no info on what fits into electronic gloves. So you're SOL since wiki *ALSO* has no info about what fits into electronic gloves/headwear/facewear

#### Anything else you may wish to add:
- Give us more tools for the electronic gloves? Or more uses? It'd be nice, if, for instance, I could upgrade my electronic gloves to be a "built-in" welding torch, or so-on, y'know?

**Comment by Mewchild** [comment]
Those are used as housing for modular circuits, a part of RnD

**Comment by Heroman3003** [comment]
All electronic things have purpose of being 'frames' for integrated circuitry. So unless you have access to doing the said circuitry, the only reason to pick them is for the looks.

**Comment by Very-Soft** [comment]
Ya, pAIs slot into your PDA. They don't really need to slot anywhere else unless we're talkin' lood stuff.

**Comment by Rykka-Stormheart** [comment]
> Ya, pAIs slot into your PDA. They don't really need to slot anywhere else unless we're talkin' lood stuff.

But why not let pAI's slot into the gloves? <3

**Comment by Heroman3003** [comment]
Because those gloves already have a clear-cut purpose to them?
