### ISSUE TITLE
[SUGGESTION] Allow Bowman headsets in Loadout Selection

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5679]
#### Brief description of the issue

It'd be nice if you could choose to have a bowman headset instead of a regular headset. I know it's "just" a visual thing, but it'd be cool. Imagine going to "earwear" in loadout and choosing "bowman headset (Replaces default headset)". It'd auto-replace whatever headset with the bowman version of it. IE - instead of spawning in with an engineering radio earpiece, you spawn with an engineering bowman headset, and so-on.

**Comment by TheFurryFeline** [comment]
This'll be a Polaris addition that I'm going to PR there. Toggleable like with backpacks in General tab of Character Setup.

**Comment by Rykka-Stormheart** [comment]
> This'll be a Polaris addition that I'm going to PR there. Toggleable like with backpacks in General tab of Character Setup.

Will you be adding in bowman headsets for those jobs that don't have one? I'd love to have a science bowman headset, a mining bowman headset, and so on. Thanks! <3

**Comment by SpadesNeil** [comment]
This is a pretty simple change. You can make the PR, I'm sure. Send it to Polaris.
