### ISSUE TITLE
[SUGGESTION] Add a labeller to the explorer prep room

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5681]
#### Brief description of the issue
There should really be one in there so you can actually mark who's locker is who's, because boy right now is it an absolute mess in there every expedition with people just grabbing shit from every locker in a chaotic fashion because they just want gear and will get it from anywhere they can.

**Comment by SpadesNeil** [comment]
This is a pretty simple change. You can make the PR, I'm sure.
