### ISSUE TITLE
Battlerifle back.dmi sprite is wrong

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#569]
![capture](https://cloud.githubusercontent.com/assets/6484985/18622986/618c6e74-7e05-11e6-9a40-5f9ae545c312.PNG)

**Comment by SpadesNeil** [comment]
I think this got fixed.

**Comment by Screemonster** [comment]
yeh, pretty sure I fixed it and the halo shotgun just after I did the particle guns 'cause I ran into the same problem. Both should be fine now.
