### ISSUE TITLE
[SUGGESTION/REQUEST?] Port over Xenobiology Console from Paradise/TG

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5690]
#### Brief description of the issue

In order to help make Xenobiology less insta-death for anything non-promethean and more fun (because breeding slimes is cool as fuck). Can we look into porting over the Xenobiology consoles from para/TG? 

> Genocide Now: The Slime Console and You
The Slime Console is a semi-new addition to the Xenobiology scene that makes your job roughly a hundred million times easier. With it you can move slimes, kill them, feed them, and process dead monkeys with mere clicks of a button! If for some reason however you want to do Xenobiology the old-fashioned way the way your pappy taught you, then this guide will still help you.

Sourced from here: [https://nanotrasen.se/wiki/index.php/Guide_to_xenobiology](url)

Requesting this since time and time again it's come up that xenobiology is insta-death and tons of RNG for anyone non-prommie, and even for Prometheans, it's still very RNG and can quickly turn to death.

Xenobio is hella cool. Let's make it more viable and more fun to get into. Barring that, can we add some other xenos for us to pen in xenobiology? Xenomorphs, spiders, etc etc.

**Comment by HzDonut** [comment]
If we could just outright take their entire xenobio in general, that'd actually be better for us in the long run. Their xenobio is now only less of a hassle to use, but actually has double the amount of core possibilities we have, last I checked. It'd just be a straight upgrade, once you tweak it for a more HRP environment of course (ex: removing the ability for luminescents to eat an oil coil and suicide bomb people)

**Comment by SpadesNeil** [comment]
have fun with that
