### ISSUE TITLE
Shadekin vore smite is broken

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#5693]
### What you expected to happen
shadekin to phase in on someone, eating them, burp, and then phase out, deleting them 

#### What actually happened
no shadekin :c

#### Steps to reproduce
- Be admin
- Want to delete something with smite
- Choose Shadekin vore smite

#### Anything else you may wish to add:
- :CCCC

**Comment by Rykka-Stormheart** [comment]
:CCCCCCCCCCC
