### ISSUE TITLE
[SUGGESTION] Add Glove-style Weaponry

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5694]
So, pulling from W40k lore, there's a "Lightning Claw", and it's basically an armored glove with claws attached, that have a disruption field that _disintegrates_ any matter it touches. Super OP.

Image [Lightning Claws](https://vignette.wikia.nocookie.net/warhammer40k/images/8/8a/Lightning_Claw.jpg/revision/latest?cb=20120908184037)

Not saying we need that, but a similar weapon would be great. Make it non-disarmable.
Also, add a "station-lock" to it.
Works like this: Claws are retracted into the gloves. You replace your current gloves with the claws. (Maybe make it a Research thing they can make?), and then go out. The station-lock prevents the claws from extending while on-station, and as soon as you step _back_ on station, the claws immediately retract, and refuse to let you deploy/extend them again.

The other alternative glove-related weapon was a suggestion from Scree:

> The Beast of BadminToday at 6:01 PM
really I just want to see someone code the Ballistic Fist

> just a glove that takes fucking shotgun shells

> it's basically a power fist with a sawn-off shotgun welded to it
the trigger is the knuckle guard

Image: [Ballistic Fist](https://vignette.wikia.nocookie.net/fallout/images/c/c0/BallisticFist.png/revision/latest?cb=20110209054932)

For those concerned about balance - station-lock it too, just like frontier phasers. Make the ammo self-generating or something.

Add different versions of the glove-claws and the shotgun-claws, for Sec, Exploration, Mining, etc etc. Make it so Research has to produce it, perhaps?

I'd love constructive criticism or ideas on how to better implement it (and tbh I might take this as my first coding project, with some help, lol).

**Comment by Screemonster** [comment]
the main thing is that nifsoft claws exist (albeit as an illegal module) that give the user an undisarmable melee attack and imo everything that nifs can do should be available as an item of some sort

**Comment by Rykka-Stormheart** [comment]
Fixed the image links, and I agree with you on that, Scree. Some stuff should be obtainable through means other than illegal. And, honestly, station-locking it like I mentioned above is the best way to get around griefers. If they want un-disarmable, melee claws or shotgun gloves, they need to get an E-Mag, which iirc you need to ask an admin for.

**Comment by Screemonster** [comment]
to be fair giving it a big obvious sprite and a clear "if security see you wearing this fucking thing on-station they'll tase the shit out of you" is probably enough

**Comment by Rykka-Stormheart** [comment]
To update this suggestion - I'll be working on it soon, I'm leaving it up for now.

**Comment by Screemonster** [comment]
There's a refactor up on polaris that touches glove things that you'll want to wait for.

**Comment by Rykka-Stormheart** [comment]
> There's a refactor up on polaris that touches glove things that you'll want to wait for.

thanks for letting me know <3
