### ISSUE TITLE
[BUG] SL-ED=209 Repeatedly blows apart

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5702]
#### Brief description of the issue

When killed, SL-ED-209's repeatedly spam their chassis parts and blow apart.

#### What you expected to happen

It blows up once, that's it.

#### What actually happened

SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
The metal baby slime (865)'s flesh sizzles where the water touches it!
The metal baby slime (865)'s flesh sizzles where the water touches it!
The metal baby slime (865) dies!
The metal baby slime (865)'s flesh sizzles where the water touches it!
The metal baby slime (865)'s flesh sizzles where the water touches it!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
The metal baby slime (917) dies!
The metal baby slime (917)'s flesh sizzles where the water touches it!
The metal baby slime (917)'s flesh sizzles where the water touches it!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
 [Science] Charlotte shell 128 states, "Complete."
SL-ED-209 Security Robot blows apart!
 [Science] Nysku says, "Well, that was... dramatic."
Nysku mrowls, "Well, that was... dramatic."
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been prodded with the slimebaton by Charlotte shell 128. Luckily it was off.
SL-ED-209 Security Robot has been prodded with the slimebaton by Charlotte shell 128. Luckily it was off.
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot has been beaten with slimebaton by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been whacked with fire extinguisher by Charlotte shell 128!
SL-ED-209 Security Robot has been thrashed with fire extinguisher by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been bludgeoned with fire extinguisher by Charlotte shell 128!
SL-ED-209 Security Robot has been bludgeoned with fire extinguisher by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot has been thrashed with fire extinguisher by Charlotte shell 128!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!
SL-ED-209 Security Robot blows apart!

**Comment by Rykka-Stormheart** [comment]
Yes, it spammed it's frames and slimebatons on the ground.
Negative? Spam.

Bonus? I can make infinite SL-ED-209's. Profit.

**Comment by Novacat** [comment]
[2019-08-23T11:32:51] Runtime in ed209bot.dm,36: undefined variable /obj/item/weapon/melee/baton/slime/var/power_supply
   Caught by Mobs subsystem
   src: (the floor) (31,66,1) (/turf/simulated/floor/tiled) ()
   src.loc: (the floor) (31,66,1) (/turf/simulated/floor/tiled) ()

**Comment by Novacat** [comment]
Polaris fixed the issue, just waiting for the fix to come here, marking this as resolved.
