### ISSUE TITLE
Removing access with ID console breaks ID presets

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#5720]
#### Brief description of the issue
The ID console seems to only be able to apply presets, and if you happen to remove access from a preset, it seems to remove that access from the preset. 

#### What you expected to happen
Give CD a new ID after they messed theirs up.

#### What actually happened
the CD preset in the computer was missing a lot of its access, including bridge access. 

Also it broke the spare, and when I spawned a new spare that spare was also broken????

#### Steps to reproduce
- ???
- Use ID machine
- Remove an access
- Observe as now anyone who's ID has that preset cannot access that thing anymore!!
 
#### Anything else you may wish to add:
- I don't know for sure if there were any steps taken before this happened, so I'm not super sure how easily repeatable this is. But! This bug would essentually let anyone with access to the ID machine remotely remove access from jobs! And that's lame!

**Comment by Screemonster** [comment]
lmao, the difference between pass-by-reference and pass-by-value strikes again
