### ISSUE TITLE
Atmospheric Technicians sleeves can't be rolled down

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5721]
#### Brief description of the issue
When you wear a normal atmos-tech outfit and click the ''roll up sleeve'', you can't roll them down again. Instead, you only get the message that you rolled down your sleeves without them actually doing so. This gets ''fixed'' by taking off the suit and putting it back on, then clicking roll up sleeves, which then rolls your sleeves down.

#### What you expected to happen
Rolling up your sleeves and down with no problems.

#### What actually happened
Biceps too big, can't contain my muscles once shown.

#### Steps to reproduce
- Spawn as Atmospheric Technician or an Engineer and grab an Atmos suit from their lockers.
- Wear it like normal
- Click ''roll up sleeves'' in the object tab
- Click ''roll down sleeves'' in the object tab

#### Code Revision
- 4538389237f9e51dda94af66869ed0481d3317da 
 
#### Anything else you may wish to add:
- Might not be limited to atmos-tech outfits, just noticed this with them.

**Comment by Rykka-Stormheart** [comment]
This should've been fixed with the September release #5772 (unless I'm tagging the wrong one) @SpadesNeil or @Novacat can you confirm?

**Comment by Huenererschrecker** [comment]
It's not them but I can confirm that it's fixed. Either that or I had a weird but/glitch that only happened once and can be disregarded anyways. So, can probably be closed.

**Comment by Cameron653** [comment]
I'll do a quick test later to see if this is resolved. If so, I'll go ahead and close this.
