### ISSUE TITLE
Atmos Firesuits are missing their helmets

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5722]
#### Brief description of the issue
The atmospheric technicians lockers spawn with their firefighter suits, except that they don't come with any helmet like they (probably) should come with. 

#### What you expected to happen
The firefighter outfit to be a full set, including a helmet.

#### What actually happened
It's just a nice looking firefighter suit with no helmet, you have to make duo with a regular hardhat

#### Steps to reproduce
- Open any atmos-tech locker. That's it.

#### Code Revision
- 4538389237f9e51dda94af66869ed0481d3317da
 
#### Anything else you may wish to add:
- Might not actually be an issue, depending on if there are dedicated helmets for that outfit or not. Also not a pressing issue since who actually uses those over atmos voidsuits.

**Comment by Rykka-Stormheart** [comment]
I'll look into it - that's likely a mapping issue, but priority is pretty low, since atmos voidsuits are also readily available at that point.

Thanks for reporting it! <3
