### ISSUE TITLE
Copy Slot copies NIFs to new character slot

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#5758]
#### Brief description of the bug
When you copy slot to another using Copy Slot function, it also carries NIF over, when its meant to only be tied to specific slot

#### What you expected to happen
All player-inputted character info to transfer, but NIF state to remain same as on the slot its copied over

#### What actually happened
NIF info copied over

#### Steps to reproduce
- Copy Slot with character that has NIF
- Paste into slot that doesn't have NIF and never been played
- Have a NIF

#### Code Revision
- 4538389237f9e51dda94af66869ed0481d3317da

**Comment by Wickedtemp** [comment]
This is actually extremely interesting and kinda cool, even if it is a rather big-ish bug

**Comment by Heroman3003** [comment]
Still a thing.
