### ISSUE TITLE
No Air Alarms for Fish Farm

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#5768]
#### Brief description of the bug
On the tin

#### What you expected to happen
Have air alarms covering virtually every room

#### What actually happened
Nope.

#### Steps to reproduce
- (Step 1) Drill outside from Fish Farm
- (Step 2) Watch as alarms go off to the stairwell
- (Step 3) Make engineers cry as they have to scrub everything.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Rykka-Stormheart** [comment]
Should be resolved by #5769
