### ISSUE TITLE
Can’t make SMES machines.

### ISSUE THREAD

**Issue by Waismuth** [VOREStation/VOREStation#578]
Can’t make SMES machines.

#### Brief description of the issue
While I was messing around in the construction area, I wanted to make a SMES machine. After making the frame and adding the circuit board into it, I add cables yet it still says “30 cable pieces needed” despite the fact I already inserted them. Also, it only takes 5 cable pieces, that’s why there are cables sticking out of the frame. 

#### What you expected to happen
To make a proper smes.

#### What actually happened
Can’t insert cables and finish the smes

#### Steps to reproducer
Make a machine frame with 5 metal pieces, screw it in place, add the smes circuit, and fail putting all 30 cable pieces in.

**Comment by Eearslya** [comment]
I believe this is actually part of a larger bug, as well. It seems like every machine frame that requires cable coils is having this same problem.

**Comment by Cameron653** [comment]
This has been fixed by polaris PR https://github.com/PolarisSS13/Polaris/pull/2509 two days ago.

We're on code from 4 days ago, so next sync will fix this

**Comment by SpadesNeil** [comment]
Oh good.
