### ISSUE TITLE
[BUG] Slimes still capable of pushing you

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5780]
#### Brief description of the bug

Got pushed into the grille, by slime, hand burned severely and then died to slime.

#### What you expected to happen

Not be pushed - patch stated this was fixed

#### What actually happened

You feel a powerful shock course through your body!
Your left hand burns badly!

**Comment by Heroman3003** [comment]
Were you on help intent when this happened?

**Comment by Rykka-Stormheart** [comment]
> Were you on help intent when this happened?

Nope, disarm/harm, I forget exactly which. I also had my slime baton in hand, because I was entering a cell with 3 active grey slimes, I had just tamed - or so I thought.

**Comment by SpadesNeil** [comment]
Are you talking about this https://github.com/VOREStation/VOREStation/issues/5773 or something else?

By the sounds of it you're referring to a duplicate issue. You should re-open the original issue, or at least link it here if you can't because it was closed.

**Comment by Rykka-Stormheart** [comment]
> Are you talking about this #5773 or something else?
> 
> By the sounds of it you're referring to a duplicate issue. You should re-open the original issue, or at least link it here if you can't because it was closed.

Something else. That's related to prommies. This is just +any+ organic gets pushed by slimes, once again. Still happening. We just had another person nearly die again from it.

**Comment by TheToaster98** [comment]
I can confirm, got pushed into the electrified grill by the slimes repeteadly, a lot of times, I was on help intent and the slime were pacified.

**Comment by Heroman3003** [comment]
@Rykka-Stormheart, that part of behaviour is intentional. Slimes never were and never were meant to be swappable with on ALL intents. The change just made swapping with them work same way it does with humanoids. Which means that if you're on help, you will swap and if you're on disarm/grab/harm, you will push them/they will push you (depending on who's bumping).

@TheToaster98, to clarify. Was that before or after most recent patch?
