### ISSUE TITLE
[BUG] Shuttle is horrendously loud

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#5782]
#### Brief description of the bug
The new shuttle is loud to the point of being painful, forcing people to mute the game unless you want that sweet tinnitus.

#### What you expected to happen
-Start shuttle jump.
-Jump.
-Not suffer physical pain from the sound.

#### What actually happened
-Start shuttle jump.
-Jump.
-Take your headphones off because is way too loud.
#### Steps to reproduce
- *Click on destination*
- **VVVRRRRRRRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMM**

#### Code Revision
Server revision: release - 
93abbf176a4aa923f37ede29dea39343d0723e41 
 
#### Anything else you may wish to add:
Nothing.

**Comment by TheFurryFeline** [comment]
Wasn't this fixed and attributed to multiple sound tracks playing at the same time?
