### ISSUE TITLE
New stomach pump feature is secretly dialysis

### ISSUE THREAD

**Issue by Burrito-Justice** [VOREStation/VOREStation#5788]
#### Brief description of the bug
Stomach pumps are a neat addition to the sleepers. Sadly they drain both the stomach and the bloodstream of chemicals instead of just the stomach.

#### Code Revision
401eb129d393d085fec77015696309b8db7c00ff 

#### Anything else you may wish to add:
It's believed that this is the code causing this anomaly:
```
for(var/datum/reagent/x in occupant.ingested.reagent_list)
        occupant.reagents.trans_to_obj(beaker, 3)
        pumped++
```

**Comment by chaoko99** [comment]
fuck
