### ISSUE TITLE
[Bug] Lasertag Turrets have lethal setting

### ISSUE THREAD

**Issue by Brasnak** [VOREStation/VOREStation#5793]
#### Brief description of the bug
The Turret Controls for Lasertag Turrets have an On/Off setting for Lethal Mode.

#### What you expected to happen
To not find a setting labeled 'Lethal Mode' on a lasertag turret.

#### What actually happened
I found said option

#### Steps to reproduce
- Get Lasertag Turret
- Look at turret controls

#### Code Revision
- 401eb129d393d085fec77015696309b8db7c00ff 
 
#### Anything else you may wish to add:
Testing shows it doesn't actually make them lethal or change their behaviour in any way, at the very least.
![2019-09-03_18-51-36](https://user-images.githubusercontent.com/9626555/64194243-eb46d600-ce7e-11e9-9aaf-9d12f42d0385.png)

**Comment by Heroman3003** [comment]
I believe difference between the settings is that 'lethal' ones will shoot even downed players?
