### ISSUE TITLE
Service AI Shells gripper won't let go

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#5829]
#### Brief description of the bug
The AI service shells gripper has some major problems in that not everything it should be able to pick up can be picked up and if it is getting picked up, it can't put them down again without the drop item command

#### What you expected to happen
I can interact with all important bits of the kitchen as a service robot thing like normal, minus the tools that are installed in it.

#### What actually happened
All the important bits are now on the floor cause that's the only way I can reasonably store them without climbing on tables all day.

#### Steps to reproduce
- Spawn as AI
- Get an AI shell build or spawn one
- Go to the kitchen with it, try to cook like normal
- The beakers you use for blending and mixing cannot be picked up, if you manage to pick something up (flourbag for example) you cannot put them on a table when you are done with them. Gotta drop it on the floor.

#### Code Revision
- 3b0b516d9042e7251a7283837a3b0e10d5bcddb6 
 
#### Anything else you may wish to add:
- Might not be limited to the AI shell. Should check on the service borgs too, just in case.

**Comment by Heroman3003** [comment]
Thats intentional and how gripper is supposed to behave. For borgs and shells both. No hands means struggles like that. As for putting items on table, service module is actually most proficent in that area, as you can use tray to pick up and put food and drinks onto tables.

**Comment by Rykka-Stormheart** [comment]
> Thats intentional and how gripper is supposed to behave. For borgs and shells both. No hands means struggles like that. As for putting items on table, service module is actually most proficent in that area, as you can use tray to pick up and put food and drinks onto tables.

That seems... stupid. And obtuse for the sake of being obtuse.

**Comment by Heroman3003** [comment]
One of key borg disadvantages is lack of hands and inability to manipulate items outside their modules. Grippers are the 'bare minimum' they are allowed to have without rendering some jobs undoable.

**Comment by Huenererschrecker** [comment]
So in order to do basic stuff like making cheese, putting things down ect which should be very much possible with those grippers and probably are possible with other cyborg modules, you want to annoy the players by just straight up causing an inconvenience that is both stupid in design and logic? Why should a cyborg not be able to put an item it can pick up on a table and instead just drop it in the most inconvenient way possible on the floor?
