### ISSUE TITLE
Being able to create Emergency Glass Shutters

### ISSUE THREAD

**Issue by SioxGWolf** [VOREStation/VOREStation#5850]
#### Brief description of the bug
While working as engineering to transform the maintenance hall at the end of the dorms, into a a proper hall, and give it a makeover, first one of my moves, was to remove the maintenance door and replace it, and put in two emergency shutters, one that was already there was an emergency glass shutter. So I wanted to do so, apparently, I can't, without admin help. This should be changed so similarly to normal doors it's possible to make glass varients of emergency shutters, for whatever construction purposes we have, without needing to call in an admin every time. I have no proper idea how difficult it is. But I thought I share it and see if anyone might get on this project.

**Comment by Mewchild** [comment]
Are you sure you were following the steps correctly?
![image](https://user-images.githubusercontent.com/13400422/64912816-08d73380-d6fa-11e9-957a-227a30ad5bc0.png)

**Comment by Very-Soft** [comment]
I was helping out with this, he's talking about making the glass variant, that you can see through. We have those around, but there doesn't seem to be a construction path for them. If you start to disassemble them, no glass comes out, and they become regular emergency shutters.

**Comment by Cameron653** [comment]
Going to slap this with the bug & feature tag. Bug being that glass isn't given when they're deconned, and feature so that the glass variants have a build path.

**Comment by SioxGWolf** [comment]
Any progress?
