### ISSUE TITLE
Unable to tame Gold Slimes

### ISSUE THREAD

**Issue by R1f72r** [VOREStation/VOREStation#5869]
#### Brief description of the bug
Cannot tame gold slimes via any means.

#### What you expected to happen
For the gold slimes to be disciplined when I smack them or tase them

#### What actually happened
They shrugged it off like I was a fool

#### Steps to reproduce
- Breed a gold slime
- Wait for it to do something to be tamed
- Attempt to tame it
- Be sad when it cannot be tamed.

#### Code Revision
- c4cda99ad7b1cb8c22118f156314e7c6e0e4eed0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cameron653** [comment]
Hmm, according to the comment in the code
"description_info = "This slime is immune to the slimebaton and taser, and will actually charge the slime, however it will still discipline the slime.""

So it should discipline them, but I presume there's something going on with the slimebaton not stunning and then just giving up everything after it.
