### ISSUE TITLE
CMO's console should have different programs

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#5870]
The console in the CMO's office in the new medbay starts with the ID card modification program and _doesn't_ start with the suit sensors monitoring program.
As the CMO is denied access to the ID card modification program and, as medbay staff, probably needs to be checking the crew monitor, this should probably be the other way around.

#### Code Revision
release - 
c4cda99ad7b1cb8c22118f156314e7c6e0e4eed0

**Comment by Novacat** [comment]
Those console are mainly supposed to be for the C&C program, which changes alert levels.

However, since it is a modular computer, you can easily just download suit sensors if you wish to use them with that console.

**Comment by chaoko99** [comment]
Just for the record, there are departmental variants of every kind of computer. You can just as easily download the alert program on the computer, or better yet just make a new subtype
