### ISSUE TITLE
People waking up during surgeries

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#5884]
#### Brief description of the bug
During surgeries while sedated properly with anaesthetics pump, people just wake up occasionally

#### What you expected to happen
Full unconciousness for entire duration

#### What actually happened
Keep passing out and waking up

#### Steps to reproduce
- Get sedated
- ..aaaaparently not

#### Code Revision
- d946dbdeec4b5c7656d257e1131f4beff690a9a6 
 
#### Anything else you may wish to add:
- Does not appear to be related to new medbay, as pumps seem exactly same as before?

- Applies to both regular tank+mask and the pump, according to Tinnie

**Comment by Cameron653** [comment]
I believe this is an extremely old bug, as I remember this occurring years back. There's a _very, very, very small chance_ that you'll wake up even while under sedation for ~1 second or so before falling back asleep.

That said, I don't know if it's intended or a bug, and I'm more leaning towards the bug side of things.
