### ISSUE TITLE
Trying to put items into your backpack counts as an attack

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5897]
#### Brief description of the bug
I think everybody is probably sick of activating a BS harpoon or cutting their hands on glass because they "hit" their backpack, right? This bug has gotta go.

#### What you expected to happen
I'd place the item into my bag.

#### What actually happened
It registers as an attack with all the consequences you can imagine.

#### Steps to reproduce
- Just pick up either glass or a harpoon and try to bag them. I'm sure there's other items but these two are the ones i know about.

#### Code Revision
- release - 
d946dbdeec4b5c7656d257e1131f4beff690a9a6

**Comment by Cameron653** [comment]
Marking this needs testing to see the specifics about this. Mainly, if it's an intent based thing, with certain items, or just occurs in general.

**Comment by Very-Soft** [comment]
I know I've seen bluespace harpoons do this a number of times. Never seen this happen for glass, but then I don't usually put glass in my backpack.

**Comment by Very-Soft** [comment]
![it do](https://user-images.githubusercontent.com/24854483/65378236-b78fec80-dc83-11e9-882a-b0bef8772986.png)

was on help intent, put glass into bag, cut hand, put BSH into bag, tried to teleport but failed. Seemed to fail regardless of LOS to the tile underneath the bag, so I'm guessing it's trying to teleport me to my present location, but I'm in the way.. 

Tried glass shards on all the other intents, it either cut my hand and went in the bag, or cut my hand and shattered (deleting itself), which seems a little silly. I'd be more fine with this behavior happening on non-help intents, but help intent tends to imply you're being careful with whatever you're dealing with, and presumably you'd recognize that glass is sharp and be careful!

**Comment by Arokha** [comment]
The glass thing was fixed last year. If the glass is out of your hand after a click, it won't cut you.

I'm working on the BSharpoon.
