### ISSUE TITLE
Vulpkanin Sprite

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#593]
#### Brief description of the issue

The Vulpkanin shows a stray pixel when facing left. And a lot of stray pixels facing right.
https://i.gyazo.com/90b51206dab84418d581b64050f4e2ae.png
https://i.gyazo.com/f3cae5aae273ba382df1f041f293766f.png

#### Steps to reproduce
Well make Vulpkanin character and face left or right.

#### Additional info:
Server revision: release - 2016-09-25

**Comment by SpadesNeil** [comment]
@Poojawa
