### ISSUE TITLE
Change character appearance doesn't work for humans.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#595]
#### Brief description of the issue

You cannot change skin color of humans. Again.
#### What you expected to happen

To be able to edit character appearance so this changes.
#### What actually happened

Nope.jpg
#### Steps to reproduce
1. Spawn a human body.
2. Fun tab -> Edit Appearance
3. It doesn't work.
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/37a1bceed5f344b32e5ed76aff94827c309ff8ba

**Comment by Eearslya** [comment]
Looks like this is a Polaris bug as well. Even in their codebase, I was unable to change the color of a Tajara. Really having a hard time tracking this one down.

**Comment by Arokha** [comment]
Don't use `Change Appearance` anymore, it's garbage and nobody maintained it over the years. Use the normal character setup and spawn your character using `Spawn Character` from the Special Verbs tab. You can customize them far easier using a far more familiar interface.
