### ISSUE TITLE
Tram is A D V A N C E D D A R K N E S S

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5985]
#### Brief description of the bug

Tram is pitchblack and blocks all light, including flashlights

#### What you expected to happen

Tram has lighting and works properly

#### What actually happened

A D V A N C E D
D A R K N E S S
https://gyazo.com/58093ed096c0152b9a9d8b8c136a97ab

Dude, even flashlights don't work lmao

#### Steps to reproduce
- Be on tram
- Lights are not allowed here

**Comment by Very-Soft** [comment]
hmh! That kinda looks like what happens when maps don't initialize their lighting properly.

**Comment by SpadesNeil** [comment]
My understanding is this was a one-off bug due to restarting a controller, and not a typical bug.

**Comment by Heroman3003** [comment]
Lighting subsystem has history with not restarting in some z-levels after MC restart, happened with Underdark before so possibly same occurance but with Central, and affected the shuttle?

**Comment by Novacat** [comment]
Master Controller had to be restarted due to a timer subsystem crash, and unfortunately for some reason the Lighting subsystem is never able to restart properly after an MC restart. This is a confirmed bug, but hard to fix because the cause is in Polaris backend.
