### ISSUE TITLE
No requests consoles in research, cargo, or medical.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#5986]
#### Brief description of the bug
Nobody uses them, but they're handy.

#### What you expected to happen
Not the title. 

#### What actually happened
Title.

#### Steps to reproduce
1) This
2) Bug
3) Report
4) Format
5) Sucks
#### Code Revision
Server revision: release - 
a865b57542af4ee6d4d8cd57f7cd205f814a35e3

**Comment by Rykka-Stormheart** [comment]
...there's RC's?
[Cargo](https://i.gyazo.com/9792998931f9312d5b166f7b0ad0cacd.png)
[Medical](https://i.gyazo.com/37c2a3e12b9c4d8ac95f1c21fe9b9a38.png)
[Research](https://i.gyazo.com/65ed8a876cb85549e5270236e54c2467.png)

**Comment by chaoko99** [comment]
Then for whatever reason, I can't send requests to them.

**Comment by TheFurryFeline** [comment]
Probably a simple mapping issue with the vars not being set with DepartmentType = 2 for requesting supplies. Can take a look.

**Comment by TheFurryFeline** [comment]
Correction: looks like it's been fixed on live. Cargo Bay, Research Department, and Medical Department are all options you can select for requesting supplies.
