### ISSUE TITLE
Alter any mention of Deathsquad / Death Commando in the code.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#60]
Deathsquad are not officially recognized by NanoTrasen, nor are the Death Commandos who are part of it.

I want all mentions of it to be removed or changed to SWAT that can be seen by the players, no matter how rare.

Something like an item path or proc though, I don't care.

**Comment by JoanRisu** [comment]
Ace, I think Polaris changed them to another name already. ouo

**Comment by Arokha** [comment]
They are 'Asset Protection' in Polaris as far as ingame stuff, like their armor and whatnot. I think it still says 'Deathsquad' in the admin spawn menu but only admins see that, and changing that means that we can't merge that part of that file anymore so I'd rather not change stuff only admins can see.

**Comment by Arokha** [comment]
This is already done on all the user-facing content. Like some variables or code comments still say deathsquad. Additionally Bay/Polaris has PRs for this already to change it on everything. Just waiting for upstream to finish it. No sense having an issue since there isn't work to be done on
