### ISSUE TITLE
Add emergency medicine cabinet to Medical

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#600]
#### Brief description of the issue
We've had multiple issues where medbay has been understaffed or chemists are overburdened too early in the round. Similar to how we used to have an emergency supply in the vault, this would greatly assist early round when we lack medical staff.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/900dde68a97b93e85bbcd6f8ccdd4c67dffb736a
 - **Anything else you may wish to add:** CentCom seems to have one of these vending machines already with _all_ the chems. However, it's like 500 units of each chem. Basically this, but nerfed and doesn't regenerate.

**Comment by Sansaur** [comment]
you said you wanted this: Bicaridine, Clonexadone, Dexalin Plus, Peridaxon, Ryetalyn, Dermaline.
