### ISSUE TITLE
Having an underscore in your username affects whitelisting

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#6000]
#### Brief description of the bug
Having an underscore in your username (IE: mr_signmeup) affects fluff items from spawning on your desired key.

#### What you expected to happen
To be given the fluff items I requested.

#### What actually happened
No fluff items spawn in on the approved characters.

#### Steps to reproduce
- Have a username with an underscore ( _ ) in their name. IE; mr_signmeup
-Add them to a whitelist, like fluff items.
-Once the server has been updated, have them spawn in on the character.
-Watch them cry as they miss out on having fluff items all because of an underscore.

#### Code Revision
a865b57542af4ee6d4d8cd57f7cd205f814a35e3
 
#### Anything else you may wish to add:
I AM THE ONLY PLAYER ON THE CUSTOM ITEMS LIST TO HAVE AN UNDERSCORE IN THEIR NAME! AAAAAAA!

**Comment by SpadesNeil** [comment]
So put the names in without an underscore and it works.

This is not a bug. This is just how Byond is.
