### ISSUE TITLE
Add random tips

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#601]
#### Brief description of the issue

It'd be nice if we had a config file "tips.txt" that gave a variety of random tips that players could use to help new players and some old players discover fun things. These things would be stuff that should be general knowledge, not like telling people how to do surgery and shit.

Example: "The chef usually has better food than what the vending machine offers."
Example (for our server): "Playing Security is a good way to get a meal. The station is better off with those pesky criminals in your stomach than in a prison cell. Just try not to get caught, as the company generally frowns on this behavior."

Below is outdated. Ignore.

> #### Brief description of the issue
> 
> Enforcing a rule that straight up says "prey cannot play security" is a dick move and people would be understandably upset about that. Enforcing a rule that straight up says, "micro cannot be Captain" would also annoy people because there's at least a few micros who are actually good leaders.
> 
> That said, it would be beneficial to the station if certain job roles were suggested to behave in certain ways.
> 
> Examples:
> I spawn as Security. By spawning as Security, I get a message: **"Tip: This role is recommended for predator-leaning characters. If you are not a predator-leaning character, you should consider playing another role for a more enjoyable experience."**
> I spawn as an EMT for Medical. By spawning as an EMT, I get a message: **"Tip: Some vore types can be used to heal people of basic damage, instead of digesting them."**
> I spawn as Captain. By spawning as Captain, I get a message: **"Tip: The role of Captain is very important for the station to function smoothly, and so vore is not a main focus. Therefore, willing prey characters who prefer digestion should probably avoid playing this role."**
> I spawn as an Assistant. By spawning as an Assistant, I get a message: **"Tip: The role of Assistant is the lowest ranked role on the station, and you are often seen as expendable by other crew. This role is recommended for prey and switch characters."**
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/900dde68a97b93e85bbcd6f8ccdd4c67dffb736a

Please discuss what other jobs should have for tips. Not all jobs necessarily need tips, but it would be ideal.

**Comment by nightwingthedragon** [comment]
Honestly, I'm not a fan of explaining "This job is FOR predators or FOR prey. I get that you have your personal preferences on the matter, but others don't, and I wouldn't consider it fair to shove messages at them every shift saying "This is what you SHOULD be doing" and so on :P The one for Cap or Med works well, but saying "I recommend..." is probably not the most user-friendly idea.

**Comment by Fevix** [comment]
Other department-head roles (CMO, HOP, QM) should have similar messages as the Captain, perhaps also denoting that other crewmembers are probably reliant on them.

**Comment by Screemonster** [comment]
Head roles already get a notification when they join that they're in a role that is important for round progression.

**Comment by Prawneen** [comment]
I feel like something people really need to be reminded about is, You are the Warden. You are the CMO, HoP or any important role? Don't get digested unless you have a scan?

**Comment by Screemonster** [comment]
Something like /tg/'s "tip of the round" system would be a neat thing to port. That's not really job-specific though, it's just a random piece of advice to anyone in general, which tends to range from useful tips like "turrets constructed with laser tag weapons will automatically target the opposing team", to joke entries like "just fucking get good lmao"

**Comment by FirstSgtDan** [comment]
I rarely ever read anything of the text on-screen after spawning... Why not just use the Wiki to suggest the best jobs for pred/prey/switch instead?

**Comment by JarielEledan** [comment]
I like the idea in general, but att he same time I can agree with people saying "outright going 'this job is more suited for predators' might be a bit user unfriendly.
EMT is quite interesting though, and the rest is quite interesting as well. I agree with Scree 'tip of the round' and honestly we might even want to look into personal 'objectives' like I read some places have to avoid having people just sitting in bar. But I guess that's about other sorts of discussions.

**Comment by Dhaeleena** [comment]
Also, I think everyone no matter if they are Prey switch or predator should play security. Im not gonna lie, Pred Secs are hawt, They are good and make up for good settings. But BUT and this is a bit BUTT, Security needs a certain level of competence, Which lots of predators doesnt reach by being all 'Hurr hurr im a pred sec, i get to be a Diek to everyone'. Anyways what im going with this is that, People should just play what they feel like and see if it fits well. If it doesn't well good luck next role.
Also Dominating someone superior in rank is pretty good ;p
Also that 'Tip of the round' thing sounds neat.

**Comment by CSchlippy** [comment]
I kinda agree with Dhaeleena; My sec character, Amy, has always been kinda switchy and might start leaning prey after the last few rounds she was in. I think having Prey sec is honestly a smart idea, if not because drama, because prey 'IN GENERAL' (aka cannon wise) would be more willing to do things by the book and making sure criminals are allowed to go back to work for minor crimes. They wouldn't sell out their predatory brothers, and maybe even become involved beyond vore with them, but in general, would be more standard sec.

Least that's how I view it; you do what you want. :P On the subject of heads though, I will agree that heads who are prey or switch leaning prey should make certain you are scanned above all else; you do have the right to say in OOC that your job and scan comes first.

**Comment by SpadesNeil** [comment]
> I rarely ever read anything of the text on-screen after spawning... Why not just use the Wiki to suggest the best jobs for pred/prey/switch instead?

Almost no one fucking updates the Wiki and even fewer people read it. :(

Though after discussing this, I think that Scree's round tips would be a very good idea. This is nothing specific, so it exposes people to a wider audience, and it's less user unfriendly if I make suggestions like, "Security is a very good role for predators because blahblahblah" because I'm not excluding prey officers directly.

Though to be completely bluntly honest I want to see less prey security. They're already mostly incompetent. The people who keep doing the role anyway are probably more competent than the edgy cool kids who want to wave around a stun baton and be assholes. If you're going to be an asshole, be an asshole who eats people.

**Comment by Screemonster** [comment]
the way /tg/ does it is they have a .txt file in the config directory and it just picks a random line at roundstart and broadcasts it to the world. (actually two text files, one for serious entries and another for joke entries, and it rolls a 95% chance of showing a serious one)

For our purposes, it might be better to give people tips individually when they join the game. Might even be worth kicking upstream, with a config option to turn the tips on and off for servers that want it, and an option for players to turn it off.

**Comment by SpadesNeil** [comment]
I would like to see this turn into a config file thing, yes.
