### ISSUE TITLE
Can't unbuckle from boat if someone buckles you in

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6014]
#### What you expected to happen
To escape from boat if not restrained and buckled in

#### What actually happened
an in-containable amount of annoyance

#### Steps to reproduce
- have boat
- someone else buckled into boat
- have them buckle you in

#### Code Revision
- release - 
a865b57542af4ee6d4d8cd57f7cd205f814a35e3 

 
#### Anything else you may wish to add:
![B O A T S D O N T G O O N L A N D](https://user-images.githubusercontent.com/24854483/65995811-321af200-e464-11e9-9e0b-92d62052cb85.png)

**Comment by Rykka-Stormheart** [comment]
Boats don't go on land!
