### ISSUE TITLE
Disposal pipes delivery system at midpoint is broken.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#6025]
#### Brief description of the bug
Sending stuff from the asteroid to the surface results in stuff being stuck in an endless loop in the midsection.

#### What you expected to happen
Stuff being able to be sent through disposals from the asteroid to the surface.

#### What actually happened
Around and around they go, for all eternity.

#### Steps to reproduce
-Be a maintenance drone.
-Get yourself to a disposal unit on the asteroid. For example; a disposal unit on asteroid 1.
-Set your tag to atmospherics.
-Climb into disposals and wait for it to activate.
-"WHEEEEEEEEEEEEE!"
-Get caught in the loop de loop of the midpoint.
- https://youtu.be/gTZ91YtKLN4

#### Code Revision
384cb4605e5215564230d2f21e4ddb488e4cca2a 
 
#### Anything else you may wish to add:
N/A

**Comment by Rykka-Stormheart** [comment]
Oh geez, I thought I fixed that, I must've fucked it up. aaaaaaaaaaaaaaaaaa

**Comment by TheFurryFeline** [comment]
This issue's been fixed on the master branch, it seems.
