### ISSUE TITLE
Surface Security barely has any cameras

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#6044]
#### Brief description of the bug
With the new surface security, cameras were not installed to cover it!

#### What you expected to happen
To be able to see surface security from security cameras

#### What actually happened
The lobby and the drunk tank is the only thing I can see!

#### Steps to reproduce
-Go to a camera console.
-Go to security tab.
-Locate camera feeds that mention 'surface security'.
-Only find 2.
-Cry.
#### Code Revision
384cb4605e5215564230d2f21e4ddb488e4cca2a 
 
#### Anything else you may wish to add:
N/A

**Comment by Very-Soft** [comment]
Ah! An oversight. I'll fix it soon!
