### ISSUE TITLE
Tether Midpoint Sky Tiles still call do_skyfall on phased Shadekin

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#6048]
#### Brief description of the bug

Got yoinked to the ground while a phased shadekin and ded

#### What you expected to happen

Be phased, unable to interact but also completely immune to the world

#### What actually happened

Do "move down" and get YEETED into the ground thanks to tether midpoint

#### Steps to reproduce
- Be Shadekin
- Phase
- Go to Tether Station 1 or Surface 3
- Do "move down" or "move up" respectively, watch as you're YEETED at terminal velocity even while phased.

#### Code Revision
release - 
384cb4605e5215564230d2f21e4ddb488e4cca2a 
 
This kinda seems unintended/silly.

**Comment by Novacat** [comment]
This was fixed but the fix has not made it to release yet.
