### ISSUE TITLE
Ladders don't allow for illogical movement anymore

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6054]
Ladders, even when built with admin tools, are not allowing transport if the ladders are not on the same x/y coordinate. When you try to move between them, it tries, but then just moves you next to the ladder you started on.

So! While I know it makes sense from a -logical- standpoint for ladders to only allow movement to a ladder that's on the same x/y coordinate, and I deffo think it should work that way when being built with normal player mechanics (which always has afaik)

Not allowing ladders to move people from one to the other if they're not on the same x/y disallows a lot of good, but technically illogical use, such as moving between floors of a building/ship that aren't actually technically on different Z levels, or other strange use cases.

Like as an example, the Inn on the Martial arts arena I built has an upstairs that is usually accessed by a ladder. But rather than having to upload two maps to simulate a technically correct Z level transition, the upstairs is just hidden away in an inaccessable area to the north of the Inn. 

I've also used ladders to allow people to climb inside of cardboard boxxes, which -can- be used with normal step portals, but that also leads to accidental triggering if you happen to bump into it, which is annoying. Modified ladders work better for strange use cases such as that. 

Ladders used to allow for these things, and with some small modifications can be used for a whole lot of interesting event ideas. Their present state makes them difficult to actually use

Build mode even has a tool specifically for building ladders, that lets you build linked ladders anywhere, 

I'd really like it if this was fixxed, since it makes using ladders for events for safe, optional interactable transitions basically impossible outside of a very specific use.

**Comment by SpadesNeil** [comment]
We could just make a "ladder" that is actually just a teleporter that behaves mostly like a ladder, except it can only be admin spawned, and links to another ladder with a matching tag.

**Comment by Very-Soft** [comment]
> We could just make a "ladder" that is actually just a teleporter that behaves mostly like a ladder, except it can only be admin spawned, and links to another ladder with a matching tag.

Yeh! That was a suggestion I tossed at Ascian the other day. I think it'd be best if they just linked to a target and let the target be anything. That way you could make it be a ladder, or a turf, or anything else.

**Comment by SpadesNeil** [comment]
For the old clown temple level I did exactly that. I had a pair of ladders that transported the players to another part of the map on the same Z-level.

I did that purely to prevent people from cheesing the whole fucking level with mechs, and that one little tweak made it my favorite expedition map ever. I am really sad I can't figure out how to port it.
