### ISSUE TITLE
The planet catches on fire if an unsimulated terrain is mixed with normal phoron terrain

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#6058]
#### Brief description of the bug
If you spawn an unsimulated terrain on the Virgo-3B surface, it'll become mixed with oxygen forever until that terrain is removed. If you ignite something, the entire planet will burn until everything is destroyed by the insane heat.

#### What you expected to happen
For the planet not to completely burn down if that happens.

#### What actually happened
![](http://i.imgur.com/67V8s2j.jpg)

#### Steps to reproduce
- Spawn unsimulated terrain that contains any oxygen on surface.
- Light a match.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/410d56067631f67bf74a322b45fa090a5b958b10
 
#### Anything else you may wish to add:
- This will never actually be fixed. I am only using this issue to demonstrate what a "Null" severity issue is. It's something that should never fucking happen in normal gameplay, and requires an admin to do something that is otherwise impossible.

**Comment by SpadesNeil** [comment]
Closed because the only reason this should ever happen is that an admin or a mapper is a retard.

**Comment by SpadesNeil** [comment]
Closed because the only reason this should ever happen is that an admin or a mapper decides to be a dumbass.

**Comment by KasparoVy** [comment]
Badass.
