### ISSUE TITLE
The gurgle sounds are too loud

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6069]
#### What you expected to happen
gurgle

#### What actually happened
god came down and penetrated my ears with a sound familiar, yet all encompassing, it was a good sound, but it also hurt my ears.

**Comment by Very-Soft** [comment]
I think if they were like, half as loud as they are presently it would be good. Maybe a 1/4th. You still want them to be prominent of course, but yeh, I keep seeing people complaining about it in LOOC and ya, when I ghosted around some people who were DOIN' THE GURGS, I have sound for SS13 turned way down because I think most things are too loud, particularly doors. 

And the gurgle sounds I heard eclipsed even the door sounds. They were pretty loud even to me, and I have SS13 down to 5% volume. So!

**Comment by SpadesNeil** [comment]
Okay I was gonna suggest turning the heckin volume down but you've already done that.

**Comment by Wickedtemp** [comment]
Kinda wish there was a way you could set your own specific 'belly volume'. I like listening to the sounds, I have to turn my volume up a lil for my headphones to actually produce the sound clear enough, which is fine until for example a door opens and FWPSSSSHHH!!! or god forbid an admin-pm.

**Comment by Very-Soft** [comment]
I would adore a setting for it ya

**Comment by Poojawa** [comment]
there's a volume bar in goonchat stuff, but that would be... slightly painful to try and port. I'll see about leveling them out
