### ISSUE TITLE
Large Electronic Assembly missing "open" state sprite

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#608]
#### Brief description of the issue

The large electronic assembly has no "open" state sprite.
#### What you expected to happen

When I crowbar the assembly open, for it to be visible and have an "open" sprite.
#### What actually happened

It turned invisible.
#### Steps to reproduce
1. Obtain electronic machine
2. Crowbar it.
3. Results.
#### Additional info:
- **Server Revision**: Server revision: release - 2016-09-30
  e4c5b15c3cc768cecda281cafd0f0e9dcaa669c2 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  Maaybe increase the amount of complexity possible inside an electronic mechanism? It's the medium sized one.

**Comment by SpadesNeil** [comment]
Can we also get screenshots of before and after?

**Comment by KiraAlitruss** [comment]
![before and after](http://i.imgur.com/mSwmC5S.png)
Before and after. Sorry for the delay.

**Comment by Arokha** [comment]
Pretty sure this was fixed.
