### ISSUE TITLE
Disposals doesn't seem to actually deliver things to the trash pit reliably

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6087]
#### Brief description of the bug
there appears to be a sorting junction blocking the path to the trash pit now when it comes in the wrong way.

#### What you expected to happen
trash go trash pit

#### What actually happened
get stuck in endless loop

#### Steps to reproduce
- be on the bridge
- get camera bug, configure it, disposal it, and watch
 
#### Anything else you may wish to add:
-
![disposals is messed](https://user-images.githubusercontent.com/24854483/67165415-8bcf5780-f352-11e9-9723-c7bb8296a327.png)

I don't know if there's a spot earler on where the tubes end up turned around and going the wrong way or that, but I noticed that when you hit that sorter, you just immediately start going the opposite direction, and end up turned around and back into the same loop again.

Also I'd fix this right now but I gotta work and I don't know how to make a separate PR not conflict with the map edits I already have up and waiting to merge.

**Comment by MrSign** [comment]
#6025 

Already spoke about a familiar issue, dunno if it got fixed or not.
