### ISSUE TITLE
Shrödinger's Glitter Bass

### ISSUE THREAD

**Issue by Brasnak** [VOREStation/VOREStation#6096]
#### Brief description of the bug
The glitter bass's sprite doesn't transition properly from alive to dead.

#### What you expected to happen
For the glitter bass to switch to the dead sprite upon dying.

#### What actually happened
The glitter bass displayed both the alive and dead sprite at the same time.

#### Steps to reproduce
- Catch glitter bass
- Wait for it to die
- Deal with the fact that you created a being that is both alive and dead at the same time

#### Code Revision
- 3f69d0b02ece9ef926a3496893049a02a86956b2 
 
#### Anything else you may wish to add:
![dreamseeker_2019-10-22_19-12-10](https://user-images.githubusercontent.com/9626555/67312278-5fa60900-f501-11e9-8e73-79792f537938.png)

**Comment by TheFurryFeline** [comment]
Duplicate issue of https://github.com/VOREStation/VOREStation/issues/5591
