### ISSUE TITLE
Soft's plans for the Tether

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6122]
So there's been a lot of talk about getting new maps and things like that, and I think that that will be great, particularly and especially if we get map rotation. But a lot of this talk has centered around not just doing things differently, but also making sure we don't repeat the mistakes the tether has made. 

I greatly support these talks, but in the short term, we still have a map to play on now that we are having more and more talks about moving away from. Now. I think the Tether is a pretty good idea, it just stumbles in a few key ways, and that those things can be improved with a little bit of effort.

Okay so I have a lot of ideas of how to make the map better to play SS13 the game on in general, that should hopefully facilitate a better overall experience for us in a variety of ways. And from the top I'd like to say that these are all things I plan to do myself, and in some parts I would really prefer to do myself. I have plans for MUCH of the station, but would prefer to do it one step at a time, so that we can critique the changes as they come along. 

I WANT to hear if you have a problem with something in the map presently or with my ideas for changes, and more than that, I WANT to hear how you think it should be different to support a better play experience with regards to the map.

I've already started working on this plan, but I figured it's probably not the most obvious what the intent is from just looking at what I'm doing. Explaining is in order.

So, a quick and dirty overview before I get around to explanations:

- ~~Move the bridge to Z3 atrium, copy paste  minibridge into space. Put office, visitor, and maint stuff in the free space.~~ (#6149)
~~- Use the space from the minibridge to expand surface security to full functionality.`~~ (#9338)
~~- move mining to space~~
~~- use the open space from mining to expand surface medical to full functionality.~~(#9320)
~~- move the holodeck near the public garden entrance on Z1.~~ (#6198)
- move cargo to Z5
- move exploration to Z5
- move EVA to Z5
~~- move public teleporter to z3~~(#9338)
- find a place to move the AI
- delete Z6 and Z7.
~~- review bar seating area size (Bar is off limits, reserved by Demi)~~

So that said, you're probably wondering why go through all this trouble. Quite simply, the number one most complained about thing on the tether. A large portion of the point of the map's basic concept. The elevator. I do not want to remove the elevator, and I don't think adding MOAR elevators will make them really much less annoying. But making it so that for your general playing, dealing with the elevator is not necessary often.

To do that, I feel like the station needs to be weighted on one side. Most of the stuff should be on one half of the station, so that you have less need to take the elevator to do something simple. I think it's silly to need to go all the way up to medical from the tram to get an implant when we had an until recently -never- used surface medical station. It makes a lot more sense to me for medical to be close to the most active areas of the station, which, in my opinion makes the generally centrally located place of surface medical a much more prime location for medical to be than all the way up on Z7. 

Now take that concept and run with it, apply it to everything. What does each location need to be effective, and fun?

Start with the simple. The Library and the Chapel. Both of these are primarily roleplay jobs. 'Doing your job' as these jobs typically involves running some gimmick within your job space, and for gimmicks to be fun, they need people to be able to discover that they are happening pretty naturally, and ideally for people to come interact with them as a result. But with the locations of these places, there was a pretty serious discover-ability issues, to the point that people almost always turned to begging others to come, or pulling really crazy antics to draw eyes, both of those things are typically pretty annoying to deal with, especially if dealt with regularly. And while neither of those has ever been an especially super popular job choice, I keep seeing people try their little hearts out at those jobs, and then burn out and quit. 

I thought the solution to this was pretty simple: Put the jobs that pretty much rely on people discovering them in places where that's likely to happen. The library was easy, because the abandoned library had been put in a great place for it, so it was really just a matter of trading them. 

The chapel was a little more tricky, and people have rightfully questioned my placement of it. I think that from an IC standpoint, NT probably wouldn't want the chapel to be super prominent. They probably would tuck it away somewhere, It shouldn't be too obvious, a bit out of sight, dimly lit, dusty, but easy to get to from the places people mainly hang out. So I picked a spot that meets all of those criteria, while still putting it in a reasonably high traffic, if less travelled route than just sticking it on a main hallway. But with an easy access point from one of the busiest hallways in the station that also adds more viable vertical access for general use.  

And of course, before that I had the basic job of simply trying to make the surface security and medical locations just, generally useful, if not fully functioning. Mostly because they should be useful, but also to test if people liked using those spots. And while I can't say they've become people's favorites, they certainly do both get very regular use now. The only real complaint I've seen with regard to them is that there's just 2 of each of those departments now, and that can cause some understandable confusion.

So. With the ideas I've already completed in mind, have some explanations for the projects going forward.

### Move the bridge to Z3 atrium, copy paste  minibridge into space. Put office, visitor, and maint stuff in the free space.

This one particularly is the thing I intend to work on next, and would prefer to be the one to actually do this.

So, while not really a thing people have complained about much, and part of the point of the shape of the surface levels, the atrium is SUPER DUPER centrally located. Aaaaand a giant waste of space on 2 of the 3 surface Z levels. Not to say that seeing down isn't neat, because it is, and I don't want to do away with that entirely, but quite simply, I think the bridge, the captain's office and quarters, the hop line, and the meeting room would go great in this space, with some connective maint going underneath it on Z2. I would still want there to be places where you can see down, especially in the corners. But in the Z2 maint I think it'd be great to have a couple of places to climb up and down from, and use drop noms from that don't require building.

Of course, we already have a bridge on Z3, the one designed by heroman. I REALLY REALLY like the design. But I think the orientation and location of it are less good than I'd like them to be. However, the orientation is perfect for going basically where the current bridge is, being as the control room faces north. I'd probably have to flip the meeting room, but I think that that small bridge would go perfectly in space. AND! Being as space is ICly sort of meant to be where trade ships and ships bearing tourists and other such visitors, I thought that having some public offices and a couple of small dorms in there to fill the free space would make sense, and give people who want to be away from the busier parts of the station more public spots that are so low traffic they may as well be private, since that's a concern a couple people have brought to me.

### Use the space from the minibridge to expand surface security to full functionality.
 
Is pretty self explanatory. But the plan is to bring surface security to full functionality before removing the space Zs that main sec currently exists on.

### Move mining to space

So! We're getting/got space mining back, or that was a plan that was being tossed around. And it's been a smidge of a complaint that's been grumbled over occasionally for a long time, that it's weird and annoying that cargo and mining is so split. So. Mining to space! 

At present I'm thinking about having, the new cargo office and the mining airlock , and the little warehouse there would be staying. In part because Cargo's a bit of a social job, and I think cargo might get a bit more business from the surface office if they run it. I was also thinking about giving them a little space for a little shop down there so they can occupy themselves with finding ways to make money. The ulterior reason would be for mining to have a drop off point for their ore that shoomps it up to space, where if you set everything up right before you set out, by the time you get up there you could have your ore already smelting/smelted and ready for you by the time you get there. 

### Use the open space from mining to expand surface medical to full functionality.

Again pretty self explanatory. But the plan is to bring surface medical to full functionality before removing the space Zs that main sec currently exists on.

### Move the holodeck near the public garden entrance on Z1.

The holodeck is usually used for relatively private things. It's a public spot, but it sees little use that isn't small scale and typically just a few friends hanging out. It being pretty secluded seems desirable to me.

### Move Cargo and Exploration and EVA to Z5

Cargo and Exploration would less move, and more just be shifted down, Cargo taking up the space the holodeck used to occupy, and Exploration taking the space the Chapel used to occupy, along with that huge open space that has been reserved for like a year now but that never got used. Eva would likely go near or be attatched to the gateway, closer to exploration. On top of that, connective maints and stuff would be added to make there be more ways to get around all over. All this in preparation for the removal of the upper 2 Z levels.

### Move public teleporter to z3

Since Z5 already has cryo, and the ultimate plan is to remove the upper two Z levels, the teleporter would need to find a new home. THOUGH. I also think the teleporter makes more sense in space, and think Cryo would go pretty well near medical. So. Maybe those will get juggled around.

### Find a place to move the AI

I'm not too sure where the AI would go in all this. I'm personally a fan of putting the AI upload in the command area, and then tucking the AI itself away somewhere, not exactly hidden, but very out of the way and fortified. Possibly still in space? Maybe a little satellite connected to the space side of things?

### Delete Z6 and Z7.

OKAY! So I've mentioned it several times now, down to brass tacks. 

The Tether's main problem is that it's too large, too spread out for what we have in it, and the top two space levels design wise in my opinion, are the weakest links. They're not very well designed for traversing outside of the bare necessities, apart from a couple of newer areas. The surface levels are for the most part great, but they need filling out to see their full potential. I think that if we used the space a little better, filled out the better areas of the station, then we wouldn't need the things on Z6 and Z7. We don't need things to be THAT spread out, and the fact that there's effectively only one reliable way up and down between many important jobs and the surface, where most people actually hang out and play, only highlights the limitations of having half the station on either side of the elevator.

I think that having medical, security, and cargo, jobs that people tend to hang out in, and in general regularly need to return to all be based on one side of the elevator, and having the places people actually hang out and are most likely to do crime and get hurt on separated by the necessity of taking the elevator only makes the elevator super busy, and as such, increasingly annoying. 

Take the stuff that doesn't NEEEEEEEED to be in space, put it on the surface. That fills out the surface levels, which offers better value to the maint labyrinth that is Z2. The more you fill it out, the more access points you have into things from already established, effectively useless maint tunnels within that Z level. Leave the things that need to be in space up there, and you'll dramatically reduce elevator traffic, which in turn, makes the elevator less annoying.

### Review bar seating area size (Bar is off limits, reserved by Demi)

I've talked to Demi about this, but I'll mention it here:

The present bar/kitchen's seating area is, in my opinion too large. Not to say that I have a problem with how many people it can fit, but! That it is its own overflow area. If it's too busy by the bar to have comfy chill times, then you can just move a few tiles north. More than likely there's hardly anyone chatting up there. And if it's too busy THERE! Then you can usually move up to the northern most tables to get quieter times. 

I think this is a problem, because it makes the other public spots that we have, which have people to man them extremely rarely ever used, and makes the station's primary general RP basically exclusively bar RP, or private stuff.

It's inconvenient when the bar is super busy. But if the bar is super busy, and you want a quieter spot to hang out in, in my opinion, you should have to leave that place, and go to a different place. 

As is, the bar gravity is too strong, so places like the cafes (we have 2 of them) almost never see use, because the bar/kitchen seating area can pretty comfortably hold most of the average server population without the chat getting too busy.

---

So. 

That's the plan. There's a general secondary mission that will be to do my best to eliminate dead ends where I can find them. There should be an alternate way out of a place as often as is possible imo. But! These are my ideas. I think if we do these things, at each step of the journey the tether will become a more pleasant place to play this spacemans game that we love, as well as remain a good place to roleplay.

I welcome feedback on this too. As I said above. I WANT YOU TO TELL ME if you think an idea I have is bad. But I also want you to think about it and tell me why. I may not agree with you, and may try to convince you why I think -your- idea is bad. But ultimately I want this map to be a good one for us to play on. 

So let's talk about it.

**Comment by Very-Soft** [comment]
I should also note that I intend to continue doing my map changes step by step, rather than all at once, to allow people to critique the changes as they're made.

**Comment by FoxCalledBox** [comment]
I feel like this is a very needed change that needs to be done. I agree that alot of this is needed I feel though that before any 'major' change goes through maybe get direct opinions from people that main said department for things that could be tweaked in the department or moved about to be more fitting.

I see nothing wrong tho with what you want to go with all this, I'm even going to encourage it as change is good and shrinking down the tether is a much needed thing, the maps just to big in places and just feels empty with how much isn't even used.

**Comment by SpadesNeil** [comment]
If the elevator acted like a normal elevator we'd have a lot less issues, but idk how to do that.

**Comment by Rykka-Stormheart** [comment]
I love the idea of the AI being its own "satellite" in space connected by a singular hallway. A ***fortified*** AI. Hell yeah.

**Comment by SpadesNeil** [comment]
Also I _like_ the labyrinth of Z2. :<

Lots of good hiding spots for predator stuff and other shenanigans.

**Comment by Very-Soft** [comment]
> Also I _like_ the labyrinth of Z2. :<
> 
> Lots of good hiding spots for predator stuff and other shenanigans.

I like Z2 as a labyrinth too, and I'm by no means proposing changing that, but just adding more ways in and out of it. I think Z2 is fantastic, but! Its original design was admittedly a lot less generally useful for traversal than I'd personally prefer. I think that Z2 should basically be a back door into pretty much any of the departments we have on the surface levels, with multiple ways up and down into it with general access, for predator and criminal activity, in addition to being a good alternate path to where you want to go in case the main path is for whatever reason unsuitable. 

I only really intend to add more to that, and would never want Z2 to become straightened out and clean and stuff.

The main change I want to make to Z2 and maints in general is to severely reduce the number of trash piles, and to make sure that they are all over, but not -everywhere-. Anywhere that has a trash pile is a pretty high traffic area, and that severely limits the place's usefulness for just about anything not quite legal.

**Comment by LSommers** [comment]
If Z2 gets more used, and this reduced, would it be at all feasible to increase maint spaghetti elsewhere? 
The feeling of "well, this was _almost_ something during construction" from some of the areas on it is very nice, and the very much labyrinthine tunnels make it ideal for any number of things.

It did always strike me as odd that there wasn't that sort of  thing going on with the other surface levels to that extent.

**Comment by Very-Soft** [comment]
> If Z2 gets more used, and this reduced, would it be at all feasible to increase maint spaghetti elsewhere?
> The feeling of "well, this was _almost_ something during construction" from some of the areas on it is very nice, and the very much labyrinthine tunnels make it ideal for any number of things.
> 
> It did always strike me as odd that there wasn't that sort of thing going on with the other surface levels to that extent.

ABSOLUTELY. We will deffo need more maint in Z5 after all this is done, but there's also space for stuff like that on Z2 as well in the west/northwest. I had been thinking of adding some tunnels over there with a bunch of side rooms and generally very unfinished stuff that's kinda sorta meant to be like 'this is where the construction people snuck off to for breaks while this was being built' or something like that. And have that connect into the 4 wide maint hallway in the west that's otherwise mostly just a super out of the way loot tunnel.

**Comment by JemliRoivas** [comment]
I think it's a good idea.  One of the things about the tether is that it could have a huge amount of people on and still feel empty, so, reducing the size of it will help it feel more populated.

**Comment by ArgobargSoup** [comment]
...Although you're already planning on reducing the asteroid to a single Z-level, I had an idle thought... what about leaving a second level?  A level that doesn't really have anything on it, but has a lot of open space for engineers to play with space construction...

**Comment by Rykka-Stormheart** [comment]
> ...Although you're already planning on reducing the asteroid to a single Z-level, I had an idle thought... what about leaving a second level? A level that doesn't really have anything on it, but has a lot of open space for engineers to play with space construction...

That's still a Z-level the game has to load. It's pointless to do that, honestly

**Comment by Arokha** [comment]
No suggestions on github, BUT, for practical reasons (the fuckton of conversation and typing that went into this ongoing series of changes that have been partially implemented), I'll make an exception!

**Comment by TheFurryFeline** [comment]
Per a recent discussion in dev-general channel, have surmised possible locations for final moves. 

- [ ] AI move - feasible for Surface 3, near Garden 3 access from Pool hallway. 

- [ ] Exploration move - Below Engy near docks.

- [ ] Cargo move - Cargo replaces old Holodeck and empty spot above Grav Generator for mining ops stuff.

- [ ] EVA/Escape Pod move - replace old library.
