### ISSUE TITLE
Loadouts get reset sometimes 

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6131]
#### Description of the bug
This has been happening for a few weeks at least now and I keep seeing people complaining about it. It also happened to one of my characters too. 

It seems to be that the loadout occasionally forgets everything you had except 1 item, which SEEMS to be the earliest one on the list.

I have no idea how to repeat this, as when it happened to me, I had spawned and deleted my CC character a couple of times to set up some event stuff that I couldn't do with admin commands, just like I always do. I made no changes to her on the character setup screen, but when the round reset, I noticed that her outfit was gone, and sure enough, her loadout was reset, save for her accessory, a blue armband.

**Comment by MrSign** [comment]
Multiple people have reported this as an issue. Thankfully, I do not believe I've ever had this occur to me... or maybe I did once. I think I had to reset my Reshari loadout a few weeks back but apart from that, all my main characters that I've played never had to experience a loadout reset.

**Comment by Zeldazackman** [comment]
One lead that I've got is to look at the interactions when someone is cryo'd while they're SSD/not connected actively anymore,as their loadout seems to be missing in the round following when they finally do happen to come back

**Comment by TheDavestDave** [comment]
I keep having it happen to me when the round ends and left to do something else

**Comment by Novacat** [comment]
It seems to be related to going SSD before round ends.
