### ISSUE TITLE
Gateway shutters got broken by recent map changes

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6138]
#### Brief description of the bug
Shutters between gateway room and gateway prep are not linked to buttons, facing wrong direction and called "Cargo Office Shutters"

#### What you expected to happen
Proper shutters

#### What actually happened
Wrong shutter type

#### Steps to reproduce
- Enter gateway prep
- Try to access gateway
- Cry
 
#### Anything else you may wish to add:
- https://prntscr.com/ppwmb0

**Comment by Very-Soft** [comment]
Huh I wonder how that happened. 

I'll fix it with my next map edits since part of that's on Z5 anyway.
