### ISSUE TITLE
Surface Medbay Mapping Issues

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#6139]
#### Brief description of the bug
The surface medbay shutters cannot be opened from the inside; the only button that controls them is behind the reception desk in FRONT of the shutters.

In addition, the surface medbay's lights are all off by default.

#### What you expected to happen
When spawning at the start of the round, to be able to leave my department or see inside it.

#### What actually happened
I was trapped inside until I crawled over the chemistry lab's counter and had to manually turn on the lights for any room I entered.

#### Steps to reproduce
- Spawn at the start of the round as medical, end up in surface medbay.
- Discover nearly all the lights are off.
- Find yourself trapped on the wrong side of the reception shutters.
- Open the chemistry shutters and crawl over the counter in order to escape.

#### Code Revision
- 897b903acb723986d368ccd472e44cac63d66f54
 
#### Anything else you may wish to add:
- NA

**Comment by Rykka-Stormheart** [comment]
Lights being off on Surface Medbay is intentional but being locked in is not.

**Comment by Very-Soft** [comment]
There is a button to open the shutters on the inside, though it's a bit further back than it really ought to be. It's something I'd intended to change. 

And yeah. The lights start off in all the side rooms outside the main hall. It's hardly a trouble to turn them on when you come into a room.

**Comment by Vorrarkul** [comment]
My apologies, I didn't realize it was intentional. I'm used to all the lights being on at roundstart. I still couldn't find the button to open the shutters from the inside, though, I'll give it another look when I can.

**Comment by Very-Soft** [comment]
Yeh! It's along the wall on the left side, though it's spot isn't very good for sure, I just didn't want to put it on the glass, or for it to be mistaken for the button that opens the doors for people leaving after resleeving.

**Comment by TheFurryFeline** [comment]
This one didn't get closed because of a keyword not being used, @Very-Soft
