### ISSUE TITLE
Driders and Webs

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#614]
#### Brief description of the issue

On old code, Driders used to be able to make webs, both tile webs and web clothing items
#### What you expected to happen

To be able to make webbing on either the tile your on [I am aware this was removed] or to make a web straight jacket for RP use
#### What actually happened

I had no such option
#### Steps to reproduce

Make Drider
Spawn as Drider
Try and make webs
Find yourself in a sticky situation, or a not so sticky one as you can't
#### Additional info: release - 2016-09-30
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** Again I am aware this was removed due to spamming, but perhaps a new way to handle removal could be created.

**Comment by Screemonster** [comment]
This wasn't in oldcode for long before it got turned off because assholes were spamming it everywhere.

**Comment by SilverTalismen** [comment]
Yeah, as I recall it was only in for a week, if not less, before it got turned off

**Comment by SariNeruda** [comment]
is it possible to make this a White list only feature?

**Comment by Benemuel** [comment]
Or rather just the clothing part as it was towards the end.

**Comment by Arokha** [comment]
This is one of those things that we had to remove because of the nature of mankind.
