### ISSUE TITLE
RIPLEY Ore Scanners Break

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6144]
#### Brief description of the bug
Install mounted ore scanner, get a RIPLEY's regular ore scanner to not work after removal

#### What you expected to happen
Remove mounted ore scanner, have usual scanner to work fine

#### What actually happened
No outputs with regular scanner. Sad face.

#### Steps to reproduce
- (Step 1) Create RIPLEY
- (Step 2) Install mounted ore scanner
- (Step 3) Give to Miner, have them say RIPLEY come with it anyway
- (Step 4) Remove mounted ore scanner, go out
- Step 5) Use regular ore scanner while out, cry because it doesn't work anymore. :C 

#### Code Revision
Server revision: release - 
897b903acb723986d368ccd472e44cac63d66f54  
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
you could say that this bug makes your mech a 

CRIPLEY...

**Comment by TheFurryFeline** [comment]
> you could say that this bug makes your mech a
> 
> CRIPLEY...

🗞

**Comment by TheFurryFeline** [comment]
Searched on Polaris pr's, don't see a fixing pull but I didn't search thoroughly. Remind me later to check. Too early in the day
