### ISSUE TITLE
Fluff Item removal

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#6147]
Demi told me to post this here.

Not sure where the fluff items are in this, but I was hoping to remove that loyalty implant from my box finally, and the armored colony coat as well.

**Comment by KasparoVy** [comment]
Box define is [here](https://github.com/VOREStation/VOREStation/blob/abe19fb977ab4673942b723c8d7603979ba45adb/code/modules/vore/fluffstuff/custom_boxes_vr.dm#L58), coat define is [here](https://github.com/VOREStation/VOREStation/blob/c9c2dd0d81ddf23626fe273c86ea62fec8736178/code/modules/vore/fluffstuff/custom_clothes_vr.dm#L506)
