### ISSUE TITLE
Sushi made with non-poisonous fish is poisonous.

### ISSUE THREAD

**Issue by Leon9621** [VOREStation/VOREStation#6158]
#### Brief description of the bug
 Sushi made with non-poisonous fish (Acquirable from the pond on-station) is still toxic, as if it were made from carpotoxin.

#### What you expected to happen
Food made with non-poisonous ingredients would not be poisonous.

#### What actually happened
Sushi made from non-carp fish poisoned me in game.

#### Steps to reproduce
- Acquire non-poisonous fish, and acquire filets.
- Prepare and consume sushi made from non-poisonous fish.
- 

#### Code Revision
- 897b903acb723986d368ccd472e44cac63d66f54 
 
#### Anything else you may wish to add:
- I think it's just because the sushi item that's made from carp is the same as the ones made from non-carp fish.

**Comment by Heroman3003** [comment]
There is no non-poisonous fish in the game. Even fish in the pond is poisonous and you need to extract poison or counter it with anti-toxin. Only difference from carp meat is that fish in the pond uses different poison type from genuine carp.

**Comment by Leon9621** [comment]
Why are salmon and perch poisonous? It's good to know it's intentional, at least, but that seems a little odd.

**Comment by TheDavestDave** [comment]
The fish meat is coded to be poisonous, even if the RL fish isn't. Fir sone reason phoron gets to the self contained pond

**Comment by Verkister** [comment]
That is because the code is shit spaghetti and folks just like to defend that crap for some reason instead of fixing it _**until now.**_

**Comment by Leon9621** [comment]
It's not phoron, the fish specifically have a poison in their meat called toxic protein, found here

https://github.com/VOREStation/VOREStation/blob/f70fffc47450d6c7f6d2a1a6155ea2d536aab31d/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm#L57. I understand the logic behind it, I just wish it were clearer in game.

**Comment by SpadesNeil** [comment]
>description = "A weak neurotoxic chemical commonly found in Sivian fish meat."
>Sivian fish

yeetus deletus that from our code
