### ISSUE TITLE
[Suggestion] Make Proteans be the T1000

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6160]
So if they touch/eat someone they can assume their identity and be super scary metal goo monsters from the future. *nod

**Comment by Very-Soft** [comment]
![image](https://user-images.githubusercontent.com/24854483/68095321-683dfe00-fe76-11e9-9ec7-3cc12aa00878.png)

![image](https://user-images.githubusercontent.com/24854483/68095326-6ffda280-fe76-11e9-9fe4-a838f3bd929f.png)

![image](https://user-images.githubusercontent.com/24854483/68095334-755aed00-fe76-11e9-929d-58d5f77bf29f.png)

**Comment by KasparoVy** [comment]
RIP Paul Blart

**Comment by Wickedtemp** [comment]
Iunno how I'd feel about this. The whole "body double" thing has always been a bit uncomfortable to me, even when done via genetics. Its just creepy.

**Comment by Arokha** [comment]
Would be cute, but morphs exist now, so eh! Also that duplication thing is not a big deal on a simple_mob with unfancy icons like a morph, but is a *huge freakin' deal* on a carbonmob.
