### ISSUE TITLE
Sergal language updates are necessary

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#6168]
#### Brief description of the bug
https://www.reddit.com/r/SergalLanguage/comments/7ieowo/new_and_improved_sekir_alphabet_phonology/ It's not Sagaru. It's Sekir. I have permission to use this language from the subreddit. https://www.reddit.com/r/SergalLanguage/comments/6z2ywm/anyone_mind_if_i_use_this/ We should include a link to the subreddit on our wiki also once we change the language name.

Furthermore, sergals should no longer growl and snarl, but rather, _merp._ I also want a custom emote for them to audibly merp.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/dbe5a630610098c1fea714a09c0f4a6f68404a0e

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=Tid3aH0S5p0

**Comment by KasparoVy** [comment]
AMEN!

**Comment by SpadesNeil** [comment]
^ Adds merp emote.

**Comment by Screemonster** [comment]
Every time I hear "merp" I remember the time my brother bought this abomination from the local game shop when we were kids and we rapidly found we were in way over our heads https://1d4chan.org/wiki/Middle-Earth_Role_Playing

**Comment by KasparoVy** [comment]
Lmao, the actual acronym for MERP. Nicely done
