### ISSUE TITLE
Uploaded maps relays send comms, but don't receive?

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6174]
#### What you expected to happen
Comms to work on uploaded map with an appropriately configured relay

#### What actually happened
People on the station can hear comms from the away map, but people on the away map cannot hear comms from anyone

#### Steps to reproduce
- Upload map
- Make sure relay is set up properly
- try to use your headset. ; w;

#### Code Revision
- release - 897b903acb723986d368ccd472e44cac63d66f54
 
#### Anything else you may wish to add:
- It's not often a big deal, but on some maps you wanna have comms!

**Comment by ArgobargSoup** [comment]
A fix for this would be appreciated, yah... we had similar problems with recent endo spa events.

...The thing is, this bug seems to be more recent, as earlier endo spa events, we were able to successfully set up comms...

**Comment by Novacat** [comment]
...Suddenly I have a realization as to what is causing this.
