### ISSUE TITLE
Big Burns = Husk = Can't Be Defibbed Even With All Damage Healed

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#6195]
#### Brief description of the bug
So, it's not really a bug, but it's kinda irritating to deal with. Basically if you get badly burnt, IIRC around 240-250 burn, your body will become 'husked'. This causes your sprite to turn grey and look mangled/charred, as a sort of 'burnt beyond recognition'. It also prevents you from being defibbed, even if everything's been treated and you have 0 burn damage and they're completely healthy other than being dead and husked and you still have plenty of time to get the defib off... but can't, solely because of the husk.

Given that the husk value is 250, and with trauma/burn kits alone we can get that down stupid easy, and we can get it down MUCH further with surgery, the ML3M laser, slime-reactions, etc, this.. just kinda gets annoying.

Now, the interesting thing is, husking is actually coded as being genetic. So if you defib someone, they're alive but still husked, a dose of ryetalyn actually clears it right up. So we already have an IC way of fixing the husk-ness IF they're alive. That part's covered.

All we need is to get rid of the bit of code that makes husked crew unres-able. Or scrap husking on burn damage altogether. Or have it instantly go away once the damage is below the husking threshold. Really any of these work, I just kinda want to be able to do Medical-stuff and pull off a save instead of having to do the most boring thing ever and hit the resleeve button.

Plus its impossible to tell if a micro is husked anyway.

**Comment by SpadesNeil** [comment]
Being charred to a crisp sounds pretty reasonably beyond what a defibrillator should be able to fix.

**Comment by Wickedtemp** [comment]
One main issue is, it happens at 250 burn. And we can heal that below 200 on the spot with first aid kits most of the time. Even if the damage is gone and healed completely, there's no way currently to get rid of the Husked status on a corpse.

**Comment by KasparoVy** [comment]
If only there was a way to make the distinction between severe and utterly toasted. Given the context of this logic I feel failure and a 'the [body part] is too mega deep fried to salve!' might make sense.

**Comment by Wickedtemp** [comment]
That would just prevent medical from defibbing people as a whole when it comes to corpses, and would FURTHER limit the uses of an already limited first-aid, and force EVEN MORE reliance on chems. Which is like the opposite of what people in Medical want.

**Comment by KasparoVy** [comment]
Yeah, this is a real predicament imo. Not sure which way to go on it

**Comment by Wickedtemp** [comment]
The amount of damage you can heal is really only limited by how much effort you're willing to put into producing the resources required to heal the patient with. I'm fine with husking being a thing, but if I heal the damage, I should be able to resuscitate the patient. The 250 damage threshold for husking is especially bleh because you can reduce it below 200 with first-aid on its own, without attempting any hat-tricks. 

The 'best' solutions as far as I can tell would be one of the following:
- Allow ryetalyn to work on corpses, which will get rid of the husking status
- Have husking be reversed once the burn damage is below 200
- Remove husking altogether, or remove its ability to stop defibs (since we can fix it once they're alive anyway)
