### ISSUE TITLE
Collar Spawning Borked

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6225]
#### Brief description of the bug
Collars don't spawn in with you if you don't have a tag set.

#### What you expected to happen
Unset tag, spawn blank in round with you either at roundstart or normally through latejoin methods.

#### What actually happened
Never gets attached to your suit or put into your bag.

#### Steps to reproduce
- (Step 1) Select collar in loadout
- (Step 2) Forget to set a tag, or just leave it blank
- (Step 3) Never get the darn thing

#### Code Revision
- release - 
7ac1260fda18f5aa70dd95eb28b5c41fd4972453 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Meghan-Rossi** [comment]
Sorry for the inconvenience.  I'm trying to reproduce this but I haven't been able to.  Does this happen reliably for you?  Any particular type of collar or character that's affected?

**Comment by TheFurryFeline** [comment]
I've had two shifts consecutively where my holocollar didn't spawn and
automatically attach to my suit or into my bag because, apparently, I
needed to have **something** typed into the field and not leave it blank.
Had to ahelp for the item to be spawned in both shifts so it's a bother to
need to remember to change it If/when my char has an inscription change.
This being most common as a result of my playstyle with partners on station.

On Nov 23, 2019 07:45, "Meghan-Rossi" <notifications@github.com> wrote:

Sorry for the inconvenience. I'm trying to reproduce this but I haven't
been able to. Does this happen reliably for you? Any particular type of
collar or character that's affected?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/issues/6225?email_source=notifications&email_token=AJGMTY52QZK4WEGWHUMWPGTQVEQU3A5CNFSM4JQXHGS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7UNSQ#issuecomment-557795018>,
or unsubscribe
