### ISSUE TITLE
Hostile vore mobs don't update sprites properly when dealing with micros

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#623]
#### Brief description of the issue
Due ta the location of a rounding function in the /mob/living/simple_animal/hostile/vore/update_icons() proc, hostile mobs that stuff themselves with micros won't show a belly, no matter how full.

#### What you expected to happen
For a hostile vore mob's gut ta show the heaving mass of micros it just gorged itself with.

#### What actually happened
Flat-bellied monster that decided it wasn't hungry anymore.

#### Steps to reproduce
-Get vore mob.
-Feed with tons of micros.
-Notice lack of belly.

#### Additional info:
 - **Server revision**: master - 2016-10-03
828236fccaea0ff309c7f839b2232ac1081bf210
 - **Anything else you may wish to add**
In "/code/modules/mob/living/simple_animal/hostile/vore/vore.dm", line 65 (as of the time of this post).  The part that rounds the "fullness" value is inside the loop, so each time the loop adds 0.25 to fullness for a micro, it's promptly rounded right back down ta zero.  Thus no belly if the mob's only eaten micros.

**Comment by SpadesNeil** [comment]
```
for(var/mob/living/M in B.internal_contents)
	fullness += M.playerscale
	fullness = round(fullness, 1) // Because intervals of 0.25 are going to make sprite artists cry.
```

I see the problem. `fullness = round(fullness, 1) // Because intervals of 0.25 are going to make sprite artists cry.` should be outside of that for loop.
