### ISSUE TITLE
IDs keep popping out of the tram doors

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#6233]
#### Brief description of the bug
I figure this has gotta be a bug due to how completely inconsistent it is. For some reason, when some people leave, their IDs drop onto the ground above the tram doors (layerwise). This can lead to their accounts being drained among other things depending on the ID, so it's definitely something to worry about for both IC and possible OOC problems!

#### What you expected to happen
ID would leave with the player, per usual.

#### What actually happened
At complete random, it drops to the floor instead.

#### Steps to reproduce
- Sadly since there's no clear rhyme or reason to it, i have no clue how to reproduce the problem besides just watching people leave.

#### Code Revision
- release - 
7ac1260fda18f5aa70dd95eb28b5c41fd4972453

**Comment by Heroman3003** [comment]
To note. This happens with all roundquit methods, not just tram doors. Teleporters and cryo have that issue too.

**Comment by TheFurryFeline** [comment]
As I said before on the discord: from my observations, this happens because an ID/Wallet/PDA containing said ID had been placed in a backpack and when the player's items are despawned along with the char, I've seen said Wallet/PDA/ID drop on top of the teleporter/Tram tiles.

**Comment by TheFurryFeline** [comment]
Tested and confirmed. ID in PDA in backpack = ID left behind in Teleporter.
