### ISSUE TITLE
New bridge conference room is missing access codes

### ISSUE THREAD

**Issue by Brasnak** [VOREStation/VOREStation#6235]
#### Brief description of the bug
Command secretaries can't open the door to the conference room, despite being able to spawn inside.

#### What you expected to happen
To be able to enter and leave the conference room as I please.

#### What actually happened
Get spawned in the conference room during round start and be unable to escape without admin/command intervention.

#### Steps to reproduce
- Ready as secretary
- Get spawned in the conference room
- Weep as you are now imprisoned

#### Code Revision
7ac1260fda18f5aa70dd95eb28b5c41fd4972453 
 
#### Anything else you may wish to add:
![dreamseeker_2019-11-24_15-32-37](https://user-images.githubusercontent.com/9626555/69496259-84aae480-0ed0-11ea-8373-e63ab75da647.png)

**Comment by TheFurryFeline** [comment]
Fixed in the master branch, seemingly.
