### ISSUE TITLE
Mimic Player Race(wip)

### ISSUE THREAD

**Issue by Alcastar** [VOREStation/VOREStation#624]
Mimic Race Idea, A colourful race of slender shape changers that like to hide as containers.

Concept Art:
http://imgur.com/a/hAtoh

I've already made the sprites for both the main body itself as well as a tongue "facial hair" found in this .Zip file.

[MimicRace.zip](https://github.com/VOREStation/VOREStation/files/509667/MimicRace.zip)

They need to be coded however, I'll try to figure it out myself but if someone wants to do so for me it would be appreciated as would be any other suggestions.

current stat suggestion is
human base stats
+increase max hp to 110
-decrease movement speed to 80%
+give an ability that disguises player as a crate, locker and/or other inanimate container object/item.

**Comment by SpadesNeil** [comment]
I dooooon't think this is a good idea.

**Comment by Alcastar** [comment]
Worked well enough in Vcraft when i sat on top of a chest with an invisible skin texture 😜 

people would come up and "accidentally" fall in

But it's up to you as server admin and such.

**Comment by CSchlippy** [comment]
I think this is a good idea o.o and I wish I could have been ate by a chest T.T

**Comment by SpadesNeil** [comment]
I feel like this is a bit too immersion breaking to be considered for adding.

**Comment by CSchlippy** [comment]
Maybe have it as a voremob/admin mob?

**Comment by Screemonster** [comment]
It already is.

**Comment by Alcastar** [comment]
Been about 30 days, closing issue for now :V
