### ISSUE TITLE
Allow players with prosthetic brains to bypass the Encoded Audio Language whitelist.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#626]
#### Brief description of the issue

People with certain synth parts should be able to speak EAL
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/b1b0f289387b7bb0585f63f02d3617bf931bc847

**Comment by SilverTalismen** [comment]
Personally, why not make it so people with specific brains, Posi or Digital can have EAL?

**Comment by SpadesNeil** [comment]
That works. Synth brains can have EAL.

**Comment by SilverTalismen** [comment]
So Posis and the Digital brains could have EAL since it would be programmed in.

**Comment by SpadesNeil** [comment]
Absolutely.

**Comment by Arokha** [comment]
Synths can already speak EAL with no problems, and synths are the only ones who can have posibrains. So this is sort of moot. Maybe there was a bug at the time.
