### ISSUE TITLE
Opening 'solar farm output' on the power monitoring console lags and crashes you

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#6262]
#### Brief description of the bug
As it says in the title, if you make the horrid mistake of opening that tab your game just absolutely hitches up to the point of completely crashing if you don't close out of it in time.

#### What you expected to happen
Absolutely nothing special and it'd work like all other tabs.

#### What actually happened
Absolute gamebreaking despair.

#### Steps to reproduce
- Navigate to either power monitoring terminal in engineering, scan for sensors, scroll down to solar farm output, select it.
- Crash

#### Code Revision
- release - 
7ac1260fda18f5aa70dd95eb28b5c41fd4972453

**Comment by Heroman3003** [comment]
Pretty sure it applies to opening any tab connected to master network before setting up the RCON and not exclusively Solars Output

**Comment by HzDonut** [comment]
Well that's even worse

**Comment by Holdelta** [comment]
I would like to say that this appears to still be occurring on:
Server revision: release -  

f9ed138687ee6ca130a7c11cd3601319e8a03781 

Work around is just using the Power Monitor on the PDA, no lag there.

**Comment by Shadow-Quill** [comment]
Does this still happen with TGUI?

**Comment by Arokha** [comment]
fixed
