### ISSUE TITLE
[Map] Micro Maintenance multi-z wiring is busted

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#6263]
#### Brief description of the bug
In this section of the station's maint, there's some wiring that's supposed to go down to the floor below to hook up to the grid. Sadly, it's not actually connected at all, and thus EVA storage doesn't get any power and drives engineering crazy.

#### Code Revision
- release - 
7ac1260fda18f5aa70dd95eb28b5c41fd4972453 
 
#### Anything else you may wish to add:
- https://gyazo.com/858588adb469079842cc8f2bab09687b the area in question

**Comment by TheFurryFeline** [comment]
Fixed in https://github.com/VOREStation/VOREStation/pull/6223

**Comment by HzDonut** [comment]
Oh, good
