### ISSUE TITLE
Smartfridges/Chemivators don't stock items thrown at them

### ISSUE THREAD

**Issue by Shadow-Quill** [VOREStation/VOREStation#6269]
#### Brief description of the issue
You cannot throw stuff into smartfridges/chemivators and stock them.

#### What you expected to happen
The item to get stocked.

#### What actually happened
It fell to the floor.

#### Steps to reproduce
1) Find chemivator.
2) Yeet item into it.
3) Cry as it falls to the ground and spills your milk.

#### Code Revision
N/A, found on YawnWider.

**Comment by Novacat** [comment]
I am fairly certain this was never an intended feature of Chemavators on this/Polaris codebase?
