### ISSUE TITLE
Stomach Acid tile / effect

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#628]
#### Brief description of the issue

Goonstation has a stomach acid tile, but I want one too, operating differently than theirs.

I want a stomach acid overlay or /effect that acts very similar to how water works in that it goes over the mob and is semi-transparent. However, I want being in these tiles to have certain effects on a mob.
1. The mob starts taking damage at the same rate that digestion would. (2 brute, 3 burn per tick).
2. The mob has a small chance of being stunned and falling over each time they step on a new tile.
3. Clothing will randomly be deleted, starting with suits and headgear, working its way down until just the jumpsuit remains.
4. Items sitting in the acid also eventually get deleted based on a random check every tick.
5. Sizzling noises played to client as you're sitting in the acids.
6. Dead mobs that reach 200 brute damage get gibbed (digested). You'll probably die of oxyloss first, so there's a chance to rescue the body. Simple_animal mobs like Ian should just gib on death since they operate differently.
7. Mobs who have digestion immunity will be undamaged, but the penalty is a much harsher chance of being knocked down when sitting in the acids. They can also still lose clothing.

If someone can code an effect that does this, I can handle mapping it in where necessary.
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/2e5f80175c18f61f6069be489632ae5ee4454de1

**Comment by SpadesNeil** [comment]
I'm debating if hardsuits should protect against acids or not.

**Comment by SilverTalismen** [comment]
The hazmat suits and the RD hardsuit would prolly be best to protect against the stomach acids

**Comment by SpadesNeil** [comment]
Both have bio = 100.

**Comment by SilverTalismen** [comment]
I would say no, since they would protect against the acids and would protect whatever is underneath it

**Comment by SpadesNeil** [comment]
I don't want stomach acids to be completely safe is the thing.

**Comment by SilverTalismen** [comment]
Hmm, Well could it be coded to even wear down the suits and get through?

**Comment by SpadesNeil** [comment]
Not without adding in health to suits, which is really not practical.

**Comment by SilverTalismen** [comment]
Well suits already have a health thing foir getting shot and other stuff, why not use that and figure out how to make it work over a longer period of time?

**Comment by SpadesNeil** [comment]
Do they? When did this happen? Can you point in the code where suit durability is handled? I am not aware.

**Comment by Techhead0** [comment]
Currently only spacesuits have damage vars and whatnot:
https://github.com/VOREStation/VOREStation/blob/release/code/modules/clothing/spacesuits/breaches.dm

**Comment by SpadesNeil** [comment]
Then we fall back to the fact that these suits should be possible to damage even when sealed.

**Comment by CSchlippy** [comment]
In reality, what Spades is saying is practical; you leave a rubber hazmat suit in acid long enough, eventually it IS going to melt apart; chemically speaking, Acid is just water with lots of free hydrogen, which would break the carbon bonds of say plastics, and readily combine to make smaller polymers. Although I don't quite know how acid proof gloves work...

**Comment by Benemuel** [comment]
Well, Not ALL things melt. Metals generally don't unless its the much stronger acids, and a base or calcium will neutralize acids. Hence why bones don't digest really. Unless its ALOT of powerful acid in which case the calcium will bond and not be enough.
