### ISSUE TITLE
Trash-eaters can't digest junk

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#6287]
#### Brief description of the bug
Trash eaters can eat trash and all that, then put it into their vore bellies. That's fine and all, however, trash is not being digested despite all setting in the belly being turned to digest.

#### What you expected to happen
Eat trash, digest trash, aquire nutrients.

#### What actually happened
A tiny junkyard in the belly.

#### Steps to reproduce
- Spawn as a character that has the trash eater trait
- Aquire any kind of trash
- Eat it, set the belly up so that it should digest items, wonder why it's not working.

#### Code Revision
- 07579c8c9792dff4a94a0ebc1d9c69dbabeecea8 
 
#### Anything else you may wish to add:
- This might not actually be a bug that goes for all trash eaters as I experienced that bug with a synthetic custom species.

**Comment by Verkister** [comment]
I believe this happened due to the digestion damages of the belly having been set to 0/0 since those now also affect item digestion rates.

**Comment by Arokha** [comment]
Things digest for meeee.
