### ISSUE TITLE
Mice Unpettable

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6288]
#### Brief description of the bug
You can't pet mice anymore. :<

#### What you expected to happen
Be able to pet mice

#### What actually happened
Nothing. :<

#### Steps to reproduce
Click -> Pick them up
Click + drag to self -> Pick them up
Click in paw = nada
SOB!!!
#### Code Revision
Server revision: release - 
07579c8c9792dff4a94a0ebc1d9c69dbabeecea8

**Comment by TheFurryFeline** [comment]
Seems https://github.com/VOREStation/VOREStation/pull/6243 also fucked with the size of the mouse mobs from tiny to small. They take up more space in bags now on top of not letting people bigger than them be able to pet them.

**Comment by Sebbe9123** [comment]
mice icky, eww dont touch

**Comment by TheFurryFeline** [comment]
Fug you :c

On Dec 13, 2019 05:47, "Sebbe9123" <notifications@github.com> wrote:

mice icky, eww dont touch

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/issues/6288?email_source=notifications&email_token=AJGMTY352JUC55NMONK7B5TQYNR4FA5CNFSM4JZDFV42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGZT3PQ#issuecomment-565394878>,
or unsubscribe
