### ISSUE TITLE
taj fem sprites

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#629]
Providing taj fem/fat sprites as promised in developmentbus like a week or two ago. Eearslya said I should put the link here.

http://puu.sh/rAk6x/df0111a86e.dmi

Will need renaming to `r_tajaran.dmi` , obviously.
My experience with actually compiling them in is limited but from it I know that byond likes to hiccup and lose its ***\* when they are changed or moved at all. So good luck getting them in. :V

**Comment by SpadesNeil** [comment]
Compared to what we currently got, what has changed?

**Comment by DeepIndigo** [comment]
More female features. Fem taj doesn't look like dude taj anymore. Also fat versions of both sexes.

**Comment by Dhaeleena** [comment]
Oh yea finally someone got the Taj female body back. The current one is plain and its literally the same as the male one. This is good. I will see what i can do with this

**Comment by Dhaeleena** [comment]
They seem to work nicely In game. They will look funky after being cloned tho Since there is no _Def_ variant (Deform, From clone damage). Also i need to put it on hold for a bit, They work In game, They look good but it doesn't show up on the Character creation screen and cant figure out whys.

**Comment by DeepIndigo** [comment]
deforms are in another dmi. I didn't bother with fem sprites for them because they;re so twisted up you can't tell the sex

**Comment by Dhaeleena** [comment]
I edited them and made the deform ones, So its all done now.
