### ISSUE TITLE
Translocators Minor Borkage

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6336]
#### Brief description of the bug
Seems that if someone holds a translocator that isn't theirs and they bap a mob with it to teleport into whoever has a beacon in their gut, it just whizzes to their tile instead of said belly.

#### What you expected to happen
All people bapping a mob with the translocator = straight to the beacon.

#### What actually happened
Not the beacon's holder? Sod you, get frakked and watch them get squished by a cow!

#### Steps to reproduce
- (Step 1) Eat a beacon
- (Step 2) Have someone else use the translocator on some mob
- (Step 3) Cry when it doesn't go into your target's gut.

#### Code Revision
- release - 
b9118b58b6d29bb51d679ae55945359c351d97cd 
 
#### Anything else you may wish to add:
- Possible cause: mobs are `Spontaneous vore prey: Disabled` by default.

**Comment by Arokha** [comment]
You can only televore people into yourself. This is intentional. If you want to suggest it be changed, do so on the forums or discord.
translocator_vr.dm:253
```
		if(!target.can_be_drop_prey && B.owner != user)
			to_chat(target,"<span class='warning'>\The [src] narrowly avoids teleporting you right into \a [lowertext(real_dest.name)]!</span>")
			real_dest = dT //Nevermind!
```

**Comment by TheFurryFeline** [comment]
A shame. Thanks for your answer
