### ISSUE TITLE
Mining is boring as sin.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#635]
#### Brief description of the issue

Mining is an absolutely horrible, unrewarding chore compared to what it used to be.
#### What you expected to happen

Head out, find ore and occasional ruins buried in the rock, abandoned crates, ore seams, all that good stuff, actually be worth taking a ripley out.
#### What actually happened

No ruins.
No crates.
Hardly any surface ores worth digging up, hell even phoron is cut in half when you compress it in the smelter so even trekking out to dig _that_ won't net you a decent haul unless you spend the entire shift.
Impossible to even _get_ hematite or coal without using the giant drills, which take three fucking trips to haul out to the dig site and that's not even counting the crate.
Mesons don't find ores any more so it's even _more_ of a chore and you have to choose between the meson goggles and material scanners.
#### Steps to reproduce

Go mining.
Die of boredom.
#### Additional info:

This has been pretty much the case since the polaris port. Pre-polaris mining was fine.

**Comment by SpadesNeil** [comment]
I was at the last staff meeting in Polaris, and improvements to mining were discussed, including the return of abandoned crates, which, no one knows why they broke.

**Comment by Screemonster** [comment]
At least put hematite and coal back on the surface, right now there's no reason to really go exploring the whole asteroid as setting up the drills when you get too far out from the base is a tedious nightmare, and if you want metal and plasteel sheets as a surface miner you're better off just shipping phoron back on the cargo shuttle and _buying_ them.

**Comment by Arokha** [comment]
Crates are back, and the belt is there now.
