### ISSUE TITLE
Gentle hairstyle missing

### ISSUE THREAD

**Issue by InvisPinkUnicorn** [VOREStation/VOREStation#6364]
#### Brief description of the bug
The Gentle hairstyle is unavailable in character setup, and all characters who previously had it have been reverted to Bald.

#### What you expected to happen
The Gentle hairstyle to be available.

#### What actually happened
It's gone. The Gentle 2 hairstyle remains, but it's not the same.

#### Steps to reproduce
1. Have a character who previously had the Gentle hairstyle, or attempt to select it on a new character.
2. Notice how it's gone.

#### Code Revision
b9118b58b6d29bb51d679ae55945359c351d97cd  (live)
 
#### Anything else you may wish to add:
Nada

**Comment by Verkister** [comment]
Apparently they're now both pathed as "gentle" and thus overriding the first one.

**Comment by Verkister** [comment]
fix sent to polaris
