### ISSUE TITLE
Jukeboxes are unhackable.

### ISSUE THREAD

**Issue by cthuloid9** [VOREStation/VOREStation#639]
Issue: You cant open the wire menu on jukeboxes.

What I expected to happen: I expected clicking on a jukebox with its maintenance panel open to open the wire menu.

What happened: Clicking on the jukebox with its maintenance panel open made me hit it with whatever I was holding (wirecutters/multitool).

How to reproduce: Open a jukebox's maintenance panel and click it with wirecutters or a multitool.

Server revision: release - 2016-10-09
d2d9a794d1478758f27bf4e664dda7db7252a988

**Comment by SpadesNeil** [comment]
This should be fixed now.
