### ISSUE TITLE
Crowd control custom suit for sergal or multiple other races not working

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#640]
#### Steps to reproduce: 1 Get security hardsuit. 2 insert suit into suit customization thingy. 3 select sergal or something other then human. 4 select crowd control (Might need HOS or Captain access for this.) 5 Activate. 

_**Server last updated: October 9th, 2016**_

**Comment by BlackjackFajah** [comment]
Right UPDATE: ALL suits for Taurs using sergal race for a base are borked for hardsuit modules and everything else.

**Comment by SpadesNeil** [comment]
Server revision is missing.

**Comment by BlackjackFajah** [comment]
Updated with server update

**Comment by SpadesNeil** [comment]
Close enough. :U
