### ISSUE TITLE
Shuttle engines mess with mapmerge tool

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6401]
#### Brief description of the bug
Engines of shuttle use special code to allow them to move without taking the turf with them, and its coded as second turf on that tile. That however, tends to trip up the mapmerge tool and it unncecessarily creates changes that bloat the diff and lean into unnecesary conflicts.

#### What you expected to happen
Edit one tile. Mapmerging shows diffs only on that tile.

#### What actually happened
Edit one tile. Mapmerging reorders and reshuffles a bunch of shuttle engine tiles because it can't handle multiple turfs.

#### Steps to reproduce
- Edit something on z-level with a roundstart shuttle using the double turfs
- Try to mapmerge it

#### Code Revision
- b9118b58b6d29bb51d679ae55945359c351d97cd 
 
#### Anything else you may wish to add:
- Maybe this could be fixed by adding special exception to mapmerger code or by changing the way the carry code works so that they aren't turfs?

**Comment by Heroman3003** [comment]
Still there

**Comment by Arokha** [comment]
That's an issue with mapmerge, so you would want to open an issue on their repo, wherever that is.
