### ISSUE TITLE
sharkchunk turns into untextured sharkmeat when cut.

### ISSUE THREAD

**Issue by Trexdude** [VOREStation/VOREStation#6402]
#### Brief description of the bug
The item 'chunk of shark meat', or `/obj/item/weapon/reagent_containers/food/snacks/sliceable/sharkchunk`, spawns a 
 `/obj/item/weapon/reagent_containers/food/snacks/sharkmeat`, which is an untextured item called 'snack' in-game, even though it should probably spawn `/obj/item/weapon/reagent_containers/food/snacks/carpmeat/fish/sharkmeat`, which is a textured item called 'slice of sharkmeat.'
I think this is an issue with [https://github.com/VOREStation/VOREStation/pull/6360/commits/15c1c45b342cffb0ed386de90cb53ed32567e136](url) conflicting with the earlier code of the PR.

#### What you expected to happen
Using a sharp object on chunk of shark meat spawns some sharkmeat.

#### What actually happened
Using a sharp object on chunk of shark meat spawns an untextured version of sharkmeat, that for some reason seems to have more protein and nutrient than the textured sharkmeat. Maybe it's the default nutriment values for default snacks.

#### Steps to reproduce
- Use shark object on chunk of shark meat, obtained from butchering or gibbing measel sharks.

#### Code Revision
- 880fe39160f2257eadf18be08b7796cc5858f402
 
#### Anything else you may wish to add:
- I figure I might be able to work on this if ye need help, though I'd need to look into it more. Also this is me first issue I've made, lemme know if I've made any mistakes.

**Comment by Ketrai** [comment]
Heck? I tested it too. I'm assuming I forgot to change the filepath for sharpmeat from chunks when I made it a child of fish meat.

**Comment by Ketrai** [comment]
I'll fix this soon. Just need to fix a few conflicts so I can start a bugfix branch. Thanks for testing the master branch btw. People making prs are only one person at a time. And it's impossible not to miss a few things here and there whilst testing alone.

**Comment by Trexdude** [comment]
Wilco, cheers.
