### ISSUE TITLE
[SUGGESTION] Port southern cross, and add a mapvote.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#6403]
Simply port southern cross from polaris, and add/enable a mapvote.

Why?
- Tether is far too big for lowpop.
- The vote can be overriden by an admin, so if need be they can force the vote to tether at the start of high pop, or end a southern cross round early if no one was online to pay attention.
- It's kinda lame to have the same map each time. Southern cross has a lot of features tether doesn't, so it offers people a chance to explore new stuff, and an incentive for more folks to play during low times.
- Tether is just too isolated in general. It takes ages to get places, important departments are spread apart. Departments are often needlessly big, making it hard to even meet people of the same profession. Less so on high pop, but it's nice to have a more closed in station from time to time.

**Comment by TheFurryFeline** [comment]
As I recall, Northern Star/Southern Cross isn't even canon to Virgo's lore? Also, @Very-Soft has their plans to reduce the size of Tether.

**Comment by lbnesquik** [comment]
This is a lot of effort for the issues we have. Southern has their own issues and would need to be maintained to work with our junk. I think randomizing some sections of tether would be a better, far easier solution to some of those issues.

**Comment by Ketrai** [comment]
@TheFurryFeline I like soft's map changes but a lot has been announced and no progress has been indicated. This wouldn't affect the changes and allow for a tie-over for now.

**Comment by Wickedtemp** [comment]
No progress?

Bruh we literally added an entire medbay to the surface level. An actual medbay instead of the glorified first-aid station we used to have. Chapel's been moved like twice, pretty sure surface-sec got an expansion as well. 

And SC has many issues. Imagine the Tether but its divided between.. the four main departments and command on one section, and then Exploration, Xenoflora and Xenobio, and a few other Sci bits, Mining, on the other section.

And it takes five to ten minutes of sitting in a stupid shuttle just to get there. Double that for a roundtrip. 

Its going to need heavy modification.

**Comment by Ketrai** [comment]
Speeding up shuttles is a code line or two. Besides how is this any different from our exploration? You have to take a shuttle or a gateway far away. Alternatively port boxstation again. It's perfect for smol shifts.

**Comment by Wickedtemp** [comment]
It'd still need a few modifications. It could likely be made to work, though it might be a bit small.

**Comment by SpadesNeil** [comment]
Do you want to port it? I don't.

If someone ports it, it's usable. It's not an issue of canon. The asteroid colony still exists in orbit. It's just used for other things now.

**Comment by SpadesNeil** [comment]
Closing this because it's otherwise another "somebody else do this" issue post. You're welcome to do it, though. It's something I would approve as a PR if you could make it happen.
