### ISSUE TITLE
You can scuff floors so hard they become clean again.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#6410]
#### Brief description of the bug
If you pass over a floor tile enough times, it will eventually become clean again when dirty.

#### What you expected to happen
For fennecian speed not to break the universe of dirtiness. How dare it be possible for tiles to be made clean again?! Every tile on station should be filled to the brim with fennec paw prints.

#### What actually happened
Enough paw prints breaks space and time, causing floor tiles to become clean again.

#### Steps to reproce
1. achieve mad speed.
2. become a fennec.
3. pass over a floor tile long enough for it to become dirty, then keep going until it becomes clean again.

#### Anything else you may wish to add:
This is unacceptable, let me turn the floor into mush.

**Comment by Heroman3003** [comment]
I tried to replicate it locally but it doesn't seem to be happening. No matter how many times I go over maxdirt tile it does not disappear. Any additional info? Specific tile it happened on, or maybe someone cleaned it while nobody was looking?

**Comment by Ketrai** [comment]
> I tried to replicate it locally but it doesn't seem to be happening. No matter how many times I go over maxdirt tile it does not disappear. Any additional info? Specific tile it happened on, or maybe someone cleaned it while nobody was looking?

You have to do it for quite a while (1-2) minutes with a green slime. It happened on the tram tiles.

**Comment by Ketrai** [comment]
And no the tram tiles don't magically clean themselves as it stops or start moving

**Comment by Heroman3003** [comment]
...they actually might. It may be that tiles DO clean themselves of their 'dirt' var, but dirt overlay remains unaffected until the dirt var restores to position where it is high enough that it can affect the overlay, at which point it gets reset back to minimal alpha. So they would clean themselves, but it wouldn't be visible until you dirty them up enough for overlay to change.

**Comment by Heroman3003** [comment]
Gonna need to look into shuttle code, but if it is the way I last remembered, tile's dirtiness would reset, while dirt overlay would remain.
