### ISSUE TITLE
Re-Add Extra AI Status Options (Flowey, Glitchey Flowey, etc.)

### ISSUE THREAD

**Issue by Jwguy** [VOREStation/VOREStation#643]
#### Brief description of the issue
After the Polaris Transfer, several items and options are missing; In this issue, the subject is the extra AI Status options that used to be available, such as the Flowey option.

#### What you expected to happen
I open AI Status menu, and look through the list for Flowey and select it.

#### What actually happened
Flowey is not present.

#### Steps to reproduce
Start as an AI, select AI Status.

#### Additional info:
Server revision: release - 2016-10-10
7657fab851dc0886c2beba788ee4538793ddf08a

**Comment by Screemonster** [comment]
I added these to polaris but after merging 'em for a while it got reverted 'cause licensing.
