### ISSUE TITLE
Taur Laying Sprite Request

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#645]
#### Additional info:

 To be honest it would be a welcome addition. Seeing as its funny as fuck and kinda ruins the moment when a taur lays down on a bed or some shit during a scene. But regardless it would be awesome to see.

Sprites for All types of taurs would be awesome. Wolf would be preferred start.

**Comment by Screemonster** [comment]
This'd require more than just taur sprites. Currently the taur sprites cover the legs below the waist. To make this work, we'd have to hide legs, including hiding the legs of whatever jumpsuit is being worn, so we don't have a lying down taur with a pair of feet sticking out into the tile below.

**Comment by BlackjackFajah** [comment]
Well it would be a extremely welcome addition to those who play taurs seeing as the resting animation is literally the normal sleeping one so you have a massive taur butt sticking up in the air. So I'm hoping someone can do this.

**Comment by lbnesquik** [comment]
Well really, to make this work, you would need to make legs despawn like citadel, which wouldn't be a bad thing to have for taurs in general. Then you could make a special "laiddown" verb/status, or perhaps a copy cat which just changes your icon slightly while making you immobile. It still wouldn't fix taurs having their butts in the air however. It's probably more trouble than it's worth.
