### ISSUE TITLE
Plant Analysers don't show recent changes

### ISSUE THREAD

**Issue by feathowl** [VOREStation/VOREStation#6450]
#### Brief description of the bug
A recent addition added whether a plant produced spores (And other effects among others. Spore is the most noticeable) However, plant analysers don't describe if this could happen. I believe other recent changes also are unreported (Haven't specifically confirmed it though)

#### What you expected to happen
The plant analyser to show if a plant would produce spores.

#### What actually happened
Plants that produced spores had no listing when analysed.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)
Obtain exotic seeds from Cargo or Exploration.
Modify seed to room light and temperature levels.
Plant seeds and wait for it them grow.
Spores are visible clouds, so observe the seeds for what produces spores (if any). Scan the plant. It shows no field for producing spores.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
The early January update. No access to the game presently to check version
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I can't remember what the other three alterations to plant genes were, but there was no sign that the output of the plant analyser has changed even though there are additional effects.
Also a suggestion: Plants able to alter the ambient temperature towards what is ideal for them. Gives  a reason to not alter the light and temperature requirements to room-average if you're looking for a plant to warm or cool an area.

**Comment by Ketrai** [comment]
Didn't know this owl played here~

**Comment by feathowl** [comment]
I suppose it's hard to make the connection between Feathy/Peeptweet and
Feath owl .. given the gender differences!

**Comment by feathowl** [comment]
Addendum:
It seems like the latest changes also stopped being able to modify the Potency gene through the Delivery machine. It can still be modified through the floral somataray, but it fails to work (or be easily identifiable) through the isolation and delivery machines.
