### ISSUE TITLE
Fingerprints on Forensic Gear

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6455]
#### Brief description of the bug
A friend of mine DM'd me about fingerprints appearing on an ID card when their char was specifically wearing forensic gloves the whole time. They spawned in with it as well and yet on further testing from them, their prints were found, partially, all over said detective gear.

#### What you expected to happen
No prints because forensic gloves.

#### What actually happened
Partial fingerprints or whole ones on various items on spawned gear while wearing the gloves.

#### Steps to reproduce
- (Step 1) Be Detective
- (Step 2) Spawn in with Forensic Gloves in Loadout
- (Step 3) Find your own prints on your own gear. Wow.

#### Code Revision
- Server revision: release - 
ff00f4280fbdbe5faf91b4328669dfdf8e539d11

**Comment by Arokha** [comment]
That makes sense. Unless you literally wear those gloves for 100% of the time you're off the station, your stuff you show up to work in is going to have your prints on them.
