### ISSUE TITLE
Whitelist will print "OK" to chatbox if you hit "OK" when it informs you that you are not whitelisted for a species.

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#6491]
#### Brief description of the bug

As title, when you hit "ok" it prints "OK" to your chatbox.

GIF:
https://i.gyazo.com/6990c063f74ba812e298a0b0e31bf51a.mp4

**Comment by Leshana** [comment]
OK

**Comment by Arokha** [comment]
OK
