### ISSUE TITLE
Sol Common and Pan-Slavic can't be spoken with the hotkeys

### ISSUE THREAD

**Issue by Wrackbang** [VOREStation/VOREStation#6540]
#### Brief description of the bug
If you speak Sol Common or Pan-Slavic with the hotkeys, instead of hearing your words as normal, you instead get the syllable set as if you can't understand it. Also, I've been told on live that other speakers of those languages get the same problem when listening to you.

#### What you expected to happen
To be able to understand myself if I use a speech hotkey instead of setting default language. 

#### What actually happened
I can't understand the words as they leave my mouth, and the two languages shift to using the same syllable set. 

#### Steps to reproduce
- Be someone who speaks Sol Common, Pan-Slavic, and some other language
- With Galactic Common as the default, say something in each of theses other languages using the hotkeys
- Notice how Sol Common and Pan-Slavic are unintelligible and your third choice is not (I tested against Daemon, Sign, Siik, Gutter, and Tradeband - all appear normally)

#### Code Revision
ff00f4280fbdbe5faf91b4328669dfdf8e539d11
 
#### Anything else you may wish to add:
Example of the bug, showing the similar syllables:
Henry Gardner spews, "Ha zencei at or cousoa nuan aning lia pai eve miu" (This is me speaking Pan-Slavic with the hotkey)
Henry Gardner spews, "But not cei at or cousoa kuanher en. Lia pai eve miu" (This is me speaking Sol Common with the hotkey)
Henry Gardner chants, "This is me speaking Daemon with the hotkey"
Henry Gardner growls, "This is me speaking Gutter with the hotkey"

**Comment by SpadesNeil** [comment]
The order of languages has nothing to do with it.

**Comment by SpadesNeil** [comment]
If you set your language to Pan Slavic as the default, you don't actually speak any Pan Slavic.
