### ISSUE TITLE
Warrant Assistant allows security offers to authorize search warrants

### ISSUE THREAD

**Issue by Darlantanis** [VOREStation/VOREStation#6549]
#### Brief description of the bug
Using the laptop/tablet program "Warrant Assistant" allows normal security officers to issue and authorize search warrants during Code Green. As per SOP, only a HoS or CD can authorize a search warrant during Code Green.

#### What you expected to happen
Security officers being unable to authorize search warrants for the warrant projector.

#### What actually happened
Security officers can authorize search warrants for the warrant projector.

#### Steps to reproduce
1. Join as a security officer.
2. Obtain a laptop/tablet and download the "Warrant Assistant" program.
3. Issue a search warrant on any crew (probably yourself if this is a test server).
4. Authorize the warrant.
5. The warrant projector will now state you have a warrant for a lawful search despite said warrant violating SOP.

#### Code Revision
master - 2020-02-08
bd2b049c7452d6441226944cf901337fd3929964
 
#### Anything else you may wish to add:
I imagine either this is an oversight or (if intended) SOP needs updated.

I suppose you could make the argument that players can point out the search warrant is unlawful but having it tied to an in-game item this way (as opposed to player-produced paperwork) is misleading for any players unfamiliar with SOP.

**Comment by Shadow-Quill** [comment]
I've been trying to fix this today in a downstream, but I've been running into an issue about checking if the current ID has hos access

**Comment by TheFurryFeline** [comment]
Fixed with https://github.com/VOREStation/VOREStation/pull/6622
