### ISSUE TITLE
Hungry hungry slimes - request

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#655]
#### Brief description of the feature

Xenobio needs voracious slimes.  Maybe a tweak to the existing slimes, or a VOREStation special replacement.

Slimes need lots of nutriment, right?  Researchers are a good source.  :P 

Ta prevent it from being _too_ dangerous, maybe they could be set ta "drain" mode, and spit people out when they got nothing left to drain.

Or just straight up "absorb" mode, if you want it ta carry some risk.

**Comment by CSchlippy** [comment]
I think absorb/digest mode would be kinda fun. Maybe add an item that digest ok xenobiologists can wear to trigger the difference?
