### ISSUE TITLE
'null - null' Cargo Listing

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#6578]
#### Brief description of the bug
In the cargo console, under the Voidsuit section, a listing with the name 'null - null' shows up. It does not deliver anything.

#### What you expected to happen
Open the console and not see a listing that does not work.

#### What actually happened
The listing shows up anyway and doesn't give anything.

#### Steps to reproduce
- Step up to the cargo console
- Open the cargo console interface
- Navigate to the voidsuits section and open
- Null - Null shows up as the first listing. 

#### Code Revision
ff00f4280fbdbe5faf91b4328669dfdf8e539d11
 
#### Anything else you may wish to add:
This ticket is being made on behalf of a user who dropped us a modmail thread about it.

**Comment by Heroman3003** [comment]
This was fixed in #6584
