### ISSUE TITLE
Forensics Crate in Cargo Listing Gives Forensics Scanner

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#6579]
#### Brief description of the bug
The forensics crate has a forensics scanner, which we do not use anymore. It does not have a sprite.

#### What you expected to happen
Forensics crate gives us the current set of forensics tools.

#### What actually happened
It includes the forensics scanner.

#### Steps to reproduce
- Open the Cargo Console and order the forensics crate
- Open the forensics crate
- Use alt-click to list the items in the crate to see the forensics scanner.

#### Code Revision
- ff00f4280fbdbe5faf91b4328669dfdf8e539d11
 
#### Anything else you may wish to add:
This ticket is being made on behalf of someone who dropped us a modmail about it.

**Comment by JoanRisu** [comment]
Just to be clear, the issue isn't so much that the sprite is missing. The issue is that the forensics scanner is in the crate to begin with.

**Comment by Heroman3003** [comment]
Scanner is functional in and of itself. Its just now functioning entirely separate of the old system, and its basically an 'advanced' tool for forensics.
