### ISSUE TITLE
New pAI chassis sprites!

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#658]
Adds corgi and corgi puppy sprites for pAI chassis!  
http://puu.sh/sfoGX/87d91b5f32.dmi

Will be working on fox and possibly lynx at some point.

~~**EDIT:** It just occurred to me they may not have resting sprites. I'll get on that.~~
**EDIT2, GETTIN' SH*T DONE BOOGALOO:** Replaced link, new one includes rest sprites. They're not fabulous because I'm only an okay spriter, but I think they'll more than do it.

**Comment by SpadesNeil** [comment]
@Arokha wait why was this closed? Were they added in a PR?
