### ISSUE TITLE
Water turfs do not function as water sources

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#6621]
#### Brief description of the bug
Can't fill reagent containers from water turfs.

#### What you expected to happen
Dunk bucket/beaker/sponge into pond, receive water.

#### What actually happened
Not That.

#### Code Revision
5ab3654a447dbaad81c7a8d314663f553984bb4d
 
#### Anything else you may wish to add:
this is unacceptable

**Comment by Leshana** [comment]
YOU don't function as a water source!

**Comment by KasparoVy** [comment]
> YOU don't function as a water source!

Damn RIP, savage 🤣

Just another on the list of issues w/ waterturfs
