### ISSUE TITLE
Unable to interact with any part of the station

### ISSUE THREAD

**Issue by hunterbirk** [VOREStation/VOREStation#6632]
#### Brief description of the bug
Can't: Eat, face direction, hug, use elevator buttons (to call the elevator or tell it which floor to go to), use vending machines, pick up items, open doors.

It seems like the game isn't picking up my mouse at all, except for the fact I can right-click and pick up some things. So close yet so far.

#### What you expected to happen
Left-click with my mouse on a button and making my character push it.

#### What actually happened
Me furiously and frantically clicking everywhere and looking online to no avail why I can't interact with anything.... so nothing.

#### Steps to reproduce
- (Step 1) Open game
- (Step 2) Click on the button

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
You may want to try updating your Byond client to the newest beta, currently 513.1511, from here: http://www.byond.com/download/

**Comment by Very-Soft** [comment]
was working with them in game and this issue was resolved by a pc reboot, so, likely unrelated to our code
