### ISSUE TITLE
Admin rightclick deletion and '

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#6652]
#### Brief description of the bug
Trying to right click delete an item with a ' in it's name deletes any mob named like the part of the item's name before the '

#### What you expected to happen
The item itself to be deleted.

#### What actually happened
Attempting to delete the item named "Red's sword" deleted it's owner instead. Multiple times, and never actually deleting the item itself.

#### Steps to reproduce
- (Step 1) Create an item named "Something's something"
- (Step 2) Create a mob named "Something"
- (Step 3) Right click and try to delete the item.
- (Step 4) Watch each attempt delete any mob named "Something" from anywhere in the world before ever getting to delete the item itself.

#### Code Revision
5ab3654a447dbaad81c7a8d314663f553984bb4d
 
#### Anything else you may wish to add:
- Doesn't really affect regular players unless the bug deletes something affecting them.

**Comment by KasparoVy** [comment]
Lol, wow. I've seen this reliably on other codebases when deleting ID cards since they say "Bob Bobson's ..."

Funny quirk.

**Comment by Arokha** [comment]
I think this is more about how byond parses verbs and less something we can fix. I'm not 100% sure really.

**Comment by Zeldazackman** [comment]
It'll also do it if you try to delete an old sleeve's brain hilariously enough, found that out the hard way when someone asked that their old body (which had fallen and gibbed from freefalling off of Virgo 2 areostat) could have it's gibs and organs removed, it winded up deleting the new, freshly created sleeve that hadn't taken more than three steps out of medical's begrudging embrace.

**Comment by TheFurryFeline** [comment]
Wasn't this fixed already?
