### ISSUE TITLE
"never for this round" doesn't get remembered for corgi runes

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#6681]
#### Brief description of the bug
If someone tries to summon a corgi with a rune and you press the "never for this round" button, it doesn't remember the preference.

#### What you expected to happen
Never to be bothered again that round for corgi runes.

#### What actually happened
got repeatedly asked if I wanted to play a corgi despite clicking never each time

#### Steps to reproduce
- be ghost
- have someone activate corgi rune
- click "never for this round"
- have them activate the rune again

#### Code Revision
- 5ab3654a447dbaad81c7a8d314663f553984bb4d 
 
#### Anything else you may wish to add:
- not tested this with other runes that might exist in the code, I've not been spammed with them yet

**Comment by Heroman3003** [comment]
This bug applies to all the ghost notifications that have no associated 'antag preference'. So for example, it works with positronics and pAIs, because they have dedicated "be X" preference, but for things that do not, it is ignored.

**Comment by TheFurryFeline** [comment]
I'm not sure if this ever got fixed but it's annoying enough to stay up if it hasn't. Shoo, Stalebot.
