### ISSUE TITLE
Vulp Mask Sprites: Busted

### ISSUE THREAD

**Issue by KillianKirilenko** [VOREStation/VOREStation#6692]
#### Brief description of the bug
Cigars, cigarettes, and other similar items are not visible when equipped, regardless of their lit/unlit-ness.

#### What you expected to happen
For cigarettes and similar items to appear when equipped to the mask slot.

#### What actually happened
They don't, whether lit or unlit.

#### Steps to reproduce
- Acquire cigar or cigarette.
- Equip to face slot.
- Note lack of visible unlit cigar or cigarette sprite on mob.
- Light cigar or cigarette.
- Note lack of visible lit cigar or cigarette sprite on mob.

#### Code Revision
- Current?
 
#### Anything else you may wish to add:
- This is an easy fix that I [just took care of downstream](https://github.com/Yawn-Wider/YWPolarisVore/pull/618). Just remove "off" from the states, and add an underscore before "on", to match all the other mask states.

**Comment by KasparoVy** [comment]
States lined up with vulp muzzles are available in Paracode as well if we want to bother species-fitting it

**Comment by KillianKirilenko** [comment]
The sprites should already fit, Para just seems to use a different icon naming convention for smokeables and whoever ported vulps across initially didn't account for that.

**Comment by radar651** [comment]
Yeah it was just a case of wrong names.
