### ISSUE TITLE
New wall terminals still use old construction step sprites

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6723]
#### Brief description of the bug
There were new sprites for wall terminals added, but no sprites for construction steps to come with it.

#### What you expected to happen
Construction steps to resemble final product

#### What actually happened
Old wall terminal all the way till final step

#### Steps to reproduce
- Begin constructing a wall terminal
- See it magically transform into entirely different shape once last step is done

#### Code Revision
- c1e40acb741894a4831765052f5a5b44c78a18df 
 
#### Anything else you may wish to add:
- http://prntscr.com/r9zuuz - example with ATM. Same issue persists with newscaster and request console.

**Comment by Arokha** [comment]
Someone would need to make sprites for them. They're probably 'close enough' for now, though. In looking, I don't even see Bay or others having separate sprites for all these different frames, unless they're hiding in different files.
