### ISSUE TITLE
Can't move immedeately after highlighting something in VChat

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6725]
#### Brief description of the bug
If you highlight something in vchat, you cannot move until you click the game window

#### What you expected to happen
Being able to move around even while having selected something

#### What actually happened
The chat begins scrolling with arrows and character doesn't move

#### Steps to reproduce
- Highlight some text in chat window
- Try moving around
- Click game part of the window
- OK, you're free, but why weren't you earlier?

#### Code Revision
- c1e40acb741894a4831765052f5a5b44c78a18df

**Comment by Arokha** [comment]
Not fixable. Goonchat probably does this too. How can you have something highlighted in one pane (which implies that the pane has focus) but also have the mapwindow focused?

The way we (and goonchat et al.) do it is that once you click, we push focus back to the map pane. If we did that with highlighting, I think you'd likely lose the section you highlighted. Maybe there's some way around that, but I'm not aware of one.

Don't highlight things while also trying to move.
