### ISSUE TITLE
Game noticably has hiccups when chat messages are appearing

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6733]
#### Brief description of the bug
With new chat system, almost every time a new message appears in chat there's a small lag that results from it. Individually not a big deal, but over time it stacks up into feeling of notable lagginess, especially if chat moves a lot.

#### What you expected to happen
Smoothness only affected by overall server lag

#### What actually happened
Hiccup lag from chat

#### Steps to reproduce
- Try walking around in a line for a while
- Notice how there are small lag hiccups every time a new message appears in chat

#### Code Revision
- ae16f6afb928528ed0e3161085c33211be42a6e6

**Comment by Arokha** [comment]
Fixed by rewriting how messages are handled, forgot to mark as fixed in PR.
