### ISSUE TITLE
VChat doesn't keep track of past chat logs after hard crash

### ISSUE THREAD

**Issue by AegisOA** [VOREStation/VOREStation#6734]
#### Brief description of the bug
Playing on-station the past couple months has been fraught with crashes for some reason, and today, merely clicking out of the window to start some music led to a hard crash to desktop. When I came back, the thing Aronai said wouldn't happen in OOC happened: everything chat-related from before the crash was gone.

#### What you expected to happen
VChat keeping track of my chat logs despite crashes to make up for its lack of active log saving.

#### What actually happened
My spicy lewds got thanos snapped.

#### Steps to reproduce
- Play on-station.
- Inexplicably crash back to desktop (or alt-f4, perhaps).
- Join back to have half the chat logs you used to have.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
It does hide messages after a while. Did you get back ANY messages?

**Comment by Heroman3003** [comment]
I am pretty sure it requires it loading messages from previous round, since thats what Hard Crash technically is. Immedeate shutdown and start of new round either right away or shortly after.

**Comment by Arokha** [comment]
They are referring to their client crashing.

**Comment by Heroman3003** [comment]
This was mentioned on git, but I will add this to the issue for proper history: If you attempt to save the log into the file after reconnecting, everything lost will still be lost. So its completely and permanently lost if you disconnected, not just not viewable in client.

**Comment by Arokha** [comment]
Fixed, forgot to mark as resolved in the PR.
