### ISSUE TITLE
Non-black sofas do not refund the steel they're made of

### ISSUE THREAD

**Issue by AegisOA** [VOREStation/VOREStation#6735]
#### Brief description of the bug
I was prettying up the Cargo Office like usual, and when I decided to add in sofas, I saw the new colors that were added in. Opted to choose brown instead of black, only to place the wrong side first. I used my wrench on it, the sound effect played, and it vanished.

#### What you expected to happen
To get back the steel sheet I used on the (brown) sofa third.

#### What actually happened
A miniature anti-matter reaction occurred, and the steel sheet harmlessly imploded without a trace.

#### Steps to reproduce
- Gather some steel sheets and a wrench.
- Build any of the non-black sofa variants, though this occurred first with brown.
- Deconstruct the sofa with your wrench.
- Stare in confusion at the distinct lack of steel on the ground.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
Did you check if black ones do refund it?
