### ISSUE TITLE
Client does not automatically reconnect after server reset

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#6754]
#### Brief description of the bug
At the end of a round, the server loses connection as expected, but doesn't seem to reconnect.

#### What you expected to happen
Client to reconnect on server restart.

#### What actually happened
Chat stopped with the last line saying that the chat would attempt to reconnect you.

#### Steps to reproduce
- be connected at end of round
- get disconnected
- wait

#### Code Revision
-  ae16f6afb928528ed0e3161085c33211be42a6e6 
 
#### Anything else you may wish to add:
- some people might like the wait as it gives them time to save logs before the chat refreshes

**Comment by Arokha** [comment]
This is because the server crashes instead, I think.

**Comment by Arokha** [comment]
Is definitely dependent on whether the server shuts down, crashes, or reboots. Is a byond thing.
