### ISSUE TITLE
[Feature] VChat, make default file name include the date and time

### ISSUE THREAD

**Issue by Tename** [VOREStation/VOREStation#6759]
#### Brief overview of the feature
When exporting log history make the file name include the date and time instead of just being Chat_export. This was included in the old system and was very helpful.

#### What you want to happen
All that I want is in the overview
 
#### Anything else you may wish to add:
https://github.com/Yawn-Wider/YWPolarisVore/issues/634

**Comment by Arokha** [comment]
A limitation in Internet Explorer 9 thru 11 prevents the msSaveBlob filename from containing any numbers. It's a known issue and Microsoft has no intents to fix it. Newer browsers with good HTML5 support don't have this issue, but Byond only allows us to use IE11 at the latest.

I'll try to find a way around it but I am not sure there is one.

**Comment by Tename** [comment]
Is there any possible way that there could be a user preference to revert to the old system?

**Comment by TheFurryFeline** [comment]
> Is there any possible way that there could be a user preference to revert to the old system?

This is exactly something that I'd like for the new system, being able to opt out of it.

**Comment by Tename** [comment]
Thank you!
