### ISSUE TITLE
Uncomfortable assignment of hotkeys

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#677]
#### Brief description of the issue

The use hotkey which was once on the "y" key has been replaced with a not-so useful whisper hotkey.
The whisper hotkey could be easily placed on the c key, v key or b key, which is used for resisting.
It'd come as a much more comfortable hotkey layout for people who use keyboards where their layouts are QWERTZ and not QWERTY.
#### What you expected to happen

I pressed Y and:
expected to towel myself off.
#### What actually happened

I pressed Y and:
it gave me a prompt to whisper.
#### Steps to reproduce
1. Press Y.
2. Be prompted to whisper.
   #### Additional info:
   - **Server Revision**:Server revision: release - 2016-10-22
     6f3cb6bf7b33650a94068197e238f07f546e9567 
   - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
I mean... there was another issue to set the whisper hotkey to Y that we decided was a good idea. And it was Y on the previous codebase for a long time. You can use Z to use the items, too, which is, coincidentally, where Y is on a QUERTZ keyboard.

**Comment by KiraAlitruss** [comment]
It is very uncomfortable.
