### ISSUE TITLE
Morphs and MedicHUD aren't getting along

### ISSUE THREAD

**Issue by AegisOA** [VOREStation/VOREStation#6774]
#### Brief description of the bug
Happened to be ghosting around at some point with MedicHUD active, and I found a person who was playing as... a rather interesting morph. Was apparently a mish-mash of many people, or at least its name of [random letters] implied as much... and its sprite was almost completely hidden by MedicHUD life bars.

#### What you expected to happen
To get to witness this atrocity in all of its glory.

#### What actually happened
I was informed that, yes, it's a very healthy atrocity.

#### Steps to reproduce
- Acquire MedicHUD through some means.
- Find a morph.
- Have the morph attempt to mimic many different people, all of different sizes.
- Marvel in the stack of green bars now standing before you.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- Note, I have very little knowledge of how morphs play mechanically, so maybe something else was happening. All those bars showing up in the HUD, though, was rather fucky.
- The morph: https://i.imgur.com/PibvRmX.png

**Comment by Heroman3003** [comment]
Seems like the bars are just not deleted when appearance changes...

**Comment by Verkister** [comment]
Yeah, seems morphs are having trouble getting rid of the overlays their previous disguises, so al the gear, markings, ears/hairs/tails/etc, and the hud overlays were all sticking on.

**Comment by Heroman3003** [comment]
That aspect is really weird and new, as I am 100% sure it didn't happen when they were originally implemented so its prolly some of the more recent changes that broke it somehow.
