### ISSUE TITLE
Communicators do not show up in call options if you don't fiddle with them a little.

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#6776]
#### Brief description of the bug
When you start a shift, your watch or your nif communicators won't be on the network until you actually mess with it.

#### What you expected to happen
Get a full list of everyone who realistically could be called from the get go 

#### What actually happened
Didn't get it.

#### Steps to reproduce
- Ghost
- Look for someone with a communicator
- See if you can text them. Chances are you can't, thanks to this bug.

#### Code Revision
- release -  58026a3b27d82f3ab4049a4f9295a9abbec89975

**Comment by Arokha** [comment]
That's actually a character preference setting. You can encourage people to enable it, if you want.

![image](https://user-images.githubusercontent.com/15028025/81068893-1884d180-8eaf-11ea-9018-c12c7929d01e.png)

Does that explain it?

**Comment by lbnesquik** [comment]
This is wrong. The setting does nothing. Asked like 4 peoples while ghosting around and they all had to get their nif fiddled with.

**Comment by lbnesquik** [comment]
Still an issue
