### ISSUE TITLE
Bellies you can hide!

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#678]
#### Brief description of the feature

An option for a belly ta make it "hideable"; if option is on, when the description code checks fer filled bellies, it takes a look at the pred/prey sizes and possibly the clothes you're wearin' as well.

Say, you're a normal person and ya ate a micro.  Oh snaps, they aren't big enough ta make a bulge, skip that belly description.

Say ya ate a few micros.  Okay, so ya ate enough people to make a bulge- oh wait, you're wearin' loose overclothes/a tight hardsuit, skip that belly description.

Maybe could even have belly struggle messages depend on the size of the struggler.  No way ta see the poor micro tucked deep away...  :P

**Comment by Very-Soft** [comment]
This is a thing now.
