### ISSUE TITLE
The entire research department is too isolated from the station

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#6781]
#### Brief description of the bug
The entire research department in its current size is like a sovereign nation of its own, and to make the matters worse, it doesn't even have any lobby whatsoever, and is literally connected to the rest of the station by a total of 3 transparent tiles and 3 non-transparent doors. And this is really starting to show psychological effects on the department players.

#### What you expected to happen
A department with a healthy level of interaction and communication with the rest of the station.

#### What actually happened
The entire department is an isolated shame basement and the workers are slowly turning into cave goblins with a private gun factory.

#### Steps to reproduce
- (Step 1) Witness the average round and the behavioral difference between the department and the rest of the crew.
- (Step 2) Look at the hallway in front ot he department entrance and see how it's essentially just one straight solid wall as if it was designed to minimize interaction.
- (Step 3) Get the tickle in your bum that something's definitely not right here.

#### Code Revision
- 58026a3b27d82f3ab4049a4f9295a9abbec89975
 
#### Anything else you may wish to add:
- Just removing this area alone and making the research upper hallway a public area would work wonders. 
![kuva](https://user-images.githubusercontent.com/13697337/76165190-abc6b280-615d-11ea-864b-ad2427756aa8.png)

**Comment by Novacat** [comment]
I also think replacing some of the steel walls with windows in robotics would also work wonders.

**Comment by Verkister** [comment]
Yeah, but it would still need a proper lobby and there's no room for one in the current public hallway, and the current department hallway would be a perfect lobby in relation to the size of the department.

**Comment by Verkister** [comment]
And most of the time the department hallway is currently just used for nothing but a super cluttered "storage area" or ripped down and repurposed into super awkward lab extensions. Other than that it's just another void zone without public access.

**Comment by TheDavestDave** [comment]
they used to have a lobby but no one ever used it. There's little need for science as a department to work with other departments other than a specialist cargo...and cargo has it's own problems with that

**Comment by AegisOA** [comment]
Rarely used but having it as an option is better than not having it at all, especially here. You have no idea how awkward it feels as a not-scientist talking with the folks doing RnD by hanging out in front of their desk... and that requires people actually being in RnD. Otherwise, you're out of luck unless they take you into the department themselves, which has its own problems.

**Comment by TheDavestDave** [comment]
if you replaced the double airlock with the lobby it would be better than it was....we still need to give people a reason to use the lobby and work with the rest of the station

**Comment by chaoko99** [comment]
If I remember correctly, this was brought up a year or so ago and the current layout was the response to this.

Research doesn't need the enormous atrium to function.

**Comment by Verkister** [comment]
The double airlock by itself would be way too small for a lobby. After all the department is **huge** and currently almost completely walled off from the rest of the station. There's literally nothing but a single little windoor in a 3-tile nook just in some random spot along a straight hallway. If the department hallway is made public, then people can finally reach some other areas of the department to contact more specialized staff rather than only have the R&D lab alone to work with. The only excuse they currently have for keeping the hallway access restricted is that it's used as a messy-ass storage room for hazardous stuffs, and frankly i don't like that one at all.

**Comment by Heroman3003** [comment]
I partly blame oversized and separated xenobio in that. Current xenobio could be shrank to less than half its size without losing any functionality and be moved to not be part of sprawling problem with the department.

As for the 'lobby it used to have'. It never had lobby. It had a room with window to outside and that's it. Thats not a lobby.

I really don't like idea of the hallways inside department (any department) being public access and I do think that of all departments, research is in least need of a 'lobby' practicality wise. It'd be nice to have, but current arrangement is already cutting available space rather tight, with making R&D accessible directly to outside aspect that was the main intent behind current iteration.

Reducing isolation would be nice, but definitely *not* by just letting whoever stroll around between the labs. That just sounds bad.

**Comment by Rykka-Stormheart** [comment]
This is resolved by https://github.com/VOREStation/VOREStation/pull/7302
