### ISSUE TITLE
Secondary Command Powernet is not connected to Main

### ISSUE THREAD

**Issue by Trexdude** [VOREStation/VOREStation#6798]
#### Brief description of the bug
The Secondary Command powernet wiring is such that none of the APCs are connected to the main powernet at roundstart.

#### What you expected to happen
Secondary Command's powernet is connected to main, and so charges from the main powernet as all other station APCs do.

#### What actually happened
The APCs aren't connected to the powernet (though are mostly connected to each other), so none of the APCs in secondary command charge.

#### Steps to reproduce
N/A

#### Code Revision
58026a3b27d82f3ab4049a4f9295a9abbec89975 
 
#### Anything else you may wish to add:
Location: Secondary Command.
Secondary Command Office APC isn't connected to the other APCs in Secondary Command, but the other APCs are connected to each other. It can be fixed in-game by wiring from the Central Hallway into Secondary Command, and connecting the Office APC to the grid and the grid to the other APCs.

**Comment by Novacat** [comment]
Fixed on master, just not released yet.

**Comment by TheFurryFeline** [comment]
Yeah, my #6768  fixed this.

**Comment by Trexdude** [comment]
Cheers.
