### ISSUE TITLE
Voidsuits are broken thens to the taurs

### ISSUE THREAD

**Issue by 0Hobo** [VOREStation/VOREStation#681]
Voidsuits fail to be refitted to any race other then the taur one and no matter what race I set it too it will refit to taur, even human

the cycler to Refit to Aluka like I set it

I refited to the Tuar suit

Refit a voidsuit, I used the one in mineing

Additional info:
- Server revision: master - 2016-10-23

**Comment by Cameron653** [comment]
Are you refitting a taur voidsuit or a normal voidsuit?

Taur voidsuits will always fit for taurs and have the taur sprite, no matter what you refit them to be, as they're not meant to be put in the cycler.

**Comment by 0Hobo** [comment]
wow that's unintuitive as fuck

**Comment by 0Hobo** [comment]
ya never mind, it should be set up as an option in the cycler then not be a seprit suit

**Comment by Cameron653** [comment]
Due to how the cycler works (Changing the department simply changes the sprite, and refitting changes what species can use the suit,) it would be harder to code it that way than simply making a voidsuit that checks their taur half and changes the sprite like it currently does.

**Comment by Repede** [comment]
Would it be possible to simply check the subtype in a cycler and block taur subtypes from being placed inside?

**Comment by Cameron653** [comment]
Possibly. I'll fiddle around with it and see if I can get it to work

**Comment by SpadesNeil** [comment]
It should really be made possible for regular voidsuits to be made taur voidsuits.

**Comment by Arokha** [comment]
Ye olden bug. Taurs don't even need taur voidsuits, it's purely for cosmetic purposes if they want the fancier sprites. And we don't have the sprites for any of the types you can't refit the suit for, so nyar.
