### ISSUE TITLE
Space edge transition sometimes leads to surface Zs

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6820]
#### Brief description of the bug
When you're flying around in space as a ghost and hit a border, you get randomly transported to the edge of another station Z. But sometimes that transfers you to the surface maps, and that doesn't seem intentional.

Not 100% sure if this only affects ghosts, but that seems unlikely. I'll test it.

#### What you expected to happen
To not fall from space

#### Steps to reproduce
- fly around in space, hit the borders of the map
- do it a few times
- maybe splat????

#### Code Revision
- release -  

0c0e76c214f6313e61cf7020e50d41ecec33e28e 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
I think it might only affect ghosts? It might be like "Oh I can't put you at the edge of these other zlevels there's a wall there" so it doesn't. Ghosts don't believe in walls though.

Just guessing tho.

**Comment by Very-Soft** [comment]
I tested it with a shadekin flying around with a jetpack and they ended up on Z1, surprisingly unharmed

**Comment by Heroman3003** [comment]
Unharmed is probably exclusively because it ended up being Z1. Seems like someone broke the limitations on where transit edges can actually take you. Normally there is a predefined list on the map datum that on Tether limited it to just 3 spaceside tether z-levels.

**Comment by Arokha** [comment]
Should be fixed now that those levels are marked as sealed.
