### ISSUE TITLE
Shadekin lack the means to travel up and down while phased out

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6821]
### What you expected to happen
To be able to go up or down while phased out!

#### What actually happened
You lack means of travel in that direction.

#### Steps to reproduce
- Be shadekin
- Phase out
- attempt to go up or down

#### Code Revision
- release -  

0c0e76c214f6313e61cf7020e50d41ecec33e28e 

#### Other notes
The infinite energy var for carbonmob shadekin is broken too. Not that big of a problem normally but I noticed it while I was testing a different bug.

**Comment by Very-Soft** [comment]
I should note, this affects carbon mob 'kin, I'm not sure about the AI variants

**Comment by Novacat** [comment]
Should be resolved on master now
