### ISSUE TITLE
Carbon mob shadekin infinite energy var doesn't work

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6857]
#### Brief description of the bug
Doesn't affect things most times, as it's not ordinarily used, but! It's broken so I report

#### What you expected to happen
toggle dark energy infinite to 1, able to phase shift as much as is liked

#### What actually happened
it do nuffink

#### Steps to reproduce
- be shadekin
- open brain's vars
- toggle dark_energy_infinite to 1
- try to phase out and in more than once in a short timeframe

#### Anything else you may wish to add:
- The vars for editing the energy do still work

**Comment by Arokha** [comment]
That var is not checked anywhere that matters. It's checked by a proc that checks if the shadekin has infinite energy, which is only checked one place in a proc it doesn't make sense to check it in.
