### ISSUE TITLE
Bar sign has inconvenient examine text

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#6859]
#### Brief description of the bug
![wat](https://user-images.githubusercontent.com/24854483/76661521-042cf400-6552-11ea-9bb2-e0ad7e7b2349.png)

examining the bar sign fills up your examine box with a bunch of nonsense

#### What you expected to happen
not that

#### Steps to reproduce
- examine bar sign

**Comment by Arokha** [comment]
I made a change in Polaris' vchat implementation that may fix this.
