### ISSUE TITLE
Single white pixel misplaced on Ponytail 6 sprite

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#689]
#### Brief description of the issue

There is a white floating pixel of the ponytail 6 sprite on the South face. 
#### What you expected to happen

There to not be a floating white pixel.
#### What actually happened

There was a white pixel. :V
#### Steps to reproduce
1. Equip Ponytail 6 on a character.
2. Face South.
3. Be disgusted and horrified.
#### Additional info:

*_Server revision: release - 2016-10-22
6f3cb6bf7b33650a94068197e238f07f546e9567 *_

**Comment by Cameron653** [comment]
Fixed via Polaris PR

https://github.com/PolarisSS13/Polaris/pull/2837
