### ISSUE TITLE
Vore catgirl sprite glitches when it eats someone.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#693]
#### Brief description of the issue

When the catgirl eats someone, no matter which of the random sprites it had previously, it changes to the default one with the white shirt and yellow hair. If the prey OOC-escapes, it stays on the default sprite rather than the one it had previously.
#### What you expected to happen

For the cat to not spontaneously change outfit or hair colour upon eating someone.
#### What actually happened

Got pounced by bikini-clad catgirl with black hair. She spontaneously got dressed and bleached her hair. Decided to keep that outfit when I escaped.
Notably, she changed back to the original outfit when I dealt damage to her via the adminpanel.
In unrelated, hilarious news, this caused the other catgirls in the room to immediately turn hostile and I didn't know adminpanel damage did that.
#### Steps to reproduce

Spawn catgirl.
Provoke catgirl.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-10-28
  18c759259bfac8d57f883283c6d2ad5224d71a86

**Comment by SpadesNeil** [comment]
I think I know what is causing this and how to fix it...

**Comment by ArgobargSoup** [comment]
It's the "initial" proc used in the vore mob's sprite update proc.  From the help file...

> This returns the original compile-time value of a variable. It could be used to reset a variable to its default value or to check if a variable has changed.

Thus, fer the catgirls...
`icon_state = "[initial(icon_state)]"`
...is always gonna give ya "catgirl", even if ya set it ta "catgirlbrown" or somethin' in the catgirl's New() proc.

Part of the reason I wrote my own sprite updatin' proc fer my own version of the catgirls.

**Comment by SpadesNeil** [comment]
I fixed this the hard way.
