### ISSUE TITLE
Pause autoscroll doesn't work

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6935]
#### Brief description of the bug
Pausing autoscroll doesn't pause autoscroll

#### What you expected to happen
Button lights up and chat stops moving

#### What actually happened
Button lights up and blinks regularly, while chat keeps getting thrown down to latest message each time a new one appears

#### Steps to reproduce
- Have a sexy ERP post
- Pause autoscroll to read and doublecheck it as you write your own
- Somebody keeps speaking over radio and you keep having to scroll back up for it

#### Code Revision
- 735f447ad4dcd4749163132cd6936f3fa49ade4e

**Comment by Arokha** [comment]
Appears to work currently. Is this still broken for you?

**Comment by Heroman3003** [comment]
Not anymore it seems. The whole "button constantly blinks with milisecond loading icon on cursor' thing is still happening but the chat properly pauses so.
