### ISSUE TITLE
Hyperzine needs a downside.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#694]
Hyperzine has no downsides. Give it something like consistent brute damage over time and lower it's OD rate to five units. That way, it can still be useful without being openly used.

**Comment by zaeperry99** [comment]
Or, alternatively, make it illegal. Or more clearly illegal, if it isn't. To be honest, a bit in Corporate Regs / Space Law outlining what qualifies "Contraband" or what medicine can be given out (Such as Tricord) or can't be given out (Such as space drugs).
But, I fully agree; Hyperzine is currently only used to get an edge on time and other people / security. There's no reason not to get an IV of it watered down and drag it around with you.

**Comment by SpadesNeil** [comment]
Forwarded this to Polaris to see if they are interested.

https://github.com/PolarisSS13/Polaris/issues/2691

However I do plan to nerf it here or at least change the laws surrounding it. Hyperzine is illegal unless prescribed by a doctor, same as literally all other medicine that does something other than just heal you.

**Comment by SpadesNeil** [comment]
Marking as "won't add" because we're not making hyperzine consistently cause damage. However the overdose could be more severe.
