### ISSUE TITLE
The engineering/atmos hardsuit in EVA eats suit slot items

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#695]
**Brass tacks:** Basically, using the atmos/engi hardsuit found on the left rack in the engi part of EVA, deletes your suit slot item (I.E. military coat, labcoat, poncho, armor vest, etc)

**Expected behavior:** Works like anomaly hardsuit, can be worn safely with suit slot items, just goes over them, leaves them alone.

**Observed behavior:** Deploying and toggling it deletes the suit slot item.

**Steps to reproduce:** 
1. Put on the AMI
2. Deploy the suit
3. toggle it and let it do its thing
4. Acquire salt and tears as your spiffy jacket vanishes some time between here and when you remove the hardsuit.
#### Additional info:
- **Server Revision**: Current as of posting this issue
- **Screenshot of item location on map:** http://puu.sh/rYZCs/fc5841e0b7.png

**Comment by SpadesNeil** [comment]
@Cameron653 this is not a bug we created.

**Comment by SpadesNeil** [comment]
I think this is fixed. Feedback?

**Comment by SpadesNeil** [comment]
@Cameron653 
why is @Cameron6531 also a thing also

**Comment by Cameron653** [comment]
@SpadesNeil Due to not being able to make multiple branches w/ the github client for the longest time, I made a shitload of alts so I could have multiple PR's up all at once.

Not too long ago I was able to make multiple PR's using one account, but sometimes it bugs out and I have to use an alt.

**Comment by SpadesNeil** [comment]
I cannot reproduce this bug.
