### ISSUE TITLE
[VChat] DarkMode Does Not Save

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6976]
#### Brief description of the bug
From a player who prefers dark mode, which reportedly does not save its setting upon opening a new client later.

#### What you expected to happen
Dark mode saved

#### What actually happened
Nope.

#### Steps to reproduce
- (Step 1) Switch to dark mode in VChat
- (Step 2) Be done for the day
- (Step 3) Open up a new client.
- (Step 4) AGHHHH! I'M BLIND! ALL WHITE!

#### Code Revision
- [186c8c6e6175e4e70de565546be3a37e6025fa6c]
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
I've not heard anyone else say anything about this. Also reporting on behalf of another player means you're not going to be able to answer any questions about it, like if you have any weird IE plugins installed, if your IE is out of localstorage space, or other things.

**Comment by TheFurryFeline** [comment]
I've actually been able to reproduce this, though. Forgot to mention that bit.

**Comment by Arokha** [comment]
Wait, when you say 'new client', do you mean like on a separate computer?

**Comment by TheFurryFeline** [comment]
> Wait, when you say 'new client', do you mean like on a separate computer?

New client as in New window

**Comment by Arokha** [comment]
Well, what are the steps you use to reproduce it? I'm not able to reproduce this on any machine. Keep in mind that the darkmode setting is saved *in Internet Explorer*, so switching computers or clearing your IE cache or other things will remove it.

**Comment by TheFurryFeline** [comment]
Yeah, exited out of a test server with darkmode on and got dark mode back when I opened a new window. Tried to reproduce it but couldn't. Huh. I've linked the purrson who I made this issue for to your questions about what steps have been taken to apparently and consistently repeat losing dark mode state. Hopefully they'll make a post in this.

**Comment by DrakeSystem** [comment]
It constantly Fails to Save darkmode for me too. no matter how often i check the dark mode setting.
Once i close and reopen the Client(aka new window) its all white again.

**Comment by TheFurryFeline** [comment]
Interesting, since I also don't use IE. And yeah, was you I was opening this for, drake.

**Comment by DrakeSystem** [comment]
Would be nice if i could find out whats causing it.
i doubt its a issue of the code and rather on my end.
So troubleshooting me would be appreciated.

**Comment by Arokha** [comment]
Still have this issue?

**Comment by DrakeSystem** [comment]
Yes this is still ongoing.
and its not only dark mode. any settings for VR chat does not save.
any added tabs or changed settings revert on client restart.
i really think its on my end but i cant figure out why.

**Comment by Arokha** [comment]
It uses internet explorer, so if you have any shenanigans going on with internet explorer... anything that cleans up cookies or localstorage data or plugins that are like 'private browsing' or whatever, they might not allow it to save.
