### ISSUE TITLE
Dust Event Affects Surface Levels

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6977]
#### Brief description of the bug
On the tin

#### What you expected to happen
Dust event to make holes in walls/windows space side

#### What actually happened
Surface also gets a chance to be hit

#### Steps to reproduce
- (Step 1) Dust event triggers
- (Step 2) Surface gets hit
- (Step 3) Phoron Fire ahoy.

#### Code Revision
- [186c8c6e6175e4e70de565546be3a37e6025fa6c]
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Doesn't happen here. Is this from another codebase?

**Comment by Arokha** [comment]
Wait, there's a typo...
