### ISSUE TITLE
Floodlight Cells

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#698]
#### Brief description of the issue
Floodlights spawn with a powercell. They appear and are even pathed as "/obj/item/weapon/cell/high", or a standard high-capacity power cell. But their charge and max_charge vars are 1000, instead of the 10000 that is normal for that kind of power cell.

#### Steps to reproduce
Go crowbar open or VV on a floodlight. Cell is /obj/item/weapon/cell/high, but has 1/10th the capacity.

#### Additional info:
 - **Server Revision**: release - 2016-10-22
6f3cb6bf7b33650a94068197e238f07f546e9567 
 - **Anything else you may wish to add** Verified today 11/1/16 on five randomly selected floodlights, as well as one spawned in.

**Comment by Arokha** [comment]
Was probably for balance so you can't just loot random floodlights and upgrade stuff with their batteries. They should start with the lower power cell though instead of this weird hack.
