### ISSUE TITLE
Vore mobs STILL broken

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#6999]
#### Description of the bug
Just making a post to cover some bugs that're still around but got either lost to time or autodeleted by github, with number two being found by me just today without any issues open that I can see.

1. Bump noms are still non-functional as mentioned in https://github.com/VOREStation/VOREStation/issues/6051
All that happens is they knock you over (if they have a pounce) and the text appears.

2. Feeding yourself to mobs doesn't work even with you and the mob having the necessary prefs (feeding, devourable, etc.).

3. Mobs still don't move upon consuming someone, instead standing totally still until the prey falls into crit/goes to sleep.

#### Code Revision
- release -  
b8c25eb7a6cf151550f40452e1d33150028d92d8

**Comment by Arokha** [comment]
I actually didn't intend to fix the vore part yet. The other AI changes were just to get things into a maintainable state and fix things while I was learning how the new AI system worked. So it's not like things were missed.

**Comment by HzDonut** [comment]
Oh I guess the title is a bit misleading, i didn't mean to imply the AI changes were meant to fix it, just to give a timeframe. I'll fix it now.

**Comment by Arokha** [comment]
They aren't now.
