### ISSUE TITLE
Spamming the "click" on the pen creates mega lag

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#7000]
#### Brief description of the bug
Can't tell if it's clientside or serverside, but it's still pretty worrying.

#### What you expected to happen
It'd just make the noise and things would be dandy.

#### What actually happened
Everything locks up for a bit every click, spamming click makes things get real janky and jittery.

#### Steps to reproduce
- Find a pen
- Mash Z on that MFer
- Perish

#### Code Revision
- release -  

b8c25eb7a6cf151550f40452e1d33150028d92d8

**Comment by Zeldazackman** [comment]
It does it with anything really that can be spammed and stacked with Vchat such as knocking on windows or even better, any swarmer deployables as they have a zero cooldown on knock.
