### ISSUE TITLE
Shadekin can phasenom phased-out shadekin, ignoring mechanical prefs

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#7034]
#### Brief description of the bug
I was a carbonmob shadekin phased out, watching something going on, and another carbonmob shadekin alighted upon the very same spot, although I couldn't see them.  They then proceeded to phase in... at which point I suddenly found myself in their gut, despite still being phased out.

The worrying part was that it happened despite me having "spontaneous prey" to off!

#### What you expected to happen
To be surprised by my fellow shadekin phasing in, and still be in the same place as they walked away.

#### What actually happened
Ended up in my fellow shadekin's gut, despite not even technically being there to be phasenom'd, nor being set as spontaneous prey!

#### Steps to reproduce
- Be a carbonmob shadekin, phased out.
- Have another phased out carbonmob shadekin move to the same spot you're in, and phase in.
- Find yourself in whatever vore belly they had active!

- Optionally, have prefs set so that this doesn't happen, and then watch as it does happen!

#### Code Revision
- Server revision: release -  
29ebb2dae06d772c22a248b980f619d760fa62e2 
 
#### Anything else you may wish to add:
- ...The server *was* having some odd issues at the time, like how digestion apparently wasn't working... decided to report this anyway, just to be safe.

**Comment by Arokha** [comment]
I think I fixed phasenom pref checking a bit ago
