### ISSUE TITLE
Xenobio airlock access

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#704]
#### Brief description of the issue
Xenobio lacks access to the doors of the airlock on the station in science leading to the R&D elevator.

#### What you expected to happen
To have access. We play on extended access.

#### What actually happened
Not having access.

#### Steps to reproduce
Self-explanatory.

#### Additional info:
 - **Server Revision**: Server revision: release - 2016-10-22 6f3cb6bf7b33650a94068197e238f07f546e9567 
 - **Anything else you may wish to add** Map location of outer door: 81,160,1

**Comment by Dhaeleena** [comment]
No longer relevant on the current map.
