### ISSUE TITLE
the lift keep breaking

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#7048]
#### Brief description of the bug
the lift keeps not responding to the buttons that summon it

#### What you expected to happen
the lift to be summoned

#### What actually happened
30mins still trapped in space away from my department

#### Steps to reproduce
- (Step 1) press lift button
- (Step 2) wait for shift to end before the lift appears

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 55a4084b8cddfd8a094906167f35a2e6af5569fa 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
... As I said in the discord, this could just as likely have been a Cleanbot or some other bugger in the doorway. Hell, to fix that issue, let's just make them not move if they're within three tiles of the lift's area.
