### ISSUE TITLE
Morph loses ability to speak, ventcrawl

### ISSUE THREAD

**Issue by piperherring** [VOREStation/VOREStation#7066]
#### Brief description of the bug
Morphs lose the ability to ventcrawl, use /me, and use /say as soon as they transform into anything that's not a mob. Furthermore, when they transform into a playermob, they regain the ability to /say and /me but doing so strips all clothes, hair, markings, tails, etc. off of their sprite, and transforming into an object mutes them once more. Not sure if it's relevant but transforming into a Teshari gave the ability to use the Hide and Agility verbs (so it seems to be copying ... something??? over???)

#### What you expected to happen
Not that

#### What actually happened
That

#### Steps to reproduce
- Crawl into vent
- Transform into anything
- Mourn your loss of the ability to hide in vents

#### Code Revision
a842fb8fc4b182f27d76800dfa6acac65b444072

**Comment by Arokha** [comment]
Fixed
