### ISSUE TITLE
Hitting edge in space causes teleportation to surface z-levels

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7078]
#### Brief description of the bug
When flying around (was ghost when testing, but space edge teleport is handled same for all mobs last I checked) you can teleport from space to surface z-lelvels

#### What you expected to happen
Only other space levels as 'target'

#### What actually happened
Suddenly, planet

#### Steps to reproduce
- Keep running into space edge, expecting to loop around station
- End up on surface levels

#### Code Revision
- 7bfa072d4446ceaabf6a23939957ff1d0ed2885f 
 
#### Anything else you may wish to add:
- Same issue as #6820, so it was not fixed. My suspicion is that it happened because level being sealed has nothing to do with it being potential transit target, but rather map datum has a predetermined list of z-levels that CAN end up as transit targets (or at least thats how it worked pre-overmap, no idea now)

**Comment by Arokha** [comment]
This seemingly only happens when you're NOT in the tether but on the same overmap turf as the tether. So if your excursion shuttle is sitting on top of the tether on the overmap and you touch the edge, there's a 50% chance it will move you to a random z-level in the tether. It's because of overmap_spacetravel()

**Comment by Heroman3003** [comment]
Well, it should only move you to z-levels on space side of it, because you can randomly end up on said overmap thing when flying off the side of spaceside tether.

**Comment by Arokha** [comment]
Should be fixed now
