### ISSUE TITLE
"Omni" alarm monitor computers are broken

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7101]
#### Brief description of the bug
Alarm monitors that display all types of alarms (both engineering and security) are nonfunctioning

#### What you expected to happen
Displays all 5 types of alarms

#### What actually happened
Displays absolutely nothing

#### Steps to reproduce
- Go to bridge/ce office/secondary bridge and look at alarm list
- Find out that it displays 0 alarm types
- Cry

#### Code Revision
- 67173207bd4ef729ddd8873ff4a45dfcb5144033 
 
#### Anything else you may wish to add:
- http://prntscr.com/rrah59

**Comment by Arokha** [comment]
Still broken as of comment
