### ISSUE TITLE
fluff items with mob_can_equip restrictions break autoequipping

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#711]
#### Brief description of the issue
Fluff items with the mob_can_equip restrictions to ensure that only one person can use them interfere with the way that items are equipped in general, resulting in things being equipped in the wrong, and sometimes impossible, slots.

#### What you expected to happen
for my jumpsuit to go on my jumpsuit slot when I hit ctrl-e, and not to be able to equip it to my back slot when there's already a backpack in it.

#### What actually happened
The suit auto-equips to the back slot. Even when there's already an item there. The auto-equip item button (next to change hand on the hud, or ctrl-e) will try to equip it there regardless of whether there's an item in the jumpsuit slot.

This results in some pretty weird stuff on spawn:

![image](https://cloud.githubusercontent.com/assets/14942479/20046327/4cc49e46-a4a0-11e6-8cd1-90d2f950dcf1.png)

#### Steps to reproduce
edit /obj/item/clothing/under/fluff/screesuit so it checks for your ckey, compile
attempt to equip it with ctrl-e in-game, or click on your back slot

#### Additional info:
The offending section of the code appears to be this part:
For /obj/item/clothing/under/fluff/screesuit

```
	mob_can_equip(var/mob/living/carbon/human/H, slot, disable_warning = 0)
		..()
		if(H.ckey != "scree")
			H << "<span class='warning'>Are you just going to tape them on or what? This isn't gonna work.</span>"
			return 0
		else
			return 1
```

Commenting this block of code out makes the jumpsuit behave as normal, not equip itself in the back slot, and stay in the hand when I attempt to autoequip when already wearing a jumpsuit.

**Comment by Techhead0** [comment]
I suspect you need to replace `..()` with `.=..()` and remove `else return 1`. 
Autoequip is asking mob_can_equip() "Can I put this in X slot?", and mob_can_equip() says "1" (ie. yes), no matter what slot.
