### ISSUE TITLE
deluxe microwave duplication

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#7115]
#### Brief description of the bug
building a deluxe microwave puts the chip for making it inside the microwave, while keeping the build completed.

#### What you expected to happen
deluxe microwave board to get used up and not duplicated to build another freely.

#### What actually happened
Building the microwave puts the board inside the 'cook' interface. You can then eject it and build another. Taking apart the microwave and the original board is still in there.

#### Steps to reproduce
- get deluxe microwave board
- take apart the rnd or kitchen one
- replace normal microwave with deluxe microwave board
- build microwave
- look inside interface
- eject board

#### Code Revision
- 7aa396a32f9487627b3e672cabb881b335a050ba 
 
#### Anything else you may wish to add:
- https://gyazo.com/7a366c8cbd88c492a9fd08aabac284af

**Comment by Tasald** [comment]
edit kinda to this, the microwave circuit is just now unprintable. it only prints some fire assist board for a weapon system.

**Comment by Arokha** [comment]
Shouuuuld be fixed now?
