### ISSUE TITLE
"Request Spice" conformation buttons are switched out

### ISSUE THREAD

**Issue by Kheve** [VOREStation/VOREStation#7133]
Requesting Spice has the confirmation button switched with each other.

Normally : Left:Yes | Right:No

Request Spice : Left:No | Right:Yes

makes accidentally pressing yes quite easy.

Picture bellow

![bug](https://user-images.githubusercontent.com/63164343/78458275-60e28100-76b0-11ea-980b-7481fb52db9a.JPG)

**Comment by Runa-Dacino** [comment]
This is a feature, not a bug.
