### ISSUE TITLE
Engineering borgs are not insulated

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#714]
Title says it all. Engineering borgs are not insulated, and in fact extremely weak to electricity. This makes wiring work effectively a suicide mission for borgs.

**Expected behavior:** engineering borgs are not shocked when handling live wires, as it has pretty much always been in most codeforks of ss13

**What happens instead:** Wiring will WRECK. YOUR. SH*T.

**Steps to reproduce:**
1. Be engi borg
2. Cut or join about 3 to 6 live wires
3. Die as a result

**Comment by SpadesNeil** [comment]
Recently fixed by https://github.com/PolarisSS13/Polaris/pull/2707

**Comment by DeepIndigo** [comment]
Were drones fixed there too? 'cause they're not insulated either.

**Comment by SpadesNeil** [comment]
The changes aren't merged into our code yet. We merge every month.

**Comment by DeepIndigo** [comment]
Yeah, I mean in theirs. :v

**Comment by SpadesNeil** [comment]
Drones are a sub-type of cyborgs so they should be fine.
