### ISSUE TITLE
white ranger suit broken

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#7149]
#### Brief description of the bug
the ranger suit from the clothing vendor has no on the ground sprite ,and can't be removed.

#### What you expected to happen
To have a suit with correct icons, and not be unremovable with out help.

#### What actually happened
Put the suit on, was unable to remove it.

#### Steps to reproduce
- get a ranger suit from the clothing vendor
- put on suit
- attempt to remove

#### Code Revision
- c76760aaf613aa7440c9d673686b99c72607c0bb

**Comment by H0lySquirr3l** [comment]
What Ranger suit are you talking about?

**Comment by H0lySquirr3l** [comment]
from what I see there isn't a white suit. only black, pink, green, cyan, orange, yellow

**Comment by H0lySquirr3l** [comment]
Correction. seems that ALOT of the ranger uniforms are missing sprites.
![image](https://user-images.githubusercontent.com/34927367/81499993-d1268880-9294-11ea-996e-0e183d847c81.png)
