### ISSUE TITLE
Nevreans no Longer Able to Wear Mining Voidsuit Helmet

### ISSUE THREAD

**Issue by KasparoVy** [VOREStation/VOREStation#7157]
#### Brief description of the bug
PR #7031 refactored how voidsuits/rigs are fitted to species
A side-effect was that Nevrean-based species now use default Human sprites, and while suits seem to work, voidsuit helmets can no longer be worn by Nevreans - particularly the Mining one from what I can tell

Even if they were able to wear the helmet, Nevreans can have large beaks that protrude quite noticeably through the front - might be best to stick with the Unathi sprites

#### Code Revision
c76760aaf613aa7440c9d673686b99c72607c0bb
 
#### Anything else you may wish to add:
Noticed this when mining as a Nevrean-based custom species today. Luckily a coworker bailed me out with a hardsuit.

Confirmed the missing species allowance thru view vars 
![virgo ss13 missing voidsuit species allowance 20200406](https://user-images.githubusercontent.com/12377767/78530335-fc6c1280-77d2-11ea-82be-61922148d154.png)

**Comment by KasparoVy** [comment]
Nevermind, looks like this was intentional. I'll explore the issue further and re-post if necessary

**Comment by TheFurryFeline** [comment]
Far as I'm aware, per discussion in Virgo dev channel https://discordapp.com/channels/173831852602294272/187013248309002240/696542504304246804, Nevrean use human voidsuits. And Zorren/fennec custom species for Vulpkanin.

**Comment by KasparoVy** [comment]
Thanks for posting that, I'll rewrite the issue

**Comment by Novacat** [comment]
Seems like somethings not setting the species restrictions correctly for the helmets, I will fix that right away.

**Comment by KasparoVy** [comment]
Thanks @Novacat!
