### ISSUE TITLE
Port-side First Aid Station Sleeper issues.

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#717]
Panel doesn't register the sleeper unless the sleeper is portward of the panel. When you assemble a sleeper panel, it always aligns to connect to a portward sleeper, regardless of frame orientation. 

Two possible solutions, I see. 

A: Fix panel alignment. 

B: Probably the easier option, remap the aid-station to look like this:
http://puu.sh/sdnbP/d507e928dc.png

**Comment by Arokha** [comment]
I vote remapping since then it looks like you're standing between the console and the wall rather than standing backed up against the rack.

**Comment by DeepIndigo** [comment]
I'd also like to note, this is an issue on the trade shuttle too. I can't get a screenie but it's the exact same problem with the exact same fix.

**Comment by SpadesNeil** [comment]
Is this fixed yet?

**Comment by Dhaeleena** [comment]
No longer relevant on the current map.
