### ISSUE TITLE
Salt shakers have infinite range.

### ISSUE THREAD

**Issue by Azurachi** [VOREStation/VOREStation#7171]
#### Steps to reproduce
- Fill salt shaker with any liquid or just salt in general.
- Click on glass with salt shaker in hand.
- it will reach it no matter what as long as the sprite is out of someones hand it can be filled with the salt shaker.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Little-119** [comment]
It's like... salt artillery. Saltillery.
