### ISSUE TITLE
Bandana's cover mask slot.

### ISSUE THREAD

**Issue by CrystalNole** [VOREStation/VOREStation#718]
#### Brief description of the issue
Bandana's equipped on your head slot keep you from eating and putting items in your mask slot.
#### What you expected to happen
For it not to do that because it's on top of my head.
#### What actually happened
The bandana blocks the mask slot and eating.
#### Steps to reproduce
Hold bandana, go to IC tab and then click "tie bandana", put bandana on head slot, be amazed at your inability to eat with a piece of headwear on.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: release - 2016-11-04
5230158308a3ffe6f8f5fe41126b9f5fa006d696 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Fixed in latest build.
