### ISSUE TITLE
The ore eater trait doesn't clearly specify it disable nutrition gain from other sources

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#7181]
#### Brief description of the bug
If you have the ore and metal trait, you can't use normal food.

#### What you expected to happen
Be able to eat everything

#### What actually happened
Only sad rocks.

#### Steps to reproduce
- Take the EXPENSIVE TASTE trait
- (Eat food
- Become hungry because you crave minerals only.

**Comment by KasparoVy** [comment]
"Anything else is beneath you."

I'll adjust the message
