### ISSUE TITLE
Flat cap doesn't exist/gives you an invisible item

### ISSUE THREAD

**Issue by CrystalNole** [VOREStation/VOREStation#719]
#### Brief description of the issue
I put the flat cap in my loadout, colored it orange, and spawned with it in my pack, but it apparently had no icon, yet took up space.
#### What you expected to happen
For the flat cap to be there(and orange)
#### What actually happened
The cap laughed at me while my mind tried to comprehend it both existing and not existing at the same time.
#### Steps to reproduce
Choose loadout, choose flat cap from under Hats and Headwear, save slot, spawn ingame. Open you backpack and look inside. See an odd tiny sized item with no icon that you can't take out of your pack.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: release - 2016-11-04
5230158308a3ffe6f8f5fe41126b9f5fa006d696 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Alcastar** [comment]
Can confirm flat cap does not have a sprite and doesnt seem to be clickable but still "exists" in some sense as you can see it when right or alt+click ing on a tile the hat is on

**Comment by Cyantime** [comment]
Fixed by PolarisSS13/Polaris#3658, for the next Polaris sync.
