### ISSUE TITLE
Loincloths have no sprite ingame when wearing one

### ISSUE THREAD

**Issue by CrystalNole** [VOREStation/VOREStation#720]
#### Brief description of the issue
I spawned as my drider character and equipped the loincloth, instead of the loincloth I got I believe the "Honk" icon, or just "Icon" something that shows up when a piece of clothing doesn't have the thing associated with it to show on a character.
#### What you expected to happen
To be drider-tarzan
#### What actually happened
I wasn't
#### Steps to reproduce
Character loadout, Xenowear, chose Loincloth (Tajaran, Unathi), Save slot, spawn character in and if loincloth is not equipped, equip it.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: release - 2016-11-04
5230158308a3ffe6f8f5fe41126b9f5fa006d696 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
https://github.com/PolarisSS13/Polaris/pull/2715
