### ISSUE TITLE
Circuit Designer: Cannot open wearable circuits

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#7220]
#### Brief description of the bug
Using the crowbar on electronic goggles or gloves does not open them.

#### What you expected to happen
For them to be opened up so that circuits could be inserted/modified.

#### What actually happened
Nothing happens when using crowbar on them, whether in hand or on the ground

#### Steps to reproduce
- Using Integrated Circuit Printer, print an "Electornic Goggles" assembly or "electronic gloves"
- Try to crowbar open to begin work

#### Code Revision
- 92161d2074329870175a2c56b7c26bb02db88c5e 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Believe this was fixed. Either here or in a PR waiting on Polaris.
