### ISSUE TITLE
Should nutrition from food scale with size?

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#723]
#### Brief description of the issue
Would be just a nice feature. Let food give more/less depending on your size, with macros needing to clear tables to satiate their appetites while micros can probably live off an apple the entire shift. Or perhaps something like that. I remember some talk about it on Discord before. The idea is to promote predators to eat people because it's more efficient to grain nutrients from them, rather than eating whatever is at the cafeteria at the time or end up cleaning out a whole vending machine just to satisfy their hunger.
#### Additional info:
 - **Server Revision**: release - 2016-11-04
 - If it'll help, perhaps just change sugar and nutriment to restore hunger depending on the size of the character, either that OR make size make a character resist chemicals (which means chemicals have more/less effect depending on a character's size, which to be honest is pretty realistic, or perhaps size could multiply the chemicals that are introduced in the body, with macros being less than 1 and micros maybe 2, 5, maybe even 10 times the dose from a regular chemical. Would mean that surgery on macros is better than giving them a really big pill, though I wonder if there is a way to make character drink more/less from a glass so they don't kill over from alcohol poisoning or take forever to get drunk.)

**Comment by SpadesNeil** [comment]
As I understand it, this was a controversial topic, but the conversation wasn't held in public (rather, among admins) so I want everyone else to have input.

Arguments against: The fact that people _already_ like to gorge themselves on food and pilfer everything in the cafe.

My counter-argument: But micros will be eating less so it balances out.

**Comment by Screemonster** [comment]
The conversation was in the development channel a few days ago.

In all honesty, eating a muffin or two will put you on "full" for the rest of the shift already, so there's no real mechanical reason for anyone to stuff themselves like fatty porkins.

And hunger-slowdown is a pain in the ass :v

**Comment by Dinnel** [comment]
This was kind of solved with traits, specifically the metabolism ones. I'll go ahead and close it
