### ISSUE TITLE
Links in flavor text preview nonfunctional

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7248]
#### Brief description of the bug
Short flavor text preview links used to be clickable and they opened browser. Not anymore

#### What you expected to happen
Click short link in flavor text preview and see glorious ref sheet of my character

#### What actually happened
Have to go through copy-and-paste routine now

#### Steps to reproduce
- Put a short enough link in general of your flavor text
- Examine yourself
- Fail to use it directly

#### Code Revision
- 620183c39f0769956b1d9fb1930a5d5c99d36e4b 
 
#### Anything else you may wish to add:
- I don't remember if expanded OOC notes links used to work or not, but they are broken too.

**Comment by Jakksergal** [comment]
OOC notes did indeed display as clickable links before the implementation of the snazzy new chat.

**Comment by Very-Soft** [comment]
Oh hey I was just coming here to report this good on you, yeah, used to be if you put an imgur link at the start of your flavortext you could click the link to go to the image and it would pop up into your browser, and it was cool.

It would be very cool if that happened again.

**Comment by Arokha** [comment]
Fixy'd.
