### ISSUE TITLE
Talon Crew doesn't show up in Character Directory

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7267]
#### Brief description of the bug
I am not sure if intentional or not but Talon crew doesn't show up in Directory

#### What you expected to happen
Check prefs and flavor text of talon peeps

#### What actually happened
They are all missing!

#### Steps to reproduce
- See talon crew on OOC manifest
- Check char directory
- ???

#### Code Revision
- c5cb36d9d056e83267ce20ea81b84f680ce12174 
 
#### Anything else you may wish to add:
- Might be intenional, but doesn't seem to be as character directory is OOC thing, same as OOC manifests and they do show up in OOC manifests.

**Comment by Very-Soft** [comment]
Imo talon crew showing up in ooc directory isn't a bad thing. To have them on it could kind of spoil who's on it, which might not be desirable. It's small enough that they shouldn't have issues finding one another, and for everyone else, you can just examine them if you see them.

**Comment by Heroman3003** [comment]
But you can already see the characters and general amount of people in Talon Crew using OOC manifests anyway. This only allows you to also check their prefs remotely

**Comment by Wickedtemp** [comment]
They should be on the OOC directory because it's an OOC directory, usually used for checking prefs and OOC notes. It's pretty clear-cut.

**Comment by Heroman3003** [comment]
That, and very purpose of it being originally added is so that you can check OOC notes/flavor text of people specifically without needing to expressly find them to do an examine.
