### ISSUE TITLE
Afk Kick message is not displayed when you are afk kicked

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7268]
#### Brief description of the bug
When you are kicked for being afk before, it displayed an appropriate message in chat before it happened. With VChat, it now happens without that and you only get a VChat disconnect message, not the AFK disconnect one.

#### What you expected to happen
First message that you were kicked for being inactive for too long, then message that VChat lost connection

#### What actually happened
Just one that VChat lost connection

#### Steps to reproduce
- Get afk kicked

#### Code Revision
- c5cb36d9d056e83267ce20ea81b84f680ce12174 
 
#### Anything else you may wish to add:
- The message does seem to show up, but only on reconnecting. Makes me wonder if maybe other messages happening at same time as disconnect may end up not going through (like maybe ban messages?)

**Comment by TheFurryFeline** [comment]
I've noticed some other messages no longer showing up in VChat but can't remember what they are right now.
