### ISSUE TITLE
Facility walls don't seem to function quite as intended

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#7279]
#### Brief description of the bug
Facility walls are meant to be unsimulated infinite sources of planetside gasmix making changing temperature/mix planetside impossible

#### What you expected to happen
The infinite gas from walls overrides any attempts at changing planetside atmosphere

#### What actually happened
Several experiments of varying success at changing temperature and/or proportions of gas planetside.

#### Steps to reproduce
- Do a longterm gas heating operation outside
- "Wait, why isn't it staying same, why is it actually slowly, but working?"

#### Code Revision
- 63c02395712106c2bdcbe689c5cd4efa43eae54a

**Comment by Arokha** [comment]
I mean the planet walls don't magically convert all outdoor turfs into fixed atmos forever or anything, they'd become unsimulated essentially. Fires couldn't happen at all. We thought about making the map that way but where's the fun in that? The walls just interface with the air outside as if they were an infinite supply of that kind of air. They'll eventually cool down and replace all the air outside with their air, but, you can outpace it if you try hard enough. There's no solution that doesn't break physics in the game.

"I want temperature to transfer faster"
Ok, well you'd have to either make the walls WAY COLDER, which would also freeze the outside even more, or somehow rewrite Newton's Law of Cooling, which has other repercussions!

"I want the air to transfer faster"
Ok, well you'd have to either make the walls WAY HIGHER PRESSURE which would also pressurize the outside, or somehow alter the speed of sound, which has other repercussions!
