### ISSUE TITLE
NiF commlinks can no longer connect to the Exonet

### ISSUE THREAD

**Issue by AegisOA** [VOREStation/VOREStation#7283]
#### Brief description of the bug
Ever since some recent Exonet updates, there have been issues using the commlink's messaging functionality. Normally, when PDAs are down, so are NiF commlinks, yet, while PDAs were up the other day, commlinks were not. Today, someone reported that their commlink had no connection from round-start to round-end. Now, I tried contacting someone at the start of a fresh shift, only for them to get no signal.

#### What you expected to happen
To send some cute texts to a friend.

#### What actually happened
Run into the space equivalent of college Wi-Fi.

#### Steps to reproduce
- Open up your NiF's commlink software.
- Try to use its call or messaging features.
- Get stopped by the red signal triangle of death.

#### Code Revision
- 89d0492947d85104b79c57225802be7e509e2421
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by AegisOA** [comment]
Small update: While station-bound people can't reply to any messages, they can still receive those messages if they're sent by a ghost. One-way communication's still better than no-way, but, still.

**Comment by Wickedtemp** [comment]
Tbh I'd say this is a high-ish priority bugfix, since it makes NIF's trash without software.

**Comment by Arokha** [comment]
Is this working again? I made a fix to exonet stuff, namely communicators.
