### ISSUE TITLE
Research department not sufficiently connected to station

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#7297]
#### Brief description of the bug
The entire research department has become a victim of the shame basement syndrome that used to burden the old Z2 R&D lab prior to the remodel. The entire department is essentially nothing but a hole in the wall for the rest of the station with a useless double airlock thing made obsolete by the proper decontamination airlocks in the xenibio wing.

#### What you expected to happen
The research to be a nice and interactable friendly neighborhood scifi department.

#### What actually happened
![kuva](https://user-images.githubusercontent.com/13697337/79496344-ad25ad80-802e-11ea-9a8b-b97a2b5491de.png)

#### Steps to reproduce
- (Step 1) Look at the department.
- (Step 2) Notice how there is only 3 total see-through tiles between the station and its biggest department with no lobby or anything.
- (Step 3) Look at all the other happy departments that do have lobbies and windows and shit.

#### Code Revision
- 89d0492947d85104b79c57225802be7e509e2421
 
#### Anything else you may wish to add:
- How to fix: Remove the obsolete double airlock thing and make the research upper hallway a part of the public hallway and repurpose it as the actual science lobby.

**Comment by Arokha** [comment]
Github ain't for suggestions no more! If you want to do a map change, jus' map it, or it can be discussed on the forums or discord if you have suggestions.
