### ISSUE TITLE
Grass can't be removed

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#7305]
#### Brief description of the bug
Grass can't be removed in any way

#### What you expected to happen
Grass to be removed with some tool

#### What actually happened
Engineer couldn't remove it, used buildmode, grass now hole.

#### Steps to reproduce
- (Step 1)Be engineer
- (Step 2)Try to remove grassed floor
- (Step 3) Suffer

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 48ad4d95b3195659dadc98c8d84409d72598ea76 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Don't buildmode delete grass flooring, folks..

**Comment by MrSign** [comment]
Use a shovel.

**Comment by Natje0** [comment]
In hindsight it seems so obvious...
