### ISSUE TITLE
PDA Application: Power Monitor no longer shows the power grid

### ISSUE THREAD

**Issue by Holdelta** [VOREStation/VOREStation#7308]
#### Brief description of the bug
Engineering app on the PDA: Power Monitor no longer shows any power.

#### What you expected to happen
To access a basic view of the power grid.

#### What actually happened
Actually nothing here.

#### Steps to reproduce
- Check the Power Monitor app on the PDA
- See nothing, image below.

#### Code Revision
Server revision: release -  

48ad4d95b3195659dadc98c8d84409d72598ea76 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/7005665/79533401-94b49380-802c-11ea-9272-79246ec478cd.png)

**Comment by Little-119** [comment]
![image](https://user-images.githubusercontent.com/4680835/79678907-47702780-81ce-11ea-8fce-c918ad310168.png)
🤔

**Comment by Holdelta** [comment]
For what it counts, closed the earlier issue as that is no longer occurring.

This one is still active, while not a complete issue, I used it to work around this bug before I set up RCON:
https://github.com/VOREStation/VOREStation/issues/6262

As it stands, its not a big deal, and the main case that I encounter as an Engineer is checking the station's APC charges before setting up the grid to ensure smooth power transitions from setting up the grid.

**Comment by Holdelta** [comment]
This has been fixed in recent implementations of TGUI, closing issue.
