### ISSUE TITLE
Goat demi parts

### ISSUE THREAD

**Issue by Alcastar** [VOREStation/VOREStation#734]
I remember talking about this on the Discord a while back, guess i forgot to make a git for it ^^;

Agudner are a race from Vilous universe like sergals and look very similar but with more goat-like appearance so i made a horns/ears combination and a tail for people who want to play agudner or as some other goat-folk. Individual sprites in PNG and game sprites in .dmi are in this zip folder.

[Agunder parts.zip](https://github.com/VOREStation/VOREStation/files/626554/Agunder.parts.zip)

Just the sprites though, I'm not sure how to code them in as select-able ears and tail myself ^^;

**Comment by SpadesNeil** [comment]
The Agudner won't be included due to a conflict of lore with old Vilous war, but we could still use these icons at some point.
