### ISSUE TITLE
Kinetic Accelerators and how they're broken

### ISSUE THREAD

**Issue by InterroLouis** [VOREStation/VOREStation#7348]
#### Brief description of the bug

Kinetic Accelerators are broken.
#### What you expected to happen

I expect it to shoot. 
#### What actually happened

It does not shoot. 
#### Steps to reproduce
- (Step 1)Get a Kinetic Accelerator. 
- (Step 2)Try to shoot it.
- (and so on)It does not shoot.

#### Code Revision
- Server revision: release -  

25bbeda9450567d2d7d02354cce25d880f37a2b3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by InterroLouis** [comment]
I'm told to add this to the report as well. To clarify, it doesn't fire at all in any location-mine, underdark, in the station, and gives no message other than failing to function when you attempt to use it. Update two, point blanking seems to work fine, it's shooting at range that doesn't work.

**Comment by InterroLouis** [comment]
Update 3: It's not just the Kinetic Accelerator. Seems it might be the shooting system in general. Tried anti particle rifle and AEG, both don't fire.

**Comment by Novacat** [comment]
I have a feeling that this might be related to your specific version of BYOND. Unable to reproduce.
