### ISSUE TITLE
Whi/Subtles Ghost Visible is a big change that's defaulted to the opposite of what people are used to.

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#7385]
This isn't a bug necessarily, but there is a new feature to prevent ghosts from being able to see your scenes, and that's cool.

Problem is, it's defaulted to off, and most people don't know about it. Most people know how things have been, and sort of expect that ghosts would be able to see their posts. 

I personally think that this feature should be off by default, since that's how things have always worked. Let people turn it on if they want to use it.

While this isn't necessarily a -problem-, with how people don't really know about it, and hiding things is the default option, it's gonna interfere with post vore scenes and teases and such.

**Comment by Arokha** [comment]
When I was writing it, it was suggested in admin chat with no opposition at the time to having it default to on, so that is what I did.

Also no suggestions on github pls!
