### ISSUE TITLE
Can't select one of my character's fluff items (NT-HASD #556's Modkit)

### ISSUE THREAD

**Issue by SilencedMP5A5** [VOREStation/VOREStation#7397]
#### Steps to reproduce
- (Step 1) Be me, NT-HASD #556 (ckey SilencedMP5A5)
- (Step 2) Go to fluff items, under loadout
- (Step 3) Scream in agony as you are unable to select the thing.

#### Code Revision
- 88956587a923eed9223a7fae06dc4bc2cfc3373e 
 
#### Anything else you may wish to add:
- Just to spawn with it like I always used to -- The character is only ever in one job anyway.

**Comment by Cameron653** [comment]
Am looking into this. I can't see any reason why it isn't spawning it in from a quick look at the code. Ckey is the same, name is the same, custom_items_vr.dm and loadout_fluffitems_vr.dm are both in the .dme, etc.

(Relevant code segments here:
https://github.com/VOREStation/VOREStation/blob/master/code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm#L805-L810

and here

https://github.com/VOREStation/VOREStation/blob/master/code/modules/vore/fluffstuff/custom_items_vr.dm#L1714-L1724)

Going to try and poke around some more to try and figure out why this isn't working.

**Comment by Cameron653** [comment]
Fix found.
