### ISSUE TITLE
Xenobio slimes not eating monkeys.

### ISSUE THREAD

**Issue by oreganovulgaris** [VOREStation/VOREStation#7398]
#### Brief description of the bug
After pacifying a grey slime and putting two monkeys in its pen, it seemed to have an animation for an attack but nothing showed in chat, and the monkeys were completely fine.

#### What you expected to happen
The slime to eat the monkeys and divide.

#### What actually happened
The slime animated as if it was attacking the monkeys, but did not actually harm them or eat them. Additionally, sometimes in chat it showed the slime as "missing" but no other messages related to this event were shown.

#### Steps to reproduce
1. Create a grey slime by injecting plasma.
2. Pacify it by repeatedly using a slime taser on it when it attacks its pen's window.
3. Put two monkeys in the pen below it, then open the divider and close after it goes to "attack" the monkeys.
#### Code Revision
release - 88956587a923eed9223a7fae06dc4bc2cfc3373e 

#### Anything else you may wish to add:
I attempted to recreate this with a second slime, planning to see if a non-tame slime would be able to eat monkeys, however after its incapacitation wore off it still did not attack monkeys successfully. After moving a monkey outside the pen, it attacked the pen's door and managed to damage it, as well as successfully putting messages into chat alongside the animation.

I decided to see if the slime could attack me (for science and whatnot), but it also failed to properly attack me, doing the exact same thing as with monkeys.

**Comment by Arokha** [comment]
Fixy'd.
