### ISSUE TITLE
Replace the bluespace gateway currently on the map with a teleporter hub

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#74]
The current gateway is just a glorified cryopod. I do not want there to be two gateways, as having two gateways is going to be confusing to players. There's no descernable difference beside location compared to the gateway I want for Research for away missions, and the gateway currently in the map. I want to remove the one acting like a glorified cryopod and replace it with a star trek style teleporter room.

**Comment by Arokha** [comment]
Sprites pls.

It's already not a real gateway. It's just a cryopod set to the icon and iconstate of the gateway. Just need an icon to replace it with.

**Comment by Arokha** [comment]
If nobody makes sprites, I'll just, like, use the stock teleporter sprites but name them 'public short-range teleporter' or rename that room or something, pending someone making some. Unless you have a suggestion for sprites anyway.

**Comment by SpadesNeil** [comment]
That works for now actually.

**Comment by Arokha** [comment]
Leshana mapped in an actual gateway room connected to EVA.
