### ISSUE TITLE
Space Whale Random Event

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#741]
#### Brief description of the issue
When the event is triggered, a space whale anomaly will randomly appear on the station in a random area (taking care not to end up in a damn wall or something). When a player clicks on the anomaly, they will be given a prompt to ask them if they _really_ want to jump into it. If they do, they'll be teleported into a whale stomach! There, they will face hazards such as a maze of stomach acid effects, slippery floors, and possibly even a few parasitic life forms living inside the whale's digestive track.

The reward for this event will be various loot scattered throughout the whale's guts. The risk is obviously the crew could end up killed or digested.

There will be an OOC warning in advance of the space whale event, hence the OOC prompt. Because of the high value rewards, digestion preferences ***will be ignored*** by stomach acid tiles. The prompt asking you if you really want to jump into the anomaly is the player's last warning to not participate, so no one whines about broken prefs later on.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/75c1e7bc7c693c8642b0acfcc79f6b5a03e93789

Requires https://github.com/VOREStation/VOREStation/issues/739 and https://github.com/VOREStation/VOREStation/issues/740 to be finished.

**Comment by OrbisAnima** [comment]
remember to check the worm hole event for mechanics of teleportation, random teleports, and reference.
