### ISSUE TITLE
Special pathfinder radio can hear all the channels

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#7410]
#### Brief description of the bug
the special pathfinder radio has been said to have access to all the channels, and it definitely shouldn't.

#### What you expected to happen
should probably only have explorer and common comms, maybe science

#### Steps to reproduce
- listen to pathfinder radio

#### Code Revision
- release -  

0426e2ea3d0e7245cc3155b9e90dbbe71573127f
 
#### Anything else you may wish to add:
- Not sure if this has been reported or how long this has been this way, I peeked around and didn't spy one, so I report.

**Comment by TheFurryFeline** [comment]
If this is the SFR headset, that's part of the poi.

**Comment by Arokha** [comment]
Fixed in master
