### ISSUE TITLE
Mining Seismic Charges No Longer Work in Underdark - Safeties Trigger

### ISSUE THREAD

**Issue by KasparoVy** [VOREStation/VOREStation#7447]
#### Brief description of the bug
Mining seismic charges/plastic explosives/c-4 no longer work in the Underdark - the message **The seismic charge lets out a loud beep as safeties trigger, before imploding and falling apart.** is returned at every attempt.

#### What you expected to happen
The explosives to detonate and yield me some sweet ore.

#### What actually happened
The safeties triggered even though I'm in the Underdark and the explosive is deleted, wasting points and time.

#### Steps to reproduce
- Buy plastic explosives from mining vendor.
- Go to Underdark.
- Plant them and be disappointed.

#### Code Revision
- a2af64cc82e799dcb77358d899c36b8bb66f65bc
 
#### Anything else you may wish to add:
- Definitely used to work about a month ago

**Comment by Arokha** [comment]
Huh, did you try this today? I thought I fixed it yesterday.

**Comment by KasparoVy** [comment]
Yeah, just tried this today during the current shift actually
