### ISSUE TITLE
Dresses do not function as intended

### ISSUE THREAD

**Issue by KiraAlitruss** [VOREStation/VOREStation#745]
#### Brief description of the issue
All colourable plain dress types are now clothing items that cover the entire body.
#### What you expected to happen
For me to get a dress.
#### What actually happened
I got clothes that covered my character's entire body.
#### Steps to reproduce
1. Loadout menu. Click on any of the dress types, whether it be plain, long or long wide.
2. Spawn with it.
3. It'll not be a dress.
![dreamseeker_2016-12-10_22-35-072](https://cloud.githubusercontent.com/assets/19210185/21076366/dc30bbb6-bf29-11e6-9591-aff2a804852a.png)
#### Additional info:
 - **Server Revision**: release - 2016-12-10 7f96011afbb99594779cd3c50f0a25a84cc2fb2d 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Somekindofpony** [comment]
Sailor dress also is affected.

**Comment by Vorrarkul** [comment]
Elaborate Purple Dress is also affected.

**Comment by Cameron653** [comment]
This has been fixed by PR #753 and should be working next release.
