### ISSUE TITLE
Matierals Ordered from cargo spawning out of their crates. 

### ISSUE THREAD

**Issue by ChillyFang** [VOREStation/VOREStation#7451]
#### Brief description of the bug
When ordering things like glass or wood from Cargo, they spawn outside of their crates instead of inside them for some strange reason. 

#### What you expected to happen
They should be spawning in the crate. 

#### What actually happened
They are just layed out on top of the crate. 

#### Steps to reproduce
- (Step 1) Order any material form Cargo (Glass, Wood, Metal) 
- (Step 2) Wait for the shuttle to arrive, see that contents of the crates are spawned outside of the crates. 
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
a2af64cc82e799dcb77358d899c36b8bb66f65bc 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
N/A

**Comment by Arokha** [comment]
Part of the new Ease Of Unpacking initiative. They unpacked them for you.

**Comment by Arokha** [comment]
Should be fixed
