### ISSUE TITLE
[BUG] Sleevemate 3700 doesn't do anything

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#7455]
#### Brief description of the bug
Sleevemates don't display options when clicking people.

#### What you expected to happen
A menu to appear to scan and store minds.

#### What actually happened
Nothing.

#### Steps to reproduce
1- Click anyone with a sleevemate 3700
2- Nothing happens.

#### Code Revision
Server revision: release - a2af64cc82e799dcb77358d899c36b8bb66f65bc

**Comment by Arokha** [comment]
Fix merged, will be resolved on server next update.
