### ISSUE TITLE
[BUG] AI hologram chatter visible in the lobby

### ISSUE THREAD

**Issue by piperherring** [VOREStation/VOREStation#7459]
#### Brief description of the bug
![image](https://user-images.githubusercontent.com/60465170/80312436-379aa980-87b3-11ea-8457-ec06b2535803.png)

#### What you expected to happen
Not that

#### What actually happened
That

#### Steps to reproduce
- Be in the lobby while there's an AI player using a hologram in the bar (default ghost spawn)
- Yes
#### Code Revision
- a2af64cc82e799dcb77358d899c36b8bb66f65bc

**Comment by KasparoVy** [comment]
Lol, I saw this a few times myself today. Confirmed still a thing
