### ISSUE TITLE
Making Pets Inedible

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#746]
Yes, the time has come to code this in after the admin staff has made repeated announcements that eating the pets is a taboo.

Until the inedible flag is implemented, Security is encouraged to enforce animal cruelty laws in regards to pets being eaten and anyone arrested will not receive special OOC consideration that is given to vore related crimes.

Also note that you leave yourself up for trespassing charges as well if you go out of your way to break into an office to do such a thing.

**Comment by Poojawa** [comment]
rename the digestible permission to 'devourable'

default it to all relevant mobs. Slap the devourable check in the nom mob proc 'if 1 return' etc. 

Easy.

**Comment by SpadesNeil** [comment]
Or I could just check if the mob is Ian or other pets. There's no need to code a var for all mobs when I have no intentions to ever use it again.

**Comment by Arokha** [comment]
No work being done on this, so closing it until someone wants to do work on this, if ever. Hasn't come up in months anyway. This is one of those issues where it happens once a year and someone freaks out and we get gungho about this.

**Comment by Screemonster** [comment]
I think making the koi toxic solved the problem, as they're the only pets that most of the crew really had access to and most people are smart enough to figure out that randomly killing the named ones is bad.
