### ISSUE TITLE
Cigarettes not going out

### ISSUE THREAD

**Issue by Alcastar** [VOREStation/VOREStation#747]
#### Brief description of the issue
If you take a lit cigarette out of your mask slot and put it back it never goes out
#### What you expected to happen
The cigarette burns out
#### What actually happened
It didn't
#### Steps to reproduce
light cigarette, remove from face, put it back in face
#### Additional info:
Not sure if it makes any difference, but the brand was Lucky Stars, a Zippo lighter was used to light it, and I took a drink from a flask before putting it back in my mask slot.
Oh, I also went through the Expedition Gate a few times.

**Comment by DeepIndigo** [comment]
I think most of them burn out far too fast, personally
