### ISSUE TITLE
Weight Gain cannot be Disabled

### ISSUE THREAD

**Issue by ForFoxSake** [VOREStation/VOREStation#749]
#### Brief description of the issue
Weight gain cannot be disabled.

#### What you expected to happen
My character to not gain or lose weight.
Ideally, to not have the flavour text at all.

#### What actually happened
My character gained weight, and still had the terrible flavour text.

#### Steps to reproduce
1. Make character, set their weight gain multiplier to 0.1 as suggested.
2. Weigh your character.
3. Eat a _lot_.
4. Weigh your character.
5. See that your character has put on weight.

#### Additional
Synthetics can lose weight by using exercise machines but are physically incapable of gaining weight.

**Comment by SpadesNeil** [comment]
It is suggested to set it to 0.01 to stop weight gain. If you set it to 0.1, weight gain doesn't turn off.

Test it with weight gain set to 0.01 instead.

**Comment by ForFoxSake** [comment]
Even if 0.01 works, there's still an issue that the system is clunky and unintuitive even to the experienced user. Making it accept 0 as an option would be the simplest solution all round.

There's also the issue of the feature applying to synthetics, unless that needs it's own issue report.

**Comment by SpadesNeil** [comment]
That should be its own report.

**Comment by SpadesNeil** [comment]
```
		if(weight_gain_rate)
			pref.weight_gain = round(text2num(weight_gain_rate),1)
			return TOPIC_REFRESH
```
This rounds 0.01 to 0. Marking bug as invalid due to lack of testing.
