### ISSUE TITLE
357 Rubber Bullet Casing invisible

### ISSUE THREAD

**Issue by DarkWolfInsanity** [VOREStation/VOREStation#751]
#### Brief description of the issue
A bullet shot from a 357 magnum (such as the Big Iron Revolver) and removed will render invisible with no icon.

#### What you expected to happen
A bullet casing without the blue rubber tip

#### What actually happened
No visible casing at all, but still in hand with right click

#### Steps to reproduce
1. Find 357 revolver
2. Pull hammer back if single action
3. Shoot 357 revolver
4. Remove empty casing
5. Ask where the casing is and wonder why you can't pick anything up

#### Additional info:
 - **Server Revision**: release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d

**Comment by SpadesNeil** [comment]
@JoanRisu !
