### ISSUE TITLE
Talon Engineers can't change airlock access

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#7525]
#### Brief description of the bug
Not sure if intended or not but Talon engineers can't change the access requirements of airlock boards like normal engineers can

#### Steps to reproduce
- Be talon engineer
- get an airlock control board from a door
- try to unlock it to change access requirements

**Comment by Rykka-Stormheart** [comment]
Was this fixed by this?
https://github.com/VOREStation/VOREStation/pull/7649

**Comment by Arokha** [comment]
Should have been
