### ISSUE TITLE
Proposal for buildable electrochrome windows/airlock activators

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#754]
**Basic info:** electrochromatic windows, their controls, and buttons to open airlocks are not buildable.
**Side info:** TG has buildable wall buttons, though they currently can't be programmed.

**Proposed solution for airlock buttons:** Make the circuit inside them programmable via multitool, a la security camera console circuits without the lock. The var set would be the "tag" as I understand. The same could be done to airlocks via an additional link on the wiring pop up, thus assigning the door to the button. The setting could be described icly as the "network signal" sent by the button to the airlock, and could, like the tag var, be a word or numbers.

**Proposed solution for electrochromatic windows:** Along the same lines as the door button, but with light switches (yes, this would in theory make the two interchangeable for the windows/doors, separate frame options for them, in the "install frame in wall" menu, labeled "lightswitch" and "control panel"). 

As for making the windows them selves, they could be created from existing r-glass windows via a tool that's a labeler clone (like the pipe painter/floor painter are). clicking the tool would set the "tag" var to be applied to the window. 

Clicking the window with the tool would start a process (like wall welding or climbing on stuff), with text along the lines of "[name] starts to chemically treat and solder circuitry into [window name]!", followed by "[name] treats and finishes soldering circuits into [window name], making it electrochromatic!"

**Comment by Dropshotz** [comment]
look at /vg/ github, they have buildable airlocks n stuff. They have A LOT of stuff. maybe port a huge/small chunk over?

**Comment by SpadesNeil** [comment]
If we make them buildable, it's something that should be given to Polaris.

**Comment by SpadesNeil** [comment]
Is this a thing yet?

**Comment by Shophaune** [comment]
Nope.
