### ISSUE TITLE
Airlock emergency access proposal

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#755]
AIs/borgs/maint drones in tg code have the ability to toggle access restrictions on airlocks (like the radiation event does to the maint doors, they become all access and the lights flash yellow). This would be extremely handy, especially on low pop shifts where a department is needed but no one has access (for example, medical). Like under tg, it should remain as a silicon-only function.

**Comment by DemicusMaximus** [comment]
I love the idea. A lockdown feature would be nice for the AI too, case of viral outbreak or hazards.

**Comment by SpadesNeil** [comment]
This is something I would suggest we forward to Polaris.
