### ISSUE TITLE
Map errors: Medbay Sec Checkpoint.

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#757]
Wiring and pipes for the medbay sec checkpoint stop under the door and don't connect to the rest of the station's air/power.
http://puu.sh/sMsyF/438260f3f6.png
Location. In the shot it was repaired by an engineer, but it spawns undone.

Revision: current
Server revision: release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d

**Comment by SpadesNeil** [comment]
Server revision missing.
