### ISSUE TITLE
Cyborg rechargers charge synths too much

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#7574]
#### Brief description of the bug
Cyborg rechargers charge you passed full now

#### What you expected to happen
For them to stop charging you when you are full

#### Steps to reproduce
- Be synth character
- Go in cyborg recharger
- Wait a long time

#### Code Revision
- release -  

64e0699b790cb4ccbfed3086c3c9ce0438c8b2eb 
 
#### Anything else you may wish to add:
- Things related to nutrition changed recently, where the way it worked before was that the cyborg recharger would refill you right to the line of being over full (Which was 449.9 iirc)

Where, sitting in the recharger while I write this, am over 2000 and rising on charge.

**Comment by Little-119** [comment]
![image](https://user-images.githubusercontent.com/4680835/80925499-3ee72780-8d5e-11ea-9cb0-a340fa7bed2f.png)

Might be related to #7416
