### ISSUE TITLE
NIF Material Scanner Overlay Stops Working for Synths with Any Amount of Damage

### ISSUE THREAD

**Issue by KasparoVy** [VOREStation/VOREStation#7587]
#### Brief description of the bug
A synth with the material scanner acquired from the standard miner nifsoft injector experiences the following once they take ANY amount of damage:
- The material scanner's slight blue-ish tint disappears
- You no longer see objects through walls
- You still have 'night-vision' (no darkness overlays)
THIS IS FIXED ONCE YOU'RE REPAIRED TO FULL HEALTH

#### What you expected to happen
I expected my material-scanning NIFSoft to work regardless of my health. This happened whether I had the tiniest scratch (3 damage) or was FUBAR (40+).

#### What actually happened
I stubbed my synthetic toe and my NIFSoft stopped working.

#### Steps to reproduce
- (Step 1) Install miner NIFSoft set into your brain with the standard injector.
- (Step 2) Activate the material scanner.
- (Step 3) Take any amount of damage - observe bug.
- (Step 4) Get repaired - observe the issue resolve

#### Code Revision
- e89555cb291cd727bf4ca3d06bd065032403287d 
 
#### Anything else you may wish to add:
- This worked properly last night 20200501 before 12 midnight EST

_Damage readout_
![synth medichines not working at all](https://user-images.githubusercontent.com/12377767/80856040-fcc2c680-8c35-11ea-9292-bbedac809419.PNG)

_Material scanner NIFSoft being broke -- tint is gone, can't see objects through walls, still have nightvision though_
![synth medichines not working at all 2](https://user-images.githubusercontent.com/12377767/80856041-fcc2c680-8c35-11ea-9ec0-0fde1185aa90.PNG)

_After repairing myself, the NIFSoft starts working again_
![synth medichines not working at all 3](https://user-images.githubusercontent.com/12377767/80856043-fd5b5d00-8c35-11ea-8821-ff9787fb2c53.PNG)

I suspect there may be issues with all NIFSofts

**Comment by Arokha** [comment]
I notice you're super-hungry, too, which also affects NIF functioning. Are you sure it wasn't that? Either way, I can't reproduce it.

![image](https://user-images.githubusercontent.com/15028025/81026931-dbd2bf00-8e49-11ea-8557-97f03e3852ff.png)

**Comment by Arokha** [comment]
Hit me up on discord during a round if it happens again so I can VV you!

**Comment by KasparoVy** [comment]
Cheers, will do! The hunger was merely the timing of the screencap, I was maxed out on energy when I first experienced the bug in the belts but hopefully it's a one-off-- haven't played synth since then
