### ISSUE TITLE
Can't upgrade grabs at all

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#7589]
#### Brief description of the bug
Can't upgrade grabs in hand using Z on hotkey mode or by manually clicking on the icon

#### What you expected to happen
To be able to aggressively grab someone

#### What actually happened
Awkwardly standing there in the middle of a scene as you can't grab and then get to wonder what happened to break everything

#### Steps to reproduce
- Finally corner the nerd that you've been teasing for the past hour and a half after they "wander into maint just because"
- Grab the snack, try to eat them and instead find out that you can't upgrade a passive grab at all
- S u f f e r

#### Code Revision
- e89555c
 
#### Anything else you may wish to add:
- This is on byond 513.1513 like people keep suggesting is to be used as the later beta versions are broken too apparently.
- Swapping a grab to a different hand with middle mouse button/clicking on it also breaks everything ever and requires a relog to be able to move once more.
![dUBtN86](https://user-images.githubusercontent.com/17093432/80859004-80c38100-8c2b-11ea-8234-a02994826e9e.png)

**Comment by Verkister** [comment]
It seems the actual hand icon in the middle of the grab is somehow no longer working as a part of the grab interface so clicking inside the hand does nothing, but you can still upgrade the grab by clicking on the colored "background" of the icon.

**Comment by Zeldazackman** [comment]
Fixed by 7585 I think, closing this issue.
