### ISSUE TITLE
AI unable to Examine

### ISSUE THREAD

**Issue by AdmiralDragon** [VOREStation/VOREStation#7591]
#### Brief description of the bug
AI are unable to examine people, this can complicate things in the case the AI is trying to see what a short/micro sized character is holding, also some weapons or items don't have the best of "in hand" sprites so examining is needed to figure out what they have.

#### What you expected to happen
Shift+Left Clicking = Examine Person

#### What actually happened
Shift+Left Clicking did nothing
Not sure if it was the connection but I experienced a slight freeze when I tried to Examine though no info appeared.

#### Steps to reproduce
- Join as AI
- Shift+Left click, "Right Click" then select "Examine"
- Watch the chat and see as nothing appears.

#### Code Revision
- e89555cb291cd727bf4ca3d06bd065032403287d
 
#### Anything else you may wish to add:
- Nothing to add.

**Comment by KeRSedChaplain** [comment]
This is a feature, unfortunately

**Comment by AdmiralDragon** [comment]
I was able to do that before an update recently which took it away. I usually use it to figure out who I can bother as an AI without interrupting a scene. Without Examine I am unable to figure out who's in a scene.

**Comment by KeRSedChaplain** [comment]
huh

**Comment by Arokha** [comment]
Hm! That's never intentionally been a feature. It's possible someone broke it to work, but it's always been a balancey thing that you can't see what people are holding and such as AI. Maybe someone can code up a middleground that lets you read OOC notes.
