### ISSUE TITLE
Talon's Boat cannot land on certain away missions visible on the overmap

### ISSUE THREAD

**Issue by knoxon1** [VOREStation/VOREStation#7609]
#### Brief description of the bug
Most away missions spawn on the overmap now, while the Talon's Boat can land on maps like the Listening Post, its unable to land on Carp Outpost or Snowy Field

#### What you expected to happen
Get in boat, land on Snowy Field, steal explorer's jobs

#### What actually happened
Sit and stare at the Boat console in disappointment

#### Steps to reproduce
- (Step 1) Fly to strange location on overmap
- (Step 2)Scan to reveal location, attempt to land boat there for sweet loots.
- (Step 3) Fail to land, repeat staring at boat console in disappointment

#### Code Revision
- feeb1af205b1dc03477a77bb46d788950a649508
 
#### Anything else you may wish to add:
- Untested with Expedition Shuttle, but may also be bugged with that as well

**Comment by Arokha** [comment]
Likely based on the positions of those landing landmarks not having the right shape/area available for the talon boat (which goes further south from it's own landmark than the excursion shuttle does)

**Comment by knoxon1** [comment]
For the record I've tested and confirmed you can land at the Listening Post map, and that really big snow field one that I don't know the name of, with the kuraraks

**Comment by Natje0** [comment]
I'd also like to add that while you can enter the Carp infested outpost with miniships/mechships like the Pinnace, the map is surrounded by Blockers so you can't actually get further
