### ISSUE TITLE
Substation SMES units no longer charge

### ISSUE THREAD

**Issue by Cafaling** [VOREStation/VOREStation#7624]
#### Brief description of the bug
All SMES units tied to substations are now incapable of charging

#### What you expected to happen
To be able to set up a series of power gates that restrict the flow of power and build a backup charge

#### What actually happened
SMES units did not register that there were charged wires feeding them power, did not charge from this power, and could not output any power, constantly reading as [Stored power too low] on the output, even when output is disabled.

#### Steps to reproduce
- Join round start
- Set up power supplies
- Enable Main SMES output
- Try to calibrate any Substation's input and output remotely or in person
- Experience a total failure to charge, much less output power.

#### Code Revision
- 7f5c502fe15ee394c56be0d880e5ad2b25f6b886
 
#### Anything else you may wish to add:
- Amaya and I tried deleting and respawning the Engineering SMES in order to see if anything changed, and saw no difference. Shuttle SMES units may also not be charging.

**Comment by Arokha** [comment]
Surely related to https://github.com/VOREStation/VOREStation/pull/7615 though I know not how
