### ISSUE TITLE
Transferlocation stomach limbo bug

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#763]
#### Brief description of the issue
Deleting a transfer location stomach then transferring prey causes prey to be stuck in limbo
#### What you expected to happen
Delete transfer location stomach, have it automatically removed as a transferlocation from all other stomachs
#### What actually happened
Didn't remove it as a transferlocation. When prey was transferred it trapped them in limbo
#### Steps to reproduce
Make a secondary stomach
Select secondary stomach as a transfer location
Delete secondary stomach
Eat prey and have them struggle while special interactions are toggled and transfer chance set to 100
Watch as prey is removed from primary stomach but trapped in limbo as secondary stomach doesn't exist
#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/3c0df7dbc08319ad4b7298a546db4de0fc17d5bb
 - **Anything else you may wish to add**: SEE COMMENTS BELOW FOR HOW TO REPRODUCE.
 Bug is from PR #758.

**Comment by SpadesNeil** [comment]
Added a revision because it's still a version, it's just in the master and not the release branch as of this moment.

**Comment by Dinnel** [comment]
Is there a way you can make it so if there is a transfer it can check first? Like see if the belly still exists by just checking the person's organs for a belly with the name or check a belly id that matches with the transfer, else abort and alert the pred?

**Comment by SpadesNeil** [comment]
Updated to severe and blocker because this causes players to become stuck without admin help.

**Comment by SpadesNeil** [comment]
Still a bug.

**Comment by Cameron653** [comment]
Possible reason for this bug occuring:

Between rounds, the stomach ID's may be changing, causing them to get bugged out due to the stomach ID it's pointing to isn't actually part of the pred anyone.

Example:
Maw ID: 1
Stomach ID: 2
2nd Stomach ID: 3
Transferlocation works fine and everything. Maw points to stomach (ID 2) and stomach points to 2nd stomach (ID 3)
Next round starts, ID's are as follow:
Maw ID: 4
Stomach id: 5
2nd Stomach ID: 6
Transferlocation is heavily bugged here, as Maw points to stomach (ID 2) which doesn't exist in the character anymore, and stomach points to 2nd stomach (ID 3) Which, also, doesn't exist anymore.

Happened in a recent round and this is what I came up with after looking at it. After they reset the transferlocations on everything it worked fine.

**Comment by Arokha** [comment]
I don't know why this happens. PREVIOUSLY, yes, the transfer thing was due to stuff like that. But as it is, it's supposed to just silently fail if it can't find the belly it wants to transfer to. Instead it moves prey into nowhere for no reason.

**Comment by SpadesNeil** [comment]
Stiiiiiiiiiiiiiiilllllllllll a bug, I think. I saw it happen recently. Need to reproduce.

**Comment by Cameron653** [comment]
It's easily reproducable as far as I know.

How to reproduce:
Set mouth(ID 1) to go to stomach (ID 2) on struggle. Save.
Have server shut down, start it back up.
Now mouth (Let's say it's ID 3 now) points to stomach (ID 2) even though stomach they spawned with has a new ID from the prior round. 
This results in the prey being added to the ID 2 stomach which the pred doesn't have anymore, meaning the prey is trapped in the void.

**Comment by Cameron653** [comment]
Alright. Here's my results after testing:
**First Round** stomach datums: http://i.imgur.com/4PH1dYg.png
**First Round** all stomach transferlocations: http://i.imgur.com/N2zbyaT.png
**Second Round** stomach datums: http://i.imgur.com/in7Gb8X.png
**Second Round** all stomach transferlocations: http://i.imgur.com/TRxAOx0.png
Below: **First round**. Maw set to stomach. Stomach set to stomach 2. Everything works.
https://i.imgur.com/GHTXu1r.gifv

Below: **Second round**. Maw set to stomach (incorrect datum) Stomach set to stomach 2 (incorrect datum) Prey gets voided.
http://i.imgur.com/isf97jS.gifv
Additional: Picture of the maw transferlocation datum stomach and stomach they spawned with 
http://i.imgur.com/fVYDBNF.png

**Comment by Cameron653** [comment]
Rest in peace.
May this bug never rear it's head up again.
