### ISSUE TITLE
[BUG] Rollerbed movement is extremely buggy

### ISSUE THREAD

**Issue by serenekerosene** [VOREStation/VOREStation#7634]
#### Brief description of the bug
Rollerbeds do not follow a straight line when being pulled. They seem to veer to random spots to the side of the player pulling them.

#### What you expected to happen
Not that

#### What actually happened
That

#### Steps to reproduce
- Be medical
- Have unexplainable muscle spasms
- Throw your critical patient off the atrium

#### Code Revision
a08cab79c82a0b4efe747d34dcaaf6747ae5c1c1

**Comment by Arokha** [comment]
Was told this was behaving fine now. Let me know if that's not the case!
