### ISSUE TITLE
Camera Rotation Breaks Taurs

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#766]
#### Brief description of the issue
When using the Spin Camera CW/CCW, taur crew will have their taur half be off-centered, potentially showing their legs.

#### What you expected to happen
The taur body to stay immersively where it was.

#### What actually happened
Immersion-breaking sprite glitches.

#### Steps to reproduce
- Have a taur nearby/be a taur.
- turn the camera.

#### Code Revision
- release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d 
 
#### Anything else you may wish to add:
- It might not be on all facings; might need testing.
- Screenshot links:
  - https://www.dropbox.com/s/omf5izyar69rf4w/Screenshot%202016-12-16%2017.39.35.png?dl=0
  - https://www.dropbox.com/s/7dc34p8dzguzl9v/Screenshot%202016-12-16%2017.39.41.png?dl=0
  - https://www.dropbox.com/s/e0lc1okdbmh1rie/Screenshot%202016-12-16%2017.40.10.png?dl=0
  - https://www.dropbox.com/s/pjpkndkxvg6e5ny/Screenshot%202016-12-16%2017.40.19.png?dl=0

**Comment by SpadesNeil** [comment]
Screenshots would be nice.

**Comment by Vorrarkul** [comment]
Screenshots added via dropbox links. Will that work?

**Comment by SpadesNeil** [comment]
Yes.

**Comment by Arokha** [comment]
Prooooooooobably not fixable. There are many other things that break, too. Like lighting. Making it work on all of them is a little much for a game that was never reaaaally intended to have the feature of camera rotation.
