### ISSUE TITLE
Autopsy scanner

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#767]
#### Brief description of the issue
The scanner would only show one limb despite being used on another body part.

#### What you expected to happen
To be able to scan specific body parts and have the scanner print the correct data.

#### What actually happened
It only showed data for the left hand, or nothing at all.

#### Steps to reproduce
1: get dead body.
2: preform autopsy.
3: scan and print different body parts.
4: Rage at lack of data.

#### Code Revision
Server revision: release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
This still a problem?

**Comment by Tasald** [comment]
yea, just tested it today.

**Comment by Shophaune** [comment]
The /biopsy/ scanner seems to be completely non-functional. Being as that's what's provided in the morgue with a scalpel and cautery, I presume that this is the item in question and therefore needs fixing.

**Comment by Shophaune** [comment]
Okay so there's no trace of the original only-left-hand bug, but the scanner doesn't seem to work because it silently returns on help intent. Is this intentional? 
![image](https://user-images.githubusercontent.com/31856537/44910716-2ec2ad80-ad1c-11e8-9268-cabbbca78fa6.png)

**Comment by Shophaune** [comment]
Is intentional, autopsy scanner works. This can probably be closed?
