### ISSUE TITLE
Nightshift Announce is audible in UD

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#7714]
#### Brief description of the bug

Heard the announcement about daylight.

#### What you expected to happen

Not hear about the lights switching to day/night, as I am a massive doggo in the underdark, away from any intercomms.

#### What actually happened

Heard the AI telling me it was now daytime, even though it wasn't physically possible! <3

#### Steps to reproduce
- Be dog
- be underground away from intercomm
- hear ai
- Profit???

**Comment by Arokha** [comment]
This is expected, since UD is within comms range now.

**Comment by Rykka-Stormheart** [comment]
> This is expected, since UD is within comms range now.

Even if I don't have a headset/am a mob with no intercomms nearby?

**Comment by Arokha** [comment]
Ye, the sound plays to everyone in the affected zlevels. There's not really a way to do 'a sound coming over the radio' to you. Presumably it's from overhead announcement systems or something, but yeah that doesn't make a lot of sense in the UD. |3

I mean I can remove it from comms range but that seems overkill for this.
