### ISSUE TITLE
Medbay cloner freezing.

### ISSUE THREAD

**Issue by SiennaAthens** [VOREStation/VOREStation#772]
#### Brief description of the issue
Attempted to clone a dead character, process froze.

#### What you expected to happen
Successful cloning after a short time.

#### What actually happened
Cloning process froze at 50%. Could not eject patient manually. Patient's player says their character (Neiseri) was at full health. This was the second time that character was cloned this round.

#### Steps to reproduce
- Attempt to clone character, perhaps for the second time.
- Check cloning process by clicking on the cloning cell.
- Observe cloning process %.

#### Code Revision
- release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d 

#### Anything else you may wish to add:
- Station medbay cloning lab. The cell was upgraded during the shift, perhaps it wasn't done properly.

**Comment by DemicusMaximus** [comment]
Unable to reproduce. Possible one-off.

Also was unable to pull vars upon discovery as I crashed every time. Wasn't getting any debug messages but a check of the debug log might have something in it.
