### ISSUE TITLE
Farmbots appear to cause mob process to hang.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#773]
#### Brief description of the issue
Farmbots seem to cause the mob process to hang. There's some brief lag, then the admin log shows the process being killed.

#### What you expected to happen
For this not to happen and farmbots to keep doing their thing.

#### What actually happened
ADMIN LOG: Process 'mob' is hung and will be restarted.
ADMIN LOG: mob process hung at tick #5870. Process was unresponsive for 90.0836 seconds and was restarted. Last task: 0. Last Object Type: /mob/living/bot/farmbot
ADMIN LOG: mob process was killed at tick #5870.

#### Steps to reproduce
Build farmbot.
Wait.

#### Code Revision
Server revision: release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d

**Comment by SpadesNeil** [comment]
Farm bots seem to work fine now.
