### ISSUE TITLE
Can no longer SPEEN

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#7745]
#### Brief description of the bug
Can't use control and arrow keys to spin with other folks like a timed classic for whatever reason.

#### What you expected to happen
To be able to spin around

#### What actually happened
Awkward changing of directions that are just as fast as if you were clicking

#### Steps to reproduce
- Hold down control
- Use arrow keys in a circular fashion to try to spin
- Realize that you can't speen anymore along with the other nerds in the group that were trying to do something small to pre-occupy the time while waiting

#### Code Revision
- 52b79d3
 
#### Anything else you may wish to add:
- Please let us speen again, [Please](https://www.youtube.com/watch?v=l4mTNQLsD0c)

**Comment by KasparoVy** [comment]
Yeah, can't dance no more. Used to have macros for dances with repeated facedir commands to act in the place of sleeps, but they're totally screwed.

Gotta dance!
