### ISSUE TITLE
Fluff Item App: Winter Coat, Cargo - Nyssa Brennan - Vorrarkul

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#775]
**Name of Item:** Winter Coat, Cargo

**Item description:** A heavy jacket made from 'synthetic' animal furs.

**Sprites (or link to sprites):** N/A, in-game item.

**Any additional resources:** N/A, in-game item.

**BYOND Key (Username):** Vorrarkul

**Name of Character:** Nyssa Brennan

**Main Job(s) of Character:** Varies Wildly (I haven't settled on a job for her.)

**Why your character should have this item:** It is grey and yellow, and its style and pattern fits her better than the other job-specific coats or the 'assistant' coat. I want it for non-cargo use as well. In-character, its style suits her tastes and she likes the furry lining.

**Additional Notes (If it's a permit, insert the information for the permit here):** N/A at the moment.

**Fluff Item slots already used:** 2 for Lucina; the dress and the PDA. 0 for this character.

Created here rather than in the forum at the direction of Joan.

**Comment by JoanRisu** [comment]
Looks gud to meeeee
