### ISSUE TITLE
Defibs at CC/Emergency Shuttle

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#776]
#### Brief description of the issue
Prisoner under Security care died in transit to CC. No defibs present on emergency shuttle OR central command.

#### What you expected to happen
Given that the shuttle is specifically an EMERGENCY shuttle, it really should have a defib. CC as well.

#### Code Revision
Server revision: release - 2016-12-10
7f96011afbb99594779cd3c50f0a25a84cc2fb2d

**Comment by SpadesNeil** [comment]
Is this resolved on the new map?
