### ISSUE TITLE
Hey ma!, there's a weird visual bug of waves everywhere outside here!

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#7770]
#### Brief description of the bug
Shoreline effects are all over the place on the outside of virgo 3b

#### What you expected to happen
For phoron grass not to try to go full surfer brah

#### What actually happened
[https://youtu.be/RHpn-o9n-cs](https://youtu.be/RHpn-o9n-cs)

#### Steps to reproduce
- Go to window
- Look outside
- Observe waves to the north of every wall and window, even waves floating in mid air over the sheer drop off of floor three to the surface below

#### Code Revision
- 961f76a
 
#### Anything else you may wish to add:
-  Surf's up dude!
![OREgPs2](https://user-images.githubusercontent.com/17093432/81521865-8e0cf980-9316-11ea-8531-025e21f16682.png)

**Comment by Rykka-Stormheart** [comment]
Known bug atm, suspected cause is `update_icon_edge()`, am working on it atm.

Fix ASAP if I can figure it out.

**Comment by Zeldazackman** [comment]
I know, just teasing you silly (also any excuse for me to post chocobo music is a good one) <3

**Comment by Rykka-Stormheart** [comment]
This was fixed by https://github.com/VOREStation/VOREStation/pull/7777
