### ISSUE TITLE
Boxes are often times smaller than the amount of contents that they contain.

### ISSUE THREAD

**Issue by Zeldazackman** [VOREStation/VOREStation#7772]
#### Brief description of the bug
What it says on the tin, the amount of stuff that is spawned crammed inside of a box is unable to be tossed back into ~~pandora's~~ the cardboard box.

#### What you expected to happen
For a bodybag box (among many others) to be able to contain the amount of stuff that it spawned in with, have something taken out of said box and then later on be able to place the thing that was taken out of the box back inside neat and proper.

#### What actually happened
![cb1ZbvF](https://user-images.githubusercontent.com/17093432/81522967-6a4bb280-931a-11ea-8f09-01e56938568a.png)
This, but with many, many things all around the station that really break immersion at times as it's now at the default of having a storage space of just 8.

#### Steps to reproduce
- Grab box
- Click and drag it to yourself, see that it's ability to contain things has been shrunken down across the board
- Weep

#### Code Revision
- 961f76a 
 
#### Anything else you may wish to add:
- It's been an ongoing thing, I hope that the solution isn't to remove the now overflowing "extra"
 things that boxes used to normally be able to contain without any issues.
- Perhaps setting a box's max_storage_space back to 16 would fix this again?

**Comment by TheFurryFeline** [comment]
This got fixed with #10314 I think
