### ISSUE TITLE
[BUG] Talon is mostly open to the Tether station AI (Including control of the ship)

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#7797]
#### Brief description of the bug

AI can see a huge part of the Talon, as well as access the flight consoles, and the sensors, and everything, and toggle them. I can force a Talon launch.

#### What you expected to happen

Be Tether AI, not be able to see the independant ship's networks, not be able to access their consoles, etc.

#### What actually happened

I AM THE SENATE. No but srs, I can control everything.

[!https://i.gyazo.com/f33d8e3baa5898ee230c851bee941011.png]
[!https://i.gyazo.com/03980b6536f111c828558e2d9bdf2f8d.png]
[!https://i.gyazo.com/f8096acf7142bca3ae1ec73862fababc.png]
[!https://i.gyazo.com/483290cd3bdba477a28bbd0c300bf32c.png]
[!https://i.gyazo.com/fee4f1dd06893732e32229e4c8d0206b.png]

**Comment by Arokha** [comment]
This is too much work for me to want to fix. There are a few ways you could fix it, but they're all bad, without a full rewrite of how the AI works. In general the game expects there to be a single faction's AI and it expects it to have access to everything, so there's no "AI access" system at all. In general, things just ignore access checks when the AI clicks on them.

You'd need to implement the AI having access, and somehow checking that on every object that allows the AI to use it. It'd be interesting, but should probably be done.

Just not by me!

**Comment by Rykka-Stormheart** [comment]
> This is too much work for me to want to fix. There are a few ways you could fix it, but they're all bad, without a full rewrite of how the AI works. In general the game expects there to be a single faction's AI and it expects it to have access to everything, so there's no "AI access" system at all. In general, things just ignore access checks when the AI clicks on them.
> 
> You'd need to implement the AI having access, and somehow checking that on every object that allows the AI to use it. It'd be interesting, but should probably be done.
> 
> Just not by me!

...things do already check access!

I clicked on the "helm control console" inside the backup bridge and it returns "Access Denied!", but the rest of the consoles outside the backup allow access.

**Comment by Arokha** [comment]
Most things definitely don't, and that's probably a bug you found.
