### ISSUE TITLE
Landing Shuttles Delete AI Eye

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#7805]
#### Brief description of the bug
If the AI view is centered on one of the tiles in a landing area when a shuttle lands, the AI loses all ability to control their camera view.

#### What you expected to happen
Nothing

#### What actually happened
Had to store the AI core and rejoin the round to get camera controls back.

#### Steps to reproduce
- Center AI Eye on a landing area
- Land a shuttle there

#### Code Revision
- Current at posting time

**Comment by Rykka-Stormheart** [comment]
Thanks for reporting!

That's a wonky-ass one.
