### ISSUE TITLE
Show Server Revision button broken

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#7848]
#### Brief description of the bug
- Pressing the Show Server Revision button only prints out "Revision unknown"

#### What you expected to happen
- To get the current revision

#### What actually happened
- Revision unknown

#### Steps to reproduce
- (Step 1) Press that button

#### Code Revision
- The current one, ironically not provided because of this very bug I am reporting.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Semifixed, but still not quite.

**Comment by Arokha** [comment]
Fixed
