### ISSUE TITLE
custom item problems -- can't get the dang thing without adminbus

### ISSUE THREAD

**Issue by SilencedMP5A5** [VOREStation/VOREStation#785]
#### Brief description of the issue
A certain type of armor that my custom item modkit works on isnt mapped in, which prevents me from acquiring said custom item.

#### What you expected to happen
To be able to get the armor set i made a custom app for :v

#### What actually happened
I bashed the kit against regular armor vests in confusion until I was told the problem (which was around when the last update came out.)

#### Steps to reproduce
- Be me, have modkit
- hit regular armor, scream internally as nothing happens
- aaaaaaaaaaaaaaaaaa

#### Code Revision
- 
 
#### Anything else you may wish to add:
- the 'wolftaur' armor that the modkit works on.

**Comment by OrbisAnima** [comment]
I tested this one, spawning /obj/item/device/modkit_conversion/fluff/serdykit on local and it worked on the wolftaur armor, and the helmet, the problem you have is that the modkit was made in such a way it works on the wolftaur armor, but not on normal armor. You would first need to convert normal armor into wolftaur armor.

**Comment by SpadesNeil** [comment]
We need taur conversion kits.

**Comment by OrbisAnima** [comment]
ah, I though THC were things that were available via cargo or lathe. On a possible griefing standpoint, wouldnt it be better if it was something produced in game so you can counter it from IC?

Either that or a machine like the one in eva but for taur stuff. (I rather like more the idea of cargo, gives people thing to do, and a few starting kits on sec should do the trick)

**Comment by OrbisAnima** [comment]
Then again, a piece of armor is not that expensive that will justify a deconversion kit, but what do you think ace?

**Comment by SpadesNeil** [comment]
Honestly it'd be better if the damn suit cycler could just handle it.
