### ISSUE TITLE
proteans can smuggle assistants into the red armory with vore

### ISSUE THREAD

**Issue by nerdass** [VOREStation/VOREStation#7863]
consume assistant, channel inner monky, get guns, cargonia strong

**Comment by Screemonster** [comment]
Probably need _some_ means of blocking ventcrawl into secure areas.
Like a powered device that can be clamped onto the pipe that blocks passage.
Like a forcefield.

Or a microwave.

**Comment by nerdass** [comment]
i'll resize to 200% so i'm immune because it's not a macrowave

**Comment by Verkister** [comment]
A good way to lose whitelist privilege there

**Comment by Arokha** [comment]
What Verk said, ya. That's why they're whitelisted. I'm not sure this is a bug.

**Comment by Screemonster** [comment]
If a place _really_ needs to be secured against ventcrawling mobs, I have some ideas. Either with a new device that would block passage through pipes, _or_ with something I'm gonna hop on and test to see if it works, and if it does then at most it's just a mapping issue.
