### ISSUE TITLE
Rapid Digestion Pills (Not mob digestion, food digestion)

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#787]
#### Brief description of the issue
I want a pill that converts nutrition into bodyfat in a matter of minutes rather than hours. This way players don't have to walk around with an engorged sloshing belly all the damn time after eating someone. Chembay could make these pills, and the overabundance of food they ate gets converted directly into padding.

#### How it should work
- Eat a lot of food so you have like, idk, 500 nutriment.
- Take a pill.
- Nutriment is converted to weight using the same values and equations already used for weight gain/loss, except that it happens **much** more rapidly. Maybe it temporarily increases body temperature slightly and you get a message like, "You can feel your stomach getting very warm."
- Overdosing is its own consequence because you'll start starving, but should there be more consequences?

**Comment by OrbisAnima** [comment]
an idea here on how to implement it.

Make a reagent that reacts with high amounts of nutriment, 10, idk, for each unit, that will turn in another reagent that is like 10 times more effective than nutriment.

Of course, you can change the multiplier to what you need, but I believe this might help you get what you want to achieve, with ease.

**Comment by SpadesNeil** [comment]
Nutriment is not a reagent that appears in your blood when you eat. It just turns into nutrition.

**Comment by OrbisAnima** [comment]
all my life has been a lie.

**Comment by Dropshotz** [comment]
chemical to lower nourishment exists. Lepizine or something, is the name i thin. check the wiki, cause I remember using it once

**Comment by Screemonster** [comment]
That's not what Ace wants though. Leporazine doesn't trigger weight gain, it only resets the nutrition var.

**Comment by BothNevarBackwards** [comment]
Making a pill in the health vendors would work best probably. Let me look into it as I wouldn't mind having something like this as well.

**Comment by lbnesquik** [comment]
I think that could be pretty easy. You'd need a reagent that just crank `hunger_factor `into over drive and then revert back to normal. The revert part being the hard one. Maybe make the ++speed only works when overdosed and then below normal levels, it just does hunger_factor = initial(hunger_factor)

**Comment by SpadesNeil** [comment]
Yes

**Comment by SpadesNeil** [comment]
cyka
