### ISSUE TITLE
Fluff items - two characters - Miria Masters

### ISSUE THREAD

**Issue by MiriaMasters** [VOREStation/VOREStation#790]
Name of Item: Dragon Fluff, Dragon Fluff ear, 9 tail black and grey tail, 9 tail black and grey ear.

Item description: Dwagon bits for Miria, Kitsune bits for Levias Fei

Sprites (or link to sprites): http://www.mediafire.com/file/yhgw1kn9da7fo68/dragon_and_9tail_project.dmi

Any additional resources: None that I know of...?

BYOND Key (Username): Miria Masters

Name of Character: Miria, Levias Fei

Main Job(s) of Character: Miria is undecided, though likely to end up doing some kind of manual labor. Levias Fei will probably be medical, but I'm hoping to RP her into learning how, rather than automatically knowing.

Why your character should have this item: Because a dwagon needs wings/horns/ears/tail, and a kitsune needs ears/tails~

Additional Notes (If it's a permit, insert the information for the permit here): Not sure what this is all about... Do I need a permit for my own body parts?

Fluff Item slots already used: I currently have no fluff items.

On a side note, I'd like to thank Molenar for the wonderful work they put into the items, rather or not they get accepted, I greatly appreciate it. <3

If I made any mistakes filling this out, let me know. I'll do my best to help fix the problem. .w.

EDIT: I simply copy/pasted this from the forum post, I was told to put this in "Issues", dunno if that's right or not?... hopefully everything is in order now.

EDIT THE SECOND!: I made a mistake when copy/pasting this... my bad... the link to the items was broken. QwQ

**Comment by Arokha** [comment]
Merged PR that added these.
