### ISSUE TITLE
Synthetics can lose weight

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#791]
#### Brief description of the issue
Synthetics can lose weight by using exercise machines but are physically incapable of gaining weight.

#### What you expected to happen
Synthetics should not be affected by any weight gain/loss mechanics at all.

#### What actually happened
See description.

#### Steps to reproduce
- Use exercise equipment.
- Weigh self.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/8cef69e9dfa98ce401b032765f7229d41e941a65

**Comment by OrbisAnima** [comment]
The problem you have here is that FBPs arent their own race, so we cant do a check per race.

Best I can think of is using a check for the torso organ, if its synth, then make them inmune to it.

**Comment by SpadesNeil** [comment]
I _think_ this is fixed.
