### ISSUE TITLE
Classic Tajara Hairstyles displaying incorrectly

### ISSUE THREAD

**Issue by DrunkArcher** [VOREStation/VOREStation#792]
#### Brief description of the issue
Classic Tajara haircuts don't show properly, with part of the character head's sprite being displayed over it (Specifically where human ears would otherwise go)

#### What you expected to happen
Tajaran hair displaying properly with old race-specific hair styles (Such as Tajaran Straight), along with the hairstyle-included ears appearing properly over the head's sprite.

#### What actually happened
Character's head displayed over the hair sprite.

#### Steps to reproduce
- Simply use any of the old tajaran-specific hairstyles (From "Tajara Ears" to "Tajara Messy"). The new added ones seem to display as intended.

#### Code Revision
- release - 2016-12-30
 
#### Anything else you may wish to add:
- https://i.gyazo.com/4f882d8e13bd68745ece3fc93a153b78.png
- https://i.gyazo.com/3fd5a3ea7acddd44f15d255964f89ae0.png

**Comment by Arokha** [comment]
That's how those hairstyles actually are.

![image](https://cloud.githubusercontent.com/assets/15028025/26387642/347a669a-401d-11e7-8bf6-c4d78ba38fbd.png)
