### ISSUE TITLE
Proteans can't repair their NIFs

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#7928]
#### Brief description of the bug
There is no apparent way of repairing a Protean's NIF.

#### What you expected to happen
To be able to repair my NIF

#### What actually happened
To try all the ways and fail.

#### Steps to reproduce
- Notice your NIF's durability being low as a protean.
- Go to science to get it fixed.
- Try the synth method, no hatch to open.
- Drink nanites, can't process them.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: b8f7ff3b2e95c803fe5ffe43c6411e50ce227674
 

#### Anything else you may wish to add:
- If there is a special way, should be documented.

**Comment by Arokha** [comment]
Their nif self-repairs between rounds, it always starts at a random durability, but won't wear down over time.

**Comment by TheToaster98** [comment]
Okay, that also explains how my NIF went from 98 to 30% in a single round, thank you for explaining.
