### ISSUE TITLE
Fluff Items-Two characters-Samanthafyre (UPDATED WITH SPRITES)

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#794]
Name of Item:Kat's Navy Engineer voidsuit

Item description: Taur engineering voidsuit. Recolored navy blue and white. Slightly tweaked as well to add about as much armor as a security voidsuit With a slight reduction in movement speed to compensate for custom padding and armor Kateryna made herself.(try to keep it short and sweet)

Sprites (or link to sprites):https://puu.sh/tRjKJ/d6f1aa6c85.dmi

Any additional resources:none at the moment

BYOND Key (Username):samanthafyre

Name of Character:Kateryna Petrovitch

Main Job(s) of Character:Engineering/Security

Why your character should have this item:She has always and still is aspiring to join the navy as a engineer so naturally she wants to feel like she belongs. She customized a suit of engineering armor her dad bought for her with some extra padding and such and figured it would be a great tool of trade on station too.

Additional Notes (If it's a permit, insert the information for the permit here):

Fluff Item slots already used: 1 If this is accepted it will be 3
------------------------------------------------------------------------------------------------------------
Name of Item:Ivy's Canine unit mask

Item description:Its just a simple recolored pink and renamed facemask that fits over a Foxes muzzle. It sports a couple decorative spikes on the cheeks to look intimidating. (try to keep it short and sweet)

Sprites (or link to sprites): Should be in the code due to the most recent update. Its literally the facemask. just recolored.

Any additional resources:Nope.

BYOND Key (Username):samanthafyre

Name of Character:Ivy Lannister

Main Job(s) of Character:Security

Why your character should have this item:She doesn't commonly use the given facemasks and has issues with it fitting on her face so a canine mask like a muzzle over her nose and mouth would make sense wouldn't it?

Additional Notes (If it's a permit, insert the information for the permit here):not a permit.

Fluff Item slots already used:0

**Comment by JoanRisu** [comment]
Might hafta lower the armor to _just_ below security rated armor on the void suit. Maybe. 

Other than that, however, I don't have a problem with this app.

**Comment by DemicusMaximus** [comment]
Note: Application was already approved for the player, they're just changing which character it's meant for.
