### ISSUE TITLE
Belly Transition Not Showing Description

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#796]
#### Brief description of the issue
When someone resists and transfers into a second belly, the text of that belly's description is not displayed.

#### What you expected to happen
The description to display like when eating them normally.

#### What actually happened
A simple message that they had been moved was displayed instead.

#### Steps to reproduce
- Be prey
- Get eaten
- Resist until transferred to a second belly

#### Code Revision
- df6ded37b5f0ab894eadb6a06c90510e93923e5e 
 
#### Anything else you may wish to add:
- N/A

**Comment by SpadesNeil** [comment]
Possibly related to https://github.com/VOREStation/VOREStation/issues/763

@Cameron653

**Comment by SpadesNeil** [comment]
Yes, related. Duplicate bug. Closing this.
