### ISSUE TITLE
Protean blobs that enter vents while dragging something break the laws of matter conservation

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#7977]
#### Brief description of the bug
If you drag something while ventcrawling, that thing is deleted from this plane of existance.

#### What you expected to happen
To not have the power to ERASE everything.

#### What actually happened
Lost my backpack.

#### Steps to reproduce
- Play as protean, Toggle Blobform
- Drag something.
- Enter vent.
- Move a couple tiles.
- Observe as the thing is now erased of this world, this is my stand.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 9e27f03747c1ae51db2166fdc37ede2eef8b596c
TGS version: 4.2.3
DMAPI version: 5.1.1

**Comment by Arokha** [comment]
It actually moves it into the pipe after you, but there's no way to retrieve it.
