### ISSUE TITLE
Teshari micro sprites look strange, don't function well upon pickup from a macro

### ISSUE THREAD

**Issue by BothNevarBackwards** [VOREStation/VOREStation#798]
#### Brief description of the issue
If you have a macro character pick up a normal sized teshari (or a micro etc.) they still get the in hand sprite, except that sprite is scaled up to macro size. In addition, the teshari sprite didn't have taur body, horns, changed tails, etc. making it so it didn't look like my character when it happened.

#### What you expected to happen
I expected my character to be picked up as a small character normally is, held in hand and placeable in pockets as usual.

#### What actually happened
My character was picked up with the teshari mechanics, showing a very large and mismatched sprite in the hand of the person who picked me up. Additionally, I wasn't able to be placed in pockets as the teshari pickup mechanics don't allow for it.

#### Steps to reproduce
- Have a tesari base character and a two+ sizes larger character.
- Have the two sizes larger character pick up the teshari character.

#### Code Revision
Server revision: release - 2016-12-30
df6ded37b5f0ab894eadb6a06c90510e93923e5e 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by OrbisAnima** [comment]
maybe removing the in hand mechanics? another solution would be making teshari of normal size for the polaris tags, but keeping them out of the push and shove lists, that would resolve the code but the whole teshari being able to be picked up would be fixed. Another posibility is that the teshari pick me up stuff is overwritten if the vr system is used, but its clear both systems cannot work in paralel.

**Comment by OrbisAnima** [comment]
uh... checking the code I saw that this was taken care of the way I am mentioning
/datum/species/teshari
	mob_size = MOB_MEDIUM
is this still a bug?

**Comment by BothNevarBackwards** [comment]
It ended up looking like this to pick up a micro tesh with a macro human 
![image](https://cloud.githubusercontent.com/assets/24940805/21739238/e248670c-d463-11e6-9f1c-6573682ba7e3.png)

**Comment by OrbisAnima** [comment]
To be expected, since teshari are accesories, so if they have the right size they will reflect on the body like that

**Comment by BothNevarBackwards** [comment]
Yup! But it make a bunch of people take pause and not carry my character as it was so jarring. I fixed it though, pull just needs to go through.
