### ISSUE TITLE
Colourable Nevrean tail much too light

### ISSUE THREAD

**Issue by BothNevarBackwards** [VOREStation/VOREStation#799]
#### Brief description of the issue
The colourable tail selectable in the vore panel is very light, with the darkest black showing up as light grey.

#### What you expected to happen
I expected the tail to be the colour I selected (in this case black)

#### What actually happened
The tail was much much lighter than the colour I selected, in this case showing as light grey.

#### Steps to reproduce
- Go to the character create menu.
- Select the colourable nevrean tail from the tail options.
- Colour the tail any colour

#### Code Revision
Server revision: release - 2016-12-30
df6ded37b5f0ab894eadb6a06c90510e93923e5e 
 
#### Anything else you may wish to add:
![snap 2017-01-05 at 11 27 20](https://cloud.githubusercontent.com/assets/24940805/21688324/68285628-d33a-11e6-80e4-81982689e0a6.png)

**Comment by Screemonster** [comment]
This'll be because teshari (and the colorable tail code on most species) are color-add while the base sprite for nevrean tails is intended for color-mult.

**Comment by Molenar** [comment]
would like to put a request on this fix that the existing one not be discarded as I and a few others i've seen use the lighter one for effect, and instead add in one that uses the black style color-mult as an additional tail.

**Comment by SpadesNeil** [comment]
Did this get fixed?
