### ISSUE TITLE
Space Carp spam knockdowns like there's no tomorrow.

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#7990]
#### Brief description of the bug
Carps spam knockdowns.

#### What you expected to happen
Get knocked down for a while, eventually get up

#### What actually happened
Repeatedly knocked down until death with zero ways to fight back.

#### Steps to reproduce
- (Step 1) Fight carps
- (Step 2) Get knocked down.
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 d0c17152faa04f9eede2c6c1e99ac9ddb14d591d

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Probably to make it more likely for them to eat you alive and stuff, if you have mob vore on, otherwise they wouldn't have a chance.

**Comment by Zeldazackman** [comment]
It's especially annoying if you've got digestable toggled to off as they'll still see fit to perma stun-lock you worse than the painter's curved in DS3 [as seen here](https://youtu.be/uLU1jt_HYQ4).

Add onto the fact that armour doesn't actually help protect against a mob's default digestion speed of 2 / 2 brute and burn respectively and it's just another case of the usual factor of events making life hell for engineering more than anything.
