### ISSUE TITLE
Material Auto-stack is broken

### ISSUE THREAD

**Issue by ExabyteDiscord** [VOREStation/VOREStation#7991]
#### Brief description of the bug
The auto stacking for materials when making (IE, making multiple steel rods, reinforced glass), instead of stacking whatever's made with whatever's on the floor, renders the item unusable since it vanishes. Continuing to make items spams that "There is now 1 item in the stack" but the item is ultimately not clickable and doesn't even exist in a playable area.

#### What you expected to happen
Items stack when multiple are created on the same tile.

#### What actually happened
Your materials vanish.

#### Steps to reproduce
- Get a stack of steel, or steel rods and glass (basically anything that can make stackable materials)
- Spam the button to make several stacks individually
- Become sad once you realize that your materials are now gone

**Comment by Arokha** [comment]
Hmm, it's not supposed to stack things when they're *created* because of another issue that came up, only when they're pulled or dropped by someone.
