### ISSUE TITLE
Low active user restriction on psychologist/psychiatrist role may hinder roleplay.

### ISSUE THREAD

**Issue by BossVoss** [VOREStation/VOREStation#800]
#### Issue Summary
Presently, the psychologist/psychiatrist role slot is limited to 1 active crewmember. As the psych role is heavily roleplay-focused, a psychological evaluation or therapy session may take multiple hours per patient, and this can easily lead to a backlog of crew requesting appointments, even on a slow day. Additionally, patients may want followup appointments with a particular psych professional, and the one on duty may have nothing active to do while filling the slot and preventing the desired psych professional from joining. These two issues tend to result in a feast-or-famine aspect to playing the psych role, and in both directions less roleplay is the outcome.

#### Change Suggestion and Rationale
I propose that the active user restriction on the psychologist/psychiatrist role be raised to 2. This will increase capacity when there are multiple crewmembers who are requesting appointments, and increase flexibility when crewmembers have a preference for who they see for an appointment. This adds to the potential roleplay on the station for players who want their characters to have a means of managing their stress and who want to play out evaluations as protocol after traumatic situations on the station.

#### Counterpoints and Responses
Presently, the issue can be sidestepped by signing on as another role and requesting a job change from the HoP or CD. However, while this is likely to not be a problem to add another psych role in-game, that raises the question of why the extra step is necessary. It takes up two players' time, potentially interrupting important scenes, to make the job change immediately upon signing in.

It may be said that in the "famine" side of the feast-or-famine, increasing the number of active psych roles to 2 only leads to 2 players sitting around and doing nothing rather than 1. To me, this is not necessarily a negative, as some of the players who desire the psych role would otherwise not sign on at all (so it is not necessarily a loss to other areas for them to be idle), and them doing so increases the server population and potential for activity and roleplay elsewhere in the station.

While there is official space on the map for only one psych professional, one office should still be sufficient even when both are actively seeing patients. The Medical break room, for instance, can serve as space for counseling.

**Comment by Arokha** [comment]
I dunno if the medical break room is really an appropriate place for some therapy sessions, heh. They might be able to find other places, but it seems kinda shifty to me. Maybe there's space for another office somewhere, or some way to slightly increase the psych office size but partition it into two parts.

**Comment by Wickedtemp** [comment]
Sub-acutes, while small, can be used. Tintable windows, all you'd have to do is say "Appointment in session in Sub-Acute A/B/C/D"

Given the number of sub-acutes, I highly doubt we'll ever see a day where ALL of them are in use.

**Comment by Arokha** [comment]
This is stalled, so I'm closing it until someone puts it forward again. Last I heard, people said not to because of office space while making Tether, so.
