### ISSUE TITLE
Taur Rear Ends Clipped Off in Character Preview

### ISSUE THREAD

**Issue by KasparoVy** [VOREStation/VOREStation#8028]
#### Brief description of the bug
Mild side-effect of #8021 causes the rear ends of some long bois to be clipped off in the character creator.
My only gripe, otherwise it's bloody awesome.

#### What you expected to happen
I wanted to see it all, man!

#### What actually happened
Docked the tail and clipped the arse.

#### Steps to reproduce
- Connect to the server
- Open Character Setup
- Be a taur

#### Code Revision
- aab9c42f961c35db35969f0cce93ce4b9d61490d
 
#### Anything else you may wish to add:
Drake and otie taurs for example, but also affects nagas, wasps, lizards and felines
![virgo ss13 clipped taur butt 20200522](https://user-images.githubusercontent.com/12377767/82632008-8be44e00-9be6-11ea-88a9-8d4bc8e91638.PNG) ![virgo ss13 clipped taur butt 2 20200522](https://user-images.githubusercontent.com/12377767/82632254-38becb00-9be7-11ea-82f3-2e681d67770b.PNG)

I know it sounds snowflakey as fuck but maybe the east-west sprites should be centered normally and offset + canvas expanded only if there's a big ol' taurbutt.

**Comment by Arokha** [comment]
Taur butts are illegal is the thing.

**Comment by KasparoVy** [comment]
https://www.youtube.com/watch?v=bBD8M3WFrAw
Watchu gonna doooooo

**Comment by lbnesquik** [comment]
Still true
