### ISSUE TITLE
Mapping Issue-Lacking cable towards Security SMES.

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#8033]
#### Brief description of the bug
There is a missing cable on security maint, and it stops the whole department from getting power.

#### What you expected to happen
Security having power.

#### What actually happened
Security has no power and I have to dive into maint.
 

#### Anything else you may wish to add:
- https://cdn.discordapp.com/attachments/657595660748587048/713399816763211848/unknown.png

**Comment by Arokha** [comment]
![image](https://user-images.githubusercontent.com/15028025/82679947-9ff57300-9c19-11ea-982d-0e8d1f66a2ad.png)

It does not appear to be mapped that way. This may have been done in-round.

**Comment by TheToaster98** [comment]
...I see.
Please close it then, it had happen many shifts in a row but I didn't expect it to be a HAHA FUNNI.

**Comment by Arokha** [comment]
Wait, no, it's not mapped in like that but it does start the round like that. I suspect this is a Byond bug. There was a bug a while ago about the 65535th map object having problems, and I suspect that cable piece is the 65535th map object.

**Comment by Arokha** [comment]
Leshana confirmed that this is a byond bug. The first object after 65535 on the map ignores whatever the mapped-in values for it's vars are.

**Comment by Arokha** [comment]
http://www.byond.com/forum/post/2573596
