### ISSUE TITLE
Protean blobs kill GPS

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#8035]
#### Brief description of the bug
If a protean blobs while carrying a GPS on their pockets, all GPS die.

#### What you expected to happen
To allow others to track me when blob.

#### What actually happened
I killed all the GPS

#### Steps to reproduce
- Put GPS on pockets.
- Change form to blob.
- Ask someone to check their GPS.
- GPS don't work.

#### Code Revision
Server revision: B:release D:
Commit: 7dabc6783f119bf51d686779714bb64203a920cd 
 

#### Anything else you may wish to add:
- This was tried with an active GPS and everyone who checked was on the same Z-level, maybe having it off or being on a different Z-level changes the results.

**Comment by Arokha** [comment]
This isn't especially fixable in terms of making the blob trackable. The GPS goes with your human body to nullspace.

It shouldn't break all the other GPSes, though, I can fix that.
