### ISSUE TITLE
Medical Record Formatting

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#807]
#### Brief description of the issue ####
You know that issue with the OOC Notes formatting being bleh? Same thing here, only not as bad. Line-breaks in IC records get ignored, depending on how you view the records. 

#### What you expected to happen ####
Look at Medical Records by examining someone with an HUD. The records stay correctly formatted the way they were written... Now look at the records through the 'Med Records' app in the PDA. Should still keep the format.

#### What actually happened ####
But it didn't keep the format. It's a giant wall of text that's a pain in the arse to read. Especially with characters who have a long record.

#### Steps to reproduce ####
- (Step 1) Write the Med Record, a long and detailed record.
- (Step 2) Struggle to read it with the PDA Records.

#### Code Revision  ####
Server revision: release - 2016-12-30

#### Anything else you may wish to add: ####
Viewed through the HUD - Fine.
Viewed via PDA - NOT fine.
Viewed via medical-laptop - ???
Viewed via physical copy of records - ??? 
Latter two need to be checked real quick.

Here's a screenshot of the first section of Tempest's records, with line-breaks. And then the PDA's records, with those line-breaks deleted. It's horrendous to try to read. http://imgur.com/a/zN877

**Comment by Leshana** [comment]
Problem also exists for security records in PDA.
Problem does not exist on medical records computer, printout from medical records computer, or security records computer.
Problem is the nano templates are HTML, just need to set styles on those fields to fix.

**Comment by ArbyTheDragon** [comment]
It's just part of what makes PDA inferior to the actual console IMO. There's a reason to actually use the console then!
