### ISSUE TITLE
Waist Holster disappearing completely if you attach an webbing of any kind

### ISSUE THREAD

**Issue by YeetBoi68** [VOREStation/VOREStation#8072]
#### Brief description of the bug
the disappearance of a waist holster once you put on a webbing, Along with the weapon.

#### What you expected to happen
ussually it would say “This acessory cannot be attached” and not do anything.

#### What actually happened
Literally just grabbed a waist holster, forgot that i had it on, and attempted to place the webbing on and poof there goes the holster with my weapon.

#### Steps to reproduce
step one:attach your waist holster
step two:attach webbing
step three:poof

**Comment by lm40** [comment]
you should be able to wear one holster with a webbing, i'm pretty sure

also i'm not able to reproduce this
