### ISSUE TITLE
Repairing a protean nif isn't possible at the moment

### ISSUE THREAD

**Issue by Voidalynx** [VOREStation/VOREStation#8082]
#### Brief description of the bug
Repairing a protean nif isn't possible at the moment.

#### Steps to reproduce
- Try any normal NIF repair means (including drinking nanites out a cup)

#### Code Revision
- 0f8cac756e85b26df7a667ff31d30af74013e214

**Comment by TheFurryFeline** [comment]
#7928 duplicate

**Comment by TheToaster98** [comment]
This was already reported, the NIF starts at a random percentage each time you are spawned.
https://github.com/VOREStation/VOREStation/issues/7928

**Comment by Arokha** [comment]
See #7928 
Protean NIFs start each round at a random percentage, which is intentional, and if broken at the end of a round, will start the next round working, at a random percentage.
