### ISSUE TITLE
Protean with system instability heal forever

### ISSUE THREAD

**Issue by Voidalynx** [VOREStation/VOREStation#8088]
#### Brief description of the bug
Proteans who gained system instability will (whilst in blob form) heal forever and use all of their metal storage up without actually healing the instability.

#### What you expected to happen
The metal storage should not decrease.

#### What actually happened
The metal storage slowly ticks down slowly until it is fully consumed.

#### Steps to reproduce
- Gain radiation damage or system instability another way
- Enter blob form

#### Code Revision
- c41156173defe6b735d7e55c5c60bb8a65ff1194
 

#### Anything else you may wish to add:
- System instability can be fixed by going into a cyborg charger. For now, this is a workaround.

**Comment by Arokha** [comment]
System instability (aka radiation) is *supposed* to be fixed by a cyborg charger. That's the intended way to fix it. Using metal up forever is the bug there, not the need to use a charger.

**Comment by Voidalynx** [comment]
@Arokha Yes that was the intention here. It would be a bit overpowered if they could heal instability themselves without going to a charger after all!
