### ISSUE TITLE
Monkey cloning by cooking

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#810]
#### Brief description of the issue
Monkeys spawn a second monkey when fried or baked or made into candy or grilled.

#### What you expected to happen
To get ONE friend/grilled/baked/candy monkey

#### What actually happened
Infinite monkeys.

#### Steps to reproduce
- (Step 1)Make monkey
- (Step 2)Try to cook it in the grill/fryer/candymaker/oven
- (and so on)

#### Code Revision
Server revision: release - 2016-12-30
df6ded37b5f0ab894eadb6a06c90510e93923e5e

**Comment by OrbisAnima** [comment]
happens also in Baystation

https://github.com/Baystation12/Baystation12/issues/15104

**Comment by SpadesNeil** [comment]
fucking lmao
