### ISSUE TITLE
EAL Implant teaches every language

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#812]
#### Brief description of the issue
When you use the EAL implant, in addition to allowing you to pass the can_speak_special() checks for speaking in EAL, it also teaches you every language since it's a child of the normal language implant item that does that.

#### What you expected to happen
To just learn EAL. It's a loadout item, so that's probably a little OP for teaching EVERY language.

#### What actually happened
Learned every language, and EAL.

#### Steps to reproduce
- Get EAL implant from loadout menu
- Learn every language e-z

#### Code Revision
- release - 2016-12-30 df6ded37b5f0ab894eadb6a06c90510e93923e5e

**Comment by OrbisAnima** [comment]
cant we not just pump the cost, rename it and advertise it as a feature? :P

**Comment by OrbisAnima** [comment]
or even as a traitor item...

**Comment by SpadesNeil** [comment]
Wasn't the EAL implant added by Polaris?

**Comment by Techtypes** [comment]
I am using it and not even getting encoded audio... in fact i get everything else besides it really.

**Comment by Arokha** [comment]
This is fixed now. The EAL implant only (physically) allows you to use EAL now. It doesn't teach you EAL (as it wasn't intended to do this)
