### ISSUE TITLE
Special prey interactions affecting wrong belly

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#813]
#### Steps to reproduce
- Create a second organ
- Give the organ any chance to absorb
- Prey in that organ uses the Resist verb until this chance triggers
- First organ gets set to Absorb rather than the organ the prey was in

#### Code Revision
- cda702a5ee2a28c08723ba6397219c1bb609bcaa (I cloned as zip from this point, deleted the old folders and performed a clean compile)

**Comment by SpadesNeil** [comment]
@Cameron653

**Comment by Cameron653** [comment]
Ack, I'll look into this. The stomach interactions are a bit hard to get right, so this might take a bit.

**Comment by Cameron653** [comment]
Just tested it and I can confirm this occurs with digestion, absorption, and escaping. Looking into a fix now.
