### ISSUE TITLE
AI holopads layer underneath floor decals

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#8162]
#### Brief description of the bug 
AI holopads are layered below floor decals.

#### What you expected to happen 
AI holopads to be above floor decals.

#### What actually happened
Holopads get covered and partially/completely hidden by certain floor decals.

#### Steps to reproduce
- (Step 1) Find a holopad on a tile that has floor decals.
- (Step 2) See the decals go on top of it.

#### Code Revision
- e669ba1d061675b672ae6407c5df2ec8970fc8c3
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
This appears to now be an issue with a whole bunch of things. Also firelocks (floor firelocks at least) and, when looked from a level higher can sometimes layer over any other objects on tile in open space.
