### ISSUE TITLE
Map issue on the Zoo map.

### ISSUE THREAD

**Issue by OrbisAnima** [VOREStation/VOREStation#817]
#### Brief description of the issue
There was a report of an edge on 1 or 2 on server start when loading the zoo away mission

#### Steps to reproduce
go to the middle arrival ship, check the entrance, its II O II O II instead of II O O II
https://cdn.discordapp.com/attachments/187013248309002240/268107938479079425/unknown.png

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Not a bug. this was made like this deliberately. The airlocks are designed in such a way that any standard ship can safely dock with them regardless of having a single or double airlocks. Note the door on the left is bolted shut. This is on purpose.
