### ISSUE TITLE
Warning on compile

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#818]
#### Brief description of the issue
There's a warning when you compile

#### What you expected to happen
No warning

#### What actually happened
Got a warning

#### Steps to reproduce
- Compile code

#### Code Revision
- b19e1e191a1f059985b1a62ffcb3e6571794a735
 
#### Anything else you may wish to add:
Line in question causing the warning (If statement has no effect)
https://github.com/VOREStation/VOREStation/blob/master/code/modules/organs/organ_icon.dm#L152

Should this line also be commented out or should it be made so its 

```
else if(s_col && s_col.len >= 3)
	applying.Blend(rgb(s_col[1], s_col[2], s_col[3]), ICON_MULTIPLY)
```

**Comment by BothNevarBackwards** [comment]
What warning does it give?

**Comment by Cameron653** [comment]
code\modules\organs\organ_icon.dm:152:warning: if: if statement has no effect

That's the error

**Comment by BothNevarBackwards** [comment]
Weird

**Comment by SpadesNeil** [comment]
https://github.com/VOREStation/VOREStation/pull/806 is why.
