### ISSUE TITLE
pAI suicide deletes the pAI card

### ISSUE THREAD

**Issue by Voidalynx** [VOREStation/VOREStation#8196]
#### Brief description of the bug
pAI suicide deletes the pAI card.

#### What you expected to happen
The card left intact and just replaced with a blank empty card.

#### Steps to reproduce
- pAI suicide and watch the card vanish.

#### Code Revision
- bd4c2d17d818928d024024e8acd8c1c3d76d8bf6

**Comment by KasparoVy** [comment]
That is so hardcore.
Nanite self-termination, like cell lysis but techier. Dissolve into nothing!

Rest In PAI
