### ISSUE TITLE
Adding end-of-round persistence

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#82]
I would like to make it possible to save statistics like flavor text, hair style, body weight, (etc) at the end of the round. This way people who like things like weight gain, transformation, or just want to save their flavor text at the end of a game and forget to do it after 6 hours can just toggle this on and off and have it automatically saved when the round ends regardless of being logged in or not.

Parameters of this issue being resolved:
- [ ] Should work <s>even if</s> when player has logged out, if possible. Maybe an option to save stats manually if this is not possible.
- [ ] You must be alive at the end of the round. If you're dead, nothing is saved!
- [ ] A manual mid-round "save current appearance" button might be nice. It is my understanding that in Polaris you can open your character prefs at any time now.
- [ ] You must have random name set to false, or nothing can be saved. The random name option overrides and stops any saving at all because it's assumed to be a randomly chosen character.
- [x] Going into cryo should save your information as it would during round end.
- [x] Going into robotic storage should also save information as it would during round end.
- [ ] Verb to toggle persistence mid-round in case you don't like some changes. This belongs under the "Preferences" tab or "OOC" tab.
- [x] Toggle persistence in character preferences and on mobs should be, turned off by default in player prefs.
- [ ] Flavor text should be saved.
- [x] Body weight should be saved (up to 500).
- [x] If when saving body weight, nutriment is over 450, calculate how much that would be in added weight. **if (nutrition > 450 && weight < 500 && weight_gain) weight += metabolism_(0.01_weight_gain)** is how it is normally calculated. In this case, **if (nutrition > 450 && weight < 500 && weight_gain) weight += (0.01_weight_gain)_(0.0285*(nutrition-450))** The reason I choose this number is because at 100% realism weight gain, the human body is worth ~30 pounds of weight gain, and you gain 1050 for an average human, so 30/1050 =  about 0.0285 so there's my math. :U
- [ ] Body appearance (including hair style, colors, taur body, scale, etc) should also be saved.

I am told this should not require SQL to work. If we figure out how to do this, it is potentially possible we can have other persistent features as well including bank accounts and taking certain items home to keep for bringing on board in the future.

This issue was planned for old Vorestation but never implemented. In the old server, gameticker.dm was where saving should have been done at end of round.

```
/datum/controller/gameticker/proc/declare_completion()
    world << "<br><br><br><H1>A round of [mode.name] has ended!</H1>"
    for(var/mob/Player in player_list)
        if(Player.mind && !isnewplayer(Player))
            if(Player.stat != DEAD)
                // If player has persistence turned on and is still a human
                    // If weight gain, calculate the amount of weight they should gain according to their final nutrition value, and add it to their current weight. I can do this. -Spades
                    // Save player stats such as weight, scale, flavortext, and physical appearance.
                var/turf/playerTurf = get_turf(Player)
                if(emergency_shuttle.departed && emergency_shuttle.evac)
                    if(isNotAdminLevel(playerTurf.z))
                        Player << "<font color='blue'><b>You managed to survive, but were marooned on [station_name()] as [Player.real_name]...</b></font>"
                        // Save player to spawn at Cryo next time they join.
                    else
                        Player << "<font color='green'><b>You managed to survive the events on [station_name()] as [Player.real_name].</b></font>"
                        // Save player to spawn at Arrival Shuttle next time they join.
                else if(isAdminLevel(playerTurf.z))
                    Player << "<font color='green'><b>You successfully underwent crew transfer after events on [station_name()] as [Player.real_name].</b></font>"
                    // Save player to spawn at Arrival Shuttle next time they join.
                else if(issilicon(Player))
                    Player << "<font color='green'><b>You remain operational after the events on [station_name()] as [Player.real_name].</b></font>"
                else
                    Player << "<font color='blue'><b>You missed the crew transfer after the events on [station_name()] as [Player.real_name].</b></font>"
            else
                if(istype(Player,/mob/dead/observer))
                    var/mob/dead/observer/O = Player
                    if(!O.started_as_observer)
                        Player << "<font color='red'><b>You did not survive the events on [station_name()]...</b></font>"
                else
                    Player << "<font color='red'><b>You did not survive the events on [station_name()]...</b></font>"
    world << "<br>"
```

**Comment by Arokha** [comment]
> Must work even if player has logged out.

Savefiles are associated with the 'Client' object. The data being saved is the data in the 'prefs' variable on Client. If they leave, there's no Client, so this isn't possible. It would be better to save **when** they logout if they have persistence turned on, it can't be done 'after'.

**Comment by Arokha** [comment]
> You must have random character set to false, or nothing can be saved. The random character option overrides and stops any saving at all.

There's no 'random character' option. The way it works is that if you've never saved a character into a slot, then it randomizes things every time. You could base it on 'always be random name' setting though.

**Comment by Arokha** [comment]
> Verb to toggle persistence mid-round in case you don't like some changes. This belongs under the "Preferences" tab or "IC" tab.

I vote preferences or OOC honestly because it's not something the character is ICly aware of as a toggle.

**Comment by Arokha** [comment]
> turned on by default in player prefs

Introducing new options already turned on is a great way to piss people off. We talked about this before and agreed it should be off by default. What changed?

**Comment by Arokha** [comment]
> including bank accounts

I talked about this in the Polaris Discord actually, and we kinda agreed it was a bad idea. You'd quickly have huge sums of money based on how much you're paid. We'd have to make the pay much, much less. And charge rent or something I dunno.

**Comment by SpadesNeil** [comment]
> There's no 'random character' option. The way it works is that if you've never saved a character into a slot, then it randomizes things every time. You could base it on 'always be random name' setting though.

That is what I meant, yes.

> I vote preferences or OOC honestly because it's not something the character is ICly aware of as a toggle.

Preferences tab it is, then.

> Introducing new options already turned on is a great way to piss people off. We talked about this before and agreed it should be off by default. What changed?

I forgot.

**Comment by SpadesNeil** [comment]
My understanding is that @Leshana is handling this? If so, assign yourself, Leshana!
