### ISSUE TITLE
Belly TF is not finishing properly.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#8211]
#### Brief description of the bug
-Using the belly TF mechanic to transform someone's species does not refresh their organs anymore.

#### What you expected to happen
-For the transformation to complete the job and not leave the body with the incompatible organs of the old species.

#### What actually happened
-A prommie was TF'd into a custom zorren, their species var was changed, but al their organs were still slime type and they suffocated to death.

#### Steps to reproduce
- (Step 1) Belly TF a prommie into non-prommie.
- (Step 2) See them suffocate.
- (Step 3) Check their vars and see all the organs are still slime type despite the species having been changed.

#### Code Revision
- bd4c2d17d818928d024024e8acd8c1c3d76d8bf6
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by cadyn** [comment]
Fixed. Was just missing a couple lines of code. Enjoy your Prommie->Zorren TFs soon as this gets merged. Must've been a bit of a scene ruiner when you realized your prey was fucking suffocating to death.
