### ISSUE TITLE
Having an OOC one of my other character's instead of the current one's

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#824]
#### Brief description of the issue
When I was waltzing about, a friend told me I had one of my other character's OOC prefs, which not only spoiled who I was with that character, but also it could be misleading to others if they saw me. When I went to fiddle with my other character's profile INGAME, not in the lobby, it took the description from him, but when I swapped back, I could see my character's original OOC again.

#### What you expected to happen
To still have my character's OOC, not my other character's OOC

#### What actually happened
My other character's OOC appeared instead of my current character's OOC

#### Steps to reproduce
- Spawn in
- Check your current OOC
- Go to preferences>Character Setup on the topright
- Load a different character
- Check your OOC again and behold!

#### Code Revision
- release - 2016-12-30

**Comment by Arokha** [comment]
Yes, that is how the OOC flavorstuff works. It's not copied to your character since it's sort of metainfo stuff. If someone wanted to fix it, they should update the copy_to prefs stuff and make a new var on humans that stores the metainfo and read from that in the examine proc.

**Comment by DeepIndigo** [comment]
This is fixed by just loading the right character again. My gut tells me trying to fix this will break ooc text in general. Call it a life-time gamer's hunch.
