### ISSUE TITLE
Poncho Front/Back Sprites Off

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#826]
#### Brief description of the issue
The poncho item exposes a few pixels of the shoulder from the front and back.

#### What you expected to happen
The poncho to line up with the shoulder.

#### What actually happened
The poncho item exposes a few pixels of the shoulder from the front and back.

#### Steps to reproduce
- Get a poncho

#### Code Revision
- df6ded37b5f0ab894eadb6a06c90510e93923e5e
 
#### Anything else you may wish to add:
- https://www.dropbox.com/s/cs1nkj8mpu4kjm2/Screenshot%202017-01-12%2022.44.40.png?dl=0
- I suspect this may be an upstream issue. However, I do not know how to report upstream issues yet, or whether they'd take a screenshot from downstream as valid evidence.

**Comment by Vorrarkul** [comment]
Addendum: Not only the green poncho is affected. It seems they all show a little shoulder. I don't believe it's necessary to provide examples of all of them, but I can get the screenshots if need be.

**Comment by Arokha** [comment]
Probably fixed, reopen if still a problem. (Polaris bug, though, so open with them)
