### ISSUE TITLE
Surface security cryopods are broken.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#8266]
#### Brief description of the bug
-The cryopod(s?) in surface security brig aren't working properly. They fail to actually cryo the person and finish the job, while printing errors on adminlog on each attempt
ADMIN LOG: Cryopod in the Surface Security Brig could not find control computer! 

#### What you expected to happen
-For the person trying to use them to get cryo'd out.

#### What actually happened
-The person was never removed from the pod, leaving them in the round and the pod occupied.

#### Steps to reproduce
- (Step 1) Watch someone attempt to leave the round via surface brig cryopod.
- (Step 2) ADMIN LOG: Cryopod in the Surface Security Brig could not find control computer! 
- (Step 3) Person still stuck in the pod.
- (Step 4) watch the error message pop up over and over again until you admin-cryo the person inside.

#### Code Revision
- d53009f1538b47ccc7ed4f6189f72a61857d9327
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Rykka-Stormheart** [comment]
Mapping issue, most likely. They just need controllers placed in those rooms.

I can do it in a bit unless someone else does it first. The computers don't even need varediting - just make sure there's one per /area/ that has a cryopod (or multiple).

**Comment by Heroman3003** [comment]
Ideally the controllers should be mapped outside brig itself (though still connected to pods) since technically they are supposed to dispense items destroyed during cryoing (even if we have it disabled).
