### ISSUE TITLE
Simultaneous bombs are self-destructive

### ISSUE THREAD

**Issue by dwinters99** [VOREStation/VOREStation#8286]
#### Brief description of the bug
Priming a grenade that shares a code with another will blow it up

#### What you expected to happen
To be able to prime multiple grenades to detonate them simultaneously

#### What actually happened
Priming a grenade with the same code as another blows up the other

#### Steps to reproduce
- Make two grenades on the same code and frequency
- Prime one
- Boom

**Comment by TheFurryFeline** [comment]
Not the first time I've heard of this happening, oof. Forgot who it was before, however.... At least we know it wasn't a one-time thing.

**Comment by Screemonster** [comment]
Yeah, signaller grenades are weird. They don't need to be primed - as soon as they're completed, receiving the signal will set them off. And priming them makes them send the signal. It's been that way for years and it's a massive missing stair for people that are new to grenades.

But I bet if you changed it, it'd result in massive complaints from people that are used to the _un_intuitive way of doing it.

Fuck it, I'm down for it.
