### ISSUE TITLE
Zeng-Hu prosthesis are missing from character creation

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#8356]
I play a character called Dayleen-A who is full Zeng-Hu FBP.
A while ago i noticed that my character did not look like she used to anymore, Now with some weird green lines i can not get rid off no matter what i do. Turning on and off, changing and swapping synth colors or synth markings do nothing, Not to mention this weird green color is there with synth color and markings OFF by default. Not only that but the normal markings of the Zeng-Hu body are gone and i was left with a sort of hybrid between a normal body and a Zeng-Hu with no markings.
Now, this wouldn't be an issue if i could try to re-set my FBP right? Well, Zeng-Hu prosthesis are completely gone from character selection and they cannot be selected, Meaning that if i remove my Zeng-Hu things from character selection and press save, they will be gone and i wont be able to select them again!

https://i.imgur.com/EDQxAHv.png Weird green lines and the markings that were part of the prosthesis to begin with are gone. Also this is NOT fixed by being re-sleeved in round or building a FBP from the ground up.

https://i.imgur.com/nkQYa4n.png As you can see here (I cant find any other pictures cuz i dont usually take any) There is no weird green markings and the normal Zeng-Hu markings are there and visible. This picture is not very old and other people have told me they cant select Zeng-Hu in character creation either.

**Comment by H0lySquirr3l** [comment]
Looking in the code... Not sure if this effects its but. 

![image](https://user-images.githubusercontent.com/34927367/86429951-9b12ed00-bcb6-11ea-9727-9db012e07f3e.png)

![image](https://user-images.githubusercontent.com/34927367/86429960-a6feaf00-bcb6-11ea-8a12-55ecb273ccac.png)


The tajar prosthetics folder is completely empty.

**Comment by Neopatra** [comment]
That would not be the issue, I still have an old archive of that file and it looked like that back in 2018. It would be something more recent I'm sure.

**Comment by Dhaeleena** [comment]
I have also found out that i can no longer use medichines on this character even tho i have used them in the past when my body wasn't fucked up

**Comment by KillianKirilenko** [comment]
Testing something but I think I might have this one figured out. Will edit this comment after testing.
