### ISSUE TITLE
Issue with the Language Implant

### ISSUE THREAD

**Issue by Techtypes** [VOREStation/VOREStation#838]
#### Brief description of the issue
Language implant dos not seem to function

#### What you expected to happen
One should get a prompt to use the say*smile emote, upon using that emote the implant activates and teaches one all languages

#### What actually happened
You get nothing telling you to use the *smile emote and also no languages are learned even if you use that emote

#### Steps to reproduce
- Produce glass case contacting implant in R&D
- Use implanter from medical on glass case
- Implant one self in the head

#### Code Revision
release - 2017-01-15
6100bd34025490a1ffe63a29c05352b934a8355e 
 
#### Anything else you may wish to add:
Also has effected the EAL implant as that starting implant also dos not work for me

**Comment by Arokha** [comment]
The EAL implant doesn't teach you EAL, it just allows you to speak/understand it if you are a biological, and otherwise know the language.

**Comment by Arokha** [comment]
Due to SHENANIGANS, the implant case spawns with TWO DIFFERENT language implants in it. One only teaches you galcom. Just implant both. I submitted the fix already.
