### ISSUE TITLE
Persistent projectiles?

### ISSUE THREAD

**Issue by cadyn** [VOREStation/VOREStation#8383]
#### Brief description of the bug
Projectiles stick around after being fired

#### What you expected to happen
The projectiles to vanish after being fired

#### What actually happened
When walking over the area where projectiles ended up after the projectiles hit, you can still be affected by them.

#### Steps to reproduce
- Acquire a taser or stun gun 
- Shoot at an entity
- Walk over the area where that entity was when it was hit by the projectile.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Rykka-Stormheart** [comment]
This is already fixed by an incoming PR from Polaris.
