### ISSUE TITLE
Clicking "Custodial Locator" on the PDA causes the PDA to crash upon open

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#8387]
#### Brief description of the bug
Upon noticing an option on the PDA i've never noticed before, Custodial Locator, I pressed it and immediately got the error down below. I clicked the option to prevent any more errors from occurring and thought it fixed, but any time I opened the PDA after that point, the error would appear again.

#### What you expected to happen
I'm not sure what the button is supposed to actually do, so I can't answer this one.

#### What actually happened
Upon pressing the button, the PDA popped up an error message (which i screencapped below) and would continue popping the message up until I ticked the option to prevent further messages. Opening the PDA from that point onwards immediately triggered the error again and again until I took the CustodiPRO cartridge out and put it back in.

#### Steps to reproduce
- Be a janitor/have a PDA with CustodiPRO installed
- Select "Custodial Locator"
- Get error messages

#### Code Revision
- B:release D:
Commit: 0ee36f9501649b74c2dbacdc4b5647c7e9a83959 
 

#### Anything else you may wish to add:
- https://gyazo.com/3663bf5cde1be0552cb077068d136100

**Comment by Rykka-Stormheart** [comment]
NanoUI issue, I'll take a look or I'll nudge Shadow to later.
