### ISSUE TITLE
Wintercoat better than snowsuit

### ISSUE THREAD

**Issue by r4d6** [VOREStation/VOREStation#8389]
#### Brief description of the bug
Less than a bug and more of a discrepancies between the wintercoat and the snowsuit

#### What you expected to happen
For the wintercoats and the snowsuits to be at least equivalent, if not for the snowsuit to be at least a bit better.

#### What actually happened
When looking at the both of them objectively, the wintercoat is the clear winner and you should always use it over the snowsuit.
Let's look over what make it equal and superior to the snowsuit :
- They both have the same level cold protection, BUT!
- The wintercoat protect the [torso, the arms and the legs](https://github.com/VOREStation/VOREStation/blob/master/code/modules/clothing/suits/hooded.dm#L95), meanwhile, the snowsuit [only cover the torso and the arms](https://github.com/VOREStation/VOREStation/blob/master/code/modules/clothing/suits/miscellaneous.dm#L867), so already the coat is superior to the suit despite one being a coat and the other a full-body suit.
- Not only that, the coat [has a hood](https://github.com/VOREStation/VOREStation/blob/master/code/modules/clothing/head/hood.dm#L10) which you can put on for protecting your head against the cold, which the snowsuit has not.

So, to resume : The wintercoat, which should at most cover the upper body with the head having a hood, end up protecting more of the body against the cold than a full-body snowsuit, which I feel should also have a hood.
So there are discrepancies between the wintercoat you wear when it get cold and the snowsuit you wear when there are 3 feet of snow.
I feel an easy fix would be to move the [LEG] tag from the wintercoat to the snowsuit, and optionally give the snowsuit a hood. (I say optionally because, with both the legs and the hood, the snowsuit would become the n1 choice, while if it doesn't have one you could argue the value of the hood vs the value of the pants.)

That's all.

**Comment by KillianKirilenko** [comment]
This issue should probably be taken up to Polaris, if anything. I'm not sure why they added the white coats when they already had the fur-trimmed ones that have matching boots.

Incidentally the reason the winter coat 'also' protects legs is because winter boots used to protect legs but now only protect feet: [PL4356](https://github.com/PolarisSS13/Polaris/pull/4356).
