### ISSUE TITLE
Steel chair in Science breakroom changes colour when sat on.

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#8396]
#### Brief description of the bug
There is a steel chair within Science Breakroom on Base level 2 that is coloured black/grey when not sat on, and white when sat on.

This does not apply to the other chairs.

#### What you expected to happen
The chair to remain black/grey when sat on.

#### What actually happened
It turned white.

#### Steps to reproduce
- Find the chair in question (only works with the one in the screenshot)
- Sit

#### Code Revision
Server revision: B:release D:
Commit: 0ee36f9501649b74c2dbacdc4b5647c7e9a83959 
 

#### Anything else you may wish to add:
https://imgur.com/a/bIgc8BB
Before and after

**Comment by Neopatra** [comment]
>"Wait, it changes colors?"

>*Loads gun* "It always has."
