### ISSUE TITLE
Medihound Crew Monitor is Screwed Up

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#8409]
#### Brief description of the bug
The medihound's crew monitor not only has the z-levels out of order, but it also doesn't actually display crew on the map like it's supposed to.

#### What you expected to happen
The medihound crew monitor would function the same as the normal one in medbay.

#### What actually happened
It was completely janked up in map view.

#### Steps to reproduce
- Become a medihound
- Open the crew monitor
- Select the map view instead of the list

#### Code Revision
- Server revision: B:release D:
Commit: 01a7591e3868903bdb109b2ab48091b04fc86d70 
 

#### Anything else you may wish to add:
- https://gyazo.com/0014359d81ee79f1ea2c86ef023daee6

**Comment by cadyn** [comment]
I just checked and the map view on the normal crew monitor computers don't work either. Best off just using the list view like everyone else does and learning the names of places in the map.

**Comment by cadyn** [comment]
Actually this is the same as #8197 and there's already a PR for it, so this should get fixed too.
