### ISSUE TITLE
Select Hair Colors issue for Prometheans

### ISSUE THREAD

**Issue by softcerv** [VOREStation/VOREStation#8420]
#### Brief description of the bug
When changing the colors of hair as a Promethean, only the primary hair color changes while the secondary stays the same.

#### What you expected to happen
I expected the secondary hair color to change according to what I put in the color change menu.

#### What actually happened
It only changed the primary color of the hair instead of both the hair colors in the gradient. 

#### Steps to reproduce
- Be a Promethean
- Use the Gradient option (in my case, I used Fade (Up)) in the Character Setup menu.
- Use the select hair colors option then try and change both colors from what they were.

#### Code Revision
Server revision: B:release D:
Commit: 4c340c5dac0a7afa8f5f219ec3ba812c5ed67033 
 
#### Anything else you may wish to add:
Hair at start
![image](https://user-images.githubusercontent.com/68373373/87654291-ab01e680-c724-11ea-8465-bb2f170d7e13.png)

Hair after changing primary to orange, and secondary to blue
![image](https://user-images.githubusercontent.com/68373373/87654355-c40a9780-c724-11ea-99cd-3b11ac9725c5.png)

**Comment by cadyn** [comment]
Fixed. Was probably mistakenly setting facial hair color instead of gradient color as up until my PR, there was no way to change it ingame.

**Comment by KasparoVy** [comment]
That looks fucking dope regardless

**Comment by cadyn** [comment]
Actually fuck, just realized the pull request is something that needs to be upstreamed. Time to yeet this on over to Polaris.

**Comment by Arokha** [comment]
fixed
