### ISSUE TITLE
Mining, Research, and Engineering Elevators still contain references to being shuttles.

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#843]
#### Brief description of the issue
Basically, the elevators' consoles and some of the mouse-over names to do with them still reference shuttles. 

#### What you expected to happen
Them to not have references to being shuttles, and instead to being elevators, unless I'm misunderstanding.

#### What actually happened
See description.

#### Steps to reproduce
Just go check out the elevators.

#### Code Revision
Server revision: release - 2017-01-15
6100bd34025490a1ffe63a29c05352b934a8355e

**Comment by SpadesNeil** [comment]
Some specific examples would save time.

**Comment by DeepIndigo** [comment]
Well, for one, the console interfaces still say "shuttle" in big white letters. I'll jot more down as I play the related jobs.

**Comment by Arokha** [comment]
Irrelevant on Tether.
