### ISSUE TITLE
Sprite for LR1 Shishi disappears when device powercell is removed.

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#8434]
#### Brief description of the bug
Small bug. The LR1 Shishi's sprite disappears when the powercell is removed. I assume this is because the sprite for an unloaded LR1 Shishi does not exist or was not referenced properly.

#### What you expected to happen
When the powercell is removed, the sprite for the rifle indicates that the rifle is not powered or a box representing the powercell does not show up when the sprite changes.

#### What actually happened
LR1 Shishi sprite disappears entirely instead of the expected parts disappearing/changing.

#### Steps to reproduce
- Hold LR1 Shishi in one hand
- Remove powercell from LR1 Shishi with free hand

#### Code Revision
4c340c5dac0a7afa8f5f219ec3ba812c5ed67033 
 

#### Anything else you may wish to add:
I'm assuming this is just a small matter of changing the sprite being referenced when the LR1 Shishi is unloaded.

**Comment by aryll-linton** [comment]
This appears to no longer be an issue- seems to have been fixed in the past 2 months.
