### ISSUE TITLE
fix the medbay security lobby piping/wiring

### ISSUE THREAD

**Issue by Dropshotz** [VOREStation/VOREStation#844]
#### Brief description of the issue
the pipes and wires from medbay sec lobby is missing

#### What you expected to happen
for tgem to be tfere

#### What actually happened

nope.
#### Steps to reproduce
- take off tiles in front of medbay sec lobby
- wonder ICly why NT is so incompetent
- wonder OOCly why its still not there

#### Code Revision
- will add in the weemends, dont have acess to pc atm
 
#### Anything else you may wish to add:
- medbay sec lobby.

**Comment by Dhaeleena** [comment]
I dont know what you are saying. Everything looks in place here https://i.gyazo.com/f8b00d961b165da591d06f7b7dd95382.png

**Comment by Screemonster** [comment]
It might be a broken wire directly under the door.

**Comment by Dhaeleena** [comment]
It looks fine to me. https://i.gyazo.com/9960614be2d2240c54ce4bb04a5e6a3e.png

**Comment by Dropshotz** [comment]
as far as i know, it sometimes is missing under thr door and in front(idk if random, someone fixed it, or removed it) /shrug

**Comment by Screemonster** [comment]
Please don't open issues without confirming it's an actual issue, just because you remembered it was a problem sometime several weeks ago, and ESPECIALLY not including snarky comments about "competence" in the issue text.
