### ISSUE TITLE
close invalid/fixed issues

### ISSUE THREAD

**Issue by Dropshotz** [VOREStation/VOREStation#845]
#### Brief description of the issue
too many unvalid/fixed open issues

#### What you expected to happen
for them to be closed when they are done with

#### What actually happened
It's a mess!

#### Steps to reproduce
- open issues
- stare at all the unvalid open issues
- wonder if I should stop beign lazy
 
#### Anything else you may wish to add:
- the issues section is a god damn mess.

**Comment by Screemonster** [comment]
Well, this one's just making the problem worse.
