### ISSUE TITLE
Generate-Recipe-Drump not working.

### ISSUE THREAD

**Issue by H0lySquirr3l** [VOREStation/VOREStation#8457]
#### Brief description of the bug
Attempted to make a dump of the recipes for the new aura cooking update. Used the verb several times on a private server and it does not output to the byond cache.
#### What you expected to happen
it to make a recipe dump in the byond cache folder with icons and two hmtl files and a Css file.
#### What actually happened
Nothing happens.
#### Steps to reproduce
Start up a server.
use the "Generate-Recipes-Dump" verb

**Comment by Rykka-Stormheart** [comment]
Noted, will be investigating.

**Comment by Rykka-Stormheart** [comment]
This is fixed, please close.
