### ISSUE TITLE
Show Server Revision not working.

### ISSUE THREAD

**Issue by H0lySquirr3l** [VOREStation/VOREStation#8458]
#### Brief description of the bug
Was making another issue and tried to use the "Show Server Revision" to get the revision of the private server. It came back as "unknown".
#### What you expected to happen
it to give the current revision number of the server.
#### What actually happened
![image](https://user-images.githubusercontent.com/34927367/88289649-30544080-ccbb-11ea-8f05-9c30f849e90d.png)
#### Steps to reproduce
use the "Show Server Revision" verb under the OOC tab.
#### Code Revision
Can't do it lol.

**Comment by lbnesquik** [comment]
Works as of this time.

**Comment by Shadow-Quill** [comment]
If this is still working, I'd say this is probably NAB
