### ISSUE TITLE
Add ghost-role bans

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#846]
#### Brief description of the issue
People can continuously respawn as infinite mice and continue to annoy people when it's pretty clear that the people they're annoying don't want to be bothered by mice in the middle of their fucking scene on account of having stomped that last half dozen of the little fuckers.

#### What you expected to happen
For me to be able to swing _**LE MARTEAU D'INTERDICTION**_ on people who are annoying as fuck with mouseroles and ruin it for everyone.

#### What actually happened
I have to actually ban them from the entire server. Which, yanno. I'm cool with that if that's what they want me to do but I'd rather they just not be annoying as fuck with mice.

#### Steps to reproduce
- be mouse
- follow someone around and annoy them
- get stomped
- rejoin as mouse one minute later
- everyone starts yelling at me in ahelps and discord to remove the little fucker from their presence

#### Code Revision
- tba, am at work
 
#### Anything else you may wish to add:
- n/a

**Comment by Arokha** [comment]
ban he, imo
