### ISSUE TITLE
Service Rework Feedback Megathread

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#8473]
If you have any issues with the Service Rework, please list them here for mappers to fix.

**Comment by lbnesquik** [comment]
I have a few!

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453114-9cbe7380-ce64-11ea-8761-d79d2cd7dacd.png)
I think you could put the disposal unit in that corner, given it is far enough that it won't be convenient for more bar people anyway.

**Comment by Verkister** [comment]
- Surface medical missing the outside roof north from new xenoflora.
- Bar shutters button missing.
- Observer spawnpoint missing.
- 2 pieces of the seated kitchen counter missing and a redundant drink machine blocking one of the seated spots.
- Xenoflora waste buffer tank outside layered underneath the catwalk.
- The floor under the forementioned catwalk area is indoors type and gets phoron flakes on it.

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453275-c62bcf00-ce65-11ea-9d95-c63faf6e2b4b.png)

Tables were missing earlier in the round, and there was an extra soft drink dispenser here. Might be worth removing the triplicate.

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453300-f5dad700-ce65-11ea-9591-ebc840caaf32.png)
An extra light in the bar backroom could be nice. It gets really moody in night mode

**Comment by Rykka-Stormheart** [comment]
Private bar backroom is not connected to the grid
https://i.gyazo.com/9a16400f872459b0514629a022d2e140.png

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453337-49e5bb80-ce66-11ea-95c8-8e2ffd4d2ac4.png)
This place could use shutters because people occasionally scene in there.
Also maybe move the goat to the garden too?

**Comment by Verkister** [comment]
![kuva](https://user-images.githubusercontent.com/13697337/88453341-b5338b80-ce6e-11ea-959e-d3d3c36980fa.png)
This pipe section probably unintended to show up on top.

**Comment by Rykka-Stormheart** [comment]
> ![image](https://user-images.githubusercontent.com/24830358/88453337-49e5bb80-ce66-11ea-95c8-8e2ffd4d2ac4.png)
> This place could use shutters because people occasionally scene in there.
> Also maybe move the goat to the garden too?

This is issues, not opinions/criticism, focus on the *issues* first please.

**Comment by TeleTubby2** [comment]
No Xenobotany Seed vendor(?)
Xenobotany lockers are the normal botanist lockers, instead of the Xenoflora ones.

**Comment by lbnesquik** [comment]
I could mark them as Suggestions to make it clear? Easier to have everything in a single spot, except if there is going to be two megathreads.

**Comment by Rykka-Stormheart** [comment]
> I could mark them as Suggestions to make it clear? Easier to have everything in a single spot, except if there is going to be two megathreads.

Please do that, thank you.

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453413-ead47680-ce66-11ea-98f3-e9bc9543d8f4.png)
As for **ISSUES**, the entertainment room has no lightswitch, it has no shutters switch and it seems the backroom isn't accessible by service staff. That might be intended or not.

**Comment by lbnesquik** [comment]
Suggestion, swap the medical station and lightswitch so the corner is a tad less dark.
![image](https://user-images.githubusercontent.com/24830358/88453471-71895380-ce67-11ea-9d9b-279267773a2f.png)

**Comment by Verkister** [comment]
Suggestion: Making the entertainment stage backdoor have a little fancier look and more discreet use sounds to be little more theme-appropriate for the frequent use it'll probably have than a regular old maintenance airlock. Especially with how the shutter and tint controls are all located in the backroom.

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453556-64209900-ce68-11ea-8504-6827acee3dcc.png)
Issue(?): The above room is called the 'hydroponics break room' but it has 3 drying racks. It might be worth moving 1 or two into the lower room with the rest of it.

Suggestion: '''Just''' merge the two. It is not the best break room, given how visible you are, and the large number of seating options in the bar, the front of hydroponics or the service backroom. And you are also very visible, so there isn't much privacy. I do approve the drying racks and pipe.

**Comment by lbnesquik** [comment]
Suggestion: Add a cigarette tray.

**Comment by lbnesquik** [comment]
I really don't want to come off as a nitpicking twat, but this really feels like too many. And that we could get rid of the one in the hall.
![image](https://user-images.githubusercontent.com/24830358/88453697-a4cce200-ce69-11ea-956e-98386cfbc078.png)

**Comment by lbnesquik** [comment]
![image](https://user-images.githubusercontent.com/24830358/88453761-5a983080-ce6a-11ea-9f08-8691b32fae91.png)
Suggestion: An extra lightbulb on either side of the counter would be very nice for visibility!

**Comment by Voidalynx** [comment]
Currently missing a sink for hydroponics and there's nothing to process honey with. I think it's a centrifuge or similar that's needed.

**Comment by lbnesquik** [comment]
Suggestion: The bar backroom could really use a lock, to allow bartenders or chefs to go through with a scene without risks of people waltzing through.

**Comment by Rykka-Stormheart** [comment]
> Suggestion: The bar backroom could really use a lock, to allow bartenders or chefs to go through with a scene without risks of people waltzing through.

Eh, no. I disagree on that front. We don't need locks everywhere to keep people from "getting into scene areas". If you want 100% immunity, go to dorms, otherwise, take it as part of the thrill of public or semi-public play.

**Comment by r4d6** [comment]
Is it possible to replace the stools in the bar with an anchored version?

Because I hate picking up stool when trying to hug someone and hitting them with it.
Sure it is funny the first time or two, but it become annoying really fast.

Also why does a 'professional' bar have shitty stools that people can pick up easily instead of [anchored stools on a swivel](https://images-na.ssl-images-amazon.com/images/I/51es7EAro2L._AC_SY355_.jpg) or something?

**Comment by lbnesquik** [comment]
> 
> 
> > Suggestion: The bar backroom could really use a lock, to allow bartenders or chefs to go through with a scene without risks of people waltzing through.
> 
> Eh, no. I disagree on that front. We don't need locks everywhere to keep people from "getting into scene areas". If you want 100% immunity, go to dorms, otherwise, take it as part of the thrill of public or semi-public play.

I mean, the bar backroom USED to be a 'safe' area with no transit reasons. Now it is pretty much going to be walked through by lotsa people. Feels a little wrong to have it be super open IMO.

**Comment by lbnesquik** [comment]
Small Suggestion, Make the entertainment room shutters start open, so it is a fair bit more open looking when  you go around the hall.

**Comment by SpooksAnno** [comment]
Suggestion for filling the walls on Xenoflora, add guest terminal, newscaster, intercom, status display and wall chargers for Xenoflora,Holographic display would be nice as well to have, since it seems pretty empty at least on the main room its used. And the same can be said for the outside. Perphaps even a medical dispenser or some dispensers.

![scrnshot2](https://user-images.githubusercontent.com/66095096/88585760-d8566a80-d029-11ea-8ed0-7e490ee95ba5.png)
![(null)scrnshot1](https://user-images.githubusercontent.com/66095096/88585762-d8ef0100-d029-11ea-85ca-51157d0cdaac.png)

**Comment by r4d6** [comment]
Is there any reason why the bartender has access to the kitchen and the cooks have access to the bar?

Because the first time I played bartender since this, a cook came on-duty, took the bar's mats, then left on the tram right after.
He was also able to access the Bar's backroom, which hold a shotgun.

**Comment by TeleTubby2** [comment]
There's Xenobotanist lockers in the lab now, but... Xenobotanists don't have access.
