### ISSUE TITLE
Cheongsam Loadout Text Error

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#848]
#### Brief description of the issue
Cheongsams in the loadout have the wrong flavor text.

#### What you expected to happen
Cheongsams to have the correct flavor text.

#### What actually happened
They have the Blazer, Blue flavor text.

#### Steps to reproduce
- Check the loadout, uniform section.

#### Code Revision
- 6100bd34025490a1ffe63a29c05352b934a8355e 
 
#### Anything else you may wish to add:
- Screenshot: https://www.dropbox.com/s/tar6yf6sws2vdry/Screenshot%202017-01-18%2005.27.27.png?dl=0

**Comment by SpadesNeil** [comment]
The hell is a Cheongsams and did we add that or did Polaris?

**Comment by Vorrarkul** [comment]
I know we had them on our old Bay code, but other than that I don't know. They're a chinese dress.

**Comment by SpadesNeil** [comment]
Did this get fixed?

**Comment by Vorrarkul** [comment]
As of f4006f65d047af977cd5ba5e015caf706af8cb14, it is not fixed. In fact, it got worse:
![screenshot 2017-08-22 22 49 47](https://user-images.githubusercontent.com/17329033/29600705-531e1a36-878c-11e7-8e79-f1fe8c335f4d.png)

**Comment by SpadesNeil** [comment]
Has this been fixed _yet_?

**Comment by Vorrarkul** [comment]
As of e0443cfb4b865c8561196af365d1aa78dede00b1 both the Cheongsam and Crop Top selections have the same duplicated descriptions as the Blazers above them. So no, not that I am aware.
