### ISSUE TITLE
Aurora Cooking Feedback Thread

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#8480]
Please provide your feelings on the cooking update. Mark OPINION for things you FEEL could be different, mark ISSUE for actual issues (such as a recipe not being make-able).

**Comment by Wulfestwulf** [comment]
ISSUE: Can't take reagents out of Oven Dishes, making them basically useless if you put one extra unit of salt.

**Comment by Wulfestwulf** [comment]
Also, put the locker with all the flour and stuff with the locker with eggs. Most of the time you'll use them both together.

**Comment by MarinaGryphon** [comment]
> ISSUE: Can't take reagents out of Oven Dishes, making them basically useless if you put one extra unit of salt.

Can you not empty it into the sink like a glass?

**Comment by LeighKnapenberger** [comment]
Batter is impossible to make, locking out most fryer recipies.

**Comment by Rykka-Stormheart** [comment]
> Batter is impossible to make, locking out most fryer recipies.

Noted, will be looking to address the issue.

**Comment by Wulfestwulf** [comment]
ISSUE: You have too use a sink to remove reagents out of a Oven Dish.

**Comment by Rykka-Stormheart** [comment]
> ISSUE: You have too use a sink to remove reagents out of a Oven Dish.

That's intended.

**Comment by Rykka-Stormheart** [comment]
> Batter is impossible to make, locking out most fryer recipies.

Fix is being worked on.

**Comment by Rykka-Stormheart** [comment]
Okay, all issues in this thread, namely batter and being unable to empty the tray have been addressed.

**Comment by Snaffoo** [comment]
Seems there are two lines of code for flat dough, one overriding the recipe for tortillas, making flatbread instead.
