### ISSUE TITLE
Love Potions in both loadout flasks.

### ISSUE THREAD

**Issue by r4d6** [VOREStation/VOREStation#8487]
#### Brief description of the bug
The Alcoholic Version of the Love Potion is in the vacuum-flask, which is supposed to only hold **non**-alcoholic drinks.

#### What you expected to happen
For the non-alcoholic version to be in the non-alcoholic flask.

#### What actually happened
Both flasks have the alcoholic version.

#### Steps to reproduce
- Be a Promethean.
- Take both flask options in the loadout.
- Set the both of it to Love Potion.
- Drink a sip of each.
- See that they have the same taste and both start to burn you.

#### Anything else you may wish to add:
- There are no way to differentiate which Love Potion is which beyond taste (At least when in flasks). That fact matter when one of them can kill a promethean/Teshari the same way Anti-Freeze can.
- It is not listed anywhere that we have a Love Potion that can actually _harm_ Teshari and Prometheans. Or that we have two Love Potion. 

#### References
Non-Alcoholic Love Potion : https://github.com/VOREStation/VOREStation/blob/master/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm#L1874
Alcoholic Love Potion : https://github.com/VOREStation/VOREStation/blob/master/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks_vr.dm#L229
Anti-Freeze : https://github.com/VOREStation/VOREStation/blob/master/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm#L2427
Screenshots : https://imgur.com/a/ZoihJ9F

**Comment by Rykka-Stormheart** [comment]
This is fixed, was fixed by https://github.com/VOREStation/VOREStation/pull/8491
