### ISSUE TITLE
Mapping error causes a phoron flood to start at Surface Medical's storage area upon roundstart

### ISSUE THREAD

**Issue by YuskoTheCoyote** [VOREStation/VOREStation#8494]
The surface medical's storage area starts the round being flooded with phoron presumably due to a mapping error. It is near impossible to patch up without having it spread to the rest of surface medical and possibly surface 3.

That the mapping is correct so that no phoron floods the storage area.

The room is flooded with phoron, and any attempts made to scrub it out failed. And it is very prone to spreading to the rest of surface medical if engineering tries to fix it but fails. 

#### Steps to reproduce
No steps required. Phoron flood begins the moment the round starts. 

 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/37598481/88499830-09389000-cf95-11ea-95d0-3633f7289c15.png)

**Comment by Novacat** [comment]
Already fixed.
