### ISSUE TITLE
Maintenance Drones unable to view camera console.

### ISSUE THREAD

**Issue by Cyantime** [VOREStation/VOREStation#8499]
#### Brief description of the bug
Attempting to view an engineering camera console is denied while a maintenance drone.

#### What you expected to happen
Click camera console, view cameras to get information on engineering or locations of alerts.

#### What actually happened
Receive a message that says `You realise its kind of stupid to access a camera console when you have the entire camera network at your metaphorical fingertips`

#### Steps to reproduce
Spawn as maintenance drone, click camera console.

#### Code Revision
53e0b5d9f053dae5af8f8b8ef1589cce8a0da8b2 
 

#### Anything else you may wish to add:
This message seems intended for an AI, which does actually have camera access.

**Comment by Heroman3003** [comment]
What about borgs? Is issue same with them too?

**Comment by Rykka-Stormheart** [comment]
> What about borgs? Is issue same with them too?

Known issue, Shadow just fixed it tonight, iirc. I'll nudge her.
