### ISSUE TITLE
resleeving doesn't work

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#8512]
if you hit sleeve on the console nothing happens

**Comment by Rykka-Stormheart** [comment]
More details, please? Context on what happened, etc? (For Shadow to investigate later).

**Comment by lm40** [comment]
i actually can't replicate this

**Comment by lm40** [comment]
i lied this is still happening on the live server apparently, but i'm not sure if that's just because it's been a while since the last update or if it's genuinely bust

**Comment by Rykka-Stormheart** [comment]
This was resolved by https://github.com/VOREStation/VOREStation/pull/8513
