### ISSUE TITLE
Lack of taur-suits in engineering (and possibly mining).

### ISSUE THREAD

**Issue by Dinnel** [VOREStation/VOREStation#852]
#### Brief description of the issue
Engineering doesn't have taur suits, simple as that, possibly with mining as well if I remember right.

#### What you expected to happen
To have taur suits (at least two for atmos, engineering, and mining)

#### What actually happened
Not having any except for the hardsuits in EVA (and even then there's only one atmos taur suit.)

#### Code Revision
- release - 2017-01-15

**Comment by chaoko99** [comment]
Is this relevant anymore?

**Comment by Dhaeleena** [comment]
No longer relevant on the current map. Fixed
