### ISSUE TITLE
Space hedgetrimmers for the republic of Botanistan.

### ISSUE THREAD

**Issue by Veecveec** [VOREStation/VOREStation#855]
Here is a .dmi file for hedgetrimmers for botanists, as I see them being issued regular wirecutters as something incredibly lazy by whoever who created botany a long time ago. I imagine them being nothing more but a re-sprite of the wirecutters, but perhaps if somebody wants to code it being 100% effective to vines and other flora-related bio-hazards, it would be great.
[Hedgetrimmers.zip](https://github.com/VOREStation/VOREStation/files/718672/Hedgetrimmers.zip)

**Comment by SpadesNeil** [comment]
Why sledgehammers? They're hardly what I'd describe as a gardening tool. This makes no sense to me.

**Comment by Screemonster** [comment]
hedgetrimmers. Not sledgehammers. Like shears.

**Comment by SpadesNeil** [comment]
....... shut up I'm sleepy

**Comment by lbnesquik** [comment]
Will do.
