### ISSUE TITLE
Sprite bug on prescription glasses.

### ISSUE THREAD

**Issue by Veecveec** [VOREStation/VOREStation#856]
#### Brief Description of the Issue
As your character wears prescription glasses, you may see a single gray pixel in the middle of a given character's left arm.

#### What You Expected to Happen
Nothing out of ordinary?

#### What Actually Happened
Something out of ordinary! Though it is so minimal that it can be repaired in less than a second.

#### Steps to Reproduce
Get yourself a pair of prescription glasses either from the medical bay, or just start with a pair, and look closely at the left arm. You will certainly see the white pixel, especially if you wear something dark, for example: Evening gloves.

#### Code Revision
- Server Revision: Release - 2017-01-15
6100bd34025490a1ffe63a29c05352b934a8355e

**Comment by Cameron653** [comment]
Fixed upstream: https://github.com/PolarisSS13/Polaris/pull/2950

**Comment by Cameron653** [comment]
Closing this. It will be in the next sync.
