### ISSUE TITLE
Dogborg gurgles can be stacked

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#857]
#### Brief description of the issue
You can gurgle people in about 5 seconds if you know how. Click self-clean a bunch of times, then click yes on all the prompts. The digestion happens several times simultaneously because there's no sanity check.

#### What you expected to happen
Not that.

#### What actually happened
That.

#### Steps to reproduce
- Click self-clean
- Click it more times
- Click yes on all the prompts

**Comment by SpadesNeil** [comment]
oh god lol

**Comment by SpadesNeil** [comment]
"It's not a bug, it's a feature."

**Comment by Zeldazackman** [comment]
https://youtu.be/x7YXo5upo18

**Comment by Arokha** [comment]
Misclick whups.

**Comment by Virgo113** [comment]
To be honest instant gurgles are kinda hot...
