### ISSUE TITLE
Taur suits replacing

### ISSUE THREAD

**Issue by BlackjackFajah** [VOREStation/VOREStation#859]
#### Brief description of the issue
Taur voidsuits for mining and engineering were removed leaving just 1 atmos suit in EVA which is kinda unfair as the perks of the engineering suits are not found in atmos suits.

#### What you expected to happen
I didnt really expect anything as this is a request to put these two suits back in the map

#### What actually happened
Taur void suits are missing and a few players are quite annoyed at that.

#### Steps to reproduce
None?

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-01-15
6100bd34025490a1ffe63a29c05352b934a8355e 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Engineering void suit storage/EVA/Mining void suit storage

**Comment by Arokha** [comment]
Fixed in #870
