### ISSUE TITLE
Add a reset button for character setup slots.

### ISSUE THREAD

**Issue by Veecveec** [VOREStation/VOREStation#863]
Some people playing on VOREStation would probably love a button that will quickly reset all character values to their default settings, as if you just freshly joined the server or/and used an empty slot. This function would make creating or re-making characters easier, while avoiding the need to use more slots to prevent all of them from being clogged up with useless things.

Bay12 already has it, perhaps there'll be a need to tweak some stuff for VORE-specific settings, but other than that it'd be pretty nice! A prompt asking if you're sure about doing a reset would also be nice, but is not necessary since changes aren't saved unless you press the 'Save Slot' button.

**Comment by SpadesNeil** [comment]
Should send to Polaris if we do this. Basically a "delete character" button.

**Comment by Screemonster** [comment]
https://github.com/PolarisSS13/Polaris/pull/2934 They're already on it from the look of things.

**Comment by Cameron653** [comment]
In polaris sync I'm about to put up.
