### ISSUE TITLE
Resleeving console unable to access disk records

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#8630]
#### Brief description of the bug
The resleeving control console (which is supposed to load up active body record from a disk when slapped with one) completely ignores the body record disk interactions, making it completely impossible to create stock or otherwise disk stored sleeves.

#### What you expected to happen
For the console to read the record from the disk.

#### What actually happened
The console UI generation overrides the active record vars automatically when interacted with, forcibly and exclusively loading the available records from the transcore backup list with no way to load up the disk record, and even if it did list the record, it would just qdel it anyway for lacking a ckey.

#### Steps to reproduce
- (Step 1) Attempt to use the disk related features on resleeving console.
- (Step 2) Fail miserably.

#### Code Revision
- 6cef1a3bb8f7de4f4920894aaf2d6b7b66281dfe
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ShadowLarkens** [comment]
Huh. Well, the simple explanation of this bug would be that I had no idea disks set the active record manually and didn't account for that at all. I'll take a look at this in my second pass of medical where I do virology and convert the Body Designer console itself, unless this is critical enough to require fixing right away.
