### ISSUE TITLE
Shuttle :B:roke and won't fly

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#8651]
#### Steps to reproduce
- I don't realy know how to reproduce this bug, sadly. I'm not too experienced with piloting mechanics yet.

#### Code Revision
- 6cef1a3bb8f7de4f4920894aaf2d6b7b66281dfe

**Comment by Verkister** [comment]
Not sure if it's related in any way, but the timing did kinda hit together with this other bug happening #8652 
I'm not familiar enough with the shuttle systems to be certain how vulnerable they are for regex failures, but if they are, then it would likely be related.

**Comment by Huenererschrecker** [comment]
Not sure, but it is the same bug as #8653 which seems to be having more details on this than what I was able to gather.
