### ISSUE TITLE
Shuttles not Being able to Fly

### ISSUE THREAD

**Issue by Wolfmeme** [VOREStation/VOREStation#8653]
#### Brief description of the bug
When you attempt to leave somewhere like the station or V2, it may sometimes not announce it. When I see this happen, means that once you are in space, you can't manually control the shuttle, nor use the auto-pilot. I've seen one time on V2 where the coordinates on the console said we were at 0:0, though that may be a separate bug, or related, not sure as this is the second instance.

#### What you expected to happen
For the comms to announce that the shuttle has left the station/planet, and let us fly away.

#### What actually happened
As we undocked from the station/planet, there was no such announcement over comms that we'd done so. While in one instance the console said we were at the coordinates 0:0, the other reported the correct location of Virgo 3-b. Seems to only happen later in the shift, and also seems to sometimes affect all shuttles (Today's case where we were trying to medivac an Exploration wipe), and other times not(When the Expedition shuttle reported we were at 0:0 while we should've been in space above V2). 

#### Steps to reproduce
0:0 on V2:
- Step 1: It seemed like we'd originally docked whilst moving, and that may be the reason.
- Step 2: Come back, try to leave, I believe it undocked us back at the moving section of space in the same level that the tram dockes to, though I may be wrong, manuel flight controls and autopilot never moving us in any direct/ the manuel controls were disabled.
Medivac Day:
- Step 1: Try to leave after the Exploration shuttle docks using the medivac shuttle, the Exploration shuttle was never announced as having docked with the station.
-Step 2: Go out to space above V3-b, and we're unable to use manuel controls as they were disabled, and the autopilot never moves the shuttle. I believe it started when either the shuttle left V2, or when the arrived at station. 

---Based on the other instance above, I think it has something to do with docking/undocking at V2, as at that time, as medivac shuttle'd already arrived and also docked.---

**Comment by Wolfmeme** [comment]
Sorry if I didn't put in a lot of details, can possibly give more info/answer questions if you have more. 

I'm doing this in-between rounds, so I'm going fast to try to get in another shift, so I haven't looked at others as examples, etc.

**Comment by Verkister** [comment]
Might be related to this one #8652 considering the timing for the two to happen. Wasn't entirely sure if the shuttle system would be somehow vulnerable to regex failures, but I just did some code diving to find out that there's 2 "main" usages for regex in the code, other being name/chat/examine message related, and the other half being map loading, so I feel like they might likely be related idk.

**Comment by Wolfmeme** [comment]
Seems so, probably two people reporting same thing, was with several people.
