### ISSUE TITLE
Area entry sounds play repeatedly

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#8686]
#### Brief description of the bug
You know those neat sounds that play when you go into different areas?

They seem to play over and over again now every few seconds, or at least, they seem to in the bar.

#### What you expected to happen
For them to just play once when you enter the area

#### Steps to reproduce
- go to bar
- listen to cool bwoms and thum thums over and over
- get annoyed
- reluctantly toggle ambiance :c 

#### Code Revision
- Commit: 6cef1a3bb8f7de4f4920894aaf2d6b7b66281dfe

**Comment by Rykka-Stormheart** [comment]
Should only be once per 60 seconds, but that's intended. If the delay is too short, that can be upped.

**Comment by Very-Soft** [comment]
I mean, I would really prefer it if it was only when you enter the area. Like, I've never wanted to turn ambiance off before, I've always kept all the normal sounds on, and this change made me want to turn it off on my first shift playing. 

Like, if it -must- play multiple times, it should be like, 15-30 minutes, not every minute.

**Comment by H0lySquirr3l** [comment]
Rykka. what makes the normal atmosphere stuff so good is its supringing timing. Adding in new stuff is great, but maybe up the times to be a bit more supringing.

**Comment by Rykka-Stormheart** [comment]
> I mean, I would really prefer it if it was only when you enter the area. Like, I've never wanted to turn ambiance off before, I've always kept all the normal sounds on, and this change made me want to turn it off on my first shift playing.
> 
> Like, if it -must- play multiple times, it should be like once every, 15-30 minutes, not every minute.
> 
> As it is, if you spend any time in the chapel, as a more distinct example, you're gonna be listening to the spooky chanting choir thing every few seconds, and that's not great, it's super distracting.

It's easy enough to increase the amount of delay between calls for the play_ambience()

**Comment by Very-Soft** [comment]
Well, I'd like the delay to be pretty long please. I've always liked the sounds. They're cool for setting the mood and getting a nice audio indicator of where you are, but hearing them over and over and over is only going to get on one's nerves. 

Like, now that I think about it, no more than once every 30 minutes.

**Comment by Rykka-Stormheart** [comment]
> Well, I'd like the delay to be pretty long please. I've always liked the sounds. They're cool for setting the mood and getting a nice audio indicator of where you are, but hearing them over and over and over is only going to get on one's nerves.
> 
> Like, now that I think about it, no more than once every 30 minutes.

You might as well turn off ambience entirely at that point. Once every 30 minutes is **insanely long**. Currently if you just move from one room to the other it will play ambience no more than once per 60 seconds, which is the same delay that the current ambience call uses, once per 60 seconds.

30 minutes is **way too long.** I'd say once every 3-5 minutes is fine, imo.

**Comment by Very-Soft** [comment]
The way that it has always been is that it will play the ambiance sound once when you enter certain areas. When you're moving around to different areas, it's fine for those sounds to play often. They give you an idea of where you are. They set the mood, and add texture to the space, and they only really play when you take action.

When you're sitting in the bar, or at your work space, or in your office, you don't need the mood set every minute, and you wouldn't need it set every 5 minutes. You also wouldn't need it set every 30 minutes, but that's long enough that I don't think it would be too annoying for, if you park yourself somewhere for the whole shift, for the sounds to play 12ish times in a shift.

As is, if you sit in the bar and hang out with people for a whole shift, you're listening to the bar ambiance sounds around 370 times, assuming that time dilation isn't too bad. 5 minutes would still be over 70 times if my math isn't wrong.

 A lot of those sounds are a good 10-20 seconds long too, and having timed it, it plays a new sound about every 60 seconds, not accounting for the length of the sound that just played.

As I said. I have -always- had these sounds on. I like the sounds. But this change made me turn them off on the first shift I played with them. 

Like. Have you actually played a round with this change on?

**Comment by Rykka-Stormheart** [comment]
> The way that it has always been is that it will play the ambiance sound once when you enter certain areas. When you're moving around to different areas, it's fine for those sounds to play often. They give you an idea of where you are. They set the mood, and add texture to the space, and they only really play when you take action.
> 
> When you're sitting in the bar, or at your work space, or in your office, you don't need the mood set every minute, and you wouldn't need it set every 5 minutes. You also wouldn't need it set every 30 minutes, but that's long enough that I don't think it would be too annoying for, if you park yourself somewhere for the whole shift, for the sounds to play 12ish times in a shift.
> 
> As is, if you sit in the bar and hang out with people for a whole shift, you're listening to the bar ambiance sounds around 370 times, assuming that time dilation isn't too bad. 5 minutes would still be over 70 times if my math isn't wrong.
> 
> A lot of those sounds are a good 10-20 seconds long too, and having timed it, it plays a new sound about every 60 seconds, not accounting for the length of the sound that just played.
> 
> As I said. I have -always- had these sounds on. I like the sounds. But this change made me turn them off on the first shift I played with them.
> 
> Like. Have you actually played a round with this change on?

Yes, I've played plenty, actually, including multiple test-rounds. I really enjoy it, personally, and it's why I went and made the change.

I'm looking into something that'll solve the concerns (And address any future ones, tbh):
> Make it a client-side option as to how often you want to hear repeating ambiance
So clients can choose if they want it every x minutes (Where x is the number they type in).

**Comment by Rykka-Stormheart** [comment]
Resolved by https://github.com/VOREStation/VOREStation/pull/8689

Changes made
