### ISSUE TITLE
Grinder Issue

### ISSUE THREAD

**Issue by RomanticalWhale** [VOREStation/VOREStation#8692]
#### Brief description of the bug
Beaker got ejected when clicked, grinding is impossible

#### What you expected to happen
When beaker inserted, it can grind by clicking on it and selecting "Grind"

#### What actually happened
Beaker got ejected instead of grinding with meny popping out

#### Steps to reproduce
- Put beaker into grinder
- Click on grinder
- Beaker gets ejected instantly

**Comment by Rykka-Stormheart** [comment]
Already fixed by https://github.com/VOREStation/VOREStation/pull/8690
