### ISSUE TITLE
There is no bent pipe in the pipe dispenser

### ISSUE THREAD

**Issue by pontifexminimus2** [VOREStation/VOREStation#8703]
#### Brief description of the bug
There is no bent pipe section in the pipe dispenser machine.

#### What you expected to happen
There to be a bent pipe option.

#### What actually happened
No bent pipes options.

#### Steps to reproduce
- Walk up to pipe dispenser
- Use the flashy new interface.
- Scream in utter terror as there is no bent pipes in any menu.

#### Anything else you may wish to add:

https://cdn.discordapp.com/attachments/155509585749344256/744324450677162084/b3aa9e23851cfbe7b716bea65a83f4e7.png

Where are the bent pipes.

**Comment by Rykka-Stormheart** [comment]
Already resolved by https://github.com/VOREStation/VOREStation/pull/8698

**Comment by pontifexminimus2** [comment]
Good, I want my fucking bent pipes.
