### ISSUE TITLE
Mulebot pathfinding is laggy

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#873]
#### Brief description of the issue
If a mulebot gets stuck somewhere, it lags the server because the pathfinding algorithm is apparently fairly intensive, and if it gets trapped then it constantly attempts to find a path.

#### What you expected to happen
For the mulebot to stop trying to find a path if it fails a few times.

#### What actually happened
Cries of lag over OOC.

#### Steps to reproduce
- set mulebot running
- prevent it from reaching its destination

#### Code Revision
- pending, this was reported over discord.
 
#### Anything else you may wish to add:
- might be worth kicking up to Polaris.

**Comment by Screemonster** [comment]
Possible (somewhat hacky) fix:

Every time the mulebot looks for a path, increase a counter by some amount.
Every time it moves a tile, decrease it until it hit zero.
If it exceeds a threshold, stop moving and call for help over the supply channel.

**Comment by Arokha** [comment]
It could get laggy sometimes, yeah! Totally irrelevant now that we have a map that they have zero hope of pathing on at all, though.
