### ISSUE TITLE
Camera Console doesn't respect DEUTER/PROTO-nopia (Colorblindness)

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#8735]
#### Brief description of the bug

As it says on the tin, Camera Consoles display their view in full color, not the colorblind view.

#### What you expected to happen

Me being colorblind would make the camera consoles look colorblind too.

#### What actually happened

Camera consoles were in full/regular color.

#### Steps to reproduce
- Choose Colorblindness trait.
- Look at Camera
 ![](https://i.imgur.com/DlJnxFe.png)

**Comment by ShadowLarkens** [comment]
Not sure if this is fixable, unfortunately. I tried removing NO_CLIENT_COLOR from the atom that has vis_contents added to it, and it still wouldn't show client color.
