### ISSUE TITLE
Surface Cargo missing wiring and pipes

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#8739]
#### Brief description of the bug
Wiring and pipes are non-existent in 3 tiles in surface cargo

#### What you expected to happen
No missing wiring and pipes.

#### What actually happened
Missing wiring and pipes.

#### Steps to reproduce
-Go to surface cargo
-Go to the cycling airlock.
-Pry open the tiles near the maintenance access just south of the airlock.
-See several empty tiles where wiring and pipes should be.

#### Code Revision
ea017e7c86ec677c6d5fe6d5e187ac2d7d1b34a7 
 

#### Anything else you may wish to add:
![surfacecargomissing](https://user-images.githubusercontent.com/33539568/90570276-b4ceac00-e1f2-11ea-83cf-fe7f29c1d4cc.JPG)

**Comment by TheFurryFeline** [comment]
If this ain't fixed by the 21st, I'll PR it. Just waiting on a new data cycle and faster wifi speed that'll allow me to do things better.
