### ISSUE TITLE
Fluff Item Application - Penelope Allen - Xsdew

### ISSUE THREAD

**Issue by Xsdew** [VOREStation/VOREStation#874]
Name of Item: Medical Swimsuit
     
Item description: 
A swimsuit colored in the style of the medical department, for those who
wish to represent their department off-duty. 

Sprites: 
I have the sprites, If needed I can post it to a drop box. Or create the pull request at a later time containing the needed sprites.

Any additional resources: none

BYOND Key: Xsdew

Name of Character: Penelope Allen

Main Job(s) of Character: Medical

Why your character should have this item:
Penelope likes to enjoy the pool located in the facility during off-duty or during long breaks. However using the provided public swimsuit is rather unpleasant to Penelope. And would like to bring her own personal swimsuit. In the style of her work department. 

Additional Notes (If it's a permit, insert the information for the permit here):

Fluff Item slots already used: 0, this would be the first item.

**Comment by JoanRisu** [comment]
Well, since someone is working on swimsuits I don't really see a problem with this. Approved pending the merge of a PR.
