### ISSUE TITLE
Mobs can attack from inside stasis cages

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#8748]
#### Brief description of the bug
after you put a netted mob inside a stasis cage it will attack the person who put it in

#### What you expected to happen
it not to attack

#### What actually happened
it can attack

#### Steps to reproduce
- (Step 1)net a mob
- (Step 2)put in stasis cage
- (step3) it will attack and can kill you if strong enougth 

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 ea017e7c86ec677c6d5fe6d5e187ac2d7d1b34a7 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by aryll-linton** [comment]
This seems to have been fixed some time in the last month. Testing with spiders and solargrubs display intended behavior.
