### ISSUE TITLE
port "signaler QoL" from /tg/

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#875]
#### Brief description of the issue
https://github.com/tgstation/tgstation/pull/23340

Simple QoL change that lets you use signalers on other signalers to copy the frequency and code over without having to click a million times.

Removed most of the rest of the template 'cause it's a feature request rather than a bug report :v

**Comment by Leshana** [comment]
I have opened a PR to Polaris for this.

**Comment by Leshana** [comment]
Merged'ed
