### ISSUE TITLE
Deleting a mech makes it explode

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#877]
#### Brief description of the issue
Deleting a mech makes explosions and wreckage.

#### What you expected to happen
For it to just be DELETED. Not damaged, exploded, or anything else that would generate a Z-level wide BOOM sound effect when I just wanted to QUIETLY REMOVE something that was ICly being sent down in the elevator.

#### What actually happened
ADMIN LOG: Scree/(Scree) deleted Scuttlebug at (139,119,1)
ADMIN LOG: Explosion with size (0, 0, 1) in area Main Elevator (139,119,1) (JMP)
 [Common] Jane-Luc Price (follow) asks, "...What was that?"

#### Steps to reproduce
- spawn a mech
- delete a mech

#### Code Revision
- Server revision: release - 2017-01-25
0c5a960215ee9e0ddc8367c49f8e87bed5e06869 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
The Destroy() proc is called when items are qdel()'d, and when the mech is destroyed. It's just the same proc. Which was probably a poor decision. tbh just send it to the shadow realm (loc=null), or, edit the "wreckage" var to be nothing, and it won't create wreckage. The explosion will still happen, though.

**Comment by chaoko99** [comment]
Could always just do a snowflakey proc override for Qdel()

**Comment by SpadesNeil** [comment]
The explosion doesn't damage anything and this prevents glitches such as C4 making mechs disappear entirely. I do not think we should fix this.
