### ISSUE TITLE
Captains Spare ID give errors

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#8809]
## Brief description of the bug
When left-clicking the spare captains ID as a ghost, you get a big window error instead of anything else. Normal ID's don't seem to be affected, at least not a player on site. 

#### What you expected to happen
ID info pops up

#### What actually happened
Error message, see the screenshot bellow

#### Steps to reproduce
- Locate the spare captains ID
- Click it as a ghost

Revision
- ea017e7c86ec677c6d5fe6d5e187ac2d7d1b34a7 

#### Anything else you may wish to add:
- https://i.gyazo.com/57820ca38b90ef8d4b8040d3d334c77d.png

**Comment by Shadow-Quill** [comment]
Is this still an issue?
