### ISSUE TITLE
Fuel Depot has very little fuel

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#8830]
#### Brief description of the bug
It runs short on pressure very fast, resulting in it quickly becoming extremely slow, and then unable to refill canisters

#### What you expected to happen
It to be excellent at refuelling, being a fuel depot

#### What actually happened
A single fuel run can empty it completely.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 38f6ff2404faee4972000636bfab1327432d0de5

**Comment by VictorZisthus** [comment]
Oh right, I should add this to my OSHApass map

**Comment by VictorZisthus** [comment]
Rip. New PR time lol

**Comment by VictorZisthus** [comment]
Oh dear. It looks like map edits won't be enough to solve this issue. Just spent the last few hours trying to get that to work, but no such luck.

**Comment by VictorZisthus** [comment]
Meghan showing me up with those coding skills. W E H.
