### ISSUE TITLE
Update that added borg patting broke giving them cell upgrades

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#8847]
#### Brief description of the bug
What it says right in the title. Looks like the update that enabled us to pat borgs on help intent botched our ability to give them cell upgrades thanks to removing cells being tied to just clicking opened borgs with an empty hand...which now pats them.

#### What you expected to happen
I'd just pop the cell right out

#### What actually happened
I just gave the borg some pats.

#### Steps to reproduce
- Be a roboticist or someone with access to robotics
- Get a borg to let you open them up for a cell upgrade
- Click them with an empty hand once they're opened

#### Code Revision
- Server revision: B:release D:
Commit: 38f6ff2404faee4972000636bfab1327432d0de5

**Comment by Cyantime** [comment]
Needs to be on grab intent now, which isn't conveyed anywhere.
