### ISSUE TITLE
Fluff Item Application - James Holder - CockatriceXL

### ISSUE THREAD

**Issue by CockatriceXL** [VOREStation/VOREStation#886]
Name of Item: Cloning Data Disk

Item description:
A small floppy disk for saving and loading cloning records.

Sprites: VOREStation/icons/obj/cloning.dmi

Any additional resources:
The item already exists in the code here: VOREStation/code/game/machinery/cloning.dm
And its interactions with the cloning console are here: VOREStation/code/game/machinery/computer/cloning.dm

BYOND Key: CockatriceXL

Name of Character: James Holder

Main Job(s) of Character: Medical Doctor, Paramedic

Why your character should have this item:
After being cloned at Central Command, James developed strong anxiety towards the idea of being digested and forgotten, left to be cloned off site with no memory of what happened to him and only the knowledge that nobody knew he died or cared to do anything about it. He'd like to bring a disk along with him to save a copy of his cloning data, in hopes that one of his friends can be there for him, and save a copy if he's taken off station and digested, or if someone he trusts would like to eat him over a period of days without leaving him to wake up without his memory and assume the worst. As a doctor, James is trusted to handle cloning, and he was awarded a metal for serving in an away mission.

Additional Notes (If it's a permit, insert the information for the permit here):

Fluff Item slots already used: 0.

**Comment by Arokha** [comment]
You know the life crystal things are like exactly for this, right? ;o Regardless, if you don't wanna use those, I'd support this item. Aren't cloning data disks already on station somewhere? If not, why don't we just make this one already start with your scan data? Or, not what you want exactly?

**Comment by CockatriceXL** [comment]
He doesn't like the life crystals because he'd just wake up at HAVENS with the same problem. :) I would rather have it blank so somebody can fetch his most recent clone data for RP purposes. I haven't been able to find the disks on the station. Otherwise, James would rush off to grab one every shift.

**Comment by Screemonster** [comment]
Well, a fluff item disk is more complicated than it might first appear. Genetics is randomised every round so we couldn't just pre-load it with a DNA string and offyougo. I mean, it's _doable_ but might require chicanery.

I'm sure they're obtainable in-game though, lemme fire up my test server and have a look.

**Comment by Arokha** [comment]
They are spawnable ingame I think. Honestly you could just do what I do for my centcom ID since I can't put my fingerprint and DNA on it in advance, which is that it just lets you whap yourself with it once, semi-OOCly and it sets itself up.

**Comment by Screemonster** [comment]
I'm pretty sure the old pre-Polaris genetics lab spawned with a box of them. I'm inclined to say this should be brought up as a mapping issue.

**Comment by CockatriceXL** [comment]
I think it works better if the disk is blank at the start of the shift anyway. It wouldn't make sense for him to bring his backup along when he's afraid of being cloned from it. His first assumption when he wakes up would be that he's been forgotten again.

**Comment by Arokha** [comment]
I don't think I quite understand why you want it. But it's sort of irrelevant since it's a simple request.

**Comment by CockatriceXL** [comment]
It's purely for RP. If James doesn't get cloned on station, he still gets cloned off station, but he has no memory of the shift, and he feels lonely and abandoned. If somebody takes a copy of his local scan, and clones him off station with that, he still has CMD for the last few hours or so and wakes up confused, but he has a heartwarming moment with whoever saved him.

**Comment by Arokha** [comment]
So what's the plan then, like, he just gives the disc to a friend at the start of every shift and if they don't see him later then they should go copy his scan data to get the latest copy? Cause if you take it at the start of the shift, seems like it'd still be 'behind' or something? I guess?

**Comment by CockatriceXL** [comment]
Pretty much. It actually works better for the scenario where one of his friends wants to digest him slowly so they can just make the copy before they leave the station, but it's nice to give them a way to help if he does go missing.
