### ISSUE TITLE
Plasteel HULL sheets filling STEEL in autolathe

### ISSUE THREAD

**Issue by VictorZisthus** [VOREStation/VOREStation#8908]
#### Brief description of the bug
Pretty much what it says in the title. Plasteel hull is added to regular steel reserves for an autolathe rather than plasteel reserves.

#### What you expected to happen
Plasteel hull sheets should add to Plasteel reserves in autolathe.

#### What actually happened
They added to stell reserves instead.

#### Steps to reproduce
Plasteel Hull sheets get [not regular plasteel]
Click on an active autolathe that isn't maxed on resources.
Plasteel becomes steel. YAY! No, wait... NOT YAY!

**Comment by Muffindrake** [comment]
I actually had an opportunity to test this out again very recently, some time after we played that. The new autolathe seems to accept both plasteel and plasteel hull as steel sheet, at least on the Talon, so the bug is a little more serious.
