### ISSUE TITLE
dead clowns disappear

### ISSUE THREAD

**Issue by nerdass** [VOREStation/VOREStation#8932]
#### Brief description of the bug
dead clowns disappear

#### What you expected to happen
dead clown to be a dead clown

#### What actually happened
dead clowns disappear

#### Steps to reproduce
- spawn clown
- clown dies
- clown is transmuted via some manner of alchemy into a bike horn, leaving no trace of the body

**Comment by SweetBlueSylveon** [comment]
This is old jank ss13 code. use the clowns/clown instead of the clown/clown. New clowns for the most part have dead sprites.
