### ISSUE TITLE
Feminine Outfits show Pixels

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#894]
#### Brief description of the issue
When wearing any outfit marked as 'feminine', such as the feminine black jumpsuit or any of the feminine undershirt options, a pixel is showing on either side of the torso.

#### What you expected to happen
Those pixels to NOT show.

#### What actually happened
https://www.dropbox.com/s/tls6800d2kk1mm9/Screenshot%202017-02-01%2014.33.23.png?dl=0 I used an empty slot to show this visual bug off.

#### Steps to reproduce
- Be female.
- Wear a feminine outfit.

#### Code Revision
- 1570579f8ad4d4557c62a61c7332e167007e6bc7
 
#### Anything else you may wish to add:
- I believe this may be due to the fact that our server uses the same sprite for male and female torsos, rather than having any sort of difference between them.

**Comment by Dinnel** [comment]
I believe female characters have a bit of hip to them, which isn't shown during setup, but I notice they fit well in-game as a female. I think this is more of a issue with setup, but if something changed I could be wrong.

**Comment by Vorrarkul** [comment]
I do not actually know for certain if it's just setup or not. I will test this when I have the time.

**Comment by Vorrarkul** [comment]
I have just tested, there are no such visible pixels when ingame; it is indeed an error in the character screen.
