### ISSUE TITLE
Space sometimes fails to render

### ISSUE THREAD

**Issue by Tenryumi** [VOREStation/VOREStation#8942]
#### Brief description of the bug
I do not understand why, but every so often, our lovely parallax space just... does not render at all, and leaves a white empty void.
This only happens client-side too. When this happened to me nobody else could see it.
![dreamseeker_2020-08-31_20-31-49](https://user-images.githubusercontent.com/22177874/91790365-313f9280-ebd6-11ea-8d32-b61e42ef0942.png)

#### What you expected to happen
For space to actually render properly

#### What actually happened
Spooky empty white void.

#### Steps to reproduce
- (Step 1) Move Z-levels in space
- (Step 2) Sometimes space will inexplicably not render. I don't know what the rhyme or reason is to it...

#### Code Revision
- 51ddc3f44b950bd918bfca37e764dfd43dc65d05

**Comment by Shadow-Quill** [comment]
I think this is an issue with Byond?
