### ISSUE TITLE
Mining Drill issues ( Yawn Wider Station )

### ISSUE THREAD

**Issue by Tigroon** [VOREStation/VOREStation#895]
Brief description of the issue

Attempted to use the mining drills outside of the mining outpost. While successful at first, they started having issues where they would not completely complete the mining section. Rather, they would continuously shut down.

The batteries were not empty, nor was their holds full. They were properly secured, and wrenched down. Ore scans showed that there were still plenty of materials waiting to be drilled from the underground.

What you expected to happen

Mining to work, and continue as usual.

What actually happened

Got pranked out of some sweet diamond that is probably sitting under the surface, laughing at me now.

Steps to reproduce

(Step 1) Set up mining drill as per usual.
(Step 2) Allow them to drill.
(Step 3) Collapse in defeat as the light turns red without any error warning of either a battery going dead, ore hold being full, or materials underground being depleated.
(Step 4) Reset drill, resume.
(Step 5) Cry in defeat as the red light pops back on, and drilling ceases, only two seconds later.
Code Revision

master - 2017-01-28
073c0e 5df51789 86986c 7c10ae 10ab7c 5a96 9ce0

Anything else you may wish to add:

This has been done on Yawn Wider Station. I've been requested to bring it on over here.

**Comment by SpadesNeil** [comment]
Is this still an issue? It should be fixed now.
