### ISSUE TITLE
Fluff Item - Chakat Tempest - Wickedtemp (Hypo)

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#897]
Name of Item: Tempest's Hypospray
     
Item description: (try to keep it short and sweet): "A custom-made MKII hypospray belonging to Chakat Tempest. There's small print engraved on the handle: "A medicine-cat has no time for doubt. Act now, act swiftly." " 

Sprites (or link to sprites): https://gyazo.com/90370f288f6e98d80b0cc6f315850ea6

Any additional resources: (in a .zip or .7z file, including sounds and DM files with code in them): NA

BYOND Key (Username): Wickedtemp

Name of Character: Chakat Tempest

Main Job(s) of Character: CMO, Chemist, MD. Medical-Only character, sometimes Resident when I want to scene.

Why your character should have this item: Being entirely devoted to Medical and having worked in the department as long as shi has, shi knows just how useful having a hypospray can be. In fact, there's been one case where a patient would have died without it. It also serves the aesthetic purpose of being, well... more purple than the normal hypo!

Additional Notes (If it's a permit, insert the information for the permit here: If I can choose the mix it starts with, 5 Dex Plus, 5 Tramadol, 20 Tricord. If not, the single loaded empty vial is fine, either one. 

Fluff Item slots already used: 2. MedHUD and the taur sprite. The hypo would be the 3rd.

**Comment by Arokha** [comment]
She wouldn't be the first character with a fluff item hypospray 😄
