### ISSUE TITLE
Airlock Name Not Shown On Multi-Controller

### ISSUE THREAD

**Issue by KillianKirilenko** [VOREStation/VOREStation#8974]
#### Brief description of the bug
Airlock names aren't being shown on their master multi-controllers in the TGUI interface. The STATUS OK/OVERRIDE notice appears fine, just no actual name from the sub-controller.

#### What you expected to happen
Airlock names to appear.

#### What actually happened
No names appear!

#### Steps to reproduce
- Set up a multi-controller with one or more sub-controllers
- Open multi-controller UI ingame
- No names!

#### Anything else you may wish to add:
You should be able to view this 'in action' in PR #8926 as the Bearcat, all Mackerel variants, and all Gecko variants are outfitted with multicontrollers and subcontrollers. Admittedly this might be an error on my part as there doesn't seem to be any good documentation on the things in the first place, so I'm just kinda making guesses based on the code and shaking it until the runtimes stop.

**Comment by ShadowLarkens** [comment]
Oh, I see the issue in your code.
https://github.com/VOREStation/VOREStation/blob/b8fc2406b636b5f5e20394a90bf2ca868373e9f5/maps/offmap_vr/om_ships/mackerel_hc.dmm#L28

`child_tags_txt` and `child_names_txt` are designed to be strings, not lists; In the format of ```
child_names_txt = "Port Airlock Control;Starboard Airlock Control"
child_tags_txt = ""mackerel_hc_docking_port;mackerel_hc_docking_star"
```

**Comment by KillianKirilenko** [comment]
Hooray for fiddly, undocumented nonsense.
