### ISSUE TITLE
Another RIG bug

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#9003]
#### Brief description of the bug
The RIG broke and I don't know why

#### What you expected to happen
The RIG to not be broken and to not be permanently stuck with the RIG.

#### What actually happened
See screenshot

#### Steps to reproduce
- I have no idea how to reproduce this at all. I just messed around with it, tried different visors since I slapped every single module into the RIG to see what is broken. And since there's like 3 bug reports in the same day by me, quite broken.

#### Code Revision
- a4f6d03944deebfca428b07914b2ae5a531bbcd2 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/860a307ed2226e87e56cb93ba766e1e7.png

**Comment by HzDonut** [comment]
Oh hey I also broke mine by trying visors. The night vision one worked fine, but any time i tried to use the materials visor, it would say my suit "isn't initialized". After that, the UI just got janky and weird, like not letting me select new primary modules. After that, the blue screen appeared and now i can't interact with some machines at all. Pretty game breaking.
