### ISSUE TITLE
Video Over Communicator lasts 3 seconds then switches back.

### ISSUE THREAD

**Issue by SioxGWolf** [VOREStation/VOREStation#9005]
Any attempts to use the video over communicator results in cameras for 3 seconds, then hard cut back to the source.

#### Steps to reproduce
Step 1: Have a call with someone with a communicator
Step 2: Open a video chat
Step 3: ATTEMPT to watch the video.

#### Anything else you may wish to add:
I am fully up to being a test subject to any experiments to fix said issues, that may be necessary, use me as you wish.

**Comment by SioxGWolf** [comment]
Might have messed up on formatting.

**Comment by TheFurryFeline** [comment]
Duplicate of https://github.com/PolarisSS13/Polaris/issues/6531

**Comment by ShadowLarkens** [comment]
Fixed by https://github.com/VOREStation/VOREStation/pull/9082
