### ISSUE TITLE
Solar trackers dissapear into thin air when dissasembled.

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#9025]
#### Brief description of the bug
Taking the glass out of a solar tracker destroys the tracker.

#### What you expected to happen
Taking the glass out of the tracker to set it somewhere else.

#### What actually happened
Tracker is gone, assembly and tracker electronics are gone too.

#### Steps to reproduce
- Get solar assembly
- Wrench down, put tracker electronics, put glass.
- Try to dissasemble it with a crowbar.
- The whole thing dissapears.

#### Code Revision
- a4f6d03944deebfca428b07914b2ae5a531bbcd2 
 

#### Anything else you may wish to add:
- You can't make solar tracker electronics either.

**Comment by aryll-linton** [comment]
```	if(!tracker)
		if(istype(W, /obj/item/weapon/tracker_electronics))
			tracker = 1
			user.drop_item()
			qdel(W)
			user.visible_message("<span class='notice'>[user] inserts the electronics into the solar assembly.</span>")
			return 1
	else
		if(W.is_crowbar())
			new /obj/item/weapon/tracker_electronics(src.loc)
			tracker = 0
			user.visible_message("<span class='notice'>[user] takes out the electronics from the solar assembly.</span>")
			return 1
	..()
```
This seems to be the guilty code in code/modules/power/solar.dm
My brain isn't big enough to fix this but putting it here will likely make it visible for someone whose brain _is_ big enough.
