### ISSUE TITLE
Generic Sock Coloration marking keeps switching position

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#9026]
#### Brief description of the bug
Every time the round restarts, a character of mines markings start to move, messing up the look.

#### What you expected to happen
Markings staying in the same place I put them after saving

#### What actually happened
Generic Socks Coloration starts climbing up in the layering, messing up the look.

#### Steps to reproduce
- Not entirely sure if it works like that but putting on the bodymarkings how I screenshoted it might do the trick. I don't have any real idea why it is like this.

#### Code Revision
- a4f6d03944deebfca428b07914b2ae5a531bbcd2 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/9df29de6979abb3ff7de5f47cb274715.png How it's supposed to be layered
- https://i.gyazo.com/55e3568c0fb3e43bf456a2ec89f9b390.png How it layers itself when a new round happens

**Comment by Verkister** [comment]
Do you have the "save markings" enabled in the setup vore tab persistence options? I feel like that feature would be the most likely suspect for markings changes happening between rounds and a good place for me to start bug hunting.

**Comment by Huenererschrecker** [comment]
Save markings is at yes. However, as of writing this, the problem hasn't happened yet so I'm not sure if it has fixed itself or not.

**Comment by Huenererschrecker** [comment]
So, I've been keeping an eye on this for a while longer now and said character and said bug does not seem to appear anymore? It might as itself fixed on it's own somehow with a different bugfix. I'm realy not sure and tbh for now I guess ignore that this happened. This is just weird again...

**Comment by Huenererschrecker** [comment]
Alright, I return with more intel. The bug seems to happen whenever I tram out/the round ends. Save markings are enabled right now and it turned into this. I will turn off save markings and report back when/if said bug happens again.
