### ISSUE TITLE
Pupdozer Gas Analyzer prints results twice

### ISSUE THREAD

**Issue by VictorZisthus** [VOREStation/VOREStation#9028]
#### Brief description of the bug
Pupdozer Gas Analyzer prints result twice with one click when scanning Canisters or Pressure Tanks

#### What you expected to happen
One readout

#### What actually happened
Gee bill, how come you get TWO readouts?

#### Steps to reproduce
Pupdozer time
Gas Analyzer time
Scan any canister or Pressure Tank
Double the fun, double the log clog.

**Comment by Meghan-Rossi** [comment]
I think https://github.com/VOREStation/VOREStation/pull/9071 fixed this.
