### ISSUE TITLE
Prey Flavor System

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#903]
Suggestion: Custom taste for being eaten now that there's a taste system for reagents, settable by prey?

**Comment by OrbisAnima** [comment]
Additional suggestion, splashing someone with x might give that flavor, or would injecting the reagent? intriguing.

**Comment by Screemonster** [comment]
Okay, adding an actual mechanical thing for upending a bottle of syrup over someone before devouring them whole would be pretty neat :v
