### ISSUE TITLE
Alien Autopsy Mechanic

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#907]
#### Brief description of the issue
I want to add an alien autopsy mechanic that makes it worth actually taking back bodies of animals to RnD for study. Each body could randomly reveal something about the creature's biology and living habits, and I want to have people pitch ideas on what different things we could talk about when the creature is dissected.

Also, what perks can be gained from this knowledge, if any?

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/94b621b3106703cf3788f62f427ddcd6abbbfb8f
 
#### Anything else you may wish to add:
- All simple mobs will have something worth knowing about for cutting them open.

**Comment by Screemonster** [comment]
This would be neat with the resleeving thing @Arokha proposed. Generating basic bodies at first but scanning in bits of various mobs to unlock new features.

Scan runtime to unlock cat ears and tails :v

**Comment by SpadesNeil** [comment]
Ooooooo I like that.

**Comment by SpadesNeil** [comment]
Alien Chitin would allow the manufacture of better body armor.

**Comment by Arokha** [comment]
> This would be neat with the resleeving thing @Arokha proposed. Generating basic bodies at first but scanning in bits of various mobs to unlock new features.

Ahh, the good old days, of having proposed neat ideas and not having gone through the horror of coding them.

**Comment by Arokha** [comment]
I think @orbisanima was going to do this

**Comment by OrbisAnima** [comment]
Yup! got it assigned from Ace with the following requirements:

I think I left a post on Github a while ago but I am technically at work right now so I need to go over it later
but basically
1. Every mob has a basic set of organs, plus maybe a few custom organs.
2. All mob organs have tech levels attached to them. By default, they're basically worthless.
3. In a mob's definitions, I can change the description and tech levels of internal organs accordingly.
4. When disected with a scalpel, you get a pop window that gives options on which organs to extract.
5 (bonus). Organs can randomly be destroyed/deleted on death sometimes. Rendered useless

We had been a little hard lately at work, so the times I got to spare and I see code my eyes tend to growl a bit, I will try to get it done when I get some time, but lately it has been tricky

**Comment by SpadesNeil** [comment]
I might do this in Polaris code.

**Comment by SpadesNeil** [comment]
@Arokha You can probably understand what I was trying to do but I failed.

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/pull/3652
