### ISSUE TITLE
New UI lacks any way to scroll down or resize windows

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#9072]
#### Brief description of the bug
More of an oversight. All those fancy new UI changes are nice and all but alot of windows (for example everything involving custom circuits or some areas of cargos order history) lack any way to scroll down, making it impossible to see everything.

#### What you expected to happen
A UI to have a way to access all the information with (for example) a scrollbar. 

#### What actually happened
No scrollbar in multiple windows, making it hard to impossible to work said windows.

#### Steps to reproduce
- It's an oversight, so no real need to replicate. The 2 mentioned windows of custom circuits assemblies and cargo order history however are 2 of the windows where said taskbar is lacking. 

#### Code Revision
- a4f6d03944deebfca428b07914b2ae5a531bbcd2 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/7c01d3ac614603ad2c96b5c42fc01f53.png
This is roughly what I mean. There is no way to scroll down, so after 4 things placed inside, you're screwed and gotta mess around with the move to bottom button. Other windows have no such work-around.

**Comment by ShadowLarkens** [comment]
the scroll wheel/two finger drag on a touchpad will still work with UIs lacking a scrollbar, but I'll take a peek at your examples
