### ISSUE TITLE
Cyborgs cannot interact with Power Cell Rack PSU's

### ISSUE THREAD

**Issue by VictorZisthus** [VOREStation/VOREStation#9083]
#### Brief description of the bug
Cyborgs cannot enable/disable charging features or remove cells from the device without deconstructing it.

#### What you expected to happen
Work it harder make it better do it faster make cells stronger

#### What actually happened
Sad borg noises. Must deconstruct the device to remove cells, cannot enable/disable charging.

#### Steps to reproduce
Select a borgo with a Magnetic gripper that can hold power cells.
Mess around with the PSU

**Comment by ShudderEve** [comment]
The PSU rack has two modes:

If the panel is closed, you'll get a pop-up akin to that of an SMES where you can set power input-output.

If the panel is open, you can manipulate individual cells. But I believe it requires one to be standing besides it.

Maybe this is your problem?

**Comment by VictorZisthus** [comment]
> The PSU rack has two modes:
> 
> If the panel is closed, you'll get a pop-up akin to that of an SMES where you can set power input-output.
> 
> If the panel is open, you can manipulate individual cells. But I believe it requires one to be standing besides it.
> 
> Maybe this is your problem?

I'll do some more testing when I get the chance.

**Comment by Runa-Dacino** [comment]
Just to check - was the PSU given a terminal and could organics interact with it?
