### ISSUE TITLE
Wolftaur Armor Vest is offset incorrectly in-hand and on-equipment slot.

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#9099]
#### Brief description of the bug

Wolftaur armor vest appears to the 'right' rather than the center in the item window. It works fine on-mob, though.

![](https://i.imgur.com/BIcVQKu.png)
![](https://i.imgur.com/BkN9F9X.png)
![](https://i.imgur.com/kZmvEgK.png)

**Comment by aryll-linton** [comment]
Looks like this is because the in-hand is using the on-mob frontsprite which is 64 x 32 instead of 32².
