### ISSUE TITLE
Add more mechs!

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#910]
#### Brief description of the project
Right now, the only combat mechs available to the crew are of the likes of the gygax and durand. Otherwise, there's the ripley and the ody.

We need _moar_.

Specifically, more mechs that are suited to _very specific things_.

- [ ] Some sort of light, fast jetpack-mech. Right now the only jetpack-mechs are adminspawn. Or the hoverpod which is ordered from cargo rather than being a robotics thing.

- [x] Combat-frame mech for micros. Really, it wouldn't need to be any more robust than any other crewmember, with similar material requirements (and robustness) to FBPs. Would probably have a new filepath 'cause they wouldn't be able to use normal mecha equipment.

- [ ] A slooooooow tanky thing that's more suited as a point-defence cannon than an attacking force. Something for sending through the gateway and holding it while the rest of the away team operate.

**Comment by Wickedtemp** [comment]
A small, fragile, low-health average speed mech/exo-suit for the Janitor.

• Powerwashers/ChemSprayers that can either automatically produce or be loaded with cleaner
• An AOE mop
• Wet Floor Sign dispenser 
• Potentially a cleaning foam grenade launcher? Maybe not, if it can be loaded with non-cleaning nades
• Can hold 3 clean bots to launch
• An HUD that makes dirt a little more visible for no missed spots (?)
• Has its own built in water/cleaner tank
------
It's a large map, I think janitors would appreciate these toys to help clean it all.

**Comment by Screemonster** [comment]
A cleaner-grenade-launcher would be astoundingly easy to code. Like, hilariously easy.
Literally just make it a child of the flashbang launcher and set its projectile path to point at cleaner grenades instead.

**Comment by Arokha** [comment]
@screemonster DO THIS
