### ISSUE TITLE
Emergency box goggles get contaminated with phoron, nullifying their purpose

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#9102]
#### Brief description of the bug
Within the "Emergency Supply Box" non-explorers start with, the goggles with the "Just plain old goggles" description get contaminated if you only wear them with a mouth-mask, rather than wear a gasmask while in an atmosphere that has phoron. 

Wearing these goggles thus, even if the character is properly covered otherwise, causes toxin damage to accumulate.

#### What you expected to happen
The goggles protecting a character's eyes from phoron to be immune to contamination, like voidsuits, softsuits and gasmasks are.

#### What actually happened
Goggles got contaminated, toxin damage was suffered.

#### Steps to reproduce
- Put on science jumpsuit, wintercoat, winter boots, gloves, breath mask
- Wear emergency oxygen tank.
- Toggle winter coat hood.
- Find atmosphere that has phoron
- Stay there until clothing is contaminated
- Go back to O2/N2 atmosphere, take off all clothes except goggles.
- Watch toxin levels rise still.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:release D:
Commit: a4f6d03944deebfca428b07914b2ae5a531bbcd2 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by VictorZisthus** [comment]
That's quite odd. Was this live or on a custom server?
