### ISSUE TITLE
Blood from a blood bowl infected with a virus crashes the isolator

### ISSUE THREAD

**Issue by Muffindrake** [VOREStation/VOREStation#9127]
#### Brief description of the bug
Artifact blood bowl blood doesn't agree with the pathogenic isolator

#### What you expected to happen
No bluescreen

#### What actually happened
Bluescreen

#### Steps to reproduce
- Obtain blood from a blood bowl artifact
- Take a sample from it, and infect it with the incubator in virology
- Attempt to put said infected sample into the pathogenic isolator
- Observe permanently broken device

#### Code Revision
- a4f6d03944deebfca428b07914b2ae5a531bbcd2

**Comment by Meghan-Rossi** [comment]
https://github.com/PolarisSS13/Polaris/pull/7705 should fix this once mirrored.
