### ISSUE TITLE
Prometheans overeat by existing/eating dust.

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#916]
#### Brief description of the issue
Prometheans constantly gain being fed and take forever to burn it off via exercise, and getting the over fed descriptions.

#### What you expected to happen
To need to eat like a normal person and exercise excess off easily instead of slowly bloating with eating to much.

#### What actually happened
Slowly bloated and lost movement speed

#### Steps to reproduce
- (Step 1)Play a promethean
- (Step 2)Wander around the station
- (Step 3)Slowly gain fatter and fatter overfed descriptions

#### Code Revision
Server revision: release - 2017-02-03
df3c823953c6a7c9b27cd6b56b7c1356f0752b72 )
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment]
Already merged the code to fix this. Will be applicable next update.
