### ISSUE TITLE
TGUI Kitchen Has Undersized Temperature Bar

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#9162]
#### Brief description of the bug

TGUI Oven/Grill/Fryer has undersized temperature bar. It doesn't fill the entire bar even when at 100% efficiency/full temp.

#### What you expected to happen

Full bar

#### What actually happened

![](https://i.imgur.com/5NsEvZp.png)

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
wouldn't that be oversized?

**Comment by Rykka-Stormheart** [comment]
> wouldn't that be oversized?

Possibly? Either way I just want the green bar to fill everything lol
