### ISSUE TITLE
laptop/tablet camera programs on the station point to talon camera network

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#9164]
basically the camera program you download to tablets/laptops point to the talon and entertainment cameras only

**Comment by Heroman3003** [comment]
They are supposed to only have networks you have 'access' to. For most jobs its just entertainment, but someone probably borked up the Talon Network and made it available to everyone.

**Comment by lm40** [comment]
i would think the cd would have access to more than the entertainment network and the talon network
