### ISSUE TITLE
Disable beeping option is missing on new PDA interface

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9179]
#### Brief description of the bug
previously you could disable the beeps that play every time you push any button on the PDA, now you cannot (or if you can, I can't find the option)

#### Steps to reproduce
- use pda
- try to turn off the beeps

#### Code Revision
- 7f729ff313e8b421f547ece99025629b988b90fe

**Comment by TheFurryFeline** [comment]
Duplicate of https://github.com/VOREStation/VOREStation/issues/9168 and fixed on master
