### ISSUE TITLE
Arcade noises from MC are way too loud

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#9180]
#### Brief description of the bug
Noises arcade game program makes are EXTREMELY loud so that they can be heard from across entire room like you are on same tile as the machine

#### What you expected to happen
Porbably not being able to hear it when like 6 tiles away from the person playing, maybe hear faintly

#### What actually happened
8-bit earrape

#### Steps to reproduce
- Just try listenting to someone playing on the edge of screen

**Comment by DemicusMaximus** [comment]
Holy sweet Moses this is very accurate. Several tiles away my poor speakers are being blasted out while at a normally low volume level.
