### ISSUE TITLE
NIFs produce heat in synthetics

### ISSUE THREAD

**Issue by CRTXBacon** [VOREStation/VOREStation#9183]
#### Brief description of the bug
Having an NIF as any full body prosthetic (robot, MMI, drone board) increases body heat. Harmless (in my brief testing) for most, but in teshari FBPs this causes damage accumulation that is lethal within roughly 10 minutes

#### What you expected to happen
Not dying from having a NIF

#### What actually happened
Dying from having a NIF

#### Steps to reproduce
- Be a synthetic teshari
- Have a NIF
- Wait 10 minutes
- You are now dead/dying

Tested on a local server with the latest (as of reporting) github repo rather than whatever revision the server is currently running.

**Comment by Ketrai** [comment]
Clearly synth tesharis were never meant to be

**Comment by Verkister** [comment]
Looks like the teshari heat issue was caused by the FBP heatsink organ using a species body_temperature value as its thermostat and the base temperature value had never been defined for teshari on species level so it was defaulting to human base temperature.

**Comment by KillianKirilenko** [comment]
Moral of the story: don't have your overheat temperature within 10 degrees of your core temperature.

This will need upstreaming as I can replicate it easily with synthtesh on compiled Polaris dmbs as well.

**Comment by Verkister** [comment]
already upstreamed the PR to fix the temps
