### ISSUE TITLE
TGUI Exosuit Fabricator and Prosthethics Fabricator UI has issues displaying list of printable objects when a search was done and the interface was closed before the search was deleted. (video included for clarity)

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#9184]
#### Brief description of the bug
The TGUI GUI for the Exosuit Fabricator and the Prosthetics Fabricator experiences a display bug when the following is done:

Player A opens the fabricator GUI, types something into the search bar
Player A closes the interface without deleting the input from the search bar
Player A opens the interface again, and cannot 

#### What you expected to happen
For the search bar to display the search made between opening/closing the interface OR to reset the search and display default thingy.

#### What actually happened
List borked. Can't explain well with words, included video.

#### Steps to reproduce
- Join as roboticist/scientist
- Go to robotics lab
- at EITHER the exosuit fabricator or prosthetics fabricator, click on the machine while wearing your I.D.
- Click on the various tabs to the side to appreciate the options
- Write the name of a random item on the list into search bar.
- Click on various tabs again, note it doesn't change what's displayed.
- Close the interface
- Open the interface, note the search bar is empty, but it still only displays what you searched
- Click on the various tabs, notice the fab is "broken", proceed to write a github report, then realize the fab is not broken, but instead you need to type something into the search bar and then delete it.

#### Code Revision
Server revision: B:release D:
Commit: 7f729ff313e8b421f547ece99025629b988b90fe 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Video proof moot. My screen recorder ignores TGUI.
Hopefully reproduction thingy helps

**Comment by ShadowLarkens** [comment]
yeah I couldn't figure out a way to prevent this from happening, it's "fixable" by just clearing the search bar manually
if anyone has any ideas on how to make it work
