### ISSUE TITLE
Vorepanel warns about unsaved changes on settings that cannot be saved.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#9192]
#### Brief description of the bug
Vorepanel does its "unsaved changes" warning when changing settings that aren't a part of the persistent prefs, such as digest mode and hunger noises.

#### What you expected to happen
For it to not yell me to save settings that cannot be saved.

#### What actually happened
Non-persistent settings triggered the unsaved changes warning.

#### Steps to reproduce
- (Step 1) Change a vorepanel setting that isn't a part of the saved prefs.
- (Step 2) Receive warning.

#### Code Revision
- 7f729ff313e8b421f547ece99025629b988b90fe
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ShadowLarkens** [comment]
This is because all of the persistent and non-persistent easy settings go through the same proc, so it was easiest to just flag unsaved changes as soon as that proc is called... plus, I wasn't actually sure what *is* and *isn't* saved. Hunger noises are not saved?

**Comment by Verkister** [comment]
Yeah, the noises and the bellymodes are something that needs to be manually set every round.
