### ISSUE TITLE
URL Links are Broken???

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#9197]
#### Brief description of the bug

http://%22https//i.imgur.com/VelIcQU.jpg%22

This happened when I tried to open a link, this is the link normally:
https//i.imgur.com/VelIcQU.jpg

It seems BYOND is injecting http://%22 before and %22 after the link, it's doing this to EVERY SINGLE LINK.

I restarted the client and this persisted.

**Comment by ArgobargSoup** [comment]
Can second this, this happened to me last night, and upon a quick check, happened just now.

Server revision: B:release D:
Commit: 7f729ff313e8b421f547ece99025629b988b90fe

**Comment by Rykka-Stormheart** [comment]
After a restart, it's also doing:
http//%22i.imgur.com/VelIcQU.jpg%22

so it's inconsistent, too.

**Comment by Fluffy74** [comment]
Happens to me as well. Seems like it works for links in the chat as well as Wiki button links. Using Chrome, client sends the link in quotes, so it fails to work in the address bar

**Comment by Rykka-Stormheart** [comment]
Update your BYOND version, that fixed it for me.

**Comment by H0lySquirr3l** [comment]
Server revision: B:release D:
Commit: d2d1b2671ea50d4d553c7195a947b5ef3bbef1c3 

This Has been fixed and issue should be closed.

![image](https://user-images.githubusercontent.com/34927367/107458608-0b6dd080-6b1a-11eb-9d45-aea2e5d472e4.png)
