### ISSUE TITLE
Cup ramen when added water gives severe burns to characters with "cold adapted" trait

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#9198]
#### Brief description of the bug
Cup ramen when added water gives severe burns to characters with "cold adapted" trait, requiring ointment and bandages to fix.

#### What you expected to happen
To not receive severe burns when eating ramen

#### What actually happened
Needed medical attention from ramen

#### Steps to reproduce
- Make character with cold-adapted trait
- Buy a cup ramen from vendor
- Add water to cup ramen twice
- Eat
- Suffer

#### Code Revision
Server revision: B:release D:
Commit: 7f729ff313e8b421f547ece99025629b988b90fe 
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Verkister** [comment]
The trait's temperature numbers are just fucked in the same way they were for tajaras and teshari synths cause nobody seems to have jack shit clue what a Kelvin is and just replaces the deadly thresholds with mundane regular body emperatures.
