### ISSUE TITLE
Fluff Item - Vinjj (Reskinned Welding helmet into bandanna-goggles combo)

### ISSUE THREAD

**Issue by Whiskyrose** [VOREStation/VOREStation#920]
Name of item: Vinjj's Stylish Bandanna

Item description: A lovely blue and purple bandanna with a refined topaz hanging from its tail end, a pair of goggles are hidden underneath its fabric. Although for some strange reason, wearing this seems to inspire lewd thoughts..

Sprites (or link to sprites): http://imgur.com/a/nNehp http://imgur.com/a/NuZFf 
https://cdn.discordapp.com/attachments/263941359105343491/278014985622388736/vinjjbandana.dmi

Any additional resources: (in a .zip or .7z file, including sounds and DM files with code in them): None 

BYOND Key (Username): Whiskyrose

Name of Character: Vinjj

Main Job(s) of Character: Xenoarcheologist, Atmospheric Technician, Shaft miner

Why your character should have this item: Almost every shift Vinjj has found the need for a pair of welding goggles, and with how easy they are for him to acquire in his three main jobs, he's decided to cut the middle man out and get himself a custom pair, along with a fashionable bandana to match! 

Additional Notes (If it's a permit, insert the information for the permit here: The DMI file lacks a code, but all it will require is the welding helmet's code, minus of course the armour bonus given by it. Toggle will make the goggles go up and down of course and will need toggle text to match if possible! All so, I still want his ears to poke out~

Fluff Item slots already used: 0

**Comment by Screemonster** [comment]
I think that icons are labelled the wrong way round (goggles cover the eyes when the bandana is "up") but otherwise looks kinda cute. No inventory icon sprite though.

**Comment by Whiskyrose** [comment]
Agh, I knew something was wrong! I was staring at what I'd typed down for ages, but that should be those issues hopefully fixed thanks to Andy. We've even gotten a inventory icon sprite sorted.

**Comment by JoanRisu** [comment]
Once this is resolved, I will label this as approved pending

**Comment by Whiskyrose** [comment]
Well Andy has sorted the issue with (goggles cover the eyes when the bandana is "up") in the dmi file as well as add in the sprite icon. But if you're talking about the code then yeah, that's all it lacks. 

Is someone able to assist with that here or should I search around for help with it?

**Comment by JoanRisu** [comment]
Oh no, I was talking about the sprite. I'm pretty sure anyone who can do basic coding for items can code it for you. 

If the sprite itself is sorted out, I'll label this as Approval Pending.
