### ISSUE TITLE
Medical and Security records are completely unusable from master branch

### ISSUE THREAD

**Issue by cadyn** [VOREStation/VOREStation#9214]
#### Brief description of the bug
TGUI Bluescreens when actually trying to use medical or sec records.

#### What you expected to happen
To be able to use records without getting bluescreens

#### What actually happened
Bluescreen pops up

#### Steps to reproduce
- Go to medical laptop or security records laptop
- Log in
- Click someone's record.
- Nice now there's a bluescreen and I can't do shit.

#### Code Revision
Branch: master
Date: 2020-10-13
Revision: e805ccf0a60bc034f26d8bdfd49dd0e2acd93855
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KillianKirilenko** [comment]
There should be a crash dump or stack trace that shows up from this. Paste it in if you can, it'll help.
