### ISSUE TITLE
New alt-titles for jobs

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#924]
#### Brief description of the issue
A couple of folks in the discord have suggested adding "maid" as an alt-title for janitor, seeing as the uniforms are already in. Though we have lizards that can occasionally use the verbs-the-noun naming convention, adding the polishing of spears as a feature as well is unnecessary.

Another one that has been brought up is "Deputy Director" as an alternative to Head of Personnel. Should hopefully make it clearer where they lie in the chain of command given the eternal arguments about "acting director" and such.

#### Code Revision
- Server revision: release - 2017-02-03
df3c823953c6a7c9b27cd6b56b7c1356f0752b72

**Comment by SpadesNeil** [comment]
I am okay with both of these things.
