### ISSUE TITLE
Species pronouns are overriding the character setup ones

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#9281]
#### Brief description of the bug
Species with ambiguous_genders var enabled cannot use the pronouns selected in char setup.

#### What you expected to happen
For the species var to not override the character's var.

#### What actually happened
Species var said fuck your genders.

#### Steps to reproduce
- (Step 1) Pick species with ambiguous genders var enabled. (unathi, tesh, maybe more)
- (Step 2) Set your pronouns.
- (Step 3) Examine ingame.

#### Code Revision
- 7f729ff313e8b421f547ece99025629b988b90fe
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Heroman3003** [comment]
That's weird. At the very least, it should be displayed properly for members of same species unless that broke at some point?
