### ISSUE TITLE
DIY custom foods (burgers, soups ets) gain no nutritional content from ingredients

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#9292]
#### Brief description of the bug
Buildable foods such as soups and burgers don't get any additional nutritional content from added ingredients, no matter how much you stuff in. They always deplete in two bites and only give the nutrition of their "empty" stage.

#### What you expected to happen
For bigass burgers to give a proper bellyful.

#### What actually happened
Deleted in 2 bites with jackshit effect on hunger.

#### Steps to reproduce
- (Step 1) Create the biggest most impressive mountain of a burger.
- (Step 2) Bite in, expect a feast.
- (Step 3) Qdel on second bite.
- (Step 4) Crumble under disappointment.

#### Code Revision
- 7f729ff313e8b421f547ece99025629b988b90fe
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Zeldazackman** [comment]
Not stale as it's still an issue for whatever strange reason.
