### ISSUE TITLE
Notice Boards Broken

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#9295]
#### Brief description of the bug
Notice boards do not display any messages, and also cannot be interacted with to remove a note.

#### What you expected to happen
To be able to read notices, and remove one already placed.

#### What actually happened
Nothing. 

#### Code Revision
Server revision: B:release D:
Commit: 7f729ff313e8b421f547ece99025629b988b90fe

**Comment by TheFurryFeline** [comment]
After taking a look at https://github.com/VOREStation/VOREStation/blob/master/code/modules/persistence/noticeboard.dm#L57, I'm not sure if the tgui_interact proc is being called with the attackby proc. There's a ``return ..()`` after an else if rather than a final else. Maybe this is the problem?

**Comment by TheFurryFeline** [comment]
Tram Noticeboard seems to be fine as of this posting? Weird. 
![image](https://user-images.githubusercontent.com/38586851/103414723-21689880-4b4d-11eb-8bb0-21b8dcf75b8f.png)
Can remove and interact with that particular one. May need to check the others.
