### ISSUE TITLE
Mecha projectile weapon ammunition is... strange.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#930]
#### Brief description of the issue
This ties in with #910 - essentially mecha are _badass_ as a sci-fi concept. Right now, they have both projectile and energy weapons available. Firing an energy weapon depletes the mech's cell. Projectiles, on the other hand, have an internal magazine and reloading it.. depletes.. the... mech's... cell.

#### What you expected to happen
For projectile weapons to have a tradeoff versus energy weapons, having the advantage of not running the cell down and thus allowing the mech to be more mobile, but a disadvantage (particularly on away missions) that pilots would be limited to whatever ammo the away team brought with them.

#### What actually happened
Effectively, all weapons are energy weapons. Even rocket launchers. _Especially_ rocket launchers.

#### Steps to reproduce
- lload a mech with an energy relay and a scattershot or AC20.
- Unleash dakka
- rearm and repeat forever

#### Code Revision
- tbc
 
#### Anything else you may wish to add:
- support crew using a mech as cover and feeding it ammo while holding the line on an away mission would be fucking _badass_
- reloading could probably be accomplished by creating a magazine item, with the attackby() proc when clicking the mech looking for a compatible weapon and transferring its contents to the weapon.

**Comment by ArbyTheDragon** [comment]
Bullets from energy. It makes about as much gameplay sense as Odysseus making reagents from its battery on a server where chemistry dispensers don't recharge. (I'd be in favor of disabling the recharge of dispensers btw. Chemistry is more useful than actual doctors.)
_Maybe we should take the mech machine gun and rename it "The Patriot" after the infinite ammo weapon from the Metal Gear Solid series_

The meta that would come from this change might have mechs using ammo based weapon whens they have to be energy efficient- such as when they're far away from the station on gateway operations!
