### ISSUE TITLE
Antagonist Encryption Keys are non-functional

### ISSUE THREAD

**Issue by ItsTheKet** [VOREStation/VOREStation#9303]
**Brief description of the bug**
The Standard Encyption Key has no function from it's interception function, to even trying to communicate in it's radio channel.

**What you expected to happen**
To be able to hear other comms and be able to hear the unknown channels without any complication.

**What actually happened**
Absolutely Nothing.

**Steps to reproduce**
- Obtain the Mercenary Encryption Key
- Put it in the headset
- Attempt to talk into the merc channel
- Nothing
- Listen to the (relieving) silence of not hearing other comms either due to interception failing

 
**Anything else you may wish to add:**
- There is currently a temporary solution to this, using an adhoc radio and a raider encryption Key, however. It's not exactly the most ideal solution.

**Comment by Novacat** [comment]
Maybe resolved by https://github.com/VOREStation/VOREStation/pull/9304
