### ISSUE TITLE
Grower pod stops growing

### ISSUE THREAD

**Issue by ZodiacShadow** [VOREStation/VOREStation#9305]
#### Brief description of the bug
The grower pod used for resleeving seemed to be stuck for entirely too long.

#### What you expected to happen
Grow body, body gets spat out after a short while at full health ready for getting conscious.

#### What actually happened
Body growing process stalled at 102% for a long time. Eventually spat out the body, anyway, but may have never gotten further than 102%, as the patient didn't recognize themselves.

#### Steps to reproduce
- Grew a person's body.
- Jackpot?

Got asked by Rykka in LOOC if this issue was still there, so... others may have more info. I haven't seen it before.

**Comment by dwinters99** [comment]
i've had this happen a few times, especially with people who were sleevedmated post-mortem
i've had it get stuck anywhere between 98% and 109%, and it's not reproducable on my side so no clue what's causing it but it's presumably something to do with the somewhat-old-at-this-point ghost changes and the relatively new but still a bit old now TGUI sleeving
