### ISSUE TITLE
Buckling Hampers PDA'ing. :C

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#9306]
#### Brief description of the bug
Unable to interact with PDA features while buckled.

#### What you expected to happen
Free access to Messenger

#### What actually happened
Cry when you need to unbuckle.

#### Steps to reproduce
- (Step 1) Buckle to chair
- (Step 2) Have PDA open
- (Step 3) Try to use it.
- (Step 4) Cry.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 [ 7f729ff313e8b421f547ece99025629b988b90fe]

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Runa-Dacino** [comment]
Fixed by https://github.com/VOREStation/VOREStation/pull/9161 , which should be merged in https://github.com/VOREStation/VOREStation/pull/9300 update

**Comment by TheFurryFeline** [comment]
Derp.
