### ISSUE TITLE
Teshari Sprite issues for Protean

### ISSUE THREAD

**Issue by Chargae** [VOREStation/VOREStation#9308]
#### Brief description of the bug
Am tesh shaped but have weird black shape looming behind me as Tesh-Protean

#### What you expected to happen
Be teshari shaped

#### What actually happened
Became an eldritch monstrosity.

#### Steps to reproduce
- (Step 1) Be Protean
- (Step 2) Become Teshari shaped
- (Step 3) Fear yourself

**Comment by Chargae** [comment]
Changing from DSI prosthetics sprites to Cenlimi elimitated the spooky body excluding the eyes which are now hovering overhead. I think the same thing happens with custom species, after my attempt to workaround tesh-synth overheating.

**Comment by KasparoVy** [comment]
A screenshot of this occurring and of your character setup screen would be awesome to get an idea of what's not behaving right

**Comment by Chargae** [comment]
Alright. Sorry for the delays. This is DSI limbs on a teshari: https://gyazo.com/e50e57a9067d8221afd6b6ec15b32a43

This is an organic custom species teshari with the same hair style. Note eyes float above head: https://gyazo.com/7d3823f0bddab777a77f0bbfd9cb5de6

Protean: Using DSI Teshari (With species fit to suit)
https://gyazo.com/d718f7b922271313cd36564d329dd761
https://gyazo.com/d98f40cbf6d6e7beec5ae4a745329bc1
Ghost boi behind the sprite, eyes located where they would be on normal species.

Using Unbranded/Cenlimi limbs:
https://gyazo.com/616a6eee4dce11f4782df4c1dd8da6c1
https://gyazo.com/739120dcab4b2cf275c32228cc7ccfdb
No ghost boi, but eyes still float over head.

**Comment by KasparoVy** [comment]
No worries, thanks for the screenshots - much appreciated. Will help with troubleshooting
