### ISSUE TITLE
Cyborg analyzers show external prosthetics twice

### ISSUE THREAD

**Issue by TheToaster98** [VOREStation/VOREStation#9331]
#### Brief description of the bug
When analyzing a FBP or any other synthmorph, proteans included, "Internal prosthetics" Shows both Internal and External.

#### What you expected to happen
External parts to only appear on External.

#### What actually happened
"External prosthetics" appearing both on external and internal.

#### Steps to reproduce
- Analyze a synth.
- Read carefully.
- Be confused.

#### Code Revision
- cb5d4e31904bd98b6c26882e4c51f9c69e8e258f 
 

#### Anything else you may wish to add:
-Screenshots:
![unknown2](https://user-images.githubusercontent.com/51209769/99853398-2a943c00-2b83-11eb-98db-7b96e8d7aadc.png)
![unknown1](https://user-images.githubusercontent.com/51209769/99853403-2b2cd280-2b83-11eb-988b-31ce09d79597.png)

**Comment by Runa-Dacino** [comment]
I wonder if this is related to the issues with
getting bruised giving the same pain messages as internal organ damage.

Might be resolved by https://github.com/VOREStation/VOREStation/pull/9323 

Worth testing if anyone's able?
