### ISSUE TITLE
Protean death bug - Unable to ghost

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#9332]
#### Brief description of the bug
Everytime proteans die(At least everytime my protean died) I go to a black screen, showing me the "No gravity" icon and basically still somehow alive but not able to ghost whatsoever. But the protean body is actually dead. There is also no Protean posibrain, it gets deleted instantly. Unable to ghost and thus always need admin intervention to spawn a mob(Brain) and put me in there so I can actually ghost and return to the menu.

#### What you expected to happen
I die. I am ghost. Did not happen.

#### What actually happened
Got shot by bullets, turned to blob form at some point, blob form took fatal damage and boom. It happened.
Though laser rifles instantly put me into blob form and just a few more shots ended me and same thing happened. So far every death ends up the same.

#### Steps to reproduce
- (Step 1) Get shot.
- (Step 2) Die.
- (and so on)

**Comment by lm40** [comment]
i am not sure how this happens but your brain/whatever you are contained in upon death somehow ends up with a null location and i think that prohibits ghosting somehow

**Comment by H0lySquirr3l** [comment]
Server revision: B:release D:
Commit: d2d1b26

I just tested this on a server and it seems to have been fixed I was able to spawn in and take a trip through the trash shoots. Was able to ghost after and it seemed to have spawned everything needed. I did not attempt to resleeve. 

![image](https://user-images.githubusercontent.com/34927367/107555889-52e97080-6b9d-11eb-8849-7ae2f6c60947.png)
