### ISSUE TITLE
Shuttles sometimes break after  short jumps

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#9347]
Legit dunno how to reproduce this 100% of the time but it happens often enough that it is starting to get annoying.

Basically sometimes after trying to jump from a landing site back into space with the short jump console, the shuttle doesn't actually appear on the overmap and the helm controls are unavailable. You are still able to jump back and forth from the landing sites in the grid but never seem to regain the ability to actually get into space and fly.

**Comment by Very-Soft** [comment]
I think this has been fixxed, haven't had this problem in a while
