### ISSUE TITLE
Synthetics break Vendors permanently

### ISSUE THREAD

**Issue by Kegsey** [VOREStation/VOREStation#9352]
#### Steps to reproduce
- (Step 1) Be a drone from a dronepod
- (Step 2) try to buy something from a vendor
- (Step 3) break vendor

#### Code Revision
Server revision: B:release D:
Commit: cb5d4e31904bd98b6c26882e4c51f9c69e8e258f

**Comment by TheFurryFeline** [comment]
Duplicate of https://github.com/VOREStation/VOREStation/issues/9345

**Comment by Kegsey** [comment]
> Duplicate of #9345

should've read it first
