### ISSUE TITLE
Latest map changes (11/23): Areas around Surface Sec(Pool, Gym) are not linked to a grid.

### ISSUE THREAD

**Issue by Holdelta** [VOREStation/VOREStation#9354]
#### Brief description of the bug
Areas on Surface such as the pool and gym are no longer linked to a power grid, assumedly because of the changes to Surface Security.

#### What you expected to happen
For it to be linked to a grid at shift start.

#### What actually happened
The area becomes depowered after a while due to a lack of grid coverage.

#### Steps to reproduce
- Shift start.
- Note that all wires are depowered around the pool and gym.

#### Code Revision
- Server revision: B:release D:
Commit: ab85d4b7d13a6adc5cd8bb6408c42138b12ca783 
 
![image](https://user-images.githubusercontent.com/7005665/100039387-f8b8ea80-2db9-11eb-953b-fb41a3d55660.png)

**Comment by Very-Soft** [comment]
thissun's fixxed in https://github.com/VOREStation/VOREStation/pull/9356

**Comment by Holdelta** [comment]
Leaving a couple more just in case these haven't been caught
Robotics Resleeve
![image](https://user-images.githubusercontent.com/7005665/100041789-e8573e80-2dbe-11eb-9e8d-0814c6ec48f0.png)

IAA main hallway
![image](https://user-images.githubusercontent.com/7005665/100041802-eee5b600-2dbe-11eb-9f6b-50b32d37af7a.png)

Missing disposal pipe for xenobio
![image](https://user-images.githubusercontent.com/7005665/100041864-0d4bb180-2dbf-11eb-98fb-742ec9ba8513.png)

**Comment by Holdelta** [comment]
...one more.

Disposal pipe in hallway to Xenobio is pointing the wrong way
![image](https://user-images.githubusercontent.com/7005665/100042573-97484a00-2dc0-11eb-917c-674b77a65994.png)

**Comment by Very-Soft** [comment]
Addressed each of these now too in the above PR, thanks for reporting them!

**Comment by TheFurryFeline** [comment]
More issue(s): Tour Bus APC is at the wrong dir and there's a missing wire connecting its terminal to the lines.

**Comment by TheFurryFeline** [comment]
Got another smol issue found: 
![image](https://user-images.githubusercontent.com/38586851/100455905-808a4780-308d-11eb-9faf-89c2e1cf96f2.png)

**Comment by TheFurryFeline** [comment]
This probably ain't valid anymore with several updoots.

**Comment by TheFurryFeline** [comment]
I stand corrected. Per #suggestions channel on discord, the disposal pipe is still layered above the conveyor.
