### ISSUE TITLE
Circuit Imprinter Bug

### ISSUE THREAD

**Issue by AzericTraveller** [VOREStation/VOREStation#9387]
#### What you expected to happen
I expected the circuit imprinter to remove the ai module from the queue

#### Steps to reproduce
- add AI module design (TeleporterOffline) to the queue without any gold stored
- add Circuit design (telecommunications monitoring console) to the queue
- ???
- witness

**Comment by Runa-Dacino** [comment]
Temporary fix: use a screwdriver-> crowbar on the machine, then add the components that spawned on its turf back to it, screwdriver it back together and then re-sync with the console.
