### ISSUE TITLE
NIFs do not blind synthetics after installation properly/other potential issues?

### ISSUE THREAD

**Issue by Loneguyfly** [VOREStation/VOREStation#9391]
#### Brief description of the bug
https://i.imgur.com/qkB1AUS.png 

As you can see, I am mechanically blind (cannot see emotes, cannot examine things) but I can still see things properly

#### What you expected to happen
Not see things during blindness.

#### What actually happened
The game did not properly blind me. I can still see everything even if the game otherwise acts like I am blind.

#### Steps to reproduce
-  Be a synth
-  Install a NIF
- Observe your lack of blindness

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 0735df0f9aacc24143c8f7f89dcad2769dc2a9f3 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
EDIT: Removed an additional report that I was wrong about regarding synths not getting the exhaustion (they do :v)

**Comment by TheFurryFeline** [comment]
I thought we completely removed the blindness mechanic from calibration period.

**Comment by Loneguyfly** [comment]
> 
> 
> I thought we completely removed the blindness mechanic from calibration period.

If that is intended to be removed as of now then I can confirm that it hasn't been, as it happened to an organic as well.

**Comment by TheFurryFeline** [comment]
Then the conversion to tgui might've had an oversight. May need to get
Shadow on this one.
