### ISSUE TITLE
Portable phoron bores can be reloaded forever with single bars of phoron

### ISSUE THREAD

**Issue by Wrackbang** [VOREStation/VOREStation#9407]
#### Brief description of the bug
The phoron bore can be reloaded forever if you have a stack of a single phoron bar.

#### What you expected to happen
Each reload consumes a single bar in a loop until you either hit the limit or run out of phoron in the stack.

#### What actually happened
When you're down to a single bar of phoron in the stack you're loading into the gun, each loop of the reload adds material to the gun but doesn't consume the bar, allowing for infinite ammo. 

#### Steps to reproduce
- Find a phoron bore and a stack of solid phoron
- Load in a couple bars and notice how the stack decreases in size
- Split off a single bar of phoron and attempt to load that single stack
- Notice the gun fills completely without issue and you still have a single bar of phoron in your hand. Infinite ammo.

**Comment by KasparoVy** [comment]
Lmao, this must be a thing upstream too.
