### ISSUE TITLE
Mecha/equipment names needed

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#943]
I'm going to be making mecha and mecha accessories and I need name suggestions which are things I suck at coming up with on my own.
This issue will be updated as and when I add more shit to the to-do.

- [ ] Janitor Mech
- [ ] Janitor mech mop
- [ ] Janitor mech cleaning grenade launcher
- [x] Micromech laser carbine
- [x] Micromech laser cannon
- [x] Micromech taser
- [x] Micromech shotgun
- [x] Micromech flashbang launcher
- [ ] Ballistic shotgun
- [ ] Ballistic LMG
- [ ] Ballistic anti-materiel gun
- [ ] Ballistic less-than-lethal riot gun

Fling name suggestions in the comments. Coming up with lore things and arms manufacturers for fluff purposes would be neato.
The micromech weapons are essentially modified versions of normal man-portable weapons with a mounting bracket instead of a grip. The ballistic weapons will be equivalents of the existing ballistic weapons but will require external reloading.

**Comment by Screemonster** [comment]
12:17 AM] Xenonia: Mobility Assistance Works develops micro mech
[12:17 AM] Xenonia: MAW
[12:17 AM] Xenonia: B^)
[12:18 AM] Xenonia: Janitor mech: The Washing-Intensive Labor Control Outfit. WILCO

Totally gonna have these. Mobility Assistance Works as a manufacturer/designer of micromechs is too good to pass up.

**Comment by Wickedtemp** [comment]
I was thinking 
The Janinator

**Comment by ArbyTheDragon** [comment]
Wait, a space quest reference? I will make a janitor character just to drive one of those mechs.
