### ISSUE TITLE
Make Infections Great Again

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#944]
#### Steps to reproduce
- Acquire infection
- Never die because infections can't beat Peridaxon. 
- Walk around as a decomposing mess of a human with a Peri IV. Steal Deadpool's identity. 

#### Code Revision 
- I'll edit this in later. I'm on mobile and can't check. It's whatever the current revision is as of this post. 
 
#### Anything else you may wish to add:
- Infections only cause fever, until they reach Acute. From there, all it does is apply minimal damage to internal organs with the acute infection. Every limb and body part could be septic, but as long as the heart, lungs and brain aren't, you don't have anything to worry about. On Polaris, septic infections cause toxins so fast, you generally have to amputate. Infections should cause toxins. 

Also, as a result of infections being pitiful, it means there aren't any symptoms. At all. A patient wouldn't even know they have an infection until it starts causing organ damage. Allowing infections to cause toxins would fix this issue as well. 

Also, right now, there's no way to fix necrotic organs. The necrotic organ repair surgery doesn't work. I've tried. Polaris wiki, Virgo wiki, bay12 wiki, no dice. I believe Polaris is working on mechanical organ replacements, which would be neat. 

And one more "Also,"... Dead organs don't show up on the scanner, at all, which makes it hard to diagnose the issue. There may be other ways to diagnose this, but since this is related to necrotic organs, I feel like it's relevant.

**Comment by Arokha** [comment]
I diff'd our entire organs folder, because those handle the infections, and there aren't any changes to infection stuff. There's one that prevents you from splashing blood while in someone, one that prevents fluid loss while in someone due to burns... and that's about it really.

I think it was probably just a coincidence.

**Comment by Arokha** [comment]
Guess I shouldn't put CR since it has other things that can be worked on like adv scanner tweaks for necrotic organs.
