### ISSUE TITLE
Disposal chutes "Engaged" button doesn't work

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9457]
#### What you expected to happen
Flush stuff down fastly

#### What actually happened
Button do nothing

#### Steps to reproduce
- be drone
- climb in trash
- hit the 'flush' button on the way in
-or just hit the engaged button at all.

#### Code Revision
-B:release D:
Commit: b769996cf087c536bbfbdefd0be6a621bde5d9e1 

#### Anything else you may wish to add:
Not sure if this affects carbon mobs or whatever, but it deffo affects drones at least, and it's annoying being as the disposal system is one of their traversal methods.

**Comment by tigercat2000** [comment]
This is intentional, there should be a message informing you of the failure. Disposals lever is meant to be a physical lever that can't be reached from inside.
```
	if(usr.loc == src)
		to_chat(usr, "<span class='warning'>You cannot reach the controls from inside.</span>")
		return TRUE
```

**Comment by tigercat2000** [comment]
Furthermore, silicons can't interact with the handle at all.
