### ISSUE TITLE
Aheals don't remove bullets/shrapnel

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#9460]
#### Brief description of the bug
Admin rejuvenate doesn't remove embedded shrapnel, causing rejuvenated person to re-die in a matter of seconds. _**It however still does remove implants for some godforsaken spaghetti excuse.**_

#### What you expected to happen
Aheals to work properly.

#### What actually happened
Aheal kept all shrapnel and shit, but deleted our implants, causing the bodies to re-die in no time.

#### Steps to reproduce
Step 1: Have an unfortunate dinner of ballistics with your partner while there's no crew around for recovery on deadshift and decide to give yourselves a second chance to not be roundended for good while having other plans.
Step 2: Rejuvenate yourselves.
Step 3: Instantly perish to shrapnel.

#### Code Revision
- b769996cf087c536bbfbdefd0be6a621bde5d9e1
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Wulfestwulf** [comment]
I just attempted this on a local server and was unable to reproduce this. I was shot by mercs with ballistic guns and got 4 different shrapnels inside me, and once ahealed they all were deleted.
