### ISSUE TITLE
pAI Flavor Text

### ISSUE THREAD

**Issue by Motherforkah** [VOREStation/VOREStation#948]
#### Brief description of the issue
The lack of pAI flavor text. I played a very, very good, or at least I think it's good, RP as a pAI, and I have made a pretty big description of how he looks like, his... "anatomical" structure, if you will. I really put a lot, a /lot/ of detail into it, so I decided to save it via flavor, and here's what I found - there's no option for a permanent flavor to a pAI. It frustrated me quite a bit.
It's not an urgent matter, but it'd be awesome if you added it, since people in here actually play as pAI's sometimes, and it'd be a great deal of help to RP them if they would have constant appearance in their unfolded chassis, and not a drowsy one.

#### What you expected to happen
I expected for a pAI to have a flavor, since there actually was a flavor tab under IC options, which, by my expectations, saved the flavor permanently.

#### What actually happened
It didn't.

#### Steps to reproduce
- Add a flavor pad for a pAI.

#### Code Revision
Server revision: release - 2017-02-03
df3c823953c6a7c9b27cd6b56b7c1356f0752b72 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
Did this get fixed?

**Comment by Arokha** [comment]
This is ingame now

**Comment by TheFurryFeline** [comment]
So.... I was going to make a new issue but this thing is happening once more lately: pAI info do not save properly to a character slot as of server revision 4538389237f9e51dda94af66869ed0481d3317da.
