### ISSUE TITLE
Vorestation Wiki Accounts Unrecoverable

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#950]
#### Brief description of the issue
I have been unable to log into my https://wiki.vore-station.net account since its inception, only being logged in the time I created the account and being unable to log in, proper password or not. I have also been unable to recover this since it never asked for my email and the 'help with logging in' button leads to this: https://www.mediawiki.org/wiki/Help:Logging_in -a completely separate account system with inaccurate information regarding how OUR wiki works.

#### What you expected to happen
To have the option during account creation to add my email so that I may recover the password if I forget it. And for my password to work at all.

#### What actually happened
Each account is a throwaway that can never be logged into once logged out of.

#### Steps to reproduce
- Make an account
- Log out
- Try to log back in

#### Code Revision
- N/A
 
#### Anything else you may wish to add:
- N/A

**Comment by SpadesNeil** [comment]
Doesn't really belong on the Github but fuckit we'll never fix it if we report it anywhere else.

**Comment by Vorrarkul** [comment]
Precisely why I decided to put it here.

**Comment by Arokha** [comment]
You wrote an auth plugin for mediawiki for this so halp me troubleshoot it.

**Comment by Vorrarkul** [comment]
So I have recently discovered that the wiki login works, it just uses the forum login system. I am not sure why I _wasn't_ using that in the first place, but that is how it works, apparently.

**Comment by JoanRisu** [comment]
The logins are actually tied together via the http://auth.vore-station.net/ page. I think resetting and logging in from there actually helps resets your account.

**Comment by SpadesNeil** [comment]
So I guess that's that.
