### ISSUE TITLE
Bug of most Circuitry Workshop wearables being inoperable/unopenable

### ISSUE THREAD

**Issue by TsuPsiLow** [VOREStation/VOREStation#9536]
#### Brief description of the bug
Custom circuitry wearables cannot be opened

#### What you expected to happen
When using the crowbar on any circuit assembly, you should be able to open (or close) it in order to start building circuits inside

#### What actually happened
Of all the electronic [wearable]s I've tested, the only one I was able to use the crowbar on to open and build circuits with was the electronic implant. All the other pieces (boots, chestpiece, earwear, gloves, goggles, headwear, and jumpsuit) did not open. 
Leaving and coming back failed to fix it. 

#### Steps to reproduce
- Integrated Circuit Printer to create an electronic wearable
- Use the crowbar on them, finding that certain ones that don't do anything when you try
- Feel frustrated in your lack of cyberpunk tech

**Comment by Runa-Dacino** [comment]
Shift-clicking should allow you to open them.

**Comment by TsuPsiLow** [comment]
> 
> 
> Shift-clicking should allow you to open them.

It doesn't, or at least, I can't get it to.

**Comment by ShadowLarkens** [comment]
You have to Control+Shift click it with a crowbar
