### ISSUE TITLE
Protean posibrains fall out of the belly when their body is digested

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9538]
#### Brief description of the bug
when digested, protean's brain falls out of the predator's belly.

#### What you expected to happen
Similarly to normal posibrains, I expected them to be deposited into the belly they were digested, and to otherwise be indigestable.

#### What actually happened
brain fall out

#### Steps to reproduce
- be and/or eat a protean
- digest protean
- wait, cuz it takes a while

#### Code Revision
-  B:release D:
Commit: b51953b032a4bfc9d84b5911f58760d6031b4745

**Comment by mel-byond** [comment]
I think this happens to normal synths too if their body expire! Had it happen before in a scene

**Comment by Very-Soft** [comment]
> ~I think this happens to normal synths too if their body expires! Had it happen before in a scene~
> Actually this is different, my fault! I misread the falls out part.

yeh, posi surviving digestion is cool, falling out of belly, not so much

**Comment by lm40** [comment]
happens to borgs too last time I did it, I expect it does that for synths now as well although that wasn't always the behavior
