### ISSUE TITLE
Rapid Piping Device (RPD) prints invisible Heat Exchange Pipes

### ISSUE THREAD

**Issue by Brimcon** [VOREStation/VOREStation#9586]
When placing heat exchange pipes with a Rapid Piping Device (RPD) they wrench down as invisible. Un-wrenching and re-wrenching does not refresh the icon.
![image](https://user-images.githubusercontent.com/7198283/104870413-515dbd00-58fd-11eb-8851-5284bad4c5a1.png)
Heat Exchange Pipes dispensed through the Dispenser do not have this issue.

To reproduce, acquire a RPD, select Regular Heat Exchange Pipes, and place them down on a space tile.
Pipe is placed, but is invisible.
Expected result: Pipe is visible.

Edit: The pipe from the RPD seems to be a different icon tint than the one from the Dispenser.
Brighter tint is Dispenser, Darker tint is RPD.
![image](https://user-images.githubusercontent.com/7198283/104870952-a9e18a00-58fe-11eb-876d-53fa973a5d96.png)

**Comment by izac112** [comment]
We (one of the downstream) had a similar issue a while ago, this is a fix we did for it maybe it could be used up here too?

https://github.com/Yawn-Wider/YWPolarisVore/pull/981
