### ISSUE TITLE
Egg transform + muffles = permanent muffles

### ISSUE THREAD

**Issue by cadyn** [VOREStation/VOREStation#9587]
#### Brief description of the bug
People are still muffled after being ejected from belly in an egg.

#### What you expected to happen
For them not to be muffled after getting ejected.

#### What actually happened
They were still muffled after they got ejected.

#### Steps to reproduce
- Go into belly with muffles turned on
- Have them put you into an egg
- Have muffled voice forever until an admin fixes it

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by TheFurryFeline** [comment]
Duplicate of #9190, I think.

**Comment by cadyn** [comment]
Yep, fix it then bb
