### ISSUE TITLE
Some Old Chat color formatting seems to be broken now

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9603]
#### Brief description of the bug
Admin PMs don't have their red/blue color, and vore flavortext doesn't have its usual blue color
Examine flavortext also doesn't have its blue color formatting, or the different colors for things like displaying species, and the vore belly flavortext and such.

Also lick/smell text, and attack/grab/disarm messages.

#### Code Revision
- Commit: c31f681c9f04f6353b964152cbbb17694859e584

**Comment by TheFurryFeline** [comment]
Should probably add this to my #9375 issue, mlem.

**Comment by Very-Soft** [comment]
This isn't the same issue, this is new issues, related to whatever got changed in the latest patch.
