### ISSUE TITLE
Possible to remove unpowered rigsuit module while rest of suit is deployed.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#963]
#### Brief description of the issue
Request for Help: I think I managed to drop a hardsuit's control module without it taking away the rest of the suit as well. 
to (?): Looked like it's fixed. It all good now?
[Player PM] : Yep, works fine. Apparently when you remove a power cell, the "can't deploy/retract components" from that overrides the "retract everything" from taking off the control module.
to (?): Ah. I'll make a github issue about that as it's probably not intended behaviour. Did it get stuck on you until you replaced the cell?
[Player PM] : It's more like the control module completely lost the ability to toggle the affected components. When I replaced the cell and put the controller back on, the toggle verbs would only work for the helmet (which I'd taken off before unplugging the cell, because FBP). I fixed it by clicking the toggle buttons in the NanoUI hardsuit control panel, getting the components in-hand and dropping them - only for them to be whisked away to the controller's hammerspace, ready to work as intended.

#### What you expected to happen
For EITHER removing the hardsuit control module to remove the hardsuit entirely regardless of power, or for the control module to be irremovable when unable to retract components.

#### What actually happened
A strange limbo-state between either.

#### Steps to reproduce
- Wear module, deploy hardsuit, remove cell, remove module.

#### Code Revision
- Server revision: release - 2017-02-15
26d18e07e36c60a89498499d825a5a8bbda20d60 
 
#### Anything else you may wish to add:
- haven't had a chance to test personally yet.

**Comment by MASMC** [comment]
Was this ever fixed? As I am getting ready to run a testing server, and can test it.

**Comment by SpadesNeil** [comment]
Was this fixed or not?
