### ISSUE TITLE
Diona weight gain, despite disabled in character setup

### ISSUE THREAD

**Issue by ktccd0** [VOREStation/VOREStation#9643]
#### Brief description of the bug
Dionas gain weight and grow fat despite having disabled the weight gain (set to 0) in character preference.

#### What you expected to happen
Characters shouldn't gain weight or lose weight when such are disabled, regardless of how long they are well-fed.

#### What actually happened
Since Diona are constantly well-fed when exposed to light, they quickly hit max weight and gain a description as such:
Her stomach is firmly packed with digesting slop. She must have eaten at least a few times worth their body weight! It looks hard for them to stand, and her gut jiggles when they move.

#### Steps to reproduce
- Be Diona.
- Disable weight gain on character setup.
- Join game and stand in light.
- Watch as weight increases extremely quickly.

**Comment by Novacat** [comment]
Have you tried setting weight gain to an extremely small percentage (.01?) instead of 0. I remember some of the VORE settings not liking 0 values.

**Comment by ktccd0** [comment]
I had not considered that 0 would have less effect than 0.01. I will try that.

**Comment by ktccd0** [comment]
at 0.01, I go from 
`She has a healthy, average body.`
to 
`She has a stuffed belly, bloated fat and round from eating too much.`
within a minute and then
`She has a rotund, thick gut. It bulges from their body obscenely, close to sagging under its own weight.`
before the 3 minute mark. It's still insanely fast weight gain for a species that eats light.
