### ISSUE TITLE
Amber slimes literally kill the server if they breach containment

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#9649]
#### Brief description of the bug
Amber slimes have no limit to how many can reproduce, they will split until the server crashes / freezes.

#### What you expected to happen
Amber slime outbreaks to be a severe IC issue, not an OOC issue for everyone on the station.

#### What actually happened
The slimes will reproduce until there are enough to crash the game unless an admin intervenes.

#### Steps to reproduce
-Feed an amber slime
-Let it reproduce
-Leave the four baby ambers together, a feedback loop is started of ambers feeding ambers.
-At this point, they will continue breeding until there are too many active slimes for the server to handle

#### Anything else you may wish to add:
To fix this I would suggest either placing a hard cap on the amount of slimes that can spawn, or removing the ability for ambers to feed each other.

**Comment by Shadow-Quill** [comment]
Fixed by https://github.com/VOREStation/VOREStation/pull/9648

**Comment by H0lySquirr3l** [comment]
Fixed by #9648
