### ISSUE TITLE
Weapon permit renewal!

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#966]
[I'll try to make this look at least a little official!]

WEAPON PERMIT RENEWAL FORM 34-G
-----------
©Nanotrasen 2556 All Rights Reserved.
This form printed on ***15/Feb/2561*** and is only valid for that date.

**Name of Renewal Applicant (please print):**
*Aronai Kadigan*

**Date of Original Issuance:**
*September 30th 2559*

**Originally Issued By:**
*Joan Risu*

**Permit Applies To:**
*See special notes below. Previously e-gun, changing weapons.*

**Reason for Permit:**
*Self-defense, defense of home/property in NT-controlled regions*

**Permit Duration (see addendum 34-Ga):**
*1 standard year*

**Special Notes (optional):**
*Permit was previously for a lethal/nonlethal combination energy gun. Requesting instead a non-lethal only weapon. Will prevent any serious 'incidents' if stolen. Have selected and obtained a non-lethal weapon from offsite and requesting permit changed to reflect this. Ammunition is flash rounds.*

**I have read the conditions of issuance for weapon permits from Nanotrasen and understand them.**
X  ***Aronai Kadigan***

**Comment by SpadesNeil** [comment]
Virgo-Erigone Sector
Central Command
Office of the Chief of Security
------------------------------
**Subject** | Re: WEAPON PERMIT RENEWAL FORM 34-G

_No notable record of abuse or criminal history to speak of on file. I'm going to forward this to Joan Risu with my approval. She will likely finalize this form. Have a secure day._

**Signed,**
### _Chief of Security, Alex Bowman_

**Comment by JoanRisu** [comment]
# Office of Central Security, Federation Affairs
**Subject** | Re: WEAPON PERMIT RENEWAL FORM 34-G

_Nothing bad on record! Squirrel will give this her full approval!_

**Signed,**
# _Federation Liaison Officer, Joan Kris Risu_

**Comment by Arokha** [comment]
Hooray for foxes!
