### ISSUE TITLE
Particle Gun should be added to RnD

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#967]
#### Brief description of the issue
But for what tech levels? Obviously, combat tech should be part of it; but what else?

And what is needed to build it? Gold and silver, I'm sure. Its construction involves many electronics. Maybe some phoron?

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/2f9071d08b009e5b28bdbdb1ffb2ae5416e9e5f3

**Comment by Arokha** [comment]
Materials probably since it's supposed to be antimatter and containing that probably means materials

**Comment by SpadesNeil** [comment]
> Materials probably since it's supposed to be antimatter and containing that probably means materials
![still shitposting](https://cloud.githubusercontent.com/assets/6484985/23006337/25967a6e-f3cf-11e6-932c-42f4edc80c56.jpg)

**Comment by Arokha** [comment]
I-I was being serious I don't understand what you mean D: "Materials" is one of the tech level things!

**Comment by SpadesNeil** [comment]
Materials tech, got it.

For a second I thought you meant, "Oh yea it needs materials as an ingredient because it exists."

**Comment by Screemonster** [comment]
It's on a par with a laser carbine in terms of ability for the basic model. It should probably get a higher-level version that uses uranium for a self-charging one like the AEG.

Magnets tech would be needed since the gun part of it is a coilgun.

Possibly power for the AM generator?

**Comment by SpadesNeil** [comment]
Magnets are a yes. Power yes.

**Comment by Arokha** [comment]
Oh MAGNETS, I forgot about that one. That makes sense.

**Comment by Screemonster** [comment]
![image](https://cloud.githubusercontent.com/assets/14942479/23039045/1ae7e462-f484-11e6-8534-e29d69f24ee8.png)
Made some more sprites for different variants.
Looking to use one as the basic model with identical stats to an egun (without the stun mode), another for an AEG-equivalent so the miners don't have to go back to the shuttle to recharge constantly, and another for a cannon-type that... well, behaves like a laser cannon.

Since they're a miner thing I'm tempted to make them call getdrilled() on mineral turfs. Can't see people ditching their drills for them considering drills don't run out of ammo, and as long as the self-charging ones recharge more slowly than a drill can drill it should be fine.

**Comment by Arokha** [comment]
@Screemonster do it!!!

**Comment by Screemonster** [comment]
Well, these are the existing design thingies for the AEG and Laser cannon.
The advanced antiparticle rifle and antiparticle cannon are roughly equivalent to these two.
I can't actually find an entry for the basic laser carbine in designs.dm, are they not constructable? Only orderable from cargo? If so, I'll put the basic pistol in a beltminer gear cargo crate along with some other handy-for-roguelike items. 

> /datum/design/item/weapon/nuclear_gun
> 	id = "nuclear_gun"
> 	req_tech = list(TECH_COMBAT = 3, TECH_MATERIAL = 5, TECH_POWER = 3)
> 	materials = list(DEFAULT_WALL_MATERIAL = 5000, "glass" = 1000, "uranium" = 500)
> 	build_path = /obj/item/weapon/gun/energy/gun/nuclear
> 	sort_string = "TAAAB"
> 
> /datum/design/item/weapon/lasercannon
> 	desc = "The lasing medium of this prototype is enclosed in a tube lined with uranium-235 and subjected to high neutron flux in a nuclear reactor core."
> 	id = "lasercannon"
> 	req_tech = list(TECH_COMBAT = 4, TECH_MATERIAL = 3, TECH_POWER = 3)
> 	materials = list(DEFAULT_WALL_MATERIAL = 10000, "glass" = 1000, "diamond" = 2000)
> 	build_path = /obj/item/weapon/gun/energy/lasercannon
> 	sort_string = "TAAAC"

**Comment by Screemonster** [comment]
[9:10 AM] Elemental/Morgosh/ORC: By the way, the only definitive thing I can find regarding antimatter production is a method of making positrons with a laser and a gold target, so maybe a cheaper laser cannon with a bit of gold?

Gold is probably a reasonable requirement for them. Some level of magnet tech. Uranium for the cannon as it's self-charging.

The pressure-interlock safety catch thing should be engineering tech and pretty low material/tech requirements. Probably even just available at roundstart.

Also I have no problem with upping the requirements and buffing them to make them actually superior to their laser counterparts given their only-in-space drawback, or making yet another model that _does_ surpass existing weapons.
