### ISSUE TITLE
Fluff Item - Swat43 (Colourised satchel)

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#971]
Name of Item: Coloured Satchel

Item description: (try to keep it short and sweet) That's a coloured satchel with red stripes, with a heart and ripley logo on each side.

Sprites (or link to sprites):  www.mediafire.com/view/0tpc28bbrbtpue2/Fortunes Bag.dmi

Any additional resources: (in a .zip or .7z file, including sounds and DM files with code in them) None

BYOND Key (Username):Swat43

Name of Character:Fortune Bloise

Main Job(s) of Character:Roboticist (sometimes RD or medical doctor when i feel like doing those..)

Why your character should have this item: Its her mothers gift before her eternal departure. Long story for my character.

Additional Notes (If it's a permit, insert the information for the permit here):No permits.

Fluff Item slots already used: im assuming none currently. This was the first Fluff item approved, so one. (Hasnt been put in-game)

**Comment by JoanRisu** [comment]
Link is broken

**Comment by JoanRisu** [comment]
Yeah, this bag is already at least in the sprite files. Someone just needs to check the code and add it to the character spawn list.
