### ISSUE TITLE
Fluff Item - Swat43 (Awsome Toolbelt) Approval pending.

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#972]
Name of Item: Awsome Toolbelt

Item description: A dark red toolbelt, with a small pulsing computer. That does look awsome!

Sprites (or link to sprites):http://www.mediafire.com/view/otj67861sbf87jr/Fortunes%20Toolbelt.dmi#

Any additional resources: None. only DMI file above

BYOND Key (Username): Swat43

Name of Character:Fortune Bloise

Main Job(s) of Character: Robotics, RD, medical

Why your character should have this item: Its her gifted item from long distance friends, while working on few of the other stations. A memmory to keep for herself when she first worked as a Roboticists and show her dedication in that field.

Additional Notes (If it's a permit, insert the information for the permit here): No notes. ^.^

Fluff Item slots already used: (0/1/2/3/4) Im asuming including my previous post it would be two in total. (If this gets accepted also)

**Comment by SpadesNeil** [comment]
Closing this for now. Fluff items should be applied for on the forum prior to requesting on Github they be added. Re-open this once your app is approved.
