### ISSUE TITLE
New hairstyles not displaying

### ISSUE THREAD

**Issue by wanderingshiba** [VOREStation/VOREStation#9720]
#### Brief description of the bug
Basically whenever you select any of the new hairstyles in character creation, they only show an error overlay saying that it needs to be fixed. The hair sprites don't appear.

#### What you expected to happen
To be able to use the new hairstyles.

#### What actually happened
I got a bald character with an error text overlay.

#### Steps to reproduce
- Go into character creation.
- Select any of the newly added hairstyles (Angelique or Feferi for example).
- Look at the character preview window.

#### Code Revision
- Server revision: B:release D:
Commit: 9ad6b38753c0b7de8aafe4d74d7c69dac216611d 
 

#### Anything else you may wish to add:
- Screenshot from the character preivew.
![pls](https://user-images.githubusercontent.com/58328860/107989789-e9b59300-6fca-11eb-8529-38103dfab2e8.PNG)

**Comment by H0lySquirr3l** [comment]
![image](https://user-images.githubusercontent.com/34927367/108758786-2294c100-7511-11eb-92c1-e4d17426cf17.png)

This should be marked as fixed it seems.

**Comment by Arokha** [comment]
Fixed
