### ISSUE TITLE
Ideas for Scree to Read. 

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#973]
These are Ideas regarding Robotics we've discussed that he wishes to read later once they're able to.
https://forums.aurorastation.org/viewtopic.php?f=18&t=4338
https://forums.aurorastation.org/viewtopic.php?f=18&t=4401

**Comment by Arokha** [comment]
Innnnteresting. It's funny, since I was just driving to work and thinking about how I was going to implement resleeving.
