### ISSUE TITLE
More of a New idea for Mappers and Aronai to read.

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#976]
This is a picture of a 'away mission' we could implement for the near future.
In short. A Research underground facility found out about a alien artefact, really powerfull that could give endless source of energy, how ever, with out containing it safely and not knowing what it could do, it activated a 'Red space' effect and demonic and hostiles creatures appeared, slaughtering entire crew. In a panic some of the heads locked the place down to help and contain most of the outbreak, but no signs of their life has been found. 
(Survivors could be played if some one Ahelps and asks to be teleported there for more RP!)
Objectives
1:Destroy the artefact by using its own power but nullifying the entire station to destruction
2:Contain the artefact, but will have to face a another swarm of monsters and probably a huge abomination.
But the reward will be compensated by NT, and humanity saved? (We know NT is greedy so I bet they will give us flowers and 50 creds.. F*ckers..)

http://image.prntscr.com/image/cc944afa86c646f3adf25012e1e83003.png

**Comment by MASMC** [comment]
I feel like this is a really good idea. Can a dev get back to me with whether or not this is being worked on? Because if not, I'll map it.

**Comment by SpadesNeil** [comment]
Any of you wanna build it? Cuz I don't lol.

**Comment by MASMC** [comment]
I mean... I will make the map? If someone else codes the crystal and shit.

**Comment by MASMC** [comment]
Actually, gonna do a bit of a re-work on our antag system, just for this. New survivor role, for those who wanna play as a survivor whenever possible.
Keeping in mind, the chance of someone actually setting up an away mission:
>1%
The chance of you not leaving, or suiciding by the end of the shift:
>5%
The amount of shit to actually do on the new map:
>A pretty good amount of stuff, actually. Fully functioning medbay, and chem lab, mebe?

**Comment by SpadesNeil** [comment]
The crystal can probably be coded. It'll be a slight pain in the ass but really the map is the hard part; not the crystal.

**Comment by MASMC** [comment]
Cool. I'll get to work on it as soon as I possibly can.

**Comment by MASMC** [comment]
Spades, Imma add you in is a collab on my fork, I got a project, go ahead
and start when ever. <3
