### ISSUE TITLE
Somatoray sucks

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#977]
#### Brief description of the issue
At the moment the Somatoray can take ten or more shots to have any mutation on them, and is useless for species as far as I can tell due to the RNG behind it. This makes it somewhat difficult to actually use the thing instead of just dumping mutagen on the plant, and makes it a waste of time to make to a degree.

#### What you expected to happen
It to actually change the plants to there mutated varients, such as golden apples or ice peppers.

#### What actually happened
It made them blow up, teleport people, sting, and survive in space, but not turn into ice peppers.

#### Steps to reproduce
- (Step 1)Plant some peppers or apples or what have you.
- (Step 2)Try to use the Somatoray to turn them into anything.

#### Code Revision
- Server revision: release - 2017-02-16
dc5c51d31bcf845bab3e17a9c8d4d2f555b8c0cd 
 
#### Anything else you may wish to add:
- Would be nice if it could be directly set to do sub-species mutation, like it can with yield or other mutations, instead of having to risk your ice peppers being stinging, and blowing up, and teleporting you.

**Comment by Benemuel** [comment]
Side note. I really wanted Ice peppers.

**Comment by Cameron653** [comment]
Code lines in question: https://github.com/VOREStation/VOREStation/blob/94b621b3106703cf3788f62f427ddcd6abbbfb8f/code/modules/hydroponics/trays/tray.dm#L183-L186

**Comment by SpadesNeil** [comment]
Is this adjusted yet?
