### ISSUE TITLE
Maintenance access is borked for non-assistants

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#978]
#### Brief description of the issue
According to Ace on discord, non-assistants should be able to get into maintenance. They can't.

#### What you expected to happen
For maint access to be on the command liason's ID card.

#### What actually happened
ID card: (E) (C) (M) access = /list (1) 1 = 19
Random maint door: (E) (C) (M) req_access = /list (1) 1 = 12
The bridge: (E) (C) (M) req_access = /list (1) 1 = 19
#### Steps to reproduce
- be not-an-assistant/engineer/detective/cargo.
- Try to get into maintenance.

#### Code Revision
Server revision: release - 2017-02-16
dc5c51d31bcf845bab3e17a9c8d4d2f555b8c0cd

**Comment by DemicusMaximus** [comment]
Confirming access is borked. Should make this a priority, its quite problematic.

**Comment by Arokha** [comment]
This is not a bug. Bugs are programming mistakes. This is working as designed. You want to change the design, not 'fix a bug'.

These are people with current maint access and my own comment next to each.
```
title = "Assistant" //Why?
title = "Head of Personnel" //Okay, acting captain.
title = "Quartermaster" //Maaaaybe.
title = "Cargo Technician" //Why?
title = "Shaft Miner" //Why?
title = "Janitor" //Okay.
title = "Librarian" //Why?
title = "Internal Affairs Agent" //Maaaybe.
title = "Chaplain" //Why?
title = "Chief Engineer" //Sure.
title = "Station Engineer" //Sure.
title = "Atmospheric Technician" //Eeehsure.
title = "Chief Medical Officer" //Sure.
title = "Paramedic" //Sure.
title = "Head of Security" //Sure.
title = "Warden" //Why?
title = "Detective" //Sure.
title = "Security Officer" //Sure.
title = "Clown" // :)
title = "Mime" //
```

**Comment by SpadesNeil** [comment]
everyone wants maint access ;-;

**Comment by Screemonster** [comment]
not gonna lie, on the old map scree's job choices were pretty much "what comes with maintenance access" because let's face it, scuttler's gonna scuttle.
