### ISSUE TITLE
Shuttle propulsion sprites are misaligned

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#979]
#### Brief description of the issue
I noticed it on the belter shuttle, but it likely affects a lot of shuttles. Basically, the l and r icon states for the ends of rows of propulsion don't line up with the heaters.

#### What you expected to happen
For the sprites to line up nicely.

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/14942479/23097532/22a6ea62-f62e-11e6-888a-ca4563766556.png)
The icon states here are a little wonky anyway, but from top to bottom, they are propulsion_l, burst_r, propulsion_l and propulsion.

Varediting them to try and fix them still doesn't line up with the heater pipes:
![image](https://cloud.githubusercontent.com/assets/14942479/23097553/5b31c7d0-f62e-11e6-9554-36c22db02d69.png)
(this one is propulsion_l, propulsion, propulsion, propulsion_r)

#### Steps to reproduce
- try to make a nice-looking row of shuttle propulsion engines
- weep
/obj/structure/shuttle/engine/propulsion and /obj/structure/shuttle/engine/heater are the objects.

#### Code Revision
Server revision: release - 2017-02-16
dc5c51d31bcf845bab3e17a9c8d4d2f555b8c0cd 
 
#### Anything else you may wish to add:
this combo sorta looks okay and will work:
![image](https://cloud.githubusercontent.com/assets/14942479/23097579/dc939b1e-f62e-11e6-9606-4db6a28af58d.png)
Edit the iconstates to burst_l, propulsion, propulsion, burst_r.

**Comment by SpadesNeil** [comment]
Old map, won't fix.
