### ISSUE TITLE
Profile link in character setup and examine text

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#98]
**What currently happens when you post URLs in descriptions:**
If the URL isn't the very first line, it must be copypasted. If it's too long, it gets cut off and the URL doesn't work.

**What I'd like to happen:**
I want it possible to add a URL to your character to link to an external profile, either on our website, or a reference pic from anywhere. To negate abuse, there should be a popup window that says, "You're about to open a browser window to [insert raw URL]. Do you wish to proceed?" Clicking "Yes" opens the link. Clicking "No" closes the menu. That way no one can link us to lemonparty.org or whatever to troll. TinyURL and other URL shorteners should be banned.

**What could also happen:**
We could change flavortext to automatically change URLs into actual clickable links instead of just text that has to be copypasted when you open the examine window.

**Comment by Arokha** [comment]
I'll let @Leshana handle this one... I'm not sure what risks/problems could arise from letting people insert <a> tags in documents sent to everyone on the server, and how to protect against them.

**Comment by Arokha** [comment]
I dunno when this changed but this happens. You can put URLs in OOC and flavortext. (I mean, I did the OOC text one, but I did it by copying the stuff from flavor, so at some point someone changed flavortext to support this).

**Comment by SpadesNeil** [comment]
The URLs aren't clickable if they are cut off past the first line. Like, you can click them, but if a url says...

**http://www.something.co...[more]** then you'll go to something.co which leads to a 404, instead of something.com.

Either way it works in the OOC field now so I don't care about this.
