### ISSUE TITLE
Heavily damaged doors are impossible to repair without deconstruction

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#981]
#### Brief description of the issue
Engine almost melted down, doors were very heavily damaged/broken. Attempted to fix via slapping metal and plasteel on them, it told me it was too broken to attempt any sort of repairs/shoring up.

#### What you expected to happen
Being able to shore up heavily damaged containment of the Engine room like Engineering is supposed to without opening the chamber up via decontruction of a broken door

#### What actually happened
"It looks like the airtight airlock is pretty busted. There's not much point reinforcing it." #959 

#### Anything else you may wish to add:
Allow Engineering the ability to repair doors without breaking them down, perhaps to turn them into a welded, makeshift wall instead to shore up any damage without wasting a huge amount of resources building a containment room and exposing themselves to incredibly hazardous situations to effect repairs. Atmosia suit is fire proof, but has no radiation protection. Engineering suit has decent Rad protection, but not as good thermal protection. I probably shouldn't have to break into the Cheng's office to fix a door.

**Comment by Screemonster** [comment]
Smash some extra girders in front and block it off with an rwall :p

But yes, for _that_ message, it looks like you tried reinforcing it with plasteel. Repairing is done with ordinary steel. The same damage check is made either way. (the only "door" type objects that are actually made of plasteel as a base material are blast doors and shutters, iirc)

But I like your idea, actually. Door's broken, you don't want to fully _fix_ it right now, just smash some extra plating on there so "door is temporarily wall". Which is effectively what a broken airlock is.

**Comment by Poojawa** [comment]
I tried both regular steel and plasteel, both didn't work as intended. I was just given the flat message of 'get stuffed' lol. the stacks of steel was 50, the plasteel was 30. I ended up just making R-walls and being very unhappy at how unprofessional it looked. 

I'd vote against super slowdowns for an engine work suit, Engineering isn't the slow, ponderous machine that a military suit needs to be 'balanced', just yell at anyone trying to drag it outside of engineering for a dumb away mission or whatever. Literally the Cheng's rig is the only thing suited for this type of work, which was why I mentioned that I shouldn't have to break in to fix a door. :P 

Since the likelyhood of the suit ever being needed is next to nill. I'd rather just have the doors not be the point of failure for an overheating engine, it just seems... odd that specialty doors you can't replace aren't able to resist far lower temps than the actually immune blast doors... which in that case should also be placed on the door squares as well.

**Comment by Poojawa** [comment]
Also, to just slightly hijack it, can we put the Tuaric-only suits in a different place? they're literally on the same squares, with the same pixel offsets as the regular suits, and the only way to tell them apart is to look at their description as they're identical in every other way. Something like 'Tuaric [suit.id]' and a different base sprite would be perfect.

**Comment by Screemonster** [comment]
Make a separate issue for the taursuits reeeeeeeeeeee

**Comment by Screemonster** [comment]
Also, the doors aren't the only point of failure. Did you check the rwalls outside?
If the engine was hot enough to melt the doors, it was hot enough to melt the walls. The walls have the same melting point, and the same HP even. And literally _any_ door can hold back those temperatures if you slap a couple of sheets of plasteel on and weld it in place.

**Comment by Poojawa** [comment]
the walls were 100% intact by looking at them. only the doors were broken.

**Comment by Screemonster** [comment]
Not the walls on the corners of the chamber. See this image from the PR:
https://cloud.githubusercontent.com/assets/14942479/22980839/956ac86e-f392-11e6-9233-5a377767ceab.png

The walls at the back that go to space failed in testing at the same time as the doors. The walls on the corners don't come into contact with any fire so naturally they wouldn't be damaged.
