### ISSUE TITLE
Security spawns still set to derelict security.

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#9813]
#### Brief description of the bug
Roundstart spawn locations for security are still set in the old security wing, Space-side floor 3

#### What you expected to happen
I readied up as a security character, and expected to spawn on Planet-side, floor 2, security equipment room.

#### What actually happened
I spawned in the equiment room in the old, now disused security wing's equipment room, Space-side floor 3.

#### Code Revision
Server revision: B:release D:
Commit: 1cd85ed0be16bfd88815234833be3d728660cf56

**Comment by H0lySquirr3l** [comment]
i'll get this

**Comment by H0lySquirr3l** [comment]
Staff have said this is intentional for the time being as the maps are worked on to be compressed. Probably can be closed.
