### ISSUE TITLE
ghost not equal gate

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#982]
#### Brief description of the issue
the not equal gate custom circuit doesn't have a sprite on it 

#### What you expected to happen
for there to be be a sprite on the not equal circuit 

#### What actually happened
this 
![image](https://cloud.githubusercontent.com/assets/16435949/23104919/bc9eaa4e-f68b-11e6-82f9-53ac8dda1dfe.png)

#### Steps to reproduce
- (Step 1) open up the logic circuit box
- (Step 2) see there is a blank box
- (Step 3) dump out box to see what doesnt have a sprite/ be able to grab said spriteless circuit 

#### Code Revision
- dc5c51d31bcf845bab3e17a9c8d4d2f555b8c0cd 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
Kicked up to Polaris since we inherited circuits from them.

**Comment by Cameron653** [comment]
Fixed https://github.com/PolarisSS13/Polaris/pull/3023

Will close this when it's merged.
