### ISSUE TITLE
Bomb being odd, exploding when not supposed to.

### ISSUE THREAD

**Issue by K54** [VOREStation/VOREStation#9832]
#### Brief description of the bug
Bomb triggered with another bomb's timer? 

#### What you expected to happen
Bomb 1 to go boom after a timer, Bomb 2 to not.

#### What actually happened
While setting a bomb, I accidentally pulled off the timer on one of them. After brief attempting to reattach, placed it in my bag. Placed second bomb, set timer to 40 seconds, ran to hide. Both bombs went boom. I ceased to exist.

#### Steps to reproduce
Get two bombs
Remove timer on one.
Set timer on other
Activate
See if both explode instead of one.
 
#### Anything else you may wish to add:
I have no clue if it was that in particular, all I know is it gave me a damn heart attack.

**Comment by TheFurryFeline** [comment]
I was wondering if this was reported before and it has, but it was never properly added on as an issue, it seems. https://discord.com/channels/173831852602294272/315700369974099969/700374500340137986
