### ISSUE TITLE
Was sent into the nth dimension by stairs

### ISSUE THREAD

**Issue by FoxDoodKMG** [VOREStation/VOREStation#9838]
**Brief description of the bug**

    The stairs sent my corpse into an odd state where I seemingly existed at multiple X, Y, and Z values with one instance
**What you expected to happen**

    For the stairs to act normally
**What actually happened**

   https://user-images.githubusercontent.com/79944416/109723300-c2ca9580-7b62-11eb-9c49-5027c2fae3fe.mp4

**Steps to reproduce**

    Get taken up/down stairs by a borg (might be an issue with the amount of people using the stairs?)
    Be thrown into the stairs

**Code Revision**

Server revision: B:release D:
Commit: [34b8502](https://github.com/VOREStation/VOREStation/commit/34b85021b1804391203312206846b52b826e022e)
**Anything else you may wish to add:**

    This has also happened to multiple people without borgs.
    Super ripleys also seem a bit Iffy.

**Comment by Arokha** [comment]
Supposedly fixed now!
