### ISSUE TITLE
Map errors: R&D Surface One and Asteroid->Midpoint

### ISSUE THREAD

**Issue by liache** [VOREStation/VOREStation#9840]
#### What happened
Map bugs. Research department surface one disconnected from the atmos of the rest of the station, and the tether access from asteroid one to midpoint cannot be climbed down.

#### What you expected to happen
Atmospherics to connect properly, to be able to climb from asteroid to surface through maintenance shafts.

#### What actually happened
Not really applicable.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)
Not really applicable either; it's a mapstate.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Attaching new lines from RND stairwell to hard storage has been my ic fix for a while.

**Comment by TheFurryFeline** [comment]
Just noticing this, but climbing preventing is intentional. As for pipes not being connected to Surface 1, Research, looking at the map now and it seems to be connected.
