### ISSUE TITLE
Stairs under catwalks ignore the catwalks and teleport people

### ISSUE THREAD

**Issue by serenekerosene** [VOREStation/VOREStation#9851]
#### Brief description of the bug
Stairs under catwalks will teleport people to their respective floor as if the catwalk isn't there

#### What you expected to happen
Enjoy aesthetically pleasing view around the station

#### What actually happened
Become claimed by the earth

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/64611899/110049493-f0107280-7d1f-11eb-830d-94ca189d3634.png)
![image](https://user-images.githubusercontent.com/64611899/110049515-fb639e00-7d1f-11eb-81e6-212801ddedba.png)
![image](https://user-images.githubusercontent.com/64611899/110049744-775de600-7d20-11eb-81fd-fe0d1c12b1c8.png)
![image](https://user-images.githubusercontent.com/64611899/110049774-8349a800-7d20-11eb-8636-71fb71cfbb48.png)

#### Code Revision
df54d624d8083743d84055dc81d83b02c61ae601

**Comment by liache** [comment]
Worth noting that if you interact with these in certain ways, they will slam you into the nearest open space in the direction you were moving off the stairs. Seems like they preserve your z-level in some weird ways?
