### ISSUE TITLE
PACMAN generators unable to be upgraded/built

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#989]
#### Brief description of the issue
Tried to RPED pacman generators on Engineering outpost Z level 5

#### What you expected to happen
Upgrading the machines to better efficiency

#### What actually happened
Absolutely nothing, probably thrown runtimes. Deconstructed it to do old fashioned way. Machine frames are broken. They show that the circuit board is still in the frame, but it drops the board, 2 coils, and the other small parts. Clicking on the frame allows you to add wires... but nothing else works.

#### Steps to reproduce
Open panel with screw driver
click with RPED
Nothing happens.

attempt to build PACMAN, put circuit board in to frame, nothing happens.

#### Code Revision
- 1001be5b2eb5bbdc528935ae9fce3606aa5833ec 
 
#### Anything else you may wish to add:
- Engineering outpost between the science and mining hub should really have its own solar field so the outpost isn't always drained/relying on pacmans.

**Comment by Cameron653** [comment]
Fixed upstream by Leshana
