### ISSUE TITLE
paper Shredding machine!

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#991]
In short! A machine to shred unnecesary paper/books/people?

I have made three sprite states for them, ages ago, and I have a feeling, this could be placed in IAA's office/secretaries office/for heads and library! 

Thoughts?

Previews: http://www.mediafire.com/file/c114kc8gvzmwx8c/Paper+Shredder+active.dmi
http://www.mediafire.com/view/b9nj6ac2d44i7bg/Paper%20Shredder.dmi#
http://www.mediafire.com/view/jo7kzq4ws99l4jr/Paper%20Shredder%20inactive.dmi#

**Comment by Leshana** [comment]
I actually briefly started to work on this!  But one of the first things I noticed is there actually is *already* a paper shredder machine in the game. However it does not seem to be construct able. I can fix that!

The question is, should we replace its sprites with the ones linked here?  I like your animation, but the existing one also shows visually how full its paper bin is.

![image](https://cloud.githubusercontent.com/assets/14110581/23185118/3f196f66-f850-11e6-8087-d5d928f95e30.png)

**Comment by Cameron653** [comment]
Added by Leshana upstream.
