### ISSUE TITLE
Setting RP Advert Doesn't Show in Char Dir

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#9919]
#### Brief description of the bug
Title.

#### What you expected to happen
Typed RP ad to show up when viewing own char in directory.

#### What actually happened
Nothing saved?

#### Steps to reproduce
- (Step 1) Type RP ad.
- (Step 2) Hit ok.
- (Step 3) Cry when you don't see it shown when viewing your character in the directory.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 [0ee95207eae9368fadf1edab8ab97a687f8b2e77]

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Edit Note: this is when playing as an active char on station.

**Comment by lm40** [comment]
Pretty sure u just have to refresh the directory and then it will show

**Comment by TheFurryFeline** [comment]
Tried that, didn't show anything. Like, it doesn't even seem to save what's written into the advert section after you spawn in.

**Comment by TheFurryFeline** [comment]
This is working now.
