### ISSUE TITLE
Resizing adminbus is broken and other size issues (And some suggestions for improving them)

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9950]
#### Description of the bug
As per https://github.com/VOREStation/VOREStation/pull/9545

Resizing outside of the normally allowed size range via admin commands outside the dorms is no longer possible, because the checks that this pull request adds happens always everywhere outside of the dorms.

The only way to resize outside of normal range without being spawned in and using an item on someone is for that person to be in the surface side dorms, and then after resizing the person, set their 'unnaturally resized' variable to 0. You will then stay that size until you are next affected by some size changing thing, which will once again return you to normal size range. 

~~ADDITIONALLY, the sharp/fuzzy toggle for sprite scaling verb appears to be gone now, and no matter what your setting in character setup is, your sprite will always be displayed as if fuzzy is selected. As far as I can tell the variable for this seems to be gone now? It had previously defaulted to sharp.~~ The verb got moved and I found it so this is kind of moot BUT!

Sprites default to fuzzy scaling mode now, which I would prefer they didn't! Also it seems like if you start as 100% size on some species the fuzzy/sharp setting is not respected, but if you aren't 100% it is. No idea what's up with that.

#### What you expected to happen
For admin resizing to not be impossible outside of super specific circumstances. I actually specifically asked about this in the PR. Being as this is a commonly used and desired adminbus tool, this being broken makes most size related events essentially impossible.

~~**And**, player sprites are supposed to respect the setting in character setup for their fuzzy/sharp setting, and there's supposed to be a verb to be able to toggle it to your liking while you're spawned. These two modes only really become especially noticeable when your sprite size gets pretty big/small. As is, if you're sized way up, your sprite will be super blurry and smudgy looking, with no way that I can find to adjust it. Fuzzy tends to look best at smaller sizes, as it preserves some sprite detail by blending colors. But the bigger the sprite gets, the more gross they tend to look, so the ability to toggle this is pretty important, in my opinion.~~

~~If 'Switch scaling mode' is an account setting now, which it seems to be, it should be displayed like one in the character setup panel, AND!~~(Apparently my client was just shitting itself?) ((Nope it just doesn't work consistently for different species apparently???)) 

It should default to sharp scaling mode like it used to, and respect your character setup setting.

#### What actually happened
Resized punpun. He briefly became a giant gross smudge, before being automatically shrunk to 200% because he wasn't in a dorm.

#### Steps to reproduce
-Have Admin/GM perms
- try to use proc call to resize someone who is not in the dorms
- Alternatively, be in the dorms, use resize to become huge, and stare at the huge gross smudge you have become.

#### Code Revision
- B:release D:
Commit: 540c974139e30f43aba4632828dba5c481f23ec9 
 

#### Anything else you may wish to add:
- This dorms size business should  be checking to see if it should be resizing someone if they have just left the dorms area. It really shouldn't be always checking everywhere. I know it's possible to do things on exiting an area, as all areas have an exit_message variable. It would be INFINITELY PREFERABLE in my opinion for areas to have a var on them that, if set to 1, would automatically return someone to normal size if they leave it. Something like that would even help to enable some size shenanigans like Jemli's macro beach events. IDEALLY there would be a seperate var there too that would let us toggle the expanded size range on an area, so we could choose to expand the size shenanigans temporarily.

**Comment by JoanRisu** [comment]
The core of the issue is that this feature that is neat is also interfering with the admins' ability to resize mobs and player characters at will. That is not good and should be resolved sooner rather than later. Otherwise, it'll get the ax.

**Comment by Heroman3003** [comment]
> Sprites default to fuzzy scaling mode now, which I would prefer they didn't! Also it seems like if you start as 100% size on some species the fuzzy/sharp setting is not respected, but if you aren't 100% it is. No idea what's up with that.

That's because at certain scales, scale happens 'perfectly'. You can see same effect on 200%. Fuzzy/sharp affects what method of graphic scaling is used for your character's down/up scaled sprite, and if sprite looks same in both methods or isn't up/down scaled at all it will have no difference.


As for the unnaturally sized, ideally the var should work the opposite way, where it doesn't look if someone is 'unnaturally sized' and sizes them down, but checks if they are, let's say 'size unlocked' and if they are, lets them keep the size. That will mean that admins just have to set the var of size_unlock or whatever to 1 and then they'll be free to resize unnaturally without worry. Flip the logic around so to say.

**Comment by Very-Soft** [comment]
> That's because at certain scales, scale happens 'perfectly'. You can see same effect on 200%. Fuzzy/sharp affects what method of graphic scaling is used for your character's down/up scaled sprite, and if sprite looks same in both methods or isn't up/down scaled at all it will have no difference.

I mean, it would be fine if it was operating by some logic, but my point is that it's not respecting the setting seemingly arbitrarily. I don't really care what size/species they are, it should respect the setting, which it's not doing consistently.

> As for the unnaturally sized, ideally the var should work the opposite way, where it doesn't look if someone is 'unnaturally sized' and sizes them down, but checks if they are, let's say 'size unlocked' and if they are, lets them keep the size. That will mean that admins just have to set the var of size_unlock or whatever to 1 and then they'll be free to resize unnaturally without worry. Flip the logic around so to say.

And, I would prefer there wasn't an extra step to making size stuff happen outside the dorms. The more annoying it is to do things, the less likely we are to try to do them. There being that extra step means it's that much slower to do the things. In cases where there's one person to do it for, that's not a big deal, but in events where you need to do it for several people, it's gonna get super old, super fast. 

I don't really understand why we need something that always checks to see if they are outside normal sizes, and why it can't just adjust people who leave the dorms area, or an area that has a certain flag set. 

It being a thing that's just always on everywhere makes it an annoying hinderance to deal with every time we want to do something, where it being a property of the area would make it an actually potentially useful tool.

**Comment by Heroman3003** [comment]
> I don't really understand why we need something that always checks to see if they are outside normal sizes, and why it can't just adjust people who leave the dorms area, or an area that has a certain flag set.

Main issue with that thinking is that its just not that easy to tell that to code. The game currently doesn't have system to recognize that "oh! Object left the area! Let's see how we should react". And if it did, it'd have to be universal code for every switch of area. It's just a more-complicated-than-it-seems thing to code. Not impossible entirely, but the current solution is semi-efficent in regards of amount of coding it takes.

Ideally, admin resizing would also have a different proc, that just automatically sets the variable that allows unnatural size before doing a regular resize proc.

**Comment by Very-Soft** [comment]
> Main issue with that thinking is that its just not that easy to tell that to code. The game currently doesn't have system to recognize that "oh! Object left the area! Let's see how we should react". And if it did, it'd have to be universal code for every switch of area. It's just a more-complicated-than-it-seems thing to code. Not impossible entirely, but the current solution is semi-efficent in regards of amount of coding it takes.
> 
> Ideally, admin resizing would also have a different proc, that just automatically sets the variable that allows unnatural size before doing a regular resize proc.

But areas do have a thing that exists right now that can print a message when you leave an area. Obviously I'm no coding whiz, but I would think that if it can detect that you have left an area to know to send you a message, it could probably know to do something else when you've left an area.

**Comment by Heroman3003** [comment]
> 
> 
> > Main issue with that thinking is that its just not that easy to tell that to code. The game currently doesn't have system to recognize that "oh! Object left the area! Let's see how we should react". And if it did, it'd have to be universal code for every switch of area. It's just a more-complicated-than-it-seems thing to code. Not impossible entirely, but the current solution is semi-efficent in regards of amount of coding it takes.
> > Ideally, admin resizing would also have a different proc, that just automatically sets the variable that allows unnatural size before doing a regular resize proc.
> 
> But areas do have a thing that exists right now that can print a message when you leave an area. Obviously I'm no coding whiz, but I would think that if it can detect that you have left an area to know to send you a message, it could probably know to do something else when you've left an area.

Uh... Can you clarify what area does that exactly? Because I'm drawing a blank and what you described is a bit too broad to search for.

**Comment by Zap-zapper** [comment]
ill get to it once i properly wake up, but right now, admins can resize people outside of dorms either with admin sizegun, or using advanced proccall to call resize() with last parameter (mark_unnatural_size) set to FALSE

**Comment by Verkister** [comment]
> 
> 
> > > Main issue with that thinking is that its just not that easy to tell that to code. The game currently doesn't have system to recognize that "oh! Object left the area! Let's see how we should react". And if it did, it'd have to be universal code for every switch of area. It's just a more-complicated-than-it-seems thing to code. Not impossible entirely, but the current solution is semi-efficent in regards of amount of coding it takes.
> > > Ideally, admin resizing would also have a different proc, that just automatically sets the variable that allows unnatural size before doing a regular resize proc.
> > 
> > 
> > But areas do have a thing that exists right now that can print a message when you leave an area. Obviously I'm no coding whiz, but I would think that if it can detect that you have left an area to know to send you a message, it could probably know to do something else when you've left an area.
> 
> Uh... Can you clarify what area does that exactly? Because I'm drawing a blank and what you described is a bit too broad to search for.

https://github.com/VOREStation/VOREStation/blob/master/code/game/area/areas_vr.dm

**Comment by Very-Soft** [comment]
The main issue of this isn't fixed, and shouldn't be closed.

**Comment by TheFurryFeline** [comment]
This no longer needs to be a pinned issue if it's fixed now.
