### ISSUE TITLE
Pineapple Rings

### ISSUE THREAD

**Issue by stobarico** [VOREStation/VOREStation#9954]
#### Brief description of the bug
Pineapples only yield one ring when cut

#### What you expected to happen
For more than a single pineapple ring to come out of a pineapple

#### What actually happened
A single pineapple ring came out of a pineapple when sliced

#### Steps to reproduce
- Grow pineapple
- Cut pineapple
- Do not profit since you only have a single ring

**Comment by Very-Soft** [comment]
I like to imagine that you just cut the shell and cored the pineapple and there's just one really tall pineapple ring.
